### ISSUE TITLE
关于clash for windows 支持clash的便携以及自身便携的建议

### ISSUE THREAD

**Issue by neatgz** [Fndroid/clash_for_windows_pkg#1]
clash本身可以使用命令
`clash-win64.exe -d .`
这样，C:\Users\用户名\.config\clash 文件夹下的配置文件等，就都会存储在当前目录。
这样可以方便的放在高速U盘里，从而方便的在家用和单位电脑之间携带，不用重复修改配置文件等。
请问，clash for windows 能够支持 clash 的这种便携方法，同时也实现 clash for windows 的自身的便携化？
谢谢，请大佬酌情考虑。

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.4.0

**Comment by neatgz** [comment]
便携版，填写好机场的托管地址后，把cfw文件夹整个移动到新电脑上，托管地址的地方变成了空的。
能否把cfw自身的设置也保存在当前文件夹？
谢谢。

**Comment by Remonli** [comment]
+1 , cfw 自身的配置没找到在那, 要是能和config.yml放在一个目录就好了

**Comment by Fndroid** [comment]
现在有Profiles的情况下，也不需要记托管地址了吧。程序本身的设置很复杂文件比较多，都按照Windows习惯放在对应的地方了。

**Comment by Fndroid** [comment]
此issue将被关闭，如问题依旧，欢迎reopen
