### ISSUE TITLE
0.11.2，Allow LAN功能失效

### ISSUE THREAD

**Issue by ljh0519** [Fndroid/clash_for_windows_pkg#1000]
问题描述：
1. 宿主机开启allow lan，虚拟机配置proxy为宿主机ip，端口默认7890，虚拟机无法通过proxy连接。
2. 回退0.10.4，同样的上述操作，虚拟机可以正常连接。
3. 宿主机与虚拟机处于同一网段。可以相互ping通，7890端口没有被其他程序占用。

**Comment by Satone7** [comment]
刚用手机和电脑尝试了局域网代理，没有问题
