### ISSUE TITLE
代理已连接，但是无法访问所有国外站点

### ISSUE THREAD

**Issue by rtrrsr** [Fndroid/clash_for_windows_pkg#1001]
time="2020-07-29T19:36:59+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-07-29T19:36:59+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-07-29T19:36:59+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-07-29T19:36:59+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-07-29T19:37:05+08:00" level=warning msg="dial Proxy error: uscn2gia19.host-sub.com:15794 connect error: dial tcp4 103.136.186.209:15794: i/o timeout"
time="2020-07-29T19:37:05+08:00" level=warning msg="dial Proxy error: uscn2gia19.host-sub.com:15794 connect error: dial tcp4 103.136.186.209:15794: i/o timeout"

**Comment by Conqueror59865** [comment]
开全局
