### ISSUE TITLE
0.11.2说支持ssr 但是不支持chacha20

### ISSUE THREAD

**Issue by Wirili** [Fndroid/clash_for_windows_pkg#1003]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

 [//]: # Windows 7

**描述**

[//]: # ssr订阅，提示不支持chacha20

**复现**

[//]: # Profiles 里面点击订阅

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by LangRanOvO** [comment]
Clash内核不支持chacha20
