### ISSUE TITLE
打开CFW会导致Xbox Live的NAT状态变成Teredo无法限定

### ISSUE THREAD

**Issue by sky96111** [Fndroid/clash_for_windows_pkg#1005]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 10 专业版 Insider Preview 20180.1000

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
（未安装TAP网卡）每一次启动Clash for windows都会导致设置-游戏-Xbox网络中NAT类型变成Teredo无法限定，导致无法进行xbox多人游戏。
点击修复后重启恢复正常，但如果设置了GFW自启动，修复将无效，重启时又会再次Teredo无法限定。而且只要打开CFW，即使不设置系统代理也会如此。
使用clash命令行版本，手动设置代理，不会出现此BUG。

**复现**

[//]: # (请描述复现问题的步骤)

1.打开Clash For Windows客户端
2.进入设置-游戏-Xbox网络，此时NAT网络已由开放变成Teredo无法限定

**预期行为**

[//]: # (清晰地描述期望看到的行为)
NAT状态保持开放，因为我没有使用TAP网卡

**日志**

[//]: # (上传触发问题对应的日志文件)
似乎...CFW没有提供日志输出?

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)
微软官方对Teredo无法限定解释：
>某些 VPN 客户端将在连接 VPN 客户端时禁用 Teredo 连接，某些 VPN 客户端将安装网络适配器，该适配器将禁用 Teredo，直到此 VPN 适配器被删除。如果您已安装 VPN 客户端，并且即使 VPN 客户端已断开连接仍然禁用了 Teredo，请查看您是否安装了名为“TAP-Windows 适配器 V9”的网络适配器：
右键单击“开始”按钮 ，然后选择“设备管理器”。
选择“查看”>“显示隐藏的设备”。
选择“网络适配器”。
识别名称类似于“TAP-Windows 适配器 V9”的任何适配器。右键单击适配器名称，然后选择“卸载”。
注意 虽然卸载 VPN 网络适配器应该会取消阻止 Teredo 连接，但这也可能导致 VPN 客户端软件出现问题。如果您仍需要 VPN 功能以及 Teredo 支持，**请参阅 VPN 客户端的支持文档**。
重启电脑。
https://support.xbox.com/help/Hardware-Network/connect-network/troubleshoot-party-chat

**Comment by BenjaminGao** [comment]
并未发现：NAT网络已由开放变成Teredo无法限定问题
![image](https://user-images.githubusercontent.com/16028320/89018871-12d44600-d34f-11ea-9826-f6051281a7fb.png)
![image](https://user-images.githubusercontent.com/16028320/89018930-27184300-d34f-11ea-9cec-f1b179945476.png)

**Comment by sky96111** [comment]
> 并未发现：NAT网络已由开放变成Teredo无法限定问题
> ![image](https://user-images.githubusercontent.com/16028320/89018871-12d44600-d34f-11ea-9826-f6051281a7fb.png)
> ![image](https://user-images.githubusercontent.com/16028320/89018930-27184300-d34f-11ea-9cec-f1b179945476.png)

哈..请问win10该怎么抓取有用的log?

**Comment by sky96111** [comment]
![屏幕截图 2020-07-31 170715.png](https://i.loli.net/2020/07/31/Bgq3ayeu2NWlzo6.png)
![屏幕截图 2020-07-31 170738.png](https://i.loli.net/2020/07/31/OA9bRINQsh4tYgC.png)
![屏幕截图 2020-07-31 171100.png](https://i.loli.net/2020/07/31/KQLC1ugEkpX5P4j.png)

**Comment by BenjaminGao** [comment]
> 最后一个已连接偶尔会变成已阻止，和CFW状态没啥关系
> ![屏幕截图 2020-07-31 170715.png](https://camo.githubusercontent.com/4f8bc0c05d929ce964b5c5faf3fbe1e8d035be65/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30372f33312f4267713361796575324e576c7a6f362e706e67)
> ![屏幕截图 2020-07-31 170738.png](https://camo.githubusercontent.com/fa5e324285562e72c98eaab6106e8160b7387651/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30372f33312f4f41396252494e51736834745967432e706e67)
> ![屏幕截图 2020-07-31 171100.png](https://camo.githubusercontent.com/bd8200ad1a51b180394e171bd5b6c49cc67bd438/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30372f33312f4b514c43317567456b70583550346a2e706e67)

所以还是关了 issues 吧，貌似是其他原因

**Comment by sky96111** [comment]
> > 最后一个已连接偶尔会变成已阻止，和CFW状态没啥关系
> > ![屏幕截图 2020-07-31 170715.png](https://camo.githubusercontent.com/4f8bc0c05d929ce964b5c5faf3fbe1e8d035be65/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30372f33312f4267713361796575324e576c7a6f362e706e67)
> > ![屏幕截图 2020-07-31 170738.png](https://camo.githubusercontent.com/fa5e324285562e72c98eaab6106e8160b7387651/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30372f33312f4f41396252494e51736834745967432e706e67)
> > ![屏幕截图 2020-07-31 171100.png](https://camo.githubusercontent.com/bd8200ad1a51b180394e171bd5b6c49cc67bd438/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30372f33312f4b514c43317567456b70583550346a2e706e67)
> 
> 所以还是关了 issues 吧，貌似是其他原因

只是服务器连接状态和CFW没关系，NAT类型还是一启动CFW立即失效。我觉得还是有关系的，但不知道如何提供更多信息，安卓可以logcat，Windows事件查看器根本没法定位啊

**Comment by BenjaminGao** [comment]
> > > 最后一个已连接偶尔会变成已阻止，和CFW状态没啥关系
> > > ![屏幕截图 2020-07-31 170715.png](https://camo.githubusercontent.com/4f8bc0c05d929ce964b5c5faf3fbe1e8d035be65/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30372f33312f4267713361796575324e576c7a6f362e706e67)
> > > ![屏幕截图 2020-07-31 170738.png](https://camo.githubusercontent.com/fa5e324285562e72c98eaab6106e8160b7387651/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30372f33312f4f41396252494e51736834745967432e706e67)
> > > ![屏幕截图 2020-07-31 171100.png](https://camo.githubusercontent.com/bd8200ad1a51b180394e171bd5b6c49cc67bd438/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30372f33312f4b514c43317567456b70583550346a2e706e67)
> > 
> > 
> > 所以还是关了 issues 吧，貌似是其他原因
> 
> 只是服务器连接状态和CFW没关系，NAT类型还是一启动CFW立即失效。我觉得还是有关系的，但不知道如何提供更多信息，安卓可以logcat，Windows事件查看器根本没法定位啊

你为什么不去谷歌搜索一下 NAT 问题解决方法呢，要不你去"极限竞速地平线4“吧看看，那里有不少解决方法。关键是解决自己不能玩的问题。

**Comment by sky96111** [comment]
> 你为什么不去谷歌搜索一下 NAT 问题解决方法呢，要不你去"极限竞速地平线4“吧看看，那里有不少解决方法。关键是解决自己不能玩的问题。

我Google了，也到微软社区查了，最后排查到发现是CFW的问题才开的issue，只要关掉cfw自启动，点设置里的修复，重启就能正常，一启动马上就无法限定...难道是似乎是玄学个例（?）只要保证不打开CFW，clash原版也没事，NAT状态就没有问题

**Comment by sky96111** [comment]
解决，安装了adguard的话关掉它高级设置中的使用WFP驱动时禁用Teredo
