### ISSUE TITLE
怎么样让某个软件使用代理或者不是用代理？是否有白名单功能？

### ISSUE THREAD

**Issue by denissyk2004** [Fndroid/clash_for_windows_pkg#1006]
**描述**
怎么样让某个软件使用代理或者不是用代理？是否有白名单功能？

**其他说明**
其他补充内容
怎么样让某个软件使用代理或者不是用代理？是否有白名单功能？我明明只是上微薄和b站但是看到流量一直跑很心疼。去到connection里面他们明明没有走代理。。。
同样，是否有和别的软件那样最基本的一件过滤不代理大陆ip的功能呢？
能否像sstap或者其他软件一样搞个大大的开关按钮？你这个开关太不明显了
为什么手动更新了配置文件会导致我自定义的一些域名规则也被重置为默认状态了？
服务器的选择可不可以固定或者每次手动选择？莫名其妙连到一些高倍率的服务器很奇怪啊，而且手动选择了也不知道生效了没有，每次都要重启软件。可否学学sstap简洁明了。

**Comment by Fndroid** [comment]
为什么不直接用sstap？简洁明了

**Comment by denissyk2004** [comment]
告辞

**Comment by yi-Xu-0100** [comment]
1. 如果没有走代理，应该不会产生流量。
2. rule 规则是配置文件提供，建议找代理商提出规则表过滤。
3. 更新配置文件会重置 rule 规则，可以使用[配置文件预处理方法](https://docs.cfw.lbyczf.com/contents/parser.html)，对配置文件自动更改规则。
4. 服务器选择是固定的，除非你的配置文件中让服务器选择是按照连接速率检查的方式去连接，他会自动更换服务器。具体情况由配置文件决定，请找代理商询问细则。

**Comment by denissyk2004** [comment]
Thx
