### ISSUE TITLE
链接过长造成显示和编辑有误

### ISSUE THREAD

**Issue by yi-Xu-0100** [Fndroid/clash_for_windows_pkg#1007]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

win10 1909 专业版

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

在配置文件预处理模块，由于连接过长，造成显示和编辑有误。

**复现**

[//]: # (请描述复现问题的步骤)

一行写入过长字符应该就能复现。

**预期行为**

[//]: # (清晰地描述期望看到的行为)

折行显示和编辑光标对齐。

**截图**

[//]: # (如果可以，请提供对应问题的截图)

![image](https://user-images.githubusercontent.com/25523606/89010210-b538fd00-d340-11ea-9601-d54834d5a0c3.png)

![image](https://user-images.githubusercontent.com/25523606/89010237-c3871900-d340-11ea-9bb5-11f67eca44f0.png)

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases

**Comment by yi-Xu-0100** [comment]
已使用，非常感谢~

@Fndroid 不知道是否提供自动折行显示的功能，链接过长，会有滚动条，能否折行显示，这样方便查看。

这是个低优先级的需求，如果有计划，我就再开个 issue，没有相关计划的话，现在的方式也没问题。
