### ISSUE TITLE
功能请求：策略组在更新时不会被覆盖

### ISSUE THREAD

**Issue by System-Warning** [Fndroid/clash_for_windows_pkg#1008]
> 原因
如果订阅方预设策略组，在进行订阅更新时，会覆盖原先所有的策略组。用户无法保存自定义策略组。

> 期望功能
在编辑策略组中加入“不随订阅更新”功能。在更新时做保留不被覆盖。

**Comment by yi-Xu-0100** [comment]
暂时可以使用[配置文件预处理方法](https://docs.cfw.lbyczf.com/contents/parser.html)，对配置文件的策略组进行自定义。

**Comment by Fndroid** [comment]
整个配置proxies/proxy-groups/rules都是耦合的，怎么保留其中一个而确保其他的不会被影响？

**Comment by System-Warning** [comment]
> 整个配置proxies/proxy-groups/rules都是耦合的，怎么保留其中一个而确保其他的不会被影响？

增加一个策略组功能:从所有节点中用关键词、节点类型等方式筛选出一些节点，加入到该策略组中。在更新订阅时自动对节点进行分组。

**Comment by yi-Xu-0100** [comment]
> > 整个配置proxies/proxy-groups/rules都是耦合的，怎么保留其中一个而确保其他的不会被影响？
> 
> 增加一个策略组功能:从所有节点中用关键词、节点类型等方式筛选出一些节点，加入到该策略组中。在更新订阅时自动对节点进行分组。


每个人的订阅不同，节点名称不同，甚至可能节点更新后，节点的名称也不同，无法保存，下次对节点分组有效。

现在可以根据个人需求使用配置文件预处理方法，对不同订阅链接使用不同的解析脚本，还是不错的。
