### ISSUE TITLE
无法打开System Proxy：系统代理开关

### ISSUE THREAD

**Issue by amazjing** [Fndroid/clash_for_windows_pkg#1009]
无法点击System Proxy：系统代理开关，打不开

**Comment by jap33** [comment]
咱重置系统解决了不能系统代理的问题

**Comment by jap33** [comment]
![GIF](https://user-images.githubusercontent.com/15140842/89099040-1d5e1080-d41f-11ea-96ce-9dfd3d340e98.gif)

**Comment by amazjing** [comment]
> 咱重置系统解决了不能系统代理的问题

路子这么野？

**Comment by HowYoungIAm** [comment]
我也遇到了一样的问题，点击System Proxy 按钮后会自动关闭，连续点好几次后能稳定住开启，但过一会又会自动关闭，不过我的问题只出现在system proxy这里，其他的按钮并没有问题。

**Comment by Fndroid** [comment]
置顶的issue看下吧，它能置顶是有道理的

**Comment by HowYoungIAm** [comment]
> 置顶的issue看下吧，它能置顶是有道理的

感谢大佬！根据置顶的issue里的方法检测出是easyconnect软件的问题，卸载后CFW已恢复正常。

**Comment by Fndroid** [comment]
Duplicate of #312
