### ISSUE TITLE
功能建议 ：url-test与load-balance策略组未被引用时不进行ping测试

### ISSUE THREAD

**Issue by System-Warning** [Fndroid/clash_for_windows_pkg#1011]
**描述**

> url-test与load-balance策略组未被引用时仍然自动进行ping测试，造成资源浪费。

![image](https://user-images.githubusercontent.com/51915931/89099178-f9e79580-d41f-11ea-9fe6-3747a2e089c6.png)

**其他说明**
建议只有策略组被引用时自动进行ping测试。
策略组没有被引用时不自动进行ping测试

**Comment by Fndroid** [comment]
首先，这是core的行为，需要去clash核心仓库提交issue或pr

其次我觉得没有必要，如果不引用，就不应该写到配置里，要么注释掉要么换个type
