### ISSUE TITLE
UI小改进建议

### ISSUE THREAD

**Issue by System-Warning** [Fndroid/clash_for_windows_pkg#1012]
**信息**

- [ x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ x] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 专业版 1909

**描述**

订阅编辑界面最大化（或放大）后界面内容全挤在左边，影响美观

**预期行为**

放大或拉长内容

**截图**

![image](https://user-images.githubusercontent.com/51915931/89099514-7b402780-d422-11ea-855f-62b210ff0389.png)

**Comment by Fndroid** [comment]
放大/拉长没有意义并且会导致操作更加麻烦
