### ISSUE TITLE
能否调整默认的配置目录

### ISSUE THREAD

**Issue by qrqhuang** [Fndroid/clash_for_windows_pkg#1013]
**描述**
当前的配置文件是放在 `%userprofile%\.config` 的， 但实际上技术人员的`%userprofile%`下已经很混乱了
所以看能否改至标准的如 `%appdata%` 下

**Comment by kinfables** [comment]
[自定义配置文件目录](https://docs.cfw.lbyczf.com/contents/profilespath.html) 或使用 [便携模式](https://docs.cfw.lbyczf.com/contents/7z.html)

**Comment by qrqhuang** [comment]
期待修改默认策略。

配置的地方我知道的
