### ISSUE TITLE
v0.11.0 配置完成之后 proxies内各节点已可正常显示延迟 但是仍无法上网

### ISSUE THREAD

**Issue by 1506245410** [Fndroid/clash_for_windows_pkg#1014]
![00](https://user-images.githubusercontent.com/60957743/89117810-5ce63480-d4d3-11ea-95c0-ba4b21be02a8.png)
如图，按照其他帖子修改了yml文件之后可以rule一栏里已经可以看见节点了，但是不论选择rule还是global，打开代理之后都无法连接外网...

**Comment by 1506245410** [comment]
图片好像打不开了.....内容就是proxies一栏各节点的正常显示ms

**Comment by yi-Xu-0100** [comment]
是不是没开系统代理，不行就开全局代理试试

**Comment by 1506245410** [comment]
> 是不是没开系统代理，不行就开全局代理试试

开了的 全局也试了 还是不行
