### ISSUE TITLE
请教一下和 Tunnelblick 一起使用的问题

### ISSUE THREAD

**Issue by acmilank22** [Fndroid/clash_for_windows_pkg#1027]
**信息**

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

macOS Catalina 10.15.6

**描述**

首先说一下基本情况，我们公司有2个内网VPN: A和B；然后办公室的网络自带A，但是只是大众权限的，我自己账号的A比办公室网络的A权限高，所以我一般都是都连着办公室的网络后，再用Tunnelblick连接自己账号的A，同时也连着B（其实B连不连对这个问题没啥影响）。

然后我是最近clash支持ShadowsocksR后，开始使用Clash for Windows。

**复现**

我发现：

1. 连接公司网络（自带A），再用Tunnelblick连接自己账号的A，运行Clash for Windows，走代理的正常，直连（比如访问百度）访问不了；

2. 连接公司网络（自带A），运行Clash for Windows，一切正常；

3. 使用手机热点，再用Tunnelblick连接自己账号的A，运行Clash for Windows，一切正常；

4. 连接公司网络（自带A），再用Tunnelblick连接自己账号的A，外网自然是访问不了，直连正常。

**预期行为**

**日志**

```log
time="2020-08-07T11:01:47+08:00" level=warning msg="dial 🎯 全球直连 error: dial tcp4 222.186.49.85:443: i/o timeout"
time="2020-08-07T11:01:48+08:00" level=warning msg="dial 🎯 全球直连 error: dial tcp4 180.101.49.12:443: i/o timeout"
time="2020-08-07T11:01:49+08:00" level=warning msg="dial 🍎 苹果服务 error: no8161725348.internetworld.cloud:1312 connect error: dial tcp4 47.112.31.36:1312: i/o timeout"
time="2020-08-07T11:01:52+08:00" level=warning msg="dial 🎯 全球直连 error: dial tcp4 114.106.160.91:443: i/o timeout"
time="2020-08-07T11:01:53+08:00" level=warning msg="dial 🎯 全球直连 error: dial tcp4 180.101.49.12:443: i/o timeout"
time="2020-08-07T11:01:54+08:00" level=warning msg="dial 🍎 苹果服务 error: no8161725348.internetworld.cloud:1312 connect error: dial tcp4 47.112.31.36:1312: i/o timeout"
time="2020-08-07T11:01:54+08:00" level=info msg="[TCP] 127.0.0.1:51721 --> bolt.dropbox.com match DomainKeyword(dropbox) using 🚀 节点选择[🇭🇰 V312U-10x-深圳香港CN2-GS]"
time="2020-08-07T11:01:57+08:00" level=warning msg="dial 🎯 全球直连 error: dial tcp4 114.106.160.91:443: i/o timeout"
time="2020-08-07T11:01:59+08:00" level=warning msg="dial 🍎 苹果服务 error: no8161725348.internetworld.cloud:1312 connect error: dial tcp4 47.112.31.36:1312: i/o timeout"
time="2020-08-07T11:01:59+08:00" level=info msg="[TCP] 127.0.0.1:51740 --> play.google.com match DomainKeyword(google) using 🚀 节点选择[🇭🇰 V312U-10x-深圳香港CN2-GS]"
time="2020-08-07T11:01:59+08:00" level=info msg="[TCP] 127.0.0.1:51720 --> data-api.similarsites.com match Match() using 🐟 漏网之鱼[🇭🇰 V312U-10x-深圳香港CN2-GS]"
time="2020-08-07T11:02:04+08:00" level=warning msg="dial 🍎 苹果服务 error: no8161725348.internetworld.cloud:1312 connect error: dial tcp4 47.112.31.36:1312: i/o timeout"
time="2020-08-07T11:02:09+08:00" level=warning msg="dial 🍎 苹果服务 error: no8161725348.internetworld.cloud:1312 connect error: dial tcp4 47.112.31.36:1312: i/o timeout"
time="2020-08-07T11:02:09+08:00" level=info msg="[TCP] 127.0.0.1:51791 --> api.dropboxapi.com match DomainKeyword(dropbox) using 🚀 节点选择[🇭🇰 V312U-10x-深圳香港CN2-GS]"
time="2020-08-07T11:02:14+08:00" level=warning msg="dial 🍎 苹果服务 error: no8161725348.internetworld.cloud:1312 connect error: dial tcp4 47.112.31.36:1312: i/o timeout"
time="2020-08-07T11:02:14+08:00" level=info msg="[TCP] 127.0.0.1:51799 --> bolt.dropbox.com match DomainKeyword(dropbox) using 🚀 节点选择[🇭🇰 V312U-10x-深圳香港CN2-GS]"
```

**截图**

<img width="620" alt="WX20200807-105932@2x" src="https://user-images.githubusercontent.com/12584040/89604114-29bdef80-d89d-11ea-8af6-5f207871fbd6.png">

**其他说明**

另外，我还发现：
1. 当直连的无法访问时，日志里都是走的ip。
2. 用Tunnelblick连接自己账号的A后，「网络」设置的「DNS」时，会在「搜索域」加上 openvpn。
3. 昨天我不知道怎么倒腾了一下，居然自己好了，今天来上班又不行了。

**Comment by Fndroid** [comment]
配置文件里有没有配置dns？

**Comment by acmilank22** [comment]
> 配置文件里有没有配置dns？

@Fndroid 是指OpenVpn的配置文件吗？

A的配置文件如下：

```txt
client
dev tun
proto tcp
remote x.x.x.x 1194
remote x.x.x.x 1195
resolv-retry infinite
nobind
persist-key
persist-tun
ca file-name.crt
comp-lzo
auth-user-pass
script-security 2
```

**Comment by Fndroid** [comment]
clash的配置文件

**Comment by acmilank22** [comment]
> clash的配置文件

@Fndroid 是指得这个吗？没有配置dns。

![image](https://user-images.githubusercontent.com/12584040/89615912-05bcd700-d8ba-11ea-97e5-ce524c984db1.png)

![image](https://user-images.githubusercontent.com/12584040/89615980-2a18b380-d8ba-11ea-8d61-372ed2b993d3.png)

**Comment by yi-Xu-0100** [comment]
> 例如：在配置文件中统一添加 `dns` 字段
> ...

[mixin 文档](https://docs.cfw.lbyczf.com/contents/mixin.html)中有添加方法。

**Comment by acmilank22** [comment]
> > 例如：在配置文件中统一添加 `dns` 字段
> > ...
> 
> [mixin 文档](https://docs.cfw.lbyczf.com/contents/mixin.html)中有添加方法。

@yi-Xu-0100 非常感谢！在mixin中加了dns就好了。

另外 mixin用js似乎有个bug

 ```js
module.exports.parse = async ({ content, name, url }, { axios, yaml, notify }) => {
  const extra = {
    dns: {
      enable: true,
      listen: ':53',
      namserver: ['8.8.8.8']
    }
  }
  return { ...content, ...extra }
}
```

![image](https://user-images.githubusercontent.com/12584040/89621667-50435100-d8c4-11ea-9ad0-59b8a6de2caf.png)

**Comment by yi-Xu-0100** [comment]
> ``` js
> module.exports.parse = async ({ content, name, url }, { axios, yaml, notify }) => {
>  const extra = {
>    dns: {
>      enable: true,
>      listen: ':53',
>      namserver: ['8.8.8.8']
>    }
>  }
>  return { ...content, ...extra }
> }
> ```

看了一下，是文档中的 `nameserver` 少打了个 `e` .

**Comment by acmilank22** [comment]
> > ```js
> > module.exports.parse = async ({ content, name, url }, { axios, yaml, notify }) => {
> >  const extra = {
> >    dns: {
> >      enable: true,
> >      listen: ':53',
> >      namserver: ['8.8.8.8']
> >    }
> >  }
> >  return { ...content, ...extra }
> > }
> > ```
> 
> 看了一下，是文档中的 `nameserver` 少打了个 `e` .
> 
> 已修复文档，哇，贼快，我还准备提交一下 pull request.

好的 多谢 

再请教一个问题 可以用mixin的js里 可以用console.log打印吗 @Fndroid @yi-Xu-0100

**Comment by yi-Xu-0100** [comment]
@acmilank22 可以使用 `notify`

``` js
notify("profile has been modified.", "Personal rules has been added.", true)
```
我用了这句，效果如下图：

![image](https://user-images.githubusercontent.com/25523606/89697815-78789180-d950-11ea-81fc-0adac17496ec.png)

在 windows 桌面端的左下角出现。

**Comment by Fndroid** [comment]
> 可以用 console.log 打印吗 

可以用nodejs内置模块``console``和``fs``自己实现一个logger

https://nodejs.org/api/console.html#console_new_console_stdout_stderr_ignoreerrors

**Comment by acmilank22** [comment]
@Fndroid @yi-Xu-0100 好的 谢谢两位 灰常感谢
