### ISSUE TITLE
添加新的订阅地址后立刻激活

### ISSUE THREAD

**Issue by lotusired** [Fndroid/clash_for_windows_pkg#1028]
**描述**
感谢开发软件! 我是某小机场场长. 我最近接到非常多的用户反馈不能正常获取服务器列表, 经研究我发现新版本的 clash for windows 在下载订阅文件之后需要手动激活这个文件. 希望可以省去这个步骤!

**其他说明**
其他补充内容

**Comment by Potterli20** [comment]
> **描述**
> 感谢开发软件! 我是某小机场场长. 我最近接到非常多的用户反馈不能正常获取服务器列表, 经研究我发现新版本的 clash for windows 在下载订阅文件之后需要手动激活这个文件. 希望可以省去这个步骤!
> 
> **其他说明**
> 其他补充内容

我建议用路由器

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
