### ISSUE TITLE
windows版的直连流量被算在了套餐流量中了，请修复一下

### ISSUE THREAD

**Issue by howshek** [Fndroid/clash_for_windows_pkg#1029]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
win10
[//]: # (平台及版本号)

**描述**
开启RULE模式，直连国内的网站的流量算在了VPN的流量中去了。
[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)
看B站时的流量如下
![TIM截图20200807180355](https://user-images.githubusercontent.com/48312888/89634732-6c50ed80-d8d8-11ea-8e04-8796f78f4cf3.png)
套餐的流量如下
![TIM截图20200807180701](https://user-images.githubusercontent.com/48312888/89635005-e4b7ae80-d8d8-11ea-9625-0a49ca88cd05.png)
由于是刚用的VPN，没在外网上浏览什么，但是看了会国内的视频。在开启RULE模式时仍然算作套餐流量

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
那不是应该问你服务商吗？

**Comment by howshek** [comment]
> 那不是应该问你服务商吗？
可是我在安卓端上，看内网的流量就不算在VPN流量中。不知道哪里出现问题

**Comment by howshek** [comment]
@Fndroid 
可是我在安卓端上，看内网的流量就不算在VPN流量中。不知道哪里出现问题。

**Comment by GrayXu** [comment]
log里显示的就是分流的DIRECT，压根不会访问代理。。  
尝试多做点测试吧，应该不是这里的问题

**Comment by gd1214b** [comment]
请尝试用此网站转换您的订阅链接：https://skapi.cool

**Comment by LittleControl** [comment]
只是计算通过clash的流量,不代表真实通过代理的流量,直连的会算进clash,但是不会算进你的服务商...

**Comment by sunkais** [comment]
去看流量记录，没什么问题的。

**Comment by sunkais** [comment]
我指的是你所使用的飞机场的网站上的流量记录
