### ISSUE TITLE
开启代理后 Windows Store 无法访问

### ISSUE THREAD

**Issue by LE88I5** [Fndroid/clash_for_windows_pkg#103]
开启代理后 Windows Store 无法访问（还有一些其他的服务，比如切换本地账户和Microsoft账户那个登录界面也是）可能是什么情况？这个现象在公司的机器和家里的机器上都能 100% 重现，关闭代理立马可以访问呢，找不到问题的原因。

**Comment by Fndroid** [comment]
原因是这些是UWP应用，默认不允许loopback代理

General里的EnableLoopback.exe就是为了解决这个问题而加的

**Comment by LE88I5** [comment]
> 原因是这些是UWP应用，默认不允许loopback代理
> 
> General里的EnableLoopback.exe就是为了解决这个问题而加的

(⊙﹏⊙)…… 明白了，这个小工具好用，勾选保存一下问题就解决了，一直也没有注意到过这个小程序，谢谢你！

**Comment by AdoShan** [comment]
> 原因是这些是UWP应用，默认不允许loopback代理
> 
> General里的EnableLoopback.exe就是为了解决这个问题而加的

EnableLoopback.exe在哪呢，怎么解决这个问题

**Comment by AdoShan** [comment]
> > 原因是这些是UWP应用，默认不允许loopback代理
> > General里的EnableLoopback.exe就是为了解决这个问题而加的
> 
> (⊙﹏⊙)…… 明白了，这个小工具好用，勾选保存一下问题就解决了，一直也没有注意到过这个小程序，谢谢你！

咋解决的？点哪呢？可以告知一下吗？

**Comment by yi-Xu-0100** [comment]
@AdoShan 
![image](https://user-images.githubusercontent.com/25523606/98462636-b6f04780-21f0-11eb-985b-773e3909b084.png)

**Comment by shao1yi** [comment]
哭了，解决了

**Comment by liyunhaocn** [comment]
> @AdoShan
> ![image](https://user-images.githubusercontent.com/25523606/98462636-b6f04780-21f0-11eb-985b-773e3909b084.png)

many thanks

**Comment by OptimisticQuan** [comment]
感动 太好用了

**Comment by liicos** [comment]
哭了，解决了

**Comment by AdoreJc** [comment]
感谢分享😁👍

**Comment by smartpippin** [comment]
太感谢了好用哭了。。终于解决了这个问题
