### ISSUE TITLE
求汉化

### ISSUE THREAD

**Issue by BeyondOneself** [Fndroid/clash_for_windows_pkg#1034]
**描述**
请具体并清楚地描述期望功能及期望的效果

**其他说明**
其他补充内容

**Comment by yi-Xu-0100** [comment]
#999 类似问题已回复。真奇怪，刚刚才有个人问了差不多的。为啥不搜索下历史 issue 呢？

**Comment by iamqiz** [comment]
BoyceLig/Clash_Chinese_Patch: Clash For Windows 汉化补丁和汉化脚本
https://github.com/BoyceLig/Clash_Chinese_Patch
