### ISSUE TITLE
[Feature Request]请为 订阅/规则 的更新提供前置代理选项

### ISSUE THREAD

**Issue by muink** [Fndroid/clash_for_windows_pkg#1036]
**描述**

gfw已经开始封锁使用tls1.3和esni的域名了，以直连的方式更新规则变得十分困难(比如gitlab)
而 tls1.2 的`raw.githubusercontent.com`一直都处于间歇性sni阻断的情况
希望能为规则的更新添加前置代理的选项，帮助快速更新规则/订阅

**Comment by Fndroid** [comment]
更新provider是clash core的功能，可以到core到repo下反馈
