### ISSUE TITLE
TUN模式在休眠唤醒后，无法工作，必须重启

### ISSUE THREAD

**Issue by tony1016** [Fndroid/clash_for_windows_pkg#1037]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows™ 10 build 1903

**描述**

在TUN模式下，每次休眠后，则TUN失效，必须重新启动或者关闭一次MIXIN再启用一次（我在MIXIN里开启了TUN设置）

**复现**

[//]: # (请描述复现问题的步骤)

1. 休眠电脑
2. 开启重新连接WiFi
3. connection中没有任何连接
4. 重新启动或者关闭一次MIXIN再启用一次（我在MIXIN里开启了TUN设置）
5.connection中出现连接

**预期行为**

从休眠中恢复后能够自动恢复

**Comment by Fndroid** [comment]
发一下 ``C:\Users\<用户名>\AppData\Roaming\clash_win\logs\renderer.log``

**Comment by tony1016** [comment]
验证了好久，似乎再也没有出现过，先关闭了
