### ISSUE TITLE
connections界面每条连接显示发起者的ip地址

### ISSUE THREAD

**Issue by UntaggedRui** [Fndroid/clash_for_windows_pkg#1038]
**描述**
请具体并清楚地描述期望功能及期望的效果
![image](https://user-images.githubusercontent.com/28807947/89791420-e346ea00-db55-11ea-84b4-cd46fbaa0087.png)
希望在这个界面上每条连接上能够显示发起者的ip地址，因为代理有可能被局域网中的其他设备使用，想能通过ip地址判断是否有恶意设备接入代理占用带宽和流量。
**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
不想被其他人用加上auth不就好了吗？

难道要盯着connections看哪个是别人的手动close掉？

**Comment by UntaggedRui** [comment]
> 不想被其他人用加上auth不就好了吗？
> 
> 难道要盯着connections看哪个是别人的手动close掉？

好的，谢谢。请问怎么加上auth呀？

**Comment by Fndroid** [comment]
```yaml
# authentication of local SOCKS5/HTTP(S) server
authentication:
  - "user1:pass1"
  - "user2:pass2"
```

**Comment by UntaggedRui** [comment]
谢谢！

**Comment by UntaggedRui** [comment]
每次更新完配置文件这个都会被覆盖，有什么办法能解决吗？
