### ISSUE TITLE
[FR] 一些小尝试

### ISSUE THREAD

**Issue by inkss** [Fndroid/clash_for_windows_pkg#104]
您好，我尝试在 linux 下通过 crossover 安装本软件，很遗憾的是测试失败了。

不过能不能测试下这种方案的可行性呢？

![image](https://user-images.githubusercontent.com/31947043/55614860-949a7a80-57c0-11e9-9107-83391f4837d6.png)

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
