### ISSUE TITLE
开启全局代理，git clone的速度没有变化仍然非常慢！！！

### ISSUE THREAD

**Issue by SamL1n** [Fndroid/clash_for_windows_pkg#1040]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

win10家庭中文版，版本10.0.18363
clash版本 0.10.1

**描述**

开启代理之后，git clone速度为7kb/s，和未开启代理速度一样

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

开启代理之后git clone速度变快

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/tap.html

**Comment by sup3root** [comment]
git 走代理需要额外设置，可以参考 https://gist.github.com/chuyik/02d0d37a49edc162546441092efae6a1

**Comment by SamL1n** [comment]
> https://docs.cfw.lbyczf.com/contents/tap.html
太牛逼了，现在clone速度实现质的飞跃，感谢！
