### ISSUE TITLE
之前可以访问，后面一直访问不了google，日志如下

### ISSUE THREAD

**Issue by lry199010** [Fndroid/clash_for_windows_pkg#1042]
time="2020-08-12T15:21:10+08:00" level=warning msg="dial DIRECT error: dial tcp4 69.63.186.30:443: i/o timeout"
time="2020-08-12T15:21:11+08:00" level=warning msg="dial DIRECT error: dial tcp4 172.217.160.74:443: i/o timeout"
time="2020-08-12T15:21:15+08:00" level=warning msg="dial DIRECT error: dial tcp4 69.63.186.30:443: i/o timeout"
time="2020-08-12T15:21:15+08:00" level=info msg="[TCP] 127.0.0.1:55165 --> 180.163.222.184 doesn't match any rule using DIRECT"
time="2020-08-12T15:21:16+08:00" level=warning msg="dial DIRECT error: dial tcp4 172.217.160.74:443: i/o timeout"
time="2020-08-12T15:21:20+08:00" level=warning msg="dial DIRECT error: dial tcp4 69.63.186.30:443: i/o timeout"
time="2020-08-12T15:21:23+08:00" level=info msg="[TCP] 127.0.0.1:55168 --> pre.vd.f.360.cn doesn't match any rule using DIRECT"
time="2020-08-12T15:21:23+08:00" level=info msg="[TCP] 127.0.0.1:55170 --> 180.163.222.194 doesn't match any rule using DIRECT"
time="2020-08-12T15:21:30+08:00" level=warning msg="dial DIRECT error: dial tcp4 69.63.186.30:443: i/o timeout"
time="2020-08-12T15:21:30+08:00" level=info msg="[TCP] 127.0.0.1:55179 --> 180.163.222.19 doesn't match any rule using DIRECT"

**Comment by Fndroid** [comment]
proxies字段为空
