### ISSUE TITLE
【请教】ALLOW LAN无法正常使用

### ISSUE THREAD

**Issue by Brocode0422** [Fndroid/clash_for_windows_pkg#1043]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # WINDOWS 8.1/CLASH FOR WINDOWS V0.11.3

**描述**

[//]: #打开ALLOW LAN以后，IOS设备进行了相应的HTTP代理配置设置，但是仍无法通过局域网科学上网。IOS设备填写的服务器是电脑的ip地址（通过ipconfig检查过），端口填写的是7890。

**预期行为**

[//]: # 希望可以使用局域网代理功能

**Comment by Fndroid** [comment]
先确定地址和端口都没填错，Allow LAN开关已经开启，配置了authentication还有在手机上再配置正确

**Comment by Brocode0422** [comment]
> 先确定地址和端口都没填错，Allow LAN开关已经开启，配置了authentication还有在手机上再配置正确
你好，请问要怎么配置authentication？谢谢

**Comment by Fndroid** [comment]
你没配置就不用配置了，确保地址和端口没错

**Comment by Brocode0422** [comment]
> 你没配置就不用配置了，确保地址和端口没错

你好，地址和端口都正确填写了，手机显示wifi是连着的，但是打不开任何网页。请问还需要怎么设置吗？谢谢
另，LOG文件也显示无法上传

**Comment by Fndroid** [comment]
手机和电脑在同一个局域网么？两者ip分别是多少

**Comment by Brocode0422** [comment]
> 手机和电脑在同一个局域网么？两者ip分别是多少

电脑ip地址是192.168.0.16 手机的ip地址是192.168.0.8

**Comment by hulnglei1** [comment]
信息

 已经从issue搜索过类似问题，并未发现重复
 已经阅读过文档相关问题，并未找到解决办法
 已经尝试更新到最新版本，问题依旧存在
 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）
系统

//: # WINDOWS 10 /CLASH FOR WINDOWS V0.11.4

描述

//: #打开ALLOW LAN以后，android设备l链接笔记本热点 但是仍无法通过局域网科学上网。

预期行为

//: # 希望可以使用局域网代理功能
@Brocode0422

**Comment by Fndroid** [comment]
看下防火墙有没有关掉

**Comment by Brocode0422** [comment]
> 看下防火墙有没有关掉

防火墙关闭后可以正常使用，谢谢。不好意思，请问一下是否局域网功能是否一定要完全关闭防火墙才可以正常使用？谢谢

**Comment by Brocode0422** [comment]
> 信息
> 
> 已经从issue搜索过类似问题，并未发现重复
> 已经阅读过文档相关问题，并未找到解决办法
> 已经尝试更新到最新版本，问题依旧存在
> 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）
> 系统
> 
> //: # WINDOWS 10 /CLASH FOR WINDOWS V0.11.4
> 
> 描述
> 
> //: #打开ALLOW LAN以后，android设备l链接笔记本热点 但是仍无法通过局域网科学上网。
> 
> 预期行为
> 
> //: # 希望可以使用局域网代理功能
> @Brocode0422

我关闭win防火墙后可以正常使用，你可以也试试

**Comment by ygsk10** [comment]
> 
> 
> > 看下防火墙有没有关掉
> 
> 防火墙关闭后可以正常使用，谢谢。不好意思，请问一下是否局域网功能是否一定要完全关闭防火墙才可以正常使用？谢谢

正确的做法是添加规则。

**Comment by Brocode0422** [comment]
> > > 看下防火墙有没有关掉
> > 
> > 
> > 防火墙关闭后可以正常使用，谢谢。不好意思，请问一下是否局域网功能是否一定要完全关闭防火墙才可以正常使用？谢谢
> 
> 正确的做法是添加规则。

请问能否告知一下如何添加规则？谢谢

**Comment by DKandrew** [comment]
请问有没有办法能通过修改wifi路由器里面的DHCP服务器设置实现让连上wifi的设备自动连接clash的代理？
