### ISSUE TITLE
could not connect to clash core

### ISSUE THREAD

**Issue by bitternolis** [Fndroid/clash_for_windows_pkg#1044]
用的好好的大概三个月，突然用不了了，这次不管重装，点repair还是手动清空yaml文件内容都无法连接clash内核了，日志：
time="2020-08-13T10:07:28+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-08-13T10:07:28+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-08-13T10:07:28+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"

**Comment by bitternolis** [comment]
多次repair后会提示Error:ENOENT:no such file or directory, open'%config.yaml%'

**Comment by bitternolis** [comment]
打开路径后发现yaml文件还是那个yaml

**Comment by bitternolis** [comment]
已重启、重装、重置网络、重装驱动，皆无效。

**Comment by bitternolis** [comment]
新的现象，当使用netch代理https和sock5接口时，开启clash，内核能正确加载，主页有信息。
关闭netch，clash立刻无法连接内核。
问题在哪？

**Comment by bitternolis** [comment]
> 新的现象，当使用netch代理https和sock5接口时，开启clash，内核能正确加载，主页有信息。
> 关闭netch，clash立刻无法连接内核。
> 问题在哪？

此时clash内所有节点均time out

**Comment by Fndroid** [comment]
有没有装其他“广告过滤”软件？

**Comment by bitternolis** [comment]
> 有没有装其他“广告过滤”软件？

没有，仅有chrome的ublock插件

**Comment by bitternolis** [comment]
找到问题所在了，因不明原因系统代理被自动打开，被设置成127.0.0.1:8888，发现某些软件联网问题后修改就好了……原来内核打不开是连不上网

**Comment by e71828** [comment]
@Fndroid @bitternolis 怎么解决 求问
