### ISSUE TITLE
trojan失效提示connect error x509 certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by angelmengg** [Fndroid/clash_for_windows_pkg#1045]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # win7 旗舰版 64位 Service Pack 1
Clash for Windows 0.11.4

**描述**

[//]: # 添加trojan失效

**日志**

[//]: # (上传触发问题对应的日志文件)
[2020-08-13-173751.log](https://github.com/Fndroid/clash_for_windows_pkg/files/5068328/2020-08-13-173751.log)

**其他说明**

[//]: # 已确定虚拟机时间同步没有问题，但是log中依然提示connect error x509 certificate has expired or is not yet valid。
补充：已确定虚拟机上的trojan没问题，手机上使用igniter能够正常代理，安卓版clash存在同样问题不能使用

**Comment by Fndroid** [comment]
clash core issue, refer: https://github.com/Dreamacro/clash/issues
