### ISSUE TITLE
下载订阅报错，download profile failed with error:network error

### ISSUE THREAD

**Issue by wzyrr520** [Fndroid/clash_for_windows_pkg#1046]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
win7系统
[//]: # (平台及版本号)
64位
**描述**
输入订阅连接点击download 两三秒出现错误提示，从未成功。但是从浏览器输入下载后导入可用。
[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'profiles'
2. 点击'download'
3. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**
无日志
[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/44134963/90137190-dc171a80-dda7-11ea-9b3c-47f9e381a2c4.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
**Network Error** 指网络访问问题。
就是订阅链接无法访问，下载不了配置文件。
最好自己再确认一下载链接，可以在浏览器打开测试一下。

**Comment by yi-Xu-0100** [comment]
看到你的描述中，有提到在浏览器中可下载。建议是重启软件试试，我有时过会就行，订阅链接访问不稳定。

**Comment by wzyrr520** [comment]
> 看到你的描述中，有提到在浏览器中可下载。建议是重启软件试试，我有时过会就行，订阅链接访问不稳定。

一直都不行，卸载重装，重启，用便携版本。都不行，

**Comment by a458486** [comment]
网页打开订阅地址，下载订阅文件，最后手动导入。

**Comment by huaifeng1993** [comment]
@a458486 打开订阅地址是一串字符编码？如何下载订阅文件？

**Comment by CodeFindingG** [comment]
> 网页打开订阅地址，下载订阅文件，最后手动导入。

请问下载的订阅文件的是php格式吗

**Comment by yi-Xu-0100** [comment]
@CodeFindingG yaml 格式

**Comment by CodeFindingG** [comment]
@yi-Xu-0100 感谢你的评论，我把订阅链接在浏览器中打开了，并将订阅链接里显示的字符保存到一个新建的yaml格式文件中。随后，我利用clash客户端import了这个yaml文件，不过proxies里仍然没有出现节点。并且刷新之后，仍然会出现Download profile with error: Network error。现在判断可能是节点订阅出现了问题

**Comment by yi-Xu-0100** [comment]
@CodeFindingG 你可以看下这个 https://github.com/Dreamacro/clash/wiki/configuration 如果格式和他的不一样，可能就不对，import 自然不行

**Comment by CodeFindingG** [comment]
@yi-Xu-0100 嗯好的，非常感谢。

**Comment by Bttrsc** [comment]
我也遇到这个问题并且已经解决，我把方法留在这里给以后的人参考。当我看到network error报错只想到要不是订阅链接本身有问题，要不就是系统自带浏览器有问题两个可能。但我试过链接在其他电脑的客户端能订阅成功，说明不是链接有问题。

用IE打开订阅链接，如果是正常的话会直接出现服务器节点，proxy，rules等等内容。如果这个链接不能正常在clash订阅，那么IE很可能弹出"此网站的安全证书有问题"，点击"继续浏览此网站(不推荐)"应该就能出现原本应有的内容，但网址右边会显示"证书错误"，提示证书无效，再点"查看证书"弹出界面，选择安装证书-将所有的证书放入下列存储-浏览-受信任的根证书颁发机构-确定，安装完证书后关掉IE再试试打开订阅链接看看能否直接弹出订阅的内容。

如果还是有错误，可以再回到IE-工具-Internet选项-高级，去除对证书地址不匹配发出警告的勾，然后保存试一下。反正我就是这样解决的。

参考：https://www.jb51.net/softjc/635462.html

**Comment by phh95** [comment]
我遇到了两个问题，一个是这里的下载订阅报错，一个是顺利下载订阅链接之后提示，Could not switch to this profile。后面回到 Clash 的 General 页面，提示软件出错了，点击页面提供的修复按钮，就又可以用了，玄学。。。

**Comment by Tevic** [comment]
非HTTP(S)的配置没法更新啊，这个能修复下么

**Comment by TransparentsWorld** [comment]
把订阅地址输入浏览器下载yaml文件，然后在clash中导入此文件，我就是这样解决的问题。

**Comment by phh95** [comment]
> 楼主我这里是链接一开始下载失败，后来链接下载成功后节点选择总是显示超时，还是无法上网，有解决办法吗？不知道问题出在哪里，谢谢！

有没有打开 系统代理System proxy 呢？

**Comment by Golvens** [comment]
我是用的Gatern的机场，有天发现clash上不了网，看到Gatern官网发的邮件，说更新了订阅信息，要手动在clash里更新配置，clash for windows点击更新显示network error，我发现订阅链接在Gatern官网，而进入官网需要梯子，没有更新梯子又无效了，好家伙，这波操作是在很迷，我们需要有实习经验的实习生。最后我是在其他地方搞了个梯子，去下了订阅文件，转成yaml格式，然后手动导入。

**Comment by ILikeIneine** [comment]
这个很大概率是证书到期了等他们更新，我今天也遇到了，捏麻麻地
<img width="384" alt="image" src="https://user-images.githubusercontent.com/37239608/175799078-86505fe8-f291-47ab-abf7-8f350816659e.png">

**Comment by fancy27** [comment]
> 这个很大概率是证书到期了等他们更新，我今天也遇到了，捏麻麻地 <img alt="image" width="384" src="https://user-images.githubusercontent.com/37239608/175799078-86505fe8-f291-47ab-abf7-8f350816659e.png">

我也是mosucloud，你手动打开一下那个网站，系统里的证书就会更新了，然后软件就能刷新配置文件了

**Comment by ILikeIneine** [comment]
> 

手动打开直接chrome给我拦截了，添加了信任还是不行= =不过昨天和在线客服反馈了，下午就更新了证书

**Comment by wenxin-zhao** [comment]
> @a458486 打开订阅地址是一串字符编码？如何下载订阅文件？

您这边有解决吗

**Comment by lightningshade** [comment]
我也有类似问题，不过修改ie并没有解决我的问题，我这里是使用了转连接的一个服务，https://sub.789.st/。
将我的订阅连接转换了一下，虽然我并不知道规则不过确实转换之后就可以使用了。我不知道什么时候会过期，做一奉上参考的网页，里面有网页的总链接，希望对你有帮助。
链接：https://www.zhuguodong.com/?id=508

**Comment by linhongjun** [comment]
测试了下，的确是因为证书的问题导致的无法下载订阅文件，不知道这个对于软件来说有没有一劳永逸的解决办法？比如可以不通过IE浏览器下载？

**Comment by Chenyanzhan** [comment]
不懂大家是怎么在浏览器下载yaml文件的，我把订阅复制到浏览器，打开就是一串很长的符号，根本就不能下载所谓的yaml配置文件。用的是win10版本的clash

**Comment by Golvens** [comment]
> 不懂大家是怎么在浏览器下载yaml文件的，我把订阅复制到浏览器，打开就是一串很长的符号，根本就不能下载所谓的yaml配置文件。用的是win10版本的clash

你用浏览器打开订阅链接，打开之后是一长串代码，你把它复制下来粘贴到一个txt文件中，再把它的后缀改成ymal格式就可以了

**Comment by aicut** [comment]
6 是证书的问题

**Comment by RIn1314** [comment]
我的解决方式是链接没加https头，加上就对了，无语了

**Comment by MartinLHX** [comment]
我也遇到相同的问题，从url导入和手动import本地的yaml文件都不行，还有什么解决办法吗（订阅链接在edge浏览器中可以正常打开并下载对应的yaml文件）

**Comment by dankexiahuxi** [comment]
![微信图片_20230522145829](https://github.com/Fndroid/clash_for_windows_pkg/assets/134046001/6b77c861-e692-4b65-944b-33c01a8a0a70)
我的下载订阅地址的是出现这个情况，不知道情况跟你们的是一样的吗》

**Comment by YUNYE01** [comment]
clash x 全部订阅无法更新，各种报错信息，有解决方案请告知一下

**Comment by ZhongxiaJun** [comment]
请问，复制订阅地址和导入到clash for Windows都失败，然后复制订阅地址到浏览器，是504 Gateway Time-out
