### ISSUE TITLE
下载订阅报错，download profile failed with error:network error,第一次issue不小心让我关掉了

### ISSUE THREAD

**Issue by wzyrr520** [Fndroid/clash_for_windows_pkg#1047]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
win7
[//]: # (平台及版本号)
64位
**描述**
输入订阅连接点击download 两三秒出现错误提示，从未成功。但是从浏览器输入下载后导入可用。
[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**
无日志，
[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/44134963/90149582-39ff2e80-ddb7-11ea-9566-1ecb8cff1b8d.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by greedyhao** [comment]
我遇到过，不过我的确实是网络问题，换了个能用的梯子后，就可以更新 profile 了

**Comment by Fndroid** [comment]
CFW本身并不会遵循系统代理设置，所以默认情况下，CFW发出的请求都是直连，包括下载配置文件。

**Comment by MartinLHX** [comment]
怎么解决的。我也遇到这个问题
