### ISSUE TITLE
自定义全局规则

### ISSUE THREAD

**Issue by Flaryer** [Fndroid/clash_for_windows_pkg#1048]
**描述**
请具体并清楚地描述期望功能及期望的效果
1. 虽然有了mixin，但是mixin是替换规则，并不能在原先的基础（如：订阅）上增加规则/节点，建议增加这项功能。
2. 还有自定义规则能不能应用到全局，即global里面也应用规则，这样可以无时无刻屏蔽某些应用暗中访问某些网站。

这里晒一下我的目前解决办法：mixin里面使用js，给急需的小伙伴借鉴一下。
```js
module.exports.parse = ({ content, name, url }, { yaml, axios, notify }) => {
  let extra = {
    rules: [
      'DOMAIN-KEYWORD,--------------,REJECT',
      'DOMAIN-KEYWORD,-----------,REJECT',
      'DOMAIN-KEYWORD,------------,REJECT',
      'DOMAIN-KEYWORD,--------------,REJECT',
      'DOMAIN-KEYWORD,--------------,REJECT',
      'DOMAIN-KEYWORD,------------,REJECT',
    ],
    proxies: [
      {
        name: '-------------',
        type: 'vmess',
        server: '------------',
        port: 443,
        uuid: '-----------------------------',
        alterId: 64,
        cipher: 'aes-128-gcm',
        tls: true,
        'skip-cert-verify': true,
        network: 'ws',
        'ws-path': '----------------',
        Host: '-----------'
      }
    ]
  };
  content.rules = extra.rules.concat(content.rules);
  content.proxies = extra.proxies.concat(content.proxies);
  return content;
}
```
**其他说明**
其他补充内容
无

**Comment by yi-Xu-0100** [comment]
感觉 rule 就是走规则列表，global 就是都走代理，如果 global 中设置 rule，和 rule 就没有区别了。

至于自定义规则的话，可以使用[配置文件预处理方法](https://docs.cfw.lbyczf.com/contents/parser.html)，可以参考我写的 [changeRule.js](https://github.com/yi-Xu-0100/Application-Lists/blob/master/Configuration/ClashForWindows/changeRule.js)

**Comment by Flaryer** [comment]
@yi-Xu-0100 赞👍，谢谢大佬

**Comment by Fndroid** [comment]
rules依赖于proxies/proxy groups，所以并没有“全局规则”的说法。

**Comment by Huelse** [comment]
不知道有没有朋友遇到这个问题，当我用mixin配置规则的时候，proxies中的规则会失效，必须在mixin中多加入目标网址匹配才行（原配置文件已有）
我的yaml示例：
```
mixin: # object
  rules:
    - DOMAIN-KEYWORD,google,🔰国外流量  # 不加这条就会导致无法访问google
    - DOMAIN-KEYWORD,bbc,🔰国外流量  # 这是自己想加的自定义条目
```

**Comment by Flaryer** [comment]
> 不知道有没有朋友遇到这个问题，当我用mixin配置规则的时候，proxies中的规则会失效，必须在mixin中多加入目标网址匹配才行（原配置文件已有）
> 我的yaml示例：
> 
> ```
> mixin: # object
>   rules:
>     - DOMAIN-KEYWORD,google,🔰国外流量  # 不加这条就会导致无法访问google
>     - DOMAIN-KEYWORD,bbc,🔰国外流量  # 这是自己想加的自定义条目
> ```
我提的是这个问题，因为mixin是直接替换所有规则的，你可以参考上面我的代码or yi-Xu-0100 的代码解决。

**Comment by Huelse** [comment]
@Flaryer 原来如此，搞懂了，谢谢
