### ISSUE TITLE
希望支持chacha20加密

### ISSUE THREAD

**Issue by Obsidian036** [Fndroid/clash_for_windows_pkg#1049]
**描述**
请具体并清楚地描述期望功能及期望的效果
据我观察相当部分提供ssr服务的商家用查查20加密，所以增加加密方式的支持可以让支持ssr更有意义
**其他说明**
其他补充内容

**Comment by yi-Xu-0100** [comment]
这个建议去上游仓库 [clash](https://github.com/Dreamacro/clash/issues) 提出。

**Comment by Fndroid** [comment]
https://github.com/Dreamacro/clash/issues/832
