### ISSUE TITLE
[BUG]配置文件不覆盖

### ISSUE THREAD

**Issue by nncy** [Fndroid/clash_for_windows_pkg#105]
大佬，您好。我最近再用clash的时候发现在更新配置文件的时候不会覆盖之前的，新下载配置文件在.config/clash/profiles这个文件夹里，需要手动覆盖。请问有什么解决方法吗？

**Comment by Fndroid** [comment]
覆盖到哪里

**Comment by nncy** [comment]
我的配置文件是在clash目录下的config.yml，更新后的配置文件是在clash/profiles里。如果不手动覆盖，还是使用的是之前的配置文件。

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/yuan-cheng-pei-zhi-remote
