### ISSUE TITLE
"none" cipher in SSR not support

### ISSUE THREAD

**Issue by lion-goose** [Fndroid/clash_for_windows_pkg#1051]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

 操作系统：Windows10 2004版本 操作系统版本：19041.450
 clash for windows：v 0.11.4

**描述**

CFW已经支持SSR协议，貌似cipher类型没有none

**预期行为**

希望可以支持cipher

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**
 
![image](https://user-images.githubusercontent.com/59443350/90306777-016c6b80-df03-11ea-8f38-bfa0a22ff5cf.png)

**Comment by yi-Xu-0100** [comment]
看看 Dreamacro/clash#865

**Comment by Fndroid** [comment]
clash core issue, refer: https://github.com/Dreamacro/clash/issues
