### ISSUE TITLE
更新订阅的时候后手动添加的规则会消失

### ISSUE THREAD

**Issue by zsh35** [Fndroid/clash_for_windows_pkg#1052]
**描述**
更新订阅的时候后，手动添加的规则会消失

**其他说明**
我手动添加了如youtube或者其他网站的规则，点击机场更新后，手动添加的规则直接没有了。

**Comment by yi-Xu-0100** [comment]
是的，自定义规则会被覆盖，需要的话，可以使用[配置文件预处理方法](https://docs.cfw.lbyczf.com/contents/parser.html)，可以参考我写的 [changeRule.js](https://github.com/yi-Xu-0100/Application-Lists/blob/master/Configuration/ClashForWindows/changeRule.js)

**Comment by Fndroid** [comment]
更新 = 下载 + 替换

规则不是单独存在的，所以要么从上游更新，要么自己用parser实现
