### ISSUE TITLE
mac 失去焦点 异常

### ISSUE THREAD

**Issue by uniquepengpeng** [Fndroid/clash_for_windows_pkg#1053]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
mac 10.15.6

[//]: # (平台及版本号)

**描述**
cfw失去焦点,从dock栏消失,用手势显示所有窗口,又自动出现在dock栏中

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 打开cfw
2. 点击其它程序,让cfw失去焦点,cfw自动从dock栏消失
3. 触发Mission Control(触摸板三指向上),cfw又自动出现在dock中.

**预期行为**
cfw失去焦点,在dock中一直存在.

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
确实是个bug，我固定所以一直没留意到。下个版本修复，感谢反馈

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
