### ISSUE TITLE
笑死你👴我了，你自己去自high到飽吧😹

### ISSUE THREAD

**Issue by zrz130** [Fndroid/clash_for_windows_pkg#1055]
> > 搜一下先不应该吗？
> 
> > 
> 
> > 重复的问题回几次谁有这个功夫？都是要工作生活的。
> 
> 
> 
> 你是从哪就觉得人家就没搜呢？万一人家没找到或者是还不理解呢？怎么的github是你家的还是怎么的？不允许别人问问题了？你有时间在这开展你的教育事业，说没时间工作生活？我看你教育人挺有时间的啊？跑到这来当人上人来了？

滚吧

_Originally posted by @Fndroid in https://github.com/Fndroid/clash_for_windows_pkg/issues/970#issuecomment-674651450_

**Comment by zrz130** [comment]
笑死你👴我了，你自己去自high到飽吧😹

**Comment by ShadyWhite** [comment]
> 笑死你👴我了，你自己去自high到飽吧😹

活久见，还真有这样的人，长见识了。

**Comment by AkariiinMKII** [comment]
F大不肯教的我来教，60块包会，凑齐6个人给你家庭组特价，来？
