### ISSUE TITLE
MacOS下启用l2tp vpn(公司VPN+静态路由)后，连接clashX 提示系统代理设置已被另一个进程修改，Clashx不再是默认代理

### ISSUE THREAD

**Issue by doolindalton** [Fndroid/clash_for_windows_pkg#1057]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

**描述**

[//]: # MacOS下启用l2tp vpn(公司VPN+静态路由)后，连接clashX 提示系统代理设置已被另一个进程修改，Clashx不再是默认代理

**复现**

[//]: # (请描述复现问题的步骤)

1. '开启l2tp vpn'
2. 开启 '设置为系统代理'
3. 提示“系统代理设置已被另一个进程修改，Clashx不再是默认代理”

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by doolindalton** [comment]
求助要如何解决？是什么问题导致的呢

**Comment by doolindalton** [comment]
windows下无此类情况

**Comment by yi-Xu-0100** [comment]
如果你确定你用的是 clashX 的话，应该想办法联系 clashX 的反馈渠道，或者等待对方更新。

当前的仓库是 Clash For Windows 的，或者你可以试试当前仓库的应用，同时支持 Mac 和 windows。

**Comment by doolindalton** [comment]
好的，谢谢 准确的说是ClashX Pro

yi_Xu <notifications@github.com> 于2020年8月17日周一 下午3:18写道：

**Comment by Fndroid** [comment]
https://github.com/yichengchen/clashX

**Comment by Fndroid** [comment]
ClashX和Clash for Windows是两个不同的软件。

**Comment by doolindalton** [comment]
Fndroid <notifications@github.com>于2020年8月18日 周二09:08写道：

**Comment by keloee** [comment]
请问你解决这个问题了吗

**Comment by ahaolee** [comment]
@doolindalton

**Comment by JPAdCoder** [comment]
> Mac下进入偏好设置，进入VPN连接选项的高级选项，切换到代理选项，然后一次设置 <img alt="image" width="321" src="https://user-images.githubusercontent.com/35681414/194255941-c6969df1-35c8-46ea-aa63-d07a66d89aa5.png"> zhe'sa这三个的代理地址及端口，然后保存应用即可 <img alt="image" width="632" src="https://user-images.githubusercontent.com/35681414/194256202-966218b5-febd-4af6-ae22-24120b3e46e3.png"> 然后clashx就可以成为vpn连接的代理服务器了

非常感谢
