### ISSUE TITLE
配置文件建议放到软件本身的目录下，默认放到C盘用云盘同步的话比较麻烦

### ISSUE THREAD

**Issue by 189169** [Fndroid/clash_for_windows_pkg#1058]
**描述**
订阅内容的配置文件默认放到C盘用云盘同步的话比较麻烦，试了下好像也不能修改

**其他说明**
其他补充内容

**Comment by yi-Xu-0100** [comment]
应用支持自定义配置文件目录：<https://docs.cfw.lbyczf.com/contents/profilespath.html>

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/7z.html
