### ISSUE TITLE
希望增加汉化功能

### ISSUE THREAD

**Issue by chouxiang99** [Fndroid/clash_for_windows_pkg#1059]
目前只支持英文的，虽然能看懂  但还是中文看的舒服一点，建议增加一个中文的切换

**Comment by yi-Xu-0100** [comment]
#999 类似问题已回复

**Comment by iamqiz** [comment]
BoyceLig/Clash_Chinese_Patch: Clash For Windows 汉化补丁和汉化脚本
https://github.com/BoyceLig/Clash_Chinese_Patch
