### ISSUE TITLE
[BUG]退出后经常出现“无法连接到代理服务器”

### ISSUE THREAD

**Issue by SailFlorve** [Fndroid/clash_for_windows_pkg#106]
Windows版本1903，开着代理退出后浏览网页，经常出现无法连接到代理服务器，进设置手动关闭代理还会自己打开。只能打开Clash，然后手动取消System Proxy才正常。

**Comment by Fndroid** [comment]
CFW退出了系统设置里的代理会自动打开？

**Comment by SailFlorve** [comment]
如果退出CFW的时候不手动取消SystemProxy选项，那么代理服务器有几率会一直自己打开，把注册表HKEY_CURRENT_USERS\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Connections下的DefaultConnectionSettings和SavedLagacySettings两项数据删了才可以，而这两个数据内容就是CFW代理服务器的设置。

**Comment by Fndroid** [comment]
- 退出之后注册表如何改变已经和CFW无关了
- 退出（右键icon，选择quit）时，CFW并不会直接关闭系统代理设置，而是还原至开启时的状态，假设你开启CFW时系统代理已经设置，关闭后，CFW只会给你还原这些设置

**Comment by CreateOneMore** [comment]
CFW退出了系统设置里的代理会自动打开.. 而且我手动把代理设置关了之后. 马上就会又强制被打开.

**Comment by Fndroid** [comment]
@CreateOneMore https://github.com/Fndroid/clash_for_windows_pkg/issues/106#issuecomment-482428979

**Comment by CreateOneMore** [comment]
我看到这条了. 我试过在关闭CFW后, 再去删除注册表里面的这两条. 再开启CFW. 但是我在没有关闭CFW的情况下关机. CFW不会还原代理设置, 开机后如果没有开启CFW就会出现无法上网的情况. 关闭CFW后 代理设置就会还原到上次关机前CFW的设置, 相当与没有还原. 手动还原之后, 会被强制开启到CFW的设置.

**Comment by Fndroid** [comment]
> 我看到这条了. 我试过在关闭CFW后, 再去删除注册表里面的这两条. 再开启CFW. 但是我在没有关闭CFW的情况下关机. CFW不会还原代理设置, 开机后如果没有开启CFW就会出现无法上网的情况. 关闭CFW后 代理设置就会还原到上次关机前CFW的设置, 相当与没有还原. 手动还原之后, 会被强制开启到CFW的设置.

1. CFW关闭后，会尝试恢复到开启前的状态，之后系统代理再怎么变，都和CFW无关
2. 系统关机不会通知软件，所以无法给你还原

**Comment by SailFlorve** [comment]
我想补充下，1809和1803没有问题，问题是在最新的预览版1903出现的。我现在已经回退到1809了，一切正常。

**Comment by phoenix12341** [comment]
同样的问题  目前还是存在  删除注册表 可以用  它还是会跳代理  但是ie设置里代理ip为空

**Comment by learnprogram2** [comment]
> Windows版本1903，开着代理退出后浏览网页，经常出现无法连接到代理服务器，进设置手动关闭代理还会自己打开。只能打开Clash，然后手动取消System Proxy才正常。

谢谢~
