### ISSUE TITLE
英文的 Settings 界面有 Typo：JavaScirpt

### ISSUE THREAD

**Issue by iBug** [Fndroid/clash_for_windows_pkg#1060]
**信息**

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

无关，CFW Windows 0.11.4 版

**描述**

英文版 Settings 页面的 JavaScript 打成了 JavaScirpt

**复现**

就在 Settings 页面

**预期行为**

JavaScript

**日志**

No

**截图**

![image](https://user-images.githubusercontent.com/7273074/90475361-e6476900-e159-11ea-808b-684c0f443002.png)

**其他说明**

No

**Comment by Fndroid** [comment]
哈哈，感谢反馈

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
