### ISSUE TITLE
开启系统代理uwp lookback问题

### ISSUE THREAD

**Issue by ForestL18** [Fndroid/clash_for_windows_pkg#1065]
开启系统代理后，如果不把uwp lookback里的某应用勾选上，则无法打开该应用，无论该应用是否需要科学上网。这个bug希望可以修复一下。

**Comment by Fndroid** [comment]
不能打开跟代理有什么关系

**Comment by ForestL18** [comment]
我前面的表述可能有点问题，应用不能打开是指打开应用后页面加载不出来，比如微软商店打开后图片全部无法加载；还有那个微软的sticky notes也无法同步。

**Comment by Fndroid** [comment]
uwp就是这样，并不是bug
