### ISSUE TITLE
dashboard无法正常显示

### ISSUE THREAD

**Issue by freejool** [Fndroid/clash_for_windows_pkg#1066]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

windows10 
0.11.4

**描述**

dashboard界面不显示，任务栏如图，
![图片](https://user-images.githubusercontent.com/39995589/90711407-36960680-e2d3-11ea-8b30-ebb4e679339d.png)
但是功能正常

**复现**

[//]: # 

一打开就这样

**Comment by Fndroid** [comment]
清空下这个文件夹试试：``C:\Users\<用户名>\AppData\Roaming\clash_win``

**Comment by freejool** [comment]
解决了，感谢

**Comment by AcquireKnown** [comment]
清空文件夹还是不行
