### ISSUE TITLE
[FR]IE代理-设置套接字代理

### ISSUE THREAD

**Issue by cdcy2000** [Fndroid/clash_for_windows_pkg#107]
Clash版本号:
Clash For Windows v0.5.30

操作系统:
Windows7 Service Pack 1

问题:
在启用Clash的System Proxy选项后，使用有道笔记，同步服务器数据失败。（始终能重现）

手动解决:
1. 禁用Clash的System Proxy选项后，使用有道笔记，同步服务器数据成功。
2. IE代理设置里面，取消"对所有协议均使用相同的代理服务器"，针对套接字的设置相应的端口。
- 比如:
Clash HTTP Proxy Port : 1081
Clash Sock5 Proxy Port : 1080
- 那么:
![image](https://user-images.githubusercontent.com/31757220/56011617-0b80c780-5d1b-11e9-9cd0-4b1fb6c51767.png)
使用有道笔记，同步服务器数据成功。

FR:
是否可能在启用Clash的System Proxy选项后针对IE的代理设置加入Sock5的端口?

**Comment by Fndroid** [comment]
有道云笔记可以单独设置APP代理

**Comment by cdcy2000** [comment]
是的，有道云笔记可以在设置里面可以单独设置代理。

但是这里有个问题: 
有道云笔记只能设置HTTP请求的代理，也就是说如果是Socket的请求，那么它还是会遵从IE的代理设置，所以会失败。
![image](https://user-images.githubusercontent.com/31757220/56034157-1fe3b500-5d59-11e9-8812-10ff8fbedb54.png)

据我观察，有道云同步数据的这个请求刚好就是基于Socket的。
这个Socket连接建立一旦成功如果再开启Clash的Proxy就不会有什么问题，但是我因为设置了Clash "Start with Windows"，所以Clash会先启动起来，然后有道云再尝试连接Socket就会失败。

我准备调整一下应用的启动顺序，先把其它应用启动起来后再开启Clash，这样就不会有问题了。

谢谢!

**Comment by Fndroid** [comment]
这里涉及的问题就是，系统代理如果要用socks5，就需要用PAC，但是Windows自己的bug导致它不支持本地路径的PAC文件。

所以只能在本地开一个server去serve这个PAC文件，但是只是为了这个去开一个服务，成本太高。而且目前Clash也不支持UDP，socks5和http的区别不是太大。

**Comment by Fndroid** [comment]
0.6以后版本套接字应该不会再设置错误而是留空，应该不会再导致无法连接
