### ISSUE TITLE
代理规则十分闹心，也许这就是我选择v2ray的原因吧

### ISSUE THREAD

**Issue by KoedaNagi** [Fndroid/clash_for_windows_pkg#1070]

**Comment by yi-Xu-0100** [comment]
如果与软件无关的~~引战~~话题，还是不要在 issue 中提出吧，这里主要用于反馈 bug 的和提出可能的需求的。
而且，代理规则的话，不应该是代理商自行提供嘛？自定义的话，也给出了[配置文件预处理办法](https://docs.cfw.lbyczf.com/contents/parser.html)的解决办法。
如果对当前模式不太满意的话，**提出功能改进的请求**，或者**直接换**的话，会比在这里抱怨~~或者提出疑似引战的话~~简单有效的多。

**Comment by Fndroid** [comment]
好
