### ISSUE TITLE
添加 PROCESS-NAME 类型的 rule 支持

### ISSUE THREAD

**Issue by liuweiGL** [Fndroid/clash_for_windows_pkg#1071]
**描述**
请具体并清楚地描述期望功能及期望的效果

添加 rule 时支持 `PROCESS-NAME` 类型：
![image](https://user-images.githubusercontent.com/21048878/90847966-4dedf600-e39e-11ea-8642-58efc3338cc9.png)

**其他说明**

clash 内核正式版已经支持：https://github.com/Dreamacro/clash/releases/tag/v1.1.0

**Comment by Fndroid** [comment]
最新版已添加
