### ISSUE TITLE
Start Mixed(http and socks5) server error

### ISSUE THREAD

**Issue by BinZJU** [Fndroid/clash_for_windows_pkg#1073]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
win10 x64 19041.450
[//]: # (平台及版本号)

**描述**
打开CFW并导入profile后，无论Global或者Direct都无法上网，google或者bing等都打不开。System Proxy关闭后，bing可打开。
[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'CFW'
2. 点击'Proxies'，Global
3. 开启Edge
4. 触发问题

**预期行为**
能够打开google，实际打不开，并且bing，baidu也打不开。切换到direct，也无法打开。关闭CFW中的System Proxy之后，bing可以打开。
[//]: # (清晰地描述期望看到的行为)

**日志**
time="2020-08-24T08:46:32+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-08-24T08:46:32+08:00" level=info msg="RESTful API listening at: 127.0.0.1:22222"
time="2020-08-24T08:46:32+08:00" level=error msg="Start Mixed(http and socks5) server error: listen tcp 127.0.0.1:7890: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2020-08-24T08:46:33+08:00" level=info msg="Start initial compatible provider Auto"
time="2020-08-24T08:46:33+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-08-24T08:46:33+08:00" level=info msg="Start initial compatible provider Auto"
time="2020-08-24T08:46:33+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-08-24T08:46:55+08:00" level=info msg="Start initial compatible provider Auto"
time="2020-08-24T08:46:55+08:00" level=info msg="Start initial compatible provider Proxy"
[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**
此前使用Trojan-Qt5，正常。
[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
mixed-port 被占用了
General YAML > Text Mode Edit 改一下
