### ISSUE TITLE
可以上架win10应用商店吗

### ISSUE THREAD

**Issue by YZY1360** [Fndroid/clash_for_windows_pkg#1074]
我正在使用surface go，由于配置原因留在S mode，希望在此模式下也能使用clash。

win10 S mode下无法运行未上架应用商店的win32程序。

感谢！

**Comment by bdbai** [comment]
可以试试这个已经上架的 UWP 代理应用  [YtFlow](https://github.com/YtFlow/YtFlowApp)。

**Comment by YZY1360** [comment]
> 可以试试这个已经上架的 UWP 代理应用 [YtFlow](https://github.com/YtFlow/YtFlowApp)。

非常感谢，不过我没有在应用商店搜到您的应用，下载[YtFlowApp_0.0.6.0_test.7z](https://github.com/YtFlow/YtFlowApp/releases/download/v0.0.6/YtFlowApp_0.0.6.0_Test.7z)然后运行Install.ps1后同样会弹出“此WIndows模式只运行Microsoft Store中经过验证的应用”的提示。

**Comment by bdbai** [comment]
> > 可以试试这个已经上架的 UWP 代理应用 [YtFlow](https://github.com/YtFlow/YtFlowApp)。
> 
> 非常感谢，不过我没有在应用商店搜到您的应用，下载[YtFlowApp_0.0.6.0_test.7z](https://github.com/YtFlow/YtFlowApp/releases/download/v0.0.6/YtFlowApp_0.0.6.0_Test.7z)然后运行Install.ps1后同样会弹出“此WIndows模式只运行Microsoft Store中经过验证的应用”的提示。

没有公开发布，链接 https://www.microsoft.com/store/apps/9NMB8FHL7MBZ 在项目首页。也可以通过设备门户或者 App Installer 进行旁加载。

**Comment by YZY1360** [comment]
> > 非常感谢，不过我没有在应用商店搜到您的应用，下载[YtFlowApp_0.0.6.0_test.7z](https://github.com/YtFlow/YtFlowApp/releases/download/v0.0.6/YtFlowApp_0.0.6.0_Test.7z)然后运行Install.ps1后同样会弹出“此WIndows模式只运行Microsoft Store中经过验证的应用”的提示。
> 
> 没有公开发布，链接 https://www.microsoft.com/store/apps/9NMB8FHL7MBZ 在项目首页。也可以通过设备门户或者 App Installer 进行旁加载。

非常感谢，可以用了。
