### ISSUE TITLE
How I can change Home Directory as same as clash.exe directory?

### ISSUE THREAD

**Issue by hamedsbt** [Fndroid/clash_for_windows_pkg#1075]
I want to make clash portable as much as possible, so can I change ``.config`` directory from ``%userprofile%.config`` to beside clash.exe?

**Comment by yi-Xu-0100** [comment]
Source document: <https://docs.cfw.lbyczf.com/contents/7z.html>
The follow is translated using Google Translate:

## Portable mode

### Version requirements

Starting from 0.4.0, Clash for Windows provides simple portable support.

### Instructions

Go to the Release page to download the latest free installation package with the suffix `.zip` or `.7z` and unzip it to the directory you want to install(such as mobile hard disk, U disk, etc.).

#### Configuration file

Enter the `your_installation_directory/resources/static/files/` directory and do the following operations:

1. Create a new `config.yaml` (the file can be empty, but it must be created).

2. Restart Clash for Windows.

There are other files and folders in the folder directory at this time, please do not modify them.

#### Start and update

`Clash for Windows.exe` in the installation directory is the software entrance, click to start.

If you need to update Clash for Windows, just download the corresponding zip installation package, unzip and overwrite it to the software directory.
