### ISSUE TITLE
URL Scheme 导入不支持 URL encoded 地址

### ISSUE THREAD

**Issue by mp-s** [Fndroid/clash_for_windows_pkg#1078]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 10 x64 v0.11.5

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
使用 0.11.5 版本客户端, 遇到URL encoded内容 ( https:// 被转义 ) 会导致不能自动下载配置
例如
`clash://install-config?url=https%3A%2F%2Fxxxxxxxxxx`  

如果使用非URL encoded内容可以触发自动下载配置
例如 `clash://install-config?url=https://xxxxxxxxxx`

**复现**

[//]: # (请描述复现问题的步骤)

1. 浏览器地址栏粘贴带URL encoded的URL Scheme
2. 回车
3. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)
CFW不应丢弃此类clash URL scheme。

**日志**

[//]: # (上传触发问题对应的日志文件)
无

**截图**

[//]: # (如果可以，请提供对应问题的截图)
无

**其他说明**

[//]: # (其他补充内容)
0.11.4 表现正常，更新到0.11.5后出现

**Comment by Fndroid** [comment]
感谢反馈，下个版本修复

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
