### ISSUE TITLE
[FR]添加 复制终端代理命令

### ISSUE THREAD

**Issue by Tatamethues** [Fndroid/clash_for_windows_pkg#108]
**Is your feature request related to a problem? Please describe.**
NO
**Describe the solution you'd like**
右键软件图标，显示 复制终端代理命令。复制下面命令，然后可以用于粘贴到terminal
```
set http_proxy=http://127.0.0.1:7890
set https_proxy=http://127.0.0.1:7890
```
**Describe alternatives you've considered**
Non
**Additional context**
Non

**Comment by Fndroid** [comment]
@Tatamethues powershell可以直接走系统代理

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.5.33

**Comment by Tatamethues** [comment]
@Fndroid 谢谢

**Comment by cy920820** [comment]
> https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.5.33
> 
> 点击General里的Port可以复制

终端无法 ping 通 google.com
