### ISSUE TITLE
提供倒序排序连接的方式？

### ISSUE THREAD

**Issue by iBug** [Fndroid/clash_for_windows_pkg#1080]
现在的连接如果按照时间排序的话，最新的连接在最下方，在需要观察最新连接的时候需要不断地往下滚动。希望可以提供一个“按时间倒序”的方案，让最新的连接在最上面显示，或者直接将现在的“时间”排序改为倒序。

**Comment by iBug** [comment]
@fndroid

**Comment by iBug** [comment]
我看到 0.13.3 的 changelog 提到了倒序排序，但是我没找到控制这个的 UI 选项，请问还是 WIP 吗？

**Comment by yi-Xu-0100** [comment]
@iBug 
![image](https://user-images.githubusercontent.com/25523606/99134961-07d1c700-265b-11eb-8308-29b1fcd958c6.png)

**Comment by iBug** [comment]
@yi-Xu-0100 非常感谢，我用深色模式所以完全没注意到

![image](https://user-images.githubusercontent.com/7273074/99142784-4edbae80-2693-11eb-95a6-58b446c4cf39.png)

cc @Fndroid 这次是一个 UI issue 了

**Comment by iBug** [comment]
Consider this fixed in 0.13.4.
