### ISSUE TITLE
请问profiles一片空白是怎么回事啊？

### ISSUE THREAD

**Issue by MuZhilin** [Fndroid/clash_for_windows_pkg#1082]
小白一枚，希望大佬帮帮我，不要解释的太复杂，不然看不懂。。。谢谢了。删了重新下也不行。重启电脑也不行。

![屏幕截图(9)](https://user-images.githubusercontent.com/7886881/91162207-5f1c6700-e6fe-11ea-9537-80ac25eb7890.png)

**Comment by yi-Xu-0100** [comment]
查看情况是否与 #1072 类似。

**Comment by MuZhilin** [comment]
> 查看情况是否与 #1072 类似。

不行，还是空白的

**Comment by yi-Xu-0100** [comment]
自行下载配置文件，查看字段是否正确，给出Home Directory 中 logs 文件下最新文件中的内容。

**Comment by Fndroid** [comment]
进入Home Directory把profikes文件夹删除，重启软件

**Comment by MuZhilin** [comment]
> 自行下载配置文件，查看字段是否正确，给出Home Directory 中 logs 文件下最新文件中的内容。

我在setting里选择了个配置文件目录就好了。

**Comment by MuZhilin** [comment]
> 自行下载配置文件，查看字段是否正确，给出Home Directory 中 logs 文件下最新文件中的内容。

但是proxies里又是空白了。

**Comment by yi-Xu-0100** [comment]
试试作者说的方法，还有检查自己的配置文件中字段是否正确。

**Comment by 1017737237** [comment]
和你一样的原因 我已经解决了 删除c盘的C:\Users\admin\.config 重新打开clash就OK了
