### ISSUE TITLE
could not connect to clash core

### ISSUE THREAD

**Issue by RosePuff** [Fndroid/clash_for_windows_pkg#1084]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'正常点击'
2. 点击管理员启动
3. 触发问题

**预期行为**

直接报错
**日志**

time="2020-08-26T16:23:32+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-08-26T16:23:32+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-08-26T16:23:32+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:99"
time="2020-08-26T16:23:32+08:00" level=error msg="External controller error: listen tcp 127.0.0.1:9090: bind: An attempt was made to access a socket in a way forbidden by its access permissions."

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)
重置网络还是修改端口号都无法启动

**Comment by jason96** [comment]
同样的问题更换[Dreamacro/clash v1.1.0](https://github.com/Dreamacro/clash/releases/tag/v1.1.0)core后就会报这个错，但只要换回来就没事，现在是不能更换clash core了吗？

**Comment by Fndroid** [comment]
> "External controller error: listen tcp 127.0.0.1:9090: bind: An attempt was made to access a socket in a way forbidden by its access permissions."

external-controller 端口被占用，General YAML更改其他端口

**Comment by hupo376787** [comment]
General yaml 根本不显示。。。
![image](https://user-images.githubusercontent.com/14960168/91438995-de48a100-e89e-11ea-9131-c20c5bfd45f7.png)

**Comment by yi-Xu-0100** [comment]
打开 Home Directory 中打开 config.yaml 修改相应字段。

**Comment by hupo376787** [comment]
@yi-Xu-0100 谢谢
