### ISSUE TITLE
clash每次升级覆盖安装，GeoIP数据库（Country.mmdb）不会自动更新为最新版

### ISSUE THREAD

**Issue by leafsoul365** [Fndroid/clash_for_windows_pkg#1088]
你好，clash每次升级覆盖安装，GeoIP数据库（Country.mmdb）不会自动更新为版本携带的最新版，需要从clash安装目录找到Country.mmdb文件手动拷贝到 “C:\Users\用户名\.config\clash\Country.mmdb”覆盖才行。

**Comment by leic4u** [comment]
我开始还以为mmdb是不会随着CFW的版本更新而更新了，只能自己去下载mmdb来手动覆盖更新。你这样一说我才发现mmdb是连同CFW一起更新的，只是没有覆盖到正确路径里面去。

**Comment by leafsoul365** [comment]
> 我开始还以为mmdb是不会随着CFW的版本更新而更新了，只能自己去下载mmdb来手动覆盖更新。你这样一说我才发现mmdb是连同CFW一起更新的，只是没有覆盖到正确路径里面去。

是的，基本每个clash版本都会附带更新了GeoIP数据库，只是需要我们手动操作一下，需要我们从   \Clash for Windows\resources\static\files\default\Country.mmdb 下把文件复制到 C:\Users\用户名.config\clash\Country.mmdb”覆盖才行。
不知是否可以自动更新。

**Comment by Fndroid** [comment]
那个并不是最新的，只是给第一次安装的时候用的。

更新GEOIP是有独立功能的，但是在Windows上有bug所以现在屏蔽了。

这个数据库没必要天天更新。（甚至没什么必要更新）
