### ISSUE TITLE
Clash for windows cfw-tap is on while system proxy button is toggled off

### ISSUE THREAD

**Issue by messi06** [Fndroid/clash_for_windows_pkg#1089]
cfw-tap is on while system proxy button is toggled off, also while I set system proxy off , I try browsing the web aka : YouTube and google etc.. , in connections tab I see it's using the selected proxy as the proxy is on and YouTube and everything works as system proxy is on. I think even we set system proxy off , as long the profile that has cfw-tap enable , still forwards the packets through the proxy...
Is there a way to fix this please ? Because I rely on clash getting the profile list daily , if the last selected proxy server is dead , it won't even let the computer connect to the internet at all...
But really shout out to you bro ! Awesome work really ! You rock !

**Comment by Fndroid** [comment]
If you don't use TAP at all, just remove the TAP Device in General.

**Comment by messi06** [comment]
> If you don't use TAP at all, just remove the TAP Device in General.

That's the thing , I use tap and I rely on it alot !

**Comment by messi06** [comment]
Although when you select another profile that doesn't have cfw-tap enabled , the tap gets off , and all works normally , I thought to point out the bug , overall thank you for your hard work 🙏

**Comment by Fndroid** [comment]
I'm not getting your point. Have you mixed up with TAP & System Proxy?

**Comment by messi06** [comment]
> I'm not getting your point. Have you mixed up with TAP & System Proxy?

i think yes , it's a bit confusing sorry , so i take it we can only use one option ? either tap or system proxy with UWP ?
and if that's the case , tap will always be on as long the profile is selected .
anyway i will create 2 separate profiles , one with tap enabled , one without , i think this is the best approach . thank you so much for replying and for your hard work !
