### ISSUE TITLE
协议规则对widnows应用监控不完全，比如OneNote

### ISSUE THREAD

**Issue by qq33357486** [Fndroid/clash_for_windows_pkg#109]
案例：
网易云音乐，windows store 版本
OneNote， windows sotre版本

在规则已经已经单独把microsoft.com加入到Direct规则里。
在caputures里已经没有额外链接。
但依旧无法通过直接链接联网。

会呈现网络无法连接，既不走代理也不走直接链接的情况。

**Comment by Fndroid** [comment]
Duplicate of #13
