### ISSUE TITLE
错误提示：Tap mode enable but no interface-name setted

### ISSUE THREAD

**Issue by EXWhiteDragon** [Fndroid/clash_for_windows_pkg#1091]
通过vmess链接导入配置文件弹出错误提示：

```
Could not switch to this profile!
Tap mode enable but no interface-name setted

```
已更新至最新的v0.11.5。
配置链接没有问题，其他人以同样的方式添加配置链接 没有任何异常。
导入替换其他人正常的配置文件，“Proxies”仍然是完全空白。
也尝试过删除C:\Users\用户\.config\clash文件夹，但没有任何效果。

**Comment by Fndroid** [comment]
1. 并没有所谓vmess导入的说法
2. 上面报错是因为配置文件配置了dns有可能会启动TAP模式，https://docs.cfw.lbyczf.com/contents/tap.html
3. Proxies空白就是配置文件没有proxies字段

**Comment by tihSdoolB** [comment]
我更新到0.11.7之后也曾经遇到这个问题，在Settings-Outbound-Interface Name中选择了出口网卡就没有了报错，你可以尝试一下。
