### ISSUE TITLE
新版CFW利用Parser或Mixin功能，支持旧格式Clash配置文件

### ISSUE THREAD

**Issue by ztyzbb** [Fndroid/clash_for_windows_pkg#1092]
这个Issue不是Bug，只是给有相同问题的人提供解决方案，在用的服务商至今没升级订阅的格式，太屑了。
在总结两位大佬的建议后，方法主要有两种：
1. 使用[Parser](https://docs.cfw.lbyczf.com/contents/parser.html)
   - 优点：
     1. 转换完的配置文件自动写入至磁盘，后续可以在Profiles中通过GUI编辑配置文件
   - 缺点：
     1. 一旦出错，排错比较困难，目前测试下来Parser的调用时机早于判断服务器返回的HTTP响应码是不是200，这导致传入的原始响应体可能根本不是YAML，而是一段错误信息，导致你的JS代码抛出各种奇奇怪怪的异常。我这里就遇到了服务器返回522，然后yaml解析时各种令人迷惑的异常
   - 使用方法：
     1. Settings→Parsers按[Parser](https://docs.cfw.lbyczf.com/contents/parser.html)中配置，code后的脚本如下：
        ```es6
        module.exports.parse = (raw, { yaml }) => {
          const content = yaml.parse(raw);
          if (content.proxies === undefined) {
            content.proxies = content.Proxy;
            delete content.Proxy;
            content['proxy-groups'] = content['Proxy Group'];
            delete content['Proxy Group'];
            content.rules = content.Rule;
            delete content.Rule;
            return yaml.stringify(content);
          } else {
            return raw;
          }
        }
        ```
     2. Profiles→点击你的订阅的刷新按钮，让CFW重新下载新的配置文件并应用
2. 使用[Mixin](https://docs.cfw.lbyczf.com/contents/mixin.html)
   - 优点：
      1. 执行Mixin是在最后配置生效前，因此可以保证content是正常的
   - 缺点：
      1. 转换后的配置文件不会回写磁盘，因此Profiles中编辑配置文件的功能依然是空的，不过用订阅的人需要调整配置文件，本来就应该在Parser或者Mixin中实现，而不应该通过GUI
   - 使用方法：
     1. Settings→Profile Mixin→Type→JavaScript
     2. Settings→Profile Mixin→JavaScript 输入如下内容：
        ```es6
        module.exports.parse = ({ content, name, url }, { axios, yaml, notify }) => {
          if(content.proxies === undefined) {
            content.proxies = content.Proxy;
            delete content.Proxy;
            content['proxy-groups'] = content['Proxy Group'];
            delete content['Proxy Group'];
            content.rules = content.Rule;
            delete content.Rule;
          }
          return content
        }
        ```
     3. General→Mixin→On
     4. Profiles→点击你的订阅，让CFW重新加载

**Comment by flyingwhitewhale** [comment]
好思路，学习了

**Comment by yi-Xu-0100** [comment]
mixin 会对所有的订阅配置生效，而且结果保存在内存中，主要用于 dns 添加
可以试试 [配置文件预处理方法](https://docs.cfw.lbyczf.com/contents/parser.html)
我在 #1072 中给出了类似的适配旧规则的方法。方便对不同订阅生效，可以参考
该方法还可以用于自定义规则，可以参考我写的 [changeRule.js](https://github.com/yi-Xu-0100/Application-Lists/blob/master/Configuration/ClashForWindows/changeRule.js)

**Comment by flyingwhitewhale** [comment]
谢谢，一直不懂scrit怎么写，同时因为机场买得比较多，所以都是用subconverter生成。今天总算是开眼了，谢谢

**Comment by Fndroid** [comment]
用parser更加合适

**Comment by ztyzbb** [comment]
@yi-Xu-0100 @Fndroid  感谢两位，这个功能之前没去研究，我之前还尝试在Mixin里把改变后的yaml回写磁盘，发现不太行。刚看完文档后发现确实Parser比较好，可以考虑将 #1072 置顶。

**Comment by ztyzbb** [comment]
@Fndroid 是否考虑将Parser的调用时机往后延一些，至少判断完HTTP状态码再调用

**Comment by Fndroid** [comment]
> 是否考虑将Parser的调用时机往后延一些，至少判断完HTTP状态码再调用

bug，下个版本修复

**Comment by Fndroid** [comment]
>  是否考虑将Parser的调用时机往后延一些，至少判断完HTTP状态码再调用

已经修复

并且最新版已经支持多个parser顺序处理配置文件
