### ISSUE TITLE
请问新版Clash怎么启用Tap模式? 

### ISSUE THREAD

**Issue by yang05051** [Fndroid/clash_for_windows_pkg#1094]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10, Clash v0.11.6

**描述**

请问新版Clash怎么启用Tap模式? 我按照官方文档尝试在conf.yaml和cfw-settings.yaml添加了dns的设置，但是cfw-tap虚拟网卡始终没有工作

**Comment by Fndroid** [comment]
哪个官方文档要你修改cfw-settings.yaml这个文件？


https://docs.cfw.lbyczf.com/contents/tap.html

**Comment by yang05051** [comment]
已经弄好了，看的是您的文档
