### ISSUE TITLE
默认配置失效了

### ISSUE THREAD

**Issue by smileat2000** [Fndroid/clash_for_windows_pkg#1095]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
win10
[//]: # (平台及版本号)

**描述**
之前的版本修改config.yaml能保存规则，别的配置也能用，更新之后没效果了，在默认配置文件写了规则不生效
[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
请注明修改了哪些部分，字段。
修改的文件是 Home Directory 目录下的 config.yaml 吗？

**Comment by Fndroid** [comment]
一直都不会生效的

**Comment by smileat2000** [comment]
> 请注明修改了哪些部分，字段。
> 修改的文件是 Home Directory 目录下的 config.yaml 吗？

就是Profiles的第一个config默认的，不能删除的那个

**Comment by smileat2000** [comment]
> 请注明修改了哪些部分，字段。
> 修改的文件是 Home Directory 目录下的 config.yaml 吗？

修改了rules，因为我需要设置一些网站白名单，DIRECT这种，设置一次永久有效，因为如果在订阅的配置里修改的话，更新订阅后就没了，每次更新都需要重新加

**Comment by yi-Xu-0100** [comment]
上面作者说明了，应该是一直不会生效的，rule字段应该是配置文件中的才会生效。 @smileat2000 
可以试试 [配置文件预处理方法](https://docs.cfw.lbyczf.com/contents/parser.html)，自定义规则，可以参考我写的 [changeRule.js](https://github.com/yi-Xu-0100/Application-Lists/blob/master/Configuration/ClashForWindows/changeRule.js)

**Comment by smileat2000** [comment]
> 上面作者说明了，应该是一直不会生效的，rules 字段应该是配置文件中的才会生效。 @smileat2000
> 可以试试 [配置文件预处理方法](https://docs.cfw.lbyczf.com/contents/parser.html)，自定义规则，可以参考我写的 [changeRule.js](https://github.com/yi-Xu-0100/Application-Lists/blob/master/Configuration/ClashForWindows/changeRule.js)

Clash for Windows在v 0.4.5 版本后可以自定义系统代理需要绕过的域名或IP，默认是全局代理，部分应用检测到系统代理会拒绝响应（例如网易云音乐uwp）。

Clash客户端下受影响应用
微软商店
网易云音乐
酷我音乐
爱奇艺
。。。
几乎所有UWP应用受此影响而无法访问外网。以下设置方法，可解决此问题

设置方式
config.yml

Clash客户端绕过系统代理设置方法

port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: Global
log-level: info
external-controller: '127.0.0.1:9090'
secret: ''
cfw-bypass:
  ...
  - 'music.163.com' # 网易云域名1
  - '*.music.126.net' # 网易云域名2
  - '*.kuwo.cn' #酷我音乐
  - '*.iqiyi.com'  #爱奇艺
  - '*.microsoft.com'  #微软商店
cfw-latency-timeout: 3000
Proxy:
  - name: Shadowsocks
    type: socks5
    server: 127.0.0.1
    port: 1080
Proxy Group:
  - name: Proxy
    type: select
    proxies:
      - Shadowsocks
Rule:
  - 'MATCH,DIRECT'


这个是我以前加白名单的方法，更新之后不管用了，还是会走代理

**Comment by yi-Xu-0100** [comment]
如果是设置 bypass 关键词的话，现在的配置更新了，参考：[绕过系统代理说明文档](https://docs.cfw.lbyczf.com/contents/bypass.html)
