### ISSUE TITLE
问题咨询：powershell 下 http 可以 proxy 但 ssh 无法 proxy

### ISSUE THREAD

**Issue by huangnauh** [Fndroid/clash_for_windows_pkg#1096]
**信息**

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

windows 1909

**描述**
powershell 下 http 可以 proxy 但 ssh 无法 proxy

**复现**

1. 配置
```
$Env:http_proxy = "http://127.0.0.1:7890"
$Env:https_proxy = "http://127.0.0.1:7890"
$Env:all_proxy = "socks5://127.0.0.1:7891"
```

2. 测试 http 正常
http 访问正常(10.0.5.108 需要 proxy)：

```
curl 10.0.5.108:8500
<a href="/ui/">Moved Permanently</a>.
```

3. 测试 ssh 超时
```
ssh root@10.0.5.108
```

**日志**

1. http 日志

![image](https://user-images.githubusercontent.com/3659433/91654408-fad11d00-eada-11ea-9b58-476a8d4295c8.png)

2. ssh 无相关日志

** 问题 **

是否需要特殊配置？

**Comment by yi-Xu-0100** [comment]
需要配置 ssh 设置代理，百度/谷歌：为 ssh 配置代理

**Comment by Fndroid** [comment]
这难道不是ssh自身问题么

**Comment by huangnauh** [comment]
> 需要为 ssh 设置代理，百度/谷歌：为 ssh 配置代理

需要 ProxyCommand ？ linux 下 nc 支持 proxy_address， windows 不熟悉，同样装了 nc ，看 help 文档似乎不支持 proxy。windows 下有类似的常用网络工具有推荐吗？

**Comment by yi-Xu-0100** [comment]
谷歌找到的第一个：https://walkedby.com/sshwindowsproxy/

或者自行百度/谷歌： Windows 为 ssh 配置代理

**Comment by huangnauh** [comment]
> 谷歌找到的第一个：https://walkedby.com/sshwindowsproxy/
> 
> 
> 
> 或者自行百度/谷歌： Windows 为 ssh 配置代理

好的，我搜寻过相关方案，但方案涉及到的工具都比较小众，所以在这边咨询下，看看有什么其他方案，这边先关闭了

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/tap.html

**Comment by huangnauh** [comment]
> 谷歌找到的第一个：https://walkedby.com/sshwindowsproxy/
> 
> 或者自行百度/谷歌： Windows 为 ssh 配置代理

咦，看了下这篇文章，原来 MinGW 只带 connect 程序， 我之前是直接编译的这个 https://github.com/larryhou/connect-proxy

**Comment by huangnauh** [comment]
> https://docs.cfw.lbyczf.com/contents/tap.html

多谢，TAP 模式还没了解过，我去研究下
