### ISSUE TITLE
便携版配置文件

### ISSUE THREAD

**Issue by netsonicyxf** [Fndroid/clash_for_windows_pkg#1097]
**描述**
下载Clash.for.Windows-0.11.6-win.7z，解压运行后，会在C:\Users\用户名\AppData\Roaming\clash_win\
和C:\Users\用户名\.config\clash
下生成配置文件。如果重装系统设置就没了，能否让设置文件和应用文件在同一个目录下？

**其他说明**
其他补充内容

**Comment by yi-Xu-0100** [comment]
可以参考 [便携模式说明文档](https://docs.cfw.lbyczf.com/contents/7z.html)

**Comment by Fndroid** [comment]
看看文档吧
