### ISSUE TITLE
无法使用tap模式

### ISSUE THREAD

**Issue by Brocode0422** [Fndroid/clash_for_windows_pkg#1098]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

-[x]已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
-[x]已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
-[x] 已经尝试更新到最新版本，问题依旧存在
-[x]软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

win8.1 clash v0.11.6

**描述**

安装tap虚拟网卡后，在Proflies中添加“interface-name: net”后无法使用该配置文件，显示"Error: Nested mappings are not allowed in compact mappings, on line:28, at colum:17
删除“interface-name: net”字段后可正常切换为该配置文件。

**预期行为**

希望能正确修改配置文件，并正常使用tap模式

**报错图片**

![报错图片](https://user-images.githubusercontent.com/69589580/91654774-59e46100-eade-11ea-938e-a683014a0f6e.png)

**配置文件**
配置文件部分如下：
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
experimental:
  ignore-resolve-fail: true
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 1.2.4.8
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://1.1.1.1/dns-query
    - tls://dns.adguard.com:853
interface-name: net

**Comment by Fndroid** [comment]
能用个代码块把你配置包裹起来吗？现在这样全居左了怎么看呢

**Comment by Brocode0422** [comment]
> 能用个代码块把你配置包裹起来吗？现在这样全居左了怎么看呢
不好意思，请问是像下面这样吗？谢谢
`port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
experimental:
  ignore-resolve-fail: true
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 1.2.4.8
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://1.1.1.1/dns-query
    - tls://dns.adguard.com:853
interface-name: net`

**Comment by yi-Xu-0100** [comment]
看不到行号和缩减……注意代码块前面留空行，预览里面先看一下

**Comment by Brocode0422** [comment]
> 看不到缩减……注意代码块前面留空行，预览里面先看一下

不好意思，确实是存在缩进的问题，修改之后就解决了，谢谢
