### ISSUE TITLE
服务器速度测试以及排序

### ISSUE THREAD

**Issue by netsonicyxf** [Fndroid/clash_for_windows_pkg#1099]
**描述**
1. 按照测试latency大小排序，现在似乎无法排序
2. 可以自定义测试URL
3. 按照自定义时间间隔自动测速。

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
1. 设置排序模式后重新进入Proxies就会触发排序，但节点必须至少进行过一次延迟测试
2. 自行在配置文件中设置
3. 自行在配置文件中设置
