### ISSUE TITLE
cfw+chrome+SwitchyOmega浏览网页的时候，出现页面频繁崩溃的情况

### ISSUE THREAD

**Issue by yyysuo** [Fndroid/clash_for_windows_pkg#11]
这个是cfw的原因还是chrome的锅？chrome是70.0.3538.102（正式版本） （64 位），SwitchyOmega是最新版本，系统是windows  pro x64 1809

**Comment by Fndroid** [comment]
暂时无法复现，更新到最新release使用看看是否改善

**Comment by ShadowLyin** [comment]
同样的问题，chrome版本：70.0.3538.110，SwitchyOmega版本：2.5.20，SwitchyOmega使用socks5代理时崩溃，使用http代理时正常，已测试只使用SwitchyOmega插件时同样崩溃。

**Comment by Fndroid** [comment]
> 同样的问题，chrome版本：70.0.3538.110，SwitchyOmega版本：2.5.20，SwitchyOmega使用socks5代理时崩溃，使用http代理时正常，已测试只使用SwitchyOmega插件时同样崩溃。

可以截个设置的图看看吗，插件里的

**Comment by ShadowLyin** [comment]
> > 同样的问题，chrome版本：70.0.3538.110，SwitchyOmega版本：2.5.20，SwitchyOmega使用socks5代理时崩溃，使用http代理时正常，已测试只使用SwitchyOmega插件时同样崩溃。
> 
> 可以截个设置的图看看吗，插件里的

忘了提，目前只测试在访问http://www.speedtest.net/zh-Hans时会发生崩溃，其他页面似乎没问题。。。

**Comment by ShadowLyin** [comment]
clash 已修复，https://github.com/Dreamacro/clash/issues/46

**Comment by Fndroid** [comment]
> clash 已修复，https://github.com/Dreamacro/clash/issues/46

等release再更新到Clash for Windows里面

**Comment by Fndroid** [comment]
测试一下[这个release](https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.4.4)

**Comment by yyysuo** [comment]
初步测试reject已经不会再崩溃了，tls我没有测试。

**Comment by Fndroid** [comment]
issue关闭，需要时可以reopen
