### ISSUE TITLE
[BUG] vmess 在 v2rayN 客户端上能使用但在 clash_for_Windows 上无法使用

### ISSUE THREAD

**Issue by touzi** [Fndroid/clash_for_windows_pkg#110]
clash_for_Windows 客户端版本 0.5.33
vmess 同样的配置在 v2rayN 上可以使用, 在 clash_for_Windows 测试提示为 timeout

**Comment by Fndroid** [comment]
服务端怎么配置的

**Comment by van7ish** [comment]
@Fndroid 
遇到了同样的问题，win10可以用vmess，win7不行。
使用的 "bash <(curl -s -L https://git.io/v2ray.sh)"脚本配置的。

**Comment by Fndroid** [comment]
@van7ish 配置了什么协议，具体一点才好判断

**Comment by van7ish** [comment]
@Fndroid 脚本一路回车，普通的TCP协议，没加tls，没加混淆。

**Comment by jozhn** [comment]
同，TCP，无TLS，auto，无法使用。感觉添加节点的方式有点反人类，虽然界面很好看

**Comment by opszhou** [comment]
两个节点都是ws + tls 除了反向代理软件不一样，域名不一样，配置都一样

|linode节点 | bandwagon节点|
|--- |---|
|阿里云的域名|godaddy域名|
|nginx + v2ray|caddy + v2ray|
|v2rayN可用|v2rayN可用|
|clash不可用|clash可用|

**Comment by Fndroid** [comment]
目前Clsah不支持V2Ray的动态端口配置，不能连接的检查一些服务端是不是配置了动态端口

**Comment by Kiotlin** [comment]
会是时间戳不一致的问题么，服务端收到请求比对时间戳不一致可能会出错，我看log上打印的是东八区时间

**Comment by WenJunDuan** [comment]
https://tgbot.lbyczf.com/v2rayn2clash?
后面拼接你们的订阅链接
