### ISSUE TITLE
建议不自动获取日志

### ISSUE THREAD

**Issue by Gluneklairo** [Fndroid/clash_for_windows_pkg#1101]
**描述**
希望给个开关能选择是否获取日志
**其他说明**
强迫症每次都要手动删除.config文件夹

**Comment by Fndroid** [comment]
General - General YAML - Edit - log-level改成silent

**Comment by Gluneklairo** [comment]
能不能将.config文件夹的目录设置到软件目录，我以为这只是日志文件夹，原来配置文件也在里面

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/7z.html

**Comment by Gluneklairo** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fndroid/clash_for_windows_pkg"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月1日(星期二) 中午1:00
收件人:&nbsp;"Fndroid/clash_for_windows_pkg"<clash_for_windows_pkg@noreply.github.com&gt;;
抄送:&nbsp;"Gluneko_Leo"<Gluneklairo@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Fndroid/clash_for_windows_pkg] 建议不自动获取日志 (#1101)





 
https://docs.cfw.lbyczf.com/contents/7z.html
