### ISSUE TITLE
希望能够在侦测到关机时一并关闭系统代理.

### ISSUE THREAD

**Issue by RA1NN1AR** [Fndroid/clash_for_windows_pkg#1102]
**描述**
在clash_for_windows运行状态下,希望能够在侦测到关机时一并关闭系统代理.
每次开机上网后才会察觉到代理没启动,要自己手动去设置里关闭.
不是所有人都会把cfw(简称)设为开机启动并启动系统代理,请添加这个便利的功能.

**其他说明**
希望仓库作者能够开放源代码,这边愿意提交相应的功能代码以供合并.

**Comment by Fndroid** [comment]
那请问应该怎么实现呢？

**Comment by RA1NN1AR** [comment]
Windows关机事件

**Comment by RA1NN1AR** [comment]
刚刚搜索到了类似的issue.
作者所使用的开发语言应该无法处理这种WIndows关机事件.
很抱歉给作者造成的麻烦.🙏

**Comment by RA1NN1AR** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/943

**Comment by Fndroid** [comment]
这里给一个方案，你可以试试看。用PAC实现。

1. 进系统设置里找到代理设置，打开pac开关，填入地址``https://cloudcompute.lbyczf.com/clash/pac?port=7890``，地址里的port改成你CFW里General那个

2. 关闭CFW里的``System Proxy``，不用打开

这样即使关机没有退出CFW，开机之后也不会影响你连国内网站

但是有些不识别系统PAC代理的APP可能要手动设置代理

**Comment by RA1NO3O** [comment]
这边想到的方案是：
添加一个Windows计划任务,设定触发器为用户会话关闭时触发.
应该会更有效一点:)

**Comment by LiJT** [comment]
> 

您好作者，我的pac设置里面默认的有这么一行code

function FindProxyForURL(url, host) {
  return "PROXY 127.0.0.1:%mixed-port%; SOCKS5 127.0.0.1:%mixed-port%; DIRECT;"
}

我应该在哪里添加您的这个地址 https://cloudcompute.lbyczf.com/clash/pac?port=7890 ？

这里具体应该怎么改呢？
