### ISSUE TITLE
cfw-tap网卡自动断开

### ISSUE THREAD

**Issue by ChanEKan** [Fndroid/clash_for_windows_pkg#1103]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
win10 1909 和 2004
**描述**

[//]: # (请具体并清楚地描述遇到的问题)
正常使用过程中 cfw-tap 网卡自动断开，显示 网络电缆被拔出, 但 Mixin 仍然是打开状态，重启软件或者关闭 Mixin 再打开能重新连上，但不定时又会断开，周而复始
**复现**

[//]: # (请描述复现问题的步骤)
打开网络连接的窗口蹲过，找不到复现规律

**预期行为**

[//]: # (清晰地描述期望看到的行为)
cfw-tap网卡不会自动断开
**日志**

[//]: # (上传触发问题对应的日志文件)
time="Tue Sep 01 2020 21:37:09 GMT+0800 (中国标准时间)" level=info msg="restore at index: 1"
time="Tue Sep 01 2020 21:37:09 GMT+0800 (中国标准时间)" level=info msg="restore proxy settings"
time="Tue Sep 01 2020 21:43:25 GMT+0800 (中国标准时间)" level=info msg="restore at index: 1"
time="Tue Sep 01 2020 21:43:26 GMT+0800 (中国标准时间)" level=info msg="restore proxy settings"
time="Tue Sep 01 2020 21:43:26 GMT+0800 (中国标准时间)" level=info msg="Spawn go-tun2socks"
time="Tue Sep 01 2020 21:44:58 GMT+0800 (中国标准时间)" level=info msg="app start with mode: production"
time="Tue Sep 01 2020 21:44:58 GMT+0800 (中国标准时间)" level=info msg="restarting clash core..."
time="Tue Sep 01 2020 21:44:58 GMT+0800 (中国标准时间)" level=info msg="load data from general config.yaml"
time="Tue Sep 01 2020 21:44:58 GMT+0800 (中国标准时间)" level=info msg="load data from general config.yaml"
time="Tue Sep 01 2020 21:44:59 GMT+0800 (中国标准时间)" level=info msg="restore at index: 1"
time="Tue Sep 01 2020 21:44:59 GMT+0800 (中国标准时间)" level=info msg="new outbound interface: WLAN"
time="Tue Sep 01 2020 21:44:59 GMT+0800 (中国标准时间)" level=info msg="restore at index: 1"
time="Tue Sep 01 2020 21:44:59 GMT+0800 (中国标准时间)" level=info msg="clash core startup success!"
time="Tue Sep 01 2020 21:44:59 GMT+0800 (中国标准时间)" level=info msg="restore proxy settings"
time="Tue Sep 01 2020 21:44:59 GMT+0800 (中国标准时间)" level=info msg="Spawn go-tun2socks"
time="Tue Sep 01 2020 21:44:59 GMT+0800 (中国标准时间)" level=info msg="check for app update, current: 0.11.6"
time="Tue Sep 01 2020 21:44:59 GMT+0800 (中国标准时间)" level=info msg="restore proxy settings"
time="Tue Sep 01 2020 21:44:59 GMT+0800 (中国标准时间)" level=info msg="Spawn go-tun2socks"

43分时打开了Mixin，没想到几秒后就断开了出现了， 44分时重启了软件，
**截图**

[//]: # (如果可以，请提供对应问题的截图)
不懂得怎么插入图片
**其他说明**

[//]: # (其他补充内容)
问题在 只打开Mixin， 打开Mixin和系统代理 时都会出现
尝试过 重装系统（1909和2004版本），卸载和重装网卡驱动，刷新dns缓存，重置网络（netsh winsock reset）
从 0.11.4 版本开始使用到现在的 0.11.6 都有这个问题，

**Comment by Fndroid** [comment]
mixin怎么设置的

**Comment by ChanEKan** [comment]
`mixin: # object
 dns:
   enable: true
   enhanced-mode: redir-host # 或 fake-ip
   listen: 0.0.0.0:53
   nameserver:
      - 223.5.5.5
 interface-name: WLAN # 物理网卡名称`

**Comment by ChanEKan** [comment]
> mixin怎么设置的

mixin: # object
 dns:
   enable: true
   enhanced-mode: redir-host # 或 fake-ip
   listen: 0.0.0.0:53
   nameserver:
      - 223.5.5.5
 interface-name: WLAN # 物理网卡名称

**Comment by ChanEKan** [comment]
> mixin怎么设置的

`mixin: # object
 dns:
   enable: true
   enhanced-mode: redir-host # 或 fake-ip
   listen: 0.0.0.0:53
   nameserver:
      - 223.5.5.5
 interface-name: WLAN # 物理网卡名称`

**Comment by ChanEKan** [comment]
> mixin怎么设置的

[http://tu.yaohuo.me/imgs/2020/09/36c0838fdc581700.png](url)

**Comment by ChanEKan** [comment]
![9c59f6faa1e1a661af64354bed1b2e9](https://user-images.githubusercontent.com/61399103/92016983-aef5d080-ed85-11ea-9a32-f5ac01bfc9e0.png)
不知道怎么保持缩进，这是图片

**Comment by ChanEKan** [comment]
> mixin怎么设置的

不知道怎么保持缩进，这是图片
![9c59f6faa1e1a661af64354bed1b2e9](https://user-images.githubusercontent.com/61399103/92017084-d2208000-ed85-11ea-961c-8a08239649ed.png)

**Comment by ChanEKan** [comment]
附一正常使用时cfe-tap网卡的图
![微信截图_20200903015243](https://user-images.githubusercontent.com/61399103/92018874-56740280-ed88-11ea-9b54-08d51682fc36.png)

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/92050041-9fdf4480-edbe-11ea-9741-0594c2284fc9.png)

缩减看起来，分别是1，2，3，1，可能有误。 建议在自己本地的代码编辑器中编辑后，再复制粘贴进去。

**Comment by Fndroid** [comment]
应该是tun2socks.exe出错退出了。

可以试试直接运行tun2socks的二进制看看报错：
1. 进入安装目录/resources/static/files/tun2socks
2. 打开powershell，命令``.\go-tun2socks.exe -tunName cfw-tap -tunDns 10.0.0.1 -tunAddr 10.0.0.1 -tunMask 255.255.255.0 -tunGw 10.0.0.0 -proxyServer 127.0.0.1:7890``，最后这个7890是General中的端口

**Comment by ChanEKan** [comment]
终于抓到了，这次是在看油管时崩了
![log](https://user-images.githubusercontent.com/61399103/92125114-351b2100-ee31-11ea-9298-7160ee00cd2d.png)

**Comment by ChanEKan** [comment]
> 应该是tun2socks.exe出错退出了。
> 
> 可以试试直接运行tun2socks的二进制看看报错：
> 
> 1. 进入安装目录/resources/static/files/tun2socks
> 2. 打开powershell，命令`.\go-tun2socks.exe -tunName cfw-tap -tunDns 10.0.0.1 -tunAddr 10.0.0.1 -tunMask 255.255.255.0 -tunGw 10.0.0.0 -proxyServer 127.0.0.1:7890`，最后这个7890是General中的端口

终于抓到了，这次是在看油管时崩了
![log](https://user-images.githubusercontent.com/61399103/92125201-567c0d00-ee31-11ea-85db-592393c77ad1.png)

**Comment by ChanEKan** [comment]
> > 应该是tun2socks.exe出错退出了。
> > 可以试试直接运行tun2socks的二进制看看报错：
> > 
> > 1. 进入安装目录/resources/static/files/tun2socks
> > 2. 打开powershell，命令`.\go-tun2socks.exe -tunName cfw-tap -tunDns 10.0.0.1 -tunAddr 10.0.0.1 -tunMask 255.255.255.0 -tunGw 10.0.0.0 -proxyServer 127.0.0.1:7890`，最后这个7890是General中的端口
> 
> 终于抓到了，这次是在看油管时崩了
> ![log](https://user-images.githubusercontent.com/61399103/92125201-567c0d00-ee31-11ea-85db-592393c77ad1.png)

`2020/09/03 22:00:27 new proxy connection to 69.171.246.9:443
2020/09/03 22:00:27 new proxy connection to 172.217.27.129:443
panic: runtime error: index out of range [0] with length 0

goroutine 3598 [running]:
github.com/eycorsican/go-tun2socks/core.(*udpConn).WriteFrom.func1(0xc002221ee0, 0xc)
        /ext-go/1/src/github.com/eycorsican/go-tun2socks/core/udp_conn.go:139 +0x11b
github.com/eycorsican/go-tun2socks/core.(*udpConn).WriteFrom(0xc00232f560, 0xc00338a00a, 0x0, 0xffd2, 0xc0026e03f0, 0x0, 0x0, 0x0)
        /ext-go/1/src/github.com/eycorsican/go-tun2socks/core/udp_conn.go:139 +0xe9
github.com/eycorsican/go-tun2socks/proxy/socks.(*udpHandler).fetchUDPInput(0xc00004c540, 0x5e3ae0, 0xc00232f560, 0x5e4980, 0xc002a6c1f8)
        /ext-go/1/src/github.com/eycorsican/go-tun2socks/proxy/socks/udp.go:81 +0x27e
created by github.com/eycorsican/go-tun2socks/proxy/socks.(*udpHandler).connectInternal
        /ext-go/1/src/github.com/eycorsican/go-tun2socks/proxy/socks/udp.go:152 +0x691

D:\Program Files\Clash\resources\static\files\tun2socks>`

**Comment by ChanEKan** [comment]
> > 应该是tun2socks.exe出错退出了。
> > 可以试试直接运行tun2socks的二进制看看报错：
> > 
> > 1. 进入安装目录/resources/static/files/tun2socks
> > 2. 打开powershell，命令`.\go-tun2socks.exe -tunName cfw-tap -tunDns 10.0.0.1 -tunAddr 10.0.0.1 -tunMask 255.255.255.0 -tunGw 10.0.0.0 -proxyServer 127.0.0.1:7890`，最后这个7890是General中的端口
> 
> 终于抓到了，这次是在看油管时崩了
> ![log](https://user-images.githubusercontent.com/61399103/92125201-567c0d00-ee31-11ea-85db-592393c77ad1.png)

2020/09/03 22:00:27 new proxy connection to 69.171.246.9:443
2020/09/03 22:00:27 new proxy connection to 172.217.27.129:443
panic: runtime error: index out of range [0] with length 0

goroutine 3598 [running]:
github.com/eycorsican/go-tun2socks/core.(*udpConn).WriteFrom.func1(0xc002221ee0, 0xc)
        /ext-go/1/src/github.com/eycorsican/go-tun2socks/core/udp_conn.go:139 +0x11b
github.com/eycorsican/go-tun2socks/core.(*udpConn).WriteFrom(0xc00232f560, 0xc00338a00a, 0x0, 0xffd2, 0xc0026e03f0, 0x0, 0x0, 0x0)
        /ext-go/1/src/github.com/eycorsican/go-tun2socks/core/udp_conn.go:139 +0xe9
github.com/eycorsican/go-tun2socks/proxy/socks.(*udpHandler).fetchUDPInput(0xc00004c540, 0x5e3ae0, 0xc00232f560, 0x5e4980, 0xc002a6c1f8)
        /ext-go/1/src/github.com/eycorsican/go-tun2socks/proxy/socks/udp.go:81 +0x27e
created by github.com/eycorsican/go-tun2socks/proxy/socks.(*udpHandler).connectInternal
        /ext-go/1/src/github.com/eycorsican/go-tun2socks/proxy/socks/udp.go:152 +0x691

D:\Program Files\Clash\resources\static\files\tun2socks>

**Comment by messi06** [comment]
Hi , i used to have the same issue on windows 10 , after testing and checking around , i found out that some other softwares installed on the system were interfeering with cfw-tap.
The software in my case was Ethernet killer driver  : https://support.killernetworking.com/download/killer-drivers-installation-64bit/
after removing that driver + service , i still have ethernet on my system and cfw-tap works great without issues , i hope this helps..
PS: make sure also to disable the service killer network in services tab of task manager
![2020-09-06_104659](https://user-images.githubusercontent.com/13597151/92317013-66147500-f02e-11ea-9509-9378a5c6000b.jpg)
