### ISSUE TITLE
无法开启System Proxy

### ISSUE THREAD

**Issue by DongGuaGH** [Fndroid/clash_for_windows_pkg#1105]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Microsoft Windows [版本 10.0.19041.450]

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
无法开启System Proxy
触发问题之后重启、重置LSP、卸载重装之后皆无法打开。
进入带网络连接的安全模式启动clash点击System Proxy的按钮也毫无反应

**复现**

[//]: # (请描述复现问题的步骤)
无

**预期行为**

[//]: # (清晰地描述期望看到的行为)
无

**日志**

[//]: # (上传触发问题对应的日志文件)
[2020-09-02-132101.log](https://github.com/Fndroid/clash_for_windows_pkg/files/5160240/2020-09-02-132101.log)

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/26429772/91935142-882f8f80-ecdc-11ea-89ad-ca41acf270c3.png)

**其他说明**

[//]: # (其他补充内容)
平时使用SwitchyOmega在chrome冲浪，今天某睿驱动更新失败，想着使用系统代理进行更新呢，发现打不开系统代理了。

**Comment by DongGuaGH** [comment]
在之后的过程中参考 #312 置顶评论的方法进行排查，并无所获。
因为在安全模式中还是无法打开System Proxy，考虑可能并非其他软件的问题，我将排查目标转向系统设置。
之后发现在Internet属性中-连接-局域网(LAN)设置中修改任何设置均无法保存，于是利用搜索引擎发现此帖子：
[Windows10无法保存代理设置且Windows 无法自动检测到该网络的代理设置。](https://answers.microsoft.com/zh-hans/windows/forum/all/%E9%97%AE%E9%A2%98%E5%B7%B2%E8%A7%A3%E5%86%B3windo/46e869c6-de9c-406f-bda6-418e06c72fdd)
其中描述 _“通过 Windows设置 > 网络和Internet > 代理 进行设置会闪退/无反应
通过 Internet选项 > 连接 > 局域网Lan设置 进行设置时保存按钮无反应”_
均符合我的情况，导致此情况的原因是 **WinHTTP Web Proxy Auto-Discovery Service 服务**没有启动
若可以通过手动启动，启动即可解决问题。
若 _“且此服务处于禁用状态，但与其他未启动服务不同，此服务所有选项都是灰色的...”_
则需要根据[此文章](https://social.technet.microsoft.com/Forums/msonline/zh-CN/3c0b9e3f-d30c-4b5f-860b-5233838af17f/22914203092517124320winhttpautoproxysvc263812115365311?forum=WinServerPreviewZHCN)进行如下步骤解决问题：

1. 打开注册表编辑器

2. 找到路径Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinHttpAutoProxySvc

3. 在右边找到一个名为Start的设置

4. 将她的值设置为2（2为自动启动）

5. 然后重新启动计算机

6. 检查该服务是否运行

解决问题后回顾感觉应该是某优化程序/加速器修改了系统服务导致的。
相信此情况并非个例，希望可以写入文档或并入置顶issue帮助其他有相似问题的朋友。

**Comment by Diealittle** [comment]
huge help thanks

**Comment by Fndroid** [comment]
感谢线索👍

**Comment by little-sherpa** [comment]
太棒了！终于帮助我将W10不能VPN的问题解决了！感谢楼主。谢谢！

**Comment by Mathinas** [comment]
呜呜呜，继上次查了好久无法解决之后，被迫重装。今天又无法打开，正准备重装，还好及时看到这个回答，已经解决了，非常感谢！！！🌹

**Comment by Mathinas** [comment]
请问Start值总是被改成4怎么解决呢，管理中的WinHTTP Web Proxy Auto-Discovery Service 服务也不见了，哎哎

**Comment by DongGuaGH** [comment]
@Mathinas 注册表键值被修改建议排查一下其他优化类软件的问题。至于服务丢失建议参考此贴[WinHTTP Web Proxy Auto-Discovery Service服务无法打开](https://answers.microsoft.com/zh-hans/windows/forum/all/winhttp-web-proxy-auto-discovery/8f45b6bd-c752-4331-bb8b-e722de473041)中的内容进行修复，这多半是系统方面的问题，修复不起作用可能就需要重装一次了。

**Comment by Mathinas** [comment]
@DongGuaGH 刚系统恢复到了一个还原点，暂时解决了问题，优化软件只有一个Advanced system care，不知道这个软件会不会

**Comment by DongGuaGH** [comment]
@Mathinas  那就很可能是advanced system care引起的，我提这个issue的时候也在用ASC，卸载之后再也没遇到过这个问题。你可以排查一下优化项目，估计其中就含有禁用此服务。

**Comment by Fndroid** [comment]
@loook98 ![image](https://user-images.githubusercontent.com/16091562/169078683-14e85c32-fd3a-4b62-8c79-32e6ff0333d2.jpeg)

**Comment by loook98** [comment]
> @loook98 ![image](https://user-images.githubusercontent.com/16091562/169078683-14e85c32-fd3a-4b62-8c79-32e6ff0333d2.jpeg)

我的是Windows。不过我把clash卸载掉，配置文件全删掉，然后重装就好了。

**Comment by greatghoul** [comment]
之前也遇到过，是 bypass 格式问题，格式修好后就没有问题了。

**Comment by H-xie** [comment]
> 之前也遇到过，是 bypass 格式问题，格式修好后就没有问题了。

同样的情况，通过修正pypass解决了。

希望增加错误提示，指示是哪个环节出错导致`系统代理`无法打开
@Fndroid

**Comment by ParvalShieh** [comment]
同样的情况，通过改正bypass解决了。

**Comment by V1067** [comment]
![image](https://user-images.githubusercontent.com/101241482/211919640-7e9e06df-6a78-4e54-af10-5d2b92b44893.png)
其实重置clash设置应该就好了，我是这么解决的！

**Comment by Canals233** [comment]
> ![image](https://user-images.githubusercontent.com/101241482/211919640-7e9e06df-6a78-4e54-af10-5d2b92b44893.png) 其实重置clash设置应该就好了，我是这么解决的！
 的确是这样，困扰了很久但重置设置后就可以了

**Comment by davidweining2333** [comment]
> 之前也遇到过，是 bypass 格式问题，格式修好后就没有问题了。

正解哦

**Comment by martinniee** [comment]
> > ![image](https://user-images.githubusercontent.com/101241482/211919640-7e9e06df-6a78-4e54-af10-5d2b92b44893.png) 其实重置clash设置应该就好了，我是这么解决的！
> > 的确是这样，困扰了很久但重置设置后就可以了

  感谢，有效。使用 https://github.com/Fndroid/clash_for_windows_pkg/issues/1105#issuecomment-685415492 重启电脑没有效果，如果可以的话，Reset All Settings就好了

**Comment by YanYeek** [comment]
> ![image](https://user-images.githubusercontent.com/101241482/211919640-7e9e06df-6a78-4e54-af10-5d2b92b44893.png) 其实重置clash设置应该就好了，我是这么解决的！

我也是 感谢提醒，建议备份一下配置

**Comment by skisqibao** [comment]
很奇怪，我是在用钉钉的时候发送图片失败了弹出是否关闭代理，之前都是取消的，这次开着会一急点到关闭上了，然后先是所有规则都超时了，我又去更新了一下配置，发现点了系统代理没反应，不变成绿色的球，然后先去internet选项里开启了代理，又按照楼主的方法配置了一遍，重启之后发现点了还是没反应，然后又重装覆盖了一遍，结果还是没反应，就随便选了个节点试了试，没想到它竟然是能用的，chatgpt也能访问，但就是系统代理那个点还是红色的，点击没反应不切换，这是什么显示bug吗

**Comment by utopia-ambition** [comment]
yes， the problem is the bypass format.

**Comment by yulimchen** [comment]
> 之前也遇到过，是 bypass 格式问题，格式修好后就没有问题了。

同！前两天修改过 bypass，现在修改了下就好了！

**Comment by n-fzwy** [comment]
> > 之前也遇到过，是 bypass 格式问题，格式修好后就没有问题了。
> 
> 同！前两天修改过 bypass，现在修改了下就好了！

请问是怎么修改的bypass呢？我试了很多方法还是打不开系统代理。

**Comment by n-fzwy** [comment]
请问是怎么修改bypass的呢？我用了很多方法还是打不开系统代理。

**Comment by yulimchen** [comment]
> 请问是怎么修改bypass的呢？我用了很多方法还是打不开系统代理。

需要注意 bypass 填入的域名格式，或者一行行删掉，看具体是哪个导致打不开的。

**Comment by 9563067** [comment]
bypass加了/就打不开系统代理
