### ISSUE TITLE
能否增加对DNS策略进行个性化修改的功能（DNS Strategy）

### ISSUE THREAD

**Issue by nonegood** [Fndroid/clash_for_windows_pkg#1106]
**描述**
类似 clash_for_android的DNS Strategy，可以对DNS进行个性化配置，比如更换DNS地址。
**其他说明**
该功能可在非全局代理模式下隐藏本地DNS地址

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/mixin.html

**Comment by nonegood** [comment]
> https://docs.cfw.lbyczf.com/contents/mixin.html

原来已经有了，感谢解答
