### ISSUE TITLE
Url not working on shadowrocket iOS app as a config

### ISSUE THREAD

**Issue by hessenm** [Fndroid/clash_for_windows_pkg#1108]
Hello 
It’s been a while that I’m using .yml url on Shadowrocket iOS app as a proxy and config but recently it’s not working I reset the settings of the app and update the .yml but still not working.
![Uploading 

>  #C836EBED-4159-4586-ABD0-2E72F38A2E75.jpeg…]()
![Uploading 934E8E02-6588-4136-8543-D74584AC141C.jpeg…]()

[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
Why don't you send your feedback to this Shaadowrocket APP?

**Comment by hessenm** [comment]
I have sent an email already, still not responding 
But when anyone wants to send feedback to the developers of this app it’s a message that you can see in this photo I attached.
I’m not sure it’s the App fault or the .yml url.




Sincerely

**Comment by Fndroid** [comment]
> But when anyone wants to send feedback to the developers of this app it’s a message that you can see in this photo I attached.

I can't see any photo you had tried to upload.

> I’m not sure it’s the App fault or the .yml url.

Both reasons are not the issue of my APP.
