### ISSUE TITLE
关于Allow LAN开关状态 Clash退出再打开后无法保持

### ISSUE THREAD

**Issue by starxin** [Fndroid/clash_for_windows_pkg#1109]
找了一台闲置的PC机安装 Clash 用于局域网的共享。Clash设置了开机自动启动start with windows。
界面上面Allow LAN 打开后，局域网的机器可以通过本机正常上网。但是一旦Clash 退出再打开或者 机器重启自动运行后，Allow LAN总是处于关闭状态。希望能够把这个设置保持住，不要每次打开clash后人工打开AllowLAN。

导入的yaml配置里面也设置了
允许局域网的连接 
allow-lan: true

版本113 跟 116 都无法保持，OS 为Windows 10

**Comment by Lechenx** [comment]
all-lan这个选项是需要配置在General yaml中的。

**Comment by starxin** [comment]
> all-lan这个选项是需要配置在General yaml中的。

我已经把默认的General yaml 删除了，只保留了一个远程的yaml。这样就不行了吧。
那要恢复的话，General yaml配置是放在哪个目录下面的呢？

**Comment by Lechenx** [comment]
username\.config\clash\config.yaml

**Comment by starxin** [comment]
> username \ .config\clash\config.yaml

OK 已经配置好，正常工作了~
