### ISSUE TITLE
System Proxy被锁定无法打开

### ISSUE THREAD

**Issue by LF9076** [Fndroid/clash_for_windows_pkg#1111]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**
System Proxy被锁定无法打开
[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
clash for windows  0.11.7
**描述**

[//]: # (请具体并清楚地描述遇到的问题)
System Proxy被锁定无法打开，最近也没有安装什么恶意软件
**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by palarain** [comment]
我跟你一样用360木马杀查扫描一下修复即可。

**Comment by palarain** [comment]
> **信息**
> System Proxy被锁定无法打开
> [//](#): # (如果符合，请将`[ ]`改为`[x]`)
> 
> * [x]  已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
> * [x]  已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
> * [x]  已经尝试更新到最新版本，问题依旧存在
> * [x]  软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）
> 
> **系统**
> 
> clash for windows 0.11.7
> **描述**
> 
> System Proxy被锁定无法打开，最近也没有安装什么恶意软件
> **复现**
> 
> 1. 进入'...'
> 2. 点击'....'
> 3. 拖动到'....'
> 4. 触发问题
> 
> **预期行为**
> 
> **日志**
> 
> **截图**
> 
> **其他说明**

我跟你一样用360木马杀查扫描一下修复即可。

**Comment by LF9076** [comment]
> 我跟你一样用360木马杀查扫描一下修复即可。
谢啦~~

**Comment by Mathinas** [comment]
查杀有用吗，我也是这样，搞了好久还是打不开

**Comment by Fndroid** [comment]
Duplicate of #312
