### ISSUE TITLE
一点改进建议

### ISSUE THREAD

**Issue by flydream3618** [Fndroid/clash_for_windows_pkg#1112]
**描述**
1、【GeoIP DataBase】建议允许用户提供下载地址，允许设定定期下载，比如允许填入下载地址：https://geolite.clash.dev/Country.mmdb，然后软件定期自动下载，目前软件只是简单弹窗提示自行搞定。

我目前用的替代方案：开发了个小工具，配合系统计划任务，自动定期更新。

2、全局代理这块比对了SSTap的全局模式，发现全局模式似乎并没起作用，比如命令行用composer安装软件时，实时网速一直保持0kb/s，相反SSTap全局模式工作很好，下载很快

我目前的替代方案：全局模式用SSTap

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
1. 因为Windows下有bug所以暂时屏蔽了这个功能

2. https://docs.cfw.lbyczf.com/contents/tap.html
