### ISSUE TITLE
有个问题挺好奇的

### ISSUE THREAD

**Issue by denghuotongming** [Fndroid/clash_for_windows_pkg#1113]
clash只设置，其他默认
  1. 开启开机自启
  2. 开启系统代理
  3. 开启了uwp loopback，里面全勾选
在这种状态下，我又打开了连接公司的VPN（在深圳），正常访问公司内网，还能访问Google。
但是我一旦把clash的mixin打开，里面配置
 mixin: 
   dns:
     enable: true
     listen: :53
     default-nameserver:
       - https://dns.rubyfish.cn/dns-query       
       - 1.1.1.1
     ipv6: false
     enhanced-mode: fake-ip
     nameserver:
       - https://223.6.6.6/dns-query
       - 1.0.0.1
就不能访问Google，公司内网可访问，把VPN给关了才行，只开clash才能访问Google！

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/tap.html
