### ISSUE TITLE
Profiles自动更新失败时反复重试

### ISSUE THREAD

**Issue by ArakiTatsuzou** [Fndroid/clash_for_windows_pkg#1115]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # macOS 10.15.6

**描述**

[//]: # Profiles自动更新失败时反复重试

**复现**

[//]: # (请描述复现问题的步骤)

1. 设置某个Profile自动更新间隔为0以外的任意数值
2. 等待自动更新
3. 当订阅反复不成功返回400错误
4. 触发问题

**预期行为**

[//]: # 失败一定次数后停止重试，直到下一个时间间隔为止

**日志**

[//]: # [2020-09-05-221004.log](https://github.com/Fndroid/clash_for_windows_pkg/files/5180509/2020-09-05-221004.log)

**截图**

[//]: # <img width="720" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/31207151/92338523-8c481c80-f0e3-11ea-9a06-7d17fc0352c7.png">

**其他说明**

[//]: # 无

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/92338912-eea21c80-f0e5-11ea-80d0-fd44a52453df.png)

上面图片来自 [百度百科-400](https://baike.baidu.com/item/400/814387) ，我在 log 文件中看到的唯一错误信息如下： 

``` log
time="2020-09-07T08:12:27+08:00" level=error msg="Start DNS server error: listen udp 127.0.0.1:53: bind: permission denied"
```

所以是不是订阅链接问题？造成无法访问。可以试试 ping 一下看看链接的 ip

**Comment by ArakiTatsuzou** [comment]
> ![image](https://user-images.githubusercontent.com/25523606/92338912-eea21c80-f0e5-11ea-80d0-fd44a52453df.png)
> 
> 
> 
> 上面图片来自 [百度百科-400](https://baike.baidu.com/item/400/814387) ，我在 log 文件中看到的唯一错误信息如下： 
> 
> 
> 
> ``` log
> 
> time="2020-09-07T08:12:27+08:00" level=error msg="Start DNS server error: listen udp 127.0.0.1:53: bind: permission denied"
> 
> ```
> 
> 
> 
> 所以是不是订阅链接问题？造成无法访问。可以试试 ping 一下看看链接的 ip

的确应该是这样，但造成反复尝试更新的还是软件机制吧

**Comment by yi-Xu-0100** [comment]
我不太确定是否可以设置更新间隔为 0，这样是不是就不会触发更新了。
因为文档中没有提到这个配置，我以我的经验来看，是这样的。
你可以尝试这样配置，让其不再更新。

当然如果你需要的是尝试失败之后，一段时间（非自动更新间隔）之后再重新尝试，可能需要更多的软件支持了。

**Comment by ArakiTatsuzou** [comment]
> 我不太确定是否可以设置更新间隔为 0，这样是不是就不会触发更新了。
> 因为文档中没有提到这个配置，我以我的经验来看，是这样的。
> 你可以尝试这样配置，让其不再更新。
> 
> 当然如果你需要的是尝试失败之后，一段时间（非自动更新间隔）之后再重新尝试，可能需要更多的软件支持了。

设置为0会禁止自动更新，但我认为尝试失败后连续尝试近20次不是作者预期效果，所以提交为bug

**Comment by Fndroid** [comment]
感谢反馈，下个版本修复

**Comment by Fndroid** [comment]
最新版已调整
