### ISSUE TITLE
一段时间不用网之后，System Proxy会自动关闭

### ISSUE THREAD

**Issue by funcodes** [Fndroid/clash_for_windows_pkg#1117]
RT。一段时间可能半个小时不操作电脑的话，System Proxy会自动关闭，开机启动的话System Proxy也不会跟着一起打开。
版本是：V0.11.7 我记得以前的版本是没有这个问题的。这是这个版本新增的功能吗。

**Comment by Fndroid** [comment]
Duplicate of #312
