### ISSUE TITLE
TAP模式无法自动启动

### ISSUE THREAD

**Issue by ccboxes** [Fndroid/clash_for_windows_pkg#1119]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 2004 专业版

**描述**

无法启用tap模式，切换到带有listen的配置后，tap网卡依然显示断开。翻看过几个issue，尝试使用mixin为配置手工添加dns和interface-name字段，依然无法启动。但是通过
https://github.com/Fndroid/clash_for_windows_pkg/issues/1103
中的命令
`.\go-tun2socks.exe -tunName cfw-tap -tunDns 10.0.0.1 -tunAddr 10.0.0.1 -tunMask 255.255.255.0 -tunGw 10.0.0.0 -proxyServer 127.0.0.1:7890`
可以手动启动tap模式

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入配置切换界面
2. 切换到tap配置
3.  触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)
tap模式自动启动

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
dns配置发出了

**Comment by ccboxes** [comment]
> 
> 
> dns配置发出来

`dns:
  enabled: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: redir-host
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fallback:
    - tls://1.1.1.1:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4`

**Comment by Fndroid** [comment]
``enable``不是``enabled``
