### ISSUE TITLE
[BUG] 无法打开 System Proxy

### ISSUE THREAD

**Issue by killsting** [Fndroid/clash_for_windows_pkg#112]
**Describe the bug**
经常性无法打开 System Proxy，每次开机时可时不可，退出后再打开也无法打开，只能重启解决。还有 Setup 的版本安装后无法使用，Portable 版反而可以。

**Desktop:**
 - OS: [e.g. Windows10]

**Comment by Fndroid** [comment]
Duplicate of https://github.com/Fndroid/clash_for_windows_pkg/issues/93#issuecomment-475875139

**Comment by Fndroid** [comment]
System Proxy是读写注册表操作，请检查是否有其他软件阻止修改

exe和zip十一样的，zip只是方便对目录进行覆盖更新

**Comment by killsting** [comment]
谢谢反馈，我再查找一下是哪里的问题导致的。Thanks!!

**Comment by Fndroid** [comment]
此issue将被关闭，如问题依旧，欢迎reopen
