### ISSUE TITLE
开启clash后IPV6网站打不开

### ISSUE THREAD

**Issue by hduwhyso** [Fndroid/clash_for_windows_pkg#1120]
**描述**
开启clash后ipv6网站打不开

**其他说明**
希望可以增加IPV6的dns，ipv6现在越来越普遍，希望可以增加

**Comment by Fndroid** [comment]
General YAML里加上

```yaml
ipv6: true
```

**Comment by vingol** [comment]
> General YAML里加上
> 
> ```yaml
> ipv6: true
> ```

有效，十分感谢

**Comment by TeemoZhang-ice** [comment]
> General YAML里加上
> 
> ```yaml
> ipv6: true
> ```

问题再次出现，加入ipv6: true该句依旧无用，开启clash后，在网站http://ip.zxinc.org/ipquery/中显示我的网络不支持ipv6，但是关闭clash后，就显示了我的ipv6地址
