### ISSUE TITLE
昨晚所有服务器突然用不了

### ISSUE THREAD

**Issue by denissyk2004** [Fndroid/clash_for_windows_pkg#1121]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

**描述** 昨晚手机电脑全部都连不上，电脑版的测速全部timeout。用别的代理软件可以正常上网。不知道是机场的协议问题还是软件的问题？已经试过重装了。

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by ygsk10** [comment]
建议看一下 时间同步 了没有

**Comment by denissyk2004** [comment]
突然又正常了....

**Comment by Alan0429** [comment]
@ygsk10 我也出现该问题，时间已同步

**Comment by yanlihu** [comment]
> 建议看一下 时间同步 了没有

请教一下同步时间是什么意思 怎么同步啊

**Comment by yanlihu** [comment]
> @ygsk10 我也出现该问题，时间已同步

我也出现该问题，时间已同步

**Comment by yanlihu** [comment]
#1128

**Comment by myfingerhurt** [comment]
![image](https://user-images.githubusercontent.com/12622279/93010435-67faad00-f5c7-11ea-912f-0cc016d30c87.png)

same problem here even in DIRECT mode. I'm living outside of GFW.

version 0.11.8, "Force Quit" and restart the App doesn't work.

Firefox Timeout but, clash logs shows nothing abnormal.

![image](https://user-images.githubusercontent.com/12622279/93010508-4d750380-f5c8-11ea-8425-aec6ceac570a.png)

**Comment by yanlihu** [comment]
> ![image](https://user-images.githubusercontent.com/12622279/93010435-67faad00-f5c7-11ea-912f-0cc016d30c87.png)
> 
> same problem here even in DIRECT mode. I'm living outside of GFW.
> 
> version 0.11.8, "Force Quit" and restart the App doesn't work.
> 
> Firefox Timeout but, clash logs shows nothing abnormal.
> 
> ![image](https://user-images.githubusercontent.com/12622279/93010508-4d750380-f5c8-11ea-8425-aec6ceac570a.png)
> 
> And I looked to my task manager, this clash refused to be killed. and my PC waked up from a hibernation.
> 
> I have tried all these and nothing worked. The clash refused to die!
> 
> ```
> C:\Windows\system32>taskkill /F /im "Clash for Windows.exe"
> ERROR: The process "Clash for Windows.exe" with PID 25112 could not be terminated.
> Reason: There is no running instance of the task.
> 
> C:\Windows\system32>wmic process where name="Clash for Windows.exe" call terminate
> Executing (\\SURFACEPRO3\ROOT\CIMV2:Win32_Process.Handle="25112")->terminate()
> Method execution successful.
> Out Parameters:
> instance of __PARAMETERS
> {
>         ReturnValue = 2;
> };
> 
> C:\Windows\system32>wmic process where "name='Clash for Windows.exe'" delete
> Deleting instance \\SURFACEPRO3\ROOT\CIMV2:Win32_Process.Handle="25112"
> ERROR:
> Description = Access denied
> ```
> 
> ![image](https://user-images.githubusercontent.com/12622279/93010730-88783680-f5ca-11ea-89f8-e549173a4d06.png)
> 
> ![image](https://user-images.githubusercontent.com/12622279/93011185-0f2f1280-f5cf-11ea-930d-55fac9c38a8b.png)

Can you copy your log file here

**Comment by yanlihu** [comment]
> ![image](https://user-images.githubusercontent.com/12622279/93010435-67faad00-f5c7-11ea-912f-0cc016d30c87.png)
> 
> same problem here even in DIRECT mode. I'm living outside of GFW.
> 
> version 0.11.8, "Force Quit" and restart the App doesn't work.
> 
> Firefox Timeout but, clash logs shows nothing abnormal.
> 
> ![image](https://user-images.githubusercontent.com/12622279/93010508-4d750380-f5c8-11ea-8425-aec6ceac570a.png)
> 
> And I looked to my task manager, this clash refused to be killed. and my PC waked up from a hibernation.
> 
> I have tried all these and nothing worked. The clash refused to die!
> 
> ```
> C:\Windows\system32>taskkill /F /im "Clash for Windows.exe"
> ERROR: The process "Clash for Windows.exe" with PID 25112 could not be terminated.
> Reason: There is no running instance of the task.
> 
> C:\Windows\system32>wmic process where name="Clash for Windows.exe" call terminate
> Executing (\\SURFACEPRO3\ROOT\CIMV2:Win32_Process.Handle="25112")->terminate()
> Method execution successful.
> Out Parameters:
> instance of __PARAMETERS
> {
>         ReturnValue = 2;
> };
> 
> C:\Windows\system32>wmic process where "name='Clash for Windows.exe'" delete
> Deleting instance \\SURFACEPRO3\ROOT\CIMV2:Win32_Process.Handle="25112"
> ERROR:
> Description = Access denied
> ```
> 
> ![image](https://user-images.githubusercontent.com/12622279/93010730-88783680-f5ca-11ea-89f8-e549173a4d06.png)
> 
> ![image](https://user-images.githubusercontent.com/12622279/93011185-0f2f1280-f5cf-11ea-930d-55fac9c38a8b.png)

Can you paste your log file here

**Comment by myfingerhurt** [comment]
@yanlihu 

There isn't much to look in the log file when it switches to DIRECT mode.

[2020-09-13-132219.log](https://github.com/Fndroid/clash_for_windows_pkg/files/5213671/2020-09-13-132219.log)

**Comment by yanlihu** [comment]
Only one usage of each socket address (protocol/network address/port) is normally permitted.
it shows that socket port occupied.
maybe you can try to restart your pc or switch another port

**Comment by yanlihu** [comment]
> @yanlihu
> 
> There isn't much to look in the log file when it switches to DIRECT mode.
> 
> [2020-09-13-132219.log](https://github.com/Fndroid/clash_for_windows_pkg/files/5213671/2020-09-13-132219.log)

Only one usage of each socket address (protocol/network address/port) is normally permitted.
it shows that socket port occupied.
maybe you can try to restart your pc or switch another port

**Comment by myfingerhurt** [comment]
@yanlihu 
I reboot my PC and so far so good.
