### ISSUE TITLE
win10设置好开机自启却无法启动

### ISSUE THREAD

**Issue by ComedianCN** [Fndroid/clash_for_windows_pkg#1122]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
win10 64位 1909    18363.1049
[//]: # (平台及版本号)

**描述**
CFW设置好开机自启，重启之后没有自动启动
此时无法上网，无法打开任何网页
任务管理器没有进程，启动项里面的clash是打开状态
必须要手动双击CFW才能启动而且才能正常上网
求助解决办法
[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by ComedianCN** [comment]
![微信图片编辑_20200908213413](https://user-images.githubusercontent.com/70957379/92483416-6756c500-f21b-11ea-890f-30cc83f5cea3.jpg)
![微信图片_20200908213427](https://user-images.githubusercontent.com/70957379/92483430-69b91f00-f21b-11ea-8524-b7bce619952e.jpg)
![微信图片_20200908213435](https://user-images.githubusercontent.com/70957379/92483434-6aea4c00-f21b-11ea-85cd-e326d06f8215.jpg)

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/92536304-e8d64380-f26b-11ea-9c87-7e38d4e6c2fb.png)

显然设置成功是这样的。

**Comment by yi-Xu-0100** [comment]
名称应该是 clash for windows 而不是 clash ，你可以试着禁用 clash 的自动启动，然后重新在 clash for windows 中设置自动启动试试，这里的启动项是否会出现和我类似的条目。名称和作者应该相同。

**Comment by ComedianCN** [comment]
> 名称应该是 clash for windows 而不是 clash ，你可以试着禁用 clash 的自动启动，然后重新在 clash for windows 中设置自动启动试试，看看这里的启动项是否会出现和我类似的条目。名称和作者应该相同。

感谢回复，已经通过重新安装CFW解决了问题。
