### ISSUE TITLE
自定义系统代理Bypass，独立于profile

### ISSUE THREAD

**Issue by zssng** [Fndroid/clash_for_windows_pkg#1123]
**描述**
内部网络某些主机名称需要直连，开关系统代理后，系统代理都会恢复为clash的默认bypass地址，需要手动追加这些主机名称，能否提供可以设置的地方
**其他说明**
其他补充内容

**Comment by yi-Xu-0100** [comment]
https://docs.cfw.lbyczf.com/contents/bypass.html
