### ISSUE TITLE
【求教】如何使用 CFW + SoftEther 搭建科学上网服务器

### ISSUE THREAD

**Issue by zhangzixun** [Fndroid/clash_for_windows_pkg#1124]
功能需求：
手机、电脑等设备，在外网通过 L2TP 连接服务，可以直接科学上网。
也就是说，只要 L2TP 连接上，不需要额外设置 Socks 等代理即可直接科学上网。

注意：已经在OpenWRT通过 PassWall+ SoftEhter 实现上述功能。原理是，SoftEther 提供 L2TP 连接功能，以 TAP 方式连接 PassWall 。

如何通过 CFW + SoftEther 实现上述功能？
请大神们赐教！

**Comment by Fndroid** [comment]
不能实现
