### ISSUE TITLE
windows 0.11.7版 图标切换不正常

### ISSUE THREAD

**Issue by pc10201** [Fndroid/clash_for_windows_pkg#1125]
之前的老版本
如果cfw没有托管系统代理，是一个小蓝猫
接管了系统代理，就会变成一个小黄猫

0.11.7版，不论是否接管了系统代理，都是一个小黄猫

**Comment by yi-Xu-0100** [comment]
我的最新版，没有问题，试试重装或者重启一下

**Comment by pc10201** [comment]
重启就好了
现在可以了

**Comment by yi-Xu-0100** [comment]
如果没问题的话，可以关闭 issue~😊
