### ISSUE TITLE
所有节点全部time out

### ISSUE THREAD

**Issue by xiaofuzia** [Fndroid/clash_for_windows_pkg#1127]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

**系统是win10，软件版本是Clash.for.Windows.Setup.0.11.8**

[//]: # (请具体并清楚地描述遇到的问题)

**从上周开始所有节点全部time out，一开始以为短暂bug，结果是一直打不开任何谷歌学术的网站
anylinks.me也打不开，我无法与售后联系...
现在的诉求是，如果软件还能用，我改怎么继续使用。
如果这个软件后面都无法使用了，那能不能按照使用时间将我的会员钱款按比例退了啊...**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by AkariiinMKII** [comment]
这边建议您先给作者打钱呢亲

**Comment by yi-Xu-0100** [comment]
我这也访问不了 anylinks.me

怕不是商家跑路了……

**Comment by xiaofuzia** [comment]
> 这边建议您先给作者打钱呢亲



> 这边建议您先给作者打钱呢亲

我买了三个月的会员啊，这才用了不到两个月

**Comment by xiaofuzia** [comment]
> 我这也访问不了 anylinks.me
> 
> 怕不是商家跑路了……

那你现在上谷歌正常吗

**Comment by yi-Xu-0100** [comment]
@xiaofuzia 当然正常啊，所以我说可能时商家跑路了，我挂代理，这个网站也没打开……

**Comment by Fndroid** [comment]
和软件无关问题请自行解决，不要浪费大家时间
