### ISSUE TITLE
clash 节点全部显示timeout

### ISSUE THREAD

**Issue by mirror123-lab** [Fndroid/clash_for_windows_pkg#1128]
![图片](https://user-images.githubusercontent.com/71115194/92924297-497f9f00-f46b-11ea-9467-4f1e22f4de07.png)
已经按照网站上的排查方式重新下载或是重启设备了，依然显示timeout

**Comment by yanlihu** [comment]
你是不是装了双系统 
我双系统进了一次linux出来就timeout，同步了系统时间也没用

**Comment by mirror123-lab** [comment]
没有装双系统。。

**Comment by xgdgsc** [comment]
奇怪的是我2个电脑,同样的0.11.8 同样的订阅url，有一个就全部timeout，另一个正常使用

**Comment by yanlihu** [comment]
> 奇怪的是我2个电脑,同样的0.11.8 同样的订阅url，有一个就全部timeout，另一个正常使用

我也是 而且时间也同步了 重装软件也不管用 就不知道该咋办了

**Comment by xgdgsc** [comment]
@yanlihu 谢谢提醒,我那个不行的电脑是好久没开机,时间比正常快了7分钟,在系统时间设置里重新同步下时间就好了

**Comment by yanlihu** [comment]
> > 奇怪的是我2个电脑,同样的0.11.8 同样的订阅url，有一个就全部timeout，另一个正常使用
> 
> 我也是 而且时间也同步了 重装软件也不管用 就不知道该咋办了

time="2020-09-12T16:49:22+08:00" level=warning msg="dial 🇺🇳 国外网站 error: gflk23vb.qrtb8gkpjv.buzz:443 connect error: lookup gflk23vb.qrtb8gkpjv.buzz: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server."
time="2020-09-12T16:49:22+08:00" level=warning msg="dial 🇺🇳 国外网站 error: gflk23vb.qrtb8gkpjv.buzz:443 connect error: lookup gflk23vb.qrtb8gkpjv.buzz: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server."
time="2020-09-12T16:49:29+08:00" level=warning msg="dial 🇺🇳 国外网站 error: gflk23vb.qrtb8gkpjv.buzz:443 connect error: lookup gflk23vb.qrtb8gkpjv.buzz: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server."
time="2020-09-12T16:49:29+08:00" level=warning msg="dial 🇺🇳 国外网站 error: gflk23vb.qrtb8gkpjv.buzz:443 connect error: lookup gflk23vb.qrtb8gkpjv.buzz: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server."

**Comment by yanlihu** [comment]
修改了dns就好了 之前一直用的223.5.5.5的dns，昨晚突然全部timeout，换了个dns就没问题了

**Comment by xsy97051** [comment]
> 修改了dns就好了 之前一直用的223.5.5.5的dns，昨晚突然全部timeout，换了个dns就没问题了

您好 我想问一下我同步了系统时间，也修改了DNS，还是所有节点timeout，您知道要怎么办吗？
![image](https://user-images.githubusercontent.com/44600210/93705996-c3431700-fb54-11ea-9e07-b386b073e046.png)

**Comment by yi-Xu-0100** [comment]
> > 修改了dns就好了 之前一直用的223.5.5.5的dns，昨晚突然全部timeout，换了个dns就没问题了
> 
> 您好 我想问一下我同步了系统时间，也修改了DNS，还是所有节点timeout，您知道要怎么办吗？
> ![image](https://user-images.githubusercontent.com/44600210/93705996-c3431700-fb54-11ea-9e07-b386b073e046.png)

可以百度下报错，我看到相关的https://blog.csdn.net/jiaolongdy/article/details/75258613

**Comment by xsy97051** [comment]
> > > 修改了dns就好了 之前一直用的223.5.5.5的dns，昨晚突然全部timeout，换了个dns就没问题了
> > 
> > 
> > 您好 我想问一下我同步了系统时间，也修改了DNS，还是所有节点timeout，您知道要怎么办吗？
> > ![image](https://user-images.githubusercontent.com/44600210/93705996-c3431700-fb54-11ea-9e07-b386b073e046.png)
> 
> 可以百度下报错，我看到相关的https://blog.csdn.net/jiaolongdy/article/details/75258613，可以看出还是时间错误，或许重装，重启什么的试试。

感谢回复，我也有查到这个，但有关windows下的解决方案还是查不到，除了重装系统都试过了。还有Android的也用不了，您还有什么可能有用的建议吗

**Comment by yi-Xu-0100** [comment]
@xsy97051 <https://www.geek-share.com/detail/2525340914.html>  注意备份，仅供参考

**Comment by yi-Xu-0100** [comment]
@xsy97051 发现一些相关的处理办法，<https://github.com/Dreamacro/clash/issues?q=is%3Aissue+x509+is%3Aclosed> 

里面有建议添加：

```
skip-cert-verify: true
```

到配置，建议查看下相关 issue

**Comment by xsy97051** [comment]
> @xsy97051 发现一些相关的处理办法，https://github.com/Dreamacro/clash/issues?q=is%3Aissue+x509+is%3Aclosed
> 
> 里面有建议添加：
> 
> ```yaml
> skip-cert-verify: true
> ```
> 
> 到配置，建议查看下相关 issue，

这些方法都不行，我再摸索一下吧，谢谢您

**Comment by yanlihu** [comment]
> > > > 修改了dns就好了 之前一直用的223.5.5.5的dns，昨晚突然全部timeout，换了个dns就没问题了
> > > 
> > > 
> > > 您好 我想问一下我同步了系统时间，也修改了DNS，还是所有节点timeout，您知道要怎么办吗？
> > > ![image](https://user-images.githubusercontent.com/44600210/93705996-c3431700-fb54-11ea-9e07-b386b073e046.png)
> > 
> > 
> > 可以百度下报错，我看到相关的[https://blog.csdn.net/jiaolongdy/article/details/75258613，可以看出还是时间错误，或许重装，重启什么的试试。](https://blog.csdn.net/jiaolongdy/article/details/75258613%EF%BC%8C%E5%8F%AF%E4%BB%A5%E7%9C%8B%E5%87%BA%E8%BF%98%E6%98%AF%E6%97%B6%E9%97%B4%E9%94%99%E8%AF%AF%EF%BC%8C%E6%88%96%E8%AE%B8%E9%87%8D%E8%A3%85%EF%BC%8C%E9%87%8D%E5%90%AF%E4%BB%80%E4%B9%88%E7%9A%84%E8%AF%95%E8%AF%95%E3%80%82)
> 
> 感谢回复，我也有查到这个，但有关windows下的解决方案还是查不到，除了重装系统都试过了。还有Android的也用不了，您还有什么可能有用的建议吗

你Windows 安卓都用不了 难道不是节点的问题吗

**Comment by philsau99** [comment]
可以尝试的解决方式：对比该计算机和手机、或其他能使用clash的计算机的系统时间，看时间是否有差别，手动设置系统时间

**Comment by FaSttttt** [comment]
改系统时间很重要
