### ISSUE TITLE
[FR] 能否在任务栏图标上增加设置菜单功能？（类似ClashX那样）

### ISSUE THREAD

**Issue by aglent** [Fndroid/clash_for_windows_pkg#113]
ClashX for Mac 在任务栏图标上点击 会出现菜单 可以选择出站模式 选择配置文件 选择Proxy Groups下的Proxies节点等等 这个功能我觉得很方便
不知道CFW对这个功能是否有兴趣？

图片在这里 https://netflixcn.com/uploads/article/20181114/4fb11884ab2dba98f3b9b17187377831.jpg

**Comment by Fndroid** [comment]
@aglent 没有兴趣，windows上面菜单不能滚动操作很不方便。你可以用ss-win
