### ISSUE TITLE
请问作者什么时候上快捷键功能呢？这个功能非常重要。

### ISSUE THREAD

**Issue by TNTboomer** [Fndroid/clash_for_windows_pkg#1131]
真的很需要开关代理的快捷键，使用有些应用时需要关闭代理，其他时候需要开着，每次用鼠标点太繁琐。希望作者能在下一个版本上快捷键😊

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
