### ISSUE TITLE
证书问题以及和adguard联合使用问题

### ISSUE THREAD

**Issue by TianYaDY** [Fndroid/clash_for_windows_pkg#1133]
adguard会安装自己的证书，但打开clash for windows后，chrome上显示的证书并非adguard CA，关闭CFW后正常。
由于证书问题，adguard很难和CFW一起联用，CFW一开启，adguard就失效。

**Comment by ous50** [comment]
我在adguard那边开了个issue，链接如下，大家可以过来看看AdguardTeam/AdguardFilters#62089

**Comment by kingforme** [comment]
1.在Adguard高级设置里打开“过滤localhost连接
2.在完成这项设置后，需要关闭Clash并重新打开才能生效，以后也都得保证Clash在Adguard之后运行(让adguard随系统启动)
3.禁用Block Teredo
![屏幕截图 2021-03-29 222001](https://user-images.githubusercontent.com/62692476/112851490-99f3dc80-90dd-11eb-99b1-8993e22cc7de.png)

按照上面的步骤设置完证书应该没有问题
