### ISSUE TITLE
Clash for windows 无法打开 system proxy 选项，其他的皆可正常开关

### ISSUE THREAD

**Issue by Mathinas** [Fndroid/clash_for_windows_pkg#1139]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (Win 10, V0.11.08)

**描述**

[//]: # (使用Clash 访问代理发现无法打开system proxy按钮)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'Clash'
2. 点击'General'
3. 拖动到'System proxy'
4. 触发问题

**预期行为**

[//]: # (能够正常打开system proxy)

**日志**

[//]: # (empty)

**截图**
![Snipaste_2020-09-16_10-27-50](https://user-images.githubusercontent.com/66516955/93285419-5d2e5b00-f807-11ea-87cb-ce3cb988d03f.jpg)

[//]: # (
![Snipaste_2020-09-16_10-26-01](https://user-images.githubusercontent.com/66516955/93285279-16d8fc00-f807-11ea-82e9-0882833eb1d7.jpg)
如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (找过群里的一些技术人员远程访问，说从没遇到过类似的问题，操作后问题依然存在)

**Comment by Fndroid** [comment]
Duplicate of #312

**Comment by Mathinas** [comment]
#312 是自动关闭或打开，我这个是完全无法打开，我认为是有一定的差异，所以重开了一个issue

**Comment by vinylalbum** [comment]
请问楼主现在解决这个问题了吗？我也是一样的问题，和#312的问题两码事

**Comment by vinylalbum** [comment]
> #312 是自动关闭或打开，我这个是完全无法打开，我认为是有一定的差异，所以重开了一个issue

请问楼主现在解决这个问题了吗？我也是一样的问题，和#312的问题两码事

**Comment by QiFong** [comment]
同样遇到这个问题了ssr和v2rayN都没有问题，只有CFW出现问题

**Comment by Pluto-123** [comment]
请问解决了，同样遇到了这个问题

**Comment by Pluto-123** [comment]
解决了吗。。？

**Comment by Mathinas** [comment]
没得办法，已经重装系统解决了

**Comment by Pluto-123** [comment]
好吧，谢谢

**Comment by jiayaoO3O** [comment]
同样问题

**Comment by yangbo620** [comment]
> 同样问题

我的解决了

**Comment by jiayaoO3O** [comment]
@csuyangbo 如何解决？？

**Comment by cangzihan** [comment]
我也遇到相同的问题，就是system proxy的按钮怎么点都打不开
后来换了个windows账户就好了。之前的账户是中文用户名，后换的是纯英文用户名，貌似是这个原因

**Comment by csuyangbo** [comment]
> @csuyangbo 如何解决？？

①打开注册表编辑器

②找到路径Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinHttpAutoProxySvc

③在右边找到一个名为Start的设置

④将她的值设置为2（2为自动启动）

⑤然后重新启动计算机

**Comment by jiayaoO3O** [comment]
@csuyangbo 
![image](https://user-images.githubusercontent.com/22891632/103594371-77658380-4f33-11eb-870a-3ee3fe85bd9d.png)
我怎么没有看到这个开关？要自己新建吗？

**Comment by jiayaoO3O** [comment]
@cangzihan 我本身就是英文用户名的，也失败了，估计不是这个原因

**Comment by yi-Xu-0100** [comment]
@jiayaoO3O 无法开关的话，给出 bypass 的内容，看看是不是格式有问题， 参考 #312 监控是哪个控制了这个

**Comment by csuyangbo** [comment]
> @csuyangbo
> ![image](https://user-images.githubusercontent.com/22891632/103594371-77658380-4f33-11eb-870a-3ee3fe85bd9d.png)
> 我怎么没有看到这个开关？要自己新建吗？

>我的这样打开有的  名为Start的设置；你的没有，那就不知道了
>

**Comment by jiayaoO3O** [comment]
@yi-Xu-0100 
![image](https://user-images.githubusercontent.com/22891632/103596931-02497c80-4f3a-11eb-999c-917e3a2c70f8.png)
我重启了电脑之后进行了监控, 左边是我的监控内容, 右边是bypass默认值, 下面是我的filter内容, 感觉还是没有谁设置了注册表的值
![image](https://user-images.githubusercontent.com/22891632/103597018-302ec100-4f3a-11eb-8a21-6be9136ccf26.png)

**Comment by yi-Xu-0100** [comment]
@jiayaoO3O 和 #312 对比图片查看键值变动，关闭 cfw 测试试试

**Comment by cangzihan** [comment]
> 
> 
> @cangzihan 我本身就是英文用户名的，也失败了，估计不是这个原因

我今天找到问题所在了，修改了我的原评论，你看一下

**Comment by jiayaoO3O** [comment]
@cangzihan 我删除了文件夹,还是打不开, v2rayN却又可以正常用

**Comment by jiayaoO3O** [comment]
![image](https://user-images.githubusercontent.com/22891632/103721780-86b70080-5009-11eb-9372-4bb3d22a890d.png)
我持续监控了这么久, 就只有两个程序进行了操作, 一个是v2rayN, 另一个是OneDrive的后台程序

**Comment by Mathinas** [comment]
通过#1105已解决问题，同样问题的可转至此 https://github.com/Fndroid/clash_for_windows_pkg/issues/1105

**Comment by jiayaoO3O** [comment]
@Mathinas @csuyangbo 好家伙, 终于解决了, 注意一点, 如果注册表不存在名为Start的设置, 直接手动新建一个就好了, 就是这个问题, 建议作者直接置顶这个解决方案 #1105

**Comment by jackieyiwu** [comment]
> @jiayaoO3O 无法开关的话，给出 bypass 的内容，看看是不是格式有问题， 参考 #312 监控是哪个控制了这个

的确是这个问题

**Comment by Rossby121** [comment]
刚教别人使用的时候也碰到了这个问题，其他开关都能用就是system那里不可以。然后我觉得应该是电脑网络代理的问题。打开设置之后查看电脑的网络代理是否开启，正好那台电脑是没有开代理的。手动开启代理，关闭clash然后重启电脑，再打开clash就能开关system了。
