### ISSUE TITLE
[BUG]策略组很多，第一次访问google就会很慢

### ISSUE THREAD

**Issue by madokaxiaoyuan** [Fndroid/clash_for_windows_pkg#114]
当我策略组很多时候，第一次访问google就会很慢，如果只要一个策略组不管任何时候访问Google都会很快，是我个人策略组问题吗，希望作者有时间能够回复下，谢谢

**Comment by Fndroid** [comment]
策略组多并不会影响访问速度。第一次访问慢可能只是因为DNS没有缓存，第一次结果被缓存了第二次就会更加快。

**Comment by madokaxiaoyuan** [comment]
当我关闭浏览器时候，再次打开浏览器访问google也会很慢

**Comment by LazyZhu** [comment]
这是所有Surge类代理都有的问题, 按策略组顺序匹配就是一个标准的[O(n)](http://bigocheatsheet.com/)算法时间复杂度, 随着规则增加而平均耗时也会增加.

解决方法:
1. 尽量把高匹配率规则放在最上面
2. 将同类规则采用改用更优的[O(log(n))](http://bigocheatsheet.com/)算法优化,参考此[patch](https://github.com/Dreamacro/clash/pull/90#issuecomment-483856877)

**Comment by Fndroid** [comment]
> 这是所有Surge类代理都有的问题, 按策略组顺序匹配就是一个标准的[O(n)](http://bigocheatsheet.com/)算法时间复杂度, 随着规则增加而平均耗时也会增加.
> 
> 解决方法:
> 1. 尽量把高匹配率规则放在最上面
> 2. 将同类规则改用更优的[O(log(n))](http://bigocheatsheet.com/)算法优化,参考此[patch](https://github.com/Dreamacro/clash/pull/90#issuecomment-483856877)

我跑了一下9k规则和1k规则不DNS解析的时候差别就是1ms和0ms。

至于这里说的策略组多和规则也没关吧
