### ISSUE TITLE
功能建议：像clashAndroid一样劫持全部dns流量

### ISSUE THREAD

**Issue by LittleRey** [Fndroid/clash_for_windows_pkg#1140]
**描述**
能不能劫持全部dns
像clashAndroid一样劫持全部dns流量，
在开启DoH并配置redir-host的情况下，使用国内节点，https://browserleaks.com/dns 测试出来的结果依然具有国内dns

DNS Leak Test
--
Test Results | Found 75 Servers, 5 ISP, 5 Locations
Your DNS Servers
IP Address : | ISP : | Location :
45.77.240.149 | AS-CHOOPA | Singapore, Singapore
67.215.80.18 | OPENDNS | Singapore, Singapore
67.215.80.64 | OPENDNS | Singapore, Singapore
67.215.80.65 | OPENDNS | Singapore, Singapore
67.215.80.66 | OPENDNS | Singapore, Singapore
67.215.80.67 | OPENDNS | Singapore, Singapore
67.215.80.68 | OPENDNS | Singapore, Singapore
67.215.80.69 | OPENDNS | Singapore, Singapore
67.215.80.70 | OPENDNS | Singapore, Singapore
67.215.80.71 | OPENDNS | Singapore, Singapore
67.215.80.72 | OPENDNS | Singapore, Singapore
67.215.80.73 | OPENDNS | Singapore, Singapore
67.215.80.74 | OPENDNS | Singapore, Singapore
67.215.80.75 | OPENDNS | Singapore, Singapore
67.215.80.77 | OPENDNS | Singapore, Singapore
172.253.4.1 | GOOGLE | Hong Kong, Central
172.253.4.2 | GOOGLE | Hong Kong, Central
172.253.4.3 | GOOGLE | Hong Kong, Central
172.253.4.4 | GOOGLE | Hong Kong, Central
172.253.4.5 | GOOGLE | Hong Kong, Central
172.253.5.1 | GOOGLE | Hong Kong, Central
172.253.5.2 | GOOGLE | Hong Kong, Central
172.253.5.3 | GOOGLE | Hong Kong, Central
172.253.5.4 | GOOGLE | Hong Kong, Central
172.253.5.5 | GOOGLE | Hong Kong, Central
172.253.6.1 | GOOGLE | Hong Kong, Central
172.253.6.2 | GOOGLE | Hong Kong, Central
172.253.6.3 | GOOGLE | Hong Kong, Central
172.253.6.4 | GOOGLE | Hong Kong, Central
172.253.6.5 | GOOGLE | Hong Kong, Central
172.253.237.1 | GOOGLE | Hong Kong, Central
172.253.237.2 | GOOGLE | Hong Kong, Central
172.253.237.3 | GOOGLE | Hong Kong, Central
172.253.237.4 | GOOGLE | Hong Kong, Central
172.253.237.5 | GOOGLE | Hong Kong, Central
172.69.32.32 | CLOUDFLARENET | United States, Los Angeles
202.102.214.6 | Chinanet | China
202.102.214.9 | Chinanet | China
207.148.124.236 | AS-CHOOPA | Singapore, Singapore
240e:46:4888:1:1:1:1:3 | Chinanet | China
240e:46:4888:1:1:1:1:13 | Chinanet | China
2001:19f0:4400:6edc:5400:2ff:fef4:9d91 | AS-CHOOPA | United States
2001:19f0:4400:613d:5400:2ff:fec5:2f3e | AS-CHOOPA | United States
2400:cb00:12:1024::ac45:2020 | CLOUDFLARENET | United States, Los Angeles
2404:6800:4005:c00::101 | GOOGLE | Hong Kong, Central
2404:6800:4005:c00::102 | GOOGLE | Hong Kong, Central
2404:6800:4005:c00::103 | GOOGLE | Hong Kong, Central
2404:6800:4005:c00::105 | GOOGLE | Hong Kong, Central
2404:6800:4005:c01::101 | GOOGLE | Hong Kong, Central
2404:6800:4005:c01::102 | GOOGLE | Hong Kong, Central
2404:6800:4005:c01::103 | GOOGLE | Hong Kong, Central
2404:6800:4005:c01::104 | GOOGLE | Hong Kong, Central
2404:6800:4005:c01::105 | GOOGLE | Hong Kong, Central
2404:6800:4005:c02::101 | GOOGLE | Hong Kong, Central
2404:6800:4005:c02::102 | GOOGLE | Hong Kong, Central
2404:6800:4005:c02::105 | GOOGLE | Hong Kong, Central
2404:6800:4005:c03::101 | GOOGLE | Hong Kong, Central
2404:6800:4005:c03::102 | GOOGLE | Hong Kong, Central
2404:6800:4005:c03::104 | GOOGLE | Hong Kong, Central
2620:0:cca:3::17 | OPENDNS | Singapore, Singapore
2620:0:cca:3::18 | OPENDNS | Singapore, Singapore
2620:0:cca::64 | OPENDNS | Singapore, Singapore
2620:0:cca::65 | OPENDNS | Singapore, Singapore
2620:0:cca::66 | OPENDNS | Singapore, Singapore
2620:0:cca::67 | OPENDNS | Singapore, Singapore
2620:0:cca::68 | OPENDNS | Singapore, Singapore
2620:0:cca::69 | OPENDNS | Singapore, Singapore
2620:0:cca::70 | OPENDNS | Singapore, Singapore
2620:0:cca::71 | OPENDNS | Singapore, Singapore
2620:0:cca::72 | OPENDNS | Singapore, Singapore
2620:0:cca::73 | OPENDNS | Singapore, Singapore
2620:0:cca::74 | OPENDNS | Singapore, Singapore
2620:0:cca::75 | OPENDNS | Singapore, Singapore
2620:0:cca::76 | OPENDNS | Singapore, Singapore
2620:0:cca::77 | OPENDNS | Singapore, Singapore

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/tap.html

**Comment by LittleRey** [comment]
尽管安装了tap,还是会解析出运营商的dns地址

**Comment by sfc9982** [comment]
关闭 Google Chrome 的 async-dns 试试？
