### ISSUE TITLE
关于hosts文件域名的处理

### ISSUE THREAD

**Issue by flydream3618** [Fndroid/clash_for_windows_pkg#1143]
**描述**
hosts文件里头的域名解析建议能直连，或加个【hosts域名直连】开/关，不然每次开启代理后，hosts里头的域名解析就废了

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/bypass.html

**Comment by flydream3618** [comment]
> https://docs.cfw.lbyczf.com/contents/bypass.html

谢谢，我知道这个，域名数量多就比较麻烦些~

我的意思是希望能自动加载hosts里头的域名，比较方便，因为这个软件看起来是闭源的，这也没法自行定制

**Comment by Fndroid** [comment]
不会考虑做这个。

不想一个个填可以写个脚本处理下。
