### ISSUE TITLE
自有服务器里开clash有没有这种可能，

### ISSUE THREAD

**Issue by fybiachi** [Fndroid/clash_for_windows_pkg#1145]
**描述**
比如有一台windows server r2的美国服务器 ，有没有可能在服务器上下载打开clash 然后 我的手机可以通过连接clash分享的端口（比如说 ALL LAN ;         来达到翻墙的目的？

**其他说明**
本人只是会想想，问问有这种可能嘛

**Comment by Fndroid** [comment]
有，但和你自己建一个socks5没差，而且clash所有功能你也没用到
