### ISSUE TITLE
[BUG]开机自启不能正确加载配置文件

### ISSUE THREAD

**Issue by dustofsoul** [Fndroid/clash_for_windows_pkg#115]
**Describe the bug**
开机自启后大概率(70%+)不能正确加载配置文件
**To Reproduce**
正常关机
启动系统

**Expected behavior**
所有配置文件变成和默认配置一样,手动切换后恢复正常
**Screenshots**

**Error Logs (located in HomeDirectory)**
```
// paste below this line
```

**Desktop (please complete the following information):**
 - OS: win10 1809 LTSB
 - Version 0.5.35

**Additional context**
同时小概率发生https://github.com/Fndroid/clash_for_windows_pkg/issues/95 的bug

**Comment by Fndroid** [comment]
恢复要时间，稍微等一下
