### ISSUE TITLE
将自定义域名添加到规则中,删除域名匹配,代理连接还显示规则分组

### ISSUE THREAD

**Issue by pertance** [Fndroid/clash_for_windows_pkg#1151]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
 win10  64位 

将自定义域名添加到规则中,删除域名匹配,代理连接还显示规则分组
以前不了解规则 将域名放在final中了

**预期行为**
 应该会走直连吧,配置了 bypass

![1](https://user-images.githubusercontent.com/35564076/93661231-cc66b200-fa88-11ea-9761-4ebc6cd836d6.jpg)
![2](https://user-images.githubusercontent.com/35564076/93661232-cd97df00-fa88-11ea-92d5-a0c58a9e5a46.png)
![3](https://user-images.githubusercontent.com/35564076/93661234-ce307580-fa88-11ea-9bcd-90300399c984.png)
![4](https://user-images.githubusercontent.com/35564076/93661236-ce307580-fa88-11ea-93ef-b2dfa584ad88.png)

**Comment by Fndroid** [comment]
需要重新开关 system proxy 选项

**Comment by pertance** [comment]
重新开启过了没用，clash都是更新的最新的

**Comment by Fndroid** [comment]
浏览器设置了代理吗？

有开TAP模式吗？

只用系统代理吗？
