### ISSUE TITLE
希望增加客户端profile模板功能

### ISSUE THREAD

**Issue by Iongtimenosee** [Fndroid/clash_for_windows_pkg#1153]
**描述**
各机场的profile配置各有差别，对一部分有细致要求的用户来说，每次更新profile都要自己再去修改来符合自己要求和使用习惯，很不方便。希望增加一个功能达以到这样的效果：更新profile时只刷新里面的服务器列表，所有其它的东西原封不动（这个原封不动的就是本地的固定的profile模板）。

现有便携模式是插入固定的本地自定代码，而profile模板功能是除服务器列表外，其它都是本地固定代码。希望考虑这部分有动手能力和本地细致要求的用户。

**Comment by yi-Xu-0100** [comment]
https://docs.cfw.lbyczf.com/contents/parser.html

**Comment by Fndroid** [comment]
节点和策略组和规则是耦合的

**Comment by Iongtimenosee** [comment]
> 节点和策略组和规则是耦合的

一般机场的profile配置没那么复杂和细致（要求必须由哪些服务器走哪个服务，这是极少数玩家关心的），都是比如笼统的整个列表统一选择指向，或手选单一服务器。所以我觉得功能能满足半数以上的使用场景都值得考虑。

在策略组规则中，可以用一种整个服务器列表替代标签方案，凡事出现某标签的地方，即替换成相应格式的整个服务器列表。这种方案简单好实现的同时，又满足数半数以上的场景。

**Comment by Iongtimenosee** [comment]
> 节点和策略组和规则是耦合的

需要替换整个服务器列表的，其实只有两个地方，一是 “Proxy:” 后面的完整列表，二是某些 “Proxy Group:” 类型比如 "url-test"，"load-balance" ，所以替换方案实现逻辑很简单，由用户自行决定即可，这种方案满足大多数场景。

**Comment by Fndroid** [comment]
第一，我不知道你说“半数以上”的数据哪里来的。

第二，即使99%的人用的是同一份规则模版，我也不会专门为这种模版去实现这种功能。

第三，如果你想实现读取自身模板进行替换等其他逻辑，可以用[配置文件预处理器](https://docs.cfw.lbyczf.com/contents/parser.html)实现。

**Comment by Iongtimenosee** [comment]
这种方案还有一大好处就是，以后还可以考虑扩张本程序的订阅类型、兼容性，比如v2ray,Trojan，只需弄个默认基本功能的profile配置模板，把v2ray,Trojan订阅更新进去就可以用，大大降低新手使用门槛，提高普及度。
