### ISSUE TITLE
关于profile模板配置的最后议题

### ISSUE THREAD

**Issue by Iongtimenosee** [Fndroid/clash_for_windows_pkg#1156]
知道大佬很忙，恕打扰。我不知道被关闭的issues还能否看到所以另开新的，如有打扰非常抱歉。

profile配置模板方案还有一大好处就是，可以扩张本程序的订阅类型、兼容性，比如v2ray,Trojan，只需弄个默认基本功能的profile配置模板，把v2ray,Trojan订阅更新进去就可以用，提高普及度，大大降低新手使用门槛。当然这对大佬来说可能根本就不屑。

还有关于表达方式的误解，之前说的“半数以上”的数据没有来源，并不是说全部用户中的半数，而是比喻能满足到大多数能使用到本地模板这种功能的人。

知道大佬背后无私奉献默默付出了很多东西，但我觉得也请仔细考虑并尊重为改进项目出谋划策的人的想法。说白了，cfw我也很久没使用了，用了其它更便捷的，这些功能更不更新我也根本不屑，何必冷言草草收场？我提意见是希望更优化本程序，方便用户使用和满足更多的场景，如果这点对本平台并不重要恕打扰。

**Comment by Fndroid** [comment]
> 我觉得也请仔细考虑并尊重为改进项目出谋划策的人的想法。

在上一个issue里不是已经针对你说的都说了我的看法和提供了解决办法吗？你怎么会认为我没有认真考虑？

**Comment by yi-Xu-0100** [comment]
1. 感觉这个是个人作品，非开源，在功能稳定后，没有太多时间处理更多的需求应理解，没必要有为了别人好的说法提要求后，没采纳就觉得被针对……
2. 给予回复了，为何**还**被认为是冷言相对？
3. 平台一说应该没有，作者没有任何社区讨论，这里的 issue 只提供 bug 反馈
4. 最后，现有配置预处理方法可处理的话，加功能可能没必要
5. 无关内容应该会被关闭，提意见可以，讨论可以，没必要解读态度，想法。
6. 个人建议，看看[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)
