### ISSUE TITLE
请求添加按节点名称筛选的功能

### ISSUE THREAD

**Issue by BlahDuckling747** [Fndroid/clash_for_windows_pkg#1158]
**描述**
希望在Proxies界面能够添加文本框，输入后只显示名称中包含这个文本作为子串/子序列的节点。

**其他说明**
无

**Comment by KOP-XIAO** [comment]
自行用parser功能实现

**Comment by AkariiinMKII** [comment]
![未标题-2](https://user-images.githubusercontent.com/6019344/94328371-9b383580-ffe4-11ea-882c-e63659013bf1.jpg)
是想要这种样子？

**Comment by Emphasia** [comment]
> ![未标题-2](https://user-images.githubusercontent.com/6019344/94328371-9b383580-ffe4-11ea-882c-e63659013bf1.jpg)
> 是想要这种样子？

请问这种筛选怎么用parser实现？必须用JS吗？

**Comment by AkariiinMKII** [comment]
> > ![未标题-2](https://user-images.githubusercontent.com/6019344/94328371-9b383580-ffe4-11ea-882c-e63659013bf1.jpg)
> > 是想要这种样子？
> 
> 请问这种筛选怎么用parser实现？必须用JS吗？

https://github.com/tindy2013/subconverter

**Comment by BlahDuckling747** [comment]
貌似已经加入这个功能很久了但是我还没有关闭issue（
谢谢F大
