### ISSUE TITLE
[BUG]非以太网打开系统代理无效

### ISSUE THREAD

**Issue by l4326769** [Fndroid/clash_for_windows_pkg#116]
在非以太网的情况下即在拨号网的情况下打开系统代理无效，可以正常打开，但是代理无效

**Comment by Fndroid** [comment]
单独为需要代理的软件设置http/socks5代理

**Comment by UntilNextTime** [comment]
> 单独为需要代理的软件设置http/socks5代理

那这个代理怎么设置呢？能详细讲讲吗？谢谢

**Comment by l4326769** [comment]
用proxycap或者proxifier这种可以对软件代理的软件，然后指向本地代理端口就行了




------------------ 原始邮件 ------------------
发件人: "UntilNextTime"<notifications@github.com>;
发送时间: 2019年6月8日(星期六) 中午1:48
收件人: "Fndroid/clash_for_windows_pkg"<clash_for_windows_pkg@noreply.github.com>;
抄送: "猛月★"<920274916@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Fndroid/clash_for_windows_pkg] [BUG]非以太网打开系统代理无效 (#116)



 
单独为需要代理的软件设置http/socks5代理
  
那这个代理怎么设置呢？能详细讲讲吗？谢谢

**Comment by UntilNextTime** [comment]
> 用proxycap或者proxifier这种可以对软件代理的软件，然后指向本地代理端口就行了
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "UntilNextTime"<notifications@github.com>; 发送时间: 2019年6月8日(星期六) 中午1:48 收件人: "Fndroid/clash_for_windows_pkg"<clash_for_windows_pkg@noreply.github.com>; 抄送: "猛月★"<920274916@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [Fndroid/clash_for_windows_pkg] [BUG]非以太网打开系统代理无效 (#116) 单独为需要代理的软件设置http/socks5代理 那这个代理怎么设置呢？能详细讲讲吗？谢谢 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

感谢
