### ISSUE TITLE
关于IPV6网络的兼容

### ISSUE THREAD

**Issue by CDCrystal** [Fndroid/clash_for_windows_pkg#1160]
**描述**
更新到0.11.9版本后发现IPV6流量会被代理，访问不了IPV6网络，请提供兼容IPV6访问的支持。

**Comment by Fndroid** [comment]
Duplicate of https://github.com/Fndroid/clash_for_windows_pkg/issues/933

**Comment by TeemoZhang-ice** [comment]
> Duplicate of #933

该网页404
