### ISSUE TITLE
从url导入后proxies无显示，只有1个灰块

### ISSUE THREAD

**Issue by angelyouyou** [Fndroid/clash_for_windows_pkg#1161]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**
v0.11.9
[//]: # (如果符合，请将``[ ]``改为``[x]``)

**系统**
v0.11.9
[//]: # (平台及版本号)
windows10 v2004

**描述**

从url导入后proxies无显示，只有1个灰块。

**复现**

[//]: # (请描述复现问题的步骤)

从url导入后proxies无显示，只有1个灰块。

**预期行为**
要有导入的代理节点列表。
[//]: # (清晰地描述期望看到的行为)

**日志**
![image](https://user-images.githubusercontent.com/12936259/93875754-2de88400-fd08-11ea-9eb7-35e954bc0a24.png)

[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/12936259/93875702-0ee9f200-fd08-11ea-99fe-513058dbda25.png)
![image](https://user-images.githubusercontent.com/12936259/93875710-13160f80-fd08-11ea-86cb-7f5933e6bb62.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
#1072 

查看配置是否未更新匹配新版 clash 规则
