### ISSUE TITLE
代理规则不能增加一个“用户级别”的规则配置吗？

### ISSUE THREAD

**Issue by lePig** [Fndroid/clash_for_windows_pkg#1162]
**描述**
就类似一个`config-user.yml`，现在在规则中增加一个域名强制走代理，然后更新后就自动消失了。虽然看了几个issue，有提到说配置文件预处理，但是看的还是有点不明白。
我期望的就是和“自定义系统代理Bypass”这个功能类似，但是是强制走{指定代理，比如GLOBAL,DIRECT等}的。扔几个域名进去就好了。

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
看不明白就再看看吧，解释肯定解释过很多次了
