### ISSUE TITLE
关于使用Mixin混合YAML的rules顺序的改进建议（Mixin不是为此而设计的，如需对配置文件预处理可使用Parsers）

### ISSUE THREAD

**Issue by xdzhu** [Fndroid/clash_for_windows_pkg#1163]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 10 2004, CFW版本 Clash.for.Windows-0.11.9-win

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
首先，经过我的测试，目前软件的Mixin功能在混合YAML配置文件时，关于rules的顺序为：原有的配置文件在上方，额外Mixin的配置在下方，而在判定域名规则时的顺序是从上到下的——这就是出现我的问题的原因。

接下来说我的具体场景。我使用Mixin功能，是为了解决在每次订阅更新之后，自定义的规则都会被更新的规则给覆盖掉的问题。

每次从我的订阅更新而来的配置文件的rules里面，原有的配置文件可以看作是下面这样的意思 ：

>  rules:
\- DOMAIN-KEYWORD,twitter,🚀 节点选择
   ... ...
\- DOMAIN-KEYWORD,google,🚀 节点选择
\- MATCH,🐟 漏网之鱼            \ \ \ \ \ \ \ 这是最后一行，意思是上面所有情况之外全部走"漏网之鱼"这个组的代理

由于这个订阅自带的rules会把我不希望走代理的一些网站也代理出去，所以想在Mixin里面指定直连这些域名，比如：

> mixin: #object
rules: 
\- DOMAIN-SUFFIX,kopernio.com,DIRECT
\- DOMAIN-SUFFIX,webofknowledge.com,DIRECT

而经过测试（测试时全部关闭了之前的连接，测试了很多情况，这一点我可以确认），仍旧无法直连这些网址，也就是说目前的关于rules这一块的规则判定顺序是：原有配置 >（漏网之鱼）> Mixin配置，但是在中间漏网之鱼这一步已经将后面Mixin里面的网址都划分进去了，导致后面续上的这些rules不生效。

**复现**

[//]: # (请描述复现问题的步骤)

按描述部分操作即可复现。

**其他说明**

[//]: # (其他补充内容)
在Profiles界面选择Edit Rules进行添加的自定义规则可以正常生效。经过使用Edit in text mode查看，可以发现添加的规则都在rules模块的最上方。这也是手动修改rules规则和目前的Mixin模式添加规则时候的不同点，正因如此，后者在面对部分rules时候（比如我的这种原始配置最后一行存在代理所有不在上面判定中的网址的），在最后面续上新的rules之后不生效。

**建议**

可以针对rules这个情况加个选项，让用户选择把Mixin配置加在最前面还是最后面。因为考虑到可能面对某些特定的rules时，没准加在最前面也会有一些错误。

辛苦开发者了！谢谢

**Comment by Fndroid** [comment]
mixin本来就不是设计给修改rules/proxies/proxy-groups的

**Comment by yi-Xu-0100** [comment]
> mixin 会对所有的订阅配置生效，而且结果保存在内存中，主要用于 dns 添加
> 可以试试 [配置文件预处理方法](https://docs.cfw.lbyczf.com/contents/parser.html)
> 我在 #1072 中给出了类似的适配旧规则的方法。方便对不同订阅生效，可以参考
> 该方法还可以用于自定义规则，可以参考我写的 [changeRule.js](https://github.com/yi-Xu-0100/Application-Lists/blob/master/Configuration/ClashForWindows/changeRule.js)

_Originally posted by @yi-Xu-0100 in https://github.com/Fndroid/clash_for_windows_pkg/issues/1092#issuecomment-683363919_

**Comment by xdzhu** [comment]
哇，回复的好快，感谢开发者。您这么一说让我想起来还有一个功能是Parsers，好像它可以实现！我去康康，谢谢

**Comment by xdzhu** [comment]
> > mixin 会对所有的订阅配置生效，而且结果保存在内存中，主要用于 dns 添加
> > 可以试试 [配置文件预处理方法](https://docs.cfw.lbyczf.com/contents/parser.html)
> > 我在 #1072 中给出了类似的适配旧规则的方法。方便对不同订阅生效，可以参考
> > 该方法还可以用于自定义规则，可以参考我写的 [changeRule.js](https://github.com/yi-Xu-0100/Application-Lists/blob/master/Configuration/ClashForWindows/changeRule.js)
> 
> _Originally posted by @yi-Xu-0100 in [#1092 (comment)](https://github.com/Fndroid/clash_for_windows_pkg/issues/1092#issuecomment-683363919)_

对，就是这个，我去看看，谢谢了

**Comment by Fndroid** [comment]
parser的新功能还没上线，但目前你可以用JavaScript实现

**Comment by Fndroid** [comment]
supported in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
