### ISSUE TITLE
昨天0.11.9正常，今天0.11.9不正常了，升级到0.11.10还是有问题。

### ISSUE THREAD

**Issue by heham** [Fndroid/clash_for_windows_pkg#1164]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ x] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
win10 2004 X 64
[//]: # (平台及版本号)

**描述**
昨天0.11.9正常，今天开机不正常，不能上网，同时general菜单里一直显示loading，手动升级到0.11.10general菜单显示正常，但是还是不能上网，软件里测试连接延迟正常显示延时，但是就是不能上网。只要开系统代理就什么都连不上，尝试关闭系统代理从浏览器代理插件连接仍然不行。尝试删除配置文件夹重新来仍然不行。
[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**
time="2020-09-25T07:56:06+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-09-25T07:56:06+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-09-25T07:56:06+08:00" level=error msg="Start Mixed(http and socks5) server error: listen tcp 127.0.0.1:7890: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2020-09-25T07:56:06+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-09-25T07:56:06+08:00" level=info msg="Start initial compatible provider Proxy"
[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by rambosir** [comment]
![image](https://user-images.githubusercontent.com/1431989/94233397-6a032b00-ff3a-11ea-8bc1-da4b18653e19.png)

**Comment by rambosir** [comment]
我升级到0.11.10也有问题

**Comment by rambosir** [comment]
> 我升级到0.11.10也有问题

![image](https://user-images.githubusercontent.com/1431989/94233436-7d15fb00-ff3a-11ea-9522-2b6a04144fdb.png)

**Comment by rambosir** [comment]
现在又好了。

**Comment by heham** [comment]
> 
> 
> 现在又好了。

神奇了，什么都没做，看到你的回复试了一下还真是好了

**Comment by Fndroid** [comment]
日志都说了是端口占用了，有什么神奇么？
