### ISSUE TITLE
昨日更新0.11.10后更新订阅报错

### ISSUE THREAD

**Issue by kdhr910** [Fndroid/clash_for_windows_pkg#1167]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ x] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)Windows 10 1909家庭版

**描述**

[//]: #更新订阅时切换下载的配置文件，然后报错Implicit map key need to be on a single line

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'Profiles'
2. 复制节点订阅链接并下载
3. 点击下载的配置信息
4. 触发问题

**预期行为**

[//]: # 成功切换节点信息

**日志**

[//]: # (上传触发问题对应的日志文件)

![-24c3c8905f730038](https://user-images.githubusercontent.com/71875099/94248813-94141780-ff51-11ea-9273-f356800f6ec6.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by AkariiinMKII** [comment]
profile去掉敏感内容发一下吧

**Comment by kdhr910** [comment]
> profile去掉敏感内容发一下吧

profiles里哪里去掉敏感内容啊

**Comment by AkariiinMKII** [comment]
> > profile去掉敏感内容发一下吧
> 
> profiles里哪里去掉敏感内容啊

浏览器里打开 编辑掉节点敏感信息

**Comment by Fndroid** [comment]
还原设置，重新下载配置。还不行，问你的服务商。
