### ISSUE TITLE
brew 源的 clash-for-windows 依然是老版本。

### ISSUE THREAD

**Issue by shunichio** [Fndroid/clash_for_windows_pkg#1171]
**描述**
brew 源的 clash-for-windows 依然是老版本。期望能够更新到最新版本，并且每次随着 github release 更新，更新到最新版本。

**其他说明**
![image](https://user-images.githubusercontent.com/23553358/94385285-51cc1f80-0177-11eb-8e5b-b02d47db06ad.png)

**Comment by Fndroid** [comment]
不是我维护的，我也没什么时间弄这个
