### ISSUE TITLE
mac版的订阅解析错误

### ISSUE THREAD

**Issue by ansemz** [Fndroid/clash_for_windows_pkg#1173]
mac版更新到0.11.10，下载订阅的url，但是没有任何信息被解析出来。看了一下yml文件，就是订阅地址的原文，没有解析成明文的。类似
dm1lc3M6Ly9ldzBLSUNBaWRpSTZJQ0l5SWl3TkNpQWdJbkJ6SWpvZ0l1bWZxZVdidlRFaUxBMEtJQ0FpWVdSa0lqb2dJbU5vYVc1aGFISXViV3dpTEEwS0lDQWljRzl5ZENJNklDSTBORE1pTEEwS0lDQWlhV1FpT2lBaU5EUmxaREUyWmpBdFptUTNNeTB4TVdWaExUaGhZalV0TlRZd01EQXlabUkwTjJVNUlpd05DaUFnSW1GcFpDSTZJQ0kwTmlJc0RRb2dJQ0p1WlhRaU9pQWlkM01pTEEwS0lDQWlkSGx3WlNJNklDSnViMjVsSWl3TkNpQWdJbWh2YzNRaU9pQWlZMmhwYm1Gb2NpNXRiQ0lzRFFvZ0lDSndZWFJvSWpvZ0lpOXVSalpsTjFwT1ZDOGlMQTBLSUNBaWRHeHpJam9nSW5Sc2N5SU5DbjA9CnZtZXNzOi8vZXcwS0lDQWlkaUk2SUNJeUlpd05DaUFnSW5Ceklqb2dJdVM2ak9

**Comment by Fndroid** [comment]
从来都不会解析这种格式
