### ISSUE TITLE
Latency Test URL 能不能改google啊？

### ISSUE THREAD

**Issue by blackshot-zard** [Fndroid/clash_for_windows_pkg#1176]
因为我发现用现有的url测试，不准，显示是600 800 甚至是1000MS
但是实际体验比现实200 300的要快，我手动改成了http://google.com
发现这个原本显示600ms的节点变成了130ms，其他所有节点也出现了延迟降低，但是基本都符合正常水平
唯有个别节点可能是用现有的URL测试会绕路，但是实际常用网站访问速度极快,会被误导！

**Comment by Fndroid** [comment]
测试的延迟只是参考，不是你改了url它就变快了

**Comment by blackshot-zard** [comment]
> 测试的延迟只是参考，不是你改了url它就变快了

是参考，但是参考测试的URL有误导性，有些地方的服务器到gstatic会绕路导致参考延迟变高，实际使用时并不访问gstatic，所以导致很多节点空闲，而我用google测试的话，就能看到这些节点的实际使用延迟

**Comment by blackshot-zard** [comment]
> 测试的延迟只是参考，不是你改了url它就变快了

节点A 香港HKT ，显示延迟是300MS

**Comment by blackshot-zard** [comment]
> 测试的延迟只是参考，不是你改了url它就变快了

例子
节点A香港hkt 显示延迟200ms
节点B香港ntt 显示延迟600ms
如果用自动选最低延迟的选法，肯定会选A，
但是A实际到谷歌的延迟是200，而B到谷歌的延迟却是130/所以B比A快但是软件不会自动选择B

**Comment by Fndroid** [comment]
所以不是已经允许你自己定义你想用的url了吗？

实际配置文件不是你自己写的吗，你写google.com就好了。

**Comment by blackshot-zard** [comment]
> 所以不是已经允许你自己定义你想用的url了吗？
> 
> 实际配置文件不是你自己写的吗，你写google.com就好了。

好吧，yaml配置文件写了是没用的，所以我才来这里提问题，没事，小事情^_^

**Comment by Fndroid** [comment]
写了当然有用，只是你在软件里测试的时候，不会读配置文件的，会读Settings里设置的

**Comment by blackshot-zard** [comment]
> 写了当然有用，只是你在软件里测试的时候，不会读配置文件的，会读Settings里设置的。自动测试的周期按配置文件里的。

soga OKOK！！！
