### ISSUE TITLE
Proxies 仅显示Shadowsocks,并且logs显示失败, 无法打开网页

### ISSUE THREAD

**Issue by Bruce-wong** [Fndroid/clash_for_windows_pkg#1177]
信息

- [ x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)windows10 1909
**描述**

[//]: # Proxies 仅显示Shadowsocks,并且logs显示失败, 无法打开网页

**复现**

**预期行为**

**日志**

**截图**
![image](https://user-images.githubusercontent.com/65887820/94513363-19007900-0251-11eb-95cf-b36a392dabb3.png)
![image](https://user-images.githubusercontent.com/65887820/94513373-21f14a80-0251-11eb-9559-b4ee6536ebdc.png)
![image](https://user-images.githubusercontent.com/65887820/94513391-2a498580-0251-11eb-89df-be44c1062bdf.png)

**Comment by Fndroid** [comment]
你导入配置了吗

**Comment by Bruce-wong** [comment]
> 你导入配置了吗

怎么导入？我对这个不太懂，麻烦指点，谢谢

**Comment by yi-Xu-0100** [comment]
> > 你导入配置了吗
> 
> 怎么导入？我对这个不太懂，麻烦指点，谢谢

https://docs.cfw.lbyczf.com/contents/quickstart.html#%E5%AF%BC%E5%85%A5%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/

**Comment by Bruce-wong** [comment]
> https://docs.cfw.lbyczf.com/

配置文件需要通过URL导入，但是URL怎么设置呢？
我尝试通过URL Scheme快速导入，但是显示错误。麻烦指点。

**Comment by yi-Xu-0100** [comment]
@Bruce-wong url 就是配置文件下载链接。
url 需要服务商提供，问问服务商有没有 clash 订阅链接。
或者你有配置文件，直接拖入就好。
有错误的话，就把错误截图发一下

**Comment by Bruce-wong** [comment]
> @Bruce-wong url 就是配置文件下载链接。
> url 需要服务商提供，问问服务商有没有 clash 订阅链接。
> 或者你有配置文件，直接拖入就好。
> 有错误的话，就把错误截图发一下

![image](https://user-images.githubusercontent.com/65887820/94529649-91286800-026c-11eb-82a0-e50646008ac0.png)

**Comment by yi-Xu-0100** [comment]
@Bruce-wong 找不到 dns 字段，你自己下载一下配置文件看看符不符合 clash 配置文件的格式和要求

**Comment by Bruce-wong** [comment]
> @Bruce-wong 找不到 dns 字段，你自己下载一下配置文件看看符不符合 clash 配置文件的格式和要求

这个订阅链接在浏览器输入之后没反应，下载不了，不知道什么问题.

**Comment by yi-Xu-0100** [comment]
> > @Bruce-wong 找不到 dns 字段，你自己下载一下配置文件看看符不符合 clash 配置文件的格式和要求
> 
> 这个订阅链接在浏览器输入之后没反应，下载不了，不知道什么问题.

@Bruce-wong  这个得问提供链接的服务商了。
