### ISSUE TITLE
[FR]为allowlan局域网共享代理设置密码

### ISSUE THREAD

**Issue by BuptBoyang** [Fndroid/clash_for_windows_pkg#118]
Allow Lan开启局域网共享，希望能为这个链接添加用户和密码

**Comment by Fndroid** [comment]
https://github.com/Dreamacro/clash/issues/101

**Comment by animagiq** [comment]
> Allow Lan开启局域网共享，希望能为这个链接添加用户和密码

你好 所以这个在cfw上怎么设置？看链接到core的源码没看懂 /(ㄒoㄒ)/~~

**Comment by yi-Xu-0100** [comment]
@animagiq 

![图片](https://user-images.githubusercontent.com/25523606/122348297-999d0c00-cf7d-11eb-9bd8-43a9d24fc461.png)

https://github.com/Dreamacro/clash/wiki/configuration

**Comment by HorrZzz** [comment]
![image](https://user-images.githubusercontent.com/42233737/184636987-81c3ec8e-6fcf-4dac-9d08-b30a895d16a8.png)
# 按照如图设置后，本机使用浏览器或者onedrive等软件，也都会弹窗让我输入“用户名:密码”
![image](https://user-images.githubusercontent.com/42233737/184637288-28dc4c72-436e-4cbb-9be2-e7bc0ab06999.png)
# 有没有可以排除本机ip需要用户名和密码的设置？
# 如果有，麻烦给个示例，感谢！

**Comment by basaltfiber** [comment]
> ![image](https://user-images.githubusercontent.com/42233737/184636987-81c3ec8e-6fcf-4dac-9d08-b30a895d16a8.png)
> 
> # 按照如图设置后，本机使用浏览器或者onedrive等软件，也都会弹窗让我输入“用户名:密码”
> ![image](https://user-images.githubusercontent.com/42233737/184637288-28dc4c72-436e-4cbb-9be2-e7bc0ab06999.png)
> 
> # 有没有可以排除本机ip需要用户名和密码的设置？
> # 如果有，麻烦给个示例，感谢！
请教一下 这是在哪里改的？
