### ISSUE TITLE
软件UI看起来有点小问题

### ISSUE THREAD

**Issue by AduitSSH** [Fndroid/clash_for_windows_pkg#1180]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 20H1

**描述**

界面UI异常

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'General'
2. 点击'TAP Device'
4. 触发问题

**截图**

![QQ截图20200930150631](https://user-images.githubusercontent.com/50974047/94654097-2855f400-032f-11eb-90f0-6a1097781b1c.png)

**Comment by AduitSSH** [comment]
软件为最新的v0.12.0

**Comment by isArtJay** [comment]
+1

**Comment by Fndroid** [comment]
失误了😂，重新传了

**Comment by Fndroid** [comment]
应该好了，再试试

**Comment by AduitSSH** [comment]
验证过了 这回可以了
