### ISSUE TITLE
 更新最新版本后开启系统代理会导致所有网页打不开

### ISSUE THREAD

**Issue by dollyp123** [Fndroid/clash_for_windows_pkg#1184]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Window 7  旗舰版 Service pack 1
**描述**

[//]: # (请具体并清楚地描述遇到的问题)
开启系统代理后无论选择Global/Rule/Direct模式均会导致所有浏览器不能浏览任何网页，关闭系统代理后即刻恢复。
**复现**

[//]: # (请描述复现问题的步骤)

1. 开启系统代理
2. 无法浏览网页
3.关闭系统代理
4.可以正常浏览网页

**预期行为**

[//]: # (清晰地描述期望看到的行为)
正常连接网页
**日志**

[//]: # (上传触发问题对应的日志文件)
![image](https://user-images.githubusercontent.com/72136324/94680308-1f2b4e00-0354-11eb-95be-64cfa4625530.png)

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/72136324/94680414-47b34800-0354-11eb-8f4d-8751f98e832c.png)

**其他说明**

[//]: # (其他补充内容)
日志里所有的内容都是那一段的重复，另一issue里提到的set http_proxy=http://127.0.0.1:7890 & set https_proxy=http://127.0.0.1:7890也使用过了，但是无效

**Comment by Fndroid** [comment]
系统代理无法联网，可以在settings的system proxy type改成HTTP，默认的HTTPS+SOCKS5有问题，下个版本修复

**Comment by ichimei** [comment]
> 系统代理无法联网，可以在settings的system proxy type改成HTTP，默认的HTTPS+SOCKS5有问题，下个版本修复

我这边多次尝试发现是纯 HTTP 网站均无法访问，但 HTTPS 则均可以，不知是不是同一个问题。确实 Type 改为 HTTP 即可修复。

**Comment by chencl0214** [comment]
系统代理开启后打不开网页的原因
![EWI5`Q @1V1R){UFSIU9)LB](https://user-images.githubusercontent.com/24311314/95012501-ae45a800-066b-11eb-9b62-bb439026a3b2.png)

**Comment by Macyrate** [comment]
> 系统代理开启后打不开网页的原因
> ![EWI5`Q @1V1R){UFSIU9)LB](https://user-images.githubusercontent.com/24311314/95012501-ae45a800-066b-11eb-9b62-bb439026a3b2.png)

[](https://sm.ms/image/3ytz9hQJngVSNei)

改成这样就OK了

**Comment by AkariiinMKII** [comment]
> > 系统代理开启后打不开网页的原因
> > ![EWI5`Q @1V1R){UFSIU9)LB](https://user-images.githubusercontent.com/24311314/95012501-ae45a800-066b-11eb-9b62-bb439026a3b2.png)
> 
> ![屏幕截图 2020-10-04 205217.png](https://camo.githubusercontent.com/ac1261433330b55fa47e29e83a511d70a47b36a8/68747470733a2f2f692e6c6f6c692e6e65742f323032302f31302f30342f3379747a3968514a6e6756534e65692e706e67)
> 
> 改成这样就OK了，不过重启之后可能又会变回去，很难受……

https://github.com/Fndroid/clash_for_windows_pkg/issues/1184#issuecomment-701404519

**Comment by ChuGary** [comment]
我也有同样的问题，改完之后可以，但是重启之后又失效了

**Comment by sigang88** [comment]
> **信息**
> 
> * [x]  已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
> * [x]  已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
> * [x]  已经尝试更新到最新版本，问题依旧存在
> * [x]  软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）
> 
> **系统**
> 
> Window 7 旗舰版 Service pack 1
> **描述**
> 
> 开启系统代理后无论选择Global/Rule/Direct模式均会导致所有浏览器不能浏览任何网页，关闭系统代理后即刻恢复。
> **复现**
> 
> 1. 开启系统代理
> 2. 无法浏览网页
>    3.关闭系统代理
>    4.可以正常浏览网页
> 
> **预期行为**
> 
> 正常连接网页
> **日志**
> 
> ![image](https://user-images.githubusercontent.com/72136324/94680308-1f2b4e00-0354-11eb-95be-64cfa4625530.png)
> 
> **截图**
> 
> ![image](https://user-images.githubusercontent.com/72136324/94680414-47b34800-0354-11eb-8f4d-8751f98e832c.png)
> 
> **其他说明**
> 
> 日志里所有的内容都是那一段的重复，另一issue里提到的set http_proxy=http://127.0.0.1:7890 & set https_proxy=[http://127.0.0.1:7890也使用过了，但是无效](http://127.0.0.1:7890%E4%B9%9F%E4%BD%BF%E7%94%A8%E8%BF%87%E4%BA%86%EF%BC%8C%E4%BD%86%E6%98%AF%E6%97%A0%E6%95%88)

确实如此，换成http后正常

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases

**Comment by CPCer** [comment]
12.1 目前好像还是有这个问题，听说13有allow lan的问题……暂时不更新了
