### ISSUE TITLE
0.12.0看虎牙直播弹幕加载不出来 以前的版本可以

### ISSUE THREAD

**Issue by Qing15** [Fndroid/clash_for_windows_pkg#1186]

**Comment by Fndroid** [comment]
系统代理无法联网，可以在settings的system proxy type改成HTTP，默认的HTTPS+SOCKS5有问题，下个版本修复

**Comment by xiaochency** [comment]
我说咋上不了这么多网站啊

**Comment by WenseRainy** [comment]
对 我也是这个问题

**Comment by ILuckyPig** [comment]
我这边也是

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
