### ISSUE TITLE
升级到最新0.12.0，clash无法正常工作，网页打不开，换成0.11.10，就没任何问题，是配置文件需要更改么？

### ISSUE THREAD

**Issue by aqbjqtd** [Fndroid/clash_for_windows_pkg#1187]
[//]: # (如不按模版填写，则issue将被直接关闭)

升级到最新0.12.0，clash无法正常工作，网页打不开，换成上一个版本，就没任何问题，是配置文件需要更改么？

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

win10 2004 64

[//]: # (平台及版本号)

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

升级到最新0.12.0，clash无法正常工作，网页打不开，换成上一个版本，就没任何问题，是配置文件需要更改么？

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/1184#issuecomment-701404519
