### ISSUE TITLE
v0.11.10 UI 问题：弹出更新提示时未遮挡原主页面 Mixin 旁 ℹ 图标

### ISSUE THREAD

**Issue by john-jane-doe** [Fndroid/clash_for_windows_pkg#1188]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ ] 已经尝试更新到最新版本，问题依旧存在 *（没有比 v0.12.0 更新的 CFW 版本，使用 v0.12.0 无从复现，无法确定问题是否依旧存在）*
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
- Windows 10
- Clash for Windows v0.11.10

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

主页面点击版本号旁边的 `New` 弹出更新提示时，背后主页面 Mixin 旁的 ℹ 没有被遮挡，如下图红框中所示

![capture](https://user-images.githubusercontent.com/62677758/94768320-b12d6800-03e1-11eb-8d6e-a806c8caab12.png)

**复现**

[//]: # (请描述复现问题的步骤)

1. 安装并使用上个版本 Clash for Windows **v0.11.10**
2. 等待其检测到新版本，在版本号旁显示 `New`，点击 `New` 弹出更新提示
3. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)
ℹ 图标应该被遮挡

**日志**

[//]: # (上传触发问题对应的日志文件)
N/A

**截图**

[//]: # (如果可以，请提供对应问题的截图)
如上

**其他说明**

[//]: # (其他补充内容)
N/A

**Comment by Fndroid** [comment]
最新版已经修复了
