### ISSUE TITLE
请支持32位系统

### ISSUE THREAD

**Issue by liyafe1997** [Fndroid/clash_for_windows_pkg#1189]
**描述**
如题，Electron编译成32位，再把32位的clash打包进去应该不是个事儿吧？不支持32位只会给32位系统用户带来不便，不是每个地方都方便换系统的，例如公司的电脑，老机器等。

**Comment by AkariiinMKII** [comment]
造成不便了真是对不起哦，要我劝开发者来给你道歉吗？
