### ISSUE TITLE
使用EnableLoopback时的问题

### ISSUE THREAD

**Issue by hellozehai** [Fndroid/clash_for_windows_pkg#119]
在general界面点击EnableLoopback打开此功能时，提示如下错误：
A Loopback exemption exists for SID:
S-1-15-2-3624051433-21525758914-......（后面一大串）
but no AppContainer with that SID could be found.
Warn if other orphaned exemptions are found in this session?
请问是怎么回事？我哪里设置错误了吗？
非常感谢~

**Comment by Fndroid** [comment]
注册表有冗余的信息，忽略即可

**Comment by haomuch** [comment]
> 注册表有冗余的信息，忽略即可

怎么样可以清除这个注册表冗余呢？每次打开都弹出真的很烦

**Comment by onemisaka** [comment]
这个问题应该是之前代理了某个uwp应用，后来这个uwp应用卸载导致软件找不到这个应用。解决方法：打开uwp loopback，点击refresh，然后exempt none，保存，最后exempt all保存。

**Comment by cancundeyingzi** [comment]
> 这个问题应该是之前代理了某个uwp应用，后来这个uwp应用卸载导致软件找不到这个应用。解决方法：打开uwp loopback，点击refresh，然后exempt none，保存，最后exempt all保存。

但是软件依旧不生效

**Comment by xingkei** [comment]
Perfect, my issue is adressed by the above method.

**Comment by xingkei** [comment]
> 这个问题应该是之前代理了某个uwp应用，后来这个uwp应用卸载导致软件找不到这个应用。解决方法：打开uwp loopback，点击refresh，然后exempt none，保存，最后exempt all保存。

似乎不能解决这个问题。

**Comment by reoLantern** [comment]
> 这个问题应该是之前代理了某个uwp应用，后来这个uwp应用卸载导致软件找不到这个应用。解决方法：打开uwp loopback，点击refresh，然后exempt none，保存，最后exempt all保存。

我通过这个问题解决了，感谢

**Comment by reoLantern** [comment]
> 这个问题应该是之前代理了某个uwp应用，后来这个uwp应用卸载导致软件找不到这个应用。解决方法：打开uwp loopback，点击refresh，然后exempt none，保存，最后exempt all保存。

我通过这个方法解决了，感谢

**Comment by cccpism** [comment]
我有一个新的问题，就是有个uwp应用在豁免，刷新之后依然显示为未豁免。我不明白该怎么解决这个问题？

**Comment by thdai2000** [comment]
> > 这个问题应该是之前代理了某个uwp应用，后来这个uwp应用卸载导致软件找不到这个应用。解决方法：打开uwp loopback，点击refresh，然后exempt none，保存，最后exempt all保存。
> 
> 但是软件依旧不生效

试试看重启一下
