### ISSUE TITLE
希望可以添加中文支持

### ISSUE THREAD

**Issue by wsay-kx99** [Fndroid/clash_for_windows_pkg#1190]
尊敬的开发者，您好：
  我是一名来自中国的用户。

  由于英文不是特别好，使用此软件时会比较吃力。甚至有很多时候因为英文看不懂，会导致很多错误的操作，希望可以增加中国语言的支持。

  此致

**Comment by BlueCat0** [comment]
单就CFW来说，用到的英文不超过100个单词

**Comment by yi-Xu-0100** [comment]
#999 类似问题已回复

**Comment by wsay-kx99** [comment]
> 单就CFW来说，用到的英语不超过100个单词

但是这100个单词..我都不会，太难了。

**Comment by Mosaic67** [comment]
https://github.com/BoyceLig/Clash_Chinese_Patch

**Comment by mxy493** [comment]
可以用这个 https://github.com/BoyceLig/Clash_Chinese_Patch
