### ISSUE TITLE
0.12.0版本 WSS协议无法通过cfw？

### ISSUE THREAD

**Issue by IceLitty** [Fndroid/clash_for_windows_pkg#1191]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 10 2004 19041.508

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
在从0.11.10版本更新至0.12.0版本后，Discord桌面应用无法进入

**复现**

[//]: # (请描述复现问题的步骤)
Discord桌面应用可以使用Ctrl+Shift+i打开控制台，以相同配置文件更新完cfw后，discord表示 `wss://gateway.discord.gg/?encoding=etf&v=8&compress=zlib-stream` 始终处于pending状态，而回退cfw版本后，则能直接成功访问该url。
相关规则：`DOMAIN-SUFFIX,discord.gg,基本代理`

**预期行为**

[//]: # (清晰地描述期望看到的行为)
能够成功访问

**日志**

[//]: # (上传触发问题对应的日志文件)
time="2020-10-02T15:54:22+08:00" level=info msg="[TCP] 127.0.0.1:13054 --> gateway.discord.gg match DomainSuffix(discord.gg) using 基本代理[上海 - 香港 Pro (0.5 倍率) #Daily #Asia]"
time="2020-10-02T16:06:29+08:00" level=info msg="[TCP] 127.0.0.1:14739 --> gateway.discord.gg match DomainSuffix(discord.gg) using 基本代理[TCP: IEPL 华南 - 香港 B #Premium #Asia]"
不同节点均有clash日志记录

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)
不知道该如何确认是cfw问题/clash core问题，但是能确认是因为我本次的cfw升级操作导致的异常，其他环境均未手动更改过，会是更新clash core导致wss协议访问有异常导致的吗？

**Comment by Fndroid** [comment]
系统代理无法联网，可以在settings的system proxy type改成HTTP，默认的HTTPS+SOCKS5有问题，下个版本修复

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases

**Comment by chawyehsu** [comment]
Still encounter the issue after update CFW to version 0.12.1, I'm using HTTP mode of system proxy, nothing of CFW configurations I've changed, the WSS protocol is pending forever.

use case: `wss://edge-chat.instagram.com/chat` in instagram.com
