### ISSUE TITLE
当使用global模式的时候本地host会失效

### ISSUE THREAD

**Issue by UlysessWeb** [Fndroid/clash_for_windows_pkg#1192]
**描述**
当CFW使用global模式全局代理的时候会使本地host失效，需要手动添加域名到bypass domain里面才行，个人认为global模式的时候不应该绕过本地host，或能能否添加一个功能将host中的域名一键添加到bypass domain

**Comment by Fndroid** [comment]
1. 配置文件不设置dns，则自动使用系统dns解析，包括hosts
2. hosts解析的IP地址依然会匹配规则
