### ISSUE TITLE
线程注入动作

### ISSUE THREAD

**Issue by KevinCLiu** [Fndroid/clash_for_windows_pkg#1194]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [X] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [X] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [X] 已经尝试更新到最新版本，问题依旧存在
- [X] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # windows 10

**描述**

[//]: v0.12 版本，正常使用两天后，防火墙拦截一项操作
时间	操作	说明	次数
  2020-10-02 21:45:30	  [已允许]	  远程线程注入	  防护 1 次
详细描述：
进程：C:\WINDOWS\System32\cmd.exe
动作：远程线程注入
路径：C:\WINDOWS\System32\ROUTE.EXE
风险文件：C:\Program Files\Clash for Windows\Clash for Windows.exe
防护信息: AD|30, 10, -1||

请问这是什么操作

**Comment by Fndroid** [comment]
> 进程：C:\WINDOWS\System32\cmd.exe

因为调用了cmd执行命令
