### ISSUE TITLE
可能导致国内网站无法解析访问

### ISSUE THREAD

**Issue by tlerbao** [Fndroid/clash_for_windows_pkg#1197]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 10 2004
Clash For Windows v0.12.0
 
**描述**

[//]: # (请具体并清楚地描述遇到的问题)
不确定是不是最新这个版本开始出现的，导致国内个别网站无法解析
不是所有国内网站都这样，个别网站，如jd.com mi.com taobao.com都出现过
一开始以为是我本地dns的问题，更改了几次后发现问题依旧
随后测试关闭clash，就可以访问了，关闭系统代理也是可以
我都是RULE模式，为何会影响到国内网站呢

**复现**

[//]: # (请描述复现问题的步骤)

访问个别网站如jd.com 导致无法访问。

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
Duplicate of #1184
