### ISSUE TITLE
macOS dark tray icon when using dark mode.

### ISSUE THREAD

**Issue by zanderzhng** [Fndroid/clash_for_windows_pkg#1199]
**描述**
black icon instead of white icon. (in dark mode)

<img width="150" alt="Screen Shot 2020-10-04 at 22 01 24" src="https://user-images.githubusercontent.com/867749/95017632-2a041c80-068d-11eb-947b-9683cbcfe1c2.png">

**其他说明**
n/a

**Comment by zanderzhng** [comment]
I found the tray color setting so I will close this request but I think it worth set the color default black for all users.

**Comment by Fndroid** [comment]
There's no Electron API to get the tray color in Big Sur, so setting the color manually is a temporary workaround.

**Comment by Fndroid** [comment]
> it worth setting the color to black by default for all users

By the way, tray icon color might change to white if you change your wallpaper.
