### ISSUE TITLE
Proxies 不显示内容

### ISSUE THREAD

**Issue by wsyh-He** [Fndroid/clash_for_windows_pkg#120]
更新完 v0.5.30以后的版本 PROXIES栏目就不显示内容了，只有灰色的小方块，0.5.30版是正常的。另0.5.30以后的版本System Proxy选项也经常点选不了 start with windows倒是没问题。

**Comment by wsyh-He** [comment]
运行环境WIN10 64BIT

**Comment by Fndroid** [comment]
1. Proxies不显示，到Profiles里面来回切换一下配置文件看看能不能切换
2. System Proxy需要读写注册表，检查是否有其他安全工具禁止此类操作

**Comment by anC8899** [comment]
更新到0.6.2出现这个问题 Proxies 里面为空 背景显示小方块。重新安装、删除config均无效。Profiles 里的配置文件也无法切换。

**Comment by Fndroid** [comment]
@anC8899 如果 General 没有显示错误的话，说明 config.yml 没有问题，Profiles里无法切换说明对应的配置文件有错，理论上应该有通知提示，按照提示修改

**Comment by anC8899** [comment]
@Fndroid 感谢回复，我找到问题了。是我增加了一个 vmess  但 AlterId 为空导致的。

**Comment by Mrgro** [comment]
机场有一键托管
但是出现了问题
Could not switch to this proflie!
yaml: line 1062: did not find expected key 
软件版本：0.7.7

**Comment by Fndroid** [comment]
@Mrgro 配置文件格式问题

**Comment by Mrgro** [comment]
那请问我该怎么解决呢
让机场主解决吗？

Fndroid <notifications@github.com> 于2019年9月7日周六 下午6:49写道：

**Comment by Fndroid** [comment]
@Mrgro 是

**Comment by LING15205** [comment]
同问一下……
