### ISSUE TITLE
无法载入profiles

### ISSUE THREAD

**Issue by Zorteph** [Fndroid/clash_for_windows_pkg#121]
下载配置文件后出现无法切换的问题，显示
proxy [7]: cannot parse 'port' as int: strconv.Parselnt: parsing " ": invalid syntax
并且只在我的一台笔记本上出现该问题，另一台台式机上没有任何配置问题可正常使用，尝试切换admin账户或手动更改端口都不可行，请问是什么原因，谢谢！

**Comment by Fndroid** [comment]
检查一下配置文件的第八个代理是不是没有写端口号，下载回来的都不能保证是一样的

**Comment by Zorteph** [comment]
不知您指的第八个代理是哪个，但是我对比了一下两台电脑的config.yml文件没有什么不一样的地方

**Comment by Zorteph** [comment]
不知配置文件可否手动拷贝？我想试试从我可以用的那台电脑上拷贝到不能用的本上试试看，如果是您说的下载出了问题，那我想这样应该可以解决吧。麻烦了！

**Comment by Fndroid** [comment]
Profiles里面点那个铅笔图案就能文本编辑配置文件

**Comment by Zorteph** [comment]
将能正常使用的那台电脑的config、list和代理的文件全部拷到不能用的那台电脑上就好了，看来是我用的梯子他们的托管出了问题。麻烦您了！
