### ISSUE TITLE
0.12.00 代理异常，http代理无法自动配置

### ISSUE THREAD

**Issue by leafsoul365** [Fndroid/clash_for_windows_pkg#1211]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

win10

**描述**
0.12.00 代理异常，http代理无法自动配置。开启代理后，查看IE-Internet选项-连接-局域网设置项，代理页面显示不正常，点击代理的高级选项，进入后发现“http”代理项空白，没有自动填入代理地址。导致http网站、程序无法访问网络。
手动在http栏填入地址，正常。
使用0.11.10版本，正常。

**复现**

IE-Internet选项-连接-局域网设置-代理服务器 项-高级

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by leafsoul365** [comment]
![Snipaste_2020-10-08_17-59-29.jpg](https://user-images.githubusercontent.com/46679575/95450377-ca618600-0998-11eb-8739-07eb6a9f7391.jpg)
![Snipaste_2020-10-08_17-59-16.jpg](https://user-images.githubusercontent.com/46679575/95450401-d51c1b00-0998-11eb-9f3b-4abcdd050441.jpg)

**Comment by MagicSnake0503** [comment]
![1](https://user-images.githubusercontent.com/14107999/95456636-372d4e00-09a2-11eb-999a-b895132920f9.png)
![2](https://user-images.githubusercontent.com/14107999/95456643-3b596b80-09a2-11eb-96ed-1606392dfd26.png)
不能用地址每次开机都需要手动修改

**Comment by Fndroid** [comment]
Duplicate of #1184
