### ISSUE TITLE
clash v 0.12.0无法访问国内网站，但低于v 0.12.0的版本都没有问题

### ISSUE THREAD

**Issue by ggshuini** [Fndroid/clash_for_windows_pkg#1213]
[//]: # (如不按模版填写，则issue将被直接关闭)

clash v 0.12.0无法访问国内网站

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

windows 2019

**描述**

clash v 0.12.0无法访问国内网站

**复现**

[//]: # (请描述复现问题的步骤)

无

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by mxdg** [comment]
同样遇到。比如这个网站：http://ip111.cn/

**Comment by Arowa-Z** [comment]
同样的问题。比如百度翻译和谷歌翻译：https://fanyi.baidu.com/ 、https://translate.google.cn/

**Comment by windyshower** [comment]
#1184

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
