### ISSUE TITLE
12.1 版本 SOCKS5 代理模式不能使用了？

### ISSUE THREAD

**Issue by iBug** [Fndroid/clash_for_windows_pkg#1215]
**信息**

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本（0.12.1），问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Win10 19041.508

**描述**

HTTP 模式下所有应用程序无法使用 SOCKS5 代理模式，只能使用 HTTP 代理模式

**复现**

随便使用任何程序，在代理设置中填入 CFW 显示的端口，并将代理模式设置为 SOCKS5，连接失败

**预期行为**

Clash 的 HTTP/SOCKS5 复合端口下两种代理模式都能正常使用

**Comment by iamqiwei** [comment]
socks5没有问题吧，是scoks4不行吧
