### ISSUE TITLE
求助，关于clash开机项的问题！！！

### ISSUE THREAD

**Issue by zhihan526** [Fndroid/clash_for_windows_pkg#1217]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [xx] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在https://docs.cfw.lbyczf.com/)
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[/win10 64 家庭版/]: # (平台及版本号)

**描述**

[/我打开了ssystem proxy 和 start with windows 但是还是不能启动开机项/]:

我尝试去任务管理器，去注册表，去启动文件夹。但是都不管用。

![image](https://user-images.githubusercontent.com/61249030/95555966-21bd3000-0a45-11eb-9a2c-b97872591a93.png)

![image](https://user-images.githubusercontent.com/61249030/95556004-300b4c00-0a45-11eb-96a7-bca4736ab550.png)

![image](https://user-images.githubusercontent.com/61249030/95556298-b32ca200-0a45-11eb-8d00-aab6fe5fba9b.png)

![image](https://user-images.githubusercontent.com/61249030/95556332-be7fcd80-0a45-11eb-8dab-ac5b1a633739.png)

求助！！！

**Comment by yi-Xu-0100** [comment]
@zhihan526 注册表的值，看起来没加引号
启动项的快捷方式看起来也是指向不对

**Comment by zhihan526** [comment]
![image](https://user-images.githubusercontent.com/61249030/95561366-3a314880-0a4d-11eb-9308-b0d833e07098.png)

是这样吗，快捷方式不知道怎么改欸。 @yi-Xu-0100

**Comment by yi-Xu-0100** [comment]
@zhihan526 我不知道 clash for windows 设置的那个注册表项目，建议不要修改注册表，你就去启动里面看看就好。

![a](https://user-images.githubusercontent.com/61249030/95556298-b32ca200-0a45-11eb-8d00-aab6fe5fba9b.png)

你这两个条目，右键看看有没有属性或者打开文件所在位置，看看有没有指向

**Comment by yi-Xu-0100** [comment]
我翻了下我的注册表，条目在 `计算机\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`, 貌似没有引号也行……

![image](https://user-images.githubusercontent.com/25523606/95563047-81203d80-0a4f-11eb-8805-61ca8bbcc566.png)

**Comment by yi-Xu-0100** [comment]
建议自己设置的内容最好都删掉，然后启动软件设置 start with windows ，然后刷新注册表，看看这个条目是否有增加。@zhihan526

**Comment by zhihan526** [comment]
有指向的。
![image](https://user-images.githubusercontent.com/61249030/95563543-18859080-0a50-11eb-8e42-f9fe7a405c4f.png)


那个注册表我删除了，然后重新打开ClashX start with windows以后，并没有在注册表里 /哭
![image](https://user-images.githubusercontent.com/61249030/95563732-626e7680-0a50-11eb-9dbe-7af27f05f4c7.png)
@yi-Xu-0100

**Comment by yi-Xu-0100** [comment]
@zhihan526 你的注册表路径有问题，不一样的

![image](https://user-images.githubusercontent.com/25523606/95574685-fbf15480-0a5f-11eb-864e-e5f84a02a8dc.png)

这里的文件是否有问题，感觉没有后缀，也没显示出来图标

**Comment by zhihan526** [comment]
对的，看起来怪怪的，但是点进去和正常图标没什么区别。

您觉得我需要怎么修改呢？

**Comment by zhihan526** [comment]
我通过重命名Clash for Windows到Clash for Windows.exe。增加了应用程序后缀名，并且重新创建了新的快捷方式，把新的快捷方式拉到启动文件夹里面解决了问题！！！
