### ISSUE TITLE
开启system proxy后Windows apps无法正常连接网络

### ISSUE THREAD

**Issue by waynerockss** [Fndroid/clash_for_windows_pkg#122]
Windows 10 v1803
勾选System Proxy之后windows apps无法连接网络；在Internet Options-LAN Settings里面把Proxy Server清除，Windows apps恢复正常联网，但Clash的System Proxy也自动消失

**Comment by Fndroid** [comment]
Windows APP指的是商店里的UWP吗

**Comment by waynerockss** [comment]
是的

**Comment by Fndroid** [comment]
UWP默认不走127.0.0.1本地代理，General里面的EnableLoopback.exe勾选一下可以解除限制

**Comment by waynerockss** [comment]
解决了，谢谢！
