### ISSUE TITLE
google 学术 无法打开

### ISSUE THREAD

**Issue by yunhaiyisx** [Fndroid/clash_for_windows_pkg#1225]
Google 学术提示
“系统检测到您的计算机网络发出了异常流量”
如果我们发现您网络中的设备可能正自动向 Google 发送流量，则您可能会看到以下消息：“系统检测到您的计算机网络发出了异常流量”。

此类拦截可能与您使用的虚拟专用网 (VPN) 浏览器插件或程序有关。您可以尝试从计算机或网络中卸载 VPN，然后看看是否奏效。

部分 VPN 会发送违反法律或违反网站服务条款的流量。如果您是互联网服务提供商 (ISP)，请向用户说明为何应卸载此类 VPN。当滥用流量停止进入 Google 的网络后，我们会自动取消拦截之前发送滥用流量的 IP/ISP。

**Comment by Fndroid** [comment]
节点问题
