### ISSUE TITLE
任务栏图标右键菜单中，ProxyMode与实际不对应？

### ISSUE THREAD

**Issue by Emphasia** [Fndroid/clash_for_windows_pkg#1229]
**信息**

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 1909
CFW 0.11.10

**描述**

任务栏图标右键菜单中，ProxyMode与实际不对应？

**复现**

1. 右键任务栏图标

**预期行为**

任务栏图标右键菜单中，ProxyMode与实际对应。

**截图**

![20201012112921](https://user-images.githubusercontent.com/8478234/95702207-451eef80-0c7e-11eb-96ee-350e24db4e6a.png)

**Comment by Fndroid** [comment]
在菜单还是APP里切换了Mode呢？
