### ISSUE TITLE
Clash使用期间无法使用Outlook和OneNote

### ISSUE THREAD

**Issue by MrDecadence** [Fndroid/clash_for_windows_pkg#123]
最近发现使用Clash for windows时，outlook链接错误，OneNote也有同样的问题。

关掉clash后问题自动解决了。

请问有人也遇到这种情况吗？知道是什么原因吗？

**Comment by MrDecadence** [comment]
补充一下：

1、如果先连接outlook和OneNote，再连接Clash就没问题，可以照常使用。

2、若先连接Clash，则会出现outlook和OneNote无法连接的情况，此时重复1可解决问题。

但请问这个是bug？还是其他原因？SS和SSR未遇到过这种问题。

**Comment by zcluo** [comment]
有个loop什么的里面勾上就可以用

发自我的 iPhone

**Comment by MrDecadence** [comment]
请问这个设置在哪里？没找到

**Comment by MrDecadence** [comment]
> 有个loop什么的里面勾上就可以用 发自我的 iPhone
> […](#)
> 在 2019年6月7日，下午9:05，MrDecadence ***@***.***> 写道： 补充一下： 1、如果先连接outlook和OneNote，再连接Clash就没问题，可以照常使用。 2、若先连接Clash，则会出现outlook和OneNote无法连接的情况，此时重复1可解决问题。 但请问这个是bug？还是其他原因？SS和SSR未遇到过这种问题。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

请问这个设置在哪里？没找到

**Comment by Fndroid** [comment]
General里面EnableLoopback.exe

**Comment by MrDecadence** [comment]
> General里面EnableLoopback.exe

噢可以了，非常感谢！！！！！！！！！！！

**Comment by HonorWater** [comment]
我也面对了这个问题，outlook在打开Clash一段时间后无法使用，必须关掉重新打开。上面的loopback解决了onenote的问题，但是outlook在loopback中找不到，也尝试了打勾了office及其他有outlook关键词的进程，还是无法彻底解决。。

**Comment by Jas0nma0915** [comment]
> 我也面对了这个问题，outlook在打开Clash一段时间后无法使用，必须关掉重新打开。上面的loopback解决了onenote的问题，但是outlook在loopback中找不到，也尝试了打勾了office及其他有outlook关键词的进程，还是无法彻底解决。。

同样遇到这个问题，加了规则也没用，时好时坏的。

**Comment by yangyangoceanographer** [comment]
> > 我也面对了这个问题，outlook在打开Clash一段时间后无法使用，必须关掉重新打开。上面的loopback解决了onenote的问题，但是outlook在loopback中找不到，也尝试了打勾了office及其他有outlook关键词的进程，还是无法彻底解决。。
> 
> 同样遇到这个问题，加了规则也没用，时好时坏的。

me too

**Comment by yangyangoceanographer** [comment]
> > 我也面对了这个问题，outlook在打开Clash一段时间后无法使用，必须关掉重新打开。上面的loopback解决了onenote的问题，但是outlook在loopback中找不到，也尝试了打勾了office及其他有outlook关键词的进程，还是无法彻底解决。。
> 
> 同样遇到这个问题，加了规则也没用，时好时坏的。

@Fndroid 没有解决方案吗？我下载了其他邮箱客户端测试了一下在clash打开时收发gmail正常，唯独outlook时好时坏，这到底是咋回事呢？

**Comment by GOUKI9999** [comment]
> > > 我也面对了这个问题，outlook在打开Clash一段时间后无法使用，必须关掉重新打开。上面的loopback解决了onenote的问题，但是outlook在loopback中找不到，也尝试了打勾了office及其他有outlook关键词的进程，还是无法彻底解决。。
> > 
> > 
> > 同样遇到这个问题，加了规则也没用，时好时坏的。
> 
> me too

相同问题，loopback作为常规操作没有漏掉，但outlook完全无法使用呈脱机状态，甚至于通过proxifier加入规则也不行（代理outlook.exe的全部流量，并通过预设值的本机代理clash进行转发）

**Comment by pzgz** [comment]
> > > > 我也面对了这个问题，outlook在打开Clash一段时间后无法使用，必须关掉重新打开。上面的loopback解决了onenote的问题，但是outlook在loopback中找不到，也尝试了打勾了office及其他有outlook关键词的进程，还是无法彻底解决。。
> > > 
> > > 
> > > 同样遇到这个问题，加了规则也没用，时好时坏的。
> > 
> > 
> > me too
> 
> 相同问题，loopback作为常规操作没有漏掉，但outlook完全无法使用呈脱机状态，甚至于通过proxifier加入规则也不行（代理outlook.exe的全部流量，并通过预设值的本机代理clash进行转发）

我是在Teams内碰到了经常断连或者重新登录不上的情况，在自带的UWP EnableLoop里面没法找到Teams，不过我看到一个工作或学校账户，然后我把这个勾上了，目前能用

**Comment by truthciao** [comment]
> 我也面对了这个问题，outlook在打开Clash一段时间后无法使用，必须关掉重新打开。上面的loopback解决了onenote的问题，但是outlook在loopback中找不到，也尝试了打勾了office及其他有outlook关键词的进程，还是无法彻底解决。。

outlook应该是邮件和日历or电子邮件和账户，我都勾了测试可以同步

**Comment by wicatfly** [comment]
> 
> 
> 我也面对了这个问题，outlook在打开Clash一段时间后无法使用，必须关掉重新打开。上面的loopback解决了onenote的问题，但是outlook在loopback中找不到，也尝试了打勾了office及其他有outlook关键词的进程，还是无法彻底解决。。

相同问题,loopback中找不到outlook

**Comment by monkeysui** [comment]
我是 office 无法登陆，在 loopback 里全选之后解决的

**Comment by wicatfly** [comment]
我也全选了 但是 loopback 列表里没有出现 office
2021年2月24日 +0800 10:17 monkeysui <notifications@github.com>，写道：

**Comment by monkeysui** [comment]
> 我也全选了 但是 loopback 列表里没有出现 office 2021年2月24日 +0800 10:17 monkeysui <notifications@github.com>，写道：
> […](#)
> 我是 office 无法登陆，在 loopback 里全选之后解决的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我也是没有，但全选保存之后再登陆却可以了

**Comment by wicatfly** [comment]
好的 感谢
2021年2月24日 +0800 11:26 monkeysui <notifications@github.com>，写道：

**Comment by w1ndy** [comment]
office 365相关服务要是全走代理的话国内用户可能会出现下载不了、登录不上等问题（或许跟梯子位置有关），关闭代理下载or登录后再打开即可

**Comment by jaychou315** [comment]
> 我也全选了 但是 loopback 列表里没有出现 office 2021年2月24日 +0800 10:17 monkeysui <notifications@github.com>，写道：
> […](#)
> 我是 office 无法登陆，在 loopback 里全选之后解决的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

还有全选这一招,感谢,我勾选了office和Onenote for win10 登录不了,全选之后能上了!!!!后来仔细看了一下应该是学校和工作帐户和我的帐户这两项勾选就行了.因为我的onenote是用的校园邮箱,必须要勾选这两个

**Comment by yypboy** [comment]
> General里面EnableLoopback.exe

他感谢了！！！困扰我很久了这个 问题

**Comment by LyndonWu233** [comment]
> > 我也全选了 但是 loopback 列表里没有出现 office 2021年2月24日 +0800 10:17 monkeysui [notifications@github.com](mailto:notifications@github.com)，写道：
> > […](#)
> > 我是 office 无法登陆，在 loopback 里全选之后解决的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 还有全选这一招,感谢,我勾选了office和Onenote for win10 登录不了,全选之后能上了!!!!后来仔细看了一下应该是学校和工作帐户和我的帐户这两项勾选就行了.因为我的onenote是用的校园邮箱,必须要勾选这两个

是的，很感谢这个贴子。

**Comment by rxzzz** [comment]
> > > 我也全选了 但是 loopback 列表里没有出现 office 2021年2月24日 +0800 10:17 monkeysui [notifications@github.com](mailto:notifications@github.com)，写道：
> > > […](#)
> > > 我是 office 无法登陆，在 loopback 里全选之后解决的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 还有全选这一招,感谢,我勾选了office和Onenote for win10 登录不了,全选之后能上了!!!!后来仔细看了一下应该是学校和工作帐户和我的帐户这两项勾选就行了.因为我的onenote是用的校园邮箱,必须要勾选这两个
> 
> 是的，很感谢这个贴子。

你好，请问你现在可以正常使用Outlook了吗？我Exempt all了尝试用outlook登录gmail，还是显示无法连接pop/imap服务器。

**Comment by Ardor-Wu** [comment]
我outlook能用，但是它不走代理，导致gmail用不了

**Comment by megamindsam** [comment]
点击 general里面的 UMP Loopback右边的launch helper，下拉到OneNote一栏勾选前面的框框，再点击页面上面的save changes，解决

**Comment by Ardor-Wu** [comment]
之前已经勾选了，现在发现还是不行

**Comment by SvenAugustus** [comment]
thx

**Comment by zzflybird** [comment]
thx

**Comment by xcl-net** [comment]
![Snipaste_2022-09-05_10-29-28](https://user-images.githubusercontent.com/15728845/188350185-2dc9846f-1690-41b9-a766-dce90c3f1a16.png)
setting clash for windows app, just like this!

**Comment by verigle** [comment]
只有上面操作没有用，
关闭TUN模式
开启 系统代理才可以

**Comment by oryjk** [comment]
我试了一下，打开UWP应用网络回环，然后勾选所有之后，微软相关的app可以连接了，但是我觉得这个不是解决这个问题最好的办法，所以想问一下是否有一套配置去过滤掉所有的微软相关的app，使得微软的app不用代理

**Comment by fredericky123** [comment]
> 我试了一下，打开UWP应用网络回环，然后勾选所有之后，微软相关的app可以连接了，但是我觉得这个不是解决这个问题最好的办法，所以想问一下是否有一套配置去过滤掉所有的微软相关的app，使得微软的app不用代理

我只勾选了”你的账户“和”工作和学校账户“可以用

**Comment by luke396** [comment]
> 在linux下没有这个UWP网络回环，同样是开了代理后thunderbird连接邮箱不行，在设置中去掉代理可以正常接收邮件。仅仅使用直连也不行。
> 
> ![Screenshot from 2022-12-12 11-09-02](https://user-images.githubusercontent.com/48241450/206952643-35d21501-8fbf-4055-8deb-5fae79a5666c.png)

thunderbird的设置可以直接搜索设置代理，手动配置一下代理或许可以。

![image](https://user-images.githubusercontent.com/77875500/210070711-0ed2c961-c91e-452d-b7fc-7b491753588d.png)


![image](https://user-images.githubusercontent.com/77875500/210070674-f4dcb2b3-d803-41d3-875d-1a7ff3685ddd.png)

**Comment by Xiwen-Lu** [comment]
> > 在linux下没有这个UWP网络回环，同样是开了代理后thunderbird连接邮箱不行，在设置中去掉代理可以正常接收邮件。仅仅使用直连也不行。
> > ![Screenshot from 2022-12-12 11-09-02](https://user-images.githubusercontent.com/48241450/206952643-35d21501-8fbf-4055-8deb-5fae79a5666c.png)
> 
> thunderbird的设置可以直接搜索设置代理，手动配置一下代理或许可以。
> 
> ![image](https://user-images.githubusercontent.com/77875500/210070711-0ed2c961-c91e-452d-b7fc-7b491753588d.png)
> 
> ![image](https://user-images.githubusercontent.com/77875500/210070674-f4dcb2b3-d803-41d3-875d-1a7ff3685ddd.png)

感谢！之前不知道在thunderbird中可以设置网络代理，经过提示以及根据之前测试的情况后，在thunderbird中取消使用代理后，邮箱可以正常使用了，感谢！

**Comment by NHypocrite** [comment]
> 只有上面操作没有用，关闭TUN模式，开启系统代理才可以

感谢！同样微软系应用（OneNote，Office）显示无Internet，打开UWP应用网络回环并勾选所有之后仍不行，
关闭了TUN模式就能够连接了

**Comment by itneedme** [comment]
勾选microsoft.windows.authhost.b_8那一项，我就可以了。

**Comment by Mr-xzq** [comment]
> > 我试了一下，打开UWP应用网络回环，然后勾选所有之后，微软相关的app可以连接了，但是我觉得这个不是解决这个问题最好的办法，所以想问一下是否有一套配置去过滤掉所有的微软相关的app，使得微软的app不用代理
> 
> 我只勾选了”你的账户“和”工作和学校账户“可以用

我也是这样就可以了，不用开启 TUN 模式之类的，只用在 uwp loopback（网络应用回环）中勾选"你的账户:，"工作和学校账户" 这两项即可，然后你就可以正常使用 teams 或者 outlook 了

**Comment by dxf1995** [comment]
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/21004361/7b4bfc43-a50e-48a2-905b-41842d3ea4c9)

今天刚验证，这样outlook是可以使用的。

**Comment by thew7rst** [comment]
感谢这个帖子的同志们，问题终于解决了

**Comment by 1191681612** [comment]
> 感谢这个帖子的同志们，问题终于解决了

怎么解决的

**Comment by ttimasdf** [comment]
除了 Office 相关的那几个，把这俩应用给配置上就行了，不用把所有安全功能全关了，不合适

```
Your account	Microsoft.Windows.CloudExperienceHost_cw5n1h2txyewy
Work or school account	Microsoft.AAD.BrokerPlugin_cw5n1h2txyewy
```

**Comment by forwells** [comment]
##勾选这里然后save changes!
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/32950945/3a6d4842-0f4e-4632-93e8-cba4f389d1dc)
