### ISSUE TITLE
parsers中 file跟yaml 同时存在的问题

### ISSUE THREAD

**Issue by convictss** [Fndroid/clash_for_windows_pkg#1234]
**描述**
如图，我有两个订阅，同时针对每个订阅的都生成一个新的proxy-group: ☣ OnlyUSA
suba:
![image](https://user-images.githubusercontent.com/39207692/95999536-800f5780-0e25-11eb-8518-cad47868e542.png)

subb:
![image](https://user-images.githubusercontent.com/39207692/95999563-89002900-0e25-11eb-9078-226032d9117d.png)

然后通过parsers进行处理器配置，目的是无论选择哪个订阅，都想要让指定网站进入 ☣ OnlyUSA这个 proxy-group，如 census.gov 域名下都进入 ☣ OnlyUSA这个 proxy-group
![image](https://user-images.githubusercontent.com/39207692/95999893-df6d6780-0e25-11eb-8e73-2b38cef3785c.png)

但发现指定了file之后，yaml处指定的内容就不再生效，生成的配置文件件也并没有包含yaml下指定的内容，只生成了 file里面的内容。

**其他说明**
是否 parsers不允许file跟yaml共存，或者说只能按照顺序要么前面是file则file生效，前面是yaml则yaml生效呢？

**Comment by convictss** [comment]
@Fndroid 
如果按照这样写的话，便是一个url对应一批的自定义规则，但我现在是多个url，且多个url都已经预处理一个统一的proxy-group，其他域名都是走自定义的proxy-group，如按你所发的写法，则需要重复定义yaml或者fiile

`parsers：
  - url: http://t.dev
    yaml:
      append-rules:
        - xxx
  - url: http://t.dev
    yaml:
      append-rules:
        - xxx`
`parsers：
  - url: http://t.dev
    file: b.yaml
  - url: http://t.dev
    file: b.yaml`

但如果是多个订阅但要配置通用规则的话，更好的处理方式或许应该类似于：
`parsers：
  - yaml:
  	append-rules:
      - xxx
      - xxx
  - url: http://t1.dev
  - url: http://t2.dev`
`parsers：
  - file: b.yaml
  - url: http://t1.dev
  - url: http://t2.dev`

**Comment by Fndroid** [comment]
建议稍微了解一点JavaScript和yaml语法再探讨这个问题

**Comment by convictss** [comment]
/笑哭 抱歉，yml语法用得有误，但大体上的意思就是多订阅节点情况下，需要统一处理自定义规则（无论是yml还是js），但就目前来讲，是需要重复去配置的

**Comment by yi-Xu-0100** [comment]
@convictss 可以用正则

**Comment by Fndroid** [comment]
重不重复都是相对的。

每个url都定义多个file或者yaml实际上也会重复，只是重复的从url变成了file或者yaml。

而且对正则匹配逻辑不友好，更不灵活了。

**Comment by convictss** [comment]
@yi-Xu-0100 @Fndroid 
感谢提出的方法与自上而下的列表处理方式的解答，点拨思维，现parsers配置如下，可以实现对多个订阅统一进行配置自定义规则，配置如下：

**Comment by convictss** [comment]
直接粘贴也挺奇怪的...还是贴个图
![image](https://user-images.githubusercontent.com/39207692/96087849-1c555f00-0ef7-11eb-9d3c-2251223f033c.png)

**Comment by convictss** [comment]
@yi-Xu-0100 @Fndroid 
再次感谢！ 此issue 结束
