### ISSUE TITLE
开发者好鸭！我想要abcdefg.com 这个网址通过特定的节点代理应该怎么做呢？

### ISSUE THREAD

**Issue by DereenMec** [Fndroid/clash_for_windows_pkg#1236]
**描述**
我想再任何profile，以及profile更新后，都使abcdefg.com 这个网址通过特定的节点代理应该怎么做呢？我注意到了mixin功能，于是我打开了mixin，然后再settings里面的mixin->yaml文件中添加了以下内容：
![image](https://user-images.githubusercontent.com/36854639/96077433-5ec07100-0ee2-11eb-97d8-abc7fc5a72a0.png)
但是，经过测试，这样的配置破坏了我的所有域名代理规则。
**其他说明**

```
rules:
   - DOMAIN-SUFFIX,iwara.tv,🇺🇸 美国WII3[x0.6|AZ|智能入口|V2Ray]
   - DOMAIN-SUFFIX,bt.byr.cn,DIRECT
```
我希望这三行只替换掉原配置文件中的`rules:`字段，但是其显然替换掉了`rules:`及其包含的所有规则。

**Comment by yi-Xu-0100** [comment]
用 parser，文档：https://docs.cfw.lbyczf.com/contents/parser.html

**Comment by DereenMec** [comment]
> 用 parser，文档：https://docs.cfw.lbyczf.com/contents/parser.html

阿里嘎多！已解决问题！
