### ISSUE TITLE
原本正常可用的配置文件，在新添加了一个节点后就不能使用了，提示 password 'expected type' string

### ISSUE THREAD

**Issue by akw5454521** [Fndroid/clash_for_windows_pkg#1239]
- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Win7 64bit

**描述**
之前使用的CFW版本是v0.11.1，配置文件里vmess和trojan节点都有，本来用的没有问题，后来为了排查Win7蓝屏原因的问题，暂时转用ClashWeb，配置文件也搬过去了。在这期间我新搭建了一个trojan节点，正常添加进了配置文件，ClashWeb和CFA都是正常使用的。现在准备换回CFW，于是导入了更新后的配置文件，点击启用后提示错误，如下面截图
节点肯定是没问题的，配置文件的语法编辑也没问题，之前也有能用的trojan节点，都是一样的格式

**复现**
换了台电脑，Win10，CFW版本是v 0.11.3，一样的问题
升级最新版v 0.12.1，也是一样的问题
但只要删掉这个最新的节点，就没有任何问题

**预期行为**
配置文件正常可用

**日志**
因为配置文件没法正常启用，故log中没有相关项

**截图**
![捕获](https://user-images.githubusercontent.com/68607321/96158003-9a405700-0f45-11eb-9a79-2968fc9f2064.PNG)

**其他说明**
附上节点的配置文件

- name: "AWS"
  type: trojan
  server: aaa.bbb.com
  port: 443
  password: 12345678
  udp: true

**Comment by Fndroid** [comment]
```
password: "1234567"
```

**Comment by akw5454521** [comment]
> ```
> password: "1234567"
> ```

感谢，问题已解决。另外能问下为啥其他trojan节点和ss节点的密码都可以不用双引吗……

**Comment by Fndroid** [comment]
https://yaml.org/spec/1.2/spec.html#id2805071
