### ISSUE TITLE
Logs窗口log数量过多会导致软件卡顿

### ISSUE THREAD

**Issue by Ericir3** [Fndroid/clash_for_windows_pkg#1240]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Win10 2004 19041.508

[//]: # (平台及版本号)

**描述**
长时间打开Logs窗口，log数量过多会导致软件卡顿，清除log后恢复正常

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 打开Logs窗口等待积攒一定数量的log
2. 触发问题，软件卡顿
3. 点击clear清除log即可恢复正常

**预期行为**
这不算一个很严重的问题，卡顿也无妨，不卡顿最好

[//]: # (清晰地描述期望看到的行为)

**日志**
暂无

[//]: # (上传触发问题对应的日志文件)

**截图**
暂无

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**
暂无

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
Logs其实目的是短时的观察和调试日志，不建议长时间留在这个页面，因为日志文件已经保存在本地了，点左下角文字可以看到
