### ISSUE TITLE
程序出现白屏

### ISSUE THREAD

**Issue by ITHcc** [Fndroid/clash_for_windows_pkg#1242]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 专业版 64-bit (10.0, Build 18362) (18362.19h1_release.190318-1202)

**描述**

程序打开就白屏卡死，无法点击拖拽等，只能force quit退出

**复现**
打开就是白屏

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/37447321/96207066-e2d72f00-0f9c-11eb-9ba3-ee9e3907346d.png)

**其他说明**

之前是正常的，突然就成这样了，已尝试删除User下的配置文件、更换程序版本都没有解决。

**Comment by Fndroid** [comment]
试试删除``C:\Users\<username>\AppData\Roaming``目录下``clash_win``及``Clash for Windows``两个文件夹，再重启app

**Comment by ITHcc** [comment]
> 试试删除`C:\Users\<username>\AppData\Roaming`目录下`clash_win`及`Clash for Windows`两个文件夹，再重启app

不行，删除以后重启app还是一样。之后我又卸载重装了下还是一样

**Comment by wolvth** [comment]
我也是打开白屏半天，显示后也卡的要死，经常假死状态。删除卸载都试过没有用。和这个问题一样https://github.com/Fndroid/clash_for_windows_pkg/issues/1267

**Comment by DingXiangYuanZhiXing** [comment]
@wolvth @ITHcc 尝试清除 `~/.config/log` 也没有用么？

**Comment by ITHcc** [comment]
> @wolvth @ITHcc尝试清除`~/.config/log`也。没有用么？

没用

**Comment by AcquireKnown** [comment]
这个问题还没有解决啊!咋整?

**Comment by ITHcc** [comment]
#442 问题已解决

**Comment by tina2114** [comment]
> #442 问题已解决

你好，请问是怎么解决的

**Comment by JakeGanada** [comment]
我也出现过，后来发现文件路径上有个文件夹名字里有符号，把符号去掉，保证路径全英文就好了
