### ISSUE TITLE
新版clash如何开启socks5代理？

### ISSUE THREAD

**Issue by hac425xxx** [Fndroid/clash_for_windows_pkg#1244]
新版的好像没有了设置socks5代理的选项

**Comment by yi-Xu-0100** [comment]
socks 的端口和 http 的端口一致，直接使用就行

**Comment by Fndroid** [comment]
界面中的Port就是HTTP+SOCKS5的混合

**Comment by rexhang** [comment]
### 直接使用混合端口就行，http+socks的端口

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/14832793/1dbb0ee9-f7b7-48b9-95a4-5ad5d4f08cbc)
