### ISSUE TITLE
请求添加Clash for windows on arm

### ISSUE THREAD

**Issue by Zaxlear** [Fndroid/clash_for_windows_pkg#1245]
**描述**
请具体并清楚地描述期望功能及期望的效果
请求添加适用arm架构的Clash for Windows，身边有windows on arm设备，无法使用clash，一直觉得clash很好用，希望作者做一个。
**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
ARM短期内估计是没有的了，但是32位的在测试了。有TG账户吗，发个给你试试？

**Comment by Zaxlear** [comment]
> ARM短期内估计是没有的了，但是32位的在测试了。有TG账户吗，发个给你试试？

有的，我把tg账户私发到您的邮箱吗？

**Comment by Fndroid** [comment]
> 有的，我把tg账户私发到您的邮箱吗？

可以

**Comment by xuanyunhui** [comment]
@Fndroid 哪里可以clone代码？想测试build一下arm架构的

**Comment by ryoumaruko** [comment]
> ARM=，[32][T3]，？

请问可以给发一份32位的吗，Windows10 on ARM装不上64位

**Comment by ryoumaruko** [comment]
> ARM短期内估计是没有的了，但是32位的在测试了。有TG账户吗，发个给你试试？

请问可以给发一份32位的吗，Windows10 on ARM装不上64位

**Comment by Fndroid** [comment]
@ryoumaruko release里下载

**Comment by yuiring** [comment]
出于某些需求，我也需要一个安装在m1的macbook上的windows虚拟机下可用的clash，但是目前x86和arm的发布似乎都不能用
