### ISSUE TITLE
安装clash在不开启代理的情况下无法访问google翻译

### ISSUE THREAD

**Issue by yizg20** [Fndroid/clash_for_windows_pkg#1246]
求解决方法，网页翻译不能用了...

**Comment by yi-Xu-0100** [comment]
emmm, 需要加配置文件。
如果不知道配置文件，和所谓的节点，服务商，订阅链接啥的。
建议问服务商，如果不知道服务商，建议不使用。🤐

**Comment by yizg20** [comment]
> emmm，需要加配置文件。
> 如果不知道配置文件，和所谓的例程，服务商，订阅链接啥的。
> 建议问服务商，如果不知道服务商，建议不使用。🤐

配置文件我设置了两个节点连接正常。
我想我需要用这台电脑连接其他的网络（联通）测试是否是网络原因造成的
谢谢你的回复

**Comment by yi-Xu-0100** [comment]
@yizg20 单独的某个网站无法访问，可能与 dns，配置规则，有关，也有可能官方网站那个时段崩溃。
Google 翻译的话，有官方的对应的镜像站：<https://translate.google.cn/> 可以使用。
如果不是完全无法连接，可能与软件本身的关系不大，与个人配置相关度更高。

**Comment by yizg20** [comment]
> Google翻译的话，有官方的对应的相应站点：[https](https://translate.google.cn/) ://translate.google.cn/可以/ @ yizg20单独的某个网站无法访问，可能与dns，配置规则，有关，也有可能官方网站那个调度崩溃。使用。
> 如果不是完全无法连接，可能与软件本身的关系不大，与个人配置相关度更高。

今天上午10点左右的时候还不能访问，现在可以访问了，可能是运营商的锅，我什么都没有设置，奇葩的问题
谢谢
