### ISSUE TITLE
希望添加一个流量统计功能，外加一个随时重置统计的，

### ISSUE THREAD

**Issue by Rem1x-2019** [Fndroid/clash_for_windows_pkg#125]
希望添加一个流量统计功能，外加一个随时重置统计的，
这样如果国内有网站走了代理路线，可以及时发现并且加入直连列表，
或者知道这条线路流量用了多少，快完的时候可以切换线路，

**Comment by Fndroid** [comment]
这只能在core里实现 https://github.com/Dreamacro/clash
