### ISSUE TITLE
Windows 網卡切換

### ISSUE THREAD

**Issue by GOODTESTA** [Fndroid/clash_for_windows_pkg#1254]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [X] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [X] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [X] 已经尝试更新到最新版本，问题依旧存在
- [X] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Win 10 1909

**描述**

Windows下TAP的切换

目前TAP下对应区域网路LAN名称为WLAN
所以设置interface-name：WLAN

然而笔电上时常扭曲有线网路改无线网路
此时设置interface-name：Wi-Fi

此部分有办法进行**自动切换**吗？

**复现**

**预期行为**

**日志**

**截图**

**其他说明**

**Comment by Fndroid** [comment]
1. 先在Settings里拉到下面看看Outbound的Interface有没有识别正确，切换网络之后确定没问题
![image](https://user-images.githubusercontent.com/16091562/96835914-d2c8bf00-1476-11eb-937e-8584af8b7f87.png)
2. 把配置/mixin里的``interface-name``删掉，就会自动使用识别的值填入

**Comment by GOODTESTA** [comment]
> 1. 先在Settings里拉到下面看看Outbound的Interface有没有识别正确，切换网络之后确定没问题
>    ![image](https://user-images.githubusercontent.com/16091562/96835914-d2c8bf00-1476-11eb-937e-8584af8b7f87.png)
> 2. 把配置/mixin里的`interface-name`删掉，就会自动使用识别的值填入
> 
> 如果识别不正确，那就只能手动设置了。也就是直接使用这里的Select，不需要配置文件里设置。

可以的，非常感谢。原来Clash for windows 本身就内建自动判别

Wi-Fi连线工则会优先切换至Wi-Fi，否则使用LAN进行TAP模式
需确认Clash之Setting下的Outbound是否能正确辨识电脑的网卡

1.修正方式为将配置的profile.yaml内的「interface-name: ???? 」移除
2.开启clash本身的Mixin功能

功能一切正常，感谢!
