### ISSUE TITLE
便携模式失效

### ISSUE THREAD

**Issue by ChaoSection** [Fndroid/clash_for_windows_pkg#1257]
更新最新的13.0之后，不可以使用便携模式，会提示无法连接内核。

- [x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

win 2004最新

[//]: # (平台及版本号)

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
已知问题，下个版本会优化这个。先退回上一版

**Comment by denghuotongming** [comment]
建议搞一个预览版和稳定版，每次更新都得看下issues😂😂

**Comment by hotsymbol** [comment]
依旧不行

**Comment by ChaoSection** [comment]
> 依旧不行
直接在主程序目录建立date文件夹，我已经成功了

**Comment by ChaoSection** [comment]
> 依旧不行

直接在主程序目录建立date文件夹，我已经成功了

**Comment by Fndroid** [comment]
@denghuotongming 正常来说，版本号第三位只要变为0，说明有比较多的内容调整，较大版本更新。可以等两三个小版再更新。
