### ISSUE TITLE
新账号试用到期使用另外的账号登录，CFW该如何设置才能正常使用？

### ISSUE THREAD

**Issue by Fireking1990** [Fndroid/clash_for_windows_pkg#126]
新账号试用到期，使用了另外一个新账号使用邀请码后试用，登录进去后，同样的设置CFW后，不能正常使用，请问是需要设置CFW吗？如果是，需要怎么设置

**Comment by Fndroid** [comment]
哪个客户端

**Comment by Fireking1990** [comment]
windows的电脑端，Clash for windows，登录按照提示进行了配置

**Comment by Fndroid** [comment]
> windows的电脑端，Clash for windows，登录按照提示进行了配置

我说你用的那个机场提供的
