### ISSUE TITLE
socks代理urltest结果总是timeout

### ISSUE THREAD

**Issue by bombah908** [Fndroid/clash_for_windows_pkg#1260]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**
socks代理，urltest总是返回timeout信息
[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 10 x64 版本1809

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
在clash中添加socks代理，设置切换方式为urltest或者fallback，点击延迟测试能够返回正确的毫秒值，关闭clash窗口后，等待一段时间后再打开clash窗口，发现代理测试返回timeout，而手动点击测试又能取得正确的毫秒值。代理一直都能正常使用

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'proxies'
2. 点击'某个socks代理的闪电按钮，测出正常延迟值'
3. 关闭clash窗口
4. 等待300秒
5. 打开clash窗口，显示socks代理的延迟值为timeout，此时手动点击闪电按钮，延迟为毫秒值（未timeout）

**预期行为**

[//]: # (清晰地描述期望看到的行为)
正常显示延迟毫秒数

**日志**

[//]: # (上传触发问题对应的日志文件)
无相关日志

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/61003363/96986160-d8e09d80-1553-11eb-8eed-750cfb8461c1.png)

**其他说明**

[//]: # (其他补充内容)
无

**Comment by yi-Xu-0100** [comment]
@bombah908 建议给出配置文件的内容，注意屏蔽部分敏感信息

**Comment by bombah908** [comment]
我确认了一下，这个问题可能跟passwall的socks代理有关。
我的socks代理是在passwall里面建立的，passwall版本：3.9-60
![image](https://user-images.githubusercontent.com/61003363/97244827-9f9a7d00-1834-11eb-80f6-29845d78deba.png)
![image](https://user-images.githubusercontent.com/61003363/97244848-a923e500-1834-11eb-8410-3bc9d9dc4202.png)

**Comment by yi-Xu-0100** [comment]
@bombah908 不太了解，没有用过，如果与 CFW 无关的话，可能没法给出建议了。

而且一般个人是不怎么看测速的，如果需要，也会自己点击确认。毕竟，如果显示有毫秒，但是上不去网，需要点一次测试，才知道当前节点是否是 timeout 了。直接看个人觉得不可信。

**Comment by Fndroid** [comment]
配置文件里url-test或者fallback的url填了什么？

**Comment by bombah908** [comment]
![image](https://user-images.githubusercontent.com/61003363/97279143-8fef5880-1875-11eb-9f4b-6e297a9e9011.png)
url填了一个本地web地址，是路由器的管理页面

**Comment by Fndroid** [comment]
界面里测试是用Settings里设置的URL，和你这个不一样结果也就不一样了。
