### ISSUE TITLE
v 0.13.0 使用 EXE 安装中止

### ISSUE THREAD

**Issue by jckling** [Fndroid/clash_for_windows_pkg#1264]
试了几次都这样，然后直接用压缩包更新了 😅 

然后再试还是这样......

[![BVDZf1.png](https://s1.ax1x.com/2020/10/24/BVDZf1.png)](https://imgchr.com/i/BVDZf1)

**Comment by Fndroid** [comment]
应该是手动删除文件导致的。正常卸载要在系统里卸载。
