### ISSUE TITLE
macOS 希望单击顶部状态栏图标的交互逻辑能跟macOS交互逻辑保持一致

### ISSUE THREAD

**Issue by iewgnaw** [Fndroid/clash_for_windows_pkg#1265]
**描述**
现在单击顶部状态栏图标是直接新开dashboard窗口, 所有修改都需要在新窗口中设置，最后再关闭窗口； 但是macOS下几乎所有的软件单击状态栏都是下拉常用菜单，只需要在下拉菜单选择就可完成常用设置，只有对于复杂的操作才需要重新打开新窗口。

是否考虑下更改下交互的逻辑，比如把切换节点等常用操作放在下拉菜单中

**Comment by Fndroid** [comment]
https://github.com/yichengchen/clashX
