### ISSUE TITLE
0.13.0版本无法LAN共享

### ISSUE THREAD

**Issue by Mr-Zhen** [Fndroid/clash_for_windows_pkg#1269]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Win10 20H2
**描述**

[//]: # (请具体并清楚地描述遇到的问题)
v0.13.0版本无法通过LAN共享代理，重新安装v0.12.1版本没有此问题。
**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by KaoImin** [comment]
The same problem

**Comment by KebabShellGitHub** [comment]
同

**Comment by KebabShellGitHub** [comment]
> 同

我的我的，手机忘了添加代理了

**Comment by lvlvxv** [comment]
今天升级13.1版本，我还是用不了网关模式，只有换到12了
