### ISSUE TITLE
关于 fake-ip 参数的写法

### ISSUE THREAD

**Issue by Love4Taylor** [Fndroid/clash_for_windows_pkg#127]
Clash for Windows v0.5.35 中设置 `enhanced-mode: fake-ip` 提示 invalid mode, 改成 `fakeip` 正常.

ClashX 1.9.11 中 `enhanced-mode: fakeip` 提示 invalid mode, 改成 `fake-ip` 正常.

所以这是谁的锅...

**Comment by xjasonlyu** [comment]
Clash core 的参数是`fake-ip`，所以应该是 Clash for Windows v0.5.35 的参数 string 弄错了吧。

然后 clash core 已经在`dev`版本中把`fake-ip`模式的`ttl`改成了`1`，这样在 clash 重启的时候，请求的dns client不会用之前的缓存 ip 导致 clash 无法对应映射域名而报错。

希望 clash for windows 也能尽快把 pkg 的 core 升级到最新。
