### ISSUE TITLE
版本0.13.0，macOS，请问如何修改端口号？

### ISSUE THREAD

**Issue by lucianzhu** [Fndroid/clash_for_windows_pkg#1271]
点击主面板上的“Port 7890”，没有反应，因为端口冲突想换一个其它的

**Comment by yi-Xu-0100** [comment]
@lucianzhu 这个是设置终端代理的方式，如果更换端口，去 `Home Directory` 里找 `config.yaml` 修改。

**Comment by lucianzhu** [comment]
> @lucianzhu 这个是设置终端代理的方式，如果更换端口，去 `Home Directory` 里找 `config.yaml` 修改。

已解决，谢谢！
