### ISSUE TITLE
Telnet 连接 smtp 服务器失败

### ISSUE THREAD

**Issue by Lechenx** [Fndroid/clash_for_windows_pkg#1273]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[windows 10 2004 20h2]: # (平台及版本号)

**描述**

[尝试使用telnet连接qq的smtp服务器，在使用cfw代理的情况下连接失败，关闭代理后正常]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'powershell / cmd/wsl,输入 “telnet smtp.qq.com 25” '
2. 触发问题（连接失败）,见截图2, 将代理模式改为直连依然无法解决，关闭cfw后可正常连接，见截图3

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

见截图1

**截图**

![image](https://user-images.githubusercontent.com/41161865/97454417-b692b980-1971-11eb-8a96-c6b10720f21b.png)

![image](https://user-images.githubusercontent.com/41161865/97455042-5ea88280-1972-11eb-8c74-6485525ecb2b.png)

 
![image](https://user-images.githubusercontent.com/41161865/97514324-5fb8ce80-19c9-11eb-901a-f368f266cb8e.png)

**其他说明**

[//]: # 
情况补充：尝试把tap的监听端口改到telnet的工作端口23，其他选项使用doc中的默认配置，telnet可以正常使用，（当然，其他应用就不能走代理了💔）

**Comment by yi-Xu-0100** [comment]
@Lechenx 没看出来和软件的关联性，有试过关闭软件测试是否有连接吗？

https://blog.csdn.net/whbttst/article/details/96428805

**Comment by Lechenx** [comment]
@yi-Xu-0100 
已更新描述，昨晚寝室断电，没来得及写详细点，抱歉。
关闭clash：可正常连接
clash 使用直连模式：依旧无法连接

**Comment by Fndroid** [comment]
我这是正常的
![image](https://user-images.githubusercontent.com/16091562/97519070-8e3ba700-19d3-11eb-9b2a-dedc3ebaafee.png)

你有手动指定TAP模式的interface-name吗

**Comment by Lechenx** [comment]
@Fndroid  没，发现关了tap模式确实正常了
![image](https://user-images.githubusercontent.com/41161865/97519326-0dc97600-19d4-11eb-9af7-40a79d5da8c2.png)

**Comment by Fndroid** [comment]
TAP模式开了之后正常联网吗？物理网卡是不是这个WLAN2？

**Comment by Lechenx** [comment]
@Fndroid 开了之后可以正常联网，wlan2应该是物理网卡（见下图）。

![image](https://user-images.githubusercontent.com/41161865/97521518-ab26a900-19d8-11eb-8e4e-c280e8face2d.png)

**Comment by Lechenx** [comment]
最新版本已正常
