### ISSUE TITLE
软件报错“Could not swith to this Profile!"

### ISSUE THREAD

**Issue by Ynsane** [Fndroid/clash_for_windows_pkg#1278]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # Windows10 Clash for windows 13.0

**描述**

[//]: # 安装后下载Profiles文件，点击出现的Profiles报错
“Could not swith to this Profile!"
"TAP mode enable but no interface-name setted"
**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'Profiles'
2. 点击'下载的profiles'
3. 报错 

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

![image](https://user-images.githubusercontent.com/62327919/97581417-80b40a80-1a2f-11eb-8013-f64d77f27148.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
把配置文件里的dns下enable的true改成false
