### ISSUE TITLE
配置文件语法与旧版本不一样，希望能考虑兼容旧版配置文件

### ISSUE THREAD

**Issue by Stormeyecloud** [Fndroid/clash_for_windows_pkg#1279]
今天从0.8.11更新到0.13.0，发先以前老的配置文件都用不了了，“Proxies”全部为空，仔细对比后发现语法有细微差别：
         老版本              | 新版本
          Proxy               | proxies
          Proxy group    | proxy-groups
          Rule                 | rules
做细微手动改动后配置文件即可使用。但这样的话就不能随时一键更新了，略有遗憾。希望下个更新能够兼容版配置文件语法。

**Comment by Fndroid** [comment]
为什么不去让你的服务商更新？

**Comment by fxzxmicah** [comment]
> 今天从0.8.11更新到0.13.0，发先以前老的配置文件都用不了了，“Proxies”全部为空，仔细对比后发现语法有细微差别：
> 老版本 | 新版本
> Proxy | proxies
> Proxy group | proxy-groups
> Rule | rules
> 做细微手动改动后配置文件即可使用。但这样的话就不能随时一键更新了，略有遗憾。希望下个更新能够兼容版配置文件语法。

现在全平台Clash均不兼容旧语法，而且旧语法已经淘汰很长时间了，现在再兼容不就是开历史倒车？

**Comment by shikkoku** [comment]
有第三方订阅转换平台，而且你应该联系服务商更新下。
