### ISSUE TITLE
Is it possible to use different ports for http and socks? 

### ISSUE THREAD

**Issue by FluorineDog** [Fndroid/clash_for_windows_pkg#1280]
Is it possible to use different ports for HTTP and socks? 
mixed-port doesn't fit my needs

**Comment by Fndroid** [comment]
> mixed-port doesn't fit my needs

Could you be more specific?

**Comment by FluorineDog** [comment]
> > mixed-port doesn't fit my needs
> 
> Could you be more specific?

I have too many scripts/programs that have hard-coded my http/socks ports, which happen to be different. It's a headache to change them one by one.

**Comment by Fndroid** [comment]
You can still set http/socks port in General `config.yaml`. 

But `mixed-port` field must not be deleted.

**Comment by FluorineDog** [comment]
OK, thanks.
