### ISSUE TITLE
clash for windows  system proxy 下面没有pac可以选择吗？

### ISSUE THREAD

**Issue by vinkchen2021** [Fndroid/clash_for_windows_pkg#1282]
**描述**
clash for windows  system proxy 下面是否可以提供pac可以选择？

**其他说明**
其他补充内容

**Comment by CyberTNT** [comment]
代理模式在设置里选就好了啊

**Comment by echo860** [comment]
在settings里，默认的是http，
但是从上一版来看，PAC有问题，版主建议用http.

**Comment by Fndroid** [comment]
mac版暂时没有这个功能，而且也没什么必要，因为mac版能直接设置socks5代理
