### ISSUE TITLE
请为mac添加Pac模式

### ISSUE THREAD

**Issue by dr1llc4t** [Fndroid/clash_for_windows_pkg#1283]
**描述**
目前windows版本的已经有pac模式了，希望开发人员为mac系统添加pac模式

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
有什么意义么

**Comment by dr1llc4t** [comment]
> 有什么意义么

之前发现很有意思的一件事情，在mac下，应用了系统代理之后，即使是设置了采用直连，不走代理，某些软件仍然会很慢。比如battlenet战网程序，下载游戏的时候，基本上速度超不过1MB/s。看clash日志也没有显示走代理。但是换个支持pac模式的软件就没事，很诡异的事情。
同时我也测试了surge代理软件，跟clash同样的问题。所以判定mac下某些软件对socket和http的代理支持度不高。
同时看到windows下支持了pac模式，因此寄希望于开发者大大能为mac带来pac模式。

**Comment by Fndroid** [comment]
这种问题跟PAC无关，跟你设置的bypass有关
