### ISSUE TITLE
希望可以支持justmysocks的订阅链接

### ISSUE THREAD

**Issue by fungtion** [Fndroid/clash_for_windows_pkg#1284]
**描述**
希望可以支持justmysocks的订阅链接，quantumult已经支持，目前clash_for_windows还不能解析。

**Comment by Fndroid** [comment]
那不就是ss或者v2ray，自己配置

**Comment by fungtion** [comment]
@Fndroid 包含所有ss或v2ray的一个链接，如何进行配置

**Comment by yi-Xu-0100** [comment]
@fungtion 建议找一下转换订阅链接的网站试试，或者向服务商提出要求

这里是网上的服务，不保证可靠性和安全性： <https://acl4ssr.netlify.app/>

**Comment by fungtion** [comment]
@yi-Xu-0100 好的，感谢
