### ISSUE TITLE
注册表缺失

### ISSUE THREAD

**Issue by QDH734** [Fndroid/clash_for_windows_pkg#1286]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (版本	Windows 10 专业版
版本号	20H2
操作系统版本	19042.610
体验	Windows Feature Experience Pack 120.2212.31.0

clash:0.13.1)

**描述**
在不使用管理员权限打开软件时无法正常使用,打开界面会显示截图所示的界面.以管理员权限打开就不会显示此界面但这样每次开机后都会是断网状态

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'不以管理员权限,双击打开软件'
2. 点击'任务栏图标打开界面'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/73753448/97784956-2f497e00-1bdd-11eb-9d0d-3a3c95279d93.png)
[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by QDH734** [comment]
我顺着目录找到的文件
mixed-port: 7890
allow-lan: false
log-level: info
external-controller: '127.0.0.1:9090'
secret: ''
ipv6: false

# Will be ignored after profile selection
proxies:
  - name: Debug
    type: socks5
    server: 127.0.0.1
    port: 1080
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - Debug
rules:
  - 'MATCH,DIRECT'

**Comment by yi-Xu-0100** [comment]
@QDH734 个人猜测，是否安装的时候，选择了"仅给当前用户安装"的选项？

**Comment by QDH734** [comment]
> @ QDH734个人猜测，是否安装的时候，选择了“仅给当前用户安装”的选项？
> 
> 或者将clash下面的所有文件删除，重新打开软件，让他重建一次试试

把用户那个目录下的文件都删除后再重装就好了,感谢.我之前只删了出问题的这个文件没起作用
