### ISSUE TITLE
Update Notification on ARM64 downloads x86/64 .exe

### ISSUE THREAD

**Issue by TJT-JTJ** [Fndroid/clash_for_windows_pkg#1288]
To reproduce:

1. Click version number in Clash for Windows GUI
2. Update Available, Info provided in window
3. Click 'Download'
4. x86 version is automatically downloaded, installer does not check if x86/64 or arm64 and throw error

If the x86/64 version is installed it cannot be launched. Need to use an alternative proxy to get the correct .exe installer

**Comment by Fndroid** [comment]
What's the arch of your device?

We don't prvide arm64 build right now. It seems that x86(ia32) is compatible with arm64 .

**Comment by TJT-JTJ** [comment]
arm64 - My mistake, misunderstood the bug

So the bug is that ia32 version update notification links to download the standard .exe which on ARM64 devices is throwing out an error because it's 64bit only and can't run the app after the installer finished upgrading. 

Some logic to detect ARM64 in the installer and prevent install of non-ia32 builds may be useful to prevent users ruining their install and being unable to open the app.

**Comment by Fndroid** [comment]
This issue had been fixed in 0.13.1

![image](https://user-images.githubusercontent.com/16091562/97822940-69587400-1cf2-11eb-9892-f1ab7b5deac5.png)
