### ISSUE TITLE
编辑器选择Sublime Text无法编辑

### ISSUE THREAD

**Issue by convictss** [Fndroid/clash_for_windows_pkg#1290]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows10，CFW-0.13.1

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
在0.13.1版本中，编辑器选择Sublime Text，则此时再点击Parsers 的edit按钮
![image](https://user-images.githubusercontent.com/39207692/97837250-c7984d80-1d18-11eb-89bd-fe492ffb9a20.png)

结果只出现一个弹窗，并且一闪而过，多次尝试依靠手速截图，弹窗内容如下：
![image](https://user-images.githubusercontent.com/39207692/97837284-d848c380-1d18-11eb-8454-92484c32b5eb.png)

无论Sublime Text是否已经处于运行，都是只有一闪而过的弹窗

**复现**

[//]: # (请描述复现问题的步骤)
与[描述] 步骤一致

**预期行为**

[//]: # (清晰地描述期望看到的行为)
自动在Sublime Text 编辑器中打开 cfw-settings.yaml

**其他说明**

[//]: # (其他补充内容)
无

**Comment by Fndroid** [comment]
这个功能基于sublime text的命令行``subl``

https://www.sublimetext.com/docs/command_line.html#mac

**Comment by convictss** [comment]
@Fndroid 
感谢回复，已配置完成，此issue结束。
