### ISSUE TITLE
怎么修改语言啊

### ISSUE THREAD

**Issue by Vxiaozhe1998** [Fndroid/clash_for_windows_pkg#1291]
**描述**
请具体并清楚地描述期望功能及期望的效果

**其他说明**
其他补充内容

**Comment by yi-Xu-0100** [comment]
官方没有其他语言支持。

Duplicate of #999

**Comment by Vxiaozhe1998** [comment]
那安装文件夹中的locales中的zh-CN.pak是什么东东

**Comment by yi-Xu-0100** [comment]
@Vxiaozhe1998 应该是框架自带的吧，官方软件上是没有支持切换语言的。

**Comment by Vxiaozhe1998** [comment]
哎，好惨，好吧，谢谢你

**Comment by iamqiz** [comment]
BoyceLig/Clash_Chinese_Patch: Clash For Windows 汉化补丁和汉化脚本
https://github.com/BoyceLig/Clash_Chinese_Patch
