### ISSUE TITLE
某些YouTube视频无法播放，有连接速度，但是网络活动和缓冲均为0

### ISSUE THREAD

**Issue by lovinglover** [Fndroid/clash_for_windows_pkg#1292]
- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
win10 

**描述**
某些YouTube视频无法播放，有连接速度，但是网络活动和缓冲均为0，同一个视频我用手机同一个节点可以播放，应该可以排除是节点问题，clash已经是最新版本

**复现**

[//]: # (请描述复现问题的步骤)

我不知道其他人是否会出现同样问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/43927158/97854772-dee53400-1d34-11eb-937b-7b7b33e1201f.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
手机上用的啥软件？
是否是一时的网络波动？
如果只是部分视频，是否是浏览器缓存问题？在无痕模式下试试。
节点什么协议？
是否只是某个节点的问题？尝试更换节点试试
CFW 的日志是否有相关 timeout ？
浏览器的控制台日志是否有相关 errror 内容输出？

**Comment by lovinglover** [comment]
手机IOS + Quantumult X
应该不是，我在5月份就有视频这样，那是很少，最近几个想看的视频也这样，才反馈
无痕模式下尝试过了，相同的视频也是一样的情况，网络活动与缓存都是0
ss
更换过节点，一样的
仔细看过日志了，并没有相关信息
浏览器控制台一堆forbidden
![image](https://user-images.githubusercontent.com/43927158/97857097-30db8900-1d38-11eb-821f-c05c3ecee759.png)
![image](https://user-images.githubusercontent.com/43927158/97857267-6da78000-1d38-11eb-88c7-35aa759c282c.png)

**Comment by yi-Xu-0100** [comment]
403 错误：<https://zhuanlan.zhihu.com/p/36680563>
可以看看这个试着解决一下，dns 缓存清一下试试，或者更换 dns
查一下 CFW 日志中 googlevideo.com 相关内容，贴一下最好。
不确定是否是 clash core 的问题，毕竟你手机上并没有使用 clash （好像也没法，可以找个安卓机试试）。

**Comment by Fndroid** [comment]
一般就是dns或者规则问题

**Comment by lovinglover** [comment]
emm，我好像知道原因了，我看日志，YouTube和Googlevideo走的不是一个策略，我把两个策略改成同样的节点就可以了

**Comment by lovinglover** [comment]
但也不对，YouTube和Googlevideo在两个策略组里都有，我看了我手机上也是这样，正常播放视频时都是YouTube走YouTube策略组，Googlevideo走另外一个策略组，但部分视频这样就是无法播放

**Comment by Fndroid** [comment]
不是刷新dns，是把配置里设置的dns关掉
