### ISSUE TITLE
cfw-bypass如何设置才能生效，我这设置之后未生效

### ISSUE THREAD

**Issue by WangJincheng4869** [Fndroid/clash_for_windows_pkg#1293]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
![image](https://user-images.githubusercontent.com/41162158/97965987-297ab500-1df6-11eb-954b-fad92d1003a5.png)

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
![image](https://user-images.githubusercontent.com/41162158/97966081-4c0cce00-1df6-11eb-8b9f-ecd2eee11472.png)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by WangJincheng4869** [comment]
![image](https://user-images.githubusercontent.com/41162158/97966270-93935a00-1df6-11eb-8469-82648724bc5f.png)

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/bypass.html

**Comment by WangJincheng4869** [comment]
> https://docs.cfw.lbyczf.com/contents/bypass.html

哦！加了双引号依旧没用！，没有生效

**Comment by Fndroid** [comment]
你能跟着步骤一个个认真看下么

**Comment by WangJincheng4869** [comment]
没有找到【System proxy Bypass】我只找到了这个。HTTP/PAC 没有修改过。修改后依旧没有生效，不知道是不是我哪里的打开方式不对
![image](https://user-images.githubusercontent.com/41162158/97970525-9f821a80-1dfc-11eb-9cd1-2ee16eb5f80b.png)
![image](https://user-images.githubusercontent.com/41162158/97970838-17e8db80-1dfd-11eb-984c-0271e1d6a04f.png)

![image](https://user-images.githubusercontent.com/41162158/97970366-621d8d00-1dfc-11eb-9c61-3ad728df963a.png)

**Comment by WangJincheng4869** [comment]
> 你能跟着步骤一个个认真看下么

但是修改之后再系统设置里已经显示了，但是通过软件查看依旧走的代理。不知道到底生没生效，是已经生效的软件显示的不对，还是配置额度不对
![image](https://user-images.githubusercontent.com/41162158/97971241-b1b08880-1dfd-11eb-8dc8-01de1408db99.png)

**Comment by yi-Xu-0100** [comment]
@WangJincheng4869 试试开关下系统代理设置，然后再访问该网站看看

**Comment by Fndroid** [comment]
``*.abc.com``

**Comment by WangJincheng4869** [comment]
> `*.abc.com`

没错！就是少前面这个【*.】，看来只能走通配符
