### ISSUE TITLE
LAN到底该如何设置，这一版PAC现在能用了吗？

### ISSUE THREAD

**Issue by echo860** [Fndroid/clash_for_windows_pkg#1294]
这是我的设置。
https://imgur.com/oSnSgZc
这里有点看不懂，我知道7080是端口，怎么上面又有一个20080端口？
https://imgur.com/QA6mLZC
还有模式设置，该选择PAC还是HTTP? 记得上一个版本PAC不好用，版主说用HTTP，这个版本能用PAC吗？

**Comment by Fndroid** [comment]
不懂就用http的

**Comment by echo860** [comment]
> 不懂就用http的

但是我用梯子一直PAC啊。还有LAN到底怎么设置的，下面哪个该点哪个不点？
自动检测设置，使用自动检测脚本，为LAN使用代理服务器

**Comment by yi-Xu-0100** [comment]
@echo860 你说的是系统的设置，不是软件设置，建议了解相关概念后再问，或者直接换回原来熟悉的软件。

软件基本使用文档：<https://docs.cfw.lbyczf.com/>

**Comment by echo860** [comment]
> @echo860 你说的是系统的设置，不是软件设置，建议了解相关概念后再问，或者直接换回原来熟悉的软件。
> 
> 软件基本使用文档：https://docs.cfw.lbyczf.com/

Clash我用两年了，前两年用得好好的，今年起有一版大动后，不灵了
这网址下没看到哪里有怎么设置系统代理的 https://docs.cfw.lbyczf.com/

**Comment by yi-Xu-0100** [comment]
@echo860 没提到的应该就是不用动的，默认就好。

除非你懂修改后会影响什么。

@echo860 软件中关于系统代理的设置，只有一个开关，打开就是启用系统代理，关闭就是关闭系统代理。所以没必要配置。

PAC 并不是都需要的，默认的 http 代理 + 配置的 rule 结果是类似的。

如果是代理无效，给出日志或者相关错误截图。
代理有效，进阶配置建议了解相关知识后，再提问，不然，回答这类问题，可能得再写个说明教程了。

**Comment by echo860** [comment]
> @echo860 没提到的应该就是不用动的，默认就好。
> 
> 除非你懂修改后会影响什么。
> 
> @echo860 软件中关于系统代理的设置，只有一个开关，打开就是启用系统代理，关闭就是关闭系统代理。所以没必要配置。
> 
> PAC 并不是都需要的，默认的 http 代理 + 配置的 rule 结果是类似的。
> 
> 如果是代理无效，给出日志或者相关错误截图。
> 代理有效，进阶配置建议了解相关知识后，再提问，不然，回答这类问题，可能得再写个说明教程了。

谢谢耐心解释。 那我就点reset all setting用默认设置算了，以前用SS习惯了点PAC
系统代理那以前确实没注意，看了网上各不相同的说法，瞎改了一通，不知道如何改回去了
LAN设置那里，<自动检测设置> <使用自动检测脚本> <为LAN使用代理服务器> 这三项你点的是哪几个？我照抄你的就行
https://imgur.com/oSnSgZc

**Comment by yi-Xu-0100** [comment]
<自动检测设置> <使用自动检测脚本> 这两个不选， <为LAN使用代理服务器> 可以由设置系统代理那个开关控制开关。

**Comment by echo860** [comment]
> @echo860 我的是：<自动检测设置> <使用自动检测脚本> 这两个不选， <为LAN使用代理服务器> 可以由设置系统代理那个开关控制开关，我使用软件控制开启，浏览器默认走系统代理。

谢谢，"设置系统代理"那个开关 是不是allow lan

**Comment by yi-Xu-0100** [comment]
@echo860 
![image](https://user-images.githubusercontent.com/25523606/97977138-b3327e80-1e06-11eb-8c91-a8a66bfa7f95.png)

**Comment by echo860** [comment]
> @echo860
> ![image](https://user-images.githubusercontent.com/25523606/97977138-b3327e80-1e06-11eb-8c91-a8a66bfa7f95.png)

非常感谢。我就按你这种来办了
