### ISSUE TITLE
系统代理相关问题

### ISSUE THREAD

**Issue by sy999999ys** [Fndroid/clash_for_windows_pkg#1298]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
windows10 20H2  v0.13.1

[//]: # (平台及版本号)

**描述**
使用HTTP代理打不开微软商店，使用pac代理电报无法使用。

**Comment by yi-Xu-0100** [comment]
那使用 tap 模式吧

**Comment by Fndroid** [comment]
``General - UWP Loopback - 全选 - 保存 ``
