### ISSUE TITLE
win10系统,通过window商店下载的app不能代理,试过网易云音乐,哔哩哔哩,日志也没有相关信息

### ISSUE THREAD

**Issue by spritewdx** [Fndroid/clash_for_windows_pkg#13]

**Comment by evilgu** [comment]
正准备提呢，同样情况

**Comment by Fndroid** [comment]
UWP应用由于阻止了loopback，所以无法使用本地代理，[参考这个](https://blog.sumblog.cn/archives/uwp-socks.html)

但是网易云音乐UWP版比较特殊，即使允许loopback，它也无法联网。比较妥当的方法是关闭Clash for Windows里的System Proxy选项，对需要代理的软件单独配置http或socks代理
