### ISSUE TITLE
此工具能不能纯代理.exe程序?

### ISSUE THREAD

**Issue by tea1111980** [Fndroid/clash_for_windows_pkg#130]
如题。
代理服，我已经有了。

就是类似于 Proxifier的功能。
就是创建一个Socks5的配置，然后能否通过自己创建的Socks-5这个代理模式，代理.exe程序？有没有相应的规则。
我看了一下规则 好像没有。不知道MATCH这个规则？
谢谢！

**Comment by Fndroid** [comment]
@tea1111980 不能

**Comment by tea1111980** [comment]
好的，谢谢。我关闭这个问题了。
