### ISSUE TITLE
Cannot destructure property 'name' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by convictss** [Fndroid/clash_for_windows_pkg#1300]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Windows10, Clash.for.Windows-0.13.1-win

**描述**
在先配置好parser 为 file为 js的情况下，如：
```
parsers: # array
  - reg: .*subcon.py6.pw.*
    file: 'E:/Clash.custom/customConfig.js'
```
js内容如下：
```
module.exports.parse = async (raw, { axios, yaml, notify }, { name, url, interval, selected }) => {
    const obj = yaml.parse(raw);
    notify("Clash for windows", "profile has been modified.", false);
    return yaml.stringify(obj);
}
```
此时在Profiles 中下载新的订阅配置，则会出现错误：
![image](https://user-images.githubusercontent.com/39207692/98214685-c453ca80-1f81-11eb-9d6a-70a325f307af.png)

但如果将parser清空还原，或者换成yaml 则可以正常下载全新的订阅，并且匹配自己的规则

如果在parser清空还原的情况下，可以正常下载订阅配置，此时再配置parser 将file指定到 js，刷新已下载的订阅配置，则又正常进入js 代码块中

**复现**
1. 配置parser 使用自定义js
2. 下载全新的订阅配置，且该路径匹配上一步建立的parser
3. 触发问题

**预期行为**
先配置好parser 的情况下，能自动下载并进入到自定义配置js中，完成自定义配置

**日志**
无

**Comment by Fndroid** [comment]
应该是一个bug，下个版本修复

**Comment by Fndroid** [comment]
默认 metadata 改为了 ``{}``， 所以解构出来的 name 之类的属性在第一次下载的时候会是 undefined 的

**Comment by convictss** [comment]
那这样的话，只能第一次下载的时候去除传入元数据，下载完后再改js 将元数据传入吗？
```
module.exports.parse = async (raw, { axios, yaml, notify }) => {
    const obj = yaml.parse(raw);
    notify("Clash for windows", "profile has been modified.", false);
    return yaml.stringify(obj);
}
```

**Comment by Fndroid** [comment]
判断一下就好了吧
