### ISSUE TITLE
proxies不显示任何节点

### ISSUE THREAD

**Issue by luisa1023** [Fndroid/clash_for_windows_pkg#1302]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # 
v0.11.2

**描述**

[//]: # 
[按照教程操作后仍上不了网，对比正常页面发现proxies不显示节点，只有global页面显示了direct和reject

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入clash for windows
2. 一键导入
3. 打开system proxies
4. 流量为0，且proxies页面无节点

**预期行为**

[//]: #
 能够上网

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
看看这个 #1072 ，查看是否是配置文件问题

或者将 Home Directory 对应的 clash 文件夹整个删除后，重启软件

**Comment by luisa1023** [comment]
> 看看这个 #1072 ，查看是否是配置文件问题
> 
> 或者将 Home Directory 对应的 clash 文件夹整个删除后，重启软件

谢谢，我的问题和链接中的基本是一样的。但是试了链接里的方法也删了文件夹，还是不行

**Comment by luisa1023** [comment]
> 看看这个 #1072 ，查看是否是配置文件问题
> 
> 或者将 Home Directory 对应的 clash 文件夹整个删除后，重启软件

和朋友下的同一个，但是朋友用并没有问题。刚刚重启后出现了shadowsocks，但都是timeout...

![微信截图_20201106114236](https://user-images.githubusercontent.com/74033305/98323674-4e08a400-2025-11eb-907a-c32110cbd892.png)

**Comment by Fndroid** [comment]
配置文件问题
