### ISSUE TITLE
点击规则组和规则过一会儿会自己返回

### ISSUE THREAD

**Issue by SplitGemini** [Fndroid/clash_for_windows_pkg#1304]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）
- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在

**系统**
Win10 20H2

[//]: # (平台及版本号)

**描述**
profiles 界面点击edit policies或者edit rules按钮进入后过几秒会自动返回

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入profiles 
2. 点击edit policie或edit rules，进入相应界面
3. 等待几秒
4. 触发问题

**预期行为**
不自动返回

[//]: # (清晰地描述期望看到的行为)

**日志**
无

[//]: # (上传触发问题对应的日志文件)

**截图**
![1](https://user-images.githubusercontent.com/34861918/98356984-72817200-205f-11eb-8fdc-4ee76f9548d3.gif)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**
每个profile往往只发生一次，短时间内不会再次发生，下次大概是重启软件后再次发生（我不确定），这个问题存在很久了

[//]: # (其他补充内容)

**Comment by erenyega** [comment]
是的，我也遇到跟你一样的情况

**Comment by Davidlasky** [comment]
+1

**Comment by Fndroid** [comment]
这个大概是CFW检测到profiles文件夹有文件发生了变化导致。下个版本优化下。

**Comment by Fndroid** [comment]
试试最新版
