### ISSUE TITLE
设置General  选中SystemProxy  切换左侧任意tab，则SystemProxy变为非选中状态  有人知道原因嘛？好怪啊

### ISSUE THREAD

**Issue by zyc12345** [Fndroid/clash_for_windows_pkg#131]
设置General  选中SystemProxy  切换左侧任意tab，则SystemProxy变为非选中状态  有人知道原因嘛？好怪啊

**Comment by zyc12345** [comment]
最新版本  v0.6.0

**Comment by Fndroid** [comment]
检查一下代理服务器有没有设置成功
![image](https://user-images.githubusercontent.com/16091562/60397316-62f63d00-9b7e-11e9-9908-0740bf045035.png)

**Comment by zyc12345** [comment]
谢谢F大，应该是我电脑系统的问题，设置这个手动代理也是保存不成功，切换tab这里也会被重置

**Comment by Fndroid** [comment]
有可能是注册表被其他程序锁定了，检查一下
