### ISSUE TITLE
`git bash`下的代理指令 &&

### ISSUE THREAD

**Issue by e71828** [Fndroid/clash_for_windows_pkg#1312]
**描述**
请具体并清楚地描述期望功能及期望的效果
`$ set http_proxy=http://127.0.0.1:7890 && set https_proxy=http://127.0.0.1:7890`
**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
什么意思

**Comment by e71828** [comment]
&& 
@e71828

**Comment by yi-Xu-0100** [comment]
@e71828 git bash 无法用 set 去设置环境变量，应该用下面的

```bash
export http_proxy=http://127.0.0.1:7890 && export https_proxy=http://127.0.0.1:7890
```
