### ISSUE TITLE
每秒钟都产生一些看起来不是很必要的频繁HTTP请求

### ISSUE THREAD

**Issue by p3p3pp3** [Fndroid/clash_for_windows_pkg#1314]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10
Clash for windows V0.13.2

**描述**

当软件界面在General时，每秒钟都产生一些看起来不是很必要的频繁HTTP请求。即使最小化软件，也依然会产生。当切换到别的选项卡时，不再发送，具体请求见Fiddler截图。

**预期行为**

降低这些请求的频率。

**截图**

![image](https://user-images.githubusercontent.com/3984167/98665191-4d09a680-2386-11eb-973e-379e64d325ed.png)

**其他说明**

无

**Comment by Fndroid** [comment]
会有什么影响吗

**Comment by p3p3pp3** [comment]
> 会有什么影响吗

一般是没什么影响的。
工作时开fiddler调试别的应用，这些消息看起来有些打扰。

**Comment by Fndroid** [comment]
最新版调整了，只要不在前台现实，就暂停一些不必要的请求

**Comment by p3p3pp3** [comment]
经测试 v0.13.3 版本已经解决这个问题，感谢！

**Comment by git10135405** [comment]
> 最新版调整了，只要不在前台现实，就暂停一些不必要的请求

我这边也在一直刷，而且更新providers一开始显示更新，重启后却是一两个月前，这样正常吗？
![image](https://user-images.githubusercontent.com/35558611/134442769-302d2fd0-7db0-41cc-b16e-2876eabf3bbf.png)

**Comment by yi-Xu-0100** [comment]
@git10135405 你前台显示了

**Comment by git10135405** [comment]
> @git10135405 你前台显示了
我打开这个看的
![image](https://user-images.githubusercontent.com/35558611/134445020-6e4014db-b57b-4a1d-b008-770589c384ee.png)

**Comment by git10135405** [comment]
这个时providers更新一会后看的：
![image](https://user-images.githubusercontent.com/35558611/134445297-5c2cc784-5d92-40d8-85f9-0b6964a2eb9c.png)

这个是重启后的：
![image](https://user-images.githubusercontent.com/35558611/134445339-524ddc2d-2053-44b9-965c-ca128a106205.png)

**Comment by yi-Xu-0100** [comment]
@git10135405 你前台显示界面，有很正常。

**Comment by git10135405** [comment]
> @git10135405 你前台显示界面，有很正常。
嗯 话说这个是干嘛用的一直报错？ 还有providers更新是正常吗？

**Comment by yi-Xu-0100** [comment]
@git10135405 provider 更新，文件不更新，不会变化更新时间。说明你的 provider 内容没变。

**Comment by git10135405** [comment]
> @git10135405 provider 更新，文件不更新，不会变化更新时间。说明你的 provider 内容没变。

跟安卓的不一样，所以问问
