### ISSUE TITLE
V0.13.2Win10下无法订阅

### ISSUE THREAD

**Issue by ahalegolas** [Fndroid/clash_for_windows_pkg#1316]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: Win10# (平台及版本号)

**描述**
订阅时报错

**复现**

**预期行为**

**日志**

**截图**

![无标题](https://user-images.githubusercontent.com/74344349/98907593-0472fa00-24fa-11eb-9a88-fff146c6ce94.png)

其他说明

**Comment by yi-Xu-0100** [comment]
建议检查下订阅地址对应文件是否符合 yaml 格式，然后看看 文件 11 行是啥，贴一下

**Comment by ahalegolas** [comment]
> 建议检查下订阅地址对应文件是否符合yaml格式，然后看看文件11行是啥，贴一下

---
port: 8888
socks-port: 8889
mixed-port: 8899
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:6170
experimental:
  ignore-resolve-fail: true
clash-for-android:
  ui-subtitle-pattern: '[一-龥]{2,4}'
proxies:


我刚才重新订阅了一下可以了，那会一直不行
