### ISSUE TITLE
v0.6.0无法加载配置

### ISSUE THREAD

**Issue by hueyless** [Fndroid/clash_for_windows_pkg#132]
使用了exe版本升级 失败
卸载后 删除%homepath%/.config/clash 删除 %appdata%clash_win %/appdata%clash 同样失败

配置文件是一个2ray

**Comment by Fndroid** [comment]
失败是什么意思？不能安装？

**Comment by hueyless** [comment]
错误是点不中配置文件
开了debug日志级别 .config/clash/log下没有看到相关的报错
怎么调试clash_for_windows本身的日志？
退回5.35没这问题

**Comment by Fndroid** [comment]
点不中配置说明配置里有错，切换的时候会有通知提示具体哪里错了

**Comment by hueyless** [comment]
配置从5.35复制.config/clash/profile/number.yml 或者自己重新手工填入都不行
clash_for_windows 默认配置是绿色 选中的橙色 现象是选中的一瞬间变成橙色 然后以还原成绿色

**Comment by Fndroid** [comment]
@hueyless 因为新的clash核心会检查规则中的策略是否存在，不存在就会报错，旧版本不存在是会忽略的。

**Comment by hueyless** [comment]
那这个报错的日志怎么可以看到 需要debug

**Comment by kanezeng** [comment]
我也碰到同样的问题了，5.35能用的配置文件，现在没办法用了，哪里能看到详细的错误信息呢？

**Comment by kanezeng** [comment]
不知道什么情况下，log里面有了这么一条：
time="2019-07-01T15:41:28+08:00" level=fatal msg="Parse config error: Rules[0] [DOMAIN,audio-ssl.itunes.apple.com,Apple Services] error: proxy [Apple Services] not found"

但是我查了确实有Apple Services这个Group。还有就是把所有Rule都删掉也不行。

**Comment by Fndroid** [comment]
> 那这个报错的日志怎么可以看到 需要debug

无法切换的错误会通过系统通知显示，如果没有：

1. 随便创建一个test文件夹
2. 进入安装目录：Clash for Windows\resources\static\files，将clash-win64.exe复制到test文件夹
3. Profiles里点击错误配置的铅笔图标，文本打开配置，复制全部内容
4. 在test文件夹里创建config.yaml，并粘贴内容
5. 打开cmd，命令行输入``clash-win64.exe -d .``

**Comment by Fndroid** [comment]
> 不知道什么情况下，log里面有了这么一条：
> time="2019-07-01T15:41:28+08:00" level=fatal msg="Parse config error: Rules[0] [DOMAIN,audio-ssl.itunes.apple.com,Apple Services] error: proxy [Apple Services] not found"
> 
> 但是我查了确实有Apple Services这个Group。还有就是把所有Rule都删掉也不行。

因为你改错文件了，删掉Home Directory目录下config.yml重启

**Comment by kanezeng** [comment]
> > 不知道什么情况下，log里面有了这么一条：
> > time="2019-07-01T15:41:28+08:00" level=fatal msg="Parse config error: Rules[0] [DOMAIN,audio-ssl.itunes.apple.com,Apple Services] error: proxy [Apple Services] not found"
> > 但是我查了确实有Apple Services这个Group。还有就是把所有Rule都删掉也不行。
> 
> 因为你改错文件了，删掉Home Directory目录下config.yml重启

谢啦，删了config.yml，重启后自然就好了。

**Comment by hueyless** [comment]
> > 那这个报错的日志怎么可以看到 需要debug
> 
> 无法切换的错误会通过系统通知显示，如果没有：
> 
> 1. 随便创建一个test文件夹
> 2. 进入安装目录：`Clash for Windows\resources\static\files`，将`clash-win64.exe`复制到test文件夹
> 3. Profiles里点击错误配置的铅笔图标，文本打开配置，复制全部内容
> 4. 在test文件夹里创建`config.yaml`，并粘贴内容
> 5. 打开cmd，命令行输入`clash-win64.exe -d .`

我试了下 发现之前版本的rule里有个Proxy是可以用的 0.60不行 没有Proxy 需要使用组名或者节点名 就出错了

**Comment by joviqiao** [comment]
`port: 9876
socks-port: 9875
redir-port: 9874
allow-lan: false
mode: Rule
log-level: info
external-controller: 0.0.0.0:9873
secret: ''
Proxy:
  - name: "admin"
    type: vmess
    server: XXXXX
    port: 443
    uuid: 532730d3-33db-4ff6-b65c-696fe6b1af01
    alterId: 32
    cipher: auto
    tls: true
Proxy Group:
  - name: Proxy
    type: select
    proxies:
      - "admin"
Rule:
- DOMAIN,gs.apple.com,Proxy
- DOMAIN-SUFFIX,mzstatic.com,DIRECT
- DOMAIN-SUFFIX,akadns.net,DIRECT
- DOMAIN-SUFFIX,aaplimg.com,DIRECT
- DOMAIN-SUFFIX,cdn-apple.com,DIRECT

- DOMAIN,itunes.apple.com, DIRECT
- DOMAIN,beta.itunes.apple.com, DIRECT
- DOMAIN-SUFFIX,apple.com, DIRECT
- DOMAIN-SUFFIX,icloud.com,DIRECT
- DOMAIN-SUFFIX,icloud-content.com,DIRECT
- DOMAIN,e.crashlytics.com,REJECT
`

![image](https://user-images.githubusercontent.com/13116366/60780647-ebbe3b80-a171-11e9-8210-68e7a1aacb9c.png)


就像这样，大家方便给我一个配置模版么。。
