### ISSUE TITLE
update profile后，Proxies里啥都没有了。

### ISSUE THREAD

**Issue by mostcool** [Fndroid/clash_for_windows_pkg#1320]
update profile后，Proxies里啥都没有了。需要手动修改yml文件里的几个节点才能在再次出现。
原因如下：
https://github.com/Dreamacro/clash/wiki/breaking-changes-in-1.0.0
Proxy, Proxy Group and Rule is no longer used. They are now respectively proxies, proxy-groups and rules.

**Comment by yi-Xu-0100** [comment]
知道原因的话，让服务商更新配置就好了
