### ISSUE TITLE
希望console output不会自动清空

### ISSUE THREAD

**Issue by SplitGemini** [Fndroid/clash_for_windows_pkg#1324]
**描述**
希望能保留每次更新配置后parser里的console output，而不是每次都覆写，最好是保存在logs文件夹里（和核心log放一起不好吗）

**其他说明**
有个问题：自动更新的配置没有output，只用手动更新的有

**Comment by Fndroid** [comment]
你可以自己实现一个console

**Comment by SplitGemini** [comment]
有道理
