### ISSUE TITLE
期待CFW原生支持中文

### ISSUE THREAD

**Issue by sunbin7288** [Fndroid/clash_for_windows_pkg#1329]
**描述**从CFW 0.13.2开始，js文件已被加密，汉化无法继续进行，请期待CFW原生支持中文
请具体并清楚地描述期望功能及期望的效果

**其他说明**
其他补充内容：期待CFW原生支持中文

**Comment by yi-Xu-0100** [comment]
Duplicate of #1190

**Comment by Fndroid** [comment]
几个单词看不会别用了建议
