### ISSUE TITLE
0.6.0 版本是否不支持对应不到 Proxy Group 的规则？

### ISSUE THREAD

**Issue by mundoque** [Fndroid/clash_for_windows_pkg#133]
上一个版本可以正常加载规则和使用，最新版本加载失败并报错 XXX not found

**Comment by Fndroid** [comment]
@mundoque 因为新版本对Rule规则检查更加严格，策略组不存在会报错。哪个规则出问题都有详细说明自己修改好就行

**Comment by mundoque** [comment]
感谢解答
