### ISSUE TITLE
如何直接进入dashboard？

### ISSUE THREAD

**Issue by galaxygh** [Fndroid/clash_for_windows_pkg#1336]
发现打开软件后会在后台运行，想要更新订阅链接还要再打开软件界面，不太方便。

请问如何直接打开软件界面呢？

**Comment by Fndroid** [comment]
目前没有这个设置

**Comment by galaxygh** [comment]
好的谢谢

**Comment by 3296969914** [comment]
#1336------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;galaxygh&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月16日(星期一) 下午4:29
收件人:&nbsp;&quot;Fndroid/clash_for_windows_pkg&quot;<clash_for_windows_pkg@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Fndroid/clash_for_windows_pkg] 如何直接进入dashboard？ (#1336)

**Comment by Fndroid** [comment]
下个版本将支持这个功能
![image](https://user-images.githubusercontent.com/16091562/99251868-0108a700-2849-11eb-8e90-f583e0803799.png)
