### ISSUE TITLE
希望可以支持domain-list-community项目数据库

### ISSUE THREAD

**Issue by Ricardo-L-C** [Fndroid/clash_for_windows_pkg#1338]
https://github.com/v2fly/domain-list-community
https://www.v2fly.org/config/routing.html#%E9%A2%84%E5%AE%9A%E4%B9%89%E5%9F%9F%E5%90%8D%E5%88%97%E8%A1%A8
包含了很多常用域名，能够方便配置

**Comment by yi-Xu-0100** [comment]
@Ricardo-L-C 
可以使用 parser 的 js 方式将内容处理并加到配置 rule 中。
CFW 的 parser 功能能够完成很多自定义，没必要将所有的需求作为固有功能，造成软件的冗余。

**Comment by akw5454521** [comment]
这个应该不适合Clash、Surge这类依赖配置文件的软件吧，加入的话反而会和自身规则冲突了
