### ISSUE TITLE
mixin中設置dns變全局代理了，正常嗎？

### ISSUE THREAD

**Issue by da-gongren** [Fndroid/clash_for_windows_pkg#1339]
有個疑問，在mixin中設置了dns，然後代理成全局了，是否正常？proxies是rule。打開百度很慢就看了下log，全是走的全局。
![image](https://user-images.githubusercontent.com/51149477/99349189-58a12400-28d6-11eb-9d64-b39464bbc7d5.png)

**Comment by yi-Xu-0100** [comment]
日志是 走的 Global 的规则？根据什么匹配的，domainsuffix? 建议给出相应的日志看看，例如

![image](https://user-images.githubusercontent.com/25523606/99359501-239ecc80-28ea-11eb-951f-e7bd8f37d046.png)

包含百度相关的。或者去日志文件截取

**Comment by XINGFUYUN** [comment]
> 日志是走的Global的规则？根据什么匹配的，domainsuffix？建议提出相应的日志看看，我的合并是这样的
> 
> ![图片](https://user-images.githubusercontent.com/25523606/99359501-239ecc80-28ea-11eb-951f-e7bd8f37d046.png)
> 
> rule是这样的
> 
> ![图片](https://user-images.githubusercontent.com/25523606/99359631-58ab1f00-28ea-11eb-87ff-60e57a1b93a5.png)
> 
> 包含百度相关的。或者去日志文件截取

![image](https://user-images.githubusercontent.com/51149477/99367698-4387bd80-28f5-11eb-91b9-5f2968858125.png)
![image](https://user-images.githubusercontent.com/51149477/99367807-5f8b5f00-28f5-11eb-862f-4b6f5af1259b.png)
![image](https://user-images.githubusercontent.com/51149477/99368022-a5482780-28f5-11eb-9485-3e742f1a5677.png)

**Comment by XINGFUYUN** [comment]
![image](https://user-images.githubusercontent.com/51149477/99368251-dde80100-28f5-11eb-9074-9f81dfb4a03a.png)

**Comment by yi-Xu-0100** [comment]
你这里的规则有问题，规则中没有对百度相关的域名进行配置到 direct，造成走的规则是 漏网之鱼，配置中的漏网之鱼指向的是节点选择，节点选择指向的是自动选择，自动选择指向的是香港节点。

以下解决办法可选择：
1. 自行添加 baidu 相关域名到规则中，设置走 direct。（parser 或者 直接修改方式）
2. 将漏网之鱼选为 direct，让没有匹配规则的不走代理。（可能会造成部分网站没有匹配规则而没走代理，却需要走代理的）
3. 告知服务商，规则问题需要更新。
4. 使用其他转换配置的软件直接替换所有的规则。

**Comment by XINGFUYUN** [comment]
> 配置文件预处理

配置文件预处理 的JavaScript不太会，没有例子呀。想设置doh和规则，yaml方式规则倒是可以了，但dns好像没生效。。。

**Comment by yi-Xu-0100** [comment]
dns 的话，还是建议使用 mixin 配置替换，parser 主要用来编辑。当然你可以尝试 yaml 中的 mix-object 和 commands。

dns 并不会觉得域名走向，只能解析域名对应 ip，如果域名由于规则走了特定代理，dns 并无法因为他是国内网站就特殊化，不太确定你指的 dns 没生效是什么样的。

如果你不太确定是否是你的配置问题，建议还是给出你自己的相应配置，方便查找问题。

如果你需要相关配置示例，在 issue 下搜索 dns 应该会有一些相关的参考。

最后，我觉得决定域名或者 ip 是否走代理的是规则，而不是 dns。dns 可能会让域名能够解析到更快的 ip 节点。(个人理解，如有错误，请指出，谢谢)

**Comment by XINGFUYUN** [comment]
> dns 的话，还是建议使用 mixin 配置替换，parser 主要用来编辑。当然你可以尝试 yaml 中的 mix-object 和 commands。
> 
> dns 并不会觉得域名走向，只能解析域名对应 ip，如果域名由于规则走了特定代理，dns 并无法因为他是国内网站就特殊化，不太确定你指的 dns 没生效是什么样的。
> 
> 如果你不太确定是否是你的配置问题，建议还是给出你自己的相应配置，方便查找问题。
> 
> 如果你需要相关配置示例，在 issue 下搜索 dns 应该会有一些相关的参考。
> 
> 最后，我觉得决定域名或者 ip 是否走代理的是规则，而不是 dns。dns 可能会让域名能够解析到更快的 ip 节点。(个人理解，如有错误，请指出，谢谢)

好的，謝謝！另外問一下，doh監聽端口是443還是53呀？

**Comment by yi-Xu-0100** [comment]
@XINGFUYUN 不太了解，不用这个，建议 Google 查下相关的内容。或者看看其他 issue 下其他人的配置。

**Comment by SplitGemini** [comment]
@XINGFUYUN 443

**Comment by akw5454521** [comment]
正常baidu不会匹配到match，把日志调到debug看看

**Comment by XINGFUYUN** [comment]
@akw5454521 debug 在哪里😂

**Comment by XINGFUYUN** [comment]
@SplitGemini 443和53好像都没用。https://ipleak.net/ 这边检测都没生效

**Comment by XINGFUYUN** [comment]
> 正常baidu不会匹配到match，把日志调到debug看看

剛剛測試了一下，適配器這
![image](https://user-images.githubusercontent.com/51149477/99935451-aec10c00-2d9b-11eb-9542-347acd55a2c0.png)
dns改119.29.29.29是正常的。改成1.1.1.1，就匹配到match了，不知什麽問題

**Comment by SplitGemini** [comment]
@XINGFUYUN 你的缩进有问题

**Comment by XINGFUYUN** [comment]
@SplitGemini 还请指点一下，我用的空格缩进的，是哪个位置少了还是多了😂

**Comment by yi-Xu-0100** [comment]
@XINGFUYUN 

```yaml
mixin: #object
  dns:
    enable: true
    enhanced-mode: redir-host
    listen: 0.0.0.0:53
    nameserver:
      - https://doh.pub/dns-query
      - https://doh.dns.sb/dns-query
  interface-name: 以太网
```

**Comment by XINGFUYUN** [comment]
@yi-Xu-0100 好的，非常感謝。另外想請教下，這個Mixin如果是JavaScript，還需要指定interface-name麽？

**Comment by yi-Xu-0100** [comment]
@da-gongren interface-name 用来开启 tap ，不用的话，把这句话省略
