### ISSUE TITLE
0.6.0 版本 config.yml 中 cfw-bypass 无效（已使用 TAP）

### ISSUE THREAD

**Issue by Hayxi** [Fndroid/clash_for_windows_pkg#134]

**Comment by Fndroid** [comment]
bypass是针对系统代理的，TAP暂时没有

**Comment by CPCer** [comment]
我按照[配置文件](https://docs.cfw.lbyczf.com/contents/configfile.html)设置了`cfw-bypass`，结果也是无效，依然走代理……

`- '*.ip38.com' # IP配置`
