### ISSUE TITLE
開啓mixin后是不是不能編輯rules了?

### ISSUE THREAD

**Issue by XINGFUYUN** [Fndroid/clash_for_windows_pkg#1340]
![image](https://user-images.githubusercontent.com/51149477/99368715-741c2700-28f6-11eb-9a3b-6bffb12190d6.png)
clash 最新版
Windows10 20H2
開啓mixin后 增加新的規則，保存會報錯。把mixin關了就不會。

**Comment by yi-Xu-0100** [comment]
mixin 使用替换方式，不适合添加规则。

parser 可能会更好用点，可以试试最新出的 commands。

parser 文档：[配置文件预处理](https://docs.cfw.lbyczf.com/contents/parser.html)

**Comment by XINGFUYUN** [comment]
> mixin使用替换方式，不适合添加规则。
> 
> parser可能会更好用点，可以尝试最新出的命令。
> 
> 解析器文档：[配置文件预](https://docs.cfw.lbyczf.com/contents/parser.html)

謝謝，可以了。
