### ISSUE TITLE
弹窗：无法切换到此配置文件；求解决

### ISSUE THREAD

**Issue by TZbeyond** [Fndroid/clash_for_windows_pkg#1341]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
2020.10.09 Premium

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
下载配置文件后不能点击切换到该配置文件

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'profiles'
2. 点击'灰色的该配置'
3. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/61233559/99487597-a9ca1a00-29a1-11eb-862a-2fcc772b4c14.png)

**其他说明**

[//]: # (其他补充内容)
个人觉得不是软件的问题，不过不是很懂，希望能帮助解决一下
配置文件相关链接：https://github.com/newcastlecy/proxypool-1

**Comment by yi-Xu-0100** [comment]
@TZbeyond 使用浏览器打开订阅链接，查看是否能够查看，检查是否是配置文件yaml的格式

**Comment by youkiey** [comment]
把网络防火墙关闭就好了
