### ISSUE TITLE
PyCharm 和 系统代理 和 Clash 的冲突问题？

### ISSUE THREAD

**Issue by JayYoung2021** [Fndroid/clash_for_windows_pkg#1342]
**信息**

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 家庭版 2004

**描述**

在 PyCharm, IDLE 使用 requests 库时，访问许多网页会出现代理错误的报错信息，在 PyCharm 里已经尝试过“不使用代理”和“自动代理“两种选项，仍然报错。只有关闭系统设置里的”代理“->”手动设置代理“后 requests 才能正确访问网页。

**复现**

1. 进入PyCharm
2. 调用 requests 库 get 'https://www.baidu.com'(https://www.google.com同样尝试过，以此为例)
3. 返回错误信息requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

**预期行为**

requests.status_code = 200

**截图**

![屏幕截图 2020-11-19 083527](https://user-images.githubusercontent.com/60842691/99605255-4c39da00-2a42-11eb-80f0-1ef10be47234.png)

**Comment by yi-Xu-0100** [comment]
1. 是否是 python 代码中关于代理设置的地址问题？
2. 是否是代理链接不稳定造成？
3. 是否是配置规则问题？
4. 是否是证书验证问题？
5. 将域名加入 bypass 再次尝试呢？

**Comment by Fndroid** [comment]
settings里把system proxy的类型改成pac试试

**Comment by JayYoung2021** [comment]
> settings里把system proxy的类型改成pac试试



> 1. 是否是 python 代码中关于代理设置的地址问题？
> 2. 是否是代理链接不稳定造成？
> 3. 是否是配置规则问题？
> 4. 是否是证书验证问题？
> 5. 将域名加入 bypass 再次尝试呢？

是代理类型的问题，已经解决了，十分感谢。

**Comment by JayYoung2021** [comment]
> settings里把system proxy的类型改成pac试试

类型改成 pac 后，浏览器访问 Google 和 PyCharm 访问网页都可以了，十分感谢。
