### ISSUE TITLE
Rule规则第一个为IP-CIDR时，Google无法连通，显示“您的连接不是私密连接”

### ISSUE THREAD

**Issue by Catnipll** [Fndroid/clash_for_windows_pkg#1345]
**信息**

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows10系统
clash_for_windows_pkg v 0.13.3 

**描述**

起因是这样的，2.2.2.2，是我这里移动Portal网络认证界面自动跳不出来以后，手动输入，然后它自己再一次跳转http://10.69.69.75打开Portal认证界面的一个手动跳转的地址。
这个地址只能直连，不能走代理，否则跳不出Portal认证界面。因为它自己跳Portal界面很难等，所以手动输入跳转很有**必要**。

于是我一直的做法是将 
- IP-CIDR,2.2.2.2/32,DIRECT   或
- IP-CIDR,2.2.2.2/32,🎯 全球直连,no-resolve
加入规则，但是每次更新都会覆盖掉，每次都得重新编辑。

在我经过一番学习[文档](https://docs.cfw.lbyczf.com/)后，在《配置文件预处理》章节找到了不用每次都手动重新编辑的方法。但是，出现了两个问题：

1、如果将“- IP-CIDR,2.2.2.2/32,DIRECT”，**用prepend-rules数组合并至原配置rules数组前，也就是rule第一个**，Google就会出现：
【您的连接不是私密连接
攻击者可能会试图从 www.google.com 窃取您的信息（例如：密码、通讯内容或信用卡信息）。了解详情
NET::ERR_CERT_AUTHORITY_INVALID】
【见图1】

别的什么诸如：YouTube、twitter、ins都正常，都能翻过去，就是Google！提示不是私密连接！2.2.2.2也是走直连正常跳Portal！

①为了区别是不是因为我自己设置Profiles-Parsers的替换的时候没有设置好，我删除了配置，重新下载，手动更改“- IP-CIDR,2.2.2.2/32,DIRECT”，为rule第一个，**测试情况依旧**。

②我记得以前是在Profiles面板里的UI里手动添加的，“- IP-CIDR,2.2.2.2/32,DIRECT”，那时候是没有Google显示“您的连接不是私密连接”这样的情况出现的。为了找出问题，我在Profiles面板里的UI手动添加，“- IP-CIDR,2.2.2.2/32,DIRECT”，add-save，然后出现提示：
【Could not switch to this profile!
    rules[1][.ssglobal.co,] error:proxy I not found     
    Edit in Text Mode                                】

【见图2】

×掉之后，去配置文件看，“- IP-CIDR,2.2.2.2/32,DIRECT”，**已写入rule，且为第一个**，关掉clash，重新打开，不但Google不是私密连接问题依旧，**Proxies面板UI里规则啥都没了，只剩下**Proxy I Debug****

【见图3】 

2、因为放到开头有问题，我就想到了那么**放到结尾怎么样**？

①我重新下载配置，手动编辑把
 ”- IP-CIDR,2.2.2.2/32,DIRECT“
放在
  - GEOIP,CN,🎯 全球直连
  - MATCH,🐟 漏网之鱼
之前，进行测试，发现一切正常，Google一切正常、翻墙一切正常、2.2.2.2走直连一切正常。**一切正常！！**

②放到结尾既然正常，我就想着用append-rules数组合并至原配置rules数组后，那不是问题就解决了吗，结果：
出现
  - GEOIP,CN,🎯 全球直连
  - MATCH,🐟 漏网之鱼
  - IP-CIDR,2.2.2.2/32,DIRECT

2.2.2.2还是走不了直连，建议大佬能不能，用append-rules数组合并至原配置rules数组后，过滤掉
  - MATCH,🐟 漏网之鱼
**有这个，在后面不管你加多少都走了MATCH啊😂**

**复现**

1. 不论是手动编辑、Profiles面板里的UI里手动添加，还是用prepend-rules数组合并至原配置rules数组前，**只要Rule规则第一个为IP-CIDR时**
2. 退出clash
3. 重启clash
4. 最终都会触发问题，**Google无法连通，显示“您的连接不是私密连接”**。其中Profiles面板里的UI里手动添加更离谱，重启clash之后直接一个规则都没有了，Proxies面板UI里规则啥都没了，**只剩下Proxy I Debug** 

**预期行为**

1、想知道为什么，只要Rule规则第一个为IP-CIDR时，Google无法连通，显示“您的连接不是私密连接”。

2、append-rules数组合并至原配置rules数组后能否进一步优化，要不然遇到这种情况，直接放最后，有MATCH在和没放一样。

**日志**
[2020.11.19日志.zip](https://github.com/Fndroid/clash_for_windows_pkg/files/5567066/2020.11.19.zip)

链接：https://pan.baidu.com/s/1onjWYhrpMZfcDdERA-EoEQ 
提取码：7qk3 
复制这段内容后打开百度网盘手机App，操作更方便哦--来自百度网盘超级会员V4的分享

**截图**
【图1】
![图一](https://user-images.githubusercontent.com/64342866/99673358-a02ed800-2aaf-11eb-8cfc-466397f3c953.png)
【图2】
![图二](https://user-images.githubusercontent.com/64342866/99673423-b89ef280-2aaf-11eb-8a5b-edf3d9c39c82.png)
【图3】
![图三](https://user-images.githubusercontent.com/64342866/99673438-bd63a680-2aaf-11eb-96b0-67c8f33c2461.png)

**其他说明**

大佬辛苦了！！！！

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/bypass.html

**Comment by yi-Xu-0100** [comment]
2.2.2.2/32 是不是有点问题？

**Comment by Catnipll** [comment]
> https://docs.cfw.lbyczf.com/contents/bypass.html

多谢大佬！！！！已经完美解决，爱您！！！！

**Comment by Fndroid** [comment]
关之前说一句，我看到日志里google的dns是127.0.0.1，所以，可能是你某些地方设置错了。

**Comment by Catnipll** [comment]
> 关之前说一句，我看到日志里google的dns是127.0.0.1，所以，可能是你某些地方设置错了。

好的好的好的，感谢您的提点！十分感谢~~~~

**Comment by yi-Xu-0100** [comment]
@Catnipll UI 设置的 bug 能复现吗？给出步骤截图看看，我这边好像没法触发。

[最新的版本](https://github.com/Fndroid/clash_for_windows_pkg/releases)支持使用 commands 删除倒数的。(v0.13.4)

```yaml
parsers:
  - reg: https://www.example.com/
    yaml:
      append-rules:
        - IP-CIDR,2.2.2.2/32,DIRECT
        - MATCH,🐟 漏网之鱼
      commands:
        - rules.(-3)-
```

注意：commands 会在最后执行，即使你放置在前面。

**Comment by Catnipll** [comment]
> @Catnipll UI 设置的 bug 能复现吗？给出步骤截图看看，我这边好像没法触发。
> 
> [最新的版本](https://github.com/Fndroid/clash_for_windows_pkg/releases)支持使用 commands 删除倒数的。(v0.13.4)
> 
> ```yaml
> parsers:
>   - reg: https://www.example.com/
>     yaml:
>       append-rules:
>         - IP-CIDR,2.2.2.2/32,DIRECT
>         - MATCH,🐟 漏网之鱼
>       commands:
>         - rules.(-3)-
> ```
> 
> 注意：commands 会在最后执行，即使你放置在前面。

谢谢谢谢大佬，奇了怪了，我刚才尝试复现，试了4次都没有成功......这就是出了问题等解决问题大佬来，绝对恢复正常的定律吗，欲哭无泪，😂

**Comment by Ericwonne** [comment]
我也遇到了这个问题，不过是访问国内网站的时候，尝试clash上的各种设置，最后发现是不小心打开了IPV6这个选项，关掉之后，就好了

![image](https://user-images.githubusercontent.com/12907709/210985230-8bb21877-ee7a-4714-b355-bdb0fc8e2c4b.png)

**Comment by Seraphli** [comment]
版本号：
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/1586755/340877b1-f7fe-4cb5-883a-94d003e88e9e)

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/1586755/c9b9fcc7-ea51-4359-8f4c-98dba8c51a47)

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/1586755/3a1ca6af-59be-4a49-9793-54f478f8410c)

如果使用prepend-rules就会出现问题，但是改成append-rules就没有问题
