### ISSUE TITLE
我使用clash for windows 做了一个透明的VPN，想要设置用户验证怎么做

### ISSUE THREAD

**Issue by kachacha** [Fndroid/clash_for_windows_pkg#1346]
**描述**
我使用clash for windows 做了一个透明的VPN，想要设置用户验证怎么做

**其他说明**
我使用clash for windows 做了一个透明的VPN，想要设置用户验证怎么做

**Comment by Fndroid** [comment]
“透明的VPN”？

**Comment by kachacha** [comment]
> “透明的VPN”？

将 clash for windows 放在了服务器，外网通过端口代理；那么怎么在这个代理加个用户名密码验证呢

**Comment by Fndroid** [comment]
配置文件里加上
```yaml
authentication:
   - "user1:pass1"
   - "user2:pass2"
```

**Comment by kachacha** [comment]
> 配置文件里加上
> 
> ```yaml
> authentication:
>    - "user1:pass1"
>    - "user2:pass2"
> ```

谢谢，就是这个。

**Comment by Antisunny** [comment]
点击General -> Minxin的“⛭”，切换成YAML格式，输入

```
mixin:
  authentication:
    - "admin:sdfsdgrty345rehiutyqweqfustdfsb"
    - "user1:sdteruiw7ergtsdf543sfdsudivfbds"
```
