### ISSUE TITLE
未启用tap模式时，后台仍然约3秒运行一次route.exe

### ISSUE THREAD

**Issue by codehz** [Fndroid/clash_for_windows_pkg#1349]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Microsoft Windows [Version 10.0.20262.1]
cfw 0.13.3

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
通过性能分析器测试，发现在一天内route.exe启动了约28800次（已关闭tap模式，通过卸载驱动），即使是为了探测有效接口而言，这个频率也似乎太高了。。。

**复现**

[//]: # (请描述复现问题的步骤)

0. 启动虚拟机，确保只安装了一个cfw应用程序，关闭系统更新和各种定期运行的程序
1. 安装clash for windows，填上连接宿主代理的配置（仅主机网络），并开启关闭tap模式一次，最后将tap驱动卸载（通过界面），然后保持软件运行
2. 打开etw性能计数器
3. 等待任意时间
4. 然后获取分析结果，就是非常精确3秒一次route.exe运行。。。

**预期行为**

[//]: # (清晰地描述期望看到的行为)
在关闭tap模式的情况下不应该定期调用route。

**日志**

[//]: # (上传触发问题对应的日志文件)
（和网络活动无关）
（开头的日志不包含tap相关信息，只有正常的 Start initial compatible provider Proxy / RESTful API listening at: 127.0.0.1:9090 等）

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/13158903/99775562-71197480-2b4a-11eb-939f-1e5ce91d42be.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
