### ISSUE TITLE
如何减少内存占用

### ISSUE THREAD

**Issue by hdzhx** [Fndroid/clash_for_windows_pkg#1353]
好用，macos也装了但测速很奇怪，同一个机场macos下可用节点明显少。
一个无法承受的是macos中占用内存高达234M，然后发热（当然机器比较旧，其实满足了），有没有可能简化一点，体积小一点，内存占用少一点。谢谢您的贡献，好棒的软件。

**Comment by hdzhx** [comment]
macos下是這樣

**Comment by yi-Xu-0100** [comment]
@hdzhx 感觉减少大小有点难，毕竟是 electron 😏

**Comment by Fndroid** [comment]
不能

**Comment by timeneverdie** [comment]
Electron所制作的软件内存占用普遍是100M起步，两三百M都算对得起你了。
如果想要减少内存占用，可以考虑ClashWeb，内存占用10M以内，不过暂时只有Windows版本。
