### ISSUE TITLE
how to use custom geosite.dat to block ads

### ISSUE THREAD

**Issue by fsheidaiee** [Fndroid/clash_for_windows_pkg#1356]
Hi
in v2ray I use geosite.dat from there
https://github.com/Loyalsoldier/v2ray-rules-dat
then I write in blocking section;
geosite:category-ads-all
is there similar feature in clash to block ads this simple from a geosite.dat file?
thanks

**Comment by Fndroid** [comment]
no

**Comment by fsheidaiee** [comment]
> no

I Could do it with rule provider after some search
