### ISSUE TITLE
direct timeout

### ISSUE THREAD

**Issue by da-gongren** [Fndroid/clash_for_windows_pkg#1357]
系統dns設置為1.1.1.1，direct 顯示 time out 怎麽解決呀？經常這樣，改大陸的就沒這問題，是不是這dns被墻了的原因？
![image](https://user-images.githubusercontent.com/51149477/99928605-cb9e1500-2d84-11eb-9a63-13d0dcc44f3d.png)
![image](https://user-images.githubusercontent.com/51149477/99928610-cf319c00-2d84-11eb-8c26-9c56dfe08a58.png)

**Comment by yi-Xu-0100** [comment]
@XINGFUYUN 你是怎么设置的 dns？设置地方和设置过程

**Comment by XINGFUYUN** [comment]
> @XINGFUYUN 你是怎么设置的 dns？设置地方和设置过程

![image](https://user-images.githubusercontent.com/51149477/99930680-deb4e300-2d8c-11eb-80f9-7b288dd58b1e.png)
这边设置的

**Comment by yi-Xu-0100** [comment]
@XINGFUYUN 是否启用 mixin 或者 tap？

**Comment by akw5454521** [comment]
之前有听说用这个DNS会被劫持然后返回投毒的内容，所以有问题就别用这个了，想在大陆用没污染的DNS不太现实，Clash一般不会受到污染的影响，我一直都是用的系统(ISP)的DNS也没什么问题

**Comment by XINGFUYUN** [comment]
> @XINGFUYUN 是否启用 mixin 或者 tap？
> 
> 是否 这个 1.1.1.1 被内网占用了

应该没，我们内网没这个段。没启用mixin和tap。只设置了parsers（加了些rule），start with windows，system proxy，uwp loopback全选。
![image](https://user-images.githubusercontent.com/51149477/100458907-84ef4880-30ff-11eb-883b-2cf5b3de8bf1.png)

**Comment by XINGFUYUN** [comment]
@yi-Xu-0100 现在没这么设置了。系统dns那边没设置了，在clash配了doh，不知起作用没😂小白一个，先这么用了

**Comment by da-gongren** [comment]
@yi-Xu-0100 好像是設置非大陸的dns，就會出現這問題！

**Comment by yi-Xu-0100** [comment]
@da-gongren 有参考价值，可能是 dns 地址无法访问吧

**Comment by AkariiinMKII** [comment]
找到你的test URL对比nslookup返回值即可

**Comment by da-gongren** [comment]
@AkariiinMKII `http://www.gstatic.com/generate_204` 是上海的IP

**Comment by AkariiinMKII** [comment]
> @AkariiinMKII `http://www.gstatic.com/generate_204` 是上海的IP

![Snipaste_2020-12-12_17-20-39](https://user-images.githubusercontent.com/6019344/101980158-788df280-3c9e-11eb-86d4-826ec8d66da3.png)

**Comment by da-gongren** [comment]
@AkariiinMKII 清楚了。
1. 可能 dns 无法访问
2. 解析到了美国的 IP
