### ISSUE TITLE
无法安装 TAP

### ISSUE THREAD

**Issue by Yves3** [Fndroid/clash_for_windows_pkg#136]
点击 Install TAP Device 之后，会弹窗是否允许命令行程序允许，允许后，Clash 左下角状态会变为 Installing TAP Device，但几秒后，什么事情都不会发生，左下角状态会重新变为 Connected to Clash，右侧列表的 TAP Device 也仍然是 Install。

使用 0.6.0 正式版 exe 安装，已尝试重启电脑、卸载重装 Clash，未能解决问题。

**Comment by Fndroid** [comment]
TAP状态在网络连接里查看

**Comment by Yves3** [comment]
网络连接里 cfw-tap 显示为：网络电缆被拔出

**Comment by Fndroid** [comment]
http://t.cn/Ai0d0Lyt

**Comment by ZhouDongDong123** [comment]
@Fndroid 兄弟这个问题解决了吗？？

**Comment by ZhouDongDong123** [comment]
@Fndroid 兄弟这个问题解决了吗？？

**Comment by lvhe19880210** [comment]
一样的问题

**Comment by 4SM** [comment]
解决了吗？我的也无法安装

**Comment by lvhe19880210** [comment]
我的解决了 注意严格按照作者介绍的新版tap设置就行
