### ISSUE TITLE
BYPASS这两种写法，哪种是对的？

### ISSUE THREAD

**Issue by echo860** [Fndroid/clash_for_windows_pkg#1360]
https://imgur.com/pruerEU
一种是引号
另一种引号，还在域名之前加. *（点+星号），好像是* .（星号+点）

**Comment by yi-Xu-0100** [comment]
官方文档：<https://docs.microsoft.com/en-us/troubleshoot/browsers/use-proxy-servers-with-ie#more-information>

根据文档得知，只能使用 `*` 匹配未知字符。而在 cfw 的解析过程中，由于 `yaml` 的语法规则限制，需要对包含 `*` 的条目使用引号包裹，单引号或者双引号都行（个人 `win10` 测试下结果一致）。

部分示例：

1. 匹配以`baidu.com`, `www.baidu.com`. 等以 `baidu.com` 为结尾的域名

```yaml
bypass:
  - "*baidu.com"
```

2. 不匹配`baidu.com`, 匹配 `www.baidu.com`, `wenku.baidu.com` 等以 `baidu.com` 为根域名的三级域名（四级及以上未测试）

```yaml
bypass:
  - "*.baidu.com"
```

3. 仅匹配 `baidu.com` 的域名

```yaml
bypass:
  - baidu.com  #此时可不加引号，加上也无妨
```

**注意，如果不走代理，仍然会走 `dns` ，如果系统的 `dns` 的解析有误，仍然可能访问有误。**

**Comment by Chi1ld** [comment]
在我使用*baidu.com这个语法的时候，如果访问了iiiiibaidu.com，他会匹配吗？

**Comment by Chi1ld** [comment]
> 官方文档：https://docs.microsoft.com/en-us/troubleshoot/browsers/use-proxy-servers-with-ie#more-information
> 
> 根据文档得知，只能使用 `*` 匹配未知字符。而在 cfw 的解析过程中，由于 `yaml` 的语法规则限制，需要对包含 `*` 的条目使用引号包裹，单引号或者双引号都行（个人 `win10` 测试下结果一致）。
> 
> 部分示例：
> 
> 1. 匹配以`baidu.com`, `www.baidu.com`. 等以 `baidu.com` 为结尾的域名
> 
> ```yaml
> bypass:
>   - "*baidu.com"
> ```
> 
> 2. 不匹配`baidu.com`, 匹配 `www.baidu.com`, `wenku.baidu.com` 等以 `baidu.com` 为根域名的三级域名（四级及以上未测试）
> 
> ```yaml
> bypass:
>   - "*.baidu.com"
> ```
> 
> 3. 仅匹配 `baidu.com` 的域名
> 
> ```yaml
> bypass:
>   - baidu.com  #此时可不加引号，加上也无妨
> ```
> 
> **注意，如果不走代理，仍然会走 `dns` ，如果系统的 `dns` 的解析有误，仍然可能访问有误。**
如果我用*baidu.com，那么遇到一个iiiiibaidu.com，他会匹配吗？

**Comment by yi-Xu-0100** [comment]
@Chi1ld 使用 `*baidu.com` 可以匹配 `iiiiibaidu.com`

**Comment by Chi1ld** [comment]
> 

我想匹配baidu.com和*.baidu.com，只能同时写两条规则吗？

**Comment by yi-Xu-0100** [comment]
@Chi1ld 看示例第一个

**Comment by 1024zzq** [comment]
> 官方文档：https://docs.microsoft.com/en-us/troubleshoot/browsers/use-proxy-servers-with-ie#more-information
> 
> 根据文档得知，只能使用 `*` 匹配未知字符。而在 cfw 的解析过程中，由于 `yaml` 的语法规则限制，需要对包含 `*` 的条目使用引号包裹，单引号或者双引号都行（个人 `win10` 测试下结果一致）。
> 
> 部分示例：
> 
> 1. 匹配以`baidu.com`, `www.baidu.com`. 等以 `baidu.com` 为结尾的域名
> 
> ```yaml
> bypass:
>   - "*baidu.com"
> ```
> 
> 2. 不匹配`baidu.com`, 匹配 `www.baidu.com`, `wenku.baidu.com` 等以 `baidu.com` 为根域名的三级域名（四级及以上未测试）
> 
> ```yaml
> bypass:
>   - "*.baidu.com"
> ```
> 
> 3. 仅匹配 `baidu.com` 的域名
> 
> ```yaml
> bypass:
>   - baidu.com  #此时可不加引号，加上也无妨
> ```
> 
> **注意，如果不走代理，仍然会走 `dns` ，如果系统的 `dns` 的解析有误，仍然可能访问有误。**

第一条示例真的难理解，像Nginx都是第二条示例就行了（也能包括baidu.com）。踩坑严重

**Comment by bigreybear** [comment]
> 官方文档：https://docs.microsoft.com/en-us/troubleshoot/browsers/use-proxy-servers-with-ie#more-information
> 
> 根据文档得知，只能使用 `*` 匹配未知字符。而在 cfw 的解析过程中，由于 `yaml` 的语法规则限制，需要对包含 `*` 的条目使用引号包裹，单引号或者双引号都行（个人 `win10` 测试下结果一致）。
> 
> 部分示例：
> 
> 1. 匹配以`baidu.com`, `www.baidu.com`. 等以 `baidu.com` 为结尾的域名
> 
> ```yaml
> bypass:
>   - "*baidu.com"
> ```
> 
> 2. 不匹配`baidu.com`, 匹配 `www.baidu.com`, `wenku.baidu.com` 等以 `baidu.com` 为根域名的三级域名（四级及以上未测试）
> 
> ```yaml
> bypass:
>   - "*.baidu.com"
> ```
> 
> 3. 仅匹配 `baidu.com` 的域名
> 
> ```yaml
> bypass:
>   - baidu.com  #此时可不加引号，加上也无妨
> ```
> 
> **注意，如果不走代理，仍然会走 `dns` ，如果系统的 `dns` 的解析有误，仍然可能访问有误。**

@yi-Xu-0100 您好，请问“仍然会走 dns” 是指仍然会通过 配置文件 设置的 dns 拿 ip 吗？或者说，“绕开”功能是否应该配合在配置文件中增加本地的 dns ？

**Comment by KeenShady** [comment]
只能跳过指定的域名，不能跳过指定的ip地址吗
