### ISSUE TITLE
360报高危事件

### ISSUE THREAD

**Issue by serfend** [Fndroid/clash_for_windows_pkg#1361]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ x ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ x ] 已经尝试更新到最新版本，问题依旧存在
- [ x ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

**描述**
应事先提醒的权限而未提醒直接执行，可参见[issue1096](https://github.com/Dreamacro/clash/issues/1096)
[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 打开`360`
2. 打开`CFW`
3. 等待片刻
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/20139227/100033325-f647a680-2e34-11eb-8613-55b3a95f7a53.png)
![image](https://user-images.githubusercontent.com/20139227/100033333-fba4f100-2e34-11eb-90a7-a154c1bd4f00.png)
![image](https://user-images.githubusercontent.com/20139227/100033338-fe9fe180-2e34-11eb-98c0-99380d6c1d66.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
Duplicate of #1228

建议立即删除软件！🤣

**Comment by yi-Xu-0100** [comment]
抱歉，好像没注意到触发的并不是核心，虽然我不知道 route 是干啥的，但是似乎有着过于频繁的问题，相关 issue： #1349

**Comment by serfend** [comment]
确实也存在频繁请求的问题，用抓包软件可以看到后台在一直请求config.json，且每次都是405无效信息
![image](https://user-images.githubusercontent.com/20139227/100065365-a7b6fe00-2e6e-11eb-8a9f-1f60b614109e.png)
![image](https://user-images.githubusercontent.com/20139227/100065405-b4d3ed00-2e6e-11eb-8c7b-8bbe0fe4f6c9.png)

**Comment by Fndroid** [comment]
> 应事先提醒的权限而未提醒直接执行，可参见issue1096

360报这个是执行命令``route print``的，在系统看来，就不是什么危险操作，如果是，早就弹出来UAC了。

> 确实也存在频繁请求的问题，用抓包软件可以看到后台在一直请求config.json，且每次都是405无效信息

这是在请求核心获取状态，有什么问题么？

**Comment by serfend** [comment]
获取到的script每次都是405没有内容，是否意味着黑客修改script为其他代码时，则会自动执行此任意代码【高危】

**Comment by yi-Xu-0100** [comment]
@serfend 我想如果黑客可以修改你电脑中的 script 时，基本也能在你的电脑中执行任何代码了。和有没有其他的软件无关……

**Comment by e71828** [comment]
请问 qq保护进程 会干掉这个么， 今天运行了tim 然后第一次页出现了内核崩溃 无法连接

**Comment by yi-Xu-0100** [comment]
@e71828 一直使用 tim ，没有问题
