### ISSUE TITLE
rule是空白的 什么都没有

### ISSUE THREAD

**Issue by 992939504** [Fndroid/clash_for_windows_pkg#1363]
已经导入了Profiles 旧版本有列表 但都是timeout
新版本rule是空白的 什么都没有
版本是0.13.4

**Comment by yi-Xu-0100** [comment]
@992939504 
1. 旧版本是哪个版本?
2. 是否是因为关键词出问题，参考 #1072
3. 备份相关设置文件，然后删除 `Home Directory` 对应的目录 `C:\Users\用户\.config\clash`，看看效果如何
4. 参考 #1066 尝试修复
5. 给出日志和截图可以更好的确定问题

**Comment by 992939504** [comment]
> @992939504
> 
> 1. 旧版本是哪个版本?
> 2. 是否是因为关键词出问题，参考 #1072
> 3. 备份相关设置文件，然后删除 `Home Directory` 对应的目录 `C:\Users\用户\.config\clash`，看看效果如何
> 4. 参考 #1066 尝试修复
> 5. 给出日志和截图可以更好的确定问题

通过#1092的办法解决了问题 不过所有节点依然是timeout  排除了是机场本身的问题 在V2rayN上可以正常使用

**Comment by yi-Xu-0100** [comment]
@992939504 可以参考 #1128 试试相关解决办法尝试修复

**Comment by 992939504** [comment]
> @992939504 可以参考 #1128 试试相关解决办法尝试修复
解决了 感谢
