### ISSUE TITLE
clash偶尔出现无法打开代理，加载不了config.yaml文件，try to repair无效

### ISSUE THREAD

**Issue by wmjgh** [Fndroid/clash_for_windows_pkg#1365]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ x] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # win10 20h2
![image](https://user-images.githubusercontent.com/52828616/100330637-2f853f80-300a-11eb-9147-70074b2ef0db.png)

**描述**

[//]: # clash无法打开代理，加载不了config.yaml文件，try to repair无效

**复现**偶尔重新开机后就会出现，无法每次都复现

[//]: # (请描述复现问题的步骤)

开机后clash出现这个画面
![image](https://user-images.githubusercontent.com/52828616/100330315-c6053100-3009-11eb-812f-a7d20d3a24c2.png)

**日志**
time="2020-11-26T16:49:07+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-11-26T16:49:07+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-11-26T16:49:07+08:00" level=error msg="Start Mixed(http and socks5) server error: listen tcp 127.0.0.1:7890: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2020-11-26T16:49:07+08:00" level=error msg="External controller error: listen tcp 127.0.0.1:9090: bind: An attempt was made to access a socket in a way forbidden by its access permissions."

[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/52828616/100330381-da492e00-3009-11eb-8d7b-d5adf6f1370e.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)
我的解决方法是重置网络然后重启电脑，有时重启一次不行，偶尔要2到3次重启才恢复正常

**Comment by Fndroid** [comment]
7890和9090两个端口都被占用了，修改General YAML里对应的值

**Comment by wmjgh** [comment]
好的，谢谢

**Comment by wmjgh** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Fndroid"<notifications@github.com&gt;; 
发送时间: 2020年11月26日(星期四) 下午5:13
收件人: "Fndroid/clash_for_windows_pkg"<clash_for_windows_pkg@noreply.github.com&gt;; 
抄送: "Micah"<1617424272@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Fndroid/clash_for_windows_pkg] clash偶尔出现无法打开代理，加载不了config.yaml文件，try to repair无效 (#1365)





 
7890和9090两个端口都被占用了，修改General YAML里对应的值
