### ISSUE TITLE
运行CFW后程序无法和Clash core连接，疑似9090端口占用问题

### ISSUE THREAD

**Issue by Ericir3** [Fndroid/clash_for_windows_pkg#1366]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
发现重复问题且未解决：
https://github.com/Fndroid/clash_for_windows_pkg/issues/1248#issue-724197264
https://github.com/Fndroid/clash_for_windows_pkg/issues/1248#issuecomment-729515670
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 10 专业版 20H2 19042.630 Windows Feature Experience Pack 120.2212.31.0

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
双击运行CFW后显示：
Could not connect to Clash Core
程序无法正常使用

已查找本地端口占用情况，未发现任何程序占用9090端口
尝试修改config.yaml将`external-controller: '127.0.0.1:9090'`改为任意未占用端口，都无法使用，相同报错

**复现**

[//]: # (请描述复现问题的步骤)

双击运行后触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)
程序正常运行

**日志**

[//]: # (上传触发问题对应的日志文件)
time="2020-11-26T14:49:56Z" level=info msg="Start initial compatible provider Proxy"
time="2020-11-26T14:49:56Z" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-11-26T14:49:56Z" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2020-11-26T14:49:56Z" level=error msg="External controller error: listen tcp 127.0.0.1:9090: bind: An attempt was made to access a socket in a way forbidden by its access permissions."

**截图**

[//]: # (如果可以，请提供对应问题的截图)
无

**其他说明**

[//]: # (其他补充内容)
无

**Comment by yi-Xu-0100** [comment]
@Ericir3 新的端口是啥，新的日志是修改成功了吗？

```log
time="2020-11-26T14:49:56Z" level=error msg="External controller error: listen tcp 127.0.0.1:端口: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
```

**Comment by Ericir3** [comment]
> @Ericir3 新的端口是啥，新的日志是修改成功了吗？
> 
> ```
> time="2020-11-26T14:49:56Z" level=error msg="External controller error: listen tcp 127.0.0.1:端口: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
> ```

随便改一个端口，都是报这个错误`External controller error: listen tcp 127.0.0.1:端口`，不能使用，电脑重启后也不能使用

**Comment by yi-Xu-0100** [comment]
你使用的什么命令去查看端口占用的？我是在 powershell 使用下面的命令查看的，没有输出则没有任何占用。

```powershell
netstat -aon|findstr "9090"
```
在 cfw 启动的情况下显示如下内容：
```powershell
  TCP    127.0.0.1:9090         0.0.0.0:0              LISTENING       20920
  TCP    127.0.0.1:9090         127.0.0.1:13340        ESTABLISHED     20920
  TCP    127.0.0.1:9090         127.0.0.1:13341        ESTABLISHED     20920
  TCP    127.0.0.1:13340        127.0.0.1:9090         ESTABLISHED     11184
  TCP    127.0.0.1:13341        127.0.0.1:9090         ESTABLISHED     11184
```

**Comment by echo860** [comment]
怎么我的端口是7890，跟你的不一样？ 在哪里改端口？

**Comment by yi-Xu-0100** [comment]
@echo860 
 ```log
time="2020-11-26T14:49:56Z" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2020-11-26T14:49:56Z" level=error msg="External controller error: listen tcp 127.0.0.1:9090: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
```
7890 是默认代理端口，9090 是 External controller 的端口。更改的话，在 config.yaml 中修改。

@Ericir3 #907 可参考

**Comment by echo860** [comment]
> @echo860
> 
> ```
> time="2020-11-26T14:49:56Z" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
> time="2020-11-26T14:49:56Z" level=error msg="External controller error: listen tcp 127.0.0.1:9090: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
> ```
> 
> 7890 是默认代理端口，9090 是 External controller 的端口。更改的话，在 config.yaml 中修改。
> 
> @Ericir3 #907 可参考

改端口有什么好处？我看教程说最好不要改端口。

**Comment by yi-Xu-0100** [comment]
@echo860 端口被占用，需要更改，或者个人需求吧，所以说，最好不改。

**Comment by Fndroid** [comment]
下载最新的0.13.6，新增的动态端口应该会改善这个问题
