### ISSUE TITLE
藍奏雲打不開

### ISSUE THREAD

**Issue by XINGFUYUN** [Fndroid/clash_for_windows_pkg#1367]
rule 藍奏云打不開，切直連也一樣，什麽原因？
![image](https://user-images.githubusercontent.com/51149477/100401048-50de3e00-3093-11eb-899d-4a716d083921.png)

**Comment by yi-Xu-0100** [comment]
@XINGFUYUN 试试加到 bypass 试试

**Comment by XINGFUYUN** [comment]
@yi-Xu-0100 額  好了，感謝！
