### ISSUE TITLE
Failed to fetch ruleset or ruleset is empty

### ISSUE THREAD

**Issue by ztjal** [Fndroid/clash_for_windows_pkg#1368]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

win10x64

v 0.13.5

[//]: # (平台及版本号)

**描述**

一直使用SubConverter作规则转换，一直都没问题，一切都【很快】就完成了，截至 v 0.13.0 版。

今天更新一下，使用最新的 v 0.13.5 ，一更新规则，SubConverter打印日志【很很很慢地】显示出每一行，最后显示几个自定的规则为，例如：
2020/11/27 Fri 15:35:40.103061 [10288 21][WARN] Failed to fetch ruleset or ruleset is empty: 'http://192.168.8.11/clash/myblock.list'!
2020/11/27 Fri 15:41:34.510127 [10288 22][ERRO] Load external configuration failed. Reason: line 0: Empty document

[//]: # (请具体并清楚地描述遇到的问题)

**其他说明**

经研究，发现新版对以“#”开头的注释一行的支持出现问题，一个文本里的第二或第三个注释之后的行的规则不会被添加到成生的规则里边。

例如我这个myblock.list，直接不认文本，在旧的v 0.13.0上，完全没有问题。
[myblock.zip](https://github.com/Fndroid/clash_for_windows_pkg/files/5606676/myblock.zip)

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
@ztjal 应该去 SubConverter 提问吧，它转换完给 cfw 才对，转换的不对，也不是 cfw 的问题。

**Comment by ztjal** [comment]
> 
> 
> @ztjal 应该去 SubConverter 提问吧，它转换完给 cfw 才对，转换的不对，也不是 cfw 的问题。

在旧的v 0.13.0上，完全没有问题。在v 0.13.5上就出问题，我不找这边找谁？

**Comment by yi-Xu-0100** [comment]
@ztjal 所以你应该检查下生成后的配置文件，生成的配置文件一样吗？如果配置文件一样，那指定的 rule-providers 内容一样吗？

**Comment by yi-Xu-0100** [comment]
@ztjal 你给出的文件不符合 rule-providers 所需文件的格式要求，所以我觉得是 subconverter 的中间文件，而不是最终文件，所以处理也应该是 subconverter 的问题了。

**Comment by ztjal** [comment]
> 
> 
> @ztjal 你给出的文件不符合 rule-providers 所需文件的格式要求，所以我觉得是 subconverter 的中间文件，而不是最终文件，所以处理也应该是 subconverter 的问题了。

subconverter的配置一直都一样，什么都没改动。
这只是其中的一个
surge_ruleset=🛑 全球拦截,http://192.168.8.11/clash/myblock.list

在旧的v 0.13.0上，完全没有问题。换到v 0.13.5上就出问题，我现在用回旧版了，问题我都研究好了，就是“#”开头的注释问题，就这样。

**Comment by yi-Xu-0100** [comment]
@ztjal 两个版本 cfw 调用配置文件内容是否相同？

**Comment by ztjal** [comment]
> 
> 
> @ztjal 两个版本 cfw 调用配置文件内容是否相同？

当然相同，我自己先找问题，确定问题在那才来报告的。

**Comment by yi-Xu-0100** [comment]
@ztjal 

> 经研究，发现新版对以“#”开头的注释一行的支持出现问题，一个文本里的第二或第三个注释之后的行的规则不会被添加到成生的规则里边。

1. 我看了你的描述，你指出部分自定义规则不会被包含？那两个配置文件应该不同。
2. 如果配置文件相同，那你是如何判断部分规则未生效的？还是代理无法生效，cfw 的相关日志可以给出吗？

>
```log
2020/11/27 Fri 15:35:40.103061 [10288 21][WARN] Failed to fetch ruleset or ruleset is empty: 'http://192.168.8.11/clash/myblock.list'!
2020/11/27 Fri 15:41:34.510127 [10288 22][ERRO] Load external configuration failed. Reason: line 0: Empty document
```
3. 这里的日志是 subconverter 给出的，不是 cfw 给出的，是否是 subconverter 未获取到该本地的文件。这里不会是 cfw 去获取你的 myblock.list 这个文件。

**Comment by ztjal** [comment]
> 
> 
> @ztjal 两个版本 cfw 调用配置文件内容是否相同？

我刚刚从 Clash.for.Windows-0.13.1-win 至 0.13.5 下载回来，按版本从底到高，运行程序并手动点击更新规则试了一偏，0.13.5的问题没有再复现了。（？）
0.13.5也好好的一下就完成更新规则了。（？！）
我什么都没动过……路由也没搞过，更没重启过。（？！）
现在也在用0.13.5。

那些日志是subconverter给出的，文件就在路由器上，可以直接通过浏览器下载。
但那时问题是，用0.13.0是正常的，用0.13.5就不正常，两个分别解压放在不同的文件夹里，只要直接运行程序，手动点击更新规则就是了。

我现在的状态是（？！），抱歉，看来先关闭这个issue吧，再有情况的话我研究下再回来回复吧。
