### ISSUE TITLE
关于Clash for windows ping节点延迟很高的问题

### ISSUE THREAD

**Issue by yorkzhy** [Fndroid/clash_for_windows_pkg#137]
同样的节点手机Quantumult和电脑ping的值完全不一样

**Comment by Fndroid** [comment]
测试方式：
Clash : **代理一个HTTP/GET请求并收到响应的总时间**
Quantumult : TCP Dial用时 及 **代理一个HTTP/HEAD请求并收到响应的总时间**

说明：
1. Quantumlt有两种测速方式，但是第二种更加准确
2. Clash和Quantumult的HTTP测速原理相同，只是请求使用的方法不一样，如果测试使用的URL是``http://www.gstatic.com/generate_204``，那么两者延迟基本是一样的
3. 如果要更改界面中测速所用URL，需要在Home Directory目录下config.yml中加入cfw-latency-url字段

**Comment by yorkzhy** [comment]
感谢F大回复~ 请问加入cfw-latency-url字段怎么配置呢
![QQ截图20190705094703](https://user-images.githubusercontent.com/14953362/60693312-6b4ad100-9f0c-11e9-8a27-cfd6b3fd8dcb.png)

**Comment by yorkzhy** [comment]
感谢F大 懂了~
