### ISSUE TITLE
rules编辑器错误

### ISSUE THREAD

**Issue by 4512369781** [Fndroid/clash_for_windows_pkg#1374]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
win10 专业版 18363.1237
cfw v0.13.5

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
首次打开cfw，然后进入 Edit rules 界面，点击Save，就会弹出错误，见图片。
但是，第一次打开 Edit rules 界面，如果直接点击Cancel，再次进入，点击Save，则不会弹出错误。

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'cfw'-'Profiles'-'Edit rules'
2. 点击'Save'
3. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)
正确保存。

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)
弹出错误：
![屏幕截图 2020-11-29 222435](https://user-images.githubusercontent.com/30334394/100545230-c9ace800-3295-11eb-8faf-6a8ecf0a5e1c.jpg)

被错误修改的配置文件：
![屏幕截图 2020-11-29 224847](https://user-images.githubusercontent.com/30334394/100545236-cf0a3280-3295-11eb-850c-374fd3ce925e.jpg)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
@Fndroid 可复现，**重启软件**第一次使用 edit rule，保存会触发，会删除第一条规则的关键词，给第一条规则加上 `""`, 第二次保存后，删除错误的第一条规则，之后的保存不再报错。

#1345 当时应该有触发该问题，我测试的时候触发一次，再也没触发（未重启），以为是个人配置问题，一直没有复现。应该当时和这里的状况一样，只会在重启后触发一次。

如果第一次不是直接保存，添加条目后保存，不会删除添加的条目，而是会删除原来的规则的第一条的关键词，后续和上述情况一样。

**Comment by yi-Xu-0100** [comment]
@4512369781 建议使用 parser 对规则进行添加，edit rule 界面编辑后，在配置文件更新后会被重置。

parser 文档：<https://docs.cfw.lbyczf.com/contents/parser.html>

**Comment by 4512369781** [comment]
@yi-Xu-0100 最开始就是添加后保存出现的问题，写好了反馈准备提交的时候，又想到如果不添加直接保存会不会触发，于是最后就只写了这一种情况。
多谢，parser 还没有用过。

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
