### ISSUE TITLE
使用USB转RJ45转换器，系统代理无效。

### ISSUE THREAD

**Issue by lluke2** [Fndroid/clash_for_windows_pkg#1377]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**
使用USB转RJ45转换器，系统代理无效。
[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
WIN10 ,CFW 0.13.5
[//]: # (平台及版本号)

**描述**
使用USB转RJ45转换器，系统代理无效。
[//]: # (请具体并清楚地描述遇到的问题)

**复现**
使用USB转RJ45转换器，系统代理无效。在浏览器中用插件使用cfw开启的代理，能够正常使用翻墙。
[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
@lluke2 确定打开系统代理了吗，在系统代理设置那里看看？有没有日志？浏览器配置系统代理了吗？是拨号上网吗？拨号上网的名称是英文吗？tap 试试呢？

**Comment by lluke2** [comment]
感谢，我删去bypass部分之后，就正常了，非常感谢，
