### ISSUE TITLE
打开clash后端口port为0是什么原因？

### ISSUE THREAD

**Issue by wmjgh** [Fndroid/clash_for_windows_pkg#1379]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ x] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

win10 1909 
clash版本为0.13.5

[//]: # (请具体并清楚地描述遇到的问题)
打开clash后端口port为0，无法代理

[//]: # (清晰地描述期望看到的行为)
访问国内网站正常，访问国外网站失败

[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/52828616/100722784-f11dc500-33fb-11eb-9350-fcdcbae25ee1.png)

![image](https://user-images.githubusercontent.com/52828616/100723157-62f60e80-33fc-11eb-9fdb-94184e3eab74.png)
![image](https://user-images.githubusercontent.com/52828616/100723201-70ab9400-33fc-11eb-9569-43cda000028a.png)

![image](https://user-images.githubusercontent.com/52828616/100723596-ec0d4580-33fc-11eb-8d97-2c537f50aec5.png)

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/52828616/100722761-eb27e400-33fb-11eb-9099-dfc5c3014299.png)
![image](https://user-images.githubusercontent.com/52828616/100723834-368ec200-33fd-11eb-8794-653ecb21e08b.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by wmjgh** [comment]
改端口重启好了。奇怪的是，并没有查到是哪个进程占用了7890端口，很奇怪

**Comment by yi-Xu-0100** [comment]
Duplicate of #671

**Comment by easyinplay** [comment]
[x] 已经从 issue 搜索过类似问题，并未发现重复 

？？？？
