### ISSUE TITLE
socks5不支持udp转发

### ISSUE THREAD

**Issue by sjdjfcu** [Fndroid/clash_for_windows_pkg#138]
![image](https://user-images.githubusercontent.com/25857422/60758218-4f981580-a047-11e9-8138-36f7cea61db4.png)

**Comment by Fndroid** [comment]
https://github.com/Dreamacro/clash/issues/225

**Comment by xjasonlyu** [comment]
@sjdjfcu 问一下，你这个测试socks UDP的软件是什么？

**Comment by Fndroid** [comment]
> @sjdjfcu 问一下，你这个测试socks UDP的软件是什么？

SocksCap里有一个
