### ISSUE TITLE
rule for directing connections on whatsapp ip's and domains

### ISSUE THREAD

**Issue by fsheidaiee** [Fndroid/clash_for_windows_pkg#1380]
Hi
how can I get direct connection on all ip's and domains related to whatsapp?
whats should I write in rules?

**Comment by yi-Xu-0100** [comment]
@fsheidaiee 

1. Find all ip's and domains related to whatsapp
2. <https://lancellc.gitbook.io/clash/clash-config-file/rules>

**Comment by Fndroid** [comment]
https://github.com/Hackl0us/SS-Rule-Snippet/blob/master/Rulesets/Clash/App/social/WhatsApp.yaml

**Comment by akw5454521** [comment]
# > Facebook
- IP-CIDR,31.13.24.0/21,(replaceofyourproxyname),no-resolve
- IP-CIDR,31.13.64.0/18,(replaceofyourproxyname),no-resolve
- IP-CIDR,45.64.40.0/22,(replaceofyourproxyname),no-resolve
- IP-CIDR,66.220.144.0/20,(replaceofyourproxyname),no-resolve
- IP-CIDR,69.63.176.0/20,(replaceofyourproxyname),no-resolve
- IP-CIDR,69.171.224.0/19,(replaceofyourproxyname),no-resolve
- IP-CIDR,74.119.76.0/22,(replaceofyourproxyname),no-resolve
- IP-CIDR,103.4.96.0/22,(replaceofyourproxyname),no-resolve
- IP-CIDR,129.134.0.0/17,(replaceofyourproxyname),no-resolve
- IP-CIDR,157.240.0.0/17,(replaceofyourproxyname),no-resolve
- IP-CIDR,173.252.64.0/19,(replaceofyourproxyname),no-resolve
- IP-CIDR,173.252.96.0/19,(replaceofyourproxyname),no-resolve
- IP-CIDR,179.60.192.0/22,(replaceofyourproxyname),no-resolve
- IP-CIDR,185.60.216.0/22,(replaceofyourproxyname),no-resolve
- IP-CIDR,204.15.20.0/22,(replaceofyourproxyname),no-resolve
- IP-CIDR,3.123.36.126/32,(replaceofyourproxyname),no-resolve
- IP-CIDR,35.157.215.84/32,(replaceofyourproxyname),no-resolve
- IP-CIDR,35.157.217.255/32,(replaceofyourproxyname),no-resolve
- IP-CIDR,52.58.209.134/32,(replaceofyourproxyname),no-resolve
- IP-CIDR,54.93.124.31/32,(replaceofyourproxyname),no-resolve
- IP-CIDR,54.162.243.80/32,(replaceofyourproxyname),no-resolve
- IP-CIDR,54.173.34.141/32,(replaceofyourproxyname),no-resolve
- IP-CIDR,54.235.23.242/32,(replaceofyourproxyname),no-resolve
- IP-CIDR,169.45.248.118/32,(replaceofyourproxyname),no-resolve

I don't have specific WA IP and here are FB IPs for your reference

**Comment by fsheidaiee** [comment]
Thanks from all
👍
