### ISSUE TITLE
clash配置太繁琐，玩了1小时，还是回到了Trojan-Qt5

### ISSUE THREAD

**Issue by adminops** [Fndroid/clash_for_windows_pkg#1382]
我之前一直在用Trojan-Qt5，根本不需要配置，可以切换到PAC模式自动识别办公内网域名，ip和国外域名。不影响办公（办公域名内网DNS自解析）也不影响浏览google。

使用了clash，想实现这个功能，简直变态了。需要手动配置不说，规则也配置了（无效），在设置里切换到PAC（无效）。

21世纪了，就一个代理软件，不要为了自定义强大的口号，整的很复杂好不。

**Comment by yi-Xu-0100** [comment]
1. 建议直接删除软件，更换即可。
2. 一般也不是手动配置，而是由服务商给出规则，有个人需求就自己实现部分功能，所以觉得配置不好，可以要求服务商提供更详细的配置。
4. CFW 提供 Clash 的 GUI 使用体验优化，功能的配置问题建议给上游提出需求，或者试试打钱要求上游作者整改，或者试试打钱要求别人帮你配置。
3. 如果个人配置未成功，服务商不提供帮助，且不想折腾和付费要求别人帮忙，参考第一条。

**Comment by AkariiinMKII** [comment]
*本软件仅作技术技术交流

**Comment by akw5454521** [comment]
我在公司用CFW，内网域名直接解析为10.x.x.x的内网ip，完全没受到clash影响，都正常连接，不知道你是个什么情况
