### ISSUE TITLE
怎么使指定域名跳过代理？

### ISSUE THREAD

**Issue by amrice** [Fndroid/clash_for_windows_pkg#1383]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ ] 已经在[官方文档](https://docs.cfw.lbyczf.com/contents/bypass.html)找过了，按照这个方法还是没用

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
- [ ] 因为打开代理后qq的快速登录就失效了，快速登陆的原理是qq.exe的进程监听某个端口用于和浏览器通信，现在因为走了代理，浏览器访问这个域名时直接访问不了，所以需要绕过代理而不是改成直连。

**Comment by yi-Xu-0100** [comment]
参考： #954，#1277，#1360

**Comment by amrice** [comment]
> 参考： #954，#1277，#1360

谢谢，成功解决
