### ISSUE TITLE
100%引发BUG，但是不会报错。

### ISSUE THREAD

**Issue by asdfj2381k** [Fndroid/clash_for_windows_pkg#1385]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
windows7  sp1 x64  所有补丁打到最新。

**描述**
正文放在2楼，我编辑一下，稍等。

**Comment by Fndroid** [comment]
楼主快更，等不及了

**Comment by asdfj2381k** [comment]
干。等一下， 我在装虚拟机，给你录个相，电脑太卡了，等下。

**Comment by asdfj2381k** [comment]
[bandicam 2020-12-04 17-42-17-630.txt](https://github.com/Fndroid/clash_for_windows_pkg/files/5641863/bandicam.2020-12-04.17-42-17-630.txt)

txt → mp4， 就可以看了。  
@Fndroid

**Comment by Fndroid** [comment]
打不开网页的时候有，打开log看看？

**Comment by asdfj2381k** [comment]
[log.txt](https://github.com/Fndroid/clash_for_windows_pkg/files/5641977/log.txt)
    你好，这是log。   我不会看，麻烦了。

**Comment by asdfj2381k** [comment]
`time="2020-12-04T17:42:01+08:00" level=info msg="[TCP] 127.0.0.1:60542 --> licensing.mp.microsoft.com using GLOBAL"
time="2020-12-04T17:42:03+08:00" level=info msg="[UDP] 127.0.0.1:55127 --> 224.0.0.252 using GLOBAL"
time="2020-12-04T17:42:03+08:00" level=info msg="[UDP] 127.0.0.1:55128 --> 224.0.0.252 using GLOBAL"
time="2020-12-04T17:42:03+08:00" level=info msg="[UDP] 127.0.0.1:55129 --> 224.0.0.252 using GLOBAL"
time="2020-12-04T17:42:03+08:00" level=info msg="[UDP] 127.0.0.1:55132 --> 224.0.0.252 using GLOBAL"
time="2020-12-04T17:42:03+08:00" level=info msg="[UDP] 127.0.0.1:55133 --> 224.0.0.252 using GLOBAL"
time="2020-12-04T17:42:07+08:00" level=info msg="[TCP] 127.0.0.1:60550 --> www.google.com.hk using GLOBAL"
time="2020-12-04T17:42:17+08:00" level=info msg="[TCP] 127.0.0.1:60559 --> www.google.com.hk using GLOBAL"
time="2020-12-04T17:42:20+08:00" level=info msg="[TCP] 127.0.0.1:60562 --> api.github.com using GLOBAL"
time="2020-12-04T17:42:36+08:00" level=info msg="[UDP] 127.0.0.1:56459 --> 10.0.0.255 using GLOBAL"
time="2020-12-04T17:42:36+08:00" level=info msg="[UDP] 127.0.0.1:54400 --> www.gstatic.com using GLOBAL"
time="2020-12-04T17:42:36+08:00" level=info msg="[UDP] 127.0.0.1:54403 --> 224.0.0.252 using GLOBAL"
time="2020-12-04T17:42:36+08:00" level=info msg="[TCP] 127.0.0.1:60579 --> www.google.cn using GLOBAL"
time="2020-12-04T17:42:36+08:00" level=info msg="[UDP] 127.0.0.1:56884 --> apis.google.com using GLOBAL"
time="2020-12-04T17:42:37+08:00" level=info msg="[TCP] 127.0.0.1:60578 --> ssl.gstatic.com using GLOBAL"
time="2020-12-04T17:42:37+08:00" level=info msg="[UDP] 127.0.0.1:56886 --> play.google.com using GLOBAL"
time="2020-12-04T17:42:37+08:00" level=info msg="[TCP] 127.0.0.1:60584 --> play.google.com using GLOBAL"
time="2020-12-04T17:42:43+08:00" level=info msg="[TCP] 127.0.0.1:60587 --> adservice.google.com.hk using GLOBAL"
time="2020-12-04T17:42:43+08:00" level=info msg="[TCP] 127.0.0.1:60590 --> adservice.google.com using GLOBAL"
time="2020-12-04T17:42:44+08:00" level=info msg="[TCP] 127.0.0.1:60593 --> googleads.g.doubleclick.net using GLOBAL"
time="2020-12-04T17:42:44+08:00" level=info msg="[UDP] 127.0.0.1:52727 --> adservice.google.com.hk using GLOBAL"
time="2020-12-04T17:42:44+08:00" level=info msg="[UDP] 127.0.0.1:52730 --> googleads.g.doubleclick.net using GLOBAL"
time="2020-12-04T17:42:48+08:00" level=info msg="[TCP] 127.0.0.1:60598 --> go.microsoft.com using GLOBAL"
time="2020-12-04T17:43:45+08:00" level=info msg="Start initial compatible provider Outbound"
time="2020-12-04T17:43:45+08:00" level=info msg="DNS server listening at: 127.0.0.1:53"
time="2020-12-04T17:43:45+08:00" level=info msg="[UDP] 127.0.0.1:53230 --> 224.0.0.251 match IPCIDR(224.0.0.0/4) using DIRECT"
time="2020-12-04T17:43:45+08:00" level=info msg="[UDP] 127.0.0.1:53231 --> 224.0.0.252 match IPCIDR(224.0.0.0/4) using DIRECT"
time="2020-12-04T17:43:45+08:00" level=info msg="[UDP] 127.0.0.1:53232 --> 10.0.0.255 match IPCIDR(10.0.0.0/8) using DIRECT"
time="2020-12-04T17:43:46+08:00" level=info msg="[UDP] 127.0.0.1:53236 --> 10.0.0.255 match IPCIDR(10.0.0.0/8) using DIRECT"
time="2020-12-04T17:43:46+08:00" level=info msg="[UDP] 127.0.0.1:53237 --> 224.0.0.252 match IPCIDR(224.0.0.0/4) using DIRECT"
time="2020-12-04T17:43:46+08:00" level=info msg="[UDP] 127.0.0.1:53238 --> 224.0.0.251 match IPCIDR(224.0.0.0/4) using DIRECT"
time="2020-12-04T17:43:46+08:00" level=info msg="[UDP] 127.0.0.1:53242 --> 10.0.0.255 match IPCIDR(10.0.0.0/8) using DIRECT"
time="2020-12-04T17:43:46+08:00" level=info msg="[UDP] 127.0.0.1:53243 --> 224.0.0.251 match IPCIDR(224.0.0.0/4) using DIRECT"
time="2020-12-04T17:43:46+08:00" level=info msg="[UDP] 127.0.0.1:53244 --> 224.0.0.252 match IPCIDR(224.0.0.0/4) using DIRECT"
time="2020-12-04T17:43:46+08:00" level=info msg="[UDP] 127.0.0.1:53248 --> 10.0.0.255 match IPCIDR(10.0.0.0/8) using DIRECT"
time="2020-12-04T17:43:46+08:00" level=info msg="[UDP] 127.0.0.1:53249 --> 224.0.0.252 match IPCIDR(224.0.0.0/4) using DIRECT"
time="2020-12-04T17:43:46+08:00" level=info msg="[UDP] 127.0.0.1:53252 --> 224.0.0.251 match IPCIDR(224.0.0.0/4) using DIRECT"
time="2020-12-04T17:43:50+08:00" level=info msg="Start initial compatible provider Outbound"
time="2020-12-04T17:43:50+08:00" level=info msg="DNS server listening at: 127.0.0.1:53"
time="2020-12-04T17:43:50+08:00" level=info msg="Start initial compatible provider Outbound"
time="2020-12-04T17:43:50+08:00" level=info msg="DNS server listening at: 127.0.0.1:53"
time="2020-12-04T17:43:50+08:00" level=info msg="Start initial compatible provider Outbound"
time="2020-12-04T17:43:50+08:00" level=info msg="DNS server listening at: 127.0.0.1:53"
time="2020-12-04T17:43:50+08:00" level=info msg="Start initial compatible provider Outbound"
time="2020-12-04T17:43:50+08:00" level=info msg="DNS server listening at: 127.0.0.1:53"
time="2020-12-04T17:43:50+08:00" level=info msg="Start initial compatible provider Outbound"
time="2020-12-04T17:43:50+08:00" level=info msg="DNS server listening at: 127.0.0.1:53"
time="2020-12-04T17:43:50+08:00" level=info msg="Start initial compatible provider Outbound"
time="2020-12-04T17:43:50+08:00" level=info msg="DNS server listening at: 127.0.0.1:53"
time="2020-12-04T17:44:05+08:00" level=info msg="Start initial compatible provider Outbound"
time="2020-12-04T17:44:05+08:00" level=info msg="DNS server listening at: 127.0.0.1:53"
time="2020-12-04T17:44:05+08:00" level=info msg="Start initial compatible provider Outbound"
time="2020-12-04T17:44:05+08:00" level=info msg="DNS server listening at: 127.0.0.1:53"
time="2020-12-04T17:44:05+08:00" level=info msg="Start initial compatible provider Outbound"
time="2020-12-04T17:44:05+08:00" level=info msg="DNS server listening at: 127.0.0.1:53"`

   好像没看出来错误信息。。

**Comment by asdfj2381k** [comment]
![image](https://user-images.githubusercontent.com/56584082/101151320-6e477500-365c-11eb-937a-24609e30ff9d.png)

**Comment by Fndroid** [comment]
我试了下是没问题的。你要不把nameserver那几个DoH换成普通UDP试试先？

**Comment by yi-Xu-0100** [comment]
@asdfj2381k 个人测试无问题……

**Comment by asdfj2381k** [comment]
[bandicam 2020-12-04 21-34-17-978.txt](https://github.com/Fndroid/clash_for_windows_pkg/files/5643082/bandicam.2020-12-04.21-34-17-978.txt)
@Fndroid    改DoH了，还是有问题。      这回把日志也录上了，你看看。

**Comment by yi-Xu-0100** [comment]
@asdfj2381k 有个小问题， 没开 mixin ，配置中没有 interface-name ，应该没有 tap 吧？

**Comment by Fndroid** [comment]
我觉得，你的TAP就没有配置上，dns里的listen就不能是127.0.0.1。

**Comment by asdfj2381k** [comment]
[bandicam 2020-12-05 09-22-52-622.txt](https://github.com/Fndroid/clash_for_windows_pkg/files/5646274/bandicam.2020-12-05.09-22-52-622.txt)

@Fndroid    @yi-Xu-0100   现在，我也不确定Tap到底有没有装上了， 现在出现了很奇怪的情况，你们看看。

**Comment by Fndroid** [comment]
你要不把Clash for Windows都关掉看看能不能上Google，如果能的话，说明Connections没有显示就是正常的。因为你压根就没有连到Clash。

**Comment by asdfj2381k** [comment]
@Fndroid   Clash关掉后，连不上google。    你再看看这个视频， Tap网卡的状况很奇怪。
https://mega.nz/file/hjxQ2TiD#EIedC6FUNklQd3Yg_FAZMjyzt98T3HDLmt9eAcl_vfE

**Comment by yi-Xu-0100** [comment]
@asdfj2381k 
第二次的和第一次的 listen 有区别，第二次是 `listen: 0.0.0.0:53`, 第一次是 `listen: 127.0.0.1:53`。更改为第一次的设置时，tap 不会被启动。

第二次的值
```yaml
mode: Rule
log-level: info
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 114.114.115.115
    - 223.6.6.6
    - 119.29.29.29
```

我使用虚拟机测试，设置为第二次的值时，他在没有设置 tap 对应字段时（虚拟机和主机都没有），会出现相应日志，由于我虚拟机中没有相应的配置文件，而无法访问 google。而如果虚拟机中提供相关配置，可以直接通过代理，在未设置 tap （虚拟机和主机）和未设置系统代理（虚拟机和主机） 的情况下，实现浏览器走 clash 的情况，日志中显示走了规则。

个人的结论：
1. 虚拟机中，在设置 `listen: 0.0.0.0:53` 的情况下，可以不设置相应的 tap，我启用这种设置时，电脑会有提示相应的网络监听和防火墙准许的提示，给予权限即可。
2. 虚拟机中，如果设置 `listen: 127.0.0.1:53` 时，不会自动完成相应的 tap 设置，需要完成 tap 设置的 interface-name 字段，才能打开相应的 tap 设置。
3. 在主机上，即使设置 `listen: 0.0.0.0:53` 的情况下，仍然需要完成 tap 设置的 interface-name 字段。

**Comment by yi-Xu-0100** [comment]
@asdfj2381k 刚刚正好碰到一个配置的所有节点挂了。现在是个人在代理正常的情况下的重新测试的结果如下（在 CFW 的 setting 中的 Outbound 指定网卡正确的情况下分别在虚拟机和主机中的情况）。
1. 在 `listen: 127.0.0.1:53` 的情况下，关闭系统代理的情况下，浏览器无法访问代理（默认系统代理），此时 tap 不生效。
2. 在 `listen: 0.0.0.0:53` 的情况下，关闭系统代理的情况下，浏览器可以访问代理（默认系统代理），此时 tap 生效。

**Comment by asdfj2381k** [comment]
@yi-Xu-0100  看到你的留言后，我进行了多次测试。   
 确实。      在`listen: 127.0.0.1:53`，Tap就坏掉了。
改回去`listen: 0.0.0.0:53`就可以正常使用.

很感谢你，解开了我的疑惑，谢谢。

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/101326494-52381380-38a8-11eb-9a10-c316f9f5a2f9.png)
我真的没看到有什么问题，你原来配置本来就不对

**Comment by asdfj2381k** [comment]
@Fndroid   明人不说暗话。
   好几个机场的Clash配置文件，就是这个样子。    我也是醉了，被误导了。

**Comment by asdfj2381k** [comment]
结贴了，谢谢各位，打扰了。

**Comment by asdfj2381k** [comment]
![image](https://user-images.githubusercontent.com/56584082/101327459-ab547700-38a9-11eb-83ff-3dbbd6d43974.png)

真没搞懂为什么，  薯条的clash配置，没法正常用。   F大你自己试试吧，只要选中这个配置文件，Tap网卡自动断开。 秒断。

**Comment by Fndroid** [comment]
它都没设置dns，当然会断啊

**Comment by asdfj2381k** [comment]
原来如此，明白了，谢谢。
