### ISSUE TITLE
建议增加配置项：开启 Windows 系统代理时的代理服务器IP

### ISSUE THREAD

**Issue by renbaoshuo** [Fndroid/clash_for_windows_pkg#1386]
### 描述

增加配置项：开启系统代理时的代理服务器IP

![image](https://user-images.githubusercontent.com/47095648/101166381-24b65480-3673-11eb-8cba-0d701df95fe3.png)

图中用红笔圈住的地方。

### 其他说明

无。

**Comment by Fndroid** [comment]
你想改成什么

**Comment by renbaoshuo** [comment]
> 你想改成什么

自定义的IP，或者本机某个网卡的IP。

**Comment by Fndroid** [comment]
要填其他IP为什么要开这个软件？

**Comment by renbaoshuo** [comment]
> 要填其他IP为什么要开这个软件？直接手动改一下不就好了。

有一个很\*\*的东西，除了Windows系统代理之外什么代理都不跟随。

即使我开了 tap 模式，也不行。

**Comment by yi-Xu-0100** [comment]
@renbaoshuo 问题是，你设置了别的东西，系统代理不走 clash ，用 clash 干嘛？直接手动改不就行？

**Comment by renbaoshuo** [comment]
> @renbaoshuo 问题是，你设置了别的东西，系统代理不走 clash ，用 clash 干嘛？直接手动改不就行？

要走WSL的IP而不是 `127.0.0.1`

**Comment by for-memory** [comment]
我觉得你说的太隐晦了……我实在是没明白你想干什么……

**Comment by Fndroid** [comment]
把system proxy关掉，手动设置一个不就好了吗

**Comment by renbaoshuo** [comment]
> 把system proxy关掉，手动设置一个不就好了吗

手动设置以后cfw的system proxy会自动变成开启状态

**Comment by AkariiinMKII** [comment]
> > 把system proxy关掉，手动设置一个不就好了吗
> 
> 手动设置以后cfw的system proxy会自动变成开启状态

不影响 此处仅反映系统代理状态

**Comment by renbaoshuo** [comment]
> > > 把system proxy关掉，手动设置一个不就好了吗
> > 
> > 
> > 手动设置以后cfw的system proxy会自动变成开启状态
> 
> 不影响 此处仅反映系统代理状态
> 或者使用PAC功能

明白了，感谢。
