### ISSUE TITLE
建议移除rixcloud广告图片

### ISSUE THREAD

**Issue by HXHGTS** [Fndroid/clash_for_windows_pkg#1387]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows10 20H1

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
软件中自带的第二个广告图片是rixcloud的，但是这家已经跑路了，可以考虑换掉或者删除

**复现**

[//]: # (请描述复现问题的步骤)

**预期行为**

[//]: # (清晰地描述期望看到的行为)
换掉或者删除rixcloud的广告图片

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![1](https://user-images.githubusercontent.com/38959826/101175418-1de20e80-3680-11eb-9d05-3818bffb1007.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by GrayXu** [comment]
lol 我看已经下线了
