### ISSUE TITLE
已经启用国内代理，但是：listen1 还是无法成功播放音乐

### ISSUE THREAD

**Issue by lioArther** [Fndroid/clash_for_windows_pkg#1390]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

版本	Windows 10 专业版
版本号	20H2
安装日期	‎2020/‎11/‎5
操作系统版本	19042.508
体验	Windows Feature Experience Pack 120.2212.31.0

[//]: # (请具体并清楚地描述遇到的问题)

已经启用国内代理，但是：listen1还是无法成功播放音乐
回国线路。

[//]: # (请描述复现问题的步骤)
1. 开启全局都连接大陆节点
2. listen1开启
3. 可以加载歌单、海报
4. 并未开启tap
5. 但是无法播放音乐‘

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)
![image](https://user-images.githubusercontent.com/27990398/101245222-2b61cc00-3746-11eb-87b3-ceb099ba105d.png)

time="2020-12-05T22:03:03+08:00" level=info msg="[TCP] 127.0.0.1:50958 --> tile-service.weather.microsoft.com match RuleSet(CN 企业) using CN 企业[上海自建]"
time="2020-12-05T22:03:04+08:00" level=info msg="[TCP] 127.0.0.1:50956 --> www.kuwo.cn match RuleSet(CN 媒体) using CN 媒体[上海自建]"
time="2020-12-05T22:03:06+08:00" level=info msg="[TCP] 127.0.0.1:50960 --> antiserver.kuwo.cn match RuleSet(CN 媒体) using CN 媒体[上海自建]"
time="2020-12-05T22:03:10+08:00" level=debug msg="[DNS] config.edge.skype.com --> 13.107.42.23"
time="2020-12-05T22:03:12+08:00" level=info msg="[TCP] 127.0.0.1:50962 --> config.edge.skype.com match Match() using CN 媒体[上海自建]"
time="2020-12-05T22:03:27+08:00" level=debug msg="[Process] Resolve process of tcp:127.0.0.1:50965 failed: Access is denied."
time="2020-12-05T22:03:32+08:00" level=warning msg="dial CN 企业 error: 106.14.210.114:8989 connect error: dial tcp4 106.14.210.114:8989: i/o timeout"
time="2020-12-05T22:03:32+08:00" level=debug msg="[Process] Resolve process of tcp:127.0.0.1:50968 failed: Access is denied."
time="2020-12-05T22:03:33+08:00" level=info msg="[TCP] 127.0.0.1:50968 --> slscr.update.microsoft.com match RuleSet(CN 企业) using CN 企业[上海自建]"
time="2020-12-05T22:03:33+08:00" level=info msg="[TCP] 127.0.0.1:50972 --> www.kuwo.cn match RuleSet(CN 媒体) using CN 媒体[上海自建]"
time="2020-12-05T22:03:33+08:00" level=info msg="[TCP] 127.0.0.1:50970 --> m.music.migu.cn match RuleSet(CN 媒体) using CN 媒体[上海自建]"
time="2020-12-05T22:03:34+08:00" level=info msg="[TCP] 127.0.0.1:50974 --> y.gtimg.cn match RuleSet(CN 企业) using CN 企业[上海自建]"
time="2020-12-05T22:03:34+08:00" level=info msg="[TCP] 127.0.0.1:50976 --> antiserver.kuwo.cn match RuleSet(CN 媒体) using CN 媒体[上海自建]"
time="2020-12-05T22:03:34+08:00" level=debug msg="[Process] Resolve process of tcp:127.0.0.1:50978 failed: Access is denied."
time="2020-12-05T22:03:34+08:00" level=debug msg="[DNS] login.live.com --> 20.190.140.231"
time="2020-12-05T22:03:34+08:00" level=debug msg="[Process] Resolve process of tcp:127.0.0.1:50980 failed: Access is denied."
time="2020-12-05T22:03:34+08:00" level=info msg="[TCP] 127.0.0.1:50978 --> login.live.com match Match() using CN 媒体[上海自建]"
time="2020-12-05T22:03:35+08:00" level=info msg="[TCP] 127.0.0.1:50980 --> v10.events.data.microsoft.com match RuleSet(CN 企业) using CN 企业[上海自建]"

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
开TAP
