### ISSUE TITLE
Clash支持新款m1芯片的MacBook Pro吗

### ISSUE THREAD

**Issue by aJLOLLOL** [Fndroid/clash_for_windows_pkg#1391]
**描述**
如题，请问clash是否支持m1芯片的MacBook Pro，谢谢。

**其他说明**
在犹豫要不要买MacBook Pro...

**Comment by Fndroid** [comment]
Clashx Pro支持，Clash for Windows暂时不支持。但这个是左右你下单的因素吗？😂

**Comment by aJLOLLOL** [comment]
最近刚学会科学上网，并且其成为我用MacBook的主要乐趣，看来我又有新的议题要研究了（ClashX）。
btw，以后Clash会支持m1吗，大概要多久...
> Clashx Pro支持，Clash for Windows暂时不支持。但这个是左右你下单的因素吗？😂

**Comment by Fndroid** [comment]
说不准￼，需要上游几个项目支持才行

**Comment by aJLOLLOL** [comment]
> 说不准￼，需要上游几个项目支持才行

好的，十分感谢，第一次距离大神这么近:)
