### ISSUE TITLE
这几个按键老是按错

### ISSUE THREAD

**Issue by ask-github** [Fndroid/clash_for_windows_pkg#1394]
这几个按键不好按, 经常按到缩放, 弄大一点, 鼠标移上去, 有提示

![image](https://user-images.githubusercontent.com/72971953/101282113-09338100-380e-11eb-9630-f2a3ad109dc4.png)

**Comment by babyzhang** [comment]
确实有过这样的问题，希望重新设计一下

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
