### ISSUE TITLE
最新几个版本火绒一直报毒

### ISSUE THREAD

**Issue by csgowdnmd** [Fndroid/clash_for_windows_pkg#1396]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/66403580/101302175-dde47c80-3875-11eb-9d77-43b1ca8c50e6.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
感觉你的图片里面没有提到 CFW

**Comment by csgowdnmd** [comment]
可是我每次运行时都会弹出来。。。

**Comment by yi-Xu-0100** [comment]
@csgowdnmd 
要么火绒信任要么卸载 CFW 吧……

**Comment by csgowdnmd** [comment]
???关键这个文件隔离了也不影响使用。。。我想问一下能不能优化

**Comment by yi-Xu-0100** [comment]
@csgowdnmd 

https://baike.baidu.com/item/dllhost.exe/8193205

估计还是有影响的，只是你没碰到

**Comment by csgowdnmd** [comment]
那暂时只能添加信任，无法解决吗

**Comment by Fndroid** [comment]
什么版本开始

**Comment by csgowdnmd** [comment]
具体版本记不清了，但最近3，4个版本都这样

**Comment by da-gongren** [comment]
可能是误报，可以联系火绒看看。`QQ：935123246`

**Comment by KoakiMiku** [comment]
我也在用火绒，但没有这个问题

**Comment by da-gongren** [comment]
@KoakiMiku 火絨本身就比較迷，有時候掃描報毒，再掃第二次正常了...

**Comment by KoakiMiku** [comment]
@da-gongren 而且这个报告的路径我觉得不像是cfw的，我 AppData\Roaming\ 下都没有 Dll 这个文件夹……

**Comment by da-gongren** [comment]
@KoakiMiku 那不懂哦，杀毒有问题，直接找火绒运营，工作人员都很给力。

**Comment by boris1993** [comment]
这应该不是CFW的文件，大概率是你装了什么奇怪的东西，把挖矿病毒带进来了。
这个目录`Dll`，和这个程序名字`dllhost.exe`，明显是为了伪装成Windows系统应用`dllhost`。

我建议你：
1. 重启到安全模式，删掉这个目录
2. 全盘查杀

**Comment by csgowdnmd** [comment]
全盘查杀也没有用。。。

**Comment by YJ2CS** [comment]
同样感觉是病毒，我电脑上也没有这个文件夹。至于一开始提到的，运行CFW期间会不定期弹出报毒窗口，我遇到了类似情况。但我这个原因完全是u盘插到学校电脑上，感染病毒了，回来插电脑上会不定期报毒，而我的CFW是一直运行着的。所以事实上，两件事情可以同时发生，但是没有一点儿联系。

**Comment by boris1993** [comment]
> 全盘查杀也没有用。。。

你说的没有用，是杀毒软件没报毒，还是杀完了又会出现？

需要重启到安全模式全盘查杀。因为这种玩意肯定有别的进程在监控挖矿进程，在挖矿进程被杀死，挖矿程序被删除的时候，监控进程会再次下载并执行挖矿程序。甚至是两者互锁的，任意一方被干掉，另一方就会重新恢复它。

安全模式仅加载系统核心组件，所以你才可以彻底杀干净。

你要是用杀毒软件杀不干净的话，那就重装系统，装好之后立刻全盘查杀。

这个铁打的绝对是你中了挖矿病毒了，跟CFW完全没关系。

**Comment by csgowdnmd** [comment]
谢谢大家解答，已经让专业人士解决了

**Comment by boris1993** [comment]
解决了的话，记得close这个issue。
