### ISSUE TITLE
When program is running, has no data for the general info window.

### ISSUE THREAD

**Issue by ky0nch3ng** [Fndroid/clash_for_windows_pkg#14]
![](https://i.imgur.com/VTczkDQ.png)

**Comment by Fndroid** [comment]
Check your log files in your configuration file directory

**Comment by ky0nch3ng** [comment]
@Fndroid 

```
time="2018-11-13T19:31:53+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2018-11-13T19:31:53+08:00" level=info msg="HTTP proxy listening at: :7890"
time="2018-11-13T19:31:53+08:00" level=info msg="SOCKS proxy listening at: :1080"
time="2018-11-13T19:31:53+08:00" level=info msg="twitter.com match DomainKeyword using Proxy"
time="2018-11-13T19:31:53+08:00" level=info msg="twitter.com match DomainKeyword using Proxy"
```
The log file looks good,  the clashx and GUI is work, this problem can not reappeared.

I have a new bug right now, It's upload and download network indicator not work, always display value is 0.00 B/s.

**Comment by Fndroid** [comment]
Maybe you should try the latest release

**Comment by Fndroid** [comment]
This issue is now closing.
You can reopen it whenever you need.
