### ISSUE TITLE
无法安装TAP

### ISSUE THREAD

**Issue by moonaileen** [Fndroid/clash_for_windows_pkg#140]
点击 Install TAP Device 之后，Clash 左下角状态会变为 Installing TAP Device，但几秒后，左下角状态会重新变为 Connected to Clash，右侧列表的 TAP Device 也仍然是 Install。在网络连接里也没有发现名为cfw的新tap。
请问这种情况应该怎么办？

**Comment by Fndroid** [comment]
进``安装目录\resources\static\files\tun2socks``里面，用**管理员打开CMD**执行这个命令：
``add_tap_device.bat "%cd%"``

看看输出什么

**Comment by moonaileen** [comment]
安装成功了！非常感谢><

**Comment by lvhe19880210** [comment]
> 进`安装目录\resources\static\files\tun2socks`里面，用**管理员打开CMD**执行这个命令：
> `add_tap_device.bat "%cd%"`
> 
> 看看输出什么
输出如截图所示，已按照最新tap要求配置了文件 ，网络适配器还是显示电缆已拔出
<img width="1464" alt="截屏2019-12-08下午10 01 38" src="https://user-images.githubusercontent.com/29178968/70390474-5831b500-1a06-11ea-8ad2-f966236eac80.png">

**Comment by lvhe19880210** [comment]
<img width="739" alt="截屏2019-12-08下午10 04 45" src="https://user-images.githubusercontent.com/29178968/70390527-c6767780-1a06-11ea-8ae2-ab4a5024f346.png">

**Comment by Fndroid** [comment]
改错文件了，要改Profiles里的

**Comment by lvhe19880210** [comment]
> 改错文件了，要改Profiles里的

已经改到文件里了 还是提示网络拔出 是不是虚拟机虚拟网络的原因？

**Comment by lvhe19880210** [comment]
> 改错文件了，要改Profiles里的
 已经好了 一开始是我这设置问题

**Comment by mophisalgmail** [comment]
> >  已经好了 一开始是我这设置问题
请问怎么改就好了？我的还是不行。非常感谢！

**Comment by mophisalgmail** [comment]
> 进`安装目录\resources\static\files\tun2socks`里面，用**管理员打开CMD**执行这个命令：
> `add_tap_device.bat "%cd%"`
> 
> 看看输出什么
大神，请问几个问题。1. 下图是输入命令后的显示。在网络连接窗口中看不到cfw-tap, 但是ipconfig命令后显示cfw-tap设备是断开连接的。这个表明安装成功了吗？2. 改配置你有2个帖子，是否应该用新的，‘0.7.7 版本后，启用新版 TAP 替代旧版，新版 TAP 能处理纯 IP 请求并且支持 redir-host 模式’？3. 用这个配置文件后，还需要在general选中‘system proxy’吗？4. 所有这些操作是一定要exe安装版还是说7z那个绿色版也可以开启TAP? 非常感谢！

![image](https://user-images.githubusercontent.com/38368721/72204278-01aa1180-34b1-11ea-9ca4-cb3bfaccbb2b.png)

**Comment by moonaileen** [comment]
不好意思，又有问题求助：
更新到0.99后TAP失效，卸载后想重新安装发现装不上了
提示如下：
![Snipaste_2020-04-30_18-35-12](https://user-images.githubusercontent.com/2804132/80695812-65fce980-8b11-11ea-8f59-c8d40c2ae7d5.png)

**Comment by Fndroid** [comment]
> 不好意思，又有问题求助：
> 
> 更新到0.99后TAP失效，卸载后想重新安装发现装不上了
> 
> 提示如下：
> 
> ![Snipaste_2020-04-30_18-35-12](https://user-images.githubusercontent.com/2804132/80695812-65fce980-8b11-11ea-8f59-c8d40c2ae7d5.png)
> 
> 

重新下载一下软件，设备管理器里把未知的删掉，选上删除文件的勾，再install

**Comment by moonaileen** [comment]
卸载后重新安装软件也依然不行。
【设备管理器里把未知的删掉，选上删除文件的勾，再install】
这句没有看懂，我的设备管理器里并没有未知的@@

**Comment by moonaileen** [comment]
TAT对不起大大，我乌龙了，忘记应该用管理员模式安装了………搞定了！给大大添麻烦了😂
