### ISSUE TITLE
High ram usage

### ISSUE THREAD

**Issue by fsheidaiee** [Fndroid/clash_for_windows_pkg#1400]
hi
there is so much ram usage when clash running.
![image](https://user-images.githubusercontent.com/74687186/101541935-4a1ac980-39b7-11eb-8558-b86c32cb432c.png)

**Comment by yi-Xu-0100** [comment]
Electron issue.

**Comment by fsheidaiee** [comment]
> Electron issue.

is there going to be an update to fix this?

**Comment by Fndroid** [comment]
Electron APPs takes more memory then native APPs. It's not a bug to me.

**Comment by fsheidaiee** [comment]
> Electron APPs takes more memory then native APPs. It's not a bug to me.

Can you release uwp clash for wnidows 10?
