### ISSUE TITLE
本地地址未直连

### ISSUE THREAD

**Issue by fxzxmicah** [Fndroid/clash_for_windows_pkg#1401]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 20H2

**描述**

本地地址未直连

**复现**

使用Clash PAC模式

**预期行为**

内网及本地ip直连

**截图**

![image](https://user-images.githubusercontent.com/48860358/101547382-1bb3e300-39e5-11eb-9889-29740040784b.png)

**Comment by yi-Xu-0100** [comment]
规则，和访问的地址如果没有其他匹配，应该会走 match ，检查规则是否有相关的配置，是否使用系统代理？

**Comment by Fndroid** [comment]
要自己写一下pac

**Comment by fxzxmicah** [comment]
@Fndroid 不能在clash层面设置一下吗？我用的不是Clash自带的PAC改起来不太方便。而且HTTP模式是有这个设置的，可以把这个改成全局设置吧。

**Comment by Fndroid** [comment]
那就不是我的问题了。要么是PAC里加，要么是配置文件rules里加。

**Comment by fxzxmicah** [comment]
@Fndroid rules里有，但是未生效。
![image](https://user-images.githubusercontent.com/48860358/101611497-8cd6b300-3a44-11eb-99a4-063c88b1f2a6.png)

**Comment by fxzxmicah** [comment]
还有就是最上面的截图中的地址其实是发起请求的地址，而不是目标地址，我的日志都是这样的：
![image](https://user-images.githubusercontent.com/48860358/101612332-7da43500-3a45-11eb-9db6-d88b47ff4603.png)

**Comment by Fndroid** [comment]
你不会是说192.168.137.149这个吧，这个是inbound地址

**Comment by yi-Xu-0100** [comment]
@fxzxmicah 它匹配的是域名，比如你应该找找规则中是否匹配 graph.microsoft.com, 没有，会走最后一项，match 来全匹配

**Comment by fxzxmicah** [comment]
@yi-Xu-0100 也就是说，有一个解析到192.168.1.1的域名，但是不会判断这个域名的解析是否是内网，而只是根据域名本身来判断，如果没有设定这个域名的规则哪怕它解析到127.0.0.1也还是算漏网之鱼？

**Comment by fxzxmicah** [comment]
@Fndroid 也就是说Log中记录的是传入连接的地址？

**Comment by yi-Xu-0100** [comment]
@fxzxmicah https://lancellc.gitbook.io/clash/clash-config-file/rules/ip-based-rule

**Comment by fxzxmicah** [comment]
@Fndroid @yi-Xu-0100 我知道你们的意思了，那我重新表述一下我的问题：直接访问一个内网IP是正常的，但是将一个域名解析到这个内网IP以后，访问这个域名，就会由于这个域名不在规则内而导致走了代理。那么是否可以请开发者将原来HTTP模式专属的cfw-bypass的配置带入到PAC模式中？

**Comment by yi-Xu-0100** [comment]
@fxzxmicah https://docs.cfw.lbyczf.com/contents/parser.html

**Comment by fxzxmicah** [comment]
@yi-Xu-0100 这个需要针对每个配置文件进行设置，没有cfw-bypass来的方便。

**Comment by yi-Xu-0100** [comment]
@fxzxmicah 用 reg
