### ISSUE TITLE
系统环境改变导致启动失败

### ISSUE THREAD

**Issue by H-olxx** [Fndroid/clash_for_windows_pkg#1410]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

    win10

**描述**

    当系统变量"NODE_ENV"值为“Development”时，软件将启动失败并卡死

**复现**

[//]: # (请描述复现问题的步骤)

1. 将系统变量"NODE_ENV"设置为“Development”

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
这个是预期行为，因为这个变量就不应该被设置在系统中，如果你是做开发，应该单独设置给你的项目。
