### ISSUE TITLE
希望增加'Open terminal with proxy set up'功能对PowerShell Core的支持

### ISSUE THREAD

**Issue by iHandle** [Fndroid/clash_for_windows_pkg#1414]
**描述**
我的`Windows Terminal`默认启动的是`PowerShell Core`。使用'Open terminal with proxy set up' -> 'Windows Terminal'这个功能时，会出现以下错误提示：
![图片](https://user-images.githubusercontent.com/16792577/101893925-63528e80-3be0-11eb-8338-ae748c11c01f.png)

**其他说明**
无

**Comment by Fndroid** [comment]
这个功能只是调用``start wt``

```js
exec(`start wt`, {
  env: {
     http_proxy: `http://127.0.0.1:${this.port}`,
     https_proxy: `http://127.0.0.1:${this.port}`,
  },
});
```

**Comment by iHandle** [comment]
抱歉，是我的Windows Terminal配置文件没写好
