### ISSUE TITLE
mixin中设置doh无效的问题

### ISSUE THREAD

**Issue by heweibyron** [Fndroid/clash_for_windows_pkg#1415]
如题，在mixin中设置doh无效，但是在单独的订阅文件中设置doh有效。

**Comment by Fndroid** [comment]
按格式了么？截个图？

**Comment by heweibyron** [comment]
> 按格式了么？截个图？

嗯嗯，具体的是yaml里设置不可用，格式是这样子的：
![1](https://user-images.githubusercontent.com/58912747/102011827-c891b580-3d81-11eb-89e1-ba5229a72410.JPG)
我刚刚又测试了Javascript的格式，发现可以使用Doh.

**Comment by heweibyron** [comment]
> 按格式了

**Comment by Fndroid** [comment]
缩进不对，去看文档

**Comment by heweibyron** [comment]
> 缩进不对，去看文档

嗯嗯。这样哦，我去看看。

**Comment by heweibyron** [comment]
> 缩进不对，去看文档
果然是缩进我自己的问题。谢谢开发者。
