### ISSUE TITLE
OVPN protocol support

### ISSUE THREAD

**Issue by messi06** [Fndroid/clash_for_windows_pkg#1416]
I saw that cfw supports http proxy , i was wondering if possible at all to include ovpn protocol as well ?
![2020-12-14_033038](https://user-images.githubusercontent.com/13597151/102021740-f0523f00-3dbc-11eb-8902-d31e737d7a22.jpg)

**Comment by Fndroid** [comment]
clash core issue, refer: https://github.com/Dreamacro/clash/issues
