### ISSUE TITLE
开启代理后无法获取网站的真实地址，获取到的IP地址为127.0.0.1

### ISSUE THREAD

**Issue by nameldk** [Fndroid/clash_for_windows_pkg#1418]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Windows 7

[//]: # (平台及版本号)
Microsoft Windows [Version 6.1.7601]
Clash For Windows v0.13.6

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
在Chrome下可以安装扩展来获取当前网站的IP地址，安装后可在网页下方显示网站的IP地址。
开启CFW系统代理后，再看网页上的地址一直显示为 `127.0.0.1` 。
之前用 SSR 客户端时，大陆地址不会进入到代理，所以还可以显示网站的IP地址；用CFW后大陆地址会显示为 `127.0.0.1`，
把网站域名加到Bypass中IP地址才可以正常显示。
Chrome扩展为: [Website IP](https://chrome.google.com/webstore/detail/website-ip/ghbmhlgniedlklkpimlibbaoomlpacmk)

**复现**

[//]: # (请描述复现问题的步骤)

1. 在Chrome上安装扩展 [Website IP](https://chrome.google.com/webstore/detail/website-ip/ghbmhlgniedlklkpimlibbaoomlpacmk)
2. 打开CFW系统代理。
3. 访问 https://www.baidu.com
4. 查看IP地址，显示为 127.0.0.1
5. 把 `*.baidu.com` 加入到Bypass配置中，重启CFW。
6. 查看IP地址，显示正常。

**预期行为**

未经过代理的网站(策略为`DIRECT`的)可以显示真实的IP地址，不用加入到bypass配置中也可以显示正常IP地址。

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

正常：
![正常](https://user-images.githubusercontent.com/1977896/102032039-bbf97580-3df2-11eb-9ee1-900638c756c2.jpg)

不正常：
![不正常](https://user-images.githubusercontent.com/1977896/102032050-c0259300-3df2-11eb-9229-de4ddacbd808.jpg)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
预期行为

**Comment by nameldk** [comment]
> 预期行为

是预期行为写的不明白，还是认为这种情况是正常的呢？

**Comment by Fndroid** [comment]
正常情况，CFW不用PAC分流，多出口，原理就和其他的不一样
