### ISSUE TITLE
Mac 关闭和退出快捷键失效

### ISSUE THREAD

**Issue by ciaoca** [Fndroid/clash_for_windows_pkg#1419]
**描述**
MacOS 版本 Catalina，在主界面按 command + w 无法关闭，按  command + q 也无法退出。
之前在使用 10.x 还是 11.x 几个版本的时候，有增加过这些快捷键，这次更新 13.x 版本后，就无效了。
希望能修复，谢谢。

**Comment by Fndroid** [comment]
隐藏界面是command+H吧，command+Q不能退出下个版本修复

**Comment by ciaoca** [comment]
隐藏界面是可以的，command + w 关闭，能把 dock 里的图标也关掉，只保留任务栏里的图标。

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
