### ISSUE TITLE
【建议】默认读data文件夹

### ISSUE THREAD

**Issue by wsa01378** [Fndroid/clash_for_windows_pkg#1420]
v2rayn和netch默认读其下路径
初次使用不熟，整个clash打包发给朋友发现里面没任何配置
要不是issue仔细查，差点以为不支持

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/7z.html

**Comment by wsa01378** [comment]
知道啦，我的建议是release里

**Comment by Fndroid** [comment]
没明白什么叫“release里”
