### ISSUE TITLE
在macOS端，Clash for Windows与卡巴斯基杀毒软件的网络内容过滤冲突

### ISSUE THREAD

**Issue by ColanCN** [Fndroid/clash_for_windows_pkg#1422]
**描述**
在macOS端，Clash for Windows与卡巴斯基杀毒软件的网络内容过滤冲突，两个同时启动后就不能正常使用了，希望能解决这个问题。

**其他说明**
希望官网能解决这个问题。

**Comment by jaykwok** [comment]
盲猜你是big sur？big sur现在统一改模式了，冲突的话你只能把卡巴斯基的过滤的上游服务器改成localhost:端口号了（前提是卡巴斯基有这个设置，否则你可能只能二选一了）

**Comment by ColanCN** [comment]
> 盲猜你是big sur？big sur现在统一改模式了，冲突的话你只能把卡巴斯基的过滤的上游服务器改成localhost:端口号了（前提是卡巴斯基有这个设置，否则你可能只能二选一了）

是big sur，可以改clash的吗？
