### ISSUE TITLE
软件打开的时候显示主界面

### ISSUE THREAD

**Issue by hupo376787** [Fndroid/clash_for_windows_pkg#1423]
**描述**
请具体并清楚地描述期望功能及期望的效果

现在软件一打开，直接在托盘上显示一个图表，没有打开主界面。需要双击那个图标才可以。

可不可以一打开软件就显示主界面呢

谢谢

**其他说明**
null

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/102491921-df027e80-40ab-11eb-9a55-4dc3501a5379.png)

@hupo376787 关掉这个

**Comment by hupo376787** [comment]
@yi-Xu-0100 谢谢
