### ISSUE TITLE
开机自启能否自动缩小至任务栏

### ISSUE THREAD

**Issue by isArtJay** [Fndroid/clash_for_windows_pkg#1425]
**信息**

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
windows10  20H2

**描述**
最近两个版本开机自启的时候软件会显示在屏幕中，希望能让直接缩小至任务栏

**复现**
无

**预期行为**
开机自启时直接缩小至任务栏

**日志**
无

**截图**
无

**其他说明**
无

**Comment by BKDOnions** [comment]
建议查看一下注册表中Clash的值，我的更新完变成了Label://path/to/Clash.exe，但是参照实际上其他软件的启动项的值，Clash的应该是"Label://path/to/Clash.exe"，必须加上`"`双引号，我更正后启动就正常了。

**Comment by BKDOnions** [comment]
FYI，常见的开机自启动项的注册表路径为：（`计算机`会在不同系统语言下会呈现不同的，国际通用英语的情况下是Computer）

（1）计算机\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run  (我在这里发现的)
（2）计算机\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
（3）计算机\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Run

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/102631822-31659d00-4189-11eb-841e-54ba9467e65b.png)
看下这个是不是被关闭了

**Comment by isArtJay** [comment]
> 建议查看一下注册表中Clash的值，我的更新完变成了Label://path/to/Clash.exe，但是参照实际上其他软件的启动项的值，Clash的应该是"Label://path/to/Clash.exe"，必须加上`"`双引号，我更正后启动就正常了。

**Comment by isArtJay** [comment]
现在为刚开机状态：
![image](https://user-images.githubusercontent.com/48620527/102683973-a11e6b00-420f-11eb-9d39-ec445038e2ab.png)

并且 Start with Windows 一直都是开启状态。
![image](https://user-images.githubusercontent.com/48620527/102684001-e6429d00-420f-11eb-9b35-af1a5a573fab.png)

我的意思是：
开机的时候任务栏的小图标确实会有，也能正常进行 “开机自启” ，但是就像图1那样，软件面板会直接显示在屏幕中，这在之前版本是没有的，不知是否是作者的有意为之。

**Comment by isArtJay** [comment]
> 建议查看一下注册表中Clash的值，我的更新完变成了Label://path/to/Clash.exe，但是参照实际上其他软件的启动项的值，Clash的应该是"Label://path/to/Clash.exe"，必须加上`"`双引号，我更正后启动就正常了。

确实刚开始注册表中Clash的值没有加双引号，加过之后也没任何变化。

**Comment by Fndroid** [comment]
你认真看我图片了吗？我图片里是start with windows吗？

**Comment by BKDOnions** [comment]
@isArtJay 那看一下作者的图，可能在那里的

> ![image](https://user-images.githubusercontent.com/16091562/102631822-31659d00-4189-11eb-841e-54ba9467e65b.png)
> 看下这个是不是被关闭了

**Comment by isArtJay** [comment]
> 你认真看我图片了吗？我图片里是start with windows吗？

不好意思，已解决
