### ISSUE TITLE
CFW安装程序在关闭CFW时会同时杀死Chrome

### ISSUE THREAD

**Issue by boris1993** [Fndroid/clash_for_windows_pkg#1427]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 Pro 2004 Build 19041.685

Google Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**描述**

CFW安装程序在关闭CFW时会同时杀死Chrome。

安装程序版本：Clash.for.Windows.Setup.0.13.7.exe

**复现**

1. 保持Chrome和CFW启动
2. 运行 Clash.for.Windows.Setup.0.13.7.exe
3. 安装位置保持默认值 Only for me，目录不变
4. 点击 Install ，提示 Clash for Windows is running 时，点击OK
5. 此时触发问题，CFW和Chrome都会被关闭

**预期行为**

仅CFW被关闭，Chrome正常继续运行

**日志**

未找到安装程序日志

**截图**

无

**其他说明**

或许是偶发行为，我再次运行安装程序，安装相同版本CFW时，仅CFW被关闭，Chrome运行正常

**Comment by boris1993** [comment]
稍后我会尝试安装上一版本CFW，重试一下“升级安装”的场景

**Comment by yi-Xu-0100** [comment]
未触发……

**Comment by boris1993** [comment]
没有再次出现。关闭issue。
