### ISSUE TITLE
刚刚亲戚家小孩来我家玩电脑，我的clash崩掉了，检查不出来错误，艹

### ISSUE THREAD

**Issue by asdfj2381k** [Fndroid/clash_for_windows_pkg#1428]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
windows 7 x64
clash 0.13.7

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
  
![image](https://user-images.githubusercontent.com/56584082/102686460-e730fa00-4222-11eb-9f5a-7373c541d68b.png)
 Tap网卡现在变成这样了
![image](https://user-images.githubusercontent.com/56584082/102686468-f4e67f80-4222-11eb-820e-951bfd265276.png)

**Comment by asdfj2381k** [comment]
现在不打开System Proxy时clash无法正确接管流量。  打开System Proxy则可以正常使用。

我倒腾了一个小时，把clash重装卸载，恢复系统网络设置都没能成功修复，真的要崩溃了。  

谁来救救我的Tap网卡。

**Comment by asdfj2381k** [comment]
我已经查看过issue里面的相关记录，   F大你说让我们不要用管理员权限打开clash，然后重装tap.

我试过了。还是不行。

**Comment by yi-Xu-0100** [comment]
@asdfj2381k 重启一下？interface-name 是否指定正确？

**Comment by asdfj2381k** [comment]
@yi-Xu-0100  你又来了，太好了。么么哒

配置文件头：
![image](https://user-images.githubusercontent.com/56584082/102686712-64a93a00-4224-11eb-8530-dc7bc3f05c33.png)

interface-name：
![image](https://user-images.githubusercontent.com/56584082/102686721-6ffc6580-4224-11eb-8d30-0c09172577d9.png)

mixin模式没有打开。

**Comment by yi-Xu-0100** [comment]
@asdfj2381k 需要打开 mixin，除非你的配置中有 listen 才不用打开

**Comment by yi-Xu-0100** [comment]
@asdfj2381k cfw-tap 应该是这样的，你手动修改成这样试试？

![image](https://user-images.githubusercontent.com/25523606/102686838-3b3cde00-4225-11eb-88d2-c81cb7e82f2e.png)

**Comment by asdfj2381k** [comment]
我把 tap网卡的属性按照你所说的更改后
![image](https://user-images.githubusercontent.com/56584082/102687226-85738e80-4228-11eb-8336-84b0d24a48e7.png)


重启clash后，再次打开tap网卡，里面所有的属性都被清空了。   自动变回
![image](https://user-images.githubusercontent.com/56584082/102687245-9d4b1280-4228-11eb-896f-1eb6a5adfd2c.png)

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/102687354-5f9ab980-4229-11eb-8a59-e586f8899875.png)

![image](https://user-images.githubusercontent.com/25523606/102687356-66293100-4229-11eb-9b0c-62fc819b85f5.png)

这个里面强制指定呢？

**Comment by yi-Xu-0100** [comment]
@asdfj2381k 卸载和按照 tap 时有没有弹出任何确认窗口和提示信息？

**Comment by Fndroid** [comment]
小孩不错

**Comment by Fndroid** [comment]
管理员打开cmd，然后输入 ``route print``看看

**Comment by asdfj2381k** [comment]
@Fndroid 
![image](https://user-images.githubusercontent.com/56584082/102687646-7c37f100-422b-11eb-96dc-d4765b16c37a.png)

**Comment by Fndroid** [comment]
tap网卡先卸载重装，再输一次

**Comment by asdfj2381k** [comment]
@yi-Xu-0100 
强制指定里面的信息和你截图是一样的。    安装完成tap时，有提示  （我知道你想问安装时有没有提示信任驱动的那个弹窗，因为我之前装过，所以没有再次弹出）
![Uploading image.png…]()

**Comment by asdfj2381k** [comment]
@Fndroid 
![image](https://user-images.githubusercontent.com/56584082/102687716-e94b8680-422b-11eb-81fe-cdf2a05cab9b.png)

**Comment by asdfj2381k** [comment]
![image](https://user-images.githubusercontent.com/56584082/102687736-0d0ecc80-422c-11eb-8b24-d4da0583fe89.png)

此时的Tap状态是：
![image](https://user-images.githubusercontent.com/56584082/102687744-139d4400-422c-11eb-9f2f-09c833482696.png)

里面的网络属性是：
![image](https://user-images.githubusercontent.com/56584082/102687748-1ac45200-422c-11eb-98bc-b1a59e22a87d.png)

**Comment by Fndroid** [comment]
拔出说明dns没有配置上

**Comment by asdfj2381k** [comment]
@Fndroid  
我的配置文件现在是这样配置dns的
![image](https://user-images.githubusercontent.com/56584082/102688116-780dd280-422f-11eb-8b72-a124cb9ada67.png)

应该如何修改呢。。

**Comment by yi-Xu-0100** [comment]
@asdfj2381k 你这些是写在你选择的配置文件中，还是 config.yaml 中？

**Comment by asdfj2381k** [comment]
@yi-Xu-0100 
clash自带的config.yaml已经被我删掉了。   

![image](https://user-images.githubusercontent.com/56584082/102688329-1d757600-4231-11eb-970c-8339c2f43093.png)

**Comment by Fndroid** [comment]
![](https://user-images.githubusercontent.com/56584082/102687736-0d0ecc80-422c-11eb-8b24-d4da0583fe89.png)

你看你这个图片，用户名就是管理员超级用户，你本来是这个用户么

**Comment by asdfj2381k** [comment]
@Fndroid   我一直都是用Administrator工作的，从来没切换过别的账户。  

![image](https://user-images.githubusercontent.com/56584082/102688369-4b5aba80-4231-11eb-9f08-bb83d33b2026.png)

**Comment by Fndroid** [comment]
用回上一版试试

**Comment by asdfj2381k** [comment]
好的，等我5分钟。我试试，别走开。

**Comment by asdfj2381k** [comment]
@Fndroid 
0.13.6能正常使用，tap也正常了。
虽然不知道为什么，但这可能是0.13.7的BUG。（如果我说错了别打我，哈哈哈）

申请结贴。

**Comment by asdfj2381k** [comment]
附上0.13.6重新安装的tap相关截图。

![image](https://user-images.githubusercontent.com/56584082/102688696-5adb0300-4233-11eb-8f58-4cb09c2b5f8b.png)


![image](https://user-images.githubusercontent.com/56584082/102688701-5f9fb700-4233-11eb-80c3-604d2b556237.png)

**Comment by asdfj2381k** [comment]
其实按道理来说不应该会这样才对，因为0.13.7，我昨天就升级了。  从昨天到今天上午，用了10多个小时了，都是能正常用Tap的。

好怪，好怪。

**Comment by Fndroid** [comment]
应该是小孩给你升级的

**Comment by asdfj2381k** [comment]
我定位出来了。

我先把可以正常工作的0.13.6退出掉， 打开0.13.7。  此时的0.13.7+0.13.6的tap是可以正常使用的。   

然后我用0.13.7的Remove把0.13.6的tap卸载掉
![image](https://user-images.githubusercontent.com/56584082/102688800-33386a80-4234-11eb-807f-4697fa839d26.png)
再用0.13.7install安装一个新的tap

挂了。  不能正常用了。

是0.13.7的 tap install有问题。   我很肯定

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases

**Comment by NOIP117** [comment]
哈哈哈 这个issue给我整笑了 (*^_^*)

**Comment by DevilHandCC** [comment]
> 

+1
