### ISSUE TITLE
cfw0.6.1开启ipv6时，直连无法打开腾讯体育和chiphell

### ISSUE THREAD

**Issue by yzxj3180** [Fndroid/clash_for_windows_pkg#143]
RT，试了global下的直连和direct以及规则的直连，都是无法上这俩网站，geoip的数据库也无法更新。关闭ipv6一切正常，我的设备和网络是支持ipv6的

**Comment by Fndroid** [comment]
配置文件里是不是定义了dns，有的话先删掉看看
