### ISSUE TITLE
期望 macOS Big Sur 系统下 icon 的颜色能够自适应

### ISSUE THREAD

**Issue by louis-neal** [Fndroid/clash_for_windows_pkg#1431]
**描述**
RT.
希望能够安排上呐，老不协调了，目前只能不去更换壁纸。

**其他说明**
本来想自己替换一下资源，拿 ClashX（会黑白变） 的 icon，发现并不会跟随变化呢。
https://stackoverflow.com/questions/41664208/electron-tray-icon-change-depending-on-dark-theme

**Comment by Fndroid** [comment]
big sur之前任务栏颜色是跟随系统的dark mode的，big sur之后是和壁纸也有关系，所以我发了issue问electron官方，他们还tag了一个enhancement：https://github.com/electron/electron/issues/25478

但是你发的这个问题下面说的这个template我试了下居然是可以的，所以下个版本加上

**Comment by louis-neal** [comment]
> big sur之前任务栏颜色是跟随系统的dark mode的，big sur之后是和壁纸也有关系，所以我发了issue问electron官方，他们还tag了一个enhancement：[electron/electron#25478](https://github.com/electron/electron/issues/25478)
> 
> 但是你发的这个问题下面说的这个template我试了下居然是可以的，所以下个版本加上

哈，又可以愉快的自动换桌面啦，老铁辛苦咯！

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
