### ISSUE TITLE
自定义图标使用相对路径时自启动后图标失效

### ISSUE THREAD

**Issue by HimekoEx** [Fndroid/clash_for_windows_pkg#1435]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
![image](https://user-images.githubusercontent.com/49508376/102848868-d6fe6200-4450-11eb-81a8-23946f4dc9d6.png)
以及 WIN10 20H2

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
使用了便携模式
所以将自定义图标也放入到了CFW目录下的/data里

正常启动CFW的话没有问题
但是加上开机自启动的话, 重开机后, 图标就变成默认图标了
必须得手动关闭CFW再重新开启才行

**复现**

[//]: # (请描述复现问题的步骤)

1. 使用便携模式
2. 将自定义图标放入CFW目录下的便携模式文件夹里
3. 手动更改配置文件 `cfw-settings.yaml` 修改行 `iconSystemProxy: .\data\faji.ico` 使用相对地址
4. 开启开机自启动, 开启系统代理
5. 重启机器
6. 状态栏自定义图标并未生效

**截图**

[//]: # (如果可以，请提供对应问题的截图)
正常情况下是可以用的
![image](https://user-images.githubusercontent.com/49508376/102849344-ea5dfd00-4451-11eb-8d34-9c11a5e2fa47.png)

开启自启动后重开机就变成了默认图标
![image](https://user-images.githubusercontent.com/49508376/102849495-3dd04b00-4452-11eb-9f0c-8e0b8bd92dc7.png)

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
