### ISSUE TITLE
wifi开启全局代理无效

### ISSUE THREAD

**Issue by lydlovezjr** [Fndroid/clash_for_windows_pkg#1438]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**
WiFi开全局代理,最新版本不能正常开启
[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x]已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
win10
[//]: # (平台及版本号)
win10 最新版本0.13.7
**描述**

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
切换不过去吗？有相关的演示吗？还是说，单纯无法代理，有日志吗？

**Comment by lydlovezjr** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/747
和这个类似,但是我按照这个设置了,还是不能成功开启代理

**Comment by yi-Xu-0100** [comment]
@lydlovezjr 你说的全局代理是 tap 模式吗？有安装 tap 网卡吗？

**Comment by lydlovezjr** [comment]
是tap模式.
点击了一下那个tap device,然后install了一下,这样算安装了吧.
没有开启mixin

**Comment by lydlovezjr** [comment]
@yi-Xu-0100

**Comment by yi-Xu-0100** [comment]
@lydlovezjr tap 模式需要启动，<https://docs.cfw.lbyczf.com/contents/tap.html>

**Comment by lydlovezjr** [comment]
dns:
   enable: true
   enhanced-mode: redir-host # 或 fake-ip
   listen: 0.0.0.0:53
   nameserver:
      - 223.5.5.5

**Comment by lydlovezjr** [comment]
这个我配置了,佬

**Comment by lydlovezjr** [comment]
@yi-Xu-0100

**Comment by lydlovezjr** [comment]
然后我主要是在cmd里 Git cloneGithub上的项目
然后就很慢,所以我估计应该没有走全局代理吧

**Comment by yi-Xu-0100** [comment]
你配置在配置文件中吗？tap 网卡状况如何，可以截个图吗？你确定你的 tap 网卡是正常工作的吗？

**Comment by lydlovezjr** [comment]
<img width="600" alt="微信截图_20201224165945" src="https://user-images.githubusercontent.com/19246347/103076783-78c8af00-4609-11eb-92de-f8774cadbcbc.png">

**Comment by lydlovezjr** [comment]
![Uploading 微信截图_20201224170033.png…]()

**Comment by lydlovezjr** [comment]
<img width="912" alt="微信截图_20201224170033" src="https://user-images.githubusercontent.com/19246347/103076864-a150a900-4609-11eb-9525-09dfbf00794e.png">

**Comment by lydlovezjr** [comment]
第一张是网络这个,第二张是配置在config.yaml

**Comment by lydlovezjr** [comment]
@yi-Xu-0100

**Comment by yi-Xu-0100** [comment]
这个部分需要配置在选择的配置文件中，或者使用 mixin 整合进去，然后确认 outbound 选择正确，mixin 文档：<https://docs.cfw.lbyczf.com/contents/mixin.html>

![image](https://user-images.githubusercontent.com/25523606/103076925-c34a2b80-4609-11eb-90e8-2c744188150d.png)

**Comment by lydlovezjr** [comment]
选择的配置文件是指的那个啊,佬

**Comment by lydlovezjr** [comment]
@yi-Xu-0100

**Comment by yi-Xu-0100** [comment]
@lydlovezjr profiles 中选择的，需要添加到那个配置文件中（可能是本地文件，可能是远程文件），建议用 mixin ，如果只是加入到 profile 中，更新会被删除修改。mixin 会整合，不会被删除修改。

再一个，如果只是终端使用的话，可以试试点击这里的图标和端口号，图标会触发显示相应的打开配置好环境变量的终端，端口号，会提供设置的语句。

![image](https://user-images.githubusercontent.com/25523606/103077363-9b0efc80-460a-11eb-992b-471cb5a1cdce.png)

**Comment by lydlovezjr** [comment]
<img width="600" alt="微信截图_20201224171114" src="https://user-images.githubusercontent.com/19246347/103077599-0eb10980-460b-11eb-82f4-b57a05949b12.png">

**Comment by lydlovezjr** [comment]
这样是不是就可以了,佬.
但是我用cmd git clone项目还是好慢.

**Comment by lydlovezjr** [comment]
<img width="535" alt="微信截图_20201224171201" src="https://user-images.githubusercontent.com/19246347/103077663-28eae780-460b-11eb-9173-b38c9d392da8.png">

**Comment by lydlovezjr** [comment]
还是十几kb每秒的速度

**Comment by lydlovezjr** [comment]
@yi-Xu-0100

**Comment by yi-Xu-0100** [comment]
@lydlovezjr  是成功的。tap 的性能可能不是特别好，好像后面会使用 tun ，会有改善，理论上这样就是成功的。

速度的话，你可以看下日志中是否有链接，确认下是否走了相关的代理，以及确认代理链路状况如何，还有就是可以试试上面说到的，配置环境变量的方式去为终端设置代理。

**Comment by lydlovezjr** [comment]
配置环境变量的方式去为终端设置代理是指的什么,大佬

**Comment by lydlovezjr** [comment]
@yi-Xu-0100

**Comment by yi-Xu-0100** [comment]
emmm @lydlovezjr 建议搜索下为终端设置代理，了解下，这是以前我自己写的可参考：<https://www.yixuju.cn/other/talking-about-proxy/>

**Comment by lydlovezjr** [comment]
<img width="639" alt="微信截图_20201224172034" src="https://user-images.githubusercontent.com/19246347/103078247-6ac85d80-460c-11eb-91b9-9fec8773910b.png">

**Comment by lydlovezjr** [comment]
这个日志应该是走代理了吧

**Comment by lydlovezjr** [comment]
@yi-Xu-0100

**Comment by lydlovezjr** [comment]
好的,大佬,我看看.谢了.
