### ISSUE TITLE
0.6.1长时间不关机，Global模式切换节点失效，重启app后解决

### ISSUE THREAD

**Issue by faynwol** [Fndroid/clash_for_windows_pkg#144]
系统：win10 1809
CFW版本：0.6.1
关闭系统代理
代理模式全局
浏览器通过扩展控制流量

现象：
一周以来未关机，CFW一直开着，访问myip.ipip.net显示没走代理，切换节点仍旧是直连状态
重启CFW后恢复正常

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/91

**Comment by faynwol** [comment]
一直选择的代理节点，会自动变成DIRECT吗
比如我前一天晚上代理没问题，第二天晚上界面上选择的是代理，但却是直连

**Comment by Fndroid** [comment]
怎么确定它变成直连了

**Comment by faynwol** [comment]
CFW关闭系统代理，代理模式全局，选择代理节点
chrome用proxy switchyomega控制所有域名IP都走clash
访问myip.ipip.net，有问题的时候显示所在地ip，重启CFW，刷新网页，变成代理ip

代理配置
![image](https://user-images.githubusercontent.com/2764772/61581571-af67e380-ab52-11e9-8b05-d889011101cf.png)

全局走代理
![image](https://user-images.githubusercontent.com/2764772/61581572-b68ef180-ab52-11e9-9992-dba0166569fc.png)

不走代理
![image](https://user-images.githubusercontent.com/2764772/61581575-bbec3c00-ab52-11e9-852e-81d9ad0375ad.png)

**Comment by Fndroid** [comment]
这不是变成了直连，而是浏览器可能复用了TCP

**Comment by faynwol** [comment]
即使是浏览器扩展控制全局走代理，也有可能复用tcp导致不走代理吗
ss和v2ray的客户端似乎没这个问题

**Comment by Fndroid** [comment]
Clash不会自动的改变策略模式，如果你确定它变了，那就从最近的log里排查变化的时间点。

即使全局，更换节点也可能会因为keep alive而不会马上切换

**Comment by faynwol** [comment]
需要什么级别的日志才能显示出这种变化？我先用命令行clash试试
