### ISSUE TITLE
Use flat icon for system tray

### ISSUE THREAD

**Issue by xmha97** [Fndroid/clash_for_windows_pkg#1440]
Hi,
Please use flat icon for system tray
![image](https://user-images.githubusercontent.com/23485114/102944063-f2a84d80-44ce-11eb-9d53-711140c9e717.png)
[Icons.zip](https://github.com/Fndroid/clash_for_windows_pkg/files/5732529/Icons.zip)

**Comment by Fndroid** [comment]
You can manage it manually
![image](https://user-images.githubusercontent.com/16091562/102953101-8435b080-450b-11eb-8f87-9fd4e03136ce.png)

**Comment by Fndroid** [comment]
Appreciate your icons though. The icons look nice. 👍

**Comment by shikkoku** [comment]
But this icon in Light theme...

**Comment by xmha97** [comment]
> 
> 
> But this icon in Light theme...

Use it:
[Uploading IconsV2.zip…]()

**Comment by fakhamatia** [comment]
> You can manage it manually ![image](https://user-images.githubusercontent.com/16091562/102953101-8435b080-450b-11eb-8f87-9fd4e03136ce.png)
What in Linux?
