### ISSUE TITLE
【功能请求】希望为文件预处理（parsers）的代理规则功能加入GUI

### ISSUE THREAD

**Issue by ZerOri** [Fndroid/clash_for_windows_pkg#1442]
**描述**
【Profiles】中为修改规则功能提供了GUI界面，简单易操作，小白也能轻易上手，希望也将类似的GUI引入【Setting】的【parsers】中，毕竟用YAML和JS配置自定义代理还是不如GUI来的直观简单，望采纳，感谢。

**其他说明**
请求为parsers加入配置自定义代理规则的GUI

**Comment by yi-Xu-0100** [comment]
一般不用 mixin 设置代理规则，而是用 parser， <https://docs.cfw.lbyczf.com/contents/parser.html>, 这个教程中 yaml 的使用也很方便，毕竟需要得对配置进行操作，有很多的选择项。

**Comment by ZerOri** [comment]
> 一般不用 mixin 设置代理规则，而是用 parser， https://docs.cfw.lbyczf.com/contents/parser.html, 这个教程中 yaml 的使用也很方便，毕竟需要得对配置进行操作，有很多的选择项。

哦，原来如此，谢谢解答

**Comment by HOMHOG** [comment]
> 一般不用 mixin 设置代理规则，而是用 parser， https://docs.cfw.lbyczf.com/contents/parser.html, 这个教程中 yaml 的使用也很方便，毕竟需要得对配置进行操作，有很多的选择项。

请问下大佬对多个订阅地址进行预处理怎么写，url那里

**Comment by ZerOri** [comment]
> > 一般不用 mixin 设置代理规则，而是用 parser， https://docs.cfw.lbyczf.com/contents/parser.html, 这个教程中 yaml 的使用也很方便，毕竟需要得对配置进行操作，有很多的选择项。
> 
> 请问下大佬对多个订阅地址进行预处理怎么写，url那里

可以看wiki有详细说明，这里我给下简要格式

parsers:
  - url:#填写订阅地址
    yaml: 
       prepend-rules:
        - DOMAIN,zh.ifixit.com,GLOBAL#示例网址

![image](https://user-images.githubusercontent.com/46775615/106546599-8d705f00-6546-11eb-8b51-3122ca54bbb0.png)

**Comment by Fndroid** [comment]
使用任何非Github版本，请勿发issue，谢谢合作
