### ISSUE TITLE
providers不会更新

### ISSUE THREAD

**Issue by BaileyZyp** [Fndroid/clash_for_windows_pkg#1443]
- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 20H2

**描述**

providers 规则文件和代理文件不更新，修改过配置文件里的更新时间也不管用

**预期行为**

按照配置设定的时间定时更新providers文件

**Comment by Fndroid** [comment]
更新需要使用TUN或者TAP模式，否则clash发起的请求不会经过代理

**Comment by BaileyZyp** [comment]
@Fndroid 已开启TUN
![image](https://user-images.githubusercontent.com/16634459/103474867-eda6a080-4de2-11eb-9f24-0e795e9e2e42.png)
，确实没有更新过代理，规则文件我不确定 
![image](https://user-images.githubusercontent.com/16634459/103474821-8c7ecd00-4de2-11eb-8d19-3105769e7eb1.png)
我试过点update确实没变化，因为我的本地流量显示247G 
![image](https://user-images.githubusercontent.com/16634459/103474842-b6d08a80-4de2-11eb-9efe-9e39f61eb7e0.png)
我远程文件是218G 
![image](https://user-images.githubusercontent.com/16634459/103474859-d5368600-4de2-11eb-9409-cb5d75473f27.png)

**Comment by BaileyZyp** [comment]
观察了好几天都没变化

**Comment by yi-Xu-0100** [comment]
@BaileyZyp 手动点 provider 中的 update 也不更新？

**Comment by BaileyZyp** [comment]
@yi-Xu-0100 是的，和我通过Mixin配置的dns和tun有没有关系？

**Comment by yi-Xu-0100** [comment]
@BaileyZyp 所以你的 dns 和 tun 相关配置是什么？使用过程中 connections 中是否有相关的显示？

**Comment by BaileyZyp** [comment]
> @BaileyZyp 所以你的 dns 和 tun 相关配置是什么？使用过程中 connections 中是否有相关的显示？

![image](https://user-images.githubusercontent.com/16634459/103540083-1e1a3780-4ed4-11eb-8648-703257389bda.png)

**Comment by BaileyZyp** [comment]
> @BaileyZyp 所以你的 dns 和 tun 相关配置是什么？使用过程中 connections 中是否有相关的显示？
connections 有显示tun链接
![image](https://user-images.githubusercontent.com/16634459/103540198-54f04d80-4ed4-11eb-8653-3250624f4912.png)

**Comment by BaileyZyp** [comment]
@yi-Xu-0100

**Comment by yi-Xu-0100** [comment]
@BaileyZyp 最近几天的 provider 信息都没有更新吗？

**Comment by BaileyZyp** [comment]
@yi-Xu-0100 没有

**Comment by BaileyZyp** [comment]
@yi-Xu-0100 需要日志吗

**Comment by yi-Xu-0100** [comment]
@BaileyZyp 当时我测试的过程中，文件会更新修改日期（疑似按照更新时间），手动点击 update 似乎文件不会更新，最近没有时间测试，等后面抽空再确认测试结果一下，或者等等看看别人是否有相关的测试结果吧。

**Comment by BaileyZyp** [comment]
@yi-Xu-0100 确切的说打开cfw就会修改文件时间，但是内容并为发生改变

**Comment by BaileyZyp** [comment]
@Fndroid 是否可以重新打开这个issues？

**Comment by yi-Xu-0100** [comment]
@BaileyZyp 个人测试如下：
1. 在远程文件更新内容的情况下，会更新本地内容
2. 如果远程文件未更新内容，则不会更新本地内容
3. 个人测试环境为本地 sub ，无网络问题，从 sub 日志中可以看出触发了定时更新和手动更新。
4. 在配置文件更新时，会强制触发 provider 更新

可以增设配置文件更新达到 provider 文件强制更新效果😥，感觉这里的更新逻辑是 core 的，个人的测试结果是这样的，不排除个人原因。

**Comment by BaileyZyp** [comment]
@yi-Xu-0100 那就奇怪了，我远程文件和本地文件内容不一样呀
这个是本地
![image](https://user-images.githubusercontent.com/16634459/104019269-3650c600-51f6-11eb-94e6-e5122d1a35fd.png)
这个是远程
![image](https://user-images.githubusercontent.com/16634459/104019319-4ec0e080-51f6-11eb-8b9b-4edb339abfa0.png)

**Comment by yi-Xu-0100** [comment]
@BaileyZyp 你可以用 本地 sub 将这个远程配置转换下，测试下会不会更新

**Comment by BaileyZyp** [comment]
@yi-Xu-0100 我用自己搭建的API试了下确实可以，难道是用gist的问题？

**Comment by yi-Xu-0100** [comment]
@BaileyZyp 我不知道。。。

**Comment by BaileyZyp** [comment]
@yi-Xu-0100 这个问题有点玄学=.= 我用gist手动更新都没反应，用sub转换一切正常，而且gist内容和本地内容不一样

**Comment by yi-Xu-0100** [comment]
母鸡……只能说，解决就好 @BaileyZyp 网络玄学没法治
