### ISSUE TITLE
Clash For Windows无法在管理员模式下开机自启

### ISSUE THREAD

**Issue by LovelyWei** [Fndroid/clash_for_windows_pkg#1445]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows10, Clash For Windows v0.13.8

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
更新Clash For Windows后尝试使用TUN模式，通过管理员身份运行可以正常使用，但 Clash For Windows 的开机自启无法使用TUN模式，推测是自启的Clash For Windows没有权限，将 `Clash for Windows.exe` 设置为 `以管理员身份运行` 后，Clash For Windows 无法开机自启。

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'C:\Users\Admin\AppData\Local\Programs\Clash for Windows'
2. 右键点击 `Clash for Windows.exe` -> 属性 -> 兼容性 -> 以管理员身份运行 -> 确定 -> 重启系统
3. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)
希望能有开机自启就能使用 TUN模式 的解决方案

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/16489620/103137471-549dc880-4704-11eb-95c4-65883416f33b.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
系统是这样

**Comment by shikkoku** [comment]
可以用Windows的计划任务高权限自启，不过我这边托盘图标没了，点不出来CFW，实际在运行中。

**Comment by lycor1s** [comment]
![image](https://user-images.githubusercontent.com/23312700/103333544-3be93600-4aa9-11eb-9d85-8c9e988d3cc0.png)
![image](https://user-images.githubusercontent.com/23312700/103333551-43a8da80-4aa9-11eb-8a14-f6d02029a41b.png)
![image](https://user-images.githubusercontent.com/23312700/103333558-499ebb80-4aa9-11eb-9aa8-0aa824beca9e.png)

同楼上

**Comment by LovelyWei** [comment]
计划任务确实可以...但是希望在程序里修改下自启下实现方式.

**Comment by shikkoku** [comment]
> 计划任务确实可以...但是希望在程序里修改下自启下实现方式.

可以是可以，但没有托盘图标，我没法打开主界面。

**Comment by BaileyZyp** [comment]
+1 我也这样 每次开机都手动管理员身份运行一次

**Comment by Fndroid** [comment]
service mode已经在测试了，耐心等下吧

**Comment by BaileyZyp** [comment]
@Fndroid 等待每周五更新中！！

**Comment by LovelyWei** [comment]
安装服务后好了,谢谢!

**Comment by Agan42** [comment]
> 安装服务后好了,谢谢!

哥们最后咋解决的

**Comment by free-angel** [comment]
![image](https://user-images.githubusercontent.com/68370467/216252888-fa42e4d2-cbe8-4281-8d49-dbb9df6a5f71.png)
