### ISSUE TITLE
profiles中，输入订阅链接下载后出错

### ISSUE THREAD

**Issue by charpng** [Fndroid/clash_for_windows_pkg#1446]
你好，
Could not switch to this profile
Error:Cannot read property 'dns' of null
是否表示当前这个profile失效了？

**Comment by Mit2g** [comment]
你的配置文件中有dns字段却无相应内容 请尝试删除相关字段
如果依然无法解决 请将配置文件脱敏后上传供人排查

**Comment by Fndroid** [comment]
在浏览器打开地址看一下不就好了

**Comment by charpng** [comment]
> 在浏览器打开地址看一下不就好了

在浏览器中打开页面是空白的，在profiles里选择edit in text mode打开后也是空白的
大概在24,25日之间出现的问题

**Comment by yi-Xu-0100** [comment]
@charpng 如果浏览器打开都是空白，恐怕这个链接没有任何内容了。问问服务商吧。

**Comment by Chiritttttt** [comment]
老铁，请问解决问题了吗
