### ISSUE TITLE
是否可以添加支持`vmess://`和`ss://`分享链接的支持

### ISSUE THREAD

**Issue by minexss11** [Fndroid/clash_for_windows_pkg#145]
如题，目前好像只支持yml配置文件

**Comment by Fndroid** [comment]
1. 不会支持直接导入“ Shadowsocks 订阅”作为配置，因为没有规则和策略
2. 如果是通过 UI 配置节点，暂时没有计划支持 Shadowsocks URI
3. v2ray 官方并未提供 vmess:// 规范，无从讨论
