### ISSUE TITLE
[Wintun] WintunOpenAdapter: Failed to impersonate SYSTEM user

### ISSUE THREAD

**Issue by LittleRey** [Fndroid/clash_for_windows_pkg#1453]
[//]: # (如不按模版填写，则issue将被直接关闭)

**time="2020-12-28T21:58:17+08:00" level=info msg="[Wintun] WintunOpenAdapter: Failed to impersonate SYSTEM user"

time="2020-12-28T21:58:17+08:00" level=info msg="[Wintun] WintunCreateAdapter: Failed to impersonate SYSTEM user"

time="2020-12-28T21:58:17+08:00" level=error msg="Start Tun interface error: Error creating interface: Access is denied."**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**win10**

[//]: # (平台及版本号)

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
是否使用管理员方式打开 cfw ？

<https://docs.cfw.lbyczf.com/contents/tun.html>

**Comment by LittleRey** [comment]
我发现了这个问题，然后我试了以管理员权限，不报错了，但是问题是，开机自启怎么设置管理员权限

**Comment by LittleRey** [comment]
> 是否使用管理员方式打开 cfw ？
> 
> https://docs.cfw.lbyczf.com/contents/tun.html
我发现了这个问题，然后我试了以管理员权限，不报错了，但是问题是，开机自启怎么设置管理员权限

**Comment by yi-Xu-0100** [comment]
@LittleRey 使用window系统任务计划。指定高级的权限组
