### ISSUE TITLE
ssr

### ISSUE THREAD

**Issue by liao6964799** [Fndroid/clash_for_windows_pkg#1454]
无法下载ssr转换的订阅链接,是不支持吗?

**Comment by yi-Xu-0100** [comment]
理论上是支持的，可能是部分的加密类型不支持，所以报啥错误。有日志吗？或者报错相关的截图

**Comment by liao6964799** [comment]
![image](https://user-images.githubusercontent.com/35887374/103272548-21a34f80-49f8-11eb-8cc6-8705abebdbdf.png)
是ss链接哈

**Comment by yi-Xu-0100** [comment]
@liao6964799 **你订阅链接暴露了**，400 的话，<https://www.runoob.com/w3cnote/http-400.html>

**Comment by yi-Xu-0100** [comment]
应该是你的格式问题吧，注意看要求啥的

![image](https://user-images.githubusercontent.com/25523606/103272830-c9b91880-49f8-11eb-8b6d-4cac6ea23336.png)

**Comment by liao6964799** [comment]
可能是吧,我也不清楚,是别人分享的链接,谢谢

**Comment by Fndroid** [comment]
https://github.com/Dreamacro/clash/wiki/configuration
