### ISSUE TITLE
希望mac下增加  增强模式

### ISSUE THREAD

**Issue by weijinsun** [Fndroid/clash_for_windows_pkg#1459]
**描述**
就是其他软件也可以走代理, 终端也可以走代理
举例:比如clashx pro的增强模式 开启后,终端也可以直接走代理

**Comment by yi-Xu-0100** [comment]
<https://docs.cfw.lbyczf.com/contents/tun.html>

**Comment by weijinsun** [comment]
> https://docs.cfw.lbyczf.com/contents/tun.html

谢谢 明白了
