### ISSUE TITLE
无法加载profiles，点击就会报错

### ISSUE THREAD

**Issue by bjfstc1** [Fndroid/clash_for_windows_pkg#146]
点击切换配置文件就会报错，添加订阅的时候也会报错一次，都是一样的提示：
yaml: unmarshal errors: line 1: cannot unmarshal !!str 'c3NyOi8...' into config.rawConfig

log里面只有
time="2019-07-23T16:51:18+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2019-07-23T16:51:18+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2019-07-23T16:51:18+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2019-07-23T16:51:18+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"

**Comment by Fndroid** [comment]
配置文件格式错误

**Comment by bjfstc1** [comment]
那请问我应该怎么做呢？我之前用的0.5的版本一直都正常的，今天重装win然后安装了0.6.2，就一直报错了。。。

**Comment by Fndroid** [comment]
按照提示修改，提示第1行有错，就打开改掉

**Comment by bjfstc1** [comment]
可是我的配置文件打开里面都是下面这种好多。。。download和directmode都这样的文件。。。
c3NyOi8vYzJndVkzUnRMbTFoTGpFdVptRnpkRzV2WkdVdWRHOXdPakV3TlRnd09qcHlZelF0YldRMU9qcF

**Comment by Fndroid** [comment]
因为导入的不是Clash配置文件

**Comment by wuyudi** [comment]
@bjfstc1  去找一个转换订阅的网站，转出来的链接可以用。
