### ISSUE TITLE
托盘图标显示异常

### ISSUE THREAD

**Issue by LagoLagoLago** [Fndroid/clash_for_windows_pkg#1460]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

Windows 10 专业版
版本号	20H2
安装日期	‎2020/‎10/‎27
操作系统版本	19042.685
体验	Windows Feature Experience Pack 120.2212.551.0

[]: # (软件版本V0.13.8)

Clash开着没有挂代理，图标是正常的深色，然后我下班盖上笔记本第二天再打开，需要使用开机键打开电脑，但是所有的软件都是和盖上之前一样的，不需要再重新启动，所以可以理解为电脑从睡眠中启动后，无论开关代理托盘图标都不会再改变了，永远是深色，需要重启软件才能正常

**Comment by yi-Xu-0100** [comment]
未复现……我是笔记本，使用流程和你一样，能够正常切换系统代理，切换系统代理后，图标会正常切换。

**Comment by LagoLagoLago** [comment]
> 未复现……我是笔记本，使用流程和你一样，能够正常切换系统代理，切换系统代理后，图标会正常切换。
> 
> CFW 什么版本？

最新版 0.13.8，我早上都要按开机键开机，还会显示BIOS的动画，但软件状态都是关机之前的样子，是不是这个睡眠有点狠，你window版本和我一样吗？

**Comment by yi-Xu-0100** [comment]
@LagoLagoLago 一样，按开机键开机，软件没变化，win10 20H2 正常使用

**Comment by yi-Xu-0100** [comment]
@LagoLagoLago 你切换的时候，看看 系统代理 那个有没有被修改，是用管理员方式吗？

**Comment by LagoLagoLago** [comment]
@yi-Xu-0100 我好像没有以管理员身份运行，我重新以管理员身份运行了，下次再看看，我先把这个issue关掉

**Comment by yi-Xu-0100** [comment]
@LagoLagoLago 下次看看切换系统代理的时候，在系统网络那里是否成功了，默认其实是不使用管理员身份的。🤔

**Comment by LagoLagoLago** [comment]
@yi-Xu-0100 系统网络是哪里，我切换之后是可以正常代理的哦，就是那个图标颜色不改变了，windows系统有些问题可能开管理员身份就好了 哈哈

**Comment by yi-Xu-0100** [comment]
@LagoLagoLago 设置里面，这个图标显示的状态是这个开启和关闭的状态，windows 的浏览器走的就是这个系统代理。

![image](https://user-images.githubusercontent.com/25523606/103392549-67c3f480-4b59-11eb-9535-7f607f9241f8.png)

**Comment by LagoLagoLago** [comment]
@yi-Xu-0100 好 我下次看一下，谢谢了😊

**Comment by yi-Xu-0100** [comment]
不过你这个问题好像在其他的 issue 中有一些人也有遇到。 如#1272  #1435 ，看看后面是否能够找到是什么因素导致的吧

**Comment by LagoLagoLago** [comment]
@yi-Xu-0100 好的

**Comment by xk-mt** [comment]
我也遇到了，不显示图标
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/77874955/91c63ac5-253a-4d0d-9248-39a7ea3f4732)
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/77874955/78ba5054-d3fd-4eb9-89bc-5a6400dec962)
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/77874955/b98af7de-747c-4e59-8fcb-e77474e770ad)

**Comment by xk-mt** [comment]
> 我也遇到了，不显示图标
 ![image](https://user-images.githubusercontent.com/77874955/246350184-91c63ac5-253a-4d0d-9248-39a7ea3f4732.png)
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/77874955/0d302a50-06c6-41b6-8baf-58381c4bd6de)
![image](https://user-images.githubusercontent.com/77874955/246350257-b98af7de-747c-4e59-8fcb-e77474e770ad.png)
