### ISSUE TITLE
用了Netch加速游戏后，clash就不能用了

### ISSUE THREAD

**Issue by MsorryMSCei** [Fndroid/clash_for_windows_pkg#1461]
用了Netch加速游戏后，clash就不能用了，是什么问题，冲突了

**Comment by yi-Xu-0100** [comment]
应该是的

**Comment by shikkoku** [comment]
Netch TAP模式会冲突，你要一起看建议Netch用进程方式代理游戏。
PS:现在Clash TUN模式也支持进程代理了，你可以体验一下效果。

**Comment by manbading** [comment]
> Netch TAP模式会冲突，你要一起看建议Netch用进程方式代理游戏。
> PS:现在Clash TUN模式也支持进程代理了，你可以体验一下效果。
这两天一直在折腾这个TUN模式，一直都不成功，报Network Error，不知道什么原因，大佬是否折腾成功？可否指导一下

**Comment by yi-Xu-0100** [comment]
@manbading 建议新开 issue 并给出日志，mixin 或者 配置中相关的设置，截图等信息。

**Comment by DancingLeaf123** [comment]
不知道为啥，开了TUN，好像不冲突了
