### ISSUE TITLE
> @deng-dengdengdeng-deng 元旦快乐~ 只新建一个空的 data 文件夹，用非管理员方式打开呢？如果还是报错， data 文件夹中有生成相关的文件吗？ 日志内容有变化吗？

### ISSUE THREAD

**Issue by deng-dengdengdeng-deng** [Fndroid/clash_for_windows_pkg#1462]
> @deng-dengdengdeng-deng 元旦快乐~ 只新建一个空的 data 文件夹，用非管理员方式打开呢？如果还是报错， data 文件夹中有生成相关的文件吗？ 日志内容有变化吗？
> 
> 如果启动软件后，报错， data 文件夹中没有 config.yaml ，新建一个空的 config.yaml 重启软件试试呢？

启动软件后，data文件夹里会生成四个文件，包括config.yaml，repair时，也可以看到文件被清空然后重新生成。
![MNS%C8$KRZNKXV}3H`JTMHQ](https://user-images.githubusercontent.com/65409577/103433140-8b338180-4be3-11eb-8823-490347c8826e.png)

以非管理员权限打开后，出现了两种情况，一种是和上面一样，直接出现no such file，刚刚出现了另一种情况，连接一段时间后（大概10s），断开，然后报错

![_B@(0~CVW1NFY$5M`IYV 2V](https://user-images.githubusercontent.com/65409577/103433147-cfbf1d00-4be3-11eb-9a5a-302e9d9602cd.png)
文档如下。
time="2021-01-01T11:40:53+08:00" level=info msg="Start initial compatible provider Proxy"
time="2021-01-01T11:40:53+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2021-01-01T11:40:53+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2021-01-01T11:40:53+08:00" level=warning msg="[TCP] dial DIRECT (match Match/) to raw.githubusercontent.com error: lookup raw.githubusercontent.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."
time="2021-01-01T11:40:53+08:00" level=warning msg="[TCP] dial DIRECT (match Match/) to raw.githubusercontent.com error: lookup raw.githubusercontent.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."
time="2021-01-01T11:40:53+08:00" level=info msg="[TCP] 127.0.0.1:51143 --> api.github.com match Match() using DIRECT"
time="2021-01-01T11:40:53+08:00" level=info msg="[TCP] 127.0.0.1:51136 --> ims-prod06.adobelogin.com match Match() using DIRECT"
time="2021-01-01T11:40:54+08:00" level=info msg="[TCP] 127.0.0.1:51148 --> clientservices.googleapis.com match Match() using DIRECT"
time="2021-01-01T11:40:55+08:00" level=info msg="Start initial compatible provider Proxy"
time="2021-01-01T11:40:57+08:00" level=info msg="[TCP] 127.0.0.1:51156 --> clientservices.googleapis.com match Match() using DIRECT"
time="2021-01-01T11:40:59+08:00" level=info msg="[TCP] 127.0.0.1:51159 --> subcon.py6.pw match Match() using DIRECT"
time="2021-01-01T11:40:59+08:00" level=warning msg="[TCP] dial DIRECT (match Match/) to clients4.google.com error: dial tcp4 172.217.27.142:443: i/o timeout"
time="2021-01-01T11:41:00+08:00" level=info msg="[TCP] 127.0.0.1:51163 --> subcon.dlj.tf match Match() using DIRECT"
time="2021-01-01T11:41:01+08:00" level=info msg="Start initial compatible provider 🌍 国外媒体"
time="2021-01-01T11:41:01+08:00" level=info msg="Start initial compatible provider 🍎 苹果服务"
time="2021-01-01T11:41:01+08:00" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2021-01-01T11:41:01+08:00" level=info msg="Start initial compatible provider 📲 电报信息"
time="2021-01-01T11:41:01+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2021-01-01T11:41:01+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2021-01-01T11:41:01+08:00" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2021-01-01T11:41:01+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2021-01-01T11:41:01+08:00" level=info msg="Start initial compatible provider 📢 谷歌FCM"
time="2021-01-01T11:41:01+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2021-01-01T11:41:01+08:00" level=info msg="Start initial compatible provider 🍃 应用净化"
time="2021-01-01T11:41:03+08:00" level=info msg="[TCP] 127.0.0.1:51234 --> ims-prod06.adobelogin.com match Match() using 🐟 漏网之鱼[🇭🇰 香港V2 电信极速AGA-N2 1x]"
time="2021-01-01T11:41:04+08:00" level=warning msg="[TCP] dial DIRECT (match Match/) to clients4.google.com error: dial tcp4 172.217.27.142:443: i/o timeout"

_Originally posted by @deng-dengdengdeng-deng in https://github.com/Fndroid/clash_for_windows_pkg/issues/1458#issuecomment-753249316_

**Comment by yi-Xu-0100** [comment]
这里可以关闭。
