### ISSUE TITLE
请各位帮我看一下我的tun是否设置正确，谢谢

### ISSUE THREAD

**Issue by asayake777** [Fndroid/clash_for_windows_pkg#1464]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # ()
win10 20H219042.685

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
原来使用tap功能可以使onenote、OneDrive同步，即代理系统流量，改成tun模式却没法实现了
原来的步骤（tap模式）:安装tap，重启cfw，可代理系统，onenote、OneDrive走代理
现在的步骤（tun）：
1.卸载tap，下载wintun并将x86移动到home directory
![image](https://user-images.githubusercontent.com/45709525/103433892-53333b00-4bf1-11eb-84aa-43a225d27fa3.png)
2.更改minxin文件
![image](https://user-images.githubusercontent.com/45709525/103433905-92618c00-4bf1-11eb-8a36-d4fc1519df3a.png)
3.管理员启动cfg并打开mixin
4.OneNote无法同步

**预期行为**

[//]: # (清晰地描述期望看到的行为)
能代理系统流量

**日志**

[//]: # (上传触发问题对应的日志文件)
尴尬的是我甚至不知道怎么上传log，只能发一部分截图，对不起
![image](https://user-images.githubusercontent.com/45709525/103434150-26812280-4bf5-11eb-9ec1-66f852f8ac2e.png)

**其他说明**

原来使用tap模式时，浏览器使用SwitchyOmega插件，在系统代理下是可以直接访问外网的，经过我一番设置tun模式就不行了，这应该也是没正确设置tun模式的一个现象
![image](https://user-images.githubusercontent.com/45709525/103434171-7eb82480-4bf5-11eb-8c24-1d8bbc8c861e.png)

[//]: # (其他补充内容)
由于没有计算机功底，可能问的有些小白，希望大家给予帮助

**Comment by yi-Xu-0100** [comment]
@asayake777 linsten 字段是开启 tap 的应该删除，tun 应该和 dns 同一缩进，出现两个 mixin 了，系统劫持按文档的走，

文档: <https://docs.cfw.lbyczf.com/contents/tun.html>

**Comment by yi-Xu-0100** [comment]
理论上说， tap 模式下，无需使用插件，开启系统代理的情况下，也无需使用插件。

日志的话，复制粘贴，用代码块包裹，见下例：
````
```
需要保留格式的内容，比如 mixin 的内容，和日志等等
```
````

**Comment by asayake777** [comment]
感谢回复，你说的5个错误我都修改好了就成功了，thank you
