### ISSUE TITLE
用allow lan手机telegarm不能用

### ISSUE THREAD

**Issue by lklx520** [Fndroid/clash_for_windows_pkg#1467]
**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
win10  LTSC

**描述**
用allow lan手机也设置好了，手机已经可以用上youtube了，但是谷歌应用商店和telegarm不能用

**Comment by yi-Xu-0100** [comment]
@lklx520 清除谷歌应用商店的数据试试呢，telegram 是不是使用了自定义的代理

**Comment by LinKai945** [comment]
@lklx520 我也有一样的问题,tg手机版要单独设置代理,在设置->数据和存储->代理

**Comment by HXHGTS** [comment]
tg要走allow lan的话必须在软件里单独设置，否则不遵循代理规则

**Comment by Fndroid** [comment]
tg自己的问题
