### ISSUE TITLE
能否加入中文选项或者可以修改语言，如果能够有大佬教修改方法也可以

### ISSUE THREAD

**Issue by SummerSnowr** [Fndroid/clash_for_windows_pkg#1468]
**描述**额，看不懂基本都是英语的界面
请具体并清楚地描述期望功能及期望的效果

**其他说明**
其他补充内容

**Comment by SummerSnowr** [comment]
还有就是我的原生的ssr订阅地址跟其他的订阅地址添加不进去得用网页转换一下，能不能加一个自动转化的功能或者提供一个转换方法。

**Comment by Fndroid** [comment]
没有计划

**Comment by SummerSnowr** [comment]
原生的ssr订阅地址跟其他的订阅地址添加不进去得用网页转换一下，能不能加一个自动转化的功能或者提供一个转换方法。

**Comment by yi-Xu-0100** [comment]
@SummerSnowr

 https://acl4ssr.netlify.app/

网络资源，安全自查

**Comment by SummerSnowr** [comment]
> @SummerSnowr
> 
> https://acl4ssr.netlify.app/
> 
> 网络资源，安全自查

谢谢
