### ISSUE TITLE
配置providers proxy后配置文件预处理问题

### ISSUE THREAD

**Issue by BaileyZyp** [Fndroid/clash_for_windows_pkg#1469]
- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 20H2

**描述**

配置provides proxy后，配置文件proxies下无节点，使用配置文件预处理后会报错
![image](https://user-images.githubusercontent.com/16634459/103451440-1bb2b480-4cff-11eb-82f6-ae8f5fcdcc1c.png)

发现是proxies的问题
![image](https://user-images.githubusercontent.com/16634459/103451381-82839e00-4cfe-11eb-94be-c552a022c976.png)

修改为proxies: null后正常
![image](https://user-images.githubusercontent.com/16634459/103451426-f32aba80-4cfe-11eb-8105-09cff21e6f0a.png)

**Comment by yi-Xu-0100** [comment]
直接 `proxies:` 行不？

**Comment by BaileyZyp** [comment]
@yi-Xu-0100 试了一下，可以的

**Comment by BaileyZyp** [comment]
> 直接 `proxies:` 行不？

我原本配置就是 `proxies:` 配置预处理完给我加的null

**Comment by yi-Xu-0100** [comment]
@Fndroid 使用示例的 yaml 方式对配置文件处理，即可复现。

**Comment by Fndroid** [comment]
proxies本来就不应该是null

**Comment by yi-Xu-0100** [comment]
@Fndroid 配置中如果为 `proxies:` 或者 `proxies: null`，则不会报错。后者可由前者 yaml 转 json 转 yaml 得到（我使用 js 中的预处理方式中的预置的 yaml 包直接转换得到的）。

```js
//test.js
module.exports.parse = async (raw, { yaml }) => {
  var rawObj = yaml.parse(raw);
  raw = yaml.stringify(rawObj);
  return raw;
};
```

但是使用 parser 预置的 yaml 语句后，会被处理为

```yaml
proxies:
  - null
```

这种形式对应的数据结构与原配置中不一样，如果是 json 版本的话，原来的数据应该是：

```json
{
  "proxies": null
}
```

而 parser 预置的 yaml 语句处理后（即使没有涉及该关键词），数据变化为：

```json
{
  "ssr": [
    null
  ]
}
```

造成读取错误。而如果删除 `proxies` 关键词，配置中有 `proxy-providers`, 会报出 `error: proxy [Proxies] not found` 的错误。

**Comment by Fndroid** [comment]
所以在``proxies``认为是数组的情况下，为什么不写``proxies: []``

**Comment by BaileyZyp** [comment]
> 所以在`proxies`认为是数组的情况下，为什么不写`proxies: []`

谢谢，这么写确实可以了，我也不懂这些光会用，配置都是看着文档写的

**Comment by yi-Xu-0100** [comment]
@Fndroid 

个人认为，core 对这个配置的推断是支持 `proxies:` 和 `proxies: null` 的，这两者应该是等价的，都表示该字段是不可枚举的（或者说枚举对象数目为 0）。而 `proxies: []` 也同样表示这个字段是数组类型，但也是没有枚举对象的。我找到配置中使用的是 `proxies:`，可能是少点需要写的？而如果支持 `proxies:` 这样的形式，说明本身会对没有值的情况给定默认值，而不需要去考虑设置的空值也需要符合默认类型。如在 workflow 中
```yaml
on:
  push:
```
也是支持的，他会给定这种缺省情况以默认值。

在 cfw 中 parser 默认的 yaml 处理会将这个没有枚举对象的含义更改为，有键值且第一个键值为 null。造成 core 在判断的过程中，对原本兼容的地方报错了。我想原配置在 core 的情况下是能够识别的，但是由于 parser 默认的 yaml 处理后的数据格式与 core 设置的默认值不一致，造成不符合 core 的规则了而无法识别是不太合理的。

而同样在 js 的 yaml 的处理过程中，不会造成这样的问题，二者也存在着一定的差异，而 js 的 yaml 库将 proxies 设置为 null 的方式更符合 core 中对 yaml 的默认值的处理规则。

**Comment by Fndroid** [comment]
@yi-Xu-0100 

``null``和``[]``本来就不同，core可以识别，因为core读到什么都没关系，反正不处理，但是cfw处理

如果你读到一个``proxies: null``，他又写了``appendRules: [...]``你要怎么处理，忽略这个append吗，还是把``null``认为是空数组帮他append？

**Comment by yi-Xu-0100** [comment]
@Fndroid 

嗯，也就是现在在 cfw 的 yaml 预置处理方法需要对其处理，但是奇怪的是，`proxies: ` 被读取应该是为 `proxies: null`, 我想处理成 `proxies: []` 应该更合适，但是默认却处理为 `proxies: [null]`。 而 `proxies: []` 和 `proxies: [null]` 也是不同的，而这种不同的默认值，后者会被报错。

情况1：如果读取到 `proxies: null` 时，写了 `append-rules: [...]`，但是这个 append 不影响 proxies 的话，此时应该不需要处理 proxies 吧，即忽略对 proxies 的操作。
情况2：如果读取到 `proxies: null` 时，写了 `append-proxies: [...]`，这个 append 会影响 proxies ，此时把 null 认为是**空数组(即 `[]` 而不是 `[null]`)**，帮他 append。

现在的情况是：
情况1： 即使没有和 proxies 相关的操作， `proxies:` 和 `proxies: null` 被处理为 `proxies: [null]`, yaml 格式变更为 
```yaml
proxies:
  - null
```
情况2， 测试为用例为下：
```yaml
yaml:  # 使用的文档的示例
  append-proxies: 
    - name: test
      type: http
      server: 123.123.123.123
      port: 456
```
yaml 格式变更为 
```yaml
proxies:
  - null
  - name: test
    type: http
    server: 123.123.123.123
    port: 456
```
二者都会报错。

**Comment by yi-Xu-0100** [comment]
@Fndroid 😋我不知道具体的这里的实现，经过我下面的测试，我有一些推测，和对推测结果的处理。以下都在配置文件中为 `proxies:` 的情况下测试。

1. 使用如下 yaml 处理，
```yaml
yaml:
  append-proxies:
```

处理结果为
```yaml
proxies:
  - null
  - null
```

2. 使用如下 yaml 处理，
```yaml
yaml:
  prepend-proxies:
```
处理过程报错为 `Downloadprofile(xxx) failed with error: [Parser Error] Cannot read property 'cancat' of null`

3. 使用如下 yaml 处理，
```yaml
yaml:
  prepend-proxies: []
```
则不会报错，而且处理结果为
```yaml
proxies:
  - null
```

综上，我的推测是，变量 a、b、c 初始默认值为 `[]`， `prepend-proxies`, `proxies`, `append-proxies` 分别读取后复制给这三个变量，然后这里的合并使用了 `var d = a.cancat(b,c)`, 最后将 d 作为 `proxies` 返回给配置文件。而如果这三者的后两者是 `null` 时，会被当作键值合并到数组中，如果这三者的第一个为 `null` 时，则会报出上面第二个测试的错误。

我对上述的推测的处理是这样想的，是否可以直接将读取到的值赋值给 a、b、c ，然后使用 `var d = (a || []).cancat(b || [],c || [])` 的方式获得合并后的 `proxies`，这样来规避 a、b、c 这三者的默认值设置，并为 `null` 和 `undefined` 的情况下设置为 `[]`。

最后，上面只是我个人的推测和想法，可能与实际情况不符合或者相去甚远😅，但是我还是觉得 cfw 将这里 core 不会报错的地方，经过处理后而产生了报错的话，算是一个 bug, 至少值得修复😀。

**Comment by yi-Xu-0100** [comment]
@BaileyZyp 新版本对此问题修复了，可关闭 issue 了

**Comment by BaileyZyp** [comment]
> @BaileyZyp 新版本对此问题修复了，可关闭 issue 了

OK

**Comment by BaileyZyp** [comment]
> @BaileyZyp 新版本对此问题修复了，可关闭 issue 了

收到
