### ISSUE TITLE
pycharm使用clash连接问题

### ISSUE THREAD

**Issue by toonbear** [Fndroid/clash_for_windows_pkg#1470]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
win10专业版
[//]: # (平台及版本号)

v0.13.4

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)
1、使用clash，可以正常浏览Google，但使用pycharm请求国内、国外网站均报错。
2、参考了本版另一篇帖子，将settings 中的 system proxy从http切换为pac后，浏览器国内、国外站均正常访问，pycharm可以正常访问国内网站，但例如google与youtube之类的网站还是无法连接，console输出为
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
3、尝试将连接模式改为global、rule均不能解决问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by toonbear** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/59920777/103453816-bf5c8e80-4d18-11eb-998f-49882654b399.jpg)
补充pycharm设置

**Comment by yi-Xu-0100** [comment]
感觉不是应该使用 manual proxy configuration 设置代理吗？

**Comment by toonbear** [comment]
> 感觉不是应该使用 manual proxy configuration 设置代理吗？
请教下如果使用手动模式，如何得知自己的host name      port number      以及下面的授权信息
如果使用系统代理模式，哪里查看pac 的url

**Comment by yi-Xu-0100** [comment]
@toonbear 如果准备让 pycharm 走 cfw 的代理规则，设置 host 为 127.0.0.1， 端口为配置中的对应端口，默认一般是 7890.

pac 的话，你切换成 pac 模式的时候，在系统的设置中找到代理，会有相关的设置url。但是随机控制端口的存在，会让 url 不固定

**Comment by toonbear** [comment]
> @toonbear 如果准备让 pycharm 走 cfw 的代理规则，设置 host 为 127.0.0.1， 端口为配置中的对应端口，默认一般是 7890.
> 
> pac 的话，你切换成 pac 模式的时候，在系统的设置中找到代理，会有相关的设置url。但是随机控制端口的存在，会让 url 不固定

感谢大佬热心解答，我以为在pycharm设置代理代码中就可以不设置proxies了，刚刚设置了一下就好了，非常抱歉以及感谢

**Comment by unachris** [comment]
> > @toonbear 如果准备让 pycharm 走 cfw 的代理规则，设置 host 为 127.0.0.1， 端口为配置中的对应端口，默认一般是 7890.
> > pac 的话，你切换成 pac 模式的时候，在系统的设置中找到代理，会有相关的设置url。但是随机控制端口的存在，会让 url 不固定
> 
> 感谢大佬热心解答，我以为在pycharm设置代理代码中就可以不设置proxies了，刚刚设置了一下就好了，非常抱歉以及感谢

大佬，我目前也遇到这个问题。pycharm是设置 host 为 127.0.0.1， 端口为 7890. 然后在代码里面是要怎么设置呢？

**Comment by yi-Xu-0100** [comment]
@unachris 代码里？这个是给 pycharm 开代理，然后注意确认端口是否是这个，看 general

**Comment by unachris** [comment]
> @unachris 代码里？这个是给 pycharm 开代理，然后注意确认端口是否是这个，看 general

嗯，我也是打算给pycharm开代理的，但是总是连不上。HTTP的方式，host 为 127.0.0.1， 端口为 7890，check connection的时候是成功的，但是运行程序还是无法连接特定网站

**Comment by yi-Xu-0100** [comment]
@unachris 你运行的代码是看你写的语句加代理过程吧。pycharm 加代理，只是下载一些库的时候能代理下载。

**Comment by Luuucy987** [comment]
pycharm2022
clash 代理设置为TUN模式【详情youtube】
且pycharm里也手动配置代理，ip为127.0.0.1，端口为443【这个根据你clash代理的端口决定】
能实现真全局代理，也包括pycharm，成功解决这个问题
