### ISSUE TITLE
Proxy Group name can not contain ',' comma!

### ISSUE THREAD

**Issue by jayagami** [Fndroid/clash_for_windows_pkg#1474]
[//]: # (如不按模版填写，则issue将被直接关闭)

Proxy Group name can not contain ',' comma!

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ x] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

Windows10 2004

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

For example
Set a proxy group name to 'hello, the world'
Then change to 'hello'

**预期行为**

[//]: # (清晰地描述期望看到的行为)

No problem

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

when comma in the proxy group name, the program can not change it to a new name.

**Comment by yi-Xu-0100** [comment]
@jayagami Well, in my test, `'hello, the world'` is ok.

![image](https://user-images.githubusercontent.com/25523606/103473157-49b3f980-4dd0-11eb-89dd-5e8f01e3c1bb.png)

But due to the rule match will separate with the comma, the name can not be used in `rules`.  Only can be used for the show.

**Comment by jayagami** [comment]
> @jayagami Well, in my test, `'hello, the world'` is ok.
> 
> ![image](https://user-images.githubusercontent.com/25523606/103473157-49b3f980-4dd0-11eb-89dd-5e8f01e3c1bb.png)
> 
> But due to the rule match will separate with the comma, the name can not be used in `rules`. Only can be used for the show.

Thanks for replying.
Sorry for did not make myself clear, that is what I trying to say.
Once a comma in a group name, it can't be changed.

**Comment by yi-Xu-0100** [comment]
@jayagami  I think this should be considered by the profile providers. 

The profile cannot be recognized due to not fitting the syntax of the profile.

The profile will not work when it uses an extra comma in rules. This is the syntax of the profile.

In order to fix possible errors, the corresponding adaptation method is given, and the grammar rules will be useless. We have to adapt all the ways that may break the rules to create a more compatible grammar. I think this is an impact on the rules and will weaken the need to follow the rules.

**Comment by jayagami** [comment]
> @jayagami I think this should be considered by the profile providers.
> 
> The profile cannot be recognized due to not fitting the syntax of the profile.
> 
> The profile will not work when it uses an extra comma in rules. This is the syntax of the profile.
> 
> In order to fix possible errors, the corresponding adaptation method is given, and the grammar rules will be useless. We have to adapt all the ways that may break the rules to create a more compatible grammar. I think this is an impact on the rules and will weaken the need to follow the rules.
> 
> I think if you need it, you can use the js processing method of `parser` to modify.

Thanks, I get it. 
I'll pay attention to this.
Of course, the comma is not necessary in most cases, just in case.
