### ISSUE TITLE
有两个问题咨询下

### ISSUE THREAD

**Issue by wajika** [Fndroid/clash_for_windows_pkg#1475]
版本 0.13.8

1、设置了system proxy之后，没有将profiles中的port设置为系统的proxy port。
2、另外在开启system proxy的状态之后，在profiles页面再选择另一个yaml，此时查看IP，没有切换代理服务器地址，关闭system proxy重新开启 依然如此，直到退出进程重新打开才能切换。
![微信截图_20210103102616](https://user-images.githubusercontent.com/17058349/103470630-8d4a3b80-4daf-11eb-9be8-8f9c17cb0ce5.png)

**Comment by yi-Xu-0100** [comment]
1. 这里设置的端口，应该为 general YAML 的默认配置中的 mixed-port。
2. 检测 connections 设置。

![image](https://user-images.githubusercontent.com/25523606/103472550-c42d4b00-4dc9-11eb-9f12-2eeb538293de.png)

**Comment by wajika** [comment]
![image](https://user-images.githubusercontent.com/17058349/103492634-2be5a380-4e67-11eb-9d11-76aab163af0f.png)
我检查了general YAML 里面写的也是7890
我开了break when change的功能，测试成功了。

还有一个事，组件日志信息在哪里能看到？就是还没有成功启动proxy状态下

**Comment by yi-Xu-0100** [comment]
1. 检查你的 模式设置的 pac 还是 http ，http 中 bypass 内容填写是啥，关闭打开 system proxy 系统设置这里是否会随之关闭打开，注意刷新页面。
2. log 内容可以自行去 home directory 中 log 中的，或者点击左下角 connected 显示最新的 log

**Comment by wajika** [comment]
ok 谢谢解答
