### ISSUE TITLE
已按照流程设置TUN,但用管理员模式启动cfw后提示 安装程序无法复制"wintun.sys"

### ISSUE THREAD

**Issue by ShadowsSide** [Fndroid/clash_for_windows_pkg#1477]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

Windows10 20H2,  cfw v 0.13.8

[//]: # (请具体并清楚地描述遇到的问题)

在配置文件中输入后,用管理员模式启动cfw后提示 安装程序无法复制"wintun.sys"

[//]: # (清晰地描述期望看到的行为)

**日志**

time="2021-01-03T13:30:55+08:00" level=info msg="[Wintun] RegistryQuery: Querying value failed: 系统找不到指定的文件。 (Code 0x00000002)"
time="2021-01-03T13:30:55+08:00" level=info msg="[Wintun] GetNetCfgInstanceId: Failed to get NetCfgInstanceId"
time="2021-01-03T13:30:55+08:00" level=info msg="[Wintun] RegistryQuery: Querying value failed: 系统找不到指定的文件。 (Code 0x00000002)"
time="2021-01-03T13:30:55+08:00" level=info msg="[Wintun] GetNetCfgInstanceId: Failed to get NetCfgInstanceId"
time="2021-01-03T13:30:55+08:00" level=info msg="[Wintun] CreateAdapter: Creating adapter"

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/61958350/103472423-45aeba00-4d85-11eb-9009-f1734acf8c78.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by shikkoku** [comment]
wintun.dll是否下载错误？是否对应x64?

**Comment by ShadowsSide** [comment]
> wintun.dll是否下载错误？是否对应x64?

我的是intel 8700k. 使用了amd64的wintun.dll. 应该没错吧?

**Comment by ShadowsSide** [comment]
> > wintun.dll是否下载错误？是否对应x64?
> 
> 我的是intel 8700k. 使用了amd64的wintun.dll. 应该没错吧?

我点击浏览是可以看到有这个文件的.但是程序就是一直显示复制错误.....

**Comment by shikkoku** [comment]
<img src="https://user-images.githubusercontent.com/16091562/103336302-b074a280-4ab2-11eb-92b3-13056d5ecf08.png"/>

文件是放在这个文件夹里了吗？如果确认无误的话，会不会是杀毒软件阻止了？

**Comment by ShadowsSide** [comment]
已解决，感谢！确实是杀软的问题，我的火绒开了免打扰模式，所以没有提示给予权限直接给我拒绝了.

**Comment by ShadowsSide** [comment]
我发现如果想要使用TUN模式的话就必须使用管理员模式启动Clash?不然无法连接上

**Comment by yi-Xu-0100** [comment]
@ShadowsSide https://docs.cfw.lbyczf.com/contents/tun.html
