### ISSUE TITLE
开启tap后，命令行无法ping得域名的真实IP地址，其它正常

### ISSUE THREAD

**Issue by zhwalker** [Fndroid/clash_for_windows_pkg#148]
开启tap后，命令行无法ping得域名的真实IP地址，其它正常，这是由什么造成的，有解决办法吗？

**Comment by Fndroid** [comment]
tun2socks无法处理TCP/UDP外的流量，ping是ICMP

如果单纯想要获取到IP地址，可以用 ``nslookup 域名 服务器`` 命令

**Comment by zhwalker** [comment]
如果想看时延呢？

**Comment by Fndroid** [comment]
现在只能临时切换配置开关TAP

**Comment by zhwalker** [comment]
有个开关能控制TAP会更方便呢
还有一个建议是：节点信息和路由如果能够分离配置，我觉得这是更优的设计
