### ISSUE TITLE
节点名字过长测速延迟显示异常

### ISSUE THREAD

**Issue by BaileyZyp** [Fndroid/clash_for_windows_pkg#1482]
- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 专业版 20H2

**描述**

测速延迟显示异常，应该是节点名字太长导致的

![image](https://user-images.githubusercontent.com/16634459/103605563-2cf20000-4f4f-11eb-829a-d2f4ec54497d.png)
![image](https://user-images.githubusercontent.com/16634459/103605617-5317a000-4f4f-11eb-8847-d5bd6c60ba2b.png)
![image](https://user-images.githubusercontent.com/16634459/103605624-59a61780-4f4f-11eb-9dec-fdf357defec4.png)

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/103606003-519aa780-4f50-11eb-9306-25d36c6893d9.png)

**Comment by BaileyZyp** [comment]
@yi-Xu-0100 应该填多少，我这里默认的

**Comment by yi-Xu-0100** [comment]
@BaileyZyp 修改到自己感觉合适即可，不填就是默认值。

**Comment by BaileyZyp** [comment]
@yi-Xu-0100 好的谢谢，还有没有其他的解决方法？

**Comment by yi-Xu-0100** [comment]
@BaileyZyp 众口难调，所以F大才提供设置的吧。

**Comment by BaileyZyp** [comment]
@yi-Xu-0100 要是有缩略节点名或者滚动节点名就好了，让延迟固定显示在右侧。改刚刚那个选项就太长了直接占满一行

**Comment by BaileyZyp** [comment]
直接占满一行可显示的节点就太少了

**Comment by Fndroid** [comment]
因为节点名是非CJK文本并且没有空格，所以不能换行
