### ISSUE TITLE
TAP not coming online

### ISSUE THREAD

**Issue by TJT-JTJ** [Fndroid/clash_for_windows_pkg#1484]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 20H2

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

TAP Driver won't come online. Working fine for several weeks, no failure, yesterday existing profiles (no changes) won't bring the TAP driver online. Tried simple Mixin, still no TAP driver. Deleted CfW, TAP,. config folder, reinstalled, still no TAP connection

**复现**

[//]: # (请描述复现问题的步骤)

Reproduction unclear.
Tried redir-host and fake-ip modes

**预期行为**

[//]: # (清晰地描述期望看到的行为)
TAP network card comes online

**日志**

[//]: # (上传触发问题对应的日志文件)
Nothing related in the log

**截图**
![image](https://user-images.githubusercontent.com/63647882/103835738-056f7480-50c2-11eb-9539-e1dc4a29f0c2.png)
![image](https://user-images.githubusercontent.com/63647882/103835939-921a3280-50c2-11eb-92de-1554c749cb6f.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
```
listen: 0.0.0.0:53
```

**Comment by TJT-JTJ** [comment]
![image](https://user-images.githubusercontent.com/63647882/103838065-1078d380-50c7-11eb-8ba5-f07bfe4a380e.png)

It still doesn't work

**Comment by Fndroid** [comment]
```yaml
mixin:
  dns:
    ......
```

Just follow the [doc](https://docs.cfw.lbyczf.com/)
