### ISSUE TITLE
url test 增加’公差‘参数 

### ISSUE THREAD

**Issue by nemo2018** [Fndroid/clash_for_windows_pkg#1486]
**描述**
url test可否增加一个参数’公差‘，如果公差小于某个值就不必切换了。比如说订阅里面有几个节点，都比较健康，测出来的值相差几十甚至只有几ms，就不必切换了。

**其他说明**
是看到了’小火箭‘有这个功能才过来看CFW有没有。可以参考图片。
![image0](https://user-images.githubusercontent.com/37334053/103847330-f3e69680-50da-11eb-82ab-df23066d4432.jpg)

**Comment by nemo2018** [comment]
tolerance 参数是不是干这个的？测试了一下好像可行。如果是，可以关闭ticket了。谢谢
![image](https://user-images.githubusercontent.com/37334053/103850719-fcdb6600-50e2-11eb-88c5-179f0b6ea20b.png)

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/103855118-e934fd00-50ec-11eb-8e24-e1c36f94d453.png)

**Comment by nemo2018** [comment]
谢谢
