### ISSUE TITLE
希望调小UI，增加可显示内容

### ISSUE THREAD

**Issue by Phowx** [Fndroid/clash_for_windows_pkg#149]
现在的UI锁死不能调，调整策略之类的操作比较麻烦，希望大佬可以缩小点。

**Comment by sakuyamaij** [comment]
机场节点太多，是否可以增加一个搜索栏....

**Comment by faynwol** [comment]
更希望能丰富下托盘的右键菜单

**Comment by openviso** [comment]
白色的UI界面太刺眼,希望可以设置界面的颜色

**Comment by aglent** [comment]
> 
> 
> 白色的UI界面太刺眼,希望可以设置界面的颜色

确实太白了 而且字体变细了 具体节点色块也没有阴影 扁平化了

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
