### ISSUE TITLE
请问ffmpeg.dll在本项目的作用？

### ISSUE THREAD

**Issue by ac1982** [Fndroid/clash_for_windows_pkg#1490]
[//]: # (如不按模版填写，则issue将被直接关闭)

请问ffmpeg.dll在本项目的作用？因为本项目只有发布版本，没有源码，所以询问下，谢谢。

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

Windows 10 20H2
Clash for windows 1.4.0

[//]: # (请具体并清楚地描述遇到的问题)

压缩包里面可见ffmpeg.dll

[//]: # (请描述复现问题的步骤)
N/A
[//]: # (清晰地描述期望看到的行为)
N/A
**日志**

[//]: # (上传触发问题对应的日志文件)

N/A

[//]: # (如果可以，请提供对应问题的截图)

N/A

**Comment by yi-Xu-0100** [comment]
Electron 的锅吧

**Comment by Kr328** [comment]
或者你也可以问

chromium 为什么要包含 ffmpeg.dll

浏览器为什么要包含 ffmpeg.dll

**Comment by ac1982** [comment]
> 或者你也可以问
> 
> chromium 为什么要包含 ffmpeg.dll
> 
> 浏览器为什么要包含 ffmpeg.dll

别人有，不代表这个项目需要有啊。就事论事这个事儿不应该很难吧。

Thanks @yi-Xu-0100 ， 我确实注意到electron有ffmpeg。我之前并不知道本项目是基于electron开发的。
