### ISSUE TITLE
[Wintun] WintunOpenAdapter: Failed to impersonate SYSTEM user

### ISSUE THREAD

**Issue by XiaoTeemo** [Fndroid/clash_for_windows_pkg#1492]
- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
- Windows 10 (business edition), version 20H2 (updated Dec 2020) (x64) - DVD (Chinese-Simplified) 企业版
- 没有安装任何杀毒软件和防火墙，包括系统自带的都已关闭。
- 第三方软件只安装了 WinRAR 和 Chrome 。

**描述**
- 新鲜出炉的 Clash for Windwos v0.14.1  Core Version 2020.12.27 Permium。
- 通过 [AdvancedRun](https://www.nirsoft.net/utils/advanced_run.html) 以 SYSTEM User 系统用户运行 Clash for Windows.exe 可以正常创建 Clash Tunnel 网卡。
- 正常运行或管理员身份运行无法创建 Clash Tunnel 网卡。

**日志**
```
time="2021-01-08T13:16:29+08:00" level=info msg="[Wintun] WintunOpenAdapter: Failed to impersonate SYSTEM user"  
time="2021-01-08T13:16:29+08:00" level=info msg="[Wintun] WintunCreateAdapter: Failed to impersonate SYSTEM user"  
time="2021-01-08T13:16:29+08:00" level=error msg="Start Tun interface error: Error creating interface: Access is denied."  
```

**Comment by yi-Xu-0100** [comment]
cfw 啥版本？

**Comment by XiaoTeemo** [comment]
> cfw 啥版本？

新鲜出炉的 Clash for Windwos v0.14.1  Core Version 2020.12.27 Permium。

**Comment by XiaoTeemo** [comment]
用服务模式已解决。
