### ISSUE TITLE
开启系统代理后，搜狗输入法无法正常同步设置。关闭系统代理恢复正常。

### ISSUE THREAD

**Issue by wkingnet** [Fndroid/clash_for_windows_pkg#1496]
[//]: # (如不按模版填写，则issue将被直接关闭)

开启clash系统代理后，搜狗输入法的同步功能失败。似乎云候选词语也失败。关闭系统代理后，同步功能恢复正常。连接搜狗服务器是直连的，并未经过代理线路。

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

win 10 20h2 x64   clash 0.14.1

[//]: # (请具体并清楚地描述遇到的问题)

开启clash系统代理后，搜狗输入法的同步功能失败。似乎云候选词语也失败。关闭系统代理后，同步功能恢复正常。连接搜狗服务器是直接的，并未经过代理线路。

[//]: # (请描述复现问题的步骤)

关闭系统代理。登录搜狗输入法的帐户。开启clash系统代理，搜狗同步设置。

**预期行为**

[//]: # (清晰地描述期望看到的行为)

time="2021-01-08T21:18:30+08:00" level=info msg="[TCP] 127.0.0.1:60111 --> account.sogou.com match GeoIP(CN) using Domestic[DIRECT]"
time="2021-01-08T21:18:30+08:00" level=info msg="[TCP] 127.0.0.1:60113 --> account.sogou.com match GeoIP(CN) using Domestic[DIRECT]"
time="2021-01-08T21:18:30+08:00" level=info msg="[TCP] 127.0.0.1:60115 --> account.sogou.com match GeoIP(CN) using Domestic[DIRECT]"
time="2021-01-08T21:18:30+08:00" level=info msg="[TCP] 127.0.0.1:60117 --> account.sogou.com match GeoIP(CN) using Domestic[DIRECT]"
time="2021-01-08T21:18:30+08:00" level=info msg="[TCP] 127.0.0.1:60119 --> pc.profile.pinyin.sogou.com match GeoIP(CN) using Domestic[DIRECT]"
time="2021-01-08T21:18:30+08:00" level=info msg="[TCP] 127.0.0.1:60121 --> get.sogou.com match GeoIP(CN) using Domestic[DIRECT]"
time="2021-01-08T21:18:30+08:00" level=info msg="[TCP] 127.0.0.1:60123 --> pc.profile.pinyin.sogou.com match GeoIP(CN) using Domestic[DIRECT]"
time="2021-01-08T21:18:30+08:00" level=info msg="[TCP] 127.0.0.1:60125 --> pc.profile.pinyin.sogou.com match GeoIP(CN) using Domestic[DIRECT]"
time="2021-01-08T21:18:30+08:00" level=info msg="[TCP] 127.0.0.1:60127 --> get.sogou.com match GeoIP(CN) using Domestic[DIRECT]"

[//]: # (上传触发问题对应的日志文件)

[//]: # (如果可以，请提供对应问题的截图)

![QQ截图20210108211340](https://user-images.githubusercontent.com/57652989/104019644-e0305280-51f6-11eb-9449-818eb65ae6f7.png)

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
配置中有 dns 配置吗？

**Comment by wkingnet** [comment]
> 配置中有 dns 配置吗？

config.yaml 


mixed-port: 1080
allow-lan: true
log-level: info
external-controller: 127.0.0.1:59765
secret: ''
ipv6: false

dns:
  enable: true
  ipv6: false
  # listen: 0.0.0.0:53
  # enhanced-mode: redir-host # 或 fake-ip
  # # fake-ip-range: 198.18.0.1/16 # 如果你不知道这个参数的作用，请勿修改
  # fake-ip-filter: # fake-ip 白名单列表
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com
  nameserver:
    - 223.6.6.6
    - 119.29.29.29
    #- https://13800000000.rubyfish.cn/

  fallback: # 与 nameserver 内的服务器列表同时发起请求，当规则符合 GEOIP 在 CN 以外时，fallback 列表内的域名服务器生效。
    - tls://1.1.1.1:853
    #- https://13800000000.rubyfish.cn/
    #- https://cloudflare-dns.com/dns-query
    #- https://dns.google/dns-query

  fallback-filter:
    geoip: true # 默认
    ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
      - 240.0.0.0/4

**Comment by yi-Xu-0100** [comment]
写在配置中，会起作用的，一般，你把 enable 设成 false 试试

**Comment by wkingnet** [comment]
> 写在配置文件中，会起作用的，一般，你把 enable 设成 false 试试
> 
> ！！！是配置文件中的，不是 home directory 中的 config.yaml @wkingnet

DNS改成false了，仍然不行……奇怪呀

**Comment by yi-Xu-0100** [comment]
@wkingnet 你的 log 完整部分是啥，有没有一些不确定的 ip 地址无法连接的。全部都没有 warning 和 error 吗？

**Comment by Fndroid** [comment]
settings里试试pac吧

**Comment by wkingnet** [comment]
```
time="2021-01-09T00:38:36+08:00" level=debug msg="[DNS] account.sogou.com --> 49.7.176.60"
time="2021-01-09T00:38:36+08:00" level=info msg="[TCP] 127.0.0.1:64947 --> account.sogou.com match GeoIP(CN) using Domestic[DIRECT]"
time="2021-01-09T00:38:36+08:00" level=debug msg="[DNS] account.sogou.com --> 49.7.176.60"
time="2021-01-09T00:38:36+08:00" level=info msg="[TCP] 127.0.0.1:64949 --> account.sogou.com match GeoIP(CN) using Domestic[DIRECT]"
time="2021-01-09T00:38:36+08:00" level=debug msg="[DNS] account.sogou.com --> 49.7.176.60"
time="2021-01-09T00:38:36+08:00" level=info msg="[TCP] 127.0.0.1:64951 --> account.sogou.com match GeoIP(CN) using Domestic[DIRECT]"
time="2021-01-09T00:38:36+08:00" level=debug msg="[DNS] account.sogou.com --> 49.7.176.60"
time="2021-01-09T00:38:36+08:00" level=info msg="[TCP] 127.0.0.1:64953 --> account.sogou.com match GeoIP(CN) using Domestic[DIRECT]"
time="2021-01-09T00:38:36+08:00" level=debug msg="[DNS] pc.profile.pinyin.sogou.com --> 49.7.176.60"
time="2021-01-09T00:38:37+08:00" level=info msg="[TCP] 127.0.0.1:64955 --> pc.profile.pinyin.sogou.com match GeoIP(CN) using Domestic[DIRECT]"
time="2021-01-09T00:38:37+08:00" level=debug msg="[DNS] get.sogou.com --> 49.7.21.51"
time="2021-01-09T00:38:37+08:00" level=info msg="[TCP] 127.0.0.1:64957 --> get.sogou.com match GeoIP(CN) using Domestic[DIRECT]"
time="2021-01-09T00:38:37+08:00" level=debug msg="[DNS] pc.profile.pinyin.sogou.com --> 49.7.176.60"
time="2021-01-09T00:38:37+08:00" level=info msg="[TCP] 127.0.0.1:64959 --> pc.profile.pinyin.sogou.com match GeoIP(CN) using Domestic[DIRECT]"
time="2021-01-09T00:38:37+08:00" level=debug msg="[DNS] pc.profile.pinyin.sogou.com --> 49.7.176.60"
time="2021-01-09T00:38:37+08:00" level=info msg="[TCP] 127.0.0.1:64961 --> pc.profile.pinyin.sogou.com match GeoIP(CN) using Domestic[DIRECT]"
time="2021-01-09T00:38:37+08:00" level=debug msg="[DNS] get.sogou.com --> 49.7.21.51"
time="2021-01-09T00:38:37+08:00" level=info msg="[TCP] 127.0.0.1:64963 --> get.sogou.com match GeoIP(CN) using Domestic[DIRECT]"

```
info等级的LOG就是上面的。开启了debug的LOG是这样。没有warning和error

设置为PAC依然如此，
PAC的内容
```
function FindProxyForURL(url, host) {
  return "PROXY 127.0.0.1:%mixed-port%; SOCKS5 127.0.0.1:%mixed-port%; DIRECT;"
}
```

**Comment by yi-Xu-0100** [comment]
这是 pac 的全部完整内容？ 你的 %mixed-port% 是替换了你配置中的 mixed-port 是吧？

**Comment by wkingnet** [comment]
> 这是 pac 的全部完整内容？ 你的 %mixed-port% 是替换了你配置中的 mixed-port 是吧？

是的。PAC没改过，默认的。

mixed-port就是global.yaml里设置的1080端口

mixed使用的JAVASCRIPT，内容如下
```
module.exports.parse = ({ content, name, url }, { yaml, axios, notify }) => {
  content.rules.unshift("DOMAIN-SUFFIX,ditu.live.com,DIRECT");
  content.rules.unshift("DOMAIN-SUFFIX,storage.live.com,DIRECT");
  content.rules.unshift("DOMAIN,by3302.storage.live.com,Others");
  content.rules.unshift("DOMAIN,steam-chat.com,Others");
  content.rules.unshift("DOMAIN-SUFFIX,steampowered.com,Others");
  content.rules.unshift("DOMAIN-SUFFIX,microsoft.com,Others");

  return content
}
```

**Comment by yi-Xu-0100** [comment]
@wkingnet 默认是 7890 的吧，我是说你的那里自己替换过了是吧，换成了 1080 ？

**Comment by wkingnet** [comment]
> @wkingnet 默认是 7890 的吧，我是说你的那里自己替换过了是吧，换成了 1080 ？

是的，改成1080了。我觉得这个和搜狗没关系吧。1080是程序主动想使用代理时去连接的代理端口，搜狗这是走的系统代理，端口改成多少都一样

**Comment by vitaminx** [comment]
设置规则不就是防止“搜狗”这种流氓软件上传数据吗？

**Comment by wkingnet** [comment]
> 设置规则不就是防止“搜狗”这种流氓软件上传数据吗？

问题是……我并没有见到规则在哪？代理的matching rule里没有，global.yaml里也没有。我不介意上传数据，我就想能正常用……

**Comment by wkingnet** [comment]
改成PAC模式以后，搜狗的上传下载配置正常了。个人中心同步不正常。配置正常就满足了。

**Comment by mjyhj** [comment]
![1](https://user-images.githubusercontent.com/22577418/116803694-890b1080-ab4c-11eb-9eab-9a804cd4c74c.png)
