### ISSUE TITLE
如何不使用节点自带的内网DNS，dns leaks的结果中总是有节点内网的DNS

### ISSUE THREAD

**Issue by LittleRey** [Fndroid/clash_for_windows_pkg#1498]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
https://docs.cfw.lbyczf.com/contents/mixin.html

**Comment by LittleRey** [comment]
@yi-Xu-0100 nameservers,  fallback我都添加了，但是dns leaks的结果中依然有所连接节点内网的dns结果

**Comment by yi-Xu-0100** [comment]
所连接节点内网的 dns 结果?啥意思？

**Comment by LittleRey** [comment]
@yi-Xu-0100 就是比方连接搭建在Amazon的vmess节点，Dns检查的结果是下面这张图 
https://i.loli.net/2021/01/10/7XdKSpbyNEtTMH4.png
![browserleaks-dns-2021_01_10_00_11_41.png](https://i.loli.net/2021/01/10/7XdKSpbyNEtTMH4.png)
我不希望出现这个Amazon节点所在网络的DNS

**Comment by yi-Xu-0100** [comment]
@LittleRey https://github.com/Fndroid/clash_for_windows_pkg/discussions/1426#discussioncomment-226251

**Comment by LittleRey** [comment]
@yi-Xu-0100 Clash将所有请求及其域发送到代理服务器，以提高CDN性能，我不想用CDN，我只想要干净的DNS解析结果，就没有一个可行的方法么

**Comment by akw5454521** [comment]
走代理的连接肯定远程DNS啊，难道再连回国内解析吗？服务器可以设置dns，我记得ubuntu是1.1.1.1好像

**Comment by LittleRey** [comment]
@akw5454521 我只希望能够使用公共DNS，不出现远程内网DNS

**Comment by Fndroid** [comment]
先回答你的问题，目前Clash做不到本地解析，除非有人去PR

其次，这个亚马逊服务器如果是你的，你其实可以直接更改服务器的系统DNS，改成喜欢的干净DNS就行

**Comment by akw5454521** [comment]
> @akw5454521 我只希望能够使用公共DNS，不出现远程内网DNS

Linux系统可以改默认DNS，我之前就在一台毛子机上改过，你可以搜下教程
