### ISSUE TITLE
proxy groups编辑保存后无效

### ISSUE THREAD

**Issue by tangkangwei54** [Fndroid/clash_for_windows_pkg#150]
![20190728224620](https://user-images.githubusercontent.com/9771358/62008791-d09b8600-b189-11e9-8672-356b1749a775.png)
删除profiles菜单下proxy groups里面的条目后点保存，再切换到菜单proxies依然显示删除了的条目。

**Comment by tangkangwei54** [comment]
0.5.35没问题，后面的版本有这个问题

**Comment by Fndroid** [comment]
全部策略组删除会导致配置文件错误无法切换，所以内存中依然保留了切换前的状态

**Comment by tangkangwei54** [comment]
没有全部删除，保留了一个，也是这样

**Comment by Fndroid** [comment]
改完之后，切换到其他配置，再切回去看看成不成功，不成功说明改错了

**Comment by tangkangwei54** [comment]
问题是0.5.35没问题，后面的版本有这个问题

**Comment by Fndroid** [comment]
所以我上面说的操作结果怎样

**Comment by tangkangwei54** [comment]
profiles里面的配置切换不了，点切换又自动跳回回来的了

**Comment by tangkangwei54** [comment]
0.5.35可以切换成功，0.6.3不行

**Comment by Fndroid** [comment]
切换不成功说明配置文件有错，错误信息在通知里。0.35使用旧的核心，可能会忽略某些错误

**Comment by tangkangwei54** [comment]
没有弹错误信息出来

**Comment by Fndroid** [comment]
可以更新0.7.0，用弹窗替代了通知

**Comment by tangkangwei54** [comment]
错误提示是有了，根据错误提示修改了机场商家的订阅下载的配置文件，错误提示没有了，但是代理用不了了，说明商家的配置文件不能改。可能是商家提供的文件跟新版本的clash core不兼容吧，我还是先用回0.5.35吧
