### ISSUE TITLE
安装Service Mode长时间无反应，一直未能安装成功

### ISSUE THREAD

**Issue by HXHGTS** [Fndroid/clash_for_windows_pkg#1503]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

Windows10家庭中文版 19042.685

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

安装Service Mode长时间无反应，一直未能安装成功

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入CFW
2. 点击Service Mode
3. 点击Install
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

成功安装Service

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![1](https://user-images.githubusercontent.com/38959826/104110135-87081200-530f-11eb-9027-1d592281ad33.png)

**其他说明**

[//]: # (其他补充内容)
已经尝试分别以普通用户、管理员权限进入CFW测试，均没有效果

**Comment by yi-Xu-0100** [comment]
UAC 不会完全关了吧

**Comment by Fndroid** [comment]
看看Home Directory/service里的那个log文件的内容

**Comment by HXHGTS** [comment]
![image](https://user-images.githubusercontent.com/38959826/104201635-ec214c00-5464-11eb-8543-e9013b94ae07.png)
默认的service没有打开日志功能，那个none改成什么可以打开日志呢？尝试着改成debug但是会自己改回去

**Comment by HXHGTS** [comment]
@yi-Xu-0100 应该不会，我电脑的UAC权限是Windows默认的，没有自己改过，而且CFW我一般是以管理员权限启动的

**Comment by HXHGTS** [comment]
今天我尝试直接手动用service.exe安装了clash-core-service.exe为服务成功了，但是在cfw里面是失败的

**Comment by yi-Xu-0100** [comment]
@HXHGTS service 文件夹中没有 log 文件吗？

**Comment by HXHGTS** [comment]
@yi-Xu-0100 没有，不管后面手动安装成功还是之前自动安装失败都没有日志

**Comment by yi-Xu-0100** [comment]
@HXHGTS 可以截图或者说明下，都有哪些文件在 service 文件夹

**Comment by HXHGTS** [comment]
![image](https://user-images.githubusercontent.com/38959826/104875688-dba33100-5990-11eb-93ed-d560c144e334.png)

我使用cfw内的按钮去安装service时是没有.log这个文件的，而且service的状态一直处于Inactive，但是我自己在cmd里输入service install clash-core-service后重启电脑，cfw中会显示软件service状态是Active，并会产生.log文件

**Comment by Sirlukeleo** [comment]
我也遇到了这个问题，怎么都装不了

**Comment by Fndroid** [comment]
service的绝对路径是不是有空格

**Comment by Sirlukeleo** [comment]
找到原因了，是我的账户名是中文的缘故，我改成英语就好了

**Comment by HXHGTS** [comment]
我也是中文用户名，那应该是了，这个算bug吗？

**Comment by yi-Xu-0100** [comment]
@HXHGTS 一般软件目录的话还是英文的好，可能不是该软件所能修复的，是部分依赖问题的话，就只能自行修改用户名了

**Comment by midrodro** [comment]
重新下载新版本的clash，老版本有这个问题，我装了新版本的一下就安装好了

**Comment by HXHGTS** [comment]
我做了个脚本解决了这个问题https://github.com/HXHGTS/Clash-Config，需要管理员权限

**Comment by midrodro** [comment]
thank you

HXHGTS ***@***.***> 于 2021年12月18日周六 下午6:23写道：

**Comment by ImagineH** [comment]
> 我做了个脚本解决了这个问题https://github.com/HXHGTS/Clash-Config ，需要管理员权限

文件没办法下载啊？

**Comment by CCrushhhh** [comment]
> 我做了个脚本解决了这个问题 https://github.com/HXHGTS/Clash-Config ，需要管理员权限
下载 无法访问网页

**Comment by HXHGTS** [comment]
> > 我做了个脚本解决了这个问题https://github.com/HXHGTS/Clash-Config ，需要管理员权限
> 
> 文件没办法下载啊？
https://raw.iqiq.io/HXHGTS/Clash-Config/main/service_install.bat
原地址可以下，只不过github有dns污染

**Comment by HXHGTS** [comment]
> > 我做了个脚本解决了这个问题 https://github.com/HXHGTS/Clash-Config ，需要管理员权限
> > 下载 无法访问网页

https://raw.iqiq.io/HXHGTS/Clash-Config/main/service_install.bat
原地址可以下，只不过github有dns污染

**Comment by jiuyueshenhua** [comment]
> 重新下载新版本的clash，老版本有这个问题，我装了新版本的一下就安装好了

有用，小地球点亮了！
