### ISSUE TITLE
TUN及TAP启动失败

### ISSUE THREAD

**Issue by Davidlasky** [Fndroid/clash_for_windows_pkg#1505]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ x] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
[//]: # 、
Windows 10 Pro 20H2
Github cfw V0.14.1

**描述** 

[//]: # (请具体并清楚地描述遇到的问题)
正确安装CFW，安装Service Mode成功，Mixin照搬示例，TUN配置正确，使用amd64版本的wintun，不开启mixin正常代理；开启mixin无法联网，log数量激增，显示上传流量极大，过几分钟软件崩溃，再也无法正常打开，以下是具体图片及描述。
**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'dashboard'
2. 点击'mixin'
3. 拖动到'....'
4. 触发问题

**预期行为**
[//]: # 像v0.13.6及以前版本一样正常使用Mixin模式，本问题在我这里从v0.13.8开始出现

**日志**

[//]: # (上传触发问题对应的日志文件)
time="2021-01-10T11:53:29+08:00" level=warning msg="[TUN] macOS auto set route error: failed to set DNS: runNetsh run - exit status 1"
time="2021-01-10T11:53:35+08:00" level=warning msg="[TCP] dial GLOBAL to mtalk.google.com error: c23s3.jamjams.net:63509 connect error: all DNS requests failed, first error: context deadline exceeded"
time="2021-01-10T11:53:35+08:00" level=warning msg="[UDP] dial GLOBAL to 224.0.0.252 error: c23s3.jamjams.net:63509 connect error: all DNS requests failed, first error: context deadline exceeded"
time="2021-01-10T11:53:35+08:00" level=warning msg="[UDP] dial GLOBAL to 224.0.0.252 error: c23s3.jamjams.net:63509 connect error: all DNS requests failed, first error: context deadline exceeded"
time="2021-01-10T11:53:35+08:00" level=warning msg="[UDP] dial GLOBAL to 224.0.0.252 error: c23s3.jamjams.net:63509 connect error: all DNS requests failed, first error: context deadline exceeded"
time="2021-01-10T11:53:35+08:00" level=warning msg="[UDP] dial GLOBAL to 239.255.255.250 error: c23s3.jamjams.net:63509 connect error: all DNS requests failed, first error: context deadline exceeded"
time="2021-01-10T11:53:35+08:00" level=warning msg="[UDP] dial GLOBAL to 224.0.0.252 error: c23s3.jamjams.net:63509 connect error: all DNS requests failed, first error: context deadline exceeded"
time="2021-01-10T11:53:35+08:00" level=warning msg="[UDP] dial GLOBAL to 224.0.0.252 error: c23s3.jamjams.net:63509 connect error: all DNS requests failed, first error: context deadline exceeded"
time="2021-01-10T11:53:35+08:00" level=warning msg="[UDP] dial GLOBAL to 224.0.0.252 error: c23s3.jamjams.net:63509 connect error: all DNS requests failed, first error: context deadline exceeded"
time="2021-01-10T11:53:35+08:00" level=warning msg="[TCP] dial GLOBAL to 183.3.234.100 error: c23s3.jamjams.net:63509 connect error: all DNS requests failed, first error: context deadline exceeded"
time="2021-01-10T11:53:35+08:00" level=warning msg="[UDP] dial GLOBAL to 224.0.0.251 error: c23s3.jamjams.net:63509 connect error: all DNS requests failed, first error: context deadline exceeded"
time="2021-01-10T11:53:35+08:00" level=warning msg="[UDP] dial GLOBAL to 239.255.255.250 error: c23s3.jamjams.net:63509 connect error: all DNS requests failed, first error: context deadline exceeded"

**截图**

[//]: # (如果可以，请提供对应问题的截图)
1. 
![administrator mode](https://user-images.githubusercontent.com/40486797/104114405-04c22280-52fc-11eb-81fc-46e9d5f32c35.png)
已经给管理员权限

2.
![blank dashboard](https://user-images.githubusercontent.com/40486797/104114413-23281e00-52fc-11eb-98b7-403fe3a31643.png)
崩溃后再次进入软件的情景

3.
![in-app failure ](https://user-images.githubusercontent.com/40486797/104114430-49e65480-52fc-11eb-882c-a8f831e64562.png)
软件崩溃，点击repair后进入第2步的死循环

4.
![mixn profile](https://user-images.githubusercontent.com/40486797/104114484-dbee5d00-52fc-11eb-88cb-62736a1f0dec.png)

软件mixin部分配置

**其他说明**

[//]: # (其他补充内容)
节点没有问题，v2ray均可正常使用，cfw不开mixin也可使用
经尝试mixin开关和system proxy开关的4种排列组合均不能成功接管系统流量。
软件崩溃的同时会导致类似网卡驱动也崩溃的情况，关闭软件一段时间后网卡回复正常。
初步判断wintun启动有问题，设置失败。

**Comment by yi-Xu-0100** [comment]
多设置几个 nameserver ，国内的 dns 。然后不要用管理员方式打开

**Comment by Davidlasky** [comment]
> 多设置几个 nameserver ，国内的 dns 。然后不要用管理员方式打开

我是想防止dnsleak才不设置国内dns的，解析慢无所谓，现在设置了谷歌和cloudflare的dns，重装软件，不以管理员模式运行，软件依然崩溃。
还是这个问题。
time="2021-01-10T12:51:53+08:00" level=warning msg="[TUN] macOS auto set route error: failed to set DNS: runNetsh run - exit status 1"
time="2021-01-10T12:51:59+08:00" level=warning msg="[TCP] dial GLOBAL to mtalk.google.com error: c23s3.jamjams.net:63509 connect error: all DNS requests failed, first error: context deadline exceeded"
time="2021-01-10T12:51:59+08:00" level=warning msg="[UDP] dial GLOBAL to 224.0.0.252 error: c23s3.jamjams.net:63509 connect error: all DNS requests failed, first error: context deadline exceeded"
time="2021-01-10T12:51:59+08:00" level=warning msg="[UDP] dial GLOBAL to 8.8.4.4 error: c23s3.jamjams.net:63509 connect error: all DNS requests failed, first error: context deadline exceeded"

**Comment by Fndroid** [comment]
interface自动检测关闭，手动设置interface-name

**Comment by Davidlasky** [comment]
> interface自动检测关闭，手动设置interface-name

成功解决，多谢。

**Comment by Davidlasky** [comment]
问题总结：关闭管理员权限，手动配置interface-name

**Comment by outlier009** [comment]
win10,用wifi开启后上网正常，用网线不行。
