### ISSUE TITLE
关于增加mixin设置多自定义mixin模式选项

### ISSUE THREAD

**Issue by Solitaryender** [Fndroid/clash_for_windows_pkg#1506]
**描述**
目前使用0.14.1版本的cfw
cfw最近添加了tun模式
个人对比后发现tun模式代理性能似乎的确要比tap好
然而cmd个人测试后tun模式下并不能代理
而tap模式本人使用0.13.7版本可以代理cmd
因此提议在mixin设置栏下添加多选项（比如模式一 模式二 供使用）
这样换个模式即可切换tap/tun/普通
能否在下个版本中增加类似选项

**其他说明**
大概无

**Comment by yi-Xu-0100** [comment]
据我所知，tun 应该是能代理 cmd 的

**Comment by Solitaryender** [comment]
> 据我所知，tun 应该是能代理 cmd 的

emmmm我的确是没能代理
![image](https://user-images.githubusercontent.com/65836154/104115110-aff7c980-5346-11eb-9121-254620d04e2a.png)

**Comment by Solitaryender** [comment]
> 据我所知，tun 应该是能代理 cmd 的
但是tap则是可以

![image](https://user-images.githubusercontent.com/65836154/104115178-42986880-5347-11eb-834c-eef7aec1d959.png)

**Comment by Fndroid** [comment]
不在我仓库下就别发issue了谢谢

**Comment by shikkoku** [comment]
cfw官方仓库从未发行过中文版。
