### ISSUE TITLE
是否考虑增加类似macOS下的surge或clashx的增强模式？

### ISSUE THREAD

**Issue by yycomyy** [Fndroid/clash_for_windows_pkg#1507]
rt,上面代理软件的增强模式非常简便好用，只需要手动把局域网设备的网关设置为CFW设备的IP即可代理成功，不用软路由，不用虚拟机，不用繁琐的安装和设置，对于小白来说简直是福音。
目前CFW让局域网设备走代理只能通过局域网设备的浏览器设置http代理，但是这样的话局域网设备的其他软件是不走代理的。
如果能实现增强模式（网关模式）就好了，因此提出建议。

**Comment by SplitGemini** [comment]
难道不是一样的吗

**Comment by Fndroid** [comment]
1. 配置[TUN模式](https://docs.cfw.lbyczf.com/contents/tun.html)
2. 打开系统转发``sudo sysctl -w net.inet.ip.forwarding=1``
