### ISSUE TITLE
规则互斥的话如何编写设置优先级（例如同时存在DOMAIN-SUFFIX,domain.com,DIRECT和DOMAIN-SUFFIX,domain.com,PROXY）

### ISSUE THREAD

**Issue by Arckzzzzz** [Fndroid/clash_for_windows_pkg#1508]
例如我的规则集中包含一条 `microsoft.com` 的规则是走代理，但是实际情况中上直连也可以。

这时如果我想在yaml配置文件中自己手写加一条 `DOMAIN-SUFFIX,microsoft.com,DIRECT` ，那么访问microsoft.com时到底使用规则集的策略走代理呢？还是按我手写的规则直连呢？

有没有什么语法可以强制以我手写的规则优先程度最高呢？😀

_PS：最近看log发现很多规则不符合我的实际情况，规则集又是自动更新的，改本地的会被覆盖；把 `Rule Providers` 的 `type` 从 `http` 改成 `file` 又会导致规则集没法更新，所以我想根据自己的情况手写几条规则，然后将它们设置为最高优先级（优先于规则集）。_

**Comment by yi-Xu-0100** [comment]
@Arckzzzzz 规则从上到下顺序匹配。

然后规则修改建议使用 parser ：<https://docs.cfw.lbyczf.com/contents/parser.html>

**Comment by Arckzzzzz** [comment]
> @Arckzzzzz 规则从上到下顺序匹配。
> 
> 然后规则修改建议使用 parser ：https://docs.cfw.lbyczf.com/contents/parser.html

十分感谢！晚上回家试试！
