### ISSUE TITLE
网关模式下，同一源使用本机可以访问，使用局域网内手机无法访问

### ISSUE THREAD

**Issue by Arckzzzzz** [Fndroid/clash_for_windows_pkg#1509]
目前只发现了微博客户端的视频多数情况下无法观看，会显示`网络出错，请重试`，在电脑网页端查看同一视频没有此问题。

通过查看log我发现，电脑端解析的地址是`weiboapi.com`，而手机端访问出错时解析出来的都是ip地址，匹配的是geoip(CN)，理应是直连可以访问的，但是实际不行。

在手机端偶尔可以访问时，再观察log会发现这时解析的是`weiboapi.com`。

目前发现的规律就是解析出来的是ip就会出错。解析出`weiboapi.com`就没问题。

PS：此文题目前只发现影响到微博手机客户端的视频，其他网页解析出的ip都可以正常访问。规则集用的是[Loyalsoldier/clash-rules](https://github.com/Loyalsoldier/clash-rules)，如果还需要其他配置部分，我可以再贴出来，提前感谢！

**Comment by yi-Xu-0100** [comment]
weiboapi.com 走的代理规则？

**Comment by Arckzzzzz** [comment]
> weiboapi.com 走的代理规则？

也是直连

**Comment by yi-Xu-0100** [comment]
个人猜测，可以多加几个 dns 试试

**Comment by Arckzzzzz** [comment]
> 个人猜测，可以多加几个 dns 试试

之前搜过一些，说是DNS污染吗我的配置文件DNS的部分是直接注释掉的，尝试过加上去也没啥用，主要改哪些部分可以给点建议吗？

**Comment by yi-Xu-0100** [comment]
没有啥推荐，把国内的一些公共的知名的 dns 放前面，我不知道局域网是否有影响，手机我是直接用 CFA。

**Comment by Fndroid** [comment]
不知道你是怎么配置网关模式（Allow LAN还是TUN），但变成IP就说明手机端DNS服务器没有配置对，Clash不能反推出来域名

**Comment by Arckzzzzz** [comment]
> 不知道你是怎么配置网关模式（Allow LAN还是TUN），但变成IP就说明手机端DNS服务器没有配置对，Clash不能反推出来域名

昨晚整理rules发现在`GEOIP,CN,DIRECT`前还有一条`GEOIP,,DIRECT`，把`GEOIP,,DIRECT`删了之前到目前为止似乎没有再出现过问题了

**Comment by Arckzzzzz** [comment]
> 不知道你是怎么配置网关模式（Allow LAN还是TUN），但变成IP就说明手机端DNS服务器没有配置对，Clash不能反推出来域名

额外问一句，简单来说Allow LAN和TUN主要区别和优缺点是什么呢？
