### ISSUE TITLE
Facebook网页进不去，其他网页正常

### ISSUE THREAD

**Issue by x1497215968** [Fndroid/clash_for_windows_pkg#1511]

**Comment by yi-Xu-0100** [comment]
log 相关内容给一下，确认下网页端，network 中请求走了 cfw

**Comment by x1497215968** [comment]
大神 你说的这个log在哪里找到给你
可不可以麻烦你截下图说明一下位置 不太懂 或者方便加个联系方式 跟您请教

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/104427837-b09a9500-55be-11eb-91b0-1229e60041bb.png)

点击这里，或者去Home directory 下找 log 文件夹里面看看最新文件

**Comment by x1497215968** [comment]
找到这个文件了  后续怎么操作

**Comment by x1497215968** [comment]
time="2021-01-13T09:24:57+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2021-01-13T09:24:57+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2021-01-13T09:24:57+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2021-01-13T09:24:57+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2021-01-13T09:24:58+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2021-01-13T09:24:58+08:00" level=info msg="Redir proxy listening at: :7892"

**Comment by yi-Xu-0100** [comment]
@x1497215968 打开 facebook，然后把 facebook 相关的日志贴一下

**Comment by Arckzzzzz** [comment]
cfw有logs这一栏，你可以先全部clear掉，然后访问Facebook，再检查log，就像下面这样
![image](https://user-images.githubusercontent.com/32861605/104444593-f19ca480-55d2-11eb-92a3-6e80d4325315.png)

**Comment by akw5454521** [comment]
Instagram也正常？

**Comment by x1497215968** [comment]
目前就只发现taobao和facebook进不去  其他都进得去 ins  tw 都能正常访问 
（clear掉 重新进入都是进不了）

**Comment by yi-Xu-0100** [comment]
@x1497215968 啥叫进不来，没有相关的记录吗？走的什么规则？

**Comment by x1497215968** [comment]
![微信截图_20210113223256](https://user-images.githubusercontent.com/77369748/104465724-50701700-55ef-11eb-8590-bb7e34879a16.png)
是不是因为公益节点是普通的节点不给进

**Comment by yi-Xu-0100** [comment]
@x1497215968 你换节点试试呢，走了代理，用同一个节点能访问其他的吗？

**Comment by Fndroid** [comment]
开Global，能进就是规则问题，不能就是节点问题

**Comment by x1497215968** [comment]
规则这个不知道哪里设置，不熟悉
节点的话我全部都试过，可能就是公益节点的问题（朋友的vip节点就可进），所以我想请教各位
如果是因为公益节点的问题导致不能进facebook，那是怎么设置规则或者在怎么设置其他能够进去facebook
各位大神有办法不？

**Comment by akw5454521** [comment]
> 规则这个不知道哪里设置，不熟悉
> 节点的话我全部都试过，可能就是公益节点的问题（朋友的vip节点就可进），所以我想请教各位
> 如果是因为公益节点的问题导致不能进facebook，那是怎么设置规则或者在怎么设置其他能够进去facebook
> 各位大神有办法不？

我觉得就是想叫你花钱买的意思。放出几个免费节点，使用有限制……

**Comment by x1497215968** [comment]
> > 规则这个不知道哪里设置，不熟悉节点的话我全部都试过，可能就是公益节点的问题(朋友的贵宾节点就可进)，所以我想请教各位如果是因为公益节点的问题导致不能进脸书，那是怎么设置规则或者在怎么设置其他能够进去facebook各位大神有办法不？
> 
> 我觉得就是想叫你花钱买的意思.放出几个免费节点，使用有限制……

挺多的免费节点 大部分时间还是比较稳定 网站基本都能进 就是Facebook进不去就很蛋疼 就看看求助大家有没有办法进去
