### ISSUE TITLE
有关 Random Controller Port问题

### ISSUE THREAD

**Issue by Giter-t** [Fndroid/clash_for_windows_pkg#1519]
**描述**
这个开关有什么作用？
使用动态端口链接clash核心程序对速度会有什么影响吗？

**其他说明**
其他补充内容

**Comment by yi-Xu-0100** [comment]
@Giter-t 主要是之前的端口占用问题，所以随机后，不再占用端口，可在设置中关闭这项。

而且是每次启动 cfw，随机一个，并不会在单次使用中更换端口，除非修改配置。

**Comment by Giter-t** [comment]
也就是说如果没有端口占用的问题这个就不用打开是吧？

**Comment by yi-Xu-0100** [comment]
@Giter-t 是的，可以选择不打开，但是端口占用问题可能是潜在的无解的 Windows 问题，所以最好确实没有此方面的问题，且了解如何排查相关问题，而且有使用固定的端口的需求的话才关闭。

**Comment by Giter-t** [comment]
好的，明白了，谢谢您

**Comment by jackwan990** [comment]
> 请问 这个Random Controller Port 是否可以通过配置文件进行关闭呢？
非常感谢



>

**Comment by Fndroid** [comment]
@jackwan990 不能在配置文件里指定
