### ISSUE TITLE
感觉我的0.7 rules模式失效了

### ISSUE THREAD

**Issue by GHOSTagw** [Fndroid/clash_for_windows_pkg#152]
已开rule模式，但是logs显示各种国内网站（百度，知乎...）都是使用代理，而不是直连。
一直在用默认规则 GEOIP, CN, DIRECT MATCH, Proxy
重装过clash，浏览器chrome和firefox都设置了使用系统代理。

**Comment by Fndroid** [comment]
我们这边发现了一个geoip的bug，可以把home directory里面的Country.mmdb删掉重启软件，暂时不要在general更新geoip

**Comment by GHOSTagw** [comment]
> 
> 
> 我们这边发现了一个geoip的bug，可以把home directory里面的Country.mmdb删掉重启软件，暂时不要在general更新geoip

解决了，灰常感谢
