### ISSUE TITLE
希望增加TCP模式下的一个功能

### ISSUE THREAD

**Issue by anypasss** [Fndroid/clash_for_windows_pkg#1521]
![微信图片_20210116155654](https://user-images.githubusercontent.com/37586791/104806573-8db4ee80-5813-11eb-90a3-03252be843aa.png)
![微信图片_20210116155710](https://user-images.githubusercontent.com/37586791/104806575-94dbfc80-5813-11eb-8f82-ae83b50f8086.png)

能否跟ws 一样，有headers这个功能？急需

**Comment by Fndroid** [comment]
我不是太明白，你软件在别处下载，为什么要在我这发issue

**Comment by anypasss** [comment]
在你这里下载的啊，我只是汉化了下。



---原始邮件---
发件人: "Fndroid"<notifications@github.com&gt;
发送时间: 2021年1月16日(周六) 下午4:14
收件人: "Fndroid/clash_for_windows_pkg"<clash_for_windows_pkg@noreply.github.com&gt;;
抄送: "anypasss"<7315547@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Fndroid/clash_for_windows_pkg] 希望增加TCP模式下的一个功能 (#1521)




 
我不是太明白，你软件在别处下载，为什么要在我这发issue
