### ISSUE TITLE
windows 10 每次熄屏或睡眠之后解锁，都需要退出 Clash for windows 再打开才能正常代理

### ISSUE THREAD

**Issue by rhzone** [Fndroid/clash_for_windows_pkg#1522]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

Microsoft Windows [Version 10.0.18363.1316]

**描述**

windows 10 每次睡眠之后解锁，都需要退出 Clash for windows 再打开才能正常代理

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 电脑熄屏或进入睡眠模式
2. 解锁
3. 访问 Google

**预期行为**

[//]: # (清晰地描述期望看到的行为)
可以正常访问 Google

**日志**

![image](https://user-images.githubusercontent.com/30968676/104806879-97d7ec80-5815-11eb-9469-60203bc19151.png)

**截图**

无

**其他说明**

系统代理还是处于开的状态

**Comment by yi-Xu-0100** [comment]
是否是系统时间需要重新校准的问题？
一直无法代理吗？
只有google吗？
切换节点后是否正常呢？

**Comment by rhzone** [comment]
> 是否是系统时间需要重新校准的问题？
> 一直无法代理吗？
> 只有google吗？
> 切换节点后是否正常呢？

1.睡眠之后每次开始几分钟内无法代理，我都是退出重启的，没试过等很久的

2.被禁的外网都不行，

3.目前只有一个节点

**Comment by rhzone** [comment]
@Fndroid 可以一些排查调试的方法吗

**Comment by Fndroid** [comment]
在home directory/logs里传一份休眠断开之后的日志吧

**Comment by rhzone** [comment]
> 在home directory/logs里传一份休眠断开之后的日志吧，你截图这几个都看不出来有没有匹配规则

time="2021-01-21T02:09:48+08:00" level=info msg="RESTful API listening at: 127.0.0.1:54810"
time="2021-01-21T02:09:48+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:1080"
time="2021-01-21T02:09:49+08:00" level=info msg="Start initial compatible provider 故障转移"
time="2021-01-21T02:09:49+08:00" level=info msg="Start initial compatible provider 自动选择"
time="2021-01-21T02:09:49+08:00" level=info msg="Start initial compatible provider 服务商名xxx"
time="2021-01-21T02:09:49+08:00" level=info msg="Start initial compatible provider 故障转移"
time="2021-01-21T02:09:49+08:00" level=info msg="Start initial compatible provider 自动选择"
time="2021-01-21T02:09:49+08:00" level=info msg="Start initial compatible provider 服务商名xxx"
time="2021-01-21T02:09:49+08:00" level=info msg="[TCP] 127.0.0.1:54882 --> avatars1.githubusercontent.com match DomainKeyword(github) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:09:49+08:00" level=info msg="[TCP] 127.0.0.1:54880 --> avatars2.githubusercontent.com match DomainKeyword(github) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:09:49+08:00" level=info msg="[TCP] 127.0.0.1:54885 --> avatars3.githubusercontent.com match DomainKeyword(github) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:09:50+08:00" level=info msg="[TCP] 127.0.0.1:54889 --> avatars0.githubusercontent.com match DomainKeyword(github) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:09:50+08:00" level=info msg="[TCP] 127.0.0.1:54895 --> avatars0.githubusercontent.com match DomainKeyword(github) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:09:50+08:00" level=info msg="[TCP] 127.0.0.1:54893 --> avatars0.githubusercontent.com match DomainKeyword(github) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:09:50+08:00" level=info msg="[TCP] 127.0.0.1:54894 --> avatars0.githubusercontent.com match DomainKeyword(github) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:09:50+08:00" level=info msg="[TCP] 127.0.0.1:54896 --> avatars0.githubusercontent.com match DomainKeyword(github) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:09:51+08:00" level=info msg="[TCP] 127.0.0.1:54901 --> collector.githubapp.com match DomainKeyword(github) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:09:51+08:00" level=info msg="[TCP] 127.0.0.1:54905 --> api.github.com match DomainKeyword(github) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:09:51+08:00" level=info msg="[TCP] 127.0.0.1:54903 --> github.githubassets.com match DomainKeyword(github) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:09:54+08:00" level=warning msg="[TCP] dial 服务商名xxx (match DomainKeyword/github) to api.github.com error: 183.60.41.64:12001 connect error: dial tcp4 183.60.41.64:12001: i/o timeout"
time="2021-01-21T02:09:54+08:00" level=warning msg="[TCP] dial 服务商名xxx (match DomainKeyword/github) to raw.githubusercontent.com error: 183.60.41.64:12001 connect error: dial tcp4 183.60.41.64:12001: i/o timeout"
time="2021-01-21T02:09:54+08:00" level=info msg="[TCP] 127.0.0.1:54910 --> api.github.com match DomainKeyword(github) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:09:54+08:00" level=info msg="[TCP] 127.0.0.1:54911 --> raw.githubusercontent.com match DomainKeyword(github) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:09:56+08:00" level=info msg="[TCP] 127.0.0.1:54916 --> mail.google.com match DomainKeyword(google) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:09:57+08:00" level=info msg="[TCP] 127.0.0.1:54919 --> mtalk.google.com match DomainKeyword(google) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:09:59+08:00" level=info msg="[TCP] 127.0.0.1:54922 --> android.clients.google.com match DomainKeyword(google) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:10:05+08:00" level=info msg="[TCP] 127.0.0.1:54927 --> accounts.google.com match DomainKeyword(google) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:10:05+08:00" level=info msg="[TCP] 127.0.0.1:54929 --> qbwup.imtt.qq.com match DomainSuffix(qq.com) using DIRECT"
time="2021-01-21T02:10:10+08:00" level=info msg="[TCP] 127.0.0.1:54937 --> github.com match DomainKeyword(github) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:10:12+08:00" level=info msg="[TCP] 127.0.0.1:54944 --> alive.github.com match DomainKeyword(github) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:10:12+08:00" level=debug msg="[DNS] userstylesapi.com --> 35.172.75.81"
time="2021-01-21T02:10:12+08:00" level=info msg="[TCP] 127.0.0.1:54941 --> userstylesapi.com match Match() using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:10:12+08:00" level=info msg="[TCP] 127.0.0.1:54947 --> clients4.google.com match DomainKeyword(google) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:10:13+08:00" level=info msg="[TCP] 127.0.0.1:54949 --> update.googleapis.com match DomainKeyword(google) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:10:13+08:00" level=info msg="[TCP] 127.0.0.1:54952 --> api.github.com match DomainKeyword(github) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:10:13+08:00" level=info msg="[TCP] 127.0.0.1:54954 --> api.github.com match DomainKeyword(github) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:10:15+08:00" level=info msg="[TCP] 127.0.0.1:54957 --> content-autofill.googleapis.com match DomainKeyword(google) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:10:16+08:00" level=info msg="[TCP] 127.0.0.1:54961 --> alive.github.com match DomainKeyword(github) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:10:16+08:00" level=info msg="[TCP] 127.0.0.1:54959 --> api.github.com match DomainKeyword(github) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:10:16+08:00" level=debug msg="[DNS] beacons.gcp.gvt2.com --> 120.232.181.162"
time="2021-01-21T02:10:16+08:00" level=info msg="[TCP] 127.0.0.1:54963 --> beacons.gcp.gvt2.com match GeoIP(CN) using DIRECT"
time="2021-01-21T02:10:31+08:00" level=info msg="[TCP] 127.0.0.1:54978 --> accounts.google.com match DomainKeyword(google) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:10:31+08:00" level=info msg="[TCP] 127.0.0.1:54979 --> mail.google.com match DomainKeyword(google) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:10:32+08:00" level=info msg="[TCP] 127.0.0.1:54983 --> www.google.com match DomainKeyword(google) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:10:33+08:00" level=debug msg="[DNS] az764295.vo.msecnd.net --> 117.18.232.200"
time="2021-01-21T02:10:33+08:00" level=info msg="[TCP] 127.0.0.1:54985 --> az764295.vo.msecnd.net match Match() using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:10:43+08:00" level=info msg="[TCP] 127.0.0.1:54996 --> clients1.google.com match DomainKeyword(google) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:10:47+08:00" level=info msg="[TCP] 127.0.0.1:55000 --> mtalk.google.com match DomainKeyword(google) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:11:01+08:00" level=info msg="[TCP] 127.0.0.1:55011 --> google.com match DomainKeyword(google) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:11:04+08:00" level=info msg="[TCP] 127.0.0.1:55015 --> mtalk.google.com match DomainKeyword(google) using 服务商名xxx[🇹🇼 台湾 AIA 中继 01]"
time="2021-01-21T02:11:11+08:00" level=warning msg="[TCP] dial 服务商名xxx (match DomainKeyword/google) to www.googleapis.com error: 162.14.19.20:8001 connect error: dial tcp4 162.14.19.20:8001: connectex: A socket operation was attempted to an unreachable host."
time="2021-01-21T02:11:11+08:00" level=warning msg="[TCP] dial 服务商名xxx (match DomainKeyword/google) to www.googleapis.com error: 162.14.19.20:8001 connect error: dial tcp4 162.14.19.20:8001: connectex: A socket operation was attempted to an unreachable host."
time="2021-01-21T02:11:11+08:00" level=warning msg="[TCP] dial 服务商名xxx (match DomainKeyword/github) to alive.github.com error: 162.14.19.20:8001 connect error: dial tcp4 162.14.19.20:8001: connectex: A socket operation was attempted to an unreachable host."
time="2021-01-21T02:11:11+08:00" level=warning msg="[TCP] dial 服务商名xxx (match DomainKeyword/google) to www.googleapis.com error: 162.14.19.20:8001 connect error: dial tcp4 162.14.19.20:8001: connectex: A socket operation was attempted to an unreachable host."
time="2021-01-21T02:11:11+08:00" level=warning msg="[TCP] dial 服务商名xxx (match DomainKeyword/github) to alive.github.com error: 162.14.19.20:8001 connect error: dial tcp4 162.14.19.20:8001: connectex: A socket operation was attempted to an unreachable host."
time="2021-01-21T02:11:11+08:00" level=info msg="Start initial compatible provider 故障转移"
time="2021-01-21T02:11:11+08:00" level=info msg="Start initial compatible provider 自动选择"
time="2021-01-21T02:11:11+08:00" level=info msg="Start initial compatible provider 服务商名xxx"
time="2021-01-21T02:11:13+08:00" level=warning msg="[TCP] dial 服务商名xxx (match DomainKeyword/google) to mtalk.google.com error: 183.60.41.64:12001 connect error: dial tcp4 183.60.41.64:12001: connectex: A socket operation was attempted to an unreachable host."
time="2021-01-21T02:11:13+08:00" level=warning msg="[TCP] dial 服务商名xxx (match DomainKeyword/google) to mtalk.google.com error: 183.60.41.64:12001 connect error: dial tcp4 183.60.41.64:12001: connectex: A socket operation was attempted to an unreachable host."
time="2021-01-21T02:11:18+08:00" level=debug msg="[DNS] beacons.gcp.gvt2.com --> 120.253.253.226"
time="2021-01-21T02:11:19+08:00" level=info msg="[TCP] 127.0.0.1:55100 --> beacons.gcp.gvt2.com match GeoIP(CN) using DIRECT"
time="2021-01-21T02:11:19+08:00" level=warning msg="[TCP] dial 服务商名xxx (match DomainKeyword/github) to alive.github.com error: 183.60.41.64:12001 connect error: dial tcp4 183.60.41.64:12001: i/o timeout"

大概是02:11:11之后吧

**Comment by Fndroid** [comment]
有试过在休眠之后在Proxies里点击任意策略组右上角第二个图标，打开的Providers界面点击“服务商xxx”右边的health check按钮，完成之后等十来秒看看能不能连上

**Comment by rhzone** [comment]
> 有试过在休眠之后在Proxies里点击任意策略组右上角第二个图标，打开的Providers界面点击“服务商xxx”右边的health check按钮，完成之后等十来秒看看能不能连上

![image](https://user-images.githubusercontent.com/30968676/105257502-e1805880-5bc2-11eb-8066-738262eab899.png)

点了这个按钮之后确实可以连上，一进来这个页面显示的是全部都 timeout 的

**Comment by rhzone** [comment]
将几个 timeout 的节点删除之后解决了

**Comment by ngn999** [comment]
这个问题在最新版本0.15.5里还在,  从休眠中恢复后, 所有节点都是timeout,要check一次后才能好.

**Comment by falloutxxx2** [comment]
现在这个问题还有！！！！要么重启一次程序！！！ win11+TUN 模式

**Comment by aiboboxx** [comment]
现在这个问题还有！！！！
我依然是这样，从休眠中恢复后, 所有节点都是timeout。

**Comment by chouxiang99** [comment]
我也是这样   tun模式    然后从睡眠模式恢复之后  所有节点都是timeout  希望能解决

**Comment by hope140** [comment]
+1 tun模式，休眠回来没网

**Comment by zhang988925** [comment]
+1 tun模式，休眠回来没网

**Comment by dosicker** [comment]
+1 难受o(╥﹏╥)o~

**Comment by zhongfq** [comment]
> 这个问题还存在，起初我以为是CFW的问题，切换成clash-verge后依然存在这个问题。

我也换了，发现还是有问题，估计是clash的BUG，clash-verge有一个重启clash内核，点一下就好了，这个BUG存在很久了，不知道是啥原因

**Comment by MafiaLee** [comment]
同 需要restart

**Comment by bianwenbo** [comment]
同样问题。但是只有笔记本出现这个问题，台式机即便是从睡眠唤醒也正常联网。
备注：台式机和笔记本中Clash使用配置完全一致。
