### ISSUE TITLE
TUN模式下

### ISSUE THREAD

**Issue by Scarecrow-ai** [Fndroid/clash_for_windows_pkg#1526]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows10 专业版 20H2

**描述**

在tun模式下使用steam,偶现steam账户无法连接，商店页面正常

**复现**

1.在clash中启动tun模式
2.启动steam

**预期行为**

steam账户正常登录

**Comment by Scarecrow-ai** [comment]
目前已解决，是我本地配置问题

**Comment by BaileyZyp** [comment]
请问是如何解决的，我也有这个问题，打开TUN不能登录Steam

**Comment by yi-Xu-0100** [comment]
@BaileyZyp 建议同时开启系统代理，而且 steam 有玄学问题，多次试试没准就行了

**Comment by lemako** [comment]
> @BaileyZyp 建议同时开启系统代理，而且 steam 有玄学问题，多次试试没准就行了

神了……我开tun模式 本地配置改了半天什么用都没有 打开系统代理好了

**Comment by K1R1T0l2** [comment]
我也是开tun模式进不了steam,开系统代理也没用，但关掉tun模式就没事了

**Comment by vohv** [comment]
我也百分百复现了，开 tun stream 无法登录，关 tun 开系统代理就可以了

**Comment by lenhoo** [comment]
试试在steam快捷方式属性-目标处加上"-tcp"

**Comment by paddingtonhu** [comment]
> 试试在steam快捷方式属性-目标处加上"-tcp"

宁简直天使。我开启TUN模式+系统代理，Steam依然无法登录，宁这个办法管用。

**Comment by keepeye** [comment]
> 试试在steam快捷方式属性-目标处加上"-tcp"

谢谢兄弟 这个办法管用

**Comment by chiqingsong** [comment]
而且我开启后uu加速节点可用极少，能加速的也丢包
