### ISSUE TITLE
打开软件后 连接报443error 

### ISSUE THREAD

**Issue by linkjoker520** [Fndroid/clash_for_windows_pkg#1529]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[x]: # (如果符合，请将``[ ]``改为``[x]``)

- [✔] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [✔] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [✔] 已经尝试更新到最新版本，问题依旧存在
- [✔] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
win10，版本号1909

**描述**
突然就不行了，然后ssr那边的日志显示的443错误，重下了一个新的Clash用也不行，之前在校园网里也可以用。
clash日志 raw.githubusercontent.com.443

**复现**

[//]: # (请描述复现问题的步骤)
![image](https://user-images.githubusercontent.com/48130822/105018721-3c884300-5a3d-11eb-9c54-9de864e07bd2.png)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

time="2021-01-19T18:08:26+08:00" level=info msg="Start initial compatible provider Proxy"
time="2021-01-19T18:08:26+08:00" level=info msg="RESTful API listening at: 127.0.0.1:54621"
time="2021-01-19T18:08:26+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2021-01-19T18:08:26+08:00" level=info msg="Start initial compatible provider 自动选择"
time="2021-01-19T18:08:26+08:00" level=info msg="Start initial compatible provider 手动选择"
time="2021-01-19T18:08:26+08:00" level=info msg="Start initial compatible provider 节点选择"
time="2021-01-19T18:08:26+08:00" level=info msg="Start initial compatible provider NETFLIX"
time="2021-01-19T18:08:26+08:00" level=info msg="Start initial compatible provider 故障切换"
time="2021-01-19T18:08:26+08:00" level=info msg="Start initial compatible provider 电报吹水"
time="2021-01-19T18:08:26+08:00" level=info msg="Start initial compatible provider 最新域名"
time="2021-01-19T18:08:26+08:00" level=info msg="Start initial compatible provider 国外网站"
time="2021-01-19T18:08:26+08:00" level=info msg="Start initial compatible provider 国外媒体"
time="2021-01-19T18:08:27+08:00" level=info msg="Start initial compatible provider 故障切换"
time="2021-01-19T18:08:27+08:00" level=info msg="Start initial compatible provider 自动选择"
time="2021-01-19T18:08:27+08:00" level=info msg="Start initial compatible provider 手动选择"
time="2021-01-19T18:08:27+08:00" level=info msg="Start initial compatible provider 节点选择"
time="2021-01-19T18:08:27+08:00" level=info msg="Start initial compatible provider 最新域名"
time="2021-01-19T18:08:27+08:00" level=info msg="Start initial compatible provider 国外网站"
time="2021-01-19T18:08:27+08:00" level=info msg="Start initial compatible provider 电报吹水"
time="2021-01-19T18:08:27+08:00" level=info msg="Start initial compatible provider NETFLIX"
time="2021-01-19T18:08:27+08:00" level=info msg="Start initial compatible provider 国外媒体"
time="2021-01-19T18:08:28+08:00" level=info msg="[TCP] 127.0.0.1:59239 --> raw.githubusercontent.com using GLOBAL"
time="2021-01-19T18:08:32+08:00" level=warning msg="dial GLOBAL error: n28.boom.party:13000 connect error: dial tcp4 139.226.21.22:13000: i/o timeout"
time="2021-01-19T18:08:32+08:00" level=info msg="[TCP] 127.0.0.1:59646 --> api.github.com using GLOBAL"

**截图**
![微信图片_20210119180934](https://user-images.githubusercontent.com/48130822/105019835-773eab00-5a3e-11eb-85bb-9a1ad4d6c1f4.png)

 

**其他说明**

端口未被占用
![微信图片_20210119181016](https://user-images.githubusercontent.com/48130822/105019900-8de50200-5a3e-11eb-9dd4-165f3d952a3d.png)
![微信图片_20210119181020](https://user-images.githubusercontent.com/48130822/105019917-90dff280-5a3e-11eb-840d-2299692d1517.png)

**Comment by Fndroid** [comment]
非GitHub版请勿发issue，谢谢

**Comment by linkjoker520** [comment]
那我想请问日志报错443是什么，我连谷歌都上不了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fndroid/clash_for_windows_pkg"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月19日(星期二) 晚上6:16
收件人： &nbsp;“ Fndroid / clash_for_windows_pkg” <clash_for_windows_pkg@noreply.github.com&gt;;
抄送： &nbsp;“ noob” <986198991@qq.com&gt;;“作者” <author@noreply.github.com&gt;;
主题:&nbsp;Re: [Fndroid/clash_for_windows_pkg] 打开软件后 连接报443error  (#1529)





 
关闭＃1529。
 
—
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。
