### ISSUE TITLE
Is it even possible to access the Source Codes?

### ISSUE THREAD

**Issue by cyanlink** [Fndroid/clash_for_windows_pkg#153]
Due to "Regulations", it's understandable that the only maintainer and developer of this wonderful project took down all source code from this repo, thus the main branch is empty, those archives in release are the same, too. Is it even possible to require a copy of the current source codes? if not, then does this violate the licenses (of its dependencies)?

**Comment by Fndroid** [comment]
Clash for Windows is not open source right now. So there is no source code we can provide. 

We are sorry for that.

Are there any dependencies you consider we used are violate their licenses?

**Comment by cyanlink** [comment]
@Fndroid You just took everything down around June out of blue. I thought it was to avoid attention like shadowsocks ( but they hide all codes into another branch ) and they will come back someday soon. Is it that you will keep the project's implicit proprietary license as is?

**Comment by OneHappyForever** [comment]
I’m mainly concerned that without the source code, something like what happened to SSTap will happen here again.

**Comment by cyanlink** [comment]
@OneHappyForever You can still access the source code of previous versions, through the previous releases.

**Comment by iovw** [comment]
But it ’s not necessarily the same as previous.

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.

**Comment by lili2012** [comment]
So this is closed source software I wont trust it. I will change back to clash.
