### ISSUE TITLE
添加节点?

### ISSUE THREAD

**Issue by liao6964799** [Fndroid/clash_for_windows_pkg#1535]
请问如何手动添加节点呢?完全不懂如何配置,希望可以改进一下节点添加功能,让它更加快捷方便.
使用订阅转换的链接感觉节点有问题,基本都出现超时情况,但实际节点没有问题.

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/105271317-40010300-5bd2-11eb-9042-0fd467f8bd5e.png)

![image](https://user-images.githubusercontent.com/16091562/105271294-36779b00-5bd2-11eb-901a-320b51dd9980.png)
