### ISSUE TITLE
绕过中国大陆IP

### ISSUE THREAD

**Issue by edamame43** [Fndroid/clash_for_windows_pkg#1537]
请问clash for Windows有没像SSR+的绕过中国大陆所有IP的配置？否则上国内网站全部加载完太慢了

**Comment by yi-Xu-0100** [comment]
主要是编辑规则去做筛选

可以试试 https://github.com/tindy2013/subconverter/blob/master/README-cn.md

网络资源，自查安全：https://acl4ssr.netlify.app/

**Comment by edamame43** [comment]
你的意思是从SSR获取国内IP段然后转换使用？

**Comment by yi-Xu-0100** [comment]
@edamame43 你的配置是哪来的？如果是别人给的，让别人把 rules 部分添上这个部分就好。如果是服务商定死的，用上面的工具，他可以按照模板重新生成配置，规则部分基本都是有绕过国内的 ip。如果想自己添加，这里有 rules 的[介绍文档](https://lancellc.gitbook.io/clash/clash-config-file/rules)。

**Comment by edamame43** [comment]
服务商的。初次用发现上淘宝都走节点，看了规则，很少肯定不能用。SSR那边国内IP段的规则有8000多条，如果全部转过来，会不会影响加载速度？

**Comment by yi-Xu-0100** [comment]
@edamame43 https://lancellc.gitbook.io/clash/clash-config-file/rule-provider

>Match 340,000+ rules only 7.545 μs.

https://github.com/Loyalsoldier/clash-rules

这个也可以配合 jsdeliver 食用。

**Comment by edamame43** [comment]
好的我看下，谢谢。

**Comment by seldomGitHub** [comment]
所以有没有帮助我这种电脑小白的人写一下教程啊qaq
