### ISSUE TITLE
启动Clash for Windows后，出来Could not run clash core！

### ISSUE THREAD

**Issue by TalentSales** [Fndroid/clash_for_windows_pkg#154]
启动Clash for Windows后，出来Could not run clash core！
Clash for Windows版本为0.70，刚刚升级，就出来了。
卸载重新、降低版本、提示……都试过，解决不了。
请指教~~~

**Comment by Fndroid** [comment]
@TalentSales 升级到最新，点try to repair

**Comment by TalentSales** [comment]
![微信图片_20190808091452](https://user-images.githubusercontent.com/19505350/62668112-32939100-b9bd-11e9-9716-77d9b6613ad5.png)
 请参考图片，都试过，没有用的。Try to repair 无穷循环。

**Comment by Fndroid** [comment]
进logs文件夹，打开最新的balog发上来

**Comment by TalentSales** [comment]
您好，请参考附件。 
[2019-08-08-091205.log](https://github.com/Fndroid/clash_for_windows_pkg/files/3479530/2019-08-08-091205.log)
[2019-08-08-091222.log](https://github.com/Fndroid/clash_for_windows_pkg/files/3479531/2019-08-08-091222.log)

**Comment by Fndroid** [comment]
@TalentSales 9090端口被占用，在logs上一级目录中config.yml文件中external-controller的端口改成其他再试

**Comment by TalentSales** [comment]
是的，修改了一下端口就好了。谢谢~~~
原来我电脑上的Apache Tomcat占用了9090端口。

**Comment by whhxmwhh** [comment]
@TalentSales 9090端口被占用，在logs上一级目录中config.yml文件中external-controller的端口改成其他再试。找到答案了。谢谢

**Comment by whhxmwhh** [comment]
logs目录没有找到

**Comment by whhxmwhh** [comment]
隐藏很隐蔽呀。给像我一样的小白。
![log捕获](https://user-images.githubusercontent.com/7959854/75832133-6a967180-5df0-11ea-88a2-a701a3993ad4.JPG)

**Comment by whhxmwhh** [comment]
config.yaml以及config.yml两个文件都的要修改就可以。

**Comment by ucfauoc** [comment]
以下情况怎么解决？
time="2020-06-04T10:33:20+08:00" level=info msg="Can't find config, create an empty file"
time="2020-06-04T10:33:20+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-06-04T10:33:20+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-06-04T10:33:20+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-06-04T10:33:20+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-06-04T10:33:20+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
