### ISSUE TITLE
uplay游戏更新下载和cfw存在冲突

### ISSUE THREAD

**Issue by Qyir** [Fndroid/clash_for_windows_pkg#1547]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

win10，cfw：v0.14.1

[//]: # (平台及版本号)

**描述**

当uplay游戏内容更新下载时，如果cfw正在运行，uplay则会报告“不可修复的错误”并退出程序。

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

1. cfw正在运行
2. 启动uplay（无论是直接启动uplay程序，还是通过steam间接启动）
3. 进入uplay主界面几秒后，游戏更新下载开始时，弹出大致为“ubisoft connect发生无法修复的错误”，确认后程序结束

- 若进入uplay主界面后无游戏更新下载或立即取消游戏更新下载，则不会报错

[//]: # (请描述复现问题的步骤)

**预期行为**

uplay程序正常

[//]: # (清晰地描述期望看到的行为)

**日志**

![屏幕截图(38)](https://user-images.githubusercontent.com/48037182/105803677-ef761500-5fd8-11eb-9395-0bd75a681ebf.png)

[//]: # (上传触发问题对应的日志文件)

**截图**

无

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

实际上不确定是uplay程序本身的问题，还是ubisoft connect服务进程的问题

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
@Qyir 尝试 PAC 模式 或者 TUN ， TAP

**Comment by Qyir** [comment]
@yi-Xu-0100 TUN模式下目前还没遇见错误发生，应该是解决了，谢谢
