### ISSUE TITLE
能否把MacOS版本App的重命名为Clash for mac？

### ISSUE THREAD

**Issue by 1457384613gh** [Fndroid/clash_for_windows_pkg#1548]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**能否把MacOS版本App的重命名为Clash for mac？**

**Comment by spinachomes** [comment]
哈哈，自己在应用里重命名一下吧

**Comment by Fndroid** [comment]
不是很想
