### ISSUE TITLE
Proxies 界面会让人产生赫尔曼栅格错觉

### ISSUE THREAD

**Issue by RemoveYourLeftistMembership** [Fndroid/clash_for_windows_pkg#1549]
Proxies 里不同节点之间的网格交叉处非常容易看到赫尔曼栅格错觉（不断跳动的灰点），希望能够换一套更舒适的 UI 界面。

赫尔曼栅格错觉：https://www.shicuojue.com/portal.php?mod=view&aid=328

**Comment by Qyir** [comment]
你换其他颜色主题试试，别用黑色的。不过这效应其实挺主观的……

**Comment by Fndroid** [comment]
感谢告知，我考虑下怎么调整下

**Comment by GHOSTagw** [comment]
可能是你最近压力太大了.......

**Comment by Fndroid** [comment]
试下最新版

**Comment by RemoveYourLeftistMembership** [comment]
> 
> 
> 试下最新版

已解决，感谢！
