### ISSUE TITLE
可否实现分类查看log

### ISSUE THREAD

**Issue by cesaryuan** [Fndroid/clash_for_windows_pkg#155]
如题，可否在 Logs 界面中按照策略组对 request 进行分类，这样便于分析。
![image](https://user-images.githubusercontent.com/35998162/62815958-d1052b00-bb52-11e9-80e5-bbbcbc0b7161.png)

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
