### ISSUE TITLE
400 bad request 无法使用

### ISSUE THREAD

**Issue by CHENGKUNHOU** [Fndroid/clash_for_windows_pkg#1550]
**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号) win10 1909

**描述**
chrome和win10自带浏览器始终无法上google，youtube等外站，手机和mac clash都可以上。
google显示400 Bad Request，其他网站显示  此网站无法提供安全连接
配置文件我是直接从 https://www.hijk.pw/clash_template.yaml 下载的模板然后修改trajon节点，添加到到代理组。折腾了一天，clash的配置文档和https://lancellc.gitbook.io/clash的文档也都看过了，都试了相应模板修改。不知道为什么，而且14和13.8版本我都试过了，都不行。而且尝试过注释dns和disable 都不行，也试试过直接使用ip代替Trojan域名，也还是不行。

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)
time="2021-01-27T16:09:39+08:00" level=info msg="Start initial compatible provider Proxy"
time="2021-01-27T16:09:39+08:00" level=info msg="RESTful API listening at: 127.0.0.1:49935"
time="2021-01-27T16:09:39+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2021-01-27T16:09:39+08:00" level=info msg="Start initial compatible provider 自动选择快速节点"
time="2021-01-27T16:09:39+08:00" level=info msg="Start initial compatible provider PROXY"
time="2021-01-27T16:09:39+08:00" level=info msg="Start initial compatible provider HKMTMedia"
time="2021-01-27T16:09:39+08:00" level=info msg="Start initial compatible provider Final"
time="2021-01-27T16:09:39+08:00" level=info msg="Start initial compatible provider GlobalMedia"
time="2021-01-27T16:09:39+08:00" level=info msg="Start initial compatible provider Apple"
time="2021-01-27T16:09:39+08:00" level=info msg="Start initial compatible provider GlobalMedia"
time="2021-01-27T16:09:39+08:00" level=info msg="Start initial compatible provider Final"
time="2021-01-27T16:09:39+08:00" level=info msg="Start initial compatible provider 自动选择快速节点"
time="2021-01-27T16:09:39+08:00" level=info msg="Start initial compatible provider PROXY"
time="2021-01-27T16:09:39+08:00" level=info msg="Start initial compatible provider Apple"
time="2021-01-27T16:09:39+08:00" level=info msg="Start initial compatible provider HKMTMedia"
time="2021-01-27T16:10:15+08:00" level=info msg="[TCP] 127.0.0.1:50043 --> www.gitbook.com match Match() using Final[DIRECT]"
time="2021-01-27T16:10:15+08:00" level=info msg="[TCP] 127.0.0.1:50041 --> cn.bing.com match DomainSuffix(bing.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:15+08:00" level=info msg="[TCP] 127.0.0.1:50039 --> www.recaptcha.net match DomainSuffix(recaptcha.net) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:16+08:00" level=info msg="[TCP] 127.0.0.1:50046 --> www.recaptcha.net match DomainSuffix(recaptcha.net) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:16+08:00" level=info msg="[TCP] 127.0.0.1:50048 --> cn.bing.com match DomainSuffix(bing.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:17+08:00" level=info msg="[TCP] 127.0.0.1:50051 --> gitbook-28427.firebaseio.com match DomainSuffix(firebaseio.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:18+08:00" level=info msg="[TCP] 127.0.0.1:50053 --> gitbook-28427.firebaseio.com match DomainSuffix(firebaseio.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:20+08:00" level=info msg="[TCP] 127.0.0.1:50058 --> gitbook-28427.firebaseio.com match DomainSuffix(firebaseio.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:21+08:00" level=info msg="[TCP] 127.0.0.1:50060 --> gitbook-28427.firebaseio.com match DomainSuffix(firebaseio.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:22+08:00" level=info msg="[TCP] 127.0.0.1:50063 --> gitbook-28427.firebaseio.com match DomainSuffix(firebaseio.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:24+08:00" level=info msg="[TCP] 127.0.0.1:50065 --> gitbook-28427.firebaseio.com match DomainSuffix(firebaseio.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:25+08:00" level=info msg="[TCP] 127.0.0.1:50073 --> gitbook-28427.firebaseio.com match DomainSuffix(firebaseio.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:26+08:00" level=info msg="[TCP] 127.0.0.1:50075 --> gitbook-28427.firebaseio.com match DomainSuffix(firebaseio.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:28+08:00" level=info msg="[TCP] 127.0.0.1:50086 --> gitbook-28427.firebaseio.com match DomainSuffix(firebaseio.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:29+08:00" level=info msg="[TCP] 127.0.0.1:50088 --> gitbook-28427.firebaseio.com match DomainSuffix(firebaseio.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:29+08:00" level=info msg="[TCP] 127.0.0.1:50090 --> cn.bing.com match DomainSuffix(bing.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:29+08:00" level=info msg="[TCP] 127.0.0.1:50092 --> cn.bing.com match DomainSuffix(bing.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:32+08:00" level=info msg="[TCP] 127.0.0.1:50098 --> cn.bing.com match DomainSuffix(bing.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:32+08:00" level=info msg="[TCP] 127.0.0.1:50097 --> www.bing.com match DomainSuffix(bing.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:32+08:00" level=info msg="[TCP] 127.0.0.1:50094 --> gitbook-28427.firebaseio.com match DomainSuffix(firebaseio.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:32+08:00" level=info msg="[TCP] 127.0.0.1:50101 --> cn.bing.com match DomainSuffix(bing.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:32+08:00" level=info msg="[TCP] 127.0.0.1:50102 --> www.bing.com match DomainSuffix(bing.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:32+08:00" level=info msg="[TCP] 127.0.0.1:50105 --> gitbook-28427.firebaseio.com match DomainSuffix(firebaseio.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:33+08:00" level=info msg="[TCP] 127.0.0.1:50107 --> www.bing.com match DomainSuffix(bing.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:33+08:00" level=info msg="[TCP] 127.0.0.1:50109 --> cn.bing.com match DomainSuffix(bing.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:33+08:00" level=info msg="[TCP] 127.0.0.1:50111 --> www.bing.com match DomainSuffix(bing.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:33+08:00" level=info msg="[TCP] 127.0.0.1:50113 --> www.bing.com match DomainSuffix(bing.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:34+08:00" level=info msg="[TCP] 127.0.0.1:50117 --> www.bing.com match DomainSuffix(bing.com) using PROXY[Los_cn2gia]"

time="2021-01-27T16:10:43+08:00" level=info msg="[TCP] 127.0.0.1:50193 --> v10.events.data.microsoft.com match DomainSuffix(microsoft.com) using DIRECT"
time="2021-01-27T16:10:43+08:00" level=info msg="[TCP] 127.0.0.1:50240 --> www.google.com match DomainKeyword(google) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:44+08:00" level=info msg="[TCP] 127.0.0.1:50244 --> www.bing.com match DomainSuffix(bing.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:44+08:00" level=info msg="[TCP] 127.0.0.1:50247 --> gitbook-28427.firebaseio.com match DomainSuffix(firebaseio.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:44+08:00" level=info msg="[TCP] 127.0.0.1:50249 --> gitbook-28427.firebaseio.com match DomainSuffix(firebaseio.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:46+08:00" level=info msg="[TCP] 127.0.0.1:50251 --> www.google.com match DomainKeyword(google) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:47+08:00" level=info msg="[TCP] 127.0.0.1:50255 --> gitbook-28427.firebaseio.com match DomainSuffix(firebaseio.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:47+08:00" level=info msg="[TCP] 127.0.0.1:50252 --> www.google.com match DomainKeyword(google) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:47+08:00" level=info msg="[TCP] 127.0.0.1:50258 --> gitbook-28427.firebaseio.com match DomainSuffix(firebaseio.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:50+08:00" level=info msg="[TCP] 127.0.0.1:50261 --> gitbook-28427.firebaseio.com match DomainSuffix(firebaseio.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:50+08:00" level=info msg="[TCP] 127.0.0.1:50267 --> gitbook-28427.firebaseio.com match DomainSuffix(firebaseio.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:54+08:00" level=info msg="[TCP] 127.0.0.1:50296 --> nav.smartscreen.microsoft.com match DomainSuffix(microsoft.com) using DIRECT"
time="2021-01-27T16:10:54+08:00" level=info msg="[TCP] 127.0.0.1:50293 --> go.microsoft.com match DomainSuffix(microsoft.com) using DIRECT"
time="2021-01-27T16:10:55+08:00" level=info msg="[TCP] 127.0.0.1:50300 --> gitbook-28427.firebaseio.com match DomainSuffix(firebaseio.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:55+08:00" level=info msg="[TCP] 127.0.0.1:50302 --> smartscreen-prod.microsoft.com match DomainSuffix(microsoft.com) using DIRECT"
time="2021-01-27T16:10:55+08:00" level=info msg="[TCP] 127.0.0.1:50304 --> gitbook-28427.firebaseio.com match DomainSuffix(firebaseio.com) using PROXY[Los_cn2gia]"
time="2021-01-27T16:10:56+08:00" level=info msg="[TCP] 127.0.0.1:50307 --> www.baidu.com match DomainSuffix(baidu.com) using DIRECT"
time="2021-01-27T16:10:56+08:00" level=info msg="[TCP] 127.0.0.1:50308 --> nav.smartscreen.microsoft.com match DomainSuffix(microsoft.com) using DIRECT"
time="2021-01-27T16:10:56+08:00" level=info msg="[TCP] 127.0.0.1:50311 --> hectorstatic.baidu.com match DomainSuffix(baidu.com) using DIRECT"
time="2021-01-27T16:10:56+08:00" level=info msg="[TCP] 127.0.0.1:50314 --> sp2.baidu.com match DomainSuffix(baidu.com) using DIRECT"

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/26861188/105963843-718b3a00-60bc-11eb-96ea-e53e3ef0ecb4.png)

**其他说明**

[//]: # (其他补充内容)
客户端截图如上图，点击还是会显示ping的延迟。就是死活上不。是不是win10本身需要啥设置，求大佬赐教。

**Comment by yi-Xu-0100** [comment]
skip-cert-verify: true

**Comment by CHENGKUNHOU** [comment]
> skip-cert-verify: true

感谢回复，试了下还是不行

**Comment by yi-Xu-0100** [comment]
@CHENGKUNHOU 检查一下时间

**Comment by CHENGKUNHOU** [comment]
> @CHENGKUNHOU 检查一下时间，用匿名页面测试，避免缓存问题

谢谢回复！时间OK的，匿名页面还是不行；系统自带的 代理页面 有需要设置吗？我看那个页面都是全关闭状态的。

**Comment by yi-Xu-0100** [comment]
@CHENGKUNHOU ？？？没开系统代理

**Comment by CHENGKUNHOU** [comment]
> @CHENGKUNHOU ？？？没开系统代理，不对啊，我看你日志里面有走规则啊
> 
> 或者你在 CFW 中切到 PAC 模式试试
还是不行哇，刚才傻逼了，是开的，刚才要回你消息关了代理然后没了，CFW开启它会代理的。PAC 全局 试过了还是不行，有毒啊 我还是以为google服务器今天炸了，一直还是400 bad request

**Comment by CHENGKUNHOU** [comment]
> @CHENGKUNHOU ？？？没开系统代理，不对啊，我看你日志里面有走规则啊
> 
> 或者你在 CFW 中切到 PAC 模式试试

ping 服务器还显示延迟数据，就是上不了，左上角下载还时不时蹦出几百B，但是就是连不上

**Comment by yi-Xu-0100** [comment]
感觉服务器端配置有问题，日志里面没有 error 是吧？

**Comment by CHENGKUNHOU** [comment]
> 感觉服务器端配置有问题，日志里面没有 error 是吧？或者给出你配置的节点的细节，端口密码域名啥的随便替代，但其他的内容是啥？

- name: "Los_cn2gia"
  type: trojan
  server: www.**.work
  port: 443
  password: **

  alpn:
    - h2
    - http/1.1
  skip-cert-verify: true

- name: "GCP_OR"
  type: trojan
  server: www.**.xyz
  port: 443
  password: **
  # udp: true
  # sni: example.com # aka server name
  alpn:
     - h2
     - http/1.1
  skip-cert-verify: true

**Comment by CHENGKUNHOU** [comment]
> 感觉服务器端配置有问题，日志里面没有 error 是吧？或者给出你配置的节点的细节，端口密码域名啥的随便替代，但其他的内容是啥？

![Uploading image.png…]()

**Comment by CHENGKUNHOU** [comment]
> 感觉服务器端配置有问题，日志里面没有 error 是吧？或者给出你配置的节点的细节，端口密码域名啥的随便替代，但其他的内容是啥？

# Trojan
- name: "Los_cn2gia"
  type: trojan
  server: www.*.work
  port: 443
  password: *
  alpn:
    - h2
    - http/1.1
  skip-cert-verify: true

- name: "GCP_OR"
  type: trojan
  server: www.*.xyz
  port: 443
  password: *.
  alpn:
     - h2
     - http/1.1
  skip-cert-verify: true

**Comment by yi-Xu-0100** [comment]
麻烦用 markdown 的代码块处理一下，显示出缩进关系，即 如下试试
````markdown
```yaml
内容
```

**Comment by CHENGKUNHOU** [comment]
> 麻烦用 markdown 的代码块处理一下，显示出缩进关系，即 如下试试
> 
> ```gfm
> ```yaml
> 内容
> ```
> ```

```
- name: "Los_cn2gia"
  type: trojan
  server: www.*.work
  port: 443
  password: *
  alpn:
    - h2
    - http/1.1
  skip-cert-verify: true

 - name: "GCP_OR"
   type: trojan
   server: www.x.xyz
   port: 443
   password: x.
   alpn:
      - h2
      - http/1.1
   skip-cert-verify: true
```

**Comment by yi-Xu-0100** [comment]
@CHENGKUNHOU 我没感觉有啥问题。。。

**Comment by CHENGKUNHOU** [comment]
> @CHENGKUNHOU 我没感觉有啥问题。。。

应该还是有问题的，我去mac上开了个win10虚拟机还是不行。有毒啊，难道这两个版本和win 10冲突？

**Comment by yi-Xu-0100** [comment]
@CHENGKUNHOU CFW 可以有 mac 版本，是否这个节点支持呢？

**Comment by CHENGKUNHOU** [comment]
> @CHENGKUNHOU CFW 可以有 mac 版本，是否这个节点支持呢？

还真的没问题，意思是win10的锅？跟配置没关系了吧，14.1的版本mac上没问题的

**Comment by yi-Xu-0100** [comment]
@CHENGKUNHOU win10 系统时间重新对下，然后清除下浏览器缓存，重启下电脑测试

**Comment by CHENGKUNHOU** [comment]
> @CHENGKUNHOU win10 系统时间重新对下，然后清除下浏览器缓存，重启下电脑测试

明天上班去试试，其实下午已经重新清下时间，明天从头开始试试，谢谢大佬

**Comment by CHENGKUNHOU** [comment]
> @CHENGKUNHOU win10 系统时间重新对下，然后清除下浏览器缓存，重启下电脑测试
我又来麻烦大佬了 ，又测试了一台同事的win10 还是无法连上，不知道为何？
连接Google还是现实的bad request。
日志如下，无error，但是好像没流量，已清缓存、重启，之前大佬提到的系统时间对一下是啥，系统时间是准的，cfw需要什么特殊操作吗？

现在感觉问题可能出在 2 点

 1. 是不是 win10  有啥需要设置的，默认啥都没设置，直接开的cfw代理，下图为开启后的win10系统代理截图，有问题吗？
![image](https://user-images.githubusercontent.com/26861188/107133801-f7ae4880-6926-11eb-8ea7-2a0c4a034e66.png)


 2.  可能是配置文件的问题，但是配置文件我试了下mac下同样的配置文件是ok的，完全没问题，问题应该不在这把？下面为log，好像没啥问题？
![image](https://user-images.githubusercontent.com/26861188/107133783-d188a880-6926-11eb-86e6-3d94275e9138.png)


请大佬赐教，感谢！

**Comment by yi-Xu-0100** [comment]
@CHENGKUNHOU 看起来系统代理没有问题，时间是因为如果系统时间不准，可能有 400 bad request 的问题。网络名称是否是中文？

**Comment by CHENGKUNHOU** [comment]
> @CHENGKUNHOU 看起来系统代理没有问题，时间是因为如果系统时间不准，可能有 400 bad request 的问题。网络名称是否是中文？

都是英文的，我安装同样的操作在同事电脑上试了一遍也不行：
1. 先清缓存 浏览器cookie等
2. exe安装或者7z直接解压 ——> 拖之前的配置文件进去 ——> 选择rule  > 打开面板代理   ——>  打开chrome ——> 无法打开，包括别的外站也不行 终端ping 也不行

**Comment by yi-Xu-0100** [comment]
1. 尝试 server 那里直接是域名呢
2. 尝试 udp 为 true 试试呢

**Comment by CHENGKUNHOU** [comment]
> @CHENGKUNHOU
> 
> 1. 尝试 server 那里直接是域名呢
> 2. 尝试 udp 为 true 试试呢

还是不行呢？不知道跟下面的tap有关系吗？
![image](https://user-images.githubusercontent.com/26861188/107141007-0ade0a00-6961-11eb-982c-dd28da0c9413.png)

对了，我的账户好像默认是管理员？这个有影响吗？
![image](https://user-images.githubusercontent.com/26861188/107141046-35c85e00-6961-11eb-974b-362991d813f5.png)

**Comment by yi-Xu-0100** [comment]
@CHENGKUNHOU 我弄了些 trojan 节点尝试，最开始会显示 “ERR_SSL_PROTOCOL_ERROR” ， 然后我切换配置，用其他节点搜索相关信息后，返回那些 trojan 节点自动好了。我不太确定可能由什么导致。

port 为 0. 正常使用就不用管，如果有问题，参考 #671
