### ISSUE TITLE
能否开发汉化包？

### ISSUE THREAD

**Issue by 1457384613gh** [Fndroid/clash_for_windows_pkg#1552]
**描述**
安卓版Clash可以是中文版，那么桌面版clash能否开发汉化包？

**Comment by yi-Xu-0100** [comment]
Duplicate of #999

**Comment by iamqiz** [comment]
BoyceLig/Clash_Chinese_Patch: Clash For Windows 汉化补丁和汉化脚本
https://github.com/BoyceLig/Clash_Chinese_Patch
