### ISSUE TITLE
Install for all users in first installation

### ISSUE THREAD

**Issue by xmha97** [Fndroid/clash_for_windows_pkg#1553]
By default clash installed for current user.
I need below feature:
- Install for all users by default
![Setup](https://user-images.githubusercontent.com/23485114/106074597-5ef71c00-6121-11eb-930d-43e1978dd371.png)

Thanks.

**Comment by Fndroid** [comment]
I think this option will be remembered and used on the next installation.

**Comment by xmha97** [comment]
Yes, this option will be remembered and used on the next installation.
But I want it to be the first installation for all users.

**Comment by Fndroid** [comment]
I don't think that's a good idea.🙁

**Comment by xmha97** [comment]
Why do you prefer to install the app for one user only? (instead of all users)

**Comment by Fndroid** [comment]
Because multiple accounts means multiple users will use the same computer.
