### ISSUE TITLE
更新v 0.14.1后好像开机自启失效了？

### ISSUE THREAD

**Issue by DearDeer7** [Fndroid/clash_for_windows_pkg#1554]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [×] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [×] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [×] 已经尝试更新到最新版本，问题依旧存在
- [×] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
OS：window10 20H2
CFW： v 0.14.1

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
更新到 v 0.14.1 后用了两天发现设置的开机自启每次都没有生效，之前用的 v 0.13.x 开机自启都是好使的，要说区别的话，之前用的是package版本，免安装使用，这次的 v 0.14.1 用的exe版本的，安装前已删除旧版本。

**复现**

[//]: # (请描述复现问题的步骤)
1. 开机，等待开机完成后，CFW未启动

**预期行为**

[//]: # (清晰地描述期望看到的行为)
开机完成后，CFW正常运行。

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
如果exe被设置成管理员权限启动就不能开机自启动

**Comment by DearDeer7** [comment]
那是我了，但是exe安装好像必须要管理员权限吧，我直接安装一直失败，后来管理员权限安装的就没啥问题

**Comment by DearDeer7** [comment]
> 如果exe被设置成管理员权限启动就不能开机自启动
那是我了，但是exe安装好像必须要管理员权限吧，我直接安装一直失败，后来管理员权限安装的就没啥问题

**Comment by DearDeer7** [comment]
> 如果exe被设置成管理员权限启动就不能开机自启动

那是我了，但是exe安装好像必须要管理员权限吧，我直接安装一直失败，后来管理员权限安装的就没啥问题

**Comment by yi-Xu-0100** [comment]
@DearDeer7 安装软件需要管理员方式，启动软件不需要

**Comment by Fndroid** [comment]
安装也不需要

**Comment by DearDeer7** [comment]
🆗，但我安装不以管理员身份没法安装，我再试试package版的，看看好不好使

**Comment by DearDeer7** [comment]
> 🆗，但我安装不以管理员身份没法安装，我再试试package版的，看看好不好使

package版好使，先这样吧
