### ISSUE TITLE
无法切换到某个配置

### ISSUE THREAD

**Issue by Giter-t** [Fndroid/clash_for_windows_pkg#1555]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**
![image](https://user-images.githubusercontent.com/67638483/106083049-cc716f80-6156-11eb-83da-93dc4035cdb4.png)

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
windows10 20H2

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
选择这个配置文件就会出问题，而另一个相同配置的只是proxyprovider网址更改过的配置文件就不会出问题。
第一次导入这个配置文件可以正常使用，重启软件以后便无法使用（重新导入配置也无法使用）。

**复现**

[//]: # (请描述复现问题的步骤)

选择配置文件，过一会就会出现。

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)
time="2021-01-28T11:00:46+08:00" level=info msg="RESTful API listening at: 127.0.0.1:5555"
time="2021-01-28T11:00:46+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2021-01-28T11:00:52+08:00" level=info msg="Start initial provider gb"
从打开软件选择配置到出现错误就只有这几行日志

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/67638483/106083966-553cdb00-6158-11eb-8a45-58398371a600.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
- [ ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**Comment by Giter-t** [comment]
用的就是刚从仓库下载下来的软件

**Comment by Fndroid** [comment]
反正我这里下的没有中文

**Comment by Giter-t** [comment]
![1](https://user-images.githubusercontent.com/67638483/106102346-36e7d700-617a-11eb-8b1a-a466a35253c0.gif)

https://proxypoolss.tk/clash/config
这是配置文件订阅

**Comment by yi-Xu-0100** [comment]
@Giter-t 个人用你的配置文件订阅并没有问题，建议检查个人操作，你的 gif 是使用的本地文件。

**Comment by Giter-t** [comment]
用订阅文件也是这个问题
![1](https://user-images.githubusercontent.com/67638483/106110189-5df7d600-6185-11eb-95ba-6007613ac9e1.gif)

**Comment by yi-Xu-0100** [comment]
@Giter-t parser 或者 mixin 内容是否修改过？去 home directory 删除所有文件，重新下载配置试试，个人测试没有问题。而且你第二个 gif 在最后的时候成功选择了配置。

**Comment by Giter-t** [comment]
就是使用的刚刚下载下来的应用，没有做过任何更改。
除了默认配置就只有这一个配置，显示是选中了这个配置，实际上proxies里没有任何内容。

**Comment by Giter-t** [comment]
现在可以切换了，好像是内存不够的问题，在切换的时候如果内存占用比较高就会出现失败的情况（大概是因为proxy provider链接内的节点导入到本地文件时占用内存较高）。
