### ISSUE TITLE
希望增加中文版

### ISSUE THREAD

**Issue by a3659950** [Fndroid/clash_for_windows_pkg#1557]
**描述**
希望增加中文版本，，，，，

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
#999

**Comment by kouhe3** [comment]
所以，  @Fndroid  您的观点是

CFW中有许多专有名词，即使汉化了也还和没翻译一样晦涩难懂。
解决晦涩难懂的最好方法应该是去看CFW的文档

对吗？

**Comment by a3659950** [comment]
不对，比如阴茎也是医学的专有名词，但是你懂阴茎的意思能代表你也看得懂penis？



发自 网易邮箱大师




在2021年02月09日 10:29，kouhe3 写道：

所以， @Fndroid 您的观点是

CFW中有许多专有名词，即使汉化了也还和没翻译一样晦涩难懂。
解决晦涩难懂的最好方法应该是去看CFW的文档

对吗？

**Comment by aogg** [comment]
只要汉化长句子，不汉化单词也好啊

**Comment by iamqiz** [comment]
BoyceLig/Clash_Chinese_Patch: Clash For Windows 汉化补丁和汉化脚本
https://github.com/BoyceLig/Clash_Chinese_Patch
