### ISSUE TITLE
0.14.2版更新providers模块报错

### ISSUE THREAD

**Issue by hackenfu** [Fndroid/clash_for_windows_pkg#1558]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 10
0.14.2
**描述**
providers模块update all后报错，proxy和rule全线报错，朋友试了也这样
[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/51818740/106240553-6c0a2d00-623f-11eb-93a2-3d885f08e373.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
上面两个是显示错误，下个版本修复
下面两个是对应地址访问不了导致的
