### ISSUE TITLE
策略组中proxy-providers名称显示不对

### ISSUE THREAD

**Issue by DockerCS** [Fndroid/clash_for_windows_pkg#1559]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

Windows 10
Clash for Windows 0.14.2及以前版本都显示不对

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

有三个proxy-providers，前两个在策略组中名称显示正确，但是第三个Provider名称显示不正确，而节点正确（如图所示）

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/26867628/106245225-1a65a080-6247-11eb-9639-7c46e430f73e.png)
![image](https://user-images.githubusercontent.com/26867628/106245281-30736100-6247-11eb-97a4-4cc5fcbb8bc5.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
因为这个节点同时存在两个providers里了？

**Comment by DockerCS** [comment]
> 因为这个节点同时存在两个providers里了？

![image](https://user-images.githubusercontent.com/26867628/106247080-01aaba00-624a-11eb-8ff1-9b38819bed43.png)
好像是的，如果前面的providers1包括后面provider2所有节点，那么就不会显示provider2的名称，这种设定也挺奇怪的

**Comment by Fndroid** [comment]
因为这个只能是推断出来的，只有一个名字也不能确定是哪一个provider里的
