### ISSUE TITLE
UI issue of version 0.7 and later on window10.

### ISSUE THREAD

**Issue by L1H0n9Jun** [Fndroid/clash_for_windows_pkg#156]
Thank u for ur excellent work. I love it.

After upgrade to 0.7.0 (and later versions), I found ui without color. As is shown below.

This is 0.6.x versions' ui on my win10:
<img width="751" alt="0 6 3" src="https://user-images.githubusercontent.com/20871291/62864775-33228380-bd3f-11e9-8a9d-c071a35eafa3.png">

This is 0.7.x versions' ui on my win10:
<img width="752" alt="0 7 2" src="https://user-images.githubusercontent.com/20871291/62864796-41709f80-bd3f-11e9-9495-e64ae06da77d.png">

Is the ui shown correctly? or sth. crashed on my pc?
What's other info needed?

**Comment by L1H0n9Jun** [comment]
Also, I find 0.7.3 with installation version only, what's the problem with protable version? Thx so much.

**Comment by Fndroid** [comment]
> I found ui without color. 

Gray is a color. If you prefer dark, try to click the logo in General module.

> what's the problem with portable version?

We did built a .zip version for 0.7.2, but could not upload it to the release assets because of a Github issue. If you need it, try to open the .exe file with WinRAR.

**Comment by L1H0n9Jun** [comment]
> > I found ui without color.
> 
> Gray is a color. If you prefer dark, try to click the logo in General module.
> 
> > what's the problem with portable version?
> 
> We did built a .zip version for 0.7.2, but could not upload it to the release assets because of a Github issue. If you need it, try to open the .exe file with WinRAR.

Awesome! Thx.
