### ISSUE TITLE
可以给个简单的教程指示一下如何使用clash给git的各种操作加速吗Quq，我看网上的好多端口的设置都看傻眼了

### ISSUE THREAD

**Issue by jensenojs** [Fndroid/clash_for_windows_pkg#1563]
**描述**
如题：网络上其实不缺乏各种配置的手段，但是各种教程之间还是有些模糊和冲突的，就有点点搞人

**Comment by yi-Xu-0100** [comment]
@jensenojs 教程一般分为2种，给终端配置代理和给 git 配置代理。

给 git 配置代理又分为给 git 全局设置，和 git 配置前置代理（proxychain大概）。
给终端配置代理可以声明环境变量来设置代理，也可以通过终端的配置脚本（预先加载的配置）来完成永久配置。

**Comment by jensenojs** [comment]
可能是给git进行全局设置？我之前在网络上参照的两份教程的链接先附上好了，一份是[CSDN的git加速总结](https://blog.csdn.net/willsnowdev/article/details/90140266)，另外一份链接是[这个](https://ruby-china.org/topics/40408)，给出两个链接的原因是它们的端口号不一样，这给还没有开始学计网的我带来一些小小的困扰Quq

我昨天照着教程弄的时候似乎稀里糊涂的成功了，但是今天我发现我push不上去，于是把所有的设置全都清空了，打算重新弄。

我当时采取的一种方式是下面这个——我在那份不是CSDN的链接中了解到这种加速方式是适用于http和https的？
```
# 这里的端口号我也忘了我当时改成什么了，反正clash的应该不是这个1086。？clash的是1080吧。？
git config --global http.https://github.com.proxy https://127.0.0.1:1086
git config --global https.https://github.com.proxy https://127.0.0.1:1086
```
然后针对ssh的加速，也是我自己仓库的连接方式，使用的就是这个加速，这个7890原来是1080的来着，但是当时连接不上吧，然后我在github上逛到一个人，它的情况是把7891改成了7890于是就行了。我也就跟着稀里糊涂地跟着改了改。。
```
Host github.com
ProxyCommand connect -H 127.0.0.1:7890 %h %p   #-S为socks
HostName %h
Port 22
User git
IdentityFile  ~/.ssh/id_rsa 
IdentitiesOnly yes
```
第一次提issue！没想到被人回复了，超级开心！如果有什么礼仪上冒犯了的还请见谅Quq

**Comment by jensenojs** [comment]
再读了一遍发现没有回答要哪种的问题，哪种都行，简单点最好（比心）

**Comment by yi-Xu-0100** [comment]
@jensenojs 端口主要指对应的代理模式，http 或者 sock，均由端口代理软件给出。clash 的端口号由配置文件决定，默认 mixed-port 是 7890。以前的 ss 是 1080 ，许多教程以以前的为主，所以会写 1080。

clash 有 mixed-port 指的是同时支持两种模式的端口。如果需要指定不同模式不同端口，则在配置文件中指出，但要保留 mixed-port 项（个人认为没必要）。官方 wiki 中的教程对 clash 提供的端口给出的介绍：<https://lancellc.gitbook.io/clash/clash-config-file/general>

你的链接中，主要是对 git 进行配置。基本满足 github 的慢速问题，可以尝试。

**Comment by jensenojs** [comment]
十分感谢您！
