### ISSUE TITLE
@Fndroid 14.2也遇到这个问题，打开cfw默认在后台运行，但是不能科学上网，必须要打开主界面Loading之后才能科学上网

### ISSUE THREAD

**Issue by Fndroid** [Fndroid/clash_for_windows_pkg#1566]
@Fndroid 14.2也遇到这个问题，打开cfw默认在后台运行，但是不能科学上网，必须要打开主界面Loading之后才能科学上网

__Originally posted by @BaileyZyp in https://github.com/Fndroid/clash_for_windows_pkg/issues/1527#issuecomment-769902129__

**Comment by 365962648** [comment]
14.3仍旧有此问题

**Comment by BaileyZyp** [comment]
@365962648 你什么系统，我win10更新14.3已经正常了

**Comment by 365962648** [comment]
@BaileyZyp win10 20h2 19042.746

**Comment by BaileyZyp** [comment]
> @BaileyZyp win10 20h2 19042.746

那不应该啊，我也是20h2

**Comment by 365962648** [comment]
> > @BaileyZyp win10 20h2 19042.746
> 
> 那不应该啊，我也是20h2

重装后已正常

**Comment by evenardo** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/1574

怀疑我遇到的问题, 跟这个有一定的关联, 我是必须要看一眼 Connections 页面才能正常使用, 看一眼 loading 不行, 不然一直自动反复切换 disconnected 和 connected .
