### ISSUE TITLE
在创建IE代理的时候，能不能单独设置套接字代理？

### ISSUE THREAD

**Issue by lddsb** [Fndroid/clash_for_windows_pkg#157]
经测试，发现有道云笔记会同步失败，在把ie代理中的套接字代理设置成sock5之后同步成功。可是每次重新启动`Clash for Windows`的时候，ie代理会被重置，所以想请问能不能在设置ie代理的时候单独设置每个代理项而不是`对所有协议使用相同的代理服务器`

**Comment by lddsb** [comment]
![iexplore_vsmeQJyfsA](https://user-images.githubusercontent.com/20765867/62869403-628abd80-bd4a-11e9-89ea-5fbc7b0d46c1.png)

**Comment by lddsb** [comment]
我错了，能不能干脆不要设置ie代理

**Comment by Fndroid** [comment]
设置系统代理是使用工具：https://github.com/Noisyfox/sysproxy
