### ISSUE TITLE
希望在设置中提供是否固定选项卡位置的开关。

### ISSUE THREAD

**Issue by Lechenx** [Fndroid/clash_for_windows_pkg#1573]
**描述**
### 希望在设置中提供是否固定选项卡位置的开关。
很高兴看到大佬在新版本中实现了选项卡可以通过拖动改变位置的功能，但是在某些情况下会产生误触。

**其他说明**
其他补充内容

**Comment by DockerCS** [comment]
> **描述**
> 
> ### 希望在设置中提供是否固定选项卡位置的开关。
> 很高兴看到大佬在新版本中实现了选项卡可以通过拖动改变位置的功能，但是在某些情况下会产生误触。
> 
> **其他说明**
> 其他补充内容

我感觉也是，很容易误触，而改动侧边栏顺序

**Comment by Fndroid** [comment]
下个版本
