### ISSUE TITLE
能否在CFW的setting一栏中增加IPV6选项

### ISSUE THREAD

**Issue by AssICan** [Fndroid/clash_for_windows_pkg#1578]
**描述**
CFW默认ipv6为false。如果要通过IPV6连接节点，需要在general yaml中添加ipv6: true。在 0.14.1及更新的版本中，还去除了对 config.yaml变化的监听，改动后需要重启CFW才能生效。因此在新版本中开启对IPV6节点的支持，相对比较麻烦，对小白用户不是很友好。
能不能在setting一栏中加上一个IPV6的开关选项，方便用户快速开启对IPV6节点的支持？
**其他说明**
自从去年下半年教育网IPV6的路由改动后，通过IPV6出国效果要好于IPV4，普通线路也能跑到很高的速度。但是由于很多小白不会手动改，所以一直用不了IPV6的节点

**Comment by Fndroid** [comment]
其实之前增加修改端口的时候就准备加了，但是碰巧发现了core的一个小bug，所以就先没加了。后面会加上的

**Comment by AssICan** [comment]
好的，非常感谢！另外我还有一个疑问，general yaml中关于IPV6的设置不能被订阅覆盖是基于什么考虑呢？

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/106458815-e18a2d80-64cb-11eb-8236-bd2c9fccb545.png)

和``mixed-port``一样，和你本地环境相关，不应该由服务提供者决定

**Comment by AssICan** [comment]
所以你是考虑到一些节点同时具有A和AAAA的记录这种情况吗？套了CF确实会有这个问题
