### ISSUE TITLE
tun模式的service mode以及force quit一起使用引发的良性（或许）bug

### ISSUE THREAD

**Issue by hope140** [Fndroid/clash_for_windows_pkg#1579]
**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

windows10 20H2
cfw 0.14.3版本

**描述**

tun模式的service mode以及force quit一起使用引发的良性（或许）bug

**复现**

1. 开启service mode（tun模式设置好，且mixin处于关闭状态）
2. 在任务栏点击more中的force quit
3. 打开任务管理器，可以看到clash-core-service.exe和clash-win64处于运行状态
4. 打开网页，代理服务依旧运行

**预期行为**

并不影响正常使用，复现也过于刁钻，退出都会用quit的吧2333

**日志**

复现过程中开启debug模式，没有涉及相关日志描述

**截图**

![image](https://user-images.githubusercontent.com/61866799/106447140-18584780-64bc-11eb-9a2f-87e3be697aec.png)

![image](https://user-images.githubusercontent.com/61866799/106447159-1c846500-64bc-11eb-85ab-6694033e5e85.png)

![image](https://user-images.githubusercontent.com/61866799/106447172-21491900-64bc-11eb-88e6-8783e7bff0bb.png)

**其他说明**

[//]: # (其他补充内容)

显然这对有些人来说是一个良性bug（比如已经设置好不需要时常打开设置调整），所以是否可以在解决退出问题的同时，增加不需要相对较高的面板常驻内存的功能

**Comment by Fndroid** [comment]
预期行为，不是bug

**Comment by hope140** [comment]
感谢F大回答我的问题，还有一个问题，如果是设定好的话，可以添加一个开机便达到如上状态的功能吗

**Comment by Fndroid** [comment]
目前做不到，因为很多看着理所当然的功能（比如恢复配置，恢复节点选择状态）都是GUI做的

**Comment by miaomiaoclub** [comment]
那么能否在GUI完成工作后自动force quit，达到同样的效果
