### ISSUE TITLE
代理后国内的一些网站打不开了 http://doc.qing-niu.tech/

### ISSUE THREAD

**Issue by drowecho** [Fndroid/clash_for_windows_pkg#1581]
Global 或者 Rule 代理后翻墙和国内的大部门网址都 ok
但是一些打不开了，比如 http://doc.qing-niu.tech/    只能跳到 Direct，请问这个是什么问题

**Comment by yi-Xu-0100** [comment]
@drowecho 这个网址，好像就是打不开，至少我不管代不代理都是不行的，是不是网址错了

**Comment by drowecho** [comment]
@yi-Xu-0100  http://doc.qing-niu.tech/ 是我们公司的wiki，应该不是局域网啊
![image](https://user-images.githubusercontent.com/56685203/106560072-5c515800-6561-11eb-93dc-41048d81f992.png)

**Comment by Fndroid** [comment]
你加个规则让它直连不就好了

**Comment by drowecho** [comment]
@Fndroid 好的，我搜一下怎么操作，谢谢
