### ISSUE TITLE
请问支持ss+ws+tls吗？用的是xray内核吗？

### ISSUE THREAD

**Issue by csgowdnmd** [Fndroid/clash_for_windows_pkg#1584]
**描述**
请具体并清楚地描述期望功能及期望的效果

**其他说明**
其他补充内容

**Comment by yi-Xu-0100** [comment]
用的 clash 内核

core issue: <https://github.com/Dreamacro/clash/issues>

**Comment by wordlesswind** [comment]
Duplicate of #1499
