### ISSUE TITLE
开启系统代理会导致B460M迫击炮WIFI版本自带AX200无线网卡无法连接网络

### ISSUE THREAD

**Issue by DeweyLau** [Fndroid/clash_for_windows_pkg#1586]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)
- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows10    Clash版本 0.14.3

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
开启系统代理会导致B460M迫击炮WIFI版本自带的AX200无线网卡无法连接网络
(一直显示正在检测网络要求  最终 无法连接到这个网络)

**复现**

无

**预期行为**

AX200 正常连接WiFi网络

**日志**

![image](https://user-images.githubusercontent.com/68521772/106760227-87759d80-666e-11eb-9a60-0bfd43dab8b0.png)

**截图**
![QQ截图20210203222119](https://user-images.githubusercontent.com/68521772/106760012-539a7800-666e-11eb-94af-b0ff843add0b.png)
![image](https://user-images.githubusercontent.com/68521772/106759946-44b3c580-666e-11eb-83cf-6d8be9d05fec.png)

**其他说明**
 Win10 LTSC 2019  和最新Win10 都无法连接网络  网络本身没有问题 笔记本和手机都可以正常连接

**Comment by kingforme** [comment]
重新安装网卡驱动
