### ISSUE TITLE
clash for android

### ISSUE THREAD

**Issue by PSYCHO856** [Fndroid/clash_for_windows_pkg#1587]
[//]: # (如不按模版填写，则issue将被直接关闭)

安卓收集导入节点后，点击启动闪退 提示cursor window allocation of 2048 kb failed.

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

华为p10的系统

[//]: # (平台及版本号)

sockboom上下的 他们现在在推荐使用clash

[//]: # (请具体并清楚地描述遇到的问题)

手动导入url后 点击启动就闪退 20次大概会有1次成功连上 但一会儿也会自动关闭

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
@PSYCHO856 ？？？这里是 clash for windows。

clash for android: <https://github.com/Kr328/ClashForAndroid/issues>

**Comment by akw5454521** [comment]
换一台大内存的手机
