### ISSUE TITLE
mac 10.15.7 看不到system tray or menu bar

### ISSUE THREAD

**Issue by zz5678** [Fndroid/clash_for_windows_pkg#1588]
ver 0.14.3
CFW 重装了，还是看不到。日志也没有显示。
在这里看到有截图，看来还是有这个东东的。
https://github.com/Fndroid/clash_for_windows_pkg/issues/1440

但目前来看，设置里也没有如上 issue 的截图里的部分：
![image](https://user-images.githubusercontent.com/67672527/106821046-6a18f180-66b7-11eb-94f6-5229f12a6edd.png)

**Comment by Fndroid** [comment]
win和mac不一样

**Comment by zz5678** [comment]
也就是说，macos 上的CFW根本就没有 tray / bar？这用起来还是真的很不方便啊。

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/106853603-f269b780-66f4-11eb-921f-e3cb70a1d4e4.png)
本来就有，默认就会显示一个图标

**Comment by zz5678** [comment]
那就是出bug了，又重装了一次CFW，还是没这个猫 icon
再重启了 mac，这个猫终于出来了，但还是没有 tray speed
截图里，猫旁边是另外一个软件的 net speed
![image](https://user-images.githubusercontent.com/67672527/106865876-bb9c9d00-6706-11eb-8e2a-44aa1024a41c.png)

**Comment by zz5678** [comment]
又点了几次猫 icon，这个speed tray 也终于出来了 :joy: :joy: :joy:
好怪异的bug啊
