### ISSUE TITLE
ipv6开关打开后，会自己关闭

### ISSUE THREAD

**Issue by DockerCS** [Fndroid/clash_for_windows_pkg#1592]
ipv6开关打开后，关闭cfw窗口后，再打开cfw，显示ipv6的开关是关闭的，但是config.yaml里面ipv6还是等于true

系统：Windows 10 20H2
cfw版本：0.14.4

**Comment by DockerCS** [comment]
未必是我系统问题，刚刚cfw又自己打开了ipv6开关，真见鬼了

**Comment by returnL** [comment]
我也遇到了这个问题
系统：Windows 10 20H2
CFW版本：0.14.4

**Comment by AssICan** [comment]
似乎是需要手动重启CFW

**Comment by Fndroid** [comment]
https://github.com/Dreamacro/clash/pull/1217

**Comment by Marukon** [comment]
多开关几次就好了

**Comment by lc6464** [comment]
我也遇到了这个问题
系统：`Windows 10 20H2`
CFW 版本：`0.14.4`

目前临时解决方案，打开 IPv6 开关后什么都不要做，退出 CFW，然后启动 CFW，就正常了。

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
