### ISSUE TITLE
不要脸的来提一个蜜汁需求

### ISSUE THREAD

**Issue by asdfj2381k** [Fndroid/clash_for_windows_pkg#1594]
我给一些朋友装了clash，方便他们看youtube。 

但是又怕他们把clash整个拷贝走，产生不好的影响。 【当然了，这个问题也存在原版shadowsocks中】

有什么办法能让节点信息不外泄呢？  （经过复制后无法正常使用，或给clash上个锁）

**Comment by yi-Xu-0100** [comment]
@asdfj2381k 我一般是让我朋友自己去买节点

**Comment by nemo2018** [comment]
对啊，用clash一般是用机场的，这不符合机场一般规则。建议朋友自己买机场。

**Comment by iBug** [comment]
如果你用的是安装版的话，节点信息是存在 `%UserProfile%` 里的，直接把安装程序拷走是肯定不带节点信息的
