### ISSUE TITLE
Windows Defender 认为 v0.14.4 版本安装程序和升级程序有威胁

### ISSUE THREAD

**Issue by steven756284184** [Fndroid/clash_for_windows_pkg#1595]
[//]: # (如不按模版填写，则issue将被直接关闭)

**Windows Defender 认为 v0.14.4 版本安装程序和升级程序有威胁**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 Pro 20H2

**描述**

Windows Defender 认为 v0.14.4 版本安装程序和升级程序有威胁

**复现**

1. 下载 v0.14.4 的 exe 安装程序并安装。

**预期行为**

Windows Defender 监控程序认为 v0.14.4 版本的安装程序和升级程序有威胁。

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

![updater](https://user-images.githubusercontent.com/43197312/106990336-05d95900-67af-11eb-9eff-90e4ecba9e12.png)

![setup](https://user-images.githubusercontent.com/43197312/106990386-1a1d5600-67af-11eb-82e0-9446be6acfcc.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by grayashlew** [comment]
米兔，同求教。

**Comment by kingforme** [comment]
手动添加排除目录C:\Users\你的用户名\AppData\Local\Programs\Clash for Windows

**Comment by Fndroid** [comment]
我也不清楚是什么意思，要不把安装包提交给他们检测下

**Comment by ac1982** [comment]
> 手动添加排除目录C:\Users\你的用户名\AppData\Local\Programs\Clash for Windows

![image](https://user-images.githubusercontent.com/11901124/107185805-0c213c80-6a1e-11eb-8789-fcdcac707bf8.png)

我主动上传了0.14.4的包，识别有危险。
[Trojan:Script/Wacatac](https://go.microsoft.com/fwlink/p/?linkid=849967&Name=Trojan:Script/Wacatac.C!ml)

**Comment by Fndroid** [comment]
@ac1982 release里没有zip包

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/107190623-fadc2e00-6a25-11eb-925d-d2b72811ab36.png)

**Comment by steven756284184** [comment]
![malwareware](https://user-images.githubusercontent.com/43197312/107190808-3f67c980-6a26-11eb-9e66-25c1716e8c1b.png)

**Comment by aLLeENSmith** [comment]
![image](https://user-images.githubusercontent.com/31880062/107333154-08f68100-6af0-11eb-87d9-f3487692b65d.png)
![image](https://user-images.githubusercontent.com/31880062/107333170-0dbb3500-6af0-11eb-98a7-932f32333eef.png)

我这边卡巴斯基也检测恶意软件；
原因不太清楚。
