### ISSUE TITLE
office软件无法登陆

### ISSUE THREAD

**Issue by mkfd** [Fndroid/clash_for_windows_pkg#16]
开启clash，登陆office软件，例如word，右上角的登陆账户无法登陆，无论规则是proxy还是direct，提示错误error code 0x80190001，关闭clash可登陆。

**Comment by Fndroid** [comment]
部分Windows软件会阻止本地代理，可以参考[这个issue](https://github.com/Fndroid/clash_for_windows_pkg/issues/13#issuecomment-438170552)
