### ISSUE TITLE
断连

### ISSUE THREAD

**Issue by mrliu666666** [Fndroid/clash_for_windows_pkg#160]
为什么有时用着用着突然就断连 ，回去ping的时候全是time out，过几分钟就好了。

**Comment by Fndroid** [comment]
@mrliu666666 可能你断网了、或者你的代理断网了

**Comment by mrliu666666** [comment]
@Fndroid 你说的这两种情况都不是，因为当clash time out的时候，ssr和ss还是正常的

**Comment by Fndroid** [comment]
@mrliu666666 那可能是配置里设置的dns不合适

**Comment by Fndroid** [comment]
配置文件里 dns 字段删掉
