### ISSUE TITLE
"好傻"

### ISSUE THREAD

**Issue by Leyoud** [Fndroid/clash_for_windows_pkg#1602]
_Originally posted by @Leyoud in https://github.com/Fndroid/clash_for_windows_pkg/issues/1598#issuecomment-774634288_

**Comment by yi-Xu-0100** [comment]
@Leyoud 请不要发无关 issue

**Comment by Leyoud** [comment]
> @Leyoud请不要发无关问题

Sorry，无意点到的，才发现！
