### ISSUE TITLE
macOS版本，可以增加配置提升启动体验

### ISSUE THREAD

**Issue by yhl452493373** [Fndroid/clash_for_windows_pkg#1603]
**描述**
在plist中dict下，增加
```xml
<key>LSUIElement</key>
<true/>
```
应用启动时，就不会再在dock栏上闪一下在消失

**其他说明**
无

**Comment by Fndroid** [comment]
感谢建议，下个版本加上😄

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases

**Comment by Fndroid** [comment]
感谢感谢哈
