### ISSUE TITLE
希望能增加绑定到指定网卡以供 wsl2 使用代理

### ISSUE THREAD

**Issue by yjh1021317464** [Fndroid/clash_for_windows_pkg#1607]
**描述**
希望在 allow LAN 之外增加一个绑定 inbound 到指定网卡的功能，我电脑有公网 IP，同时需要在 wsl2 内使用代理，现在只能开启 allow LAN, 有安全风险。

**其他说明**
无

**Comment by Fndroid** [comment]
```
bind-address: 192.168.50.1
```

**Comment by yjh1021317464** [comment]
> ```
> bind-address: 192.168.50.1
> ```
> 
> home directory的config.yaml里加上绑定的地址，然后重启app

wsl2 的地址每次开机都不一样。。。况且这种方法 windows 下就没法访问了

**Comment by Fndroid** [comment]
那就给port加auth

**Comment by yjh1021317464** [comment]
> 那就给port加auth

行吧，也不是不可以

**Comment by qinywolf** [comment]
> > 那就给port加auth
> 
> 行吧，也不是不可以

可以使用[Tun模式](https://docs.cfw.lbyczf.com/contents/tun.html)，WSL2无需配置就可以走代理了。
另外，你有公网IP，也需要路由器映射内网端口地址外网才可以访问到，你完全不需要担心安全问题。
