### ISSUE TITLE
0.14.5 被 Windows Defender 报毒

### ISSUE THREAD

**Issue by lydasia** [Fndroid/clash_for_windows_pkg#1611]
**描述**
请具体并清楚地描述期望功能及期望的效果

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
![Uploading image.png…]()

**Comment by lydasia** [comment]
![image](https://user-images.githubusercontent.com/22676960/107627280-05066280-6c9a-11eb-924f-c5d27b77d624.png)
