### ISSUE TITLE
请问最新版(0.14.5)节点的延迟测试结果是否显示有问题

### ISSUE THREAD

**Issue by LeslieYon** [Fndroid/clash_for_windows_pkg#1612]
Windows最新版节点的延迟测试结果是否显示有问题？
点击测速后结果不会立即显示，只有在任意切换节点后才会正常显示
麻烦大佬给排查一下

**Comment by asdfj2381k** [comment]
其实可以找个QA做合伙人，让他免费帮忙写点自动化测试的脚本。

**Comment by zz5678** [comment]
不止win版本，mac版本也错乱了，0.14.5版本测试节点不会在测试当前窗口显示，要切换到其他窗口再切回来，但会打断整个测试过程。

**Comment by zz5678** [comment]
另外，希望作者能改一下，保持测速的数据时间长一些，目前是几个小时（没发现具体规律）就消失了，再测并不科学啊。

**Comment by CZY3434123** [comment]
确实有此类问题

**Comment by zz5678** [comment]
mac 上使用，0.14.6 新版还是有卡死界面的问题，标志之一是左下角的 connected 上的秒表会卡住不动 5-30 秒不等，有时候还无法滚动窗口。

而且还是会过几个小时（未知具体是多少时间，大概1-2小时）测试数据就会重置消失 -- 这个烦请作者还是改改吧，太不人道了 :skull::skull::skull:
