### ISSUE TITLE
0.14.5版更新后TAP模式无法使用

### ISSUE THREAD

**Issue by bigbaldy1128** [Fndroid/clash_for_windows_pkg#1613]
**信息**
- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
win10

**描述**
更新0.14.5版后TAP模式无法使用，TAP网卡上面画着一个红叉，还原回0.14.4后就好了

**Comment by Jed-Z** [comment]
请查看更新日志

**Comment by falloutxxx2** [comment]
> 请查看更新日志

是不是用这个的都是程序员啊 我反正看不懂 prevent interface-name being filled when TAP device not installed(Windows) 是什么意思。。。。

**Comment by yi-Xu-0100** [comment]
> > 请查看更新日志
> 
> 是不是用这个的都是程序员啊 我反正看不懂 prevent interface-name being filled when TAP device not installed(Windows) 是什么意思。。。。
> 
> 
> 

在Windows系统上，不要在未安装TAP设备时填写 interface-name。

**Comment by bigbaldy1128** [comment]
> 请查看更新日志

看了，我0.14.4能用TAP模式说明我肯定是安装了TAP设备了，而且interface-name我也没写

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/108008568-9d566b80-703b-11eb-9052-c58b6799e5c9.jpeg)
