### ISSUE TITLE
使用 mixin 方式开启 tun 模式时 报network err

### ISSUE THREAD

**Issue by Weibin74** [Fndroid/clash_for_windows_pkg#1614]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 专业版 Insider Preview

[//]: # (平台及版本号)

- 平台:  amd64
- 版本号: Windows Feature Experience Pack 221.501.0.3

**描述**

![image](https://user-images.githubusercontent.com/24431872/107873895-be5e7580-6ef0-11eb-8c29-affcb33f4abf.png)  

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

**预期行为**

**日志**

[//]: # (上传触发问题对应的日志文件)
2021/02/14 17:54:13 http: panic serving 127.0.0.1:54199: The specified module could not be found.
goroutine 67 [running]:
net/http.(*conn).serve.func1(0xc0002aa000)
	net/http/server.go:1801 +0x147
panic(0xabccc0, 0x103d770)
	runtime/panic.go:975 +0x499
golang.org/x/sys/windows.(*LazyProc).mustFind(...)
	golang.org/x/sys@v0.0.0-20210124154548-22da62e12c0c/windows/dll_windows.go:325
golang.org/x/sys/windows.(*LazyProc).Addr(...)
	golang.org/x/sys@v0.0.0-20210124154548-22da62e12c0c/windows/dll_windows.go:333
github.com/Dreamacro/clash/proxy/device/wintun.loadDLL.func1()
	github.com/Dreamacro/clash/proxy/device/wintun/wintun.go:58 +0x11e
sync.(*Once).doSlow(0xc0000310b0, 0xbac938)
	sync/once.go:66 +0xf7
sync.(*Once).Do(...)
	sync/once.go:57
github.com/Dreamacro/clash/proxy/device/wintun.loadDLL()
	github.com/Dreamacro/clash/proxy/device/wintun/wintun.go:55 +0x50
github.com/Dreamacro/clash/proxy/device/wintun.MakePool(0xb70457, 0x5, 0xc00004f080, 0xc0001db268, 0x346129)
	github.com/Dreamacro/clash/proxy/device/wintun/wintun.go:66 +0x2d
github.com/Dreamacro/clash/proxy/device.getWinPool.func1()
	github.com/Dreamacro/clash/proxy/device/tun_windows.go:61 +0x45
sync.(*Once).doSlow(0xc0000310c0, 0xbac918)
	sync/once.go:66 +0xf7
sync.(*Once).Do(...)
	sync/once.go:57
github.com/Dreamacro/clash/proxy/device.getWinPool(0x79eddb)
	github.com/Dreamacro/clash/proxy/device/tun_windows.go:59 +0x5c
github.com/Dreamacro/clash/proxy/device.CreateTUNWithRequestedGUID(0xb70457, 0x5, 0xc00393f450, 0x2328, 0x1, 0xa820c0, 0x20, 0x20)
	github.com/Dreamacro/clash/proxy/device/tun_windows.go:117 +0x3b
github.com/Dreamacro/clash/proxy/device.CreateTUN(0xb70457, 0x5, 0x2328, 0xc0001db3dc, 0x4, 0x4, 0xc004a46b80)
	github.com/Dreamacro/clash/proxy/device/tun_windows.go:106 +0x154
github.com/Dreamacro/clash/proxy/tun.NewTunProxy(0xc0053d9710, 0xc004a46c20, 0x3, 0x4, 0x3, 0xc004a46c20, 0x2)
	github.com/Dreamacro/clash/proxy/tun/adapter.go:271 +0xb2
github.com/Dreamacro/clash/proxy.ReCreateTun(0x1, 0xc0053d9710, 0xc000313038, 0x6, 0x101, 0x10bccd8, 0x0, 0x0, 0xc003a87530, 0x1, ...)
	github.com/Dreamacro/clash/proxy/listener.go:233 +0x5ea
github.com/Dreamacro/clash/hub/executor.updateTun(0xc000334d00)
	github.com/Dreamacro/clash/hub/executor/executor.go:133 +0x1f8
github.com/Dreamacro/clash/hub/executor.ApplyConfig(0xc000334d00, 0x1300)
	github.com/Dreamacro/clash/hub/executor/executor.go:73 +0x113
github.com/Dreamacro/clash/hub/route.updateConfigs(0xc65160, 0xc0003320e0, 0xc00031e400)
	github.com/Dreamacro/clash/hub/route/configs.go:124 +0x16d
net/http.HandlerFunc.ServeHTTP(0xbac8e8, 0xc65160, 0xc0003320e0, 0xc00031e400)
	net/http/server.go:2042 +0x4b
github.com/go-chi/chi.(*Mux).routeHTTP(0xc000064840, 0xc65160, 0xc0003320e0, 0xc00031e400)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x28b
net/http.HandlerFunc.ServeHTTP(0xc00005baf0, 0xc65160, 0xc0003320e0, 0xc00031e400)
	net/http/server.go:2042 +0x4b
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc000064840, 0xc65160, 0xc0003320e0, 0xc00031e400)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:70 +0x50c
github.com/go-chi/chi.(*Mux).Mount.func1(0xc65160, 0xc0003320e0, 0xc00031e400)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:298 +0x122
net/http.HandlerFunc.ServeHTTP(0xc000005800, 0xc65160, 0xc0003320e0, 0xc00031e400)
	net/http/server.go:2042 +0x4b
github.com/Dreamacro/clash/hub/route.authentication.func1(0xc65160, 0xc0003320e0, 0xc00031e400)
	github.com/Dreamacro/clash/hub/route/server.go:96 +0x3f3
net/http.HandlerFunc.ServeHTTP(0xc000005820, 0xc65160, 0xc0003320e0, 0xc00031e400)
	net/http/server.go:2042 +0x4b
github.com/go-chi/chi.(*ChainHandler).ServeHTTP(0xc000038f00, 0xc65160, 0xc0003320e0, 0xc00031e400)
	github.com/go-chi/chi@v4.1.2+incompatible/chain.go:31 +0x59
github.com/go-chi/chi.(*Mux).routeHTTP(0xc000064780, 0xc65160, 0xc0003320e0, 0xc00031e400)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x28b
net/http.HandlerFunc.ServeHTTP(0xc00005ba90, 0xc65160, 0xc0003320e0, 0xc00031e400)
	net/http/server.go:2042 +0x4b
github.com/go-chi/cors.(*Cors).Handler.func1(0xc65160, 0xc0003320e0, 0xc00031e400)
	github.com/go-chi/cors@v1.1.1/cors.go:228 +0x1c6
net/http.HandlerFunc.ServeHTTP(0xc0000056a0, 0xc65160, 0xc0003320e0, 0xc00031e400)
	net/http/server.go:2042 +0x4b
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc000064780, 0xc65160, 0xc0003320e0, 0xc00031e300)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:86 +0x2d1
net/http.serverHandler.ServeHTTP(0xc0001d0000, 0xc65160, 0xc0003320e0, 0xc00031e300)
	net/http/server.go:2843 +0xaa
net/http.(*conn).serve(0xc0002aa000, 0xc662a0, 0xc000286040)
	net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	net/http/server.go:2969 +0x36d

**其他说明**

[//]: # (其他补充内容)
将 mixin 部分配置直接写入配置则不会报错

**Comment by yi-Xu-0100** [comment]
@Weibin74 是不是 tun 部分删除就好使？wintun.dll 有没有下载放入 home directory ？

**Comment by yi-Xu-0100** [comment]
@Weibin74 

![image](https://user-images.githubusercontent.com/25523606/107874201-d3d49f00-6ef2-11eb-917d-9564d91a2bcf.png)

**Comment by Fndroid** [comment]
dll下载错了或者没有下载

**Comment by Weibin74** [comment]
解决了
