### ISSUE TITLE
他似乎只能代理我电脑上的edge浏览器

### ISSUE THREAD

**Issue by Kingstom8MB** [Fndroid/clash_for_windows_pkg#1616]
点击系统代理后，
![image](https://user-images.githubusercontent.com/50566074/107875568-b952f380-6efb-11eb-8eca-c176a8b22e08.png)只有我的edge浏览器可以访问Google
![image](https://user-images.githubusercontent.com/50566074/107875590-d4256800-6efb-11eb-8a30-edc0b1380237.png)
其他浏览器，我电脑上还有火狐和谷歌浏览器，都无法访问谷歌
![image](https://user-images.githubusercontent.com/50566074/107875605-e99a9200-6efb-11eb-8bdd-9b0b5a263217.png)
CMD的pip指令也无法代理
![image](https://user-images.githubusercontent.com/50566074/107875686-5150dd00-6efc-11eb-87e2-82a5d02bdfed.png)
同一条安装指令，上面那个没找到包的是打开代理后的，下面那个低速的是关闭代理后的结果，两个包名是一样的，但是没法打开代理后就没法直接下载
想问一下有没有人遇到过这种问题，我没做其他设置，下载好配置后
![image](https://user-images.githubusercontent.com/50566074/107875727-996fff80-6efc-11eb-95c9-937645c5f134.png)
就直接点击代理了，就这样不知道怎么解决

**Comment by yi-Xu-0100** [comment]
1. 浏览器不要使用插件，可以在设置中找”代理“，如果是使用的系统代理才是对的，如果谷歌浏览器还是无法连接，建议查看访问时的日志记录。
2. 第二个你是怎么配置终端代理部分？如果没有配置，试试在设置中切换为 PAC 试试

**Comment by Kingstom8MB** [comment]
> 1. 浏览器不要使用插件，可以在设置中找”代理“，如果是使用的系统代理才是对的，如果谷歌浏览器还是无法连接，建议查看访问时的日志记录。也可以直接在谷歌浏览器的无痕模式尝试是否能否访问
> 2. 第二个你是怎么配置终端代理部分？如果没有配置，试试在设置中切换为 PAC 试试

诶，他好像可以了，我换成pac后谷歌和火狐行了，CMD也可以了，非常感谢，我用两天试试会不会出问题
另外问一下，你第一条里的插件是指浏览器拓展里的插件吗？代理设置也是浏览器里的设置吗？

**Comment by yi-Xu-0100** [comment]
@Kingstom8MB 是的，默认浏览器走系统代理，如果有其他插件接管了，就可能出现问题，需要确保代理走了 clash

**Comment by Kingstom8MB** [comment]
@yi-Xu-0100 了解了，非常感谢你的解答
