### ISSUE TITLE
无法连接

### ISSUE THREAD

**Issue by lyrica147** [Fndroid/clash_for_windows_pkg#1617]
使用V2RAYN和CLASH都无法科学上网，但是国内的网站都可以正常使用，都是跟着教程走的，所有的设置都没有问题，每个浏览器都无法使用，不知道具体是什么问题

**Comment by yi-Xu-0100** [comment]
@lyrica147 给出日志，或者给出你使用的教程和步骤，视频演示也行

**Comment by akw5454521** [comment]
两个完全不同的软件都不能用，那说明不是软件的问题
