### ISSUE TITLE
Mac M1

### ISSUE THREAD

**Issue by nightmare30** [Fndroid/clash_for_windows_pkg#1618]
请问是否计划适配Mac M1

**Comment by kingforme** [comment]
使用clashX

**Comment by Fndroid** [comment]
已经在适配了，但是没有测试机器，想测试的把telegram账号发我邮箱我发安装包

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
