### ISSUE TITLE
Windows TUN模式下无法连接代理服务器，电脑也无法上网。

### ISSUE THREAD

**Issue by xyqyear** [Fndroid/clash_for_windows_pkg#1621]
**信息**

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 19042

**描述**

Windows10下开启TUN模式，无法连接到互联网，日志里显示无法连接代理服务器。不使用TUN模式可以正常连接。

**复现**

- 复制wintun.dll文件到Home Dir
- 复制wiki中tun的配置文件到mixin配置中
- 安装Service Mode
- 开启Mixin

**预期行为**

连接TUN模式可以正常上网。

**日志**

[2021-02-16-113017.log](https://github.com/Fndroid/clash_for_windows_pkg/files/5985964/2021-02-16-113017.log)

**截图**

![image](https://user-images.githubusercontent.com/29950788/108016119-c501ff80-704c-11eb-9171-c46d92cdea93.png)

![image](https://user-images.githubusercontent.com/29950788/108016130-c9c6b380-704c-11eb-9718-163c4aad2926.png)

![image](https://user-images.githubusercontent.com/29950788/108016258-0d212200-704d-11eb-9f26-53beb19dd74b.png)

**其他说明**

无论是手动指定interface-name还是自动检测都无法连接。

部分配置文件: 
[config.txt](https://github.com/Fndroid/clash_for_windows_pkg/files/5985993/config.txt)

**Comment by Fndroid** [comment]
什么型号的网卡

**Comment by xyqyear** [comment]
> 什么型号的网卡

Killer E2500

**Comment by kingforme** [comment]
#1243

**Comment by xyqyear** [comment]
> #1243

已解决，感谢。
