### ISSUE TITLE
建议增加从粘贴板导入配置并内置一些规则

### ISSUE THREAD

**Issue by Moriarty6086** [Fndroid/clash_for_windows_pkg#1623]
**描述**
建议增加从粘贴板导入配置，并内置一些规则。
从实践上看，很多节点经过转换后再导入clash，会导致节点失效无法使用(tinme out)
但如果尝试用clash内置的功能：手动添加单个配置，会出现无法识别节点的情况像(ss,ssr)
但是这些节点，却可以用相同的方式添加到其他客户端，并且可用
并且我的添加方式应该无误

**Comment by yi-Xu-0100** [comment]
1. "从粘贴板导入配置，并内置一些规则" 本质上和 “经过转换后再导入clash” 没有区别，建议排查个人配置文件。
2. 手动添加单个配置，会出现无法识别节点的情况像(ss,ssr)， 这个无法识别是啥意思，报啥错误了？
3. 可以用相同的方式添加到其他客户端，并且可用的话，可以直接换用其他客户端滴，话说，为啥大家会觉得作者用了 CFW 还会用其他的？🤣

**Comment by akw5454521** [comment]
节点：那就直接编辑配置文件，也就是复制粘贴6、7行的事，再调整下格式就完了
以及，你要是复制了确定完整的配置文件，那就直接粘贴替换配置文件

**Comment by Fndroid** [comment]
如果要编辑节点，建议先了解下YAML
