### ISSUE TITLE
关于使用Rule Providers后的connections和Proxy Providers

### ISSUE THREAD

**Issue by jenniferak** [Fndroid/clash_for_windows_pkg#1624]
1.在使用rule-providers后，Connection Info的Rule一栏只显示RuleSet，希望可以把匹配到规则的provider名称以及规则的类型显示出来，例如RuleSet(Global)-DomainSuffix，RuleSet(Game)-Process。

2.在使用proxy-providers时，如果设置为
    health-check:
      enable: false
那么在Proxies页面对应的策略组中，单个节点将没有check按钮，不能单节点测速，只能先把全组测一次，再测单个节点，希望可以加上check按钮。

**Comment by yi-Xu-0100** [comment]
第一个好像是官方的 clash 的 api 没有提供的问题，建议去 core issue: <https://github.com/Dreamacro/clash/issues> 提出

**Comment by jenniferak** [comment]
> 第一个好像是官方的 clash 的 api 没有提供的问题，建议去 core issue: https://github.com/Dreamacro/clash/issues 提出

**Comment by Fndroid** [comment]
这两个问题，目前core都没有提供相应的API
