### ISSUE TITLE
Update更新失败

### ISSUE THREAD

**Issue by jalena** [Fndroid/clash_for_windows_pkg#1626]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Microsoft Windows 10 专业版
10.0.19042 暂缺 Build 19042

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
使用自动更新update选项，在程序下载完成更新过程中，因主程序未能杀死，导致主程序占用而更新失败。
**复现**

[//]: # (请描述复现问题的步骤)
略

**预期行为**
成功更新

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by kingforme** [comment]
手动下载安装包覆盖安装

**Comment by Fndroid** [comment]
如果旧版本安装时选择了”为所有用户安装“，那么自动安装将会因权限问题而失败，后续版本将会禁止直接Update，请手动下载安装更新

**Comment by zwwskm** [comment]
> 如果旧版本安装时选择了”为所有用户安装“，那么自动安装将会因权限问题而失败，后续版本将会禁止直接Update，请手动下载安装更新

请问如何改变权限的设置呢？完全卸载软件后，重新进行仅为自己安装，软件内有update选项，但仍然无法杀死主程序，更新过程无限循环。还有哪里需要更改吗？万分感谢！

**Comment by yi-Xu-0100** [comment]
@zwwskm 新版本应该没事，无限循环是？

**Comment by zwwskm** [comment]
> @zwwskm 新版本应该没事，无限循环是？

就是在线更新时无法杀死主程序，更新完了以后主程序的版本还是旧的，然后判定更新失败再次静默运行安装程序，会一直这样重复。而且本来重装在其他磁盘，这样静默的安装最后会安到C盘里，而且原来主程序的文件因为被正在占用，不会被卸载程序自动删除。
