### ISSUE TITLE
更新失败,安装包在什么位置?

### ISSUE THREAD

**Issue by RiotGamesU** [Fndroid/clash_for_windows_pkg#1628]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

win10

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

从上个版本在线更新这个版本,下载完安装包点击安装之后显示失败,文件正在被使用,请问下载的安装文件在哪里,我想删除

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
Temp目录

**Comment by RiotGamesU** [comment]
> Temp目录

在C:\Users\UserName\AppData\Local\Temp下找到了,谢谢
