### ISSUE TITLE
Allow LAN扶墙速度慢

### ISSUE THREAD

**Issue by BruceDeng619** [Fndroid/clash_for_windows_pkg#1629]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)win10 CFW 0.14.5

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
笔记本上开启Allow Lan，配置好手机的WiFi，可以正常扶墙，但是下行速度很慢，只有使用手机端Clash的十分之一左右

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)
下行速度能达到使用手机端Clash的水平

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
Allow LAN只是监听在局域网里。和PC本地连接是一样的。

**Comment by BruceDeng619** [comment]
本人小白，还望进一步解释。适应这种方法最直观的感受就是google play store下载速度很慢，完全达不到手机上开启clash的速度。

**Comment by BruceDeng619** [comment]
> Allow LAN只是监听在局域网里。和PC本地连接是一样的。

本人小白，还望进一步解释。适应这种方法最直观的感受就是google play store下载速度很慢，完全达不到手机上开启clash的速度。

**Comment by yi-Xu-0100** [comment]
@BruceDeng619 同一个 WiFi 下，同一个节点？

**Comment by BruceDeng619** [comment]
> @BruceDeng619 同一个 WiFi 下，同一个节点？

是的。我觉得可能会是硬件的问题？我电脑上插的是腾达的双频usb无线网卡。然后我用安卓手机运行v2ray，打开allow lan，电脑端配置wifi，速度就会快一些，但还是没有各自运行软件跑的速度快。
