### ISSUE TITLE
有考虑中文语言吗？

### ISSUE THREAD

**Issue by fjj739964256** [Fndroid/clash_for_windows_pkg#163]
have you considered about the Chinese version?

**Comment by Fndroid** [comment]
@fjj739964256 不考虑

**Comment by fjj739964256** [comment]
ok

发送自 Windows 10 版邮件应用

发件人: Fndroid
发送时间: 2019年8月16日 PM 01:13
收件人: Fndroid/clash_for_windows_pkg
抄送: fjj739964256; Mention
主题: Re: [Fndroid/clash_for_windows_pkg] 有考虑中文语言吗？ (#163)

@fjj739964256 不考虑

**Comment by wanlimua** [comment]
作者说过不考虑，我怎么老收到邮件

发自我的iPhone

在 2019年8月20日，下午3:57，Fndroid <notifications@github.com> 写道：

﻿

Closed #163<https://github.com/Fndroid/clash_for_windows_pkg/issues/163>.
