### ISSUE TITLE
0.14.6 把ESC键给控制了，别的软件无法正常使用ESC键了。

### ISSUE THREAD

**Issue by asdfj2381k** [Fndroid/clash_for_windows_pkg#1630]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [√ ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [√ ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ √] 已经尝试更新到最新版本，问题依旧存在
- [√ ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**[//]: # (平台及版本号)
win7 x64

[//]: # (请描述复现问题的步骤)

同时打开微信电脑版和clash，   由微信获得窗口焦点（微信放在前面，clash放在后面），然后按一下ESC。  结果关闭掉的居然是clash

**Comment by asdfj2381k** [comment]
clash截取esc的优先级太高了， 导致别的所有的软件都响应不了esc。

希望可以紧急发个版本修复，太难受了。

**Comment by Fndroid** [comment]
重新下载安装包覆盖安装一下

**Comment by asdfj2381k** [comment]
@Fndroid  F大，我就是覆盖安装的。            虽然你们说好像可以自动update？ 但是我没发现这个功能在哪里      o(╥﹏╥)o

**Comment by lvlvxv** [comment]
我是把之前的版本卸载了装的新版本，现在也不能在别的软件里面使用ESC键

**Comment by Fndroid** [comment]
@lvlvxv 重启一下电脑

**Comment by Fndroid** [comment]
> @Fndroid F大，我就是覆盖安装的。 虽然你们说好像可以自动update？ 但是我没发现这个功能在哪里 o(╥﹏╥)o

重新下载安装包了么

**Comment by asdfj2381k** [comment]
@Fndroid    刚刚（1分钟前）， 重新下载安装包，解决问题了.

看了一下MD5，和上午发的不一样了。     修好就行。  (#^.^#)
