### ISSUE TITLE
主界面持续loading，左下角提示disconnected

### ISSUE THREAD

**Issue by NobuYuki1027** [Fndroid/clash_for_windows_pkg#1631]
日志里只有一行
time="2021-02-19T14:04:46+08:00" level=fatal msg="Parse config error: yaml: control characters are not allowed"
昨天还能用，今天就不行了，降级升级都试过了

**Comment by NobuYuki1027** [comment]
已解决

**Comment by asmallbit** [comment]
> 已解决

可否告知一下您的解决方法?

**Comment by jingkeling** [comment]
> 已解决

你好，怎么解决的

**Comment by davidCybrook** [comment]
遇到同样的问题，每天动不动就出这个错误。

**Comment by chen-ccy** [comment]
刚才解决了，C盘用户文件下的\.config\clash的config.yaml文件错误了，内容正确就没问题了
