### ISSUE TITLE
0.14.4开始无法对主菜单进行重排序

### ISSUE THREAD

**Issue by lukewarmthee** [Fndroid/clash_for_windows_pkg#1633]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows10 X64

**描述**

我用的是便携版,自从0.14.4开始就无法对主菜单重排序了,0.14.3是可以的,删除了.config中的clash文件夹重启依旧不行,刚刚我尝试了最新的安装版,同样也是不行,大家有没有这个问题呢
![image](https://user-images.githubusercontent.com/74102866/108502428-bdad5100-72ed-11eb-82dc-029b60242f46.png)

**Comment by yi-Xu-0100** [comment]
左键长按试试

**Comment by lukewarmthee** [comment]
> 左键长按试试

还是不行嘿

**Comment by lukewarmthee** [comment]
> 左键长按试试

啊可以了,我误会了长按的意思,超级感谢
