### ISSUE TITLE
0.14.6更新后clash强制占用esc

### ISSUE THREAD

**Issue by YehowahLiu** [Fndroid/clash_for_windows_pkg#1634]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
[//]: # (平台及版本号)
Windows 10 Pro 20H2 
OS build: 19042.804

**描述**
[//]: # (请具体并清楚地描述遇到的问题)
更新到最新版本的cfw后，其余软件无法检测到esc键，比如qq聊天界面按esc无法关闭当前聊天窗口、mc游戏内无法通过按esc触发选项，在关闭cfw后恢复正常

**复现**

[//]: # (请描述复现问题的步骤)

1. cfw更新到最新版本
2. 打开qq聊天界面（或其他能够识别esc的窗口
3. 按下esc键

**预期行为**
[//]: # (清晰地描述期望看到的行为)
正常触发其他软件的esc功能

**日志**
[//]: # (上传触发问题对应的日志文件)
无

**截图**
[//]: # (如果可以，请提供对应问题的截图)
无

**其他说明**
[//]: # (其他补充内容)
已尝试重启电脑，无法解决问题；
ctrl+shift+esc可正常触发任务管理器

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/1630
