### ISSUE TITLE
关于新增ESC快速关闭窗口与其他软件冲突的问题

### ISSUE THREAD

**Issue by hope140** [Fndroid/clash_for_windows_pkg#1635]
**描述**
新增的ESC退出功能，即便是快速关闭后，依然在监听esc
使得比如我正使用的utools（esc同样是快速关闭）的esc无法正常使用
当使用force quit的方法关闭gui时，esc可以使用
能否使esc在关闭窗口后不再被监听
**其他说明**
顺便问一下能不能多加一些自定义快捷键，感谢

**Comment by yi-Xu-0100** [comment]
重新安装

**Comment by Fndroid** [comment]
重新下载一个安装

**Comment by hope140** [comment]
确实新下载一个就好了，但是我一直都是github下安装包更新啊

**Comment by yi-Xu-0100** [comment]
重发了一下

**Comment by hope140** [comment]
哦哦，谢谢，这次更新关注太过及时了哈哈
