### ISSUE TITLE
system proxy 自动关闭

### ISSUE THREAD

**Issue by sky31even** [Fndroid/clash_for_windows_pkg#164]
更新了0.7.3发现的，打开了没一会之后，system proxy就变成自动关闭状态，甚至有时候我一直停留在clash界面，只是不停切换左侧的功能tab，一会就会发现它给自动关闭了。。。。
![image](https://user-images.githubusercontent.com/49628447/63150292-04572680-c039-11e9-97cd-6302313f844f.png)

**Comment by Fndroid** [comment]
@sky31even 检查下是不是有其他程序也会修改这个地方

**Comment by sky31even** [comment]
没装其他app= =不知道咋回事，用https://docs.cfw.lbyczf.com/ban-ben-chang-jian-wen-ti 这里面的清除系统设置后好像正常了

**Comment by JamesQFreeman** [comment]
怎么检查下是不是有其他程序也会修改这个地方？
