### ISSUE TITLE
更新到v0.14.6后，电脑的esc按键失效了

### ISSUE THREAD

**Issue by RupingLiu** [Fndroid/clash_for_windows_pkg#1641]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
电脑型号是matebook x，系统版本20H2  19042.804
**描述**
打开了CFW后，esc按键会失效，具体表现为中文输入法下，候选框下，无法按esc按键取消输入，关闭CFW后，则正常了。
**复现**

[//]: # (请描述复现问题的步骤)

1. 打开CFW
2. 使用中文输入法
3. 输入拼音至出现候选框
4. 这时候，按ESC按键，无法取消候选框

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
重新下载安装

**Comment by Wolf1329** [comment]
问题同上 更新到v0.14.6后 Counter-Strike Online 游戏中无法通过ESC按键退出了,退出CFW后正常

**Comment by yi-Xu-0100** [comment]
Duplicate of #1635 #1634 #1630
