### ISSUE TITLE
Mac 下托盘图标，能否展示是否开启或者关闭 System Proxy

### ISSUE THREAD

**Issue by Kaijun** [Fndroid/clash_for_windows_pkg#1642]
**描述**
Mac 下托盘图标，能否展示是否开启或者关闭 System Proxy?

当前无法很好区分代理是否开启，希望可以支持一下

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
