### ISSUE TITLE
cfw 开启之后会把系统的代理打开,导致速度很慢

### ISSUE THREAD

**Issue by Escher1108** [Fndroid/clash_for_windows_pkg#1643]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

window 10 专业版 | cfw 0.14.6

**描述**
貌似自从cfw 0.10以后，cfw 开启代理会打开系统的代理功能，即127.0.0.1:7980，然后我的节点规则是国内直连，但是，访问国内站点很慢，国外站点不受影响。

[//]: # (请具体并清楚地描述遇到的问题)
除了以上行为，还会存在断流，需要关闭代理重新启用

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
开启cfw 代理，不开启系统自己的代理设置

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**
<a href="https://sm.ms/image/CfigYGZ95KA8bWB" target="_blank"><img src="https://i.loli.net/2021/02/22/CfigYGZ95KA8bWB.png" /></a>

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**
能不能开启代理，不打开系统自己的代理?或者有什么方法解决？v2win不存在这个问题，但是喜欢cfw

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
General里System Proxy关掉

**Comment by Escher1108** [comment]
> General里System Proxy关掉

关掉之后系统的代理也跟着关掉，如果是关掉系统的代理，cfw 的System Proxy 也会被关掉，他们是相通的，关掉之后就无法使用代理功能了

**Comment by Fndroid** [comment]
那你到底想怎样呢

**Comment by Escher1108** [comment]
> 那你到底想怎样呢
没问题了，已解决
