### ISSUE TITLE
ip instead of hostname in logs and connections

### ISSUE THREAD

**Issue by fsheidaiee** [Fndroid/clash_for_windows_pkg#1647]
Hi
I have set some set of hostnames (domain suffix) to get direct connection in config but when enabling tun mode, all logs are ip numbers and none of these rules to get direct connection on domain suffix work.
this is my tun config;
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 1.1.1.1
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 198.18.0.2:53
  macOS-auto-route: true
  macOS-auto-detect-interface: true

what is the problem?

**Comment by yi-Xu-0100** [comment]
@fsheidaiee Try to add more `nameserver` for it.

**Comment by ygsk10** [comment]
remove this line

```yaml
listen: 0.0.0.0:53
```

**Comment by fsheidaiee** [comment]
> @fsheidaiee Try to add more `nameserver` for it.

thanks
it worked.
