### ISSUE TITLE
能否增加语言包，出中文版

### ISSUE THREAD

**Issue by liuluanming** [Fndroid/clash_for_windows_pkg#1653]
**描述**
英语不好的渣渣，用起来略蛋疼。。请问能否增加中文语言包，麻烦您了。

**其他说明**
其他补充内容

**Comment by yi-Xu-0100** [comment]
Duplicate of #999

**Comment by gbaoye** [comment]
李子柒在YouTube很久了，一个闭源的软件，为中国制作的软件却不支持中文
