### ISSUE TITLE
如何开启PAC模式，封闭的软件全局代理是否合适

### ISSUE THREAD

**Issue by gbaoye** [Fndroid/clash_for_windows_pkg#1655]
**描述**
PAC自动代理

**其他说明**
添加功能开关

**Comment by Fndroid** [comment]
就几个字，我都猜不到你想表达什么意思

**Comment by gbaoye** [comment]
> 就几个字，我都猜不到你想表达什么意思

你是不是，中文起诉

**Comment by gbaoye** [comment]
> 就几个字，我都猜不到你想表达什么意思

你是不是，中文歧视

**Comment by yi-Xu-0100** [comment]
PAC 是按规则选择是否走特定代理，全局代理是 clash 提供代理模式的一种，可以看下 #1532 ，其他的建议换软件。
