### ISSUE TITLE
勾选了Ipv6 浏览器还是无法获取ipv6地址

### ISSUE THREAD

**Issue by luojunyuan** [Fndroid/clash_for_windows_pkg#1656]
浏览器：edge chromium
CFW版本：0.14.6

`config.yaml` 中 ipv6 已经是 true
退出CFW或关闭 `System Proxy` 后 ip.sb 才能获取ipv6地址

**Comment by Fndroid** [comment]
``ip.sb``加了直连规则了吗

**Comment by luojunyuan** [comment]
my bad

**Comment by aidou2014** [comment]
Ipv6的功能需要原本具备ipv6地址吗？
