### ISSUE TITLE
你好，为何rule-autoproxy模式下，访问baidu还是走的本地的7890端口

### ISSUE THREAD

**Issue by M-make** [Fndroid/clash_for_windows_pkg#166]
你好，为何rule-autoproxy模式下，访问baidu还是走的本地的7890端口

**Comment by M-make** [comment]
![image](https://user-images.githubusercontent.com/35563513/63207556-c8849580-c0fa-11e9-851b-9e02f4ba09f3.png)

**Comment by Fndroid** [comment]
不走http怎么进clash里

**Comment by M-make** [comment]
什么鬼。、

**Comment by M-make** [comment]
浏览器是http

**Comment by AaronWong002** [comment]
分流是在进7890以后的事

**Comment by M-make** [comment]
> 分流是在进7890以后的事

好的，也就是说clashx托管了所有的流量，然后根据规则再去判定是否走代理对吧
