### ISSUE TITLE
使用软件内的Update无法升级Clash Core

### ISSUE THREAD

**Issue by returnL** [Fndroid/clash_for_windows_pkg#1660]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 10 20H2

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
在0.14.6版本使用软件内的Update升级至0.14.7，显示的Core Version依旧为2020.12.27（之前安装是仅为我安装）。
卸载后使用安装包重装，Core升级成功，显示为2021.02.19

**Comment by Fndroid** [comment]
开了service mode吗

**Comment by returnL** [comment]
> 开了service mode吗

开了，使用的TUN模式

**Comment by yi-Xu-0100** [comment]
@Fndroid 我没有用 TUN/TAP ,但是开了 service ……也有这个问题

**Comment by Fndroid** [comment]
那其实应该是更新成功了，只是核心没有重启成功，大概更新完重启一下app就可以

**Comment by yi-Xu-0100** [comment]
@Fndroid 我重启了，好像没效果，标注上是原来的 core，我不确定是不是更新了

**Comment by returnL** [comment]
> 那其实应该是更新成功了，只是核心没有重启成功，大概更新完重启一下app就可以

我用另一台电脑试了一下，同样的情况，重启了电脑还是显示2020.12.17
![Snipaste_2021-02-26_11-43-20](https://user-images.githubusercontent.com/44701395/109252839-6e08e100-7829-11eb-84dc-04d8eb340a12.png)
![Snipaste_2021-02-26_11-50-10](https://user-images.githubusercontent.com/44701395/109252850-73fec200-7829-11eb-9f16-1353f3a61ac8.png)

我另一台电脑还没卸载重装，有什么办法能检测下只是显示问题还是核心确实没有升级呢？

**Comment by returnL** [comment]
我看了下Home Directory里面service文件夹里clash-core-service.exe的修改日期
软件里显示Core Version 2020.12.27的话，修改日期是这样的
![Snipaste_2021-02-26_12-31-55](https://user-images.githubusercontent.com/44701395/109255466-005fb380-782f-11eb-9956-7e04d3cda246.png)
卸载重装之后，软件里显示Core Version 2021.02.19，clash-core-service.exe的修改日期也变成了今天

**Comment by Fndroid** [comment]
应该是core在service mode下被系统占用导致的，下个版本修复

**Comment by falloutxxx2** [comment]
> 应该是core在service mode下被系统占用导致的，下个版本修复

是不是并没有解决啊！

![QQ图片20210305143911](https://user-images.githubusercontent.com/34625315/110077740-a0828300-7dc1-11eb-9e27-94e002768b51.png)

**Comment by Fndroid** [comment]
> > 应该是core在service mode下被系统占用导致的，下个版本修复
> 
> 
> 
> 是不是并没有解决啊！@Fndroid
> 
> 
> 
> ![QQ图片20210305143911](https://user-images.githubusercontent.com/34625315/110077740-a0828300-7dc1-11eb-9e27-94e002768b51.png)
> 
> 

今天的更新修复，不是得等下次更新才有效果吗？😂

**Comment by falloutxxx2** [comment]
> > > 应该是core在service mode下被系统占用导致的，下个版本修复
> > 
> > 
> > 是不是并没有解决啊！@Fndroid
> > ![QQ图片20210305143911](https://user-images.githubusercontent.com/34625315/110077740-a0828300-7dc1-11eb-9e27-94e002768b51.png)
> 
> 今天的更新修复，不是得等下次更新才有效果吗？😂

![QQ截图20210312101606](https://user-images.githubusercontent.com/34625315/110881960-2d769080-831c-11eb-82b1-aec7b01a171e.png)

**Comment by yi-Xu-0100** [comment]
@Fndroid 我觉得，可以增加一个重新安装当前版本的选项 /狗头

**Comment by returnL** [comment]
> > > > 应该是core在service mode下被系统占用导致的，下个版本修复
> > > 
> > > 
> > > 是不是并没有解决啊！@Fndroid
> > > ![QQ图片20210305143911](https://user-images.githubusercontent.com/34625315/110077740-a0828300-7dc1-11eb-9e27-94e002768b51.png)
> > 
> > 
> > 今天的更新修复，不是得等下次更新才有效果吗？😂
> 
> ![QQ截图20210312101606](https://user-images.githubusercontent.com/34625315/110881960-2d769080-831c-11eb-82b1-aec7b01a171e.png)
> @Fndroid

我的成功更新了，要不你完全卸了重装试试吧

**Comment by falloutxxx2** [comment]
> > > > > 应该是core在service mode下被系统占用导致的，下个版本修复
> > > > 
> > > > 
> > > > 是不是并没有解决啊！@Fndroid
> > > > ![QQ图片20210305143911](https://user-images.githubusercontent.com/34625315/110077740-a0828300-7dc1-11eb-9e27-94e002768b51.png)
> > > 
> > > 
> > > 今天的更新修复，不是得等下次更新才有效果吗？😂
> > 
> > 
> > ![QQ截图20210312101606](https://user-images.githubusercontent.com/34625315/110881960-2d769080-831c-11eb-82b1-aec7b01a171e.png)
> > @Fndroid
> 
> 我的成功更新了，要不你完全卸了重装试试吧

其实要吧 Service Mode 卸载了再装就好了。。。只是不去研究肯定不知道。。。。

**Comment by yi-Xu-0100** [comment]
@falloutxxx2 我没有卸载，也更新成功了，只能说，可以试试这个方法，没准可行

**Comment by Jaygeec** [comment]
和我的问题一模一样

**Comment by Xlight5** [comment]
me too, I have the same problem.
from 0.20.14, in China.
