### ISSUE TITLE
M1 Macbook Air无法打开APP “Clash for Windows” is damaged and can’t be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by Yan9527** [Fndroid/clash_for_windows_pkg#1666]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ x] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**Big Sur 11.2.2**

[//]: # (平台及版本号)

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

****

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by kingforme** [comment]
卸载,重新安装

**Comment by Yan9527** [comment]
> 卸载,重新安装

没有安装过旧版本，第一次安装。。。arm64位的版本

**Comment by JNZ116** [comment]
sudo xattr -r -d com.apple.quarantine /Applications/Clash\ for\ Windows.app

**Comment by xiaominglui** [comment]
> sudo xattr -r -d com.apple.quarantine /Applications/Clash\ for\ Windows.app

遇到了一样的问题，运行过上面的命令后可以正常启动了

**Comment by rinex20** [comment]
> sudo xattr -r -d com.apple.quarantine /Applications/Clash\ for\ Windows.app

solved.

**Comment by cclovescj** [comment]
> sudo xattr -r -d com.apple.quarantine /Applications/Clash\ for\ Windows.app

非常感谢，这个问题已经困扰我好几天了

**Comment by Yan9527** [comment]
亲测有效，只是每次更新还是需要再输入一次。

**Comment by cclovescj** [comment]
> 亲测有效，只是每次更新还是需要再输入一次。

对，我明明也已经打开了安全性与隐私里的 任何来源了，不知道为什么还要输入这个来单独给他允许，按理是不需要的

**Comment by GOUKI9999** [comment]
m1 air 问题相同，通过上述方案已经解决，多谢，另及，m1是0.14.7支持的吧，我不记得14.7还是14.8安装dmg出现过签名错误问题，是否和这个问题有相关？

**Comment by yony1018** [comment]
> sudo xattr -r -d com.apple.quarantine /Applications/Clash\ for\ Windows.app

Thanks a lot! Sovled Perfectly on Macbook Air 2020 M1 Version.

**Comment by verring** [comment]
Thanks a lot! Sovled Perfectly on Macbook Pro 15-inch, 2019 intel MacOS Ver 13.5.1 (22G90)
