### ISSUE TITLE
error message: Could not switch to this profile!

### ISSUE THREAD

**Issue by Goswell** [Fndroid/clash_for_windows_pkg#167]
![image](https://user-images.githubusercontent.com/32272548/63208270-9d06a880-c104-11e9-9f93-d5e52b1d200e.png)
切换到手动编辑后，每次保存时，刚保存完的这个*.yml文件就会立刻被删除，并会在原位置创建一个新名字的*.yml**空**文件。
CFW版本：0.7.2
系统：Win10专业版1903
已尝试：卸载，重启，删了所有带clash的注册表都没解决。

**Comment by Fndroid** [comment]
@Goswell 手动编辑不会重命名配置文件吧，用Clash for Windows的UI编辑才会

**Comment by liukaiwen0422** [comment]
我也出现了一个类似的问题，想知道应该怎样解决啊？
![BB31DA94-E6A2-451B-B7FE-4AD5DDFE118B](https://user-images.githubusercontent.com/53621063/68073745-5dc82980-fdce-11e9-9df9-3d2999c85842.jpeg)
