### ISSUE TITLE
Mac M1芯片（Apple Silicon）无法启动

### ISSUE THREAD

**Issue by xxsoul** [Fndroid/clash_for_windows_pkg#1670]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
MacOS 11.2.1

[//]: # (平台及版本号)
Darwin Arm64，Kernel Version 20.3.0
**描述**

[//]: # (请具体并清楚地描述遇到的问题)
在仓库的Release中，下载0.14.7的dmg安装包（Clash.for.Windows-0.14.7-arm64.dmg）后，无论在dmg中运行和拖到Application目录下运行，均报“‘Clash for Windows’已损坏...”

**复现**

[//]: # (请描述复现问题的步骤)

1. 双击安装包（dmg）
2. 双击Clash for Windows“
3. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)
应用正常启动
**日志**
无
[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/17698125/109423422-475dcc80-7a1a-11eb-8639-fffe13a7547f.png)
![image](https://user-images.githubusercontent.com/17698125/109423543-cd7a1300-7a1a-11eb-81d8-2f4a1ed93885.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by rinex20** [comment]
遇到同样的问题。

**Comment by rinex20** [comment]
> 遇到同样的问题。

参考另外一个issue说明，安装后，sudo xattr -r -d com.apple.quarantine /Applications/Clash\ for\ Windows.app
 已解决。

**Comment by xxsoul** [comment]
问题解决，感谢~
