### ISSUE TITLE
How to resolve all dns through clash

### ISSUE THREAD

**Issue by fsheidaiee** [Fndroid/clash_for_windows_pkg#1672]
Hi
I am using clash with tun mode with this dns and tun config;
dns:
  enable: true
  enhanced-mode: redir-host
  nameserver:
    - https://cloudflare-dns.com/dns-query
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 198.18.0.2:53
  macOS-auto-route: true
  macOS-auto-detect-interface: true

as you see I am using cloudflare dns over https for my nameserver.
but when I go to [dns leak test](https://browserleaks.com/dns) I see google dns (its the default dns of my device) and also I see my vpn providers dns as well.
this means that I have dns leak. I want all of my requests goes through cloudflare dns over https which I defined in the config.
(I want to see only cloudflare dns in the test resaults).
How can I do that?

**Comment by yi-Xu-0100** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/discussions/1426

**Comment by Fndroid** [comment]
https://github.com/Dreamacro/clash/issues/1177

**Comment by fsheidaiee** [comment]
I enabled the "Turn off smart multi-homed name resolution in Windows" from gpedit and the problem got solved.
