### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by xianyu12345** [Fndroid/clash_for_windows_pkg#1673]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows10

**描述**

除了直连所有节点都是timeout，系统时间没问题，如何排查

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by DawnMagnet** [comment]
windows客户端已经无法使用

**Comment by xianyu12345** [comment]
> windows客户端已经无法使用

是吗...

**Comment by Fndroid** [comment]
可能是dns没设置对，也可能是节点确实访问不了

**Comment by DawnMagnet** [comment]
应该是配置的问题，我把windows用户.config/clash文件夹删除后就可以连接到服务器了

**Comment by xianyu12345** [comment]
> 应该是配置的问题，我把windows用户.config/clash文件夹删除后就可以连接到服务器了

那不是还得从新导入配置文件吗，我试了一下没效果欸

**Comment by xianyu12345** [comment]
> 可能是dns没设置对，也可能是节点确实访问不了

可以具体教一下吗，我这边dns一直是自动获取的

**Comment by Fndroid** [comment]
@xianyu12345 如果配置文件不是你自己写的，就找给你配置文件的人

**Comment by RaibFlee** [comment]
你问题解决了吗
