### ISSUE TITLE
I have problem using Tun mode

### ISSUE THREAD

**Issue by seemystories** [Fndroid/clash_for_windows_pkg#1674]
I copied the amd64 version of `wintun.dll` to both `C:\Program Files\Clash for Windows` & `C:\Users\[USER]\AppData\Local\Programs\Clash for Windows` directories. I enabled "Mixin" and installed "Service Mode" as it was written in the manual and then the globe icon turned green as the instruction said. I added the same exact Mixins in the manuals yet the Tun mode does not seem to work. I ran "Tap mode" successfully though it was not that good now I want to try Tun mode to see if it's better.

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/109516954-bc490900-7ae3-11eb-9b3d-038448a7a6d8.png)
![image](https://user-images.githubusercontent.com/16091562/109517008-cb2fbb80-7ae3-11eb-8024-d1bae5749084.png)
