### ISSUE TITLE
更新0.14.8版本后开启系统代理无法连接

### ISSUE THREAD

**Issue by 1394805163** [Fndroid/clash_for_windows_pkg#1684]
同一个节点，在电脑的v2rayN上可以使用，并且用clash订阅直接到手机clash也可以使用，但是就是在电脑上无法使用，现在回滚了版本也无济于事，求解决，网络是学校的校园网用的拨号连接，
![image](https://user-images.githubusercontent.com/26848256/110123486-e8260080-7dfb-11eb-95e8-36fecec60930.png)
![image](https://user-images.githubusercontent.com/26848256/110123517-f3792c00-7dfb-11eb-90bb-a18b0b1c0b26.png)
![image](https://user-images.githubusercontent.com/26848256/110123533-f83de000-7dfb-11eb-9e2c-7e80c7dd8e0e.png)
![image](https://user-images.githubusercontent.com/26848256/110123543-fb38d080-7dfb-11eb-97c8-c31bee9c4111.png)
![Screenshot_20210305_211912_com github kr328 clash](https://user-images.githubusercontent.com/26848256/110123704-33401380-7dfc-11eb-93dc-d63393b2fa6a.jpg)
一直转圈圈
![image](https://user-images.githubusercontent.com/26848256/110123890-6d111a00-7dfc-11eb-84ef-dbd94f731194.png)
或者就是这样子
![image](https://user-images.githubusercontent.com/26848256/110123840-61255800-7dfc-11eb-9cf4-b2f196dace7b.png)然后跳出没有连接互联网
但是v2ray可以连接
![image](https://user-images.githubusercontent.com/26848256/110124121-b1041f00-7dfc-11eb-8a55-6321dc6bc1c3.png)
![image](https://user-images.githubusercontent.com/26848256/110124161-bb261d80-7dfc-11eb-80fe-33b413a481ac.png)
除了敏感时间速度稍微慢一些外无任何影响求大佬们帮忙解决

**Comment by yi-Xu-0100** [comment]
@1394805163 看看日志规则走向，和有没有相应的 warning 和 error ？

**Comment by 1394805163** [comment]
就是log里面什么都没有我也不知道为什么，tg电报群里都说是我网络环境问题，那为啥我v2ray可以用啊

**Comment by 1394805163** [comment]
给我一种就是系统代理不行，但是你像v2ray或者ssr通过直连或者pac就是可以使用我是真的很奇怪，有没有大佬能帮忙看一下啊

**Comment by 1394805163** [comment]
> @1394805163 看看日志规则走向，和有没有相应的 warning 和 error ？

或者如果方便的话，能直接teamviwer,或者todesk帮忙远程看一下吗

**Comment by akw5454521** [comment]
Log不是实时更新的，会有滞后，你开着log页面多刷新几次油管页面看看

**Comment by yi-Xu-0100** [comment]
@1394805163 那你在切换系统代理模式到 PAC 模式试试

**Comment by 1394805163** [comment]
感谢大佬们的帮助，大概知道是什么原因了是我去了学校以后学校的防火墙禁止任何加密数据出去但是我使用热点没有任何问题，校园网自己本身的问题，目前的解决办法是，不用校园网的拨号连接，买了一个路由器刷上固件就可以了，单单连接路由器不够，感谢大佬的帮助

**Comment by Fndroid** [comment]
你拨号是不是中文名

**Comment by 1394805163** [comment]
> 你拨号是不是中文名

感谢大佬的关心不是中文名，是学号加学校后缀的方式，然后是让运行商进校园的，也不好重新拉线进来，现在已经可以用了，真的很感谢大家的帮助
