### ISSUE TITLE
奇怪问题请教。同一网络下2台电脑网卡型号一样，同一个URL源

### ISSUE THREAD

**Issue by Mjmaster** [Fndroid/clash_for_windows_pkg#1685]
三天前开始，一台用Clash，所有服务器节点都显示Timeout，并且连不上。（但是直接ping 节点的地址，都是通的）
原以为是梯子服务商的问题，等了几天都没好。
今天用了另一台电脑，同样的源，所有节点都很好，速度飞快。

在无法使用的那台电脑上检查了网卡设置，防火墙，执行了netsh winsoc reset等等常规项目，确保与第二台电脑设置完全一样，还是不行。

请教下还有其他什么可以检查的吗？

**Comment by Mjmaster** [comment]
搞定了，在clash的文件里，把dns enable从true改成false后就一切正常了。
虽然还是不明白为什么，因为在其他电脑上不需要改成false。

**Comment by Fndroid** [comment]
那这个issue先关闭了

**Comment by akw5454521** [comment]
两台电脑是同一网络？

**Comment by Mjmaster** [comment]
> 两台电脑是同一网络？

是的，都是家里的同一网络，同一机场的源。
