### ISSUE TITLE
希望可以增加开机自启的优先启动功能

### ISSUE THREAD

**Issue by CaliInn-Li** [Fndroid/clash_for_windows_pkg#1689]
**描述**
目前状态下如果在关机时没有关闭clash的代理功能，在开机时clash自启前系统将因为代理设置暂时无法访问网络。但是目前clash for windows的启动优先度较低，会对使用产生不便。我了解到壁纸软件Wallpaper Engine为了解决这类问题提供了优先启动的选项，开启该功能后该软件将以较高的优先度开机自启，希望clash for windows也可以引进。

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
settings里system proxy的type选pac
