### ISSUE TITLE
新版开启代理，网易云音乐uwp版播放不了

### ISSUE THREAD

**Issue by ltu00** [Fndroid/clash_for_windows_pkg#169]
看logs正常，网易相关的都是direct，uwploopback也用了，tap之前版本就装了的。之前可以正常播放的，现在不行了，只能关了代理听歌。规则没改过一直用的是旧的

**Comment by nyaachen** [comment]
请自行查阅文档，进log说明配置错误

**Comment by ltu00** [comment]
> 请自行查阅文档，进log说明配置错误

一直用的神机规则都没问题的，

**Comment by Fndroid** [comment]
有可能是你还原过 config.yml 然后又忘记把 cfw-bypass 加回去了

https://docs.cfw.lbyczf.com/rao-guo-xi-tong-dai-li

**Comment by ltu00** [comment]
> 有可能是你还原过 config.yml 然后又忘记把 cfw-bypass 加回去了
> 
> https://docs.cfw.lbyczf.com/rao-guo-xi-tong-dai-li

by pass里面已经有了，

cfw-bypass:
  - qq.com
  - music.163.com
  - '*.music.126.net'
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
cfw-latency-timeout: 5000

**Comment by ltu00** [comment]
> 有可能是你还原过 config.yml 然后又忘记把 cfw-bypass 加回去了
> 
> https://docs.cfw.lbyczf.com/rao-guo-xi-tong-dai-li

换了https://github.com/Hackl0us/SS-Rule-Snippet/tree/master这个规则好了

**Comment by ltu00** [comment]
> 有可能是你还原过 config.yml 然后又忘记把 cfw-bypass 加回去了
> 
> https://docs.cfw.lbyczf.com/rao-guo-xi-tong-dai-li

找到原因了，对Profiles里的配置文件添加cfw-bypass没用，要在general---TextModeEdit，这算bug吗
@Fndroid

**Comment by Fndroid** [comment]
Profiles里的文件只有 dns / Proxy / Proxy Group / Rule 是生效的，这是一直以来的设定
