### ISSUE TITLE
有些进程无法通过VPN连接

### ISSUE THREAD

**Issue by Alvine1r43** [Fndroid/clash_for_windows_pkg#1691]
作者您好！
应该如何让电脑上所有进程通过VPN访问网络呢？
例如我使用某个软件，它的后台会去下载一些google的依赖项，可是它却无法通过vpn访问。
（而我自己打开网页，访问是没问题的）

我应该如何解决呢....

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/tun.html
