### ISSUE TITLE
安装包太大   ，  运行不流畅

### ISSUE THREAD

**Issue by Masir01** [Fndroid/clash_for_windows_pkg#1693]
**描述**
能用C# 重做GUI么......    
这个   真的   太臃肿了

**Comment by Fndroid** [comment]
https://github.com/shadowsocks/shadowsocks-windows/releases

**Comment by Masir01** [comment]
打扰了。。。&nbsp; 老板&nbsp; &nbsp;哈哈哈&nbsp; &nbsp; &nbsp;这&nbsp; 这这这&nbsp; &nbsp; &nbsp; 机场那边给的订阅链接指定的&nbsp; clash......
&nbsp;

人生就在相遇之間！


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Fndroid"<notifications@github.com&gt;; 
发送时间: 2021年3月9日(星期二) 中午11:39
收件人: "Fndroid/clash_for_windows_pkg"<clash_for_windows_pkg@noreply.github.com&gt;; 
抄送: "无痕❀"<1486109452@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Fndroid/clash_for_windows_pkg] 安装包太大   ，  运行不流畅 (#1693)





 
Closed #1693.
 
&mdash;
