### ISSUE TITLE
DNS in tun mode

### ISSUE THREAD

**Issue by fsheidaiee** [Fndroid/clash_for_windows_pkg#1694]
Hi
1. as you see here
[clash documents for tun mode](https://lancellc.gitbook.io/clash/start-clash/clash-tun-mode/setup-gvisor-in-real-ip-mode)
there is a line;
  listen: 0.0.0.0:1053
whats the use of this line in windows? in[ this document](https://docs.cfw.lbyczf.com/contents/tun.html#macos) i dont see this line.
is it necessary to put this line? what for? in which conditions I have to put this line?
2. does clash support dns over quic?
can I use "quic://dns-unfiltered.adguard.com:784" as nameserver?
thanks

**Comment by Fndroid** [comment]
1. ``listen``is not required
2. no
