### ISSUE TITLE
公司网络（屏蔽一些特殊聊天工具）使用Rule模式怎么让微信也走代理，使用Global模式可以正常使用微信的

### ISSUE THREAD

**Issue by OtherSun** [Fndroid/clash_for_windows_pkg#1696]
**描述**
搜索现有问题没有找到答案
公司网络（屏蔽了微信）使用Rule模式怎么让微信也走代理，使用Global模式可以正常使用微信的

**其他说明**
暂无

**Comment by yi-Xu-0100** [comment]
https://lancellc.gitbook.io/clash/clash-config-file/rules

**Comment by akw5454521** [comment]
Process name规则

**Comment by flyhunterl** [comment]
PROCESS-NAME, WeChat, PROXY

**Comment by Hilo1989** [comment]
> PROCESS-NAME, WeChat, PROXY

请问 mac版的clash如何设置PROCESS-NAME ？我没有找到相关设置规则的地方，求教
