### ISSUE TITLE
rule模式无效

### ISSUE THREAD

**Issue by mike-lei** [Fndroid/clash_for_windows_pkg#1697]
[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

 # (平台及版本号)
win10 20h2 
Clash.for.Windows-0.14.8-win.7z

 # (请具体并清楚地描述遇到的问题)
rule模式打开后，YouTube仍打开失败，使用v2ray无问题

**Comment by yi-Xu-0100** [comment]
@mike-lei 查看日志是否命中规则，如果日志没有相关记录，查看是否开启系统代理和浏览器代理是否被其他插件接管

**Comment by mike-lei** [comment]
> @mike-lei 查看日志是否命中规则，如果日志没有相关记录，查看是否开启系统代理和浏览器代理是否被其他插件接管

你好，由于电脑暂时不在身边，只能文字描述非常抱歉。当时日志关于链接YouTube几个网站全是failed或者直接不显示。至于代理，当时系统并没开启其他代理，浏览器也无，dns设置的是腾讯和谷歌dns.但依然毫无作用。只有全局模式才能正常访问油管

**Comment by yi-Xu-0100** [comment]
@mike-lei 
1. 给出相关日志，如果有日志命中，给出错误信息，会有具体原因。
2. 考虑到全局模式能用，在 rule 中选择同样节点，如果规则合适的话，应该同样可用。建议排查日志和对应规则。

**Comment by mike-lei** [comment]
> @ mike-lei
> 
> 1. 称为相关日志，如果有日志命中，表示错误信息，会有具体原因。
> 2. 考虑到一级模式能用，在规则中选择相同的等级，如果规则合适的话，应该同样可用。

更新到0.14.9 7z版本，问题已解决
