### ISSUE TITLE
更新失败

### ISSUE THREAD

**Issue by zth0550** [Fndroid/clash_for_windows_pkg#1699]
**信息**

- [ x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ x ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ x ] 已经尝试更新到最新版本，问题依旧存在
- [ x ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Win10 20h2

**描述**

从14.8更新至14.9时更新失败

**复现**

14.8为仅为当前用户安装在D盘，更新时从github下载安装包覆盖安装，并没有使用软件内更新，更新过程中出现报错。错误见截图。中止和忽略错误后，均无法在安装路径再找到clash for windows文件夹

**日志**

没找到哪里有安装日志

**截图**

![QQ截图20210312110753](https://user-images.githubusercontent.com/30037036/110886645-f4421e80-8323-11eb-9f8d-c5ede9532d27.png)

**其他说明**

无

**Comment by Fndroid** [comment]
一般就是文件被占用了然后更新程序覆盖不了

**Comment by zth0550** [comment]
> 一般就是文件被占用了然后更新程序覆盖不了

我看了一下，好像是storemi的锅，它在调用小文件到加速盘。如果可以的话写个提示，不要安装在storemi盘里。
