### ISSUE TITLE
TAP网卡是否可以加入手动修改地址

### ISSUE THREAD

**Issue by kz-wind** [Fndroid/clash_for_windows_pkg#170]
因同时使用tunsafe软件，在设置中使用10.0.0.0/24的网段，两者似乎无法共存，所以希望加入手动修改tap网卡上的10.0.0.1地址

**Comment by Fndroid** [comment]
TAP 现在似乎是有更好的实现方式，后面会尝试重构这部分再加上这些内容

**Comment by kz-wind** [comment]
> TAP 现在似乎是有更好的实现方式，后面会尝试重构这部分再加上这些内容

感谢回复，另外我尝试修改了add_tap_device.bat这个文件里的关于10.0.0.0网段的内容，全部替换成了10.1.0.0，网关也改成了10.1.0.1，并且在cfw-tap上面也生效了。依照wiki上的测试指导，在cmd里路由表能看到相关的路由信息，并且也按照文档修改了config配置的内容，在cmd里使用ping可以得到fake ip给的198.18的地址，但是此地址无法ping通，也无法curl，初步怀疑是转换成fake ip后没有再次转入clash进行转发，此处有点不解，是否程序已经写死只对进入10.0.0.0网段的进行处理。

**Comment by Fndroid** [comment]
@kz-wind 连接TAP的代码目前是固定的

**Comment by kz-wind** [comment]
> @kz-wind 连接TAP的代码目前是固定的

好的，了解了，希望后续版本可以改善此问题。
