### ISSUE TITLE
打开 TUN 或者 TAP 后，微软拼音输入法无法弹出

### ISSUE THREAD

**Issue by Zxilly** [Fndroid/clash_for_windows_pkg#1701]
**信息**

- [ x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ x ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ x ] 已经尝试更新到最新版本，问题依旧存在
- [ x ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 Dev 21332.1000
Clash latest

**复现**

[//]: # (请描述复现问题的步骤)

打开 TUN 或者 TAP 后，微软拼音输入法无法弹出

**预期行为**

正常使用输入法

**其他说明**

因为同样是走 TAP 的 Netch 貌似没有这个问题， 因此我怀疑这是一个 Clash 的 bug

**Comment by yi-Xu-0100** [comment]
@Zxilly 弹出来是啥意思？文字候选框吗？

**Comment by Zxilly** [comment]
@yi-Xu-0100 是的，在开启了 TUN/TAP 后，中文输入模式下击键无响应

**Comment by xhsu** [comment]
我也有這個問题，微軟注音輸入法和微軟倉頡輸入法也一樣無法選字

**Comment by Zxilly** [comment]
我解决这个问题了，方法是在Netch中卸载NF驱动
我不知道背后的具体原理，但是还是希望能帮到其他遇到同样问题的人

**Comment by hmqgg** [comment]
成功复现，使用 Win10 21H2 版本，Clash 使用 Tun/TAP 模式，有*较大*概率无法弹出候选窗口。仅开启 Proxy 则不影响。
按照此 issue 中提供的方案，卸载 Netfilter 服务并不能有效解决此问题，可能需要 reopen。

**Comment by Zxilly** [comment]
@hmqgg 试试更新wintun.dll

**Comment by hmqgg** [comment]
> @hmqgg 试试更新wintun.dll

已是 `0.11.0`
