### ISSUE TITLE
CFW 0.14.9退出后再打开，不能自动启用系统代理的Bug

### ISSUE THREAD

**Issue by rollexxx** [Fndroid/clash_for_windows_pkg#1702]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息****设置了系统代理，退出后再打开CFW不能自动启用系统代理，需要手动打开**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by gehengshun** [comment]
同样问题，现用老版本代替，望修复

**Comment by Fndroid** [comment]
下个版本修复

**Comment by DSG613** [comment]
0.14.9这个版本太坑了，更新之后有一些网站直接访问不了

**Comment by chendijun527** [comment]
0.14.8版本没问题，已回退

**Comment by abae136ab** [comment]
> 下个版本修复
0.14.10依旧没有修复~

**Comment by Fndroid** [comment]
@abae136ab 手动开关下system proxy

**Comment by abae136ab** [comment]
> @abae136ab 手动开关下system proxy

测试通过~手动开关一次，再退出开启就好了。

**Comment by returnL** [comment]
我感觉0.14.10版本还是有点问题，我用的TUN+Service Mode，用的Mixin当TUN模式的开关。把Mixin关了一会之后，左下角会显示红点+Disconnected，Service Mode卸载后重装，左下角恢复成绿点+Connected

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
