### ISSUE TITLE
0.14.9 PuTTY 无法使用 SOCKS5 代理

### ISSUE THREAD

**Issue by mwhds97** [Fndroid/clash_for_windows_pkg#1703]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 8.1 9600

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
PuTTY 使用 SOCKS5 代理时，有如下提示：

![image](https://user-images.githubusercontent.com/32876945/111021012-92a5b100-8404-11eb-93f1-af2f58528da9.png)

HTTP 代理正常
0.14.8 SOCKS5 代理正常

**Comment by mwhds97** [comment]
![image](https://user-images.githubusercontent.com/32876945/111023358-95f46900-8413-11eb-9d3b-96d73e8e7cd6.png)

WinSCP 也有同样的状况

**Comment by Fndroid** [comment]
我试了下winscp是正常的，而且你图里这个看着不是因为socks5连不上，而是目标主机连不上

**Comment by mwhds97** [comment]
> 我试了下winscp是正常的，而且你图里这个看着不是因为socks5连不上，而是目标主机连不上

应该不是目标主机的问题， 0.14.8 SOCKS5 可以连上。
排查之后发现是 Clash Core 的问题。即使不运行 CFW ，直接使用 Clash Core 问题依然存在。 2.19 Premium 是正常的。

**Comment by nasaboy** [comment]
clash-core 1.4.2遇到同样的问题，刚开始我还以为是服务器问题呢，换到http就正常了

**Comment by mwhds97** [comment]
该问题已在最新 commit [5da1b2a](https://github.com/Dreamacro/clash/commit/5da1b2a8aafe928aa7927f9eeaf9725993d67fca) 中被修复

**Comment by flyingwhitewhale** [comment]
最新的CORE1.5.0还没修复好像，问题重现
