### ISSUE TITLE
如何更改软件的显示语言？

### ISSUE THREAD

**Issue by mswbol** [Fndroid/clash_for_windows_pkg#1704]
我是中国人，英语不好，怎么软件没有设置语言选项？能不能支持一下中文？还有，能不能定义规则，希望国内的网站跳过代理。

**Comment by Fndroid** [comment]
你英语不好，和我有什么关系？

**Comment by mswbol** [comment]
> 你英语不好，和我有什么关系？

对于傲慢的你而言，用户体验的好坏的确和你没关系，因为你根本不在乎。再者，假使你是“中国人”，从你的回复内容可以反映出你并不以自己的母语为荣！

**Comment by Fndroid** [comment]
@mswbol 我挺佩服你这种人的，只要自己认知出现困难，就能随便上升到“中国人”、“母语为荣”这个层面。

**Comment by Sunbread** [comment]
> @mswbol 我挺佩服你这种人的，只要自己认知出现困难，就能随便上升到“中国人”、“母语为荣”这个层面。

很简单啊，发现自己智商比别人低就会很难受，于是就会想找优越感，但是自己智商低，只好找自己所属的中国人有什么优越之处了。这种人很可怜的，支撑自己生活的理由是和自己毫不相干的东西……

**Comment by hashwu333** [comment]
这人这么理直气壮，真是孝死我了

**Comment by cnSchwarzer** [comment]
哄堂大笑了兄弟们
