### ISSUE TITLE
关于python爬虫

### ISSUE THREAD

**Issue by jihuayi1997** [Fndroid/clash_for_windows_pkg#1705]
使用python爬虫时会失败比如requests库...求解决办法qaq 这个具体怎么配置

**Comment by jihuayi1997** [comment]
即使改成DIRECT模式，仍然会失败，除非关闭代理。。。

**Comment by Fndroid** [comment]
settings里system proxy的type选pac

**Comment by jihuayi1997** [comment]
> settings里system proxy的type选pac

谢谢！改成PAC好用了！！！（虽然没太懂）
查到了好像是因为python pip urllib3这些库现在支持了https，会用https连接代理服务器，代理服务器不支持！（是这样吧qaq）
我看解决方案还有：2. 改代码传proxies参数 3.改HTTPS_PROXY

**Comment by Fndroid** [comment]
因为windows的系统代理默认就只支持http代理
