### ISSUE TITLE
使用Update更新会卸载整个程序

### ISSUE THREAD

**Issue by RamonChao** [Fndroid/clash_for_windows_pkg#1706]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Windows 10 20H2
[//]: # (平台及版本号)

**描述**
原始安装版本为0.14.5，有更新提示后点击版本号，然后选择Update更新，下载完成后提示是否解压，选择是，然后程序退出，随后启动了old unistaller旧版本卸载程序，但是该卸载程序将整个程序进行了卸载，查看安装目录文件已经消失
[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入0.14.5版本主界面
2. 点击版本号提示更新，使用Update方式更新
3. 等待更新包下载后选择解压
4. 程序退出，自动启动旧版本卸载程序 

**预期行为**

[//]: # (清晰地描述期望看到的行为)
程序退出，安装目录文件消失，完整程序被卸载

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
因为你这个0.14.5是为所有用户安装的，然后Update没有权限写入Program Data里。重新下载一个最新版安装就好了，数据默认都不在安装目录里。
