### ISSUE TITLE
Tun模式与WSL下SSH、Git可能存在的冲突

### ISSUE THREAD

**Issue by SiyangShao** [Fndroid/clash_for_windows_pkg#1709]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ x] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Windows 10
[//]: # (平台及版本号)
Clash For Windows V0.14.9
**描述**
按照官方操作利用Mixin开启TUN模式，在WSL1下代理git发现权限错误，ssh git@github.com提示kex_exchange_identification: Connection closed by remote host，
而git 向github 推送提示
kex_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
关闭TUN模式，采用export HTTP_PROXY的方式对WSL1进行代理可正常提交
**预期行为**

**截图**
![图片](https://user-images.githubusercontent.com/61853047/111317903-8721e680-869f-11eb-9a9f-f94c6a3ba7cf.png)
![图片](https://user-images.githubusercontent.com/61853047/111317942-8f7a2180-869f-11eb-97fa-618ef088884d.png)

**其他说明**

**Comment by Foglotus** [comment]
请问这个你解决了吗？

**Comment by Foglotus** [comment]
> 请问这个你解决了吗？

我也遇到了这个情况，git没法用了

**Comment by lengthmin** [comment]
同样遇到了类似的问题。。开 clash 的 tun 模式就无法使用 ssh

**Comment by tigerruanyifan** [comment]
同样的问题...不知道你怎么解决的呀

**Comment by daolanfler** [comment]
同样的问题，ssh push to git repo ，如下报错信息
```
kex_exchange_identification: read: Connection reset by peer
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
``` 
关闭 tun mode 可以正常push

**Comment by xizeyoupan** [comment]
在配置文件rules最前面添加
`DST-PORT,22,DIRECT`

用[parsers](https://docs.cfw.lbyczf.com/contents/parser.html)可以这样:
```yml
parsers:
  - url: your_config_url
    yaml:
      prepend-rules:
        - DST-PORT,22,DIRECT
```

**Comment by daolanfler** [comment]
> 在配置文件rules最前面添加 `DST-PORT,22,DIRECT`
> 
> 用[parsers](https://docs.cfw.lbyczf.com/contents/parser.html)可以这样:
> 
> ```yaml
> parsers:
>   - url: your_config_url
>     yaml:
>       prepend-rules:
>         - DST-PORT,22,DIRECT
> ```

谢谢，` DOMAIN-KEYWORD,your-git-registry-keyword,DIRECT`，我这样配置也解决了这个问题
