### ISSUE TITLE
关于https

### ISSUE THREAD

**Issue by jihuayi1997** [Fndroid/clash_for_windows_pkg#1710]
上次用python爬虫时出现proxy error，查到是因为最新的库使用proxy时传的是https
所以听了建议把系统代理改成了PAC，但只能解决国内网站不使用代理，才能爬取成功，有点治标不治本
问题1：PAC模式下新建环境变量HTTPS_PROXY=http://127.0.0.1:7890，百度网盘客户端无法播放视频，退出clash则百度网盘无法联网
问题2：为了解决百度网盘的问题，采用了PAC模式删除环境变量，而是采用修改注册表的方式：http=http://127.0.0.1:7890;https=http://127.0.0.1:7890，并且手动打开系统代理选项，这时win10窗口显示自动pac脚本和手动代理都是开的（clash客户端系统代理显示为关）我也不知道到底走的哪个，但是用idm下载东西的时候出现ssh connect error
问题3：为了解决idm的问题，我把clash客户端的系统代理打开了，就可以下载了，但在爬取国外网站的数据时，结果不知道为什么出现国外网站无法爬取的情况...
现在的状态就是clash客户端选择http系统代理，注册表改为http=http://127.0.0.1:7890;https=http://127.0.0.1:7890，一切都是正常的，但是注册表每次都要自己开机改，不然clash开机自启就会变为老样子，请问有什么好的解决办法吗能够解决所有问题吗？一直不太懂PAC和路由规则的关系，我要继续用HTTP手动修改注册表吗

**Comment by jihuayi1997** [comment]
好像是 如果我修改注册表，就会出现idm的ssl connec error 但不改又没法解决上面的问题

**Comment by Fndroid** [comment]
选PAC，开[TUN](https://docs.cfw.lbyczf.com/contents/tun.html)模式

**Comment by jihuayi1997** [comment]
> 选PAC，开[TUN](https://docs.cfw.lbyczf.com/contents/tun.html)模式

嗯嗯 谢谢 目前一切正常了
