### ISSUE TITLE
能不能考虑做一个用开源clash core的版本？

### ISSUE THREAD

**Issue by CCRcmcpe** [Fndroid/clash_for_windows_pkg#1713]
这样本程序也可以开源，对于这种性质的软件，用着更让人放心

**Comment by Fndroid** [comment]
没有精力维护非premium core的版本，所以应该不会做。

**Comment by CCRcmcpe** [comment]
好吧。

**Comment by akw5454521** [comment]
以前Clash core还开源的时候，本程序也没开源啊

**Comment by CCRcmcpe** [comment]
> 以前Clash core还开源的时候，本程序也没开源啊

我记得在issue里作者说过没开源是因为用了premium的core，现在我搜不到了，很奇怪，可能我记错了
现在我换用了开源的clash core，自己配置。在powershell里 `Invoke-RestMethod` 就可以改变当前设置，还算方便

**Comment by CCRcmcpe** [comment]
> 开源是因为用了premium的core

不好意思，记混了。这是Clash for Android说的
