### ISSUE TITLE
windows 0.14.9版本，打开service mode，开启mixin，CPU占用率会很高

### ISSUE THREAD

**Issue by ForestL18** [Fndroid/clash_for_windows_pkg#1714]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Windows 1909
[//]: # (平台及版本号)

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
windows 0.14.9版本，打开service mode，开启mixin，clash的CPU占用率会很高，关闭mixin占用率下降
**复现**
多次试验，均会出现
[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
@ForestL18 给出 `mixin` 内容

**Comment by ForestL18** [comment]
mixin:
  dns:
    enable: true
    enhanced-mode: redir-host
    nameserver:
      - 61.132.163.68 # 真实请求DNS，可多设置几个
      - https://175.102.18.197/dns-query
      - tls://dns.google:853
      - tls://1.0.0.1:853
  # interface-name: WLAN # 出口网卡名称，或者使用下方的自动检测
  tun:
    enable: true
    stack: gvisor
    dns-hijack:
      - 198.18.0.2:53
    macOS-auto-route: true
    macOS-auto-detect-interface: true # 自动检测出口网卡

**Comment by ForestL18** [comment]
![image](https://user-images.githubusercontent.com/45709305/111556346-4ae8a600-87c5-11eb-826e-3757aeee09ba.png)

**Comment by yi-Xu-0100** [comment]
@ForestL18  dns 多设置几个，可以试试我的版本 https://github.com/Fndroid/clash_for_windows_pkg/issues/1688#issuecomment-795068269

**Comment by ForestL18** [comment]
我觉得有可能是我开启tun导致的，tun开启就有问题

**Comment by yi-Xu-0100** [comment]
@ForestL18 那就禁用自动检测，填写 interface-name

**Comment by ForestL18** [comment]
试了，还是不行，一开启tun占用率就极高

**Comment by yi-Xu-0100** [comment]
@ForestL18 过会呢？一直很高吗？日志表现如何，一直在请求 dns 吗？

**Comment by ForestL18** [comment]
是的，日志一直在请求dns

**Comment by ForestL18** [comment]
退回0.14.8版本测试依然会有这个问题，同时也测试了开启tap同时开启mixin，也会出现上述情况

**Comment by ForestL18** [comment]
@Fndroid 大佬可以看一下这个开启tun就满负载的原因吗，感谢

**Comment by ForestL18** [comment]
重置电脑网络后解决
