### ISSUE TITLE
代理被强制改变 无网络连接

### ISSUE THREAD

**Issue by Warborn123** [Fndroid/clash_for_windows_pkg#1715]
代理被强制改变为http://127.0.0.1:86/， clash无法关闭system proxy(但是没有连接)

**Comment by yi-Xu-0100** [comment]
@Warborn123 #312 

1. 建议自查有啥控制了系统代理
2. 看下配置中的 port 填写内容
3. 建议安装模板填写，给出日志或者相关截图。

**Comment by Warborn123** [comment]
@yi-Xu-0100 大神 我最近什么新软件都没安，可能是windows更新的原因吗？刚才用360断网恢复，然后现在系统代理是关闭了，clash也成灰色的了，打不开代理了。

**Comment by yi-Xu-0100** [comment]
@Warborn123 备份订阅和配置，删除 home directory 重启试试

**Comment by Warborn123** [comment]
@yi-Xu-0100 试过了，还重装了一边旧版本clash，还是不行:(

**Comment by yi-Xu-0100** [comment]
@Warborn123 日志里面有什么？现在是启动不了系统代理吗？

**Comment by Warborn123** [comment]
@yi-Xu-0100 嗯，我刚才根据#312 里说的，把注册表 HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
ProxySettingsPerUser 改成 1，现在好了，难道是windows更新的锅吗？这个参数其他软件应该不会改吧。
