### ISSUE TITLE
ws-path被错误格式化

### ISSUE THREAD

**Issue by wloot** [Fndroid/clash_for_windows_pkg#1716]
**信息**

- [x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ x] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

CFW v0.14.9

**描述**

设置ws-path, cfw会错误地将path里的`?`格式化成`%3F`, 然后发起连接

**复现**

```
    - { name: 'xxx', type: vmess, server: example.com, port: 8080, uuid: 000-000--00000, alterId: 1, udp: true, network: ws, ws-path: '/?ed=2048', ws-headers: { Host: vexample.com }, cipher: auto }
```
如上配置无法访问节点, 从nginx服务器查看日志, 访问的是`/%3Fed=2048`

**Comment by iKingEast** [comment]
同样问题，困惑好久，原来是这个原因

**Comment by Fndroid** [comment]
clash core issue, refer: https://github.com/Dreamacro/clash/issues
