### ISSUE TITLE
Connections > Connection Info > Host 无法选中/复制

### ISSUE THREAD

**Issue by HaloWang** [Fndroid/clash_for_windows_pkg#1719]
**描述**

期望图中黄色部分是可选/可复制的。

![捕获](https://user-images.githubusercontent.com/7344724/111863493-e2e9b980-8996-11eb-8a11-ea329ff1ecef.PNG)

这样的话，可以方便用户根据 host 快速编辑（复制粘贴）自己的 profile

**其他说明**
无

**Comment by akw5454521** [comment]
可以从log里复制

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
