### ISSUE TITLE
Profile 这儿输入/复制粘贴完URL, 应该支持点enter 就下载, 不用点一下"Download"

### ISSUE THREAD

**Issue by congcong0806** [Fndroid/clash_for_windows_pkg#172]
![image](https://user-images.githubusercontent.com/3024785/63313824-513c4500-c338-11e9-843e-3dcabbcd502f.png)

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.7.5
