### ISSUE TITLE
 能否加上 ShadowsocksR 的 端口设置功能，可以在clash代理规则为RULE的情况下，某个软件流量全部出海

### ISSUE THREAD

**Issue by tutuorz** [Fndroid/clash_for_windows_pkg#1723]
![1](https://user-images.githubusercontent.com/23742758/111905136-30445480-8a85-11eb-9bb0-8af6a2b03a0c.png)
假设使用proxifier+ShadowsocksR，ShadowsocksR按照上图设置后，proxifier设置127.0.0.1:2088端口的代理，代理规则加上A浏览器，此时用A浏览器访问百度或者谷歌均为出海流量。
而另外一个未在proxifier代理规则内的B浏览器代理为默认的127.0.0.1:1080，B浏览器会按照ShadowsocksR设置分流。

假设使用proxifier+clash，proxifier只能设置127.0.0.1:7890端口的代理，代理规则加上A浏览器，clash的代理规则设置为RULE的情况下，此时用A浏览器访问百度为直连流量，访问谷歌则为代理。
请问有什么方法可以实现proxifier+ShadowsocksR的效果？
简言之想实现的就是：在clash设置为rule的情况下，如何设置一个软件不受rule的控制，所有流量均走代理。

**Comment by Fndroid** [comment]
```yaml 
rules:
  - PROCESS-NAME,chrome.exe,Proxy
```

**Comment by tutuorz** [comment]
感谢
- PROCESS-NAME,chrome.exe,Proxy  有效
- PROCESS-NAME,vmnat.exe,Proxy 无效，vmnat是vm虚拟机网络活动进程，用proxifier可以代理vmnat.exe
请问什么原因？
