### ISSUE TITLE
开启TUN模式无法访问网络

### ISSUE THREAD

**Issue by danielchans** [Fndroid/clash_for_windows_pkg#1727]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 10 专业版 20H2
Clash For Windows v 0.14.10

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入Gerneral - Service Mode - install（出现绿色地球logo）
2. 点击settings - proxy mixin - yaml - edit
3. 复制mixin文档 ![QQ截图20210323161427](https://user-images.githubusercontent.com/72936182/112118693-96e97f80-8bf7-11eb-8123-1cf1dac44ec7.png)
![QQ截图20210323161436](https://user-images.githubusercontent.com/72936182/112118695-97821600-8bf7-11eb-8c30-f971f569cf31.png)
4. 开启Mixin，关闭system proxy 
![QQ截图20210323161407](https://user-images.githubusercontent.com/72936182/112120957-acf83f80-8bf9-11eb-8a4e-329ac8de7441.png)

5. 触发问题：网络访问失败，包括代理分组策略及本地direct

**预期行为**

[//]: # (清晰地描述期望看到的行为)
Tun模式正常运行，网络正常访问

**日志**

[//]: # (上传触发问题对应的日志文件)
![QQ截图20210323161356](https://user-images.githubusercontent.com/72936182/112118687-951fbc00-8bf7-11eb-84d4-ab1a8a76ce07.png)
![QQ截图20210323161559](https://user-images.githubusercontent.com/72936182/112118696-981aac80-8bf7-11eb-9a82-d27954050035.png)
**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)
网卡：Killer E2200 Gigabit Ethernet Controller

**Comment by Fndroid** [comment]
killer网卡看看这里，https://docs.cfw.lbyczf.com/contents/questions.html

**Comment by danielchans** [comment]
> killer网卡看看这里，https://docs.cfw.lbyczf.com/contents/questions.html

感谢回复！

**Comment by danielchans** [comment]
已解决. 下载Killer Control Center 后禁用 Killer Priority Engine，关闭Clash System Proxy，开启Mixin后，即可正常使用TUN模式。
