### ISSUE TITLE
可否在不同proxy mode下显示不同颜色的状态栏图标？

### ISSUE THREAD

**Issue by ServiceYun** [Fndroid/clash_for_windows_pkg#1731]
**描述**
可否在不同proxy mode下显示不同颜色的状态栏图标？

**其他说明**
谢谢

**Comment by ServiceYun** [comment]
> **描述**
> 可否在不同代理模式下显示不同颜色的状态栏图标？
> 
> **其他说明**
> 谢谢

**Comment by Fndroid** [comment]
不会做
