### ISSUE TITLE
怎么配置全局系统代理

### ISSUE THREAD

**Issue by cjlhll** [Fndroid/clash_for_windows_pkg#1734]
**描述**
改为golbal模式后。系统的一些cmd。还是无法代理。。还有不管什么模式下。苹果的icloud和微软的网站都无法代理。速度很慢

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/tun.html

**Comment by akw5454521** [comment]
ICMP本来就不代理
苹果微软网站走直连这个，确定全局模式选择节点了？
