### ISSUE TITLE
升级到0.15.0后，Proxies下的内容都消失了

### ISSUE THREAD

**Issue by mostcool** [Fndroid/clash_for_windows_pkg#1737]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Windows 10
Clash.for.Windows.Setup.0.15.0
**描述**
升级到0.15.0后，Proxies下的内容都消失了

**复现**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
@mostcool
1. 保存订阅链接，关闭软件，删除 home directory 下的 profiles， 重启软件，重新下载订阅试试
2. 保存相关配置，关闭软件，完全删除 home directory ，重启试试
