### ISSUE TITLE
添加“不修改系统代理设置”的选项

### ISSUE THREAD

**Issue by hyxxsfwy** [Fndroid/clash_for_windows_pkg#174]
目前的软件行为是，在关闭“System Proxy”按钮的情况下，软件启动时不会修改现有的系统代理设置，但退出时会自动取消掉现有的系统代理设置。而预期的行为是完全不修改现有的系统代理设置。

**Comment by Fndroid** [comment]
下个版本修复

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.7.5
