### ISSUE TITLE
0.15.0版本主界面卡loading

### ISSUE THREAD

**Issue by xiaochency** [Fndroid/clash_for_windows_pkg#1740]
[![6xsi7D.png](https://z3.ax1x.com/2021/03/27/6xsi7D.png)](https://imgtu.com/i/6xsi7D)
[![6xstcq.png](https://z3.ax1x.com/2021/03/27/6xstcq.png)](https://imgtu.com/i/6xstcq)
C盘也没有生成clash配置文件
运行环境：win10-2004-64位
安装包exe和便携版都是这样，退回0.14.9没有问题
[![6xs4ED.png](https://z3.ax1x.com/2021/03/27/6xs4ED.png)](https://imgtu.com/i/6xs4ED)

**解决办法：用0.14.9生成.config\clash配置文件后，0.15.0就可以进入主界面了**
**解决办法：用0.14.9生成.config\clash配置文件后，0.15.0就可以进入主界面了**
**解决办法：用0.14.9生成.config\clash配置文件后，0.15.0就可以进入主界面了**

**Comment by yi-Xu-0100** [comment]
clash配置文件? home directory 看看？

**Comment by xiaochency** [comment]
> clash配置文件? home directory 看看？

用0.14.9生成\.config\clash配置文件后，0.15.0就可以进入主界面了

**Comment by RainCat1998** [comment]
+1，在重装的电脑上可以复现此问题

**Comment by wangliang1989** [comment]
+1

**Comment by zhiying8710** [comment]
最新版不能生成.config文件夹， 复制旧版本生成的包括里面的文件过去就行了

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
