### ISSUE TITLE
Lightweight Mode下Silent Start失效

### ISSUE THREAD

**Issue by returnL** [Fndroid/clash_for_windows_pkg#1747]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
 Windows 10 20H2

**描述**
最新版本0.15.1下，同时打开Silent Start和Lightweight Mode，开机时会弹出CFW的界面。如果只打开Silent Start，则开机时不会弹出CFW界面

**预期行为**
开启Silent Start时，开机不应该弹出CFW的界面

**Comment by Fndroid** [comment]
逻辑上没有问题，开了lightweight mode之后启动都会打开界面
