### ISSUE TITLE
无法连接Clash内核

### ISSUE THREAD

**Issue by ZR1314** [Fndroid/clash_for_windows_pkg#1748]
![IMG_20210330_031724](https://user-images.githubusercontent.com/81339236/112889598-6f6b4900-9108-11eb-8687-4d8acb856c47.jpg)
![IMG_20210330_031729](https://user-images.githubusercontent.com/81339236/112889404-261af980-9108-11eb-8bc3-ea8e2c87bfab.jpg)
![IMG_20210330_031724](https://user-images.githubusercontent.com/81339236/112889598-6f6b4900-9108-11eb-8687-4d8acb856c47.jpg)

time="2021-03-30T02:40:41+08:00" level=info msg="Start initial compatible provider Proxy"
time="2021-03-30T02:40:41+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2021-03-30T02:40:41+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2021-03-30T02:40:41+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2021-03-30T02:40:41+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2021-03-30T02:40:41+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2021-03-30T02:41:51+08:00" level=info msg="Start initial compatible provider Proxy"
time="2021-03-30T02:41:51+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2021-03-30T02:41:51+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2021-03-30T02:41:51+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2021-03-30T02:41:51+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2021-03-30T02:41:51+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2021-03-30T02:42:33+08:00" level=info msg="Start initial compatible provider Proxy"
time="2021-03-30T02:42:33+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2021-03-30T02:42:33+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2021-03-30T02:42:33+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2021-03-30T02:42:33+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2021-03-30T02:42:33+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2021-03-30T02:43:41+08:00" level=info msg="Start initial compatible provider Proxy"
time="2021-03-30T02:43:41+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2021-03-30T02:43:41+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2021-03-30T02
![IMG_20210330_031729](https://user-images.githubusercontent.com/81339236/112889404-261af980-9108-11eb-8bc3-ea8e2c87bfab.jpg)
![Uploading IMG_20210330_031729.jpg…]()

**Comment by Fndroid** [comment]
使用任何非Github版本，请勿发issue，谢谢合作
