### ISSUE TITLE
开机clash自启时出现错误弹窗，手动关闭弹窗后clash才启动。

### ISSUE THREAD

**Issue by s1mple11** [Fndroid/clash_for_windows_pkg#1749]
**信息**
Clash for Windows版本为0.15.1

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

win10家庭版20H2 19042.906

**描述**

开机clash自启时出现错误弹窗，手动关闭弹窗后clash才启动，但使用时未发现其他异常。

**复现**
重启电脑。

**预期行为**

开机自启时不出现弹窗

**截图**
![image](https://user-images.githubusercontent.com/53406185/112987167-febe3e00-9194-11eb-952f-43e17881952b.png)

**Comment by yi-Xu-0100** [comment]
@s1mple11 兄弟，建议用原版。https://github.com/Fndroid/clash_for_windows_pkg/releases
