### ISSUE TITLE
希望软件可以在电脑关机时自动关闭Windows的代理设置

### ISSUE THREAD

**Issue by troyeguo** [Fndroid/clash_for_windows_pkg#1750]
**描述**

系统：Windows 10
版本：0.15.1

希望软件在电脑关机时，如果处于运行状态，可以自动关闭Windows的代理设置

**其他说明**

目前电脑关机的时候如果没有手动退出应用，再次开机就会无法上网，设置-网络-代理-手动设置代理处于开启状态，但如果clash没有设置开机自启动，就会无法上网，必须手动开启clash或者到设置里关闭代理设置，才能正常上网。

**Comment by iwsbiwy** [comment]
软件正常任务栏退出的的时候，会自动关闭系统代理的，关机时算非正常退出不行。软件设置开机自启吧。

**Comment by AkariiinMKII** [comment]
软件不知道你关机

**Comment by dkl520** [comment]
我也有上述的问题 。。请问有什么办法直接在cfw 关闭后自动关闭代理服务器的方法吗？

**Comment by cikichen** [comment]
> 软件正常任务栏退出的的时候，会自动关闭系统代理的，关机时算非正常退出不行。软件设置开机自启吧。

因为有些电脑开机后等一会才能连上网，如果开机启动会导致节点更新异常进而引发其他异常情况
