### ISSUE TITLE
Keep user edit rule alone and auto merge to profile when it gets updated

### ISSUE THREAD

**Issue by small-pineapple** [Fndroid/clash_for_windows_pkg#1752]
I found after update profile, the manually added rules by myself will be overwriten, so I have to keep add those rules every time when I update profile, this is tedious. The rules add by user should keep alone and auto merged after profile updated.

**Comment by yi-Xu-0100** [comment]
CFW support parser after the profile update, maybe you need Google Translate for reading the docs. 

Here is the link: <https://docs.cfw.lbyczf.com/contents/parser.html>
