### ISSUE TITLE
Allow LAN模式下访问局域网下设备

### ISSUE THREAD

**Issue by Pharrio** [Fndroid/clash_for_windows_pkg#1755]
在Mac Mini M1上使用CFW v0.15.1设置好了Allow LAN并且配置了手机/Pad的http代理，可以正常运作。但是手机/Pad此时无法访问同一局域网下的其他设备，比如路由器管理界面或者NAS，关闭了http代理就可以正常访问。

想问一下这是Allow LAN模式的限制吗？（因为我在Mac上是可以访问局域网内设备的，所以推测不是配置文件的问题）

有没有什么解决办法呢？

**Comment by Fndroid** [comment]
这不是Allow LAN的问题，是你手机/平板设置的代理问题，没有绕过内网地址

**Comment by Pharrio** [comment]
感谢回复，确认了是配置文件的问题。

之前Mac上由于网络设置里配置了bypass localhost之类所以可以访问内网，让我以为是配置文件里写好了。
