### ISSUE TITLE
杀毒软件报木马

### ISSUE THREAD

**Issue by crazythinking** [Fndroid/clash_for_windows_pkg#176]
时间	操作	说明	次数
2019-08-23 11:10:23	[未处理]	  发现木马：Trojan.Win32.QQPass.wzd	防护 1 次
详细描述：
木马名称：Trojan.Win32.QQPass.wzd
所在路径：##################\clash-win64.exe

**Comment by Fndroid** [comment]
误报，core代码开源：https://github.com/Dreamacro/clash

**Comment by tslling** [comment]
虽然我们信任这个软件，但是windows防火墙都报木马导致下载的exe文件被删除，还有去windows defender那边手动点信任。有没有办法绕过让他不报呢

**Comment by Fndroid** [comment]
@tslling 没有，因为没有签名
