### ISSUE TITLE
Win10下TUN模式开启移动热点时卡死

### ISSUE THREAD

**Issue by SamuNatsu** [Fndroid/clash_for_windows_pkg#1764]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows10
Clash v0.15.1

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
在开启TUN模式后，如果打开Windows移动热点功能，会导致产生大量53端口的DNS连接，进而导致程序卡死
TUN模式按照文档进行设置，仅改变了nameserver条目，使用Mixin部署

**复现**

[//]: # (请描述复现问题的步骤)

1. 开启TUN模式
2. 开启系统代理
3. 打开Windows移动热点

**预期行为**

[//]: # (清晰地描述期望看到的行为)
Clash的Connection栏内被快速灌满端口为53连接

**日志**

[//]: # (上传触发问题对应的日志文件)
[2021-04-02-180912.log](https://github.com/Fndroid/clash_for_windows_pkg/files/6249012/2021-04-02-180912.log)

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![屏幕截图 2021-04-02 180553](https://user-images.githubusercontent.com/49141130/113406491-20f6cc80-93de-11eb-975b-a446dd83d662.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
Duplicate of #1444

**Comment by zhongguozhu** [comment]
same problem
