### ISSUE TITLE
Windows 10「你的手机」应用无法联网

### ISSUE THREAD

**Issue by Littlegolden** [Fndroid/clash_for_windows_pkg#1767]
**信息**

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本（0.15.1），问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 20H2 19042.906

**描述**

处于 TUN 模式，已在网络回环中勾选并保存 @{Microsoft.YourPhone_1.21022.139.0_x64}，尝试重启该应用/电脑，同时尝试将代理规则中的微软服务从直连修改为节点代理，但你的手机仍提示「我们遇到了网络问题」

**预期行为**

你的手机能联网，不论是通过代理还是直连。

**日志**

无

**截图**

![image](https://user-images.githubusercontent.com/35162802/113476345-91205380-94ad-11eb-8628-ba810f5be8a3.png)

**其他说明**

打开网络回环时，会提示一下内容，但比如我勾选应用商店之后，商店确实可以走代理。
![image](https://user-images.githubusercontent.com/35162802/113476576-e3ae3f80-94ae-11eb-8e72-3997b94a795c.png)

**Comment by Fndroid** [comment]
enhanced-mode是什么

**Comment by Littlegolden** [comment]
> enhanced-mode是什么

请问是啥意思。。。这个 issue 好像没有提到这个

**Comment by yi-Xu-0100** [comment]
@Littlegolden 

![image](https://user-images.githubusercontent.com/25523606/113499277-3fc4a280-9547-11eb-9f26-cd4845775cce.png)

TUN 配置文档： <https://docs.cfw.lbyczf.com/contents/tun.html#windows>

**Comment by Littlegolden** [comment]
是这样的：
![image](https://user-images.githubusercontent.com/35162802/113499294-67b40600-9547-11eb-8709-1fcb88405d9f.png)

**Comment by yi-Xu-0100** [comment]
@Littlegolden dns-hijack 改成文档中的呢？

**Comment by Littlegolden** [comment]
> @Littlegolden dns-hijack 改成文档中的呢？

好了，神奇。。。非常感谢！
