### ISSUE TITLE
添加一个功能，在connection界面里的connection info显示完整域名

### ISSUE THREAD

**Issue by Ben-md5** [Fndroid/clash_for_windows_pkg#1769]
**描述**
希望在connection界面里的connection info显示完整域名，现在如访问https://github.com/Fndroid/clash_for_windows_pkg/ connection info只会显示访问GitHub.com，希望可以添加完整内容

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
没有MITM，所以做不到的

**Comment by Ben-md5** [comment]
好的，谢谢F大
