### ISSUE TITLE
小小的建议，能否把proxy和rules分开

### ISSUE THREAD

**Issue by GHOSTagw** [Fndroid/clash_for_windows_pkg#177]
每次更新订阅，之前自己添加的rules就被清除了，还要再重新写一遍......
鄙人觉得应该单独把rules从profiles里分出来，像bitfoast V和kitsunebi一样，毕竟机场很少更新rules，更新rules的又很少开机场。

**Comment by Fndroid** [comment]
@GHOSTagw 那怎么保证rule里对应的proxy和group存在

**Comment by GHOSTagw** [comment]
> 
> 
> @GHOSTagw 那怎么保证rule里对应的proxy和group存在

改个名应该就可以了吧，比如我的proxy叫US-B，网上的规则一般是这种DOMAIN-SUFFIX,apps.apple.com,Proxy，把",Proxy"搜索替换成",US-B"。

**Comment by Fndroid** [comment]
@GHOSTagw 建议你理解一下节点、策略组和规则的关系再说

**Comment by xt1085** [comment]
@GHOSTagw 你可以联系你的机场，把你自己的规则添加到机场rules，这样你每次更新订阅你自己的规则也不会清除，更可以帮助 你的机场完善规则。

**Comment by xt1085** [comment]
@Fndroid 可否给软件界面的右上角添加个最大化的选项啊

**Comment by Fndroid** [comment]
@xt1085 意义是什么

**Comment by xt1085** [comment]
@Fndroid 节点太多了全在一个小框里，放大了就好一些。

**Comment by XiaoTeemo** [comment]
> 每次更新订阅，之前自己添加的rules就被清除了，还要再重新写一遍......
> 鄙人觉得应该单独把rules从profiles里分出来，像bitfoast V和kitsunebi一样，毕竟机场很少更新rules，更新rules的又很少开机场。

这个建议要去 https://github.com/Dreamacro/clash 这里提。
我也很期待这个功能。

**Comment by yhnbgfd** [comment]
> @GHOSTagw 那怎么保证rule里对应的proxy和group存在

我这边也有这个困扰，我的机场有很多Proxy，其中有部分是双倍流量的高速Proxy，所以我会把一些流量小但是常用的网站比如github、google或者个人相关的网站直接指定跑双倍流量的Proxy，其他网站走普通流量Proxy。
所以自定义设置Rule对我非常重要，Clash本身也已经支持了，至于在更新profile后怎么处理，我的想法是这样的，一般来说机场的profile是不会有大的改动的，例如命名等，所以更新profile后再将同名profile中自定义的Rule应用上去不会有大的问题，如果出现Proxy增删导致Rule中找不到对应的Proxy或Proxy Group，那直接忽略这条Role就好了（最好界面上给个提示，不要直接删除Role）。

**Comment by Fndroid** [comment]
> Clash本身也已经支持了

怎么理解

> 一般来说机场的profile是不会有大的改动的，例如命名等，所以更新profile后再将同名profile中自定义的Rule应用上去不会有大的问题，如果出现Proxy增删导致Rule中找不到对应的Proxy或Proxy Group，那直接忽略这条Role就好了（最好界面上给个提示，不要直接删除Role）。
还有一些细节问题例如用户删除了Proxy原有的Rule，或转移了优先级顺序怎么处理等，我个人基本是不会这么操作，如果真有需要，我会创建一条新的Rule去覆盖机场Rule，所以这一块我就建议不保存用户修改了

这一部分，每个人的需求都不一样，没有一个通用方案下，并不会添加到CFW里

**Comment by GHOSTagw** [comment]
> 
> 
> > > Clash本身也已经支持了
> > 
> > 
> > 怎么理解
> 
> CFW本身已经支持在下载profile加载后，进行EditRules操作了，在我看来这个功能最简单的实现方法就是Add的时候另外存一份，UDPATE profile后将另存的自定义Rule重新Add进去。
> 
> ![image](https://user-images.githubusercontent.com/3962004/64773517-1c14c280-d585-11e9-87b0-bc132ad3d8c1.png)

可以是可以，不过每次都手动的话还是比较麻烦，而且导入规则也费事，就比如导入神机规则

**Comment by hdcat** [comment]
这样的话，是不是加一个RULE的批量导入和导出功能就可以解决这个问题了？

**Comment by binaijing** [comment]
同头大这个问题，以前SS有用户规则文件可以编辑，一劳永逸。
现在每更新一次节点信息，自己加的规则全部清0，头大。有的机场经常换节点。
建议加一个全局高优先级的用户规则，功能很简单，就两个选择proxy和direct就够了。
