### ISSUE TITLE
关于软件升级时让用户选择目录的建议。

### ISSUE THREAD

**Issue by ShadowsSide** [Fndroid/clash_for_windows_pkg#1770]
**描述**
建议软件内使用update和install进行升级时可以让用户自行选择目录，或者setting里添加一个可以自定义目录的选项。
总是直接安装的C盘下总觉得怪怪的。。

**其他说明**
期待可以支持该功能。

**Comment by yi-Xu-0100** [comment]
安装的话应该可以选路径，update 好像是静默安装，应该是原路径。

**Comment by ShadowsSide** [comment]
我试过软件内置的升级或下载都是默认在C盘

**Comment by yi-Xu-0100** [comment]
@ShadowsSide 

![image](https://user-images.githubusercontent.com/25523606/113551885-f26c3200-9627-11eb-8de1-98263e4df28e.png)

我这里， update 是静默安装，download 是浏览器弹出下载页面下载 release 的包，和直接去 release 下载安装没区别，也就是都是会打开安装页面，有选择安装位置的页面。

**Comment by ShadowsSide** [comment]
> @ShadowsSide 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/25523606/113551885-f26c3200-9627-11eb-8de1-98263e4df28e.png)
> 
> 
> 
> 我这里， update 是静默安装，download 是浏览器弹出下载页面下载 release 的包，和直接去 release 下载安装没区别，也就是都是会打开安装页面，有选择安装位置的页面。

我用的是update 静默安装，默认装在c盘.但我原来目录并不在c盘.
另外点击Download 也是直接把安装包下到c盘…

**Comment by yi-Xu-0100** [comment]
@ShadowsSide 我的装在 D盘， update 是覆盖原位置， download 下载是浏览器下载，所以也是可以选择下载目录。

**Comment by Fndroid** [comment]
理论上是覆盖到原安装位置的。如果没有看看是不是有多个版本同时存在。把旧的先卸载
