### ISSUE TITLE
tun 模式下的 ipv6 DNS 查询问题

### ISSUE THREAD

**Issue by BlademasterQAQ** [Fndroid/clash_for_windows_pkg#1771]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**CFW 0.14.10**

[//]: # (平台及版本号)

**tun模式工作非常健壮，对作者的工作表示感谢！**
**发现 ping 和 DNS 解析只有ipv4地址，于是照葫芦画瓢试着设了下ipv6，发现解析失败**

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 在profiles的yml文件中的`tun:`下的`dns-hijack:`下增加`    - "[fc00::1111:1111:1111:1112]:53"`。`nameserver:`增加`    - "[2001:4860:4860::8888]:53"`
2. 修改网络适配器`clash`的ipv6配置，ipv6地址设定为`fc00::1111:1111:1111:1111`，首选DNS服务器设置为`fc00::1111:1111:1111:1112`
3. nslookup输出
```
服务器:  UnKnown
Address:  fc00::1111:1111:1111:1112

DNS request timed out.
    timeout was 2 seconds.
```
**不知道是因为CFW不支持ipv6 DNS解析，还是我的配置有问题。**

4. 重启clash后，tun会重启，网络适配器`clash`的ipv6配置会消失，只是一次性的。

[//]: # (清晰地描述期望看到的行为)

[//]: # (上传触发问题对应的日志文件)

[//]: # (如果可以，请提供对应问题的截图)

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
没看出来你想实现什么效果？dns-hijack不能随便设置

**Comment by BlademasterQAQ** [comment]
> 没看出来你想实现什么效果？dns-hijack不能随便设置

需求就是让CFW能够通过ipv6解析网址。
我的理解是tun将198.18.0.2作为DNS服务器，CFW的dns-hijack设置为198.18.0.2就是为了进行DNS解析。所以我认为增加了ipv6地址就能将域名通过CFW解析为ipv6地址了。不知道我的理解有没有错。

**Comment by Fndroid** [comment]
错。TUN拿到的DNS结果并不最后用于请求，而是根据DNS反推出来域名进行规则匹配。

如果你本地环境支持IPv6并且你想直连的时候走IPv6访问，打开General里的IPv6开关就可以了。


如果你要用IPv6的DNS服务器，只要在``nameserver``里添加就可以了。
如果你想Clash里DNS服务器（配置了listen）响应IPv6结果，设置``dns``里``ipv6: true``。

**Comment by BlademasterQAQ** [comment]
> 错。TUN拿到的DNS结果并不最后用于请求，而是根据DNS反推出来域名进行规则匹配。
> 
> 如果你本地环境支持IPv6并且你想直连的时候走IPv6访问，打开General里的IPv6开关就可以了。
> 
> 如果你要用IPv6的DNS服务器，只要在`nameserver`里添加就可以了。
> 如果你想Clash里DNS服务器（配置了listen）响应IPv6结果，设置`dns`里`ipv6: true`。

谢谢F大，在profiles的`dns:`增加`ipv6: true`解决了。
