### ISSUE TITLE
是否可以支持软件启动时自动更新一次配置文件

### ISSUE THREAD

**Issue by jorejia** [Fndroid/clash_for_windows_pkg#1772]
**描述**
目前自动更新的配置文件的功能是比如设置1个小时，开启后要等待1个小时后才会更新，并不符合使用需求
如果有更新需求的话，更希望在启动的时候就立即更新一次，之后按照设定的时间更新，这样更合理
**其他说明**
期待可以支持该功能。

**Comment by Fndroid** [comment]
设置1小时不是app启动之后的1小时，而是配置文件的修改时间距离现在1个小时
