### ISSUE TITLE
能否考虑支持 scoop

### ISSUE THREAD

**Issue by Goooler** [Fndroid/clash_for_windows_pkg#1774]
**描述**
能否考虑添加 [scoop](https://scoop.sh/) 支持，提供一个 bucket

**Comment by RtYkk** [comment]
[dorado](https://github.com/chawyehsu/dorado) 这个`bucket`里面有，自己加上就行了。scoop 这种东西都是社区维护的。
[clash-for-windows](https://github.com/chawyehsu/dorado/pull/239)  [clash-for-windows-portable](https://github.com/chawyehsu/dorado/pull/292)

**Comment by Goooler** [comment]
> [dorado](https://github.com/chawyehsu/dorado) 这个`bucket`里面有，自己加上就行了。scoop 这种东西都是社区维护的。
> [clash-for-windows](https://github.com/chawyehsu/dorado/pull/239) / [clash-for-windows-portable](https://github.com/chawyehsu/dorado/pull/292)

 谢了
