### ISSUE TITLE
logs 里显示解析域名获得的IP地址以及使用的DNS

### ISSUE THREAD

**Issue by Maasea** [Fndroid/clash_for_windows_pkg#1776]
**描述**
希望可以在log里看到域名返回的ip地址以及使用哪个dns进行的解析。
现在只有本地 `ip:port`  ,我觉得调试的时候应该很少有人关注从哪个端口发出的请求。
相反，请求所用的IP 和DNS 在调试的时候关联性大一点。

**其他说明**
[无]

**Comment by akw5454521** [comment]
Debug级别不是有返回地址吗？不过redir-host模式是没有的，我猜是因为太多了。另外你这两个是上游的问题，这里只是客户端
