### ISSUE TITLE
您好楼主 请问能不能尽量添加可以选择语言的选项呢？真诚的期待添加简体中文

### ISSUE THREAD

**Issue by 7579845** [Fndroid/clash_for_windows_pkg#1777]
**描述**
请具体并清楚地描述期望功能及期望的效果
特别希望这个软件更加好用，也很感谢软件的创作者，特别感谢给我们这么好用的软件，诚挚的希望添加语言可选项，建议添加中文版本，谢谢软件创作者
**其他说明**
其他补充内容
I especially hope this software is more user-friendly, and thank the creator of the software, especially for giving us such a user-friendly software. I sincerely hope to add language options. I suggest adding Chinese version. Thank you for the creator of the software

**Comment by yi-Xu-0100** [comment]
Duplicate of #999
