### ISSUE TITLE
[Feature Request] 希望添加“隐藏不可选择的策略组”的选项

### ISSUE THREAD

**Issue by northword** [Fndroid/clash_for_windows_pkg#1781]
**描述**
感谢大佬的CFW，我有个小需求，如下：
策略组中存在`URL-TEST`类型的，不能手动选择，希望可以有个选项隐藏了他们（分组有些多，看着有点乱），类似于CFA的这个：
![CFA](https://user-images.githubusercontent.com/44738481/114134862-01f6be00-993b-11eb-98b4-3bd4c5cb1b1b.jpg)

**其他说明**
无

**Comment by Fndroid** [comment]
下个版本支持
![image](https://user-images.githubusercontent.com/16091562/116021706-498b8280-a67b-11eb-9633-91a4974db531.png)

**Comment by northword** [comment]
> 下个版本支持
> ![image](https://user-images.githubusercontent.com/16091562/116021706-498b8280-a67b-11eb-9633-91a4974db531.png)

感谢，辛苦了！

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
