### ISSUE TITLE
v0.15.2版本，上下行速率不实时变化

### ISSUE THREAD

**Issue by alexchanchan** [Fndroid/clash_for_windows_pkg#1783]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
win10

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
更新v0.15.2版本后，界面上下行速率不再实时变化

**复现**

[//]: # (请描述复现问题的步骤)
隐藏界面再打开界面会才会变化一次

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/13378806/114168825-5b72e300-9963-11eb-8b51-3493a671bd26.png)

**其他说明**

[//]: # (其他补充内容)
无

**Comment by Fndroid** [comment]
已知问题，下个版本修复

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
