### ISSUE TITLE
Enhanced Tray不显示

### ISSUE THREAD

**Issue by returnL** [Fndroid/clash_for_windows_pkg#1784]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Windows 10 2004

**描述**
打开Enhanced Tray后什么都不显示

**Comment by LittleRey** [comment]
同

**Comment by AgClKawauso** [comment]
同

**Comment by poemsiu** [comment]
一样没有显示

**Comment by brownhuang163** [comment]
I have the same issue.

**Comment by clover-yan** [comment]
I have the same issue; it doesn't work at all. 

According to a message, it's because Fndroid forgot to pack the icon while packing. It'll be fixed in the next version.

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases

**Comment by klgd** [comment]
我用的0.18.8 也不显示
系统win10 21H1 19043.1348

**Comment by xcool-rabbit** [comment]
我更新到0.18.9了，也不显示，我找了半天以为要有什么特殊的开启方法呢，win10 1909

**Comment by yi-Xu-0100** [comment]
@klgd @xcool-rabbit 怀疑是被任务栏挡住了，取消锁定任务栏，然后移动到其他地方试试。

**Comment by xcool-rabbit** [comment]
> @klgd @xcool-rabbit 怀疑是被任务栏挡住了，取消锁定任务栏，然后移动到其他地方试试。

取消锁定任务栏，还是没有，重启windows重启客户端也没有(T_T)

**Comment by yi-Xu-0100** [comment]
@xcool-rabbit 

![图片](https://user-images.githubusercontent.com/25523606/142749215-a4338415-0530-40d2-901b-f98f95ca8c7a.png)

这里截图看看

**Comment by xcool-rabbit** [comment]
> @xcool-rabbit
> 
> ![图片](https://user-images.githubusercontent.com/25523606/142749215-a4338415-0530-40d2-901b-f98f95ca8c7a.png)
> 
> 这里截图看看

![image](https://user-images.githubusercontent.com/34806100/142749409-6e8d680a-6417-443c-96b3-a8b6b21eb49b.png)

**Comment by yi-Xu-0100** [comment]
@xcool-rabbit 你看到 Show 和 Hide 了吗？当左边只有猫的时候不显示，你需要**拖动右边的东西到左边**，才能显示。

**Comment by xcool-rabbit** [comment]
> @xcool-rabbit 你看到 Show 和 Hide 了吗？当左边只有猫的时候不显示，你需要**拖动右边的东西到左边**，才能显示。

emmm，原来是这样，非常感谢你教我如何设置

**Comment by canyinga** [comment]
> @xcool-rabbit 你看到 Show 和 Hide 了吗？当左边只有猫的时候不显示，你需要**拖动右边的东西到左边**，才能显示。

问下这个前景色咋整啊,,我输入了没反应

**Comment by TcDhlPro** [comment]
> @xcool-rabbit 你看到 Show 和 Hide 了吗？当左边只有猫的时候不显示，你需要**拖动右边的东西到左边**，才能显示。

离大谱......我琢磨了半天没想到这么设置的哈哈哈, 但是,为什么这玩意会显示在屏幕其他位置
![image](https://user-images.githubusercontent.com/100897011/167621974-3b033560-b716-4196-bed2-1bc52b83cd8f.png)

**Comment by huanglusong** [comment]
> @xcool-rabbit 你看到 Show 和 Hide 了吗？当左边只有猫的时候不显示，你需要**拖动右边的东西到左边**，才能显示。

哈哈，谢谢，看了您的回复才知道怎么设置的。一直琢磨官网的说明没想明白，这个设计不能说不好，但要是能配上图文解释就更人性化了
