### ISSUE TITLE
system proxy 经常会假死

### ISSUE THREAD

**Issue by huanx9** [Fndroid/clash_for_windows_pkg#1785]
system proxy 启动后过了一段时间，就不能用了， 明明是开启状态、
需要关闭后然后再次启动 就可以用了。 稳定性不是很好， 不知道是什么导致了这个问题。

**Comment by AWeng0526** [comment]
可能是开了加速器原因？我开了加速器占用端口cfw就没用了，也是要关闭再重新启动

**Comment by huanx9** [comment]
我没有开加速器，但是你说的这个好像是一个思路。。。  请问监听的端口是`7890` 吗

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/312
