### ISSUE TITLE
[Feature Request] HTTP 系统代理增加协议头

### ISSUE THREAD

**Issue by chawyehsu** [Fndroid/clash_for_windows_pkg#1787]
**描述**
开启 HTTP 系统代理，修改系统注册表（`HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings`）设置 `ProxyServer` 时对填写的代理增加 `http://` 协议头。

Current:
```reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings]
"ProxyServer"="127.0.0.1:7890"
```

Expected:

```reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings]
"ProxyServer"="http://127.0.0.1:7890"
```

**其他说明**

源于开启 HTTP 系统代理后使用 pip 的问题，关联 [#1568](https://github.com/Fndroid/clash_for_windows_pkg/issues/1568#issuecomment-770220389) #1616 #1705。一篇分析[文章](https://note.bobo.moe/2021/02/clash-for-windows-pip-proxyerror.html)指出了核心问题在于 urllib 对于没有协议头的代理地址会强制增加 https 导致代理连接问题。这既是 python 上游的问题，也可以算是 CFW 的问题。鉴于提交给 psf 修复可能性不大/时间线长。建议 CFW 先处理。

既然 [Windows 系统代理默认只支持 HTTP](https://github.com/Fndroid/clash_for_windows_pkg/issues/1705#issuecomment-798815506)，那不如修改时直接增加协议头显式指定为 HTTP。至于可行性，`ProxyServer` 是允许携带协议头进行赋值的，见[示例](https://docs.microsoft.com/en-us/troubleshoot/windows-client/networking/configure-client-proxy-server-settings-by-registry-file#create-a-registry-file)。

**Comment by Fndroid** [comment]
用pac吧，windows分分钟改完这个问题又出新的问题

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/114306404-86e60100-9b0e-11eb-9fa1-b47bb8e45a00.png)

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases

**Comment by da-gongren** [comment]
@Fndroid pac 怎么添加绕过呀？文档好像没示例，能写个示例不？
再原本的基础上，我想绕过 `*.163.com`、`129.168.1.*`

**Comment by yi-Xu-0100** [comment]
@da-gongren 

1. 新的问题建议新开个 issue
2. 参考示例看看这个：https://github.com/Fndroid/clash_for_windows_pkg/issues/2073#issuecomment-887773201

**Comment by da-gongren** [comment]
@yi-Xu-0100 已经google解决了。感谢！想来删的，你这边就回了。
