### ISSUE TITLE
拖动条焦点错误，当鼠标移动到拖动条的位置时经常变成左右缩放箭头，只有拖动条的左边小半部分可以正常可拖动，稍微靠右点就不行，焦点位置不太准确，持续了多个版本

### ISSUE THREAD

**Issue by OG-C** [Fndroid/clash_for_windows_pkg#1791]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

WIN10 20H2

拖动条焦点错误，当鼠标移动到拖动条的位置时经常变成左右缩放箭头，只有拖动条的左边小半部分可以正常可拖动，稍微靠右点就不行，焦点位置不太准确，持续了多个版本

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'软件主界面'
2. 点击'界面右侧拖动条'
3. 在拖动条的位置鼠标焦点不太准确，容易变成双向缩放箭头
4. 触发问题

**预期行为**

修正拖动条鼠标焦点不准确的BUG

**日志**

无

**截图**

无（无法截取鼠标指针，如需要可提供录屏）

**其他说明**

无

**Comment by yi-Xu-0100** [comment]
emmm, 虽然成功复现，但我一般不用拖动条，直接用滚轮或者方向键了……

**Comment by OG-C** [comment]
> emmm, 虽然成功复现，但我一般不用拖动条，直接用滚轮或者方向键了……

BUG始终在那不是吗

**Comment by Fndroid** [comment]
和焦点没关系吧，窗口边界识别成缩放是系统行为，只能说是滚动条太窄不方便拖动

**Comment by OG-C** [comment]
> 和焦点没关系吧，窗口边界识别成缩放是系统行为，只能说是滚动条太窄不方便拖动

是有问题的，F大你试试，鼠标焦点在拖动条中间指针就变了

**Comment by OG-C** [comment]
> > 和焦点没关系吧，窗口边界识别成缩放是系统行为，只能说是滚动条太窄不方便拖动
> 
> 是有问题的，F大你试试，鼠标焦点在拖动条中间指针就变了

测试过比这更窄的拖动条也不会这样

**Comment by Fndroid** [comment]
> 是有问题的，F大你试试，鼠标焦点在拖动条中间指针就变了

因为靠近边框系统就认为你要开始缩放窗口

**Comment by OG-C** [comment]
> > 是有问题的，F大你试试，鼠标焦点在拖动条中间指针就变了
> 
> 因为靠近边框系统就认为你要开始缩放窗口

你试试edge，拖动条更窄，但是一点问题没有。不考虑改吗？

**Comment by OG-C** [comment]
> > 是有问题的，F大你试试，鼠标焦点在拖动条中间指针就变了
> 
> 因为靠近边框系统就认为你要开始缩放窗口

录了个视频你看下，还没到边框就变了

**Comment by Fndroid** [comment]
> 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**Comment by OG-C** [comment]
> > 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

从本仓库下的0.15.3，未替换任何文件依然有这个问题

**Comment by yi-Xu-0100** [comment]
@OG-C 
![image](https://user-images.githubusercontent.com/25523606/114972595-5b1d9f00-9eb1-11eb-9433-6afe535b21a4.png)

我觉得没毛病了。

**Comment by OG-C** [comment]
> @OG-C 
> ![image](https://user-images.githubusercontent.com/25523606/114972595-5b1d9f00-9eb1-11eb-9433-6afe535b21a4.png)
> 
> 我觉得没毛病了。
> 

0.15.3比上一版要好点，但还是没到边框鼠标指针就变了
