### ISSUE TITLE
每次启动都会重置为Global

### ISSUE THREAD

**Issue by xyfsmile** [Fndroid/clash_for_windows_pkg#1792]
虽然设置完Rule，但是每次start with windows都会变成Global。

**Comment by weylz** [comment]
Same as you, so I temporarily rolled back the version to 0.15.1.

**Comment by yi-Xu-0100** [comment]
暂未复现，啥系统，把 home directory 删除后，重新配置是否会好？

**Comment by sfycyh** [comment]
同样遇到，删除clash的配置文件后回复正常，文件在C:\Users\用户名.config\clash下

**Comment by shikkoku** [comment]
复现，试试楼上的方法。

**Comment by Fndroid** [comment]
下个版本修复

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases

**Comment by git10135405** [comment]
@Fndroid 这个问题我这边用v0.18.4还是存在
