### ISSUE TITLE
最强大的客户端，但有一点不便

### ISSUE THREAD

**Issue by OG-C** [Fndroid/clash_for_windows_pkg#1793]
**描述**
多设备间订阅链接的分享非常麻烦，只能复制链接使用微信QQ等来发送，出于隐私考虑始终心里有疙瘩。能否添加扫码和生成二维码分享的功能？万分感谢。这是困扰我使用clash最大的问题了，几次都要差点放弃了。万分期望。爱之深责之切。

**其他说明**
无

**Comment by Fndroid** [comment]
生成二维码和发链接有区别吗

**Comment by OG-C** [comment]
> 生成二维码和发链接有区别吗

区别大了，一个必须要借助第三方IM来传达，一个不需要中间介质，更保证隐私。

**Comment by yi-Xu-0100** [comment]
@OG-C https://cli.im/url

**Comment by OG-C** [comment]
> @OG-C https://cli.im/url

这类在线工具当然知道，手机上还有Awesome QR生成二维码APP，但又是生成，又是解码很繁琐。

**Comment by yi-Xu-0100** [comment]
@OG-C 我懂了，但是手机上没有 CFW 啊？

**Comment by OG-C** [comment]
> @OG-C 我懂了，但是手机上没有 CFW 啊？

手机有CFA，生成二维码以及扫码这个建议是否需要clash核心支持？应该去隔壁提交吗？

**Comment by yi-Xu-0100** [comment]
@OG-C CFA 不支持扫码，生成 二维码也没用不是，电脑应该不好扫码吧，最多也就生成 二维码，那链接放收藏网页处理一下就好

**Comment by OG-C** [comment]
> @OG-C CFA 不支持扫码，生成 二维码也没用不是，电脑应该不好扫码吧，最多也就生成 二维码，那链接放收藏网页处理一下就好

CFW上游支持了，CFA应该也会跟进的 ，我去提交下建议。

**Comment by yi-Xu-0100** [comment]
@OG-C 巧了，CFW 也是这么想的，如果 CFA 支持了，CFW 有那么点可能跟进吧。他们俩不是上下游的关系，算同级估计。

**Comment by OG-C** [comment]
> @OG-C 巧了，CFW 也是这么想的，如果 CFA 支持了，CFW 有那么点可能跟进吧。他们俩不是上下游的关系，算同级估计。

只是在这里的表述，这不重要，重要的是主题

**Comment by yi-Xu-0100** [comment]
@OG-C 个人觉得 CFA 更好点，比较手机之间分享是有应用场景的，电脑之间没啥必要弄 二维码，所以觉得 CFA 先实现更好。

**Comment by Fndroid** [comment]
fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases

**Comment by OG-C** [comment]
> fixed in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases

万分感谢，拜谢~
