### ISSUE TITLE
规则区分大小写

### ISSUE THREAD

**Issue by bb2** [Fndroid/clash_for_windows_pkg#18]
发现域名大写就不能被识别了,可以考虑自动转换成小写，或在日志中给出提示

**Comment by bb2** [comment]
另外，日志里的emoji显示乱码。

**Comment by Fndroid** [comment]
1. 规则规范与由Clash制定，可以在核心仓库提交建议，[Clash](https://github.com/Dreamacro/clash)
2. Emoji无法显示是系统问题
