### ISSUE TITLE
系统代理开启时可以让 UWP 应用正常联网吗？

### ISSUE THREAD

**Issue by mundoque** [Fndroid/clash_for_windows_pkg#180]
最近在用 UWP QQ，开启系统代理时不能正常联网（如文字消息能加载但图片不能）。不开系统代理给非 UWP 应用逐个设置代理有些麻烦，现在有其他的方案吗？

**Comment by lizongzeshunshun** [comment]
你需要主界面中的 EnableLoopback.exe

**Comment by mundoque** [comment]
> 你需要主界面中的 EnableLoopback.exe
> 
> https://github.com/Fndroid/clash_for_windows_pkg/wiki/UWP%E5%BA%94%E7%94%A8%E8%81%94%E7%BD%91

尝试过，勾选之后会彻底无法联网（离线并提示无可用网络）

**Comment by shawchen123** [comment]
由于Microsoft的全部应用在中国区的设置默认都是直连，所以当打开网络代理之后就无法使用应用商店了，这个时候只需要下载 fiddler（http://www.telerik.com/fiddler）
在下载完成之后，点击左上角的winconfig


之后把所有的microsoft的产品打勾就行

**Comment by Fndroid** [comment]
> 由于Microsoft的全部应用在中国区的设置默认都是直连，所以当打开网络代理之后就无法使用应用商店了，这个时候只需要下载 fiddler（http://www.telerik.com/fiddler）
> 在下载完成之后，点击左上角的winconfig
> 
> 
> 之后把所有的microsoft的产品打勾就行

其实和中国区无关，只是禁止了loopback代理，Clash for Windows里面已经自带了工具解除这个限制

**Comment by shawchen123** [comment]
> > 由于Microsoft的全部应用在中国区的设置默认都是直连，所以当打开网络代理之后就无法使用应用商店了，这个时候只需要下载 fiddler（[http://www.telerik.com/fiddler）](http://www.telerik.com/fiddler%EF%BC%89)
> > 在下载完成之后，点击左上角的winconfig
> > 之后把所有的microsoft的产品打勾就行
> 
> 其实和中国区无关，只是禁止了loopback代理，Clash for Windows里面已经自带了工具解除这个限制

哈哈哈哈，你不说我都不知道，感谢

**Comment by ssyangchn** [comment]
> > 由于Microsoft的全部应用在中国区的设置默认都是直连，所以当打开网络代理之后就无法使用应用商店了，这个时候只需要下载 fiddler（[http://www.telerik.com/fiddler）](http://www.telerik.com/fiddler%EF%BC%89)
> > 在下载完成之后，点击左上角的winconfig
> > 之后把所有的microsoft的产品打勾就行
> 
> 其实和中国区无关，只是禁止了loopback代理，Clash for Windows里面已经自带了工具解除这个限制

我开了系统代理，UWP Loopback里也勾选了itunes，但是itunes还是没有没有走代理

**Comment by bingsing** [comment]
我也有相同问题，UWP的QQ应用正常代理下不能加载出图片，开loopback之后完全没网。

**Comment by desperadoxhy** [comment]
我也遇到了相同的问题，请问现在这个问题解决了吗

**Comment by Fndroid** [comment]
1. 用TAP
2. 开启loopback限制后，在cfw-bypass加入qq的域名过滤

**Comment by mundoque** [comment]
> 1. 用TAP

开启 TAP 后 UWP QQ 表现与开启前一致［在线，文字消息正常加载但图片（包括聊天图片、头像、照片墙等一切图片）不加载］

> 2. 开启loopback限制后，在cfw-bypass加入qq的域名过滤

开启 Loopback 限制后，在 cfw-bypass 加入`  - '*.qq.com'`，UWP QQ 表现与加入前一致（离线，提示无可用网络）

**Comment by mundoque** [comment]
> @mundoque 使用fiddler抓包后将以下几个域名添加到cfw-bypass后，qq uwp正常工作。
> 
> ```yaml
>   - 'monitor.uu.qq.com'
>   - 'opensdk.uu.qq.com'
>   - 'qq.com'
>   - 'cos.myqcloud.com'
>   - 'q.qlogo.cn'
> ```

参考您的建议进行了测试，发现

只需 bypass
```
  - 'qq.com'
```
（而非
```
  - '*.qq.com'
```
）
即可正常工作。

感谢您提供的方法！

**Comment by DEXTERcyy** [comment]
更新后又出现该问题,log如下
<img width="821" alt="屏幕截图 2020-12-13 185443" src="https://user-images.githubusercontent.com/49469764/102009765-b2312d00-3d74-11eb-8e80-5c2b2d5e00b0.png">

**Comment by Fndroid** [comment]
@DEXTERcyy cfw-bypass已经弃用了，在settings里的bypass里加

**Comment by ATQlove** [comment]
求问，在UWP Loopback - launch helper 处选择了exempt all依然还是没有办法联网
