### ISSUE TITLE
0.15.3 clash General 菜单卡loading

### ISSUE THREAD

**Issue by hiahia1234** [Fndroid/clash_for_windows_pkg#1802]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 10 专业版64位 2004版本 
Clash For Windows v0.15.3
**描述**

[//]: # (请具体并清楚地描述遇到的问题)
一打开clash，general就卡loading，未更改config与任何程序配置文件，重新下载也依旧
**复现**

[//]: # (请描述复现问题的步骤)

1. 进入程序
2. 点击general菜单
3. 
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)
卡在loading
**日志**

[//]: # (上传触发问题对应的日志文件)
[2021-04-16-231318.log](https://github.com/Fndroid/clash_for_windows_pkg/files/6326173/2021-04-16-231318.log)

- [ ] 

**截图**
![image](https://user-images.githubusercontent.com/67541936/115046561-2d187900-9f0a-11eb-8c21-ecfc72b612c5.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)
no more

**Comment by yi-Xu-0100** [comment]
@hiahia1234 看看任务管理器里面有没有 clash-win64.exe, 删除 home directory（位置在`C:\Users\自己的用户名\.config\clash`） 重启软件试试。

**Comment by hiahia1234** [comment]
已经删除过home directory了，任务管理器里也有clash-win64.exe
![image](https://user-images.githubusercontent.com/67541936/115101338-ea8c8600-9f75-11eb-870f-c8ecf826e630.png)

**Comment by hiahia1234** [comment]
> @hiahia1234 看看任务管理器里面有没有 clash-win64.exe, 删除 home directory（位置在`C:\Users\自己的用户名\.config\clash`） 重启软件试试。

已经删除过home directory了，任务管理器里也有clash-win64.exe
![image](https://user-images.githubusercontent.com/67541936/115101389-5bcc3900-9f76-11eb-8eed-28b5726e79c5.png)

**Comment by Fndroid** [comment]
这个clash-win64.exe是原来的吗

**Comment by hiahia1234** [comment]
原来的？我删除clash重新下载clash再打开这个进程就会启动，退出clash后也会自己结束进程，反正就是随软件携带的，而且没有我更改过。

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/115116157-cd35d700-9fca-11eb-82c4-c6cad90376fb.png)
把这里的log文件发一下

**Comment by hiahia1234** [comment]
> ![image](https://user-images.githubusercontent.com/16091562/115116157-cd35d700-9fca-11eb-82c4-c6cad90376fb.png)
> 把这里的log文件发一下

[renderer.log](https://github.com/Fndroid/clash_for_windows_pkg/files/6329416/renderer.log)

**Comment by Fndroid** [comment]
应该是系统防火墙阻止了GUI和Core通讯导致的，把``安装目录/resources/static/files/win/x64/clash-win64.exe``加到防火墙允许应用通过列表里
