### ISSUE TITLE
下载页面所有的更新时间显示的都是2020年8月21日，是bug吗？

### ISSUE THREAD

**Issue by qhdhjb** [Fndroid/clash_for_windows_pkg#1804]
下载页面所有的更新时间显示的都是2020年8月21日，是bug吗？

**Comment by yi-Xu-0100** [comment]
@qhdhjb 啥意思，截个图看看

**Comment by qhdhjb** [comment]
不会贴图，找不到图床。下载页面粘过来的：
0.15.3 …
 on 21 Aug 2020  d4b3ad1  zip  tar.gz  Notes  Downloads

0.15.2 …
 on 21 Aug 2020  d4b3ad1  zip  tar.gz  Notes  Downloads

0.15.1 …
 on 21 Aug 2020  d4b3ad1  zip  tar.gz  Notes  Downloads

0.15.0 …
 on 21 Aug 2020  d4b3ad1  zip  tar.gz  Notes  Downloads

更新日期全是 on 21 Aug 2020

**Comment by qhdhjb** [comment]
@yi-Xu-0100 上面内容，我表达明白了吗？

**Comment by yi-Xu-0100** [comment]
@qhdhjb 你的下载页面指的哪个页面，网页的话，给网页链接。github 支持直接上传图片。

我找到了你说的了，你找的是 tag，代表当前仓库的不同版本，不是文件位置，去 https://github.com/Fndroid/clash_for_windows_pkg/releases 里找下载。

**Comment by qhdhjb** [comment]
谢谢
