### ISSUE TITLE
访问一些网站时遇到了乱码与自动跳出下载对话框的问题

### ISSUE THREAD

**Issue by DannyVim** [Fndroid/clash_for_windows_pkg#181]
当我开着系统代理模式要打开这个网站的时候： http://s1vote.com/
（除此之外，我发现学校图书馆的网站也会碰到这个问题）

1. 页面会呈现乱码
![image](https://user-images.githubusercontent.com/7478103/63668401-99140e00-c809-11e9-9f36-239a9459e60f.png)

2. 然后浏览器会跳出下载框，请求下载一个名为`download.gz`的文件
![image](https://user-images.githubusercontent.com/7478103/63668467-d2e51480-c809-11e9-9cd3-af8938f4231d.png)

如果我在Chrome里面选择直连的话，打开网站就没有问题。我有些搞不明白是怎么回事，请问有人能解答一下我的困惑吗？

环境：
WIN10 1903，Chrome 76.0.3809.100，CFW 0.7.5，系统代理模式

配置文件信息：
```
port: 7980
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
secret: ""
省略服务器地址
省略规则
```

从`log`文件可以确定连接网站的规则为`DIRECT`；
同时打开网站的时候，没有发现其他连结请求；
根据下载信息，下载的地址也是s1vote.com；

**Comment by Fndroid** [comment]
开着 adguard 么

是的话，把 adguard 里的 WFP 驱动关闭（不影响过滤）

![image](https://user-images.githubusercontent.com/16091562/63669364-6e778480-c80c-11e9-994b-c3d391cc3e5d.png)

**Comment by DannyVim** [comment]
确实如此，如您所言。
我在关闭掉Adguard WFP驱动之后，一切正常了。
非常感谢！
