### ISSUE TITLE
Lightweight Mode PAC异常

### ISSUE THREAD

**Issue by urluca** [Fndroid/clash_for_windows_pkg#1810]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Windows 10 Home 20H1 19041.746

[//]: # (平台及版本号)

**描述**
Lightweight Mode无PAC代理服务 
次日系统自动刷新或手动关开飞行模式会丢失
须手动重新启动完整版的CFW

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 开启Lightweight Mode
2. Proxy Type选择PAC
3. 开启System Proxy
4. 关闭窗口
5. 启用接着关闭飞行模式
6. 外网无法访问

**预期行为**
PAC仍生效 

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/56034581/115488419-056c3c80-a28d-11eb-8768-0ae3156217d1.png)
1215为随机PAC端口

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
预期行为，Lightweight Mode无法兼容PAC模式
