### ISSUE TITLE
clash无法代理pip

### ISSUE THREAD

**Issue by Halfknow** [Fndroid/clash_for_windows_pkg#1813]
**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 10 教育版 21H1

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
1. powershell 已经设置代理，通过：netsh winhttp import proxy source=ie && set HTTP_PROXY=http://127.0.0.1:7899 && set HTTPS_PROXY=https://127.0.0.1:7899 （我的端口是7899）
2. powershell 中 git 可以走代理，但 pip 无法走代理
3. 打开clash的情况下pip install package 报错：ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))

**复现**

[//]: # (请描述复现问题的步骤)

1. 用管理员模式进入'powershell'
2. 输入 pip install opencv
3. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)
https://note.bobo.moe/2021/02/clash-for-windows-pip-proxyerror.html?showComment=1619089821817#c1174206466737483533
此博客对该问题有清晰的描述，希望此后pip可以通过clash走代理

**Comment by yi-Xu-0100** [comment]
@Halfknow #1787 看看？应该是同一个文章吧
