### ISSUE TITLE
频繁请求 127.0.0.1:xxxxx/script 405 异常

### ISSUE THREAD

**Issue by xiaogezzz** [Fndroid/clash_for_windows_pkg#1814]
**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
windows 10

**clash 版本**
0.15.4

**描述**
通过 fiddler 可以查看到 clash 一直在请求 http://127.0.0.1:xxxxx/script (clash core 端口) 并抛出 405 异常，并且频率非常之高

**截图**

![image](https://user-images.githubusercontent.com/27753789/115812471-0683a200-a424-11eb-874b-4412e801d6d3.png)

**Comment by yi-Xu-0100** [comment]
@xiaogezzz CFW 前台？#1314 看看这个，应该类似吧

**Comment by xiaogezzz** [comment]
> @xiaogezzz CFW 前台？#1314 看看这个，应该类似吧

的确是这个😂，后台之后就没啥影响了，还以为是哪里配置除了问题

**Comment by Fndroid** [comment]
不用理，正常的
