### ISSUE TITLE
希望速度表只显示流向代理的速度

### ISSUE THREAD

**Issue by Atom2004** [Fndroid/clash_for_windows_pkg#1821]
**描述**
![image](https://user-images.githubusercontent.com/22042246/115952599-7031a800-a519-11eb-96f2-1e6885f88974.png)
如上图在主界面上显示的网速表，希望此速度表只显示需要经过代理的这些流量。Direct的连接流量不计入速度表中。

**其他说明**

**Comment by Fndroid** [comment]
这里指的是经过Clash的流量速度

**Comment by akw5454521** [comment]
这个是上游问题
