### ISSUE TITLE
希望对url-test类型的proxygroup测试时是使用配置的url

### ISSUE THREAD

**Issue by Talonshaw** [Fndroid/clash_for_windows_pkg#1823]
**描述**
我新增了一个url-test类型的proxygroup，并将url设置为国内测试url（因为需要对国内代理进行测速），
[http://connect.rom.miui.com/generate_204](http://connect.rom.miui.com/generate_204)，但是当我点击测速按钮对该组进行测速时，仍然是使用默认的[http://www.gstatic.com/generate_204](http://www.gstatic.com/generate_204)，导致国内代理测速均显示超时。希望对url-test类型的proxygroup手动测速时可以使用配置的url，非常感谢。

**其他说明**
希望对国内代理服务器的使用做相应优化。

**Comment by yi-Xu-0100** [comment]
@Talonshaw 我记得点击测试的是按照 setting 的 latency test URL 测试的

![image](https://user-images.githubusercontent.com/25523606/115995022-1cec5200-a60c-11eb-9022-758cec4d3e94.png)

**Comment by Talonshaw** [comment]
> @Talonshaw 我记得点击测试的是按照 setting 的 latency test URL 测试的
> 
> ![image](https://user-images.githubusercontent.com/25523606/115995022-1cec5200-a60c-11eb-9022-758cec4d3e94.png)

没错，但是对于设置了url的组，感觉还是用设置的url测试比较合理吧，
![image](https://user-images.githubusercontent.com/33741608/116015289-3e305b00-a66b-11eb-9ecb-775764358668.png)

**Comment by Fndroid** [comment]
并不能这么理解，如果这个节点在多个url-test里面那怎么决定用哪个

**Comment by Talonshaw** [comment]
你说的有道理，我实测也发现了，一个组测速完，别的组相同节点也使用了同样的测试结果。不过确定一点，url-test自动测速会使用配置的url吧，那也同样次在你所说的这个问题啊，这里是不是有更好的处理方式呢

**Comment by Fndroid** [comment]
自动测试触发的时候会用配置指定的，但是在界面点击只会用settings里设置的，因为有的组比如select就没有url的设置，但依然可以单独执行测试，就需要在测试的时候传入url

**Comment by Talonshaw** [comment]
好吧，仍然觉得自动测速与手动测速使用不同的url得到完全不同的测试结果是一个比较奇怪的事情，自动测速显示了延迟，手动测一下就timeout了，有没有什么方法可以解决一下呢，比如加个配置项，各组独立测速，相同节点不要共享测速结果？或者不允许相同节点在多个url-test里，个人建议可能欠缺考虑哈。
不过话说回来确实不是什么大问题，毕竟国内节点测速也不是硬需求，问题我就先关闭啦
