### ISSUE TITLE
win10 更新到 Inside Preview 21364 后无法使用 tun

### ISSUE THREAD

**Issue by kakakuwai** [Fndroid/clash_for_windows_pkg#1828]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Windows 10 Insider Preview 10.0.21364.1000
[//]: # (平台及版本号)

**描述**
升级到21364后无法使用tun模式，service mode 安装正常，clash tunnel 无法正常加载，显示Windows is still setting up the class configuration for this device. (Code 56) ；卸载设备重启后依旧无法正常加载。
[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
clash tunnel 正常加载
[//]: # (清晰地描述期望看到的行为)

**日志**
打开Mixin 开启tun：
time="2021-04-26T12:34:48+08:00" level=debug msg="Generate GUID: {330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}"
time="2021-04-26T12:34:54+08:00" level=info msg="[Wintun] EnsureDeviceObject: Failed to connect to adapter ROOT\\NET\\0000 associated instance : 系统找不到指定的路径。 (Code 0x00000003)"
time="2021-04-26T12:34:54+08:00" level=info msg="[Wintun] OpenDeviceObject: Failed to connect to adapter ROOT\\NET\\0000 associated instance : 系统找不到指定的路径。 (Code 0x00000003)"
time="2021-04-26T12:34:54+08:00" level=info msg="[Wintun] ForceCloseWintunAdapterHandle: Failed to get adapter 16 object"
time="2021-04-26T12:34:54+08:00" level=info msg="[Wintun] WintunDeleteAdapter: Failed to force close adapter 16 handles"
time="2021-04-26T12:34:54+08:00" level=info msg="[Wintun] CreateAdapter: Creating adapter"
time="2021-04-26T12:34:54+08:00" level=info msg="[Wintun] SelectDriver: Using existing driver 0.10"
time="2021-04-26T12:34:55+08:00" level=info msg="[Wintun] CreateAdapter: Failed to setup adapter (status: 0x0): 操作成功完成。 (Code 0x00000000)"
time="2021-04-26T12:34:55+08:00" level=error msg="Start Tun interface error: Element not found."

卸载clash tunnel ，重新开启tun：
time="2021-04-26T12:38:16+08:00" level=debug msg="Generate GUID: {330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}"
time="2021-04-26T12:38:16+08:00" level=info msg="[Wintun] CreateAdapter: Creating adapter"
time="2021-04-26T12:38:16+08:00" level=info msg="[Wintun] SelectDriver: Installing driver 0.10"
time="2021-04-26T12:38:16+08:00" level=info msg="[Wintun] SelectDriver: Extracting driver"
time="2021-04-26T12:38:16+08:00" level=info msg="[Wintun] SelectDriver: Installing driver"
time="2021-04-26T12:38:17+08:00" level=info msg="[Wintun] CreateAdapter: Failed to setup adapter (status: 0x0): 操作成功完成。 (Code 0x00000000)"
time="2021-04-26T12:38:17+08:00" level=error msg="Start Tun interface error: Element not found."

clash tunnel device status：
Windows is still setting up the class configuration for this device. (Code 56)

events：
Driver Management has concluded the process to add Service wintun for Device Instance ID ROOT\NET\0000 with the following status: 0.

Device ROOT\NET\0000 was deleted.

Class Guid: {4d36e972-e325-11ce-bfc1-08002be10318}

[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/37097550/116029908-edc9f500-a68c-11eb-90db-ded2f04fecba.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**
另外一台笔记本电脑在升级后可以正常使用tun，记得升级的时候并没有开启tun；出问题这台电脑升级win10时开着tun模式的，有可能是升级过程中出了问题，但因为两台电脑不同，不能确定。
[//]: # (其他补充内容)

**Comment by Zxilly** [comment]
@kakakuwai 能问一下您是怎么解决这个问题的吗

**Comment by kakakuwai** [comment]
> @kakakuwai 能问一下您是怎么解决这个问题的吗

这个应该是win10和虚拟网卡的问题，我尝试了cc清除注册表和重置网络，不过没有用，应该是我把升级前版本的旧数据删了的原因😂；最后重装了系统......
总结就是大版本更新记得关了tun虚拟网卡

**Comment by kakakuwai** [comment]
> @kakakuwai 能问一下您是怎么解决这个问题的吗

可能是这个[issue](https://github.com/Dreamacro/clash/issues/1389#issue-875434913)提到的问题，今天又遇到了，更新wintun解决了
