### ISSUE TITLE
从睡眠、休眠恢复时，cfw-bypass会失效。

### ISSUE THREAD

**Issue by Nycteus** [Fndroid/clash_for_windows_pkg#183]
我cfw-bypass加了一些自己想不走代理软件的站点，但每次从睡眠、休眠恢复后，LAN设置的bypass就会恢复成以下这样（似乎是windows默认的）
localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;192.168.*;;windows10.microdone.cn

必须重开cfw，或者进cfw重新关开一次System Proxy才恢复有效。

**Comment by Fndroid** [comment]
cfw 并无类似逻辑（休眠恢复时修改系统代理设置），系统代理设置是所有软件都能修改的，请检查是否有其他软件（尤其是代理类）也在后台活跃

**Comment by yhnbgfd** [comment]
我的系统是睡眠恢复后，所有地址都不通了。

**Comment by Fndroid** [comment]
refer: https://github.com/Fndroid/clash_for_windows_pkg/issues/312
