### ISSUE TITLE
希望connections界面的每条链接下边都可以显示所属策略组的名称

### ISSUE THREAD

**Issue by s1mple11** [Fndroid/clash_for_windows_pkg#1832]
描述如下：
我有个小需求，希望connections界面的链接旁能够显示该链接所属的策略组的名称；
如我的配置文件中苹果的域名被分类在”苹果服务“策略组中，而我希望能在苹果的域名旁看到”苹果服务“
ios端同类app quantumult x效果如图
![image](https://user-images.githubusercontent.com/53406185/116093314-242d6180-a6d9-11eb-9369-8a338c1b7892.png)

**Comment by s1mple11** [comment]
![image](https://user-images.githubusercontent.com/53406185/116094761-62775080-a6da-11eb-9801-f458d31b2c0c.png)
就是希望能在图示区域显示策略组名称

**Comment by Fndroid** [comment]
下个版本支持
![image](https://user-images.githubusercontent.com/16091562/116102217-1b408e00-a6e1-11eb-858d-7183c60dd2ae.png)

**Comment by s1mple11** [comment]
> 下个版本支持
> ![image](https://user-images.githubusercontent.com/16091562/116102217-1b408e00-a6e1-11eb-858d-7183c60dd2ae.png)
非常感谢！大佬辛苦了

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
