### ISSUE TITLE
macOS下tun模式无法连网

### ISSUE THREAD

**Issue by yhl452493373** [Fndroid/clash_for_windows_pkg#1833]
mixin中配置了tun，其enable设为true，整个系统无法连网，节点检测时全部超时。将tun的enable改为false就好了

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

macOS 11.3

**描述**

mixin中配置了tun，其enable设为true，整个系统无法连网，节点检测时全部超时。将tun的enable改为false就好了

**复现**

1. 进入'Settings'
2. 拖动到'Profile Mixin'
3. 点击YAML后的'Edit'
4.将tun下的enable设为true，保存
5. 触发问题

**日志**

time="2021-04-27T13:25:39+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:39+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:39+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:39+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:39+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:39+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:39+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match DomainKeyword/google) to clients4.google.com error: iplc-sy-01.ddns-only.xyz:53255 connect error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:39+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match DomainKeyword/google) to clients4.google.com error: iplc-sy-01.ddns-only.xyz:53255 connect error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:40+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:40+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:40+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:40+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:40+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:40+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:41+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:41+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:41+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:41+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:41+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:41+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:41+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:41+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:41+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:41+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:41+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:41+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/cn) to p12-caldav.icloud.com.cn error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/cn) to p12-caldav.icloud.com.cn error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/cn) to p12-caldav.icloud.com.cn error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:42+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:43+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:43+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:43+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:43+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:43+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:43+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:45+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:45+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:45+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:45+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:45+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:45+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:45+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:45+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:45+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:45+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:45+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:45+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:50+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:50+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:50+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:50+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:50+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:51+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:59+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainKeyword/microsoft) to self.events.data.microsoft.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:59+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainKeyword/microsoft) to self.events.data.microsoft.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:25:59+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainKeyword/microsoft) to self.events.data.microsoft.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:14+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainKeyword/microsoft) to self.events.data.microsoft.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:14+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainKeyword/microsoft) to self.events.data.microsoft.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:14+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainKeyword/microsoft) to self.events.data.microsoft.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:18+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainSuffix/windows.com) to skydrive.wns.windows.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:21+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:21+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:21+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:21+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to img.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:21+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:21+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/ithome.com) to www.ithome.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:24+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match DomainKeyword/google) to clients4.google.com error: iplc-sy-01.ddns-only.xyz:53255 connect error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:24+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match DomainKeyword/google) to clients4.google.com error: iplc-sy-01.ddns-only.xyz:53255 connect error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:25+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match DomainKeyword/google) to oauthaccountmanager.googleapis.com error: iplc-sy-01.ddns-only.xyz:53255 connect error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:25+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match DomainKeyword/google) to oauthaccountmanager.googleapis.com error: iplc-sy-01.ddns-only.xyz:53255 connect error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:29+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainKeyword/microsoft) to self.events.data.microsoft.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:29+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainKeyword/microsoft) to self.events.data.microsoft.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:29+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainKeyword/microsoft) to self.events.data.microsoft.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:44+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainKeyword/microsoft) to self.events.data.microsoft.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:44+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainKeyword/microsoft) to self.events.data.microsoft.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:44+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainKeyword/microsoft) to self.events.data.microsoft.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:58+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainKeyword/microsoft) to self.events.data.microsoft.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:58+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainKeyword/microsoft) to self.events.data.microsoft.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:26:58+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainKeyword/microsoft) to self.events.data.microsoft.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:27:06+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainSuffix/windows.com) to skydrive.wns.windows.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:27:12+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainKeyword/microsoft) to self.events.data.microsoft.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:27:12+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainKeyword/microsoft) to self.events.data.microsoft.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:27:12+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainKeyword/microsoft) to self.events.data.microsoft.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:27:15+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/baidu.com) to suggestion.baidu.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:27:15+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/baidu.com) to suggestion.baidu.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:27:16+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match DomainKeyword/github) to github.com error: iplc-sy-01.ddns-only.xyz:53255 connect error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:27:16+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match DomainKeyword/github) to github.com error: iplc-sy-01.ddns-only.xyz:53255 connect error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:27:26+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainKeyword/microsoft) to self.events.data.microsoft.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:27:26+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainKeyword/microsoft) to self.events.data.microsoft.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:27:26+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainKeyword/microsoft) to self.events.data.microsoft.com error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:27:29+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match DomainKeyword/github) to alive.github.com error: iplc-sy-01.ddns-only.xyz:53255 connect error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:27:29+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match DomainKeyword/github) to alive.github.com error: iplc-sy-01.ddns-only.xyz:53255 connect error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:27:30+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match DomainKeyword/github) to alive.github.com error: iplc-sy-01.ddns-only.xyz:53255 connect error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:27:30+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match DomainKeyword/github) to alive.github.com error: iplc-sy-01.ddns-only.xyz:53255 connect error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:27:32+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match DomainKeyword/google) to oauthaccountmanager.googleapis.com error: iplc-sy-01.ddns-only.xyz:53255 connect error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:27:32+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match DomainKeyword/google) to oauthaccountmanager.googleapis.com error: iplc-sy-01.ddns-only.xyz:53255 connect error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:27:32+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match DomainKeyword/github) to alive.github.com error: iplc-sy-01.ddns-only.xyz:53255 connect error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:27:32+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match DomainKeyword/github) to alive.github.com error: iplc-sy-01.ddns-only.xyz:53255 connect error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:27:37+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match DomainKeyword/github) to alive.github.com error: iplc-sy-01.ddns-only.xyz:53255 connect error: all DNS requests failed, first error: gateway not found"
time="2021-04-27T13:27:37+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match DomainKeyword/github) to alive.github.com error: iplc-sy-01.ddns-only.xyz:53255 connect error: all DNS requests failed, first error: gateway not found"

**截图**

<img width="850" alt="01F87671-A5CF-472F-9B45-57794798E474" src="https://user-images.githubusercontent.com/26134687/116190116-9f842700-a75c-11eb-96b6-10ce675eb1ca.png">

<img width="850" alt="8D2F5DFA-ACFC-4395-AF4B-DA3B2E09B5F9" src="https://user-images.githubusercontent.com/26134687/116190134-a6ab3500-a75c-11eb-9417-8612437fdaf8.png">

从日志来说，似乎是说我网关没找到，但是我的网关192.168.0.1是可以ping的，同时只要把tun模式关闭，tap模式也能正常访问

**Comment by Fndroid** [comment]
``macOS-auto-detect-interface``这个值是什么？如果是false，把``interface-name``注释掉

**Comment by OG-C** [comment]
劫持DNS错了吧。
  dns-hijack:
    - 198.18.0.2:53

**Comment by yi-Xu-0100** [comment]
@OG-C Mac 和 Windows 的配置不一样。

**Comment by Fndroid** [comment]
这个是因为系统更新后路由表Flags改变导致的，core那边应该也改完了，但要等它发release才能恢复正常，目前不能用``macOS-auto-detect-interface``这个选项，只能手动设置``interface-name``

**Comment by yhl452493373** [comment]
> 这个是因为系统更新后路由表Flags改变导致的，core那边应该也改完了，但要等它发release才能恢复正常，目前不能用`macOS-auto-detect-interface`这个选项，只能手动设置`interface-name`

感谢，确实，指定网卡就可以了，期待core发release
