### ISSUE TITLE
0.15.4 在M1 Macbook air（MacOs 11.3）上可以安装 但是无法打开 报错。

### ISSUE THREAD

**Issue by Lanjerman** [Fndroid/clash_for_windows_pkg#1835]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
M1 Macbook Air MacOs 11.3 / Clash for windows 0.15.4
[//]: # (平台及版本号)
M1 Macbook Air MacOs 11.3 / Clash for windows 0.15.4
**描述**
本程序 0.15.4 在M1 Macbook air（MacOs 11.3）上可以安装 但是无法打开 报错。
[//]: # (请具体并清楚地描述遇到的问题)
我之前的电脑版本是11.1或者11.2 正常运行本程序的0.15.4 版本 没有任何异常。但是前天更新到MacOS 11.3 之后，发现无法关闭Clash 的开机启动开关，所以卸载，从本仓库下载软件，重新安装，然后就发现了这个问题。

总结一下：
M1 MacOS 11.2: Clash 0.15.4 正常 
M1 MacOS 11.3: Clash 0.15.4 可以安装，无法打开。显示文件以损坏。
M1 MacOS 11.3：Clash 0.13 正常

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入本仓库下载软件
2. 点击安装
3. 打开程序
4. 触发问题：无法打开，显示程序已经损坏。

**预期行为**

[//]: # (清晰地描述期望看到的行为)
希望大佬可以修复此问题。十分感谢。
**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
报什么错，截个图看看

**Comment by Lanjerman** [comment]
以前安装你们的Clash 的时候 我可以在安全与隐私那里点击“仍然打开”就可以使用你们的app了 但是现在的情况是0.15.4 安装好之后并没有在安全性与隐私那里显示“仍然打开” 而是直接说文件已经损坏，让我删除。幸亏我之前备份了0.13 版本的clash，目前还可以正常使用。

**Comment by Lanjerman** [comment]
<img width="593" alt="截屏2021-04-29 上午10 22 28" src="https://user-images.githubusercontent.com/83381379/116509818-81eac500-a8f6-11eb-837c-af932ae7057f.png">
<img width="532" alt="截屏2021-04-29 上午10 24 45" src="https://user-images.githubusercontent.com/83381379/116509834-86af7900-a8f6-11eb-83b1-480a748b9337.png">

**Comment by Lanjerman** [comment]
希望大佬可以修复一下这个问题 下个版本比如0.15.5，可以顺利安装，让更多的小白可以便捷安装。不必费心做其他任何操作。感谢了大佬

**Comment by Lanjerman** [comment]
虽然我想通过终端输入命令的方式可以解决这个问题，但是如此安装的过程对小白用户来说还是不够友好的。如果可以像之前的版本那样不必费心做其他任何操作，一键安装，我想必定可以得到很好的使用体验。感谢大佬的努力。真的 这么快得到您的回复，我真的受宠若惊。

**Comment by Lanjerman** [comment]
补充一点：我刚才测试了0.14.8-0.15.4 的各个版本，在M1 Macbook Air MacOS 11.3 上面安装之后均无法顺利打开。

**Comment by yi-Xu-0100** [comment]
@Lanjerman 个人觉得，这类软件本身不适合小白使用。🙊

**Comment by Lanjerman** [comment]
> @Lanjerman 个人觉得，这类软件本身不适合小白使用。🙊

将复杂的功能装进一个简单的盒子里，我想这也许是开发者的责任和魅力吧。我自己是设计师一枚，虽然行业相差甚远，但总觉得有很多共同之处。

**Comment by Fndroid** [comment]
实际上这个隔离标识是系统加的，除非签名和公证了，不然肯定一直都有的，至于为什么在系统里不能允许，这个我也不清楚了。

**Comment by edgexyz** [comment]
`sudo spctl --master-disable`🌚
<img width="454" alt="Screen Shot 2021-05-02 at 10 20 03" src="https://user-images.githubusercontent.com/32131214/116800036-fb212c80-ab2f-11eb-9937-12e96d88b44c.png">

**Comment by Lanjerman** [comment]
好方法，顺利解决了。太感谢各位了。
