### ISSUE TITLE
0.15.5更新后卡巴斯基报恶意对象

### ISSUE THREAD

**Issue by journey-to** [Fndroid/clash_for_windows_pkg#1838]
今天(2021-04-30)更新了0.15.5版本，然后卡巴斯基报恶意对象
![1](https://user-images.githubusercontent.com/24454046/116663743-1d993580-a9ca-11eb-8491-d5ceac874e44.png)

之前版本无此问题

**Comment by wasonliu** [comment]
同样遇到此问题，我的卡巴斯基版本号为21.3.10.391(b)
[![gEurCT.png](https://z3.ax1x.com/2021/04/30/gEurCT.png)](https://imgtu.com/i/gEurCT)

**Comment by kingforme** [comment]
clash中的clash-core-service.exe也会被卡巴斯基报毒

**Comment by ColanCN** [comment]
![Uploading 1.png…]()
![2](https://user-images.githubusercontent.com/35485676/116691524-7a5a1780-a9ed-11eb-881b-db0d39482a72.png)
我也遇到了，什么情况啊？

**Comment by ColanCN** [comment]
我感觉是TAP和TUN的强制代理网络的程序被卡巴斯基拦截了

**Comment by ColanCN** [comment]
估计是卡巴斯基和clash的虚拟网卡代理模式要二选一了

**Comment by Haruhikoo** [comment]
我也遇到了这个问题 报错的信息都是一样的

**Comment by shy86** [comment]
我用旧版本现在也报毒了，可能是卡巴斯基的病毒库升级导致

**Comment by ColanCN** [comment]
确定了卡巴斯基与TAP不兼容，但是TUN模式不受影响。需要用虚拟网卡的同学转向TUN吧！

**Comment by monywoex** [comment]
也遇到同样问题,并且用virustotal扫描,有三个杀毒软件报毒了.

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/116752384-66b6ad00-a9fd-11eb-8507-9b6dcc8d396d.png)

Same issue here.

**Comment by LittleGrocery** [comment]
我也遇到了一样的问题
![微信截图_20210501143834](https://user-images.githubusercontent.com/44335381/116773878-1c7c0d00-aa8b-11eb-8930-8c64419680c7.png)

**Comment by lordageluo** [comment]
降级到0.15.2没有报错。

**Comment by monywoex** [comment]
不对啊,怎么今天再看,有六个杀毒软件报毒了????

**Comment by RnJ4** [comment]
0.15.4也报毒
卡巴添加排除项C:\Users\你的用户名\AppData\Local\Programs\Clash for Windows\resources\static\files\win\x64\service\clash-core-service.exe

**Comment by kongkongzzz** [comment]
腾讯电脑管家也报错，降级到0.15.4以后不再报错

> （不要问为什么用腾讯电脑管家）

![image](https://user-images.githubusercontent.com/39525252/116790020-b4f2ab80-aae4-11eb-8a26-d588ba56129a.png)

**Comment by Fndroid** [comment]
这个``clash-core-service``是需要注册成服务/守护进程，然后利用管理员/root权限启动TUN，这个过程不是正常的系统提权（因为正常系统提权每次都要弹出UAC/输入用户密码），如果你不需要用TUN模式，那就让杀软把它杀掉也没问题，不会影响其他功能。

**Comment by ColanCN** [comment]
> 0.15.4也报毒
> 卡巴添加排除项C:\Users\你的用户名\AppData\Local\Programs\Clash for Windows\resources\static\files\win\x64\service\clash-core-service.exe

我今天尝试把这个软件加入到排除项了，但是卡巴斯基貌似还在阻拦。

**Comment by LittleGrocery** [comment]
在线扫了一下  结果大家看下：https://www.virustotal.com/gui/file/3aa56ff260941fe903dd0027d069ac9317eb7704317076c328ade36710f929c0/behavior/C2AE

**Comment by Hackcn023** [comment]
卡巴斯基误报解除
![1](https://user-images.githubusercontent.com/61652547/116991070-9966eb00-ad06-11eb-8433-b6209fd41523.png)
![2](https://user-images.githubusercontent.com/61652547/116991085-9cfa7200-ad06-11eb-8237-15488f7bf97c.png)
