### ISSUE TITLE
为什么我的软件里面vmess的节点都显示timeout

### ISSUE THREAD

**Issue by zgithubx-code** [Fndroid/clash_for_windows_pkg#1839]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)windows10,版本号0.15.4

**描述**

[//]: # (请具体并清楚地描述遇到的问题)使用当中所有ss的节点可以连接，vmess节点测试就是timeout，无论如何更新节点文件，手头一共两台机器安装，无法连接vmess节点的机器只不过是安装0.1.53版本，然后在线升级。另外一台直接安装0.1.54版本的正常使用没问题。

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'clash for windows'软件。
2. 点击'更新软件版本'
3. 重新测试接连连接
4. vmess节点显示timeout无法使用

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
vmess对系统时间有要求

**Comment by zgithubx-code** [comment]
系统时间什么时候出问题了，可能跟我外挂其他系统启动设备有关系，更新一下时间，好用了，多谢作者回复！
