### ISSUE TITLE
「功能」隐藏左下角连接时长，或者可以配置显示到「分钟」

### ISSUE THREAD

**Issue by wenfangdu** [Fndroid/clash_for_windows_pkg#1843]
**描述**
添加选项可以隐藏左下角连接时长，或者可以配置显示到「分钟」，显示到秒看的都焦虑

**Comment by akw5454521** [comment]
你的服务商是按秒计费的嘛……

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases

**Comment by SplitGemini** [comment]
为什么不支持dd
