### ISSUE TITLE
「功能」切换代理模式时，保留原服务器选择

### ISSUE THREAD

**Issue by wenfangdu** [Fndroid/clash_for_windows_pkg#1844]
**描述**
目前 Global Mode 和 Rule Mode 的服务器选择是分开记忆的，希望添加选项切换代理模式时，保留原选项，如原选项不可用，则默认回退到第一个选项，例如：Rule Mode 下选择服务器 2，切换到 Global Mode 时保留服务器 2 的选择（不管上次 Global Mode 下所选的服务器），如果服务器 2 不可用，则回退到第一个选项。

**Comment by yi-Xu-0100** [comment]
@wenfangdu Rule Mode 有很多组，怎么决定 Global Mode 用 Rule Mode 中哪个组的选择呢？

**Comment by wenfangdu** [comment]
@yi-Xu-0100 用 Proxies 下面？

**Comment by yi-Xu-0100** [comment]
@wenfangdu 组的名字是自己可以更改的，我的就不是这个名字。
