### ISSUE TITLE
Connections 列表顯示套用的 profile

### ISSUE THREAD

**Issue by bestpika** [Fndroid/clash_for_windows_pkg#1847]
**描述**

在前一版的時候每個 Connection 在列表會顯示此連線套用的 profile
但現在卻一定要點進去才看得到，這樣變得很不方便
希望可以放回去

謝謝

**其他说明**

![image](https://user-images.githubusercontent.com/5698157/116772813-f868fd80-aa83-11eb-9713-69030b592ef9.png)

**Comment by yi-Xu-0100** [comment]
@bestpika 
![image](https://user-images.githubusercontent.com/25523606/116772823-1171ae80-aa84-11eb-8e7e-67e43c134cdd.png)

看看选择的是啥？更换试试

**Comment by bestpika** [comment]
@yi-Xu-0100 我剛發現了，我本來選 Proxy 卻看不到，要選 Group 才看得到
可是我的規則檔沒有設定 group 只有設定 proxies
所以這算 bug?

**Comment by bestpika** [comment]
我的規則如下

```rules:
  - DOMAIN,httpbin.org,SpeedJP
  - DOMAIN-SUFFIX,dmm.co.jp,SpeedJP
  - DOMAIN-SUFFIX,dmm.com,SpeedJP
  - MATCH,DIRECT
proxies:
  - name: SpeedJP
  ... 省略
  - name: NetflixJP
  ... 省略
proxy-groups: []
proxy-providers: {}
rule-providers: {}
```

**Comment by yi-Xu-0100** [comment]
@bestpika 好像 proxy 模式下只显示 group 中的 proxy。比如在 proxy 模式下，我规则直接走的 direct 也无法显示。感觉是 bug

**Comment by bestpika** [comment]
@yi-Xu-0100 因為設定不變的狀況下換個版本行為就不一樣了
那這應該算是 bug

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
