### ISSUE TITLE
[FR] 添加新快捷键可以「打开/关闭」CFW

### ISSUE THREAD

**Issue by wenfangdu** [Fndroid/clash_for_windows_pkg#1849]
**描述**
类似微信的「打开微信」快捷键，添加的新快捷键可以快速「打开/关闭」CFW。  
一些功能例如切换服务器节点，只能通过界面来操作，如果有快捷键的话，会方便很多。

**Comment by yi-Xu-0100** [comment]
@wenfangdu 打开主界面吗？个人觉得没有特别的需求总是打开主界面去设置吧，大部分的功能开关，应该都支持快捷键了。毕竟这主要还是个后台应用，更多时候是配置好了就不管它了吧。

**Comment by wenfangdu** [comment]
@yi-Xu-0100 是的，打开主界面。切换节点的操作只能打开之后才能做吧，没有相应的快捷键，这个操作使用的还是非常频繁的。目前只能 `Alt` + `Tab` 来回切换，如果有快捷键能让 CFW 随叫随到是最好了。

**Comment by gtang8** [comment]
> **描述**
> 类似微信的「打开微信」快捷键，添加的新快捷键可以快速「打开/关闭」CFW。
> 一些功能例如切换服务器节点，只能通过界面来操作，如果有快捷键的话，会方便很多。

Nice suggestion

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
