### ISSUE TITLE
对clash-core-service.exe报毒的杀软数量已经增加到6家了

### ISSUE THREAD

**Issue by monywoex** [Fndroid/clash_for_windows_pkg#1850]
希望能够引起重视,是否是上有代码被人植入了恶意代码,还是真的只是误报.
因为最开始是自己的卡巴斯基报毒,然后,把文件放到virustotal上面去查,最开始只有两个杀软报毒,然后我发现是有3个杀软报毒.刚才我又去让virustotal重新扫描了一下,已经有六家了,
[https://www.virustotal.com/gui/file/3aa56ff260941fe903dd0027d069ac9317eb7704317076c328ade36710f929c0/detection](https://www.virustotal.com/gui/file/3aa56ff260941fe903dd0027d069ac9317eb7704317076c328ade36710f929c0/detection)

![Snipaste_2021-05-01_20-25-54](https://user-images.githubusercontent.com/44083619/116782527-36821380-aabc-11eb-9fd7-84d120e79572.png)

**Comment by IlO0OlI** [comment]
0.14.9版本的Clash for Windows中clash-core-service.exe没有报毒，用这个版本试试。
https://www.virustotal.com/gui/file/c46243fda7095dbe24d02146d606e5cd32895410835e4865916816f7e5e17ae9/detection

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/1838#issuecomment-830731550
