### ISSUE TITLE
关于增强托盘的一点建议

### ISSUE THREAD

**Issue by OG-C** [Fndroid/clash_for_windows_pkg#1851]
**描述**
建议默认嵌入托盘，背景透明，隐藏小猫咪LOGO。贴边可以隐藏。

**其他说明**
目前版本有个小问题，拖动到任务栏，全屏操作时，会被任务栏挡住（详见录像）。不知是否和我用的任务栏半透明工具TranslucentTB有关。我另外使用的流量监控工具TrafficMonitor无此问题。期待能完善，从而能替代其他流量监控工具。以后就可以少装一个工具了。

https://user-images.githubusercontent.com/82382147/116800042-04aa9480-ab30-11eb-9c44-ba44e5dc7aa0.mp4

**Comment by yi-Xu-0100** [comment]
Duplicate of #1800
