### ISSUE TITLE
Netflix无法串流

### ISSUE THREAD

**Issue by PIndividual** [Fndroid/clash_for_windows_pkg#1852]
**描述**
即使在使用
那些专门解锁流媒体的服务到时候，Netflix，hulu等网页仍会报错或者提示关闭代理
**其他说明**
希望能出一个教程，使用clash避开vpn检测或者在后续添加这样的支持

**Comment by yi-Xu-0100** [comment]
@PIndividual 感觉至少不是 CFW 的问题。

core issue: <https://github.com/Dreamacro/clash/issues>

**Comment by Fndroid** [comment]
一般是规则问题，如果用Global都不行，那就是服务端节点问题
