### ISSUE TITLE
0.15.5 被卡巴斯基报毒

### ISSUE THREAD

**Issue by Sylyia** [Fndroid/clash_for_windows_pkg#1854]
内核服务和更新程序被卡巴斯基报毒，并回滚了全部文件。
![Snipaste_2021-05-02_21-17-37](https://user-images.githubusercontent.com/54952917/116814733-e757e380-ab8c-11eb-82bb-d677c8cd24cd.png)
![Snipaste_2021-05-02_21-19-54](https://user-images.githubusercontent.com/54952917/116814734-e921a700-ab8c-11eb-81f2-8daabf6e4549.png)
![Snipaste_2021-05-02_21-12-49](https://user-images.githubusercontent.com/54952917/116814741-ede65b00-ab8c-11eb-9c36-d71760d3d09e.png)
![Snipaste_2021-05-02_21-13-56](https://user-images.githubusercontent.com/54952917/116814743-ee7ef180-ab8c-11eb-97cb-df95a6804440.png)

**Comment by Nocch1** [comment]
腾讯管家也报了

**Comment by yi-Xu-0100** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/1838#issuecomment-830731550

**Comment by Sylyia** [comment]
> [第1838章（评论）](https://github.com/Fndroid/clash_for_windows_pkg/issues/1838#issuecomment-830731550)

这样并没有解决问题，除非卸载报毒的杀软，否则依旧无法使用新版本。

**Comment by yi-Xu-0100** [comment]
@Sylyia 这是重复的 issue ，你可以去 #1838 和别人讨论更多的解决办法而不是多开一个 issue。
