### ISSUE TITLE
tun网卡无法创建

### ISSUE THREAD

**Issue by swwrww** [Fndroid/clash_for_windows_pkg#1855]
mixin配置正确
server mode也绿色运行 tun.dll也放在正确位置
无法创建tun网卡，tap模式正常
错误日志
level=info msg="[Wintun] WintunOpenAdapter: Device object file did not appear: 系统找不到指定的路径。 (Code 0x00000003)"

**Comment by yi-Xu-0100** [comment]
core issue: <https://github.com/Dreamacro/clash/issues>

**Comment by RnJ4** [comment]
重新安装试一下，可能是一个文件被误报干掉了
https://github.com/Fndroid/clash_for_windows_pkg/issues/1838

**Comment by swwrww** [comment]
谢谢,更新到Wintun 0.10.4版本后,可以正常使用了!
