### ISSUE TITLE
更细失败可以恢复上一次的服务器列表

### ISSUE THREAD

**Issue by netsonicyxf** [Fndroid/clash_for_windows_pkg#1856]
**描述**
今天某机场宕机，事前不知道，更新后发现服务器列表被清空了。
能否加个 “更细失败后，自动/手动 恢复上一次的服务器列表”的功能？

**Comment by yi-Xu-0100** [comment]
@netsonicyxf 理论上，如果更新失败，则不会更新配置内容。所以，配置文件是更新成功的，但是配置内容为空了。

即远端的配置链接并没有失效。
