### ISSUE TITLE
Ignore local websites

### ISSUE THREAD

**Issue by codewithah** [Fndroid/clash_for_windows_pkg#1857]
**描述**
请具体并清楚地描述期望功能及期望的效果

Ignore some website

**其他说明**
其他补充内容

Hello.If you can add a  a Feature for windows client to ignore some local website that banned other countries IPs is very good
As you may know in some countries such as China and Iran some sensitive websites are just visible with local IPs
If you you can add a option in client to add this website by users to ignore this website is very good

By the way this option could be better;
For example windows client load this website from multiple repository

**Comment by Fndroid** [comment]
You can accomplish that by adding a rule like:

```
rules:
  - DOMAIN-SUFFIX,example.com,REJECT
```

**Comment by akw5454521** [comment]
By "ignore", you mean direct connect?

**Comment by codewithah** [comment]
> By "ignore", you mean direct connect?

Yes

**Comment by akw5454521** [comment]
- GEOIP,CN,DIRECT

Change CN to your country code

**Comment by codewithah** [comment]
Thank you I try

**Comment by mehdifirefox** [comment]
> 
> 
> You can accomplish that by adding a rule like:
> 
> ```yaml
> rules:
>   - DOMAIN-SUFFIX,example.com,REJECT
> ```

The sites list is very high
Please add a feature to the TXT file

**Comment by yi-Xu-0100** [comment]
@mehdifirefox use rule-provider: <https://lancellc.gitbook.io/clash/clash-config-file/rule-provider>

**Comment by mehdifirefox** [comment]
> 
> 
> @mehdifirefox use rule-provider: https://lancellc.gitbook.io/clash/clash-config-file/rule-provider

We should always change the file because of blocking servers

I think it's better to add this feature to the program. Be recorded forever

**Comment by yi-Xu-0100** [comment]
@mehdifirefox Use the [`parser`](https://docs.cfw.lbyczf.com/contents/parser.html#%E7%AE%80%E4%BE%BF%E6%96%B9%E6%B3%95-yaml) to append rules which will be added into the profile every time.
