### ISSUE TITLE
可否添加profile定时更新的功能？

### ISSUE THREAD

**Issue by yanghaigang** [Fndroid/clash_for_windows_pkg#186]
可否添加让Calsh for Windows 的profile定时更新的功能，比如每隔12小时或者24小时。因为有时Profile好几天没更新，但是旧的Profile里面的节点已经失效了，不知此功能是否可实现，谢谢！

**Comment by XiaoTeemo** [comment]
可否让软件运行自动更新，先通过代理更新，如果代理不可用，再尝试直连更新。

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
