### ISSUE TITLE
win10 clash在后台未关闭重启后"使用代理服务器"选项未自动关闭

### ISSUE THREAD

**Issue by EWinner1** [Fndroid/clash_for_windows_pkg#1860]
**信息**

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

版本	Windows 10 专业版
版本号	20H2
安装日期	‎2020/‎5/‎30
操作系统内部版本	19042.964
体验	Windows Feature Experience Pack 120.2212.2020.0

**描述**

win10 clash在后台未关闭重启后，系统设置中的"使用代理服务器"选项未自动关闭，显示为127.0.0.1加本地代理端口，导致开机后需要手动关闭才能上网

**复现**

[//]: # (请描述复现问题的步骤)

1. 打开软件，关闭界面保留后台；
2. 重启
3. 触发问题

**预期行为**

重启后代理应该是关闭状态

**日志**

**截图**

![捕获](https://user-images.githubusercontent.com/38932060/117090234-5cdcd300-ad8a-11eb-963a-f56f06719bab.PNG)

**其他说明**

**Comment by yi-Xu-0100** [comment]
Duplicate of #1750
