### ISSUE TITLE
无法安装Service Mode：点击install后无任何后续响应

### ISSUE THREAD

**Issue by asdfj2381k** [Fndroid/clash_for_windows_pkg#1861]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
win7 64

**描述**

无法安装Service Mode：点击install后无任何后续响应。

（我提问之前已经在issue里面把所有带有service mode关键词的问题都看过了，问题没解决。）

**Comment by asdfj2381k** [comment]
clash是最新的0.15.5

**Comment by asdfj2381k** [comment]
我先把logs清空，然后去点击service mode里面的install后，过5秒左右再打开logs，里面没任何logs输出。

**Comment by asdfj2381k** [comment]
我这个win7系统还是刚装好的msdn原版，里面除了clash啥东西都没有。   （所以我就奇了怪了。）

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/questions.html

**Comment by asdfj2381k** [comment]
@Fndroid 

好像提示我缺少什么依赖？  没看明白。  

这个错误也和：https://github.com/Fndroid/clash_for_windows_pkg/issues/1627 里面的提示不一样。

![image](https://user-images.githubusercontent.com/56584082/117125487-2758d980-adcc-11eb-955f-0f5383a8b869.png)

**Comment by yi-Xu-0100** [comment]
@asdfj2381k 

![image](https://user-images.githubusercontent.com/25523606/117125674-70109280-adcc-11eb-9ec6-c2c7219d5ef8.png)

**Comment by asdfj2381k** [comment]
@yi-Xu-0100 

是这个吗，好像已经装了。
![image](https://user-images.githubusercontent.com/56584082/117125785-933b4200-adcc-11eb-9b0e-f92e5b42e74b.png)

**Comment by yi-Xu-0100** [comment]
@asdfj2381k 查了下，报的错好像是需要 4.5 以上

**Comment by asdfj2381k** [comment]
@yi-Xu-0100    谢谢，我安装了新版本的.net framework后问题解决了。
