### ISSUE TITLE
请教下有没有办法把windows热点功能分享的网络也走clash

### ISSUE THREAD

**Issue by jaoyina** [Fndroid/clash_for_windows_pkg#1862]
我的需求是把网络分享给游戏机用，之前用的ps4是可以用代理的，所以只需要打开allow lan，在ps4端设置代理就行
但最近用xbox没找到可以设置代理的地方，于是我想通过windows 10的热点功能把网络share给xbox，但发现好像并没有走clash，打开system proxy也没用，有没有其他办法可以实现这个需求？

**Comment by coolyzp** [comment]
配置一下TUN模式，并把Allow LAN打开

**Comment by Fndroid** [comment]
Windows下不能，macOS可以
