### ISSUE TITLE
clash windows tun模式 作为网关 没有转发其他设备的请求

### ISSUE THREAD

**Issue by LinSHP** [Fndroid/clash_for_windows_pkg#1865]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
系统：windows10 专业版 19042.928
clash：0.15.5

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
想用clash的tun模式作为其他设备的网关，以进行代理请求，参考文档进行了设置https://docs.cfw.lbyczf.com/contents/tun.html

在mac上已经测试可以作为网关处理并转发其他设备（switch，ps4）的请求

但是windows上不行，设置switch时，测试网络提示无法连接，通过抓包可以看到这个请求

![image](https://user-images.githubusercontent.com/19932215/117463761-97a95b80-af82-11eb-8eb4-8ad8e17f2de2.png)

54是switch的ip，47是windows的ip，switch到23.210.215.66的tcp包没有发送到，重传了最终导致switch连接失败

通过clash的日志也没看到这个ip的请求，是哪里还要设置吗？。

**复现**

[//]: # (请描述复现问题的步骤)

按照描述操作

**预期行为**

[//]: # (清晰地描述期望看到的行为)
可以转发其他设备请求

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)
mac是可以的

**Comment by LinSHP** [comment]
> [#1862 (comment)](https://github.com/Fndroid/clash_for_windows_pkg/issues/1862#issuecomment-833461650)

所以老哥是为啥呢，是因为windows没有IP forwarding类似的功能嘛

就是系统本身能否实现，可以实现的话有相应思路吗，我看看能不能整整，还是说本身就是不行的

**Comment by Fndroid** [comment]
win和mac都可以转发，但是因为windows的interface-name绑定是设置local address实现的，转发打开之后这个这个连接就被转发回来，然后回环。
