### ISSUE TITLE
关于配置文件的规则不考虑一下“非”这样的逻辑吗

### ISSUE THREAD

**Issue by BILLYx1120** [Fndroid/clash_for_windows_pkg#1866]
**描述**
举个例子，我想实现“除了某些特定的国家以外，剩下的在geoip上的国家全部走某个代理”，如果可以用“除了”那么会非常方便吧。

**其他说明**
...如果有其他更优雅的实现这个需求的方法的话也欢迎提及

**Comment by Fndroid** [comment]
clash core issue, refer: https://github.com/Dreamacro/clash/issues
