### ISSUE TITLE
求帮助，我的clash用不了了，订阅更新成功但是无节点，MAC版clash可以用。

### ISSUE THREAD

**Issue by shawchen123** [Fndroid/clash_for_windows_pkg#1868]
我的Windows版clash用不了了，同样的订阅地址，MAC版clash和安卓版都可以正常上外网，唯独win版无法使用了，订阅地址更新成功但是没有任何节点显示，我是小白不知道哪里出了问题，附上截图，求大家帮我看一下，感谢。![mmexport1620463910650.png](https://user-images.githubusercontent.com/56788618/117533191-14d5de80-b01e-11eb-8ecc-c7b3ddd69995.png)![mmexport1620463908096.png](https://user-images.githubusercontent.com/56788618/117533192-16070b80-b01e-11eb-805a-e801d6dd7948.png)![mmexport1620463905899.png](https://user-images.githubusercontent.com/56788618/117533193-17d0cf00-b01e-11eb-848c-c8bcd603c45c.png)

**Comment by yi-Xu-0100** [comment]
@shawchen123 能给出日志吗？点击这里

![image](https://user-images.githubusercontent.com/25523606/117533248-56ff2000-b01e-11eb-883b-fa43723419e3.png)

**Comment by shawchen123** [comment]
> @shawchen123 能给出日志吗？点击这里
> 
> ![image](https://user-images.githubusercontent.com/25523606/117533248-56ff2000-b01e-11eb-883b-fa43723419e3.png)
> 
> 

你好，日志内容是：
time="2021-05-08T16:50:09+08:00" level=info msg="RESTful API listening at: 127.0.0.1:54451"
time="2021-05-08T16:50:09+08:00" level=warning msg="Failed to start Redir UDP Listener: not supported on current platform"
time="2021-05-08T16:50:09+08:00" level=info msg="Redir proxy listening at: :7892"
time="2021-05-08T16:50:09+08:00" level=info msg="Mixed(http+socks5) proxy listening at: :7890"
time="2021-05-08T16:50:21+08:00" level=info msg="DNS server listening at: 0.0.0.0:53"
time="2021-05-08T16:50:27+08:00" level=info msg="DNS server listening at: 0.0.0.0:53"
time="2021-05-08T16:56:11+08:00" level=info msg="DNS server listening at: 0.0.0.0:53"
time="2021-05-08T16:56:19+08:00" level=info msg="DNS server listening at: 0.0.0.0:53"

**Comment by yi-Xu-0100** [comment]
@shawchen123 检测你的配置文件，将 dns 这个条目里面的 listen 那一行删除试试，还有将 enable 那一行删除或者设置为 false

**Comment by shawchen123** [comment]
> @shawchen123 检测你的配置文件，将 dns 这个条目里面的 listen 那一行删除试试，还有将 enable 那一行删除或者设置为 false

![mmexport1620464973251.png](https://user-images.githubusercontent.com/56788618/117533579-2ddf8f00-b020-11eb-8aa9-9765203e6f33.png)请问你说的是这两个地方吗？

**Comment by yi-Xu-0100** [comment]
@shawchen123 是的

**Comment by shawchen123** [comment]
> @shawchen123 好吧，是的，我看错了
> 应该改的是你订阅的配置里的字段

感谢你的帮助，我在另一位朋友的帮助下可以用了，用他提供的地址转换了一下订阅链接可以用了。

**Comment by wj20010915** [comment]
你好，请问可以问一下怎么解决吗？我也是这个问题

**Comment by shawchen123** [comment]
> 

我在另一位朋友的帮助下可以用了，用他提供的地址转换了一下订阅链接可以用了。

**Comment by Steven-w-848** [comment]
你好，能具体说说怎么操作吗，我也遇到了这个情况，很头疼

**Comment by jochemyip** [comment]
clashback2me.cn转换订阅链接

**Comment by Automan1218** [comment]
请问什么是转换订阅链接啊
