### ISSUE TITLE
配置界面的小问题

### ISSUE THREAD

**Issue by Scelus-et-poena** [Fndroid/clash_for_windows_pkg#1873]
[//]: # (如不按模版填写，则issue将被直接关闭)

为什么我的配置界面填充不满

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ x ] 已经尝试更新到最新版本，问题依旧存在
- [ x ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

![Snipaste_2021-05-09_21-24-02](https://user-images.githubusercontent.com/45129699/117573975-8b053e80-b10d-11eb-8949-c7bedba6b28e.png)
![Snipaste_2021-05-09_21-24-23](https://user-images.githubusercontent.com/45129699/117573977-8c366b80-b10d-11eb-8858-f60ec978f6d9.png)

**描述**

我自己家里的有这种情况，公司的电脑就没有

**复现**

暂时不知道，我删除重新订阅和卸载重装都试了，还是一样的

**预期行为**

希望能将整个界面填充

**日志**

估计没有

**截图**

![Snipaste_2021-05-09_21-22-50](https://user-images.githubusercontent.com/45129699/117574075-fa7b2e00-b10d-11eb-8bd0-e75d97789545.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
@Scelus-et-poena 怀疑是就一个的原因，因为我拉这么长，发现，变成双栏了。。。

**Comment by Scelus-et-poena** [comment]
我就一个啊😂

**Comment by Fndroid** [comment]
因为足够长就会显示多个，和proxies一样
