### ISSUE TITLE
clash开启系统代理后，默认将172等网段自动排除代理，如何设置不排除呢？

### ISSUE THREAD

**Issue by seryte** [Fndroid/clash_for_windows_pkg#1874]
我访问远程的172网段，需要使用代理，而打开clash后，win10的代理配置中默认是排除了172网段的，我尝试在config.yaml中的cfw-bypass将172网段取消掉，重启了clash后，照样还是排除的，怎么处理这个呢？现在是每次开了clash后，手动在win10的代理设置里边，将排除的172网段给删除掉，然后才能使用
```
mixed-port: 7890
allow-lan: false
external-controller: 127.0.0.1:57764
log-level: info
secret: ''

cfw-bypass:
  - localhost
  - 127.*

```
![image](https://user-images.githubusercontent.com/17977783/117575089-e84fbe80-b112-11eb-8a39-c3f0db35e5f5.png)

**Comment by yi-Xu-0100** [comment]
@seryte 
![image](https://user-images.githubusercontent.com/25523606/117575272-ae32ec80-b113-11eb-8147-7c65d9216f97.png)

**Comment by seryte** [comment]
> @seryte
> ![image](https://user-images.githubusercontent.com/25523606/117575272-ae32ec80-b113-11eb-8147-7c65d9216f97.png)

现在的问题就是172被网段被Bypass了啊，我需要让172加入代理，而不是排除掉。
。。。另外，你截图的这个界面，我一点就是一闪而过一个黑框

**Comment by seryte** [comment]
@yi-Xu-0100
感谢，可以了，我从这里边将172的删除后就可以了。另外请教一下，在config.yaml中配置了bypass，不能覆盖界面上Bypass Domain/IPNet吗

**Comment by yi-Xu-0100** [comment]
@seryte 不能，这个是 cfw 的配置项，不会从配置中读取。

**Comment by seryte** [comment]
> @seryte 不能，这个是 cfw 的配置项，不会从配置中读取。

明白了，再次感谢😁

**Comment by wpzzz** [comment]
> @seryte 不能，这个是 cfw 的配置项，不会从配置中读取。

那在之前的基础上添加也不行？  如果是的话 cfw-bypass等于无效了？

**Comment by yi-Xu-0100** [comment]
@wpzzz 版本升级了，这个系统代理的设置，建议从 gui 界面去设置。

**Comment by wpzzz** [comment]
> 

好吧 多谢， 如果能cfw-bypass优先级大于setting里的设置就好了
