### ISSUE TITLE
No proxy group in this peofile

### ISSUE THREAD

**Issue by midezhanghao** [Fndroid/clash_for_windows_pkg#1877]
![1](https://user-images.githubusercontent.com/76832486/117766362-0a0b8b80-b262-11eb-96cf-f6d1e8faa399.png)
![2](https://user-images.githubusercontent.com/76832486/117766366-0b3cb880-b262-11eb-9280-9cb8e72c9480.png)
#没有代理

**Comment by yi-Xu-0100** [comment]
@midezhanghao 日志呢？

![image](https://user-images.githubusercontent.com/25523606/117775222-e13cc380-b26c-11eb-94d9-45f160f84799.png)

点这里，proxy 是 provider 提供的吗？

**Comment by midezhanghao** [comment]
> @midezhanghao日志呢？
> 
> ![图像](https://user-images.githubusercontent.com/25523606/117775222-e13cc380-b26c-11eb-94d9-45f160f84799.png)
> 
> 点这里，proxy是提供商提供的吗？

你好，proxy是provider提供，手机端能用，Win端就显示没有代理
![2](https://user-images.githubusercontent.com/76832486/117939405-99846d80-b33a-11eb-9cd0-57afa877f5a9.png)
![1](https://user-images.githubusercontent.com/76832486/117939429-9db08b00-b33a-11eb-999b-4d70db87517e.png)

**Comment by yi-Xu-0100** [comment]
@midezhanghao raw.githubusercontent.com 超时。provider 如果也是这个域名提供的话，是因为这个域名被污染的原因。改 host 或者 换成 cdn 版本

**Comment by midezhanghao** [comment]
> @midezhanghao raw.githubusercontent.com超时。provider如果也是这个域名提供的话，是因为这个域名被污染的原因。改主机还是换成cdn版本

小白不会弄啊，改host是在Win端的clash里面改还是改整台电脑的host？

**Comment by yi-Xu-0100** [comment]
@midezhanghao 可以参考这个链接，用第三方转换

https://github.com/Fndroid/clash_for_windows_pkg/issues/1820#issuecomment-835232493

**Comment by midezhanghao** [comment]
> @midezhanghao可以参考这个链接，用第三方转换
> 
> [第1820章（评论）](https://github.com/Fndroid/clash_for_windows_pkg/issues/1820#issuecomment-835232493)

OK了，谢谢大佬，谢谢大佬！！！

**Comment by zhouhelted** [comment]
I have the same issue on 19.2
