### ISSUE TITLE
无法访问网址

### ISSUE THREAD

**Issue by NolanHzy** [Fndroid/clash_for_windows_pkg#1878]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ x] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)
访问百度网盘 显示不出来资源

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**
time="2021-05-11T18:35:27+08:00" level=warning msg="[TCP] dial DIRECT (match Domain/pannss.bdstatic.com) to pannss.bdstatic.com error: dial tcp4 180.163.198.38:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2021-05-11T18:35:27+08:00" level=warning msg="[TCP] dial DIRECT (match Domain/pannss.bdstatic.com) to pannss.bdstatic.com error: dial tcp4 180.163.198.38:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2021-05-11T18:35:27+08:00" level=warning msg="[TCP] dial DIRECT (match Domain/pannss.bdstatic.com) to pannss.bdstatic.com error: dial tcp4 180.163.198.38:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2021-05-11T18:35:27+08:00" level=warning msg="[TCP] dial DIRECT (match Domain/pannss.bdstatic.com) to pannss.bdstatic.com error: dial tcp4 180.163.198.38:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2021-05-11T18:35:27+08:00" level=warning msg="[TCP] dial DIRECT (match Domain/pannss.bdstatic.com) to pannss.bdstatic.com error: dial tcp4 180.163.198.38:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2021-05-11T18:35:27+08:00" level=warning msg="[TCP] dial DIRECT (match Domain/pannss.bdstatic.com) to pannss.bdstatic.com error: dial tcp4 180.163.198.38:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2021-05-11T18:35:27+08:00" level=warning msg="[TCP] dial DIRECT (match Domain/pannss.bdstatic.com) to pannss.bdstatic.com error: dial tcp4 180.163.198.38:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.

[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/21116175/117803387-28d14880-b289-11eb-81b8-e965552fcba1.png)
![image](https://user-images.githubusercontent.com/21116175/117803470-41416300-b289-11eb-8511-8930d6c4e6ea.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
有没有可能这个域名真的访问不了？

**Comment by NolanHzy** [comment]
> 有没有可能这个域名真的访问不了？

好像是网络问题。我用手机热点可以访问的。

**Comment by Fndroid** [comment]
不是软件问题，我colse了
