### ISSUE TITLE
TAP模式下添加的默认路由与系统原默认路由的跃点数相同

### ISSUE THREAD

**Issue by lyz05** [Fndroid/clash_for_windows_pkg#1879]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Win7 专业版 SP1

[//]: # (平台及版本号)

**描述**
cfw启用tap后，TAP模式下添加的默认路由与系统原默认路由的跃点数相同，造成无法联网的问题。
原默认网络是有线接入的10.0.0.0/8的校园网，不知道会不会有影响。
手动修改物理网卡的跃点数，将跃点数调大，即可正常使用

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'cfw'
2. 点击'mixin'
3. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/11796777/117912305-d9832a80-b311-11eb-82db-a1dae3d7f8f4.png)
![image](https://user-images.githubusercontent.com/11796777/117913189-81e5be80-b313-11eb-8434-9ea793a6269d.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
route add已经设置为1了
