### ISSUE TITLE
clash REJECT 可以按照域名拦截dns查询请求(手机使用)

### ISSUE THREAD

**Issue by kurdsvv** [Fndroid/clash_for_windows_pkg#1880]
**描述**
请具体并清楚地描述期望功能及期望的效果

**其他说明**
其他补充内容

**Comment by yi-Xu-0100** [comment]
现在应该是可行的，https://lancellc.gitbook.io/clash/clash-config-file/rules/domain-based-rule

**Comment by Fndroid** [comment]
没看懂
