### ISSUE TITLE
更新后图标消失问题

### ISSUE THREAD

**Issue by ElegantAlan** [Fndroid/clash_for_windows_pkg#1881]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
win10 教育版 20H2
**描述**
您好，我在win10系统通过clash界面的update从0.15.3更新到0.15.5版本后，桌面的clash启动图标没有了，想去菜单栏再拖一个出来，发现菜单栏也没有clash图标，可否解决一下此bug

**补充1：**
控制面板中已经不存在clash for windows这个应用，无法卸载

**补充2：**
没办法卸载，直接github下载了最新版安装一遍。

**Comment by yi-Xu-0100** [comment]
怀疑没有更完，update 其实就是自动下载安装包，会提示你安装的，有提示吗？

**Comment by ElegantAlan** [comment]
> 怀疑没有更完，update 其实就是自动下载安装包，会提示你安装的，有提示吗？

有提示的，然后clash重启了

**Comment by yi-Xu-0100** [comment]
emmm 不太清楚，我更新和安装一个样，所以都会有图标，你原来的版本是便携版吗?安装模式是为个人还是全部安装？

**Comment by ElegantAlan** [comment]
> emmm 不太清楚，我更新和安装一个样，所以都会有图标，你原来的版本是便携版吗?安装模式是为个人还是全部安装？

是安装版的啊，免安装的用起来不舒服，是不是为个人安装的不太记得了，以后要是没解决就再重新下载安装一遍也行

**Comment by OG-C** [comment]
> > emmm 不太清楚，我更新和安装一个样，所以都会有图标，你原来的版本是便携版吗?安装模式是为个人还是全部安装？
> 
> 是安装版的啊，免安装的用起来不舒服，是不是为个人安装的不太记得了，以后要是没解决就再重新下载安装一遍也行

免装版和安装版使用体验上没有区别吧

**Comment by ElegantAlan** [comment]
> > > emmm 不太清楚，我更新和安装一个样，所以都会有图标，你原来的版本是便携版吗?安装模式是为个人还是全部安装？
> > 
> > 是安装版的啊，免安装的用起来不舒服，是不是为个人安装的不太记得了，以后要是没解决就再重新下载安装一遍也行
> 
> 免装版和安装版使用体验上没有区别吧

对，应用启动后没什么不同，单纯不太喜欢免安装应用这种使用逻辑，喜欢使用安装的应用，有点强迫症

**Comment by ElegantAlan** [comment]
> 怀疑没有更完，update 其实就是自动下载安装包，会提示你安装的，有提

**Comment by ElegantAlan** [comment]
> **信息**
> 
> * [x]  已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
> * [x]  已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
> * [x]  已经尝试更新到最新版本，问题依旧存在
> * [x]  软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）
> 
> **系统**
> win10 教育版 20H2
> **描述**
> 您好，我在win10系统通过clash界面的update从0.15.3更新到0.15.5版本后，桌面的clash启动图标没有了，想去菜单栏再拖一个出来，发现菜单栏也没有clash图标，可否解决一下此bug
> 
> **补充1：**
> 控制面板中已经不存在clash for windows这个应用，无法卸载
> 
> **补充2：**
> 没办法卸载，直接github下载了最新版安装一遍。

可以确定这是一个bug,今天从0.15.5升级到0.15.7又上演了同样的一幕，希望大佬早日处理

**Comment by Fndroid** [comment]
今天的版本加了检测，要从下次更新才能看出来

**Comment by ElegantAlan** [comment]
> 今天的版本加了检测，要从下次更新才能看出来

大佬太强惹！打call!

**Comment by ElegantAlan** [comment]
> 今天的版本加了检测，要从下次更新才能看出来

我来关闭issue了，5月31日刚升级到0.15.8版本的CFW，并没有出现以前图标消失的情况，感谢带佬的无私奉献

**Comment by OG-C** [comment]
> 今天的版本加了检测，要从下次更新才能看出来

F大，我也做过测试，最新版（0.15.8）确实如楼主所说，更新后快捷方式会消失

**Comment by ElegantAlan** [comment]
> > 今天的版本加了检测，要从下次更新才能看出来
> 
> F大，我也做过测试，最新版（0.15.8）确实如楼主所说，更新后快捷方式会消失

0.15.8版本已经修复了
