### ISSUE TITLE
关闭random control port 后 restful 端口仍然不是我配置中所设置的端口号

### ISSUE THREAD

**Issue by Skyxim** [Fndroid/clash_for_windows_pkg#1882]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
WIndows10  19043.867

**描述**
在关闭随机控制端口后仍然不是自己在配置文件中所设的端口

**复现**

1.在开启随机端口下 关闭随机端口
2.退出cfw，并重新启动

**预期行为**
可以正确使用配置中所使用的端口号，如果cfw本身对端口号有一定要求，可以在cfw设置中进行端口号设置，总的来说希望可以自定义设置restful api的端口号

**日志**
time="2021-05-13T21:19:34+08:00" level=info msg="Mixed(http+socks5) proxy listening at: :7890"
time="2021-05-13T21:19:34+08:00" level=info msg="RESTful API listening at: 127.0.0.1:51701"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial provider BA"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial provider PC-HK"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial provider SS"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial provider SS-SG"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial provider BA-SG2"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial provider PC"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial provider BA-HK"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial provider SS-HK"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial provider BA-SG"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial compatible provider YouTube"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial compatible provider AsianTV"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial compatible provider Github"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial compatible provider Steam"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial compatible provider Fallback"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial compatible provider GlobalTV"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial rule provider LocalAreaNetwork"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial rule provider YouTube"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial rule provider Github"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial rule provider BanAD"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial rule provider BanEasyList"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial rule provider BanEasyListChina"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial rule provider China"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial rule provider BanEasyPrivacy"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial rule provider BanProgramAD"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial rule provider Apple"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial rule provider Speedtest"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial rule provider Global"
time="2021-05-13T21:19:35+08:00" level=info msg="Start initial rule provider Microsoft"
time="2021-05-13T21:19:35+08:00" level=info msg="DNS server listening at: :6666"
time="2021-05-13T21:19:35+08:00" level=debug msg="Generate GUID: {330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}"
time="2021-05-13T21:19:35+08:00" level=info msg="[Wintun] CreateAdapter: Creating adapter"
time="2021-05-13T21:19:35+08:00" level=info msg="[Wintun] CreateAdapter: Requested GUID {330EAEF8-7578-5DF2-D97B-8DADC0EA85CB} has leftover residue"
time="2021-05-13T21:19:35+08:00" level=info msg="[Wintun] SelectDriver: Using existing driver 0.10"
time="2021-05-13T21:19:36+08:00" level=info msg="Tun Proxy listening at: Clash(198.18.0.1)"

**截图**
![image](https://user-images.githubusercontent.com/70276018/118131641-5a851380-b431-11eb-8c3d-353b8fefbb8d.png)
![image](https://user-images.githubusercontent.com/70276018/118133892-e9932b00-b433-11eb-8f90-3bd6ba79cff4.png)

**其他说明**

**Comment by yi-Xu-0100** [comment]
@Skyxim 该设置是在 home directory 中的 config.yml 中设置，不从配置文件中读取

**Comment by Skyxim** [comment]
> @Skyxim 该设置是在 home directory 中的 config.yml 中设置，不从配置文件中读取

嗨，还真在这，我没去看，还以为是写死在软件里的
