### ISSUE TITLE
测试延迟的时候节点都超时，但是连接上以后网络一切正常，在别的客户端测ping都是正常显示

### ISSUE THREAD

**Issue by jay-mars** [Fndroid/clash_for_windows_pkg#1884]
**信息**
- [X ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [X ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [X ] 已经尝试更新到最新版本，问题依旧存在
- [X ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
WINDOWS 

0.14.9 - 0.15.x
**描述**

测试延迟的时候节点都超时，但是连接上以后网络一切正常，在别的客户端测ping都是正常显示.
虽然可以使用，但是很影响感官，而且自动选择节点，也会把这些节点直接PASS掉。

**复现**

1. 进入'订阅导入后'
2. 点击'延迟测速图标'
3. 拖动到'....'
4. 触发问题  “超时”

**预期行为**
节点有正常绿色延迟出现

**日志**

无日志问题

**Comment by yi-Xu-0100** [comment]
@jay-mars 
1. 重新同步下时间再试试。
2. CFW setting 中的延迟测试链接有没有更改？

**Comment by jay-mars** [comment]
> @杰伊·马尔斯
> 
> 1. 重新同步下时间再试试。
> 2. CFW设置中的延迟测试链接有没有更改？

没有更改cfw的延迟测试URL
![image](https://user-images.githubusercontent.com/58627914/118210350-07e14100-b49d-11eb-9309-d99373985a06.png)
vps上和windows都同步了时间，不止是我一个人出现，会不会跟VPS系统设置有关系？

**Comment by jay-mars** [comment]
> @杰伊·马尔斯
> 
> 1. 重新同步下时间再试试。
> 2. CFW设置中的延迟测试链接有没有更改？

我的其他节点都能ping出正常延迟，就昨天新增的一台VPS的节点，全部无法ping出来  但是ios小火箭ping测试完全正常

**Comment by Fndroid** [comment]
使用任何非Github版本，请勿发issue，谢谢合作

**Comment by jay-mars** [comment]
> 使用任何非Github版本，不要发issue，谢谢合作

是github版本，为了各种比较测试，截图的时候打了个汉化补丁。

**Comment by Fndroid** [comment]
对，这种就不是官方版本，就不要在我这问
