### ISSUE TITLE
希望支持添加额外的前置代理（二级代理）

### ISSUE THREAD

**Issue by Blackbytes-max** [Fndroid/clash_for_windows_pkg#1887]
**描述**
我通过伪装代理软件欺骗了手游加速器，将我的手机变成了一个连接手游加速节点的HTTP tunnel，但我发现大多数翻墙软件包括一些知名VPN软件（openvpn除外）都不支持设置前置代理，手动修改机场的配置文件极为繁琐而且不是所有的协议都能通过修改配置文件支持前置代理。

**其他说明**
这个需求虽然可能很小众，但还是希望开发者考虑一下

**Comment by yi-Xu-0100** [comment]
@Blackbytes-max

**Comment by Blackbytes-max** [comment]
我研究一下
