### ISSUE TITLE
更改屏幕分辨率（也可能是缩放比例）会导致页面显示BUG

### ISSUE THREAD

**Issue by ok-day** [Fndroid/clash_for_windows_pkg#189]
当cfw页面打开时，更改屏幕分辨率（也可能是缩放比例）会导致页面显示BUG，即使改回原来的分辨率（也可能是缩放比例）也不能恢复，只能关闭clash重新打开。

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
