### ISSUE TITLE
[BUG] "No Internet access" in 15.6 with TUN

### ISSUE THREAD

**Issue by bakamosokyo** [Fndroid/clash_for_windows_pkg#1892]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [?] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
WIN10 20H2

**描述**
**I do have Internet, dns resolve just fine.**
**But windows says other wise, Things are normal after gone back to 15.5+2021.04.08**
**Update: 15.5+2021.05.08 is not working after reboot.**

**日志**

**截图**

**其他说明**

        dns:
         enable: true
         nameserver: 
          - https://94.140.14.14/dns-query
          - https://94.140.15.15/dns-query
         default-nameserver:
          - 1.1.1.1
          - 1.0.0.1
          

        tun:
           enable: true
           stack: gvisor
           dns-hijack:
             - 198.18.0.2:53
           macOS-auto-route: true
           macOS-auto-detect-interface: true

**Comment by mwhds97** [comment]
tun:
  enable: true
  stack: gvisor # or system
  dns-hijack:
    - 198.18.0.2:53 # when `fake-ip-range` is 198.18.0.1/16, should hijack 198.18.0.2:53
  auto-route: true # auto set global route for Windows
  # It is recommended to use `interface-name`
  auto-detect-interface: true # auto detect interface, conflict with `interface-name`

**Comment by mwhds97** [comment]
![image](https://user-images.githubusercontent.com/32876945/118394984-83e4b000-b67a-11eb-9f65-0737dc53e492.png)
[https://github.com/Dreamacro/clash/wiki/premium-core-features#windows](https://github.com/Dreamacro/clash/wiki/premium-core-features#windows)

**Comment by bakamosokyo** [comment]
> ![image](https://user-images.githubusercontent.com/32876945/118394984-83e4b000-b67a-11eb-9f65-0737dc53e492.png)

Problem not solved, and macOS- is still the correct parameter in 2021.04.08

**Comment by returnL** [comment]
![image](https://user-images.githubusercontent.com/44701395/118395616-df646d00-b67d-11eb-977f-1fd012c1f9bd.png)
指的是这个“无网络访问权限”吧，TUN模式是生效的，代理也都正常。但是因为网卡这里是“无网络访问权限”，所以会导致Microsoft Store无法登陆，其他微软的软件可能也会这样

**Comment by Fndroid** [comment]
@returnL 用了fakeip？

**Comment by Fndroid** [comment]
@bakamosokyo I don't get your point. What is "But windows says other wise"?

**Comment by bakamosokyo** [comment]
> @bakamosokyo I don't get your point. What is "But windows says other wise"?

The image you just see above.

**Comment by Fndroid** [comment]
> > @bakamosokyo I don't get your point. What is "But windows says other wise"?
> 
> 
> 
> The image you just see above.

What issues does this cause?

**Comment by bakamosokyo** [comment]
> > > @bakamosokyo I don't get your point. What is "But windows says other wise"?
> > 
> > 
> > The image you just see above.
> 
> What issues does this cause?

Unable to use native windows apps. *Microsoft store, mail, weather, etc. Edge and windows update are working fine.
3rd party software are usually not effected.
Not a problem most of the time, but sometimes things just doesn't work.

**Comment by returnL** [comment]
https://github.com/Dreamacro/clash/issues/1407
