### ISSUE TITLE
启用TUN，虚拟网卡显示无网络访问权限

### ISSUE THREAD

**Issue by OG-C** [Fndroid/clash_for_windows_pkg#1893]
**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Win10 20h2

**描述**
所有功能都正常启用，clash 仪表盘的连接里也能显示TUN。网络都能正常访问。只是虚拟网卡显示“无网络访问权限”，托盘网络指示器显示“无法连接Internet”

**截图**
![Snipaste_2021-05-16_19-11-26](https://user-images.githubusercontent.com/82382147/118395036-d2924a00-b67a-11eb-8992-85f1b63b5d81.png)
![Snipaste_2021-05-16_19-12-01](https://user-images.githubusercontent.com/82382147/118395039-d625d100-b67a-11eb-92b0-80c823f27e98.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by mwhds97** [comment]
![image](https://user-images.githubusercontent.com/32876945/118394984-83e4b000-b67a-11eb-9f65-0737dc53e492.png)
[https://github.com/Dreamacro/clash/wiki/premium-core-features#windows](https://github.com/Dreamacro/clash/wiki/premium-core-features#windows)

**Comment by OG-C** [comment]
> ![image](https://user-images.githubusercontent.com/32876945/118394984-83e4b000-b67a-11eb-9f65-0737dc53e492.png)
> https://github.com/Dreamacro/clash/wiki/premium-core-features#windows

不是咨询启用方法，此处已经启用了，只是虚拟网卡状态有时会变成无网络访问权限。网络其实是通的。

**Comment by mwhds97** [comment]
> > ![image](https://user-images.githubusercontent.com/32876945/118394984-83e4b000-b67a-11eb-9f65-0737dc53e492.png)
> > https://github.com/Dreamacro/clash/wiki/premium-core-features#windows
> 
> 不是咨询启用方法，此处已经启用了，只是虚拟网卡状态有时会变成无网络访问权限。网络其实是通的。

新版的 clash core 更改了字段，去掉了 macos- 前缀

**Comment by bakamosokyo** [comment]
> > > ![image](https://user-images.githubusercontent.com/32876945/118394984-83e4b000-b67a-11eb-9f65-0737dc53e492.png)
> > > https://github.com/Dreamacro/clash/wiki/premium-core-features#windows
> > 
> > 
> > 不是咨询启用方法，此处已经启用了，只是虚拟网卡状态有时会变成无网络访问权限。网络其实是通的。
> 
> 新版的 clash core 更改了字段，去掉了 macOS- 前缀

Quote:
"rename macOS-auto-* to auto-* (will be backward compatible with several versions)"

**Comment by Fndroid** [comment]
有什么影响吗

**Comment by returnL** [comment]
> 有什么影响吗

会导致Microsoft Store无法登陆

**Comment by returnL** [comment]
https://github.com/Dreamacro/clash/issues/1407

**Comment by OG-C** [comment]
> > > ![image](https://user-images.githubusercontent.com/32876945/118394984-83e4b000-b67a-11eb-9f65-0737dc53e492.png)
> > > https://github.com/Dreamacro/clash/wiki/premium-core-features#windows
> > 
> > 
> > 不是咨询启用方法，此处已经启用了，只是虚拟网卡状态有时会变成无网络访问权限。网络其实是通的。
> 
> 新版的 clash core 更改了字段，去掉了 macOS- 前缀

我的网络没问题，UWP应用以及微软相关的程序都能正常访问网络。就是虚拟网卡偶尔变成“无网络访问权限”

**Comment by OG-C** [comment]
> [Dreamacro/clash#1407](https://github.com/Dreamacro/clash/issues/1407)

原来是核心的问题，谢谢

**Comment by OG-C** [comment]
> > > ![image](https://user-images.githubusercontent.com/32876945/118394984-83e4b000-b67a-11eb-9f65-0737dc53e492.png)
> > > https://github.com/Dreamacro/clash/wiki/premium-core-features#windows
> > 
> > 
> > 不是咨询启用方法，此处已经启用了，只是虚拟网卡状态有时会变成无网络访问权限。网络其实是通的。
> 
> 新版的 clash core 更改了字段，去掉了 macOS- 前缀

去掉了字段依然有此问题，现在知道了，是clash新版闭源核心的bug.

**Comment by bazinga-zero** [comment]
请问一下是什么核心问题？具体怎么解决的呢
