### ISSUE TITLE
windows系统tun模式下怎么共享给局域网上网

### ISSUE THREAD

**Issue by HOMHOG** [Fndroid/clash_for_windows_pkg#1895]
**描述**
windows系统tun模式下怎么共享给局域网上网，用的redirect-host模式

**其他说明**
macOS上开启tun之后客户端可以改网关和dns实现透明代理，但是windows上不行，请问怎么设置

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/1865#issuecomment-834872349
