### ISSUE TITLE
Win10下Clash保持连接状态关机并重启后浏览器无法打开网页

### ISSUE THREAD

**Issue by JansenX** [Fndroid/clash_for_windows_pkg#1899]
Win10下使用Clash保持连接状态关机并重启后浏览器无法打开网页，但QQ登录不受影响，启动Clash后浏览器才能够正常打开网页，可能是DNS的问题。

**Comment by yi-Xu-0100** [comment]
@JansenX 如果开启了系统代理，关机时未设置 CFW 自动启动，重启后，系统代理会指向 CFW。

**Comment by JansenX** [comment]
> @JansenX 如果开启了系统代理，关机时未设置 CFW 自动启动，重启后，系统代理会指向 CFW。

机制是这样的话有什么解决的办法？

**Comment by yi-Xu-0100** [comment]
@JansenX 设置自启动，或者改为 pac 模式。

**Comment by JansenX** [comment]
可以，我用PAC试试
