### ISSUE TITLE
ipv6的网页无法正常访问

### ISSUE THREAD

**Issue by dlutwy** [Fndroid/clash_for_windows_pkg#190]
教育网的pt站的域名后缀都是.cn的 然而开启clash后会无法正常访问

**Comment by Fndroid** [comment]
log怎么显示的，全局可以访问么

**Comment by dlutwy** [comment]
> log怎么显示的，全局可以访问么

global 就没log了。
bt.byr.cn (127.0.0.1)		Direct
DomainSuffix 09:45:05.955

另外网易云音乐也不能播放。。。

**Comment by Fndroid** [comment]
HomeDirectory里的logs文件夹里的log文件会记录，如果连不上会有log

网易云UWP需要添加bypass，参考：https://docs.cfw.lbyczf.com/rao-guo-xi-tong-dai-li

**Comment by dlutwy** [comment]
> HomeDirectory里的logs文件夹里的log文件会记录，如果连不上会有log
> 
> 网易云UWP需要添加bypass，参考：https://docs.cfw.lbyczf.com/rao-guo-xi-tong-dai-li

并没有找到logs文件夹。
开启了system proxy 以后无论是global 还是rule 都会检测不到ipv6地址。（http://test-ipv6.com/）
如果需要我可以提供远程操作我的电脑。

**Comment by Fndroid** [comment]
@dlutwy 你配置（Profiles）文件里有定义dns么

**Comment by dlutwy** [comment]
> HomeDirectory里的logs文件夹里的log文件会记录，如果连不上会有log
> 
> 网易云UWP需要添加bypass，参考：https://docs.cfw.lbyczf.com/rao-guo-xi-tong-dai-li

time="2019-09-23T12:33:22+08:00" level=info msg="127.0.0.1 --> bt.neu6.edu.cn doesn't match any rule using DIRECT"
time="2019-09-23T12:33:27+08:00" level=info msg="127.0.0.1 --> bt.byr.cn doesn't match any rule using DIRECT"

**Comment by dlutwy** [comment]
dns:
  enable: true
  ipv6: false
  nameserver:
     - 1.2.4.8
     - 114.114.114.114
     - 223.5.5.5
     - tls://dns.rubyfish.cn:853
     
  fallback: 
     - tls://dns.rubyfish.cn:853
     - tls://dns.google
     - tcp://1.1.1.1:53
     - tls://1.1.1.1:853
     - tls://1.0.0.1:853
     - tcp://1.0.0.1:53
     - tcp://208.67.222.222:443

是这个部分吗？ 配置文件是梯子服务商提供的链接下载来的，我也没（不）有（会）修改。

**Comment by Fndroid** [comment]
你看到第三行ipv6是false没有。

**Comment by dlutwy** [comment]
> 你看到第三行ipv6是false没有。

谢谢~改true就好了🤣🤣
