### ISSUE TITLE
Mac OS Error：Make sure you have installed Service Mode to control system proxy.

### ISSUE THREAD

**Issue by cy920820** [Fndroid/clash_for_windows_pkg#1904]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ x ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ x ] 已经尝试更新到最新版本，问题依旧存在
- [ x ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

**描述**

OS: Mac OS 11.3.1
Client Version: 0.15.6

[//]: # (请具体并清楚地描述遇到的问题)

**复现**
![image](https://user-images.githubusercontent.com/21211512/118760371-44e67280-b8a5-11eb-9fe9-2a5632d53097.png)

一直亮着，无法关闭，一旦关闭就显示如下图提示，点击安装但是没有任何安装进度（无反应）

![image](https://user-images.githubusercontent.com/21211512/118760401-516acb00-b8a5-11eb-9f94-6132723973fb.png)

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

现在将版本回退到0.14.1 后，service mode 可以正常打开和关闭了

**Comment by cy920820** [comment]
自从更新到新版本后，service mode 一直打不开，点击后一直提示安装 mode，但是点击 install now 后没有任何动静

**Comment by Fndroid** [comment]
没有弹出授权提示输入密码吗

**Comment by cy920820** [comment]
> 没有弹出授权提示输入密码吗

这个忘记描述了，是有提示要输入密码的，但是输入完密码后就没有任何动静了

**Comment by Fndroid** [comment]
试试点service mode右边的manage，uninstall一次然后重新install，看看小地球有没变成绿色

因为以前的方法给的权限不够

**Comment by cy920820** [comment]
> 试试点service mode右边的manage，uninstall一次然后重新install，看看小地球有没变成绿色
> 
> 因为以前的方法给的权限不够

刚替换的最新版 clash 客户端，试了一下您刚才说的操作，还是没有反应，小地球也没有变绿色

**Comment by Fndroid** [comment]
你看看端口53000是被什么程序占用了

**Comment by happyHou** [comment]
mac可以尝试使用clashx项目，自用，很稳定。

**Comment by cy920820** [comment]
> lsof

好尴尬，并没有其他程序占用该端口啊

**Comment by cy920820** [comment]
> 你看看端口53000是被什么程序占用了
> `sudo lsof -i tcp:53000`

好尴尬，并没有其他程序占用该端口啊！

**Comment by Fndroid** [comment]
@cy920820  有Telegram账号吗，我远程看看？

**Comment by cy920820** [comment]
> @cy920820 有Telegram账号吗，我远程看看？

可以的。
同 github 账号(cy920820)，但是这会不方便啊， 您晚上 6-7 点方便吗？

**Comment by Fndroid** [comment]
可以

**Comment by cy920820** [comment]
> 可以

我这边可以了，您那边有时间上一下 Telegram，我给你留言了

**Comment by cy920820** [comment]
> @cy920820 有Telegram账号吗，我远程看看？

感谢作者远程支持~
