### ISSUE TITLE
这么好的软件居然不支持中文？

### ISSUE THREAD

**Issue by LsnmxNB** [Fndroid/clash_for_windows_pkg#191]
clash_for_windows作者是不是跟中文仇啊？

**Comment by Fndroid** [comment]
Duplicate of #163

**Comment by LsnmxNB** [comment]
> 重复 [＃163](https://github.com/Fndroid/clash_for_windows_pkg/issues/163)
一个会中文的人居然看不起中文， 好吧， Fndroid 你牛逼啊，88

**Comment by Fndroid** [comment]
> > 重复 [＃163](https://github.com/Fndroid/clash_for_windows_pkg/issues/163)
> > 一个会中文的人居然看不起中文， 好吧， Fndroid 你牛逼啊，88

不支持 != 看不起

不爱用，滚
