### ISSUE TITLE
win10升级21h1后 Allow LAN 失效！望大佬排查一下！

### ISSUE THREAD

**Issue by JohyC** [Fndroid/clash_for_windows_pkg#1910]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Win10 21h1
**描述**
Win10升级21h1后 Allow LAN 失效
[//]: # (请具体并清楚地描述遇到的问题)
win10 未升级时，我还愉快的连clash socks5代理更新Linux包呢。昨天更新后就不能使用局域网共享了。不知道那出问题了。
我把clash for Windows 换成 qv2ray后，代理就能连。确定问题出在clash上。
**复现**
没有第二台电脑，没有进行复现操作。。。
[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by OG-C** [comment]
暂未收到推送。客户机设置是否正确？

**Comment by harrisonyi** [comment]
试试0.15.6版本 我今天也用到Allow LAN，发现连不上，退回0.15.6就可以了
**系统**
Windows 10 专业工作站版 20H2 19042.985

**Comment by Fndroid** [comment]
一般是防火墙问题，手动把安装目录/resource/static/files/win/x64/clash-win64.exe加到允许联网列表里就行。

加的时候你肯定会发现已经有这个程序了，路径也一样，这就是windows莫名其妙的地方了。重新加一次就正常。

**Comment by Tanche-Z** [comment]
v0.15.8 也是，虚拟机无法使用代理了，同21h1

**Comment by YuanfengZhang** [comment]
![image](https://user-images.githubusercontent.com/71358306/120022277-c44f1100-c01e-11eb-8b86-e5cb020199ff.png)
![image](https://user-images.githubusercontent.com/71358306/120022430-fb252700-c01e-11eb-9ca9-eedddeb73bc6.png)
WIN10=20H2, CLASHX=0.14.9和0.14.8
失败…… 添加后并不行。FXXK MS。为了排除虚拟机的影响，我更换了Ubuntu和Kbuntu两个虚拟机，这两个虚拟机之前都正常使用，但现在都失效了。
请问大家，我下一步应该做什么？再更新到最新版本的clashx吗？

**Comment by YuanfengZhang** [comment]
太痛苦了，完全不行。希望clash尽快解决这个问题。经过控制变量，已经排除VMWARE和虚拟机内部的影响。现在基本确定是clash和Win10的问题。我已经丧心病狂地把clash安装目录下所有exe程序都添加到了允许列表里，并且启用了规则。但是仍然没有反应。
![image](https://user-images.githubusercontent.com/71358306/120025107-c5823d00-c022-11eb-8273-c7a0c80836f7.png)
![image](https://user-images.githubusercontent.com/71358306/120025113-c9ae5a80-c022-11eb-9141-bfcd561bed4d.png)

防火墙入站规则页面导出的列表：
[firewall.txt](https://github.com/Fndroid/clash_for_windows_pkg/files/6562686/firewall.txt)

**Comment by harrisonyi** [comment]
> 试试0.15.6版本 我今天也用到Allow LAN，发现连不上，退回0.15.6就可以了
> **系统**
> Windows 10 专业工作站版 20H2 19042.985

重新添加以后防火墙规则后 公司和家里的电脑都可以了  现在升级到0.15.8  21H1也是可以正常使用

**Comment by JohyC** [comment]
> 太痛苦了，完全不行。希望clash尽快解决这个问题。经过控制变量，已经排除VMWARE和虚拟机内部的影响。现在基本确定是clash和Win10的问题。我已经丧心病狂地把clash安装目录下所有exe程序都添加到了允许列表里，并且启用了规则。但是仍然没有反应。
> ![image](https://user-images.githubusercontent.com/71358306/120025107-c5823d00-c022-11eb-8273-c7a0c80836f7.png)
> ![image](https://user-images.githubusercontent.com/71358306/120025113-c9ae5a80-c022-11eb-9141-bfcd561bed4d.png)
> 
> 防火墙入站规则页面导出的列表：
> [firewall.txt](https://github.com/Fndroid/clash_for_windows_pkg/files/6562686/firewall.txt)
> 
> 补充：
> 尝试了三个版本的clash for windows，包括14.8,14.9和15.8，每次安装后都尝试了重新添加规则。均失败。
> 
> 再次补充：
> 发现个很不好的事情，14.9程序内升级15.8后再次重启，用任务管理器发现新版本并未移除旧版本，而是新安装在了另一个地方…… 所以开机启动的其实是旧版本，我弄半天可能白弄了？无论是否与这个问题有关，程序升级的这个问题似乎应该得到解决。
> 我准备尝试用geek.exe卸载14.9和15.8，并清理注册表，删除防火墙规则。重启，再次安装15.9，添加防火墙规则。

老哥屏幕尺寸多大的？这截图有点爽呀！

**Comment by YuanfengZhang** [comment]
> 一般是防火墙问题，手动把安装目录/resource/static/files/win/x64/clash-win64.exe加到允许联网列表里就行。
> 
> 加的时候你肯定会发现已经有这个程序了，路径也一样，这就是windows莫名其妙的地方了。重新加一次就正常。

第三次更新进展：
使用Clashy成功实现虚拟机内部连到梯子，说明问题还是在于Clash for Windows自己。
![image](https://user-images.githubusercontent.com/71358306/120066630-f5c0ee80-c0a9-11eb-964f-c5dc2df6dc67.png)
![image](https://user-images.githubusercontent.com/71358306/120066686-30c32200-c0aa-11eb-969c-b7e4771a39de.png)

我能够提供的信息不多，只记得这不是最新版本才出现的问题，似乎一个月前就已经出现了。这期间Clash for Windows的更新和Win10的安全补丁都有嫌疑。

另外，程序内升级的处理方式过于糟糕。如果自定义一个安装路径，那么未来程序内更新并不会在这个路径内覆盖原程序，而是会在~\Appdata\Roaming目录下新建一个实例，从github下载安装的旧版本仍然会在重启后正常使用。启动旧版本目录内的卸载程序，会删除~\Appdata\Roaming目录下的新版本，而旧版本的目录保持完整。再次运行该卸载程序会快速跳过卸载进度条，显示已完成卸载。

以上就是我认为的三个疑点。
————————————————————————————————————————————————————————————————————
另外对于其他遭遇类似问题的人，如果和我一样尝试过修改防火墙规则但是失败，请不要浪费时间，先装个Clashy或者别的凑活一下。

**Comment by Fndroid** [comment]
[允许应用通过防火墙](https://support.microsoft.com/zh-cn/windows/%E5%85%81%E8%AE%B8%E5%BA%94%E7%94%A8%E9%80%9A%E8%BF%87-windows-defender-%E9%98%B2%E7%81%AB%E5%A2%99%E7%9A%84%E9%A3%8E%E9%99%A9-654559af-3f54-3dcf-349f-71ccd90bcc5c)

**Comment by MrFox7638** [comment]
把7890端口加入允许进入列表就好。

**Comment by JohyC** [comment]
> [允许应用通过防火墙](https://support.microsoft.com/zh-cn/windows/%E5%85%81%E8%AE%B8%E5%BA%94%E7%94%A8%E9%80%9A%E8%BF%87-windows-defender-%E9%98%B2%E7%81%AB%E5%A2%99%E7%9A%84%E9%A3%8E%E9%99%A9-654559af-3f54-3dcf-349f-71ccd90bcc5c)

额！F大，我另外一台电脑也出现此问题了。win10家庭中文版，1909。clash for windows版本为0.15.8。允许应用通过防火墙也重新配置了，电脑也重启无数次了。没能解决此问题。。。
