### ISSUE TITLE
开启代理后，mac一直弹出“networksetup“正在尝试修改网络配置，输入密码以允许此次操作”。

### ISSUE THREAD

**Issue by junyanxu21** [Fndroid/clash_for_windows_pkg#1914]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: mac os, 0.15.7 

**描述**

[//]: 使用mac系统安装clash后，打开代理，系统便一直弹出对话框，“networksetup“正在尝试修改网络配置，输入密码以允许此次操作”， 输入密码后仍会弹出。请问该怎么处理？

**Comment by Fndroid** [comment]
什么系统版本？

试试``chmod u+s /usr/sbin/networksetup``

**Comment by junyanxu21** [comment]
谢谢回复。
系统是macOS Sierra 10.12.6
在terminal中输入`sudo chmod u+s /usr/sbin/networksetup`后，
报错 'Unable to change file mode on /usr/sbin/networksetup: Operation not permitted' 

另外有Google有相同的问题，解决办法为删除一个文件，但是使用clash找不到类似的文件。
<img width="637" alt="Screen Shot 2021-05-25 at 9 06 24 PM" src="https://user-images.githubusercontent.com/52808301/119503048-23055800-bd9d-11eb-9818-c0224de5254e.png">

**Comment by edgexyz** [comment]
Sierra 版本太低了吧...
建议先升级再说（

**Comment by junyanxu21** [comment]
谢谢，系统已升级，问题解决了 :)
