### ISSUE TITLE
底部图标显示状态不对

### ISSUE THREAD

**Issue by MikeVoy** [Fndroid/clash_for_windows_pkg#1916]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
windows
[//]: # (平台及版本号)
windows10
**描述**
打开clash 后 应用内关闭SystemProxy 之后图标还是黄色的 我记得之前版本状态是没问题额
[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: #底部应用图标跟随状态切换正常

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # 
![image](https://user-images.githubusercontent.com/40830151/119433865-a9904a00-bd49-11eb-8262-99b8b632dd87.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by MikeVoy** [comment]
已修复

**Comment by Fndroid** [comment]
我没改。。会不会是你更新了windows
