### ISSUE TITLE
网络连接问题

### ISSUE THREAD

**Issue by Monster-DP** [Fndroid/clash_for_windows_pkg#192]
使用一段时间后速度变得很慢，但是同样的ShadowsocksR没有任何问题，节点的配制都是来自同一个网站的订阅链接，就算删除订阅连接重新更新打开网站速度还是同样的慢，全局代理与规则代理同样慢。版本 0.7.7

**Comment by Fndroid** [comment]
配置了dns么

**Comment by Monster-DP** [comment]
dns没有配置过 clash不怎么会用 只会获取订阅连接 为什么没有中文版本的呢



------------------ 原始邮件 ------------------
发件人: "Fndroid"<notifications@github.com>; 
发送时间: 2019年9月10日(星期二) 晚上10:10
收件人: "Fndroid/clash_for_windows_pkg"<clash_for_windows_pkg@noreply.github.com>; 
抄送: "木羊羽"<1948281933@QQ.COM>; "Author"<author@noreply.github.com>; 
主题: Re: [Fndroid/clash_for_windows_pkg] 网络连接问题 (#192)




配置了dns么

**Comment by Fndroid** [comment]
@Monster-DP 那去问你的机场吧

**Comment by Monster-DP** [comment]
好吧




------------------ 原始邮件 ------------------
发件人: "Fndroid"<notifications@github.com>; 
发送时间: 2019年9月10日(星期二) 晚上10:17
收件人: "Fndroid/clash_for_windows_pkg"<clash_for_windows_pkg@noreply.github.com>; 
抄送: "木羊羽"<1948281933@QQ.COM>; "Mention"<mention@noreply.github.com>; 
主题: Re: [Fndroid/clash_for_windows_pkg] 网络连接问题 (#192)




@Monster-DP 那去问你的机场吧
