### ISSUE TITLE
无法正常设置系统代理，提示Make sure you have installed Service Mode to control system proxy.

### ISSUE THREAD

**Issue by thlz998** [Fndroid/clash_for_windows_pkg#1920]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

MacBook Pro (13-inch, M1, 2020)

[//]: # (请具体并清楚地描述遇到的问题)

设置系统代理的时候，提示：Make sure you have installed Service Mode to control system proxy.
点击install Now ，输入系统密码，之后无任何反应

[//]: # (请描述复现问题的步骤)

1. 进入clash for windows
2. 点击System Proxy
3. 出现弹窗并提示Make sure you have installed Service Mode to control system proxy.
4. 点击Install Now 之后，输入系统密码，之后无任何反应

**预期行为**

可以正常的设置系统代理

**Comment by Fndroid** [comment]
1. 检查53000端口是否被占用，``sudo lsof -i tcp:53000``
2. 检查提权服务是否启动，``sudo launchctl list | grep com.lbyczf.cfw.helper``

**Comment by thlz998** [comment]
> 1. 检查53000端口是否被占用，`sudo lsof -i tcp:53000`
> 2. 检查提权服务是否启动，`sudo launchctl list | grep com.lbyczf.cfw.helper`

![image](https://user-images.githubusercontent.com/36218343/120138088-56663d80-c208-11eb-91d4-19a5bbfd4517.png)

53000端口未被占用，检查提权服务是否启动的命令执行后，无任何输出

**Comment by Fndroid** [comment]
1. 进入``/Library/LaunchDaemons``看看有没有``com.lbyczf.cfw.helper.plist``这个文件，没有的话在 General里Service Mode安装一次
2. ``sudo launchctl load com.lbyczf.cfw.helper.plist``
3. 看看输出什么

**Comment by thlz998** [comment]
> 1. 进入`/Library/LaunchDaemons`看看有没有`com.lbyczf.cfw.helper.plist`这个文件，没有的话在General里Service Mode 安装一次
> 2. `sudo launchctl load com.lbyczf.cfw.helper.plist`
> 3. 看看输出什么

![image](https://user-images.githubusercontent.com/36218343/120156094-33e21d80-c224-11eb-9753-25aecfb662a0.png)

**Comment by Fndroid** [comment]
``sudo launchctl load -w com.lbyczf.cfw.helper.plist``

**Comment by thlz998** [comment]
> `sudo launchctl load -w com.lbyczf.cfw.helper.plist`

可以了~谢谢

**Comment by xenonz95** [comment]
我也遇到的相同的问题，但是我是新电脑，sudo launchctl load com.lbyczf.cfw.helper.plist，执行之后找不到文件，而且点击service mode 里面的install也没有任何反应，包括不弹出输入密码的界面，请问要怎么解决？我是M1的电脑

**Comment by xenonz95** [comment]
@Fndroid 您好，我遇到了相似但似乎更糟糕的问题，本issues里提到的方法我都尝试了，但并不能解决问题
我是M1的MacBook pro
53000端口未占用
提权服务未启动
没有服务文件，但点击service mode 里面的install也没有任何反应
命令行的输出是空的（刚开始用，没装几个软件）

**Comment by Fndroid** [comment]
> 1. 进入``/Library/LaunchDaemons``看看有没有``com.lbyczf.cfw.helper.plist``这个文件，没有的话在 General里Service Mode安装一次
> 
> 2. ``sudo launchctl load com.lbyczf.cfw.helper.plist``
> 
> 3. 看看输出什么

@xenonz95 建议你按这个一步步操作并把结果给出来

**Comment by xenonz95** [comment]
@Fndroid 谢谢回复，不过我现在已经复现不了这个bug了，我通过找可以正常安装的朋友拷了一份plist文件到对应的目录之后自行解决了这个问题。
我当时拷完plist之后尝试打开cfw看能不能正常使用，记得好像是状态不太对，然后我点了删除服务，要输密码了，再点安装了一次好像装上了，之后就没有bug了，现在可以正常工作。
当时是做这些事情之前是不管怎么点安装那个服务都没有反应，点完就消失了，那个plist文件也没有出现
个人建议可以加个按钮弹出个小说明指导如何手动安装这个plist服务，或者在那个软件说明的站点加一个如何自行添加提权服务的Q@A

**Comment by xenonz95** [comment]
当时我执行2之后输出是空的，因为是新电脑，还什么都没装，没有其他的服务

**Comment by Aaron-Y-Wong** [comment]
@xenonz95 你好，我也遇到了同样的问题，请问可以提供一份plist文件吗

**Comment by xenonz95** [comment]
> @xenonz95 你好，我也遇到了同样的问题，请问可以提供一份plist文件吗

文件名是这个com.lbyczf.cfw.helper.plist
内容是下面：

<?xml version=1.0 encoding=UTF-8?>
<!DOCTYPE plist PUBLIC -//Apple//DTD PLIST 1.0//EN http://www.apple.com/DTDs/PropertyList-1.0.dtd>
<plist version=1.0>
    <dict>
        <key>Label</key>
        <string>com.lbyczf.cfw.helper</string>
        <key>Program</key>
        <string>/Users/xenon/.config/clash/service/clash-core-service</string>
        <key>RunAtLoad</key>
        <true/>
        <key>KeepAlive</key>
        <true/>
    </dict>
</plist>

注意你可能要改一下内容，里面有个字符串应该表示的是clash-core-service的绝对路径，我不太记得当时我有没有改了，可能因为没改导致报错了，但是却消除了bug，使得后面可以接着删除后再重新安装

**Comment by xenonz95** [comment]
> @xenonz95 你好，我也遇到了同样的问题，请问可以提供一份plist文件吗

`<?xml version=1.0 encoding=UTF-8?>
<!DOCTYPE plist PUBLIC -//Apple//DTD PLIST 1.0//EN http://www.apple.com/DTDs/PropertyList-1.0.dtd>
<plist version=1.0>
    <dict>
        <key>Label</key>
        <string>com.lbyczf.cfw.helper</string>
        <key>Program</key>
        <string>/Users/xenon/.config/clash/service/clash-core-service</string>
        <key>RunAtLoad</key>
        <true/>
        <key>KeepAlive</key>
        <true/>
    </dict>
</plist>`

**Comment by xenonz95** [comment]
```<?xml version=1.0 encoding=UTF-8?>
<!DOCTYPE plist PUBLIC -//Apple//DTD PLIST 1.0//EN http://www.apple.com/DTDs/PropertyList-1.0.dtd>
<plist version=1.0>
    <dict>
        <key>Label</key>
        <string>com.lbyczf.cfw.helper</string>
        <key>Program</key>
        <string>/Users/xenon/.config/clash/service/clash-core-service</string>
        <key>RunAtLoad</key>
        <true/>
        <key>KeepAlive</key>
        <true/>
    </dict>
</plist>

**Comment by Aaron-Y-Wong** [comment]
> > @xenonz95 你好，我也遇到了同样的问题，请问可以提供一份plist文件吗
> 
> 文件名是这个com.lbyczf.cfw.helper.plist
> 内容是下面：
> 
> ```
> <!DOCTYPE plist PUBLIC -//Apple//DTD PLIST 1.0//EN http://www.apple.com/DTDs/PropertyList-1.0.dtd>
> <plist version=1.0>
>     <dict>
>         <key>Label</key>
>         <string>com.lbyczf.cfw.helper</string>
>         <key>Program</key>
>         <string>/Users/xenon/.config/clash/service/clash-core-service</string>
>         <key>RunAtLoad</key>
>         <true/>
>         <key>KeepAlive</key>
>         <true/>
>     </dict>
> </plist>
> 
> 注意你可能要改一下内容，里面有个字符串应该表示的是clash-core-service的绝对路径，我不太记得当时我有没有改了，可能因为没改导致报错了，但是却消除了bug，使得后面可以接着删除后再重新安装
> ```

是的，Users字段后面是用户名

我在原先Clash for Windows使用失败之后安装了Clash X Pro，用了一段时间之后卸载Clash X Pro并再次尝试Clash for Windows。
此时 `/Library/LaunchDaemons` 目录下出现Clash X Pro相关的一些文件
使用 `sudo rm` 命令删除之后在Clash for Windows的General界面再次安装Service Mode成功出现提示输入密码对话框

个人推测可能和文件夹权限有关？

还是感谢您的帮助

**Comment by sibaiabis** [comment]
yyds

**Comment by hiifong** [comment]
你好我也遇到过同样的问题，我的解决办法是把其卸载然后重启并重新安装其，就解决了，亲测有效！

**Comment by sincerexie** [comment]
我也遇到了同样的问题：
我运行上述提到的
`sudo launchctl load com.lbyczf.cfw.helper.plist`，出现了权限报错，然后我删除了它（`rm -rf com.lbyczf.cfw.helper.plist`），重新安装service就好了

**Comment by xkd88** [comment]
你好，我也遇见了同样的问题，我的clash版本是0.19.26ARM版本,MAC系统是 monterey 12.5 M1 ,上面的方法我都试验过，还是不行，资源库中没有com.lbyczf.cfw.helper.plist，系统无法选择开启代理，点击系统代理提示 make sure you have已经安装用于控制系统代理服务，再点击安装输入管理原密码直接跳回，没有反应。clas软件也卸载重新安装过还是不行，请求帮助，谢谢！
![20220810123342](https://user-images.githubusercontent.com/101411596/183816652-5b2858df-1c8b-419d-a7ae-fcf4a40d3147.jpg)
![20220810123355](https://user-images.githubusercontent.com/101411596/183816667-122d83bb-3d11-4c5b-b70d-75308b38f3f2.jpg)

**Comment by sibaiabis** [comment]
> 你好，我也遇见了同样的问题，我的clash版本是0.19.26ARM版本,MAC系统是 monterey 12.5 M1 ,上面的方法我都试验过，还是不行，资源库中没有com.lbyczf.cfw.helper.plist，系统无法选择开启代理，点击系统代理提示 make sure you have已经安装用于控制系统代理服务，再点击安装输入管理原密码直接跳回，没有反应。clas软件也卸载重新安装过还是不行，请求帮助，谢谢！ ![20220810123342](https://user-images.githubusercontent.com/101411596/183816652-5b2858df-1c8b-419d-a7ae-fcf4a40d3147.jpg) ![20220810123355](https://user-images.githubusercontent.com/101411596/183816667-122d83bb-3d11-4c5b-b70d-75308b38f3f2.jpg)

按照操作创建plist文件即可

**Comment by xkd88** [comment]
没有创建从别的地方拷贝了一份 com.lbyczf.cfw.helper.plist
