### ISSUE TITLE
m1 下arm版本无法运行

### ISSUE THREAD

**Issue by thlz998** [Fndroid/clash_for_windows_pkg#1921]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

MacBook Pro (13-inch, M1, 2020)

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

Clash.for.Windows-0.15.7-arm64.dmg

无法正常打开

**复现**

[//]: # (请描述复现问题的步骤)

1. 下载Clash.for.Windows-0.15.7-arm64.dmg
2. 拖拽app到/Applications
3. 双击打开
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

可以正常使用

**Comment by yi-Xu-0100** [comment]
@thlz998 什么都不显示？

**Comment by liuzhaozhuo** [comment]
Clash.for.Windows-0.15.8-arm64-mac也还是不可以在M1上运行。

**Comment by thlz998** [comment]
> @thlz998什么不显示？

![image](https://user-images.githubusercontent.com/36218343/120138220-a80ec800-c208-11eb-9ddd-c69e6f05e84a.png)

首次打开如图所示


可以通过如下命令正常打开

`sudo xattr -r -d com.apple.quarantine /Applications/Clash\ for\ Windows.app`

但是依旧会出现 [issues/1920](https://github.com/Fndroid/clash_for_windows_pkg/issues/1920)  的问题

**Comment by Fndroid** [comment]
这是macOS的设定

**Comment by hwanghan** [comment]
遇到同样的问题，请问如何解决？

**Comment by yi-Xu-0100** [comment]
@hwanghan 上面有解决办法，你是遇到什么问题，执行到哪一步不行的。
