### ISSUE TITLE
网易云音乐UWP 开启Clash 联网部分功能异常

### ISSUE THREAD

**Issue by NalCol** [Fndroid/clash_for_windows_pkg#1923]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 20H2
Clash for Windows 0.15.7

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
网易云音乐UWP（最后一版UWP）
UWP Loopback限制已解除
在开启System Proxy（PAC模式）后
歌曲正常播放，评论等加载不出
提示”网络太拥挤，请稍后再试！“
Log内正常显示Direct连接的网易云域名
（关闭CFW、TUN模式可以正常加载）

**预期行为**

[//]: # (清晰地描述期望看到的行为)
正常加载评论等内容

**Comment by Herts** [comment]
试过 [UWP应用联网](https://github.com/Fndroid/clash_for_windows_pkg/wiki/UWP%E5%BA%94%E7%94%A8%E8%81%94%E7%BD%91)了吗?

**Comment by NalCol** [comment]
这样设置后也无法联网
![image](https://user-images.githubusercontent.com/58576200/119931422-f24b3b80-bfb3-11eb-8c1a-06bfb7f1fcc0.png)

**Comment by NalCol** [comment]
问题根据[绕过系统代理](https://docs.cfw.lbyczf.com/contents/bypass.html)教程解决
![image](https://user-images.githubusercontent.com/58576200/119933244-53740e80-bfb6-11eb-84c0-bcca8bba9669.png)
配置文件添加：
```
  - "music.163.com" # 网易云域名1
  - "*.music.126.net" # 网易云域名2
```
![image](https://user-images.githubusercontent.com/58576200/119933281-61299400-bfb6-11eb-918a-b1fc6ed9c74c.png)

**Comment by NalCol** [comment]
> 试过 [UWP应用联网](https://github.com/Fndroid/clash_for_windows_pkg/wiki/UWP%E5%BA%94%E7%94%A8%E8%81%94%E7%BD%91)了吗?

感谢回复，似乎Profile的bypass在PAC模式不生效
导致了这个问题

**Comment by yi-Xu-0100** [comment]
@NalCol CFW 不从配置中读取 bypass 这一项，应该

**Comment by NalCol** [comment]
> @NalCol CFW 不从配置中读取 bypass 这一项，应该
是吗？不过Clash只能在HTTP模式Bypass
但HTTP模式重启还得手动开Clash
不是很方便

**Comment by yi-Xu-0100** [comment]
@NalCol 那你可以看看 pac 编写，将这个过滤掉

**Comment by NalCol** [comment]
> @NalCol 那你可以看看 pac 编写，将这个过滤掉

好像在HTTP模式写好规则再切换PAC模式
可以正常Bypass
不知道是运气，还是设计失误？

**Comment by NalCol** [comment]
> @NalCol 那你可以看看 pac 编写，将这个过滤掉

@yi-Xu-0100 PAC 是不能 Bypass 的，可能 PAC 有对应语法
日后研究吧
