### ISSUE TITLE
关闭TUN后，Clash网卡依旧存在

### ISSUE THREAD

**Issue by returnL** [Fndroid/clash_for_windows_pkg#1929]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Windows 10 21H1

**描述**
使用Mixin开关TUN模式，关闭Mixin后，Clash网卡有概率依旧存在，而此时TUN模式已经关闭，导致无法上网。

**复现**

[//]: # (请描述复现问题的步骤)

1. CFW运行在后台，未使用Lightweight Mode
2. 通过快捷键关闭Mixin，或者调出Dashboard关闭Mixin
3. TUN模式的Clash网卡未关闭，依旧存在

**预期行为**
使用快捷键关闭Mixin后，Clash网卡也关闭

**截图**
![image](https://user-images.githubusercontent.com/44701395/120152318-e95ea200-c21f-11eb-8df0-359031ddcfaf.png)

**其他说明**
此问题在0.15.7和0.15.8版本我都遇到过，尝试过重装CFW或Service Mode，问题依旧存在。在我使用过程中，Clash网卡无法正常关闭的情况比正常关闭的情况多，往往是无法正常关闭的

**Comment by yi-Xu-0100** [comment]
是否是某一个配置中有 tun 的相关配置？

**Comment by returnL** [comment]
> 是否是某一个配置中有 tun 的相关配置？

没有，Profile里面都没写Tun配置

**Comment by Fndroid** [comment]
TUN模式是core实现的，发到core仓库吧

**Comment by returnL** [comment]
> TUN模式是core实现的，发到core仓库吧

行，我再换旧版本的core试试。谢谢

**Comment by Fndroid** [comment]
有tg吗，联系我一下我远程看看？

**Comment by returnL** [comment]
> 有tg吗，联系我一下我远程看看？

有tg，我要怎么联系你呢
