### ISSUE TITLE
新版tap无法使用redir-host

### ISSUE THREAD

**Issue by cjwddtc** [Fndroid/clash_for_windows_pkg#193]
升级到0.78版本后（0.77版本无法正常使用）按照https://github.com/Fndroid/clash_for_windows_pkg/wiki/%E6%96%B0%E7%89%88-TAP 这个页面中的描述修改配置文件后，仍然无法使用redir-host模式，具体表现为修改为redir-host后，tap的适配器变为网络电缆已拔出，同时也无法再设置系统代理的情况下翻墙。

**Comment by Fndroid** [comment]
0.7.8不支持redir host

重新安装tap可以恢复系统代理
