### ISSUE TITLE
Adguard 无法过滤广告

### ISSUE THREAD

**Issue by ShadowLyin** [Fndroid/clash_for_windows_pkg#194]
Adguard 更新 7.2 后，CFW 开启的情况下 Adguard 会失效，完全无法过滤广告。尝试过关闭或开启 Adguard 的 WFP 驱动程序，不过没有效果。

**Comment by Fndroid** [comment]
设置 - 常规设置拉到最下面 - 高级设置 - 拉到最下面选中 ``filter localhost``
![image](https://user-images.githubusercontent.com/16091562/64901231-95b5c900-d6c9-11e9-825f-caf3dcdb58d7.png)

**Comment by Mon5ter777** [comment]
> 设置 - 常规设置拉到最下面 - 高级设置 - 拉到最下面选中 `filter localhost`
> ![image](https://user-images.githubusercontent.com/16091562/64901231-95b5c900-d6c9-11e9-825f-caf3dcdb58d7.png)

F大你好，今天我也碰到了这个问题，而且我已经打开了filter localhost选项，但是仍然无法过滤广告，请问该怎么办。

**Comment by yzy1228682367** [comment]
Adguard 7.4同样出现了楼上的问题，尝试了小火箭同样也无法过滤广告。

**Comment by yzy1228682367** [comment]
> Adguard 7.4同样出现了楼上的问题，尝试了小火箭同样也无法过滤广告。

发现并不是代理软件的原因，而是adguard设置-网络-使用wfp网络驱动程序与杀毒软件的冲突所致。去除勾选即可。

**Comment by chenApostle** [comment]
我也碰到这样的问题

**Comment by TianYaDY** [comment]
> > 设置 - 常规设置拉到最下面 - 高级设置 - 拉到最下面选中 `filter localhost`
> > ![image](https://user-images.githubusercontent.com/16091562/64901231-95b5c900-d6c9-11e9-825f-caf3dcdb58d7.png)
> 
> F大你好，今天我也碰到了这个问题，而且我已经打开了filter localhost选项，但是仍然无法过滤广告，请问该怎么办。

感谢大佬！成功了！
