### ISSUE TITLE
TUN模式无法安装驱动

### ISSUE THREAD

**Issue by jakernel** [Fndroid/clash_for_windows_pkg#1941]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

Win7 SP1

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

启用TUN模式，不能安装TUN网卡，查看日志提示无法安装驱动
time="2021-06-03T11:12:53+08:00" level=info msg="[Wintun] SelectDriver: Could not install driver C:\\Windows\\Temp\\c989eab138891e53268a5cb67d6317489d97a1c70d3ae0e73a1dca5f76176183\\wintun.inf to store: 尚未建立对验证码(TM)签名的目录的发布者信任。 (Code 0xE0000242)"

**复现**

[//]: # (请描述复现问题的步骤)
已按下图配置，启动后查看最新日志，就有无法安装驱动的报错
![image](https://user-images.githubusercontent.com/1704664/120582996-f9fd5b00-c45f-11eb-87f4-76453111162c.png)
![image](https://user-images.githubusercontent.com/1704664/120583031-0b466780-c460-11eb-8517-ba72af760863.png)

**预期行为**

[//]: # (清晰地描述期望看到的行为)

正常安装TUN网卡

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/1704664/120583242-6b3d0e00-c460-11eb-8678-645788154e71.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by kingforme** [comment]
#1905

**Comment by jakernel** [comment]
应该不是同一个情况，我在另外一台机器测试可以正常使用。
似乎是驱动签名的问题，另外一台机子会弹出一个对话框，让我信任驱动发布者，
信任后就正常安装tun虚拟网卡了。
这个机子不会弹出信任的对话框。

**Comment by jakernel** [comment]
已解决，安装驱动签名的相关系统补丁
参考 `https://stackoverflow.com/questions/33778515/dpinst-silent-signed-driver-installation-fails-on-windows-7`
> Might be a little late, but which patch(s) have you installed? KB3033929 is the required patch for sha256 on Windows 7 and Windows Server 2008 R2. An additional problem I ran into, is even though I had installed my certificate as a trusted publisher, the installation was ignoring it. I would always get prompted to trust the publisher. To fix this issue there is an additional hotfix kb2921916. Hopefully this helps you or someone else out there.

**Comment by vousembrasser** [comment]
KB3033929这个补丁安装了,还是相同的报错
kb2921916这个补丁已经下不到了,楼主是怎么弄成功的
