### ISSUE TITLE
windows下使用tun模式 ping 任意地址 延迟<1ms

### ISSUE THREAD

**Issue by xiaod-dev** [Fndroid/clash_for_windows_pkg#1942]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Windows 10 LTSC 1809

[//]: # (平台及版本号)

**描述**
按照官方文档配置tun模式并开启成功后，今天发现本机不管ping什么地址，延迟都小于1<ms, 在本机运行的ubuntu子系统中也是这样，但可以显示具体的毫秒数。

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 成功启用tun模式，并且能上网。
2. 分别ping 国内地址 和 国外地址.
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

显示正常的延迟时间。

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/21277644/120735946-06e08400-c51e-11eb-8df3-6efb9207932c.png)

子系统Ubuntu下

![image](https://user-images.githubusercontent.com/21277644/120736092-368f8c00-c51e-11eb-8fd6-e237a1e27455.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by AkariiinMKII** [comment]
预期行为
tun/tap模式下`ping`和`traceroute`都不工作

**Comment by xiaod-dev** [comment]
> 预期行为
> tun/tap模式下`ping`和`traceroute`都不工作

好的，了解了 谢谢
