### ISSUE TITLE
clash tun 开机启动失败

### ISSUE THREAD

**Issue by Sailing168** [Fndroid/clash_for_windows_pkg#1944]
几乎是每个月我都会遇到不下五次电脑开机的时候显示本地网络可用-clash网络不可用，通常我都会选择重新安装或者直接替换tun data文件夹。但这个星期再次遇到这个问题，目前暂用net语言的clash，很明显net语言的mixin模式驱动不会出现在网卡设置中，应该不会导致类似于我这样的问题，望改进！

**Comment by yi-Xu-0100** [comment]
暂未复现，建议给出无法成功使用的日志。

**Comment by Sailing168** [comment]
那估计要等几天了

**Comment by yi-Xu-0100** [comment]
嗯，那赶在新版本前吧，不然就更新了 （

**Comment by Sailing168** [comment]
那没关系的，问题与案件#1943类似。但实际使用是tun未产生作用，即未代理流量。

**Comment by yi-Xu-0100** [comment]
@Sailing168 建议修改标题为 tun 开机启动失败，与 mixin 关系不大。日志记得开 debug 级别的 loglevel，然后注意看看那时候的 service 是否启动成功（绿色地球）。

**Comment by Sailing168** [comment]
近期问题暂未复现，使用环境：wintun0.12 clash0.16.0 Windows server 2019
