### ISSUE TITLE
v0.15.9 connections中查询,界面会卡死,但其他功能正常

### ISSUE THREAD

**Issue by ShadowsSide** [Fndroid/clash_for_windows_pkg#1948]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

windows 10 21H1

[//]: # (请具体并清楚地描述遇到的问题)

connections中查询记录时,点击回车后统计界面就卡死.停止接受新的记录,并且旧的记录一直停顿在那.
点击搜索栏的×也无法删除搜索内容.
clash的日志还是继续在工作,可以看到实时统计数据,

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
windows 20H2 ，CFW 0.15.9 可复现。

**Comment by yi-Xu-0100** [comment]
> 输入 ? 可复现

最新版已修复
