### ISSUE TITLE
启动Clash for Windows后，显示出错

### ISSUE THREAD

**Issue by meshiro** [Fndroid/clash_for_windows_pkg#1949]
![-753d8808698f5829](https://user-images.githubusercontent.com/85471063/120959062-845cfc00-c78b-11eb-845b-2ce968556b53.png)
![Uploading 10884f0711e6a81c.png…]()

**Comment by yi-Xu-0100** [comment]
订阅能否打开？是否是  provider ？里面有 githubcontent 链接？

**Comment by meshiro** [comment]
> 订阅能否打开？是否是 provider ？里面有 githubcontent 链接？

我试着更新了最新版的clash，general一直显示lodging，proxies显示不了节点，订阅链接导入就显示network  error。

time="2021-06-07T19:40:34+09:00" level=info msg="Start initial compatible provider Proxy"
time="2021-06-07T19:40:35+09:00" level=info msg="RESTful API listening at: 127.0.0.1:55160"
time="2021-06-07T19:40:35+09:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"

**Comment by yi-Xu-0100** [comment]
@meshiro 你的配置中的 provider 是 githubcontent.com 的链接吗？链接能否直连打开？

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/1802#issuecomment-821833507

**Comment by meshiro** [comment]
> [#1802 (comment)](https://github.com/Fndroid/clash_for_windows_pkg/issues/1802#issuecomment-821833507)

确实是这个问题，把clash-win64.exe加到防火墙允许应用通过列表就行了
