### ISSUE TITLE
在Profiles添加clash订阅链接后在Proxies中没有节点

### ISSUE THREAD

**Issue by Monster-DP** [Fndroid/clash_for_windows_pkg#195]
!
![Snipaste_2019-09-14_12-49-15](https://user-images.githubusercontent.com/47738288/64903638-3ff41780-d6ef-11e9-95de-1df2d0cf8049.png)
![Snipaste_2019-09-14_12-49-12](https://user-images.githubusercontent.com/47738288/64903639-408cae00-d6ef-11e9-9508-7d37c5b1c600.png)
![Snipaste_2019-09-14_12-49-20](https://user-images.githubusercontent.com/47738288/64903640-408cae00-d6ef-11e9-927f-fa33057a7ba4.png)

在Profiles添加clash订阅链接后在Proxies中没有节点

**Comment by Fndroid** [comment]
有没有考虑过点一下这个profile选中它

**Comment by Monster-DP** [comment]
我还点了save的



------------------ 原始邮件 ------------------
发件人: "Fndroid"<notifications@github.com>; 
发送时间: 2019年9月14日(星期六) 中午12:59
收件人: "Fndroid/clash_for_windows_pkg"<clash_for_windows_pkg@noreply.github.com>; 
抄送: "木羊羽"<1948281933@QQ.COM>; "Author"<author@noreply.github.com>; 
主题: Re: [Fndroid/clash_for_windows_pkg] 在Profiles添加clash订阅链接后在Proxies中没有节点 (#195)




有没有考虑过点一下这个profile选中它

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/64915651-47bec500-d79e-11e9-931d-a245dd879b08.png)
