### ISSUE TITLE
即使切换TUN状态

### ISSUE THREAD

**Issue by w3AD4y-r5** [Fndroid/clash_for_windows_pkg#1951]
**描述**
希望更改mixin后，TUN状态可以立即在TRUE和FALSE间切换，不用重启CLASH

**其他说明**
现版本更改mixin中的tun enable状态后，必须重启clash才能发挥作用

**Comment by yi-Xu-0100** [comment]
@w3AD4y-r5 只需要修改后开关 mixin 一下应该就可以。
