### ISSUE TITLE
功能建議

### ISSUE THREAD

**Issue by da-gongren** [Fndroid/clash_for_windows_pkg#1955]
**描述**
PC 上打開 allow lan 後，同 wifi 的局域網手機配置代理，手機不會繞過 PC 配置的繞過地址，希望可以支持下？

**其他说明**
无

**Comment by Fndroid** [comment]
控制不了你的手机，怎么支持

**Comment by da-gongren** [comment]
@Fndroid 那手機上網的規則不遵守 PC 上 cfw 配置文件的 “cfw-bypass:” 嗎

**Comment by yi-Xu-0100** [comment]
@da-gongren 那个 cfw-bypass 是设置 windows 系统代理的。

**Comment by da-gongren** [comment]
@yi-Xu-0100 那手機那邊默認應該也有規則吧？試了下，好像有繞過局域網的 IP

**Comment by yi-Xu-0100** [comment]
@da-gongren 手机配置代理的时候，也有设置“不使用网址”，即bypass。(下面是小米10 pro的演示)

![IMG_20210610_152701.jpg](https://user-images.githubusercontent.com/25523606/121483048-5e09ad00-c993-11eb-99b9-cc6729dc135a.jpg)
