### ISSUE TITLE
注册表 NlaSvc 设置代理参数错误

### ISSUE THREAD

**Issue by MisteryMonster** [Fndroid/clash_for_windows_pkg#1958]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 10 21H1 19043.985
**描述**

[//]: # (请具体并清楚地描述遇到的问题)
设置系统代理时 NlaSvc 的代理设置似乎有问题，导致网络识别错误，让一些依赖判断网络类型的应用无法联网（比如Office）。
**复现**

[//]: # (请描述复现问题的步骤)

1. 关闭系统代理
2. 打开系统代理
3. 注册表参数 `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet\ManualProxies\(Default)` 被设置为 `1127.0.0.1`
**预期行为**

[//]: # (清晰地描述期望看到的行为)
注册表参数应该被正确设置为代理地址及端口
**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**
[//]: # (如果可以，请提供对应问题的截图)
![{086C0F13-0032-42D5-9302-20298BB98119}](https://user-images.githubusercontent.com/40703811/121616972-8d551280-ca96-11eb-82ce-79c3b857dadf.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
@MisteryMonster 

![image](https://user-images.githubusercontent.com/25523606/121762202-0a4fbd00-cb67-11eb-89f5-d182ba3aad56.png)

个人测试了下，你比我多一条。建议减少筛选，查看具体哪个软件造成的。

**Comment by yi-Xu-0100** [comment]
@MisteryMonster 抱歉，是我的筛选问题，我保留和你一样的筛选后，出现了同样的设置问题。考虑到我使用了 Specify Protocol 。应该是 cfw 触发的。

![image](https://user-images.githubusercontent.com/25523606/121762909-5270de80-cb6b-11eb-8d26-f762aceb90e3.png)

无 Specify Protocol 情况下：

![image](https://user-images.githubusercontent.com/25523606/121763033-9e238800-cb6b-11eb-97a9-e2d16e9e64ca.png)

**Comment by LeslieYon** [comment]
![image](https://user-images.githubusercontent.com/43743875/122634710-4f00c880-d112-11eb-94b4-4880863304b6.png)
确实有这方面的问题。难怪Windows10总是检测无网络连接。

**Comment by yi-Xu-0100** [comment]
不过，感觉奇怪的是，这个修改看起来是系统在注册表变化做的，而且，个人使用中，未触发相关网络检测问题。

**Comment by LeslieYon** [comment]
重新测试了一下，发现是Windows10的问题。
即便用户手动开启代理设置，这个位置也会变成1127.0.0.1。
准确地说，系统会在填写的代理服务器IP地址前加上字符“1”，然后设置到这个位置。

**Comment by MisteryMonster** [comment]
不知道是不是 `sysproxy.exe` 触发的修改，因为我在切换“”手动代理“”开关是不会修改这个值的。我这里运行 CFW 目录 `resources\static\files\win\common` 下的 `sysproxy.exe global <proxy-server>` 就会有这个问题。但是进一步我发现这个问题并不是真正影响“无网络连接”，因为当我修改该值为正确的代理地址时会触发一次 NlaSvc 的检测，错以为是值本身的问题。当我把该注册表项删除权限后（NlaSvc 不再有权限修改了，因此是固定的）固定为 `127.0.0.1:7890` 还是会发生无网络连接的问题。忘记补充一个十分重要的：我的网络环境需要认证，NlaSvc 的 Active Probing 有超时的设定，因此问题的发生应该是我没能在超时前认证所以显示为无网络连接。而且 Passive Polling 看样子是没有正常运作，不知道该怎么办。现在十分尴尬，这个小问题似乎应该在[https://github.com/Noisyfox/sysproxy](https://github.com/Noisyfox/sysproxy) 这里提了。先 Close。
