### ISSUE TITLE
连接问题 提取自log

### ISSUE THREAD

**Issue by mrliu666666** [Fndroid/clash_for_windows_pkg#196]
dial Proxy error: uslaxbgp11.host-sub.com:38076 connect error: lookup uslaxbgp11.host-sub.com: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server."
请问这是什么问题？

**Comment by Fndroid** [comment]
@mrliu666666 什么版本？升级到最新版试试

**Comment by mrliu666666** [comment]
@Fndroid F大，是最新版本0.7.8

**Comment by Fndroid** [comment]
配置文件的dns先关闭试试

**Comment by mrliu666666** [comment]
@Fndroid config.yml里哪个是dns关闭？

**Comment by mrliu666666** [comment]
@Fndroid 不是dns的问题 因为配置文件里没有这个选项

**Comment by Fndroid** [comment]
打开cmd，再输入 

nslookup uslaxbgp11.host-sub.com 

看看输处什么内容

**Comment by mrliu666666** [comment]
@Fndroid 
服务器:  public1.alidns.com
Address:  223.5.5.5

非权威应答:
名称:    uslaxbgp11.host-sub.com
Address:  38.121.20.36

**Comment by Fndroid** [comment]
这个log不是一直出现的？

**Comment by mrliu666666** [comment]
@Fndroid 对有时候突然就出现 过一会就好了 好奇怪

**Comment by Fndroid** [comment]
那就是有时候你本地的DNS解析不出来这个域名导致的，你可以试着换其他DNS试试
