### ISSUE TITLE
Select After Updated 功能无效

### ISSUE THREAD

**Issue by OG-C** [Fndroid/clash_for_windows_pkg#1964]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

WIN10 20H2
CFW 0.15.10

[//]: # (平台及版本号)

**描述**

设置里启用Select After Updated后，实际不产生作用

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)
1. 进入'Settings'
2. 点击'Select After Updated'
3. 触发问题

**预期行为**

更新配置后，自动选择当前更新的配置

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
如果功能是“更新配置后，自动选择当前更新的配置”的话，确实可复现不产生作用。

但是这样，该功能应该也会触发自动更新，也会切换配置。感觉不太对。

**Comment by OG-C** [comment]
@Fndroid 谢谢F大，0.16.0修复了这个BUG，但还是有个问题，当点击更新全部时，会导致全部配置挨个选一遍(观感上是这样，不知道是不是)，个人理解"Select After Updated"这个功能在点击"Update All"时逻辑上应该不作更改的
