### ISSUE TITLE
Service Mode 无法正常启动，服务进程意外停止。

### ISSUE THREAD

**Issue by NevadaCities** [Fndroid/clash_for_windows_pkg#1967]
**信息**

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 21H1 内部版本 19043.1055

**描述**

无法启动Service Mode，General页面显示灰色图标，但服务已经安装，尝试过1.5.10与1.5.9版本都无法启动。尝试使用net start手动启动“Clash Core Service”服务提示1607错误。

**复现**

问题可以被复现，但是触发此问题的原因未知。

**预期行为**

无

**日志**

![屏幕截图 2021-06-13 141720](https://user-images.githubusercontent.com/58358419/121797333-24b29500-cc52-11eb-88a5-b6c4e5d8969f.png)
![屏幕截图 2021-06-13 134904](https://user-images.githubusercontent.com/58358419/121796782-35f9a280-cc4e-11eb-8a48-59b61a3e85fb.png)
![屏幕截图 2021-06-13 134923](https://user-images.githubusercontent.com/58358419/121796783-36923900-cc4e-11eb-8678-8c7320d6569e.png)

**截图**

![屏幕截图 2021-06-13 133432](https://user-images.githubusercontent.com/58358419/121796617-07c79300-cc4d-11eb-9de9-c64d0c426952.png)
![屏幕截图 2021-06-13 133525](https://user-images.githubusercontent.com/58358419/121796618-08f8c000-cc4d-11eb-96e1-509127c0879b.png)
![屏幕截图 2021-06-13 134303](https://user-images.githubusercontent.com/58358419/121796779-33974880-cc4e-11eb-9717-08d9329bf006.png)
![屏幕截图 2021-06-13 143544](https://user-images.githubusercontent.com/58358419/121797743-c63ae600-cc54-11eb-8e39-da0c577abf26.png)

**其他说明**

软件版本：
Clash for Windows : 1.5.9 - 1.5.10
Clash-core : Premium 2021.04.08 - Premium 2021.05.08
WinTUN : 0.11.0

**Comment by yi-Xu-0100** [comment]
@NevadaCities google 搜索 ”发生系统错误 1067“，大部分是 mySQL 服务启动错误，不过你可以看下相关的解决办法试试。

**Comment by NevadaCities** [comment]
设备重启就解决了，估计这个问题和 #1944 一样的情况
