### ISSUE TITLE
支持多种订阅类型查看订阅信息

### ISSUE THREAD

**Issue by Quetweilan** [Fndroid/clash_for_windows_pkg#1968]
**描述**

查看订阅信息的功能非常实用。
可以在不打开机场网址的情况下了解流量情况和到期时间。
对于网络上获取的订阅情况更清晰。

现在只支持https://jichang.xyz/link/123123123?clash=1 这种形式的订阅。
对于https://jichang.xyz/api/v1/client/subscribe?token=123123 或者其他形式的订阅都无法查看信息。
希望能支持

**Comment by yi-Xu-0100** [comment]
@Quetweilan 只能从订阅链接的 header 中获取相关信息，如果订阅链接没有提供，则不会获取到。

**Comment by Quetweilan** [comment]
之前有提到过userinfo是由Quantumult建议，那么能不能从shadowrocket使用同样的方法，shadowrocket是可以获取下面那种订阅的订阅信息的

**Comment by yi-Xu-0100** [comment]
@Quetweilan 不知道，你可以去看看 shadowrocket 的实现方式，应该也是和他的订阅链接有关， clash 的订阅链接和他应该不是一个，没有提供的话，就没法了。

**Comment by Fndroid** [comment]
和什么连接没有关系，只要是header里有数据就能显示
