### ISSUE TITLE
如果内置一个订阅转换就更完美了

### ISSUE THREAD

**Issue by king4107** [Fndroid/clash_for_windows_pkg#1974]
**描述**
如果内置一个订阅转换就更完美了，这样更方便。

**其他说明**
在PROFILES里添加个转换按钮，点击弹出订阅转换框，把普通订阅连接黏贴转换后，直接生成clash配置，完美。

**Comment by yi-Xu-0100** [comment]
这不应该向提供商要求提供支持 clash 订阅链接吗？

**Comment by Fndroid** [comment]
没有计划
