### ISSUE TITLE
tun 模式 DNS 请求问题

### ISSUE THREAD

**Issue by MichaelPan1026** [Fndroid/clash_for_windows_pkg#1976]
**信息**
- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Windows 10 Version 21H1

**描述**
开启 tun 模式并设置 DNS 后，DNS 请求还是会走向路由器。

**预期行为**
在路由器 DNS 请求记录上没有来自这台电脑的请求

**截图**
![圖片](https://user-images.githubusercontent.com/26241105/122373633-38ccfe00-cf94-11eb-90b1-0f8532e52860.png)
![圖片](https://user-images.githubusercontent.com/26241105/122373662-3f5b7580-cf94-11eb-8733-2261e1bbb66e.png)

**Comment by AkariiinMKII** [comment]
请求是谁发起的呢？
已知 chromium based 的浏览器在非隐身模式下会通过所有网卡发送DNS query

**Comment by MichaelPan1026** [comment]
> 请求是谁发起的呢？
> 已知 chromium based 的浏览器在非隐身模式下会通过所有网卡发送 DNS query

Firefox.

**Comment by Fndroid** [comment]
这个我印象中是系统行为（curl），即使是没有连接的网卡，系统也会向它们设置的DNS服务器发送查询请求

**Comment by MichaelPan1026** [comment]
> 
> 
> 这个我印象中是系统行为（curl），即使是没有连接的网卡，系统也会向它们设置的DNS服务器发送查询请求

那就没法主导浏览器访问的网站时的 DNS 请求发给谁了啊，有点难受。

**Comment by Fndroid** [comment]
这个在软件层面没办法解决，系统设计是这样
