### ISSUE TITLE
打开clash for windows软件空白

### ISSUE THREAD

**Issue by lixuyong2014** [Fndroid/clash_for_windows_pkg#1977]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

win10

**描述**
 
下载后clash for windows后打开软件，软件界面空白，点击电脑桌面右下角clash，toggle dev查看console控制台，报三条错误，第一条显示unload reload.js，第二条显示cannot find  .../app.asar/.../reload.js

**复现**

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/442

**Comment by lixuyong2014** [comment]
> #442

感谢

**Comment by NLNLZNLT** [comment]
没看懂，能麻烦详细讲解一下吗
