### ISSUE TITLE
想了解一下如何检测用户剩余流量的

### ISSUE THREAD

**Issue by Flaryer** [Fndroid/clash_for_windows_pkg#1979]
**描述**
想了解一下如何检测用户剩余流量的，我配置文件里没有出现剩余流量，有点好奇。

![图片](https://user-images.githubusercontent.com/30646834/122553810-c1b66900-d06a-11eb-901d-19821cbdf81d.png)

**其他说明**
无

**Comment by Fndroid** [comment]
https://github.com/crossutility/Quantumult/blob/master/extra-subscription-feature.md

**Comment by Flaryer** [comment]
谢谢大佬！

**Comment by imwyh** [comment]
> https://github.com/crossutility/Quantumult/blob/master/extra-subscription-feature.md

谢谢大佬！大佬牛啊
