### ISSUE TITLE
服务模式开启后clash-core-service无法自启

### ISSUE THREAD

**Issue by MrZQAQ** [Fndroid/clash_for_windows_pkg#1982]
**信息**

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

windows10 21H1 19043.1052

**描述**

软件设置：激活service mode，开启轻量模式，便携模式，使用系统代理，未加载网卡

关机再开机后，clash core service服务不能自动启动，软件内service mode为灰色
手动运行  `clash-core-service.exe` 控制台阻塞，无输出，点击logo重启软件后产生输出

后通过 `service.exe` 运行服务后，可正常使用

**复现**

1. 开始菜单关机
2. 启动，正常进入桌面
3. clash GUI能够启动
4. 任务管理器查看进程，clash-core-service 和 clash-win64 均未运行

本机复现概率100%

**预期行为**

  重启系统后服务正常运行

**截图**

软件内设置：
![image](https://user-images.githubusercontent.com/22658616/122629322-b73db300-d0ee-11eb-93e4-e8ccc512be05.png)
![image](https://user-images.githubusercontent.com/22658616/122629327-c02e8480-d0ee-11eb-8dd3-696ba66c3adf.png)

重启后服务没有运行：
![image](https://user-images.githubusercontent.com/22658616/122629353-e2280700-d0ee-11eb-8163-00d0a100a0ec.png)

手动从控制台启动：
![image](https://user-images.githubusercontent.com/22658616/122629381-1996b380-d0ef-11eb-968f-02f6e732e791.png)

**其他说明**

事件查看器显示，服务启动失败，目前有两种报错
1. 
![image](https://user-images.githubusercontent.com/22658616/122629492-fe787380-d0ef-11eb-8aef-638d08b8fc65.png)
2. 
![image](https://user-images.githubusercontent.com/22658616/122629501-164ff780-d0f0-11eb-9dac-e925e894517e.png)

与 #1707 相似，但是我没有使用TAP/TUN模式

**Comment by yi-Xu-0100** [comment]
@MrZQAQ

软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**Comment by MrZQAQ** [comment]
> @MrZQAQ
> 
> 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

现已使用仓库下载版本，问题可复现
