### ISSUE TITLE
添加系统代理的代理服务器ip地址设置

### ISSUE THREAD

**Issue by kxxt** [Fndroid/clash_for_windows_pkg#1987]
**描述**
现在 CFW 在设置系统代理时会默认将代理服务器IP设置为 `127.0.0.1`，
但是这会导致 Windows 沙盒无法联网，
经过简单的分析可以知道，Windows 沙盒会自动继承主机的代理服务器设置，而且无法修改。
( 更确切地说是，Windows 沙盒的代理服务器设置被强制和主机同步)
Window 沙盒继承主机的代理服务器设置的`127.0.0.1`IP地址，就导致沙盒无法联网。
通过将代理服务器的IP地址设置为 Windows 沙盒所用虚拟网卡上主机的IP地址，例如`172.22.64.1`，可以让 Windows 沙盒联网并且走系统代理。
目前可以通过手动修改主机的代理服务器设置来实现，每次打开 CFW 都要手动设置一遍。
建议增加一条设置，可以在 CFW 设置系统代理时使用指定的代理服务器的IP地址。

**其他说明**
![image](https://user-images.githubusercontent.com/18085551/122705046-81800200-d287-11eb-9156-b1fce391bf3e.png)
![image](https://user-images.githubusercontent.com/18085551/122705096-9f4d6700-d287-11eb-93a2-c39539007188.png)
![image](https://user-images.githubusercontent.com/18085551/122705140-b4c29100-d287-11eb-8b9e-343c77d58d8d.png)
![image](https://user-images.githubusercontent.com/18085551/122705172-c2781680-d287-11eb-9ff8-54127395e20a.png)

**Comment by Fndroid** [comment]
可以试试PAC，把地址直接写在PAC Content里

**Comment by kxxt** [comment]
> 可以试试PAC，把地址直接写在PAC Content里

感谢提醒， 但是这样做问题仍然存在。
Windows 沙盒继承代理设置后会尝试向沙盒本身的端口获取 pac 脚本，这注定是会失败的。
不过这样做虽然解决不了让沙盒也翻墙的问题，但至少可以解决设置系统代理时沙盒无法上网的问题。
![image](https://user-images.githubusercontent.com/18085551/122924673-99937680-d398-11eb-8b3f-96a5428e94a6.png)

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/123046670-f3df1680-d42e-11eb-9b8b-669150f3c813.png)
下个版本支持

**Comment by kxxt** [comment]
十分感谢作者能够添加此项功能！🎉🎉
________________________________

**Comment by kxxt** [comment]
Close this issue since the desired functionality has been implemented.

**Comment by CellLz** [comment]
最近正被这个问题困扰着，没想到直接就搜到解决方案了
