### ISSUE TITLE
使用TUN模式电脑开热点CPU占用一直100%

### ISSUE THREAD

**Issue by ChengjinYang** [Fndroid/clash_for_windows_pkg#1997]
使用TUN模式电脑开热点CPU占用一直100%，logs和connections一直疯狂输出IP，一直在发送数据，电脑明显卡顿，关了热点功能立马改善

Win10 专业版 21H1，Clash版本0.16.0

**Comment by kingforme** [comment]
#1444
#1925

**Comment by ChengjinYang** [comment]
> [#1444 ](https://github.com/Fndroid/clash_for_windows_pkg/issues/1444)
> #1925

？

**Comment by ChengjinYang** [comment]
> 使用TUN模式电脑开热点CPU占用一直100%，日志和连接一直在疯狂输出IP，一直在发送数据，电脑显示卡顿，关了重点功能立马改进
> 
> Win10专业版21H1，冲突版本0.16.0
