### ISSUE TITLE
能否添加程序启动退出时自动修改系统代理功能？

### ISSUE THREAD

**Issue by lvhe19880210** [Fndroid/clash_for_windows_pkg#2]
类似ssr，启动时自动修改系统代理，这样切换不同客户端时不用每次都手动改系统代理

**Comment by Fndroid** [comment]
不会在启动退出时开关系统代理，但是最新版加入了开关系统代理的选项

**Comment by lvhe19880210** [comment]
感谢～～

Fndroid <notifications@github.com> 于2018年10月26日周五 下午6:06写道：
