### ISSUE TITLE
lightweight模式可否做到自动开机时不会自动打开主界面

### ISSUE THREAD

**Issue by plutonemhikari** [Fndroid/clash_for_windows_pkg#2001]
**描述**
现在的版本，开启lightweight模式后，silent start会失效，使得lightweight模式有些不完美。如果能够做到开始lightweight模式时，silent start仍然有效，会更好。

**其他说明**
其他补充内容

**Comment by AkariiinMKII** [comment]
在 lightweight mode 下 cfw 没有后台，拉起 clash core 和载入配置文件需要 cfw 主进程在前台执行
