### ISSUE TITLE
新版本clash打开代理后有道云笔记会无法同步

### ISSUE THREAD

**Issue by purextrem** [Fndroid/clash_for_windows_pkg#2002]
**描述**
新版本(0.16.0)打开系统代理后，有道云笔记会无法同步，永远显示正在准备数据，关闭clash系统代理后正常。但是以前从来没这个问题。然后我重新安装了0.13.5版的，打开代理后，有道云也是可以正常同步的。

反复测试了两三次，确认是跟clash新版本系统代理相关。在 domain 配置中设置了 youdao.com域名 direct ，也是这样。connections中显示有道是直连的。然后看到clash帮助中说bypass可以绕过代理，我就在里面添加了youdao.com，但是似乎没效果，connections中还是会youdao，最终只能使用低版本。

想咨询这是什么原因导致的，我一直以为程序只要 direct ，代理就不会对软件造成影响。

不是程序员，所以对这个软件的具体设置不太懂~

**Comment by yi-Xu-0100** [comment]
@purextrem 给出bypass具体设置，比如截图，并检查系统设置，系统代理部分是否一致

**Comment by purextrem** [comment]
我又试了一下，安装0.16.0版本后就又不能更新了（然后我试了下0.15.8版本也不行），然后检查了系统代理设置是ok的，bypass设置如图。只要换回0.13.5版本就正常了，然后我又试了下载了0.14.10版本也正常，猜测是0.15-0.16的版本哪里的改变和这个问题有相关性。
![image](https://user-images.githubusercontent.com/86669927/123964271-d3dac480-d9e5-11eb-8476-3a46940a2426.png)
![image](https://user-images.githubusercontent.com/86669927/123964324-e35a0d80-d9e5-11eb-99df-417633bc9123.png)
![image](https://user-images.githubusercontent.com/86669927/123964401-f2d95680-d9e5-11eb-9c23-f60bb266f8e4.png)
![image](https://user-images.githubusercontent.com/86669927/123964447-fec51880-d9e5-11eb-8f14-d7462f3dc854.png)
![image](https://user-images.githubusercontent.com/86669927/123964501-0dabcb00-d9e6-11eb-9ba4-e93943b0bc50.png)

**Comment by yi-Xu-0100** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/1360#issuecomment-732524206

**Comment by purextrem** [comment]
> [#1360 (comment)](https://github.com/Fndroid/clash_for_windows_pkg/issues/1360#issuecomment-732524206)

重设置bypass后，问题已解决~非常感谢~
