### ISSUE TITLE
tun模式未能建立clash网卡

### ISSUE THREAD

**Issue by FoobarRogers** [Fndroid/clash_for_windows_pkg#2005]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

win1021H1 19043.1052

**描述**

clash按要求的mixin配置文件填写、打开mixin、启动tun，但仍然未建立clash虚拟网卡，应用也没有获得代理

**复现**

[//]: # (请描述复现问题的步骤)

1.按文档修改mixin

dns:
  enable: true
  enhanced-mode: redir-host
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 8.8.8.8 
    - 114.114.114.114 # 真实请求DNS，可多设置几个
interface-name: 1000Gbps # 出口网卡名称，或者使用下方的自动检测
tun:
  enable: true
  stack: gvisor # 使用 system 需要 Clash Premium 2021.05.08 及更高版本
  dns-hijack:
    - 198.18.0.2:53
  auto-route: true
#auto-detect-interface: true # 自动检测出口网卡（当前设置自动检测无效

2. 打开mixin
3. 打开tun模式，软件重启
4. 查看“网络连接”并没有新增clash网卡
5. 
**预期行为**

浏览器和windows组件正常访问墙外服务

网络适配器列表出现名称为Clash，备注为Clash Tunnel的网络适配器

**日志**

time="2021-06-30T10:39:33+08:00" level=info msg="Start initial compatible provider Proxy"
time="2021-06-30T10:39:33+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2021-06-30T10:39:33+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2021-06-30T10:39:33+08:00" level=warning msg="[TCP] dial DIRECT (match Match/) to raw.githubusercontent.com error: lookup raw.githubusercontent.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."
time="2021-06-30T10:39:33+08:00" level=warning msg="[TCP] dial DIRECT (match Match/) to raw.githubusercontent.com error: lookup raw.githubusercontent.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."
time="2021-06-30T10:39:33+08:00" level=info msg="[TCP] 127.0.0.1:65470 --> api.github.com match Match() using DIRECT"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial compatible provider YouTube"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial compatible provider AdBlock"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial compatible provider Microsoft"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial compatible provider Spotify"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial compatible provider AsianTV"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial compatible provider PayPal"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial compatible provider Netflix"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial compatible provider Telegram"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial compatible provider Disney"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial compatible provider Auto - UrlTest"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial compatible provider Domestic"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial compatible provider Scholar"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial compatible provider GlobalTV"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial compatible provider Speedtest"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial compatible provider Apple"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial compatible provider Proxy"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial compatible provider Others"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial compatible provider Steam"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider BBC iPlayer"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Amazon"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Apple"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Telegram"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Steam"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Pandora"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider PayPal"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Fox Now"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Microsoft"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider PROXY"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Apple News"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider DAZN"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider encoreTVB"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Speedtest"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider HBO"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider ABC"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Domestic"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Tencent Video"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Hulu"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider WeTV"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Scholar"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Netflix"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Netease Music"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider iQiyi"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Disney Plus"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider KKTV"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Bahamut"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Reject"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider JOOX"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider myTV SUPER"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider ViuTV"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider LAN"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Hulu Japan"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Soundcloud"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Spotify"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Fox+"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Special"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Pornhub"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Letv"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Japonx"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Discovery Plus"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Bilibili"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Line TV"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Domestic IPs"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Apple TV"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider YouTube"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Youku"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider PBS"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider KKBOX"
time="2021-06-30T10:39:33+08:00" level=info msg="Start initial rule provider Abema TV"
time="2021-06-30T10:39:33+08:00" level=info msg="[TCP] 127.0.0.1:55292 --> alive.github.com match Match() using DIRECT"
time="2021-06-30T10:39:33+08:00" level=debug msg="[DNS] alive.github.com --> 140.82.112.26"
time="2021-06-30T10:39:33+08:00" level=info msg="[TCP] 127.0.0.1:54367 --> alive.github.com match RuleSet(PROXY) using Proxy[🇭🇰 香港 AIA [East]]"
time="2021-06-30T10:39:36+08:00" level=info msg="[TCP] 127.0.0.1:64942 --> 91.108.56.188 match RuleSet(Telegram) using Telegram[🇭🇰 香港 AIA [East]]"
time="2021-06-30T10:39:36+08:00" level=info msg="[TCP] 127.0.0.1:64943 --> 91.108.56.188 match RuleSet(Telegram) using Telegram[🇭🇰 香港 AIA [East]]"
time="2021-06-30T10:39:36+08:00" level=debug msg="[DNS] setting1.hicloud.com --> 119.3.92.108"
time="2021-06-30T10:39:36+08:00" level=info msg="[TCP] 127.0.0.1:64950 --> setting1.hicloud.com match RuleSet(Domestic IPs) using Domestic[DIRECT]"
time="2021-06-30T10:39:36+08:00" level=debug msg="[DNS] setting1.hicloud.com --> 119.3.92.108"
time="2021-06-30T10:39:36+08:00" level=info msg="[TCP] 127.0.0.1:64954 --> setting1.hicloud.com match RuleSet(Domestic IPs) using Domestic[DIRECT]"
time="2021-06-30T10:39:36+08:00" level=debug msg="[DNS] upfile1.hicloud.com --> 49.4.20.82"
time="2021-06-30T10:39:37+08:00" level=info msg="[TCP] 127.0.0.1:64958 --> upfile1.hicloud.com match RuleSet(Domestic IPs) using Domestic[DIRECT]"

[//]: # (如果可以，请提供对应问题的截图)

![image](https://user-images.githubusercontent.com/25246983/123893873-c8f54500-d98f-11eb-93f9-676c7e24a1d7.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
mixin 内容是上面的？第一行没有 `mixin:` ?

**Comment by FoobarRogers** [comment]
> mixin 内容是上面的？第一行没有 `mixin:` ?

有的，默认有mixin那行

**Comment by yi-Xu-0100** [comment]
@FoobarRogers 检查缩进。查看 https://docs.cfw.lbyczf.com/contents/questions.html 中部分解决办法是否有效。

**Comment by FoobarRogers** [comment]
> @FoobarRogers 检查缩进。查看 https://docs.cfw.lbyczf.com/contents/questions.html 中部分解决办法是否有效。

好了，原来mixin下面 的代码要整体缩进一格
