### ISSUE TITLE
英雄联盟主页无法加载，确定是clash的问题

### ISSUE THREAD

**Issue by bb2** [Fndroid/clash_for_windows_pkg#2010]
[](url)**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 20H2

**描述**

英雄联盟主页无法加载

**复现**

1.启动英雄联盟客户端
2.进入游戏
3.主页加载失败

**预期行为**

主页加载成功

**其他说明**
搜索问题只有 [https://github.com/Fndroid/clash_for_windows_pkg/issues/1815](https://github.com/Fndroid/clash_for_windows_pkg/issues/1815) 有提过类似的问题，但是我是除此问题之外，其它规则匹配代理功能一切正常。

是在开启Service Mode也就是tun之后才出现这样的问题。
可以确定是clash的问题，因为同样的问题在OpenClash上也有。一直是最新版本，在不同电脑上测试也是同样的问题，甚至在虚拟机上也是如此。
也不是配置文件的问题，试了几个机场默认的托管配置文件问题仍然是存在的。

各位英雄联盟玩家有遇到和我一样问题的吗？如果有人是正常加载的希望也可以回复一下。
相同的issue：[https://github.com/vernesong/OpenClash/issues/1433](https://github.com/vernesong/OpenClash/issues/1433)

**Comment by bb2** [comment]
问题已解决 [https://github.com/vernesong/OpenClash/issues/1433](https://github.com/vernesong/OpenClash/issues/1433)

**Comment by daomengRen** [comment]
> 问题已解决 [vernesong/OpenClash#1433](https://github.com/vernesong/OpenClash/issues/1433)

大佬，能贴一下你的dns配置吗，我在开启TUN 模式的情况下，也无法启动英雄联盟
