### ISSUE TITLE
在 rules 中对 RULE-SET 规则再次分流（套娃）

### ISSUE THREAD

**Issue by stars-island** [Fndroid/clash_for_windows_pkg#2019]
**描述**
　　一般地，去广告白名单的域名会使用以下方式来放行：
```
RULE-SET,白名单规则,DIRECT(或者其它proxy-groups)
```
　　但是，当这条规则里的有些域名更适合走代理，有些域名更适合走直连的时候，可以设想，设计一种新的方式，将白名单规则再进行分流，分流按已有的 proxy-groups 再走一次：
```
RULE-SET,白名单规则,PROXY-GROUPS(之类的叫法)
```
　　或者
```
RE-PROXY-GROUPS,RULE-SET,白名单规则
```
　　就像是一种套娃。这样就可以对 混杂了适合不同连接策略 的规则走多一次分流。

　　为了避免规则编写不当，保证软件运行效率，初期建议套娃功能用类似 ```MATCH``` ```GEOIP``` 等字段固定下来，人为限定针对使用了套娃功能的规则，其套娃动作只能发生 1 次，不能出现套娃里再套娃的情况。例如：
```
payload:
  # 内容：小林
  # 数量：24条
  # USER-AGENT,啦啦啦
  - DOMAIN-KEYWORD,114514
  - DOMAIN-SUFFIX,哼哼啊啊啊啊.com
  - RE-PROXY-GROUPS,先辈规则        #  这条被忽略
```
```
rules:
  RE-PROXY-GROUPS,RULE-SET,白名单规则    #  这条在线规则只会发生 1 次再分流。若规则里含有同样的套娃字段，则忽略【先辈规则】 ，不再对它触发套娃动作。
```

**其他说明**
　　诚然，将某条域名单独拎出来放行也不是不可以。不过在此考虑到，某些白名单规则可能写得比较长，同时在线规则是会不定期更新的，个人手动自编的时效性弱于在线更新。自动化有利于进一步解放人的双手。所以综上所述，提出此功能。
　　感谢开发者！

**Comment by yi-Xu-0100** [comment]
自己的自定义规则，可以放在规则的最上面，匹配会按照自上而下的方式匹配。

**Comment by Fndroid** [comment]
反复读了几次，看不明白你想实现的效果。

我猜测你是想覆盖别人的规则集，按照：
> 不过在此考虑到，某些白名单规则可能写得比较长，同时在线规则是会不定期更新的，个人手动自编的时效性弱于在线更新。

这个说法，规则集的作者要再维护一个你认为可以代理的规则？那他为什么不直接把直连的规则删掉？

想覆盖他原有的规则除了自己手动写，还有其他办法吗？

**Comment by stars-island** [comment]
感谢两位回复！

我本来的意思是，对规则集里面的某几条规则作分流处理。我这种想法应该属于 rules 上加 rules 的情况，（大概不太可行……）

因为我要用的规则集是一个针对去广告的白名单，含有 firefox 相关的域名，要将它走代理；但是同时，同一规则集里还有什么 weibo 、 联通之类的域名必须走直连，所以整体对规则集套直连策略不合适，套代理策略也不合适。

现在折衷的办法，按照从上往下依次匹配，上面的优先级更高的原则，将自己特殊的几条自定义规则手动写在规则集的前面。

希望我这样子解释能更清晰地表达我的想法~

**Comment by yi-Xu-0100** [comment]
@stars-island 嗯，自上而下的匹配模式很容易实现自定义规则的重载，自定义规则可以使用 parser 维护，如果需要公开和更新，可以将自己的自定义规则做成 rule-provider 的形式，然后用 parser 引入在规则前部。（需要注意：parser 更新需要更新配置，rule-provider 更新，需要等待 provider 更新。）

**Comment by stars-island** [comment]
@yi-Xu-0100 明白，感谢教导！
