### ISSUE TITLE
Could not run clash core

### ISSUE THREAD

**Issue by qq412524875** [Fndroid/clash_for_windows_pkg#202]
![8fb3aa1d5588a8ceff61cd77bba2dfa](https://user-images.githubusercontent.com/18748508/65317916-4abb1a80-dbcf-11e9-8e34-19e0deadb652.png)
[2019-09-20-174904(1).log](https://github.com/Fndroid/clash_for_windows_pkg/files/3635297/2019-09-20-174904.1.log)
更新，修复都没有解决

**Comment by Fndroid** [comment]
@qq412524875 把最新的log发出来看看

**Comment by qq412524875** [comment]
这个就是最新的log了，之前的log都是一样的。没有报error说明端口占用

**Comment by Fndroid** [comment]
用了proxifier之类的代理软件吗

**Comment by qq412524875** [comment]
妹子电脑第一次装代理软件-.-

**Comment by Fndroid** [comment]
@qq412524875 那我也不知道是什么了。只要是clash的api访问不到就是这个界面了。有其他软件干扰了请求

**Comment by qq412524875** [comment]
close掉吧！估计是妹子电脑里乱七八糟的东西导致的！！
