### ISSUE TITLE
打开网页时，需再次刷新才能正常加载网页

### ISSUE THREAD

**Issue by lsjiaowo** [Fndroid/clash_for_windows_pkg#2028]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统** Win10 21H1

[//]: # (平台及版本号)

**描述** 使用最新版Clash.for.Windows-0.16.2

[//]: # (请具体并清楚地描述遇到的问题)

**复现** 运行Clash，打开网页，需再次刷新才能正常加载网页

[//]: # (请描述复现问题的步骤)

1. 运行Clash代理，规则Rule
2. 打开网页（网站运行均正常可访问）
3. 网页提示：该网页无法正常运作/无法访问此网站（无论被墙或未被墙）
4. 然后刷新一下，网页正常加载完成

**预期行为**

希望运行Clash的时候，网页能正常一次性完成加载，正常打开，无需再次刷新

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

![image](https://user-images.githubusercontent.com/49240966/125155308-7dae1400-e191-11eb-862c-e409eb266de9.png)

**其他说明**

在[#521](https://github.com/Fndroid/clash_for_windows_pkg/issues/521)中同样提到该问题，给出的原因解释如下，但并未有解决方法：
因为clash for windows 每次启动之后，clash-win64.exe(核心) 也会跟着启动，问题就在这 每次核心启动总是慢一秒 于clash for windows 或者说 clash的核心 与 clash for windows 不能同步启动，导致clash for windows 启动了，实际上核心没启动就访问不了代理网站

**Comment by Fndroid** [comment]
我没看明白什么意思。意思是启动CFW之后，马上访问一个网站，会访问不了是吗？还是说界面已经加载完成了，之后访问网站都显示无法访问？

**Comment by lsjiaowo** [comment]
CFW界面已经加载完成了，访问一个网站，访问不了，显示无法访问此网站，然后再刷新一下网页就加载出来了。此时如果继续打开其他新网页都可以打开。
但是如果闲置一段时间，再点开新的网页，就又打不开了，再次刷新，就又能打开了。
[#521](https://github.com/Fndroid/clash_for_windows_pkg/issues/521#issuecomment-606956583)这里有同样的描述

**Comment by Fndroid** [comment]
界面如果加载完，那clash-win64肯定就已经启动完了

**Comment by lsjiaowo** [comment]
Clash界面加载完应该是这样的吧（我没理解错吧）。就是在这样的状态，网页需要再次刷新才能打开

![image](https://user-images.githubusercontent.com/49240966/125162768-443ece00-e1bc-11eb-8651-cedc25b8b78a.png)

**Comment by Fndroid** [comment]
那肯定没有问题，建议你用无痕模式试试，不排除你插件有问题

**Comment by Pearlulu** [comment]
我也是更新16.2后用PAC模式就经常这样子，会显示已重置，而且还进不去路由器设置网页，换成http模式暂时没事了。

**Comment by akw5454521** [comment]
是电信163网络的问题吧，换联通网络试试呢？

**Comment by MuXiangChen** [comment]
我也是，简直折磨人，总是需要刷新几次才能正常打开网页

**Comment by lsjiaowo** [comment]
@ChuanfengZhang 更新之后就好了。我也不知道是哪里的问题

**Comment by ZhuBa8** [comment]
> @ChuanfengZhang 更新之后就好了。我也不知道是哪里的问题

我也出现了这个问题，更新版本之后也没有解决。。

**Comment by MrBrilliant2046** [comment]
我在openclash也遇到了相似的问题
