### ISSUE TITLE
部分网站直连无法访问

### ISSUE THREAD

**Issue by nncy** [Fndroid/clash_for_windows_pkg#203]
从今天早晨开始，访问微软、苹果这两个走直连的网站时，无法访问，log会出现
Dial [DIRECT] failed 的反馈。让他们走代理是可以访问的。
![image](https://user-images.githubusercontent.com/19932520/65325730-392f3e00-dbe2-11e9-92bd-167a229b1269.png)

clash版本:0.7.8

**Comment by Fndroid** [comment]
@nncy 关掉Clash for Windows能访问吗

**Comment by nncy** [comment]
关掉后也不可以。是本机网络出问题了吗

**Comment by Fndroid** [comment]
那就是本地网络问题了
