### ISSUE TITLE
无法科学上网

### ISSUE THREAD

**Issue by HolaAmigoV5** [Fndroid/clash_for_windows_pkg#2031]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**
在 `https://biteb.me`上面注册了账号，充值了会员，按照教程配置。使用Clash for windows V 0.16.2客户端连接成功，但是无法使用谷歌搜索等其他相关网站。
 # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
# (平台及版本号)
Windows 10 企业版  20H2 19042.1083

**描述**

# (请具体并清楚地描述遇到的问题)
在 `https://biteb.me` 上面注册了账号，充值了会员，按照教程配置。使用Clash for windows V 0.16.2客户端连接成功，但是无法使用谷歌搜索等其他相关网站。
- 从日志上看，访问google时，出现timeout问题。
- 在家里和在公司不用网络环境下依然无法使用。
- 无论切换节点，还是设置Global等方式都无法使用。

**复现**
 # (请描述复现问题的步骤)
直接无法使用

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
能正常使用各种网站。

**日志**
# (上传触发问题对应的日志文件)
time="2021-07-11T23:30:22+08:00" level=info msg="RESTful API listening at: 127.0.0.1:54604"
time="2021-07-11T23:30:22+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2021-07-11T23:30:23+08:00" level=info msg="Start initial compatible provider ⚓️其他流量"
time="2021-07-11T23:30:23+08:00" level=info msg="Start initial compatible provider 🎬国外媒体"
time="2021-07-11T23:30:23+08:00" level=info msg="Start initial compatible provider 🚀直接连接"
time="2021-07-11T23:30:23+08:00" level=info msg="Start initial compatible provider 🔰国外流量"
time="2021-07-11T23:30:23+08:00" level=info msg="Start initial compatible provider 🎬哔哩哔哩"
time="2021-07-11T23:30:23+08:00" level=info msg="Start initial compatible provider ✈️Telegram"
time="2021-07-11T23:30:23+08:00" level=info msg="Start initial compatible provider 🍎苹果服务"
time="2021-07-11T23:30:23+08:00" level=info msg="Start initial compatible provider 🎬Youtube"
time="2021-07-11T23:30:23+08:00" level=info msg="Start initial compatible provider 🎬Netflix"
time="2021-07-11T23:32:12+08:00" level=info msg="[TCP] 127.0.0.1:64023 --> ssl.gstatic.com match DomainSuffix(gstatic.com) using 🔰国外流量[DIRECT]"
time="2021-07-11T23:32:16+08:00" level=warning msg="[TCP] dial 🔰国外流量 (match DomainKeyword/google) to www.google.com error: dial tcp4 172.217.24.4:443: i/o timeout"
time="2021-07-11T23:32:19+08:00" level=warning msg="[TCP] dial 🔰国外流量 (match DomainKeyword/google) to www.google.com error: dial tcp4 172.217.24.4:80: i/o timeout"
time="2021-07-11T23:32:21+08:00" level=warning msg="[TCP] dial 🔰国外流量 (match DomainKeyword/google) to www.google.com error: dial tcp4 172.217.24.4:443: i/o timeout"
time="2021-07-11T23:33:15+08:00" level=info msg="[TCP] 127.0.0.1:54582 --> safebrowsing.googleapis.com match DomainKeyword(google) using 🔰国外流量[DIRECT]"
time="2021-07-11T23:33:19+08:00" level=info msg="[TCP] 127.0.0.1:54585 --> www.bing.com match DomainSuffix(bing.com) using 🔰国外流量[DIRECT]"
time="2021-07-11T23:33:19+08:00" level=info msg="[TCP] 127.0.0.1:54587 --> cn.bing.com match DomainSuffix(bing.com) using 🔰国外流量[DIRECT]"

**截图**
# (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/16334099/125201263-e0da9c00-e2a0-11eb-8ea6-5a0b02fd6d0b.png)

![image](https://user-images.githubusercontent.com/16334099/125201808-3617ad00-e2a3-11eb-9747-05ec9e3987ed.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
没有bug没有功能建议就请不要发issue，我这里不是售后

**Comment by HolaAmigoV5** [comment]
那我这充值了的会员，用不了找谁啊？我找不到售后啊。

**Comment by yi-Xu-0100** [comment]
@HolaAmigoV5 哪里付款找哪里，而且你的国外流量选的是直连。

**Comment by HolaAmigoV5** [comment]
我要是能找到客服，我哪会费劲跑这里来说。这界面哪有反馈问题的地方？
<img width="496" alt="17" src="https://user-images.githubusercontent.com/16334099/125221575-fb416380-e2fa-11eb-84b6-89c642e4be00.png">

**Comment by Fndroid** [comment]
我这是免费软件，你买的什么东西，和我软件有关系吗？
