### ISSUE TITLE
win10浏览器页面访问出现“连接已重置”问题

### ISSUE THREAD

**Issue by peter123456789** [Fndroid/clash_for_windows_pkg#2032]
win10所有浏览器页面访问出现“连接已重置”问题，如图：
注意是clash使用的是 “脚本”模式
![clash_err](https://user-images.githubusercontent.com/12538824/125225822-7a866580-e302-11eb-870c-0e1d632f0bef.png)

另外：切换到全局模式此问题就不再出现。。求解答。。   
clash version:   Clash.for.Windows-0.16.2-win

**Comment by Fndroid** [comment]
脚本模式是什么

**Comment by peter123456789** [comment]
我知道了。我选错模式了
