### ISSUE TITLE
最新版本0.16.2出现无法连接订阅地址，主页Loading

### ISSUE THREAD

**Issue by Wisil** [Fndroid/clash_for_windows_pkg#2034]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # win10 20H2 19042.1083

**描述**

[//]: # 最新版本0.16.2会出现无法选择订阅地址的错误(即选择订阅时会出现网络错误弹窗），主页显示Loading，左下角显示Disconnected，该问题在卸载后重装依旧无法避免。

**复现**

[//]: # 

1. 全新安装后，打开软件开启系统代理并添加订阅地址；
2. 在Proxies板块选择可用节点并连接成功；
3. 在Proxies板块直接点击右上角关闭窗口并在系统右下角托盘区点击quit退出；
4. 再次打开软件，并重复以上步骤3达3次或以上，则会出现标题所描述的问题，即无法选择订阅，并伴随出现错误弹窗，此时主页出现Loading以及Proxies板块的节点也无法加载，左下角显示Disconnected。

**预期行为**

[//]: # 希望修复，不再出现此问题。

**日志**

[//]: # panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x58 pc=0x146ac4e]

goroutine 35 [running]:
github.com/Dreamacro/clash/tunnel.resolveMetadata.func1(0xc000315d98, 0x1762db0, 0x1bec828, 0xc000315d88, 0xc000315d78, 0xc0002ac000)
 github.com/Dreamacro/clash/tunnel/tunnel.go:190 +0x8e
github.com/Dreamacro/clash/tunnel.resolveMetadata(0x276e32f0088, 0xc0002980f0, 0xc0002ac000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
 github.com/Dreamacro/clash/tunnel/tunnel.go:209 +0x225
github.com/Dreamacro/clash/tunnel.handleTCPConn(0x1762e20, 0xc0002980f0)
 github.com/Dreamacro/clash/tunnel/tunnel.go:358 +0x1ca
created by github.com/Dreamacro/clash/tunnel.process
 github.com/Dreamacro/clash/tunnel/tunnel.go:135 +0xc5

**截图**

[//]: # 
![image](https://user-images.githubusercontent.com/78348427/125242630-8c2a3600-e31f-11eb-91a2-e27eb1e5f0bd.png)
![image](https://user-images.githubusercontent.com/78348427/125242661-951b0780-e31f-11eb-9c7b-ac274e111a1e.png)
![image](https://user-images.githubusercontent.com/78348427/125242689-9c421580-e31f-11eb-9be6-36d02cb985f5.png)

**其他说明**

[//]: # 暂无。

**Comment by Wisil** [comment]
@Fndroid

**Comment by Fndroid** [comment]
Duplicate of #2026
