### ISSUE TITLE
最新版 Chrome 使用 clash 做代理造成网络环路问题

### ISSUE THREAD

**Issue by ForestL18** [Fndroid/clash_for_windows_pkg#2038]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
win10 2009
[//]: # (平台及版本号)
Windows10 20H2
**描述**

[//]: # (请具体并清楚地描述遇到的问题)
Chrome 91.0.4472.124 for Windows 在开启 clash for Windows0.16.0 做代理时，会在打开网页视频（如 B 站，油管等）时产生严重的网络环路。clash 内核进程（ clash-win64.exe)会同时跑上传下载，上传下载都为一百多兆；在路由器端查看，发现电脑只与路由上的 LAN 口发生数据交换（是的，LAN 口同时在跑上传下载流量)，WAN 口没有流量。

在我回退 Chrome 上一版本后，再次开启 clash 代理打开视频网页不会出现上述情况。目前推测是最新版 Chrome 问题。

路由器是 ubnt erx，固件 1.10.11 ，只做了拨号，只划分了一个子网，其他没有动。

希望有大佬可以解答一下，谢谢!
**复现**

[//]: # (请描述复现问题的步骤)
与上述描述相同

**预期行为**

[//]: # (清晰地描述期望看到的行为)
clash内核不无故同时跑大流量的上传下载
**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by ForestL18** [comment]
@Fndroid

**Comment by akw5454521** [comment]
日志发来看看

**Comment by ForestL18** [comment]
该问题通过升级路由器固件解决，神奇的bug
