### ISSUE TITLE
关于Clash Windows的一些思考，以及一些建议

### ISSUE THREAD

**Issue by ted423** [Fndroid/clash_for_windows_pkg#204]
首先我之所以写这些是因为我在入这个的门的时候遇到了很大的困难，让我感觉难以理解软件的运行逻辑。
这些是在我还未完全弄明白的情况写的，之前只用过SS以及PAC，如有一些差错，还请谅解。

我主要看到的文档有https://github.com/Dreamacro/clash/blob/master/README.md
以及https://docs.cfw.lbyczf.com/chang-gui-general
我不太清楚后者是不是官方文档哈。
还有这个应该是非官方文档
<https://withdewhua.space/2018/10/27/how-to-use-clash-for-windows/>

首先是pofile,首页有 Text Mode Edit ，然后还有一个专门的Profile,这两者的关系以及生效范围一开始就让我非常迷惑。

按我现在的理解，Text Mode Edit 只涉及 "Proxy:" 以前的配置生效，而Profile里则生效 "Proxy:" 以后的那一段。两者的初始配置看起来则完全一样。
但这些文档里我没看到具体的介绍以及解释，所以是否能加进文档里？因为我认为这一块非常具有迷惑性。

题外话，tap device似乎可以无限点击install，这个我还没试具体怎么生效。

Proxies 这一块就比较戏剧了
我点着Global然后去设置Rule,Global选了Proxy Group，然后在Rule里选Proxy Group具体的代理。然后看Rule生不生效。然后有时候全局代理，有时候走rule弄得我一头雾水。

最后又看着Global里的Direct和Direct陷入疑惑

我的理解是标签选Global就全局，Rule就走Rule,Direct就全局直通？

建议把Proxy Group的选择单独弄一块出来，因为我感觉全局走代理组和全局选个代理应该没太大差别？Direct似乎可以拿掉？

我的理解Clash没法按应用走规则，不知道我的理解是否有误？
以下的提议是根据上面的疑问，如果我的理解有误可以跳过。
首先部分应用会使用多个端口，所以SRC-PORT似乎不太好用。
最后就是希望能增加个全局代理的端口设置，走这个可以让整个应用全走代理从而绕过clash的规则，因为像Dropbox和telegram这些应用是需要全局走代理的，相比dropbox还好，telegram的连接是IP，规则写起来比较麻烦，而且我觉得应用直接全局会省些CPU？另一方面，我有时候验证网站是被墙了还是挂了还是连代理无法访问会切全局代理或直连，但如果直接在Clash里切势必会影响到别的应用。
这个是否需要在clash那里去提？

**Comment by Fndroid** [comment]
> 首先是pofile,首页有 Text Mode Edit ，然后还有一个专门的Profile,这两者的关系以及生效范围一开始就让我非常迷惑。

这部分我们正在更新文档内容，会详细解析一些类似的细节

> 题外话，tap device似乎可以无限点击install，这个我还没试具体怎么生效。

这个地方本意也只是进行安装的，其他连接问题要自己在网络链接里确认

> Proxies 这一块就比较戏剧了
我点着Global然后去设置Rule,Global选了Proxy Group，然后在Rule里选Proxy Group具体的代理。然后看Rule生不生效。然后有时候全局代理，有时候走rule弄得我一头雾水。

并没看懂

> 我的理解Clash没法按应用走规则，不知道我的理解是否有误？

Clash的本意就是按照规则分发请求，不会如何编写规则可以使用一些现成的

**Comment by ted423** [comment]
> > 首先是pofile,首页有 Text Mode Edit ，然后还有一个专门的Profile,这两者的关系以及生效范围一开始就让我非常迷惑。
> 
> 这部分我们正在更新文档内容，会详细解析一些类似的细节
> 
> > 题外话，tap device似乎可以无限点击install，这个我还没试具体怎么生效。
> 
> 这个地方本意也只是进行安装的，其他连接问题要自己在网络链接里确认
> 
> > Proxies 这一块就比较戏剧了
> > 我点着Global然后去设置Rule,Global选了Proxy Group，然后在Rule里选Proxy Group具体的代理。然后看Rule生不生效。然后有时候全局代理，有时候走rule弄得我一头雾水。
> 
> 并没看懂
> 


按我的理解，rule 就是按rule 走规则，但是proxy group里的具体的proxy的选择只能在rule这个标签里操作，但这个标签里的变动同时会影响global里选到proxy group组的选项，这样，新接触者会无法理解Rule的具体作用。
一开始我以为Global里选规则组是走rule。

> > 我的理解Clash没法按应用走规则，不知道我的理解是否有误？
> 
> Clash的本意就是按照规则分发请求，不会如何编写规则可以使用一些现成的

主要是现成的规则似乎没法满足我的需求。不知道规则这些有没有比较详细文档，或者能否让单个应用全局走代理的办法？SRC-PORT似乎可以，但我感觉部分应用是使用随机端口的。
当然这个并不急切，也不是必须的。

**Comment by ted423** [comment]
Sorry,关于Proxies这块，我再整理下语言

**Comment by ted423** [comment]
关于Proxies这块，我的提议主要为了降低用户的上手难度。基于KISS原则（比如我，现成的例子...）

首先，大部分用户初次会以为Global、RULE以及Direct 只是个选项卡，不知道在Proxies里点选项卡会更改模式。并且profile里有个mode: Rule（我就以为会以这个配置里的mode 为主）

所以在选项卡这块，选择后前面打个勾或者在哪里有个提示当前模式的显示就好了。

然后就是proxy group了，一开始我没注意有type: url-test这个用法，所以我之前关于Global里说的proxy group的就有问题，请无视。

但是既然proxy  group 在Global也有作用，那么proxy  group 的设置 放在rule标签里就不是很合适，我觉得可以单独给个地方.或者界面上global、RULE以及Direct不在起到选项卡的作用，单纯更改模式，Proxies下集成所有设置，然后标识哪些设置是属于GLobal的,哪块设置更改proxy  group。

我仍然觉得 Globle下的 direct跟direct这个选项功能重复了。

**Comment by Fndroid** [comment]
1. profile里只会认dns/Proxy/Proxy Group/Rule，其他都只会认config.yml，包括mode

2. Global和Direct都是特殊策略组，Global为所有节点和策略组的集合

**Comment by ted423** [comment]
> 1. profile里只会认dns/Proxy/Proxy Group/Rule，其他都只会认config.yml，包括mode
> 2. Global和Direct都是特殊策略组，Global为所有节点和策略组的集合

了解，我再去理解一下

**Comment by cooper1x** [comment]
这个我也感觉好复杂，比起v2rayN来说，这个rule模式，其实我的理解就是PAC模式，国内直连，国外代理。现在这个搞几十个，不知道怎么连接哪一个，也不知道点击高亮了是连上了还是没有连上，一脸懵逼。

**Comment by ted423** [comment]
> 这个我也感觉好复杂，比起v2rayN来说，这个rule模式，其实我的理解就是PAC模式，国内直连，国外代理。现在这个搞几十个，不知道怎么连接哪一个，也不知道点击高亮了是连上了还是没有连上，一脸懵逼。

我也是折腾半天才搞懂，总之点到rule就是rule模式，然后里面可以在代理组里选择服务器，这样指定的网页组可以更换服务器

**Comment by LauJon** [comment]
有没有例如一键设置“绕过局域网和某国Ip” ，rule里面好复杂。不知道怎么设置。

**Comment by ted423** [comment]
> 有没有例如一键设置“绕过局域网和某国Ip” ，rule里面好复杂。不知道怎么设置。

这个就要你看懂怎么写配置了，bypass 那里跳局域网，某国ip是geoip这么写

**Comment by dspjm** [comment]
@ted423 我觉得挺好理解的啊，Global就是所有请求走代理，rule就是根据rule，direct就是所有direct。proxy group更多是写规则的时候用吧，否则只放到一个组也是可以的。不知道我理解的对不对。不过对我而言我还是觉得ss更好用一些。

**Comment by ted423** [comment]
> @ted423 我觉得挺好理解的啊，Global就是所有请求走代理，rule就是根据rule，direct就是所有direct。proxy group更多是写规则的时候用吧，否则只放到一个组也是可以的。不知道我理解的对不对。不过对我而言我还是觉得ss更好用一些。

初次使用者是根据UI设计来理解软件逻辑。我最开始是因为不太理解Proxy Group的作用(最主要当时没看到log,又是自己上手直接去写规则，也没个可参照物)
就好比没人给你解释Proxy Group是什么，然后你要通过软件的各种反应来试出来Proxy Group具体起个什么作用,作为什么角色，当然也包括其他一些东西。（一方面我语文没学好，所以理解和表达可能不太好）

rule就是你可以通过各种匹配或者规则指定走代理或者代理组，代理组还可以切换具体代理。

而我说的最迷惑的就是我最早单单以为 Global 这些是作为一个选项卡存在的，我并不知道点了就有功能上的改变。因为这个软件界面上没有太直观的改变或者提示。所以我没搞清楚->"卧槽，这玩意怎么就一直走代理，怎么改配置都没用。" 或者->"这东西怎么又怎么都不走代理了。"
而ss，你改下代理模式的显示还是蛮直观的。
所以我说的属于交互设计上的一些想法

总之我的这个issue属于初学者踩坑记录

**Comment by ted423** [comment]
> @ted423 我觉得挺好理解的啊，Global就是所有请求走代理，rule就是根据rule，direct就是所有direct。proxy group更多是写规则的时候用吧，否则只放到一个组也是可以的。不知道我理解的对不对。不过对我而言我还是觉得ss更好用一些。

初次使用者是根据UI设计来理解软件逻辑。我最开始是因为不太理解Proxy Group的作用(最主要当时没看到log,又是自己上手直接去写规则，也没个可参照物)
就好比没人给你解释Proxy Group是什么，然后你要通过软件的各种反应来试出来Proxy Group具体起个什么作用,作为什么角色，当然也包括其他一些东西。（一方面我语文没学好，所以理解和表达可能不太好）

rule就是你可以通过各种匹配或者规则指定走代理或者代理组，代理组还可以切换具体代理。

而我说的最迷惑的就是我最早单单以为 Global 这些是作为一个选项卡存在的，我并不知道点了就有功能上的改变。因为这个软件界面上没有太直观的改变或者提示。所以我没搞清楚->"卧槽，这玩意怎么就一直走代理，怎么改配置都没用。" 或者->"这东西怎么又怎么都不走代理了。"
而ss，你改下代理模式的显示还是蛮直观的。
所以我说的属于交互设计上的一些想法

总之我的这个issue属于初学者踩坑记录

**Comment by bluerthanever** [comment]
说真的，我也觉得global就是直接转到clash的流量就按照选择的服务器走就行了，不太理解你们设置那么多组和集合什么的想法。总得让用户自己可以选择我要不要所有流量都走代理吧。强行给加一道，真心烦躁。

**Comment by ted423** [comment]
> 说真的，我也觉得global就是直接转到clash的流量就按照选择的服务器走就行了，不太理解你们设置那么多组和集合什么的想法。总得让用户自己可以选择我要不要所有流量都走代理吧。强行给加一道，真心烦躁。

这个设计应该是方便代理组切换代理，这样可以部分网址切换代理规则。global就是按全局走的。

**Comment by CuiTN** [comment]
同意这个issue的proxy那一部分。
我是个刚下载使用不到一小时的新手
不理解 的地方在于，设置了global，rule以及direct这三个模式之后，如何激活它们。
查看了这个页面后才明白，点击每个选项之后，就自动激活了该模式。
的确应该有个明确的标识。

**Comment by 1353604736** [comment]
有没有和ssr或v2一样的一键PAC绕过大陆什么的，Rule里面太复杂，弄不懂，不懂英文的还是大多数

**Comment by 00LT00** [comment]
原来点了就会切换，我还专门查了clash怎么走pac的方法，结果才发现原来是通过选项卡切换的

**Comment by iam7cn** [comment]
cfw-bypass:  和  DIRECT 有什么区别？？？ @Fndroid

**Comment by salzburgrujvnun** [comment]
有缓冲，要测试是否走代理，建议使用隐身模式打开新链接。隐身模式中重复切换代理模式，还是会受缓冲影响，必须每切换一次，就重新打开一个隐身窗口。

**Comment by ted423** [comment]
> 我真的很困惑这个软件的UI的逻辑, 每次用都很痛苦. 非常痛苦. 极为痛苦

用一段时间就好了。
