### ISSUE TITLE
打开开始菜单状态下，右键任务栏中的小图标没有反应

### ISSUE THREAD

**Issue by chenfangshuo** [Fndroid/clash_for_windows_pkg#2041]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 10 专业版 64-bit (10.0, Build 19043) (19041.vb_release.191206-1406)
**描述**

[//]: # (请具体并清楚地描述遇到的问题)
打开开始菜单状态下，右键任务栏中的小图标没有反应(软件不会弹出右键菜单)，之后点一下屏幕上除任务栏的其他任何区域才能打开右键菜单
**复现**

[//]: # (请描述复现问题的步骤)

1. 打开'开始菜单'
2. 右击任务栏右侧软件的小图标
3. 触发问题: 没有反应(其他软件会弹出右键菜单)

**预期行为**

[//]: # (清晰地描述期望看到的行为)
在开始菜单打开的状态下，可以像其他软件一样右键打开菜单
**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by 4512369781** [comment]
这个是Win10的问题，按esc 关掉开始菜单就行了。
