### ISSUE TITLE
Bypass domain/IPNet 不能设置为 *.domain.com

### ISSUE THREAD

**Issue by yixinin** [Fndroid/clash_for_windows_pkg#2042]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. settings
2. Bypass domain/IPNet
3. 添加*.domain.com
4. 无法保存

**预期行为**

能够设置*.domain.com

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

![image](https://user-images.githubusercontent.com/17738162/125754184-71b03828-abae-495b-b55a-3dd40d94050f.png)

**其他说明**

经测试，win10可以支持 *.domain.com过滤
![image](https://user-images.githubusercontent.com/17738162/125754527-970e1883-7af7-42c3-9acf-ef495a5af5d8.png)

**Comment by yi-Xu-0100** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/1360#issuecomment-732524206
