### ISSUE TITLE
Enhanced Tray流量速度显示为什么会在访问国内站点时有速度显示？

### ISSUE THREAD

**Issue by Liquidlkw** [Fndroid/clash_for_windows_pkg#2044]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x]已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x]已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x]已经尝试更新到最新版本，问题依旧存在
- [x]软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Windows 10 家庭中文版
20H2
[//]: # (平台及版本号)

**描述**
在访问国内网址时,代理模式已设置为Rule，Enhanced Tray任然会有流量速度显示
问题1.此处表现为正常现象吗？
问题2.此处流量速度难道不是指通过代理的流量速度吗？为什么国内网址任然会有流量速度显示？
[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

开启Enhanced Tray 代理模式设置为RULE
访问baidu.com 

**预期行为**

[//]: # (清晰地描述期望看到的行为)
访问明确在Rule规则中使用Domestric的网址 应该在Enhanced Tray 中看不见流量速度
**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/48376042/125790135-1f14bbd3-cf33-4a9b-8118-19b017d803fe.png)

**其他说明**
如果这是正常表现 可以添加这个功能吗？
[//]: # (其他补充内容)

**Comment by Liquidlkw** [comment]
@Fndroid

**Comment by yi-Xu-0100** [comment]
你指的流量波动是多少？几kb/s还是几百kb/s还是几Mb/s

**Comment by Fndroid** [comment]
预期行为，那是指经过clash的流量

**Comment by Liquidlkw** [comment]
> 预期行为，那是指经过clash的流量
经过clash 的流量 而不是经过代理的流量是这个理解吗?
容易让人误解,不考虑,仅检测经过代理的流量吗

**Comment by Liquidlkw** [comment]
> 你指的流量波动是多少？几kb/s还是几百kb/s还是几Mb/s

几kb/s 我想知道这部分流量是否也是进过代理 这个功能若是检测进过clash的流量速度是否有些鸡肋呢 是否考虑添加仅检测经过代理的流量了 @yi-Xu-0100 @Fndroid
