### ISSUE TITLE
请问作者考虑增加“外部代理订阅链接”这一功能吗？

### ISSUE THREAD

**Issue by dsafkj** [Fndroid/clash_for_windows_pkg#2048]
**描述**
在自己编辑（非托管）的配置文件中可放入代理服务器的订阅链接

**其他说明**
机场用户，但是用不惯机场配给的分流规则，希望作者添加仅订阅代理的功能

**Comment by UntaggedRui** [comment]
可以使用proxy-providers解决你的问题。

**Comment by dsafkj** [comment]
> 可以使用proxy-providers解决你的问题。

谢谢
