### ISSUE TITLE
Could you please implement a new release with the latest dev Clash core？

### ISSUE THREAD

**Issue by Dukewill** [Fndroid/clash_for_windows_pkg#205]
The latest Clash (dev version) now supports mux disabling dealing with v2ray-plugin. This function is quite significant for multi platforms.

Could you please also implement this in CFW? Thanks a lot!

FYR: https://github.com/Dreamacro/clash/commit/1a8a6d0b5d28161069c23560464be9f1e0eb6fd7

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.7.9
