### ISSUE TITLE
mac版本在启动或者切换配置文件时出现too many open files

### ISSUE THREAD

**Issue by UntaggedRui** [Fndroid/clash_for_windows_pkg#2054]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ x] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
big sur  11.4 (20F71)， cfw v0.16.3
**描述**

[//]: # (请具体并清楚地描述遇到的问题)
1. 启动时出现
![clash错误](https://user-images.githubusercontent.com/28807947/126061812-24b44c78-0cd4-43c8-9947-925827d94811.png)

2. 切换配置文件时出现
<img width="855" alt="clash出错了" src="https://user-images.githubusercontent.com/28807947/126061814-1d2355df-8f15-4fe3-b676-007ab19808b9.png">

已经修改了系统配置，增加了文件句柄的大小。
![系统配置](https://user-images.githubusercontent.com/28807947/126061862-03440fd5-e060-4fe8-8ada-cd82e438a023.png)
实际上使用的文件句柄数量并不多
![文件句柄数量](https://user-images.githubusercontent.com/28807947/126061909-b726ce9e-26f2-4e22-a1a8-8943eeed750e.png)

虽然有相关话题https://github.com/Fndroid/clash_for_windows_pkg/issues/1658, 但是似乎并不能解决我的问题。
**复现**

[//]: # (请描述复现问题的步骤)
切换配置文件或者重新启动时都会遇到类似的情况发生。

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
如果是开了service mode的话试试加大launchctl的maxfile对应的值

**Comment by UntaggedRui** [comment]
> 如果是开了service mode的话试试加大launchctl的maxfile对应的值

没有打开service mode。launchctl的maxfile对应的值已经是65536了，应该已经足够大了吧。
不知道有没有其他的macos用户有类似的情况，我这几天一直频繁遇到。
而且我感觉应该不是真的没有文件句柄了，具体的错误原因还不知道。

**Comment by wangzexi** [comment]
同样，只要多点几次有`provider`的`profile`文件就能触发这个错误，`win`和`mac`平台都是。

**Comment by UntaggedRui** [comment]
每次启动软件几乎都会出现这个错误，有点难受。

**Comment by ekilzen** [comment]
> 同样，只要多点几次有`provider`的`profile`文件就能触发这个错误，`win`和`mac`平台都是。
> 
> 为了正常使用有`provider`的`profile`文件，先切换至无`provider`的`profile`文件，再切换回来，有时候就好了。

我也碰到同样的情况。

**Comment by Fndroid** [comment]
如果开了service mode，更新到0.16.4之后重新安装一service mode应该会解决

**Comment by UntaggedRui** [comment]
> 如果开了service mode，更新到0.16.4之后重新安装一service mode应该会解决

感谢，正在下载安装尝试。

**Comment by UntaggedRui** [comment]
mac0.16.4 在软件启动和重启时不再会出现这个错误了。但是在配置文件界面切换到有proxy-provider的配置文件时还是会出现这个问题。
![image](https://user-images.githubusercontent.com/28807947/126795617-08d57f62-7ee3-4bf5-91ba-8254cd287543.png)

**Comment by Fndroid** [comment]
@UntaggedRui 你试试打开service mode吧

**Comment by UntaggedRui** [comment]
> @UntaggedRui 你试试打开service mode吧，macOS默认launchctl的maxfiles只有256，provider节点稍微多一点切换就会触发health check占满

感谢及时的回复！我已经把launchctl改大了。现在重启了可以用了，我再使用看一下。
![图片](https://user-images.githubusercontent.com/28807947/126061862-03440fd5-e060-4fe8-8ada-cd82e438a023.png)
感谢耐心回复。

**Comment by UntaggedRui** [comment]
经过几天的使用，已经没有这个问题了。
感谢修复！
