### ISSUE TITLE
可以支持语言切换吗，英文不好的孩子用起来有些头疼

### ISSUE THREAD

**Issue by sky-wdl** [Fndroid/clash_for_windows_pkg#2058]
**描述**
希望可以增加支持简体中文，可以在settings里边设置切换语言为中文，这样真是太棒了！

**其他说明**
其他补充内容

**Comment by sky-wdl** [comment]
我找到汉化包了hhh

**Comment by leezn** [comment]
关了干嘛，建议支持多语言没毛病，不然每次更新还需要再更新汉化包

**Comment by sky-wdl** [comment]
> 关了干嘛，建议支持多语言没毛病，不然每次更新还需要再更新汉化包

说得也是，不知道可不可以直接内置，然后手动切换，懒得再提issues了..

**Comment by lostwindsenril** [comment]
我猜测不会支持，是为提高使用门槛，避免在墙内大范围流行。

**Comment by VillainTom** [comment]
> 我找到汉化包了hhh

能发一下吗朋友 我qq3209047204 看到回复一下

**Comment by jtyoui** [comment]
能发一个链接吗？我亲爱的小伙伴

**Comment by sky-wdl** [comment]
> 能发一个链接吗？我亲爱的小伙伴

稍等哦

**Comment by sky-wdl** [comment]
> 能发一个链接吗？我亲爱的小伙伴

https://github.com/ender-zhao/Clash-for-Windows_Chinese

**Comment by sky-wdl** [comment]
大家可以戳链接，使用汉化版本的https://github.com/ender-zhao/Clash-for-Windows_Chinese
