### ISSUE TITLE
希望开启系统代理时可以选择写成类似http=http://x.x.x.x:y;https=http://x.x.x.x:y; ······· 的形式

### ISSUE THREAD

**Issue by railzy** [Fndroid/clash_for_windows_pkg#2059]
**描述**
python的requests包和urllib3包在某次更新后，开始优先使用https代理，pip也受到了这个的影响。
当系统设置了写成 `127.0.0.1:xxxx` 的代理时，会优先补完成 `https://127.0.0.1:xxxx` 的形式并尝试连接。
然而clash本地只提供了http和socks代理，无法处理https代理请求，导致requests报错
如图所示
![image](https://user-images.githubusercontent.com/57893649/126343708-22b33d6c-97ba-4830-a265-2ee76d26ca64.png)

而如果手动将系统代理写成这样的形式 `http=http://127.0.0.1:xxxx;https=http://127.0.0.1:xxxx` ，即手动指定https代理走http，则requests不会遇到代理问题
![image](https://user-images.githubusercontent.com/57893649/126342174-fa15c4d9-9eb1-4c4d-b9fd-0d3afb0a65c5.png)

又或者手动设置环境变量，也可以正常运行（在虚拟环境中无效），但这明显不方便日常使用
```
set HTTP_PROXY=http://127.0.0.1:xxxx
set HTTPS_PROXY=http://127.0.0.1:xxxx
```
![image](https://user-images.githubusercontent.com/57893649/126343399-f3a987a9-eb1d-442b-9e78-f92e6c8bda4d.png)

如果cfw开启系统代理时可以选择写成类似 `http=http://x.x.x.x:y;https=http://x.x.x.x:y; ······` 的形式，这样就方便多了

**Comment by yi-Xu-0100** [comment]
setting 开 special protocol 。

**Comment by railzy** [comment]
> setting 开 special protocol 。

打开后确实不用特别设置就可以正常使用了，谢谢
我好像没有找到specify protocol的相关说明，请问能稍微讲讲这是个什么东西吗

**Comment by yi-Xu-0100** [comment]
@railzy #1787
