### ISSUE TITLE
「反馈建议」希望右键托盘增加，全局/代理/直连的托盘按钮

### ISSUE THREAD

**Issue by gongyoyo** [Fndroid/clash_for_windows_pkg#206]
感谢作者的辛苦维护与开发！
这样切换就比较方便了，最好还有个系统代理开关的托盘右键菜单

**Comment by Fndroid** [comment]
这几个操作我个人认为都不是高频操作，而且右键点击选择和左键打开GUI界面再选择效率也差不多

**Comment by Pnutile** [comment]
> 这几个操作我个人认为都不是高频操作，而且右键点击选择和左键打开GUI界面再选择效率也差不多

部分人还是经常用的，比如我设置的"MATCH, Direct"，以免浪费不必要的流量，所以有时连不上的网站就临时切换到Global。。
不过你说有计划增加快捷键了，我觉得有了快捷键就不需要lz要的这个功能了。
谢谢你开发的软件在这几天让我还能呼吸自由空气！

**Comment by gongyoyo** [comment]
> 这几个操作我个人认为都不是高频操作，而且右键点击选择和左键打开GUI界面再选择效率也差不多

用SSR用惯了，每次想切换模式就下意识的右键托盘，而且最好在global，proxy，direct不同模式时，托盘图标可以变色，方便区分当前状态，而且可以让大部分SSR用户快速过渡。还有我昨天还发了有关流量统计的问题，还有仅显示代理的上下行网速建议，（因为有时候看个国内视频，显示10M/s我还以为我流量刷刷就没了），和节点延迟波动统计图好像消失了，这里一并给作者大大提意见吧，感谢作者大大的开发与维护，让我们 可以用上这么好的新一代工具，更方便的呼吸新鲜空气，谢谢😘

**Comment by Fndroid** [comment]
> 可以让大部分SSR用户快速过渡

Clash不能用SSR，其次，不是很明白为什么要让SSR用户快速过渡

**Comment by Fndroid** [comment]
> > 这几个操作我个人认为都不是高频操作，而且右键点击选择和左键打开GUI界面再选择效率也差不多
> 
> 部分人还是经常用的，比如我设置的"MATCH, Direct"，以免浪费不必要的流量，所以有时连不上的网站就临时切换到Global。。
> 不过你说有计划增加快捷键了，我觉得有了快捷键就不需要lz要的这个功能了。
> 谢谢你开发的软件在这几天让我还能呼吸自由空气！

如果不需要使用规则，那为什么不用Shadowsocks-windows呢

**Comment by gongyoyo** [comment]
> > > 这几个操作我个人认为都不是高频操作，而且右键点击选择和左键打开GUI界面再选择效率也差不多
> > 
> > 
> > 部分人还是经常用的，比如我设置的"MATCH, Direct"，以免浪费不必要的流量，所以有时连不上的网站就临时切换到Global。。
> > 不过你说有计划增加快捷键了，我觉得有了快捷键就不需要lz要的这个功能了。
> > 谢谢你开发的软件在这几天让我还能呼吸自由空气！
> 
> 如果不需要使用规则，那为什么不用Shadowsocks-windows呢

因为SSR没有Clash好用

**Comment by Pnutile** [comment]
> > > 这几个操作我个人认为都不是高频操作，而且右键点击选择和左键打开GUI界面再选择效率也差不多
> > 
> > 
> > 部分人还是经常用的，比如我设置的"MATCH, Direct"，以免浪费不必要的流量，所以有时连不上的网站就临时切换到Global。。
> > 不过你说有计划增加快捷键了，我觉得有了快捷键就不需要lz要的这个功能了。
> > 谢谢你开发的软件在这几天让我还能呼吸自由空气！
> 
> 如果不需要使用规则，那为什么不用Shadowsocks-windows呢

我个人的话，
1 国庆这波主要针对SS啊！我买的SS全挂了，临时买了V2ray的
2 发现Clash各方面都很好用，比如能查看日志，一键查看所有节点的latency等等
3 现在发现MATCH, Direct状态下有些网站的加载会有小问题（比如打开wikipedia时因为涉及wikimedia.org而后者没有写入规则所以就打不开），打算改回MATCH, V2ray然后手动添加一些不需要走代理的网站了。

**Comment by Comah** [comment]
其实如果ssr客户端好用或者更新的话 用谷歌的proxy插件一样能够达到策略分流的功能 主要是sr断更太久 还是用s或者clash好点

**Comment by Hongshiqiang** [comment]
想请问下怎么开启全局代理和分局代理

**Comment by gongyoyo** [comment]
2020年-04-10,  clash for  windows v0.9.5已增加此项Issues建议功能
![image](https://user-images.githubusercontent.com/36725275/82137622-62c16780-984c-11ea-8686-f25d78e8b799.png)
![image](https://user-images.githubusercontent.com/36725275/82137623-6523c180-984c-11ea-8d76-54039126b175.png)
