### ISSUE TITLE
tap模式不支持 process name ，tun支持 

### ISSUE THREAD

**Issue by debao1996lu** [Fndroid/clash_for_windows_pkg#2062]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ x] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

windows 10 

**描述**

tun支持process name 规则 tap 不支持

**复现**

自定义规则在tun模式下支持process name 规则 ，tap不支持

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

time="2021-07-22T23:57:18+08:00" level=debug msg="[Rule] find process name Process error: process not found"
time="2021-07-23T00:02:49+08:00" level=info msg="[TCP] 198.18.0.1:61308 --> 183.236.55.229 match Process(wv2ray.exe) using DIRECT"

**截图**

**其他说明**

[//]: # (其他补充内容)

**Comment by AkariiinMKII** [comment]
预期行为 tap mode 本身不支持process-name
