### ISSUE TITLE
DNS的enable属性报错

### ISSUE THREAD

**Issue by NalCol** [Fndroid/clash_for_windows_pkg#2064]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 11 Pro 22000.100
Clash for Windows 0.16.1 和 0.16.4
Clash Core 2021.05.08和2021.07.03
**描述**

[//]: # (请具体并清楚地描述遇到的问题)
有时dns属性无法识别
有时却不报错
**复现**
[//]: # (请描述复现问题的步骤)

1. 写出
```
dns:
   enable: true
```
2.导入CFW

**预期行为**
正确识别
[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/58576200/126852722-dfca3c41-2960-4c07-a5d5-f9aa5d84738b.png)
[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
mixin ? 给出去敏配置

**Comment by NalCol** [comment]
> mixin ? 给出去敏配置

直接在配置文件加会报错

**Comment by AkariiinMKII** [comment]
抄作业的时候请务必把缩进也抄了

**Comment by NalCol** [comment]
> 抄作业的时候请务必把缩进也抄了

怎么个抄法，我上面有代码段，缩进没有问题的吧
![image](https://user-images.githubusercontent.com/58576200/126854147-993eed82-f4b5-4ac1-815a-e9969c80b598.png)

**Comment by AkariiinMKII** [comment]
> > 抄作业的时候请务必把缩进也抄了
> 
> 怎么个抄法，我上面有代码段，缩进没有问题的吧
> ![image](https://user-images.githubusercontent.com/58576200/126854147-993eed82-f4b5-4ac1-815a-e9969c80b598.png)

问题大了去了
![image](https://user-images.githubusercontent.com/6019344/126854666-5a347f36-4d4c-4017-9589-ed3b6e733cbb.png)

**Comment by NalCol** [comment]
tun: 也需要缩进？谢谢提醒。
不过
```
dns: enable: true
```
确实是一个bug
我在没有动源文件（本地和URL都有测）的情况下这个错误自己消失了

**Comment by AkariiinMKII** [comment]
> > > > 抄作业的时候请务必把缩进也抄了
> > > 
> > > 
> > > 怎么个抄法，我上面有代码段，缩进没有问题的吧
> > 
> > 
> > 问题大了去了
> 
> tun: 也需要缩进？谢谢提醒。
> 不过
> 
> ```
> dns: enable: true
> ```
> 
> 确实是一个bug
> 我在没有动源文件（本地和URL都有测）的情况下这个错误自己消失了

你再仔细看看？

**Comment by NalCol** [comment]
> > > > > 抄作业的时候请务必把缩进也抄了
> > > > 
> > > > 
> > > > 怎么个抄法，我上面有代码段，缩进没有问题的吧
> > > 
> > > 
> > > 问题大了去了
> > 
> > 
> > tun: 也需要缩进？谢谢提醒。
> > 不过
> > ```
> > dns: enable: true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 确实是一个bug
> > 我在没有动源文件（本地和URL都有测）的情况下这个错误自己消失了
> 
> 你再仔细看看？

缩进多了一行？我直接从CFW Docs里复制的，我再改改看看能不能生效

**Comment by NalCol** [comment]
> > > > > 抄作业的时候请务必把缩进也抄了
> > > > 
> > > > 
> > > > 怎么个抄法，我上面有代码段，缩进没有问题的吧
> > > 
> > > 
> > > 问题大了去了
> > 
> > 
> > tun: 也需要缩进？谢谢提醒。
> > 不过
> > ```
> > dns: enable: true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 确实是一个bug
> > 我在没有动源文件（本地和URL都有测）的情况下这个错误自己消失了
> 
> 你再仔细看看？
![image](https://user-images.githubusercontent.com/58576200/126854833-d0f490e3-fac0-4719-92e5-c0f023b2a7e5.png)
把缩进规范了一下，确实生效了
感谢
