### ISSUE TITLE
Linux支持

### ISSUE THREAD

**Issue by AI1379** [Fndroid/clash_for_windows_pkg#2065]
**描述**
众所周知Linux上似乎并没有什么好用的clash客户端 虽然可以直接编写配置文件但是总没有gui来得方便 所以可否请开发者提供对于Linux的支持？

**其他说明**
cfw看起来是用electron做的gui然后配上了一些已经编译好的第三方库 这些库看起来似乎都有原生对linux的支持 所以移植的过程（至少从表面上来看）应该不会特别复杂👀

**Comment by yi-Xu-0100** [comment]
Duplicate of #1981
