### ISSUE TITLE
「功能建议」网速上下行能否仅显示代理的流量

### ISSUE THREAD

**Issue by gongyoyo** [Fndroid/clash_for_windows_pkg#207]
未走代理的上下行就要不要显示了
还有希望增加个网络上下行收发总流量的统计
最好再弄个折线图来表示网络波动情况

**Comment by Fndroid** [comment]
Clash Core的API只会给出上下行，没有其他数据 https://clash.gitbook.io/doc/restful-api/common

Clash Repo: https://github.com/Dreamacro/clash
