### ISSUE TITLE
咨詢各位彥祖們一個問題

### ISSUE THREAD

**Issue by da-gongren** [Fndroid/clash_for_windows_pkg#2070]
clash 的 dns 解析是怎樣的過程呀？在 [v2](https://v2ex.com/t/788130?p=1) 上看到個帖子，說軟件會自動對被汙染的域名做分流解析？

分流是規則那邊吧？不都是域名麽？

**Comment by yi-Xu-0100** [comment]
@da-gongren 个人理解如下：

1. 规则从上到下匹配。
2. 先本地匹配规则，规则也有 ip 匹配。
3. 规则中直连则直连，走代理则发送到代理端解析。
4. 污染域名可能按域名规则匹配走代理，也可能解析为国外 ip 走规则后去代理。

**Comment by AkariiinMKII** [comment]
反过来了 预解析主要是因为有不走 proxy 的需求 无论是 system proxy 层面还是 clash rule 层面的 一些 IP-based rule 反而是后话了
对应这些需求的规则导致如果被污染会因地址误判送进 direct
当然了 你直接全部走 proxy 送去远端解析也是可以的  就是本地地址和一些需要直连环境的会出问题

> 分流是規則那邊吧？不都是域名麽？
上课不好好听讲是要挂科的 https://lancellc.gitbook.io/clash/clash-config-file/rules
