### ISSUE TITLE
构建 Electron 使用 Webpack 但未删除 node_modules 导致包体积增大

### ISSUE THREAD

**Issue by ResetPower** [Fndroid/clash_for_windows_pkg#2075]
## 描述
（从一个前端的角度解包了应用，发现了一点点🤏东西）
解包后的 Resources/app.asar 中：
**package.json**:
- 诸如 `@babel/core` 的依赖属于开发依赖，不应放在 `package.json` 的 `dependencies` 中，应放在 `devDependencies` 中
- 从 `dist` 文件夹内容来看，打包应该使用了诸如 webpack 的打包工具，此时已经不需要 `node_modules` 文件夹，会增加部分包体积，如果您使用 electron-builder 请在主 json 的 `build` 中或 `electron-builder.yml` 中的 `file` 数组中加上 `!node_modules` 代表去掉 `node_modules` 文件夹。

## 其他说明
由于没有真正的源代码，看起来您的项目采用了双 package.json 结构，很多东西也是不清楚的，这些描述未必正确，只是我一时的观察。

**Comment by Fndroid** [comment]
1. package.json里的是`@babel/runtime`
2. electron是有node集成的，可以在js里引用模块
