### ISSUE TITLE
tun模式下开热点，内存占用过高

### ISSUE THREAD

**Issue by harnseen** [Fndroid/clash_for_windows_pkg#2077]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

~~- [ ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复~~
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
win10 & win11

**描述**
tun模式开热点，内存占用过高

**复现**

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**
[2021-07-28-090500.log.txt](https://github.com/Fndroid/clash_for_windows_pkg/files/6889667/2021-07-28-090500.log.txt)

**截图**
![](https://i.loli.net/2021/07/28/ZjYv73aPNxSV6y1.png)

![](https://i.loli.net/2021/07/28/Bs3y8EeDzxUKIT2.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by H4M5TER** [comment]
dump of #1444 #1622 #1649 #1862 #1865 #1895 #1912 #1925 #1997 ?
