### ISSUE TITLE
配置地址更新，怎么获取？

### ISSUE THREAD

**Issue by xinsuinizhuan** [Fndroid/clash_for_windows_pkg#2078]
win10，用的用的，突然不能用了，用之前的配置地址，一直提示错误。配置地址更新，怎么获取？

[//]: # (平台及版本号)

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
？配置找服务商啊
