### ISSUE TITLE
[Feature Request] Custom Rules

### ISSUE THREAD

**Issue by iam3ddy** [Fndroid/clash_for_windows_pkg#208]
Hi,

Would be nice if we could have an option to add custom rules. Therefore updating servers from subscription would not affect them.

**Comment by Fndroid** [comment]
- Rule -> Proxy (Group)
- Proxy Group -> Proxy

So we can't change Rules without considering Proxies and Proxy Groups

If you got a better idea, comment it in this issue https://github.com/Dreamacro/clash/issues/272
