### ISSUE TITLE
Proxies文件夹为空，点击配置文件显示Could not switch to this profile

### ISSUE THREAD

**Issue by MrRainbowYoo** [Fndroid/clash_for_windows_pkg#2082]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Win10-1909、v0.16.2

[//]: # (平台及版本号)

**描述**
System proxy可正常开启，但无法加载yaml配置文件，Proxies为空，点击配置文件出现Could not switch to this profile。

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
无
[//]: # (清晰地描述期望看到的行为)

**日志**
无
[//]: # (上传触发问题对应的日志文件)

**截图**
[![WO6mwT.png](https://z3.ax1x.com/2021/07/30/WO6mwT.png)](https://imgtu.com/i/WO6mwT)
[//]: # (如果可以，请提供对应问题的截图)

**其他说明**
无
[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
把配置文件里dns那部分删掉

**Comment by MrRainbowYoo** [comment]
> 把配置文件里dns那部分删掉

解决了！非常感谢！

**Comment by lengyuner** [comment]
> 把配置文件里dns那部分删掉

It helps!
thx!

**Comment by RorschachW** [comment]
> 把配置文件里dns那部分删掉
解决了，太感谢了！

**Comment by LeoLUuuu** [comment]
> 把配置文件里dns那部分删掉

It helps thx

**Comment by MarcWebber** [comment]
It helps thx

**Comment by xiaocuanChina** [comment]
> 把配置文件里dns那部分删掉
活菩萨啊，真好了
