### ISSUE TITLE
「功能建议」集成SSRClash批量转Clash格式

### ISSUE THREAD

**Issue by gongyoyo** [Fndroid/clash_for_windows_pkg#209]
部分ssr机场未提供clash配置，这里我发现了个机制脚本，支持直接通过ssR订阅生成clash配置文件，https://github.com/lzdnico/SSRClash
希望作者大大有空集成至主菜单，可怜的我小白一个，py脚本啥的一点都不懂😭

**Comment by Fndroid** [comment]
Clash不支持SSR，也不打算集成这些第三方脚本

**Comment by gongyoyo** [comment]
> Clash不支持SSR，也不打算集成这些第三方脚本

收到👌
