### ISSUE TITLE
感谢支持Linux，但是如何设置tun模式呢？

### ISSUE THREAD

**Issue by tony1016** [Fndroid/clash_for_windows_pkg#2090]
我通过mixing设置了tun，似乎tun接口也有了，但是域名没法正常解析。另外我看到是通过ip rule走的，但是能否介绍一下原理呢？

**Comment by Fndroid** [comment]
```yaml
dns-hijack：
  - 1.0.0.1:53
```

**Comment by tony1016** [comment]
很奇怪，我看mangle链没有打标记啊，请问是哪里打的标记呢？

**Comment by plutonemhikari** [comment]
> 很奇怪，我看mangle链没有打标记啊，请问是哪里打的标记呢？

看Kr328的clash-premium-installer，用的就是那个脚本，用的nftables

**Comment by tony1016** [comment]
> > 很奇怪，我看mangle链没有打标记啊，请问是哪里打的标记呢？
> 
> 看Kr328的clash-premium-installer，用的就是那个脚本，用的nftables

哦，懂了懂了，是用nftables实现的
