### ISSUE TITLE
无法代理ftp链接

### ISSUE THREAD

**Issue by wapmxls** [Fndroid/clash_for_windows_pkg#2096]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

使用filezilla(一款ftp软件)，开启了clash，然后按照端口设置了socket代理，但是没法正常链接到ftp服务器

但是使用V2RAYN是正常的，求大佬说下怎么处理

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

windows clash v0.17

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

![image](https://user-images.githubusercontent.com/41887380/127966133-c94b1472-352d-496e-b1aa-9190883ba3bc.png)

![image](https://user-images.githubusercontent.com/41887380/127966147-19bd02aa-81cc-4c3c-9d2d-5a3492c24de9.png)
![image](https://user-images.githubusercontent.com/41887380/127966172-1431611a-b78b-41fa-a8eb-5768683ff097.png)

**Comment by Fndroid** [comment]
看你配置走对了规则没有

**Comment by wapmxls** [comment]
> 看你配置走对了规则没有



> 看你配置走对了规则没有

配置完后，在链接的时候可以看到connecttion有ip:21的记录，但是很快就消失了，然后ftp客户端就会报错

**Comment by wapmxls** [comment]
@Fndroid 配置完后，在链接的时候可以看到connecttion有ip:21的记录，但是很快就消失了，然后ftp客户端就会报错,请问怎么解决呢？

**Comment by Fndroid** [comment]
看你自己规则，你把它reject了它肯定访问不了

**Comment by wapmxls** [comment]
@Fndroid  
规则里面没有关于我的IP(虚拟的代替)111.222.333.444的设置，然后为了测试我在规则里面添加了IP-CIDR的配置，内容是111.222.333.444/22（使用sftp协议，设置21一样连不上~），并设置了代理，没有选择reject

结果是无论在【没有规则】和【有IP-CIDR规则】规则，都是无法连接的

**Comment by yi-Xu-0100** [comment]
@wapmxls 检查日志中走的什么规则

**Comment by wapmxls** [comment]
@yi-Xu-0100 
日志里面是这样的
![image](https://user-images.githubusercontent.com/41887380/127982671-7f4f8280-c7d9-40d4-b16c-aa0a0c8ae024.png)

**Comment by wapmxls** [comment]
> @wapmxls 检查日志中走的什么规则

有办法解决吗 大佬

**Comment by wapmxls** [comment]
> 看你自己规则，你把它reject了它肯定访问不了

请问有办法解决吗 谢谢

**Comment by yi-Xu-0100** [comment]
规则上最后是走了代理的，其他的我也不知道。

**Comment by wapmxls** [comment]
> 规则上最后是走了代理的，其他的我也不知道。

用v2rayn的话是正常的，很喜欢clash 其他方面很好，能找一下原因吗？不想转回去用v2了

**Comment by yi-Xu-0100** [comment]
试试 pac 模式

**Comment by wapmxls** [comment]
> 试试 pac 模式， 参考这里 [#2073 (comment)](https://github.com/Fndroid/clash_for_windows_pkg/issues/2073#issuecomment-887773201)

不行  还是一样的错误 哎

**Comment by 1itt1eB0y** [comment]
Allow LAN打开，试过吗

**Comment by cpuopt** [comment]
可以考虑filezilla问题，试下不用内置代理设置，用proxifier代理filezilla到10813端口

**Comment by wapmxls** [comment]
> Allow LAN打开，试过吗

试过了 不行

**Comment by wapmxls** [comment]
> 可以考虑filezilla问题，试下不用内置代理设置，用proxifier代理filezilla到10813端口

测试了，依然还是不行  感觉是小猫客户端的问题....

**Comment by RtYkk** [comment]
ftp 还是 sftp？试试看换个节点或者设置规则为 DIRECT 试试看呢？
