### ISSUE TITLE
TUN模式下微信电脑版和手机版之间无法备份、恢复

### ISSUE THREAD

**Issue by leafsoul365** [Fndroid/clash_for_windows_pkg#2102]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

win10 21H1

**描述**
在使用TUN模式或TUN+system模式时，微信电脑版和手机版之间进行聊天记录备份、恢复等无法顺利完成，提示不在同一网络内。

**Comment by yi-Xu-0100** [comment]
参考这个 https://printempw.github.io/wechat-backup-in-sandboxie/

将所有的防火墙关闭即可，我的在公用网络中有 clash 网卡

**Comment by leafsoul365** [comment]
> 参考这个 https://printempw.github.io/wechat-backup-in-sandboxie/
> 
> 将所有的防火墙关闭即可，我的在公用网络中有 clash 网卡

谢谢解答。尝试过，我这里关闭防火墙也不行。

**Comment by yi-Xu-0100** [comment]
@leafsoul365 那建议先关闭 tun 试试吧，我这里尝试过是可行的。三个防火墙（域，专用，公用）我都关闭是可行的。

**Comment by leafsoul365** [comment]
> @leafsoul365 那建议先关闭 tun 试试吧，我这里尝试过是可行的。三个防火墙（域，专用，公用）我都关闭是可行的。

测试了下，由于我的台式机和手机是通过同一路由器分出的有线和无线两种连接方式，当1个有线1个无线时，clash系统代理认可为同一网络。TUN则不认可，即便关闭防火墙；
我把台式电脑和手机均用无线连接，则无论哪种模式，都可以顺利认可为同一网络。

**Comment by yi-Xu-0100** [comment]
@leafsoul365 确实如此，我两个都是无线环境。
