### ISSUE TITLE
Clash能否不自动刷新系统IE代理服务及“例外”？

### ISSUE THREAD

**Issue by MapleRen** [Fndroid/clash_for_windows_pkg#2103]
**描述**
1、因为公司需要挂代理服务器才能上网，我是通过Proxifier去使用Clash的，我希望在IE的代理服务器保留公司的代理和例外地址；然而不管我是否勾选System proxy时，我手动设置IE的代理服务器，保存之后重新打开会自动把代理服务器设置为127.0.0.1:7890，例外每次都会更新成。没办法自定义。
localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;192.168.*

**Comment by yi-Xu-0100** [comment]
![图片](https://user-images.githubusercontent.com/25523606/128107734-13510acb-5c45-4cd8-b3a5-299797ca2748.png)
