### ISSUE TITLE
在Parser中添加了规则，更新后规则也有，但还是不生效

### ISSUE THREAD

**Issue by geeklihui** [Fndroid/clash_for_windows_pkg#2104]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

Windows 10 21H7

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

把rarbgprx.org域名通过Parser规则，希望指定全球媒体规则（或GLOBAL，俩我都试了），保存Parser后更新订阅，编辑规则时发现该配置已经在规则中了，但是实际还是打不开这个域名，用Logs抓取显示该域名匹配的规则是漏网之鱼。

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'Settings'
2. 点击'Parsers项目的Edit'
3. 输入规则，点击保存
4. 打开浏览器刷新网页，问题复现

**预期行为**

[//]: # (清晰地描述期望看到的行为)

1. 应该可以正常访问该域名；
2. Logs抓取的结果应该是匹配国外媒体（或GLOBAL）

**日志**

[//]: # (上传触发问题对应的日志文件)
无

**截图**

[//]: # (如果可以，请提供对应问题的截图)
以下是Parser内容：
![image](https://user-images.githubusercontent.com/28993319/128116557-732580b9-fff2-4cb3-8bc6-eb819aa4f0b1.png)

以下是更新订阅后的规则：
![image](https://user-images.githubusercontent.com/28993319/128116083-b2da77f0-fbac-4373-a48a-23ce8a93c0be.png)

以下是Logs抓取情况：
![image](https://user-images.githubusercontent.com/28993319/128116037-a9523c35-18ad-4c1d-807d-ca1cd0ca2aa4.png)
**其他说明**

[//]: # (其他补充内容)
无

**Comment by geeklihui** [comment]
重启了客户端一下又好了...

**Comment by yi-Xu-0100** [comment]
parser 触发需要更新订阅。
