### ISSUE TITLE
TUN网卡显示“无网络访问权限” 的临时解决方法

### ISSUE THREAD

**Issue by returnL** [Fndroid/clash_for_windows_pkg#2108]
**描述**
Windows系统下 system stack 的TUN网卡第一次连通性测试会超时，网卡显示”无网络访问权限“，影响微软系应用的使用。在https://github.com/Dreamacro/clash/issues/1488#issuecomment-878999293 中@icpz 说明了连通性测试超时的原因，我发现运行 `ipconfig /renew` 可以顺便立刻让Windows进行一次连通性检测，可能短时间之内也等不到wintun解决这个问题，能否在TUN网卡开启后由CFW来执行`ipconfig /renew`，避免长时间等待系统再次进行连通性检测。
**其他说明**
或者能否实现 pre launch 和 post launch 的脚本支持，用以实现更多的事情。

**Comment by Fndroid** [comment]
不是已经修复了吗

**Comment by returnL** [comment]
gvisor的连通性检测没问题，换成system还是会显示
![image](https://user-images.githubusercontent.com/44701395/128335138-1423eba8-e35d-4859-9f0e-a083459b9c52.png)
我的Clash核心和CFW版本都是最新的，wintun也用的0.13版本

**Comment by icpz** [comment]
> 不是已经修复了吗

只修复了 gvisor 模式的连通性检测，system stack 目前可能没有什么好办法

**Comment by Fndroid** [comment]
那我在put configs完成之后执行`ipconfig /renew`能刷新过来吗 @icpz

**Comment by icpz** [comment]
> 那我在put configs完成之后执行`ipconfig /renew`能刷新过来吗 @icpz

应该不行……估计需要等 clash 实际监听好本地 `fake-ip:7777` 之后出现再 renew。

**Comment by PeroNya** [comment]
stack system模式下，无法代理游戏

**Comment by falloutxxx2** [comment]
> 不是已经修复了吗

Microsoft Windows [版本 10.0.22000.120] 
Clash v 0.17.0

**Comment by Fndroid** [comment]
下个版本会加上这个renew操作

**Comment by kmahyyg** [comment]
我不知道你们有没有设置这个？（当然，我现在的stack是 gvisor，不是system，Windows 10）

![image](https://user-images.githubusercontent.com/16604643/129431981-4a25e396-33a2-47b9-8f31-4c2e2fa8715b.png)

另外还有个小问题...

![image](https://user-images.githubusercontent.com/16604643/129432024-f12fef53-a783-4a49-8d23-c36e92252ea0.png)

我不知道 Windows 是怎么计数网络的... 我之前用自己写的 bat 直接起 core 的时候没有这个问题，我猜应该是什么 uuid，能不能把虚拟网络的这个标识符在第一次启动时固定，不然每次 mixin 开启前后 clash 这个网络的数字总会 +1 次，有点心里不舒服...

**Comment by returnL** [comment]
> 我不知道你们有没有设置这个？（当然，我现在的stack是 gvisor，不是system，Windows 10）
> 
> ![image](https://user-images.githubusercontent.com/16604643/129431981-4a25e396-33a2-47b9-8f31-4c2e2fa8715b.png)
> 
> 另外还有个小问题...
> 
> ![image](https://user-images.githubusercontent.com/16604643/129432024-f12fef53-a783-4a49-8d23-c36e92252ea0.png)
> 
> 我不知道 Windows 是怎么计数网络的... 我之前用自己写的 bat 直接起 core 的时候没有这个问题，我猜应该是什么 uuid，能不能把虚拟网络的这个标识符在第一次启动时固定，不然每次 mixin 开启前后 clash 这个网络的数字总会 +1 次，有点心里不舒服...

设置过`fake-ip-filter`了，此comment讨论的“无网络访问权限” 的原因并不是这个。

我自己三台电脑试下来，Clash网卡后面的数字均并不会因为开关而增加，应该需要你排查一下自己电脑的设置。

**Comment by falloutxxx2** [comment]
我觉得这个问题在 win11 上面就没修复！！！！

**Comment by lcysyx** [comment]
由于ipconfig /renew只对DHCP获取IP的网络环境有效，对于公司等静态配置IP的网络环境无效，stack使用system还是会显示“无网络访问权限”

**Comment by DEXTERcyy** [comment]
20220626, v.0.19.22,core61196,wintun14.1, 问题还是没有解决

**Comment by hongwen000** [comment]
没解决....

**Comment by hongwen000** [comment]
救命，求一个即便是临时的解决方案，微软系app包括整套office 服务都无法使用

**Comment by RangXuan** [comment]
> 20220626, v.0.19.22,core61196,wintun14.1, 问题还是没有解决

我的也是0.20.17
