### ISSUE TITLE
新版本v0.7.9添加规则界面Proxy or Policy部分是空的

### ISSUE THREAD

**Issue by Iant20** [Fndroid/clash_for_windows_pkg#211]
节点和策略组都没显示，如下图所示

![image](https://user-images.githubusercontent.com/30554621/65791286-fea24400-e193-11e9-8ca5-9dcb690f049c.png)

**Comment by yhnbgfd** [comment]
而且Add跟Cancel按钮不是圆角的，有点不和谐

**Comment by Fndroid** [comment]
已知bug，下版本修复

**Comment by Fndroid** [comment]
最新版已修复：https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.7.11
