### ISSUE TITLE
强烈建议在 UI 中加入 “添加防火墙例外” 选项。

### ISSUE THREAD

**Issue by Mirr0ch1** [Fndroid/clash_for_windows_pkg#2111]
well，事情是这样的。

我打算和朋友共用电脑，所以新建了一个 windows 账户。为了方便操作，把原本安装在 users 目录的 clash 移除，重新安装在了 program files 里。

于是问题来了 —— 不论如何操作，wintun 模式都用不了。

最后检查发现，是由于我更改了 Clash 安装目录，并且 tun mode 使用的为 system 并非 gvisor，需要对 clash-win64 添加防火墙例外。

而旧的例外规则因为安装目录更改失效了。。。

嗯我知道这个选项可能有点儿一次性了，但是还是想请问一下能否能在设置页面加入一个快速添加 CFW 相关进程到防火墙例外的一键按钮？感谢。

**Comment by yi-Xu-0100** [comment]
我记得重新安装的话，会再次提醒防火墙的。
