### ISSUE TITLE
TUN 模式启动失败

### ISSUE THREAD

**Issue by DotRacel** [Fndroid/clash_for_windows_pkg#2114]
**信息**
- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 Pro 21H1
Clash for Windows v0.17.0

**描述**

TUN 模式无法开启，通过设备管理器删除掉原有的网卡，然后重启 CFW，即可修复，但是下次启动 CFW 同样的问题还会重现

`time="2021-08-09T07:59:55+08:00" level=error msg="Start Tun interface error: error deleting already existing interface: The handle is invalid."`

**复现**

不太清楚是怎么一回事，有的时候会出现这种问题，可能是我使用了UU加速器的问题？
（但我用加速器一般都直接把Clash关掉不会让他俩共存）

**预期行为**
在网络连接中 Clash Tunnel 应该正常可用，而不正常情况下是未插入

**日志**

`time="2021-08-09T07:59:55+08:00" level=error msg="Start Tun interface error: error deleting already existing interface: The handle is invalid."`

**Comment by Fndroid** [comment]
看看设备管理器里面网络适配器是不是有Clash Tunnel的网卡卸载了重新试试

**Comment by falloutxxx2** [comment]
> 看看设备管理器里面网络适配器是不是有Clash Tunnel的网卡卸载了重新试试

TUN 模式 WIN11 休眠后唤醒 就有这个问题 把 Clash Tunnel的网卡卸载了 再开 clash 就好了 老板修一下呗~！

**Comment by DotRacel** [comment]
> 看看设备管理器里面网络适配器是不是有Clash Tunnel的网卡卸载了重新试试

现在每次都是这样来搞的。
直接在网络适配器里卸载不了，需要在设备管理器里卸载设备+驱动。
每次启动前都得卸载一遍，否则就用不了TUN，Clash Tunnel也不会正常
会显示断开。

**Comment by falloutxxx2** [comment]
> > 看看设备管理器里面网络适配器是不是有Clash Tunnel的网卡卸载了重新试试
> 
> 现在每次都是这样来搞的。
> 直接在网络适配器里卸载不了，需要在设备管理器里卸载设备+驱动。
> 每次启动前都得卸载一遍，否则就用不了TUN，Clash Tunnel也不会正常
> 会显示断开。

Wintun 0.12 好像没这个问题 。。。驱动卸载了换了看看

**Comment by kusiru** [comment]
我也是这样，wifi就没问题

**Comment by DotRacel** [comment]
> > > 看看设备管理器里面网络适配器是不是有Clash Tunnel的网卡卸载了重新试试
> > 
> > 
> > 现在每次都是这样来搞的。
> > 直接在网络适配器里卸载不了，需要在设备管理器里卸载设备+驱动。
> > 每次启动前都得卸载一遍，否则就用不了TUN，Clash Tunnel也不会正常
> > 会显示断开。
> 
> Wintun 0.12 好像没这个问题 。。。驱动卸载了换了看看

用的就是这个
很奇怪，现在没这个问题了，到时候问题复现再说吧
