### ISSUE TITLE
部分profile无法更新

### ISSUE THREAD

**Issue by lshilshi** [Fndroid/clash_for_windows_pkg#2115]
[//]: # (如不按模版填写，则issue将被直接关闭)

**更新profile时候，报错。**
[Parser Error] Cannot read property "length' of null

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

**WIN 7 Pro X64，Clash for Win最新版**

[//]: # (请具体并清楚地描述遇到的问题)

**从CFW 0.16.0版本之后必然出现**
但不清楚是Profile端还是CFW的问题
但是同一个profile，在Clash的android端是可以正常更新的，所以CFW至少有些问题吧

[//]: # (请描述复现问题的步骤)

1. 进入'profile'页面
2. 点击'对应prrofile的更新按钮/更新全部'
3. 触发问题：此profile必然会更新失败，报错，报错内容如下
```
Error
Downloac profile(https://free.kingfu.cf/clash/config) failed
with error: [Parser Error] Cannot read property "length' of null
OK
```

**预期行为**

[//]: # (清晰地描述期望看到的行为)
修复引发此问题的bug(maybe?)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
parser 写啥了？

**Comment by lshilshi** [comment]
> parser 写啥了？

Parser空白的时候也是这样的啊

**Comment by lshilshi** [comment]
> parser 写啥了？

抱歉测试了下，还真是parser的问题
将parser留空，更新无问题

但是我10来个profile，其它几个更新都正常，就这个profile更新会失败

parser内容如下
```
parsers: # array
  - reg: ^.*$
    file: 'C:/Users/CanYang/.config/clash/scripts/change-rules.js'
```

初步看，是parser写错了，还是js的问题？

**Comment by yi-Xu-0100** [comment]
js 中读取某个值的长度时，没找到这个值。

js 处理过程中的问题。parser 写的对的。

也可以通过精确reg匹配，让这个配置不经过该 parser 。

**Comment by lshilshi** [comment]
> js 中读取某个值的长度时，没找到这个值。
> 
> js 处理过程中的问题。parser 写的对的。
> 
> 也可以通过精确reg匹配，让这个配置不经过该 parser 。

希望都通过这个parser，因为不同profile的规则相当不一致，有的用的好，换个就各种不适
所以想统一下，看来的看看js有啥问题了

抱歉写错issue了，应该不是bug，请管理员修正下标题吧。

**Comment by lshilshi** [comment]
> js 中读取某个值的长度时，没找到这个值。
> 
> js 处理过程中的问题。parser 写的对的。
> 
> 也可以通过精确reg匹配，让这个配置不经过该 parser 。

汗了，发现我用的这个js，就是用的老大你的作品啊
"https://github.com/yi-Xu-0100/cfw-scripts"
直接请你看看js哪里的问题吧

问题profile是"https://free.kingfu.cf/clash/config"

**Comment by yi-Xu-0100** [comment]
@lshilshi 那关闭这个 issue ，去我的仓库提交 issue 吧，给出全部的相关的 parser 内容。方便我复现。( 没想到有人会用我的这个脚本 😂
