### ISSUE TITLE
恢复在 macOS 的状态栏图标中显示代理状态的功能

### ISSUE THREAD

**Issue by alanyoungCN** [Fndroid/clash_for_windows_pkg#2120]
**描述**
在某个版本之前，软件打开 System Proxy 后在上面的状态栏中会多一个小 s 标志，表示打开系统代理，但之后的所有更新都取消了这一功能，这是个很方便的细节，所以希望能够恢复。

**其他说明**
无

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/128975330-082bd125-dfc9-45ab-a5fe-35906a853d8f.png)

**Comment by alanyoungCN** [comment]
但是这样会附带显示网速，占用较多空间，13寸屏幕较小，还望理解🙏 。

**Comment by chenby228** [comment]
+1

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
