### ISSUE TITLE
更新软件之后，过段时间会重新回到更新之前的版本

### ISSUE THREAD

**Issue by chwncy** [Fndroid/clash_for_windows_pkg#2121]
![1](https://user-images.githubusercontent.com/31879464/128979715-175a7658-3c35-4fb1-903d-e20ef115294a.png)

**Comment by yi-Xu-0100** [comment]
安装多个版本了吗？

**Comment by chwncy** [comment]
> 安装多个版本了吗？

并没有，一直都是让他自动更新的，目录下面貌似也没有看到其他版本

**Comment by yi-Xu-0100** [comment]
去对应目录看看版本

**Comment by chwncy** [comment]
> 去对应目录看看版本

当我把安装目录删除之后,重新安装最新版本时,它提示c盘目录下有个软件目录,打开之后发现确实存在另外一个版本,删除之后就没有
