### ISSUE TITLE
0.7.9 安装版完整检查出错 绿色版解压数据出错

### ISSUE THREAD

**Issue by sharpzhango** [Fndroid/clash_for_windows_pkg#213]
![解压报错](https://user-images.githubusercontent.com/43055229/65826435-816fef80-e2b7-11e9-9731-b18b29785a28.jpg)
![安装报错](https://user-images.githubusercontent.com/43055229/65826440-89c82a80-e2b7-11e9-9257-88e91b8051a0.jpg)

**Comment by Meeeeow** [comment]
重新下载一下，测试了下7-Zip可以解压，也可以正常安装
