### ISSUE TITLE
Adding System Proxy feature to linux

### ISSUE THREAD

**Issue by hamidreza2005** [Fndroid/clash_for_windows_pkg#2130]
Hi there . i'm not chinese by the way . i'm from iran and as you know iran like china has been censored internet for a long time . 
i am currently using linux and there is no system proxy option in linux version of clash and i have to set proxy by myself. so it would be better to add system proxy to linux version like mac and windows versions.

thanks;

**Comment by yi-Xu-0100** [comment]
See the answer by the author about this question: https://github.com/Fndroid/clash_for_windows_pkg/issues/2107#issuecomment-893139189

The following is translated through Google Translate.

Linux does not have a unified system proxy concept, and it is troublesome to implement different desktops with different interfaces. I will update the document for opening TUN later. If it is configured to directly take over the system network, there is no need to open a system proxy.

**Comment by sky5454** [comment]
If you wanna use System Proxy, you can see: https://github.com/Qv2ray/Qv2ray
