### ISSUE TITLE
Mac Apple Silicon can't start clash for windows.

### ISSUE THREAD

**Issue by carloscn** [Fndroid/clash_for_windows_pkg#2133]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # MAC M1 Apple SILICON 

**描述**

[//]: # Can't start clash.

**复现**

[//]: # 

1. download arm64 dmg file.
2. move clash to applications
3. click clash for windows.
4. prompt the error as the follow picture.

both the 17.0. and 17.1 can be reproduced.
![image](https://user-images.githubusercontent.com/16836611/129439208-a8301846-9998-4f65-ade9-89e0d0e134a0.png)

**Comment by LiamSho** [comment]
尝试使用 Homebrew 进行安装也是如此

1. 使用 `brew install clash-for-windows` 指令安装 Cask
2. 打开 Clash for Windows.app
3. 弹出 “Clash for Windows” 已损坏，无法打开 的对话框

**Comment by donald-ning** [comment]
使用终端
```
sudo xattr -r -d com.apple.quarantine /Applcations/Clash\ for \ Windows.app 
```

**Comment by carloscn** [comment]
> 使用终端
> 
> ```
> sudo xattr -r -d com.apple.quarantine /Applcations/Clash\ for \ Windows.app 
> ```

yes, it works.

**Comment by eromoe** [comment]
@donald-ning  想问一下为什么一定要通过命令安装？

**Comment by Cekavis** [comment]
> 使用终端
> 
> ```
> sudo xattr -r -d com.apple.quarantine /Applcations/Clash\ for \ Windows.app 
> ```

在 `for` 后面似乎多了一个空格？

**Comment by Aurora-Stack** [comment]
> sudo xattr -r -d com.apple.quarantine /Applcations/Clash\ for \ Windows.app

Applications

**Comment by wanglz111** [comment]
```
sudo xattr -r -d com.apple.quarantine /Applications/Clash\ for\ Windows.app
```
