### ISSUE TITLE
linux（manjaro）下 2k分辨率 200缩放 窗口过大，且无法调节

### ISSUE THREAD

**Issue by dalaoshi777** [Fndroid/clash_for_windows_pkg#2135]
![image](https://user-images.githubusercontent.com/47414347/129448092-f99dab73-ef13-4b06-b818-0a8b3067c38c.png)

**Comment by Fndroid** [comment]
`ctrl`+`-`能调整吗

**Comment by dalaoshi777** [comment]
18.0正常了
