### ISSUE TITLE
节点名称重复导致无法更新订阅

### ISSUE THREAD

**Issue by JoinWDT** [Fndroid/clash_for_windows_pkg#2137]
**系统**

windows 10 家庭版
clash for windwos v 0.17.1

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

订阅地址中有两个相同的节点名称，导致无法更新订阅吗，如下图:

![image](https://user-images.githubusercontent.com/26700541/129500695-7e35ab12-5f8f-4822-bb75-fbeb179c73eb.png)

点击 Edit in Text Mode编辑后再次更新订阅无效

在v2aryN中可以正常订阅，如下图:

![image](https://user-images.githubusercontent.com/26700541/129500757-6867878a-0227-4141-b7cb-4329c69b50c4.png)

**Comment by Fndroid** [comment]
预期行为
