### ISSUE TITLE
在 TUN 模式下，使用 ssh 连接远程主机时出现错误

### ISSUE THREAD

**Issue by renbaoshuo** [Fndroid/clash_for_windows_pkg#2139]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

+ Windows 11 22000.132
+ Clash for Windows v0.17.1

**描述**

![image](https://user-images.githubusercontent.com/47095648/129509029-519522a6-8e7c-41f4-b212-bf90ab1310cf.png)

在 TUN 模式下，使用 ssh 连接远程主机时会出现如上图所示的连接错乱的情况。

**复现**

[//]: # (请描述复现问题的步骤)

1. 开启 TUN 模式。
2. 使用 `ssh root@${ip}` 连接自己域名解析到的三台服务器。

**预期行为**

正常连接到对应的服务器。

**日志**

```
time="2021-08-16T11:50:07+08:00" level=info msg="[TCP] 198.18.0.1:64523 --> baoshuo.ren:22 match DstPort(22) using DIRECT"
time="2021-08-16T11:50:10+08:00" level=info msg="[TCP] 198.18.0.1:52970 --> baoshuo.ren:22 match DstPort(22) using DIRECT"
time="2021-08-16T11:50:22+08:00" level=info msg="[TCP] 198.18.0.1:52990 --> baoshuo.ren:22 match DstPort(22) using DIRECT"
```

**其他说明**

我在连接时是使用服务器 IP 进行的连接，但不知为何到了日志里记录下的是域名。

**Comment by Fndroid** [comment]
我这里无法复现连接问题（win10）
至于日志里显示的是域名很可能是因为你用过域名连接，DNS解析的结果被缓存了，之后用IP访问会反推出域名

**Comment by renbaoshuo** [comment]
> 我这里无法复现连接问题（win10）
> 至于日志里显示的是域名很可能是因为你用过域名连接，DNS解析的结果被缓存了，之后用IP访问会反推出域名

那请问如何关闭反推域名的功能，因为网站解析指向的 IP 也是这三个，清除了缓存也没用。

**Comment by Fndroid** [comment]
不能关闭，实际上也不影响访问，你最后是直连的话也是用你输入的IP的，只是日志打印出来是域名

**Comment by renbaoshuo** [comment]
但是事实上连接到的服务器确实是错误的，通过我的截图就能看出来。

**Comment by Fndroid** [comment]
你重启下Clash，然后直接用IP试试

**Comment by renbaoshuo** [comment]
感谢，现在看起来好了，那为什么当时我测试的时候会出现错误呢？

**Comment by Fndroid** [comment]
因为你如果执行过`ssh root@baoshuo.ren`，会匹配到DIRECT就会触发域名解析，然后解析结果会被缓存，如果这个时候你用这里面其中一个结果访问，那么Clash就会反推出来域名，拿域名去访问，这确实有可能会导致最后访问的IP不对应。

但是TUN里也需要这种反推，不然所有域名类规则都无法生效。

**Comment by renbaoshuo** [comment]
事实上我并没有执行过 `ssh root@baoshuo.ren` 这种操作，但是访问过 https://baoshuo.ren ，应该是访问的时候缓存了解析结果。

**Comment by Fndroid** [comment]
直接访问也会缓存结果的。

如果你想要从3个IP固定一个，可以试试在配置文件里用hosts指定：
```yaml
hosts:
  'baoshuo.ren': 1.1.1.1
```

**Comment by renbaoshuo** [comment]
这样似乎并没有作用，ssh 时仍然会复现错误。

**Comment by fakeboboliu** [comment]
很简单，如果你开了 fakeip 的话可能会有这样的问题，流程如下：

 - 通过浏览器访问域名，此时增强模式下，clash 的 redir 用 cache mapping 记录下你的域名对应 ip
 - 通过 ssh 客户端访问 ip，[tunnel](https://github.com/Dreamacro/clash/blob/baf03b81e36e3c5d8b9a370ebb82dd2b25b4a58d/tunnel/tunnel.go#L120) 开始解析 metadata，并在 L134 的 FindHostByIP 中，从 redir 的 mapping 中得到了你的域名
 - 因为 fakeip 打开，上述文件 L139 在 metadata 中删除了你的目标ip
 - L321，因为 metadata 中没有 ip 只有 host，隧道开始通过 dns 寻找 host 对应 ip
 - 你的连接被发到一个错误的 ip，因为你的域名有三个 ip 随机顺序返回

**Comment by renbaoshuo** [comment]
这似乎是 Clash 核心的问题，抱歉打扰到各位，我认为应该移步 https://github.com/Dreamacro/clash/issues/1545 讨论，先关闭掉这个 issue 了。

**Comment by inkss** [comment]
请问我在 tun 下，ssh 的 ip 地址连接自己的服务器走代理了，请问怎么避免这个过程呢？

**Comment by renbaoshuo** [comment]
@inkss 可以考虑对 22 端口配置特定的规则： https://lancellc.gitbook.io/clash/clash-config-file/rules/miscellaneous-rule

**Comment by inkss** [comment]
> @inkss 可以考虑对 22 端口配置特定的规则： https://lancellc.gitbook.io/clash/clash-config-file/rules/miscellaneous-rule

写成这个样子吗？

```
SRC-PORT,22,DIRECT
```

**Comment by yuze0804007** [comment]
> > @inkss 可以考虑对 22 端口配置特定的规则： https://lancellc.gitbook.io/clash/clash-config-file/rules/miscellaneous-rule
> 
> 写成这个样子吗？
> 
> ```
> 
> - DST-PORT,22,DIRECT
> ```

- DST-PORT,22,global
亲测可行!!!
