### ISSUE TITLE
什么事件会让url-test重新选择节点？

### ISSUE THREAD

**Issue by zt900403** [Fndroid/clash_for_windows_pkg#214]
最近因为一些众所周知的原因，一些url-test中的节点不可用了，
设定的timeout是300s，用着用着就不能用了， 手动测速也不会影响他重新选择节点，
但是又想让他自动选择一个速度较快的节点，请问什么动作可以让url-test重新选择节点？

有在clash中找到url-test有prefer参数，stable是否支持重新手动测速？https://github.com/Dreamacro/clash/pull/280

谢谢！

**Comment by Fndroid** [comment]
现在手动测试应该是会激活节点了
