### ISSUE TITLE
Mac电脑安装不了

### ISSUE THREAD

**Issue by lenvonsam** [Fndroid/clash_for_windows_pkg#2148]
**系统**

![image](https://user-images.githubusercontent.com/10168476/129840642-37fa37af-8b97-4d00-a12f-1ea40f3fdaa0.png)

**版本号**
0.17.1

**描述**

![image](https://user-images.githubusercontent.com/10168476/129840604-0eb408fe-9c91-4c0e-95b5-3eceb109670d.png)

从github releases上面下载了后，双击dmg文件，显示上图的问题，完全无法安装

**Comment by Fndroid** [comment]
你的是intel，下m1的arm干什么
