### ISSUE TITLE
Direct traffic  at startup

### ISSUE THREAD

**Issue by realsarm** [Fndroid/clash_for_windows_pkg#2149]
Hi,
While startup if you look at the connection list a few connection connects directly. This might be in some cases lethal as it leaks your real IP. 
![image](https://user-images.githubusercontent.com/37932944/129900790-1cc286ac-623c-48b9-95d6-ff96571daa09.png)

Can this be fixed by incorporating something like kill-switch or blocking connections on startup?

**Comment by akw5454521** [comment]
I think this is for obtaining Ads only

**Comment by realsarm** [comment]
@akw5454521 No, its very first connection whatever it is. also I don't think cfw contains any ads

**Comment by Fndroid** [comment]
1. Edit `config.yaml` in Home Directory at General
  ```yaml
  mode: rule
  rules:
    - MATCH,REJECT
  ```
2. Restart the APP

**Comment by realsarm** [comment]
Thanks. It's a little hidden. Can't this be added as a switch?  @Fndroid
