### ISSUE TITLE
0.17.1 设置开机自启后，重启电脑会展示程序界面

### ISSUE THREAD

**Issue by Musecanyang** [Fndroid/clash_for_windows_pkg#2151]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ x] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号) 
Windows 10 家庭中文版  21H1  版本号：19043.1165
**描述**

[//]: # (请具体并清楚地描述遇到的问题)
设置了开机自启，之前都是默认只展示托盘，但是现在会展示程序界面
**复现**
设置开机自启，然后重启电脑
[//]: # (请描述复现问题的步骤)
设置开机自启，然后重启电脑
1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)
不展示程序界面，只在托盘中展示
**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
![图片](https://user-images.githubusercontent.com/25523606/129997324-48aef2d9-46be-41cb-badd-ad4d99dd2a76.png)

**Comment by Musecanyang** [comment]
@yi-Xu-0100  谢谢你。完美解决了。
