### ISSUE TITLE
0.7.10_Error: Drag to sort or add to the list  on the right

### ISSUE THREAD

**Issue by happy201807** [Fndroid/clash_for_windows_pkg#216]
0.7.10,改Profiles-Edit policies 总是提示这个“Drag to sort or add to the list  on the right”，删了.config/重装exe都无效，请问现阶段可以回退到哪个版本用?

**Comment by Fndroid** [comment]
没看懂，这句话也不是报错

**Comment by happy201807** [comment]
![阿里旺旺图片20191006202634](https://user-images.githubusercontent.com/41731934/66269169-ef985180-e877-11e9-84aa-32ee25156572.jpg)

![阿里旺旺图片20191006203028](https://user-images.githubusercontent.com/41731934/66269184-2a9a8500-e878-11e9-99e0-3e4b9b07f977.jpg)

**Comment by Fndroid** [comment]
你这个配置文件能选中么，内容确定没问题？

**Comment by happy201807** [comment]
目前无法通过webgui修改config，删了.config/重装exe都无效。

**Comment by happy201807** [comment]
删了原来的.config文件夹，重新打开clash for Windows创建，发现profiles文件夹里的自动生成的文件xx.yml内容为“null”，请问是这个原因吗？

**Comment by happy201807** [comment]
cp C:\Users\.config\clash\config.yml  C:\Users\.config\clash\profiles\number.yml 后Edit policies可以正常打开，问题解决。
