### ISSUE TITLE
局域网连接( Allow LAN )问题

### ISSUE THREAD

**Issue by Jxpro** [Fndroid/clash_for_windows_pkg#2161]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

-  win10系统
-  软件版本 0.17.1

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
- 现有A和B两个wifi
- 当我在电脑上连接A wifi，软件打开系统代理，允许局域网
- 手机连接A wifi以后，也将代理设置为了电脑所对应的WLAN地址 和 混合端口11223
- 此时手机可以通过代理正常科学上网，国内国外网站均可访问
- 当我将手机和电脑同时切换到B wifi以后
- 电脑同样打开系统代理和允许局域网
- 手机也将代理设置为了电脑的WLAN地址和混合端口11223
- 但是却无法通过代理上网，国内国外的网站均访问不了，但是还可以使用qq聊天发消息

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)
- 连接A和B wifi时应该均可正常上网

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
建议先看看日志，手机访问的时候，确实有访问。

**Comment by Jxpro** [comment]
### 这是连接A wifi 可以正常上网时的日志
![}7VQKC%Y`J{(~}}A$EPN OM](https://user-images.githubusercontent.com/87376573/130342211-6015331f-e7a8-4e13-b484-e343316064d3.png)
**图一**

**Comment by Jxpro** [comment]
![V(V1 5FFYI Y2QRJ15R35](https://user-images.githubusercontent.com/87376573/130342242-acd00c16-f1ee-42d2-8c90-10110de5a552.png)
**图二**

**Comment by Jxpro** [comment]
### 这是连接B wifi 无法上网时候的日志，都是空的，设置过防火墙了，但是也没用， 不知道是不是哪没设置好呢
![TB_8ZAJLF)8 E}_~}H~UTRQ](https://user-images.githubusercontent.com/87376573/130342276-a20f39ea-20be-44be-b96b-bcb11caec9e4.png)

**Comment by Fndroid** [comment]
使用任何非Github版本，请勿发issue，谢谢合作
