### ISSUE TITLE
[ Bug ] 配置界面 订阅的刷新时间 的显示问题

### ISSUE THREAD

**Issue by Jxpro** [Fndroid/clash_for_windows_pkg#2162]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
- win10
- CFW 0.17.1

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
- 配置界面的订阅刷新显示有问题，第一次更新订阅以后，更新订阅的时间显示为几秒前
- 我再点一下更新，他的更新时间就变成了几秒后

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'配置'
2. 点击'某个配置文件的刷新按钮'
3. 订阅旁边的时间显示为 几秒前
4. 再次点击'同一配置文件的刷新按钮'
5. 订阅旁边的时间显示为 几秒后

**预期行为**

[//]: # (清晰地描述期望看到的行为)
不管怎么刷新都应该显示为 某个时间前，而不是 某个时间后

**日志**

[//]: # (上传触发问题对应的日志文件)
日志文件对此问题无太大帮助

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![s (1)](https://user-images.githubusercontent.com/87376573/130342790-40ddb310-d97c-4eb4-a52a-c011684c8a95.png)
![s (2)](https://user-images.githubusercontent.com/87376573/130342793-ba009544-dc48-4395-a8f2-d4d0bfbcf656.png)

**其他说明**

[//]: # (其他补充内容)
辛苦大佬们了

**Comment by Fndroid** [comment]
使用任何非Github版本，请勿发issue，谢谢合作

**Comment by Jxpro** [comment]
这是GitHub版本汉化了一下也不行吗
