### ISSUE TITLE
System Proxy和TUN同时打开时，Force Quit后再打开CFW 无法重启TUN网卡

### ISSUE THREAD

**Issue by returnL** [Fndroid/clash_for_windows_pkg#2163]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Windows 10 21H1 CFW 0.17.1

**描述**
System Proxy和TUN同时打开时，会碰到以下两种情况
现象1：Quit再打开（Quit后TUN网卡正常关闭了），TUN模式未正常开启（不一定碰到）。
现象2：Force Quit后，TUN网卡未关闭，再次开启CFW后，TUN网卡先关闭但未再打开（可100%重现，0.17.0和0.17.1均存在此现象）。
两种现象产生的日志是一样的

关闭System Proxy，只用TUN时
Quit后再打开，TUN模式能正常打开。
Force Quit后，TUN网卡未关闭，但是再开CFW，TUN网卡能先关闭再打开，顺利重启。

**复现**
1. CFW开启TUN模式在后台运行
2. Force Quit CFW，此时TUN网卡仍打开
3. 再次打开CFW，TUN网卡先关闭，但未再打开

**预期行为**
成功开启TUN模式

**日志**
```
time="2021-08-22T19:29:15+08:00" level=info msg="[Wintun] WintunDeleteAdapter: Failed to remove adapter 19: 句柄无效。 (Code 0x00000006)"
time="2021-08-22T19:29:15+08:00" level=info msg="[Wintun] CheckReboot: Failed to retrieve adapter 19 device installation parameters: 句柄无效。 (Code 0x00000006)"
```

**截图**
![image](https://user-images.githubusercontent.com/44701395/130353110-bdc6d1e8-a6c9-406a-b938-1393072840d9.png)

**Comment by yi-Xu-0100** [comment]
你是如何退出的？强制关闭？日志里是啥？

**Comment by returnL** [comment]
> 你是如何退出的？强制关闭？日志里是啥？
> 

右键图标，点击“Quit”退出

**Comment by returnL** [comment]
日志如下
```
time="2021-08-22T19:29:15+08:00" level=info msg="[Wintun] WintunDeleteAdapter: Failed to remove adapter 19: 句柄无效。 (Code 0x00000006)"
time="2021-08-22T19:29:15+08:00" level=info msg="[Wintun] CheckReboot: Failed to retrieve adapter 19 device installation parameters: 句柄无效。 (Code 0x00000006)"
```

**Comment by returnL** [comment]
开关了几次CFW之后，现象又变了。现在Quit后再打开，TUN模式能正常打开；但是Force Quit后，TUN网卡未正常关闭

**Comment by returnL** [comment]
两种现象，产生的日志是一样的，都是上面发的那两条

**Comment by yi-Xu-0100** [comment]
@returnL 嗯，quit 就好，force quit 应该只是关 CFW。理论上，重新打开会尝试关闭原来的 clash 网卡，然后重新建立，如果关闭不成功，可能就出问题吧。

**Comment by returnL** [comment]
> @returnL 嗯，quit 就好，force quit 应该只是关 CFW。理论上，重新打开会尝试关闭原来的 clash 网卡，然后重新建立，如果关闭不成功，可能就出问题吧。
> 

我正常Quit会出现一开始描述的问题。后来现象改变之后，多次开关GFW，还是能遇到最初描述的现象，即Quit再打开，TUN模式未能成功开启

**Comment by returnL** [comment]
两种现象产生的日志是一样的

**Comment by returnL** [comment]
以上现象都是在System Proxy和TUN同时打开的情况下遇到的。
我关闭System Proxy后，TUN模式的开关都是正常的。
Quit后再打开，TUN模式能正常打开。
Force Quit后，TUN网卡未关闭，但是再开CFW，TUN网卡能先关闭再打开，顺利重启。

**Comment by returnL** [comment]
System Proxy和TUN同时打开，Force Quit后，TUN网卡未关闭，再次开启CFW后，TUN网卡先关闭但未再打开。这个现象我在0.17.0和0.17.1版本都能碰到

**Comment by xy9860** [comment]
我在更新了tun之后，100%出现重开clash无法启动tun网卡，每次都要去删除网卡设备再打开clash

**Comment by yi-Xu-0100** [comment]
@xy9860 更新的是 wintun.dll 吗？不建议更，新版好像就是有点问题

**Comment by xy9860** [comment]
> @xy9860 更新的是 wintun.dll 吗？不建议更，新版好像就是有点问题

是的，我另外一台用旧版 wintun.dll 的就没有问题

**Comment by returnL** [comment]
那我也用回0.12版本的wintun了
