### ISSUE TITLE
pac代理时出现代理失败，切换成http代理时恢复：求问系统代理类型http和pac区别和原理

### ISSUE THREAD

**Issue by Elucidator-xrb** [Fndroid/clash_for_windows_pkg#2166]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
windows 10
v 0.14.6

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
调整“代理类型“为”pac“，并添加了pac内容，一开始可以正常使用代理。然而某时段再次使用时，代理失效（即google用不了翻墙失败）；切回http代理（也添加过绕过域名/网段 bypass内容），又可以正常代理。因而感到困惑。
![image](https://user-images.githubusercontent.com/70893377/130610838-26e368f1-15a7-4e8c-a945-127491edaa98.png)

· 想知道为何pac代理会出现这种问题。
· 想知道http代理和pac代理的区别和原理。
· 想知道相关知识哪里会有较为系统的介绍，或者相关知识的名称。（只检索到零碎pac代理文件相关内容）
本人初涉网络，没有相关知识，一般的检索方法似乎找不到相关知识介绍和问题处理方式，因而在此求助

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'设置'（setting）
2. 在'系统代理'（system proxy）切换pac和http模式，查看代理是否生效

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)
在写issue的过程中，clash不小心被我更新了，好像找不到了的样子。。。
![image](https://user-images.githubusercontent.com/70893377/130611489-c2bcc511-0342-4ba4-9299-cbdb511be173.png)
是在这里找的吗？

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)
其实主要还是想寻求相关门径的知识~

**Comment by Fndroid** [comment]
使用任何非Github版本，请勿发issue，谢谢合作
