### ISSUE TITLE
【更新】pac代理时出现代理失败，切换成http代理时恢复：求问系统代理类型http和pac区别和原理

### ISSUE THREAD

**Issue by Elucidator-xrb** [Fndroid/clash_for_windows_pkg#2167]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
windows 10
v 0.17.1

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
调整“代理类型“为”pac“，并添加了pac内容，一开始可以正常使用代理。然而某时段再次使用时，代理失效（即google用不了翻墙失败）持续到我写这段issue仍是如此；切回http代理（也添加过绕过域名/网段 bypass内容），又可以正常代理。因而感到困惑。
![image](https://user-images.githubusercontent.com/70893377/130612291-1d5d3d1e-ae75-4e6e-a56a-baba8cb7c807.png)

· 想知道为何pac代理会出现这种问题。
· 想知道http代理和pac代理的区别和原理。
· 想知道相关知识哪里会有较为系统的介绍，或者相关知识的名称。（只检索到零碎pac代理文件相关内容）
本人初涉网络，没有相关知识，一般的检索方法似乎找不到相关知识介绍和问题处理方式，因而在此求助

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'设置'（setting）
2. 在'系统代理'（system proxy）切换pac和http模式，查看代理是否生效

**预期行为**

[//]: # (清晰地描述期望看到的行为)
pac模式无法成功代理

**日志**

[//]: # (上传触发问题对应的日志文件)
好像这东西也没有什么日志的样子

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/70893377/130612614-bfb43209-0579-4c6f-8afb-5a1faded1b2d.png)
pac模式状况，节点无问题

![image](https://user-images.githubusercontent.com/70893377/130612879-5121562a-abe7-4056-ae93-0d6acfd11f60.png)
pac文件添加内容

**其他说明**

[//]: # (其他补充内容)
其实主要还是想寻求相关门径的知识~

**Comment by yi-Xu-0100** [comment]
pac模式，代理失败，没有日志，是没进cfw吧。

**Comment by Elucidator-xrb** [comment]
@yi-Xu-0100 似乎确实如您所说。我注释掉第一行，该地址却仍可以访问（以往代理时是不行的），所以说没有在执行FindProxyForURL（没进cfw？）。那应该怎么办呢，是哪里设置需要修改吗？其他地方看上去都往常一样
![image](https://user-images.githubusercontent.com/70893377/130751103-5c2bdf4c-16e9-4a1d-ae7e-2c50a91cb8ea.png)

**Comment by yi-Xu-0100** [comment]
@Elucidator-xrb 系统设置看看 pac 地址

**Comment by Elucidator-xrb** [comment]
@yi-Xu-0100 啊谢谢！！我好像终于理解什么是pac地址了，所以是云端有这么个pac文件，然后本地通过设置“代理”去使用这个文件嘛？
pac地址：“http://127.0.0.1:56897/pac?t=1629884915998”
![image](https://user-images.githubusercontent.com/70893377/130767905-2d2b1492-f9e3-4dc3-b0c1-97eef06c90f8.png)
把使用设置脚本打开之后就可以正常代理了。。
![image](https://user-images.githubusercontent.com/70893377/130768079-c5738709-5a94-448d-9b92-7d706c96ee51.png)
所以是：http模式对应“手动设置代理”，pac模式对应“自动设置代理” 咯？我在cfw里选其中一个模式，会自动关闭另一个模式对应的代理。。

问题大致上解决了，但是用pac文件的时候，google似乎还是没代理上的样子，是缺少什么内容吗？

**Comment by yi-Xu-0100** [comment]
@Elucidator-xrb 日志呢？如果进 CFW 没有代理成功，有日志的。

如果没进 CFW 的话，检查你的 pac 地址能否访问，还有重新打开这个设置项看看有没有被其他软件重置了。

**Comment by Elucidator-xrb** [comment]
@yi-Xu-0100  啊我武断了。goole不能用就是没代理失败（一直以为github被墙了的）现在的状况如下
①cfw开http代理，代理成功，有日志，代理项中”手动设置代理“打开：
<img width="1064" alt="http代理" src="https://user-images.githubusercontent.com/70893377/130793398-2e0f9900-406f-489d-a4c9-de67458cc7de.png">

②cfw开pac代理，代理失败，无日志，代理项中“使用设置脚本”打开：
<img width="1078" alt="pac代理" src="https://user-images.githubusercontent.com/70893377/130793898-7ee9fb72-3b40-47df-9fde-f2d1f5c62ba5.png">

chrome里输入pac文件地址的话，会下载pac到本地，文本编辑器打开就是那个FindProxyForURL函数，不知道这算不算“可以访问”； （设置项应该就是cfw改的。）这会是cfw自身的问题吗？麻烦您了

**Comment by yi-Xu-0100** [comment]
@Elucidator-xrb 你下载的pac脚本中的 mixed-port 是否已经替换为你的代理的端口。在无痕浏览器中访问google，去除插件的影响，看看是否还是无日志。

**Comment by Elucidator-xrb** [comment]
@yi-Xu-0100  mixed-port已替换，就是127.0.0.1:7890 ; 无痕访问依旧无日志
![image](https://user-images.githubusercontent.com/70893377/130800453-26f9cd0c-1a6f-4195-a65b-91936f5f034c.png)

**Comment by yi-Xu-0100** [comment]
@Elucidator-xrb 建议点击 左下connected打开日志看看。
