### ISSUE TITLE
如何在Linux系统中实现开机自启？

### ISSUE THREAD

**Issue by fantasysee** [Fndroid/clash_for_windows_pkg#2168]
[//]: # (如不按模版填写，则issue将被直接关闭)

**勾选 Start with Linux 后启动系统无法自动启动clash**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # 
系统：Ubuntu 18.04 LTS。

**描述**

[//]: # 
勾选 Start with Linux 后启动系统无法自动启动clash

**Comment by Fndroid** [comment]
这个貌似是因为electron的API不支持，所以开关没有效果

**Comment by fantasysee** [comment]
噢这样子，感谢作者解答！

**Comment by xq114** [comment]
Start with linux功能0.17.1版在我的Debian 11上可用，但更新到0.17.3发现这个功能没了？请求作者不要移除这个功能，这个功能非常好用

**Comment by xq114** [comment]
在ubuntu上提示此功能不可用也行啊

**Comment by Fndroid** [comment]
暂时先恢复这个选项显示 @xq114

**Comment by sr1canskhsia** [comment]
绝大多数Linux桌面环境的开机启动都遵循[XDG Autostart规范](https://specifications.freedesktop.org/autostart-spec/autostart-spec-latest.html)，可以参考同为electron应用的bitwarden是[如何实现](https://github.com/bitwarden/desktop/blob/3aa171a66463f32f1d17cead8864b4c66696b082/src/main/messaging.main.ts#L106-L139)的

**Comment by Fndroid** [comment]
@sr1canskhsia 感谢👍
