### ISSUE TITLE
电脑关机后开机，添加的规则profiles会被重置

### ISSUE THREAD

**Issue by dreamstation625** [Fndroid/clash_for_windows_pkg#2169]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**windows10 21H1 内部版本号19043.1165

[//]: # (平台及版本号)

**描述**关机前，已手动退出clash（未关系统代理，右键任务栏的图标退出），第二天开机后，自己添加的规则被重置。

[//]: # (请具体并清楚地描述遇到的问题)

**复现**目前发现的是重启系统会重置

[//]: # (请描述复现问题的步骤)

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
用 parser ，文档： https://docs.cfw.lbyczf.com/contents/parser.html

**Comment by dreamstation625** [comment]
好的，谢谢，我试试

**Comment by dreamstation625** [comment]
已解决，感谢
