### ISSUE TITLE
无法导入配置和订阅链接

### ISSUE THREAD

**Issue by tauyyy** [Fndroid/clash_for_windows_pkg#2175]
从某网站获得的节点经过转换后导入Clash客户端失败，请大佬看看是什么问题？是不支持还是我操作不当？谢谢！
https://pub-api-1.bianyuan.xyz/sub?target=clash&url=proxies%3A%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22144.48.38.21%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A43893%2C%22password%22%3A%22YyCBeDdYX4cadHpCkkmdJLq8%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22185.124.240.169%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A33992%2C%22password%22%3A%228n6pwAcrrv2pj6tFY2p3TbQ6%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22199.10.64.133%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A39772%2C%22password%22%3A%22CUndSZnYsPKcu6Kj8THVMBHD%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22209.216.92.5%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A37588%2C%22password%22%3A%22kD9vkjnE6dsUzwQfvKkPkQAd%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22209.216.92.3%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A35294%2C%22password%22%3A%22J9Y2ncrdPEC38gwydNFFGBna%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22198.147.22.87%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A34815%2C%22password%22%3A%22LkFAzkzXkSCRYa2CsRdL8cGb%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22209.216.92.3%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A37588%2C%22password%22%3A%22kD9vkjnE6dsUzwQfvKkPkQAd%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22207.244.84.58%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A33992%2C%22password%22%3A%228n6pwAcrrv2pj6tFY2p3TbQ6%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22198.147.22.87%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A31757%2C%22password%22%3A%22wj7nDCuNARchSeKNCN8VFK62%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%2245.89.173.205%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A33992%2C%22password%22%3A%228n6pwAcrrv2pj6tFY2p3TbQ6%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%2245.89.173.205%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A39772%2C%22password%22%3A%22CUndSZnYsPKcu6Kj8THVMBHD%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%2245.89.173.205%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A33998%2C%22password%22%3A%22NHwQTPLCfaTMSqTnU3mjcSxe%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22143.244.60.162%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A39772%2C%22password%22%3A%22CUndSZnYsPKcu6Kj8THVMBHD%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22143.244.60.164%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A33992%2C%22password%22%3A%228n6pwAcrrv2pj6tFY2p3TbQ6%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22143.244.60.172%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A39772%2C%22password%22%3A%22CUndSZnYsPKcu6Kj8THVMBHD%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22154.16.171.213%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A31572%2C%22password%22%3A%22n8w4StnbVD9dmXYn4Ajt87EA%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22154.16.171.213%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A39772%2C%22password%22%3A%22CUndSZnYsPKcu6Kj8THVMBHD%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22156.146.33.79%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A39772%2C%22password%22%3A%22CUndSZnYsPKcu6Kj8THVMBHD%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22173.237.207.30%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A31572%2C%22password%22%3A%22n8w4StnbVD9dmXYn4Ajt87EA%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22185.102.217.161%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A39772%2C%22password%22%3A%22CUndSZnYsPKcu6Kj8THVMBHD%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22185.134.23.40%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A39772%2C%22password%22%3A%22CUndSZnYsPKcu6Kj8THVMBHD%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22185.134.23.40%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A33998%2C%22password%22%3A%22NHwQTPLCfaTMSqTnU3mjcSxe%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%2237.120.221.5%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A33992%2C%22password%22%3A%228n6pwAcrrv2pj6tFY2p3TbQ6%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%2237.120.221.5%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A31944%2C%22password%22%3A%22aYNeKDMzYQYw4KbUbJA8Wszq%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22193.29.107.125%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A39772%2C%22password%22%3A%22CUndSZnYsPKcu6Kj8THVMBHD%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22193.29.107.91%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A39772%2C%22password%22%3A%22CUndSZnYsPKcu6Kj8THVMBHD%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22188.92.78.145%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A35294%2C%22password%22%3A%22J9Y2ncrdPEC38gwydNFFGBna%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22188.92.78.145%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A31944%2C%22password%22%3A%22aYNeKDMzYQYw4KbUbJA8Wszq%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22188.92.78.145%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A40093%2C%22password%22%3A%22x23Z4LGkGDkThZ9Kaz4DURQp%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22188.92.78.145%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A39772%2C%22password%22%3A%22CUndSZnYsPKcu6Kj8THVMBHD%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22188.92.78.145%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A33992%2C%22password%22%3A%228n6pwAcrrv2pj6tFY2p3TbQ6%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22185.153.150.63%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A40093%2C%22password%22%3A%22x23Z4LGkGDkThZ9Kaz4DURQp%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%222.58.46.5%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A39772%2C%22password%22%3A%22CUndSZnYsPKcu6Kj8THVMBHD%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%222.58.46.3%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A39772%2C%22password%22%3A%22CUndSZnYsPKcu6Kj8THVMBHD%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%2237.120.221.5%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A39772%2C%22password%22%3A%22CUndSZnYsPKcu6Kj8THVMBHD%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%225.157.13.101%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A31572%2C%22password%22%3A%22n8w4StnbVD9dmXYn4Ajt87EA%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22198.147.22.87%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A33148%2C%22password%22%3A%22CMduaFXddcQbwNAAs7xFDnc8%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%2237.120.221.5%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A31572%2C%22password%22%3A%22n8w4StnbVD9dmXYn4Ajt87EA%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%2237.120.221.5%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A31764%2C%22password%22%3A%22YgusH2MWA8PWc3p2VDsR7AVv%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%2237.120.221.5%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A37473%2C%22password%22%3A%22enctdKyJfSu76VqznKwTt6Ap%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%2289.187.168.49%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A39772%2C%22password%22%3A%22CUndSZnYsPKcu6Kj8THVMBHD%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%2231.171.153.163%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A39772%2C%22password%22%3A%22CUndSZnYsPKcu6Kj8THVMBHD%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22193.29.107.99%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A39772%2C%22password%22%3A%22CUndSZnYsPKcu6Kj8THVMBHD%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%2237.120.194.109%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A39772%2C%22password%22%3A%22CUndSZnYsPKcu6Kj8THVMBHD%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22193.29.107.117%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A39772%2C%22password%22%3A%22CUndSZnYsPKcu6Kj8THVMBHD%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%225.157.13.99%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A37588%2C%22password%22%3A%22kD9vkjnE6dsUzwQfvKkPkQAd%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%2237.120.221.5%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A35294%2C%22password%22%3A%22J9Y2ncrdPEC38gwydNFFGBna%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%2231.171.154.219%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A33992%2C%22password%22%3A%228n6pwAcrrv2pj6tFY2p3TbQ6%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22207.244.67.149%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A40093%2C%22udp%22%3Atrue%2C%22password%22%3A%22x23Z4LGkGDkThZ9Kaz4DURQp%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22207.244.67.149%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A35294%2C%22udp%22%3Atrue%2C%22password%22%3A%22J9Y2ncrdPEC38gwydNFFGBna%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22212.102.44.83%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A35294%2C%22udp%22%3Atrue%2C%22password%22%3A%22J9Y2ncrdPEC38gwydNFFGBna%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22212.102.44.83%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A31944%2C%22udp%22%3Atrue%2C%22password%22%3A%22aYNeKDMzYQYw4KbUbJA8Wszq%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%2284.17.35.78%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A33992%2C%22udp%22%3Atrue%2C%22password%22%3A%228n6pwAcrrv2pj6tFY2p3TbQ6%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%2291.90.123.115%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A45329%2C%22udp%22%3Atrue%2C%22password%22%3A%22CXSjgD7u7Ar7GxkZ4CgTMUsj%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22144.48.38.21%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A48938%2C%22password%22%3A%224ejJ8n5ddLuYDUHGXJre2ufJ%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22144.48.38.21%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A49396%2C%22password%22%3A%22BdRWC38L5JUDMTYNNxJGcUwB%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22144.48.38.19%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A48938%2C%22password%22%3A%224ejJ8n5ddLuYDUHGXJre2ufJ%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22144.48.38.183%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A49396%2C%22password%22%3A%22BdRWC38L5JUDMTYNNxJGcUwB%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22144.48.38.19%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A49396%2C%22password%22%3A%22BdRWC38L5JUDMTYNNxJGcUwB%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22103.192.80.133%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A43893%2C%22password%22%3A%22YyCBeDdYX4cadHpCkkmdJLq8%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22144.48.38.19%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A43893%2C%22password%22%3A%22YyCBeDdYX4cadHpCkkmdJLq8%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22144.48.38.19%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A49339%2C%22password%22%3A%22suucSeVLmt6PQKAP77NtGw9x%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%2291.206.168.50%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A48938%2C%22password%22%3A%224ejJ8n5ddLuYDUHGXJre2ufJ%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%2245.248.78.45%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A50168%2C%22password%22%3A%22WCuz7yrfZSCQQXSNrtGPz2HT%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22138.199.19.132%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A50168%2C%22password%22%3A%22WCuz7yrfZSCQQXSNrtGPz2HT%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%2286.106.90.43%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A50168%2C%22password%22%3A%22WCuz7yrfZSCQQXSNrtGPz2HT%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%2282.102.26.117%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A50695%2C%22password%22%3A%22gqtwGu9bVreJqL3FTHSVKGzy%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22143.244.57.99%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A41738%2C%22password%22%3A%22X6yMGXnfUsuKTvEDYZSLPk4d%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22185.252.222.99%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A50168%2C%22password%22%3A%22WCuz7yrfZSCQQXSNrtGPz2HT%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22185.252.223.85%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A50168%2C%22password%22%3A%22WCuz7yrfZSCQQXSNrtGPz2HT%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D%7C-%20%7B%22name%22%3A%22%22%2C%22server%22%3A%22152.89.160.59%22%2C%22type%22%3A%22ss%22%2C%22port%22%3A50168%2C%22password%22%3A%22WCuz7yrfZSCQQXSNrtGPz2HT%22%2C%22cipher%22%3A%22aes-256-gcm%22%7D&insert=false

**Comment by Fndroid** [comment]
格式问题
