### ISSUE TITLE
能不能加个清空按钮？

### ISSUE THREAD

**Issue by tauyyy** [Fndroid/clash_for_windows_pkg#2176]
我不知道如何清空这个输入框里面的链接，感觉很麻烦，好像只有退出客户端才能自动清空？能不能在右边加个清空按钮？

https://i.imgur.com/lAf4faE.png

**Comment by tauyyy** [comment]
> 退格？试试

如果文本很多，要退到什么时候？

**Comment by yi-Xu-0100** [comment]
@tauyyy ctrl+A 试试

**Comment by tauyyy** [comment]
> @yi-Xu-0100  ctrl+A 也没有一键清空来得方便啊







> @tauyyy ctrl+A 试试

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases

**Comment by tauyyy** [comment]
> fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases

大大真是动作迅速，谢谢！
