### ISSUE TITLE
定位按钮图标显示问题

### ISSUE THREAD

**Issue by nxyd** [Fndroid/clash_for_windows_pkg#2178]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
在暗色主题下图标显示有问题

**复现**

[//]: # (请描述复现问题的步骤)

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/3884211/131122094-9aebd192-62ce-459a-8588-70ac42eff6ef.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by salzburgrujvnun** [comment]
定位按钮具体怎么用？为什么点击却没有任何反应，使用场景是什么？

**Comment by yi-Xu-0100** [comment]
@salzburgrujvnun 定位到你选择的代理上。

**Comment by salzburgrujvnun** [comment]
为什么没有反应？第一个组是手动，第二组是自动，都没有定位反应。

![jRowW33C0w](https://user-images.githubusercontent.com/79001470/131471354-c0884eda-3784-48ce-8473-dff5dd327be8.gif)

**Comment by yi-Xu-0100** [comment]
@salzburgrujvnun 需要很多，存在滚动状态，很少的话，没有滚动。直接就在这一页了。

**Comment by nxyd** [comment]
已解决

**Comment by chensrnile** [comment]
之前还奇怪呢^^
