### ISSUE TITLE
关闭后，系统代理还依旧运行。

### ISSUE THREAD

**Issue by hyy34** [Fndroid/clash_for_windows_pkg#218]
windows10，软件启动，关闭后，我怎么系统的vpn不会自动关闭？导致无法上网。

**Comment by Fndroid** [comment]
关闭系统代理需要右键点击任务栏图标，选择Exit

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
