### ISSUE TITLE
无法打开System Proxy：系统代理开关 #2183

### ISSUE THREAD

**Issue by qumingnan24** [Fndroid/clash_for_windows_pkg#2185]
信息：
无法开启SystemProxy
表现为点击无反应，并非开启之后自动关闭。

已在#1105和#1009所提供方法尝试并未解决

[x]: # ？？
- [ ] 已经阅读过[文档]相关问题，并未找到解决办法
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

系统：win10

版本号：0.17.2

描述：
无法开启System Proxy
触发问题之后重启、重置LSP、卸载重装cfw之后皆无法打开。
进入带网络连接的安全模式启动clash点击System Proxy的按钮也毫无反应

日志: 点击系统代理按钮后毫无反应，也并未触发bug类信息

**Comment by yi-Xu-0100** [comment]
看看 #312

**Comment by qumingnan24** [comment]
谢谢已经解决，原因是因为在白名单中添加了一行错误写法的主机名

**Comment by AkaSakana** [comment]
感谢！原因同楼内

**Comment by 46516044** [comment]
感谢！原因同楼内

**Comment by omymenzies** [comment]
> > > 不用那么复杂！我也出现了这个问题，最后是发现自己设置的bypass的问题，有个地址后面加多了一个“/”反斜杠，导致那个按钮按不了了。
> > 
> > 
> > 老哥说清楚点，不懂啊
> 
> 我遇到三种情况，基本是看着这个issue解决的，总结如下：
> 
> 1. 打开后自动关闭就是系统代理寄存器被其他程序修改了，解决过程参考上面利用 `process monitor` 先找到是哪个程序干的再具体解决
> 2. 点击打开无效遇到了两种
> 
> * clash法自动设置系统代理寄存器，可能是自动设置服务未开。这个我实际没有解决，但是可以在使用时手动开关 `Windows设置` -> `网络和internet` -> `代理` -> `使用代理服务器`
> * bypass设置出现不符合规范语法（现在不能使用带 `\` 的像 `bing.com/work` ，以及 `.cn` 这样的语法，可以直接用 `bing.com` 和 `cn` ）这个真的很奇怪，之前是可以的。
这个方法管用

**Comment by omymenzies** [comment]
> > > 不用那么复杂！我也出现了这个问题，最后是发现自己设置的bypass的问题，有个地址后面加多了一个“/”反斜杠，导致那个按钮按不了了。
> > 
> > 
> > 老哥说清楚点，不懂啊
> 
> 我遇到三种情况，基本是看着这个issue解决的，总结如下：
> 
> 1. 打开后自动关闭就是系统代理寄存器被其他程序修改了，解决过程参考上面利用 `process monitor` 先找到是哪个程序干的再具体解决
> 2. 点击打开无效遇到了两种
> 
> * clash法自动设置系统代理寄存器，可能是自动设置服务未开。这个我实际没有解决，但是可以在使用时手动开关 `Windows设置` -> `网络和internet` -> `代理` -> `使用代理服务器`
> * bypass设置出现不符合规范语法（现在不能使用带 `\` 的像 `bing.com/work` ，以及 `.cn` 这样的语法，可以直接用 `bing.com` 和 `cn` ）这个真的很奇怪，之前是可以的。
这个方法管用

**Comment by omymenzies** [comment]
> > > 不用那么复杂！我也出现了这个问题，最后是发现自己设置的bypass的问题，有个地址后面加多了一个“/”反斜杠，导致那个按钮按不了了。
> > 
> > 
> > 老哥说清楚点，不懂啊
> 
> 我遇到三种情况，基本是看着这个issue解决的，总结如下：
> 
> 1. 打开后自动关闭就是系统代理寄存器被其他程序修改了，解决过程参考上面利用 `process monitor` 先找到是哪个程序干的再具体解决
> 2. 点击打开无效遇到了两种
> 
> * clash法自动设置系统代理寄存器，可能是自动设置服务未开。这个我实际没有解决，但是可以在使用时手动开关 `Windows设置` -> `网络和internet` -> `代理` -> `使用代理服务器`
> * bypass设置出现不符合规范语法（现在不能使用带 `\` 的像 `bing.com/work` ，以及 `.cn` 这样的语法，可以直接用 `bing.com` 和 `cn` ）这个真的很奇怪，之前是可以的。

这个方法管用
