### ISSUE TITLE
Clash请求超时时间配置

### ISSUE THREAD

**Issue by linmii** [Fndroid/clash_for_windows_pkg#2186]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

 Windows10 2020H2 10.0.19042.1165

**描述**
*有下载Clash汉化包替换文件*

 调用服务器的一个导出接口，下载excel，开启Clash的时候，到10s请求就超时断开了，退出Clash后，能够请求完成下载(25s左右)。看请求日志这个是直连，没有走代理，所以10s超时这个是Clash内部的一直超时时间控制吗？是否可以通过配置文件修改这个超时时间？
![image](https://user-images.githubusercontent.com/17309471/131482389-cb1488f5-6ec0-4ed7-a64d-59db06362219.png)
![image](https://user-images.githubusercontent.com/17309471/131482521-e69dd064-1e4b-4602-a784-e93e06726c83.png)

**Comment by yi-Xu-0100** [comment]
1. 修改文件后，不建议发issue。
2. 下载文件的话，我下载过很长时间没问题，可以试着加 bypass 解决 或者 pac 试试。

**Comment by komorebi64** [comment]
我也遇到了这个问题，调用一个外网接口，超过10秒就报错502了

**Comment by oldstar1** [comment]
醉了 最近好多节点都超时
