### ISSUE TITLE
开机后clash自启但会以窗口化启动

### ISSUE THREAD

**Issue by shangguan6636** [Fndroid/clash_for_windows_pkg#2187]
![clash](https://user-images.githubusercontent.com/44657091/131600825-39dac69b-8ed4-4e1f-957d-3af07cd29eee.PNG)
每次开机clash会以窗口化运行，不会必须手动关闭窗口

**Comment by yi-Xu-0100** [comment]
#2151

**Comment by shangguan6636** [comment]
啊，我的脑残issues
