### ISSUE TITLE
两个问题请教

### ISSUE THREAD

**Issue by hackenfu** [Fndroid/clash_for_windows_pkg#2192]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # Win10

**描述**

[//]: # 1、请教：开启TUN之后，电脑的DNS应该设为什么？114这样的外部IP，还是198.18.0.1？我是redir模式
2、在dashboard中，有两个地址，一个是172.0.0.1，一个是198.18.0.1，前者连接类型全是HTTP或者HTTP CONNECT，后者全是TUN，这正常吗？我用Linux搭建旁路由的时候，不管设备IP还是198.18.0.1，全是TUN。不知道问题出在哪里？

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
1. https://docs.cfw.lbyczf.com/contents/tun.html
2. 那个是发起地址好像，HTTP的话，是系统代理吧，所以是本地的 127.0.0.1 ，tun 的话，接管网卡的，所以是 198.18.0.1。只会简单解答，其他不知。

**Comment by hackenfu** [comment]
> 1. https://docs.cfw.lbyczf.com/contents/tun.html
> 2. 那个是发起地址好像，HTTP的话，是系统代理吧，所以是本地的 127.0.0.1 ，tun 的话，接管网卡的，所以是 198.18.0.1。只会简单解答，其他不知。

谢谢解答。您说的第一个链接我之前都仔细读过，我意思是电脑网络适配器里设置网关和DNS的那个DNS应该设为什么，链接里似乎没提到

**Comment by yi-Xu-0100** [comment]
@hackenfu 没提到，就不用管，按默认的就行

**Comment by hackenfu** [comment]
> 1. https://docs.cfw.lbyczf.com/contents/tun.html
> 2. 那个是发起地址好像，HTTP的话，是系统代理吧，所以是本地的 127.0.0.1 ，tun 的话，接管网卡的，所以是 198.18.0.1。只会简单解答，其他不知。

顺着你”系统代理“的思路，我猜测是不是因为勾选了”system proxy“，果然取消勾选后，全是TUN了，破案了，感谢！
第一题我暂时先用114这样的外部DNS，使用没啥问题
