### ISSUE TITLE
uplay无法登录

### ISSUE THREAD

**Issue by Emt-lin** [Fndroid/clash_for_windows_pkg#2198]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 10 Version 20H2

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
uplay无法登录。
只要一启动，开启了 `System Proxy`，就会显示如下面截图所示。不管有没有 `Profiles` 都一样。
当只要关闭软件或者关闭 `System Proxy`，就又可以正常登录。
在开启代理的情况下，不管是将其域名加到 `Proxy` 规则还是 `Direct` 规则，一样不能登录。
补充一下：以前版本都没出现这个问题的，是最近几个版本出现的。

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/41323133/132083539-57489235-000e-4ea2-88c9-2e713012e8e3.png)

**其他说明**

[//]: # (其他补充内容)
不知道是不是自己的问题！！！

**Comment by lcysyx** [comment]
+1
只有关闭代理用TUN模式才能正常登录

**Comment by yi-Xu-0100** [comment]
@Emt-lin 试试全局模式；试试使用 pac；试试开启 special protocol

**Comment by a57892** [comment]
> @Emt-lin 试试全局模式；试试使用 pac；试试开启 special protocol

都试过了，还是一样无法连接。

**Comment by Emt-lin** [comment]
> @Emt-lin 试试全局模式；试试使用 pac；试试开启 special protocol

只要打开软件，开启 `System Proxy`，就不行了，direct、pac、global都是一样不行

**Comment by yi-Xu-0100** [comment]
@Emt-lin emmm，bypass 掉吧

**Comment by a57892** [comment]
> @Emt-lin emmm，bypass 掉吧

早试过了。唯一可行的就是关掉代理。

**Comment by yi-Xu-0100** [comment]
@a57892 bypass 的话，就是不走代理，可能你的规则不全。

**Comment by a57892** [comment]
> @a57892 bypass 的话，就是不走代理，可能你的规则不全。

Be my guest 请您试试

**Comment by Fndroid** [comment]
看起来就是ubiconnect没有用系统API做网络请求，自己读了代理设置以至于bypass也不生效

**Comment by Azrael2233** [comment]
我也是有同样的问题 还以为是机场的规则写错了。。。

**Comment by Emt-lin** [comment]
@Fndroid 老哥，这个问题有解决方式吗？

**Comment by Ma1otru** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/2073#issuecomment-887773201
你再看看没有相关答案？

**Comment by Emt-lin** [comment]
@Ma1otru 好像没完全解决 -_-

**Comment by XueTeng2** [comment]
遇到了同样的问题，每次登陆Uplay都要关掉Clash

**Comment by chensrnile** [comment]
不用关代理啊  再开个加速器就好了

**Comment by Emt-lin** [comment]
@chensrnile 不行，开的 UU，还是不行。必须关代理

**Comment by chensrnile** [comment]
我开的奇妙  可以的  或者你试试关掉再打开clash试一下

**Comment by Erdrian** [comment]
+1，另外还有win11下的microso store也有这个问题

**Comment by chensrnile** [comment]
> +1，另外还有win11下的microso store也有这个问题

改过 UWP Loopback吗

**Comment by liruishan1995** [comment]
一样的问题

**Comment by taotao913** [comment]
我（只会用软件的小白）来补充一下，虽然pac模式可以做到代理uplay，但存在以下几种情况：
1.pac单独设置SOCKS5 127.0.0.1:%mixed-port%；可正常打开uplay，但无法打开win10商店+一些只支持http的软件
2.pac单独设置PROXY 127.0.0.1:%mixed-port%；可正常打开win10商店+一些只支持http的软件，但无法打开uplay
3.pac设置PROXY 127.0.0.1:%mixed-port%;；SOCKS5 127.0.0.1:%mixed-port%；可正常打开win10商店+一些只支持http的软件，但无法打开uplay
4.pac设置SOCKS5 127.0.0.1:%mixed-port%；PROXY 127.0.0.1:%mixed-port%;；可正常打开uplay+win10商店，但无法打开一些只支持http链接的软件

楼上那种不是完全解决的办法（分享出来也挺好）就别拿来说事了...综上，这问题怪就怪uplay只支持sock5代理？

ps：一些只支持http的软件指的是一些小众开发软件，比如在CE基础上做的单机游戏修改器联网下载配置

**Comment by yi-Xu-0100** [comment]
@taotao913 可以使用 pac 的匹配功能，只给 uplay 相关的送 SOCKS5 就行。


下面是个人修改 https://github.com/Fndroid/clash_for_windows_pkg/issues/2073#issuecomment-887773201 后的使用版本，简陋代码，仅供参考。

```js
function FindProxyForURL(url, host) {
  if (
    dnsDomainIs(host, "ubisoft.com") ||
    shExpMatch(host, "(*.ubisoft.com|ubisoft.com|ubisoft)") ||
    dnsDomainIs(host, "ubi.com") ||
    shExpMatch(host, "(*.ubi.com|ubi.com)") ||
    dnsDomainIs(host, "akamaihd.net") ||
    shExpMatch(host, "(*.akamaihd.net|akamaihd.net)")
  )
    return "SOCKS5 127.0.0.1:%mixed-port%;DIRECT";

  if (
    isPlainHostName(host) ||
    shExpMatch(host, "*.local") ||
    isInNet(host, "10.0.0.0", "255.0.0.0") ||
    isInNet(host, "127.0.0.0", "255.0.0.0") ||
    isInNet(host, "172.16.0.0", "255.240.0.0") ||
    isInNet(host, "192.168.0.0", "255.255.0.0") ||
    isInNet(dnsResolve(host), "10.0.0.0", "255.0.0.0") ||
    isInNet(dnsResolve(host), "127.0.0.0", "255.0.0.0") ||
    isInNet(dnsResolve(host), "172.16.0.0", "255.240.0.0") ||
    isInNet(dnsResolve(host), "192.168.0.0", "255.255.0.0")
  ) {
    return "DIRECT";
  } else {
    return "PROXY 127.0.0.1:%mixed-port%";
  }
}

```

**Comment by Emt-lin** [comment]
@yi-Xu-0100 下午试一试

**Comment by lvhe19880210** [comment]
> @taotao913 可以使用 pac 的匹配功能，只给 uplay 相关的送 SOCKS5 就行。
> 
> 下面是个人修改 [#2073 (comment)](https://github.com/Fndroid/clash_for_windows_pkg/issues/2073#issuecomment-887773201) 后的使用版本，简陋代码，仅供参考。
> 
> ```js
> function FindProxyForURL(url, host) {
>   if (
>     dnsDomainIs(host, "ubisoft.com") ||
>     shExpMatch(host, "(*.ubisoft.com|ubisoft.com|ubisoft)") ||
>     dnsDomainIs(host, "ubi.com") ||
>     shExpMatch(host, "(*.ubi.com|ubi.com)") ||
>     dnsDomainIs(host, "akamaihd.net") ||
>     shExpMatch(host, "(*.akamaihd.net|akamaihd.net)")
>   )
>     return "SOCKS5 127.0.0.1:%mixed-port%;DIRECT";
> 
>   if (
>     isPlainHostName(host) ||
>     shExpMatch(host, "*.local") ||
>     isInNet(host, "10.0.0.0", "255.0.0.0") ||
>     isInNet(host, "127.0.0.0", "255.0.0.0") ||
>     isInNet(host, "172.16.0.0", "255.240.0.0") ||
>     isInNet(host, "192.168.0.0", "255.255.0.0") ||
>     isInNet(dnsResolve(host), "10.0.0.0", "255.0.0.0") ||
>     isInNet(dnsResolve(host), "127.0.0.0", "255.0.0.0") ||
>     isInNet(dnsResolve(host), "172.16.0.0", "255.240.0.0") ||
>     isInNet(dnsResolve(host), "192.168.0.0", "255.255.0.0")
>   ) {
>     return "DIRECT";
>   } else {
>     return "PROXY 127.0.0.1:%mixed-port%";
>   }
> }
> ```
> 
> 上述代码，个人测试下，uplay + win10 商店都能打开，暂无单机游戏修改器。。。
试了试 挺好 另外我这16.1版本测试http代理模式ok 没问题不用开pac 不知道是从哪个版本开始不行的

**Comment by taotao913** [comment]
> @taotao913 可以使用 pac 的匹配功能，只给 uplay 相关的送 SOCKS5 就行。
> 
> 下面是个人修改 [#2073 (comment)](https://github.com/Fndroid/clash_for_windows_pkg/issues/2073#issuecomment-887773201) 后的使用版本，简陋代码，仅供参考。
> 
> ```js
> function FindProxyForURL(url, host) {
>   if (
>     dnsDomainIs(host, "ubisoft.com") ||
>     shExpMatch(host, "(*.ubisoft.com|ubisoft.com|ubisoft)") ||
>     dnsDomainIs(host, "ubi.com") ||
>     shExpMatch(host, "(*.ubi.com|ubi.com)") ||
>     dnsDomainIs(host, "akamaihd.net") ||
>     shExpMatch(host, "(*.akamaihd.net|akamaihd.net)")
>   )
>     return "SOCKS5 127.0.0.1:%mixed-port%;DIRECT";
> 
>   if (
>     isPlainHostName(host) ||
>     shExpMatch(host, "*.local") ||
>     isInNet(host, "10.0.0.0", "255.0.0.0") ||
>     isInNet(host, "127.0.0.0", "255.0.0.0") ||
>     isInNet(host, "172.16.0.0", "255.240.0.0") ||
>     isInNet(host, "192.168.0.0", "255.255.0.0") ||
>     isInNet(dnsResolve(host), "10.0.0.0", "255.0.0.0") ||
>     isInNet(dnsResolve(host), "127.0.0.0", "255.0.0.0") ||
>     isInNet(dnsResolve(host), "172.16.0.0", "255.240.0.0") ||
>     isInNet(dnsResolve(host), "192.168.0.0", "255.255.0.0")
>   ) {
>     return "DIRECT";
>   } else {
>     return "PROXY 127.0.0.1:%mixed-port%";
>   }
> }
> ```
> 
> 上述代码，个人测试下，uplay + win10 商店都能打开，暂无单机游戏修改器。。。

好使👍看了这个规则，我懂了（懂王），如果有其他适配不好的软件，我自己抓下它的域名，让它走规则就好了！感谢~

**Comment by Emt-lin** [comment]
@taotao913 老哥，这段 js 代码应该加到哪里？没找到位置（-_-）

**Comment by taotao913** [comment]
> @taotao913 老哥，这段 js 代码应该加到哪里？没找到位置（-_-）

settings-system proxy-type（pac）-pac content，全选-复制粘贴上面老哥的内容，用下来感觉兼容性很好

**Comment by Emt-lin** [comment]
@taotao913 感谢老哥

**Comment by Ma1otru** [comment]
> 这个问题在下次clash核心更新时会修复

支持正义更新！

**Comment by pinacoladae** [comment]
> @yi-Xu-0100 下午试一试



> @taotao913 可以使用 pac 的匹配功能，只给 uplay 相关的送 SOCKS5 就行。
> 
> 下面是个人修改 [#2073 (comment)](https://github.com/Fndroid/clash_for_windows_pkg/issues/2073#issuecomment-887773201) 后的使用版本，简陋代码，仅供参考。
> 
> ```js
> function FindProxyForURL(url, host) {
>   if (
>     dnsDomainIs(host, "ubisoft.com") ||
>     shExpMatch(host, "(*.ubisoft.com|ubisoft.com|ubisoft)") ||
>     dnsDomainIs(host, "ubi.com") ||
>     shExpMatch(host, "(*.ubi.com|ubi.com)") ||
>     dnsDomainIs(host, "akamaihd.net") ||
>     shExpMatch(host, "(*.akamaihd.net|akamaihd.net)")
>   )
>     return "SOCKS5 127.0.0.1:%mixed-port%;DIRECT";
> 
>   if (
>     isPlainHostName(host) ||
>     shExpMatch(host, "*.local") ||
>     isInNet(host, "10.0.0.0", "255.0.0.0") ||
>     isInNet(host, "127.0.0.0", "255.0.0.0") ||
>     isInNet(host, "172.16.0.0", "255.240.0.0") ||
>     isInNet(host, "192.168.0.0", "255.255.0.0") ||
>     isInNet(dnsResolve(host), "10.0.0.0", "255.0.0.0") ||
>     isInNet(dnsResolve(host), "127.0.0.0", "255.0.0.0") ||
>     isInNet(dnsResolve(host), "172.16.0.0", "255.240.0.0") ||
>     isInNet(dnsResolve(host), "192.168.0.0", "255.255.0.0")
>   ) {
>     return "DIRECT";
>   } else {
>     return "PROXY 127.0.0.1:%mixed-port%";
>   }
> }
> ```
> 
> 上述代码，个人测试下，uplay + win10 商店都能打开，暂无单机游戏修改器。。。

谢谢大佬
