### ISSUE TITLE
proxygroup not found

### ISSUE THREAD

**Issue by holll** [Fndroid/clash_for_windows_pkg#220]
![](http://img02.sogoucdn.com/app/a/100520146/a045ed901f375225e5dbba98c9687ad3)
不知道这个问题出在哪里？恳求开发者或者其他知道这个问题的使用者能帮助我解决这个问题

**Comment by Fndroid** [comment]
就是你策略组里有节点不存在，如果不是你自己写的配置，就去找给你配置的人
