### ISSUE TITLE
dashboard白屏问题

### ISSUE THREAD

**Issue by WellTong** [Fndroid/clash_for_windows_pkg#2200]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
win 10  
0.17.3 

**描述**
node模式production  
GPU面板也是标准的  
用户/appdata和用户/.config都已清空

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**
toggle devtools报错信息
![image](https://user-images.githubusercontent.com/66908950/132133543-4c3b558e-a84b-4a52-be06-3b3d4aa3b869.png)  
![image](https://user-images.githubusercontent.com/66908950/132133754-1a622bd3-ebb5-40b4-a349-25f627d36df3.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/442

看看是不是环境变量问题

**Comment by WellTong** [comment]
> #442
> 
> 看看是不是环境变量问题

不是的、node弄成production了。

**Comment by WellTong** [comment]
> #442
> 
> 看看是不是环境变量问题

ok了 之前开发的时候从系统环境变量配置里面把node改成development了。 CMD里面改完显示的是这个，然后后台又给该回去了
