### ISSUE TITLE
Service Mode安装后没有clash的网卡，而且无法卸载，点击卸载后无反应

### ISSUE THREAD

**Issue by Howlingx** [Fndroid/clash_for_windows_pkg#2205]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Windows 10 20H2
[//]: # (平台及版本号)

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/88699683/132294484-39ffa780-5957-4e4d-b71c-0b1320b53d48.png)
![image](https://user-images.githubusercontent.com/88699683/132294514-181af703-5212-4626-ae1f-f40f9120d599.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
安装service mode后开tun会有clash网卡

**Comment by Howlingx** [comment]
> 安装service mode后开tun会有clash网卡

![image](https://user-images.githubusercontent.com/88699683/132297325-d3bb85a7-b3d4-480b-99c1-a9cafb56912a.png)
![image](https://user-images.githubusercontent.com/88699683/132297361-c1a96e1a-7bd3-413d-9a99-78d7c61a8426.png)
是否这样设置，但是依然没有

**Comment by yi-Xu-0100** [comment]
@Howlingx 缩进错误，在mixin后的要在mixin下一级。

**Comment by Howlingx** [comment]
> @Howlingx 缩进错误，在mixin后的要在mixin下一级。
已解决，谢谢
