### ISSUE TITLE
解压到D盘服务器无法保存

### ISSUE THREAD

**Issue by tauyyy** [Fndroid/clash_for_windows_pkg#2208]
win10系统
4.20最新版
解压到D盘导入的服务器信息无法保存也不能翻墙，界面一片空白。解压到C盘也一样。

**Comment by yi-Xu-0100** [comment]
啥意思？

**Comment by tauyyy** [comment]
> 啥意思？

服务器列表被清空

**Comment by yi-Xu-0100** [comment]
@tauyyy 服务器列表？配置列表吗？什么解压？配置文件还是软件压缩包？啥是4.20最新版？

**Comment by tauyyy** [comment]
> win10系统
> 4.20最新版
> 解压到D盘导入的服务器信息无法保存也不能翻墙，界面一片空白。解压到C盘也一样。



> @tauyyy 服务器列表？配置列表吗？什么解压？配置文件还是软件压缩包？啥是4.20最新版？

发错了，是v2rayN
