### ISSUE TITLE
0.18.0 Windows版右上角关闭按钮无效

### ISSUE THREAD

**Issue by returnL** [Fndroid/clash_for_windows_pkg#2209]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Window 10 21H1, CFW 0.18.0

**描述**
关闭按钮点击无效，最大化和最小化正常。只能暂时通过按`Esc`键退出界面

**复现**

[//]: # (请描述复现问题的步骤)

1. 显示Dashboard
2. 点击右上角'关闭'按钮
3. 主界面未关闭

**预期行为**
点击关闭按钮，界面正常关闭

**截图**
![image](https://user-images.githubusercontent.com/44701395/132794979-62861942-659d-4d6b-a59d-87803989105b.png)

**Comment by moeosu** [comment]
我的关闭按钮也不能用

**Comment by yi-Xu-0100** [comment]
撤包了，等等新的包，🙈
