### ISSUE TITLE
【请教】关于CFW局域网共享给其他设备问题

### ISSUE THREAD

**Issue by xiaochency** [Fndroid/clash_for_windows_pkg#221]
1、之前SSR局域网共享给设备的代理是1080，即其他设备设置代理192.168.XX.XX，端口1080，即能实现共享代理。
2、现在CFW同样操作（已打开Allow LAN），其他设备设置代理192.168.XX.XX，端口7890和7891都试过，依然不行，是端口有变化吗？
望大佬不吝赐教。

**Comment by UntaggedRui** [comment]
我的打开Allow LAN后，在其他设备使用7890端口设置http代理时能够共享CFW的。

**Comment by Fndroid** [comment]
Allow LAN开启后，会将socks5和http端口开在0.0.0.0，如果其他设备无法访问，检查下防火墙

**Comment by Aithosa** [comment]
请问我的allow lan打开后是这些地址，我的笔记本是连接的无线网，那我的代理地址是哪一个?
![2019-10-25 (3)](https://user-images.githubusercontent.com/32020141/67563621-a55a1000-f753-11e9-8e87-da382ea0810e.png)

我尝试过wlan和本地连接2，端口设为7890其他设备都无法正常联网。

另外，请问比如我希望共享给手机，那么我是到手机的无线网设置页面设置吗?就像下面这样？
![Screenshot_2019-10-25-18-19-50-888_com android se](https://user-images.githubusercontent.com/32020141/67563881-3af59f80-f754-11e9-822d-95548c5fc842.jpg)

谢谢！

**Comment by Fndroid** [comment]
> 请问我的allow lan打开后是这些地址，我的笔记本是连接的无线网，那我的代理地址是哪一个?
> ![2019-10-25 (3)](https://user-images.githubusercontent.com/32020141/67563621-a55a1000-f753-11e9-8e87-da382ea0810e.png)
> 
> 我尝试过wlan和本地连接2，端口设为7890其他设备都无法正常联网。
> 
> 另外，请问比如我希望共享给手机，那么我是到手机的无线网设置页面设置吗?就像下面这样？
> ![Screenshot_2019-10-25-18-19-50-888_com android se](https://user-images.githubusercontent.com/32020141/67563881-3af59f80-f754-11e9-822d-95548c5fc842.jpg)
> 
> 谢谢！

两个设备没有连接到同一个局域网

**Comment by Aithosa** [comment]
@Fndroid  您好，这是否意味着要想使用这个功能，电脑和手机要同时连接到我的路由器局域网中，然后再在我的手机网络中找到路由器的网络，进入里边修改代理配置。

或者是我的电脑可以连接外部的无线网，之后分享热点给手机，然后在手机上找到电脑分享的热点做代理配置修改？

我之前一直以为是指第二种方法。

**Comment by Fndroid** [comment]
@Aithosa 电脑可以分享热点给手机，Win10自带的“移动热点”就可以实现，创建出来的网卡地址就是手机要填代理的IP地址

**Comment by Aithosa** [comment]
@Fndroid 谢谢您的帮助，我的电脑的防火墙限制了连接，关闭之后可以正常使用。另外请问port-7890和socks port-7891有什么区别吗？我试过7890可以正常连接，但是使用8901时无法访问互联网。

**Comment by Fndroid** [comment]
socks port就是一个socks5代理端口

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.

**Comment by yiping8-23** [comment]
> This issue has not been updated for a long time. I am sorry to close it.
> 
> Please try updating to the latest version first to see if the problem has disappeared.
> 
> If not, feel free to start a new issue.



> 请问我的allow lan打开后是这些地址，我的笔记本是连接的无线网，那我的代理地址是哪一个?
> ![2019-10-25 (3)](https://user-images.githubusercontent.com/32020141/67563621-a55a1000-f753-11e9-8e87-da382ea0810e.png)
> 
> 我尝试过wlan和本地连接2，端口设为7890其他设备都无法正常联网。
> 
> 另外，请问比如我希望共享给手机，那么我是到手机的无线网设置页面设置吗?就像下面这样？
> ![Screenshot_2019-10-25-18-19-50-888_com android se](https://user-images.githubusercontent.com/32020141/67563881-3af59f80-f754-11e9-822d-95548c5fc842.jpg)
> 
> 谢谢！

允许应用通过防火墙中把clash-win64的专用/公用都勾选，就可以了。

**Comment by wangshuai-007** [comment]
这里有点问题是，之前我用SS的时候在docker里面配置代理直接用127.0.0.1就可以了
而用Clash之后要设置成具体的IP地址192.168.xx.xx；那如果路由器用开了DHCP，每次开机docker用代理还得手动修改代理配置
不知道能不能优化一下

**Comment by valee777** [comment]
clash allow lan IP地址每天都会变吗，可不可以设置成不变

**Comment by wangshuai-007** [comment]
> clash allow lan IP地址每天都会变吗，可不可以设置成不变

Lan ip就是你本机IP地址，你去百度怎么设置固定ip就行了

**Comment by brothore** [comment]
> 的防火墙限制了连接，关闭之后可以正

感谢，我关闭了网络防火墙之后也可以连接了。
