### ISSUE TITLE
clash for windows   0.18 版本增强托盘 右侧有遮挡，并且无法用鼠标拖动！

### ISSUE THREAD

**Issue by helloktity** [Fndroid/clash_for_windows_pkg#2210]
clash for windows   0.18 版本增强托盘 右侧有遮挡，并且无法用鼠标拖动！这应该是一个bug吧

**Comment by yi-Xu-0100** [comment]
@helloktity 有图吗？啥系统？没懂。。。

**Comment by helloktity** [comment]
![image](https://user-images.githubusercontent.com/90443993/132936192-368f4bbb-10f6-4753-8c0f-47e3997fbec6.png)
![image](https://user-images.githubusercontent.com/90443993/132936214-6607219c-724c-464f-9e7f-c71f19366737.png)
 汉化前后 图 ，并且 这个版本 0.18 这个托盘不能被拖动。

**Comment by helloktity** [comment]
以前版本 这个 托盘 都能随意拖动  改变桌面上的位置

**Comment by Fndroid** [comment]
使用任何非Github版本，请勿发issue，谢谢合作

**Comment by helloktity** [comment]
关键是  原版英文 没汉化的 也拖动不了  我都试过了 以前0.17.3都可以拖动的

**Comment by helloktity** [comment]
这个图标  不能拖动 总不是汉化引起的 ， 是0.18程序本身就不能拖动
