### ISSUE TITLE
clash for windows 0.18 版本Proxies和Rules都是空的

### ISSUE THREAD

**Issue by mostcool** [Fndroid/clash_for_windows_pkg#2211]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Win11
clash for windows 0.18

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
clash for windows 0.18 版本Proxies和Rules都是空的

**复现**

[//]: # (请描述复现问题的步骤)

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/2172570/132819370-cc940862-fdd8-42f5-a81a-c6df4b4c04b6.png)
![image](https://user-images.githubusercontent.com/2172570/132819395-66ae0979-e6ff-4f92-85cf-4b5feb40fe4a.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by alaya129** [comment]
同样问题

**Comment by yi-Xu-0100** [comment]
日志呢？

**Comment by alaya129** [comment]
解决了，估计是新版本对YAML验证更严格了，把你的配置文件在https://jsonformatter.org/yaml-validator验证一下再修改就可以了。
