### ISSUE TITLE
Linux无法安装Tun，报错Error occurred in handler for 'app': Error: Failed to get 'tmp' path

### ISSUE THREAD

**Issue by klniu** [Fndroid/clash_for_windows_pkg#2212]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Archlinux 5.13.13-arch1-1 x86_64 GNU/Linux

Clash_For_Windows 1.8.0

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
已经安装nftables和iproute2，打开Service Mode后，多次尝试点击安装没反应。

在命令行运行后，同样点击，报以下错误：
```
Error occurred in handler for 'app': Error: Failed to get 'tmp' path
    at /home/klniu/bin/Clash/resources/app.asar/dist/electron/main.js:1:4678
    at electron/js2c/browser_init.js:197:579
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10173)
    at Object.emit (events.js:376:20)

```

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)
安装Tun

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
应该是个bug，用上一版试试

**Comment by miadabdi** [comment]
I got the same issue. it is a bug

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
