### ISSUE TITLE
更新程序没有退出托盘图标

### ISSUE THREAD

**Issue by bb2** [Fndroid/clash_for_windows_pkg#2215]
**更新程序没有退出托盘图标**

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**描述**

每次使用程序自带更新按钮更新程序后都会在任务栏留下两个托盘图标，鼠标移动一下才消失，陈年老BUG了

**复现**

1. 进入'程序主界面'
2. 点击'NEW'
3. 点击'Update'
4. 按提示完成更新
5. 出现两个Clash托盘图标

**预期行为**

只有一个Clash托盘图标

**Comment by Fndroid** [comment]
windows的bug
