### ISSUE TITLE
httpy认证失败

### ISSUE THREAD

**Issue by 643406834** [Fndroid/clash_for_windows_pkg#2216]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

win10 19043.1165

**描述**

看了官方文档，之前有设置用户名和密码，从某个版本开始，http和sock5认证失败

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

不能打开网页

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

![image](https://user-images.githubusercontent.com/39716940/132941586-ca160683-007d-448f-afba-5ccc019c1e43.png)
![image](https://user-images.githubusercontent.com/39716940/132941597-8e68ec6e-7964-411c-837f-bbc3690eb015.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by akw5454521** [comment]
allow lan都false了，就别搞认证了呗
