### ISSUE TITLE
windows 10 系统下 0.18  原版英文程序 增强托盘 小长方形窗口 无法用鼠标拖动！再次反馈

### ISSUE THREAD

**Issue by helloktity** [Fndroid/clash_for_windows_pkg#2217]
windows 10 系统下  原版0.18版本 英文程序 增强托盘 小长方形窗口 无法用鼠标拖动

- [ ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

windows 10   专业版

windows 10 系统下  原版0.18版本 英文程序 增强托盘 小长方形窗口 无法用鼠标拖动

具体表现： 鼠标拖动不了 就会固定在屏幕一个位置

**Comment by Snipakillah** [comment]
+1

**Comment by xyqrm** [comment]
+1

**Comment by AkariiinMKII** [comment]
上游 请

**Comment by yushufeng** [comment]
Windows11
Clash.for.Windows-0.18.0-win.7z
Enhanced Tray悬浮窗不能移动

**Comment by st-youth** [comment]
0.18.1 +1
