### ISSUE TITLE
【建议】能否增加应用数据使用量统计功能

### ISSUE THREAD

**Issue by zqily** [Fndroid/clash_for_windows_pkg#2218]
**描述**
请具体并清楚地描述期望功能及期望的效果
如题，能否增加数据使用量统计功能，虽然平常仅代理浏览器和下载软件端口，但是对于全局代理等模式如果有数据使用量统计功能的话会方便清晰很多
**其他说明**
其他补充内容

**Comment by zqily** [comment]
![image](https://user-images.githubusercontent.com/40664217/132972036-a9ce4ef9-ad0b-4b4d-8b4c-858561ced8f1.png)

**Comment by Fndroid** [comment]
clash core issue, refer: https://github.com/Dreamacro/clash/issues
