### ISSUE TITLE
win10 V0.711版本 System Proxy按钮功能失效.

### ISSUE THREAD

**Issue by feng99** [Fndroid/clash_for_windows_pkg#222]
关掉软件的系统代理后 
这里是灰色的.
![image](https://user-images.githubusercontent.com/13182572/66702219-e0157e80-ed37-11e9-94ea-f2ef32078d03.png)

浏览器这里也需要手动开启.  
![image](https://user-images.githubusercontent.com/13182572/66702253-2074fc80-ed38-11e9-9e65-c3499d77c5ab.png)

软件的系统代理开关按钮  完全失效了

我使用的是V0.710版本 升级到V0.711版本  问题依旧. 

请处理下  谢谢

**Comment by Fndroid** [comment]
无法开启系统代理？

系统代理涉及注册表修改操作，所有软件都可以进行的，所以可能被其他软件影响了，自己检查一下

**Comment by feng99** [comment]
> 无法开启系统代理？
> 
> 系统代理涉及修改修改操作，所有软件都可以进行的，所以可能被其他软件影响了，自己检查一下

同类型的软件   我只开启了这一个 
电脑里也有SSR4.0  但我并没有运行.
昨天我卸载,重新安装了Clash for Windows、v0.7.11
问题依旧.

**Comment by Fndroid** [comment]
> 软件的系统代理开关按钮 完全失效了

究竟是不能打开还是不能关闭还是点了没反应

> 同类型的软件 我只开启了这一个

不一定是同类软件，所有软件都可以修改系统代理

再不行照这个试试：https://github.com/Fndroid/clash_for_windows_pkg/issues/223#issuecomment-541652487

**Comment by feng99** [comment]
> > 软件的系统代理开关按钮完全失效了
> 
> 究竟是不能打开还是不能关闭还是点了没反应
> 
> > 同类型的软件我只开启了这一个
> 
> 不一定是同类软件，所有软件都可以修改系统代理
> 
> 再不行照这个试试：[＃223（留言）](https://github.com/Fndroid/clash_for_windows_pkg/issues/223#issuecomment-541652487)

不管是 打开 还是 关闭  都不起作用.

**Comment by feng99** [comment]
我使用SSR软件 就没有这种问题.

**Comment by GainSury** [comment]
我没有这个问题

**Comment by feng99** [comment]
2019-12-10
再次下载最新版    此问题在win10下 依然没有修复
不浪费这个时间了
关闭此issue
继续使用SSR 
还是SSR更香~
