### ISSUE TITLE
macos bigsur 启动报错 permission denied

### ISSUE THREAD

**Issue by xiaoOops** [Fndroid/clash_for_windows_pkg#2223]
[//]: # (如不按模版填写，则issue将被直接关闭)

安装后启动没有自动请求权限，启动后报错，无权限，尝试过修复，不行。

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [✔] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [✔] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [✔] 已经尝试更新到最新版本，问题依旧存在
- [✔] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

macOS bigsur
![image](https://user-images.githubusercontent.com/23649228/133185651-4b774da3-e2f7-4956-9073-8d56a5778447.png)

**日志**
time="2021-09-14T10:12:36+08:00" level=fatal msg="Initial configuration directory error: can't create config directory /Users/Linkä¸¹/.config/clash: mkdir /Users/Linkä¸¹: permission denied"

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**
![image](https://user-images.githubusercontent.com/23649228/133185816-bb9da8ae-1731-4d17-aa66-ec1df00cab9c.png)

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
你这用户名里的是什么字符

**Comment by xiaoOops** [comment]
> 你这用户名里的是什么字符

是中文

**Comment by Fndroid** [comment]
你看看这个用户文件夹存在了没

**Comment by xiaoOops** [comment]
> 你看看这个用户文件夹存在了没。正常用户文件夹权限用户自己肯定可以读写，不需要提权。

这个路径么？/user/Link丹/.config，好像没有。

**Comment by xiaoOops** [comment]
把用户名的中文给改掉了，ok了。
