### ISSUE TITLE
快捷键设置触发存在问题

### ISSUE THREAD

**Issue by Zacama** [Fndroid/clash_for_windows_pkg#2225]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 企业版 1909 18363.1801

**描述**

将如下快捷键 界面 -> Settings -> Shortcuts-> System Proxy 设置为 <Ctrl + D + L>，实际使用时，<Ctrl + D + L>与<Ctrl + L>皆生效

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入界面
2. 点击Settings
3. 拖动到 Shortcuts 
4. 触发问题  System Proxy 设置为 <Ctrl + D + L>，<Ctrl + D + L>与<Ctrl + L>皆生效

**预期行为**

System Proxy 设置为 <Ctrl + D + L>，仅<Ctrl + D + L>生效

**日志**

无日志

**截图**

![image](https://user-images.githubusercontent.com/50320281/133540193-2522cb82-9375-4362-9921-662d470bfc3d.png)

**其他说明**

此外尝试了Direct Mode的设置，一样的问题

**Comment by Fndroid** [comment]
最新版吗

**Comment by Zacama** [comment]
![image](https://user-images.githubusercontent.com/50320281/133584774-182c7489-dd4e-4924-bce5-512839c7b231.png)
v 0.18.0

**Comment by Fndroid** [comment]
似乎是electron不认为这个是合法的组合键，三个键建议用shift，win之类的组合

**Comment by Zacama** [comment]
好的，谢谢
