### ISSUE TITLE
How to force a system wide proxy?

### ISSUE THREAD

**Issue by miadabdi** [Fndroid/clash_for_windows_pkg#2226]
Describe:
I am looking for an option in GUI or text-based configs to turn on system-wide proxy.
I want the entire traffic to be rerouted through my server.

Clash for windows 0.17.3 (new version has bugs)
Ubuntu 20.04

**Comment by yi-Xu-0100** [comment]
Use TUN mode。

https://docs.cfw.lbyczf.com/contents/tun.html#linux
