### ISSUE TITLE
直接更新版本，core版本不更新。需要卸载，全新安装新版才行

### ISSUE THREAD

**Issue by leafsoul365** [Fndroid/clash_for_windows_pkg#2227]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统** win10 21H2

[//]: # (平台及版本号)

**描述**  直接更新版本，core版本不更新。需要卸载，全新安装新版才行

[//]: # (请具体并清楚地描述遇到的问题)

**复现** 最近几次覆盖更新都如此

**Comment by Fndroid** [comment]
开启Servcie Mode是会这样，两个办法：
1. 使用APP内置更新
2. 先完全退出后再安装新版

**Comment by leafsoul365** [comment]
> 开启Servcie Mode是会这样，两个办法：
> 
> 1. 使用APP内置更新
> 2. 先完全退出后再安装新版

OK，多谢了。Done
