### ISSUE TITLE
0.18.0&0.18.1  Enhanced Tray悬浮窗无法移动

### ISSUE THREAD

**Issue by Snipakillah** [Fndroid/clash_for_windows_pkg#2228]
**信息**

- [ ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Win 10 x64 1809

**描述**

如题，0.18.0及0.18.1版本，Enhanced Tray悬浮窗无法移动

**复现**

Setting - Appearance - 打开Enhanced Tray

**预期行为**

Enhanced Tray悬浮窗可由鼠标单击并按住拖动

**日志**

无

**截图**

无

**其他说明**

暂无

**Comment by yi-Xu-0100** [comment]
Duplicate of #2217

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
