### ISSUE TITLE
Start with Linux功能异常

### ISSUE THREAD

**Issue by SamTripleOne** [Fndroid/clash_for_windows_pkg#2229]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Ubuntu18.04

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
下载最新0.18.1版本，将解压缩后的文件放置在`~/下载`目录下，打开`Start with Linux`，可以随系统启动

如果放置在`/opt`目录下，打开`Start with Linux`，则无法随系统启动，且Ubuntu系统产生错误，若之后再将cfw文件移动至`~/下载`目录，错误仍存在

**预期行为**

[//]: # (清晰地描述期望看到的行为)
cfw文件放置在`/opt`目录下，依然可以设置随系统启动

**Comment by yi-Xu-0100** [comment]
@SamTripleOne 是开启设置之后移动的，还是设置后，又移动了位置

**Comment by SamTripleOne** [comment]
在`~/下载`目录下取消开机启动，重启电脑，再移动到`/opt`，再打开开机启动，功能正常，但是Ubuntu偶尔会报错，我再观察几天，issues先关了
