### ISSUE TITLE
代理无法关闭

### ISSUE THREAD

**Issue by inkss** [Fndroid/clash_for_windows_pkg#223]
我在退出软件 **前** 已经关闭了代理，此时打开设置-网络-代理可以确认代理按钮是关闭的。

但是一段时间之后，它又被自动开启了，而且由于软件没有在运行，它影响到了电脑的正常上网。
这个现象发生了很多很多次，我是真的无法排除是谁做的这一切，please help me

**Comment by Fndroid** [comment]
照这个清空一下注册表：https://github.com/Fndroid/clash_for_windows_pkg/wiki/%E7%B3%BB%E7%BB%9F%E4%BB%A3%E7%90%86%E5%BC%82%E5%B8%B8%E5%85%B3%E9%97%AD

在CFW关闭情况下是没办法修改你系统代理的，只能是其他软件

**Comment by inkss** [comment]
> 刷新注册表编辑器，查看条目是否重新出现。

重新开关后，出现了两条，原先是有7条的样子，其中有四个显示的是乱码，锟斤拷

**Comment by inkss** [comment]
@Fndroid 有个新问题，比较尴尬的是，现在由原先的自动开启，变为了自动关闭。。。  

即使是软件运行开启下的。。。。    我太难了。。。

**Comment by Fndroid** [comment]
只能考虑是不是其他软件的问题了

**Comment by inkss** [comment]
按照这个链接的描述，似乎解决了这个问题，起码目前是没有复现：[将WIN10代理重启电脑自动启用](https://answers.microsoft.com/zh-hans/windows/forum/windows_10-networking/%E5%B0%86win10%E4%BB%A3%E7%90%86%E8%AE%BE%E7%BD%AE/f6708416-3028-45fc-9666-aadab55f59aa)

> 最终在”设置--账户--你的信息“中，将账户改为”改用本地账户登陆“，然后进入”设置--网络和Internet--代理“，将手动设置代理项关闭，然后再将账户改回使用Microsoft账户登陆即可。此后至今再没有出现以上情况。所有关于设置失效的操作，都要以尝试此方法去解决。

虽然完全不理解这是为什么。。

**Comment by inkss** [comment]
`V0.7.12` 版本，也是这边软件关了，过会儿代理自动开启，虽然有点不太好，但是如果将CFW卸载了，代理就没有再开启，我有点怀疑是浏览器开启的，谷歌或者火狐什么的。

其实是上次十一好多节点用不了之后，开着代理也没什么用，想着关闭了它才发现关闭不了的。

**Comment by cc9014** [comment]
我也遇到了类似的问题，软件里面System Proxy是关闭的，刚打开电脑的时候系统代理也是关闭，过一段时间后，系统代理就被打开了。但此时Clash的System Proxy还是正常关闭状态……

**Comment by nmare727** [comment]
我现在也遇到这个问题，已经卸载了CLASH，但是代理服务器那里仍然被设置，导致我打开网页，出现跟作者一样的提示，找不到原因 我是WIN10 1903系统

**Comment by nmare727** [comment]
> 按照这个链接的描述，似乎解决了这个问题，起码目前是没有复现：[将WIN10代理重启电脑自动启用](https://answers.microsoft.com/zh-hans/windows/forum/windows_10-networking/%E5%B0%86win10%E4%BB%A3%E7%90%86%E8%AE%BE%E7%BD%AE/f6708416-3028-45fc-9666-aadab55f59aa)
> 
> > 最终在”设置--账户--你的信息“中，将账户改为”改用本地账户登陆“，然后进入”设置--网络和Internet--代理“，将手动设置代理项关闭，然后再将账户改回使用Microsoft账户登陆即可。此后至今再没有出现以上情况。所有关于设置失效的操作，都要以尝试此方法去解决。
> 
> 虽然完全不理解

试了没有用。。

**Comment by inkss** [comment]
@nmare727  我猜测，应该是浏览器打开的代理功能，不太确定，或许是别的软件。

**Comment by singledoggy** [comment]
我也遇到了一样的情况，自动设置代理出了问题。不明白为什么。以上方法都用了无果，不知道是什么软件的错。

**Comment by Fndroid** [comment]
refer: https://github.com/Fndroid/clash_for_windows_pkg/issues/312
