### ISSUE TITLE
升级到0.18.1后，自定义配置文件目录未生效。

### ISSUE THREAD

**Issue by borpubi** [Fndroid/clash_for_windows_pkg#2231]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**
无报错信息
[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [X ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [X] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [X] 已经尝试更新到最新版本，问题依旧存在
- [X] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

WIN10 20H1
**描述**

[//]: # (请具体并清楚地描述遇到的问题)

升级后，无profile，再次手动选择配置文件目录也未生效。
配置文件路径含中文。

**复现**

[//]: # (请描述复现问题的步骤)

1. 设置含中文路径的配置文件路径
2. 升级到0.18.1
3. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

升级后，无profile，再次手动选择配置文件目录也未生效。
配置文件路径含中文。

**日志**
无
[//]: # (上传触发问题对应的日志文件)
无
**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/28093885/133882567-50001625-5740-4e8a-99b8-caca333906b1.png)
![image](https://user-images.githubusercontent.com/28093885/133882587-ebfb0f66-fb6c-4476-89db-8900a813899f.png)
![image](https://user-images.githubusercontent.com/28093885/133882595-fa347138-7dda-4463-ad9e-d3cde6366f59.png)
**其他说明**
无
[//]: # (其他补充内容)
无

**Comment by yi-Xu-0100** [comment]
要不改成纯英文试试

**Comment by Fndroid** [comment]
应该是bug

**Comment by VaylorGesco** [comment]
是否是因为删除了最初的配置文件，可是我再次安装后还是没有哪个配置文件，应该是BUG

**Comment by borpubi** [comment]
补充一下最近的操作：
1.移动运行程序到英文目录，无效。
2.修改配置文件目录到英文目录，无效。
3.退回0.18.0，无效。
到这一步，猜测是主要的配置文件被损坏
所以删除了C:\Users\个人账号名\.config目录，然后重新运行0.18.0版本，重新配置后正常上网。
等下测试再次升级到0.18.1看结果。

**Comment by borpubi** [comment]
测试成功，完全重新解压缩的程序和全新的配置文件是可以升级到0.18.1的。
程序在中文目录中。配置文件在默认路径中。
现在不知道是程序目录里面的文件有问题还是配置文件目录里面的配置文件有问题造成的。
所有之前修改过的配置又得重新经历一遍才能修改了。

**Comment by borpubi** [comment]
改了一下主题为DARK，然后好像又读不到配置了
![image](https://user-images.githubusercontent.com/28093885/134019895-3d6803a3-1b2e-4c71-901a-103b107e50cf.png)
好消息是状态是连接的……
坏消息是这个状态是假的，实际已经不能用了。

**Comment by borpubi** [comment]
重新解压缩程序到一个英文目录中，目前运行良好。
![image](https://user-images.githubusercontent.com/28093885/134020423-6dad2fe5-196a-4e10-a233-598ae1c909d1.png)
![image](https://user-images.githubusercontent.com/28093885/134020426-37b2beb8-c1e2-4049-b7e4-a63902f8f809.png)

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
