### ISSUE TITLE
Ubuntu18.04 cfw界面卡在Loading

### ISSUE THREAD

**Issue by SamTripleOne** [Fndroid/clash_for_windows_pkg#2233]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Ubuntu18.04

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

全新安装的Ubuntu系统，启动`./cfw`始终停留在Loading

**复现**

[//]: # (请描述复现问题的步骤)

1. 全新安装的Ubuntu系统，第一次打开`./cfw`，终端提示`bash:./cfw权限不够`
2. `chmod 777`后再次启动
3. 出现CFW界面，但始终停留在Loading

**日志**

[//]: # (上传触发问题对应的日志文件)

终端提示如下：
```
[1926:0919/123406.332134:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
(node:1872) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(Use `cfw --trace-warnings ...` to show where the warning was created)
```

**其他说明**

[//]: # (其他补充内容)
回退至Clash for Windows18.0，依旧有相同问题

**Comment by yi-Xu-0100** [comment]
不会是root权限去打开的吧

**Comment by SamTripleOne** [comment]
> 不会是root权限去打开的吧
![Inked2021-09-19 14-45-25 的屏幕截图_LI](https://user-images.githubusercontent.com/62505930/133918338-ad7f20d3-caff-4182-96c7-69c71d4b3e42.jpg)
这就是所有操作了，不给权限根本打不开

**Comment by yi-Xu-0100** [comment]
@SamTripleOne github 下载的吗？我今天刚虚拟机装一个，ubuntu 20.04 直接可行。。。点左下角的 disconnected 看看日志呢？不会是用户名是中文吧。。。

**Comment by SamTripleOne** [comment]
> @SamTripleOne github 下载的吗？我今天刚虚拟机装一个，ubuntu 20.04 直接可行。。。点左下角的 disconnected 看看日志呢？不会是用户名是中文吧。。。

github下载的， disconnected日志完全空白，英文用户名

就很玄学

**Comment by yi-Xu-0100** [comment]
@SamTripleOne 直接 ubuntu 下载的？为啥会有权限问题呢。。。 很迷

**Comment by SamTripleOne** [comment]
> @SamTripleOne 直接 ubuntu 下载的？为啥会有权限问题呢。。。 很迷

是另一台电脑下载，拷贝到这台电脑上，再解压的
直接用本机下载，问题解决了。。。
