### ISSUE TITLE
HTTP ERROR 502

### ISSUE THREAD

**Issue by sysreng** [Fndroid/clash_for_windows_pkg#2236]
**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
版本	Windows 10 专业版
操作系统内部版本	19043.1237

**描述**
好像近期几个版本我有时候会遇到出现 502 的错误，是什么问题呀？访问的网站应该没问题，看 log 也没发现什么异常

cfw 设置跟以前一样的，以前没出现过，唯一有变化的就是 cfw 跟着升级

**截图**
![image](https://user-images.githubusercontent.com/51149477/133975307-697a1a6b-ce7e-4ce8-bc19-ba75d83b1f1b.png)

![image](https://user-images.githubusercontent.com/51149477/133974198-2e124bb9-21d5-40c7-bdd1-c886f4c0bbbd.png)

![image](https://user-images.githubusercontent.com/51149477/133974256-4413406b-7bb8-464f-98c5-d3321cfa82b5.png)

![image](https://user-images.githubusercontent.com/51149477/133974392-4b594bd4-3e5f-41ee-8bfa-56bb6d6bd1bd.png)

**Comment by yi-Xu-0100** [comment]
点击左下角 connected 查看日志。可能有原因。

**Comment by sysreng** [comment]
@yi-Xu-0100 好像没记录到，16:24 这个时间点挂了呀？
![image](https://user-images.githubusercontent.com/51149477/133984609-0fd7d821-a50d-4fc6-afda-2d73ca60645b.png)

![image](https://user-images.githubusercontent.com/51149477/133984309-b17d77fa-01f5-4d37-955d-208c2c77bfb6.png)

![image](https://user-images.githubusercontent.com/51149477/133984145-4c4b280c-a0fd-4dd7-afb5-6fe4172cab3e.png)

**Comment by yi-Xu-0100** [comment]
参照这个 https://github.com/Fndroid/clash_for_windows_pkg/issues/2073#issuecomment-887773201 试试 pac 用 socks5

**Comment by sysreng** [comment]
@yi-Xu-0100 system proxy 是用的 pac。

**Comment by sysreng** [comment]
![image](https://user-images.githubusercontent.com/51149477/134273442-8764859a-55bf-4a83-9308-2826cc672c25.png)
这个日志为啥没记录到，是不是 down 了！但是 log 那边看又有显示

**Comment by yi-Xu-0100** [comment]
@sysreng 把 pac 内容看看

**Comment by sysreng** [comment]
@yi-Xu-0100 
![image](https://user-images.githubusercontent.com/51149477/134279753-d8e7cfa0-485f-4b20-9f20-1a109909a1d8.png)

**Comment by yi-Xu-0100** [comment]
最后一句返回 SOCKS5写在前面 PROXY 写后面试试

**Comment by sysreng** [comment]
@yi-Xu-0100 改成 `return "SOCKS5 127.0.0.1:%mixed-port%";`了，后面看看是否还会有问题。
