### ISSUE TITLE
发现病毒HEUR:Trojan/JS.Obfuscator.a

### ISSUE THREAD

**Issue by traoearth** [Fndroid/clash_for_windows_pkg#2238]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: #(平台及版本号)

Windows v0.17.3

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

凌晨五点多的时候火绒提示发现病毒HEUR:Trojan/JS.Obfuscator.a，病毒URL：http://www.51jianku.com/51jianku/?p=1399

**复现**

[//]: # (请描述复现问题的步骤)

无法复现

**预期行为**

[//]: # (清晰地描述期望看到的行为)

没有报毒提示

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

![QQ图片20210921113604](https://user-images.githubusercontent.com/82272385/134108041-35226a44-3990-4b4f-a5fd-765a795af755.png)
**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
病毒 url 是指的什么？

**Comment by traoearth** [comment]
如截图里所示，我也不清楚，从来没遇到过这种状况。

**Comment by yi-Xu-0100** [comment]
如果是 github 下载的就信任（或者不用），别的地方下载的就换成 github 下载的

**Comment by yi-Xu-0100** [comment]
https://www.52pojie.cn/thread-1384358-1-1.html

可能是你访问的网站问题，毕竟流量都走 clash 。

**Comment by traoearth** [comment]
但是我甚至都不知道那个网站。。。

**Comment by traoearth** [comment]
而且五点钟那会都在睡觉

**Comment by yi-Xu-0100** [comment]
母鸡……开个虚拟机，只安装CFW和火绒试试。

估计很难复现。。。

**Comment by traoearth** [comment]
已经将问题上报到火绒论坛了，希望能有所帮助吧...

**Comment by qwerty12394** [comment]
有没有汉化版的

**Comment by Fndroid** [comment]
就是访问的URL被火绒拦截了

**Comment by zhuangdx** [comment]
meet
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/16098983/0d2edf97-56f2-40ef-b17e-9db76d69eb76)
