### ISSUE TITLE
是否在未来考虑加入ota升级?

### ISSUE THREAD

**Issue by ArnoFrost** [Fndroid/clash_for_windows_pkg#224]
请问未来是否愿意加入这项功能?或者是现在已经有了?我没有找到...

**Comment by Fndroid** [comment]
OTA具体是什么方式呢

**Comment by ArnoFrost** [comment]
比如保留用户配置文件夹,程序全量下载到一个temp文件夹中,然后覆盖到当前执行的目录中,删除temp并重启这种 可行吗

**Comment by Fndroid** [comment]
目前不会自动下载，因为CFW是不受系统代理影响的（除非使用TAP），而直连情况访问Github Release会很糟糕

但是软件会自动检查更新，在General中标题右边版本号如果有新版会有个``new``的图标，点击会访问并下载
