### ISSUE TITLE
What is the default  encryption method of clash_for_windows ?

### ISSUE THREAD

**Issue by LiuChang-ao** [Fndroid/clash_for_windows_pkg#2242]
I have a clash subscribe. It gave me a URL but it return some meaningless code instead of config.yaml.
Such as(just for example) : 9UbGNkVFpsTW1aQlYxTTRJaXdpWVdSa0lqb2lZMjFqWTNW.........
I guess that This is an encrypted text. Now I want to build a similiar service in Linux(CentOS 7),which don't have a window system. I would appreciate it if someone could help me with the config.yaml.

**Comment by yi-Xu-0100** [comment]
base64?

**Comment by LiuChang-ao** [comment]
用了其他的工具，似乎不是。导入到win下的clash客户端就可以直接用，linux下因为没有自动更新订阅，想自己实现一下。

**Comment by yi-Xu-0100** [comment]
@LiuChang-ao 你base64试下，应该是节点链接吧

**Comment by yi-Xu-0100** [comment]
你请求带上请求头，就是对应的yaml了

**Comment by LiuChang-ao** [comment]
对不起，是我弄错了，确实是base64，返回的是一组节点链接。复制的时候漏了最后两个==，没识别出来。
问题已解决，谢谢了。
