### ISSUE TITLE
开发者能否增加对http/2协议的支持

### ISSUE THREAD

**Issue by pikaqiu-ru** [Fndroid/clash_for_windows_pkg#2247]
clash好像不支持http/2协议，希望开发者能增加对http/2协议的支持

**Comment by yi-Xu-0100** [comment]
core issue: <https://github.com/Dreamacro/clash/issues>

**Comment by liuxingzhang** [comment]
同希望能够增加h2协议

**Comment by Fndroid** [comment]
clash core issue, refer: https://github.com/Dreamacro/clash/issues
