### ISSUE TITLE
could not run clash core (clash for windows v0.7.11)

### ISSUE THREAD

**Issue by chzhzhzh** [Fndroid/clash_for_windows_pkg#225]
您好，我今天从0.5.35版的更新提示中下载安装了新版，然后就不能使用clash了，现在的状态是内外所有网站都没有响应但是QQ还可以收发文字消息(›´ω`‹ )
我在网上搜了一下发现需要看日志，我看不懂。。。想麻烦您帮我看看怎么解决，谢谢！！！
以下应该是出现问题的日志：

time="2019-10-14T16:23:35+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2019-10-14T16:23:35+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2019-10-14T16:23:35+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2019-10-14T16:23:35+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2019-10-14T16:23:36+08:00" level=info msg="DNS server listening at: 0.0.0.0:53"
time="2019-10-14T16:23:40+08:00" level=warning msg="dial DIRECT error: dial tcp4 69.63.178.13:443: i/o timeout"
time="2019-10-14T16:23:40+08:00" level=warning msg="dial DIRECT error: dial tcp4 69.63.178.13:443: i/o timeout"

期待解救(｡>ㅿ<｡)！！

**Comment by Fndroid** [comment]
把你配置里dns那部分删掉

**Comment by chzhzhzh** [comment]
刚才在这个位置删掉了dns，其他文件里找不到dns了。。现在还是和之前一样的用不了(;_;)
![T@QMA1WV}HKJT6}O)_WXZ4Q](https://user-images.githubusercontent.com/17667318/66742802-16273f80-eeab-11e9-987b-409468f81914.png)

**Comment by Fndroid** [comment]
重新选中这个配置文件了么

log发一下

**Comment by chzhzhzh** [comment]
您好！今天到单位重启了电脑，然后就能上网了！！太好了。。clash也可以用了，已经没有could not run clash core的提示了，超级感谢d(ŐдŐ๑)！！
