### ISSUE TITLE
win11下tun模式开热点连接数爆炸 以按#1444操作

### ISSUE THREAD

**Issue by linger040831** [Fndroid/clash_for_windows_pkg#2252]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 11 专业工作站版 Insider Preview
版本	Dev
安装日期	‎2021/‎9/‎24
操作系统版本	22463.1000
体验	Windows Feature Experience Pack 1000.22463.1000.0

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
win11下tun模式开热点连接数爆炸 以按#1444操作 [但是网卡选项没有#1444所示的选项

**复现**

[//]: # (请描述复现问题的步骤)

打开热点 打开tun 连接数爆炸 clash客户端卡死
**预期行为**

[//]: # (清晰地描述期望看到的行为)
正常连接

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/84896599/134654631-725de864-2016-4fe9-a8e3-ee33cb5050c2.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
设置里是啥样子，没装 win11 就想看看。。。👀

**Comment by linger040831** [comment]
![image](https://user-images.githubusercontent.com/84896599/134667324-60104123-3659-4877-a58a-3cbd0cea49b2.png)

**Comment by yi-Xu-0100** [comment]
@linger040831 我是说 clash 网卡，共享里这个设置，是新出来的？点开啥样？

**Comment by linger040831** [comment]
![image](https://user-images.githubusercontent.com/84896599/134670944-ac3fd9e6-9123-4297-8058-1717cf170a25.png)
