### ISSUE TITLE
Lightweight Mode开机自启动时必弹出窗口。

### ISSUE THREAD

**Issue by LeoYHZ** [Fndroid/clash_for_windows_pkg#2255]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
- 系统：Win10 1809
- 系统：Win11 22000.194
- 软件版本：v 0.18.2

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
在CFW中启用 Lightweight Mode 后开机自启动时必弹出窗口，然后需要手动关闭才可，打开 Silent Start 不能解决该问题。

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入CFW，同时开启 Lightweight Mode 和 Silent Start；
2. 重启电脑；
3. 开机后弹出CFW的窗口。

**预期行为**

[//]: # (清晰地描述期望看到的行为)
同时打开 Lightweight Mode 和 Silent Start 后可以开机后无感自启动。

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
Lightweight Mode 需要手动关闭 CFW，才能保留 core ，不然，一打开 Lightweight Mode ，就会关闭 CFW，会造成之后无法打开 CFW（因为一打开，就检测到设置了 Lightweight Mode，CFW 被关闭，只保留 core）。懂？

**Comment by LeoYHZ** [comment]
> Lightweight Mode 需要手动关闭 CFW，才能保留 core ，不然，一打开 Lightweight Mode ，就会关闭 CFW，会造成之后无法打开 CFW（因为一打开，就检测到设置了 Lightweight Mode，CFW 被关闭，只保留 core）。懂？

想了一下，确实是这样，谢谢提醒。我看一下使用其他方法解决吧。

**Comment by yi-Xu-0100** [comment]
@LeoYHZ 建议找找给 core 设置开机自启即可，关闭 CFW 的开机自启，有需要设置时，再去打开 CFW。Lightweight Mode 只是关闭了 CFW ，保留 core。
