### ISSUE TITLE
与Clash-tracing的兼容性问题

### ISSUE THREAD

**Issue by lostwindsenril** [Fndroid/clash_for_windows_pkg#2256]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Manjaro 以及 Windows 10，版本0.18.2，Premium内核
**描述**

[//]: # (请具体并清楚地描述遇到的问题)

clash-tracing是clash内核作者Dreamacro的另一个项目，提供了一个高级的仪表盘。项目地址：https://github.com/Dreamacro/clash-tracing

最近在部署该仪表盘时发现与Cfw的兼容性不佳。具体的说，如果提供的不是完整的配置文件（即：只有proxies/proxy-groups/rules三个字段），就会导致clash-tracing的大部分数据无法显示。必须将完整的字段写入单个配置文件才可以使clash-tracing生效。
该问题在Linux和Windows下均可以重现。
鉴于不完整的配置文件是Cfw的独有功能，因此将issue提在这里。

[//]: # (请描述复现问题的步骤)
0.部署clash-tracing仪表盘。Compose文件如下，其中172.18.0.1是docker网络的网关：

> version: '3'
services:
  influxdb:
......
  grafana:
......
  scraper:
......
      CLASH_HOST: '172.18.0.1:9090'
networks:
  default:
    name: clash
    external: true

1.给home directory的config.yaml文件写入

> .....
external-controller: 0.0.0.0:9090
profile:
  tracing: true
......

2.选中配置文件config-A.yml，其只具有proxy-providers，proxy-groups，rule-providers，rules四个字段，dns与tun字段写在mixin中。重启CfW。
3.重建docker-compose内的所有容器。
4.打开localhost:3000观察仪表盘，发现大部分数据都是no data状态，只有流量统计有效

5.选中配置文件config-B.yml，其增加了如下字段：

> mixed-port: 7890
allow-lan: true
external-controller: 0.0.0.0:9090
secret: # Hide
log-level: info
profile:
  tracing: true
dns:
  ......
tun:
  ......

6.重启CfW，重建docker-compose内的所有容器
7.打开localhost:3000观察仪表盘，发现恢复正常
**预期行为**

[//]: # (清晰地描述期望看到的行为)
在选中config-A与config-B时，clash-tracing应有相同表现。

**日志**

[//]: # (上传触发问题对应的日志文件)
不需要

**截图**

[//]: # (如果可以，请提供对应问题的截图)
config-A
![Screenshot_20210924_212258](https://user-images.githubusercontent.com/24893148/134686084-4245d2b0-4e77-464a-9467-411264e347a8.png)
config-B
![Screenshot_20210924_212411](https://user-images.githubusercontent.com/24893148/134686112-296a445f-fe3a-408c-b8ec-7293eddfc6ac.png)

**其他说明**

[//]: # (其他补充内容)
使用config-A这样的配置在跨平台时具有很好的灵活性，希望作者能解决这个问题，使得config-A也能正常使用仪表盘。

**Comment by yi-Xu-0100** [comment]
@lostwindsenril 如果你需要给 配置文件写入设置，用 parser 才会更改文件内容。mixin 是在内存中完成的。

**Comment by Fndroid** [comment]
因为tracing这个键是根据profiles设置的，如果没有设置那就是false

**Comment by lostwindsenril** [comment]
> 因为tracing这个键是根据profiles设置的，如果没有设置那就是false
您可能没有理解我的意思，在config-A中，我将profiles设置在mixin里了。如果没有设置profiles，那么所有数据都是no data，而非只有流量数据生效。

**Comment by Fndroid** [comment]
所以config-A或者mixin里有没有
```yaml
tracing: true
```

**Comment by lostwindsenril** [comment]
> 所以config-A或者mixin里有没有
> 
> ```yaml
> tracing: true
> ```

有的

**Comment by yi-Xu-0100** [comment]
@lostwindsenril mixin 里吗？建议给出 mixin 完整配置或者截图。

**Comment by lostwindsenril** [comment]
今日再次尝试复现，发现问题似乎不再存在，应该是我的配置问题。抱歉误报issue😂
