### ISSUE TITLE
windows2019server上打开白屏，右下角托盘里也没有。

### ISSUE THREAD

**Issue by wangty225** [Fndroid/clash_for_windows_pkg#2257]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [1] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [2] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [3] 已经尝试更新到最新版本，问题依旧存在
- [4] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

windows server 2019 standard

**描述**

新装的服务器，远程调用访问。但是下载这个打开后白屏，右下角托盘也没有。

**复现**

1. 进入安装目录
2. 双击启动clash for windows.exe
3. 无警告弹窗，但是clash的UI白屏，右下角托盘也未出现clash图标

**截图**

![image](https://user-images.githubusercontent.com/47712270/134703474-fd653bf5-f971-4d2b-955c-0700fe296f4a.png)

**Comment by yi-Xu-0100** [comment]
去 home directory 删除全部文件重新打开试试，注意不用管理员身份打开。

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/442

**Comment by wangty225** [comment]
> #442

解决了！万分感谢！
SET NODE_ENV=production
