### ISSUE TITLE
配置文件的编码问题

### ISSUE THREAD

**Issue by chensimmons** [Fndroid/clash_for_windows_pkg#2262]
我有一个配置文件，编辑后是用UTF-8编码保存的，然后在CFW中导入，导入后显示这配置文件不可用，然后在CFW的配置按钮中，点击"以文本模式编辑”(CFW汉化过)，发现在notepad++中该配置文件的编码变成了ANSI编码，于是一些符号就变成了乱码，想问问这是CFW的问题还是clash的问题。

类似问题:
[配置文件能否支持#号开头的注释？](https://github.com/Fndroid/clash_for_windows_pkg/issues/69)

**Comment by Fndroid** [comment]
汉化过就别问

**Comment by nyaachen** [comment]
我有两个电脑，而且我的CFW是原版的，订阅也都是一个地址，但是之前有一天之后其中一台电脑就出了问题，CFW提示文档中有乱码，另一台就完全没有问题。有问题的电脑上我试过完全卸载后重装，删除home文件夹后重装，均无效
