### ISSUE TITLE
开启系统代理，部分网站请问 CDN 资源产生 CORS 错误

### ISSUE THREAD

**Issue by shangdev** [Fndroid/clash_for_windows_pkg#2264]
类似这样的：

Access to script at 'http://localhost:8001/CLodopfuncs.js?priority=1' from origin 'http://abc,.cn' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `local`.

关闭系统代理后不报 CORS 错误。Clash 版本：0.18.2

**Comment by yi-Xu-0100** [comment]
看日志，可能规则匹配问题，或者 dns 被污染

**Comment by Fndroid** [comment]
你是不是把http这个网站的域名加到bypass里了？

**Comment by shangdev** [comment]
不能加入到bypass里、
