### ISSUE TITLE
Error: Cannot read properties of null (reading 'enable')

### ISSUE THREAD

**Issue by sysreng** [Fndroid/clash_for_windows_pkg#2268]
**信息**
- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
版本	Windows 10 专业版
版本号	21H1
操作系统内部版本	19043.1237

**描述**
根据这个[文档](https://docs.cfw.lbyczf.com/contents/tun.html#windows)使用 tun 模式，在 mixin 中添加了内容，启动 cfw 就报错了，是我写的有问题吗？

**截图**
报错
![image](https://user-images.githubusercontent.com/51149477/135039920-79e4f074-ae18-4e4e-aafb-1605a1ab969b.png)
mixin 配置
![image](https://user-images.githubusercontent.com/51149477/135040147-b117f95e-7329-49dd-b556-eae8095f4e4c.png)
cfw 配置
![image](https://user-images.githubusercontent.com/51149477/135040986-334b18ab-66ec-49f3-9dde-9defe7180a39.png)

![image](https://user-images.githubusercontent.com/51149477/135041053-f0ce099c-2b98-4de7-8d97-bcc23ceeeec9.png)

**Comment by Fndroid** [comment]
yaml格式不对，tun下面开始缩进都不对

**Comment by sysreng** [comment]
.....抄过来的
![image](https://user-images.githubusercontent.com/51149477/135061121-26bdb6a7-92e0-4be9-b8c7-0fe8edb98c38.png)
