### ISSUE TITLE
win10 microsoft to-do 无法更新

### ISSUE THREAD

**Issue by fanzibin** [Fndroid/clash_for_windows_pkg#227]
win10版本号：1903 
microsfot to-do 是win10商店下载的
clash for windows 是 0.7.8
谢谢，clash开代理、全局、直连 都无法更新，只有把clash exist之后，就可以更新了。
![Snipaste_2019-10-18_16-27-10](https://user-images.githubusercontent.com/8002736/67078598-2e0d0500-f1c4-11e9-8cd2-54279270de79.png)

**Comment by Fndroid** [comment]
System Proxy开了么

**Comment by fanzibin** [comment]
开了
![Snipaste_2019-10-18_16-52-44](https://user-images.githubusercontent.com/8002736/67080402-c5278c00-f1c7-11e9-9532-e19ba6a2a888.png)

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/227#issuecomment-543601667

**Comment by fanzibin** [comment]
哦 ，可以了，以前不知道还要这样设置的，谢谢谢谢😄
