### ISSUE TITLE
卡巴斯基网页反病毒

### ISSUE THREAD

**Issue by XSdark** [Fndroid/clash_for_windows_pkg#2271]
[//]: # (如不按模版填写，则issue将被直接关闭)

卡巴斯基网页反病毒自动阻止

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

windows10
18.3

**预期行为**
不确定

[//]: # (如果可以，请提供对应问题的截图)
![批注 2021-09-29 023434 - 副本](https://user-images.githubusercontent.com/78119366/135146615-b9ade99b-5f25-4f89-b72f-5f3175d10473.jpg)

**Comment by Fndroid** [comment]
这是请求的网址有问题
