### ISSUE TITLE
clash for windows v0.18.2 URL导入失败

### ISSUE THREAD

**Issue by WilliamWangshao** [Fndroid/clash_for_windows_pkg#2273]
clash for windows v0.18.2 URL导入失败，失败提示弹窗如图

![](https://s3.bmp.ovh/imgs/2021/09/10941168ddef5877.png)

使用的订阅URL用浏览器打开，会自动下载yml文件。

**Comment by yi-Xu-0100** [comment]
用管理员模式打开的 cfw?

**Comment by WilliamWangshao** [comment]
> 用管理员模式打开的 cfw?

管理员模式打开，同样会报这个错误

**Comment by yi-Xu-0100** [comment]
用户名是英文吗？要不去 home directory 删除 profiles 目录试试，注意备份内容。

**Comment by WilliamWangshao** [comment]
> 用户名是英文吗？要不去 home directory 删除 profiles 目录试试，注意备份内容。

竟然成功了……感谢

**Comment by Fndroid** [comment]
因为第一次启动用了管理员之后创建了高权限文件
