### ISSUE TITLE
更改设置失败

### ISSUE THREAD

**Issue by zhmq18** [Fndroid/clash_for_windows_pkg#2274]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
版本	Windows 10 家庭中文版
版本号	21H1
操作系统内部版本	19043.1237
体验	Windows Feature Experience Pack 120.2212.3530.0
clash for Windows 0.18.2
**描述**
不能更改设置
[//]: # (请具体并清楚地描述遇到的问题)
在设置里添加快捷键，重启软件后都失效了
**复现**
100%复现
[//]: # (请描述复现问题的步骤)
更新Windows后出现

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
用户名是否修改？尝试删除 home directory 目录重启试试

**Comment by zhmq18** [comment]
卸载重装后就搞定了
