### ISSUE TITLE
代理

### ISSUE THREAD

**Issue by liao6964799** [Fndroid/clash_for_windows_pkg#2276]
请问如何设置只代理某些网站?

**Comment by yi-Xu-0100** [comment]
写规则。

**Comment by liao6964799** [comment]
> 写规则。

比如www.google.com 该如何写 能说明一下吗

**Comment by yi-Xu-0100** [comment]
这与你的策略组耦合。

如果你的策略组有一个代理组叫 proxy。

```yaml
rules:
  - DOMAIN-SUFFIX,google.com,proxy
  - MATCH,DIRECT
```

这样就行。建议看看规则编写部分。https://github.com/Dreamacro/clash/wiki/configuration#rules 或者 https://lancellc.gitbook.io/clash/clash-config-file/rules

**Comment by liao6964799** [comment]
> 这与你的策略组耦合。
> 
> 如果你的策略组有一个代理组叫 proxy。
> 
> ```yaml
> rules:
>   - DOMAIN-SUFFIX,google.com,proxy
>   - MATCH,DIRECT
> ```
> 
> 这样就行。建议看看规则编写部分。https://github.com/Dreamacro/clash/wiki/configuration#rules 或者 https://lancellc.gitbook.io/clash/clash-config-file/rules

感谢,目前已经可以实现,只是有一个问题:proxy我选择的是某一个节点,可是连接其他节点也同样做了限制着正常吗
我现在的规则:
 - DOMAIN-SUFFIX,google.com, US 17455
  - MATCH,DIRECT

**Comment by yi-Xu-0100** [comment]
@liao6964799 可以选择某一节点，但是么
我没懂你所说的第二句，其他节点限制是啥意思。

**Comment by liao6964799** [comment]
DOMAIN-SUFFIX,google.com, US 17455
MATCH,DIRECT
 我选择US 17455 这个节点,但是其他节点也只能连接google.com

**Comment by liao6964799** [comment]
变成所有节点都只能连接google

**Comment by yi-Xu-0100** [comment]
是的，你不是只代理某些网站吗？这个例子就是只代理 google.com

**Comment by liao6964799** [comment]
好的 谢谢
