### ISSUE TITLE
Select After Updated 含义？

### ISSUE THREAD

**Issue by salzburgrujvnun** [Fndroid/clash_for_windows_pkg#2277]
**描述**
在Profiles设置栏的一项 `Select After Updated`，不理解是什么？
是点击后更新？

![image](https://user-images.githubusercontent.com/79001470/135322656-49917176-cc9f-40f4-801a-7f01c588c3f4.png)

**Comment by Fndroid** [comment]
profile更新后或新下载后会直接切换

**Comment by salzburgrujvnun** [comment]
具体切换什么？不明白。

**Comment by yi-Xu-0100** [comment]
@salzburgrujvnun 你选择了一个 profile，但是手动更新另一个的时候，会自动切换到那个 profile
