### ISSUE TITLE
打开软件后dota2国服无法正常游戏

### ISSUE THREAD

**Issue by xieccc** [Fndroid/clash_for_windows_pkg#2287]
已经尝试打开软件，选择direct以及不勾选系统代理，依旧无法连接国服进行游戏
使用其他代理工具，例如v2rayN是正常的

**Comment by yi-Xu-0100** [comment]
使用系统代理的话，可以试着将 dota 相关域名放到 bypass 中。

而且如果不勾选系统代理，而且没有使用 tun 的话，日志看不到 dota 相关请求的话，应该没有走 CFW。建议检查系统代理是否被修改。

**Comment by xieccc** [comment]
> 使用系统代理的话，可以试着将 dota 相关域名放到 bypass 中。
> 
> 而且如果不勾选系统代理，而且没有使用 tun 的话，日志看不到 dota 相关请求的话，应该没有走 CFW。建议检查系统代理是否被修改。

已经尝试使用bypass，无法生效。
不勾选系统代理，确定连接没有走本软件。但是只要是退出软件就可以正常连接，也怀疑是端口冲突，也修改过，没有任何效果

**Comment by xieccc** [comment]
> 使用系统代理的话，可以试着将 dota 相关域名放到 bypass 中。
> 
> 而且如果不勾选系统代理，而且没有使用 tun 的话，日志看不到 dota 相关请求的话，应该没有走 CFW。建议检查系统代理是否被修改。

刚才使用昨天的方法尝试，发现可以正常连接，怀疑是昨天系统环境有点问题，感谢

**Comment by wttanny** [comment]
> 已经尝试打开软件，选择direct以及不勾选系统代理，依旧无法连接国服进行游戏 使用其他代理工具，例如v2rayN是正常的
你好，我是新手，目前也遇到这个问题，请问你是怎么解决的
