### ISSUE TITLE
手机怎么切换节点

### ISSUE THREAD

**Issue by yonheng** [Fndroid/clash_for_windows_pkg#2288]
有什么办法能令手机通过局域网来切换电脑里clash for win的节点

**Comment by yi-Xu-0100** [comment]
我记得可以将 external-controller 设置为0.0.0.0：端口号。这样局域网可以通过 webui 去控制。

如果不会弄，我还是建议个 CFA.

**Comment by yonheng** [comment]
问题是电脑本身都打不开web页面
