### ISSUE TITLE
开机自动启动未能最小化

### ISSUE THREAD

**Issue by NepPure** [Fndroid/clash_for_windows_pkg#2289]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

![image](https://user-images.githubusercontent.com/12379907/135949473-3baaf719-84a6-4adf-8d10-9646823cb904.png)

平台及版本号

![image](https://user-images.githubusercontent.com/12379907/135949515-4e1aa86a-982f-42b4-a1e0-a7bf54f7895c.png)

**描述**

更新后开机启动会显示界面，不会静默后台启动了，没有找到开机启动最小化的选项

**复现**

1. 设置开机自动启动
2. 重启电脑

**预期行为**

开机启动并最小化，或者后台静默开机自动启动

**日志**

无

**截图**

**其他说明**

**Comment by yi-Xu-0100** [comment]
setting 里打开 slient start

**Comment by NepPure** [comment]
原来如此 谢谢！
