### ISSUE TITLE
报错 yaml: line 218: could not find expected “:”

### ISSUE THREAD

**Issue by kid101x** [Fndroid/clash_for_windows_pkg#230]
今天改了下规则，拖拽进窗口导入配置后选择就报错这个，这一行删掉也没用，把217之后所有东西都删了才可以。
我需要补什么内容可以更好地反馈并解决？

**Comment by Fndroid** [comment]
这不是bug，是你配置格式不对。但是你也没提供错误配置，所以无法帮你指出来

**Comment by kid101x** [comment]
感谢回复我已经找到原因。我之前用Excel过滤规则并复制粘贴进yml文件，问题出在这几条里。
非常感谢。
