### ISSUE TITLE
为Linux版本发布appimage格式软件包

### ISSUE THREAD

**Issue by lumingzh** [Fndroid/clash_for_windows_pkg#2300]
**描述**
为Linux版本发布appimage格式的软件包，appimage是类似苹果dmg的单文件捆绑软件包，无需解压直接运行，使用更方便。

**其他说明**
https://appimage.org/

**Comment by xlbetter** [comment]
现在你们在linux中更新clash是怎么操作的？

**Comment by lumingzh** [comment]
> 现在你们在linux中更新clash是怎么操作的？

下载、解压、覆盖。

其实对于我个人，我更希望以[flatpak](https://flatpak.org/)方式发布到[flathub.org](https://flathub.org/home)上：

- 对于软件开发者，可以利用构建机器人和更新发布脚本，实现从新版本编译打包到flathub更新发布的全流程自动化执行。
- 对于用户，可以实现在所有配置flatpak的linux发行版上一键安装，自动更新。

**Comment by yswtrue** [comment]
希望能早点出appimage或者flatapk的包，自己下载安装比较麻烦，aur更新也不及时

**Comment by lumingzh** [comment]
看到 flathub 上新出现了 clash for windows 是 @Fndroid 发布的吗？

**Comment by lumingzh** [comment]
> 看到 flathub 上新出现了 clash for windows 是 @Fndroid 发布的吗？

看起来不是作者发布的，[@qvshuo](https://github.com/qvshuo)。

**Comment by Sciroccogti** [comment]
> > 看到 flathub 上新出现了 clash for windows 是 @Fndroid 发布的吗？
> 
> 看起来不是作者发布的，[@qvshuo](https://github.com/qvshuo)。

我这里这个 flathub 的好像目前用不起来，你们能用吗？我的一直是 Disconnected。

**Comment by yswtrue** [comment]
> > > 看到 flathub 上新出现了 clash for windows 是 @Fndroid 发布的吗？
> > 
> > 
> > 看起来不是作者发布的，[@qvshuo](https://github.com/qvshuo)。
> 
> 我这里这个 flathub 的好像目前用不起来，你们能用吗？我的一直是 Disconnected。

我也是disconnected

**Comment by lumingzh** [comment]
> > > > 看到 flathub 上新出现了 clash for windows 是 @Fndroid 发布的吗？
> > > 
> > > 
> > > 看起来不是作者发布的，[@qvshuo](https://github.com/qvshuo)。
> > 
> > 
> > 我这里这个 flathub 的好像目前用不起来，你们能用吗？我的一直是 Disconnected。
> 
> 我也是disconnected

我这可以正常使用。发行版：fedora silverblue 35

**Comment by yswtrue** [comment]
可能和arch分支有一些不兼容，我提了issue给作者了

**Comment by lumingzh** [comment]
开发者也不回应，那我就关闭这个提案了。

**Comment by lumingzh** [comment]
开发者也不回应，那我就关闭这个提案了。
