### ISSUE TITLE
如何启用tap模式

### ISSUE THREAD

**Issue by sceraser** [Fndroid/clash_for_windows_pkg#231]
在安装了tap虚拟网卡后，如何启用tap模式代理全局流量呢？

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/wiki/%E5%90%AF%E5%8A%A8TAP

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
