### ISSUE TITLE
clahs导致uplay无法连接

### ISSUE THREAD

**Issue by D3DSKELL** [Fndroid/clash_for_windows_pkg#2318]
![20211011111259](https://user-images.githubusercontent.com/40630732/136728932-d7bbf182-10b5-4d6a-8a11-79c70cb0ce16.png)

uplay走系统代理，之前是可以正常连网的，clahs更新后uplay就无法连上了，代理设置默认的，现在开了tun也没用

**Comment by DEiYdaIWVt** [comment]
同问题！
