### ISSUE TITLE
语言和功能

### ISSUE THREAD

**Issue by anyfeels** [Fndroid/clash_for_windows_pkg#2320]
希望能添加中文语言，实现单进程代理并能多节点同时代理不同进程。

问题：在线升级后升级的新版本会处于与现版本不同目录，而非替换旧版本。

**Comment by yi-Xu-0100** [comment]
clash 本身就需要一定的学习成本。可以找下教程看看。

第二个不太确定是否有人碰到，如果确实能复现，建议新开 issue 关闭当前。
