### ISSUE TITLE
TUN模式下观看b站直播会有大量连接

### ISSUE THREAD

**Issue by billowssun** [Fndroid/clash_for_windows_pkg#2322]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**
TUN模式下观看b站直播会有大量连接
[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
windows11
**描述**

[//]: # (请具体并清楚地描述遇到的问题)
开启TUN模式，看b站直播有大量连接
**复现**

[//]: # (请描述复现问题的步骤)

1开启TUN模式
2打开b站直播

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:56939 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:56945 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:56947 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:56949 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:56951 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:56953 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:56955 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:56957 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:56959 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:56961 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:56965 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:56967 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57009 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:56963 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57013 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57015 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57011 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57017 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57019 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57021 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57023 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57025 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57027 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57069 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57071 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57077 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57075 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57073 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57079 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57081 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57083 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57085 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57087 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57129 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57131 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57190 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57194 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57192 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57198 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57196 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57200 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57204 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57202 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57250 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57206 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57252 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"
time="2021-10-12T22:11:28+08:00" level=info msg="[UDP] 198.18.0.1:57208 --> stun.chat.bilibili.com:3478 match DomainSuffix(bilibili.com) using 🌏 国内媒体[DIRECT]"

[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/55521033/136972764-10d524be-2e26-47ff-a815-5c0f725bd526.png)
![image](https://user-images.githubusercontent.com/55521033/136972892-150233c5-ef6d-4c26-8913-43f952826aaa.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**
配置如下
![image](https://user-images.githubusercontent.com/55521033/136973006-c05349d4-8001-415c-8922-e0c578582cfb.png)
没有开wifi
[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
1. 所谓的汉化，就是对打包后的源码进行修改，那你能保证修改之后还能和原来的一样吗？
2. 对你来说，就是“加了个汉化文件”，对我来说，就是未经我同意强行修改版本，这些人本就未对我的软件有一点尊重，我还要花时间来处理这些本就是浪费时间的issue吗？
3. 发出来之前，`软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）`这个勾你是怎么能打的出手的？

**Comment by Karmylr** [comment]
这是bilibili的p2p上传，和clash for windows是否汉化没关系
