### ISSUE TITLE
希望对0.18.4开始配置选择选项卡内的的更多选项框弹出的判断进行更改

### ISSUE THREAD

**Issue by Solitaryender** [Fndroid/clash_for_windows_pkg#2338]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 10 21H1
**描述**

[//]: # (请具体并清楚地描述遇到的问题)
更新到0.18.4后Profiles选项卡中的更多选项框弹出太过诡异，鼠标一经移动到相应配置文件就弹出框，非常遮挡视线，并且有时鼠标移开也不会消失
**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'CFW Dashboard'
2. 点击'Profiles'
3. 在当前选项卡中移动鼠标
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)
除非点击按钮，否则并不弹出选项卡，或延迟弹出选项卡
**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![图片](https://user-images.githubusercontent.com/65836154/137620727-da6bd28e-5f96-4269-ad97-d141d8d2c0cb.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
下个版本改为点击弹出

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
