### ISSUE TITLE
windows11 设置为开机启动后，开机在前台自动打开

### ISSUE THREAD

**Issue by mikicomo** [Fndroid/clash_for_windows_pkg#2339]
**描述**
win10下如果设置为开机自启，clash会在后台启动，任务栏多一个icon托盘，然而升级到win11后，设置为开机启动后，会在用户ui前台弹出clash的窗口，每次需要手动关闭，希望能保持和win10一样的逻辑

**其他说明**
其他补充内容

**Comment by yi-Xu-0100** [comment]
setting 里 打开 slient start
