### ISSUE TITLE
Dial [Direct] Failed

### ISSUE THREAD

**Issue by nyaachen** [Fndroid/clash_for_windows_pkg#234]
Dial [Direct] Failed
EOF（timeout之类的）

报了一个下午的这种类型的错
本来以为是自己dns代理设置有问题
config.yml里面的dns设置清掉了，还是会发生

此外旧版本似乎没遇到过这个问题

**Comment by Fndroid** [comment]
关键的报错就别省略了

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
