### ISSUE TITLE
能代理UDP请求吗？

### ISSUE THREAD

**Issue by ssyangchn** [Fndroid/clash_for_windows_pkg#235]
请问是否支持代理UDP

**Comment by Fndroid** [comment]
socks5代理可以，节点添加udp:true

**Comment by ssyangchn** [comment]
> socks5代理可以，节点添加udp:true

可以添加ss和vmness节点支持udp嘛？用来代理游戏

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
