### ISSUE TITLE
clash无法识别版本号为0.14和0.14.1的wintun.dll

### ISSUE THREAD

**Issue by kingforme** [Fndroid/clash_for_windows_pkg#2350]
如果使用0.14和0.14.1的wintun.dll将无法创建适配器选项中无法出现clash tunnel虚拟网卡
最后可以使用的版本是wintun.dll 0.13
正常配置
![Snipaste_2021-10-19_19-16-05](https://user-images.githubusercontent.com/62692476/137899084-14234527-72fc-416d-b592-d6e3d271ba89.png)

0.13 wintun.dll
[wintun.zip](https://github.com/Fndroid/clash_for_windows_pkg/files/7372701/wintun.zip)
：

**Comment by Fndroid** [comment]
因为0.14 API改了
