### ISSUE TITLE
[Feature Request]: Profiles右键菜单Parsers无响应

### ISSUE THREAD

**Issue by OG-C** [Fndroid/clash_for_windows_pkg#2363]
### 功能描述

Profiles-右键-Parsers 无响应。
BUG里无法发帖，遂发在此。

**Comment by bimozhiyani** [comment]
18.6 我也有这个问题，但是settings里可以编辑

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
