### ISSUE TITLE
[Bug]: 启动崩溃

### ISSUE THREAD

**Issue by ssssssbbb** [Fndroid/clash_for_windows_pkg#2366]
### 功能描述
以下两台都是Win10 x64 1909
A机：从0.18.3升级到0.18.5，刚升完能打开，重启后再也打不开，后退回0.18.4正常，隔几天又试了0.18.5正常了，原因没查出来
B机：从0.18.4升级到0.18.5，刚升完能打开，重启后再也打不开，后退回0.18.4也不行，再退回0.18.3才可以，今天试了0.18.6也不行

试了清除config.yaml无效，甚至没到重新生成就闪退了。

以下是Log，感觉就是正常运行被掐断了，反映不出什么
[2021-10-29-143024.log](https://github.com/Fndroid/clash_for_windows_pkg/files/7439420/2021-10-29-143024.log)

以下是Crash Dump
[Clash for Windows.exe.9960.zip](https://github.com/Fndroid/clash_for_windows_pkg/files/7439422/Clash.for.Windows.exe.9960.zip)

另外：Users\用户名\AppData\Local\clash_win-updater这个位置每次覆盖安装后能否不生成installer.exe或自动清除啊，白占了110MB

### 其他内容
Bug模版无法发帖，HTTP400

**Comment by Glory-gg** [comment]
一样, 解决了吗?

**Comment by ssssssbbb** [comment]
新版解决了

> 一样, 解决了吗?

**Comment by ssssssbbb** [comment]
19.0又复现

**Comment by Glory-gg** [comment]
改个安装目录名就好了

**Comment by TheTychoStar** [comment]
我0.17刚升级0.19也出这个问题了，如果覆盖安装到旧版本路径就crash，换个路径或者目录名就可以正常启动。不知道什么原因。

**Comment by ssssssbbb** [comment]
19.1已解决
