### ISSUE TITLE
更新Profile同时,可否同步更新Providers....

### ISSUE THREAD

**Issue by FAST0888** [Fndroid/clash_for_windows_pkg#2368]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.18.6

### 操作系统

macOS amd64(Intel)

### 系统版本

Macox

### 问题描述

更新Profile同时,可否同步更新Proviers....而不是Proviers 每次程序重启或是更新GeoIp 或是程序重启启动进入的时候,Proviers 还是保持第一次配置文件导入时候留存的时间记录

### 复现步骤

以上问题,望解决

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
provider更新时，如果内容无变化，不会更改文件，则修改日期不变，表现为更新日期较早。并不是不检查更新。
