### ISSUE TITLE
[Q] 想问下开启 IPv6 有啥作用吗？

### ISSUE THREAD

**Issue by wenfangdu** [Fndroid/clash_for_windows_pkg#2369]
![image](https://user-images.githubusercontent.com/28700378/139571188-6c1cc0d2-5b0b-48d3-bd2f-eca194010850.png)

试了开启和关闭，似乎没啥区别，[文档](https://docs.cfw.lbyczf.com/contents/ui/general.html)上也没有提及这个功能。

**Comment by Fndroid** [comment]
本地没有ipv6就没影响，如果有，那关闭的话所有流量都只会用ipv4去连接

**Comment by luweijun1992** [comment]
> 本地没有ipv6就没影响，如果有，那关闭的话所有流量都只会用ipv4去连接

请问如果本地有IPv6环境，软件关闭IPv6选项，那是什么效果呢？
