### ISSUE TITLE
rules，能删能移不能改。

### ISSUE THREAD

**Issue by young-blood** [Fndroid/clash_for_windows_pkg#237]
说实话，其实没差，如果要重新整理规则，只需要，先打好草稿，添加完规则，再调整优先级。如改后，增加额外的计算，损失运行效率，得不偿失。同时，我也建议，规则越少越高效。

**Comment by Fndroid** [comment]
没有看明白你想表达什么

**Comment by young-blood** [comment]
先失礼一句。你注意你该看的部分

**Comment by Fndroid** [comment]
请问我该看什么

**Comment by young-blood** [comment]
我不讲废话。No offense to you. Now, I have a question. To be honest, are you joking?
