### ISSUE TITLE
请问如何添加自定义的DIRECT规则

### ISSUE THREAD

**Issue by refo2613** [Fndroid/clash_for_windows_pkg#2371]
请问如何添加自定义的DIRECT规则。

目前尝试的方法：
1. HOME FOLDER\PROFILES里，PROFILE的YAML文件修改，添加自定义的DIRECT规则。
有效。但是UPDATE PROFILE后，自定义的DIRECT规则就消失了。
2. SETTING -> SYSTEM PROXY ->BYPASS DOMAIN/IP
BYPASS下面增加需要DIRECT的完整域名。 （SYSTEM PROXY的TYPE是HTTP）
无效。

**Comment by yi-Xu-0100** [comment]
建议用 parser， https://docs.cfw.lbyczf.com/contents/parser.html

**Comment by refo2613** [comment]
> 
> 
> 建议用 parser， https://docs.cfw.lbyczf.com/contents/parser.html

非常感谢，搞定了！
