### ISSUE TITLE
[Bug]: 设置开机启动失败

### ISSUE THREAD

**Issue by hdmnba** [Fndroid/clash_for_windows_pkg#2372]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.18.6

### 操作系统

Windows x64

### 系统版本

win10专业版 20H2

### 问题描述

原来电脑上装的版本是17.1，设置了开机启动
### 后来从17.1更新到18.6（用Clash.for.Windows.Setup.0.18.6.exe覆盖安装）
安装时直接双击打开，中途报错，关闭后右键用管理员身份打开安装包，安装成功。
重启电脑后弹了个报错信息，发现clash没有自动启动，打开设置界面发现已经设置了开机启动，关闭开机启动，然后后重新打开开机启动开关，重启后依然弹错误信息。
### 多次重装后开机依然弹错误信息，无法开机启。（试过多个版本都不行）

![微信图片_20211031195945](https://user-images.githubusercontent.com/8556433/139582018-243e8414-4299-411b-be84-5e5d3a3ca76d.png
![微信图片_20211031200042](https://user-images.githubusercontent.com/8556433/139582036-7dfd61ec-93e5-41f4-9e24-90e1dd0810de.png)
)

### 复现步骤

全写问题描述里了。。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
感觉两次安装的位置是不是不一样，去任务管理器的启动项看看，开机自启的对应路径吧

**Comment by hdmnba** [comment]
两次安装的路径确实不一样，17.1装在C:\Program Files\clash\，18.6安装的时候我也把安装路径改成了这个C:\Program Files\clash(不记得末尾有没有加斜杠了)，最后18.6被装在C:\Program Files\clash\Clash for windows\里面。。。
安装中途报的错没仔细看，只记得有三个按钮“中止”“忽略”“取消”，我应该是点了“忽略”

**Comment by yi-Xu-0100** [comment]
@hdmnba 你去修改下启动项吧，或者去启动两个地方的CFW，取消下自启动试试

**Comment by hdmnba** [comment]
前两天我全卸载了，注册表都清了，然后重装了18.6，发现还是没好。。今天开机发现它启动了？！居然自己好了。。。可能是我系统有问题？不清楚了，反正好了就行。。。

发现18.6好像不是静默启动了，每次开机会弹clash主窗体，之前的版本是静默启动的，感觉静默启动会比较好

**Comment by yi-Xu-0100** [comment]
@hdmnba setting 里 打开 slient start

**Comment by SoTTT** [comment]
我个人的经验是如果你在程序属性中勾选了“以管理员身份运行”这一项的话，那它肯定不会自启动的（即使其他配置都是正确的），离大谱的是32位的程序是可以启动的，但64位的就不行（这是Windows的问题，和clash无关），但是在使用Clash Core那里的add firewall rules功能是需要管理员权限的，也许可以用任务计划程序注册一个在开机时用最高权限启动clash的任务来代替clash的开机自启动

**Comment by Hyalincry** [comment]
> 我个人的经验是如果你在程序属性中勾选了“以管理员身份运行”这一项的话，那它肯定不会自启动的（即使其他配置都是正确的），离大谱的是32位的程序是可以启动的，但64位的就不行（这是Windows的问题，和clash无关），但是在使用Clash Core那里的add firewall rules功能是需要管理员权限的，也许可以用任务计划程序注册一个在开机时用最高权限启动clash的任务来代替clash的开机自启动

不得不点个赞了，居然还有这么大离谱的事情，我取消了它的管理员权限就好了，感谢！

**Comment by Xigua7i** [comment]
> 我个人的经验是如果你在程序属性中勾选了“以管理员身份运行”这一项的话，那它肯定不会自启动的（即使其他配置都是正确的），离大谱的是32位的程序是可以启动的，但64位的就不行（这是Windows的问题，和clash无关），但是在使用Clash Core那里的add firewall rules功能是需要管理员权限的，也许可以用任务计划程序注册一个在开机时用最高权限启动clash的任务来代替clash的开机自启动

离谱，终于找到原因了

**Comment by Kitterato** [comment]
我也碰到了 默认勾选管理员就开机启动失败

**Comment by Hyalincry** [comment]
不要开启管理员启动就没事了
________________________________
发件人: Kitterato ***@***.***>
发送时间: 2023年9月14日 7:31
收件人: Fndroid/clash_for_windows_pkg ***@***.***>
抄送: Hyalincry ***@***.***>; Comment ***@***.***>
主题: Re: [Fndroid/clash_for_windows_pkg] [Bug]: 设置开机启动失败 (Issue #2372)


我也碰到了 默认勾选管理员就开机启动失败

―
