### ISSUE TITLE
[Bug]: wintun0.14.1版本 Clash无法创建虚拟网卡，且程序假死，无法加载Proxies界面

### ISSUE THREAD

**Issue by Mashiro-qwq** [Fndroid/clash_for_windows_pkg#2377]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.18.6

### 操作系统

Windows x64

### 系统版本

Windows 10 21H1 19043.1288

### 问题描述

wintun更新到0.14.1版本，我尝试将原本wintun0.13更新至0.14.1，结果程序假死，虚拟网卡无法创建

### 复现步骤

1.General主界面，关闭Mixin模式，点击Service Mods，点击Uninstall，等待软件重启

2.重启完毕再次打开General主界面，点击Open Floder打开程序配置目录，删除目录下wintun.dll，下载[wintun0.14.1](https://www.wintun.net/builds/wintun-0.14.1.zip)，将压缩包内 bin/amd64/wintun.dll 解压至原位置，回到软件General界面，点击Service Mods，点击Install，等待软件重启

3.重启后打开General主界面，打开Mixin模式，此时程序假死，约10s后左下角连接提示由绿色 `connected` 变为红色 `disconnected` ，同时开启System Proxy模式或者单独使用System Proxy模式也无法代理流量，点击Proxies界面，显示空白页面，无法加载节点信息，且假死无法切换代理模式，打开更改适配器选项界面，没有名为 `clash` 的虚拟网卡

重试上述步骤，更换[wintun0.14](https://www.wintun.net/builds/wintun-0.14.zip)版本问题依旧

重试上述步骤，更换[wintun0.13](https://www.wintun.net/builds/wintun-0.13.zip)版本问题解决，成功开启 `clash` 虚拟网卡

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
好像要等待 core 更新。

**Comment by castting** [comment]
你换成那个x86的就可以用了

**Comment by Mashiro-qwq** [comment]
> 你换成那个x86的就可以用了

算了不搞了，等更新支持吧

**Comment by Mashiro-qwq** [comment]
> 好像要等待 core 更新。

好的，那我不折腾了，等core更新后再升级

**Comment by Martin33357** [comment]
请问这个bug解决了吗

**Comment by Mashiro-qwq** [comment]
解决了，请更新CFW至最新版本即可

Martin33357 ***@***.***> 于2023年6月18日周日 14:27写道：
