### ISSUE TITLE
报错该如何解决

### ISSUE THREAD

**Issue by MESS8** [Fndroid/clash_for_windows_pkg#238]
configuration file ~/.config/clash/config（一串数字）.yml  is empty

**Comment by Fndroid** [comment]
配置文件被删除了，重新导入

**Comment by MESS8** [comment]
> 配置文件被删除了，重新导入

怎么导入啊

**Comment by Fndroid** [comment]
URL下载或者拖拽文件到Profiles里

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
