### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by huiruo** [Fndroid/clash_for_windows_pkg#2387]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.18.4

### 操作系统

Linux

### 系统版本

Ubuntu 21.04

### 问题描述

安装了软件，运行./cfw,然后从Profiles---->Downlod from a URL导入了配置，依然不能访问google(在windows使用相同配置是可以的)

### 复现步骤

安装了软件，运行./cfw,然后从Profiles---->Downlod from a URL导入了配置，依然不能访问google
![20211106-100127](https://user-images.githubusercontent.com/11364222/140594159-8bedd410-72a0-44ad-8349-19e168b753ff.png)
![20211106-100137](https://user-images.githubusercontent.com/11364222/140594164-4e1299b5-d8d2-4c18-a14a-32630ccc11e8.png)

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
日志？

**Comment by huiruo** [comment]
没看到日记
![20211106-111305](https://user-images.githubusercontent.com/11364222/140596124-c47ee868-99cb-46ec-b0a9-21600d7ae6cb.png)

**Comment by yi-Xu-0100** [comment]
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴到这里

**Comment by Fndroid** [comment]
linux没有统一的系统代理概念，要么自己给桌面设置代理，要么开tun模式

**Comment by huiruo** [comment]
> linux没有统一的系统代理概念，要么自己给桌面设置代理，要么开tun模式

你好，请问在linux clash,系统代理配什么域名和端口？

**Comment by huiruo** [comment]
> > linux没有统一的系统代理概念，要么自己给桌面设置代理，要么开tun模式
> 
> 你好，请问在linux clash,系统代理配什么域名和端口？

刚在全局配置了，7890端口貌似可以了，感谢
