### ISSUE TITLE
Could the software provide the accumulated downloaded  amount in MBs ?

### ISSUE THREAD

**Issue by tengyuhuo** [Fndroid/clash_for_windows_pkg#239]
The software now presents the connection time, download speed and upload speed. But, I cant know how many MBs I have used in a single day. It would be nice to have this function on the software interface. Thanks.

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
