### ISSUE TITLE
[Feature Request]: 关机时自动关闭代理

### ISSUE THREAD

**Issue by Jxpro** [Fndroid/clash_for_windows_pkg#2395]
### 功能描述

- 希望CFW关机的时候可以**自动关闭一下系统代理**，等开机的时候再重新开启代理
- 不然就会导致开机时CFW自启动的时间比较慢时，CFW启动前，打开浏览器会显示`代理服务器出现错误`
![}@6MWW%B71_V6)0T6P@ AET](https://user-images.githubusercontent.com/87376573/141024148-429b0597-8b9c-44d6-8a81-0ffb448dcc72.png)

### 其他内容
**非常感谢大佬，辛苦您了**

**Comment by yi-Xu-0100** [comment]
无法设置，CFW感知不到关机，建议设置为 pac 模式

**Comment by Jxpro** [comment]
PAC模式也会一样，在clash没有自启之前，有无法访问互联网的问题

**Comment by yi-Xu-0100** [comment]
@Jxpro 感觉不太应该，你的 pac 配置啥样？

**Comment by Jxpro** [comment]
默认的，我没改过

**Comment by yi-Xu-0100** [comment]
@Jxpro 所以点开看看是啥

**Comment by Jxpro** [comment]
像这样的，全部规则太长了，截不下来
![image](https://user-images.githubusercontent.com/87376573/141240925-989c6219-6e7f-4d1c-97d4-f7b835b270ae.png)

**Comment by yi-Xu-0100** [comment]
@Jxpro 
![图片](https://user-images.githubusercontent.com/25523606/141283639-7c79cea3-4d06-4d7b-8542-df54e205dc12.png)

改到 pac 试试，不行，贴出里面的内容

**Comment by Jxpro** [comment]
试了以后不可以，然后内容是这样的，应该改成什么好？
![image](https://user-images.githubusercontent.com/87376573/141402557-2bbcdc27-57df-4492-9f3d-a51c8a165f26.png)

**Comment by yi-Xu-0100** [comment]
@Jxpro 我用的 pac 是可行的，你单纯设置 pac，不设置自启动，然后看重启后，电脑无法访问网页给出的错误信息是啥？

**Comment by Jxpro** [comment]
@yi-Xu-0100 就是上面那张图，代理服务器出现错误
![image](https://user-images.githubusercontent.com/87376573/141439224-375d94ee-5e08-49ed-9ed5-8c0d4d690aa8.png)

**Comment by Jxpro** [comment]
可以了，我不设置自启动以后就没有错误了，然后我现在过了大半天把自启动再打开，现在也没问题了，谢谢大佬！
