### ISSUE TITLE
[Feature Request]: 希望设置系统代理可配置是否使用127.0.0.1地址

### ISSUE THREAD

**Issue by nekojp** [Fndroid/clash_for_windows_pkg#2397]
### 功能描述

希望给个选项或配置使切换系统代理用本机IP(192.168.2.2)来取代127.0.0.1作为连接地址。

### 其他内容

Windows
使用127.0.0.1会导致原本被系统防火墙禁止出站流量的软件获得网络访问权限。
若用本机ip，比如192.168.1.2，就没这个问题。

或者设置系统代理前先检测IE浏览器里的设置，若原来是IP是本机且正常访问就不改它。
例子，本来系统代理是192.168.1.2:7890，且可正常连接，就不改这部份。

是可以写规则按软件名称拦截，但是难免会有切换到全局模式的时候。谢谢～

_No response_

**Comment by Fndroid** [comment]
settings里的static host设置成你ip就行
