### ISSUE TITLE
添加 Proxy Group 后报错无法连接

### ISSUE THREAD

**Issue by daomeideshu** [Fndroid/clash_for_windows_pkg#24]
在 **Manage** 添加 **Proxy Group** 到第四个的时候，点击保存就 ‘Disconnected to Clash’，删除后保存恢复连接。
日志

`panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x68f5b5]

goroutine 1 [running]:
github.com/Dreamacro/clash/adapters/outbound.(*Selector).Name(0x0, 0xc0001da210, 0xc000011aa0)
	/home/travis/gopath/src/github.com/Dreamacro/clash/adapters/outbound/selector.go:22 +0x5
github.com/Dreamacro/clash/adapters/outbound.NewSelector(0x7d7215, 0x6, 0xc0001fa800, 0x29, 0x40, 0xc0001fa800, 0x20, 0x40)
	/home/travis/gopath/src/github.com/Dreamacro/clash/adapters/outbound/selector.go:62 +0x81
github.com/Dreamacro/clash/config.(*Config).parseProxies(0xc000034300, 0xc0000a62c0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/Dreamacro/clash/config/config.go:357 +0x1736
github.com/Dreamacro/clash/config.(*Config).Parse(0xc000034300, 0xc000065f30, 0x4d0da6)
	/home/travis/gopath/src/github.com/Dreamacro/clash/config/config.go:126 +0x88
main.main()
	/home/travis/gopath/src/github.com/Dreamacro/clash/main.go:42 +0xd7`

请问要如何解决？

**Comment by Fndroid** [comment]
Group里面有节点吗，Save的时候
