### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mjj-projects** [Fndroid/clash_for_windows_pkg#2401]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.18.7

### 操作系统

macOS amd64(Intel)

### 系统版本

12.0.1 (21A559)

### 问题描述

点击`Download`按钮，显示：Http Response Status Code(400)

### 复现步骤

在应用中的`Profiles`选项，填写订阅地址，然后点击`Download`按钮，显示：Http Response Status Code(400)

**Comment by yi-Xu-0100** [comment]
https://www.google.com/search?q=400+%E9%94%99%E8%AF%AF

**Comment by shikkoku** [comment]
因为你的订阅文件格式非法。你试着用浏览器打开你的订阅连接看看有没有东西在？
