### ISSUE TITLE
[Bug]: 不启用系统代理无法访问一部分国内网站

### ISSUE THREAD

**Issue by bluesWalker** [Fndroid/clash_for_windows_pkg#2403]
信息

- [x]  已经从issue搜索过类似问题，发现一个类似问题但没有得到解决
- [x]  已经阅读过文档相关问题，并未找到解决办法
- [x]  已经尝试更新到最新版本，问题依旧存在
- [x]  软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

系统

Windows10 家庭版 21H1

描述

近期发现在关闭系统代理的情况下，部分国内网站（如知乎）无法访问。开启系统代理后可以访问（即便在全部流量走DIRECT的情况下）。使用TUN模式。发现时为0.18.7版本，目前是0.18.8版本。在无法访问网站的时候浏览器报错为ERR_TIMED_OUT但此时任能够ping通该网站。

另外注意到无法访问的网站在ping的时候解析到的都是IPv6地址

复现

关闭系统代理并访问www.zhihu.com：浏览器报错ERR_TIMED_OUT
此时执行ping www.zhihu.com

正在 Ping 1595096.sched.d0-dk.tdnsv5.com [240e:96c:6200:400:3d::] 具有 32 字节的数据:
来自 240e:96c:6200:400:3d:: 的回复: 时间=5ms
来自 240e:96c:6200:400:3d:: 的回复: 时间=4ms
来自 240e:96c:6200:400:3d:: 的回复: 时间=3ms
来自 240e:96c:6200:400:3d:: 的回复: 时间=3ms

240e:96c:6200:400:3d:: 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 3ms，最长 = 5ms，平均 = 3ms

启用系统代理后问题解决。

**Comment by yi-Xu-0100** [comment]
@bluesWalker 关闭系统代理，然后用 tun 吗？最好看看日志。还有试着用无痕模式查看网页，看下日志有没啥

ping 好像没啥用。用 curl 才有可能走 CFW。

**Comment by bluesWalker** [comment]
> @bluesWalker 关闭系统代理，然后用 tun 吗？最好看看日志。还有试着用无痕模式查看网页，看下日志有没啥
> 
> ping 好像没啥用。用 curl 才有可能走 CFW。

抱歉我可能描述的不够准确。这方面我不是很懂，我指的是Service Mode激活并显示绿色小地球图标，平时这个是一直打开的。

无痕模式依然无法访问。日志级别是debug，关闭系统代理时访问没有任何log信息，打开系统代理时访问知乎有如下记录
![image](https://user-images.githubusercontent.com/6717570/141479365-015cd2b9-26f2-45b5-8aca-bdb5c7b463d9.png)

**Comment by yi-Xu-0100** [comment]
@bluesWalker 没有日志，应该没进 CFW 吧，可以试着关闭 CFW 看看如何？去 右下角点 connected 查看日志。

**Comment by uuip** [comment]
<img width="663" alt="2021-11-14_000023" src="https://user-images.githubusercontent.com/16631174/141650589-53e4eb12-2f92-4698-b066-9f8b842a6309.png">

你确认tun模式开启成功了吗？另外你得禁用ipv6
tun模式下的ping实际是ping的clash，不是远程地址。

**Comment by bigbaldy1128** [comment]
问题一样，18.6以前没有这个问题

**Comment by bluesWalker** [comment]
> @bluesWalker 没有日志，应该没进 CFW 吧，可以试着关闭 CFW 看看如何？去左下角点 connected 查看日志。

我排查了以后发现应该不是clash的问题，是我最近新开通的电信国际精品网的锅。问了电信说是IPv6地址和精品网线路有冲突，目前在联系电信那边解决了。

感谢答复！

**Comment by bluesWalker** [comment]
> <img alt="2021-11-14_000023" width="663" src="https://user-images.githubusercontent.com/16631174/141650589-53e4eb12-2f92-4698-b066-9f8b842a6309.png">
> 
> 你确认tun模式开启成功了吗？另外你得禁用ipv6 tun模式下的ping实际是ping的clash，不是远程地址。

排查了以后应该不是clash的问题，是电信国际精品网的锅。感谢建议！
