### ISSUE TITLE
希望能把节点配置文件放在安装目录下

### ISSUE THREAD

**Issue by fqdssr** [Fndroid/clash_for_windows_pkg#2406]
### 功能描述

感谢作者。翻墙很快！
希望能把节点等配置文件放在软件目录下。
就是像ShadowSocksR、v2rayN那样，能便携打包带走到另一台电脑，而不用每到一台新电脑就从新设置。
目前配置文件在C盘，把软件传给别人还要另传一份配置文件，很不方便。

**Comment by akw5454521** [comment]
.config这个文件夹应该是按照上游的设置

**Comment by VinKang** [comment]
这个只是部分需求吧，我觉得分开存放挺好的。要不整个自定义目录也行

**Comment by yi-Xu-0100** [comment]
本身支持自定义 profile

![图片](https://user-images.githubusercontent.com/25523606/141646492-d9ba8694-f258-4fea-bc66-970b2376af79.png)

或者用便携模式：
https://docs.cfw.lbyczf.com/contents/7z.html#%E4%BE%BF%E6%90%BA%E6%A8%A1%E5%BC%8F

**Comment by shikkoku** [comment]
明明有便携模式……
