### ISSUE TITLE
配置中的external-controller地址无效

### ISSUE THREAD

**Issue by BruceLee569** [Fndroid/clash_for_windows_pkg#2409]
配置文件中有开启 external-controller: 127.0.0.1:9090

但是cfw中启用配置后，该端口并没有被启用监听控制，查了cfw的端口，发现是一个动态端口。

请问怎样将其设置为静态端口？配置里的端口没有被占用，为什么不让他生效呢？

有时候通过浏览器来控制clash面板更加方便，或者自己调用外部控制时，都需要用到这个。

**Comment by yi-Xu-0100** [comment]
setting 里关闭 random controller port

**Comment by BruceLee569** [comment]
> setting 里关闭 random controller port

呃呃，没注意到这个选项，谢啦！🤣

**Comment by BruceLee569** [comment]
> setting 里关闭 random controller port

刚关了动态端口，但依然是由cfw生成的某个端口，而不是配置文件里的9090。。。

不能自己指定一个端口么？

**Comment by yi-Xu-0100** [comment]
@BruceLee569 在 home directory 的 config.yaml 中指定。

**Comment by BruceLee569** [comment]
> @BruceLee569 在 home directory 的 config.yaml 中指定。

懂了，非常感谢！☺
