### ISSUE TITLE
请问能不能在开机的时候自动开启局域网共享

### ISSUE THREAD

**Issue by NZESupB** [Fndroid/clash_for_windows_pkg#241]
现在每次开机都要自己手动打开

**Comment by Fndroid** [comment]
General - Edit General (Text Mode Edit) - 将配置文件中 allow-lan 从 false 改成 true

**Comment by NZESupB** [comment]
> General - Edit General (Text Mode Edit) - 将配置文件中 allow-lan 从 false 改成 true

好的,感谢
