### ISSUE TITLE
[Bug]：Mini List Width设置为0时，Settings下的Mini List Width未隐藏

### ISSUE THREAD

**Issue by returnL** [Fndroid/clash_for_windows_pkg#2410]
**软件版本**
0.18.8

**操作系统**
Windows x64

**系统版本**
Windows 11 21H2

**问题描述**
Mini List Width设置为0时，Settings下的Mini List Width未隐藏，如下图所示![IMG_20211114_091136_398.png](https://user-images.githubusercontent.com/44701395/141663824-d8fec138-f4a0-4854-9e32-9b704232f8b1.png)

**复现步骤**
Mini List Width设置为0

**其他补充**
在网页端使用模板提交issue时会在提交时显示HTTP 400，希望能改一下模板设置

**Comment by yi-Xu-0100** [comment]
这是 proxies 的，不是 setting 的

**Comment by returnL** [comment]
> 
> 
> 这是 proxies 的，不是 setting 的

我非常确定它是Settings的
![图片](https://user-images.githubusercontent.com/44701395/141667923-ce1e5ae0-34f6-4970-8c70-e774847461ff.png)

**Comment by yi-Xu-0100** [comment]
@returnL 我是说，现在的这个设置项是给 proxies 里的 list 设置的。不是给 setting 设置的。还没有这个设置。

**Comment by returnL** [comment]
> 
> 
> @returnL 我是说，现在的这个设置项是给 proxies 里的 list 设置的。不是给 setting 设置 list 宽度的。还没有这个设置。得看情况是否提供支持。
> 
> 现在的 setting 确实也很长了。

但是Mini List修改为0确实对Settings的Mini List有影响，你自己试下就知道了。而且就像我上面说的“或者说Settings本不应该有Mini List但是在0.18.8里面出现了，并且没有办法正常隐藏”，总之这个现象称之为Bug应该不为过

**Comment by returnL** [comment]
![动画](https://user-images.githubusercontent.com/44701395/141670701-672c68e6-1198-4f5a-b9f6-5cccf1ed809e.gif)

**Comment by Ben-md5** [comment]
+1，可以复现

**Comment by yi-Xu-0100** [comment]
@returnL 现在懂了，前面确实没有测试，只是看了 issue 的描述，没理解到错误是啥。

**Comment by codafi21** [comment]
抽搐+1
