### ISSUE TITLE
[Bug]: 0.18.8版本引起Python的pip联网失败

### ISSUE THREAD

**Issue by LeslieYon** [Fndroid/clash_for_windows_pkg#2411]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.18.8

### 操作系统

Windows x64

### 系统版本

21H1

### 问题描述

![image](https://user-images.githubusercontent.com/43743875/141711041-38d7b3d6-e5d3-486f-9e55-f1bc44a07499.png)

打开系统代理时，pip网络连接失败  
打开设置中的Specify Protocol时，问题消失（旧版本并不需要如此）  

### 复现步骤

打开系统代理时，使用pip安装软件

**Comment by returnL** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/1787
Specify Protocol就是为了解决这个问题的呀，这个不算bug吧
