### ISSUE TITLE
[Bug]: 初始化错误：不支持密码（cipher not supported）

### ISSUE THREAD

**Issue by Emt-lin** [Fndroid/clash_for_windows_pkg#2413]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.18.8

### 操作系统

macOS amd64(Intel)

### 系统版本

12.0.1

### 问题描述

最近的版本出现的，不知道是否是自己的问题。
不知道是否和 issue #323 问题一样
![image](https://user-images.githubusercontent.com/41323133/141768085-ec864b6c-7ba7-4b0a-a9bf-c0c8d9692f06.png)

### 复现步骤

无

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
应该是吧，把那个 proxies 删掉试试。

**Comment by Emt-lin** [comment]
@yi-Xu-0100 果然还是那个问题。-_-，谢了。
