### ISSUE TITLE
[Bug]: connect error: interface not found"

### ISSUE THREAD

**Issue by joshuawm** [Fndroid/clash_for_windows_pkg#2418]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.18.8

### 操作系统

Windows x64

### 系统版本

21H1

### 问题描述

所有网站均无法访问，访问网页浏览器均显示：

嗯… 无法访问此页面已重置连接。
请尝试：

检查连接
检查代理和防火墙
运行 Windows 网络诊断
ERR_CONNECTION_RESET

### 复现步骤

1 打开clash
2 打开chrome或者edge
3 如果clash没开代理就用SwitchyOmega连接对应的clash端口，e.g. 127.0.0.1:7891 ,开启系统代理的话就是SwitchyOmega的系统代理
4 网页均无法访问

### 日志文件

time="2021-11-17T10:27:57+08:00" level=info msg="RESTful API listening at: 127.0.0.1:52637"
time="2021-11-17T10:27:57+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7891"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial provider PaoLu"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial provider OWN"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial compatible provider Direct"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial compatible provider rejectio"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider China"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider HBO Max"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider Hulu"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider Netflix"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider Friday"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider myVideo"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider ChinaIP"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider WETV"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider IQ"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider PBS"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider CATCHPLAY+"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider Paramount+"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider Amazon Prime Video"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider TikTok"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider Telegram"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider LINE TV"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider Viu"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider Spotify"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider KKTV KKBOX"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider Global"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider Disney+"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider Ad"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider IQIYI"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider HBO GO"
time="2021-11-17T10:27:58+08:00" level=info msg="Start initial rule provider Peacock"
time="2021-11-17T10:28:22+08:00" level=debug msg="[DNS] beacons.gcp.gvt2.com --> 114.250.65.34"
time="2021-11-17T10:28:22+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:22+08:00" level=warning msg="[TCP] dial Direct (match GeoIP/CN) to beacons.gcp.gvt2.com:443 error: interface not found"
time="2021-11-17T10:28:22+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:22+08:00" level=debug msg="[DNS] beacons.gcp.gvt2.com --> 114.250.65.34"
time="2021-11-17T10:28:22+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:22+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:22+08:00" level=warning msg="[TCP] dial Direct (match GeoIP/CN) to beacons.gcp.gvt2.com:443 error: interface not found"
time="2021-11-17T10:28:23+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:23+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:23+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:23+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:23+08:00" level=debug msg="[DNS] beacons.gvt2.com --> 114.250.68.34"
time="2021-11-17T10:28:23+08:00" level=warning msg="[TCP] dial Direct (match GeoIP/CN) to beacons.gvt2.com:443 error: interface not found"
time="2021-11-17T10:28:23+08:00" level=debug msg="[DNS] beacons.gvt2.com --> 114.250.68.34"
time="2021-11-17T10:28:23+08:00" level=warning msg="[TCP] dial Direct (match GeoIP/CN) to beacons.gvt2.com:443 error: interface not found"
time="2021-11-17T10:28:24+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:24+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:24+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:24+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:24+08:00" level=debug msg="[DNS] beacons2.gvt2.com --> 203.208.39.226"
time="2021-11-17T10:28:24+08:00" level=warning msg="[TCP] dial Direct (match GeoIP/CN) to beacons2.gvt2.com:443 error: interface not found"
time="2021-11-17T10:28:24+08:00" level=debug msg="[DNS] beacons2.gvt2.com --> 203.208.39.226"
time="2021-11-17T10:28:24+08:00" level=warning msg="[TCP] dial Direct (match GeoIP/CN) to beacons2.gvt2.com:443 error: interface not found"
time="2021-11-17T10:28:24+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:24+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:24+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:24+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:24+08:00" level=debug msg="[DNS] beacons3.gvt2.com --> 114.250.67.34"
time="2021-11-17T10:28:24+08:00" level=warning msg="[TCP] dial Direct (match GeoIP/CN) to beacons3.gvt2.com:443 error: interface not found"
time="2021-11-17T10:28:24+08:00" level=debug msg="[DNS] beacons3.gvt2.com --> 114.250.67.34"
time="2021-11-17T10:28:24+08:00" level=warning msg="[TCP] dial Direct (match GeoIP/CN) to beacons3.gvt2.com:443 error: interface not found"
time="2021-11-17T10:28:24+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:24+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:24+08:00" level=debug msg="[DNS] browser.events.data.microsoft.com --> 20.42.72.131"
time="2021-11-17T10:28:24+08:00" level=warning msg="[TCP] dial Global (match Match/) to browser.events.data.microsoft.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:24+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:24+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:24+08:00" level=debug msg="[DNS] browser.events.data.microsoft.com --> 20.42.72.131"
time="2021-11-17T10:28:24+08:00" level=warning msg="[TCP] dial Global (match Match/) to browser.events.data.microsoft.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:24+08:00" level=debug msg="[DNS] beacons4.gvt2.com --> 216.239.32.116"
time="2021-11-17T10:28:24+08:00" level=warning msg="[TCP] dial Global (match Match/) to beacons4.gvt2.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:24+08:00" level=debug msg="[DNS] beacons4.gvt2.com --> 216.239.32.116"
time="2021-11-17T10:28:24+08:00" level=warning msg="[TCP] dial Global (match Match/) to beacons4.gvt2.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:24+08:00" level=debug msg="[DNS] browser.events.data.microsoft.com --> 20.42.72.131"
time="2021-11-17T10:28:24+08:00" level=warning msg="[TCP] dial Global (match Match/) to browser.events.data.microsoft.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:24+08:00" level=debug msg="[DNS] browser.events.data.microsoft.com --> 20.42.72.131"
time="2021-11-17T10:28:24+08:00" level=warning msg="[TCP] dial Global (match Match/) to browser.events.data.microsoft.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:24+08:00" level=debug msg="[DNS] beacons5.gvt2.com --> 216.239.32.116"
time="2021-11-17T10:28:24+08:00" level=warning msg="[TCP] dial Global (match Match/) to beacons5.gvt2.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:24+08:00" level=debug msg="[DNS] beacons5.gvt2.com --> 216.239.32.116"
time="2021-11-17T10:28:24+08:00" level=warning msg="[TCP] dial Global (match Match/) to beacons5.gvt2.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:25+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:25+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:25+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:25+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:25+08:00" level=debug msg="[DNS] beacons5.gvt3.com --> 203.208.50.162"
time="2021-11-17T10:28:25+08:00" level=warning msg="[TCP] dial Direct (match GeoIP/CN) to beacons5.gvt3.com:443 error: interface not found"
time="2021-11-17T10:28:25+08:00" level=debug msg="[DNS] beacons5.gvt3.com --> 203.208.50.162"
time="2021-11-17T10:28:25+08:00" level=warning msg="[TCP] dial Direct (match GeoIP/CN) to beacons5.gvt3.com:443 error: interface not found"
time="2021-11-17T10:28:25+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:25+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:25+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:25+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:25+08:00" level=debug msg="[DNS] clients2.google.com --> 142.250.204.142"
time="2021-11-17T10:28:25+08:00" level=warning msg="[TCP] dial Global (match Match/) to clients2.google.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:25+08:00" level=debug msg="[DNS] clients2.google.com --> 142.250.204.142"
time="2021-11-17T10:28:25+08:00" level=warning msg="[TCP] dial Global (match Match/) to clients2.google.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:25+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:25+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:25+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:25+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:26+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:26+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:26+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:26+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37418 connect error: interface not found"
time="2021-11-17T10:28:33+08:00" level=debug msg="[DNS] clients4.google.com --> 142.250.204.142"
time="2021-11-17T10:28:33+08:00" level=warning msg="[TCP] dial Global (match Match/) to clients4.google.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:28:33+08:00" level=debug msg="[DNS] clients4.google.com --> 142.250.204.142"
time="2021-11-17T10:28:33+08:00" level=warning msg="[TCP] dial Global (match Match/) to clients4.google.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37310 connect error: interface not found"
time="2021-11-17T10:28:33+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:33+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37276 connect error: interface not found"
time="2021-11-17T10:28:33+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:33+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37311 connect error: interface not found"
time="2021-11-17T10:28:34+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:34+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37393 connect error: interface not found"
time="2021-11-17T10:28:34+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:34+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37411 connect error: interface not found"
time="2021-11-17T10:28:34+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:34+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37230 connect error: interface not found"
time="2021-11-17T10:28:34+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:34+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cu-moe.ikc3549ol1w65zbm.xyz:37244 connect error: interface not found"
time="2021-11-17T10:28:34+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:34+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: jscm1.cosmic-love.xyz:37080 connect error: interface not found"
time="2021-11-17T10:28:34+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:34+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37374 connect error: interface not found"
time="2021-11-17T10:28:34+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:34+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37057 connect error: interface not found"
time="2021-11-17T10:28:34+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:34+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: kobayashi.cosmic-love.xyz:37346 connect error: interface not found"
time="2021-11-17T10:28:34+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:34+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: 116.163.10.151:20302 connect error: interface not found"
time="2021-11-17T10:28:34+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:34+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: 116.163.10.151:20301 connect error: interface not found"
time="2021-11-17T10:28:35+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:35+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:28:35+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:35+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:28:43+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:43+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:28:43+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:43+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:28:44+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:44+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:28:44+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:44+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:28:45+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:45+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:28:45+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:45+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:28:50+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:50+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:28:50+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:50+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:28:51+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:51+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:28:51+08:00" level=debug msg="[DNS] www.v2ex.com --> 31.13.69.245"
time="2021-11-17T10:28:51+08:00" level=warning msg="[TCP] dial Global (match Match/) to www.v2ex.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:34:51+08:00" level=debug msg="[DNS] ping.cloud.tencent.com --> 119.29.44.247"
time="2021-11-17T10:34:51+08:00" level=debug msg="[DNS] cloud.tencent.com --> 211.91.160.249"
time="2021-11-17T10:34:51+08:00" level=debug msg="[DNS] nleditor.osi.office.net --> 52.109.52.15"
time="2021-11-17T10:34:51+08:00" level=warning msg="[TCP] dial Global (match Match/) to nleditor.osi.office.net:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:34:51+08:00" level=warning msg="[TCP] dial Direct (match RuleSet/China) to ping.cloud.tencent.com:443 error: interface not found"
time="2021-11-17T10:34:51+08:00" level=warning msg="[TCP] dial Direct (match RuleSet/China) to cloud.tencent.com:443 error: interface not found"
time="2021-11-17T10:34:51+08:00" level=debug msg="[DNS] cloud.tencent.com --> 211.91.160.249"
time="2021-11-17T10:34:51+08:00" level=debug msg="[DNS] nleditor.osi.office.net --> 52.109.52.21"
time="2021-11-17T10:34:51+08:00" level=warning msg="[TCP] dial Direct (match RuleSet/China) to cloud.tencent.com:443 error: interface not found"
time="2021-11-17T10:34:51+08:00" level=debug msg="[DNS] ping.cloud.tencent.com --> 119.29.44.247"
time="2021-11-17T10:34:51+08:00" level=warning msg="[TCP] dial Global (match Match/) to nleditor.osi.office.net:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:34:51+08:00" level=warning msg="[TCP] dial Direct (match RuleSet/China) to ping.cloud.tencent.com:443 error: interface not found"
time="2021-11-17T10:34:51+08:00" level=debug msg="[DNS] sensors.cloud.tencent.com --> 157.148.32.174"
time="2021-11-17T10:34:51+08:00" level=warning msg="[TCP] dial Direct (match RuleSet/China) to sensors.cloud.tencent.com:8106 error: interface not found"
time="2021-11-17T10:34:51+08:00" level=debug msg="[DNS] sensors.cloud.tencent.com --> 157.148.32.174"
time="2021-11-17T10:34:51+08:00" level=warning msg="[TCP] dial Direct (match RuleSet/China) to sensors.cloud.tencent.com:8106 error: interface not found"
time="2021-11-17T10:34:52+08:00" level=debug msg="[DNS] cloud.tencent.com --> 211.91.160.249"
time="2021-11-17T10:34:52+08:00" level=warning msg="[TCP] dial Direct (match RuleSet/China) to cloud.tencent.com:443 error: interface not found"
time="2021-11-17T10:34:52+08:00" level=debug msg="[DNS] cloud.tencent.com --> 211.91.160.249"
time="2021-11-17T10:34:52+08:00" level=warning msg="[TCP] dial Direct (match RuleSet/China) to cloud.tencent.com:443 error: interface not found"
time="2021-11-17T10:34:53+08:00" level=debug msg="[DNS] browser.events.data.microsoft.com --> 104.46.162.224"
time="2021-11-17T10:34:53+08:00" level=warning msg="[TCP] dial Global (match Match/) to browser.events.data.microsoft.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:34:53+08:00" level=debug msg="[DNS] browser.events.data.microsoft.com --> 104.46.162.224"
time="2021-11-17T10:34:53+08:00" level=warning msg="[TCP] dial Global (match Match/) to browser.events.data.microsoft.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:34:53+08:00" level=debug msg="[DNS] browser.events.data.microsoft.com --> 104.46.162.224"
time="2021-11-17T10:34:53+08:00" level=warning msg="[TCP] dial Global (match Match/) to browser.events.data.microsoft.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:34:53+08:00" level=debug msg="[DNS] browser.events.data.microsoft.com --> 104.46.162.224"
time="2021-11-17T10:34:53+08:00" level=warning msg="[TCP] dial Global (match Match/) to browser.events.data.microsoft.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:35:02+08:00" level=debug msg="[DNS] clients4.google.com --> 142.250.204.142"
time="2021-11-17T10:35:02+08:00" level=warning msg="[TCP] dial Global (match Match/) to clients4.google.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:35:02+08:00" level=debug msg="[DNS] clients4.google.com --> 142.250.204.142"
time="2021-11-17T10:35:02+08:00" level=warning msg="[TCP] dial Global (match Match/) to clients4.google.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:35:12+08:00" level=debug msg="[DNS] github.com --> 20.205.243.166"
time="2021-11-17T10:35:12+08:00" level=warning msg="[TCP] dial Global (match Match/) to github.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:35:12+08:00" level=debug msg="[DNS] github.com --> 20.205.243.166"
time="2021-11-17T10:35:12+08:00" level=warning msg="[TCP] dial Global (match Match/) to github.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:35:12+08:00" level=debug msg="[DNS] github.com --> 20.205.243.166"
time="2021-11-17T10:35:12+08:00" level=warning msg="[TCP] dial Global (match Match/) to github.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:35:12+08:00" level=debug msg="[DNS] github.com --> 20.205.243.166"
time="2021-11-17T10:35:12+08:00" level=warning msg="[TCP] dial Global (match Match/) to github.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:35:14+08:00" level=debug msg="[DNS] nleditor.osi.office.net --> 52.109.52.21"
time="2021-11-17T10:35:14+08:00" level=warning msg="[TCP] dial Global (match Match/) to nleditor.osi.office.net:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:35:14+08:00" level=debug msg="[DNS] nleditor.osi.office.net --> 52.109.52.20"
time="2021-11-17T10:35:14+08:00" level=warning msg="[TCP] dial Global (match Match/) to nleditor.osi.office.net:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:35:14+08:00" level=debug msg="[DNS] github.com --> 20.205.243.166"
time="2021-11-17T10:35:14+08:00" level=warning msg="[TCP] dial Global (match Match/) to github.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:35:14+08:00" level=debug msg="[DNS] github.com --> 20.205.243.166"
time="2021-11-17T10:35:14+08:00" level=warning msg="[TCP] dial Global (match Match/) to github.com:443 error: cm-moe.ikc3549ol1w65zbm.xyz:37280 connect error: interface not found"
time="2021-11-17T10:35:22+08:00" level=debug msg="[DNS] cloud.tencent.com --> 211.91.160.249"
time="2021-11-17T10:35:22+08:00" level=warning msg="[TCP] dial Direct (match RuleSet/China) to cloud.tencent.com:443 error: interface not found"
time="2021-11-17T10:35:22+08:00" level=debug msg="[DNS] cloud.tencent.com --> 211.91.160.249"
time="2021-11-17T10:35:22+08:00" level=warning msg="[TCP] dial Direct (match RuleSet/China) to cloud.tencent.com:443 error: interface not found"

**Comment by Fndroid** [comment]
配置文件设置了错误的`interface-name`或proxies设置了错误的`interface`
