### ISSUE TITLE
Clash Allow Lan

### ISSUE THREAD

**Issue by KOF136** [Fndroid/clash_for_windows_pkg#2423]
运行环境:Windows 11  Android11
问题描述:PC和路由器防火墙均已关闭， 同一局域网WIFI下
clash开启allow lan 共享模式， 端口为默认7890
手机电脑连接同一WIFI， 移动端WiFi(192.168.1.2)打开手动代理， 填写PC端的ipv4地址(192.168.1.6)与7890端口后保存设置。移动端显示WLAN网络不可用。

**Comment by YirunFantasy** [comment]
电脑端防火墙添加7890端口的入站规则

**Comment by KOF136** [comment]
> 不用关闭防火墙，电脑端防火墙添加7890端口的入站规则即可（我都是tcp和udp都添一下）。
> 192.168.1.6是有线网卡的地址还是无线的？确定没填错？还有是不是自动分配IP地址的，这样每次开机无线网卡的地址都会变得吧，建议手动分配到偏后面的一个，比如我的分给128，怎么着都用不到这个，手机端填这个，一劳永逸

谢谢你的回答。
>你的第一个回复:防火墙尝试过加入7890端口TCP/UDP入站规则，手机无外网。然后尝试关闭PC与路由器防火墙均无效。
>你的第二个回复:192.168.1.6是无线网卡，网卡型号为Intel AX200 ，地址尝试更换为固定IP地址192.168.1.233 ，仍然无法启用网关模式。
>尝试更换路由器 并更改为固定IP192.168.3.233，
还是无法访问外网 
附下图:
![L~M1G@((GUA}]X{21$]5IBL(1).png](https://user-images.githubusercontent.com/90687473/142749722-5f99e6d4-cc4e-42bd-864a-2087e1622911.png)
![Q@4~5)Z6@TN0A)ED{%6EDF8(1).png](https://user-images.githubusercontent.com/90687473/142749724-5fdd7469-9989-449b-9c92-71720e94daf0.png)

**Comment by KOF136** [comment]
回复1:防火墙尝试过加入7890端口TCP/UDP入站规则，手机无外网。然后尝试关闭PC与路由器防火墙均无效。



回复2:192.168.1.6是无线网卡，网卡型号为Intel&nbsp;AX200&nbsp;，地址尝试更换为固定IP地址192.168.1.233&nbsp;，仍然无法启用网关模式。
尝试更换路由器&nbsp;并更改为固定IP192.168.3.233，
还是无法访问外网




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fndroid/clash_for_windows_pkg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月21日(星期天) 上午9:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fndroid/clash_for_windows_pkg] Clash Allow Lan (Issue #2423)





 
电脑端防火墙添加7890端口的入站规则

**Comment by YirunFantasy** [comment]
看你的描述，即使关了系统防火墙和路由器防火墙也没用，那这问题基本就是在你的手机端了，八成不属于技术问题，就是自己设置错了。
看了你的描述，不是很懂你为什么改路由器为192.168.3.233，lan共享你唯一需要改的就是手机，（之前我说的改电脑端地址只是为了方便以后使用，并且要改的不是路由器，是无线网卡，注意是网卡，不是路由器）

1. 首先，恢复你的路由器IP设置，不要乱动，一般默认都是192.168.1.1
2. 第二，电脑端打开网络适配器，找到你的无线网卡，将IPV4里的IP地址改成192.168.1.X（X随意一个数，考虑到家里面有多个设备，可以往后靠一靠），比如改成192.168.1.20
3. 手机端，不需要你改手机端的IP地址，只需要改里面的代理设置，地址为192.168.1.20（上面第二步你改的IP），端口7890

不要改什么192.168.3.xxx，3 和 1 都不是一个网段了，你怎么可能连的上。

这种不是软件层面的事儿，自己想办法解决一下

**Comment by KOF136** [comment]
回复：路由器IP没有更改，网段是一致的， 3段是因为我更换了新的路由器尝试。 只更改了电脑网卡的IP地址，目的为了固定IP。移动端我没有更换IP地址，模式为DHCP WIFI代理模式设置为手动， 填写电脑的IPV4地址与7890端口 尝试后均无效。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月21日(星期天) 中午1:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Fndroid/clash_for_windows_pkg] Clash Allow Lan (Issue #2423)





 
看你的描述，即使关了系统防火墙和路由器防火墙也没用，那这问题基本就是在你的手机端了，八成不属于技术问题，就是自己设置错了。
 看了你的描述，不是很懂你为什么改路由器为192.168.3.233，lan共享你唯一需要改的就是手机，（之前我说的改电脑端地址只是为了方便以后使用，并且要改的不是路由器，是无线网卡，注意是网卡，不是路由器）
  
首先，恢复你的路由器IP设置，不要乱动，一般默认都是192.168.1.1
 
第二，电脑端打开网络适配器，找到你的无线网卡，将IPV4里的IP地址改成192.168.1.X（X随意一个数，考虑到家里面有多个设备，可以往后靠一靠），比如改成192.168.1.20
 
手机端，不需要你改手机端的IP地址，只需要改里面的代理设置，地址为192.168.1.20（上面第二步你改的IP），端口7890
  
不要改什么192.168.3.xxx，3 和 1 都不是一个网段了，你怎么可能连的上。
 
这种不是软件层面的事儿，自己想办法解决一下

**Comment by KOF136** [comment]
作为clash 共享的电脑 是不是不能是WiFi连接，
只能接网线才能启用网关模式

**Comment by YirunFantasy** [comment]
> 

是的。并且随后也不能开启电脑的热点共享

**Comment by KOF136** [comment]
> > 
> 
> 是的，要用有线连接，无线是个工具人吧。并且随后也不能开启电脑的热点共享

谢谢你的回答 估计逻辑死循环了

**Comment by Mashiro-qwq** [comment]
> 运行环境:Windows 11 Android11 问题描述:PC和路由器防火墙均已关闭， 同一局域网WIFI下 clash开启allow lan 共享模式， 端口为默认7890 手机电脑连接同一WIFI， 移动端WiFi(192.168.1.2)打开手动代理， 填写PC端的ipv4地址(192.168.1.6)与7890端口后保存设置。移动端显示WLAN网络不可用。

然而事实上不用这么麻烦啊，只需要勾选allow lan 鼠标悬浮在allow lan选项上看到 `192.168.x.x WLAN` 这一项(根据你的网卡，看了你的描述，你是使用wifi连接那么应该有一条名为WLAN的地址)
![QQ截图20211122101309](https://user-images.githubusercontent.com/46055880/142791376-9b02424f-ddcc-46f0-83f1-f5316b4a82f9.png)

接下来只需要打开手机（我使用的Samsung Galaxy S10 Plus Android 11） ->设置->连接->WLAN->点击你连接的wifi（长按选择编辑或者有单独的齿轮图标）)->展开高级设置->代理服务器选项选择手动->代理主机名填入上面步骤 `WLAN` 对应的ip地址->代理服务器端口填入你的代理端口->选择保存->此时建议开启飞行模式等待3s再关闭（Google应用并不会立即使用你配置的代理，刚配置好就打开Google系应用会提示无连接并且很长时间都不会识别到你设置的代理，手动重连wifi刷新代理设置即可）
![Screenshot_20211122-101216_Settings](https://user-images.githubusercontent.com/46055880/142792047-91e08429-424d-4e1c-96e5-60bacce176a3.jpg)

**Comment by KOF136** [comment]
> > 运行环境:Windows 11 Android11 问题描述:PC和路由器防火墙均已关闭， 同一局域网WIFI下 clash开启allow lan 共享模式， 端口为默认7890 手机电脑连接同一WIFI， 移动端WiFi(192.168.1.2)打开手动代理， 填写PC端的ipv4地址(192.168.1.6)与7890端口后保存设置。移动端显示WLAN网络不可用。
> 
> 然而事实上不用这么麻烦啊，只需要勾选allow lan 鼠标悬浮在allow lan选项上看到 `192.168.x.x WLAN` 这一项(根据你的网卡，看了你的描述，你是使用wifi连接那么应该有一条名为WLAN的地址)
> ![QQ截图20211122101309](https://user-images.githubusercontent.com/46055880/142791376-9b02424f-ddcc-46f0-83f1-f5316b4a82f9.png)
> 
> 接下来只需要打开手机（我使用的Samsung Galaxy S10 Plus Android 11） ->设置->连接->WLAN->点击你连接的wifi（长按选择编辑或者有单独的齿轮图标）)->展开高级设置->代理服务器选项选择手动->代理主机名填入上面步骤 `WLAN` 对应的ip地址->代理服务器端口填入你的代理端口->选择保存->此时建议开启飞行模式等待3s再关闭（Google应用并不会立即使用你配置的代理，刚配置好就打开Google系应用会提示无连接并且很长时间都不会识别到你设置的代理，手动重连wifi刷新代理设置即可）
> ![Screenshot_20211122-101216_Settings](https://user-images.githubusercontent.com/46055880/142792047-91e08429-424d-4e1c-96e5-60bacce176a3.jpg)

我就是这样尝试设置的 也依然无法访问外网
路由器是移动光猫和无线一体机的盒子

**Comment by Mashiro-qwq** [comment]
> > > 运行环境:Windows 11 Android11 问题描述:PC和路由器防火墙均已关闭， 同一局域网WIFI下 clash开启allow lan 共享模式， 端口为默认7890 手机电脑连接同一WIFI， 移动端WiFi(192.168.1.2)打开手动代理， 填写PC端的ipv4地址(192.168.1.6)与7890端口后保存设置。移动端显示WLAN网络不可用。
> > 
> > 
> > 然而事实上不用这么麻烦啊，只需要勾选allow lan 鼠标悬浮在allow lan选项上看到 `192.168.x.x WLAN` 这一项(根据你的网卡，看了你的描述，你是使用wifi连接那么应该有一条名为WLAN的地址)
> > ![QQ截图20211122101309](https://user-images.githubusercontent.com/46055880/142791376-9b02424f-ddcc-46f0-83f1-f5316b4a82f9.png)
> > 接下来只需要打开手机（我使用的Samsung Galaxy S10 Plus Android 11） ->设置->连接->WLAN->点击你连接的wifi（长按选择编辑或者有单独的齿轮图标）)->展开高级设置->代理服务器选项选择手动->代理主机名填入上面步骤 `WLAN` 对应的ip地址->代理服务器端口填入你的代理端口->选择保存->此时建议开启飞行模式等待3s再关闭（Google应用并不会立即使用你配置的代理，刚配置好就打开Google系应用会提示无连接并且很长时间都不会识别到你设置的代理，手动重连wifi刷新代理设置即可）
> > ![Screenshot_20211122-101216_Settings](https://user-images.githubusercontent.com/46055880/142792047-91e08429-424d-4e1c-96e5-60bacce176a3.jpg)
> 
> 我就是这样尝试设置的 也依然无法访问外网 路由器是移动光猫和无线一体机的盒子

1.检查手机是否与PC处于同一局域网下（手机IP应与PC机IP有相同的前三项：192.168.3.x根据你的路由器设置）
2.windows打开控制面板->Windows Defender 防火墙->允许应用或功能通过 Windows Defender 防火墙->下拉找到`Clash for Windows` `clash-win64` 等Clash名开头的将 `专用` `公用`两个选项都勾上点击确定保存
![QQ截图20211122103632](https://user-images.githubusercontent.com/46055880/142793139-ef2312c6-020e-4338-b8c0-4e6f6a7aeb2a.png)
3.检查是否连接成功
4.可以将windows连接的WiFi设置为专用连接尝试能否连接代理
![QQ截图20211122103924](https://user-images.githubusercontent.com/46055880/142793155-7f4ddfcc-2f4a-4a79-a4c1-573bb26449f0.png)

**Comment by KOF136** [comment]
软件层已经检查过了 设置都是这样的 
应该是路由硬件层有问题 路由都是同一局域网
手机是小米10 至尊版

**Comment by Mashiro-qwq** [comment]
> 软件层已经检查过了 设置都是这样的 应该是路由硬件层有问题 路由都是同一局域网 手机是小米10 至尊版

继续检查你的路由器wifi设置里是否关闭无线AP隔离
![image](https://user-images.githubusercontent.com/46055880/142793599-a38f2c7a-fc29-460e-b163-e1bc16596bd5.png)

**Comment by KOF136** [comment]
> > 软件层已经检查过了 设置都是这样的 应该是路由硬件层有问题 路由都是同一局域网 手机是小米10 至尊版
> 
> 继续检查你的路由器wifi设置里是否关闭无线AP隔离
> ![image](https://user-images.githubusercontent.com/46055880/142793599-a38f2c7a-fc29-460e-b163-e1bc16596bd5.png)

请问可以添加TG进行交流吗 感谢

**Comment by Mashiro-qwq** [comment]
> > > 软件层已经检查过了 设置都是这样的 应该是路由硬件层有问题 路由都是同一局域网 手机是小米10 至尊版
> > 
> > 
> > 继续检查你的路由器wifi设置里是否关闭无线AP隔离
> > ![image](https://user-images.githubusercontent.com/46055880/142793599-a38f2c7a-fc29-460e-b163-e1bc16596bd5.png)
> 
> 请问可以添加TG进行交流吗 感谢

电脑没装TG,就在这问吧,路由器关掉无线AP隔离也不行的话,我也只能帮你到这了,再往下也是我的知识盲区

**Comment by KOF136** [comment]
> > > > 软件层已经检查过了 设置都是这样的 应该是路由硬件层有问题 路由都是同一局域网 手机是小米10 至尊版
> > > 
> > > 
> > > 继续检查你的路由器wifi设置里是否关闭无线AP隔离
> > > ![image](https://user-images.githubusercontent.com/46055880/142793599-a38f2c7a-fc29-460e-b163-e1bc16596bd5.png)
> > 
> > 请问可以添加TG进行交流吗 感谢
> 
> 电脑没装TG,就在这问吧,路由器关掉无线AP隔离也不行的话,我也只能帮你到这了,再往下也是我的知识盲区

移动光猫路由设置没有ap隔离这个选项
超级管理员账号

**Comment by Mashiro-qwq** [comment]
> > > > > 软件层已经检查过了 设置都是这样的 应该是路由硬件层有问题 路由都是同一局域网 手机是小米10 至尊版
> > > > 
> > > > 
> > > > 继续检查你的路由器wifi设置里是否关闭无线AP隔离
> > > > ![image](https://user-images.githubusercontent.com/46055880/142793599-a38f2c7a-fc29-460e-b163-e1bc16596bd5.png)
> > > 
> > > 
> > > 请问可以添加TG进行交流吗 感谢
> > 
> > 
> > 电脑没装TG,就在这问吧,路由器关掉无线AP隔离也不行的话,我也只能帮你到这了,再往下也是我的知识盲区
> 
> 移动光猫路由设置没有ap隔离这个选项 超级管理员账号

你用电脑能ping通你的手机吗

**Comment by KOF136** [comment]
> > > > > > 软件层已经检查过了 设置都是这样的 应该是路由硬件层有问题 路由都是同一局域网 手机是小米10 至尊版
> > > > > 
> > > > > 
> > > > > 继续检查你的路由器wifi设置里是否关闭无线AP隔离
> > > > > ![image](https://user-images.githubusercontent.com/46055880/142793599-a38f2c7a-fc29-460e-b163-e1bc16596bd5.png)
> > > > 
> > > > 
> > > > 请问可以添加TG进行交流吗 感谢
> > > 
> > > 
> > > 电脑没装TG,就在这问吧,路由器关掉无线AP隔离也不行的话,我也只能帮你到这了,再往下也是我的知识盲区
> > 
> > 移动光猫路由设置没有ap隔离这个选项 超级管理员账号
> 
> 你用电脑能ping通你的手机吗

这个是可以的

**Comment by Mashiro-qwq** [comment]
> > > > > > > 软件层已经检查过了 设置都是这样的 应该是路由硬件层有问题 路由都是同一局域网 手机是小米10 至尊版
> > > > > > 
> > > > > > 
> > > > > > 继续检查你的路由器wifi设置里是否关闭无线AP隔离
> > > > > > ![image](https://user-images.githubusercontent.com/46055880/142793599-a38f2c7a-fc29-460e-b163-e1bc16596bd5.png)
> > > > > 
> > > > > 
> > > > > 请问可以添加TG进行交流吗 感谢
> > > > 
> > > > 
> > > > 电脑没装TG,就在这问吧,路由器关掉无线AP隔离也不行的话,我也只能帮你到这了,再往下也是我的知识盲区
> > > 
> > > 
> > > 移动光猫路由设置没有ap隔离这个选项 超级管理员账号
> > 
> > 
> > 你用电脑能ping通你的手机吗
> 
> 这个是可以的

手机装一个[V2rayNG](https://github.com/2dust/v2rayNG) 软件右上角<kbd>+</kbd>点击手动输入[Socks]
别名随便写,服务器地址填写上面的 `WLAN` 地址,服务器端口填写你的代理端口,其余不填,右上角<kbd>√</kbd>保存
然后点击你建立的配置右下角按钮开启,看看可以连接吗

**Comment by Mashiro-qwq** [comment]
> > > > > > > > 软件层已经检查过了 设置都是这样的 应该是路由硬件层有问题 路由都是同一局域网 手机是小米10 至尊版
> > > > > > > 
> > > > > > > 
> > > > > > > 继续检查你的路由器wifi设置里是否关闭无线AP隔离
> > > > > > > ![image](https://user-images.githubusercontent.com/46055880/142793599-a38f2c7a-fc29-460e-b163-e1bc16596bd5.png)
> > > > > > 
> > > > > > 
> > > > > > 请问可以添加TG进行交流吗 感谢
> > > > > 
> > > > > 
> > > > > 电脑没装TG,就在这问吧,路由器关掉无线AP隔离也不行的话,我也只能帮你到这了,再往下也是我的知识盲区
> > > > 
> > > > 
> > > > 移动光猫路由设置没有ap隔离这个选项 超级管理员账号
> > > 
> > > 
> > > 你用电脑能ping通你的手机吗
> > 
> > 
> > 这个是可以的
> 
> 手机装一个[V2rayNG](https://github.com/2dust/v2rayNG) 软件右上角+点击手动输入[Socks] 别名随便写,服务器地址填写上面的 `WLAN` 地址,服务器端口填写你的代理端口,其余不填,右上角√保存 然后点击你建立的配置右下角按钮开启,看看可以连接吗

曲线救国方案,其实都这样了不如直接在手机上配置订阅连接直接连接代理

**Comment by KOF136** [comment]
> > > > > > > > > 软件层已经检查过了 设置都是这样的 应该是路由硬件层有问题 路由都是同一局域网 手机是小米10 至尊版
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 继续检查你的路由器wifi设置里是否关闭无线AP隔离
> > > > > > > > ![image](https://user-images.githubusercontent.com/46055880/142793599-a38f2c7a-fc29-460e-b163-e1bc16596bd5.png)
> > > > > > > 
> > > > > > > 
> > > > > > > 请问可以添加TG进行交流吗 感谢
> > > > > > 
> > > > > > 
> > > > > > 电脑没装TG,就在这问吧,路由器关掉无线AP隔离也不行的话,我也只能帮你到这了,再往下也是我的知识盲区
> > > > > 
> > > > > 
> > > > > 移动光猫路由设置没有ap隔离这个选项 超级管理员账号
> > > > 
> > > > 
> > > > 你用电脑能ping通你的手机吗
> > > 
> > > 
> > > 这个是可以的
> > 
> > 手机装一个[V2rayNG](https://github.com/2dust/v2rayNG) 软件右上角+点击手动输入[Socks] 别名随便写,服务器地址填写上面的 `WLAN` 地址,服务器端口填写你的代理端口,其余不填,右上角√保存 然后点击你建立的配置右下角按钮开启,看看可以连接吗
> 
> 曲线救国方案,其实都这样了不如直接在手机上配置订阅连接直接连接代理

添加sock代理 服务器填写电脑ip与7890端口
成功连接 并可以访问外网

**Comment by Mashiro-qwq** [comment]
啊这,那我想不通为什么在WiFi上设置代理无法连接....这应该甩锅给小米吗???

**Comment by KOF136** [comment]
> 啊这,那我想不通为什么在WiFi上设置代理无法连接....这应该甩锅给小米吗???

可能应该是国产Rom的原因，我在YouTube看到小米的教程是可以使用的

**Comment by Mashiro-qwq** [comment]
> > 啊这,那我想不通为什么在WiFi上设置代理无法连接....这应该甩锅给小米吗???
> 
> 可能应该是国产Rom的原因，我在YouTube看到小米的教程是可以使用的 还是无法实现网关模式 透明代理

剩下的我也帮不到你了,你可能需要等待系统更新来修复

**Comment by KOF136** [comment]
> > > 啊这,那我想不通为什么在WiFi上设置代理无法连接....这应该甩锅给小米吗???
> > 
> > 可能应该是国产Rom的原因，我在YouTube看到小米的教程是可以使用的 还是无法实现网关模式 透明代理
> 
> 剩下的我也帮不到你了,你可能需要等待系统更新来修复
可以换软路由或者mac mini使用surge做网关模式解决吗

**Comment by Mashiro-qwq** [comment]
> > > > 啊这,那我想不通为什么在WiFi上设置代理无法连接....这应该甩锅给小米吗???
> > > 
> > > 
> > > 可能应该是国产Rom的原因，我在YouTube看到小米的教程是可以使用的 还是无法实现网关模式 透明代理
> > 
> > 
> > 剩下的我也帮不到你了,你可能需要等待系统更新来修复
> > 可以换软路由或者mac mini使用surge做网关模式解决吗

不清楚,mac mini我没有,也没有软路由,你的问题大概率是你手机的问题,如果你有其他设备,不如在其他设备尝试最开始的解决方案以排除问题所在

**Comment by KOF136** [comment]
> > > > > 啊这,那我想不通为什么在WiFi上设置代理无法连接....这应该甩锅给小米吗???
> > > > 
> > > > 
> > > > 可能应该是国产Rom的原因，我在YouTube看到小米的教程是可以使用的 还是无法实现网关模式 透明代理
> > > 
> > > 
> > > 剩下的我也帮不到你了,你可能需要等待系统更新来修复
> > > 可以换软路由或者mac mini使用surge做网关模式解决吗
> 
> 不清楚,mac mini我没有,也没有软路由,你的问题大概率是你手机的问题,如果你有其他设备,不如在其他设备尝试最开始的解决方案以排除问题所在

我TG电报使用socks 代理
填写电脑ip和7890端口 可以访问外网
应该就是手机问题

**Comment by KOF136** [comment]
> > > > > 啊这,那我想不通为什么在WiFi上设置代理无法连接....这应该甩锅给小米吗???
> > > > 
> > > > 
> > > > 可能应该是国产Rom的原因，我在YouTube看到小米的教程是可以使用的 还是无法实现网关模式 透明代理
> > > 
> > > 
> > > 剩下的我也帮不到你了,你可能需要等待系统更新来修复
> > > 可以换软路由或者mac mini使用surge做网关模式解决吗
> 
> 不清楚,mac mini我没有,也没有软路由,你的问题大概率是你手机的问题,如果你有其他设备,不如在其他设备尝试最开始的解决方案以排除问题所在

已解决 换iPhone手机后成功访问外网
四年前vivo手机都可以 这小米手机有毒

**Comment by jerrykkkkk** [comment]
我也是这个问题，防火墙都没开，关了火绒后虽然手机wifi那显示无法连接到互联网， 用浏览器谷歌等外网都可以访问。但是正常的国内软件，像小红薯的评论打不开

**Comment by Skyzhu881** [comment]
我也有完全一样的情况
我的情况是使用电脑代为中转， 小米手机、iPad都无法连接这个代理，在WIFI中设置了代理之后，会提示该wifi无法联网、墙内地址和墙外地址都无法使用 ，但是另一台电脑可以

**Comment by Gseventeen17** [comment]
同样的问题，用clash allow lan手机无法连通，用V2rayn 手机就可以连通

**Comment by Menzor-future** [comment]
> 

允许防护墙这个好用！记得所有和clash的都勾上 可以访问了 我也是小米10U

**Comment by Skyzhu881** [comment]
> > 
> 
> 允许防护墙这个好用！记得所有和clash的都勾上 可以访问了 我也是小米10U

@Menzor-future 请问你说的是哪里操作的“允许防护墙”呢？
