### ISSUE TITLE
[Bug]: 更新到 0.18.9 版本后，Windows 下 TUN 模式中 Discord 连接语音服务器失败

### ISSUE THREAD

**Issue by HamsterReserved** [Fndroid/clash_for_windows_pkg#2424]
（GitHub 的 issue 表单提交会 HTTP 400，所以我就直接开空白 issue 来写了）

## 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

## 软件版本

0.18.9

## 操作系统

Windows x64

## 系统版本

Windows 10 21H1, build 19043.1348

## 问题描述

从 0.18.7 版本升级到 0.18.9 版本后，使用完全相同的配置文件，Discord 就无法连接语音服务器了。Discord 中在“即时通讯服务器连接中”卡了几秒钟后变成“没有路径”。回退到 0.18.7 版本则正常。

已经确认不是机场和节点的问题，因为在 0.18.9 和 0.18.7 中按以下步骤短时间内反复切换几次，都可以精准地使问题复现或消失。

## 复现步骤

1. 关闭 Discord 
2. 从 Release 页面下载 Clash.for.Windows-0.18.9-win.7z 
3. 进入原先存放 0.18.7 的目录，删除所有文件 
4. 进入 Clash Home directory，删除 wintun.dll 
5. 进入 Windows 设备管理器，选择显示隐藏的设备，找到网络适配器下的 Clash Tunnel，将其删除，同时勾选“删除此设备的驱动程序软件” 
6. 将 Clash.for.Windows-0.18.9-win.7z 解压到原先存放 0.18.7 的目录中 
7. 双击 Clash for Windows.exe 启动程序 
8. 启动 Discord，在任意 server 加入语音频道，即可复现问题 
 
按照上面同样方法操作，但将最初下载的文件换成 Clash.for.Windows-0.18.7-win.7z，最后一步中的 Discord 即可恢复正常。

## 日志文件

<details><summary>logs</summary><p> 
 
``` 
time=\"2021-11-21T12:15:56 08:00\" level=info msg=\"RESTful API listening at: 127.0.0.1:55708\" 
time=\"2021-11-21T12:15:56 08:00\" level=warning msg=\"Failed to start Redir UDP Listener: not supported on current platform\" 
time=\"2021-11-21T12:15:56 08:00\" level=info msg=\"Redirect proxy listening at: [::]:7892\" 
time=\"2021-11-21T12:15:56 08:00\" level=info msg=\"Mixed(http socks) proxy listening at: [::]:7890\" 
time=\"2021-11-21T12:15:56 08:0…com) using 🖥 Microsoft[🇭🇰 HKG 15]\" 
time=\"2021-11-21T12:16:19 08:00\" level=info msg=\"[TCP] 198.18.0.1:51563 --> japan4428.discord.media:443 match Match() using Final[🇭🇰 HKG 15]\" 
time=\"2021-11-21T12:16:20 08:00\" level=info msg=\"[UDP] 198.18.0.1:64797 --> 103.194.167.16:50002 match Match() using Final[🇭🇰 HKG 15]\" 
time=\"2021-11-21T12:16:20 08:00\" level=info msg=\"[UDP] 198.18.0.1:64798 --> 103.194.167.16:50002 match Match() using Final[🇭🇰 HKG 15]\" 
``` 
 
</p></details> 

## 其他补充

从上面的日志中，可以看到 Clash core 已经收到建立 Discord 语音服务器连接的请求： 
 
``` 
time=\"2021-11-21T12:16:20 08:00\" level=info msg=\"[UDP] 198.18.0.1:64797 --> 103.194.167.16:50002 match Match() using Final[🇭🇰 HKG 15]\" 
time=\"2021-11-21T12:16:20 08:00\" level=info msg=\"[UDP] 198.18.0.1:64798 --> 103.194.167.16:50002 match Match() using Final[🇭🇰 HKG 15]\" 
``` 
 
与此同时，在 Clash Tunnel 接口用 Wireshark 抓包也能看到这些数据包。但是，这些数据包都是只有发出，而没有回复。 
 
作为对比：
1. 在 0.18.9 下 Discord 语音服务器无法连接的同时，使用 NATTypeTester 测试 NAT 类型，仍能测试出 FullCone，且确认  Public end 是机场节点。
2. 关闭 TUN，使用 Netch 为 Discord 提供代理，没有问题
3. 换用 TAP 模式，也一样存在问题

**Comment by ainihaohao** [comment]
一样的问题。  18.9搞了几个小时 我以为就我自己这样

**Comment by lisansas** [comment]
差不多的情况，我的问题是tun没有成功开启，开关几次mixin就行了

**Comment by HamsterReserved** [comment]
> 差不多的情况，我的问题是tun没有成功开启，开关几次mixin就行了

我这里 TUN 是成功开启的，不然 Discord 语音的前面几个连接步骤都过不去。

**Comment by cqhhy2001** [comment]
一样的问题，我被折腾几天了，排查了无数遍都连不上，我还以为我配置出问题了
观点mixin就能正常连接

**Comment by BiuZero** [comment]
19.2版本，TUN TAP我这里也是都连不上Discord语音服务器，试了好几天了，更新wintun版本，换节点啥的，都是同样问题😢

**Comment by KunoiSayami** [comment]
Same here.
OS: Arch linux 2021-12-26
Version: 0.19.3

**Comment by Fndroid** [comment]
用fake-ip

**Comment by taoletsgo** [comment]
> 

尝试了但不行，0.19.0后面的版本修复了育碧bug...而这个版本有discord bug，(╯﹏╰)

**Comment by taoletsgo** [comment]
> 用fake-ip

尝试了但不行，0.19.0后面的版本修复了育碧bug...而这个版本有discord bug，(╯﹏╰)

**Comment by BiuZero** [comment]
> > 用fake-ip
> 
> 尝试了但不行，0.19.0后面的版本修复了育碧bug...而这个版本有discord bug，(╯﹏╰)

我也试过fake-ip连不上，貌似是clash内核本身的问题，路由器上用openclash也有这个问题，但是openclash开全局可以，开规则就不行，哪怕规则设置都走节点，总之很迷。。。

用Netch就能正常连上，但是可能我不太会设置，一用这个软件，dns就会变成走节点解析，比如打开淘宝延迟非常高，ping 300ms

目前已经放弃Discord语音了，虽然降噪效果很强。。。但是裸连语音频道延迟太高了，希望clash能修复吧🤦‍♂️

**Comment by HamsterReserved** [comment]
后来发现 TUN 模式下还有其他问题，所以我换成 TAP 了。保留当前配置（TAP + redir-host）升级到 0.19.4 的话，会额外遇到 #2527 的现象，Discord 故障依然存在。所以我目前是保持在 0.18.7 + TAP & redir-host 没有升级。

另外，Discord 的语音服务器似乎并不依赖域名，所以 fake-ip 应当起不到太大作用。如下是 0.18.7 + fake-ip 后从 Discord 启动到自动连接语音频道的日志，注意最后面 43.239.139.229:50001 没有 DNS 解析的记录：

```
time="2022-01-01T22:11:42+08:00" level=info msg="[TCP] 127.0.0.1:56889 --> 162.159.136.232:443 match Match() using Others[🇭🇰 香港 IEPL [04] -> 香港 NTT]"
time="2022-01-01T22:11:43+08:00" level=info msg="[TCP] 127.0.0.1:55673 --> 162.159.136.232:443 match Match() using Others[🇭🇰 香港 IEPL [04] -> 香港 NTT]"
time="2022-01-01T22:11:43+08:00" level=debug msg="[DNS] gateway.discord.gg --> 162.159.133.234"
time="2022-01-01T22:11:43+08:00" level=info msg="[TCP] 127.0.0.1:49740 --> gateway.discord.gg:443 match Match() using Others[🇭🇰 香港 IEPL [04] -> 香港 NTT]"
time="2022-01-01T22:11:44+08:00" level=debug msg="[DNS] go.microsoft.com --> 104.99.26.106"
time="2022-01-01T22:11:44+08:00" level=info msg="[TCP] 127.0.0.1:49743 --> go.microsoft.com:443 match RuleSet(Microsoft) using Microsoft[🇭🇰 香港 IEPL [04] -> 香港 NTT]"
time="2022-01-01T22:11:45+08:00" level=debug msg="[DNS] ocsp.digicert.com --> 117.18.237.29"
time="2022-01-01T22:11:48+08:00" level=info msg="[TCP] 127.0.0.1:49746 --> ocsp.digicert.com:80 match RuleSet(Domestic) using Domestic[DIRECT]"
time="2022-01-01T22:11:49+08:00" level=debug msg="[DNS] cdn.discordapp.com --> 128.242.240.189"
time="2022-01-01T22:11:49+08:00" level=info msg="[TCP] 127.0.0.1:55270 --> cdn.discordapp.com:443 match Match() using Others[🇭🇰 香港 IEPL [04] -> 香港 NTT]"
time="2022-01-01T22:11:50+08:00" level=debug msg="[DNS] status.discord.com --> 210.56.51.193"
time="2022-01-01T22:11:50+08:00" level=info msg="[TCP] 127.0.0.1:57599 --> status.discord.com:443 match Match() using Others[🇭🇰 香港 IEPL [04] -> 香港 NTT]"
time="2022-01-01T22:11:51+08:00" level=debug msg="[DNS] hongkong3354.discord.media --> 162.159.137.234"
time="2022-01-01T22:11:51+08:00" level=info msg="[TCP] 127.0.0.1:50231 --> hongkong3354.discord.media:443 match Match() using Others[🇭🇰 香港 IEPL [04] -> 香港 NTT]"
time="2022-01-01T22:11:51+08:00" level=info msg="[UDP] 127.0.0.1:64275 --> 43.239.139.229:50001 match Match() using Others[🇭🇰 香港 IEPL [04] -> 香港 NTT]"
time="2022-01-01T22:11:51+08:00" level=info msg="[UDP] 127.0.0.1:64276 --> 43.239.139.229:50001 match Match() using Others[🇭🇰 香港 IEPL [04] -> 香港 NTT]"
time="2022-01-01T22:11:52+08:00" level=debug msg="[DNS] latency.discord.media --> 162.159.130.235"
time="2022-01-01T22:11:52+08:00" level=info msg="[TCP] 127.0.0.1:56585 --> latency.discord.media:443 match Match() using Others[🇭🇰 香港 IEPL [04] -> 香港 NTT]"
```

**Comment by HamsterReserved** [comment]
我在上游提了修复的 PR，如果各位比较着急用的话可以先帮忙试试看。https://github.com/Dreamacro/clash/pull/1868

**Comment by Heisenberglue** [comment]
> 我在上游提了修复的 PR，如果各位比较着急用的话可以先帮忙试试看。[Dreamacro/clash#1868](https://github.com/Dreamacro/clash/pull/1868)

太强了，我前面一直在使用 TUN 模式配合自己写的进程规则，努力想实现无感翻墙，但是总是会有个别应用出现问题，Discord、”荒野大镖客2“就是其中两个典型，排查了很久也搞不清楚为什么无法连接。现在看起来都是由于这个原因，非常感谢你帮助解决了这个问题！很期待新版本内核的表现！

**Comment by HamsterReserved** [comment]
上游已经发布新版本。将上游的 Release 1.9.0 binary 替换到 CFW 0.19.4 中以后可验证 Discord 恢复正常，但 2022.01.02 Premium 版本仍然会导致 Discord 语音提示“没有路径”。不过，Clash log 不再是本 task 所描述的那样了，而是 #2527 那样的 `listen udp :0: An invalid argument was supplied`.

本 task 所述的这个现象已解决，就先关闭了。新的这个问题就在 #2527 里面跟进吧。

**Comment by xlbljz** [comment]
> > 我在上游提了修复的 PR，如果各位比较着急用的话可以先帮忙试试看。[Dreamacro/clash#1868](https://github.com/Dreamacro/clash/pull/1868)
> 
> 太强了，我前面一直在使用 TUN 模式配合自己写的进程规则，努力想实现无感翻墙，但是总是会有个别应用出现问题，Discord、”荒野大镖客2“就是其中两个典型，排查了很久也搞不清楚为什么无法连接。现在看起来都是由于这个原因，非常感谢你帮助解决了这个问题！很期待新版本内核的表现！

真要想无感翻墙，我用过最接近的就是在路由器里装代理。任何设备只要连上路由器就能翻，无需任何设置
