### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by 123shiyue** [Fndroid/clash_for_windows_pkg#2425]
### 功能描述

希望右键菜单可以调用**系统默认样式**
希望软件增加夜间模式,可以随系统更改

**Comment by LucienShaw** [comment]
软件里已经包含了夜间模式这一功能，并且支持跟随系统
![image](https://user-images.githubusercontent.com/82591976/143515989-6fdea82c-870a-46f1-b7bf-cf8f4d602a21.png)
