### ISSUE TITLE
[BUG]: TUN模式打开后, 网络无法使用, clash tun驱动打上了,但是无网络, fake-ip filter也不行. 退坑到netch了, 不搞了

### ISSUE THREAD

**Issue by Jzhnakui** [Fndroid/clash_for_windows_pkg#2434]
### BUG描述

# 如题

## 图一
![image](https://user-images.githubusercontent.com/49728819/143524962-a1b6e1f8-fc8d-4908-8160-d8058a493d1b.png)

![image](https://user-images.githubusercontent.com/49728819/143525053-720b4286-4e5f-4156-8a3f-4121efbfce33.png)

![image](https://user-images.githubusercontent.com/49728819/143525080-b2c60587-7b74-42fb-842a-f40320544bf1.png)

![image](https://user-images.githubusercontent.com/49728819/143525185-2797d9bf-b36f-49ba-a621-ca49fd073307.png)

![image](https://user-images.githubusercontent.com/49728819/143525207-57aff0c8-a153-48db-a74e-14653f5f8851.png)

![image](https://user-images.githubusercontent.com/49728819/143525222-bd2f3682-21e4-45dd-aea1-2a070036a2f0.png)

![image](https://user-images.githubusercontent.com/49728819/143525264-0fadd973-10ec-4ae2-a9d4-efde329e77f3.png)

# 我已经换了5个版本了, 05到10都试了, 开安全模式, 删了config文件夹, 替换wintun, 保证版本是0.14.1, 也都不行, 我已经耗费了7个多小时, 一直在尝试, 配置文件不行和mixin我都单独重新配置了, 还是不行, 不开tun, 是一切正常的, 检测节点也不会timeout.

# 怎么复现? 
## 我不知道, 救救我救救我, 跪谢跪谢
# log信息:
# 2021-11-26-114645.log
time="2021-11-26T11:46:45+08:00" level=info msg="RESTful API listening at: 127.0.0.1:7261"
time="2021-11-26T11:46:45+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
time="2021-11-26T11:46:45+08:00" level=info msg="Start initial compatible provider Others"
time="2021-11-26T11:46:45+08:00" level=info msg="Start initial compatible provider GlobalTV"
time="2021-11-26T11:46:45+08:00" level=info msg="Start initial compatible provider AsianTV"
time="2021-11-26T11:46:45+08:00" level=info msg="Start initial compatible provider Proxy"
time="2021-11-26T11:46:45+08:00" level=info msg="Start initial compatible provider Domestic"
time="2021-11-26T11:46:45+08:00" level=debug msg="Generate GUID: {330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}"
time="2021-11-26T11:47:00+08:00" level=error msg="Start Tun interface error: error creating interface: Cannot create a file when that file already exists."
time="2021-11-26T11:47:08+08:00" level=info msg="Start initial compatible provider Proxy"
time="2021-11-26T11:47:08+08:00" level=info msg="Start initial compatible provider Domestic"
time="2021-11-26T11:47:08+08:00" level=info msg="Start initial compatible provider Others"
time="2021-11-26T11:47:08+08:00" level=info msg="Start initial compatible provider GlobalTV"
time="2021-11-26T11:47:08+08:00" level=info msg="Start initial compatible provider AsianTV"
time="2021-11-26T11:47:08+08:00" level=debug msg="Generate GUID: {330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}"
time="2021-11-26T11:47:08+08:00" level=info msg="Tun Proxy listening at: Clash(198.18.0.1)"
time="2021-11-26T11:47:09+08:00" level=info msg="Start initial compatible provider AsianTV"
time="2021-11-26T11:47:09+08:00" level=info msg="Start initial compatible provider GlobalTV"
time="2021-11-26T11:47:09+08:00" level=info msg="Start initial compatible provider Proxy"
time="2021-11-26T11:47:09+08:00" level=info msg="Start initial compatible provider Domestic"
time="2021-11-26T11:47:09+08:00" level=info msg="Start initial compatible provider Others"
time="2021-11-26T11:47:11+08:00" level=debug msg="Others UDP is not supported"
time="2021-11-26T11:47:11+08:00" level=debug msg="Others UDP is not supported"
time="2021-11-26T11:47:11+08:00" level=info msg="[UDP] 198.18.0.1:5353 --> 224.0.0.251:5353 doesn't match any rule using DIRECT"
time="2021-11-26T11:47:11+08:00" level=info msg="[UDP] 198.18.0.1:55225 --> 224.0.0.252:5355 doesn't match any rule using DIRECT"
time="2021-11-26T11:47:11+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-11-26T11:47:11+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-11-26T11:47:11+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-11-26T11:47:12+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:47:12+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:47:12+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-11-26T11:47:12+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-11-26T11:47:12+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-11-26T11:47:12+08:00" level=info msg="[UDP] 198.18.0.1:1863 --> 221.181.81.223:8014 match GeoIP(CN) using Domestic[DIRECT]"
time="2021-11-26T11:47:13+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:47:13+08:00" level=debug msg="Others UDP is not supported"
time="2021-11-26T11:47:13+08:00" level=info msg="[UDP] 198.18.0.1:49767 --> 239.255.255.250:1900 doesn't match any rule using DIRECT"
time="2021-11-26T11:47:13+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-11-26T11:47:13+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-11-26T11:47:13+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-11-26T11:47:14+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-11-26T11:47:14+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-11-26T11:47:14+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-11-26T11:47:14+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-11-26T11:47:14+08:00" level=debug msg="Others UDP is not supported"
time="2021-11-26T11:47:14+08:00" level=debug msg="Others UDP is not supported"
time="2021-11-26T11:47:14+08:00" level=info msg="[UDP] 198.18.0.1:51773 --> 224.0.0.252:5355 doesn't match any rule using DIRECT"
time="2021-11-26T11:47:14+08:00" level=info msg="[UDP] 198.18.0.1:54361 --> 224.0.0.252:5355 doesn't match any rule using DIRECT"
time="2021-11-26T11:47:15+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-11-26T11:47:16+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-11-26T11:47:16+08:00" level=info msg="[UDP] 198.18.0.1:8000 --> 121.204.38.40:29514 match GeoIP(CN) using Domestic[DIRECT]"
time="2021-11-26T11:47:17+08:00" level=debug msg="[DNS] resolve www.msftconnecttest.com error: all DNS requests failed, first error: read udp4 10.186.16.12:64452->114.114.114.114:53: i/o timeout"
time="2021-11-26T11:47:17+08:00" level=warning msg="[TCP] dial Domestic (match DomainSuffix/microsoft.com) to v10.events.data.microsoft.com:443 error: all DNS requests failed, first error: read udp4 10.186.16.12:49283->8.8.8.8:53: i/o timeout"
time="2021-11-26T11:47:18+08:00" level=warning msg="[TCP] dial DIRECT (match DomainKeyword/feixun) to v2-ty02.feixun.men:19002 error: all DNS requests failed, first error: read udp4 10.186.16.12:49765->114.114.114.114:53: i/o timeout"
time="2021-11-26T11:47:18+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:47:22+08:00" level=warning msg="[TCP] dial Others (match Match/) to www.msftconnecttest.com:80 error: v2-tw01.feixun.men:30004 connect error: all DNS requests failed, first error: read udp4 10.186.16.12:54536->114.114.114.114:53: i/o timeout"
time="2021-11-26T11:47:23+08:00" level=warning msg="[TCP] dial DIRECT (match DomainKeyword/feixun) to v2-ty02.feixun.men:19002 error: all DNS requests failed, first error: read udp4 10.186.16.12:63180->114.114.114.114:53: i/o timeout"
time="2021-11-26T11:47:24+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:47:28+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:47:29+08:00" level=warning msg="[TCP] dial Domestic (match DomainSuffix/microsoft.com) to v10.events.data.microsoft.com:443 error: all DNS requests failed, first error: read udp4 10.186.16.12:56843->8.8.8.8:53: i/o timeout"
time="2021-11-26T11:47:30+08:00" level=info msg="[TCP] 198.18.0.1:7300 --> 112.13.119.18:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2021-11-26T11:47:33+08:00" level=debug msg="[DNS] resolve searchrecommend.kugou.com error: all DNS requests failed, first error: context deadline exceeded"
time="2021-11-26T11:47:34+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:47:35+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:47:36+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:47:38+08:00" level=warning msg="[TCP] dial Others (match Match/) to searchrecommend.kugou.com:80 error: v2-tw01.feixun.men:30004 connect error: all DNS requests failed, first error: context deadline exceeded"
time="2021-11-26T11:47:40+08:00" level=warning msg="[TCP] dial DIRECT (match DomainKeyword/feixun) to v2-ty02.feixun.men:19002 error: all DNS requests failed, first error: read udp4 10.186.16.12:49761->8.8.8.8:53: i/o timeout"
time="2021-11-26T11:47:40+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:47:40+08:00" level=debug msg="[DNS] resolve searchrecommend.kugou.com error: all DNS requests failed, first error: context deadline exceeded"
time="2021-11-26T11:47:41+08:00" level=warning msg="[TCP] dial DIRECT (match DomainKeyword/feixun) to shop.feixun.vip:443 error: all DNS requests failed, first error: context deadline exceeded"
time="2021-11-26T11:47:41+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:47:42+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:47:45+08:00" level=warning msg="[TCP] dial DIRECT (match DomainKeyword/feixun) to v2-ty02.feixun.men:19002 error: all DNS requests failed, first error: read udp4 10.186.16.12:53514->8.8.8.8:53: i/o timeout"
time="2021-11-26T11:47:45+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:47:45+08:00" level=warning msg="[TCP] dial Others (match Match/) to searchrecommend.kugou.com:80 error: v2-tw01.feixun.men:30004 connect error: all DNS requests failed, first error: read udp4 10.186.16.12:53516->114.114.114.114:53: i/o timeout"
time="2021-11-26T11:47:46+08:00" level=warning msg="[TCP] dial DIRECT (match DomainKeyword/feixun) to shop.feixun.vip:443 error: all DNS requests failed, first error: context deadline exceeded"
time="2021-11-26T11:47:47+08:00" level=debug msg="[DNS] resolve searchrecommendretry.kugou.com error: all DNS requests failed, first error: read udp4 10.186.16.12:60904->8.8.8.8:53: i/o timeout"
time="2021-11-26T11:47:49+08:00" level=info msg="[TCP] 198.18.0.1:7314 --> 121.14.40.84:80 match GeoIP(CN) using Domestic[DIRECT]"
time="2021-11-26T11:47:50+08:00" level=warning msg="[TCP] dial DIRECT (match DomainKeyword/feixun) to v2-ty02.feixun.men:19002 error: all DNS requests failed, first error: read udp4 10.186.16.12:55031->8.8.8.8:53: i/o timeout"
time="2021-11-26T11:47:52+08:00" level=warning msg="[TCP] dial Others (match Match/) to searchrecommendretry.kugou.com:80 error: v2-tw01.feixun.men:30004 connect error: all DNS requests failed, first error: read udp4 10.186.16.12:55033->8.8.8.8:53: i/o timeout"
time="2021-11-26T11:47:58+08:00" level=warning msg="[TCP] dial Domestic (match DomainSuffix/microsoft.com) to v10.events.data.microsoft.com:443 error: all DNS requests failed, first error: read udp4 10.186.16.12:55035->8.8.8.8:53: i/o timeout"
time="2021-11-26T11:48:06+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:48:11+08:00" level=warning msg="[TCP] dial DIRECT (match DomainKeyword/feixun) to v2-ty02.feixun.men:19002 error: all DNS requests failed, first error: context deadline exceeded"
time="2021-11-26T11:48:11+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:48:16+08:00" level=warning msg="[TCP] dial DIRECT (match DomainKeyword/feixun) to v2-ty02.feixun.men:19002 error: all DNS requests failed, first error: read udp4 10.186.16.12:54245->8.8.8.8:53: i/o timeout"
time="2021-11-26T11:48:29+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:48:34+08:00" level=warning msg="[TCP] dial DIRECT (match DomainKeyword/feixun) to v2-ty02.feixun.men:19002 error: all DNS requests failed, first error: context deadline exceeded"
time="2021-11-26T11:48:34+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:48:36+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:48:39+08:00" level=warning msg="[TCP] dial DIRECT (match DomainKeyword/feixun) to v2-ty02.feixun.men:19002 error: all DNS requests failed, first error: context deadline exceeded"
time="2021-11-26T11:48:41+08:00" level=warning msg="[TCP] dial DIRECT (match DomainKeyword/feixun) to shop.feixun.vip:443 error: all DNS requests failed, first error: context deadline exceeded"
time="2021-11-26T11:48:41+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:48:46+08:00" level=warning msg="[TCP] dial DIRECT (match DomainKeyword/feixun) to shop.feixun.vip:443 error: all DNS requests failed, first error: read udp4 10.186.16.12:61681->8.8.8.8:53: i/o timeout"
time="2021-11-26T11:48:54+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:48:54+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:48:54+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:48:59+08:00" level=warning msg="[TCP] dial DIRECT (match DomainKeyword/feixun) to v2-ty02.feixun.men:19002 error: all DNS requests failed, first error: context deadline exceeded"
time="2021-11-26T11:48:59+08:00" level=warning msg="[TCP] dial DIRECT (match DomainKeyword/feixun) to v2-ty02.feixun.men:19002 error: all DNS requests failed, first error: context deadline exceeded"
time="2021-11-26T11:48:59+08:00" level=warning msg="[TCP] dial DIRECT (match DomainKeyword/feixun) to v2-ty02.feixun.men:19002 error: all DNS requests failed, first error: context deadline exceeded"
time="2021-11-26T11:48:59+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:48:59+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:48:59+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:49:04+08:00" level=warning msg="[TCP] dial DIRECT (match DomainKeyword/feixun) to v2-ty02.feixun.men:19002 error: all DNS requests failed, first error: read udp4 10.186.16.12:57795->114.114.114.114:53: i/o timeout"
time="2021-11-26T11:49:04+08:00" level=warning msg="[TCP] dial DIRECT (match DomainKeyword/feixun) to v2-ty02.feixun.men:19002 error: all DNS requests failed, first error: read udp4 10.186.16.12:57795->114.114.114.114:53: i/o timeout"
time="2021-11-26T11:49:04+08:00" level=warning msg="[TCP] dial DIRECT (match DomainKeyword/feixun) to v2-ty02.feixun.men:19002 error: all DNS requests failed, first error: read udp4 10.186.16.12:57795->114.114.114.114:53: i/o timeout"
time="2021-11-26T11:49:10+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:49:13+08:00" level=debug msg="Others UDP is not supported"
time="2021-11-26T11:49:13+08:00" level=info msg="[UDP] 198.18.0.1:51639 --> 239.255.255.250:1900 doesn't match any rule using DIRECT"
time="2021-11-26T11:49:15+08:00" level=warning msg="[TCP] dial Domestic (match DomainSuffix/microsoft.com) to go.microsoft.com:443 error: all DNS requests failed, first error: context deadline exceeded"
time="2021-11-26T11:49:15+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:49:16+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:49:16+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:49:16+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:49:20+08:00" level=warning msg="[TCP] dial Domestic (match DomainSuffix/microsoft.com) to go.microsoft.com:443 error: all DNS requests failed, first error: context deadline exceeded"
time="2021-11-26T11:49:20+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:49:21+08:00" level=warning msg="[TCP] dial Domestic (match DomainSuffix/bdstatic.com) to ss1.bdstatic.com:443 error: all DNS requests failed, first error: context deadline exceeded"
time="2021-11-26T11:49:21+08:00" level=warning msg="[TCP] dial Domestic (match DomainSuffix/baidu.com) to www.baidu.com:443 error: all DNS requests failed, first error: context deadline exceeded"
time="2021-11-26T11:49:21+08:00" level=warning msg="[TCP] dial Domestic (match DomainSuffix/bdstatic.com) to dss0.bdstatic.com:443 error: all DNS requests failed, first error: read udp4 10.186.16.12:60007->8.8.8.8:53: i/o timeout"
time="2021-11-26T11:49:21+08:00" level=warning msg="[TCP] dial Domestic (match DomainSuffix/baidu.com) to www.baidu.com:443 error: all DNS requests failed, first error: context deadline exceeded"
time="2021-11-26T11:49:21+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:49:21+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:49:21+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:49:22+08:00" level=debug msg="Others UDP is not supported"
time="2021-11-26T11:49:22+08:00" level=info msg="[UDP] 198.18.0.1:5353 --> 224.0.0.251:5353 doesn't match any rule using DIRECT"
time="2021-11-26T11:49:25+08:00" level=warning msg="[TCP] dial Domestic (match DomainSuffix/microsoft.com) to go.microsoft.com:443 error: all DNS requests failed, first error: context deadline exceeded"
time="2021-11-26T11:49:25+08:00" level=warning msg="[TCP] dial Domestic (match DomainSuffix/microsoft.com) to v10.events.data.microsoft.com:443 error: all DNS requests failed, first error: read udp4 10.186.16.12:56601->8.8.8.8:53: i/o timeout"
time="2021-11-26T11:49:26+08:00" level=warning msg="[TCP] dial Domestic (match DomainSuffix/baidu.com) to www.baidu.com:443 error: all DNS requests failed, first error: read udp4 10.186.16.12:58743->114.114.114.114:53: i/o timeout"
time="2021-11-26T11:49:26+08:00" level=warning msg="[TCP] dial Domestic (match DomainSuffix/baidu.com) to www.baidu.com:443 error: all DNS requests failed, first error: read udp4 10.186.16.12:58743->114.114.114.114:53: i/o timeout"
time="2021-11-26T11:49:26+08:00" level=warning msg="[TCP] dial Domestic (match DomainSuffix/bdstatic.com) to dss0.bdstatic.com:443 error: all DNS requests failed, first error: context deadline exceeded"
time="2021-11-26T11:49:26+08:00" level=warning msg="[TCP] dial Domestic (match DomainSuffix/bdstatic.com) to ss1.bdstatic.com:443 error: all DNS requests failed, first error: context deadline exceeded"
time="2021-11-26T11:49:26+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:49:27+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:49:27+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:49:27+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"

# 2021-11-26-114154.log
time="2021-11-26T11:41:54+08:00" level=info msg="RESTful API listening at: 127.0.0.1:10226"
time="2021-11-26T11:41:54+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
time="2021-11-26T11:41:55+08:00" level=info msg="Start initial compatible provider GlobalTV"
time="2021-11-26T11:41:55+08:00" level=info msg="Start initial compatible provider Others"
time="2021-11-26T11:41:55+08:00" level=info msg="Start initial compatible provider AsianTV"
time="2021-11-26T11:41:55+08:00" level=info msg="Start initial compatible provider Proxy"
time="2021-11-26T11:41:55+08:00" level=info msg="Start initial compatible provider Domestic"
time="2021-11-26T11:41:55+08:00" level=debug msg="Generate GUID: {330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}"
time="2021-11-26T11:41:55+08:00" level=info msg="Tun Proxy listening at: Clash(198.18.0.1)"
time="2021-11-26T11:41:58+08:00" level=debug msg="Others UDP is not supported"
time="2021-11-26T11:41:58+08:00" level=debug msg="Others UDP is not supported"
time="2021-11-26T11:41:58+08:00" level=info msg="[UDP] 198.18.0.1:5353 --> 224.0.0.251:5353 doesn't match any rule using DIRECT"
time="2021-11-26T11:41:58+08:00" level=info msg="[UDP] 198.18.0.1:63919 --> 224.0.0.252:5355 doesn't match any rule using DIRECT"
time="2021-11-26T11:41:58+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-11-26T11:41:58+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-11-26T11:41:58+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-11-26T11:41:59+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2021-11-26T11:41:59+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-11-26T11:41:59+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"
time="2021-11-26T11:41:59+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.255.255 missing"

**Comment by Jzhnakui** [comment]
bug issue类别提交, 我提交不了, 所以试试这里终于提交上去了

**Comment by Jzhnakui** [comment]
换到netch ,ok了

**Comment by kingforme** [comment]
[TUN(fake-ip).txt](https://github.com/Fndroid/clash_for_windows_pkg/files/7608298/TUN.fake-ip.txt)
把TXT的代码复制进mixin
效果图:
![Snipaste_2021-11-26_19-05-05](https://user-images.githubusercontent.com/62692476/143571433-a9be6736-9013-4461-a06d-b173920dcd05.png

**Comment by Nothing-China** [comment]
我遇到的问题是stack设置为system会断网，防火墙加进去就解决了

**Comment by yxt945** [comment]
> [TUN(fake-ip).txt](https://github.com/Fndroid/clash_for_windows_pkg/files/7608298/TUN.fake-ip.txt) 把TXT的代码复制进mixin 效果图: ![Snipaste_2021-11-26_19-05-05](https://user-images.githubusercontent.com/62692476/143571526-05b6e753-a057-4b10-9c8c-cb0bf1fcce51.png)

你的方法很有效，redir-host模式不能访问的twitter也正常了。

**Comment by Jzhnakui** [comment]
> [TUN(fake-ip).txt](https://github.com/Fndroid/clash_for_windows_pkg/files/7608298/TUN.fake-ip.txt) 把TXT的代码复制进mixin 效果图: ![Snipaste_2021-11-26_19-05-05](https://user-images.githubusercontent.com/62692476/143571526-05b6e753-a057-4b10-9c8c-cb0bf1fcce51.png)

牛逼啊兄弟

**Comment by foxnihao** [comment]
> [TUN(fake-ip).txt](https://github.com/Fndroid/clash_for_windows_pkg/files/7608298/TUN.fake-ip.txt) 把TXT的代码复制进mixin 效果图: ![Snipaste_2021-11-26_19-05-05](https://user-images.githubusercontent.com/62692476/143571526-05b6e753-a057-4b10-9c8c-cb0bf1fcce51.png)

十分有效
