### ISSUE TITLE
cfw-tap打红色叉 正常吗

### ISSUE THREAD

**Issue by bjwanghao** [Fndroid/clash_for_windows_pkg#244]
cfw-tap打红色叉 正常吗

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/wiki/%E5%90%AF%E5%8A%A8TAP

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
