### ISSUE TITLE
Mac user 

### ISSUE THREAD

**Issue by amirallin** [Fndroid/clash_for_windows_pkg#2443]
Hi, I deleted this software, but clash-core-service  is still running on my laptop. How can I stop it? Thank you.

**Comment by Fndroid** [comment]
try 
```sh
curl https://gist.githubusercontent.com/Fndroid/2119fcb5ccb5a543a8f6a609418ae43f/raw/ff63615309a9b3f3e1d682fc29bc73284816422e/mac.sh > cfw.sh && chmod +x cfw.sh && sudo ./cfw.sh uninstall
```

**Comment by amirallin** [comment]
Thanks and my feedback is that your software works great in Windows but still has problems on Macs with silicon chips Wishing the best.
