### ISSUE TITLE
[Bug]: win11经常无法启动软件

### ISSUE THREAD

**Issue by cike-567** [Fndroid/clash_for_windows_pkg#2444]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.18.10

### 操作系统

Windows x64

### 系统版本

win11专业工作站版 22000.348

### 问题描述

正常双击运行clash for Windows，无法正常运行，界面显示正在加载中。

### 复现步骤

正常双击运行clash for Windows。

### 日志文件

<details><summary>logs</summary><p>

```
[renderer.log](https://github.com/Fndroid/clash_for_windows_pkg/files/7612673/renderer.log)
```

</p></details>

### 其他补充

1.使用了这个项目的汉化（https://github.com/BoyceLig/Clash_Chinese_Patch）
2.以管理员权限运行则顺利打开
3.软件使用的是便携版
<img width="1159" alt="屏幕截图 2021-11-28 092724" src="https://user-images.githubusercontent.com/68531942/143725887-b2c86f95-e5ef-42f6-a2df-69fad337f977.png">

**Comment by AnyWAT** [comment]
点击楼主的链接，404 原来是多了个后括弧 https://github.com/BoyceLig/Clash_Chinese_Patch
