### ISSUE TITLE
这是什么狗屁玩意儿？

### ISSUE THREAD

**Issue by loyou22** [Fndroid/clash_for_windows_pkg#2448]
更新到最新版以后延迟计算都卡死了。你妈逼你想这么做软件以后就别做了。谁还求着你更新啊

**Comment by Fndroid** [comment]
建议先看医生，有空再上网

**Comment by AkariiinMKII** [comment]
只有你遇到问题了 建议你妈逼的先反思一下自己

**Comment by EpLiar** [comment]
「狗比这玩意儿可爱多了，喂过就算没再喂见了还会冲人摇尾巴。最重要的是狗也不会上网，这玩意经常乌泱批量出墙，难免有时候会让人产生“巴不得墙再高一点”的念头，尤其评论区出现，哪怕只有一只在那儿蛄蛹，就算踩到爆浆都会觉得恶心，坏了一天的好心情」——文件传输助手

**Comment by SetsunaKiyouraTD** [comment]
建议宁自己去写一个高大上的，写不出来就把宁那粪坑般的嘴闭结实然后滚蛋，什么几把😅

**Comment by nonblockio** [comment]
Reported 👌
![Uploading A6B827C7-1FFF-42EE-8EAF-4A90180E1EE2.png…]()

**Comment by Howlingx** [comment]
你们弱智吧没有自己的吧吗

**Comment by micsama** [comment]
素质diao差
