### ISSUE TITLE
下载设置文件出错，提示不能切换到前配置

### ISSUE THREAD

**Issue by hzishuo** [Fndroid/clash_for_windows_pkg#245]
![微信图片_20191105191527](https://user-images.githubusercontent.com/57396590/68203405-ad8e3700-0000-11ea-89f2-e2356eabf43e.png)
下载设置文件出错，提示不能切换到前配置

请问如何操作。

**Comment by Fndroid** [comment]
https://github.com/Dreamacro/clash#config

格式有错，策略组没有节点

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
