### ISSUE TITLE
[Bug]: win11中clash自动选择不能定位到时延最小的节点

### ISSUE THREAD

**Issue by Wilson2003** [Fndroid/clash_for_windows_pkg#2451]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.18.10

### 操作系统

Windows x64

### 系统版本

21H2

### 问题描述

昨天操作系统由win10升级到win11，就出现这个问题：win11中clash的自动选择不能定位到时延最小的节点。clash用的是最新版Clash.for.Windows-0.18.10-win.7z。
另外，win11中把光标放到窗体右上角的最大化小方框上，会显示多窗体布局，clash没有这个功能，这个好像有点吹毛求疵了，哈。

### 复现步骤

再自动选择中点击定位图标。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
自动选择的？选择的应该是它内部测试完时延最小的节点吧，你手动测试，好像需要等全组全部测完吧。

**Comment by Wilson2003** [comment]
在clash界面上依次点击：Proxies--自动选择---test latency--，（等待全部测试完），点击scroll to selected proxy，这个时候并没有定位在时延最小的节点上。

**Comment by Mashiro-qwq** [comment]
这个按钮不是定位到当前使用的节点吗,以前的版本也不是自动选择延迟最低的啊

**Comment by Soizzer** [comment]
Win10 21H2遇到了一样的问题，刷新延时后不会自动排序了，需要点击其他界面后，再返回代理界面，才显示已排好序的节点列表，应该是测速完后的刷新功能有问题了。测试了汉化版、英文原版都一样的问题。用回0.18.9则完全正常。

**Comment by Wilson2003** [comment]
v 0.19.0版本没有这个问题了，谢谢！
