### ISSUE TITLE
[bug] linux mixin 在终端里不起作用

### ISSUE THREAD

**Issue by zzttyy413841467** [Fndroid/clash_for_windows_pkg#2457]
打开mixin，终端里不走代理，ping不通谷歌，设置系统代理才可以curl google.com

内核 IP 路由表
目标            网关            子网掩码        标志  跃点   引用  使用 接口
default         _gateway        0.0.0.0         UG    100    0        0 eno2
link-local      0.0.0.0         255.255.0.0     U     1000   0        0 eno2
172.17.180.0    0.0.0.0         255.255.254.0   U     100    0        0 eno2
noob@504:~$ curl www.google.com
^C
noob@504:~$ ping google.com
PING google.com (142.251.42.238) 56(84) bytes of data.
^C
--- google.com ping 统计 ---
已发送 7 个包， 已接收 0 个包, 100% 包丢失, 耗时 6152 毫秒

mixin 配置

dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114 # 真实请求DNS，可多设置几个
    - 8.8.8.8
tun:
  enable: true
  stack: system # 或 gvisor
  dns-hijack:
    - 1.0.0.1:53 # 请勿更改

日志

time="2021-12-02T18:20:14+08:00" level=info msg="Start initial compatible provider  全球直连"
time="2021-12-02T18:20:14+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2021-12-02T18:20:14+08:00" level=info msg="Start initial compatible provider  节点选择"
time="2021-12-02T18:20:14+08:00" level=info msg="Start initial compatible provider  电报信息"
time="2021-12-02T18:20:14+08:00" level=info msg="Start initial compatible provider  国外媒体"
time="2021-12-02T18:20:14+08:00" level=info msg="Start initial compatible provider  国内媒体"
time="2021-12-02T18:20:14+08:00" level=info msg="Start initial compatible provider  苹果服务"
time="2021-12-02T18:20:14+08:00" level=info msg="Start initial compatible provider  漏网之鱼"
time="2021-12-02T18:20:14+08:00" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2021-12-02T18:20:14+08:00" level=info msg="Start initial compatible provider  全球拦截"
time="2021-12-02T18:20:14+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
time="2021-12-02T18:20:14+08:00" level=info msg="RESTful API listening at: 127.0.0.1:37641"
time="2021-12-02T18:20:15+08:00" level=info msg="Start initial compatible provider  漏网之鱼"
time="2021-12-02T18:20:15+08:00" level=info msg="Start initial compatible provider  全球直连"
time="2021-12-02T18:20:15+08:00" level=info msg="Start initial compatible provider  节点选择"
time="2021-12-02T18:20:15+08:00" level=info msg="Start initial compatible provider  电报信息"
time="2021-12-02T18:20:15+08:00" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2021-12-02T18:20:15+08:00" level=info msg="Start initial compatible provider  全球拦截"
time="2021-12-02T18:20:15+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2021-12-02T18:20:15+08:00" level=info msg="Start initial compatible provider  国外媒体"
time="2021-12-02T18:20:15+08:00" level=info msg="Start initial compatible provider  国内媒体"
time="2021-12-02T18:20:15+08:00" level=info msg="Start initial compatible provider  苹果服务"
time="2021-12-02T18:23:03+08:00" level=info msg="Mixed(http+socks) proxy listening at: [::]:7890"
time="2021-12-02T18:23:53+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
time="2021-12-02T18:27:41+08:00" level=warning msg="[TCP] dial  全球直连 (match Domain/mtalk.google.com) to mtalk.google.com:443 error: dial tcp4 64.233.189.188:443: i/o timeout"
time="2021-12-02T18:27:46+08:00" level=warning msg="[TCP] dial  全球直连 (match Domain/mtalk.google.com) to mtalk.google.com:443 error: dial tcp4 64.233.189.188:443: i/o timeout"
time="2021-12-02T18:30:59+08:00" level=warning msg="[TCP] dial  漏网之鱼 (match Match/) to easylist-downloads.adblockplus.org:443 error: 42.157.196.199:7647 connect error: dial tcp4 42.157.196.199:7647: i/o timeout"
time="2021-12-02T18:31:04+08:00" level=warning msg="[TCP] dial  漏网之鱼 (match Match/) to easylist-downloads.adblockplus.org:443 error: 42.157.196.199:7647 connect error: dial tcp4 42.157.196.199:7647: i/o timeout"
time="2021-12-02T10:37:47+08:00" level=info msg="[TCP] 127.0.0.1:33720 --> mtalk.google.com:5228 match Domain(mtalk.google.com) using  全球直连[DIRECT]"

**Comment by yi-Xu-0100** [comment]
ping 没用，需要 tun

**Comment by zzttyy413841467** [comment]
> ping 没用，需要 tun

地球图标是绿的，应该是开启tun了吧，还需要什么设置

**Comment by yi-Xu-0100** [comment]
@zzttyy413841467 我的描述有歧义，是ping是代理不了的好像，需要用curl测试。tun的话，看connect里有没有tun.还有日志打开debug看看。

**Comment by zzttyy413841467** [comment]
> @zzttyy413841467 我的描述有歧义，是ping是代理不了的好像，需要用curl测试。tun的话，看connect里有没有tun.还有日志打开debug看看。

connection里看不到tun，curl日志没有太大变化，中间能连网是因为采用chrome系统代理



time="2021-12-02T11:36:00+08:00" level=info msg="Start initial compatible provider  苹果服务"
time="2021-12-02T11:36:00+08:00" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2021-12-02T11:36:00+08:00" level=info msg="Start initial compatible provider  节点选择"
time="2021-12-02T11:36:00+08:00" level=info msg="Start initial compatible provider  国内媒体"
time="2021-12-02T11:36:00+08:00" level=info msg="Start initial compatible provider  全球拦截"
time="2021-12-02T11:36:00+08:00" level=info msg="Start initial compatible provider  国外媒体"
time="2021-12-02T11:36:00+08:00" level=info msg="Start initial compatible provider  电报信息"
time="2021-12-02T11:36:00+08:00" level=info msg="Start initial compatible provider  全球直连"
time="2021-12-02T11:36:00+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2021-12-02T11:36:00+08:00" level=info msg="Start initial compatible provider  漏网之鱼"
time="2021-12-02T11:36:00+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
time="2021-12-02T11:36:00+08:00" level=info msg="RESTful API listening at: 127.0.0.1:46803"
time="2021-12-02T11:36:01+08:00" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2021-12-02T11:36:01+08:00" level=info msg="Start initial compatible provider  全球拦截"
time="2021-12-02T11:36:01+08:00" level=info msg="Start initial compatible provider  漏网之鱼"
time="2021-12-02T11:36:01+08:00" level=info msg="Start initial compatible provider  全球直连"
time="2021-12-02T11:36:01+08:00" level=info msg="Start initial compatible provider  苹果服务"
time="2021-12-02T11:36:01+08:00" level=info msg="Start initial compatible provider  国外媒体"
time="2021-12-02T11:36:01+08:00" level=info msg="Start initial compatible provider  国内媒体"
time="2021-12-02T11:36:01+08:00" level=info msg="Start initial compatible provider  电报信息"
time="2021-12-02T11:36:01+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2021-12-02T11:36:01+08:00" level=info msg="Start initial compatible provider  节点选择"
time="2021-12-02T11:36:47+08:00" level=debug msg="[DNS] beacons.gcp.gvt2.com --> 180.163.151.34"
time="2021-12-02T11:36:47+08:00" level=info msg="[TCP] 127.0.0.1:37764 --> beacons.gcp.gvt2.com:443 match GeoIP(CN) using  全球直连[DIRECT]"
time="2021-12-02T11:41:48+08:00" level=debug msg="[DNS] beacons.gcp.gvt2.com --> 180.163.150.162"
time="2021-12-02T11:41:48+08:00" level=info msg="[TCP] 127.0.0.1:37866 --> beacons.gcp.gvt2.com:443 match GeoIP(CN) using  全球直连[DIRECT]"
time="2021-12-02T11:43:26+08:00" level=info msg="[TCP] 127.0.0.1:37880 --> mtalk.google.com:443 match Domain(mtalk.google.com) using  全球直连[DIRECT]"
time="2021-12-02T11:44:42+08:00" level=debug msg="[DNS] www.google.com --> 108.160.172.204"
time="2021-12-02T11:44:42+08:00" level=info msg="[TCP] 127.0.0.1:37886 --> www.google.com:443 match DomainKeyword(google) using  节点选择[ 深港专线2[倍率:2.5]]"
time="2021-12-02T11:44:43+08:00" level=debug msg="[DNS] play.google.com --> 142.251.42.238"
time="2021-12-02T11:44:43+08:00" level=info msg="[TCP] 127.0.0.1:37890 --> play.google.com:443 match DomainKeyword(google) using  节点选择[ 深港专线2[倍率:2.5]]"
time="2021-12-02T11:44:43+08:00" level=debug msg="[DNS] adservice.google.com --> 180.163.151.38"
time="2021-12-02T11:44:43+08:00" level=info msg="[TCP] 127.0.0.1:37894 --> adservice.google.com:443 match DomainKeyword(google) using  节点选择[ 深港专线2[倍率:2.5]]"
time="2021-12-02T11:44:43+08:00" level=debug msg="[DNS] play.google.com --> 142.251.42.238"
time="2021-12-02T11:44:43+08:00" level=info msg="[TCP] 127.0.0.1:37898 --> play.google.com:443 match DomainKeyword(google) using  节点选择[ 深港专线2[倍率:2.5]]"
time="2021-12-02T11:46:57+08:00" level=info msg="[TCP] 127.0.0.1:38120 --> wcpstatic.microsoft.com:443 match DomainKeyword(microsoft) using Ⓜ️ 微软服务[DIRECT]"
time="2021-12-02T11:46:57+08:00" level=info msg="[TCP] 127.0.0.1:38114 --> code.visualstudio.com:443 match DomainSuffix(visualstudio.com) using Ⓜ️ 微软服务[DIRECT]"
time="2021-12-02T11:46:57+08:00" level=info msg="[TCP] 127.0.0.1:38116 --> code.visualstudio.com:443 match DomainSuffix(visualstudio.com) using Ⓜ️ 微软服务[DIRECT]"
time="2021-12-02T11:47:00+08:00" level=info msg="[TCP] 127.0.0.1:38118 --> az725175.vo.msecnd.net:443 match DomainSuffix(msecnd.net) using Ⓜ️ 微软服务[DIRECT]"

**Comment by yi-Xu-0100** [comment]
感觉就没开 tun ，mixin用` ``` `包裹，保留缩进看看你的结果，或者截图看看。

**Comment by zzttyy413841467** [comment]
> 

是这个问题，格式不对
