### ISSUE TITLE
[Feature Request]: 关于修改 Mixin 文件时，强调 【注意缩进！】

### ISSUE THREAD

**Issue by vickychinghk** [Fndroid/clash_for_windows_pkg#2458]
### 功能描述

**在官方 doc 文档中给出的 Mixin 代码，最前面均省略了一个 tab 缩进。**

（垃圾的我搞 tun和tap 的时候出错了一晚上，才发现是少了缩进的问题 TAT

或许可以在 doc 内强调一下，复制过去时记得补足缩进？ 谢谢大佬！

![image](https://user-images.githubusercontent.com/63624554/144425085-07f8ae29-e51c-41b5-8c36-d0dfc0e7d8cf.png)

**Comment by Fndroid** [comment]
mixin是一个功能，tun是一个功能，文档里事例我没看出来哪里有错

**Comment by yi-Xu-0100** [comment]
@vickychinghk 文档中描述无误，没有提到这是 mixin 配置，大概是看到最后的 tip 想当然的认为可以放 mixin 里，就没去看 mixin 的文档了。

![图片](https://user-images.githubusercontent.com/25523606/144436453-2c6fe821-3551-4695-b54b-09ebaa4851cd.png)

**Comment by Oldming1** [comment]
确实，刚才报错了半天发现多了一个空格

**Comment by vickychinghk** [comment]
> mixin是一个功能，tun是一个功能，文档里事例我没看出来哪里有错

没错 没错 TAT，我只是想着要不要强调一下 注意这个点

**Comment by vickychinghk** [comment]
> @vickychinghk 文档中描述无误，没有提到这是 mixin 配置，大概是看到最后的 tip 想当然的认为可以放 mixin 里，就没去看 mixin 的文档了。
> 
> ![图片](https://user-images.githubusercontent.com/25523606/144436453-2c6fe821-3551-4695-b54b-09ebaa4851cd.png)

嗯嗯，刚才没区分清楚。

![image](https://user-images.githubusercontent.com/63624554/144441649-4cdcf957-40ab-4c87-a3a8-f0be350bac11.png)

mixin 中也是有#备注 的，谢谢啦~
