### ISSUE TITLE
便攜版clash-wins配置文件可否放置在程序当前目录里，達致便携U盤方式﹑配置文件保密﹑不需重設? 謝謝

### ISSUE THREAD

**Issue by hxhwing0522** [Fndroid/clash_for_windows_pkg#246]
大佬，你好。

請問便攜版clash windows可以弄一個<配置文件夾>模式，把衍生的配置文件都存在便攜版clash windows程序的当前目录里。

讓程序放在U盤里，隨時可以帶著已設好的配置文件移動到不同PC上使用。

目前便攜版clash windows的配置，都是放在C:\Users\用户名\.config\clash。
這樣有幾個問題:
1. 便攜版clash windows放在U盤里，移動到別的PC也要重新配置文件。
2. 目前配置存在PC里的用戶文件夾。因此配置里的節點資料，也可能被他人看到。拿掉clash時，也要自行刪除配置文件。

希望大佬考慮，能讓clash windows放在U盤隨時使用，不需要每次重新配置。

**Comment by Fndroid** [comment]
@hxhwing0522 请按照文档操作 https://docs.cfw.lbyczf.com/

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
