### ISSUE TITLE
[Feature Request]: 实现开机自动启动时不显示窗口

### ISSUE THREAD

**Issue by fuweichin** [Fndroid/clash_for_windows_pkg#2460]
### 功能描述

设置Start with Windows后，Clash for Windows在每次开机登入后都显示窗口，但此时我并不需要显示窗口，因此我得把它关掉，像关闭广告弹窗一样。

不知该怎么做，才能实现开机自动运行时不显示窗口？禁用Windows快速启动？更改启动项的命令行参数？或者软件自身改动一下？

### 其他内容

Clash for Windows 0.18.3
Windows 10.0.19043

**Comment by 0v0-plus** [comment]
打开 Silent Start 即可
如果使用 Lightweight Mode 每次开机需要前台拉起 clash core.
reference:
#1747 
#2001 
#2255

**Comment by fuweichin** [comment]
谢谢，可以办到。

但我希望在手动启动Clash for Windows时能显示窗口。因为原则上：开启自动启动的一般是服务或Deamon进程，双击启动的一般是GUI程序。

算了，如果不在乎这类原则，那就这样吧。

**Comment by Chen1fly** [comment]
Setting -> General -> Silent Start，On

**Comment by Wilson1823** [comment]
> 

设置了还是显示界面
