### ISSUE TITLE
[Feature Request]: TUN Mode Settings中不强制修改DNS

### ISSUE THREAD

**Issue by Marukon** [Fndroid/clash_for_windows_pkg#2461]
### 功能描述

![1](https://user-images.githubusercontent.com/6285343/144569458-a895fc1a-2c6e-4da5-9dfe-38193200e2d0.png)

建议在此处添加一个“修改dns”的复选框，不勾选的时候允许只保留图中红圈部分的tun配置（因为我的配置文件已经包括了这些dns配置，不想再重复添加了）。

**Comment by Fndroid** [comment]
用mixin

**Comment by JokerQyou** [comment]
如果使用之前版本时，mixin已有tun相关配置，更新之后从界面上的TUN mode settings又填了设置，最终生效的配置是怎么样的？会有优先级之分吗？
