### ISSUE TITLE
[Bug]: clash进程占用大量下载速度，但clash内部的网速指示都是几k的样子

### ISSUE THREAD

**Issue by paulpaulzhang** [Fndroid/clash_for_windows_pkg#2462]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.18开始

### 操作系统

Windows x64

### 系统版本

11

### 问题描述

clash进程占用大量下载速度，但clash内部的网速指示都是几k的样子，把clash代理模式改成直连也不行，试过关闭所有连接，也还是占满了下载带宽，查不到原因，而且只有下午6点左右开始就会出现，白天没有，clash关掉后下载占用就恢复正常

### 复现步骤

我也不知道怎么复现，这个问题就很迷，不像是clash的问题，但感觉又是clash的问题

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by HiMyCocoo** [comment]
我今天任务管理器里以太网Clash显示大约占用了600多M的局域网带宽，然后cpu蹦到了六七十，重启后恢复正常。

**Comment by paulpaulzhang** [comment]
> 

我的每天下午开始都是这样，cpu占用目前最大为20%左右，但带宽基本占满了，重启也没用，甚至重新安装了clash，不知道什么原因，关掉clash就一切正常了

**Comment by HiMyCocoo** [comment]
> > 
> 
> 我的每天下午开始都是这样，cpu占用目前最大为20%左右，但带宽基本占满了，重启也没用，甚至重新安装了clash，不知道什么原因，关掉clash就一切正常了

我占的是内网的带宽

**Comment by paulpaulzhang** [comment]
> 

我应该是外网带宽，网站都打不开了，非常离谱

**Comment by paulpaulzhang** [comment]
已经解决，关闭允许局域网连接就行了
