### ISSUE TITLE
系统代理老是偷偷的关闭

### ISSUE THREAD

**Issue by Mrvivi** [Fndroid/clash_for_windows_pkg#247]
我在使用软件的过程当中经常发现系统代理被关闭了，更新了v0.8.0之后明显些了，其实我按照https://github.com/Fndroid/clash_for_windows_pkg/wiki/%E7%B3%BB%E7%BB%9F%E4%BB%A3%E7%90%86%E5%BC%82%E5%B8%B8%E5%85%B3%E9%97%AD
这个教程操作过了，还是发现系统代理又被关闭了。我附上log了。
[logs.zip](https://github.com/Fndroid/clash_for_windows_pkg/files/3813232/logs.zip)

**Comment by WongRuoran** [comment]
你试试用管理员权限运行

**Comment by bruceCzK** [comment]
允许局域网连接也是同样的问题

**Comment by singledoggy** [comment]
使用process monitor 监测是什么修改了注册表种的proxy enable选项，我因此解决了部分问题。这不是clash的原因，是一些奇怪的软件为了保证可以一直长期连接成功设置的，firefox浏览器会自动关闭，微信和qq有时候会自动打开。

**Comment by Fndroid** [comment]
refer: https://github.com/Fndroid/clash_for_windows_pkg/issues/312
