### ISSUE TITLE
[Bug]: 更新后安装目录发生了变化

### ISSUE THREAD

**Issue by binglin1009** [Fndroid/clash_for_windows_pkg#2472]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.0

### 操作系统

Windows x64

### 系统版本

win10-21H2

### 问题描述

直接点击版本号，弹出来的窗口点击Update，下载完毕后更新，程序被安装到了C:\Users\xxuser\AppData\Local\Programs 目录下。更新之前，程序是放在D盘的。

### 复现步骤

见上面描述。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
先用exe安装一次，之后安装会装到对应目录。如果解压出来，安装器并不知道你之前解压在哪里
