### ISSUE TITLE
WIN7系统上传速度异常，可否修复？

### ISSUE THREAD

**Issue by gengruihuan** [Fndroid/clash_for_windows_pkg#248]
我尝试了很多软件，目前只有sstap在WIN7系统上上传速度能跑满速，其他的所有软件包括您的这个clash都只有200K左右，sstap能17M/S左右，不知什么原因，希望能修复

**Comment by LitingLin** [comment]
其实你这issue发跟没发一样，鬼知道为啥呦

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
