### ISSUE TITLE
[Bug]: TUN Mode 设置界面无法使用键盘

### ISSUE THREAD

**Issue by mwhds97** [Fndroid/clash_for_windows_pkg#2487]
软件版本：0.19.1

操作系统：Windows 8.1 9600

问题描述：在 TUN Mode 设置界面中，按下任一键盘按钮，设置界面就会直接关闭，导致无法修改 TUN 设置

**Comment by sfc9982** [comment]
软件版本：0.19.1

操作系统：Windows 10 21H2

问题描述：在 TUN Mode 设置界面中，按下任一键盘按钮，设置界面就会直接关闭，导致无法修改 TUN 设置

同上

**Comment by Fndroid** [comment]
已知问题，下个版本修复
