### ISSUE TITLE
[BUG] lightweight mode 下程序关闭后再打开，proxies里面不显示节点，要到profiles里面点选一下配置文件后节点才会显示

### ISSUE THREAD

**Issue by srrshweee** [Fndroid/clash_for_windows_pkg#2495]
lightweight mode 下程序关闭后再打开，proxies里面不显示节点，要到profiles里面点选一下配置文件后节点才会显示。这个问题0.19.1才有，之前的版本没有发现。尝试过删除CFW以后清理系统，重新安装和导入profiles，问题依旧。
不好意思，按照issue里面选择bug的哪个模式，我提交issue显示400错误页面，所以直接提了。

**Comment by Fndroid** [comment]
复现一次，点左下角文字，发日志

**Comment by srrshweee** [comment]
[2021-12-11-104328.log](https://github.com/Fndroid/clash_for_windows_pkg/files/7696300/2021-12-11-104328.log)

**Comment by srrshweee** [comment]
[2021-12-11-104658.log](https://github.com/Fndroid/clash_for_windows_pkg/files/7696307/2021-12-11-104658.log)

**Comment by Fndroid** [comment]
bug，下个版本修复，影响使用的话先退回上一个版本

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
