### ISSUE TITLE
TUN模式，每次电脑重启后无法联网。必须手动关、开TUN一次。 

### ISSUE THREAD

**Issue by leafsoul365** [Fndroid/clash_for_windows_pkg#2496]
### 功能描述

TUN模式，每次电脑重启后无法联网。必须手动关、开TUN一次。

**Comment by boot-vue** [comment]
我的同时开启TAP  TUN模式   系统代理不管打不打开    主机上网  代理都没问题

每次都要重新 关 开 一下TUN模式   vmware虚拟机内才能正常使用宿主机clash代理

**Comment by bigbaldy1128** [comment]
问题一样

**Comment by Marukon** [comment]
三台电脑全部复现

**Comment by Fndroid** [comment]
发一下tun的配置

**Comment by Marukon** [comment]
mixin:
  tun:
    enable: true
    stack: gvisor
    dns-hijack:
      - 198.18.0.2:53
    macOS-auto-route: true
    macOS-auto-detect-interface: true


重新mixin开关后立即恢复正常。0.19.0一切正常，0.19.1新出现的故障。

**Comment by xushulang** [comment]
问题相同

**Comment by leafsoul365** [comment]
@Fndroid 
Mixin配置如下，TUN模式下的本身配置也基本和mixin同样。 
无论是单独开启TUN模式，或是Mixin混合，都同样存在重启电脑无法联网问题，关 开一次自动恢复正常。
mixin: 
  dns:
    enable: true
    enhanced-mode: fake-ip
    nameserver:
    - 114.114.114.114
    - 8.8.8.8
   tun:
    enable: true
    stack: gvisor 
    dns-hijack:
    - 198.18.0.2:53
    auto-route: true
    auto-detect-interface: true

**Comment by uuip** [comment]
我的解决方法是用0.19.0 ，在启动clash前先执行清理。DevManView.exe /uninstall "Clash Tunnel"
https://www.nirsoft.net/utils/device_manager_view.html

**Comment by Fndroid** [comment]
下个版本修复

**Comment by yangchuansheng** [comment]
> 下个版本修复

建议 tun 模式支持修改 enhanced-mode 的值

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases

**Comment by bhxxwx** [comment]
0.19.2版本依旧存在这个问题

**Comment by shikkoku** [comment]
0.19.2确实仍有问题。

**Comment by Bryan2333** [comment]
0.19.2仍存在此问题

**Comment by Loukyuu1120** [comment]
有问题的试试把Tun Mode reset一下，或者是直接用Tun Mode

**Comment by shikkoku** [comment]
> 有问题的试试把Tun Mode reset一下，或者是直接用Tun Mode

我不用Tun Mode，一直用Mixin，不过我还是尝试Reset了一下。

**Comment by Loukyuu1120** [comment]
> > 有问题的试试把Tun Mode reset一下，或者是直接用Tun Mode
> 
> 我不用Tun Mode，一直用Mixin，不过我还是尝试Reset了一下。

我也不用Tun Mode，不清楚是不是共性，反正我是通过reset了下tun mode网卡之后开启tun mode，Mixin关闭着，tun网卡也能用，再用回Mixin之后重启电脑是不需要重开Mixin模式了。

**Comment by shikkoku** [comment]
> > > 有问题的试试把Tun Mode reset一下，或者是直接用Tun Mode
> > 
> > 
> > 我不用Tun Mode，一直用Mixin，不过我还是尝试Reset了一下。
> 
> 我也不用Tun Mode，不清楚是不是共性，反正我是通过reset了下tun mode配置之后开启tun mode，Mixin关闭着，tun网卡也能用，再用回Mixin之后重启电脑是不需要重开Mixin模式了。

我今天冷启动还是不行。开机看不到Clash的虚拟TUN网卡，只有重新开关一次Tun mode才行。Tun stack 选了 system。

**Comment by iocscix** [comment]
0.19.11 tun mode 默认配置，任务栏图标，more->重启 也存在这个问题

**Comment by imbian** [comment]
0.19.12依然存在此问题，0.19.0没有这问题

**Comment by Turing-Wu** [comment]
0.19.15 仍存在此问题

**Comment by The-OAA** [comment]
0.19.13 仍存在此问题

**Comment by jazzychai** [comment]
0.19.15 仍存在此问题

**Comment by UNY7438** [comment]
0.19.17 仍存在此问题

**Comment by WayneStyle** [comment]
0.19.19仍然存在此问题

**Comment by iocscix** [comment]
0.19.20 仍然存在此问题

**Comment by justdoiting** [comment]
0.19.23仍然存在此问题
log如下：
time="2022-07-14T23:13:41+08:00" level=info msg="Start initial configuration in progress"
time="2022-07-14T23:13:41+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2022-07-14T23:13:41+08:00" level=info msg="Initial configuration complete, total time: 2ms"
time="2022-07-14T23:13:41+08:00" level=info msg="Sniffer is closed"
time="2022-07-14T23:13:41+08:00" level=info msg="Start initial compatible provider default"
time="2022-07-14T23:13:41+08:00" level=info msg="RESTful API listening at: 127.0.0.1:12052"
time="2022-07-14T23:13:58+08:00" level=error msg="[TUN] Timed out waiting for device query: 等待的操作过时。 (Code 0x00000102)"
time="2022-07-14T23:13:58+08:00" level=error msg="[TUN] Failed to setup adapter (problem code: 0x1F, ntstatus: 0xC0000001): 连到系统上的设备没有发挥作用。 (Code 0x0000001F)"
time="2022-07-14T23:13:58+08:00" level=error msg="Start TUN listening error: can't open tun: create tun: Error creating interface: A device attached to the system is not functioning."

**Comment by z10056** [comment]
0.19.23还是有这问题，
具体表现为：
service mode 绿色
tun mode 已打开
正常重启，，重启之后service mode和tun mode都是打开状态，重启之后不会显示tun网卡，得手动重新开关一下tun mode才会有tun网卡，cfw是用管理员权限运行的。否则创建的tun网卡会提示无法连接到因特网，从而无法科学上网。

**Comment by families** [comment]
0.19.25有同样问题，无法解决，必须手动关闭再启用一次tun开关，才会有tun网卡。

**Comment by z10056** [comment]
> 0.19.25有同样问题，无法解决，必须手动关闭再启用一次tun开关，才会有tun网卡。

别安装到c盘和给管理员权限一般就没啥问题了。但如果你不是admin的系统权限，cfw是无法开启自启的

**Comment by kidult1039** [comment]
同问这个问题有没有解法，给了管理员权限 还是不行

**Comment by googidaddy** [comment]
依旧存在

**Comment by sosgaa** [comment]
i'm in mac13.2,it seem that open cfw notfications,closed the random controller port,that solve
