### ISSUE TITLE
[Feature Request]: 对proxy-providers订阅的节点也启用check按钮，以便单独测试某个节点的延时

### ISSUE THREAD

**Issue by FrankAirs** [Fndroid/clash_for_windows_pkg#2499]
### 功能描述

您好，我提一个建议，不知是否合适：

现状：通过proxy-providers订阅的所有节点，只有统一测试延时
期望：对proxy-providers订阅的节点，也能添加check按钮，以便单独测试某个节点的延时

![Snipaste_2021-12-12_03-15-42](https://user-images.githubusercontent.com/91299174/145688880-c5209bab-cc2b-46a0-a908-9aed1cde9db6.png)

**Comment by yi-Xu-0100** [comment]
core issue: <https://github.com/Dreamacro/clash/issues>
