### ISSUE TITLE
Logs可否按命中规则的时间排序？

### ISSUE THREAD

**Issue by billowcbt** [Fndroid/clash_for_windows_pkg#250]
发现Logs不是按命中规则的时间排序的，最新命中的规则有时出现在顶部，有时出现在底部，查看logs不太方便。
统一出现在顶部或者底部都不会影响查看（如果出现在底部最好也能自动向下滚动logs）。
希望考虑下，谢谢！

**Comment by Fndroid** [comment]
什么版本

**Comment by billowcbt** [comment]
> 
> 
> 什么版本

最新的0.8.1

**Comment by billowcbt** [comment]
又去仔细观察了一下，0.8.1版本的logs好像都是生成在底部，但软件不会自动向下滚动，要手动往下拉滚动条。
之前的版本的logs生成在顶部和底部都有。

**Comment by billowcbt** [comment]
> 
> 
> 什么版本

0.8.1版。
又去仔细观察了一下，0.8.1版本的logs好像都是生成在底部，但软件不会自动向下滚动，要手动往下拉滚动条。
之前的版本的logs生成在顶部和底部都有。

**Comment by Fndroid** [comment]
0.8.1是按顺序的，还有暂停控制，自动向下滚动我觉得没有必要，暂停下来再看就好了

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
