### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by autumn789** [Fndroid/clash_for_windows_pkg#2506]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.1

### 操作系统

Windows x64

### 系统版本

20H2

### 问题描述

更新版本时，软件安装在新的目录C:\Users\username\AppData\Local\Programs\Clash for Windows，而不是原本的目录

### 复现步骤

更新软件

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
如果第一次不是用 exe 安装的，而是用 zip 直接使用，update 时，无法知道上次安装目录。

**Comment by autumn789** [comment]
> 如果第一次不是用 exe 安装的，而是用 zip 直接使用，update 时，无法知道上次安装目录。

谢谢！
