### ISSUE TITLE
请问这两种情况该怎么解决啊

### ISSUE THREAD

**Issue by RudeTheJack** [Fndroid/clash_for_windows_pkg#251]
![QQ图片20191110175419](https://user-images.githubusercontent.com/27954602/68542070-33d0c180-03e3-11ea-9ef6-10c8d76e3ab2.png)
![QQ图片20191110175537](https://user-images.githubusercontent.com/27954602/68542076-56fb7100-03e3-11ea-9474-5c41adab41dc.png)

**Comment by RudeTheJack** [comment]
![QQ图片20191110175939](https://user-images.githubusercontent.com/27954602/68542128-e99c1000-03e3-11ea-87f2-2cf8266acb3d.png)
还有一种情况，是我的电脑缺少什么吗

**Comment by RudeTheJack** [comment]
![QQ图片20191110180455](https://user-images.githubusercontent.com/27954602/68542166-a2624f00-03e4-11ea-906f-e50248bc494d.png)

**Comment by Fndroid** [comment]
1. 没有能打开YAML格式的应用，所以打不开config.yml文件
2. 不懂忽略就好
3. 配置文件格式错误
4. 配置文件格式错误

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
