### ISSUE TITLE
[Bug]: TUN Mode Settings Dialog crashes when typing info

### ISSUE THREAD

**Issue by codafi21** [Fndroid/clash_for_windows_pkg#2510]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.1

### 操作系统

Windows x64

### 系统版本

22000.348

### 问题描述

![Screenshot 2021-12-14 161538](https://user-images.githubusercontent.com/93474348/145967433-227fc954-2ff3-475f-8558-5cac137647f8.png)
when typing info in this dialog, the dislog crashes instantly

### 复现步骤

as per my info above

### 日志文件

<details><summary>logs</summary><p>

</p></details>

### 其他补充

plz fix this

**Comment by Fndroid** [comment]
It's a bug and will be fixed in the next release

**Comment by codafi21** [comment]
> It's a bug and will be fixed in the next release

how to revert settings in the dialog to default, coz i cant use tun without dns empty

**Comment by Fndroid** [comment]
That's nothing you can do. Install 0.19.0 or wait for 0.19.2

**Comment by codafi21** [comment]
> That's nothing you can do. Install 0.19.0 or wait for 0.19.2

ok ima use the old method, turn off mixin and turn on turn mode when 0.19.2 releases

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
