### ISSUE TITLE
[Bug]: Clash For Windows 内存不停在变化

### ISSUE THREAD

**Issue by luojunyuan** [Fndroid/clash_for_windows_pkg#2516]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.0

### 操作系统

Windows x64

### 系统版本

windows 11

### 问题描述

Clash For Windows 内存从10mb-70mb不停循环变化，大概30秒循环一次的频率。

### 复现步骤

打开 Clash For WIndows 和 Taskmanager 观察内存。

### 日志文件

无

### 其他补充

为什么内存会一直在变化？这个现象对计算机或者对软件性能会有什么影响吗

**Comment by yi-Xu-0100** [comment]
只要不是一直增大，不是多大影响。

**Comment by lucky812** [comment]
这是正常现象

**Comment by ririliu** [comment]
不明白gui程序的逻辑，为什么使用内存会一直升高，然后降低（触发gc？），这个时候系统甚至没有任何网络活动，处于完全闲置状态下。

**Comment by luojunyuan** [comment]
> 不明白gui程序的逻辑，为什么使用内存会一直升高，然后降低（触发gc？），这个时候系统甚至没有任何网络活动，处于完全闲置状态下。

仔细看硬盘写入，内存降低的时候是把内存写入到硬盘的，猜测内存升高是软件活动模块再次把内存从硬盘中拿出来。我不知道怎么实现的，但目的无非是为了让electron内存占用看起来更好看罢了，硬盘在不停读写，读写的量好像不大应该不至于对硬盘有什么影响
