### ISSUE TITLE
Allow LAN

### ISSUE THREAD

**Issue by bjwanghao** [Fndroid/clash_for_windows_pkg#252]
修改配置文件allow-lan :   true   开机重起 造成System Proxy关闭.bug吗

**Comment by Fndroid** [comment]
allow-lan设置和System Proxy被关闭并没有关联，系统代理被关闭可能是其他软件造成的。

可以尝试：
1. [清除系统代理设置](https://github.com/Fndroid/clash_for_windows_pkg/wiki/%E7%B3%BB%E7%BB%9F%E4%BB%A3%E7%90%86%E5%BC%82%E5%B8%B8%E5%85%B3%E9%97%AD)
2. 排除其他代理类/网盘类应用关闭系统代理
3. 使用TAP模式

**Comment by Fndroid** [comment]
refer: https://github.com/Fndroid/clash_for_windows_pkg/issues/312
