### ISSUE TITLE
如何设置纯ipv6全局呀？

### ISSUE THREAD

**Issue by fuxiansen** [Fndroid/clash_for_windows_pkg#2522]
### 功能描述

如何设置ipv6节点全局？

**Comment by yi-Xu-0100** [comment]
global mode ？

**Comment by fuxiansen** [comment]
好像没有用，自己添加了ipv6DNS，在纯ipv6节点下还是无法使用，想知道在哪里更改DNS的yaml配置文件

**Comment by yi-Xu-0100** [comment]
@fuxiansen 节点的 dns 配置由节点自己配置，自己配置的 dns 是本地解析然后判断规则用

**Comment by fuxiansen** [comment]
> @fuxiansen 节点的 dns 配置由节点自己配置，自己配置的 dns 是本地解析然后判断规则用

有点搞不懂，可以多给讲一些吗，我现在有一个自己搭建的clash节点（通过在线转换）我现在在本地禁止ipv4协议后，无法使用，可以问一下具体点的如何配置吗？

**Comment by yi-Xu-0100** [comment]
@fuxiansen dns 配置给本地，解析域名后走规则，如果去了节点，节点仍然需要使用节点的服务器配置去解析域名，这是为了 cdn。所以 clash 配置中的 dns 只是给本地用的。你是否启用 ipv6 取决于你本地的配置，而不是你节点的配置。

cdn 参考 https://github.com/Fndroid/clash_for_windows_pkg/discussions/1426#discussioncomment-226251

**Comment by fuxiansen** [comment]
> @fuxiansen dns 配置给本地，解析域名后走规则，如果去了节点，节点仍然需要使用节点的服务器配置去解析域名，这是为了 cdn。所以 clash 配置中的 dns 只是给本地用的。你是否启用 ipv6 取决于你本地的配置，而不是你节点的配置。
> 
> cdn 参考 [#1426 (comment)](https://github.com/Fndroid/clash_for_windows_pkg/discussions/1426#discussioncomment-226251)

我明白你的意思，就是不知道在本地如何设置,想知道clash如何设置才能全局走ipv6(只有ipv6环境，校园网ipv6)

**Comment by yi-Xu-0100** [comment]
一般使用 mixin。

https://docs.cfw.lbyczf.com/contents/mixin.html

**Comment by Fndroid** [comment]
你把v4禁用了之后 nslookup 你节点的域名有返回v6地址吗

**Comment by fuxiansen** [comment]
> 一般使用 mixin。
> 
> https://docs.cfw.lbyczf.com/contents/mixin.html

谢谢你的回复，mixin确实可以。tun却不可以

**Comment by fuxiansen** [comment]
> 你把v4禁用了之后 nslookup 你节点的域名有返回v6地址吗，如果有的话，理论上打开General里的ipv6开关就可以了

![image](https://user-images.githubusercontent.com/58103411/146555254-9fb18a9e-8354-4900-91ca-4b1bfd3974a5.png)
节点返回有v6地址，mixin添加ipv6DNS后可以用，tun却不行，已经尝试过多次。在其他电脑也有测试，确实不行。
