### ISSUE TITLE
尝试修复 issue template 的问题

### ISSUE THREAD

**Issue by yi-Xu-0100** [Fndroid/clash_for_windows_pkg#2524]
用 github.dev 去查看 issue template 的时候，发现有一些检查出来的错误。尝试修复一下，看看会不会有好转。

![图片](https://user-images.githubusercontent.com/25523606/146498178-3f555520-cf98-41a7-9d4b-434c5d7e14ec.png)

**Comment by Fndroid** [comment]
感谢感谢
