### ISSUE TITLE
[Feature Request]: 可否提高首页TUN模式设置里DNS部分的优先级

### ISSUE THREAD

**Issue by LeslieYon** [Fndroid/clash_for_windows_pkg#2529]
### 功能描述

如题，首页TUN模式里的DNS设置在mixin中有DNS设置时，会不生效  
这会有一种这里DNS设置无效的感觉  
按照界面的逻辑，TUN模式里的DNS设置应该是专用于TUN模式的  
另外，如果想要在TUN模式单独设置一套DNS配置，提高优先级也会方便一些  
麻烦大佬考虑下

**Comment by yi-Xu-0100** [comment]
mixin 可以替换配置文件的所有字段（包含 DNS 和 tun），且在内存中完成处理，所以最后一步处理，优先级最高。
如果同时使用 tun 和 mixin ，建议 mixin 中不包含 tun 配置。
如果 mixin 中除了 tun 配置无其他。那两个应该是二选一的。

> TUN模式里的DNS设置应该是专用于TUN模式的

个人理解，此处的 TUN 模式只是提供一个带 GUI 模板并只能配置 DNS 和 TUN 配置的，方便不会使用 mixin 的用户使用的。也就是说，这里的 TUN 模式的配置是配置文档的字段，DNS 字段也是服务整个 Clash 流程的，并没有说专注于 TUN 模式。所以，即使你单独设置了 DNS ，也都只有一个生效，不会有某个用于 TUN ，某个用于其他的说法。
