### ISSUE TITLE
0.8.1不能记忆代理选择

### ISSUE THREAD

**Issue by Amonhuz** [Fndroid/clash_for_windows_pkg#253]
0.8.1在更改代理选择后退出重开，会恢复成默认的第一个代理，无法记忆退出前的选择。
0.8.0正常。

Windows 10 1903

**Comment by Fndroid** [comment]
重新下载安装

**Comment by Amonhuz** [comment]
解决了，但是不知道什么原因造成的，可能是我操作太快吧-_-。

我删除了.config和AppData\Roaming\clash_win，然后运行0.8.1。
.config\clash\profiles\下没有自动生成yml配置文件，而且.config\clash\profiles\list.yml中不会保存代理选择，点击几次左侧的标签Log和Proxies切换之后，就可以保存了。

非常感谢！
