### ISSUE TITLE
[Bug]: mac os，开启service mode后dns被频繁修改

### ISSUE THREAD

**Issue by fire7night** [Fndroid/clash_for_windows_pkg#2530]
安装service mode后系统dns被改为1.1.1.1 114.114.114.114
打开tun，dns为tun设置的dns；关闭tun，则会恢复1.1.1.1 114.114.114.114（这时为什么不是恢复isp的dns呢？）。
我的网络环境需要上游自动配置的网关，不能用1.1.1.1 114.114.114.114，有办法解决吗？

**Comment by yi-Xu-0100** [comment]
订阅的配置内容里是否有 dns 字段？

**Comment by fire7night** [comment]
> 

有的

**Comment by fire7night** [comment]
> 订阅的配置内容里是否有 dns 字段？

有的

**Comment by fire7night** [comment]
> > 订阅的配置内容里是否有 dns 字段？
> 
> 有的

dns:
  enable: true
  listen: 127.0.0.1:8853
  default-nameserver:
    - 223.5.5.5
    - 1.0.0.1
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.10.0.1/16
  fake-ip-filter:
    - "*.lan"
    - stun.*.*.*
    - stun.*.*
...
..
.

**Comment by yi-Xu-0100** [comment]
把这个 enable 设置为 false 试试

**Comment by fire7night** [comment]
> 把这个 enable 设置为 false 试试

不太行，只有关掉service mode才不会改

**Comment by fire7night** [comment]
重装mac系统可解决，具体原因未知

**Comment by UntaggedRui** [comment]
我也遇到了这个问题，总是被重置为1.1.1.1 114.114.114.114

**Comment by fanyang89** [comment]
我也遇到了这个问题。更新订阅之后手动设置的 DNS 就被替换了
