### ISSUE TITLE
请添加 snell v3的支持

### ISSUE THREAD

**Issue by Weeker** [Fndroid/clash_for_windows_pkg#2537]
### 功能描述

https://github.com/surge-networks/snell/releases/tag/v3.0.0b1

UDP over TCP relay support

Optimized for high throughput.
Port Restricted Cone NAT support. (aka NAT type 2)
Connection reuse is deprecated in v3. But the server-side program still supports v2/v1 clients.

snell 已经进行v3的更新，希望能够支持，谢谢

**Comment by Fndroid** [comment]
clash core issue, refer: https://github.com/Dreamacro/clash/issues
