### ISSUE TITLE
could not run Clsah core（0.8.1）

### ISSUE THREAD

**Issue by meetljm** [Fndroid/clash_for_windows_pkg#254]
作者好，0.7.12升级了0.8.1 启动报了这个错误：time="2019-11-11T11:37:57+08:00" level=fatal msg="Parse config error: Proxy [3]: uuid: incorrect UUID length: uuid"
请问这个要怎么解决？

**Comment by Fndroid** [comment]
和新版无关，就是你config.yml写错了

**Comment by meetljm** [comment]
我把整个配置文件目录删除重新安装就好了
