### ISSUE TITLE
[Feature Request]: 希望在tun mode选项中添加fallback-filter和fake-ip-range选项的设置

### ISSUE THREAD

**Issue by Solitaryender** [Fndroid/clash_for_windows_pkg#2549]
### 功能描述

截至CFW 0.19.2版本，TUN Mode Settings选项中仍无法更改fallback-filter和fake-ip-range
![图片](https://user-images.githubusercontent.com/65836154/147250488-036a75d8-4454-4e4d-82cc-1aa7f2effafa.png)

**Comment by shikkoku** [comment]
🤣Mixin还要不要了

**Comment by YirunFantasy** [comment]
@Fndroid 无语了，前段时间冒出来个不能改DNS的，后来又说个DNS不能劫持的，再现在还有要求这个加filter的，马上就变成俩Mixin了，除了优先级有区别，人的欲望是无止境的，真没必要为了易用给人加个tun模式按钮，这加法做的，作者受累，使用者还挑剔，就还是老式的Mixin解决一切就行，真有心帮新手，在wiki文档里更新一下，弄个Mixin模板，他不会用，复制黏贴总会吧，连这个也不会的话，说实话，你已经从开发者变成保姆了，没啥意义了

**Comment by GHOSTagw** [comment]
确实，Tun还是集成在Mixin里比较好，复制黏贴很省事，而且选项也更多更细。

**Comment by kingsey** [comment]
直接用Mixin吧，想设置啥设置啥  优先级还高

**Comment by Solitaryender** [comment]
虽然我本人用的就是mixin来着…… 也不知道为什么有人就推导出觉得我不会用mixin才来问这个问题的……
