### ISSUE TITLE
用了clash_for_windows便携版后vps被封，说是有垃圾邮件经过vps发出

### ISSUE THREAD

**Issue by bluehysteric** [Fndroid/clash_for_windows_pkg#255]
用了clash_for_windows便携版后vps被封（大概使用了不到半个小时），说是有垃圾邮件经过vps发出,vps本身已经使用快2年没出过任何问题，win10新装的有nod32保护另外里面只装了chrome和steam，下面是vps被封的信息：
Reason:	Network abuse: Mass Mailing
More details:	We have detected a large number of outgoing SMTP connections originating from this server. This usually means that the server is sending out spam.
Additional information:

1573416153.871165	CBWnE14GW4L6jQ1lo5	97.65.122.132	48316	172.253.112.27	25	1	DETqwO	-	-	-	-	-	-	-	-	-	-	-	-	-	220 2.0.0 Ready to start TLS	172.253.112.27,97.65.122.132	-	T	(empty)	F

1573416594.287512	CBexet3ugVsLu6hsbb	97.65.122.132	46842	74.125.195.109	587	1	0ungsshiqlgfzpz7kzv	4utre3@gmail.com	0ungsshiqlgfzpz7kzv@gmail.com	-	-	-	-	-	-	-	-	-	-	-	221 2.0.0 closing connection i11sm11430792pgd.7 - gsmtp	74.125.195.109,97.65.122.132	-	F	(empty)	F

1573416601.062265	CAsLpu2cy70WYVF2c2	97.65.122.132	33168	173.194.192.27	25	1	hng8nbj06tbx1iza	4utre3@gmail.com	hng8nbj06tbx1iza@gmail.com	-	-	-	-	-	-	-	-	-	-	-	221 2.0.0 closing connection y14si14793033jar.69 - gsmtp	173.194.192.27,97.65.122.132	-	F	(empty)	F

1573416696.197963	CA80QV1YxzCPfvVte4	97.65.122.132	38032	198.235.201.2	587	1	csHsqULvKhdWuWJ	-	-	-	-	-	-	-	-	-	-	-	-	-	220 Ready to start TLS	198.235.201.2,97.65.122.132	-	T	(empty)	F

1573416792.304114	Ct6qUC1XZWvDEAmtka	97.65.122.132	54390	207.69.189.209	587	1	9284RERHW47AA90V42H8RQSFL7QUUL	-	-	-	-	-	-	-	-	-	-	-	-	-	220 TLS go ahead	207.69.189.209,97.65.122.132	-	T	(empty)	F

1573416895.581784	CLgihv1lNYUgqEyzfl	97.65.122.132	38946	62.36.20.30	25	1	8AK5BBW0JZ6ARTLDFHF	mdsdepor@ya.com	serv_1@yahoo.com	-	Drema Venable <mdsdepor@ya.com>	<serv_1@yahoo.com>	-	-	-	-	What are you doing on...	-	-	-	550 Your message was declared SPAM in Vade Retro system //	62.36.20.30,97.65.122.132	-	F	FDv1cq4i5j2Hcg2t09	F

1573416892.223168	C6Fyhx4cepYQw1eIy8	97.65.122.132	33214	74.125.199.26	25	1	k0eqx5t49735rtegqdvwvirv	4utre3@gmail.com	k0eqx5t49735rtegqdvwvirv@gmail.com	-	-	-	-	-	-	-	-	-	-	-	221 2.0.0 closing connection d2si14971593pln.233 - gsmtp	74.125.199.26,97.65.122.132	-	F	(empty)	F

1573416899.051140	CLgihv1lNYUgqEyzfl	97.65.122.132	38946	62.36.20.30	25	2	8AK5BBW0JZ6ARTLDFHF	mdsdepor@ya.com	nathans.rapid@gmail.com	-	Drema Venable<mdsdepor@ya.com>	<nathans.rapid@gmail.com>	-	-	-	-	I want to ask you, but its not my ambision.	-	-	-	550 Your message was declared SPAM in Vade Retro system //	62.36.20.30,97.65.122.132	-	F	F6vyIvocw1wRXEPma	F

1573416912.198328	CnMJUg4FRe7mzxSJpg	97.65.122.132	33638	74.125.199.26	25	1	2cqrflvt2jkjokx87wnp	4utre3@gmail.com	2cqrflvt2jkjokx87wnp@gmail.com	-	-	-	-	-	-	-	-	-	-	-	221 2.0.0 closing connection w80si10187911pfc.187 - gsmtp	74.125.199.26,97.65.122.132	-	F	(empty)	F

1573416921.896761	CB1mgt2pY9grzfNG3e	97.65.122.132	35628	195.121.65.26	587	1	U0CU717BV7FKK3PA2PCYWCD1DGY3D	-	-	-	-	-	-	-	-	-	-	-	-	-	220 2.0.0 Ready to start TLS	195.121.65.26,97.65.122.132	-	T	(empty)	F

1573416967.644766	CjUOWCCrllPJgDZ7f	97.65.122.132	40362	62.36.20.30	25	1	ZLVHL6HA4HU9YQ6ZZ0U8SHBE7R31C1	cjgomez@ya.com	bs63638@ail.com	-	Nam Weise <cjgomez@ya.com>	bs63638@ail.com	-	-	-	-	\xe2\x9c\xa8There is a half for everyone in this world, might you be mine?\xf0\x9f\x94\xa5	-	-	-	550 Your message was declared SPAM in Vade Retro system //	62.36.20.30,97.65.122.132	-	F	FCHbQ51sQHezvWvH1a	F

1573416964.263913	Cf4LsO112DFiwZ3emi	97.65.122.132	38936	173.194.202.27	25	1	xecccbxko47j9bo3ayk0exnk	4utre3@gmail.com	xecccbxko47j9bo3ayk0exnk@gmail.com	-	-	-	-	-	-	-	-	-	-	-	221 2.0.0 closing connection 36si4303796plf.237 - gsmtp	173.194.202.27,97.65.122.132	-	F	(empty)	F

1573416971.117504	CjUOWCCrllPJgDZ7f	97.65.122.132	40362	62.36.20.30	25	2	ZLVHL6HA4HU9YQ6ZZ0U8SHBE7R31C1	cjgomez@ya.com	nathans.rapid@gmail.com	-	Nam Weise<cjgomez@ya.com>	nathans.rapid@gmail.com	-	-	-	-	\xf0\x9f\x92\x8bA princess is waiting for a prince\xf0\x9f\x91\x84	-	-	-	550 Your message was declared SPAM in Vade Retro system //	62.36.20.30,97.65.122.132	-	F	FgdE8A4PFpAbwsChF1	F

Abuse points:	100 – points added for this suspension
Total abuse points:	100 – total points already accumulated during current calendar year
Max abuse points:	1300 – maximum points allowed within one calendar year; after reaching this number service will be permanently suspended until end of year.
How to resolve:	This usually happens when your server is rooted/hacked. Make sure to install a clean OS immediately after resuming service, otherwise the issue will likely repeat.
You can unsuspend service as long as Total abuse points accumulated within one calendar year is less than Max abuse points allowed by your plan.
By clicking the button above you agree to take all measures to prevent future TOS violations.
You also acknowledge that if/when Total abuse points exceeds Maximum abuse points within this calendar year, then service will be disabled until January 1, 2021.

麻烦看看怎么回事

**Comment by ttimasdf** [comment]
在vps上把服务端的log打开看看。如果你是v2或者ss的话所有外联都是有日志的。

**Comment by bluehysteric** [comment]
我今天又换了个服务器，禁用密码，用密钥登录v2配置了tls，依然是这个情况，又被封了
这个vps的通知

Reason: | Network abuse: Mass Mailing
-- | --
More details: | We have detected a large number of outgoing SMTP connections originating from this server. This usually means that the server is sending out spam.Additional information:


1573512397.005396	Cll8cD1VSBEphGXkq2	172.95.218.153	51166	67.195.228.106	25	1	007q.com	infocuvvu@007q.com	kingsummere420@yahoo.com,kingsup73@yahoo.com,kingsummers420@yahoo.com,kingsun0009@yahoo.com,kingsunmarc91@yahoo.com,kingsunny@yahoo.com,kingsup1@yahoo.com	Mon, 11 Nov 2019 11:03:34 -1100	"Yahoo Premium Dating" <infocuvvu@007q.com>	<kingsummere420@yahoo.com>	-	"Yahoo Premium Dating" <infocuvvu@007q.com>	<AE3607B7.63336C33@007q.com>	-	You've received an invitation from Olivia to an adult dating site	-	from [131.202.250.180] by asx121.turbo-inline.com with LOCAL; Mon, 11 Nov 2019 11:15:54 -1100	from [72.225.223.109] by webmail.halftomorrow.com with SMTP; Mon, 11 Nov 2019 11:24:18 -1100	250 ok dirdel 1/6	67.195.228.106,172.95.218.153,72.225.223.109,131.202.250.180	-	F	FhNRnq3hP1FKK7Kksj	F

1573512405.820102	Cll8cD1VSBEphGXkq2	172.95.218.153	51166	67.195.228.106	25	2	007q.com	infocuvvu@007q.com	kirbydyer@yahoo.com,kirbyearle@yahoo.com	Mon, 11 Nov 2019 12:57:31 -0900	"Yahoo Premium Dating" <infocuvvu@007q.com>	<kirbydyer@yahoo.com>	-	"Yahoo Premium Dating" <infocuvvu@007q.com>	<188E3CAD.BBBA8A4F@007q.com>	-	You've received an invitation from Brianna to an adult dating site	-	from smtp.doneohx.com [184.147.87.107] by smtp4.cyberemailings.com with ESMTP; Mon, 11 Nov 2019 13:18:44 -0900	from relay.2yahoo.com ([Mon, 11 Nov 2019 13:25:32 -0900])\x09by qnx.mdrost.com with QMQP; Mon, 11 Nov 2019 13:25:32 -0900	250 ok dirdel 0/2	67.195.228.106,172.95.218.153,26.148.138.7,184.147.87.107	-	F	FDvntB5lYheWs8Fke	F

1573512409.789040	Cll8cD1VSBEphGXkq2	172.95.218.153	51166	67.195.228.106	25	3	007q.com	infocuvvu@007q.com	kireyonadesirablepeaches@yahoo.com	Mon, 11 Nov 2019 18:07:49 -0400	"Yahoo Premium Dating" <infocuvvu@007q.com>	<kireyonadesirablepeaches@yahoo.com>	-	-	<C1C8C4E7.C9891AA9@007q.com>	-	You've received an invitation from Autumn to an adult dating site	-	from public.micromail.com.au [130.9.73.90] by m1.gns.snv.thisdomainl.com with SMTP; Mon, 11 Nov 2019 18:09:54 -0400	from [181.51.69.246] by smtp.endend.nl with QMQP; Mon, 11 Nov 2019 18:11:48 -0400	250 ok dirdel	67.195.228.106,172.95.218.153,124.92.51.244,105.31.112.157,181.51.69.246,130.9.73.90	-	F	FXrcwd4Y1SU5T7wto9	F

1573512408.554629	CzDYeu3vE9DNiWcokl	172.95.218.153	51174	67.195.228.106	25	1	01media.it	adminekobc@01media.it	kingranch48@yahoo.com,kingranch@yahoo.com,kingranch86@yahoo.com,kingranch4564@yahoo.com,kingranch82@yahoo.com,kingrat007-bond@yahoo.com	Mon, 11 Nov 2019 21:07:07 -0100	"Yahoo Premium Dating" <adminekobc@01media.it>	<kingranch4564@yahoo.com>	-	-	<7726545B.E3B26AE7@01media.it>	-	You've received an invitation from Jocelyn to an adult dating site	-	from mtu67.syds.piswix.net ([55.40.244.188]) by smtp.endend.nl with ASMTP; Mon, 11 Nov 2019 21:33:18 -0100	-	421 4.7.0 [IPTS04] Messages from 172.95.218.153 temporarily deferred due to user complaints - 4.16.55.1; see https://help.yahoo.com/kb/postmaster/SLN3434.html	67.195.228.106,172.95.218.153,55.40.244.188	-	F	FwUyyc2FWIESPBcEzb	F

1573512412.403002	CeNpT91velB39fnwT6	172.95.218.153	58446	67.195.204.82	25	1	001.co.jp	adminah@001.co.jp	-	-	-	-	-	-	-	-	-	-	-	-	421 4.7.0 [TSS04] Messages from 172.95.218.153 temporarily deferred due to user complaints - 4.16.55.1; see https://help.yahoo.com/kb/postmaster/SLN3434.html	67.195.204.82,172.95.218.153	-	F	(empty)	F

1573512413.241195	Cll8cD1VSBEphGXkq2	172.95.218.153	51166	67.195.228.106	25	4	007q.com	infocuvvu@007q.com	kirk2622@yahoo.com,kirk2327@yahoo.com,kirk2510@yahoo.com,kirk2425@yahoo.com,kirk20@yahoo.com,kirk202536@yahoo.com,kirk22wood24@yahoo.com	Mon, 11 Nov 2019 23:29:58 +0100	"Yahoo Premium Dating" <infocuvvu@007q.com>	<kirk202536@yahoo.com>	-	-	<72240DBE.E21DB21C@007q.com>	-	You've received an invitation from Melanie to an adult dating site	-	from asx121.turbo-inline.com ([Mon, 11 Nov 2019 23:38:53 +0100])\x09by mail.webhostings4u.com with SMTP; Mon, 11 Nov 2019 23:38:53 +0100	-	421 4.7.0 [IPTS04] Messages from 172.95.218.153 temporarily deferred due to user complaints - 4.16.55.1; see https://help.yahoo.com/kb/postmaster/SLN3434.html	67.195.228.106,172.95.218.153	-	F	FHlSmY2bLcOq9Bo4S	F

1573512415.641204	CTV3Ak1RBTsyS10Cz9	172.95.218.153	51180	67.195.228.106	25	1	00810.com	infoosyq@00810.com	-	-	-	-	-	-	-	-	-	-	-	-	421 4.7.0 [TSS04] Messages from 172.95.218.153 temporarily deferred due to user complaints - 4.16.55.1; see https://help.yahoo.com/kb/postmaster/SLN3434.html	67.195.228.106,172.95.218.153	-	F	(empty)	F

1573512463.204925	C8L8gN3w5fFux9kJik	172.95.218.153	50478	67.195.228.94	25	1	0-173.com	adminziaxe@0-173.com	-	-	-	-	-	-	-	-	-	-	-	-	421 4.7.0 [TSS04] Messages from 172.95.218.153 temporarily deferred due to user complaints - 4.16.55.1; see https://help.yahoo.com/kb/postmaster/SLN3434.html	67.195.228.94,172.95.218.153	-	F	(empty)	F

1573512480.363538	CiogDZ2SET7kJ3nzFd	172.95.218.153	35060	104.47.0.33	25	1	0-glove.com	infocuje@0-glove.com	jorgenieves224@msn.com,jesshotmail@msn.com,joellemeunier3@msn.com,terapin1@msn.com,slonakerge@msn.com,alberto_robles@msn.com,ranoronha@msn.com	Tue, 12 Nov 2019 03:36:26 +0500	"Dating for sex" <infocuje@0-glove.com>	<ranoronha@msn.com>	<jesshotmail@msn.com>,<terapin1@msn.com>,<slonakerge@msn.com>,<joellemeunier3@msn.com>,<jorgenieves224@msn.com>,<alberto_robles@msn.com>	"Dating for sex" <infocuje@0-glove.com>	<B1214771.F7431411@0-glove.com>	-	savannah	-	from external.newsubdomain.com ([Tue, 12 Nov 2019 03:45:03 +0500])\x09by external.newsubdomain.com with LOCAL; Tue, 12 Nov 2019 03:45:03 +0500	-	250 2.6.0 <B1214771.F7431411@0-glove.com> [InternalId=63127429391716, Hostname=HE1EUR01HT045.eop-EUR01.prod.protection.outlook.com] 8264 bytes in 0.133, 60.481 KB/sec Queued mail for delivery	104.47.0.33,172.95.218.153	-	F	Fb7jlq23GryU7p3HZ6	F

1573512490.877848	Cybp5QSPHPILccrji	172.95.218.153	35064	104.47.0.33	25	1	007escorts.co.uk	infosnaoc@007escorts.co.uk	alexcarmona22@msn.com,adam1423@msn.com,gedlschaaf@msn.com,selly0@msn.com	Mon, 11 Nov 2019 17:15:42 -0500	"Dating for sex" <infosnaoc@007escorts.co.uk>	<adam1423@msn.com>,<gedlschaaf@msn.com>,<alexcarmona22@msn.com>,<selly0@msn.com>	-	-	<9559533D.B80D7A4A@007escorts.co.uk>	-	haley	-	from unknown (HELO mail.gimmicc.net) (Mon, 11 Nov 2019 17:19:57 -0500)\x09by group21.345mail.com with ASMTP; Mon, 11 Nov 2019 17:19:57 -0500	from unknown (159.173.165.129)\x09by mail.webhostings4u.com with SMTP; Mon, 11 Nov 2019 17:29:26 -0500	250 2.6.0 <9559533D.B80D7A4A@007escorts.co.uk> [InternalId=62955630696281, Hostname=HE1EUR01HT109.eop-EUR01.prod.protection.outlook.com] 7866 bytes in 0.151, 50.573 KB/sec Queued mail for delivery	104.47.0.33,172.95.218.153,159.173.165.129	-	F	Fy4SCF2iKfvknJLaRc	F

1573512498.069540	Cybp5QSPHPILccrji	172.95.218.153	35064	104.47.0.33	25	2	007escorts.co.uk	infosnaoc@007escorts.co.uk	mollystarlight@msn.com,brumitfamily@msn.com	Mon, 11 Nov 2019 12:15:01 -1000	"Dating for sex" <infosnaoc@007escorts.co.uk>	<brumitfamily@msn.com>	-	"Dating for sex" <infosnaoc@007escorts.co.uk>	<414B6869.28D09414@007escorts.co.uk>	-	nicole	-	from unknown (160.133.36.150)\x09by mail.webhostings4u.com with SMTP; Mon, 11 Nov 2019 12:34:19 -1000	-	250 2.6.0 <414B6869.28D09414@007escorts.co.uk> [InternalId=44053479629201, Hostname=HE1EUR01HT185.eop-EUR01.prod.protection.outlook.com] 7494 bytes in 0.153, 47.664 KB/sec Queued mail for delivery	104.47.0.33,172.95.218.153,160.133.36.150	-	F	FbYf6E1XKQKVpppXN9	F

1573512499.796408	ClkDR83g0q7QmMnXS7	172.95.218.153	34496	104.47.14.33	25	1	001.jp	infopluz@001.jp	ninagunn@hotmail.de,mel28w@hotmail.de,beat_sigrist@hotmail.de	Tue, 12 Nov 2019 07:47:08 +1000	"Dating for sex" <infopluz@001.jp>	<ninagunn@hotmail.de>	-	-	<41FBC230.53AE6D7F@001.jp>	-	kaylee	-	from asx121.turbo-inline.com [65.249.94.226] by smtp18.yenddx.com with ESMTP; Tue, 12 Nov 2019 08:04:58 +1000	from mxs.perenter.com ([Tue, 12 Nov 2019 08:05:56 +1000])\x09by qrx.quickslick.com with ASMTP; Tue, 12 Nov 2019 08:05:56 +1000	250 2.6.0 <41FBC230.53AE6D7F@001.jp> [InternalId=67899138059704, Hostname=VI1EUR04HT095.eop-eur04.prod.protection.outlook.com] 7836 bytes in 0.053, 142.886 KB/sec Queued mail for delivery	104.47.14.33,172.95.218.153,168.116.22.198,65.249.94.226	-	F	FMxUZO3LE6zvpdUmzf	F

1573512504.784606	C744Sc2RvroOXYyOJ6	172.95.218.153	39948	104.47.125.33	25	1	000-000-0000.com	adminsz@000-000-0000.com	mighty_tom123@live.com,geoff.moon@live.com	Mon, 11 Nov 2019 23:39:05 +0200	"Dating for sex" <adminsz@000-000-0000.com>	<mighty_tom123@live.com>,<geoff.moon@live.com>	-	-	<F683DCCB.6CBFCC88@000-000-0000.com>	-	katelyn	-	from [141.48.167.212] by smtp.endend.nl with LOCAL; Tue, 12 Nov 2019 00:05:13 +0200	from unknown (HELO m1.gns.snv.thisdomainl.com) (Tue, 12 Nov 2019 00:15:59 +0200)\x09by snmp.otwaloow.com with QMQP; Tue, 12 Nov 2019 00:15:59 +0200	250 2.6.0 <F683DCCB.6CBFCC88@000-000-0000.com> [InternalId=67881958186387, Hostname=SG2APC01HT187.eop-APC01.prod.protection.outlook.com] 7708 bytes in 0.202, 37.258 KB/sec Queued mail for delivery	104.47.125.33,172.95.218.153,176.190.43.30,141.48.167.212	-	F	FrgUls23ydS1ZGuYld	F

1573512507.577380	Ckql721VPL3rQ0nGaj	172.95.218.153	39950	104.47.125.33	25	1	0085.co.jp	infosood@0085.co.jp	stephk1970@live.com,musad88@live.com,angelchavis@live.com,kaiowklds@live.com,sirbirk@live.com	Mon, 11 Nov 2019 18:40:44 -0400	"Dating for sex" <infosood@0085.co.jp>	<stephk1970@live.com>	<musad88@live.com>,<angelchavis@live.com>,<sirbirk@live.com>,<kaiowklds@live.com>	"Dating for sex" <infosood@0085.co.jp>	<1A51B2EC.5DC20ADD@0085.co.jp>	-	sara	-	from mx.reskind.net ([146.146.60.151]) by mx03.listsystemsf.net with ESMTP; Mon, 11 Nov 2019 18:42:39 -0400	-	250 2.6.0 <1A51B2EC.5DC20ADD@0085.co.jp> [InternalId=68006512237962, Hostname=SG2APC01HT214.eop-APC01.prod.protection.outlook.com] 7836 bytes in 0.167, 45.736 KB/sec Queued mail for delivery	104.47.125.33,172.95.218.153,146.146.60.151	-	F	FmYvnE8bjcOeMt9k8	F

1573512512.443532	CznQME4RbZyPH04DOg	172.95.218.153	60604	104.47.5.33	25	1	0-shop.com	adminqodxv@0-shop.com	elbanderin@hotmail.es	Mon, 11 Nov 2019 15:03:07 -0700	"Dating for sex" <adminqodxv@0-shop.com>	<elbanderin@hotmail.es>	-	-	<A38007E8.1254FB98@0-shop.com>	-	vanessa	-	from unknown (HELO smtp18.yenddx.com) (Mon, 11 Nov 2019 15:16:40 -0700)\x09by mts.locks.grgtween.net with LOCAL; Mon, 11 Nov 2019 15:16:40 -0700	from mail.gimmicc.net [14.108.45.226] by webmail.halftomorrow.com with QMQP; Mon, 11 Nov 2019 15:33:06 -0700	250 2.6.0 <A38007E8.1254FB98@0-shop.com> [InternalId=43782896694601, Hostname=HE1EUR02HT065.eop-EUR02.prod.protection.outlook.com] 7656 bytes in 0.329, 22.704 KB/sec Queued mail for delivery -> 250 2.1.5	104.47.5.33,172.95.218.153,200.37.109.29,54.94.222.89,14.108.45.226	-	F	FCSRyU20nI1unXeZ9l	F

Abuse points: | 100 – points added for this suspension
-- | --
Total abuse points: | 100 – total points already accumulated during current calendar year
Max abuse points: | 1300 – maximum points allowed within one calendar year; after reaching this number service will be permanently suspended until end of year.
How to resolve: | This usually happens when your server is rooted/hacked. Make sure to install a clean OS immediately after resuming service, otherwise the issue will likely repeat.You can unsuspend service as long as Total abuse points accumulated within one calendar year is less than Max abuse points allowed by your plan.By clicking the button above you agree to take all measures to prevent future TOS violations.You also acknowledge that if/when Total abuse points exceeds Maximum abuse points within this calendar year, then service will be disabled until January 1, 2020.

一会我把日志打开看看

**Comment by bluehysteric** [comment]
> 在vps上把服务端的日志打开看看。如果你是v2或ss的话所有外联都是有日志的。

关机是我pc端，是新系统，而且本身是正版，并非什么装机盘或者来路不明，而且系统里面没有装什么软件，nod32也正常，而且这几个vps我都用了有些年头了。。因为我的vps都是在mac上用从来没出国问题，

**Comment by Fndroid** [comment]
clash只是一个客户端，没有能耐操控vps发邮件吧。。

**Comment by bluehysteric** [comment]
> 有能耐干扰vps发邮件吧。。

我不知道，技术上的事情，应该你更专业点，我不确定是不是clash win这个版本有问题，但可以肯定的是，开了以后半小时内必出问题，我第一个那个vps我用了全局代理我也怀疑是不是电脑系统有问题，所以第二个vps我在clash里面只规定了google和youtube可以走代理其他的全部正常走，基本上不到半个小时就挂了。

**Comment by bluehysteric** [comment]
2019/11/11 17:46:35 117.67.236.233:51798 accepted tcp:67.195.228.106:25 
2019/11/11 17:46:41 117.67.236.233:51802 accepted tcp:www.google.dk:443 
2019/11/11 17:46:44 117.67.236.233:51804 accepted tcp:95.100.139.28:80 
2019/11/11 17:46:46 117.67.236.233:51806 accepted tcp:23.62.130.245:80 
2019/11/11 17:46:47 117.67.236.233:51808 accepted tcp:67.195.228.106:25 
2019/11/11 17:46:51 117.67.236.233:51811 accepted tcp:67.195.204.82:25 
2019/11/11 17:46:52 117.67.236.233:51812 accepted tcp:23.62.130.245:443 
2019/11/11 17:46:54 117.67.236.233:51814 accepted tcp:**67.195.228.106**:25
上面是v2服务端日志
下面是vps给的警告可以看见里面的垃圾邮件地址的确走了v2的线路
1573512397.005396 Cll8cD1VSBEphGXkq2 172.95.218.153 51166 **67.195.228.106** 25 1 007q.com infocuvvu@007q.com kingsummere420@yahoo.com，kingsup73@yahoo.com，kingsummers420@yahoo.com，kingsun0009@yahoo.com，kingsunmarc91@yahoo.com，金顺怡@ yahoo.com，kingsup1 @yahoo.com 2019年11月11日，星期一11:03:34 -1100“雅虎高级约会” infocuvvu@007q.com kingsummere420@yahoo.com- “雅虎高级约会” infocuvvu@007q.com AE3607B7。 63336C33@007q.com -您已经从Olivia收到了一个成人约会网站的邀请-asx121.turbo-inline.com与LOCAL的[131.202.250.180]；2019年11月11日星期一11:15:54 -1100来自[72.225.223.109]通过webmail.halftomorrow.com使用SMTP; 2019年11月11日星期一11:24:18 -1100 250 ok dirdel 1/6 67.195.228.106,172.95.218.153,72.225.223.109,131.202.250.180-F FhNRnq3hP1FKK7Kksj F

**Comment by Fndroid** [comment]
> **67.195.228.106**:25

看起来是你PC上的SMTP请求被代理到VPS上了

**Comment by bluehysteric** [comment]
> > **67.195.228.106**：25
> 
> 看起来是你PC上的SMTP请求被代理到VPS上了

是的，但是代理我只允许google和youtube走代理其他的都是走本地，它是怎么代理到vps呢，而且我电脑里面也没有装其他的软件，就一个chrome和steam都是官网下的。nod32也是。而且第一次vps挂了我就查过毒了，防火墙也是开启的。。真是奇了怪了。晚上在拿个vps测试一下吧，这次换个软件看看是不是还有这个问题

**Comment by bluehysteric** [comment]
我已经用恢复过的vps测试了如surge /Proxifier/v2rayn这3个客户端，每个客户端全局代理测试了个40分钟目前没有出现被封的问题，一会在用clash for win看看。

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
