### ISSUE TITLE
帮忙解答一下Mixin和Diff使用的问题和bypass与TUN的优先级问题

### ISSUE THREAD

**Issue by YirunFantasy** [Fndroid/clash_for_windows_pkg#2557]
使用过程中，得知Mixin是自己写的模板和订阅来的配置文件，在内存里动态混合后生效，不对本地文件进行修改，对吧，那出于个人的一些原因，比如订阅的配置文件里我不想用

  1. 写的是geoip : true ,而我自己的Mixin模板里按自己需要设置的是false，那么这个时候针对这同一个“开关”，Mixin混合之后，生效的是我的配置false，还是订阅文件的配置true呢？

  2. 配置文件里的namesever和fallback都有机场提供的几个DNS，但都不是我想要用的，我自己在Mixin里编写了完全不同的DNS，混合之后，是叠加一起生效，还是某一边被覆盖呢？覆盖的话是哪一边被覆盖？
  
  3. 我在bypass里添加了一个域名，但是我同时开启了system proxy 和 TUN（Mixin模式），跳过代理的那个域名会不会被TUN反手再接回来？不是说TUN就专治那些不走代理的吗？那这样是要手动添加direct规则吗 ?还是说我多想了，bypass优先级更高？

- 1-2问题目前我是通过Diff把订阅文件我不喜欢的地方给删除之后锁定了，然后通过Mixin补足我删掉的那些部分，感觉有点麻烦，累倒是次要的，主要是不明白运行机制，有点迷，能帮忙解答一下吗，我能通过什么已有的方法解决

**Comment by yi-Xu-0100** [comment]
diff 文档：https://docs.cfw.lbyczf.com/contents/diff.html

从文档看，Diff 处理会在预处理之后进行。

而 mixin 是处理完配置文件之后。

所以，mixin 优先级最高，且为覆盖式配置。

system proxy 优先级高于 tun，bypass 的应该会被 tun 接管，最好测试下，建议加上规则。

**Comment by Fndroid** [comment]
mixin开关打开后，会将mixin里的内容覆盖到你配置文件对应的内容，按最上层键覆盖（dns/tun等），mixin开关是对所有配置文件有效，但不会更改配置文件内容

bypass只影响system proxy，要绕过TUN需要自己加路由表
