### ISSUE TITLE
[Feature Request]: 配置文件名相关请求

### ISSUE THREAD

**Issue by yangyucacaa** [Fndroid/clash_for_windows_pkg#2559]
### 功能描述

建议下载订阅文件没有响应头时用下载的文件名做配置名，而不是订阅URL后缀。

**Comment by yi-Xu-0100** [comment]
如果有下载的文件名的话，应该用的就是下载的文件名吧。

**Comment by yangyucacaa** [comment]
不是的，用的是订阅地址的最后一部分> 如果有下载的文件名的话，应该用的就是下载的文件名吧。

**Comment by yangyucacaa** [comment]
> 如果有下载的文件名的话，应该用的就是下载的文件名吧。

用的是订阅url最后一部分
