### ISSUE TITLE
有pca模式么

### ISSUE THREAD

**Issue by momomoi** [Fndroid/clash_for_windows_pkg#2560]
### 功能描述

之前用其他的软  都有pca和全局代理模式，第一次用这个发现没有，请问怎么开启pca模式

**Comment by Fndroid** [comment]
你有没有想过为什么要pac

**Comment by momomoi** [comment]
> 你有没有想过为什么要pac
在自己的电脑(地点A）上登陆一个自己的VPN来访问公司（地点B）内部服务器，同时打开clashx（地点C)，发现系统代理这时候只能2选1，  因为我初使用 是我哪里没有设置好吗？ 还麻烦解答下   谢谢～

**Comment by Fndroid** [comment]
我还是没有明白，你是要开两个本地代理用pac分流进去？
