### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by bbhxwl** [Fndroid/clash_for_windows_pkg#2566]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.4

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

我老版本的订阅地址，在新版本不能用，有什么区别么？老版本是1年前的版本了。

### 复现步骤

我老版本的订阅地址，在新版本不能用，有什么区别么？老版本是1年前的版本了。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
配置文件的字段有重大更新，见：https://github.com/Dreamacro/clash/wiki/breaking-changes-in-1.0.0
