### ISSUE TITLE
[Bug]: snell version error:3

### ISSUE THREAD

**Issue by Weeker** [Fndroid/clash_for_windows_pkg#2569]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.4

### 操作系统

Windows x64

### 系统版本

Win10

### 问题描述

![image](https://user-images.githubusercontent.com/295112/147850867-0fadfe47-271e-4259-b209-2ee4aa158e5c.png)

希望能支持 version: 3 谢谢
https://github.com/surge-networks/snell/releases/tag/v3.0.0rc2

### 复现步骤

 snell配置文件改为 version: 3 就报错

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
core issue: <https://github.com/Dreamacro/clash/issues>
