### ISSUE TITLE
设置domain-keyword direct不生效

### ISSUE THREAD

**Issue by kbill4345** [Fndroid/clash_for_windows_pkg#257]
设置路径：profiles-Edit rules，新增domain-keyword为指定域名的关键词，模式选择direct，保存后重启clash；如keyword=sony，域名www.sony.com生效direct，mm.sony.com不生效 无法访问，关闭clash，mm.sony.com正常访问；

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
