### ISSUE TITLE
[Feature Request]:【建议】 增强托盘的悬浮窗 可调整显示范围区域

### ISSUE THREAD

**Issue by wokaozws** [Fndroid/clash_for_windows_pkg#2577]
### 功能描述

想做个天气小玩意但如果是双排显示的话这字体太小了
![image](https://user-images.githubusercontent.com/6488577/148001696-6cf8c044-e4cf-477d-a74d-8008feb46f70.png)
单排的话也有长度限制
![image](https://user-images.githubusercontent.com/6488577/148001880-5f73ef98-aed8-4428-b2a5-d50484474d37.png)

建议：可配置调整悬浮窗大小  或 可通过脚本控制

**Comment by Fndroid** [comment]
长度其实是会自动识别你内容宽度，只是你这里放的超过了我设置的最大值，我可以把值调大但是太长不会不好看嘛

**Comment by yi-Xu-0100** [comment]
@wokaozws 不知道脚本是否开源？看起来很震撼！🙌

**Comment by Fndroid** [comment]
上个版本已经增加最大宽度限制了

**Comment by canyinga** [comment]
卧槽,求
