### ISSUE TITLE
[Feature Request]: 更新配置但不覆盖规则

### ISSUE THREAD

**Issue by bolieriniefu** [Fndroid/clash_for_windows_pkg#2596]
### 功能描述

从URL更新了订阅之后，规则会重新覆盖，之前设置的会被顶掉，我如何只更新节点而不更新规则呢？谢谢。

**Comment by yi-Xu-0100** [comment]
parser: <https://docs.cfw.lbyczf.com/contents/parser.html>

**Comment by bolieriniefu** [comment]
> parser: https://docs.cfw.lbyczf.com/contents/parser.html

感谢您，我成功插入了一些规则，但请问如何删去规则呢？我看command可以删去节点，规则的语法怎样呢？

**Comment by bolieriniefu** [comment]
> parser: https://docs.cfw.lbyczf.com/contents/parser.html

我可以用 rule.0- 来删去第一条规则，但我如何定位关键字来删去规则呢？谢谢

**Comment by yi-Xu-0100** [comment]
@bolieriniefu 建议用 js 语法尝试操作。或者在规则最上面的地方添加新的规则覆盖掉旧的规则（规则匹配会按照从上到下的顺序）

**Comment by bolieriniefu** [comment]
> @bolieriniefu 建议用 js 语法尝试操作。或者在规则最上面的地方添加新的规则覆盖掉旧的规则（规则匹配会按照从上到下的顺序）

问题解决了，谢谢！

**Comment by bolieriniefu** [comment]
> @bolieriniefu 建议用 js 语法尝试操作。或者在规则最上面的地方添加新的规则覆盖掉旧的规则（规则匹配会按照从上到下的顺序）

我发现在添加规则时，只有添加单引号才起作用，不知道这是否是我个人的问题。
写成：
          prepend-rules:
            - DOMAIN-KEYWORD,steamstatic,🍃 Proxies

能够在规则里看到它被添加了，但并不起作用。
写成：
          prepend-rules:
            - 'DOMAIN-KEYWORD,steamstatic,🍃 Proxies'

这时才起作用，我不知道这是否是某种bug。

**Comment by zsh35** [comment]
我这里正常添加，不需要加引号

**Comment by bolieriniefu** [comment]
> 我这里正常添加，不需要加引号

不知道原因捏。
