### ISSUE TITLE
在115下载时clash抢下载带宽

### ISSUE THREAD

**Issue by jiaminxun** [Fndroid/clash_for_windows_pkg#260]
不开clash115下载时，我同时下载三个文件能拉满35M的带宽，一切情况正常。但只要开了clash，打开115下载，35M的带宽还是拉满，但115的三个文件下载速度加起来只有10+M，这时我要是关了115下载，clash还是把带宽拉满，一直不知道下载什么东西，只有重启或关闭clash客户端网络才会停止下载。用的是0.81版，无论是安装版还是便携版，规则无论是机场规则还是神机规则都是这种情况。另外要是在打开115下载前，把system proxy关闭，再开115下载，就不会出现这种情况。

**Comment by sahrechiiz** [comment]
同样的问题，关掉之后不知道在下什么

**Comment by Fndroid** [comment]
下个版本再观察一下，我们这周发现了一个连接问题

**Comment by jiaminxun** [comment]
> 下个版本再观察一下，我们这周发现了一个连接问题

0.85版还是这样，希望修复。

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.8.6

**Comment by jiaminxun** [comment]
> https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.8.6

测试已解决
