### ISSUE TITLE
[Feature Request]: 提供快速更新 rule-priovider 的功能

### ISSUE THREAD

**Issue by Bpazy** [Fndroid/clash_for_windows_pkg#2605]
### 功能描述

当使用 rule-provider 且规则发生变化时，需要打开 GUI 点击按钮才能生效，比较麻烦。我这边期望是可以快速添加规则并生效。
<p align="center"><img src="https://user-images.githubusercontent.com/9838749/149248504-06084fc5-8e7b-4683-8f86-ebf6487e06a8.png" height="400" /></p>

期望的新功能:
1. Clash for Windows 提供 HTTP API，类似于 Clash core 的 API，可以更新某 rule-privider；
2. 或 提供某快捷键，可以更新某 rule-provider；
3. 或 提供某快捷键，可以重启 Clash for Windows; 

### 其他内容

目前我是通过脚本曲线救国的，新增规则到 type=file 的 rule-provider 中，并重启 Clash for Windows。
方式过于粗暴了，[这是脚本](https://github.com/Bpazy/script/blob/bdf233fde373b01dd6ccaffe6115b7a262870b63/windows/addRule.ps1):

```ps1
# 不支持 Service Mode
Stop-Process -Name "Clash for Windows"
Stop-Process -Name "clash-win64"

if ($args.Count -eq 0) {
    return
}

if ($args[0].StartsWith("http://") -or $args[0].StartsWith("https://")) {
    $arr = ([System.Uri]$args[0]).Host -split "\."
    $domain = $arr[-2..-1] -join "."
} else {
    $arr = $args[0] -split "\."
    $domain = $arr[-2..-1] -join "."
}

$newRule = "  - DOMAIN-SUFFIX," + $domain
Write-Output $newRule
Add-Content -Path "C:\Users\hanzi\.config\clash\ruleset\myproxy.yaml" -Value $newRule
Start-Process -RedirectStandardOutput nul "C:\Users\hanzi\AppData\Local\Programs\Clash for Windows\Clash for Windows.exe"
```

**Comment by yi-Xu-0100** [comment]
我记得 rule provider 有配置 interval（自动更新间隔） 的功能

**Comment by Bpazy** [comment]
@yi-Xu-0100 这不够及时，当遇到 example.com 不可访问时，我期望的是添加到 rule 中立刻生效

**Comment by yi-Xu-0100** [comment]
@Bpazy 我看到你提到 core 有 api，CFW 只是个界面，你可以直接调用 core 的 api。

**Comment by Bpazy** [comment]
@yi-Xu-0100 core API 有几个问题：
1. 每次 Clash for Windows 启动时，都指定了不同的 core API port；
2. core API 的文档没看到 reload rule-provider 的功能，所以也想知道 CFW 是如何实现该功能的；

**Comment by yi-Xu-0100** [comment]
@Bpazy 第一个我知道在 CFW 的 setting 中可以关闭 random control port 的设置。第二个我觉得如果没有 api 的话，可能只是解析配置，请求配置中 rule provider 的链接去更新文件的吧 （个人猜测的）

**Comment by zixuan945** [comment]
> @yi-Xu-0100 core API 有几个问题：
> 
> 1. 每次 Clash for Windows 启动时，都指定了不同的 core API port；
> 2. core API 的文档没看到 reload rule-provider 的功能，所以也想知道 CFW 是如何实现该功能的；

直接通过 core api 重载主配置文件可以使 rule provider 生效吧 我猜的

**Comment by Bpazy** [comment]
@zixuan945 谢谢建议，不过调查后发现不可行。根据 CFW 的文档中 [加载过程](https://docs.cfw.lbyczf.com/contents/configfile.html#%E5%8A%A0%E8%BD%BD%E8%BF%87%E7%A8%8B) 中描述的：
```
CFW 启动流程如下：
1. 使用基础配置文件 config.yaml 启动 Clash 核心
2. 根据用户上次使用的配置文件（Profiles/xxxxx.yml）进行恢复
3. 恢复用户上次操作的策略情况

解读：
步骤 1 完成后，Clash 会按照 config.yaml 设置启动
步骤 2 完成后，用户配置文件里的proxies/proxy-providers/proxy-groups/rule-providers/rules/dns这几个字段的内容会被替换到 Clash 里面，除了上面值几个字段，其他的内容均不会替换（这就是 Profiles 里配置文件可以不完整的原因）
```

其中主配置文件内容:
```
mixed-port: 7890
allow-lan: false
external-controller: 127.0.0.1:1976
secret: ''
log-level: info
```

所以如果仅重载主配置文件，相当于启动了一个 **零功能** 的 clash core，除非按照 CFW 文档描述实现一套：`根据用户上次使用的配置文件（Profiles/xxxxx.yml）进行恢复`

**Comment by zixuan945** [comment]
@Bpazy 我打开developer tools 看了一下，点击那个刷新按钮 也是发一个PUT请求到 core API port，直接通过脚本发送这个请求应该可以达到相同的效果吧。
![image](https://user-images.githubusercontent.com/17488847/149447996-2523f428-6e86-467a-a6a9-0b6bedfef74b.png)

**Comment by Bpazy** [comment]
@zixuan945 原来是我看错 core API 的文档了，正确的链接在这里: https://github.com/Dreamacro/clash/wiki/external-controller-API-reference

还有请问 developer tools 是在哪打开的？

**Comment by zixuan945** [comment]
@Bpazy 任务栏图标右键-More-第一个Togger Devtools

**Comment by Bpazy** [comment]
感谢各位的帮助，该 issue 描述的需求 clash core 和 CFW 已具备: 
```sh
curl -X PUT 'http://127.0.0.1:1976/providers/rules/myproxy'
```

**Comment by Bpazy** [comment]
If you also have trouble adding rules quickly, you might as well use the tool I created: [github.com/Bpazy/clash](https://github.com/Bpazy/acr)

**Comment by Yik0o** [comment]
我也是interval无法更新，请问你有遇见这种情况吗？interval 24小时的但是都48h了还是没有更新，只能我手动更新

**Comment by Bpazy** [comment]
@Yik0o 你的问题和我的看起来不一样，建议新开一个 issue 咨询
