### ISSUE TITLE
出现了list.yml更新失败的问题

### ISSUE THREAD

**Issue by Polyploid** [Fndroid/clash_for_windows_pkg#261]
每次开启cfw之后都会回滚到一个远古的profile，手动刷新profile之后能正常使用，重启cfw之后又会回滚到同一个远古版本profile。检查之后发现list.yml不会随着profile的更新而更新。删除所有配置文件后重启cfw即可正常更新list.yml文件。可能是更新list.yml的功能卡住了。系统windows10 1903。

**Comment by Fndroid** [comment]
用的什么版本

**Comment by Polyploid** [comment]
版本0.8.1。

**Comment by Fndroid** [comment]
如果是上周五更新的，那么建议重新下载安装包再覆盖一次

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
