### ISSUE TITLE
[Bug]: TUN模式无法解析访问纯ipv6网站

### ISSUE THREAD

**Issue by Arcohol** [Fndroid/clash_for_windows_pkg#2616]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.5

### 操作系统

Windows x64

### 系统版本

21H2

### 问题描述

TUN模式无法解析访问纯ipv6网站，尝试mixin后则所有网站首次解析十分缓慢，几乎无法工作。
system proxy下工作正常如预期。

### 复现步骤

开启mixin:
```
mixin:
  dns:
    ipv6: true
```
开启默认配置的TUN模式，尝试访问纯ipv6网站如https://byr.pt

### 日志文件

<details><summary>logs</summary><p>

```
[2022-01-17-004727.log](https://github.com/Fndroid/clash_for_windows_pkg/files/7877476/2022-01-17-004727.log)
[2022-01-17-005309.log](https://github.com/Fndroid/clash_for_windows_pkg/files/7877477/2022-01-17-005309.log)
```

</p></details>

**Comment by shikkoku** [comment]
你那个访问不了，但我可以访问https://speed.neu6.edu.cn/

**Comment by Fndroid** [comment]
全部用mixin，不然你mixin这个dns会覆盖tun mode里所有dns的设置包括nameserver和fallback

**Comment by Arcohol** [comment]
> 全部用mixin，不然你mixin这个dns会覆盖tun mode里所有dns的设置包括nameserver和fallback

我将tun mode里的dns设置加上一条`ipv6: true`再全部写进mixin中，可以正常访问网站了。
访问纯ipv6网站时日志显示如下：
```
time="2022-01-17T15:43:51+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2022-01-17T15:43:51+08:00" level=debug msg="[DNS] resolve speed.neu6.edu.cn error: couldn't find ip: speed.neu6.edu.cn"
time="2022-01-17T15:43:51+08:00" level=info msg="[TCP] 198.18.0.1:52455 --> speed.neu6.edu.cn:443 match DomainSuffix(cn) using China-Websites[DIRECT]"
```
此时可以正常打开使用网站。如https://byr.pt 被规则分配到代理组的网站则打不开。
既然能正常打开，为什么是`couldn't find ip`呢

**Comment by Arcohol** [comment]
更新至最新版已解决
