### ISSUE TITLE
[Feature Request]: 支持导入 basic auth encoding URL Profile

### ISSUE THREAD

**Issue by myloft** [Fndroid/clash_for_windows_pkg#2618]
### 功能描述

希望支持导入 basic auth encoding URL Profile，url 形态如下：
```
https://user:pass@www.example.com/clash.yaml
```
尝试通过 github private repo 托管配置文件，测试发现不能通过如下两种类型的链接获取配置，crul 可以正常获取配置文件。
```
https://<access_token>@raw.githubusercontent.com/<user>/<repo>/<branch>/clash.yaml
https://<user>:<access_token>@raw.githubusercontent.com/<user>/<repo>/<branch>/clash.yaml 
```
<img width="437" alt="图片" src="https://user-images.githubusercontent.com/25258169/149730517-ae65409f-f8a1-46b0-bdec-80d87bdf8513.png">

## 参考链接
[Access using credentials in the URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#access_using_credentials_in_the_url)
[Via OAuth and personal access tokens](https://docs.github.com/en/rest/overview/other-authentication-methods#via-oauth-and-personal-access-tokens)

**Comment by Fndroid** [comment]
或者我加一下允许定义更新请求的header，感觉能覆盖更多场景

**Comment by myloft** [comment]
> 或者我加一下允许定义更新请求的header，感觉能覆盖更多场景
Nice！可以避免 Basic Auth 的方式被 github 废弃，通用性也更好。

**Comment by Fndroid** [comment]
下个版本支持
![image](https://user-images.githubusercontent.com/16091562/149897054-2f4b08f6-6628-4c47-ab0c-4aa795c40ad5.png)

**Comment by myloft** [comment]
Thanks！

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases

**Comment by myloft** [comment]
@Fndroid 请求配置文件内包含的配置文件似乎不会携带 header。比如 http://xxx.xx/clash.yml 中包含 proxies url：http://xxx.xx/proxies.yml 。只能拉取 clash.yml，不能将包含的 proxies.yml 拉下来。可以适配一下这种情况嘛～

**Comment by yi-Xu-0100** [comment]
@myloft provider?

**Comment by myloft** [comment]
@yi-Xu-0100 是的
<img width="671" alt="image" src="https://user-images.githubusercontent.com/25258169/163528916-1c7b4d9c-5a6a-4501-bea9-d637e5e274fc.png">

**Comment by yi-Xu-0100** [comment]
@myloft provider 的更新由 core 决定，或者用 parser 处理。

**Comment by myloft** [comment]
@yi-Xu-0100 感谢！仔细看了一下 clash-core 支持 basic auth url 的方式认证，虽然 clash 和 cfw 对认证实现的方法不一样，但是还是可以把配置托管在 github 的～
