### ISSUE TITLE
[Feature Request]: 通过schema导入profile

### ISSUE THREAD

**Issue by hhcol620** [Fndroid/clash_for_windows_pkg#2621]
### 功能描述

![image](https://user-images.githubusercontent.com/56748103/149964085-8006d6fa-a697-455b-9db6-cf324ef0cdd0.png)

我们想通过schema的方式导入更新profile，来实现自动化更新的目的

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/urlscheme.html
