### ISSUE TITLE
mac版的几个问题

### ISSUE THREAD

**Issue by tlerbao** [Fndroid/clash_for_windows_pkg#2622]
### 功能描述

之前用clashx 有个增强模式，可以快速代理iterm2，刚换到CFW，相对应的模式是什么？是TUN模式吗？

![image](https://user-images.githubusercontent.com/20442232/149975499-a00b5282-e525-46c3-8000-4162a29302cf.png)
状态栏怎么才能像设置这里的图示一样显示右边的实时速率的

**Comment by Fndroid** [comment]
1. https://docs.cfw.lbyczf.com/contents/tun.html#macos

2. 把右边的速率拖到左边
