### ISSUE TITLE
[Bug]: UWP loopback软件不支持HIDPI，在高分屏上无法使用

### ISSUE THREAD

**Issue by sceraser** [Fndroid/clash_for_windows_pkg#2624]
### 请认真检查以下清单中的每一项

- [√] 已经搜索过，没有发现类似issue
- [√] 已经搜索过文档，没有发现相关内容
- [√] 已经尝试使用过最新版，问题依旧存在
- [√] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.5

### 操作系统

Windows x64

### 系统版本

Winodws 11

### 问题描述

![image](https://user-images.githubusercontent.com/42718757/150373682-4e34a31b-529a-4377-8a85-5cb49977ab5c.png)
在高分屏上开启高倍（本人是350%）缩放后，UWP loopback软件文字缩成一团，完全没法使用
![image](https://user-images.githubusercontent.com/42718757/150374049-b4893737-4f07-40c3-9ec3-d88380de9897.png)
即使最大化也无法使用

### 复现步骤

将系统缩放开至200%以上即可复现，300%以上问题会非常严重

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by codafi21** [comment]
use tun, who tf use UWP loopback these days

**Comment by sceraser** [comment]
> use tun, who tf use UWP loopback these days

如果开发者认为loopback模式无意义就该去除，既然保留了为什么不能给有需求的人做好一点

**Comment by codafi21** [comment]
CFW is buggy af rn

**Comment by Fndroid** [comment]
这个工具是第三方的工具，不过我试了下最新的版本应该没有这个问题了，下个版本会升级一下

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
