### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Cook21** [Fndroid/clash_for_windows_pkg#263]
希望能在Logs和Connections中增加显示GEOIP判断的IP所在地区, 并能够通过条目的域名/IP/IP所在地区快速添加对应的rule.

**Comment by Fndroid** [comment]
https://www.maxmind.com/en/geoip-demo

Clash并不一定会为每个域名测试GEOIP，所以GUI无法显示出来

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
