### ISSUE TITLE
[Bug]: 窗口不能置顶而是变为置底

### ISSUE THREAD

**Issue by RSSYLY** [Fndroid/clash_for_windows_pkg#2639]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.6

### 操作系统

Windows x64

### 系统版本

10 20H2

### 问题描述

点击窗口置顶按钮，窗口被置于最底层。

### 复现步骤

点击窗口右上角从左往右数第一个按钮。

### 日志文件

<details><summary>logs</summary><p>

```
无
```

</p></details>

**Comment by Fndroid** [comment]
我测试了下没有复现

**Comment by RSSYLY** [comment]
是系统问题，已经重装系统了
