### ISSUE TITLE
反馈：关闭系统代理和切换节点时，没有立即切断连接

### ISSUE THREAD

**Issue by Hugh08** [Fndroid/clash_for_windows_pkg#264]
最近发现一个问题
1、在切换节点时，还是会持续使用上一个节点一会，才切换到新的节点。
2、在关闭system proxy时，系统应用还是会持续使用代理很长一段时间，实际并没有断开代理连接，要把CFW关闭后，才真正断开了代理连接。

如果帅气的作者有空闲的话，建议添加一个类似ssr客户端的功能，在切换服务器（节点）和关闭system proxy时断开所有连接。
在此感谢帅气的作者的无私奉献，给我们带来这么好用的代理工具，谢谢！

**Comment by Fndroid** [comment]
会考虑

**Comment by negnegneg** [comment]
F大辛苦了

**Comment by Fndroid** [comment]
最新版已经支持，参考文档：https://docs.cfw.lbyczf.com/contents/breakconn.html
