### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by billowssun** [Fndroid/clash_for_windows_pkg#2640]
### 功能描述

建议改名，毕竟有MAC版。

**Comment by kingforme** [comment]
重命名桌面快捷方式

**Comment by billowssun** [comment]
任务栏怎么办
________________________________
发件人: King ***@***.***>
发送时间: Wednesday, January 26, 2022 5:16:01 PM
收件人: Fndroid/clash_for_windows_pkg ***@***.***>
抄送: billows ***@***.***>; Author ***@***.***>
主题: Re: [Fndroid/clash_for_windows_pkg] [Feature Request]: (Issue #2640)


重命名桌面快捷方式

―

**Comment by AkariiinMKII** [comment]
~~好的 下次改成clash for windows for macos~~
