### ISSUE TITLE
> > > > > > > 在Parser中填入以下代码: ![where](https://user-images.githubusercontent.com/45936772/148669083-93d9b877-c3e7-4ae5-9153-07d06f47c37d.png)

### ISSUE THREAD

**Issue by shixinwu** [Fndroid/clash_for_windows_pkg#2645]
> > > > > > > 在Parser中填入以下代码: ![where](https://user-images.githubusercontent.com/45936772/148669083-93d9b877-c3e7-4ae5-9153-07d06f47c37d.png)
> > > > > > > ```yaml
> > > > > > > parsers:
> > > > > > >   - url: YOUR_SUBSCRPTION_URL
> > > > > > >     code: |
> > > > > > >       module.exports.parse = async (raw, { axios, yaml, notify, console }, { name, url, interval, selected }) => {
> > > > > > >         const obj = yaml.parse(raw)
> > > > > > >         obj.proxies.forEach( v => {
> > > > > > >             if (v.network === 'ws' && !v['ws-opts']) {
> > > > > > >               const opts = {}
> > > > > > >               opts.path = v['ws-path']
> > > > > > >               opts.headers = v['ws-headers']
> > > > > > >               v['ws-opts'] = opts
> > > > > > >             }
> > > > > > >         })
> > > > > > >         return yaml.stringify(obj)
> > > > > > >       }
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > 即可自动重写旧版配置
> > > > > > 
> > > > > > 
> > > > > > 感谢 大家记得修改 parse 后需要更新配置文件才能生效
> > > > > 
> > > > > 
> > > > > 请问该怎么更新配置文件呢，我的config那里并没有update选项
> > > > > ![Snipaste_2022-01-20_22-27-20](https://user-images.githubusercontent.com/62692476/150357454-e71a558f-d462-4fdf-ba02-e8465fcb7f60.png)
> > > 
> > > 
> > > 就是点你图中这个更新按钮就发了
> > 
> > 
> > parsers中的url: YOUR_SUBSCRPTION_URL有没有改成你这真正订阅的url？
> 
> 感谢兄弟，能正常用了，但是多个订阅url之间在url：中用什么符号分隔开呢

> 可以把  - url: YOUR_SUBSCRPTION_URL  换成   - reg: '^.*$'  就可以对所有的订阅进行替换了

```
parsers:
  - reg: '^.*$'
    code: |
      module.exports.parse = async (raw, { yaml }) => {
        const obj = yaml.parse(raw)
        obj['proxies'].forEach( proxy => {
            if (proxy.network === 'ws' && !proxy['ws-opts']) {
              const opts = {}
              if(proxy['ws-path'] && proxy['ws-headers']) {
                  opts.path = proxy['ws-path']
                  opts.headers = proxy['ws-headers']
                  proxy['ws-opts'] = opts
                  
                  delete proxy['ws-path']
                  delete proxy['ws-headers']
              }
              
            }
        })
        return yaml.stringify(obj)
      }
```

_Originally posted by @ditstyle-yang in https://github.com/Fndroid/clash_for_windows_pkg/issues/2588#issuecomment-1022908980_

**Comment by maxjn8985** [comment]
还是不行，是否因为我的订阅是.php格式而非.yaml格式

**Comment by ditstyle-yang** [comment]
@maxjn8985 对的，这个是针对js格式的（yaml可以认为是js），php格式应该使用其他的方法，我不懂php的。

**Comment by maxjn8985** [comment]
@ditstyle-yang 谢谢，我还是老实在19.4待着吧
