### ISSUE TITLE
[Bug]: 开机自动弹窗

### ISSUE THREAD

**Issue by tianjg** [Fndroid/clash_for_windows_pkg#2647]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.7

### 操作系统

Windows x64

### 系统版本

Windows11

### 问题描述

设置开机自启，每次都会弹出主界面

### 复现步骤

安装最新版即可

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```
[2022-01-28-161610.log](https://github.com/Fndroid/clash_for_windows_pkg/files/7957049/2022-01-28-161610.log)

</p></details>

**Comment by tianjg** [comment]
弹出如下界面：
![image](https://user-images.githubusercontent.com/29768449/151514550-9aac4561-0ace-41af-9a7b-bcde030e2b55.png)

**Comment by tianjg** [comment]
我重置电脑后，再安装之前不弹床，并且其他电脑不弹窗口的0.18.10版本，问题还是依旧

**Comment by yi-Xu-0100** [comment]
setting 设置 silent start
