### ISSUE TITLE
[Bug]: 安装器无法关闭Clash并覆盖

### ISSUE THREAD

**Issue by SpaceTimee** [Fndroid/clash_for_windows_pkg#2657]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.1-0.19.7(仅测试了这些)

### 操作系统

Windows x64

### 系统版本

Win11企业版

### 问题描述

* 注: 本Issue中的Clash指Clash For Windows

在Clash运行的情况下用安装器(Clash For Windows Setup.exe) 安装会提示是否关闭Clash，确定后Clash却不会被关闭 (无警告和报错)。这导致Clash本体无法被覆盖安装 (其他文件应该可以正常被替换)。关闭Clash后再用安装器更新或者让Clash自己静默更新则不会出现这种问题。

### 复现步骤

开着Clash用安装器更新

### 日志文件

无

### 其他补充

如不好调整安装器，建议在更新前提示用户手动关闭Clash

**Comment by yi-Xu-0100** [comment]
安装器？应用内的 update 吗？

**Comment by Fndroid** [comment]
用管理员权限运行的Clash for Windows么

**Comment by SpaceTimee** [comment]
> 

Windows上使用安装器更新(Setup)会出现这个问题，应用内的Update不会有这个问题

**Comment by SpaceTimee** [comment]
> 用管理员权限运行的Clash for Windows么

以管理员权限运行安装器(Clash For Windows Setup.exe)还是会出现这个问题

**Comment by yi-Xu-0100** [comment]
@SpaceTimee 原先运行的 CFW 是否是管理员权限运行的？

**Comment by SpaceTimee** [comment]
> @SpaceTimee 原先运行的 CFW 是否是管理员权限运行的？

不是

**Comment by SpaceTimee** [comment]
不好意思，我想我找到原因了，似乎是安全软件拦截的，将安全软件关闭后CFW就可以被正常关闭了

**Comment by SpaceTimee** [comment]
另外还有另一个问题我没办法解决，[#issuecomment-1030732835](https://github.com/Fndroid/clash_for_windows_pkg/issues/2595#issuecomment-1030732835)，希望作者大大关注一下，谢谢！
