### ISSUE TITLE
远程设备不接受链接的问题

### ISSUE THREAD

**Issue by zxiling03** [Fndroid/clash_for_windows_pkg#267]
我需要每次手动进去网络设置关闭lan自动设置，是什么原因啊555大家是怎么解决的啊
还有最近噶都是官网等不了了吗？001那个

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
