### ISSUE TITLE
release里面的文件下载很慢，怎么可以加速下载？

### ISSUE THREAD

**Issue by zwl1619** [Fndroid/clash_for_windows_pkg#2671]
release里面的文件下载很慢，怎么可以加速下载？

**Comment by yi-Xu-0100** [comment]
配置想要规则，看日志。

**Comment by qihangliu** [comment]
使用镜像加速站可以加速release下载，更方便的使用这个脚本，集合了一些镜像站
> https://greasyfork.org/zh-CN/scripts/412245-github-%E5%A2%9E%E5%BC%BA-%E9%AB%98%E9%80%9F%E4%B8%8B%E8%BD%BD
