### ISSUE TITLE
一个小建议：RULE规则可以单独做配置加载

### ISSUE THREAD

**Issue by z3c3b3** [Fndroid/clash_for_windows_pkg#269]
自建VPS，使用本地配置文件，更新一下规则要手动复制粘贴覆盖，有点不方便，可以将RULE规则单独作为一个配置文件加载更新吗

**Comment by Fndroid** [comment]
目前的解决方案：https://github.com/Fndroid/clash-config-builder

**Comment by z3c3b3** [comment]
> 目前的解决方案：https://github.com/Fndroid/clash-config-builder

感谢，Local模式好用的，请问RULE-SET解析有机会做到客户端里吗，自建的VPS做配置链接有点繁琐，Local模式只能在固定机器更新，便携版有点不方便呢，不管如何解决大部分需求了，继续加油，感谢

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
