### ISSUE TITLE
[Bug]: 频繁连接app.appjson.net、app.gosnakk.com、api.1bhk.cc等网站

### ISSUE THREAD

**Issue by fanvree** [Fndroid/clash_for_windows_pkg#2696]
开机后频繁连接app.appjson.net、app.gosnakk.com、api.1bhk.cc等网站。通过性能查看器看到是clash-win64消耗大量流量。关闭clash后，就没有消耗流量的软件了。clash消耗的流量是100MB级别的。
win10 64位
复现方式：未知

**Comment by Fndroid** [comment]
只要你开了System Proxy，那么遵守的应用所有的请求都算在clash-win64里

**Comment by fanvree** [comment]
在校园网内，并且打开了"允许局域网连接"选项。不知道是哪些热心人士在嗅探接口。
总之，一打开这个选项，就有大量流量。一关闭这个选项，电脑就安静了。
