### ISSUE TITLE
clash客户端启动不了：第一次安装时使用正常，后来再也没打开成功过，log也没生成

### ISSUE THREAD

**Issue by hbjycl** [Fndroid/clash_for_windows_pkg#27]
杀毒软件也关了，重启系统重新安装了n次，也没用

**Comment by hbjycl** [comment]
杀毒软件也关了，重启系统重新安装了n次，也没用

**Comment by Fndroid** [comment]
请提供系统信息

**Comment by wang173999** [comment]
之前装过也正常使用，但是升级之后就无法正常启动了    time="2018-12-03T10:00:11+08:00" level=fatal msg="Parse config error: Rules[0] error: format invalid"

**Comment by Fndroid** [comment]
> 之前装过也正常使用，但是升级之后就无法正常启动了 time="2018-12-03T10:00:11+08:00" level=fatal msg="Parse config error: Rules[0] error: format invalid"

dev版Clash对规则部分做了一些调整，某些情况会导致解析直接失败，例如包含no-resolve，或者带有//的注释

解决办法：如果通过API生成，浏览器下载覆盖即可，其他情况自行解决

**Comment by hbjycl** [comment]
> > 之前装过也正常使用，但是升级之后就无法正常启动了 time="2018-12-03T10:00:11+08:00" level=fatal msg="Parse config error: Rules[0] error: format invalid"
> 
> dev版Clash对规则部分做了一些调整，某些情况会导致解析直接失败，例如包含no-resolve，或者带有//的注释
> 
> 解决办法：如果通过API生成，浏览器下载覆盖即可，其他情况自行解决

win7 64位

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
