### ISSUE TITLE
反馈系统代理出现自动关闭的现象

### ISSUE THREAD

**Issue by CaiJie0611** [Fndroid/clash_for_windows_pkg#270]
之前出现过这样的问题，我没怎么在意，以为是我不小心点到的。
但是真正确定有问题的是，我打开 airexplore（这软件只能走系统代理，不能设置socks5），软件全部googledrive 账号都不能连接，显示无法连接状态，然后我特地盯了下右下角 clash 图标，是橘色的，明显已经打开系统代理的状态了，打开 clash 操作界面，按钮也是打开,但是我再最小化后再打开clash,界面按钮又变成关闭状态。。。

**Comment by szl0834** [comment]
遇到同样的问题

**Comment by bbbi** [comment]
遇到同样的问题

**Comment by Fndroid** [comment]
Refer: https://github.com/Fndroid/clash_for_windows_pkg/issues/312
