### ISSUE TITLE
[Feature Request]: 请问一下windows11系统如何打开clash?

### ISSUE THREAD

**Issue by Taoist-master** [Fndroid/clash_for_windows_pkg#2700]
### 功能描述

解压了Clash.for.Windows-0.19.8-arm64-win,点击后提示我"此应用无法在你的电脑上运行",请问有办法解决吗?

**Comment by kingforme** [comment]
装Clash.for.Windows.Setup.0.19.8.exe。arm64针对的处理器架构为ARM

**Comment by Taoist-master** [comment]
> 装Clash.for.Windows.Setup.0.19.8.exe。arm64对的处理器架构为ARM

好的,谢谢
