### ISSUE TITLE
[Feature Request]: Edit Proxy Group没有tolerance参数

### ISSUE THREAD

**Issue by exlulu** [Fndroid/clash_for_windows_pkg#2706]
### 功能描述

![001](https://user-images.githubusercontent.com/35789196/154913719-b4224309-1dcd-4e6e-ad52-c9e5902bec96.JPG)
是新版clash取消了还是这个参数有问题？

**Comment by Fndroid** [comment]
编辑yaml吧，这个地方已经很久没有更新了

**Comment by exlulu** [comment]
> 编辑yaml吧，这个地方已经很久没有更新了

好的，我主要不知道是没了这个参数还是其他问题，谢谢大佬
