### ISSUE TITLE
[Feature Request]: 希望TUN模式可以在轻量模式下开机自启

### ISSUE THREAD

**Issue by YohoYang** [Fndroid/clash_for_windows_pkg#2709]
### 功能描述

目前的情况是，开启服务模式、TUN模式、以及轻量模式时（未开启Mixin、系统代理、开机软件自启）：
开启软件后将软件关闭，由于开启了轻量模式，CFW主程序进程已经退出了，但TUN相关的进程依然是在运行的，TUN模式可以正常使用。
但当重启电脑后，服务模式并没有自动启动TUN相关进程，导致无法使用TUN模式。需要打开一次CFW再关闭才可正常使用。

希望可以使服务模式在开机时即使不启动CFW主程序也能够将TUN模式的功能生效起来（如果打开了TUN模式）；
或者是可以有在轻量模式下增加子选项：开机隐藏式启动CFW主程序，相关进程就绪后，再自动关闭CFW主程序，使得后台的相关功能能够正常使用。

**Comment by kingforme** [comment]
追求更好体验，不建议使用此功能

**Comment by YohoYang** [comment]
> 追求更好体验，不建议使用此功能 https://docs.cfw.lbyczf.com/contents/lightweight.html#%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E

嗯，关闭轻量模式功能就都正常，可以暂时用着，但也确实会有一些需求，比如小内存用户之类的，毕竟框架本身对内存的占用还是挺高的。可以暂时关闭issue，有机会可以参考优化~

**Comment by kingforme** [comment]
小内存用户可以使用ClashWeb,这玩意仅有Clash内核和Clashweb.exe在后台,大概占用2MB,设置页面调用浏览器
