### ISSUE TITLE
[Bug]: proxy-provider有重名节点时，界面显示问题

### ISSUE THREAD

**Issue by gdyan2001** [Fndroid/clash_for_windows_pkg#2711]
配置文件中使用proxy-provider时，如果有两个provider（例如a和b）都包含相同节点名称的节点的时候，cfw的proxies列表中显示不正常。节点会显示两次，但是节点下方的provider均显示为provider a。 另外，当选择使用该节点的时候，两个节点都会被选上。 

![1645671294(1)](https://user-images.githubusercontent.com/26614893/155448841-a772a643-3778-4703-a142-d5a33e5e2ae6.png)

**Comment by Fndroid** [comment]
这个是已知问题，需要等待clash上游增加字段解决
