### ISSUE TITLE
[Bug]: Wrong window position when switching dual monitors to single monitor

### ISSUE THREAD

**Issue by WellWells** [Fndroid/clash_for_windows_pkg#2713]
Version: 0.19.8
OS: Windows 10 x64

Description: 
--
> When using dual monitors, close window on the second monitor.
> The windows position which store at "C:\Users\_____\AppData\Roaming\clash_win\clash_win-window-bounds.json" will cause the problem that the window cannot be displayed correctly when it becomes a single monitor.
> 
> 雙螢幕下，在第二的螢幕關閉App
> 拔除HDMI線變為單螢幕後，視窗顯示會無法正常顯示

Steps to reproduce:
--

> Copy the following to crash_win-window-bounds.json
> 
> {
>   "1": {
>     "x": 3815,
>     "y": -213,
>     "width": 850,
>     "height": 611
>   }
> }

**Comment by Fndroid** [comment]
<img width="430" alt="image" src="https://user-images.githubusercontent.com/16091562/155646563-91a49219-337e-492a-aced-4b4598fd14c3.png">
