### ISSUE TITLE
求问删除超时节点Parsers 怎么写

### ISSUE THREAD

**Issue by voice1230** [Fndroid/clash_for_windows_pkg#2714]
### 功能描述

或者筛选延迟小于300的节点也可

**Comment by yi-Xu-0100** [comment]
没法在更新订阅的时候去检查订阅的节点可用性。最多加url-test组。

**Comment by voice1230** [comment]
> 没法在更新订阅的时候去检查订阅的节点可用性。最多加url-test组。

好的，感谢
