### ISSUE TITLE
[Feature Request]: clash已经支持多种协议，希望可以增加各协议的手动增加，而不需要在配置文件里面填写

### ISSUE THREAD

**Issue by ZogeMung** [Fndroid/clash_for_windows_pkg#2716]
### 功能描述

目前手动增加proxy只有四种协议：ss, vmess, socks5, http；可否增加例如ssr，trojan等协议的手动添加
![image](https://user-images.githubusercontent.com/21040938/155695237-c47d06ee-d188-4191-a9e7-15aefc26c57d.png)

**Comment by yi-Xu-0100** [comment]
这个界面设置的会被更新的订阅覆盖点，建议还是使用 diff 或者 parser。
