### ISSUE TITLE
无法正常启动cfw

### ISSUE THREAD

**Issue by LxnChan** [Fndroid/clash_for_windows_pkg#2721]
0.19.8及以上版本无法正常启动cfw，无论双击快捷方式还是双击主程序文件均无法启动，任务管理器未见Clash相关进程，未找到对应的log日志文件或文件夹。降级安装0.19.7（覆盖安装）及以下版本可恢复正常使用。重启后问题没有解决，重装（同版本覆盖安装）后没有解决，完整卸载后再重装没有解决。

系统版本：Windows 10 Pro 21H2（19044.1415）

**Comment by LxnChan** [comment]
我无法使用该仓库issue提供的模板提交（Github报告HTTP 400），因此我将其他信息补充如下：

故障版本：0.19.8及以上版本
系统版本：Windows 10 Pro 21H2（19044.1415）x64

**Comment by myfingerhurt** [comment]
你试试用7z的解压版本，而不是安装版。

**Comment by Fndroid** [comment]
有可能是electron升级导致的，下个版本试试

**Comment by RayvChan** [comment]
同样，无法正常显示dashboard

**Comment by TheTychoStar** [comment]
我的问题更诡异，自从之前某个版本出现启动闪退的问题之后，我再用新版本时只要安装到旧版同样的路径就无法启动，但只要更换任意的其他路径安装，就能正常启动，无法理解。感觉是有问题的旧版残留了某些信息导致只要clash在原来的安装目录就会出错？

**Comment by LxnChan** [comment]
问题解决了，完整卸载之后选择安装在用户目录（仅当前用户）就可以正常启动了，目前最新版本（0.19.11）覆盖安装也没有问题，我觉得像是权限的问题。
