### ISSUE TITLE
[Bug]: Profiles > Proxies 编辑节点信息会生成老版本的websocks配置代码

### ISSUE THREAD

**Issue by ColanCN** [Fndroid/clash_for_windows_pkg#2722]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.10

### 操作系统

Windows x64

### 系统版本

Windows11（22000.527）

### 问题描述

使用 Profiles > Proxies 编辑节点信息会生成老版本的WebSocks配置代码

### 复现步骤

【原始配置文件代码】
proxies:
  - name: test
    type: vmess
    server: www.qq.com
    port: "443"
    uuid: 1-1-1-1-1
    alterId: "0"
    cipher: auto
    tls: true
    network: ws
    ws-path: /10086
    ws-opts:
      path: /10086
      headers: { Host: www.qq.com }

使用 Profiles > Proxies 编辑节点信息后

【编辑后配置文件代码】
proxies:
  - name: test
    type: vmess
    server: www.qq.com
    port: "443"
    uuid: 1-1-1-1-1
    alterId: "0"
    cipher: auto
    tls: true
    network: ws
    ws-path: /10086

### 其他补充

这个问题貌似从0.19.5之后就存在了，发言结束。

mua~

**Comment by yi-Xu-0100** [comment]
这个页面好像很久没更新了，建议走 parser ，这个界面编辑的更新后不会被保存。

**Comment by Fndroid** [comment]
下个版本将会去掉这个编辑器😂
