### ISSUE TITLE
想问下这些服务商文件放在哪的

### ISSUE THREAD

**Issue by voice1230** [Fndroid/clash_for_windows_pkg#2730]
### 功能描述

经常更新不了，打算手动替换里面内容
![image](https://user-images.githubusercontent.com/29227184/155865999-4fddc497-5cbc-47ac-a198-44f146f8a54c.png)

**Comment by yi-Xu-0100** [comment]
Home directory 下

**Comment by voice1230** [comment]
> 

![image](https://user-images.githubusercontent.com/29227184/155866110-2c981549-f4a1-480d-ab78-2a23cfe6ac8e.png)
![image](https://user-images.githubusercontent.com/29227184/155866114-6fc9d0ed-d65c-4847-a4ff-62dcd5b4a53b.png)


没有哦

**Comment by voice1230** [comment]
> Home directory 下

已找到，感谢！
