### ISSUE TITLE
[Feature Request]: 希望可以通过代理更新订阅

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [Fndroid/clash_for_windows_pkg#2731]
### 功能描述

希望可以通过代理更新订阅，有些订阅是在外网的，难以更新，希望增加设置，选择clash本身经不经过代理。

**Comment by BeUnhappy** [comment]
那么问题来了，通过clash来获取外网订阅信息的中转流量从哪里来呢，难道让开发者来用爱发电？clash只是一个工具

**Comment by SBBTD** [comment]
> 那么问题来了，通过clash来获取外网订阅信息的中转流量从哪里来呢，难道让开发者来用爱发电？clash只是一个工具

他的意思是走当前配置的节点来更新，有些一开始能更新后续给杀了的这样就更方便，之前ss的客户端是有这个功能的。

**Comment by Fndroid** [comment]
system proxy开启的情况下，就会用系统代理更新
