### ISSUE TITLE
[Bug]:CFW允许局域网连接，iOS设备部分软件出现问题

### ISSUE THREAD

**Issue by SamTripleOne** [Fndroid/clash_for_windows_pkg#2736]
CFW允许局域网连接，iOS设备做相应设置后，大多数软件可以正常上网（测试了Twitter、Youtube、微博、微信），但部分软件出现问题
Bilibili：图片、动态、评论均可正常加载，甚至直播也可正常观看，但无法播放视频
![微信图片_20220301170904](https://user-images.githubusercontent.com/62505930/156140611-63bfdaf6-3cef-4e6e-97d5-f15f47a9e804.jpg)
Connections显示：
![微信图片_20220301170920](https://user-images.githubusercontent.com/62505930/156140661-23433d0a-769b-4de0-83cc-a43ff1f1f3a7.png)
Logs显示：
![微信图片_20220301172718](https://user-images.githubusercontent.com/62505930/156142244-41d0d9c2-1878-432a-847f-02cdd200e7e6.png)

但如果将视频分享到微信，从小程序打开，即可观看
![微信图片_20220301171220](https://user-images.githubusercontent.com/62505930/156140790-15810037-4c52-4010-bfff-4259cc450658.jpg)

王者荣耀：无法加载游戏
![微信图片_20220301170911](https://user-images.githubusercontent.com/62505930/156140826-d0992b3e-d800-457f-afb1-78a04b2adacb.jpg)
Connections显示：
![微信图片_20220301170923](https://user-images.githubusercontent.com/62505930/156140873-4f65b719-432b-4187-95ab-a88e20ca8177.png)

**Comment by Fndroid** [comment]
试了下没有复现

**Comment by SamTripleOne** [comment]
iPhone的上网工具是Quanx，家里的电脑安装CFW，目前的设置是连上家里的WIFI时，Quanx转换模式，手机走电脑的代理。采用三种方案，各有不同的问题

1. 连接到家中WIFI时，Quanx通过配置自动关闭
quanx的配置：`ssid_suspended_list=Asus`
问题：如上所述，大多数软件可以正常上网（测试了Twitter、Youtube、微博、微信），但B站视频播放、王者荣耀等出现问题


2. 连接到家中WIFI时，Quanx转换代理模式为直连
quanx的配置：`running_mode_trigger=filter, filter, Asus:all_direct`
问题：国内网站均正常，但无法访问外网

3. 连接到家中WIFI时，手动关闭Quanx
问题：除Telegram外，软件上网均正常，[查到了一个解释](https://hellodk.cn/post/703#:~:text=%E8%BF%99%E6%A0%B7%E5%8F%AA%E8%83%BD%E8%8E%B7%E5%8F%96%20http%20%E4%BB%A3%E7%90%86%EF%BC%8C%E4%B8%8D%E8%83%BD%E9%80%9A%E8%BF%87%20socks5%20%E4%BB%A3%E7%90%86%E8%BF%9E%E6%8E%A5%E5%88%B0%E5%B1%80%E5%9F%9F%E7%BD%91%E7%9A%84%20clash%EF%BC%8C%E6%89%80%E4%BB%A5%E5%8F%AA%E8%83%BD%E5%9C%A8%E6%B5%8F%E8%A7%88%E5%99%A8%E4%B8%8A%E4%BD%BF%E7%94%A8%E4%BB%A3%E7%90%86%EF%BC%8C%E4%B8%80%E4%BA%9B%E5%9F%BA%E4%BA%8E%20socks5%20%E7%9A%84%E5%BA%94%E7%94%A8%EF%BC%8C%E6%AF%94%E5%A6%82%20im%20%E5%BA%94%E7%94%A8%20%60telegram%60%20%E5%B0%B1%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8%E8%BF%99%E4%B8%AA%E4%BB%A3%E7%90%86%E4%BB%8E%E8%80%8C%E6%97%A0%E6%B3%95%E8%BF%9E%E6%8E%A5%E5%88%B0%E7%BD%91%E7%BB%9C%E3%80%82%E5%BD%93%E7%84%B6%E4%BD%A0%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8%E5%9F%BA%E4%BA%8E%20web%20%E7%9A%84%20telegram%20%E7%A8%8B%E5%BA%8F%E3%80%82)，似乎是代理协议的锅，不太好解决。上网正常了，但是比较麻烦。。。

**Comment by SamTripleOne** [comment]
> 试了下没有复现

所以现在是Quanx和CFW配合使用出现了问题

**Comment by SamTripleOne** [comment]
查看了大量issues，发现我的需求其实是，要在win上实现网关模式，接管局域网内其它设备的所有流量，但F大在其它issue里解释过，由于系统的原因，只能在mac上实现

至于[开启quanx，CFW不接管流量](https://github.com/Fndroid/clash_for_windows_pkg/issues/2736#:~:text=connection%E4%B8%AD%E6%B2%A1%E6%9C%89%E7%9B%B8%E5%85%B3%E7%9A%84%E8%BF%9E%E6%8E%A5%E8%AE%B0%E5%BD%95%EF%BC%8Cquanx%E7%9B%B4%E8%BF%9E%E6%A8%A1%E5%BC%8F%E4%B8%8B%EF%BC%8C%E6%89%8B%E6%9C%BA%E6%B5%81%E9%87%8F%E5%AE%8C%E5%85%A8%E6%B2%A1%E6%9C%89%E9%80%9A%E8%BF%87CFW%E4%BB%A3%E7%90%86%EF%BC%8C%E4%BA%8B%E5%AE%9E%E4%B8%8A%EF%BC%8C%E5%8F%AA%E8%A6%81%E6%89%8B%E6%9C%BA%E4%B8%8A%E7%9A%84quanx%E8%BF%98%E5%9C%A8%E5%B7%A5%E4%BD%9C%EF%BC%8C%E6%97%A0%E8%AE%BA%E6%98%AF%E5%A4%84%E4%BA%8E%E8%A7%84%E5%88%99/%E7%9B%B4%E8%BF%9E/%E5%85%A8%E5%B1%80%E6%A8%A1%E5%BC%8F%EF%BC%8CCFW%E5%9D%87%E4%B8%8D%E6%8E%A5%E7%AE%A1%E4%BB%BB%E4%BD%95%E6%B5%81%E9%87%8F)的问题，我猜测是这样：
win中的CFW允许局域网连接后，只是让手机流量转发到一个HTTP代理服务器，如果同时开启quanx，quanx也会对手机流量进行代理，除非可以实现win系统的网关模式，否则quanx处理后的流量不会再转发到PC上

等等看大佬有无回复😂之后我关掉这个issue

**Comment by Fndroid** [comment]
我说一个思路你可以试试

1. 在quanx里建一个http代理，ip是cfw电脑局域网ip，端口是mixed port
2. 在Proxy策略里选中这个节点
3. `running_mode_trigger = filter, filter, Asus:all_proxy`
