### ISSUE TITLE
[Bug] Proxies 布局问题

### ISSUE THREAD

**Issue by wenfangdu** [Fndroid/clash_for_windows_pkg#2747]
Proxy 名字较长，将 CFW 宽度设成最小后会变成这样（方格无法对齐）：

![image](https://user-images.githubusercontent.com/28700378/156678738-b118df94-feec-4946-ba6e-7c991b60265b.png)

**Comment by yi-Xu-0100** [comment]
不建议测试这种 feature

**Comment by wenfangdu** [comment]
@yi-Xu-0100 几个版本之前是正常的，节点的名字就是那么长呀😅，感觉是网格布局做了改动后变成这样的。

**Comment by yi-Xu-0100** [comment]
哦，没看出来，以为是嫌节点变宽了😂

**Comment by codafi21** [comment]
![image](https://user-images.githubusercontent.com/93474348/156714869-0060dbab-45d9-4ba1-996e-b32773b1c19e.png)
从0.19.10开始就是这样了。

**Comment by codafi21** [comment]
![image](https://user-images.githubusercontent.com/93474348/156715284-03d00049-e507-46bb-90f8-dc3b6ab2364c.png)
electron还是不行

**Comment by Fndroid** [comment]
下个版本修复，谢谢大佬

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
