### ISSUE TITLE
[Bug]: proxies里的策略图标只有黑白色和节点前面的国旗图标不显示.

### ISSUE THREAD

**Issue by jiaminxun** [Fndroid/clash_for_windows_pkg#2749]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.11

### 操作系统

Windows x64

### 系统版本

win10 21H1

### 问题描述

proxies里的策略图标只有黑白色和节点前面的国旗图标不显示.
![QQ截图20220304090929](https://user-images.githubusercontent.com/57553009/156680989-f6ad1011-f4df-40ab-a587-a25dd04c6cef.jpg)
![QQ截图20220304090809](https://user-images.githubusercontent.com/57553009/156681025-9f071f89-776e-4d28-b93f-204572cca4e1.jpg)

### 复现步骤

参考问题描述

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
和字体有关

**Comment by jiaminxun** [comment]
> 和字体有关

解决了，感谢
