### ISSUE TITLE
关于开启系统代理后使用youtube-dl等命令行工具时的问题

### ISSUE THREAD

**Issue by lidoworld** [Fndroid/clash_for_windows_pkg#275]
我个人发现使用上的情况：
我在之前使用youtube-dl(python)的时候 一直都用proxifier，接管python.exe通过Socks Port 7891喂给cfw的。
不过最近开始我使用System Proxy接管Windows的代理，配合UWP Loopback让NETFLIX等App走代理，但发现了副作用，使用youtube-dl获取链接非常非常慢，下载速度也很慢，会下个一点点比如几M卡住。
我查看Proxifier的时候发现，卡的时候一直没有截获记录，下那几M的时候会有一下记录然后继续卡，以此循环。几百MB的视频可能需要几分钟才能下完。
当我关掉System Proxy后，一切正常，Proxifier让y-dl走代理可以占满带宽下视频。

另外当我使用awscli拖aws s3的时候，开系统代理会卡非常长一段时间才开始传输，而关掉后Proxifier正常工作，速度很快。

**Comment by Fndroid** [comment]
CMD默认不会走系统代理，PowerShell可以

**Comment by lidoworld** [comment]
py程序执行的时候是python.exe在联网 proxifier里也是设置拦截py

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/tap.html
