### ISSUE TITLE
希望恢复旧版节点策略编辑界面！！

### ISSUE THREAD

**Issue by Soizzer** [Fndroid/clash_for_windows_pkg#2750]
### 功能描述

旧版的节点策略编辑界面很好用啊！很适合快速修改节点和策略，为什么要去除？
现在搞了两个文本编辑方式，一个内部一个外部，那不是功能重复了吗？？？

**Comment by zsh35** [comment]
我也感觉图形编辑器比较实用，这是CFW的一个特色，不知道为什么要取消。

**Comment by wyyzcjw** [comment]
同求恢复节点编辑功能~~

**Comment by naskater** [comment]
属实是在开倒车，真不知道怎么想的，好用的功能出掉，不停的添加一些无用的功能

**Comment by Fndroid** [comment]
会考虑加回来

**Comment by fanmli** [comment]
> 会考虑加回来，如果需要的人多的话，并且简单更新一下

谢谢作者把这个功能加回来吧，这个功能非常不错的。

**Comment by Wilson2003** [comment]
+1

**Comment by fireflycao** [comment]
谢谢作者把这个功能加回来吧

**Comment by srrshweee** [comment]
> 会考虑加回来，如果需要的人多的话，并且简单更新一下

加回来吧，至少增减节点到对应的组会快好多，现在还要去配置文件里面去改，以前只要鼠标拖拽就好了。

**Comment by mrlbing** [comment]
强烈希望此功能回归。

**Comment by xxiaohaoh** [comment]
很需要这个功能啊，希望下个版本加回来。

**Comment by Liameternal** [comment]
联名➕1

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
