### ISSUE TITLE
显示此应用无法在你的电脑上运行

### ISSUE THREAD

**Issue by sdhiaoshdkljasndjklsah** [Fndroid/clash_for_windows_pkg#2752]
显示此应用无法在你的电脑上运行

**Comment by Fndroid** [comment]
说明下错安装包

**Comment by sdhiaoshdkljasndjklsah** [comment]
下载的64第一个第二个都不行

**Comment by sdhiaoshdkljasndjklsah** [comment]
有没有其他的联系方式？帮忙远程看看   非常感谢

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.19.11/Clash.for.Windows.Setup.0.19.11.exe
