### ISSUE TITLE
[Bug]: 关于win11使用最新版的Clash for Windows界面数字无法显示

### ISSUE THREAD

**Issue by shibendan** [Fndroid/clash_for_windows_pkg#2753]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.11

### 操作系统

Windows x64

### 系统版本

Windows 11 专业版22567.1

### 问题描述

当时打开Clash for Windows的时候发现UI界面上所有的数字都无法显示，以下是截图
![image](https://user-images.githubusercontent.com/43409708/156725744-73a7dd67-174a-43b5-9805-a318f2db4d75.png)
![image](https://user-images.githubusercontent.com/43409708/156725800-fc263ec2-1a96-498c-a777-40979f294ac8.png)
![image](https://user-images.githubusercontent.com/43409708/156725854-aae87f40-cfb6-422d-9b8c-2131b35a98e4.png)

### 复现步骤

我两台电脑，同样的Windows 11 专业版22567.1，以及0.19.11都有这个问题。

### 日志文件

<details><summary>logs</summary><p>

```
[2022-03-04-161354.log](https://github.com/Fndroid/clash_for_windows_pkg/files/8184190/2022-03-04-161354.log)
```

</p></details>

**Comment by Fndroid** [comment]
settings - font family 设置了一个不存在的字体

**Comment by shibendan** [comment]
> settings - font family 设置了一个不存在的字体

谢谢大佬
