### ISSUE TITLE
开机启动,start with windows,开机启动后,能够自动最小化,不要占据桌面

### ISSUE THREAD

**Issue by caogee** [Fndroid/clash_for_windows_pkg#2758]
### 功能描述

建议配置'开机启动,start with windows,'选项后,
开机启动后,能够自动最小化,不要占据桌面位置,
不要打开显示在屏幕中,
最好自动最小化到小任务栏中.

**Comment by Kam323** [comment]
有静默启动模式的，setting项里面general里面

**Comment by caogee** [comment]
thank you!

> 有静默启动模式的，setting项里面general里面

thank you!

**Comment by aichixiaojuzi** [comment]
![屏幕截图 2023-03-17 111503](https://user-images.githubusercontent.com/43509012/225803717-4b03e358-3597-4eb8-94e9-d200f2b807db.png)

**Comment by zhouyang3456** [comment]
> you are my hero

**Comment by zhouyang3456** [comment]
> 有静默启动模式的，setting项里面general里面

you are my hero
