### ISSUE TITLE
[Feature Request]: dark模式下部分文字阅读困难，希望更改显示效果

### ISSUE THREAD

**Issue by SamTripleOne** [Fndroid/clash_for_windows_pkg#2767]
### 功能描述

dark模式下部分文字与背景颜色一致，阅读困难，例如Profiles中Rules编辑模式，当输入文字进行Rules筛选时
![595c4d3dcb373820b0395d3793822bd](https://user-images.githubusercontent.com/62505930/156993557-07c6f44f-b9ab-491d-b70b-7a97c245a8de.png)
文字几乎不可见，希望可以更改颜色

**Comment by Fndroid** [comment]
感谢反馈，下个版本修复

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
