### ISSUE TITLE
日志中的错误含义

### ISSUE THREAD

**Issue by negnegneg** [Fndroid/clash_for_windows_pkg#277]
由于本人没有学习过深度的IT知识，所以只能理解一些简单的代码含义，但是CFW中有些错误代码不是很理解，请求作者可以帮忙分析一下。
1、
dial 🎯 通往电信 error: 
dial tcp4 13.88.218.172:443: i/o timeout
2、
dial 📲 电报信息 error: 
服务器节点域名:15495 connect error: lookup 服务器节点域名: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server 
3、
dial 🎯 通往电信 error: 
lookup pingfore.wegame.com.cn: no such host

目前只遇到这三类错误日志，我用谷歌翻译出来的意思有点答非所问，所以还是厚着脸皮来请大佬解答一下，非常感谢大佬百忙之中愿意花时间回答小白的问题，谢谢。

**Comment by Fndroid** [comment]
1. 本地网络无法连接该地址
2. DNS请求节点域名解析，但是没有收到响应
3. DNS请求解析该域名，响应表示该DNS服务器中不存在该域名的解析记录

**Comment by negnegneg** [comment]
> 1. 本地网络无法连接该地址
> 2. DNS请求域名域名解析，但是没有收到响应
> 3. DNS请求解析该域名，响应表示该DNS服务器中不存在该域名的解析记录

1、这是一条直连国内的策略，请问为什么还会连接代理服务器的地址，是配置文件哪个部分需要修改吗？

**Comment by negnegneg** [comment]
> 1. 本地网络无法连接该地址
> 2. DNS请求域名域名解析，但是没有收到响应
> 3. DNS请求解析该域名，响应表示该DNS服务器中不存在该域名的解析记录


感谢F大的回复，请问造成这些错误的原因，如下解释正确吗？
1，这是一条直连国内的策略，请问为什么继续连接代理服务器的地址，是配置文件其中部分需要修改吗？
2，造成这个问题是不是因为dns设置的问题，导致没办法解析服务器节点域名？
3，这个没问题，可以理解了。

**Comment by Fndroid** [comment]
1. 连接的是网站的地址，不是代理服务器的
2. 短暂不能解析的原因很多，运营商限制，网络波动都有可能

**Comment by negnegneg** [comment]
> 1. 连接的是网站的地址，不是代理服务器的
> 2. 短暂不能解析的原因很多，运营商限制，网络波动都有可能

谢谢回复

**Comment by negnegneg** [comment]
> > 1. 连接的是网站的地址，不是代理服务器的
> > 2. 短暂不能解析的原因很多，运营商限制，网络波动都有可能
> 
> 谢谢回复

不好意思，我又厚着脸皮来打扰F大了，关于第二条错误日志，我延伸出了第二个问题。首先说明一下这个错误是在使用过程中遇到的，不是刚刚开启代理。问题如下：
CFW从启动时，首次成功解析了节点域名后正常使用一段时间，为什么后续使用中，还会出现无法解析节点域名的错误日志，是每次需要使用节点代理时CFW都要再重新解析一次节点域名吗？

**Comment by Fndroid** [comment]
DNS不是一直有效的，建议Google: DNS TTL

**Comment by Fndroid** [comment]
如果没其他问题就关闭了哦

**Comment by negnegneg** [comment]
> 如果没其他问题就关闭了哦

好的，谢谢F大
