### ISSUE TITLE
[Bug]: 日志疯狂刷新match GeoIP(CN) using Domestic[DIRECT] 且无法上网

### ISSUE THREAD

**Issue by lijiachang** [Fndroid/clash_for_windows_pkg#2776]
**clash软件版本：0.19.11
电脑系统：macOS  12.2.1**

开启规则代理后，日志中疯狂刷新TCP GeoIP(CN) using Domestic[DIRECT] 且无法打开国内网站，google等国外网站可以正常打开

我尝试过更新Geoip数据库，更新后问题依旧。
![Snipaste_2022-03-10_10-07-51](https://user-images.githubusercontent.com/28041718/157575694-9b4f9138-e50d-4dc7-ade3-967d3e13d64a.png)

PS： 我使用过汉化补丁，但是汉化之前就存在这个问题了，汉化是为了尝试找个解决这个问题的设置选项
![Snipaste_2022-03-10_10-08-43](https://user-images.githubusercontent.com/28041718/157575832-bb221ab1-451f-4d03-bd95-15ecce295a7c.png)

下面是日志的截取部分
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55577 --> 139.224.214.226:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55576 --> 139.224.214.226:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55583 --> 139.224.214.226:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55582 --> 110.76.30.13:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55581 --> 140.205.31.68:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55589 --> 139.224.214.226:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55586 --> 110.76.30.13:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55587 --> 139.224.214.226:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55585 --> 110.76.30.13:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55590 --> 139.224.214.226:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55588 --> 139.224.214.226:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55593 --> 110.76.30.13:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55591 --> 139.224.214.226:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55592 --> 140.205.31.68:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55599 --> 139.224.214.226:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55594 --> 139.224.214.226:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55597 --> 110.76.30.13:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55596 --> 110.76.30.13:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55595 --> 139.224.214.226:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55598 --> 139.224.214.226:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55600 --> 110.76.30.13:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55602 --> 139.224.214.226:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55601 --> 140.205.31.68:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55607 --> 139.224.214.226:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55608 --> 110.76.30.13:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55603 --> 139.224.214.226:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55606 --> 139.224.214.226:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55605 --> 110.76.30.13:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55604 --> 139.224.214.226:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55609 --> 110.76.30.13:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55610 --> 139.224.214.226:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55611 --> 140.205.31.68:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55613 --> 139.224.214.226:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55615 --> 110.76.30.13:443 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-03-10T10:17:08+08:00" level=info msg="[TCP] 127.0.0.1:55616 --> 110.76.30.13:443 match GeoIP(CN) using Domestic[DIRECT]"

**Comment by Fndroid** [comment]
说明有其他应用在用http代理请求
