### ISSUE TITLE
[Feature Request]: 请问为何要移出"内部代理"这个功能？

### ISSUE THREAD

**Issue by xxiaohaoh** [Fndroid/clash_for_windows_pkg#2777]
### 功能描述

内部代理编辑器真的很好，不用打开配置文件进行添加，请问是出于什么原因考虑而要移出内部代理编辑器呢？

希望能加回来此功能，感谢！

**Comment by yi-Xu-0100** [comment]
Duplicate of #2750

**Comment by xxiaohaoh** [comment]
> #2750的副本[](https://github.com/Fndroid/clash_for_windows_pkg/issues/2750)

谢谢！
