### ISSUE TITLE
error: unsupported rule type DomainSuffix

### ISSUE THREAD

**Issue by Iant20** [Fndroid/clash_for_windows_pkg#278]
Version: 0.8.2

更新配置不会出错，可是在添加rule保存的时候会出现此错误。

![image](https://user-images.githubusercontent.com/18302931/69483052-a28b3180-0e5d-11ea-924a-7d03b2f97c97.png)

**Comment by Fndroid** [comment]
已知，下版本修复

**Comment by Fndroid** [comment]
fixed: https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.8.3
