### ISSUE TITLE
日志与连接全为空，测试节点有速度，但无法走代理

### ISSUE THREAD

**Issue by bolieriniefu** [Fndroid/clash_for_windows_pkg#2783]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19

### 操作系统

Windows x64

### 系统版本

win7专业版

### 问题描述

系统代理已开，节点测试时有速度，但不论是全局还是规则模式，日志和连接全为空白，没有走任何流量，windows时间已同步。

请问为什么？没有任何一点流量，代理或直连都空白

### 复现步骤

![QQ截图20220311171758](https://user-images.githubusercontent.com/44076296/157838797-ab1cedc4-e0c5-4a7a-8046-0f4cafcba1df.png)
![QQ截图20220311171804](https://user-images.githubusercontent.com/44076296/157838806-d5b9a929-0761-4c84-bc2c-fea791c3df40.png)
![QQ截图20220311171807](https://user-images.githubusercontent.com/44076296/157838808-b87bfea4-7de8-46a7-b5ae-582ff6b151e7.png)
![QQ截图20220311171833](https://user-images.githubusercontent.com/44076296/157838809-471d57c5-493e-41f2-ba2f-80857531a0b6.png)
![QQ截图20220311171903](https://user-images.githubusercontent.com/44076296/157838811-4dd87f50-e62e-4e78-b2cd-6d455cd2cc7e.png)

**Comment by Wrandz** [comment]
虽然我不清楚为什么这个会被直接关闭了，但是确实我mac上也出现过这个问题
