### ISSUE TITLE
频繁掉线

### ISSUE THREAD

**Issue by nervicia** [Fndroid/clash_for_windows_pkg#279]
尽管任务栏是浅色，翻不出去，关闭代理再打开就好了（节点不变），但过一会又掉线……

望修复，谢谢

**Comment by narakuzi** [comment]
节点问题自行处理

**Comment by nervicia** [comment]
> 节点问题自行处理

不是节点问题，关闭**系统代理**再打开就好了

**Comment by Fndroid** [comment]
refer: https://github.com/Fndroid/clash_for_windows_pkg/issues/312
