### ISSUE TITLE
[Feature Request]: 请求加入 VLESS 协议的支持

### ISSUE THREAD

**Issue by erbanku** [Fndroid/clash_for_windows_pkg#2790]
### 今天想导入一个 VLESS 协议的节点，CFW 提示不支持此协议（如下图）。VLESS 比其他协议相对更加安全，希望 CFW 加入 VLESS 协议的支持，谢谢。
![ShareX_2022-03-13_10-55-57_Sunday_Window](https://user-images.githubusercontent.com/79493862/158043069-4ecf978c-1b05-41c0-a2b2-b945dd0d2d87.png)

**Comment by yi-Xu-0100** [comment]
core issue: <https://github.com/Dreamacro/clash/issues>
