### ISSUE TITLE
请问最多支持导入多少个节点？，怎么玩不支持vless节点导入，还有不支持vless grpc, trojna grpc 协议[Bug]: 

### ISSUE THREAD

**Issue by JACKUSR2089** [Fndroid/clash_for_windows_pkg#2794]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

v 0.19.12

### 操作系统

Windows x64

### 系统版本

v 0.19.12

### 问题描述

请问最多支持导入多少个节点？，怎么玩不支持vless节点导入，还有不支持vless grpc, trojna grpc 协议[Bug]: 

### 复现步骤

在使用中转换出来的节点老是报错

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
core issue: <https://github.com/Dreamacro/clash/issues>
