### ISSUE TITLE
v0.4.3启动后无论选择什么模式都不能连接Microsoft Store

### ISSUE THREAD

**Issue by kennysoul** [Fndroid/clash_for_windows_pkg#28]

**Comment by kennysoul** [comment]
windows 10 1809版，去Google等网站均没有问题，就是无法连接Microsoft Store，两台电脑都是同样问题，不知道是什么原因

**Comment by Fndroid** [comment]
看起来是loopback的问题，[参考这个](https://github.com/Fndroid/clash_for_windows_pkg/issues/13#issuecomment-438170552)

**Comment by kennysoul** [comment]
也许你是正确的，谢谢
