### ISSUE TITLE
请求新增任务栏右键菜单项“快速开关http代理”选项

### ISSUE THREAD

**Issue by leiersai** [Fndroid/clash_for_windows_pkg#280]

**Comment by leiersai** [comment]
即“system proxy”快捷开关，标题才发现写错了

**Comment by GrayXu** [comment]
@Fndroid this issue can be closed by [v0.9.5 release](https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.5) with tray menu?

**Comment by Fndroid** [comment]
@GrayXu thank you
