### ISSUE TITLE
GitHub SSH在TUN模式下无法工作

### ISSUE THREAD

**Issue by xzhang8102** [Fndroid/clash_for_windows_pkg#2805]
GitHub SSH在TUN模式下无法工作，关闭TUN或者关闭cfw都可以正常工作。
TUN模式下，DNS设置为`redir-host`或`fake-ip`均会报错

redir-host:
```
kex_exchange_identification: Connection closed by remote host
Connection closed by 20.205.243.166 port 22
```

fake-ip:
```
kex_exchange_identification: Connection closed by remote host
Connection closed by 198.18.0.3 port 22
```

TUN模式配置
<img width="624" alt="image" src="https://user-images.githubusercontent.com/43830077/159113046-12d55e96-1c5b-44d7-9be4-bce002055d5e.png">

Log
```
time="2022-03-19T15:10:24+08:00" level=info msg="[TCP] 198.18.0.1:53878 --> github.com:22 match RuleSet(Global) using <节点名>
```

**Comment by xzhang8102** [comment]
类似issue： #2139 
切换成了`fake-ip`并没有解决我的问题

**Comment by AdoShan** [comment]
大佬开代理使用pip install 命令会遇到这种错误不。我都不知道咋解决了。
`WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory'))': /simple/ffmpeg/`

**Comment by Fndroid** [comment]
改成Direct估计就能连上了，和TUN没什么关系，倒是可能节点连不上GitHub

**Comment by AdoShan** [comment]
> 改成Direct估计就能连上了，和TUN没什么关系，倒是可能节点连不上GitHub

大佬，只要是开了代理，哪怕是全局直连pip都会报错。
如国内豆瓣源，提示无法连接代理
![image](https://user-images.githubusercontent.com/44154107/159828681-3a69150f-c1e1-4b8e-9769-299e746e1042.png)

默认源的话报错就变成了不安全的ssl证书
![image](https://user-images.githubusercontent.com/44154107/159828823-cd5f936d-5f2d-4a66-97f4-95c9a75f73df.png)

**Comment by Fndroid** [comment]
@AdoShan 我回的是这个issue的，你的问题和这个issue都不一样。python的奇怪问题搜一下issue就有了，#1787

**Comment by xzhang8102** [comment]
> 改成Direct估计就能连上了，和TUN没什么关系，倒是可能节点连不上GitHub

刚刚咨询了一下，确实是节点的问题，感谢回复！
