### ISSUE TITLE
GUI添加SS配置有BUG

### ISSUE THREAD

**Issue by Iongtimenosee** [Fndroid/clash_for_windows_pkg#281]
我今天添加SS服务器，确定后提示配置端口号错误，打开配置文件看，GUI给端口号加了空格，然后用双引号引住了端口号和空格，导致程序无法识别。

写端口配置建议不用引号了，因为加不加结果都一样。不加反而方便带语法加亮的编辑器观看。

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
