### ISSUE TITLE
proxies页面节点前国家emoji不显示

### ISSUE THREAD

**Issue by Jessire** [Fndroid/clash_for_windows_pkg#2811]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.12

### 操作系统

Windows x64

### 系统版本

win11 dev 22579

### 问题描述

未修改字体，proxies页面节点前国家emoji不显示
<img width="675" alt="屏幕截图 2022-03-21 214440" src="https://user-images.githubusercontent.com/61305123/159275667-7e936983-c7d7-4793-b1f8-57f16004c626.png">

### 复现步骤

参考问题描述

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
settings里font family为空？

**Comment by Jessire** [comment]
> 

setting里font family显示正常
<img width="676" alt="image" src="https://user-images.githubusercontent.com/61305123/159643013-19dc7140-6117-4c79-bb7b-e5765d418fad.png">

**Comment by vj23456** [comment]
关了   Use System Emoji

**Comment by Jessire** [comment]
> 关了 Use System Emoji

试了，没用

**Comment by lucacham** [comment]
我的和你一样的问题，结果是因为更换了系统字体导致不支持。我现在换回了字体又可以显示了。
