### ISSUE TITLE
Clash 的 tun Mode无法与共享热点共存

### ISSUE THREAD

**Issue by Tao888888** [Fndroid/clash_for_windows_pkg#2812]
当开启tun Mode及System Proxy是再打开热点，当有设备连接时，电脑直接处于断网状态，显示WiFi无网络连接
运行系统 win11

**Comment by yi-Xu-0100** [comment]
https://docs.cfw.lbyczf.com/contents/questions.html#在-windows-系统中-tun-模式下无法使用热点分享功能
