### ISSUE TITLE
[Feature Request]: silent start无效，开机重启还是会弹出来

### ISSUE THREAD

**Issue by yangjindou** [Fndroid/clash_for_windows_pkg#2814]
### 功能描述
0.19.12版本 没有开启lightweight mode

**Comment by yi-Xu-0100** [comment]
Setting 里打开 silent start

**Comment by yangjindou** [comment]
> 设置里打开静音启动
设置过了，还是不可以，重启，关机开机都不行
![image](https://user-images.githubusercontent.com/35205030/159688244-612a4917-6de3-403b-9179-986a81d4869f.png)

**Comment by yi-Xu-0100** [comment]
@yangjindou 检查一下是否是多个安装位置了

**Comment by yangjindou** [comment]
@yi-Xu-0100 我尝试把老版本删了，并且把配置文件也一并删了，还是无效，开机会打开窗口

**Comment by yangjindou** [comment]
哭了

**Comment by yi-Xu-0100** [comment]
@yangjindou 配置文件是 profile 吗？把 home directory 备份一下，然后删除，重启一下软件，重新设置一下试试。其他得到我也不知道。

**Comment by yangjindou** [comment]
@yi-Xu-0100 C:\Users\XXX\.config文件夹，放着clash配置文件。home directory是什么

**Comment by yangjindou** [comment]
@yi-Xu-0100 找到原因了，老版本的开机启动项卸载的时候没有删除，安装目录又与新版一样，相当于打开两次，禁用了老版本的开机启动项就正常了

**Comment by nxy1999** [comment]
> @yi-Xu-0100 找到原因了，老版本的开机启动项卸载的时候没有删除，安装目录又与新版一样，相当于打开两次，禁用了老版本的开机启动项就正常了

能详细说说吗，我也有这个问题
