### ISSUE TITLE
[Bug] 光标放到右上角图标上 `cursor: pointer` 失效

### ISSUE THREAD

**Issue by wenfangdu** [Fndroid/clash_for_windows_pkg#2816]
光标放在图标上，`cursor: pointer` 会失效变成 `cursor: auto`：

![image](https://user-images.githubusercontent.com/28700378/159830318-eac06cc2-5f3d-4acd-b9c9-4af972afc077.png)

CFW 版本：v0.19.12

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
