### ISSUE TITLE
[Feature Request]: 设置系统代理时支持`https`

### ISSUE THREAD

**Issue by sirliu** [Fndroid/clash_for_windows_pkg#2817]
### 功能描述

CFW在设置windows系统代理时，仅设置了http代理，导致很多https请求代理不能正常访问。比如pip install 时会报错。
![目前的代理设置](https://pic2.zhimg.com/v2-c0e4fb382c662f93a08c6f74233a78b1_b.jpg)

正确的应该是
`http=http://127.0.0.1:7890;https=http://127.0.0.1:7890`
类似如下:
![正确设置](https://pic1.zhimg.com/v2-5d87ba3083a85dce5e39329d17dc9988_b.jpg)

解决方案来源，https://zhuanlan.zhihu.com/p/350015032

**Comment by Fndroid** [comment]
Duplicate of #1787
