### ISSUE TITLE
[Bug]: 您好，请问为什么我使用v19.5功能正常，但是换到19.12或者19.13之后不能正常使用呢？节点和设置是相同的。

### ISSUE THREAD

**Issue by Ethanisthebestman** [Fndroid/clash_for_windows_pkg#2822]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

19.13

### 操作系统

Windows x64

### 系统版本

Win10

### 问题描述

我使用v19.5功能正常，但是换到19.12或者19.13之后不能正常使用呢？节点和设置是相同的，在v19.5版本中打开4k视频很顺畅，但是换成v19.12和v19.13后，连网页也无法打开。

### 复现步骤

用两个版本的软件同时测速同一个节点试试。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by LemonTreee** [comment]
同问

**Comment by Soizzer** [comment]
19.5版本的内核使用的是不兼容旧版的配置文件格式，当时这个版本被很多机场建议不要使用。后来19.6升级时重新更换了旧版的内核。重新下载机场订阅导入吧。

**Comment by mj5219054** [comment]
![W( C8XP$4XC(5KJZ 5R@2)Y](https://user-images.githubusercontent.com/79394963/160152243-159e7433-70b5-432b-846a-b2cf935d93f5.png)

**Comment by Fndroid** [comment]
duplicate #2588
