### ISSUE TITLE
[Bug]: failed to clash core

### ISSUE THREAD

**Issue by DaBiaoDi** [Fndroid/clash_for_windows_pkg#2825]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.13

### 操作系统

Windows x64

### 系统版本

WIN11最新版

### 问题描述

failed to clash core

### 复现步骤

打开就这样

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

![5599cd589832f5e9](https://user-images.githubusercontent.com/102382364/160176869-52412f11-4306-4208-8777-8eee4e8d798d.png)

**Comment by DaBiaoDi** [comment]
failed to clash core

**Comment by DaBiaoDi** [comment]
failed to clash core

**Comment by yi-Xu-0100** [comment]
日志。
