### ISSUE TITLE
[Feature Request]: 建议启用clash最新的amd64-v3内核

### ISSUE THREAD

**Issue by Marukon** [Fndroid/clash_for_windows_pkg#2826]
### 功能描述

rt，对AMD64版本使用amd64-v3内核，或者单独编译发布一个amd64-v3的版本
望作者考虑

**Comment by shikkoku** [comment]
目前我自行替换了内核，不过就算v3支持AVX2了，性能有提升吗？

**Comment by Marukon** [comment]
> 目前我自行替换了内核，不过就算v3支持AVX2了，性能有提升吗？

没测试过，不过感觉应该有（心理作用

**Comment by Fndroid** [comment]
缺失指令的虚拟机和旧CPU都用不了的，性能提升普通使用也不明显，所以不会默认改成其他
