### ISSUE TITLE
手机局域网连接后，浏览器正常翻墙，其他国外app无法使用

### ISSUE THREAD

**Issue by z277608** [Fndroid/clash_for_windows_pkg#2828]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.13

### 操作系统

Windows x64

### 系统版本

win11

### 问题描述

打开允许局域网连接，手机连上后浏览器可以正常科学上网，其他软件比如tiktok,facebook,tg等都不能科学上网，CFW显示有手机访问浏览器或者app的日志，tg通过代理可以正常使用

### 复现步骤

如题

### 日志文件

![1](https://user-images.githubusercontent.com/95560013/160232901-cf850432-1bc8-42a2-a2f3-0185ca01fd62.png)

### 其他补充

打开关闭tun模式都一
![1](https://user-images.githubusercontent.com/95560013/160232914-8b0d31f1-2c4f-4c20-8132-def86a324ef0.png)
样

**Comment by ffplayer** [comment]
手机具体是怎么连接的？是从wlan设置里面添加代理么？

**Comment by z277608** [comment]
> 
是从wlan里设置手动代理，只是想着直接代理了不用手机平板每次科学上网都再打开clash，不过这样既然不太稳定那就直接用clash算了，省的折腾了

**Comment by FuHengYa** [comment]
YouTube Vanced 这个软件可以用 但是 Telegram却不能用。
