### ISSUE TITLE
[Bug]: "CMD with proxy"中的"run as admin"的颜色不随主题改变。

### ISSUE THREAD

**Issue by ruiy326** [Fndroid/clash_for_windows_pkg#2829]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.13

### 操作系统

Windows x64

### 系统版本

19044.1586

### 问题描述

"CMD with proxy"中的"run as admin"的颜色不随主题改变。
![图片](https://user-images.githubusercontent.com/102410131/160233427-a9d8368f-2b78-4ff3-8129-75a17f8d5eeb.png)
![图片](https://user-images.githubusercontent.com/102410131/160233482-4b45cb36-0bcb-4700-8ffb-c2bbedb5c3ba.png)

### 复现步骤

点击主界面Port项中的 "CMD with proxy" 可见

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
thanks for the report, this issue has been fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
