### ISSUE TITLE
clash无法成功安装

### ISSUE THREAD

**Issue by UFO404** [Fndroid/clash_for_windows_pkg#283]
升级clash0.8.2新版本后发现旧版本的和新版本的clash都在，然后卸载了刚装的新版本，旧版本的在卸载新版本后就卸载不掉了，就删除了旧版本的clash文件，随后再重新安装clash的时候安装器提示“安装已终止 安装程序并未成功的运行”
![tu](https://user-images.githubusercontent.com/11772053/69566620-75bc5300-0ff2-11ea-851f-9a364b837a1b.png)

**Comment by UFO404** [comment]
补充系统版本是windows10专业版 1809

**Comment by Fndroid** [comment]
> 删除了旧版本的clash文件

删除了哪些文件

**Comment by UFO404** [comment]
今天解决了，就是更新的时候不是覆盖安装导致在一个文件夹里装了两个版本的clash，通过文件里面的卸载程序卸载后实际只卸载了一个，还有一个版本的用那个卸载程序卸载不掉了我把安装文件夹下的clash文件手动删了，然后在windows10程序里的clash还保持已安装，然后再安装就安装不进去了，我进程序与功能里手动吧残留的clash删了就好了。

**Comment by LINLIN12345** [comment]
> 今天解决了，就是更新的时候不是覆盖安装导致在一个文件夹里装了两个版本的clash，通过文件里面的卸载程序卸载后实际只卸载了一个，还有一个版本的用那个卸载程序卸载不掉了我把安装文件夹下的clash文件手动删了，然后在windows10程序里的clash还保持已安装，然后再安装就安装不进去了，我进程序与功能里手动吧残留的clash删了就好了。

谢谢，跟你一样的状况出现同样的问题，找了好久原因。

**Comment by Bakanbu** [comment]
谢谢，我也是同样问题，要把旧版本删干净

**Comment by yzhang-max** [comment]
我也出现这样的问题，但是我是直接把文件夹删除，重新下载的时候什么也没有，就是下载不出来怎么办

**Comment by Kevin6Liu** [comment]
太感谢了，一模一样的问题，已经解决了
