### ISSUE TITLE
[Bug]: 在windows虚拟机中无法连接

### ISSUE THREAD

**Issue by popococo-hanks-bocan** [Fndroid/clash_for_windows_pkg#2832]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.13

### 操作系统

Windows x64

### 系统版本

win7

### 问题描述

虚拟机安装win7 64位。网络试过了nat，桥接网卡。虚拟机内关闭防火墙。
clash软件能正常开启，连不上服务器。 
一样的程序和配置，在主机里能正常开启。
有人遇到同样的问题吗？还请指导一下。

### 复现步骤

虚拟机安装win7 64位。网络试过了nat，桥接网卡。虚拟机内关闭防火墙。
clash软件能正常开启，连不上服务器。 
一样的程序和配置，在主机里能正常开启。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by aecra** [comment]
相同的问题, 回退到上一个版本

**Comment by Wrandz** [comment]
连不上服务器，指的是连不上什么服务器？

**Comment by aecra** [comment]
开启局域网代理之后, 无法通过 clash 暴露在局域网的 ip 和端口代理上网
