### ISSUE TITLE
[Bug]: 游玩过可以修改系统分辨率的游戏后, 下次开机后 cfw 的主窗口会不断的变大

### ISSUE THREAD

**Issue by kayanouriko** [Fndroid/clash_for_windows_pkg#2835]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.13

### 操作系统

Windows x64

### 系统版本

Windows 11 专业版 22000.556

### 问题描述

cfw 设置里面是开启 Silent Start 选项, 在游玩过一些修改系统分辨率的游戏后, 下次开机启动 cfw 后, 点击状态栏 cfw 图标显示主界面, 窗口会扩大超越屏幕.  
如果这次开机后从不显示 cfw 主界面或者不手动调整 cfw 的窗口大小, 重复多次上述游玩游戏, 关机开机的操作后, cfw 窗口会越来越大且无法手动调整大小, 需要使用 windows 的分屏功能才能调整窗口大小.  
我搜索发现之前有过相关的 issue: #2547 , 但是我使用一直保持最新版本, 最近的几个版本均有此问题.  

### 复现步骤

游玩可以修改系统分辨率的游戏, 例如: 艾尔登法环, 4k 显示屏下以 2k 分辨率运行.
下次开机后 cfw 的主窗口则会变大, 反复几次后会变大至无法调整的状态.

**Comment by yi-Xu-0100** [comment]
我既没有4K屏，又没有艾尔登法环。 (*꒦ິ⌓꒦ີ)

**Comment by Fndroid** [comment]
上游问题

**Comment by Fndroid** [comment]
最新版上游有类似的fix，可以试试，但不保证能正常

**Comment by kayanouriko** [comment]
> 最新版上游有类似的fix，可以试试，但不保证能正常

刚升级v0.19.14测试了一下, 问题依旧存在sad

**Comment by kayanouriko** [comment]
v0.19.15 测试了半田, 貌似已经修复了.
