### ISSUE TITLE
[Feature Request]: 添加多语言功能

### ISSUE THREAD

**Issue by zhongweisheng1** [Fndroid/clash_for_windows_pkg#2838]
### 功能描述

Clash for windows 默认语言是英语，对于不懂英语的来说必须要在网上找**对应版本**的汉化文件，特别麻烦，所以我建议添加多语言功能。

### 其他内容

在 `General` 页或在 `Settings` 页添加语言选项。

**Comment by yi-Xu-0100** [comment]
Duplicate of #999
