### ISSUE TITLE
Service Mode 作用是啥？为什么要开启这个模式

### ISSUE THREAD

**Issue by tomven1990** [Fndroid/clash_for_windows_pkg#2839]
### 功能描述

clash项目里并没有clash-core-service这个服务。它的作用是啥？我开启tun的时候没开启service mode照样能代理流量。
我理解只要开启了tun，配置了默认路由规则到tun网卡，就可以实现所有ip包代理，clash-core-service是一个守护?
是否有该服务的相关说明？

**Comment by tomven1990** [comment]
我看 #1838  提到是为了通过高级权限提权启动tun，是在一些无高级权限的场景下才有用？相当于启动了一个service，接收command启动高级命令？

**Comment by yi-Xu-0100** [comment]
开 tun 好像需要创建网卡，然后会跳 UAC，开机自动启动 tun，如果没有管理员权限，应该会失败。当然如果你禁用 uac 提示应该也行。

~~大致应该是这样，我记不太清楚了 （x~~

**Comment by ffplayer** [comment]
![clash](https://user-images.githubusercontent.com/4073704/160584367-0468caa8-4cae-435a-951d-8a074d6e0fd4.png)

我理解是把自身进程安装为一个服务的形式工作，以实现更稳定的服务？ 
我现在遇到了时不时崩溃的问题。先用服务模式试试。

安装之后系统内服务项会多一个 clash core service。 我观察还会不会有崩溃问题。

**Comment by tomven1990** [comment]
测试了一下，clash core service的确是一个执行命令的服务。
包含了ping/start/stop 还有一个command。我测试了一下ping就是探活，start/stop启动关闭clash。command用途是啥？我测试了一下command允许执行任何命令。
是否方便解释一下core-service的具体用途或者开放service的源码？理论上service就是一个运行程序的容器，但是看二进制包大小，应该还包含有其它功能 @Fndroid

**Comment by Fndroid** [comment]
command是用来给mac版设置系统dns的。

启动服务这个行为就需要权限了，那注册成服务其实没有意义了。service mode其实只是在dashboard低权限运行的情况下保证tun模式可以正常运行，如果你直接用管理员运行cfw那用不用service mode都一样效果。

**Comment by wsepr** [comment]
TUN 模式和 Lightweight 模式都依赖service mode
