### ISSUE TITLE
开机自启后没有载入或没有正确载入配置文件, 需要手动点一下配置文件

### ISSUE THREAD

**Issue by flyingfeather99** [Fndroid/clash_for_windows_pkg#284]
如题, 开机自启后节点列表是空的(只有默认的 shadowsock ), 手动点一下配置文件节点列表才加载出来

**Comment by flyingfeather99** [comment]
win10 1909 x64

**Comment by Fndroid** [comment]
CFW什么版本，不是最新的话升级到最新先试试

**Comment by dragon-tang** [comment]
最新版本，出现同样问题，软件是绿色版那个

**Comment by dragon-tang** [comment]
再试了一下，可能是因为新版本覆盖旧版本的原因，我删除clash文件夹的所有文件，再解压新版本的进去就没事了

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
