### ISSUE TITLE
[Bug]: Time out

### ISSUE THREAD

**Issue by kolomee** [Fndroid/clash_for_windows_pkg#2841]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.13

### 操作系统

Windows x64

### 系统版本

Windows 11 专业版 21H2 22000.556

### 问题描述

部分外网（tradingview，jable等）Global 下能正常访问，Rule 下无法访问，显示time out。

### 复现步骤

版本升级到 0.19.10 后就出现

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

<
[2022-03-29-191355.log](https://github.com/Fndroid/clash_for_windows_pkg/files/8371124/2022-03-29-191355.log)
/p></details>
[](url)

**Comment by yi-Xu-0100** [comment]
看了下日志，走的【其他流量】策略组 ，不知道那个选的什么节点。

**Comment by kolomee** [comment]
> 看了下日志，走的【其他流量】策略组 ，不知道那个选的什么节点。

感谢指点！
