### ISSUE TITLE
[Bug]: tun模式下office联网异常

### ISSUE THREAD

**Issue by Wind-Tracker** [Fndroid/clash_for_windows_pkg#2846]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.13

### 操作系统

Windows x64

### 系统版本

19044.1586

### 问题描述

开启系统代理，会造成部分网站（如知乎）的图片加载异常，表现为部分图片能加载出来，而部分图片无法加载并显示，刷新页面无改善；使用tun mode能够解决这个问题，但是有新问题，会造成office、微软商店等软件联网异常，表现为office显示无网络连接，微软商店能访问但频繁弹窗。
![image](https://user-images.githubusercontent.com/64177772/160559977-685deccf-036a-49e8-b40c-91f82c9788c7.png)
![image](https://user-images.githubusercontent.com/64177772/160559949-549fdff7-4089-4320-b4ad-e73f360ead0d.png)
![image](https://user-images.githubusercontent.com/64177772/160560500-c2497a5c-08ab-47c5-9fa5-538a776469f9.png)

想问一下有没有能同时解决的方法

### 复现步骤

开启系统代理和tun mode，tun mode为默认设置

### 日志文件

<details><summary>logs</summary><p>

```
time="2022-03-29T15:48:03+08:00" level=warning msg="[TCP] dial Domestic (match DomainSuffix/windows.net) to onedriveclucprodbn20050.blob.core.windows.net:443 error: all DNS requests failed, first error: read udp4 192.168.1.158:51549->8.8.4.4:53: i/o timeout"
time="2022-03-29T15:48:08+08:00" level=warning msg="[TCP] dial Domestic (match DomainSuffix/microsoft.com) to self.events.data.microsoft.com:443 error: all DNS requests failed, first error: read udp4 192.168.1.158:51550->1.1.1.1:53: i/o timeout"
time="2022-03-29T15:48:08+08:00" level=warning msg="[TCP] dial Domestic (match DomainSuffix/windows.net) to onedriveclucprodbn20050.blob.core.windows.net:443 error: all DNS requests failed, first error: context deadline exceeded"
time="2022-03-29T15:48:13+08:00" level=warning msg="[TCP] dial Domestic (match DomainSuffix/microsoft.com) to self.events.data.microsoft.com:443 error: all DNS requests failed, first error: context deadline exceeded"
time="2022-03-29T15:48:13+08:00" level=warning msg="[TCP] dial Domestic (match DomainSuffix/windows.net) to onedriveclucprodbn20050.blob.core.windows.net:443 error: all DNS requests failed, first error: read udp4 192.168.1.158:51565->8.8.4.4:53: i/o timeout"
time="2022-03-29T15:48:18+08:00" level=warning msg="[TCP] dial Domestic (match DomainSuffix/microsoft.com) to self.events.data.microsoft.com:443 error: all DNS requests failed, first error: read udp4 192.168.1.158:51584->8.8.4.4:53: i/o timeout"
```

</p></details>

**Comment by yi-Xu-0100** [comment]
看看 tun 配置的 dns，设置一些国内公共 dns 。

**Comment by Wind-Tracker** [comment]
> 看看 tun 配置的 dns，设置一些国内公共 dns 。

DNS Servers默认就有114和阿里，还需要再加吗？还是说应该在fallback里添加？

**Comment by yi-Xu-0100** [comment]
![图片](https://user-images.githubusercontent.com/25523606/160755405-626a50d4-1f7d-46b9-b5b1-c3cb571c8029.png)

**Comment by Wind-Tracker** [comment]
> ![图片](https://user-images.githubusercontent.com/25523606/160755405-626a50d4-1f7d-46b9-b5b1-c3cb571c8029.png)

默认的设置就带有这三个，不知道还应该添加别的吗？
![image](https://user-images.githubusercontent.com/64177772/160757873-9932747c-c366-4ff8-a5be-53ab73a0d6d1.png)

**Comment by yi-Xu-0100** [comment]
看看日志有啥情况吧

**Comment by PRCABK** [comment]
在fake-ip-filter里面添加个  +.microsoft.com
