### ISSUE TITLE
[Bug]: Clash for Windows cannot be closed.

### ISSUE THREAD

**Issue by NatsuGaOwatta** [Fndroid/clash_for_windows_pkg#2849]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.12

### 操作系统

Windows x64

### 系统版本

Windows 11 Version 22H2 (OS Build 22581.200)

### 问题描述

1. 从 0.19.12 版本正常 Update 过程中出现如下错误，检测过没有端口占用：
<img width="798" alt="image1" src="https://user-images.githubusercontent.com/68507149/160884268-5c9db488-7b25-4405-856e-f4e1a641bbab.png">

2. 从 Releases 页面下载 Clash.for.Windows.Setup.0.19.13.exe 直接安装提示 Clash for Windows cannot be closed. 重启电脑后也是一样：
<img width="962" alt="image2" src="https://user-images.githubusercontent.com/68507149/160884842-85c4e8a5-0d2f-4634-99f0-e31eca248c82.png">

3. 卸载 0.19.12 同样提示 cannot be closed (重启一样)，系统是 Win 11 Beta 通道

### 复现步骤

nope

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

请问有大佬知道解决办法吗，目前 0.19.12 可以正常使用，就是更新不了卸载不了😥

**Comment by dhdgves** [comment]
我有同样的问题，我是这样解决的：
1. 首先，找到你clash for windows的安装位置，然后把安装文件夹（一般在C:\Program Files\Clash for Windows）里面。
2. 然后，移动这个文件夹，删除这个文件夹，或者单纯的改个名字
3. 重新运行0.19.13安装程序

如此，我就用上了0.1913
