### ISSUE TITLE
发现三个显示BUG

### ISSUE THREAD

**Issue by negnegneg** [Fndroid/clash_for_windows_pkg#285]
版本：0.8.2
系统环境：windows10-1803-64位

1、在进行托管订阅时，实际已经成功下载订阅，却显示Error（已试验多次，几乎每次都是）
2、配置文件更改名称，点击OK后，名称不会马上变更，需要切换窗口（点击Prixies后再点击Profiles）后配置文件框才显示新名称。
3、切换配置文件时，配置文件框不会马上变色，也是需要切换窗口（点击Prixies后再点击Profiles）后才显示生效（但实际配置文件已经生效，只是显示BUG）
![微信截图_20191126191806](https://user-images.githubusercontent.com/56794580/69625416-7cde7200-1081-11ea-8269-e61432ba2f1d.png)

**Comment by Fndroid** [comment]
fixed: https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.8.3
