### ISSUE TITLE
[Bug]: Specify Protocol 的处理有误使得 cfw 在 windows 平台上使用系统代理时仍与 pip 和 requests 存在问题

### ISSUE THREAD

**Issue by fakeboboliu** [Fndroid/clash_for_windows_pkg#2855]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.14

### 操作系统

Windows x64

### 系统版本

Windows 10++

### 问题描述

https://note.bobo.moe/2021/02/clash-for-windows-pip-proxyerror.html

> cfw 中启用 Specify Protocol 对访问 https 网站依旧无效

分析见文，此处略了。

修复方案：注册表项内容改为 `http=http://127.0.0.1:7890;https=http://127.0.0.1:7891`

### 复现步骤

 1. 不使用 TUN
 1. 不使用 Proxifier
 1. 打开系统代理
 1. 打开 Specify Protocol 
 1. 使用 requests 尝试 get 只有使用代理可以访问的 https 资源

**Comment by xinleg339** [comment]
win11无法运行

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
