### ISSUE TITLE
[Bug]: 更新到0.19.14后只要打开GUI就会CFW连带核心一起崩溃

### ISSUE THREAD

**Issue by bym018** [Fndroid/clash_for_windows_pkg#2859]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.14

### 操作系统

Windows x64

### 系统版本

Windows 11 x64

### 问题描述

从0.19.13通过软件内更新至0.19.14后只要打开界面就会cfw和核心一起崩溃掉
目前回滚至0.19.13没有发现任何问题

### 复现步骤

从0.19.13通过软件内更新至0.19.14，只需从任务栏点开GUI就会出现问题

### 日志文件

<details><summary>logs</summary><p>

```
[renderer.log](https://github.com/Fndroid/clash_for_windows_pkg/files/8401906/renderer.log)
```

</p></details>

### 其他补充

有问其他人，别人说没有发现类似问题，可能是个体案例

**Comment by xy1999729** [comment]
出现了同样能的问题

**Comment by schalldemz** [comment]
我的也出现了，系统是windows 11 build 22581.100, 通过winget更新， 回滚后由软件内更新也出现了

**Comment by NestRoomPast** [comment]
同样的问题，不过GUI崩溃之后核心还在运行，可正常上网，任务管理器中多出了一个"clash-core.exe"。

**Comment by spinningwatt** [comment]
同样的问题，打开GUI后只要不操作就不会退掉（能够一直正常运行），一旦切换tab就会连核心一起退掉

**Comment by spinningwatt** [comment]
同样的问题，打开GUI后只要不操作就不会退掉（能够一直正常运行），一旦切换tab就会连核心一起退掉

系统：
Windows10 x64 刚打上KB5011543补丁

**Comment by Microbubu** [comment]
一样的问题，托盘右键也会崩溃，系统Windows Server 2022

**Comment by jokervTv** [comment]
windows 11 21H2 同

**Comment by Fndroid** [comment]
如果0.19.13是正常的话应该是electron更新导致的，下个版本会再更新一下，可以留意下

**Comment by Wrandz** [comment]
@Fndroid 0.19.13版本是好的，但是0.19.14版本打开运行也是可以的，很诡异的是只要点击那个General，cfw就整个的自动崩溃关闭了，重装还是一样，而且日志里面没有任何报错，我现在回到0.19.13版本了。我的电脑版本Windows11 21H2。

**Comment by Em0zz1e** [comment]
同LZ，无奈先用clashy了

**Comment by jokervTv** [comment]
问题已解决，更新到19.15即可

**Comment by bym018** [comment]
0.19.15版本已解决

**Comment by Fndroid** [comment]
同步VSCode更新了Electron到v18.3.2，之前闪退的可以试试这个还会不会闪退：https://cowtransfer.com/s/c772960ab25640，下个版本可能也会更新到这个
