### ISSUE TITLE
系统代理总是被篡改，导致浏览器无法访问网页

### ISSUE THREAD

**Issue by lingfeng0303** [Fndroid/clash_for_windows_pkg#286]
自从装了clash之后，发现软件容易crash，不稳定，再之后就出现系统代理被篡改的情况，出现被篡改不能上网的情况后，通过系统将代理开关重置之后，浏览器便可以上网，可几分钟之后，代理又被篡改，怀疑是clash的问题，所以做了卸载，可卸载之后，这个代理被篡改的问题，依然如此反复的出现，不知道什么原因。

原先是没有问题的，从装了clash之后开始出现这个问题

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/312
