### ISSUE TITLE
[Bug]: 最新版(v0.19.13)开启TAP模式无法正常开启

### ISSUE THREAD

**Issue by tomven1990** [Fndroid/clash_for_windows_pkg#2865]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.13

### 操作系统

Windows x64

### 系统版本

win10 家庭版

### 问题描述

安装了TAP网卡，如何启动TAP模式？我按文档中配置，并启动cfw，安装了TAP Device。TAP没任何反应？还需要哪里启动？
另外，TUN模式无论开关，都会自动启动TUN网卡，是不是哪里有BUG造成的？
尝试了两台电脑，都是同样的情况？ 是TAP功能已经废弃？
<img width="876" alt="image" src="https://user-images.githubusercontent.com/2385355/161414978-a261b175-b8d8-4a50-9fd5-340e3d9e50e8.png">

### 复现步骤

配置
mixed-port: 7890

ipv6: true

external-controller: 127.0.0.1:9090

external-ui: dashboard

interface-name: '以太网'

dns:
  enable: true
  enhanced-mode: redir-host # 或 fake-ip
  listen: 0.0.0.0:53
  nameserver:
    - 223.5.5.5

启动cfw，安装TAP device .  tap正常安装。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by tomven1990** [comment]
我看网卡有TAP版本是单独启动一个tun2socks.不过是一两年前的方案

**Comment by tomven1990** [comment]
TUN 模式无法使用Connectify热点软件。TAP模式可以，不过TAP模式好像文档不全，点击无反应

**Comment by tomven1990** [comment]
建议更新一下文档，TAP开启时的配置和操作流程https://uzbox.com/tech/clash-atp.html

**Comment by nameless3721** [comment]
可能是core问题吧 
![image](https://user-images.githubusercontent.com/50364156/162380917-e48fcec0-76fd-4602-9da4-431bd486de6e.png) 其他不变就替换成2021 11 08内核(0.19.0)就不会回环 12月开始的内核开tap模式都会回环  dns流量都在logs里面
