### ISSUE TITLE
windows7 service mode management [Bug]: 

### ISSUE THREAD

**Issue by thissuper** [Fndroid/clash_for_windows_pkg#2869]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.14

### 操作系统

Windows x64

### 系统版本

windows 7 pro sp1

### 问题描述

安装和卸载都没反应，什么原因？

https://user-images.githubusercontent.com/57950591/161721739-49a0a45b-6da2-4bf4-b5e3-317a5bd735ff.mp4

### 复现步骤

本想安装的，安装后，tun mode 打开未成功，想着就卸载了重新安装下，但点卸载无响应。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
也许得手动安装看看情况

**Comment by thissuper** [comment]
@yi-Xu-0100 感谢！
