### ISSUE TITLE
[Bug]: 开启clash后无法登录 onedrive

### ISSUE THREAD

**Issue by wpzzz** [Fndroid/clash_for_windows_pkg#2876]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.11

### 操作系统

Windows x64

### 系统版本

10

### 问题描述

 

今天登录win10自带的onedrive 提示“我们无法连接你。我们似乎无法立即连接到其中一项服务。请稍后再试，如果问题仍然存在，请联系支持人员。 HTTP 404 login.microsoftonline.com” 。如果退出cfa就正常，然后我切换到cfa默认配置文件config.yaml  proxies选择全局DIRECT ， 相同的错误， 如果用浏览器直接打开login.microsoftonline.com 也能打开， 如果在代理设置的例外里添加login.microsoftonline.com ，onedrive也能正常登录

### 复现步骤

初始化CFA ，然后登录onedrive

### 日志文件

<details><summary>logs</summary><p>

```
time="2022-04-07T16:37:25+08:00" level=info msg="RESTful API listening at: 127.0.0.1:10692"
time="2022-04-07T16:37:25+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
time="2022-04-07T16:37:34+08:00" level=info msg="[TCP] 127.0.0.1:10737 --> odc.officeapps.live.com:443 using GLOBAL"
```

</p></details>

**Comment by Wrandz** [comment]
应该是你的规则有问题，我一直用着onedrive都没问题。可以试一下（1）打开Loopback里面的onedrive，如果有的话（2）使用PROCESS-NAME这个规则放行onedrive客户端

**Comment by wpzzz** [comment]
> 应该是你的规则有问题，我一直用着onedrive都没问题。可以试一下（1）打开Loopback里面的onedrive，如果有的话（2）使用PROCESS-NAME这个规则放行onedrive客户端

我都改成自带的默认配置了，DIRECT，都不行

`mixed-port: 7890
allow-lan: false
external-controller: 127.0.0.1:50721
secret: ''
`

**Comment by yi-Xu-0100** [comment]
额，看起来是 secret 错误，可以尝试备份配置，关闭软件 然后删除 home directory ，重启试试 @wpzzz

**Comment by wpzzz** [comment]
> 额，看起来是 secret 错误，可以尝试备份配置，关闭软件 然后删除 home directory ，重启试试 @wpzzz

依旧不行，然后我发现这似乎不止是clash的问题，我用ssr 全局模式，代理规则无论选择哪种都出现相同错误，也就是说只要login.microsoftonline.com经过代理软件了，无论是直连  还是走代理，都会出错

**Comment by Rex0929** [comment]
是system proxy吗，是否尝试过使用tun/tap 可能是自带的onedrive流量没被clash接管？

**Comment by wpzzz** [comment]
我上次测试的是一个刚注册的教育账号，从未登陆过，我换成一个个人账户，可以正常登录， 然后退出这个账户，登录教育账户问题依旧，然后我退出clash，教育账户也登陆上了，再次退出，开启clash直连后重新登录教育账户，依旧异常，但错误和上次稍有不同


连接到onedriver时出现问题 错误代码0x8004e4c3

No Network Connection 
Please check your network settings and try again. [2603]

**Comment by wpzzz** [comment]
https://support.microsoft.com/zh-cn/office/%E9%94%99%E8%AF%AF%E4%BB%A3%E7%A0%81-0x8004deb4%E7%99%BB%E5%BD%95%E6%97%B6onedrive-e8a8d97c-a87e-4dda-a67e-bae4fef05dcb

**Comment by wpzzz** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/123

loopback勾选我的账户和学习账户 搞定

**Comment by Wrandz** [comment]
> #123
> 
> loopback勾选我的账户和学习账户 搞定

我onedrive都用得好好的，只能是loopback问题或者规则问题，开始跟你说了偏不相信。

**Comment by streamgo** [comment]
謝謝了，我也出現同樣的問題，在代理设置的例外里添加[login.microsoftonline.com](http://login.microsoftonline.com/) ，onedrive才能正常登录。此前一直是正常的。WIN10系統。

**Comment by streamgo** [comment]
謝謝你的回覆。暫時是採用這種方式登陸，或者把這個域名添加進排除名單里。

m785887730 ***@***.***> 于2022年10月20日周四 09:44写道：

**Comment by wayne3602** [comment]
我也遇到了这个问题，后来这样解决了           设置-系统代理-绕过域和网络（Bypass Domain/IPNet）-添加- 'login.microsoftonline.com' 这个然后重启clash和onedrive即可

**Comment by streamgo** [comment]
> 

謝謝。暫時只能這樣解決了。

**Comment by hollypeter** [comment]
感谢！
大家可以看看这篇 https://www.9ump.com/archives/79/

**Comment by streamgo** [comment]
感謝！

hollypeter ***@***.***> 于2023年1月9日周一 11:33写道：

**Comment by xiaoze1332** [comment]
> #123
> 
> loopback勾选我的账户和学习账户 搞定

牛！ 实测V2rayN，在将geosite:microsoft添加到直连规则后，将loopback勾选“学校和工作账户”后，解决了onedrive无限登录的问题。

**Comment by Githubbili** [comment]
> 感谢！ 大家可以看看这篇讲Loopback的 https://www.9ump.com/archives/79/

十分有用

**Comment by crazy-zxx** [comment]
系统代理用HTTP模式OneDrive无法登录，PAC模式可以

**Comment by YaoLiMuMu** [comment]
linux 无界面用户terminal怎么办?都没办法登录onedrive网页获取cid了

**Comment by PerryGore** [comment]
> #123
> 
> loopback勾选我的账户和学习账户 搞定

mark

**Comment by weimeng23** [comment]
> 謝謝了，我也出現同樣的問題，在代理设置的例外里添加[login.microsoftonline.com](http://login.microsoftonline.com/) ，onedrive才能正常登录。此前一直是正常的。WIN10系統。

这个有用！ thx
