### ISSUE TITLE
绕过系统代理的功能扩展和疑问

### ISSUE THREAD

**Issue by bai12123** [Fndroid/clash_for_windows_pkg#2878]
### 功能描述

我想请教个问题，因为机场自带的规则，并不能保证我需要直连的网页会直连，所以我只好将网址添加进绕过系统代理功能。但是在连接界面，看到我在浏览这个网站的时候，网站里的某些内容还是会通过代理的方式连接，尽管我在绕过系统代理里添加的是 * .ABCD . * 这样的规则，但是这些内容的地址是  * .CDEF. *这样的，一些大的内容导致机场流量狂飙，所以我不得不手动关闭系统代理，再浏览这个网站。可否添加一个功能，当我填写www.abcd.*这样的规则绕过代理时，我在这个网站所浏览的所有流量都直连（包括其中加载的内容）。又或者是我添加的网址代码不对？？希望作者能回复下我，感谢！！

**Comment by Wrandz** [comment]
你应该修改规则为，碰到不认识的一律直连，可以使用match来实现

**Comment by bai12123** [comment]
> 你应该修改规则为，碰到不认识的一律直连，可以使用match来实现

如何修改，请指教  。

**Comment by Sakuzy0** [comment]
我一直用的是匹配规则没用过绕过代理，选DOMAIN-KEYWORD、SUFFIX下面输网址再选direct。如果不认识的全要直连那远程配置一般不都有漏网之鱼吗，改成direct。

**Comment by bai12123** [comment]
> 我一直用的是匹配规则没用过绕过代理，选DOMAIN-KEYWORD、SUFFIX下面输网址再选direct。如果不认识的全要直连那远程配置一般不都有漏网之鱼吗，改成direct。

你说的这个方法是配置文件-编辑规则-添加规则吧，这个配置文件一更新，你之前添加的不都被覆盖掉了吗？

**Comment by Wrandz** [comment]
> > 我一直用的是匹配规则没用过绕过代理，选DOMAIN-KEYWORD、SUFFIX下面输网址再选direct。如果不认识的全要直连那远程配置一般不都有漏网之鱼吗，改成direct。
> 
> 你说的这个方法是配置文件-编辑规则-添加规则吧，这个配置文件一更新，你之前添加的不都被覆盖掉了吗？

可以试下订阅转化，这样既能实现自定义规则，又能保证不被update的时候覆盖。

**Comment by bai12123** [comment]
> > > 我一直用的规则没有用过传输协议替代，选择匹配域名、后缀再直接选择。不认识的全要直连下面那条鱼配置一般不漏网之类的吗，改成直接成。
> > 
> > 
> > 你说的这个方法是配置文件-编辑规则-添加规则吧，这个配置文件一更新，你之前添加的不都被覆盖掉了吗？
> 
> 可以试下订阅恢复，这样既能实现自定义规则，又能保证不被更新的时间覆盖。

什么是订阅转化，怎么用如何操作

**Comment by Wrandz** [comment]
@bai12123 这是一个很基础的问题，我建议你谷歌，会有一堆很详细的答案。我在这里三言两语根本说不清楚。

**Comment by Sakuzy0** [comment]
> > 我一直用的是匹配规则没用过绕过代理，选DOMAIN-KEYWORD、SUFFIX下面输网址再选direct。如果不认识的全要直连那远程配置一般不都有漏网之鱼吗，改成direct。
> 
> 你说的这个方法是配置文件-编辑规则-添加规则吧，这个配置文件一更新，你之前添加的不都被覆盖掉了吗？

可以用配置预处理，不管怎么更新 添加新机场订阅都可以注入规则

**Comment by Sakuzy0** [comment]
可以看看这个https://github.com/Fndroid/clash_for_windows_pkg/issues?page=3&q=is%3Aissue+is%3Aopen
太复杂可以用这个简单的https://musetransfer.com/s/dmkwofkwi 里面的粘到预处理配置里，按格式添加你要直连的网站

**Comment by bai12123** [comment]
> 可以看看这个#2729 太复杂可以用这个简单的https://musetransfer.com/s/dmkwofkwi 里面的粘到预处理配置里，按格式添加你要直连的网站

感谢感谢，恶补了几小时知识。我用了 #2729方法，虽然跟我想的不太一样，但也算是解决了我的问题。
