### ISSUE TITLE
更新最新版本0.19.15后开启tun模式后,windows网络显示小地球,上网是正常的,就是microsoftconnect被代理,并没有跳过

### ISSUE THREAD

**Issue by zhangde2333** [Fndroid/clash_for_windows_pkg#2882]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.15

### 操作系统

Windows x64

### 系统版本

11

### 问题描述

更新最新版本0.19.15后开启tun模式后,windows网络显示小地球,上网是正常的,就是microsoftconnect被代理,并没有跳过

### 复现步骤

额,就是开了tun模式就会这样,然后logs会显示microsoftconnect.com连接

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
@zhangde2333

`进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行`

**Comment by zhangde2333** [comment]
问题似乎没有了,抱歉
