### ISSUE TITLE
[Bug]: 点击“clash core”无法自动打开dashboard

### ISSUE THREAD

**Issue by ruiy326** [Fndroid/clash_for_windows_pkg#2883]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.15

### 操作系统

Windows x64

### 系统版本

19044.1586

### 问题描述

点击“Clash Core”右方链接，打开Dashboard，需要手动填写controller port 和secret，才能连接。之前都可以自动连接
![图片](https://user-images.githubusercontent.com/102410131/162573493-9ba40164-3ea7-4cfa-8e45-f5b3b5a86a61.png)
图片展示了port不同导致无法连接。重建过config.yaml和appdata\roaming\clash_win文件夹，确定secret也不会自动更新

### 复现步骤

更新controller port或secret，再点击“Clash Core”右方链接，即可复现。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充
_**可能是系统问题，尝试了0.19.11和0.19.13，也需要手动更改port和secret才能打开dashboard。**_

**Comment by Wrandz** [comment]
这个好像很早的版本就一直有这个问题，一直到现在都是，但是我感觉这个问题影响并不大，自己手动改一下不就好了。

**Comment by Fndroid** [comment]
什么浏览器？

**Comment by ruiy326** [comment]
Edge

**Comment by Fndroid** [comment]
这个最新版应该修好了
