### ISSUE TITLE
[Bug]: 开启TUN时右键退出Clash后重新打开Clash不会自动创建TUN网卡

### ISSUE THREAD

**Issue by lcysyx** [Fndroid/clash_for_windows_pkg#2884]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.15

### 操作系统

Windows x64

### 系统版本

21H2

### 问题描述

无论是使用Mixin开关还是TUN开关，在TUN生效的情况下右键任务栏的Clash图标点击Quit退出Clash后，再打开Clash就不会自动创建TUN网卡了，需要手动重新开关一次Mixin或TUN开关才能开启成功。

并且测试了旧版本的CFW 0.18.7是没有这个问题的。

### 复现步骤

1. 使用Mixin或者TUN开关启动TUN模式；
2. 确认TUN网卡能正常上网后，右键任务栏Clash图标，点击Quit退出Clash；
3. 双击桌面的Clash图标重新打开Clash；
4. 等待一段时间，观察TUN网卡未能成功创建，也无法科学上网；
5. 手动重新关闭再打开Mixin或TUN开关，再次观察TUN网卡成功创建，能够正常上网。

### 日志文件

<details><summary>logs</summary><p>

```
time="2022-04-10T00:33:50+08:00" level=error msg="Start Tun interface error: error creating interface: Cannot create a file when that file already exists."
```

</p></details>

**Comment by Fndroid** [comment]
这个是上游问题，可以试试这个[临时解决办法](https://docs.cfw.lbyczf.com/contents/questions.html#%E8%BD%AF%E4%BB%B6%E5%90%AF%E5%8A%A8%E6%97%B6-tun-%E5%88%9B%E5%BB%BA%E7%BD%91%E5%8D%A1%E5%A4%B1%E8%B4%A5-%E6%8F%90%E7%A4%BA-start-tun-interface-error-error-creating-interface-cannot-create-a-file-when-that-file-already-exists-windows)
