### ISSUE TITLE
[Bug]: Script模式+Rule Providers规则匹配可能出现覆盖问题

### ISSUE THREAD

**Issue by LeslieYon** [Fndroid/clash_for_windows_pkg#2885]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.5

### 操作系统

Windows x64

### 系统版本

Windows 10 21H2

### 问题描述

规则模式匹配Rule Providers中的通配规则时，可能出现覆盖问题。
假设有如下一个Rule Provider：
文件名 direct.yaml
```direct.yaml
payload:
  - '+.cn'
  - '+.gov.cn'
```
有如下Script脚本：
```yaml
 script:
   code: |
       if ctx.rule_providers["direct"].match(metadata):
         return "DIRECT"
       return "Proxy"
```
此时Clash只能匹配到+.gov.cn而无法匹配到+.cn
![图片](https://user-images.githubusercontent.com/43743875/162586552-f554fc6d-8540-442a-aa4c-c40518f31b9b.png)
![图片](https://user-images.githubusercontent.com/43743875/162586558-1ae2e53a-3d7b-4edb-87cc-e9549f429664.png)

如果这两条规则位于不同的Rule Provider，则不存在这个问题。

**Comment by Fndroid** [comment]
应该是这个问题，https://github.com/Dreamacro/clash/issues/2045

可以从[这里](https://release.dreamacro.workers.dev/latest/)下载最新的core替换看看
