### ISSUE TITLE
[Bug]: 开启 Specify Protocol 导致 icloud 认证错误

### ISSUE THREAD

**Issue by Maasea** [Fndroid/clash_for_windows_pkg#2886]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.15

### 操作系统

Windows x64

### 系统版本

19043.1586

### 问题描述

当 clash 打开 Specify Protocol 时，icloud 会出现 “认证过程发生错误，请重试”，且icloud 无法正常进行同步。
经过以下排错：
1、全局直连或全局代理，都会出现。排除规则问题
2、UWP loopback 打开/关闭 icloud，都会出现。
3、关闭 Specify Protocol 后，iCloud 恢复正常

### 复现步骤

1、使用微软应用商店的icloud并登陆账号
2、打开Specify Protocol
3、打开 icloud 设置
4、icloud 出现错误提示

**Comment by Fndroid** [comment]
不用python就不要开了

**Comment by yangloft** [comment]
找到了答案，多谢

**Comment by kyan001** [comment]
在 `Internet 属性` → `局域网设置` → `代理服务器` → `高级` → `套接字` 中同样设置代理地址，也可以
