### ISSUE TITLE
[Feature Request]: 需要自定义某些站点不走代理或强制走代理，请问具体怎么操作。

### ISSUE THREAD

**Issue by billowssun** [Fndroid/clash_for_windows_pkg#2889]
### 功能描述

需要自定义某些站点不走代理或强制走代理，请问具体怎么操作。
我知道是在Minxin中添加规则，但是不知道具体的格式，请教一下。谢谢。

**Comment by yi-Xu-0100** [comment]
建议用 parser 或者 diff 修改规则。

https://docs.cfw.lbyczf.com/contents/parser.html

**Comment by Sakuzy0** [comment]
以下填入parser预处理配置 更新订阅,自定义改中间的网址即可

parsers: # array
  # - reg: ^.*$ 匹配所有订阅，或  - url: https://example.com/profile.yaml 指定订阅
  - reg: ^.*$
    yaml:
  # 添加规则
      prepend-rules: # 规则由上往下遍历，如上面规则已经命中，则不再往下处理
        - DOMAIN-SUFFIX,baidu.com,DIRECT#域名后缀匹配
        - DOMAIN-KEYWORD,360,REJECT#域名关键字匹配

**Comment by Sakuzy0** [comment]
以下填入parser预处理配置 更新订阅,自定义改中间的网址即可

```parsers: # array
  # - reg: ^.*$ 匹配所有订阅，或  - url: https://example.com/profile.yaml 指定订阅
  - reg: ^.*$
    yaml:
  # 添加规则
      prepend-rules: # 规则由上往下遍历，如上面规则已经命中，则不再往下处理
        - DOMAIN-SUFFIX,baidu.com,DIRECT#域名后缀匹配
        - DOMAIN-KEYWORD,360,REJECT#域名关键字匹配```

**Comment by billowssun** [comment]
> 
这样做之后我每次更新的订阅都是被处理过的吗？

**Comment by yi-Xu-0100** [comment]
@billowssun parser 是更新订阅后的操作，所以不受更新订阅影响。 diff 类似，同理。建议先看看文档。
