### ISSUE TITLE
如何在clash自定义屏蔽某些站点？如steam，epic下载

### ISSUE THREAD

**Issue by songfy825** [Fndroid/clash_for_windows_pkg#2892]
如何在clash自定义屏蔽某些站点？如steam，epic下载

**Comment by yi-Xu-0100** [comment]
加 rule 规则，建议 parser 或者 diff

**Comment by songfy825** [comment]
有具体的操作教程吗？谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月11日(星期一) 晚上7:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Fndroid/clash_for_windows_pkg] 如何在clash自定义屏蔽某些站点？如steam，epic下载 (Issue #2892)





 
加 rule 规则，建议 parser 或者 diff

**Comment by yi-Xu-0100** [comment]
https://docs.cfw.lbyczf.com/contents/parser.html

**Comment by songfy825** [comment]
3Q




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月11日(星期一) 晚上7:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Fndroid/clash_for_windows_pkg] 如何在clash自定义屏蔽某些站点？如steam，epic下载 (Issue #2892)





 
https://docs.cfw.lbyczf.com/contents/parser.html

**Comment by Rex0929** [comment]
直接把steam/epic的所有网站reject就好了

**Comment by songfy825** [comment]
但是reject以后，登录Steam就会被墙。。。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月11日(周一) 晚上7:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Fndroid/clash_for_windows_pkg] 如何在clash自定义屏蔽某些站点？如steam，epic下载 (Issue #2892)




 
https://docs.cfw.lbyczf.com/contents/parser.html

**Comment by Rex0929** [comment]
> 但是reject以后，登录Steam就会被墙。。。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年4月11日(周一) 晚上7:46 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Fndroid/clash_for_windows_pkg] 如何在clash自定义屏蔽某些站点？如steam，epic下载 (Issue #2892) https://docs.cfw.lbyczf.com/contents/parser.html — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

这好像没办法了，没办法仅屏蔽下载，建议设置一个steam策略，平时就选择proxy，需要下载东西的时候就direct或者reject

**Comment by lilyblessing** [comment]
屏蔽是？如果希望不走代理可以直连 先随便开个游戏下 然后观察一下用的下载域名，暂停了改成那个域名直连就行
```yaml
        - DOMAIN,steampipe.akamaized.net,🎯 全球直连
        - DOMAIN-SUFFIX,steamstatic.com,🎮 游戏平台
        - DOMAIN-SUFFIX,steam-chat.com,🎮 游戏平台
        - DOMAIN-SUFFIX,steampowered.com,🎮 游戏平台
        - DOMAIN-SUFFIX,steamcommunity.com,🎮 游戏平台
        - DOMAIN-SUFFIX,steamcontent.com,🎮 游戏平台
```

**Comment by songfy825** [comment]
谢谢谢谢!



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月17日(周日) 晚上8:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Fndroid/clash_for_windows_pkg] 如何在clash自定义屏蔽某些站点？如steam，epic下载 (Issue #2892)




 
屏蔽是？如果希望不走代理可以直连 先随便开个游戏下 然后观察一下用的下载域名，暂停了改成那个域名直连就行
         - DOMAIN,steampipe.akamaized.net,🎯 全球直连         - DOMAIN-SUFFIX,steamstatic.com,🎮 游戏平台         - DOMAIN-SUFFIX,steam-chat.com,🎮 游戏平台         - DOMAIN-SUFFIX,steampowered.com,🎮 游戏平台         - DOMAIN-SUFFIX,steamcommunity.com,🎮 游戏平台         - DOMAIN-SUFFIX,steamcontent.com,🎮 游戏平台

**Comment by songfy825** [comment]
![image](https://user-images.githubusercontent.com/100999715/163769507-50bc866e-a370-41bc-b658-887332494e34.png)
就像这样，已经设置成DIRECT了，但左上角还是记录了下载速度。这应该不算已经屏蔽成功了吧？我clash一直开着 下载百度云什么的，左上角也没有显示下载速度

**Comment by songfy825** [comment]
![image](https://user-images.githubusercontent.com/100999715/163769728-b23af6d4-c8b9-4317-aa55-23f129452cf5.png)
还有zhe'z这种情况，已经将全局代理关闭了，为什么左上角还是记录我的下载，请求大神帮助

**Comment by lilyblessing** [comment]
> 

关全局也有：域名规则里面记录了，碰撞到这条规则就会走clash接管。
记录下载速度：你设置的直连direct就不会走节点流量下载，左上角有没有显示都无所谓。不放心可以自己看看节点流量

**Comment by songfy825** [comment]
好的好的，谢谢解答！

**Comment by songfy825** [comment]
我也不知道为什么 关闭系统代理后，Steam在下载的时候 clash也一直在工作代理，偷偷跑了几十个g流量



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月13日(周三) 晚上8:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Fndroid/clash_for_windows_pkg] 如何在clash自定义屏蔽某些站点？如steam，epic下载 (Issue #2892)




  
但是reject以后，登录Steam就会被墙。。。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年4月11日(周一) 晚上7:46 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Fndroid/clash_for_windows_pkg] 如何在clash自定义屏蔽某些站点？如steam，epic下载 (Issue #2892) https://docs.cfw.lbyczf.com/contents/parser.html — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
这好像没办法了，没办法仅屏蔽下载，建议设置一个steam策略，平时就选择proxy，需要下载东西的时候就direct或者reject

**Comment by wangshuai-007** [comment]
steam是会识别你的IP地址然后选择就近的服务器给你下载
假如你需要steam下载加速

我的经验是,
1. 关闭`System Proxy`
2. 重启`Steam` 等待steam下载开始
3. 开始下载后再打开`System Proxy`就不会通过代理下载游戏了

这样一天调整一次开关就可以了

**Comment by SKYchiEz** [comment]
我的问题是STEAM下载偏偏不走代理……你是怎么弄得，我下载不走代理的话速度只有几kb每秒

**Comment by lilyblessing** [comment]
> 我的问题是STEAM下载偏偏不走代理……你是怎么弄得，我下载不走代理的话速度只有几kb每秒

开tun模式，还没走就写条规则走进程代理

**Comment by SKYchiEz** [comment]
（已经开了，用的Global全局）是TUN的配置有问题吗？


[cid:943927db-f999-45db-b492-8f0f9000c96e]
________________________________
发件人: lilyblessing ***@***.***>
发送时间: 2023年3月12日 13:02
收件人: Fndroid/clash_for_windows_pkg ***@***.***>
抄送: SKYchiEz ***@***.***>; Comment ***@***.***>
主题: Re: [Fndroid/clash_for_windows_pkg] 如何在clash自定义屏蔽某些站点？如steam，epic下载 (Issue #2892)


我的问题是STEAM下载偏偏不走代理……你是怎么弄得，我下载不走代理的话速度只有几kb每秒

开tun模式，还没走就写条规则走进程代理

―

**Comment by SKYchiEz** [comment]
已经开了，用的是global全局。是tun配置有问题吗？

`dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback: []
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53`

**Comment by lilyblessing** [comment]
> 已经开了，用的是global全局。是tun配置有问题吗？

那就打开connection检查 输入框打steam 检查流量；

如果steam那条连接显示的直连就点进去看rule规则；

然后删改规则就行了。

**Comment by SKYchiEz** [comment]
> > 已经开了，用的是global全局。是tun配置有问题吗？
> 
> 那就打开connection检查 输入框打steam 检查流量；
> 
> 如果steam那条连接显示的直连就点进去看rule规则；
> 
> 然后删改规则就行了。

![屏幕截图 2023-03-14 185551](https://user-images.githubusercontent.com/98296970/224980540-3b41e298-d275-4ac4-b380-f362aea23ed5.png)

全显示global，但速度慢
