### ISSUE TITLE
[Bug]: 是否可以设置开机后不启动Clash也能代理？

### ISSUE THREAD

**Issue by Cairl** [Fndroid/clash_for_windows_pkg#2897]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.15

### 操作系统

Windows x64

### 系统版本

21H2

### 问题描述

之前不知道怎么弄的，每次开机不用开启clash也能用上面的代理看youtube，现在电脑重装一次就不知道怎么复现了

### 复现步骤

重新试过重装，没改过文件，没设置开机启动

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Cairl** [comment]
又反复试了试，发现只要点了「强制退出」的话，后台没有clash也能进行代理，可是重启电脑之后就失效了，不知道之前是怎么弄的重启电脑后也照旧能代理

**Comment by yi-Xu-0100** [comment]
看不懂，大受震撼.jpg

1. 猜测 core 被设置自启动了 （与重启无代理冲突
2. 猜测 cfw 被设置自启动了 （与描述不符
3. 猜测 这里的重启 是否会保留原后台软件，类似假重启。 （有点可能，那估计是 windows 的锅

**Comment by Fndroid** [comment]
没有这个功能
