### ISSUE TITLE
[Feature Request]: 希望自启动时可以自动最小化

### ISSUE THREAD

**Issue by godefy** [Fndroid/clash_for_windows_pkg#2898]
### 功能描述

目前自启动时会显示完整界面，通过cmd命令调用，也不支持cmd命令里的通用最小化参数min。希望可以优化一下，如果勾选"开机启动"，那么在开机启动时，是以最小化形式启动的。或者是能支持命令行启动时，通过参数控制最小化。

**Comment by yi-Xu-0100** [comment]
setting 里打开 slient start

**Comment by godefy** [comment]
收到~感谢~
