### ISSUE TITLE
能否增加一个新的功能开关，在右上角关闭时直接退出

### ISSUE THREAD

**Issue by jkqxl** [Fndroid/clash_for_windows_pkg#2899]
### 功能描述

希望，可以在右上角关闭时直接退出，而不是在设置中退出程序，之后还要弹窗确定

因为只是偶尔使用，并不是全天都开启软件，所以希望增加一个可以直接退出的开关

**Comment by yi-Xu-0100** [comment]
setting 打开 lightweight mode

**Comment by jkqxl** [comment]
没用啊，和原来还是一样

**Comment by yi-Xu-0100** [comment]
@jkqxl 

> 之后还要弹窗确定

抱歉，没注意你的描述，以为你是想关闭 cfw ，只保留 core。

我这边测试 win10 21H2 没有弹窗确定，你的是什么系统，有无截图？

**Comment by jkqxl** [comment]
这样，我说的是能否直接关闭，以及不保留任何后台服务，轻量模式在关闭后还是有部分服务

![Snipaste_2022-05-16_12-24-08](https://user-images.githubusercontent.com/72729140/168519550-34fc791d-51f4-46dd-99af-7e89d165fad7.png)

**Comment by Fndroid** [comment]
不能
