### ISSUE TITLE
4.4.0以后 不能切换规则了

### ISSUE THREAD

**Issue by LiuShuaiChen** [Fndroid/clash_for_windows_pkg#29]
全局和rules规则 切换方式不能用了

**Comment by Fndroid** [comment]
Clash dev版本的bug

**Comment by Fndroid** [comment]
https://github.com/Dreamacro/clash/pull/49

**Comment by Fndroid** [comment]
0.4.5已解决 https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.4.5
