### ISSUE TITLE
开加速器后代理自动关闭

### ISSUE THREAD

**Issue by zseventh** [Fndroid/clash_for_windows_pkg#290]
每次玩游戏开了加速器之后代理总是自动关闭是什么原因

**Comment by OwoHealing** [comment]
你所説的“加速器”其本質為為具體項目服務的代理工具，很明顯你用的”加速器“和Clash一樣使用了系統代理通道(win+i可以看到系統代理設定)，他們在使用系統資源上是互斥的。

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
