### ISSUE TITLE
[Feature Request]: 引入Meta内核

### ISSUE THREAD

**Issue by zzz6839** [Fndroid/clash_for_windows_pkg#2901]
### 功能描述

[https://github.com/MetaCubeX/Clash.Meta/tree/Meta](url)
Meta内核支持特性例如Policy Group Filter：

 proxy-groups:

 - name: 🚀 HK Group

    type: select
    use:
      - ALL
    filter: 'HK'

  - name: 🚀 US Group
    type: select
    use:
      - ALL
    filter: 'US'

原版没有，个人觉得相比再proxy-provider里加Filter，Meta里的这个特性更方便。

**Comment by Fndroid** [comment]
没有计划

**Comment by chenzhiguo** [comment]
如今cf自建vless大火，不支持meta内核...就没法用，很可惜，只能放弃该app了。

**Comment by NyaMisty** [comment]
3年了，Meta早已经5k star，反观CFW自始至终就一句“没有计划”。或许，只能理解为Fndroid想和Dreamacro搞护城河，拒绝Meta参与生态。

Meta支持并不难做：
- 配置方面本来CFW也没有特殊的界面，都不用动
- 界面上的测速需要修改一下，目前手动测速全是Timeout
- Log需要修改一下，目前meta的log不会自动滚动

举手之劳，若不是Fndroid不开放源代码，想必早已能兼容。

**Comment by chenzhiguo** [comment]
所以目前已启用CFW，`Clash Verge`挺香的，很好用。

**Comment by Fndroid** [comment]
有多少star我并不关心，不支持是因为我不用，也没有精力了解各种“新特性”所以不能处理兼容问题。

目前premium提供的功能可以满足我的各种需求，且接受PR。

至于本项目不开源这个没办法。可以去用其他兼容的客户端。
