### ISSUE TITLE
只有在开启 Clash for Windows 的情况下，UWP 应用才能正常上网

### ISSUE THREAD

**Issue by ChuNiZuoJi** [Fndroid/clash_for_windows_pkg#2905]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.15

### 操作系统

Windows x64

### 系统版本

Windows 11

### 问题描述

如题所述，只有在**开启 Clash for Windows 代理**的情况下，UWP 应用（如 Microsoft Store）才能正常上网。一旦关闭 Clash 或关闭 System Proxy，UWP 应用就会全部断网。
UWP Loopback 已经全部勾选。

我可能是唯一一个遇上这个问题的人。

### 复现步骤

莫名其妙就成这样了，不知道怎么复现。

### 日志文件

<details><summary>logs</summary><p>

```


```

</p></details>

**Comment by ChuNiZuoJi** [comment]
在尝试安装卸载 Service Mode、开关 TUN Mode，并重装了一次 Clash 后，问题莫名其妙消失了。

**Comment by ChuNiZuoJi** [comment]
再补充：在没问题的时候开启了一下 Adguard（最新版 7.9.1），然后问题立刻就回来了。

**Comment by Indekkusu545** [comment]
Adguard的原理也是代理，应该和cfw冲突了。请检查一下**Windows设置**里的**代理**（[ms-settings:network-proxy](ms-settings:network-proxy)）选项。

正常情况下关闭 Clash 或关闭 System Proxy 时，会关闭代理选项。但 Adguard 导致代理选项没有正确关闭，此时流量依然发送到了 mixed-port 端口上，而 Clash 并没有在监听这个端口，从而导致上不了网。

**Comment by ChuNiZuoJi** [comment]
> Adguard的原理也是代理，应该和cfw冲突了。请检查一下**Windows设置**里的**代理**（ms-settings:network-proxy）选项。
> 
> 正常情况下关闭 Clash 或关闭 System Proxy 时，会关闭代理选项。但 Adguard 导致代理选项没有正确关闭，此时流量依然发送到了 mixed-port 端口上，而 Clash 并没有在监听这个端口，从而导致上不了网。

已检查，未发现这个问题。Adguard 设置里勾选的是流量过滤和 WFP 驱动模式，而不是系统代理模式。

**Comment by ChuNiZuoJi** [comment]
后续：在反复重装几次 Adguard 后，不知道怎么就打通了任督二脉，问题又消失了。
推测问题可能还是出在 Adguard 使用的驱动这里。
