### ISSUE TITLE
cfw-bypass无效？

### ISSUE THREAD

**Issue by wpzzz** [Fndroid/clash_for_windows_pkg#2908]
cfw-bypass等于系统代理设置的例外对吧？ 
我在配置文件末尾写上以下内容，其中只有开头两个域名是我添加的，剩下的部分是复制SETTINGS里Bypass Domain/IPNet内容
```
cfw-bypass:
  - 'music.163.com' # 网易云域名1
  - '*.music.126.net' # 网易云域名2
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
```

保存后重启，然后打开系统代理设置，例外一栏还是原来的，没有看到163
win10  . cfw 0.19.14

**Comment by yi-Xu-0100** [comment]
去 setting 找 system proxy 的 http 设置，这个字段好像不是这样，原先的设置是，但被废了

**Comment by AkariiinMKII** [comment]
字段已废弃 新用法参考 https://docs.cfw.lbyczf.com/contents/bypass.html#%E8%AE%BE%E7%BD%AE%E6%96%B9%E5%BC%8F
