### ISSUE TITLE
[Bug]: 窗口无法记忆上一次关闭的位置

### ISSUE THREAD

**Issue by CaTechX** [Fndroid/clash_for_windows_pkg#2909]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.15

### 操作系统

Windows x64

### 系统版本

22000.613

### 问题描述

当CFW在超出屏幕左边框外的位置关闭时，再次启动时窗口位置会被重置，无法记忆关闭时的位置。而下边与右边没有类似问题，能够保持上次的位置启动

### 复现步骤

将窗口部分拖动至屏幕外，彻底关闭应用
![Snipaste_2022-04-15_11-14-19](https://user-images.githubusercontent.com/90589341/163513597-c2124012-9068-408d-9845-a97052fc2557.png)

再次启动时窗口复位居中
![Snipaste_2022-04-15_11-15-08](https://user-images.githubusercontent.com/90589341/163513686-35077580-77a3-4b6a-8dbf-6741b0a6a97d.png)

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
