### ISSUE TITLE
Clash for window 不能连上。

### ISSUE THREAD

**Issue by yjays3981** [Fndroid/clash_for_windows_pkg#291]
你好，我安装clash for window 以后，成功导入profiles,也成功刷到节点，选了节点，但是一直没连上。显示 connected，但是上下载都是处于0kb/s.以下是log。

time="2019-11-28T19:59:58+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2019-11-28T19:59:58+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2019-11-28T19:59:58+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2019-11-28T19:59:58+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"

请问有什么办法解决吗？
![image](https://user-images.githubusercontent.com/58296609/69805580-eabea100-121b-11ea-9a15-9b03c0ea7ab2.png)

**Comment by Fndroid** [comment]
系统设置 - 网络和 internet - 代理 看下系统代理设置

**Comment by yjays3981** [comment]
![image](https://user-images.githubusercontent.com/58296609/69848047-d62de780-12b3-11ea-88fd-59b3d251f934.png)
![image](https://user-images.githubusercontent.com/58296609/69848054-dcbc5f00-12b3-11ea-81bc-2081a9c91cc1.png)
你说的是这个吗？
我用其他ssr是没问题的，但是就是clash 用不上。

**Comment by Fndroid** [comment]
用不上是因为系统代理没被改成clash的，你是有其他软件阻止软件设置代理了吧

手动设置 Address: 127.0.0.1 Port: 7890

**Comment by yjays3981** [comment]
![image](https://user-images.githubusercontent.com/58296609/69848873-29a13500-12b6-11ea-8e9e-44a2755aec38.png)


也是不行。我已经把其他代理软件都关闭了。

**Comment by g8up** [comment]
一个小教程，参考一下，看看设置问题：
https://v.youku.com/v_show/id_XNDQ2NzQzODY4OA==.html

**Comment by pandaevil** [comment]
我也碰到了类似的问题，联系服务商看了下设置没有问题，延迟测试也正常，但始终连不上。系统代理已经正常设置。不知道还有什么地方设置需要改动。

**Comment by Fndroid** [comment]
refer: https://github.com/Fndroid/clash_for_windows_pkg/issues/312

**Comment by flyinginte** [comment]
我也遇到了同样的问题。
尝试过修改端口为2028，不成功。
尝试过在cmd命令下netsh winsock reset，但是只有重启以后感觉有点数据量，但是也是连不上。
尝试过换数据源，但是都不成功。
总体来说，就是上传和下载的数据量很小，几乎可以忽略不计。

**Comment by zjz3001** [comment]
ubuntu可以，但是win10用不了

**Comment by 46319943** [comment]
> refer: #312

系统：Win10
Clash版本：0.18.10
我的表现是：Clash进行延迟测试，一切正常，系统代理也设置正常。开机之后的一段时间，立马打开浏览器，可以正常上网。但是过一段时间之后，网络异常，谷歌打不开；一直刷新，有时候会有几秒钟网络畅通，然后又不行了。表现很迷惑
按照这个Issue中的方法，使用Process Monitor测试之后，发现有一个叫做ECAgent.exe的进程在我打开浏览器，访问网页后的几秒钟后，修改了注册表值，然后就访问不了网页了。
经查询，这个进程是深信服的VPN软件，在没有设置开机启动启动它的情况下也会自动运行后台进程。由于学校内网需要使用VPN连接，所以多年前下了这个软件。网上查了一下这个软件，发现这个软件风评很不好，这个垃圾软件会有很多间谍行为，包括扫描硬盘、拦截请求等。
卸载软件并重启之后，一切恢复正常了。

之前我使用的是校园网，自然没有这个问题；而后换到学校的电信网之后，就出现了这个问题。搞了一天，终于发现问题在哪了。这个EasyConnet软件是真的流氓。

**Comment by administrator2019** [comment]
系统：Win11
Clash版本：0.19.29
我的表现是：Clash进行延迟测试，一切正常，系统代理也设置正常。一切设置都正常，但是就是上不了网，节点什么的也没问题，显示上下都是0，打开google就是无法连接，不知到是什么阻止了上网进程。

**Comment by theParkerWong** [comment]
看看時區、時間同步有沒有問題。我裝了英文系統，市區設置到北美去了，於是無法連接，校正後恢復正常

**Comment by yelian1** [comment]
插件，看看浏览器有没有安装了科学上网插件

**Comment by hydd30** [comment]
> 

谢谢你帮大忙了，真就是easyconnect这个进程的问题，这个进程还关不掉，会自动重启，关进程之后只要迅速删掉那个ECAgent.exe就好了😅😅害我换了好几个机场查了好久

**Comment by hydd30** [comment]
> > refer: #312
> 
> 系统：Win10 Clash版本：0.18.10 我的表现是：Clash进行延迟测试，一切正常，系统代理也设置正常。开机之后的一段时间，立马打开浏览器，可以正常上网。但是过一段时间之后，网络异常，谷歌打不开；一直刷新，有时候会有几秒钟网络畅通，然后又不行了。表现很迷惑 按照这个Issue中的方法，使用Process Monitor测试之后，发现有一个叫做ECAgent.exe的进程在我打开浏览器，访问网页后的几秒钟后，修改了注册表值，然后就访问不了网页了。 经查询，这个进程是深信服的VPN软件，在没有设置开机启动启动它的情况下也会自动运行后台进程。由于学校内网需要使用VPN连接，所以多年前下了这个软件。网上查了一下这个软件，发现这个软件风评很不好，这个垃圾软件会有很多间谍行为，包括扫描硬盘、拦截请求等。 卸载软件并重启之后，一切恢复正常了。
> 
> 之前我使用的是校园网，自然没有这个问题；而后换到学校的电信网之后，就出现了这个问题。搞了一天，终于发现问题在哪了。这个EasyConnet软件是真的流氓。

谢谢你，真就是easyconnect这个进程的问题，关键是这个进程还关不掉，会自动重启，需要关掉之后迅速删掉源文件ECAgent.exe😅😅😅害我换了好几个✈场还查了好久
，就牛魔离谱

**Comment by F243p** [comment]
点击配置文件却不能出现节点
![Uploading IMG_1521.jpeg…]()
