### ISSUE TITLE
[Feature Request]: 导入openflash导出的clash配置文件报错

### ISSUE THREAD

**Issue by anglesccs** [Fndroid/clash_for_windows_pkg#2911]
### 功能描述

导入openflash导出的clash配置文件报错，需要删除如图语句才能正常使用，能否把这个给屏蔽掉？不要去识别这句
![163539493-b36cf9ac-0efe-46a5-bd63-ba47bce0d7f2](https://user-images.githubusercontent.com/49857157/163540083-5565e62a-ba44-4068-9ea4-dde1886e606e.jpg)

**Comment by Fndroid** [comment]
不能

**Comment by yi-Xu-0100** [comment]
parser 或者 diff 处理。

**Comment by yeefaye** [comment]
Openclash有配置文件和运行文件两种的，我在Openclash/CFA/CFW都使用同样的配置文件，没有任何问题。
