### ISSUE TITLE
[Bug]: 开启service mode后，面板关闭整个面板进程退出而不是缩小回状态栏图标

### ISSUE THREAD

**Issue by Xianbei233** [Fndroid/clash_for_windows_pkg#2913]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.15

### 操作系统

Windows x64

### 系统版本

21h2

### 问题描述

开启service mode，关闭面板，发现面板进程退出，右下角tray icon消失，重新打开后发现面板链接时间重新计数

### 复现步骤

开启service mode，关闭面板（面板右上角按x）

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```
[2022-04-15-212754.log](https://github.com/Fndroid/clash_for_windows_pkg/files/8496129/2022-04-15-212754.log)

</p></details>

**Comment by Fndroid** [comment]
settings里lightweight mode关掉
