### ISSUE TITLE
[Bug]: 右键托盘图标后展开的功能栏未跟随Windows原生样式

### ISSUE THREAD

**Issue by EA-DICE** [Fndroid/clash_for_windows_pkg#2922]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.15

### 操作系统

Windows x64

### 系统版本

22000.613

### 问题描述

右键托盘图标后展开的功能栏未跟随Windows原生样式，而在0.19.14版本中可以支持原生样式
![image](https://user-images.githubusercontent.com/42771283/163677547-5c672912-0602-46d4-9001-fb038f619f8f.png)

### 复现步骤

右键托盘图标

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
上游问题
