### ISSUE TITLE
理解你们打广告,但是不要什么烂钱都恰.

### ISSUE THREAD

**Issue by XiHanShui** [Fndroid/clash_for_windows_pkg#2923]
理解你们打广告,但是不要什么烂钱都恰.看到你们的广告买了极客云, 用不了用不了.建议去掉他们的广告不要误导其他人了. 已经加了他们的电报群,全部都是禁言的. 希望其他人不要上当了

**Comment by Fndroid** [comment]
我试了一下，基本全部节点都可用

**Comment by XiHanShui** [comment]
刚刚看了一下,除了广港其他的都可用了. 我昨天测试时Benchmark都是通的,就是上不了.

**Comment by XiHanShui** [comment]
自己有一个主力机场,看到推荐的,买了最便宜的套餐试用一下,看来最便宜的不太稳定

**Comment by shen-lan** [comment]
google helper 它不香 ？跟人合租一个月才5块钱
