### ISSUE TITLE
[疑问] CFW为什么不能做到像手机QX、Surge、Loon等代理工具那样的独立配置文件呢？

### ISSUE THREAD

**Issue by Soizzer** [Fndroid/clash_for_windows_pkg#2926]
### 功能描述

CFW现在完全是使用机场设定的配置文件，也就是说，只要一更新，所有个人设定的配置将全部被覆盖。
虽然也有提供“合并”和“配置文件预处理”等辅助功能，但其实需要懂得一些相关命令和代码才能更好的使用，对于小白用户并不友好。
而手机上的几乎所有代理工具，都支持配置文件独立使用，只要按自己习惯设置好规则、策略组等，不论你用几个机场、怎么更新订阅，用户个人的配置文件都不会被覆盖丢失。
那为什么CWF不能采用这种方式呢？？

是不是可以设计成两种模式供用户选择呢：
1、标准模式，即现在的默认使用机场配置方式，小白导入订阅即可实现简单的规则和策略组。
2、高级模式，即调用用户个人配置文件，适合进阶用户配置自己的规则和策略组。机场订阅只保留节点信息，为策略组提供正则筛选节点的功能。

**Comment by yi-Xu-0100** [comment]
1. 是 CFW。
2. 如果这一点点都不愿意学，很难说你是怎么学会配置策略组的，毕竟最开始 clash 的相关配置内容还得学。

**Comment by AkariiinMKII** [comment]
您要找的是 `proxy-provider` 吗

**Comment by Soizzer** [comment]
> 您要找的是 `proxy-provider` 吗

不仅仅是，还包括用户根据自己习惯修改的策略组、命名方式、规则包等自定义的内容，默认情况下，一更新订阅，就都被覆盖了。需要使用配置文件预处理在更新时混合自定义内容，但感觉还不是太方便，有些内容对于一般用户无法实现，比如我想删除订阅里某个自带的策略组，在不懂得脚本语言的前提下基本无法实现。但如果是把配置文件单独调用，那么只需完成一次配置文件的修改，就可以任意更新机场订阅而不受影响了，手机上的代理工具，目前都是这样，无论怎么更新订阅，都不会影响到已经设置好的配置文件。

**Comment by Soizzer** [comment]
> 1. 是 CFW。
> 2. 如果这一点点都不愿意学，很难说你是怎么学会配置策略组的，毕竟最开始 clash 的相关配置内容还得学。
> 3. 我个人手机上也只用过 CFA，而且用默认配置，不自定义，所以不增加学习成本。如果你手机上用的多，可以降低电脑的学习成本，放弃不学即可，又不是一定要修改后才能用。对小白来说，先能使才对，后面都是个人学习过程。
> 4. 如果觉得 parser 还复杂，建议看看 diff

谢谢纠正。
我只是觉得，如果能更方便用户使用会更好，手机上的代理工具用户体验其实就很好。我现在觉得CFW和手机代理工具在功能上几乎没差别，唯一就是更新订阅会覆盖配置这点，挺不习惯的，手机上的工具配置完一次，无论怎么更新订阅、更换机场、使用多个机场，都不会影响已配置好的配置文件。

**Comment by yi-Xu-0100** [comment]
> 比如我想删除订阅里某个自带的策略组，在不懂得脚本语言的前提下基本无法实现。

这里从 clash 的角度看，是很难做的，因为策略组和规则是耦合的，如果策略组被删除了，对应规则没有仍然会报错，而这样的对应关系，是需要了解 clash 的配置规则的。所以我也是很奇怪，如果有修改的需求，必然需要了解 clash 的配置规则，而了解之后，那不论是直接使用 proxy-provider 整合一次性配置，还是使用 parser 或 diff 修改配置，都是一样的需要解决节点、策略组、规则三者的耦合关系。他不只是单独一项而成立的。

当然如果你想 clash 完成配置中的三者关系的分离，方便配置，应该尝试去 core 提出需求。
core issue: <https://github.com/Dreamacro/clash/issues>

> 手机上的工具配置完一次，无论怎么更新订阅、更换机场、使用多个机场，都不会影响已配置好的配置文件。

这里其实，使用  proxy-provider 是可以实现的。
如果愿意去学习的话，parser 也是可以做的。
可以参考 #2193 #2729

**Comment by Soizzer** [comment]
> > 比如我想删除订阅里某个自带的策略组，在不懂得脚本语言的前提下基本无法实现。
> 
> 这里从 clash 的角度看，是很难做的，因为策略组和规则是耦合的，如果策略组被删除了，对应规则没有仍然会报错，而这样的对应关系，是需要了解 clash 的配置规则的。所以我也是很奇怪，如果有修改的需求，必然需要了解 clash 的配置规则，而了解之后，那不论是直接使用 proxy-provider 整合一次性配置，还是使用 parser 或 diff 修改配置，都是一样的需要解决节点、策略组、规则三者的耦合关系。他不只是单独一项而成立的。
> 
> 当然如果你想 clash 完成配置中的三者关系的分离，方便配置，应该尝试去 core 提出需求。 core issue: https://github.com/Dreamacro/clash/issues
> 
> > 手机上的工具配置完一次，无论怎么更新订阅、更换机场、使用多个机场，都不会影响已配置好的配置文件。
> 
> 这里其实，使用 proxy-provider 是可以实现的。 如果愿意去学习的话，parser 也是可以做的。 可以参考 #2193 #2729
> 
> 甚至你可以使用第三方的订阅转化工具。见： https://github.com/tindy2013/subconverter

感谢大佬的耐心解答！
这次又回去仔细研究了下您推荐的 #2193 #2729，现在已经解决了我所有的问题啦！
虽然之前也有看，但没有看完整，所以只解决了一部分问题，现在已全部满足我需求了！！
再次感谢！！

**Comment by learner0116** [comment]
最简单的方法是用自带的新功能differ，differ能把自定义的变更保存下来，后面更新文件时不会覆盖自定义规则！不需要parse，mix，proxy-provider
