### ISSUE TITLE
开了代理页面经常只加载到一半是什么情况？

### ISSUE THREAD

**Issue by takeItIzzy** [Fndroid/clash_for_windows_pkg#293]
有时候是 css 没加载出来，有时候是页面元素没加载出来

**Comment by Fndroid** [comment]
带个图？

**Comment by Fndroid** [comment]
是不是用了adguard for windows

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
