### ISSUE TITLE
TUN模式无法使用

### ISSUE THREAD

**Issue by bigbaldy1128** [Fndroid/clash_for_windows_pkg#2930]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.15

### 操作系统

Windows x64

### 系统版本

Windows 11 专业版 21H2

### 问题描述

0.19.0之后版本的TUN模式都无法访问外网，必须设置System Proxy才行，这个问题我在去年就提过了，但是到现在依然没有解决
https://github.com/Fndroid/clash_for_windows_pkg/issues/2497

### 复现步骤

1.设置TUN模式
2.访问外网

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by 0x696c757a696f** [comment]
可以试试卸载后安装选给所有人安装，并安装到其他盘符。我这边成功了。
