### ISSUE TITLE
[Feature Request]: 设置开机启动后，每次启动电脑后，clash都会弹出窗口，需要手动点x按钮让其在后台运行，希望能够自动完成这个动作

### ISSUE THREAD

**Issue by chazhongbao** [Fndroid/clash_for_windows_pkg#2931]
### 功能描述

打开 Silent Start 、Lightweight Mode、Start with Windows后，每次开机后，都会弹出clash启动窗口，能否设置不要弹出窗口呢，让其在后台运行即可

**Comment by yi-Xu-0100** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/2888#issuecomment-1094483218

**Comment by shixuewei** [comment]
目前也发现clash这个问题，能不能每次开机自启动后不弹出客户端页面呢
