### ISSUE TITLE
[Feature Request]: 让TUN模式的配置复用订阅中的TUN设置

### ISSUE THREAD

**Issue by gouku** [Fndroid/clash_for_windows_pkg#2933]
### 功能描述

目前TUN模式需要手动设置DNS服务器、fallback dns、fake ip、dns劫持、tun stack一系列设置，非常的繁琐，然而我通过subconverter转出来的链接是自带这些配置的，如果cfw在读取到配置文件中有这个设置直接复用他是不是更好？这样就不需要单独设置了（像clashx pro 一样）

**Comment by Fndroid** [comment]
把tun mode关掉就是用profile里的

**Comment by gouku** [comment]
@Fndroid 谢谢大佬回复，希望可以考虑 https://github.com/Fndroid/clash_for_windows_pkg/issues/2699 ，不然确实不好判断
