### ISSUE TITLE
[已解决 感谢yi-Xu大神] 哪位大佬可以分享一个在Parser里查找并替换文本的代码呀？

### ISSUE THREAD

**Issue by Soizzer** [Fndroid/clash_for_windows_pkg#2934]
### 功能描述

不想使用机场默认的节点命名，因为很多机场的节点名都很“啰嗦”，想根据自己的习惯修改名字。
我自己现在的做法是，更新完订阅后，用记事本打开配置文件，使用记事本的“查找”“替换”功能，手动修改节点名。
前几天看到有网友分享了在Parser里删除机场订阅默认的策略组和规则代码，特别有用，想着这个节点改名是不是应该也可以用代码来自动完成呢？可惜自己不懂脚本，谷歌了半天，有些文章对我来说还是太复杂。
有大佬可以分享一个吗？

以下是删除机场订阅默认的策略组和规则代码：
  # 删除服务商提供的策略组和规则
    code: |
      module.exports.parse = (raw, { yaml }) => {
        const rawObj = yaml.parse(raw)
        const groups = []
        const rules = []
        return yaml.stringify({ ...rawObj, 'proxy-groups': groups, rules })
      } 
原贴在此：#2729  #2193

谢谢！

**Comment by Soizzer** [comment]
> 说实话，感觉用 parser 实现订阅转化功能，我的实验是更新订阅比较慢的，不如直接第三方订阅转化来的快。如果不考虑正则，可以尝试这样：
> 
> ```js
> parser:
>   - reg: '^.*$'
>     code: |
>       module.exports.parse = async (raw, { yaml }) => {
>         let rawObj = yaml.parse(raw);
>         let newName = '美国节点'; //此处更换想要的名字
>         rawObj['proxies'].forEach(proxy => {
>           if (proxy['name']==='US') { //此处更换想替换的名字，可以考虑正则匹配或者更多的条件判断
>             proxy['name'] = newName;
>           }
>         });
>         return yaml.stringify(rawObj);
>       };
> ```
> 
> 至于更多的思路，需要给出更多的判断条件，和匹配方式了。

哇塞，太谢谢乐于助人的yi-Xu大佬了，在很多帖子里都看到你热情的解答网友的问题！感谢感谢，我先试试看！

**Comment by Soizzer** [comment]
> 说实话，感觉用 parser 实现订阅转化功能，我的实验是更新订阅比较慢的，不如直接第三方订阅转化来的快。如果不考虑正则，可以尝试这样：
> 
> ```js
> parser:
>   - reg: '^.*$'
>     code: |
>       module.exports.parse = async (raw, { yaml }) => {
>         let rawObj = yaml.parse(raw);
>         let newName = '美国节点'; //此处更换想要的名字
>         rawObj['proxies'].forEach(proxy => {
>           if (proxy['name']==='US') { //此处更换想替换的名字，可以考虑正则匹配或者更多的条件判断
>             proxy['name'] = newName;
>           }
>         });
>         return yaml.stringify(rawObj);
>       };
> ```
> 
> 至于更多的思路，需要给出更多的判断条件，和匹配方式了。
yi-Xu大佬，刚才试用了下代码，没成功，可能我用的方式不对。现在有两个问题：
1、
我是想和那段“删除机场策略组和规则的代码一起使用，目的是删除完默认规则后，修改机场默认节点名字。
我将您的代码直接放到删除机场规则的代码后，结果原来的删除机场规则代码也不起作用了，如图。我觉得应该不是直接 
把代码放在之前那段代码后面，可是我自己也不懂如何调整。
![微信截图_20220420220129](https://user-images.githubusercontent.com/73036854/164249845-c61a7826-a478-471b-bd85-c5031f8dddea.png)
2、
我想修改的名字，不是完整替换，而是只想修改节点名字里的一部分，例如：
把 “HONGKONG-IEPL-01-2X” 这个名字中的 “HONGKONG" 替换成 ”HK" 
这样即可，这样可以做到吗？

**Comment by yi-Xu-0100** [comment]
尝试一下看看，暂时没空验证

```js
parser:
  - reg: '^.*$'
    code: |
      module.exports.parse = (raw, { yaml }) => {
        const rawObj = yaml.parse(raw)
        const groups = []
        const rules = []
        return yaml.stringify({ ...rawObj, 'proxy-groups': groups, rules })
      } 

  - reg: '^.*$'
  # 订阅的处理是按照从上到下依次能匹配到的去处理
    code: |
      module.exports.parse = async (raw, { yaml }) => {
        let rawObj = yaml.parse(raw);
        rawObj['proxies'].forEach(proxy => {
            proxy['name'] = proxy['name'].replace(/HONGKONG/ig, 'HK'); //i指忽略大小写， g指全局搜索
        });
        return yaml.stringify(rawObj);
      };

  - reg: '^.*$'
  # yaml 同样是一种处理，所以和 code 要同处时需要加一个匹配器
    yaml: 
```

**Comment by Soizzer** [comment]
> 尝试一下看看，暂时没空验证
> 
> ```js
> parser:
>   - reg: '^.*$'
>     code: |
>       module.exports.parse = (raw, { yaml }) => {
>         const rawObj = yaml.parse(raw)
>         const groups = []
>         const rules = []
>         return yaml.stringify({ ...rawObj, 'proxy-groups': groups, rules })
>       } 
> 
>   - reg: '^.*$'
>   # 订阅的处理是按照从上到下依次能匹配到的去处理
>     code: |
>       module.exports.parse = async (raw, { yaml }) => {
>         let rawObj = yaml.parse(raw);
>         rawObj['proxies'].forEach(proxy => {
>             proxy['name'] = proxy['name'].replace(/HONGKONG/ig, 'HK'); //i指忽略大小写， g指全局搜索
>         });
>         return yaml.stringify(rawObj);
>       };
> 
>   - reg: '^.*$'
>   # yaml 同样是一种处理，所以和 code 要同处时需要加一个匹配器
>     yaml: 
> ```

经测试，本段代码可以完美使用！！！
超级感谢yi-Xu大神！！！！
完美解决我的全部问题！！！！

**Comment by Soizzer** [comment]
> 尝试一下看看，暂时没空验证
> 
> ```js
> parser:
>   - reg: '^.*$'
>     code: |
>       module.exports.parse = (raw, { yaml }) => {
>         const rawObj = yaml.parse(raw)
>         const groups = []
>         const rules = []
>         return yaml.stringify({ ...rawObj, 'proxy-groups': groups, rules })
>       } 
> 
>   - reg: '^.*$'
>   # 订阅的处理是按照从上到下依次能匹配到的去处理
>     code: |
>       module.exports.parse = async (raw, { yaml }) => {
>         let rawObj = yaml.parse(raw);
>         rawObj['proxies'].forEach(proxy => {
>             proxy['name'] = proxy['name'].replace(/HONGKONG/ig, 'HK'); //i指忽略大小写， g指全局搜索
>         });
>         return yaml.stringify(rawObj);
>       };
> 
>   - reg: '^.*$'
>   # yaml 同样是一种处理，所以和 code 要同处时需要加一个匹配器
>     yaml: 
> ```

现在有了大神们的代码，使用CFW感觉如虎添翼，强迫症表示终于解决了每次更新订阅时还要手动修改配置的苦恼！！
谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢！！！哈哈哈！！！
