### ISSUE TITLE
[Bug]: 最新0.19.16配置加载配置文件出错

### ISSUE THREAD

**Issue by haitau** [Fndroid/clash_for_windows_pkg#2942]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

v 0.19.16

### 操作系统

Windows x64

### 系统版本

window 11

### 问题描述

从0.19.15升级到 0.19.16 ，发现之前能加载的.yml文件现在不能加载。
报错：Error:The : indicator must be at most 1024 chars after the start of an implicit block mapping key 

重新下载0.19.15 版本安装后，能正常加载.yml配置文件。

.yml文件也有在 https://jsonformatter.org/yaml-formatter  这里做验证, 一切正常。

### 复现步骤

重新安装0.19.16后，继续报同样的错误。
安装回 0.19.15，又能正常加载同样的.yml配置文件

### 日志文件

日志文件没有记录配置文件载入时的错误。所有的日志已经搜索过。

### 其他补充

报错信息里面有行号，行号开始的地方内容如下：
proxies:
  - name: 'xxxxxxxxxxxxxxx'
    type: ss
    server: xxxxxxxxxxxxxxxxxxxxxxxxxx
    port: 111111
    cipher: aes-256-gcm
    password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    udp: true

**Comment by yi-Xu-0100** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/2940#issuecomment-1105915068

**Comment by haitau** [comment]
确实是注释太长的原因。去掉注释后就正常了
