### ISSUE TITLE
[Bug]: 不管以任何方式更新 CFW，tun 模式将在更新完成后失效

### ISSUE THREAD

**Issue by QuentinHsu** [Fndroid/clash_for_windows_pkg#2943]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.16

### 操作系统

macOS arm64(M1,M1*)

### 系统版本

macOS 12.3.1

### 问题描述

不管以任何方式更新 CFW，tun 模式将在更新完成后失效
重启 app，无效。
重启系统，恢复正常。

### 复现步骤

不管以任何方式更新 CFW，tun 模式将在更新完成后失效
重启 app，无效
重启系统，恢复正常

100% 复现

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

我不知道这是否是个 bug，还是说应该发生的事情而导致体验不好。
希望开发者可以解决下，或者给个说明。

**Comment by yi-Xu-0100** [comment]
有无更新后，的日志。

**Comment by QuentinHsu** [comment]
> 

很抱歉，当前又无法复现了。😂
在我发帖之前，有复现过 3 次以上后我才提的 issue。是从 0.19.15 升级到 0.19.16 出现的。

假如后续又有复现我再贴日志过来

非常抱歉。您当前可以关闭这个 issue 了

**Comment by QuentinHsu** [comment]
> 有无更新后，的日志。


很抱歉，当前又无法复现了。😂
在我发帖之前，有复现过 3 次以上后我才提的 issue。是从 0.19.15 升级到 0.19.16 出现的。

假如后续又有复现我再贴日志过来

非常抱歉。您当前可以关闭这个 issue 了
