### ISSUE TITLE
[Bug]: 复制订阅以后告诉我不可用，要以文本编辑，且没有网络连接

### ISSUE THREAD

**Issue by MaoLiMaoLi** [Fndroid/clash_for_windows_pkg#2944]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.7

### 操作系统

Windows x64

### 系统版本

18363.959

### 问题描述

![1](https://user-images.githubusercontent.com/104190984/164624539-2f639889-473b-4a56-b143-bd05becfe78c.png)

### 复现步骤

复制订阅

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
去 home directory 删除 profiles 重启软件试试，或者完全删除 home directory 重启软件试试

**Comment by Fndroid** [comment]
编辑文本，里面dns enable改成false

**Comment by MaoLiMaoLi** [comment]
> 编辑文本，里面的dns enable改成false

太牛了兄弟，解决了！！！！感谢！！！！
