### ISSUE TITLE
[Bug]: 0.19.9之后UI界面无法显示数字

### ISSUE THREAD

**Issue by vicumi** [Fndroid/clash_for_windows_pkg#2947]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.10-0.19.16

### 操作系统

Windows x64

### 系统版本

Windows 10 21H2

### 问题描述

更新之后，界面上凡是应该出现数字的地方均为空白，如图所示。图中只展示General标签页的，实际上其他标签页也是同样的现象。
![clash issue](https://user-images.githubusercontent.com/46856601/164879524-7f4b7efe-c647-4364-860a-ba7d767f5f61.png)

### 复现步骤

从0.19.10更新到目前版本（截至0.19.16）都有这样的问题。重新安装回0.19.9版本后问题消失。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Wrandz** [comment]
这好像是你的字体问题，有相关的issue的你搜索一下

**Comment by Fndroid** [comment]
font family设置了不存在的字体

**Comment by vicumi** [comment]
谢谢，设置好了font family之后解决了。
