### ISSUE TITLE
[Feature Request]: Mac 功能建议

### ISSUE THREAD

**Issue by Bob-ju** [Fndroid/clash_for_windows_pkg#2949]
### 功能描述

建议 打开和关闭代理 对应不同的 icon ，用于直观反应软件运行状态。
可以是颜色或者造型区别，类似 Windows 蓝橙两色图标。
谢谢。

**Comment by Fndroid** [comment]
<img width="51" alt="image" src="https://user-images.githubusercontent.com/16091562/165009962-83c5ce63-fa3b-43b9-a4f1-3c8ab1e022bd.png">
这个S不明显吗

**Comment by Bob-ju** [comment]
感谢回复，我找到了
