### ISSUE TITLE
adguard和cfw同时开启，网速很卡顿，关闭任意一个软件就不卡了。

### ISSUE THREAD

**Issue by lujiannan888** [Fndroid/clash_for_windows_pkg#295]

**Comment by Fndroid** [comment]
@lujiannan888 这个问题涉及比较多的东西，目前建议关闭adguard主程序，使用浏览器插件替代

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.

**Comment by ous50** [comment]
我在adguard那边开了个issue，链接如下，大家可以过来看看AdguardTeam/AdguardFilters#62089
