### ISSUE TITLE
[Feature Request]: 广告问题

### ISSUE THREAD

**Issue by saiyajiang** [Fndroid/clash_for_windows_pkg#2953]
### 功能描述

许久没更新，更新后发现有广告，只能接受可选的赞助，不能接受强制的广告。
至少希望能够有广告和无广告两个版本。
另外问一下，哪个版本是无广告的最新版本。

**Comment by yi-Xu-0100** [comment]
印象中一直有，或者你直接不升级应该就可以了。暂时现在版本应该就这样。

**Comment by AkariiinMKII** [comment]
请问可选的赞助是指什么？

**Comment by saiyajiang** [comment]
二话不说直接关单还行……被金钱蒙蔽了双眼。


> 请问`可选的赞助`是指什么？

可以是二维码或者赞助网站

**Comment by Fndroid** [comment]
您是以前赞助过吗？如果现在这个模式您不满意的话，可以把赞助记录和收款码私信给我邮箱，我可以给您退回的。

**Comment by AkariiinMKII** [comment]
> 二话不说直接关单还行……被金钱蒙蔽了双眼。
> 
> 
> > 请问`可选的赞助`是指什么？
> 
> 可以是二维码或者赞助网站

请问您是想通过付费去广告吗
