### ISSUE TITLE
[Bug]: 配置文件在0.19.16版本下报错

### ISSUE THREAD

**Issue by qingchuwudi** [Fndroid/clash_for_windows_pkg#2954]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.16

### 操作系统

Windows x64

### 系统版本

10

### 问题描述

从 v0.19.15 升级到 v0.19.16 后，启用配置的时候软件报错，如下图：

![image](https://user-images.githubusercontent.com/10055337/165005663-9888fec1-b04f-4dbd-826d-70fb4f967465.png)

> 重新用 v0.19.15覆盖后恢复正常，升级到 v0.19.16 还是有问题。

### 复现步骤

覆盖安装或直接安装 v0.19.16 版本的软件。

### 日志文件

<details><summary>logs</summary><p>

```
软件无法正常运行，没有日志
```

</p></details>

**Comment by yi-Xu-0100** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/2940#issuecomment-1105915068
