### ISSUE TITLE
clash_for_windows在玩游戏时非常卡顿

### ISSUE THREAD

**Issue by BBENG-DADA** [Fndroid/clash_for_windows_pkg#296]
clash_for_windows启动后，在检测延时的时候，所有节点的延时都高于其他的代理软件所测试出来的延时，而且clash_for_windows启动节点后节点上网，游戏的速度慢于其他的代理软件，尤其是游戏速度，相同的节点在其他软件上使用游戏，上网速度远高于clash_for_windows，我想问一下是我设置有问题还是软件本身就带有这个缺陷。

**Comment by Fndroid** [comment]
直接用其他软件就好了

**Comment by BBENG-DADA** [comment]
> 直接用其他软件就好了

V2ray这种连接方式除了CLASH还有什么可用的软件呢？

**Comment by BBENG-DADA** [comment]
> 直接用其他软件就好了

我没有说你软件不好的意思，只是问问你有没有解决方法

**Comment by Fndroid** [comment]
> 游戏的速度慢于其他的代理软件，尤其是游戏速度，相同的节点在其他软件上使用游戏，上网速度远高于clash_for_windows

按照这个描述，我觉得就没必要要Clash for Windows了，游戏当然延迟最重要

**Comment by BBENG-DADA** [comment]
> > 游戏的速度慢于其他的代理软件，尤其是游戏速度，相同的节点在其他软件上使用游戏，上网速度远高于clash_for_windows
> 
> 按照这个描述，我觉得就没必要用Clash for Windows了，游戏当然延迟最重要

谢谢了，我知道了
