### ISSUE TITLE
UWP应用telegram

### ISSUE THREAD

**Issue by wclmgcd** [Fndroid/clash_for_windows_pkg#297]
如要使用需要代理的UWP应用  大部分UWP应用都没有开放代理设置功能（目前仅发现Telegram有），此时要让UWP使用代理就必须打开系统代理，同时需要在General界面点击EnableLoopback.exe并为需要代理的UWP应用解除回环代理限制.
（同时需要在General界面点击EnableLoopback.exe并为需要代理的UWP应用解除回环代理限制.），这个方式在openclash上如何设置？

**Comment by Fndroid** [comment]
openclash不需要设置这个

**Comment by wclmgcd** [comment]
关键是Telegram无法连接，只有设置代理才可以

**Comment by Fndroid** [comment]
@wclmgcd 只能说和loopback无关，不能连的问题建议发到openclash对应的repo里
