### ISSUE TITLE
[Feature Request]: 安卓版有隔多少分钟更新订阅的功能，但是电脑版似乎没有，希望加上这个功能

### ISSUE THREAD

**Issue by redstoneleo** [Fndroid/clash_for_windows_pkg#2970]
### 功能描述

安卓版有隔多少分钟更新订阅的功能，但是电脑版似乎没有，希望加上这个功能

**Comment by ruiy326** [comment]
你想设定多少分钟？可以设定1小时。点击Profiles标签，右键你的订阅，Settings，Update Interval。
![图片](https://user-images.githubusercontent.com/102410131/165984813-b0479387-63fe-4ccb-8afd-66a59776c00a.png)
