### ISSUE TITLE
想知道这个跟原版有什么区别

### ISSUE THREAD

**Issue by NianBroken** [Fndroid/clash_for_windows_pkg#2971]
我自己用的一直是这个
但是今天发现这是一个二次修改的库
而且star比原版要高
所以这个跟原版的区别是什么？

**Comment by yi-Xu-0100** [comment]
你指的原版是？

**Comment by NianBroken** [comment]
> 

https://github.com/Dreamacro/clash

**Comment by NianBroken** [comment]
> 你指的原版是？

https://github.com/Dreamacro/clash

**Comment by yi-Xu-0100** [comment]
@NianBroken 看该仓库的 readme，这个用的 clash premium 作为核心，提供可视化界面和一些方便的配置更新与修改。

**Comment by RangXuan** [comment]
Clash的可视化版本
