### ISSUE TITLE
[Bug]: 订阅链接用不了，但在v2rayN里可以用

### ISSUE THREAD

**Issue by redstoneleo** [Fndroid/clash_for_windows_pkg#2972]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.15

### 操作系统

Windows x64

### 系统版本

11

### 问题描述

这个订阅链接用不了，但在v2rayN里可以用
https://raw.fastgit.org/mianfeifq/share/main/data202204.txt

### 复现步骤

如上

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by kusiru** [comment]
转换一下

**Comment by redstoneleo** [comment]
> 转换一下

主要还是软件要支持一下才方便

**Comment by yi-Xu-0100** [comment]
core issue: <https://github.com/Dreamacro/clash/issues>
