### ISSUE TITLE
[Bug]: Slient Start 无效？

### ISSUE THREAD

**Issue by dayue1984** [Fndroid/clash_for_windows_pkg#2977]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.17

### 操作系统

Windows x64

### 系统版本

Windows 11

### 问题描述

开启Slient Start，启动电脑，仍然会弹出主窗口，需要手动关闭

### 复现步骤

开启Slient Start和Lightweight Mode，开机自动隐藏实效

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
预期行为，lightweight mode需要GUI先进行一次通信

**Comment by dayue1984** [comment]
谢谢解答，不知道有无可能在通讯后自动关闭gui，谢谢

**Comment by yi-Xu-0100** [comment]
@dayue1984 https://github.com/Fndroid/clash_for_windows_pkg/issues/2888#issuecomment-1094483218
