### ISSUE TITLE
如何关闭core secret？

### ISSUE THREAD

**Issue by sakray233** [Fndroid/clash_for_windows_pkg#2978]
打开core secret后只有更新密钥/密码的选项，请问如何删除这个密钥？
<img width="638" alt="屏幕截图 2022-05-03 175550" src="https://user-images.githubusercontent.com/42052199/166434772-9c4517c8-af44-4b85-9672-adb330a57770.png">

**Comment by Fndroid** [comment]
编辑Home Directory里config.yaml删掉secrwt字段

**Comment by Harry2336** [comment]
> 打开core secret后只有更新密钥/密码的选项，请问如何删除这个密钥？ <img alt="屏幕截图 2022-05-03 175550" width="638" src="https://user-images.githubusercontent.com/42052199/166434772-9c4517c8-af44-4b85-9672-adb330a57770.png">

请问这个core secret有什么用呢？

**Comment by yi-Xu-0100** [comment]
@Harry2336 防止远程控制clash等潜在安全隐患。
