### ISSUE TITLE
开启迅雷后，clash代理全部timeout，关闭迅雷后一切正常

### ISSUE THREAD

**Issue by dc165015** [Fndroid/clash_for_windows_pkg#299]
请问是否有方法配置rule，让迅雷绕行？

**Comment by singledoggy** [comment]
手册里有教怎么让网易云绕行，你改下就正则匹配就好

**Comment by ikarosu** [comment]
同样问题

**Comment by 4SM** [comment]
关闭clash的系统代理。使用proxifier来代理系统程序。

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
