### ISSUE TITLE
[Bug]: win11 升级到最新版本后节点timeout

### ISSUE THREAD

**Issue by zhengjun131461** [Fndroid/clash_for_windows_pkg#2994]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.17

### 操作系统

Windows x64

### 系统版本

win11 22000.652

### 问题描述

所以订阅节点全都显示timeout
![1a6b1c9246c2bdadf169d51fc06d492](https://user-images.githubusercontent.com/43834414/167259749-9b7fe7de-bc95-445e-9c2c-3ee259977fb8.jpg)

### 复现步骤

新安装的，配置文件已经删除过了

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
可能是vmess的格式有问题，core有更新

**Comment by neoblackxt** [comment]
因为vmess协议更新了，去掉了旧版支持（ws-path和ws-headers等），机场没跟着更新协议。
[v1.9.0更新日志](https://github.com/Dreamacro/clash/releases/tag/v1.9.0)
[v1.9.0去掉了VMess配置文件旧格式的兼容是基于何种考虑？](https://github.com/Dreamacro/clash/issues/1951) 
[配置文件格式](https://github.com/Dreamacro/clash/wiki/configuration)
解决方案：1. 降级clash core到 [v1.8.0](https://github.com/Dreamacro/clash/releases/tag/v1.8.0) 到对应文件 `Clash.for.Windows-xx.xx.xx-win\resources\static\files\win\x64\clash-win64.exe`
2. 换支持新vmess协议的机场
3. 给机场主发工单（不存在的，机场主技术菜的一笔好嘛）

**Comment by zhengjun131461** [comment]
谢谢啦！就是规则更新导致的，已经解决了

**Comment by alien-wxr** [comment]
> 因为vmess协议配置格式更新了，去掉了旧版兼容性支持（ws-path和ws-headers等），机场没跟着更新格式。 [clash v1.9.0更新日志](https://github.com/Dreamacro/clash/releases/tag/v1.9.0) [clash v1.9.0去掉了VMess配置文件旧格式的兼容是基于何种考虑？](https://github.com/Dreamacro/clash/issues/1951) [clash 配置文件格式](https://github.com/Dreamacro/clash/wiki/configuration) 解决方案：
> 
> 1. 降级clash到 [v1.8.0](https://github.com/Dreamacro/clash/releases/tag/v1.8.0) 到对应文件 `Clash.for.Windows-xx.xx.xx-win\resources\static\files\win\x64\clash-win64.exe`
> 2. 换支持新vmess协议配置格式的机场或更换其他受支持协议
> 3. 给机场主发工单（不存在的，机场主技术菜的一笔好嘛）
> 4. 使用规则转换 [parser（进阶）](https://docs.cfw.lbyczf.com/contents/parser.html)、[diff（进阶）](https://docs.cfw.lbyczf.com/contents/diff.html)、[在线订阅转换器（傻瓜、隐私安全性未知）](https://sub-web.netlify.app/)

请问macOS降级clash的对应文件路径是什么？

**Comment by alien-wxr** [comment]
> > 因为vmess协议配置格式更新了，去掉了旧版兼容性支持（ws-path和ws-headers等），机场没跟着更新格式。 [clash v1.9.0更新日志](https://github.com/Dreamacro/clash/releases/tag/v1.9.0) [clash v1.9.0去掉了VMess配置文件旧格式的兼容是基于何种考虑？](https://github.com/Dreamacro/clash/issues/1951) [clash 配置文件格式](https://github.com/Dreamacro/clash/wiki/configuration) 解决方案：
> > 
> > 1. 降级clash到 [v1.8.0](https://github.com/Dreamacro/clash/releases/tag/v1.8.0) 到对应文件 `Clash.for.Windows-xx.xx.xx-win\resources\static\files\win\x64\clash-win64.exe`
> > 2. 换支持新vmess协议配置格式的机场或更换其他受支持协议
> > 3. 给机场主发工单（不存在的，机场主技术菜的一笔好嘛）
> > 4. 使用规则转换 [parser（进阶）](https://docs.cfw.lbyczf.com/contents/parser.html)、[diff（进阶）](https://docs.cfw.lbyczf.com/contents/diff.html)、[在线订阅转换器（傻瓜、隐私安全性未知）](https://sub-web.netlify.app/)
> 
> 请问macOS降级clash的对应文件路径是什么？

用了 @neoblackxt 补充的parser，已经不需要降级了。

**Comment by yeminny** [comment]
经过以下方法，测试有效。
将：\Clash for Windows\resources\static\files\win\x64\clash-win64.exe 
右键--兼容性--以管理员身份运行些程序，这一项打勾，
经过几天测试，订阅timeout没有出问题了。
