### ISSUE TITLE
[Bug]: iphone连接电脑clash的热点后，能翻墙，但抖音、懂车帝app提示网络错误

### ISSUE THREAD

**Issue by ck4ever** [Fndroid/clash_for_windows_pkg#2999]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.17

### 操作系统

Windows x64

### 系统版本

ios15.4.1

### 问题描述

 iphone连接电脑clash的热点后，能翻墙，但抖音、懂车帝app提示网络错误

### 复现步骤

 iphone连接电脑clash的热点后，能翻墙，但抖音、懂车帝app提示网络错误

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
提示什么网络错误，截图出来看看，或者看看日志

**Comment by ck4ever** [comment]
> 提示什么网络错误，截图出来看看，或者看看日志

![4ed3588ad399f743526b8b7c9970b80](https://user-images.githubusercontent.com/49236379/167784646-749e8103-7bc9-4f25-a668-0a2a70addddf.jpg)
![4cf8289263775748fd3a988ec22e4ca](https://user-images.githubusercontent.com/49236379/167784700-ffe96fa0-70a6-400b-84cd-7fdf9d4dd618.jpg)

**Comment by ck4ever** [comment]
> 

![image](https://user-images.githubusercontent.com/49236379/167787496-5139503f-5bd6-4f04-8dfe-08b57021d42d.png)
刷懂车帝的app，查的log对应的应该是这个

**Comment by yi-Xu-0100** [comment]
不清楚，要不 bypass 试试

**Comment by YirunFantasy** [comment]
![20220513_083720.jpg](https://user-images.githubusercontent.com/88962428/168188897-e5f042f7-e586-490c-9226-aac6ba5f9b86.jpg)需要打开对应APP的“本地网络”开关

**Comment by ck4ever** [comment]
> ![20220513_083720.jpg](https://user-images.githubusercontent.com/88962428/168188897-e5f042f7-e586-490c-9226-aac6ba5f9b86.jpg)需要打开对应APP的“本地网络”开关

nice，按照这个方法搞定了，多谢~！！
