### ISSUE TITLE
开机自启动

### ISSUE THREAD

**Issue by oscargong** [Fndroid/clash_for_windows_pkg#3]
你好，可以增加开机自启动功能吗？

**Comment by Fndroid** [comment]
自己设置一下也很简单的吧

**Comment by oscargong** [comment]
可以设置，但是 `clash_for_windows_pkg` 启动后不会自动设置系统代理，还需要手动最小化到托盘。

还是内建这个功能到话会更方便一些…

**Comment by lvhe19880210** [comment]
> 可以设置，但是 `clash_for_windows_pkg` 启动后不会自动设置系统代理，还需要手动最小化到托盘。
> 
> 还是内建这个功能到话会更方便一些…

系统代理的话最新版已经有了system proxy的选项了啊， 在框上打钩就行了

**Comment by rosuH** [comment]
@oscargong  简单的添加程序自启动。

https://www.howtogeek.com/208224/how-to-add-programs-files-and-folders-to-system-startup-in-windows-8.1/

**Comment by Fndroid** [comment]
最新版本已加入
