### ISSUE TITLE
使用cfw 0.4.3+版本ssh走代理无法正常连接

### ISSUE THREAD

**Issue by ZvonimirSun** [Fndroid/clash_for_windows_pkg#30]
使用xshell设置代理，连接到本地代理正常，再连接到远程就会被断开。看capture显示代理了我到远程主机22端口的连接，但是不能正常连接，``Connection closed by foreign host.``。使用其他代理软件，如v2rayn,ssr等没有出现这种情况。话说我是不是应该去clash那边提。

**Comment by ZvonimirSun** [comment]
抱歉，似乎不是clash的问题，和ufw有关，通过代理就不能正常连接，没开ufw就正常。

**Comment by ZvonimirSun** [comment]
经过测试，根据规则直连的ssh可以正常连接，走代理的就会连接失败，无论是通过域名的ssh连接，还是直接ip的ssh。

**Comment by Fndroid** [comment]
试了一下没什么问题
![image](https://user-images.githubusercontent.com/16091562/49263067-fc902b80-f483-11e8-8345-23a9fc5e2d5d.png)

**Comment by KngEast** [comment]
我这里没问题

**Comment by MutingLeng** [comment]
MobaXterm Personal 10.6 + cfw v 0.5.3 ，同样无法使用 cfw 的 socks5 或 http 代理连接 SSH 。已经确定代理服务器、端口正确无误。

作为对比，telegram + cfw v 0.5.3 + 同样的代理服务器 + cfw 的 socks5 或者 http 代理，可以正常使用telegram，但是，MobaXterm Personal 10.6 使用 cfw 的 socks5 或者 http 代理，就无法正常连接。

下图为 MobaXterm Personal 10.6 使用 cfw 的 socks5 或者 http 代理连接 SSH 的结果：

![image](https://user-images.githubusercontent.com/30371006/49559993-b9363100-f94b-11e8-815e-272a44f7c650.png)

而 cfw 的 Capture 中也确实显示了目标 IP 已经通过 cfw 走了代理连接：


![image](https://user-images.githubusercontent.com/30371006/49560237-87719a00-f94c-11e8-8deb-f19662ac8410.png)

而其他的客户端如v2rayN，则正常。

**Comment by Fndroid** [comment]
> MobaXterm Personal 10.6 + cfw v 0.5.3 ，同样无法使用 cfw 的 socks5 或 http 代理连接 SSH 。已经确定代理服务器、端口正确无误。
> 
> 作为对比，telegram + cfw v 0.5.3 + 同样的代理服务器 + cfw 的 socks5 或者 http 代理，可以正常使用telegram，但是，MobaXterm Personal 10.6 使用 cfw 的 socks5 或者 http 代理，就无法正常连接。
> 
> 下图为 MobaXterm Personal 10.6 使用 cfw 的 socks5 或者 http 代理连接 SSH 的结果：
> 
> ![image](https://user-images.githubusercontent.com/30371006/49559993-b9363100-f94b-11e8-815e-272a44f7c650.png)
> 
> 而 cfw 的 Capture 中也确实显示了目标 IP 已经通过 cfw 走了代理连接：
> 
> 
> ![image](https://user-images.githubusercontent.com/30371006/49560237-87719a00-f94c-11e8-8deb-f19662ac8410.png)
> 
> 而其他的客户端如v2rayN，则正常。

我晚点再测测看

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/65
