### ISSUE TITLE
[Feature Request]: 使用全局代理之后,  访问一些国内的网站速度很慢.  看过文档了不知道怎么解决, 不知道本来就是这样, 还是我哪里没有设置对.

### ISSUE THREAD

**Issue by yangS97** [Fndroid/clash_for_windows_pkg#3005]
### 功能描述

使用全局代理之后,  访问一些国内的网站速度很慢.  看过文档了不知道怎么解决, 不知道本来就是这样, 还是我哪里没有设置对.

**Comment by kingforme** [comment]
使用Rule进行分流

**Comment by yi-Xu-0100** [comment]
![图片](https://user-images.githubusercontent.com/25523606/168190546-1fa5f104-3722-4296-aa36-9afc10eea270.png)

这里切换一下

**Comment by yangS97** [comment]
好的谢谢
