### ISSUE TITLE
[Feature Request]:  需要支持Win7 32位系统的版本!

### ISSUE THREAD

**Issue by wlp7662973** [Fndroid/clash_for_windows_pkg#3007]
### 功能描述

需要支持Win7 32位系统的版本!

### 其他内容

需要支持Win7 32位系统的版本!

**Comment by LightAPIs** [comment]
Releases 里有 `ia32.exe` 的安装包可以用呀。。。

**Comment by NIXEU1** [comment]
目录里有32位的，不会用建议移步vpn
