### ISSUE TITLE
[Bug]: M1芯片的MBP 在parallels desktop下Ubuntu 下载clash 执行./cfw报错

### ISSUE THREAD

**Issue by CrushIndex** [Fndroid/clash_for_windows_pkg#3008]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.17

### 操作系统

Linux

### 系统版本

M1 Max芯片下用parallels desktop装的 Ubuntu 20.04.2

### 问题描述

M1 Max芯片的MBP 在parallels desktop下Ubuntu 下载clash 执行./cfw报错
![image](https://user-images.githubusercontent.com/105451035/168279072-2e197596-78be-46c7-9e91-5c3c7497b71b.png)

### 复现步骤

下载完对应linux的安装包后 解压  然后执行./cfw就会这样

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
因为不支持arm的linux

**Comment by CrushIndex** [comment]
> 因为不支持arm的linux

请问后续会支持吗？

**Comment by GainSury** [comment]
今天支持了，可以关闭了
