### ISSUE TITLE
[Feature Request]: 托盘右键节点显示太多了，影响使用体验

### ISSUE THREAD

**Issue by DustinWin** [Fndroid/clash_for_windows_pkg#3009]
### 功能描述

已经更新到 v0.19.18，发现托盘右键可以选择节点了，这点很方便。但随之的问题也显现，当节点很多时，菜单也被拉长了（上下拉满），如图：
![QQ截图20220514000255](https://user-images.githubusercontent.com/45238096/168322948-cfc1b71f-bd9a-45b5-9220-2d49575624ef.png)
希望能优化一下。

**Comment by LightAPIs** [comment]
功能本身是不错，但是我的策略组实在太多，现在点开托盘右键菜单直接爆炸，太长辣。🤦

**Comment by yorunning** [comment]
deepin托盘闪烁，没法用  面板都打不开，其他Linux不清楚情况

**Comment by Fndroid** [comment]
@yorunning 上个版本界面能打开么

**Comment by Fndroid** [comment]
下个版本会考虑加个开关

**Comment by DustinWin** [comment]
> 下个版本会考虑加个开关

好的，谢谢！

**Comment by baraja** [comment]
> deepin托盘闪烁，没法用 面板都打不开，其他Linux不清楚情况

ubuntu 22.04同样，还造成鼠标卡顿，我以为是系统坏了。。。，退回上一版本解决问题

**Comment by yorunning** [comment]
> @yorunning 上个版本界面能打开么

上个版本没问题

**Comment by Yiwei-Liao** [comment]
> 下个版本会考虑加个开关
希望可以直接放进一个子菜单里，搞一个节点配置之类的然后选中后展开选项

**Comment by LightAPIs** [comment]
> 下个版本会考虑加个开关

或许可以考虑放至二级菜单当中。

**Comment by lingfeng01** [comment]
确实太多了

**Comment by din1028** [comment]
或者改成单行显示

**Comment by JeffXephon** [comment]
多谢持续更新~
其实不离开当前窗口，右键切换Mode比较常用，更新之后跑到好远的上方去了。。。
真的需要切换节点，也是打开Dashboard直观快捷，右键菜单里是全文字+首字母排列+多层级菜单，很难找到目标。

**Comment by wannaw-i** [comment]
这个设计是真反人类

**Comment by bojinge** [comment]
强迫症的极度修改
<img width="132" alt="CAP" src="https://user-images.githubusercontent.com/96866062/168468227-6bcdb9f5-7d52-4d93-83f6-d18261e0b3fe.png">

**Comment by XinSSS** [comment]
> 下个版本会考虑加个开关

是否可以考虑下托盘里的顺序和代理里面的顺序保持一致呢? 目前看上去像是根据字符顺序排序的

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases

**Comment by Alc-z** [comment]
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/25759539/294d0f47-2e05-41d7-8de6-4205c54869df)
linux版本有proxy selector吗?

**Comment by 592360560** [comment]
> 感觉挺好的啊，又不会超过屏幕点不了，点不了才有问题吧。

大家都说不好用，应该听劝啊。如果我需要频繁开关系统代理呢，每次都要拉到顶部才能切换，真的很麻烦
