### ISSUE TITLE
提个建议，添加portable版本识别

### ISSUE THREAD

**Issue by Mosney** [Fndroid/clash_for_windows_pkg#301]
给7z版本的程序加一个标识，检测更新的更新链接指向Clash.for.Windows-x.x.x.7z而不是安装版exe。

**Comment by Fndroid** [comment]
1. exe也只是一个压缩包，可以用winrar直接解压的
2. 如果在软件里创建了对应的文件启动了便携模式，那么检查更新是会下载7z的

**Comment by Mosney** [comment]
2 是指在哪里开启？

**Comment by Brightmbsh** [comment]
> 2 是指在哪里开启？

https://docs.cfw.lbyczf.com/contents/7z.html

**Comment by Mosney** [comment]
> > 2 是指在哪里开启？
> 
> https://docs.cfw.lbyczf.com/contents/7z.html

清楚了 感谢
