### ISSUE TITLE
[Bug]: win64无法安装最新版本

### ISSUE THREAD

**Issue by liwen211** [Fndroid/clash_for_windows_pkg#3013]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

Clash.for.Windows-0.19.17-arm64-win

### 操作系统

Windows x64

### 系统版本

Windows 10 家庭中文版

### 问题描述

开发者你好。我是第一次试图安装clash win版，我的系统版本是windows 10的64版本，但我在试图安装最新版的arm64客户端时显示 我的电脑无法安装该软件。
请问是否有解决办法呢？

### 复现步骤

解压压缩包，打开解压后的文件夹，直接点击安装exe文件。电脑弹出提示“无法安装”。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
@liwen211 

![图片](https://user-images.githubusercontent.com/25523606/168410895-98eb916e-cd9b-4a38-9196-df5234583df2.png)
用这些就行，便携或者安装版，你的是 amd64
