### ISSUE TITLE
[Bug]: logs 显示了数量巨多的由 CFW 发起的127.0.0.1连接

### ISSUE THREAD

**Issue by JanWhite** [Fndroid/clash_for_windows_pkg#3015]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.18

### 操作系统

Windows x64

### 系统版本

Windows 11 21H2

### 问题描述

升级到 0.19.18版本后 logs 显示了数量巨多的由 CFW 发起的 127.0.0.1 连接 半个小时内大概有5K+的记录 而且按道理也不该匹配final（？）
回退 0.19.17 后正常
系统代理模式 fake-ip 

### 复现步骤

正常使用即可发生

### 日志文件

<details><summary>logs</summary><p>

```
time="2022-05-14T20:18:57+08:00" level=debug msg="[Process] 127.0.0.1 from process \\Device\\HarddiskVolume3\\Users\\xxx\\Program\\Clash for Windows\\Clash for Windows.exe"
time="2022-05-14T20:18:57+08:00" level=debug msg="[Process] 127.0.0.1 from process \\Device\\HarddiskVolume3\\Users\\xxx\\Program\\Clash for Windows\\Clash for Windows.exe"
time="2022-05-14T20:18:57+08:00" level=info msg="[TCP] 127.0.0.1:29015 --> 127.0.0.1:28582 match Match() using Final[xxx]"
time="2022-05-14T20:18:57+08:00" level=info msg="[TCP] 127.0.0.1:29016 --> 127.0.0.1:28582 match Match() using Final[xxx]"

```

</p></details>

### 其他补充

<details><summary>rules</summary><p>

```
  - GEOIP,LAN,DIRECT,no-resolve
  - GEOIP,CN,DIRECT
  - MATCH,Final

```

</p></details>

**Comment by liverMxu** [comment]
我一样有这个问题，发现它每秒刷新一次，同时状态栏的图标获取当前节点情况也是，应该是类似功能导致的

**Comment by Fndroid** [comment]
127.0.0.1的请求不可能会进入clash，除非自己改过路由

**Comment by SplitGemini** [comment]
cfw向内核的请求也走代理了
