### ISSUE TITLE
如何在WIN7系统下使用CFW的TAP功能

### ISSUE THREAD

**Issue by BBENG-DADA** [Fndroid/clash_for_windows_pkg#302]
在WIN7系统下如何打开TAP功能使UWP应用走代理呢？我看见CFW有TAP相关选项，但是配套的工具“UWP LOOPBACK”在WIN7系统下无法使用，请问除了使用“UWP LOOPBACK”还有其他方法能让UWP应用在WIN7系统下走代理吗？

**Comment by GainSury** [comment]
uwp应用在Windows 7上不能用，只能在Windows下运行

**Comment by Fndroid** [comment]
WIN7不能用UWP吧

TAP和UWP设置也没有关系

**Comment by BBENG-DADA** [comment]
> WIN7不能用UWP吧
> 
> TAP和UWP设置也没有关系

看来是我没搞清楚，我想说的是如何让CFW代理掉WIN7系统的全部流量

**Comment by BBENG-DADA** [comment]
> WIN7不能用UWP吧
> 
> TAP和UWP设置也没有关系

因为CFW只代理了我浏览器的流量并没有代理我计算机上的所有流量，就像SSTAP那样

**Comment by BBENG-DADA** [comment]
因为CFW只代理了我浏览器的流量并没有代理我计算机上的所有流量，我想让CFW代理我计算机上的所有流量，就像SSTAP那样

**Comment by GreatFireWall** [comment]
> 因为CFW只代理了我浏览器的流量并没有代理我计算机上的所有流量，我想让CFW代理我计算机上的所有流量，就像SSTAP那样

Win2Socks 可以代理所有 TCP UDP 流量, 不过要付费.

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
