### ISSUE TITLE
[Feature Request]: 0.19.18提供的任务栏代理选择器加入开关功能

### ISSUE THREAD

**Issue by ralphwong** [Fndroid/clash_for_windows_pkg#3024]
### 功能描述

由于rule中的可选项很多，导致任务栏右键菜单过长，是否可以添加一个开关选择关闭此项功能，谢谢。

**Comment by ddzzkunye** [comment]
Duplicate of #3009

**Comment by mikayao** [comment]
确实，右键打开一大堆没用的，比之前不方便太多了

**Comment by fanzh365** [comment]
放二级菜单里好一些吧，更新完吓坏了

**Comment by ddzzkunye** [comment]
> 可以在profiles中使用groups给节点分组
> ```
> proxy-groups:
>   -
>     name: '****'
>     type: select
>     proxies:
>       - '****'
> ```
> 这样右键菜单就不会很长了。
> 具体怎么写可以参照[文档](https://github.com/Dreamacro/clash/wiki/configuration)。
> 
> ***
> 如果担心更新节点后group会消失，
> 可以考虑使用`配置文件预处理`或`Diff处理`，
> 具体请参考[文档](https://docs.cfw.lbyczf.com/contents/parser.html#%E7%89%88%E6%9C%AC%E8%A6%81%E6%B1%82)


就是有一堆节点组才很长啊

**Comment by ddzzkunye** [comment]
> ### 功能描述
> 由于rule中的可选项很多，导致任务栏右键菜单过长，是否可以添加一个开关选择关闭此项功能，谢谢。
> 
> ### 其他内容
> _No response_

这个issue可以关了吧

**Comment by ralphwong** [comment]
0.19.19更新后关闭issue
