### ISSUE TITLE
关闭clash不能正常上网

### ISSUE THREAD

**Issue by ierroric** [Fndroid/clash_for_windows_pkg#303]
请问如何设置，才能在关闭clash的时候，上网时不出现代理服务器出现问题。
我并不想一直开着clash上网。

**Comment by Fndroid** [comment]
右键任务栏图标，选择Quit

**Comment by ierroric** [comment]
啊，我找到解决办法了，把计算机代理设置的手动设置代理 ，关掉就行了

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
