### ISSUE TITLE
[Bug]: Every SingleReboot  computer,the port changed

### ISSUE THREAD

**Issue by MemoriseXuxu** [Fndroid/clash_for_windows_pkg#3034]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.18

### 操作系统

Windows x64

### 系统版本

21H2 LTSC

### 问题描述

Every SingleReboot  computer,the port changed. However,this issue comes up in recently version.

### 复现步骤

The PC reboots and the port is chaged randomly.

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
![图片](https://user-images.githubusercontent.com/25523606/169193900-c138acfa-f9b8-48d0-8726-cd31b085677d.png)

**Comment by MemoriseXuxu** [comment]
Thanks!!! It works! My bad
Besh wishes!
