### ISSUE TITLE
Clash for windows 0.8.5，URL导入配置失败

### ISSUE THREAD

**Issue by Lightmaring** [Fndroid/clash_for_windows_pkg#304]
![QQ截图20191203173108](https://user-images.githubusercontent.com/58465530/70038222-e1a24b00-15f2-11ea-9754-a45dbf436dc8.png)

大神，我用URL导入配置显示失败，请问这是什么原因呢？

**Comment by Fndroid** [comment]
浏览器能打开这个地址么

**Comment by Lightmaring** [comment]
嗯嗯，可以打开

**Comment by Lightmaring** [comment]
> 浏览器能打开这个地址么



> 浏览器能打开这个地址么

请问是哪个地址呢？URL吗？

**Comment by Lightmaring** [comment]
> 浏览器能打开这个地址么

我试了下浏览器打开URL，下载了一个YAML文件，现在可以用啦，谢谢大神！

**Comment by SilenceJoyson** [comment]
我也是一样不能导入  打开URL后怎么下载出YAML文件啊？

**Comment by Fndroid** [comment]
不能直接在软件里下载的可能：
1. 地址被阻隔，无法直连访问，CFW程序默认不走代理
2. 耗时超过20s

**Comment by Lightmaring** [comment]
> 我也是一样不能导入 打开URL后怎么下载出YAML文件啊？

我是将URL粘贴至chrome，然后就自动弹出下载框了

**Comment by Lightmaring** [comment]
> 不能直接在软件里下载的可能：
> 
> 1. 地址被阻隔，无法直连访问，CFW程序默认不走代理
> 2. 耗时超过20s

嗯嗯，我这可能是地址被阻隔的原因

**Comment by 2020guo** [comment]
> > 我也是一样不能介绍：URL后怎么下载出YAML文件啊？
> 
> 我是将URL粘贴至chrome，然后就自动放入下载框了

前面情况一致，URL下载文件后还是下载失败，这个怎么解决？

**Comment by Lightmaring** [comment]
正常来说，将URL粘贴至chrome之后，会弹出一个下载框，下载一个YAML文件，然后把这个文件拖动到clash配置就好了，我是这样解决的。

 

发件人: noreply@github.com <noreply@github.com> 代表 2020guo
发送时间: 2020年6月16日 8:40
收件人: Fndroid/clash_for_windows_pkg <clash_for_windows_pkg@noreply.github.com>
抄送: Lightmaring <shenhao_sh163@163.com>; Author <author@noreply.github.com>
主题: Re: [Fndroid/clash_for_windows_pkg] Clash for windows 0.8.5，URL导入配置失败 (#304)

 

我也是一样不能介绍：URL后怎么下载出YAML文件啊？

我是将URL粘贴至chrome，然后就自动放入下载框了

前面情况一致，URL下载文件后还是下载失败，这个怎么解决？

**Comment by charlie-iu** [comment]
将URL粘到浏览器，没有自动下载，而是自动解析内容，显示了一个html的内容，怎么办
