### ISSUE TITLE
[Feature Request]: 希望Request Logs支持复制域名

### ISSUE THREAD

**Issue by ZachQin** [Fndroid/clash_for_windows_pkg#3040]
### 功能描述

希望Request Logs支持一键复制域名
因为经常需要根据Logs在Profiles里添加新的域名规则，现在只能手动输入不是很方便。
谢谢🙏

**Comment by Fndroid** [comment]
你点一下对应的log不就复制了么？

**Comment by Wrandz** [comment]
话说，我总是感觉那个connections和logs重复了

**Comment by ZachQin** [comment]
> 你点一下对应的log不就复制了么？

原来是这样😂学到了
