### ISSUE TITLE
[Feature Request]: 快捷菜单规则过多时显示不友好

### ISSUE THREAD

**Issue by Arifisar** [Fndroid/clash_for_windows_pkg#3042]
### 功能描述

![image](https://user-images.githubusercontent.com/66297144/169464637-19aecd48-5814-4816-a947-0efdbf4f93cd.png)
希望能加一个选项控制是否在快捷菜单显示所有规则

**Comment by yi-Xu-0100** [comment]
![图片](https://user-images.githubusercontent.com/25523606/169482846-ff891fba-760f-45e4-8164-b228e825c90d.png)
