### ISSUE TITLE
[Bug]: Parsers执行错误？

### ISSUE THREAD

**Issue by chensrnile** [Fndroid/clash_for_windows_pkg#3043]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.19

### 操作系统

Windows x64

### 系统版本

Win11专业版  21H2

### 问题描述

Parsers里输入两个订阅地址以及规则（见补充），不知道我的写法是否完全正确但是在Profile选项卡右键相应订阅均能显示当前有效Parsers。更新订阅后分别查看两个订阅中正在生效的规则，发现写在上面一行的订阅实际并没有加载我补充的规则，但是将第一行复制到第二行下面再看自己的规则又生效了

另外将-url+订阅 更改为- reg: ^.*$可以使用    请问是我规则格式写错了吗还是parser有bug

### 复现步骤

只要是放在第一行的订阅 parser在profile里显示生效但是在rules里并没有生效

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>
[2022-05-20-162315.log](https://github.com/Fndroid/clash_for_windows_pkg/files/8738143/2022-05-20-162315.log)

### 其他补充

![parsers](https://user-images.githubusercontent.com/53550688/169498478-1ac5e8ba-538d-4d7e-8c14-213443b961f9.png)

**Comment by yi-Xu-0100** [comment]
看不到 parser 内容，重新传一下

**Comment by Fndroid** [comment]
yaml格式不对

**Comment by chensrnile** [comment]
> 看不到 parser 内容，重新传一下

黑色的就是几个网站域名，会有影响吗？

**Comment by yi-Xu-0100** [comment]
![图片](https://user-images.githubusercontent.com/25523606/169625641-b30168b6-eebe-4768-972f-fd7b0c307d3f.png)

大概类似这样，一个匹配器，写一个内容。

**Comment by chensrnile** [comment]
> ![图片](https://user-images.githubusercontent.com/25523606/169625641-b30168b6-eebe-4768-972f-fd7b0c307d3f.png)
> 
> 大概类似这样，一个匹配器，写一个内容。

这样啊，那请问reg和url这两个用起来有什么区别吗

**Comment by yi-Xu-0100** [comment]
@chensrnile reg 用正则匹配，可以匹配多个配置。然后 url 只能匹配一个配置。

**Comment by chensrnile** [comment]
> @chensrnile reg 用正则匹配，可以匹配多个配置。然后 url 只能匹配一个配置。

🆗
