### ISSUE TITLE
[Bug]: 更新0.19.19后关闭窗口默认是最小化, 右下角图标显示空白,   双击无反应

### ISSUE THREAD

**Issue by chenzhihao1040728129** [Fndroid/clash_for_windows_pkg#3045]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.19

### 操作系统

Windows x64

### 系统版本

W10

### 问题描述

更新0.19.19后关闭窗口默认是最小化, 右下角图标显示空白,   双击无反应

### 复现步骤

更新0.19.18  和 0.19.19 后出现

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
settings-hide tray icon是不是开了

**Comment by AkariiinMKII** [comment]
使用的是汉化版吗？

**Comment by chenzhihao1040728129** [comment]
> 设置-隐藏托盘图标不是未查看

没有,  已经卸载过, 删除C磁盘中 clash文件夹,  重装了, 一样,

**Comment by chenzhihao1040728129** [comment]
> 

官方版

**Comment by chenzhihao1040728129** [comment]
> 使用的是汉化版吗？

官方版本

**Comment by chenzhihao1040728129** [comment]
> settings-hide tray icon是不是开了
Windows 10 家庭中文版    版本号:  21H2      操作系统内部版本: 19044.1706
 对应的视频:   

https://user-images.githubusercontent.com/49114216/169637556-b5dbfa3e-1a68-4abb-bc84-3f4062de1b0f.mp4

**Comment by Fndroid** [comment]
是一下开关hide tray icon

**Comment by chenzhihao1040728129** [comment]
> 



> 是一下开关hide tray icon

试了, 没有效果, 还是一样右下显示空白,   窗口关闭了还保留在任务栏

**Comment by HIM0GB** [comment]
要不然试试在任务管理器中重新启动Windows资源管理器，之前我也出过类似问题。
