### ISSUE TITLE
[Bug]: 托盘无图标

### ISSUE THREAD

**Issue by wonchong** [Fndroid/clash_for_windows_pkg#3046]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.19

### 操作系统

Windows x64

### 系统版本

Windows11 23H2 Dev 预览版 Build 25120.1010

### 问题描述

![image](https://user-images.githubusercontent.com/82252714/169618108-2cc97f2f-2fce-4338-8867-0e0b89750377.png)
托盘无图标

### 复现步骤

装个系统。
更新0.19.19.

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by wonchong** [comment]
最新系统下载 ： https://geek-wonchong.lanzouj.com/b0cx99ssf 密码:QuTMDBaiDu

**Comment by github-h** [comment]
建议是先把汉化版扬了用原版测试
然后用官方原版系统 不要找什么奇怪的精简版
https://next.itellyou.cn/

**Comment by wonchong** [comment]
> 建议是先把汉化版扬了用原版测试 然后用官方原版系统 不要找什么奇怪的精简版 https://next.itellyou.cn/
![image](https://user-images.githubusercontent.com/82252714/169715615-58b687e3-b2be-4aeb-b86e-46322dd3b12f.png)
这其实是Dev的锅，不信你自己试。
