### ISSUE TITLE
节点过多显示不方便

### ISSUE THREAD

**Issue by wannaw-i** [Fndroid/clash_for_windows_pkg#3047]
我想知道任务栏小猫咪右键后会显示代理组，如果节点多的话特别不友好，能不能出个功能可以自行关闭那个代理组的显示

**Comment by yi-Xu-0100** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/3042#issuecomment-1132603439

**Comment by Yiwei-Liao** [comment]
希望能放进子菜单，节点太多导致菜单太长
