### ISSUE TITLE
开发对普通人更友好的功能

### ISSUE THREAD

**Issue by myckjx** [Fndroid/clash_for_windows_pkg#3053]
BT、迅雷是一般人都常用的软件，如何设置Clash不代理这类流量？一些人告诉我要编辑规则，门槛太高了！建议增加个【只代理常规端口】选项，或者学安卓版可以设置哪些软件不走代理。

**Comment by kingforme** [comment]
- PROCESS-NAME,Thunder.exe
  - PROCESS-NAME,ThunderVIP.exe

**Comment by listenerri** [comment]
建议换个思路，在 ClashForWindows（后文简称 CFW） 中设置不启用系统代理（托盘图标上右键可以看到此选项），这样设置后默认情况下所有流量都不会走 CFW，然后在个别你需要走代理的软件里设置代理地址和端口，一般情况下普通用户也就给浏览器设置一下，操作也很简单
