### ISSUE TITLE
[Bug]: windows系统自启动问题

### ISSUE THREAD

**Issue by K0zero** [Fndroid/clash_for_windows_pkg#3055]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

019.019

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

在设置了开机自启之后，弹出了这个界面。没有直接自启动。
只能不选择使用什么应用开启。之后自行点击快捷键打开应用程序。
在3天前出现了这个问题，也就是5.21日左右，之前使用正常，没有出现此问题
![image](https://user-images.githubusercontent.com/57054783/169869680-a12c82c2-ce8e-430e-8cfc-c48781c90936.png)

### 复现步骤

一开始使用的是018版本，但是出现此问题，更新了019版本，仍有此问题

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
居然没说打开啥文件。。。

**Comment by K0zero** [comment]
对，我也很奇怪，因为其他的开机自启应用都开启了，只有clash没有启动，所以我很确定这个弹出的窗口就是clash应用文件用什么打开（

**Comment by yi-Xu-0100** [comment]
看看启动页面，路径是不是有问题

**Comment by K0zero** [comment]
> 

从哪里看

**Comment by yi-Xu-0100** [comment]
任务管理器的启动标签页

**Comment by yi-Xu-0100** [comment]
![图片](https://user-images.githubusercontent.com/25523606/170153927-9c462a8e-1cae-4867-aafc-3e3793879f0e.png)

看看这里是否正常，不正常的话，百度注册表修改启动项，找到对应的，看看值

**Comment by K0zero** [comment]
恢复正常了，我发现我电脑上同时有安装版本和绿色免安装版本，可能导致了自启动冲突。
感谢您提供的帮助！
