### ISSUE TITLE
[Bug]: 节点配置文件中密码为0开头的字符串parse报错

### ISSUE THREAD

**Issue by xingwen7** [Fndroid/clash_for_windows_pkg#3057]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.19

### 操作系统

Windows x64

### 系统版本

Windows 10

### 问题描述

节点配置文件中的代理服务器密码为0开头的字符串时，app提示 'password' expected type 'string', got unconvertible type 'float64

### 复现步骤

1. 节点配置文件中加入：
proxies: 
    - {name: 🇨🇳 台湾08, server: 61.220.179.26, port: 4433, type: ss, cipher: aes-256-gcm, password: 03378e208106}
 2. 切换至该配置文件
 3. 出现报错

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
yaml解析器优先将字符串解析为float，如果需要指定为string，需要用双引号包裹起来
