### ISSUE TITLE
[Bug]: Mac 退出软件后不会修改回代理，导致无法上网

### ISSUE THREAD

**Issue by hello-wy** [Fndroid/clash_for_windows_pkg#3059]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

1.93.1.1

### 操作系统

macOS amd64(Intel)

### 系统版本

12。1

### 问题描述

退出软件后，刷新网页，提示页面加载失败

### 复现步骤

退出软件

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
1.93.1.1？
