### ISSUE TITLE
[Feature Request]: Suggestion on supporting naiveproxy  protocol

### ISSUE THREAD

**Issue by supermangithu** [Fndroid/clash_for_windows_pkg#3062]
### 功能描述

Suggestion on supporting naiveproxy  protocol!
Clash for Windows support  Vmess，clash ，ssr...  .etc protocol,hope develpoer can add the support for naiveproxy  protocol if it is properly.
Thanks in  advance!

**Comment by yi-Xu-0100** [comment]
core issue: <https://github.com/Dreamacro/clash/issues>

**Comment by yi-Xu-0100** [comment]
I think CFW only need supports some protocols supported by clash core. If CFW does the things clash core has been doing, it is putting the cart before the horse. 🙊

**Comment by Fndroid** [comment]
clash core issue, refer: https://github.com/Dreamacro/clash/issues
