### ISSUE TITLE
最新版本的clash提示无法在我的电脑上运行 ，可能是因为版本的原因

### ISSUE THREAD

**Issue by liangyus** [Fndroid/clash_for_windows_pkg#3064]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.19

### 操作系统

Windows x64

### 系统版本

Windows 11 Insider Preview 22621.1 (ni_release)

### 问题描述

打开clash for Windows 时一直提示此版本无法在你的电脑上运行，请咨询软件开发者
图片如链接所示(https://user-images.githubusercontent.com/101518223/170311309-9d0d0469-07c2-44f7-9c40-e3ccc7f007b5.png)

### 复现步骤

下载之后打开，打开即提示此信息，管理员打开也不行
下载版本如图所示(https://user-images.githubusercontent.com/101518223/170312055-f0d31c64-4b7e-4732-a739-b6afca3a00f2.png)

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
用 ia32 的试试

**Comment by bestwinc** [comment]
你解决了吗，我和你一样的问题，最新的两个版本都是提示无法运行

**Comment by liangyus** [comment]
你好，解决了 ，你可以下载ia32的试下，可以使用，我的电脑可以运行


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fndroid/clash_for_windows_pkg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月27日(星期五) 晚上6:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fndroid/clash_for_windows_pkg] 最新版本的clash提示无法在我的电脑上运行 ，可能是因为版本的原因 (Issue #3064)





 
你解决了吗，我和你一样的问题，最新的两个版本都是提示无法运行

**Comment by liangyus** [comment]
已解决，谢谢

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fndroid/clash_for_windows_pkg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月26日(星期四) 上午8:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fndroid/clash_for_windows_pkg] 最新版本的clash提示无法在我的电脑上运行 ，可能是因为版本的原因 (Issue #3064)





 
用 ia32 的试试

**Comment by Ealsen** [comment]
谢谢，很有用

**Comment by ASuzuhA** [comment]
现在是2023年的4月3号，现在windows版本是22h2，下载的是最近的版本，但是电脑上显示无法在该版本下运行，该如何解决？

**Comment by wangguijiepedeval** [comment]
ia32可以

**Comment by xioushiw** [comment]
> 

请问一下ia32是什么呀

**Comment by liangyus** [comment]
指的是Windows 32位 版本，一个版本不行就选择不同的多试试
