### ISSUE TITLE
[Feature Request]: 希望CFW加入设置多端口分配的功能

### ISSUE THREAD

**Issue by ImAmelie** [Fndroid/clash_for_windows_pkg#3065]
### 功能描述

现在的CFW是根据网址或IP来分配具体的proxy的。
我希望proxy能直接绑定到监听端口，也就是我有 10000 和 10001 两个端口，我希望 10000 能绑定到美国结点， 10001 能绑定到香港结点。
请问目前CFW能做到这个功能吗，如果不能，有没有考虑加入此功能呢？
当然，只是提案。

**Comment by yi-Xu-0100** [comment]
core issue: <https://github.com/Dreamacro/clash/issues>

**Comment by Fndroid** [comment]
如果是要给不同应用设置不同端口来实现应用级别规则，完全可以用PROCESS-NAME规则

**Comment by ImAmelie** [comment]
> 如果是要给不同应用设置不同端口来实现应用级别规则，完全可以用PROCESS-NAME规则

@Fndroid CFW好像没有那这个PROCESS-NAME规则只能手动编写了吧？

**Comment by yi-Xu-0100** [comment]
parser,diff 等操作来给配置增加自定义规则。

https://docs.cfw.lbyczf.com/contents/parser.html

https://docs.cfw.lbyczf.com/contents/diff.html

https://lancellc.gitbook.io/clash/clash-config-file/rules/process-based-rule
