### ISSUE TITLE
[Bug]:  win10 无法启动

### ISSUE THREAD

**Issue by martin-1120** [Fndroid/clash_for_windows_pkg#3066]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

Clash.for.Windows-0.19.19-arm64-win

### 操作系统

Windows x64

### 系统版本

Clash.for.Windows-0.19.19-arm64-win

### 问题描述

win10下，软件不能运行
![image](https://user-images.githubusercontent.com/5887140/170401915-e402e7bb-d407-4691-9ee6-f7d3a873f1d2.png)

### 复现步骤

![image](https://user-images.githubusercontent.com/5887140/170401907-0e45470c-adb4-4d96-9158-895cd58b196d.png)

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
试试这些？

![图片](https://user-images.githubusercontent.com/25523606/170403275-7eebf463-8bca-4793-9c71-508219cf991e.png)

**Comment by martin-1120** [comment]
Clash.for.Windows-0.19.19-ia32-win 下载了这个版本就可以了

**Comment by martin-1120** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
