### ISSUE TITLE
[Bug]: 无法切换配置到此文件 

### ISSUE THREAD

**Issue by yyhil** [Fndroid/clash_for_windows_pkg#3068]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.19

### 操作系统

Windows x64

### 系统版本

Windows10 19077.1706

### 问题描述

无法切换到此配置文件
yaml：unmarshal errors：
line 1484：cannot unmarshal!! map into string

### 复现步骤

每次打开电脑后打开clash会没有节点，点击更新配置就会显示这个

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yyhil** [comment]
![mmexport1653479269513](https://user-images.githubusercontent.com/106291387/170406349-c4faa78e-18c8-4bb5-a3ab-e6852bc4de99.png)

**Comment by pdxxxxx** [comment]
怎么解决的啊

**Comment by NonsKate** [comment]
有大佬知道怎么解决吗

**Comment by ASLy123** [comment]
我看到贴吧里说把  enhanced-mode: redir-host 改成 enhanced-mode: fake-ip  就可以了
