### ISSUE TITLE
锁定代理服务器的功能有可能实现吗

### ISSUE THREAD

**Issue by singledoggy** [Fndroid/clash_for_windows_pkg#307]
win10
我下了Process Monitor试了，发现会自动打开关闭代理的包括微信和一些奇怪东西
试着用组策略锁定代理，想的是锁定了的话只要开着软件的时候不随便断掉就好
结果打开了锁定代理却不能锁定，试着换了几个管理员账号也不行
能增加锁定代理服务器的功能就好了
emm,或者像那些奇怪的软件一样，连不上就把代理重新打开一次

![
5(VC3_M4XV_72682@$DXEAB](https://user-images.githubusercontent.com/44222677/70085267-d844cd00-164a-11ea-8551-9552c53cb89b.png)

**Comment by singledoggy** [comment]
使用process monitor 监测是什么修改了注册表种的proxy enable选项，我因此解决了部分问题。这不是clash的原因，是一些奇怪的软件为了保证可以一直长期连接成功设置的，firefox浏览器会自动关闭，微信和qq有时候会自动打开。

**Comment by singledoggy** [comment]
![图片](https://user-images.githubusercontent.com/44222677/70118584-52a13b80-16a3-11ea-9de2-013f69d77bce.png)

**Comment by Meeeeow** [comment]
这些东西应该都不会修改代理设置，微信不使用系统内置的代理，QQ是应用内实现的选项，Firefox 只会读取不会修改系统代理，可以看看是不是应用有被第三方注入

**Comment by singledoggy** [comment]
> 
> 
> 这些东西应该都不会修改代理设置，微信不使用系统内置的代理，QQ是应用内实现的选项，Firefox 只会读取不会修改系统代理，可以看看是不是应用有被第三方注入
火狐卸载重装了，关闭了所有的addon，清理的应该算干净，关键是明明组策略禁止修改代理还是可以改。

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/312

**Comment by CPCer** [comment]
建议像 #312 里提到的那样，用注册表权限控制
