### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by coco456** [Fndroid/clash_for_windows_pkg#3070]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.19

### 操作系统

Linux

### 系统版本

manjaro kde 

### 问题描述

cannot check for updates:Error:net::ERR_NETWORK_CHANGED at SimpleURLLoaderWrapper.<anonymous>(electron/js2c/brower_init.js:105:6536)
at SimpleURLLoaderWrapper.emit(event.js:315:20)

### 复现步骤

![photo_2022-05-26_13-06-15](https://user-images.githubusercontent.com/42911402/170434230-a1c13fc7-b471-4b54-83a3-9d71817da41a.jpg)

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

某天重启后弹出这个，然后所有vmess节点都用不了 ，只有ss,Trojan节点可以用。

**Comment by Fndroid** [comment]
上游问题
