### ISSUE TITLE
[Feature Request]: 关机后如何让CFW自动关闭并关闭全局代理？

### ISSUE THREAD

**Issue by LiJT** [Fndroid/clash_for_windows_pkg#3072]
### 功能描述

因为CFW默认的自启动优先级不够而且速度也不够快，我如果把cfw的开机自启动和全局代理都打开了的话，每次开机都要输入steam的密码账号以及每周都要看到msi afterburner的更新提示，就非常烦。初步排查以后，发现是如果上次关机没有关闭clash的全局代理，下次开机时直到cfw启动前的这一小段窗口，很多软件因为挂着系统代理无法上网（比如steam），他们就不会自动登入。

我现在使用的是win自带的计划任务让clash延时启动，但是现在仍然不能解决关机的同时关闭cfw的问题，请求大大答疑解惑，还有什么更好的方式？

我尝试了https://github.com/Fndroid/clash_for_windows_pkg/issues/1102 这个方法，但是没有用，而且我没有找到计划任务能够识别关机程序。。。

**Comment by Fndroid** [comment]
settings里system proxy改成pac不就行了

**Comment by LiJT** [comment]
> 

谢谢大大，确实，目前是最优解，配合计划任务
