### ISSUE TITLE
[Bug]: 触摸屏问题

### ISSUE THREAD

**Issue by Xeloan** [Fndroid/clash_for_windows_pkg#3075]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

最新版

### 操作系统

Windows x64

### 系统版本

windows 11 beta 22621.1 机型：surface pro 7

### 问题描述

主界面打开以后，原来在0.19.17中，触摸右上角关闭，或最小化，正常没问题。但是，在最近两个版本中，触摸按这两个按钮几乎没反应。

### 复现步骤

![Screenshot 2022-05-29 203858](https://user-images.githubusercontent.com/105624127/170868931-f0dfe89c-4adf-4e2f-b2be-d9e1fe02a656.png)

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
最近换成了electron自带的原生按钮了，有问题的话可能要等上游修复

**Comment by YexuanXiao** [comment]
应该是这个issue：https://github.com/electron/electron/issues/34364

**Comment by Xeloan** [comment]
解决了，26版
