### ISSUE TITLE
因 ftp 链接访问的问题，对 cfw-bypass 与 bypass 感到很困惑

### ISSUE THREAD

**Issue by saytesnake** [Fndroid/clash_for_windows_pkg#3076]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.11

### 操作系统

Windows x64

### 系统版本

10

### 问题描述

可能我都没想到会将 Clash 运用在生产环境。

在客户的内网环境，写好配置文件后，代理运行一切正常，结果客户这边反馈，一个上古时代的 ftp 服务器（Windows 2003）的链接打不开了，关闭 Clash 之后，就正常。

随即在设置 - 系统代理，类型改为 HTTP（原为 PAC，忘了当时为何配置这个），bypass 照抄一下 cfw-bypass 的，就好了。

### 复现步骤

Google 了一番，仅发现了一个 2021 年的反馈，

https://github.com/Dreamacro/clash/issues/445

我刚刚还提问了一下。

可能是版本问题，实践了一下，实际上已经不需要过滤 ftp 的关键词了。

cfw-bypass 里面的配置是这样的，

```cfw-bypass:
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - 192.167.*
  - <local>
 ```
ftp 服务器的地址是 192.167.92.1:8888，链接是 ftp://192.167.92.1:8888/xxx.jpg。

情况是：
1、CFW 开启时是无法打开也无法下载；
2、系统代理切为 HTTP，修改了 bypass，与 cfw-bypass 一致，ftp 链接可以正常打开，也可以下载；
3、指定协议不知道是啥，我开启了；

官方文档上，没找到相关的说明或解释，不知道啥原因。

**Comment by yi-Xu-0100** [comment]
cfw-bypass 已不再支持，由 CFW 内部设置 bypass 支持，原理是修改系统代理的设置部分字段。

**Comment by saytesnake** [comment]
> cfw-bypass 已不再支持，由 CFW 内部设置 bypass 支持，原理是修改系统代理的设置部分字段。

感谢回复，可能 99% 用 Clash 的都是为了科学上网，网上的各路资料比较杂乱，也有时间上的版本差异，还真不知道 cfw-bypass 已不再支持。
