### ISSUE TITLE
[Feature Request]: 希望增加开机自启动时不显示主界面的功能和修改图标的功能

### ISSUE THREAD

**Issue by koreyzen** [Fndroid/clash_for_windows_pkg#3078]
### 功能描述

开机自启动后不显示主界面，从而使用户无感使用。增加修改图标作为个性化设置。

**Comment by fooooxxxx** [comment]
`Settings`里有一个`Slient Start`,勾选后启动不会自动显示主页面

**Comment by dolores824** [comment]
可以在`setting`的`Appearance`里修改图标
