### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by BeyondYourself** [Fndroid/clash_for_windows_pkg#3080]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.19

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

使用一段时间后就会出现下面这个可疑病毒怎么回事

### 复现步骤

使用一段时间后就会出现下面这个可疑病毒怎么回事

### 日志文件

![image](https://user-images.githubusercontent.com/12640462/171102338-0f524932-ffce-4584-821f-7e53b4b46102.png)

**Comment by BeyondYourself** [comment]
使用360会出现这样的问题，之前使用其他clash版本没有出现这样的问题

**Comment by yi-Xu-0100** [comment]
我觉得得问问tencent……

**Comment by BeyondYourself** [comment]
已经删除了，不知道了

**Comment by wwxghh** [comment]
建议你换个杀毒软件😇

**Comment by BeyondYourself** [comment]
> 建议你换个杀毒软件😇

额（︶︿︶）=凸

**Comment by Fndroid** [comment]
360问题
