### ISSUE TITLE
[Bug]: start with linux 无效

### ISSUE THREAD

**Issue by ss8688** [Fndroid/clash_for_windows_pkg#3083]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.19

### 操作系统

Linux

### 系统版本

raspberry pi os arm64

### 问题描述

start with linux无效

### 复现步骤

开启start with linux 但是无效

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

难道clash需要放在特定的目录?

**Comment by Fndroid** [comment]
应该是desktop文件exe路径有空格问题，下个版本修复

**Comment by paras-zomby** [comment]
保证可执行文件路径没有空格，再重新设置一次start with linux就能用了

**Comment by ss8688** [comment]
已解决，路径不能有空格
