### ISSUE TITLE
[Feature Request]: 可以为clash  for win加上（自定义）热键功能

### ISSUE THREAD

**Issue by 1638276310** [Fndroid/clash_for_windows_pkg#3084]
### 功能描述

可以为clash  for win加上（自定义）热键功能，比如按下ctrl+F3开启/关闭 代理，按下ctrrl+F4上下切换“global/rule/direct/scripts” ， 按下CTRL+F5上下 切换节点 按下ctrl+F6是刷新yaml ，热键可以自定义，按照用户的习惯来设置，因为我自己就需要的开启或者关闭代理，来保证每个网址或者某个应用内置的功能可以正常访问到。比如我需要Google的时候按下快捷键就开启代理了，用完之后随手一按快捷键就 关闭代理了 ，不影响其他应用的正常使用，因为 某些网站是没有解析到外国ip的，就造成了404

**Comment by jabobian** [comment]
能否增加一下 打开系统代理和关闭系统代理的热键？

**Comment by jabobian** [comment]
或者显示系统托盘右键菜单也可以。可以方便的查看系统代理的热键。

**Comment by yi-Xu-0100** [comment]
@jabobian 
![image](https://user-images.githubusercontent.com/25523606/209101502-7eda20c5-a66c-4fa3-bc4b-f2d71c1b2ca5.png)
