### ISSUE TITLE
下载节点链接的时候总是报错，换了好几个也是这样，卸载软件重装也不行

### ISSUE THREAD

**Issue by LYChen0808** [Fndroid/clash_for_windows_pkg#3086]
不知道为什么我这个， 下载节点链接的时候总是报错（提示：下载配置失效，HTTP返回状态码404），换了好几个也是这样，卸载软件重装也不行

**Comment by yi-Xu-0100** [comment]
404 说明节点链接不存在，不可访问

**Comment by LYChen0808** [comment]
> 404 说明节点链接不存在，不可访问

谢谢
