### ISSUE TITLE
[求助]: 全局模式可以访问外网, 但规则模式不行

### ISSUE THREAD

**Issue by 1situzj** [Fndroid/clash_for_windows_pkg#3087]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.19

### 操作系统

Windows x64

### 系统版本

Win10 LTSC

### 问题描述

1. 在路由器 clash 上，全节点可用

2. 在 clash for windows 上，大部分节点显示超时。
 
3. 在规则模式下，使用不超时的节点也无法访问外网。使用全局模式则没问题。

4. 只有该 clash 链接出现该问题，其他的没出现过这种情况。

### 复现步骤

1

### 其他补充

目前推测是 dns 解析问题，请问要如何定位与解决？

**Comment by yi-Xu-0100** [comment]
看看配置中的 dns 配置。看看日志

**Comment by itKelis** [comment]
看看log
