### ISSUE TITLE
[Bug]: TUN无法正常使用

### ISSUE THREAD

**Issue by caiciyu** [Fndroid/clash_for_windows_pkg#3088]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.19

### 操作系统

Windows x64

### 系统版本

Win10 家庭中文版

### 问题描述

已安装service mode，TUN mode为初始设定，打开TUN（system proxy和mixin都已关闭），右下角clash显示无网络连接，ipv4无网络访问权限
![0f592ca867f9d666898e838e3c398bb](https://user-images.githubusercontent.com/90396377/171587995-4832f77d-c1d5-4d56-8e1b-237c89ed7235.png)

此时电脑出现卡顿，clash-win64.exe吃了大量CPU
![8e3bcbcd7f19aebc0bb5bab9f5f3e8f](https://user-images.githubusercontent.com/90396377/171588026-230a5751-e373-45ae-9ead-434e7a440ec6.png)

同时clash的connection数量激增至20000多条，大部分为重复的connection
![8b4af3f026c2706877fdaee668f95c7](https://user-images.githubusercontent.com/90396377/171588096-99af4694-4b5a-47c3-a717-a86ae385b90f.png)

切换profile文件时出现报错
![8b453bc6a3b776a25ff0ae482be90c7](https://user-images.githubusercontent.com/90396377/171588050-6e1ce960-9cde-48a3-8f3a-355a0acf28b1.png)

前一天都正常使用，后来玩游戏的时候用来迅游加速器，加速效果不大理想便使用了迅游的网络修复，结果导致了TUN模式无法正确使用
将clash卸载重装，删除clash相关的注册表和文档，卸载重装service mode都试过，均无效

### 复现步骤

安装service mode，关闭system  proxy，打开TUN mode

### 其他补充

clash基本信息
![b39791490d368007955cd20fc09101d](https://user-images.githubusercontent.com/90396377/171587479-ee4ea2ce-c5d2-4cd3-b2bd-6d4ce257ffef.png)
TUN mode setting
![fb2d79e99f29dfeb6f7a687699528dc](https://user-images.githubusercontent.com/90396377/171587499-18b64ed7-c5a8-433a-bd01-ee4e06871425.png)

**Comment by caiciyu** [comment]
日志文件
[2022-06-02-034134.log](https://github.com/Fndroid/clash_for_windows_pkg/files/8822089/2022-06-02-034134.log)

**Comment by yi-Xu-0100** [comment]
allow lan 关掉

**Comment by caiciyu** [comment]
> allow lan 关掉

关闭了但是也没效果，而且我的wsl2的代理需要打开这个开关

**Comment by caiciyu** [comment]
再次测试了一下，发现用tap模式也不行，还是同样的问题

**Comment by Cookiekira** [comment]
我这也是一样的状况  更新到 0.19.19 后  关闭TUN Mode后无法正常代理 对节点延迟检测都为超时

**Comment by Cookiekira** [comment]
试着回退到0.19.18 和 0.19.10 还是一样的情况 
![image](https://user-images.githubusercontent.com/42908926/171618451-d4ee9dbb-4178-4a87-925a-486b210db346.png)
关闭TUN Mode以后代理还在尝试连接TUN

**Comment by Cookiekira** [comment]
> 再次测试了一下，发现用tap模式也不行，还是同样的问题
![image](https://user-images.githubusercontent.com/42908926/171622299-f9983da6-3c79-49a3-8f43-49384262ddfa.png)
在windows设置里使用网络重置以后重启，我恢复正常了。

**Comment by caiciyu** [comment]
> > 再次测试了一下，发现用tap模式也不行，还是同样的问题
> > ![image](https://user-images.githubusercontent.com/42908926/171622299-f9983da6-3c79-49a3-8f43-49384262ddfa.png)
> > 在windows设置里使用网络重置以后重启，我恢复正常了。

已解决，谢谢你！

**Comment by Fndroid** [comment]
关闭auto detect interface选项，手动设定出口网卡名

**Comment by mylovesaber** [comment]
看我测试结果，请直接下载0.19.13版本，并在设置中关闭新版本提示即可详情可见我的测试：#3096

**Comment by caiciyu** [comment]
关闭auto detect interface选项，手动设定出口网卡名
问题得到解决！

**Comment by Ichigobai** [comment]
> zerotier
 请问最后问题解决了吗 我和你问题一样 重置好了 重启又出现问题

**Comment by mylovesaber** [comment]
> > zerotier
> > 请问最后问题解决了吗 我和你问题一样 重置好了 重启又出现问题

我的问题来源于机场22端口总被人扫，所有22端口号的代理都被他们drop了，导致我这ssh软件走代理连节点一直工作不正常，关掉代理就正常了

**Comment by lengxii** [comment]
我解决了，本地网线连接 名称是以太网，一直连不上网，我把名称改成WLAN 无线 ipv4 连上了，不知道是啥原因

**Comment by cosifis** [comment]
> 关闭auto detect interface选项，手动设定出口网卡名 问题得到解决！

请问设定的出口网卡名是什么？我输入的网卡接口名称之后开启tun模式连接不上网路。

**Comment by Journalist-HK** [comment]
我遇到同样的问题，开 TUN 模式直接卡死。请问网卡名称是填 `'以太网'` 吗？

**Comment by Uc207Pr4f57t9-251** [comment]
> 

确实是的，填写你能够上网的网卡，打开适配器选项看，我是用wifi就写WLAN。

**Comment by dubai1230** [comment]
> 

我也是这么解决的。。。

**Comment by TheSixPasserby** [comment]
> > 电脑重启之后，该问题又出现了
> 
> 我重启以后也复现了，然后我把zerotier的连接断开以后莫名其妙的就好了。完全没有头绪，感觉是不能有其他虚拟网卡设备在运行。
谢谢你，我也是这样
