### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Harmonia0908** [Fndroid/clash_for_windows_pkg#3089]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.16/0.19.19

### 操作系统

Windows x64

### 系统版本

Windows11

### 问题描述

导入订阅到profile后，无法切换到该订阅，提示如下
![image](https://user-images.githubusercontent.com/23402948/171644621-ce9f1323-177a-4fba-8688-385a95a91442.png)

### 复现步骤

如问题描述

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
把配置里dns enable改成false

**Comment by Harmonia0908** [comment]
感谢 已解决
