### ISSUE TITLE
0.8.5问题反馈 - System Proxy 自动关闭

### ISSUE THREAD

**Issue by toozwu** [Fndroid/clash_for_windows_pkg#309]
General - System Proxy 的开关经常自动关闭。需要手动点一下才可以恢复。

自动关闭时打不开所有网页。

**Comment by inkss** [comment]
在这之前，提过一个反馈：[#223 代理无法关闭](https://github.com/Fndroid/clash_for_windows_pkg/issues/223)，内容大概是代理自动开启，无法关闭。

然后不知道怎么搞的，现在状态反而成了经常自动关闭，也是够无奈了。有没有什么办法能够检测到关闭/开启代理的事件，肯定是出了什么问题。

系统：`Win10 1909` ，软件版本：`V0.8.5` 

 :joy:...

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/312

**Comment by inkss** [comment]
好的 ，我监测一段时间

**Comment by thank243** [comment]
我观察到的现象是如果开其他代理软件，他就自动关闭了。比如v2rayN

**Comment by Bi9River** [comment]
请问process monitor怎么监控对应路径呀？
