### ISSUE TITLE
[Bug]: yaml: unmarshal errors:line 27:cannot unmarshal !!map into []map[string]interface {}

### ISSUE THREAD

**Issue by Alexan517** [Fndroid/clash_for_windows_pkg#3091]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.19

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

无法切换配置文件

### 复现步骤

节点导入点击配置就不可用了

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
说明配置文件格式有问题
