### ISSUE TITLE
【已解决】如果只有ssh无法走代理的话，记得把默认22端口改掉，可能节点屏蔽了

### ISSUE THREAD

**Issue by mylovesaber** [Fndroid/clash_for_windows_pkg#3096]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.14-0.19.20

### 操作系统

Windows x64

### 系统版本

win11（这跟操作系统版本无关）

### 问题描述

tun mode一旦开启，所有第三方软件使用代理的方式就无法连接网络，比如ssh无法连接服务器

我是隔壁 dler cloud 用户，手里有他们基于0.19.13版本定制的安装包，某天我发现那定制软件提示有新版了，更新完成后是0.19.19版本，更新完后重启过电脑，发现ssh的clash代理127.0.0.1:7890完全失效，所有走这个代理的服务器均无法打开，彻底卸载0.19.19版本后重装0.19.13版本定制clash并做好之前一样的设置，结果ssh客户端走代理一切正常，咨询 dler cloud 客服，被告知来这寻求帮助，随后我测试了从0.19.13-0.19.20也就是6月4日能下载到的最新版本发现通用版clash也是0.19.13版本一切正常，0.19.14-0.19.20这所有的版本只要开了tun mode就会导致ssh走代理连不上服务器

### 复现步骤

假设系统内没有任何clash安装过的痕迹，从最新版本0.19.20依次往低版本测试（重启系统和不重启系统都测试了）：
1. 全局安装clash后打开，导入订阅链接，在proxies中指定一个可用的节点
2. 点击 General，打开这个界面除了Mixin和TAP Device以外的所有选项（其实只开启System Proxy、Allow LAN和TUN Mode即可）
3. 打开securecrt或xshell之类的ssh客户端，添加代理，socks5，127.0.0.1:7890
4. 打开一个设置了走代理的服务器的连接会话窗口，此时会立马断开链接，关掉TUN Mode会正常进入
5. 用revo uninstaller彻底卸载clash，然后手动删掉C:\Users\用户名\.config\clash这个文件夹
6. 安装上一个版本的安装包，从第一点开始重复步骤

直到0.19.13才会在开启tun mode的时候让ssh正常走代理

**Comment by Fndroid** [comment]
tun mode 设置打开截图看看，我这里 putty 无法复现

**Comment by itKelis** [comment]
打开tun之后就不需要UWP Loopback了，可以试试

**Comment by FudanSE-Nick** [comment]
我这边win11 clash_v0.19.20是正常的，“使用system作为 TUN stack 时，需要在系统防火墙中将 Clash core 放行”。

**Comment by mylovesaber** [comment]
> tun mode 设置打开截图看看，我这里 putty 无法复现

<img width="477" alt="image" src="https://user-images.githubusercontent.com/36480362/172089876-2cf2a9bb-05fb-4693-9cdc-eec43ecd0b18.png">
<img width="790" alt="image" src="https://user-images.githubusercontent.com/36480362/172090129-7e460b8e-273c-4697-b4c5-852de67b9f8b.png">
<img width="503" alt="image" src="https://user-images.githubusercontent.com/36480362/172090195-d5f13189-7419-48d1-b93c-b647016ca9b8.png">
<img width="497" alt="image" src="https://user-images.githubusercontent.com/36480362/172090271-6ba8cf50-4572-4aa0-b116-145e47f923a1.png">
其实这issue发完以后13版本也没法使用了，跟版本好像关系不大，但就是tun mode一开，ssh就Connection closed.哪怕关掉后再关掉service，重启系统也都无法让ssh再连接，必须重装clash然后只开一个system proxy

**Comment by mylovesaber** [comment]
> tun mode 设置打开截图看看，我这里 putty 无法复现

<img width="464" alt="image" src="https://user-images.githubusercontent.com/36480362/172090757-c1905e83-a8d1-40d2-b271-e2e54a3f6f5c.png">

![](https://user-images.githubusercontent.com/36480362/172090757-c1905e83-a8d1-40d2-b271-e2e54a3f6f5c.png)

**Comment by mylovesaber** [comment]
> 我这边win11 clash_v0.19.20是正常的，“使用system作为 TUN stack 时，需要在系统防火墙中将 Clash core 放行”。

<img width="655" alt="image" src="https://user-images.githubusercontent.com/36480362/172091127-2cd72b12-7229-43ea-8baa-6b046e519af3.png">
你是说这两个吗？都开了吧

**Comment by FudanSE-Nick** [comment]
> > 我这边win11 clash_v0.19.20是正常的，“使用system作为 TUN stack 时，需要在系统防火墙中将 Clash core 放行”。
> 
> <img alt="image" width="655" src="https://user-images.githubusercontent.com/36480362/172091127-2cd72b12-7229-43ea-8baa-6b046e519af3.png">
> 
> 你是说这两个吗？都开了吧

你把VMware这些网卡都禁用，只留一个连网的网卡以及clash，再开一下tun mode.  估计是auto-interface的原因

**Comment by Fndroid** [comment]
auto detect interface 关掉，手动输出出口网卡名试试

**Comment by mylovesaber** [comment]
> auto detect interface 关掉，手动输出出口网卡名试试

我禁用了vmware还有hyperv中的虚拟网卡，重置了win11 22621.1网络并重启后，
用revo uninstaller pro卸载了clash包括注册表中的信息，并删除了C:\Users\用户名\.config\clash配置文件存储，
然后安装了0.19.20，
无论仅开启系统代理还是tun mode，浏览器均能上谷歌，
wsl在开启tun mode后可以通过w3m打开命令行版谷歌网页，
但xshell、putty、securecrt均无法用过socks5  127.0.0.1:7890 来连接服务器

**Comment by FudanSE-Nick** [comment]
> > auto detect interface 关掉，手动输出出口网卡名试试
> 
> 我禁用了vmware还有hyperv中的虚拟网卡，重置了win11 22621.1网络并重启后， 用revo uninstaller pro卸载了clash包括注册表中的信息，并删除了C:\Users\用户名.config\clash配置文件存储， 然后安装了0.19.20， 无论仅开启系统代理还是tun mode，浏览器均能上谷歌， wsl在开启tun mode后可以通过w3m打开命令行版谷歌网页， 但xshell、putty、securecrt均无法用过socks5 127.0.0.1:7890 来连接服务器

都用tun mode了，就不需要在putty里配置proxy了，系统所有流量会自动分流的。

**Comment by Fndroid** [comment]
有没有可能是你节点把22drop了

**Comment by mylovesaber** [comment]
> 有没有可能是你节点把22drop了

大佬牛逼果然是这个问题，我给一个服务器改了ssh端口号，然后再走代理一切正常，问了机场客服被证实有人扫端口所以做了22的限制。。。太感谢了，这毛病恶心我好多天了。。。

**Comment by raycool** [comment]
非常感谢，确实是这个问题，修改为2222就没问题。

**Comment by mylovesaber** [comment]
> 我节点没问题，就是clash必须开global模式才行吗，我开rule模式，他就走直连了。 是要在我的订阅配置文件里面自己写规则吗? <img alt="屏幕截图 2023-06-07 123936" width="400" src="https://user-images.githubusercontent.com/50540240/243919134-650696ce-9ebf-472f-9af3-60dfaa03a998.png">

如果这是你的服务器，你需要在连接服务器所用的ssh软件中设置proxy，比如xshell/securecrt之类的软件
