### ISSUE TITLE
Windows安装包 安装路径空格导致无法正确安装

### ISSUE THREAD

**Issue by LittleBlacklb** [Fndroid/clash_for_windows_pkg#3103]
# 环境
Windows 11
# 问题
我在releases里下载了 [Clash.for.Windows.Setup.0.19.20.exe](https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.19.20/Clash.for.Windows.Setup.0.19.20.exe) 以及 0.19.19作为测试 发现：
默认安装路径(个人用户 || 所有用户)的Clash目录名`Clash for Windows`有空格的情况下(可能不是这个原因 没有尝试过其他sample)安装速度特别快（所以可以判断可能并没有安装在其他文件夹）
完成安装后在目标文件夹下只有`Uninstall Clash for Windows.exe`，其可以正常运行。但是没有其他文件以及主程序。

后来我删掉了空格后解决。

**Comment by yi-Xu-0100** [comment]
不会用户名中文了吧
