### ISSUE TITLE
[Bug]: 后台一直修改windows代理设置

### ISSUE THREAD

**Issue by FocusProgram** [Fndroid/clash_for_windows_pkg#3106]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.20

### 操作系统

Windows x64

### 系统版本

11 22000.708

### 问题描述

当我退出clash_for_windows后，使用Fiddler软件时，发现clash for windows会一直篡改windows的代理设置，导致Fiddler无法正常使用

### 复现步骤

当退出clash for windows后，观察window的代理设置
![image](https://user-images.githubusercontent.com/44283663/172581390-a9816d93-8f63-4fdb-8705-15fce597cd87.png)
是否会被一直修改为Clash的代理配置

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
很奇怪，你都退出了CFW，怎么还会有CFW在用呢

**Comment by FocusProgram** [comment]
是啊，我也很纳闷为什么会一直在后台修改代理，#312 观察到的现象是
![image](https://user-images.githubusercontent.com/44283663/172586488-1c662c2a-2ffa-4556-ab6f-085d2b52f0e9.png)
有一个svchost进程一直在修改代理配置，这个跟clash有关系吗？
