### ISSUE TITLE
[Bug]: Please add support for prefix subdomain

### ISSUE THREAD

**Issue by supermangithu** [Fndroid/clash_for_windows_pkg#3109]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.20

### 操作系统

Windows x64

### 系统版本

win10 2002

### 问题描述

Bypass domain/IPnet
When setting bypass one domain and it prefix domian,
- *.xxx.com
it appears
Error:Unresolved alias(the anchor must be set before the alias): .xxx.com
for instance,
os.xxx.com
inner.xxx.com
....
many of xxx.com prefix subdomain.
add - xxx.com can not be used for bypass os.xxx.com or other prefix subdomain.
Please add support for prefix subdomain.

### 复现步骤

Bypass domain/IPnet
Edit
add
- *.xxx.com

**Comment by Fndroid** [comment]
```yaml
bypass:
  - *.xxx.com
```
