### ISSUE TITLE
AppContainer Loopback Exemption Utility这个小程序不能正常获取uwp软件列表[Bug]: 

### ISSUE THREAD

**Issue by vilau** [Fndroid/clash_for_windows_pkg#3112]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.20

### 操作系统

Windows x64

### 系统版本

21H2

### 问题描述

general 界面点击 Launch Helper ，点击refresh后无法获取uwp应用列表
如图：
[https://sm.ms/image/Lt7gVQeWIzqMT1f](url)

### 复现步骤

我不知道如何在其他计算机上重现我的问题

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
Duplicate of #2830

**Comment by tomorrowi** [comment]
遇到了同样的问题，按照提示重置防火墙显然没有作用。直接用fiddler里面好像又可以，不知道是不是这个clash自带版本问题，但是其他的机器又是正常。
