### ISSUE TITLE
TUN Mode 下如何直连某些网站？🙇

### ISSUE THREAD

**Issue by wenfangdu** [Fndroid/clash_for_windows_pkg#3116]
开启 TUN Mode 后，WSL2 可以代理出去，但是公司的内网上不了了，求教如何在 TUN Mode 下直连公司内网呢？🙇 

公司域名如：company.com

**Comment by zixuan945** [comment]
@wenfangdu 
[绕过系统代理](https://docs.cfw.lbyczf.com/contents/bypass.html#%E8%AE%BE%E7%BD%AE%E6%96%B9%E5%BC%8F)

**Comment by zixuan945** [comment]
第三种方案，参考第二种方案，DNS设置中配置DNS分流，让 company.com 使用内网提供的DNS服务器进行解析
[dns分流配置](https://github.com/Dreamacro/clash/wiki/configuration#dns:~:text=%23%20Lookup%20domains%20via%20specific%20nameservers%0A%20%20%23%20nameserver%2Dpolicy%3A%0A%20%20%23%20%20%20%27www.baidu.com%27%3A%20%27114.114.114.114%27%0A%20%20%23%20%20%20%27%2B.internal.crop.com%27%3A%20%2710.0.0.1%27)
