### ISSUE TITLE
[Bug]: TUN 模式下疯狂连接 DNS 服务器

### ISSUE THREAD

**Issue by alex3236** [Fndroid/clash_for_windows_pkg#3119]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.20

### 操作系统

Windows x64

### 系统版本

Windows 11 22H2 22621.1

### 问题描述

一打开 TUN 模式就疯狂刷日志 看上去一直在连 DNS 服务器，一下子几万个连接数。局域网连接和系统代理都为关闭状态。之前是正常的 重启了一次就这样了

### 复现步骤

-

### 日志文件

<details><summary>logs</summary><p>

```

time="2022-06-11T22:38:31+08:00" level=info msg="[UDP] 192.168.124.9:60492 --> 114.114.114.114:53 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-06-11T22:38:31+08:00" level=info msg="[UDP] 192.168.124.9:60488 --> 192.168.124.15:161 match IPCIDR(192.168.0.0/16) using DIRECT"
time="2022-06-11T22:38:31+08:00" level=info msg="[UDP] 192.168.124.9:60490 --> 114.114.114.114:53 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-06-11T22:38:31+08:00" level=info msg="[UDP] 192.168.124.9:60491 --> 114.114.114.114:53 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-06-11T22:38:31+08:00" level=info msg="[UDP] 192.168.124.9:60494 --> 114.114.114.114:53 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-06-11T22:38:31+08:00" level=info msg="[UDP] 192.168.124.9:60495 --> 114.114.114.114:53 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-06-11T22:38:31+08:00" level=info msg="[UDP] 192.168.124.9:60505 --> 114.114.114.114:53 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-06-11T22:38:31+08:00" level=info msg="[UDP] 192.168.124.9:60503 --> 192.168.124.15:161 match IPCIDR(192.168.0.0/16) using DIRECT"
time="2022-06-11T22:38:31+08:00" level=info msg="[UDP] 192.168.124.9:60497 --> 114.114.114.114:53 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-06-11T22:38:31+08:00" level=info msg="[UDP] 192.168.124.9:60498 --> 114.114.114.114:53 match GeoIP(CN) using Domestic[DIRECT]"
time="2022-06-11T22:38:31+08:00" level=info msg="[UDP] 192.168.124.9:60496 --> 114.114.114.114:53 match GeoIP(CN) using Domestic[DIRECT]" 
```

</p></details>

**Comment by cyanlink** [comment]
如果你是windows，进入控制面板看你的全部网络适配器，不能存在Cisco VPN等软件的虚拟网卡，也不能存在奇怪的“传入的连接”等等，如果存在请卸载（关闭auto detect interface并手动指定网卡是没用的）。

**Comment by Fndroid** [comment]
如果开了热点分享才出现的，[参考这个](https://docs.cfw.lbyczf.com/contents/questions.html#%E5%9C%A8-windows-%E7%B3%BB%E7%BB%9F%E4%B8%AD-tun-%E6%A8%A1%E5%BC%8F%E4%B8%8B%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8%E7%83%AD%E7%82%B9%E5%88%86%E4%BA%AB%E5%8A%9F%E8%83%BD)

其他情况说明流量interface-name无法识别，需要关闭 auto detect interface，手动设置出口网卡名，一般是 `WLAN` 或 `以太网`

**Comment by alex3236** [comment]
![图片](https://user-images.githubusercontent.com/45303195/173284371-ea730440-609d-4b3d-b282-b704c0074cd1.png)
![图片](https://user-images.githubusercontent.com/45303195/173284392-4cb1632e-5700-47df-a861-be14a138fd26.png)

**Comment by paleomoon** [comment]
> 如果你是windows，进入控制面板看你的全部网络适配器，不能存在Cisco VPN等软件的虚拟网卡，也不能存在奇怪的“传入的连接”等等，如果存在请卸载（关闭auto detect interface并手动指定网卡是没用的）。

感谢，我就是更新后直接卡死，按大佬说的删掉“传入的连接”，重启就好了。

**Comment by kirsting** [comment]
> ![图片](https://user-images.githubusercontent.com/45303195/173284371-ea730440-609d-4b3d-b282-b704c0074cd1.png) ![图片](https://user-images.githubusercontent.com/45303195/173284392-4cb1632e-5700-47df-a861-be14a138fd26.png) 看起来没有问题，但打开TUN还是一样

和你一模一样

**Comment by alex3236** [comment]
> > ![图片](https://user-images.githubusercontent.com/45303195/173284371-ea730440-609d-4b3d-b282-b704c0074cd1.png) ![图片](https://user-images.githubusercontent.com/45303195/173284392-4cb1632e-5700-47df-a861-be14a138fd26.png) 看起来没有问题，但打开TUN还是一样
> 
> 和你一模一样

挺离谱的 好久了都没找到解决方法
