### ISSUE TITLE
[Bug]: 发现一个兼容问题，和智量安全软件不兼容

### ISSUE THREAD

**Issue by lhbdhr** [Fndroid/clash_for_windows_pkg#3120]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.20

### 操作系统

Windows x64

### 系统版本

WIN10

### 问题描述

智量是最近被不少人推荐的安全软件，
从昨天装了智量后，clash就频繁卡死，
表现为 proxies节点界面空白，provides界面空白。
国内国外网站都打不开。
日志没有任何报错，就是软件卡死了。
而且试用了多个历史版本都不行。

研究了整整一天，才发现，好像是智量的问题。
关闭智量软件后，再也不卡死了。

### 复现步骤

安装智量后发生的，关闭就好了。
复现率特别高，通常正常运行个十几分钟就卡死了。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
这种问题不可能在我这里修复的，和核心通信的http被拦截了就会这样

**Comment by lhbdhr** [comment]
> 这种问题不可能在我这里修复的，和核心通信的http被拦截了就会这样

嗯嗯，我主要想让遇到同样问题的人看一下，也没期望能解决兼容问题。
推荐作者可以放在readme提醒一下智量有兼容性问题。

**Comment by Fndroid** [comment]
几乎所有安全软件都有这种问题，文档里也有提了

**Comment by lhbdhr** [comment]
OK，那没事了。
