### ISSUE TITLE
[Bug]: 0.19.20 不支持后备字体（fallback font）

### ISSUE THREAD

**Issue by GRzun** [Fndroid/clash_for_windows_pkg#3122]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.20

### 操作系统

Windows x64

### 系统版本

Windows 11 专业版 21H2

### 问题描述

CFW 0.19.20 中的 Appearance - Font Family 设置项不支持后备字体，在先前版本中未出现此问题

### 复现步骤

在 Clash 界面中：

- 进入 Settings 面板
- 在 Appearance - Font Family 项中，首先输入西文字体，如 `Roboto`
- 程序中的西文以 Roboto 字族显示
- 以 `,` 分隔，再输入中文字体，如 `Roboto, Noto Sans CJK SC`
- 程序中的西文、中文均以默认的 Microsoft Yahei 字族显示

或在 `cfw-settings.yaml` 文件里，将 `fontFamily` 项修改为如下内容，亦可复现该问题：

``` yaml
fontFamily:
  - Roboto
  - Noto Sans CJK SC
```

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
下版本修复，可以用逗号分隔，但不会支持数组写法

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
