### ISSUE TITLE
[Bug]: 创建profile diff文件后，update profile提示冲突且无法通过make change解决

### ISSUE THREAD

**Issue by ssppest** [Fndroid/clash_for_windows_pkg#3126]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.20

### 操作系统

Windows x64

### 系统版本

windows 10 21H2 19044.1706

### 问题描述

update profile文件时，从线上拉回来的文件并没有变化，但diff功能提示冲突，解决冲突时发现diff功能判断的插入位置有误（将原有diff file添加的行插入到了原位置的前面，于是提示该行后冲突），手动解决冲突后再次update，依然提示冲突，只能删掉diff文件才能正常update

### 复现步骤

1. init diff file，修改diff文件，保存
2. update profile，提示冲突
3. make change，保存
4. 再次update profile，再次提示冲突
5. 2-4循环

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
能不能给一下冲突的那部分片段
