### ISSUE TITLE
[Bug]: cmd setproxy后仍然无法ping通google

### ISSUE THREAD

**Issue by asdfj2381k** [Fndroid/clash_for_windows_pkg#3127]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

v0.19.20

### 操作系统

Windows x64

### 系统版本

win7

### 问题描述

在cmd使用`set http_proxy=http://127.0.0.1:7890 & set https_proxy=http://127.0.0.1:7890`命令后

cmd 仍然无法ping通google

### 复现步骤

![微信截图_20220613215802](https://user-images.githubusercontent.com/56584082/173370694-22c9c866-f9cd-44d0-b51c-f257f6db2800.png)

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by asdfj2381k** [comment]
![image](https://user-images.githubusercontent.com/56584082/173372042-23934325-153b-48ae-bf8d-da925a8305a5.png)

**Comment by Fndroid** [comment]
预期行为，ping是icmp，本就不走代理

**Comment by Fndroid** [comment]
你最后多了个空格
