### ISSUE TITLE
0.8.5导入URL失败  

### ISSUE THREAD

**Issue by SilenceJoyson** [Fndroid/clash_for_windows_pkg#313]
<img width="638" alt="3ba7e685e89baabf007d11304da852e" src="https://user-images.githubusercontent.com/58633234/70377176-32e07080-194c-11ea-938e-528ec0ecf17b.png">

**Comment by SilenceJoyson** [comment]
@Fndroid   大神 怎么解释？

**Comment by narakuzi** [comment]
配置文件是对的吗

**Comment by Fndroid** [comment]
core没有启动成功，看logs文件夹最新文件排除

**Comment by SilenceJoyson** [comment]
> core没有启动成功，看日志文件夹最新文件排除
logs文件在哪里看？  我是个小白  不太懂

**Comment by SilenceJoyson** [comment]
> > core没有启动成功，看日志文件夹最新文件排除
> > logs文件在哪里看？  我是个小白  不太懂

我找到两个log文件  不知道那个才是
<img width="810" alt="15481e3b1e8977255fb0f01c8f7e0fe" src="https://user-images.githubusercontent.com/58633234/70386765-99f73700-19d7-11ea-90e9-c8a9bbf3ddc9.png">
<img width="810" alt="f14d43ab7cf63293dbce90db24f5029" src="https://user-images.githubusercontent.com/58633234/70386766-9a8fcd80-19d7-11ea-9a4e-46167b17bbe4.png">

**Comment by SilenceJoyson** [comment]
> > > core没有启动成功，看日志文件夹最新文件排除
> > > logs文件在哪里看？  我是个小白  不太懂
> 
> 我找到两个log文件 不知道那个才是
> <img alt="15481e3b1e8977255fb0f01c8f7e0fe" width="810" src="https://user-images.githubusercontent.com/58633234/70386765-99f73700-19d7-11ea-90e9-c8a9bbf3ddc9.png">
> <img alt="f14d43ab7cf63293dbce90db24f5029" width="810" src="https://user-images.githubusercontent.com/58633234/70386766-9a8fcd80-19d7-11ea-9a4e-46167b17bbe4.png">
@Fndroid  求帮助 谢谢大神

**Comment by Fndroid** [comment]
点左下角文字

**Comment by SilenceJoyson** [comment]
> 点左下角文字

在哪两个记事本里面点左下角文字吗

**Comment by Fndroid** [comment]
软件左下角disconnected文字，建议看看软件文档

**Comment by SilenceJoyson** [comment]
> 软件左下角disconnected文字，建议看看软件文档

第一个文件打开是这样的
<img width="810" alt="2189f941a207ed5a4b107c9e88c85e7" src="https://user-images.githubusercontent.com/58633234/70386917-b5634180-19d9-11ea-9c5d-8c5bc938eebc.png">

**Comment by Fndroid** [comment]
发个最新的啊

**Comment by SilenceJoyson** [comment]
> 发个最新的啊

<img width="810" alt="5093b0cd96b85e51c56a4ec5683a6c9" src="https://user-images.githubusercontent.com/58633234/70386956-26a2f480-19da-11ea-84ad-dfaaeddf8e3c.png">

**Comment by Fndroid** [comment]
点软件General，选try to repair

**Comment by SilenceJoyson** [comment]
> 点软件General，选try to repair
没有try to repair
<img width="638" alt="23588f65f426622cbdf14b9fb77e3de" src="https://user-images.githubusercontent.com/58633234/70387002-bb0d5700-19da-11ea-8b0b-7c6a045ab734.png">

**Comment by SilenceJoyson** [comment]
@Fndroid 怎么弄？大神
