### ISSUE TITLE
[Bug]: 通过 Mixin 开启 TUN，无法代理

### ISSUE THREAD

**Issue by QuentinHsu** [Fndroid/clash_for_windows_pkg#3137]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.20

### 操作系统

macOS arm64(M1,M1*)

### 系统版本

12.4

### 问题描述

通过 Mixin 开启 TUN，无法代理

直接使用 TUN Mode 开关，可以正常代理。

我复制 TUN Mode 中的配置信息到 Mixin 中，亦无法代理。

国内网站，访问始终正常。

### 复现步骤

已尝试重装 CFW，依旧存在该问题。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```
time="2022-06-17T10:02:05+08:00" level=debug msg="[TUN] hijack udp dns: 1.1.1.1:53"
time="2022-06-17T10:02:05+08:00" level=info msg="[TCP] 198.18.0.1:61239 --> caldav.fe.apple-dns.cn:443 doesn't match any rule using DIRECT"
time="2022-06-17T10:02:05+08:00" level=info msg="[TCP] 198.18.0.1:61238 --> caldav.fe.apple-dns.cn:443 doesn't match any rule using DIRECT"
time="2022-06-17T10:02:07+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.52:443 error: dial tcp4 149.154.175.52:443: i/o timeout"
time="2022-06-17T10:02:09+08:00" level=debug msg="[TUN] hijack udp dns: 1.1.1.1:53"
time="2022-06-17T10:02:13+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.50:443 error: dial tcp4 149.154.175.50:443: i/o timeout"
time="2022-06-17T10:02:14+08:00" level=warning msg="[TCP] dial DIRECT to cognito-idp.us-east-1.amazonaws.com:443 error: all DNS requests failed, first error: Post \"https://dns.google/dns-query\": context deadline exceeded"
time="2022-06-17T10:02:16+08:00" level=debug msg="[TUN] hijack udp dns: 1.1.1.1:53"
time="2022-06-17T10:02:16+08:00" level=info msg="[TCP] 198.18.0.1:61299 --> ws.lanhuapp.com:443 doesn't match any rule using DIRECT"
time="2022-06-17T10:02:19+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.50:443 error: dial tcp4 149.154.175.50:443: i/o timeout"
time="2022-06-17T10:02:20+08:00" level=warning msg="[TCP] dial DIRECT to cognito-idp.us-east-1.amazonaws.com:443 error: all DNS requests failed, first error: Post \"https://dns.google/dns-query\": context deadline exceeded"
time="2022-06-17T10:02:23+08:00" level=debug msg="[TUN] hijack udp dns: 1.1.1.1:53"
time="2022-06-17T10:02:23+08:00" level=debug msg="[TUN] hijack udp dns: 1.1.1.1:53"
time="2022-06-17T10:02:23+08:00" level=info msg="[TCP] 198.18.0.1:61349 --> cds.apple.com:443 doesn't match any rule using DIRECT"
time="2022-06-17T10:02:23+08:00" level=debug msg="[TUN] hijack udp dns: 1.1.1.1:53"
time="2022-06-17T10:02:23+08:00" level=debug msg="[TUN] hijack udp dns: 1.1.1.1:53"
time="2022-06-17T10:02:25+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.52:443 error: dial tcp4 149.154.175.52:443: i/o timeout"
time="2022-06-17T10:02:26+08:00" level=debug msg="[TUN] hijack udp dns: 1.1.1.1:53"
time="2022-06-17T10:02:27+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.52:5222 error: dial tcp4 149.154.175.52:5222: i/o timeout"
time="2022-06-17T10:02:27+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.50:80 error: dial tcp4 149.154.175.50:80: i/o timeout"
time="2022-06-17T10:02:27+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.50:443 error: dial tcp4 149.154.175.50:443: i/o timeout"
time="2022-06-17T10:02:27+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.52:443 error: dial tcp4 149.154.175.52:443: i/o timeout"
time="2022-06-17T10:02:27+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.50:5222 error: dial tcp4 149.154.175.50:5222: i/o timeout"
time="2022-06-17T10:02:27+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.52:80 error: dial tcp4 149.154.175.52:80: i/o timeout"
time="2022-06-17T10:02:27+08:00" level=debug msg="[TUN] hijack udp dns: 1.1.1.1:53"
time="2022-06-17T10:02:27+08:00" level=debug msg="[TUN] hijack udp dns: 1.1.1.1:53"
time="2022-06-17T10:02:27+08:00" level=debug msg="[TUN] hijack udp dns: 1.1.1.1:53"
time="2022-06-17T10:02:27+08:00" level=debug msg="[TUN] hijack udp dns: 1.1.1.1:53"
time="2022-06-17T10:02:27+08:00" level=debug msg="[TUN] hijack udp dns: 1.1.1.1:53"
time="2022-06-17T10:02:28+08:00" level=debug msg="[TUN] hijack udp dns: 1.1.1.1:53"
time="2022-06-17T10:02:28+08:00" level=debug msg="[TUN] hijack udp dns: 1.1.1.1:53"
time="2022-06-17T10:02:28+08:00" level=warning msg="[TCP] dial DIRECT to help.apple.com:443 error: all DNS requests failed, first error: Post \"https://dns.google/dns-query\": context deadline exceeded"
time="2022-06-17T10:02:31+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.50:443 error: dial tcp4 149.154.175.50:443: i/o timeout"
time="2022-06-17T10:02:31+08:00" level=warning msg="[TCP] dial DIRECT to chrome.cloudflare-dns.com:443 error: all DNS requests failed, first error: Post \"https://dns.google/dns-query\": context deadline exceeded"
time="2022-06-17T10:02:32+08:00" level=warning msg="[TCP] dial DIRECT to mozilla.cloudflare-dns.com:443 error: all DNS requests failed, first error: Post \"https://dns.google/dns-query\": context deadline exceeded"
time="2022-06-17T10:02:32+08:00" level=warning msg="[TCP] dial DIRECT to dns.google.com:443 error: all DNS requests failed, first error: Post \"https://dns.google/dns-query\": dial tcp4 8.8.4.4:443: i/o timeout"
time="2022-06-17T10:02:32+08:00" level=warning msg="[TCP] dial DIRECT to vscode-sync.trafficmanager.net:443 error: all DNS requests failed, first error: Post \"https://dns.google/dns-query\": context deadline exceeded"
time="2022-06-17T10:02:33+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.50:80 error: dial tcp4 149.154.175.50:80: i/o timeout"
time="2022-06-17T10:02:33+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.52:5222 error: dial tcp4 149.154.175.52:5222: i/o timeout"
time="2022-06-17T10:02:33+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.52:80 error: dial tcp4 149.154.175.52:80: i/o timeout"
time="2022-06-17T10:02:33+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.50:5222 error: dial tcp4 149.154.175.50:5222: i/o timeout"
time="2022-06-17T10:02:33+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.50:443 error: dial tcp4 149.154.175.50:443: i/o timeout"
time="2022-06-17T10:02:33+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.52:443 error: dial tcp4 149.154.175.52:443: i/o timeout"
time="2022-06-17T10:02:33+08:00" level=warning msg="[TCP] dial DIRECT to www.google.com:443 error: all DNS requests failed, first error: Post \"https://dns.google/dns-query\": dial tcp4 8.8.8.8:443: i/o timeout"
time="2022-06-17T10:02:33+08:00" level=warning msg="[TCP] dial DIRECT to help.apple.com:443 error: all DNS requests failed, first error: Post \"https://dns.google/dns-query\": context deadline exceeded"
time="2022-06-17T10:02:36+08:00" level=info msg="[TCP] 198.18.0.1:61494 --> ws.lanhuapp.com:443 doesn't match any rule using DIRECT"
time="2022-06-17T10:02:36+08:00" level=warning msg="[TCP] dial DIRECT to chrome.cloudflare-dns.com:443 error: all DNS requests failed, first error: Post \"https://dns.google/dns-query\": context deadline exceeded"
time="2022-06-17T10:02:36+08:00" level=warning msg="[TCP] dial DIRECT to chrome.cloudflare-dns.com:443 error: all DNS requests failed, first error: Post \"https://dns.google/dns-query\": context deadline exceeded"
time="2022-06-17T10:02:37+08:00" level=warning msg="[TCP] dial DIRECT to dns.google.com:443 error: all DNS requests failed, first error: Post \"https://dns.google/dns-query\": context deadline exceeded"
time="2022-06-17T10:02:37+08:00" level=warning msg="[TCP] dial DIRECT to mozilla.cloudflare-dns.com:443 error: all DNS requests failed, first error: Post \"https://dns.google/dns-query\": dial tcp4 8.8.8.8:443: i/o timeout"
time="2022-06-17T10:02:38+08:00" level=warning msg="[TCP] dial DIRECT to vscode-sync.trafficmanager.net:443 error: all DNS requests failed, first error: Post \"https://dns.google/dns-query\": context deadline exceeded"
time="2022-06-17T10:02:38+08:00" level=warning msg="[TCP] dial DIRECT to help.apple.com:443 error: all DNS requests failed, first error: Post \"https://dns.google/dns-query\": context deadline exceeded"
time="2022-06-17T10:02:39+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.50:443 error: dial tcp4 149.154.175.50:443: i/o timeout"
time="2022-06-17T10:02:39+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.50:80 error: dial tcp4 149.154.175.50:80: i/o timeout"
time="2022-06-17T10:02:39+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.52:443 error: dial tcp4 149.154.175.52:443: i/o timeout"
time="2022-06-17T10:02:39+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.52:80 error: dial tcp4 149.154.175.52:80: i/o timeout"
time="2022-06-17T10:02:39+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.52:5222 error: dial tcp4 149.154.175.52:5222: i/o timeout"
time="2022-06-17T10:02:39+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.50:5222 error: dial tcp4 149.154.175.50:5222: i/o timeout"
time="2022-06-17T10:02:40+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.50:443 error: dial tcp4 149.154.175.50:443: i/o timeout"
time="2022-06-17T10:02:41+08:00" level=info msg="[TCP] 198.18.0.1:61551 --> ws.lanhuapp.com:443 doesn't match any rule using DIRECT"
time="2022-06-17T10:02:41+08:00" level=warning msg="[TCP] dial DIRECT to chrome.cloudflare-dns.com:443 error: all DNS requests failed, first error: Post \"https://dns.google/dns-query\": context deadline exceeded"
time="2022-06-17T10:02:42+08:00" level=warning msg="[TCP] dial DIRECT to dns.google.com:443 error: all DNS requests failed, first error: Post \"https://dns.google/dns-query\": context deadline exceeded"
time="2022-06-17T10:02:42+08:00" level=warning msg="[TCP] dial DIRECT to mozilla.cloudflare-dns.com:443 error: all DNS requests failed, first error: Post \"https://dns.google/dns-query\": context deadline exceeded"
time="2022-06-17T10:02:45+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.52:80 error: dial tcp4 149.154.175.52:80: i/o timeout"
time="2022-06-17T10:02:45+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.50:80 error: dial tcp4 149.154.175.50:80: i/o timeout"
time="2022-06-17T10:02:45+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.50:443 error: dial tcp4 149.154.175.50:443: i/o timeout"
time="2022-06-17T10:02:45+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.50:5222 error: dial tcp4 149.154.175.50:5222: i/o timeout"
time="2022-06-17T10:02:45+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.52:443 error: dial tcp4 149.154.175.52:443: i/o timeout"
time="2022-06-17T10:02:45+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.52:5222 error: dial tcp4 149.154.175.52:5222: i/o timeout"
time="2022-06-17T10:02:45+08:00" level=debug msg="[TUN] hijack udp dns: 1.1.1.1:53"
time="2022-06-17T10:02:48+08:00" level=debug msg="[TUN] hijack udp dns: 1.1.1.1:53"
time="2022-06-17T10:02:49+08:00" level=info msg="[TCP] 198.18.0.1:61612 --> lanhu-logger.cn-beijing.log.aliyuncs.com:443 doesn't match any rule using DIRECT"
time="2022-06-17T10:02:49+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.52:443 error: dial tcp4 149.154.175.52:443: i/o timeout"
time="2022-06-17T10:02:50+08:00" level=warning msg="[TCP] dial DIRECT to alive.github.com:443 error: all DNS requests failed, first error: Post \"https://dns.google/dns-query\": context deadline exceeded"
time="2022-06-17T10:02:51+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.52:5222 error: dial tcp4 149.154.175.52:5222: i/o timeout"
time="2022-06-17T10:02:51+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.50:443 error: dial tcp4 149.154.175.50:443: i/o timeout"
time="2022-06-17T10:02:51+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.52:443 error: dial tcp4 149.154.175.52:443: i/o timeout"
time="2022-06-17T10:02:51+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.52:80 error: dial tcp4 149.154.175.52:80: i/o timeout"
time="2022-06-17T10:02:51+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.50:80 error: dial tcp4 149.154.175.50:80: i/o timeout"
time="2022-06-17T10:02:51+08:00" level=warning msg="[TCP] dial DIRECT to 149.154.175.50:5222 error: dial tcp4 149.154.175.50:5222: i/o timeout"
time="2022-06-17T10:02:51+08:00" level=debug msg="[TUN] hijack udp dns: 1.1.1.1:53"
time="2022-06-17T10:02:51+08:00" level=debug msg="[TUN] hijack udp dns: 1.1.1.1:53"
time="2022-06-17T10:02:52+08:00" level=debug msg="[TUN] hijack udp dns: 1.1.1.1:53"
time="2022-06-17T10:02:53+08:00" level=debug msg="[TUN] hijack udp dns: 1.1.1.1:53"
time="2022-06-17T10:02:55+08:00" level=warning msg="[TCP] dial DIRECT to alive.github.com:443 error: all DNS requests failed, first error: Post \"https://dns.google/dns-query\": context deadline exceeded"

</p></details>

**Comment by yi-Xu-0100** [comment]
建议给出mixin的内容

**Comment by QuentinHsu** [comment]
> 建议给出mixin的内容

非常抱歉，我以为既然 TUN Mode 中的配置在 Mixin 中亦无效，所以就没贴。

如下是我的 Mixin 配置

```
mixin: # object
  # dns:
  #   enable: true
  #   ipv6: false # default is false
  #   #listen: 0.0.0.0:53 # 假如开启 tun，此项可以不用配置
  #   enhanced-mode: fake-ip
  #   nameserver:
  #     - https://doh.pub/dns-query
  #     - https://dns.alidns.com/dns-query
  #   fallback:
  #     - https://dns.google/dns-query
  #     - https://cloudflare-dns.com/dns-query
  #     - 8.8.4.4
  #   fallback-filter:
  #     geoip: true
  #     geoip-code: CN
  #     ipcidr:
  #       - 240.0.0.0/4
  # tun:
  #   enable: true
  #   stack: gvisor
  #   dns-hijack: # DNS 劫持
  #     - any:53
  #   auto-route: true
  #   auto-detect-interface: true
  dns:
    enable: true
    enhanced-mode: fake-ip
    nameserver:
      - https://dns.alidns.com/dns-query
      - https://doh.pub/dns-query
    fallback:
      - https://dns.google/dns-query
    fake-ip-filter:
      - apps.apple.com
  tun:
    enable: true
    stack: gvisor
    auto-detect-interface: true
    auto-route: true
    dns-hijack:
      - 1.1.1.1
      - 114.114.114.114
  rules:
    - DOMAIN-SUFFIX, xxxx, 🌍 Global Proxy
```'

注释的 dns/tun 部分，是我曾经使用且能正常代理的配置，但现在不行了。
未注释的 dns/tun 部分，是我从 TUN Mode 中复制出来的配置，依旧不行。

**Comment by yi-Xu-0100** [comment]
我看到你增加了一个rule，这样会把规则全部覆盖为一个，也就是你这样只会有一个rule.是否是这个原因？

**Comment by QuentinHsu** [comment]
> 我看到你增加了一个rule，这样会把规则全部覆盖为一个，也就是你这样只会有一个rule.是否是这个原因？

感谢！！！应该就是这个！我注释掉就好了！搞了我两三天了😭！

刚刚再次拜读了下 CFW 文档利用 Profiles - Parsers 实现了！
