### ISSUE TITLE
[Bug]: 在配置文件右键选择Rules填加规则后注释文本全部消失

### ISSUE THREAD

**Issue by jiangqi3230** [Fndroid/clash_for_windows_pkg#3138]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.20

### 操作系统

Windows x64

### 系统版本

win11_21H2_22000.739

### 问题描述

平时我添加规则用的是edit externally,觉得麻烦就用了clash的rules直接添加规则。但是添加规则保存后配置文件的注释全都不见了。

### 复现步骤

一份本地配置文件里面有自己的注释，使用clash的rules添加规则保存后，注释全部消失

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
那个会解析结构，所以会丢失注释应该。
