### ISSUE TITLE
[解惑]能否帮忙解答一下自定义转发配置上的疑惑

### ISSUE THREAD

**Issue by zxdposter** [Fndroid/clash_for_windows_pkg#3139]
当我直接使用机场订阅地址是，是能够解析正常使用的。

但是当我自己搭建服务器，转发机场地址的返回结果时，无法解析。

代码如下
<img width="511" alt="image" src="https://user-images.githubusercontent.com/13846260/174270040-2c5e11b1-d68c-4a22-9ee0-ffdf80d63597.png">

我请求机场地址返回结果，和我自己的地址返回结果是完全一样的，但是客户端无法解析结果。

请求解惑，是什么原因导致的？
<img width="645" alt="image" src="https://user-images.githubusercontent.com/13846260/174270644-e069a467-9bcd-4ae3-b780-b86ea98987ac.png">

**Comment by Fndroid** [comment]
因为是从http response header里取得信息

**Comment by zxdposter** [comment]
@Fndroid 我也猜到了，我把头都拷贝了一遍，还是不行，具体是哪个头？
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/13846260/174432104-4d81ff94-086c-4235-ab71-3b36c0783fb8.png">

**Comment by yi-Xu-0100** [comment]
@zxdposter 

我怀疑是这样的，机场的响应是分 header 中 ua 信息的，CFW 请求会带 `user-agent: ClashforWindows/0.19.21` 这样的信息的，所以会返回对应的 clash 订阅配置文件（.yaml）。

> 我请求机场地址返回结果，和我自己的地址返回结果是完全一样的，但是客户端无法解析结果。

而你请求的时候没有这样做，所以你看到的可能是 base64 的节点编码信息，与你自己地址转发的结果当然也是一致的，所以看起来获得的是对的信息，但其实不是能够被解析的。

所以你的地址转发过程中，请求机场订阅的时候加上 ua 信息，然后转发的时候带上请求获得的 header 才算完整的请求转发。

**Comment by zxdposter** [comment]
@yi-Xu-0100 啊，感谢，明白了
我一直以来的想法是返回的头部信息，没想到请求的头部信息才是重点，可以了，非常感谢
