### ISSUE TITLE
大神紧急求助！！！使用Clash 无法翻墙了

### ISSUE THREAD

**Issue by CopRipper** [Fndroid/clash_for_windows_pkg#314]
![v0 75（2）](https://user-images.githubusercontent.com/58581665/70383610-8d5ce980-19ab-11ea-80bf-c59348646992.png)
![v0 75](https://user-images.githubusercontent.com/58581665/70383612-8d5ce980-19ab-11ea-87e0-ac378bf2cf24.png)
我昨天还能使用，今天突然无法翻墙了，但手机的可以使用，我尝试过以下方法：
更新到最新版本0.8.5版本（失败！）
重新安装并下载配置（失败！）
通过管理员身份打开（失败！）
![YouTube](https://user-images.githubusercontent.com/58581665/70383629-eaf13600-19ab-11ea-915b-9766a996938c.png)
所以请大神帮我看看是什么原因，我是刚买的年费会员（T-T）

**Comment by Fndroid** [comment]
请自行联系你的机场

**Comment by CopRipper** [comment]
机场是什么，我没听懂

**Comment by Fndroid** [comment]
> 所以请大神帮我看看是什么原因，我是刚买的年费会员（T-T）

跟谁买的就找谁

**Comment by CopRipper** [comment]
懂了，那个服务人员的weixin无法联系很久了，怎么办，我最近一直都是自己在弄😓
