### ISSUE TITLE
[Bug]: macOS Ventura 下开机自启失效

### ISSUE THREAD

**Issue by jdjxk** [Fndroid/clash_for_windows_pkg#3141]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.21

### 操作系统

macOS amd64(Intel)

### 系统版本

13.0

### 问题描述

开机自启失效

### 复现步骤

重新安装无效

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by acse-bp221** [comment]
我也有同样的问题

**Comment by chowhwei** [comment]
same issue

Ventura beta 3
clash for windows version 0.19.24
