### ISSUE TITLE
下载教程[Feature Request]: 

### ISSUE THREAD

**Issue by Mendax1999** [Fndroid/clash_for_windows_pkg#3147]
### 功能描述

我看了两个小时，不知道怎么下载，下载成解压包了，不会用，有人可以教教我吗吗

**Comment by JXGO** [comment]
头回在github上看见这么牛逼的问题

**Comment by Mendax1999** [comment]
第一次用github...

**Comment by JXGO** [comment]
在release界面里找到你需要的版本下载

**Comment by yi-Xu-0100** [comment]
要不直接 bing 搜索下 CFW教程？

**Comment by Sakuzy0** [comment]
https://gh.ddlc.top/https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.19.21/Clash.for.Windows.Setup.0.19.21.exe

**Comment by alex3236** [comment]
![image](https://user-images.githubusercontent.com/45303195/174439023-854e87ae-723a-441a-9522-902fda2cf604.png)
![image](https://user-images.githubusercontent.com/45303195/174439030-83c44bb3-5c06-45ff-ba4c-0b7a87fa8f44.png)
