### ISSUE TITLE
there is nothing in profiles option

### ISSUE THREAD

**Issue by bitdan** [Fndroid/clash_for_windows_pkg#315]
![image](https://user-images.githubusercontent.com/44058167/70584133-043bf180-1bfb-11ea-82f8-042d7660510d.png)
and i use win1909 Professional

**Comment by Fndroid** [comment]
Please check is there a directory named "profiles" was created at ``Home Directory``(General)

**Comment by weimeibuqieryu** [comment]
![image](https://user-images.githubusercontent.com/44058167/70585610-ad84e680-1bff-11ea-832e-beeb0c21f22f.png)
i think yes

**Comment by bitdan** [comment]
> Please check is there a directory named "profiles" was created at `Home Directory`(General)

![image](https://user-images.githubusercontent.com/44058167/70586418-f9d12600-1c01-11ea-89fe-8555d55e8210.png)
i think yes

**Comment by Fndroid** [comment]
try to remove that then restart the app

**Comment by bitdan** [comment]
> try to remove that then restart the app

Oak, that works, thank u

**Comment by Fndroid** [comment]
This issue will be closed, reopen it whenerver you need.
