### ISSUE TITLE
[Bug]: Windows 11 KB5014697 update breaks connections to clash-win64.exe

### ISSUE THREAD

**Issue by pseudovector** [Fndroid/clash_for_windows_pkg#3154]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.21

### 操作系统

Windows x64

### 系统版本

Windows 11 21H2 22000.708

### 问题描述

After Windows 11 update KB5014697, Clash for Windows won't connect to clash core anymore
Removing KB5014697 fix this issue.
But I had to pause windows update preventing windows reinstalling this update package.
Could you look into this and see if there is anything we could do to fix this issue without having to pause windows update?
Thank you!

### 复现步骤

1. Windows update install KB5014697
2. Reboot system
3. Clash for Windows won't connect to core, showing issue 'failed to clash core'

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
https://t.me/atashare/1246

**Comment by pseudovector** [comment]
> https://t.me/atashare/1246

Copy, thanks
