### ISSUE TITLE
[Feature Request]: Support DNS-over-QUIC

### ISSUE THREAD

**Issue by jiayouba233** [Fndroid/clash_for_windows_pkg#3156]
### 功能描述

#1817 Clash for Windows 的 TUN 模式暂时不支持 DNS-over-QUIC

目前支持 DNS-over-QUIC 的只有 [AdGuard](https://adguard.com/zh_cn/blog/dns-over-quic.html)，但应该会得到广泛的使用

而且 QUIC 的 DNS 服务器应该会有更快地响应（相比于 DoH 与 DoT)

### 其他内容

[AdGuard 公共 DNS 页面](https://adguard-dns.io/zh_cn/public-dns.html)

**Comment by yi-Xu-0100** [comment]
core issue: <https://github.com/Dreamacro/clash/issues>
