### ISSUE TITLE
希望提供按时延排序的功能

### ISSUE THREAD

**Issue by LauJon** [Fndroid/clash_for_windows_pkg#316]
1、测速后的节点列表，希望可以排序
2、在polices中删除某节点，更新profile会重新将删除的节点加回来。建议删除的节点，更新时不要加回来
3、期望右下角小图标右键菜单支持开启和关闭代理

加油。感谢。

**Comment by dayfan0810** [comment]
+1

**Comment by Fndroid** [comment]
最新版已经有了
