### ISSUE TITLE
[Feature Request]: 允许用户自定义适用于每个订阅配置的分流、DNS

### ISSUE THREAD

**Issue by mayunqing1230** [Fndroid/clash_for_windows_pkg#3160]
### 功能描述

允许用户自定义适用于每个订阅配置的分流、DNS，分流也可以获取gfwlist并且自定义，DNS最好是DNS over https这类有加密的，可以用私人DNS的

**Comment by yi-Xu-0100** [comment]
https://github.com/Dreamacro/clash/wiki/configuration

https://docs.cfw.lbyczf.com/contents/diff.html

https://docs.cfw.lbyczf.com/contents/parser.html
