### ISSUE TITLE
[Bug]: Internet Download Manager 无法正常使用代理

### ISSUE THREAD

**Issue by alem0n** [Fndroid/clash_for_windows_pkg#3164]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.21

### 操作系统

Windows x64

### 系统版本

Windows 10 21H2

### 问题描述

我使用Clash for Windows里默认的代理端口7890。在IDM中设置代理服务器为127.0.0.1:7890，而在下载文件的时候IDM不能正常走代理。这是否是Clash for Windows在代理端口上的配置有问题。或者是否有方法固定PAC的地址端口因为每天都要重新更新端口才可以使用。

### 复现步骤

使用代理服务器无法进行下载
![image](https://user-images.githubusercontent.com/44863015/174960885-92928d16-14c8-43fa-be9f-9e8f407729bd.png)
一直显示连接中
![image](https://user-images.githubusercontent.com/44863015/174961544-8675fdd6-a790-4dd1-a0fd-a3fd4f70c5a8.png)

使用PAC可以正常下载
![image](https://user-images.githubusercontent.com/44863015/174961289-d2bb5e1b-2c1f-44da-a3ef-23131bfc18c1.png)
![image](https://user-images.githubusercontent.com/44863015/174961631-87ed931a-9a7f-4dff-8743-9a7fdca7f3f1.png)

### 日志文件

<details><summary>logs</summary><p>

```
time="2022-06-22T11:40:56+08:00" level=info msg="RESTful API listening at: 127.0.0.1:1291"
time="2022-06-22T14:33:58+08:00" level=warning msg="[TCP] dial DIRECT (match DomainSuffix/qq.com) to antibot.qq.com:443 error: lookup antibot.qq.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."
time="2022-06-22T14:33:58+08:00" level=warning msg="[TCP] dial DIRECT (match DomainSuffix/qq.com) to antibot.qq.com:443 error: lookup antibot.qq.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."
time="2022-06-22T14:33:58+08:00" level=warning msg="[TCP] dial DIRECT (match DomainSuffix/qq.com) to antibot.qq.com:443 error: lookup antibot.qq.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."
time="2022-06-22T14:33:59+08:00" level=warning msg="[TCP] dial DIRECT (match DomainSuffix/qq.com) to antibot.qq.com:443 error: lookup antibot.qq.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."
time="2022-06-22T14:33:59+08:00" level=warning msg="[TCP] dial DIRECT (match DomainSuffix/qq.com) to antibot.qq.com:443 error: lookup antibot.qq.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."
time="2022-06-22T14:33:59+08:00" level=warning msg="[TCP] dial DIRECT (match DomainSuffix/qq.com) to antibot.qq.com:443 error: lookup antibot.qq.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."
time="2022-06-22T14:33:59+08:00" level=warning msg="[TCP] dial DIRECT (match DomainSuffix/qq.com) to antibot.qq.com:443 error: lookup antibot.qq.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."
time="2022-06-22T14:33:59+08:00" level=warning msg="[TCP] dial DIRECT (match DomainSuffix/qq.com) to antibot.qq.com:443 error: lookup antibot.qq.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."
time="2022-06-22T14:33:59+08:00" level=warning msg="[TCP] dial DIRECT (match DomainSuffix/qq.com) to antibot.qq.com:443 error: lookup antibot.qq.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."
time="2022-06-22T14:37:16+08:00" level=warning msg="[TCP] dial DIRECT (match DomainSuffix/qq.com) to scdown.qq.com:80 error: lookup scdown.qq.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."
time="2022-06-22T14:37:17+08:00" level=warning msg="[TCP] dial DIRECT (match DomainSuffix/qq.com) to scdown.qq.com:80 error: lookup scdown.qq.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."
time="2022-06-22T14:37:17+08:00" level=warning msg="[TCP] dial DIRECT (match DomainSuffix/qq.com) to scdown.qq.com:80 error: lookup scdown.qq.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."

```

</p></details>

**Comment by onlunar** [comment]
IDM不需要手动配置，直接“使用系统中的设置”自动获取。
System Proxy的类型选择HTTP才会走你Allow WAN上面设置的端口，Type如果是PAC端口设置是不生效的
![image](https://user-images.githubusercontent.com/21257369/174992224-d2bdb3b1-7ba2-4ba5-aca9-d5e56670040e.png)

**Comment by alem0n** [comment]
> 
但是其他软件像Firefox和Telegram可以走端口，请问这是为什么呢。

我要每次重启clash以后重新获取一下系统中的设置，因为系统中设置的链接的端口只要重启clash就会改变，请问有什么办法可以固定这个链接吗。
重启clash前
![image](https://user-images.githubusercontent.com/44863015/174993868-313c1a00-7b97-45d7-8d57-408f4faef837.png)
重启clash后
![image](https://user-images.githubusercontent.com/44863015/174993957-cda12519-f550-4a12-bfff-88586fbbb8f3.png)

**Comment by norangit** [comment]
你肯定是设置了啥东西了，clash的端口不会更换的，默认端口应该是被占用了，你可以在刚打开的界面 Port 那设置自己想要的端口，也可以就使用默认的

**Comment by alem0n** [comment]
> 


> 你肯定是设置了啥东西了，clash的端口不会更换的，默认端口应该是被占用了，你可以在刚打开的界面 Port 那设置自己想要的端口，也可以就使用默认的

不是，你理解错了，这个不是mixed端口，这个是pac的端口这两个不一样

**Comment by onlunar** [comment]
Proxy Auto Config`PAC`自动配置获取代理脚本的`url`和`port`，为了不和本地的任何端口冲突，这个端口是随机生成的。上个comment里说得很清楚了，用HTTP模式走的就是General-Port设置的固定端口。PAC模式的端口等于是在HTTP模式下开了Random Mixed Port。不像浏览器和IM，那些自身不会主动同步系统代理的软件不适用于PAC模式，建议使用HTTP模式或者TUN/TAP模式。

**Comment by alem0n** [comment]
一个新的解决方式：
       关闭CFW的System Proxy开关
![image](https://user-images.githubusercontent.com/44863015/177002268-001bc0ea-74ec-4761-82f7-21922afe9499.png)

       chrome使用SwitchyOmega进行上网
![image](https://user-images.githubusercontent.com/44863015/177002282-c6d72c23-67cf-43de-8a09-82a0aa14287a.png)

       这时候设置idm的代理服务器为127.0.0.1:7890可以正常使用并且不会再改变端口了
![image](https://user-images.githubusercontent.com/44863015/177002296-48ab08ab-9a9c-4811-87ec-70139fa9e554.png)
