### ISSUE TITLE
[Bug]: 请教大家，如何只给浏览器走代理？我只开了系统代理，结果epic下游戏流量也走了代理

### ISSUE THREAD

**Issue by JoysonZ** [Fndroid/clash_for_windows_pkg#3172]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.20

### 操作系统

Windows x64

### 系统版本

Windows 11

### 问题描述

服务模式已经安装，确认TUN模式没有开启，我只开了系统代理
打开EPIC，更新了个游戏，走了系统代理（把我流量直接烧没了……）
我确实有在规则内将游戏平台设置了一个代理，但是通常情况下我以为那是为了网页服务的……

请问这是EPIC特有的问题使得它会走系统代理吗？
还是说可以通过某些设置，让Clash有办法只让浏览器走代理么？

### 复现步骤

在系统代理模式下打开EPIC GAME客户端，稳定复现

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by EA-DICE** [comment]
epic平台下载走系统代理是正常情况

**Comment by Sakuzy0** [comment]
代理规则里把游戏平台改成direct 或者自行添加规则

**Comment by JoysonZ** [comment]
> 关闭系统代理，然后给浏览器安装个proxy插件，使用proxy插件进行代理，就可以实现只让浏览器走代理

靠着这个方式基本实现了我的需求，谷歌浏览器使用SwithyOmega插件
