### ISSUE TITLE
[Bug]: 打开Clash 导致 Xbox 游戏无法进入，错误代码 0x89235106

### ISSUE THREAD

**Issue by Maasea** [Fndroid/clash_for_windows_pkg#3173]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.22

### 操作系统

Windows x64

### 系统版本

window11 21H2

### 问题描述

当系统开机时，clash 处于 proxy 状态，则无法进入 Xbox 游戏。测试游戏： 地平线5，我的世界地下城。

具体表现为：

打开游戏，出现 正在登录 -> 正在检查更新 -> 弹出错误框 启动你的游戏时出现错误。错误代码: (0x89235106)

我经过以下排错：
1. windows 启动时，开启了Clash 作为系统代理  [X]
2. windows 启动时，开启了Clash 作为系统代理，但在打开游戏前关闭 clash   [X]
3. windows 启动时，clash 代理没有打开 [√]
4. windows 启动时，系统代理没有打开。进入游戏后，关闭游戏，再次打开clash 代理，游戏依然能再次进入 [√]
5. windows 启动时，没有开启clash 代理，但是进游戏前开始代理 [x]
6. windows 启动时,   clash使用TUN 模式 [√]

这些测试中包括，开关全局直连，开关UWP Loopback。

简单的总结，就是系统启动时，如果clash 处于 系统代理状态则无法进入游戏。每次恢复都需要关闭clash 代理，然后重启电脑。

### 复现步骤

在开机时，或者启动游戏前，保持clash 处于系统代理的模式下。

### 日志文件

<details><summary>logs</summary><p>

</p></details>

**Comment by Maasea** [comment]
补充：Clash 使用 PAC 模式，正常启动。

**Comment by t13528829926** [comment]
> 补充：Clash 使用 PAC 模式，正常启动。

我开了pac模式还是打不开游戏

**Comment by Maasea** [comment]
> 我开了pac模式还是打不开游戏

打开Clash 主页的 Loopback，然后全部勾选。

`empty none`

**Comment by wuditieniu** [comment]
麻了，一样的情况。之前每次换电脑或者重装系统都会被类似问题折磨好几次，后来知道开loopback解决了大半问题。
和你一模一样的问题之前有过，明明东搞西搞弄好了，下次装机还是不行。
昨天刚装好的机器，又是和你一摸一样的问题，目前是这样解决的，把clash的规则页面不是可以给每个项目选节点吗，我之前微软那一项选的直连，改成随便哪个常用的节点就可以进游戏了，loopback已开。不知道是不是这个操作解决的。

**Comment by lilyrader** [comment]
> 

哪有微软的选项呢

**Comment by wuditieniu** [comment]
> > 
> 
> 哪有微软的选项呢

clash你订阅的机场一般自带规则就有吧，就是左边选项卡第二个怕proxies选项，点进去右边是四个选项global rule direct script，默认一般就是RULE，里边不是有很多规则让你设置嘛，比如流媒体走哪个节点，谷歌服务走哪个节点，苹果服务走哪个节点，微软服务选一个常用的稳定节点就可以。我的机场订阅自带规则就有。
