### ISSUE TITLE
[Bug]: 为什么这个 tun mode 经常不起作用？

### ISSUE THREAD

**Issue by saodis** [Fndroid/clash_for_windows_pkg#3174]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.22

### 操作系统

Windows x64

### 系统版本

Windows 10 专业版 21H2

### 问题描述

两个问题：
1. 为什么这个 tun mode 经常不起作用？不起作用时，windows 的网络连接也没有 clash 网卡，任务栏网络那个位置也没有 clash。
![image](https://user-images.githubusercontent.com/51149477/175802384-cf3853a1-1ef8-48d6-a1fd-cb6ac18421c5.png)
解决办法就是重启一下 clash。
clash 截图
![image](https://user-images.githubusercontent.com/51149477/175802604-a305ef8a-393b-42ac-ad39-63e2fcc2af02.png)
tun 配置（默认）
![image](https://user-images.githubusercontent.com/51149477/175802616-1d19a159-b5fa-4029-a57d-c705cba0ea68.png)

2. 开启 tun mode 成功时，是不是 pac 的规则就无效了？不开启，规则是有效的。
![image](https://user-images.githubusercontent.com/51149477/175802586-da5b809c-957f-43f9-a84d-e8b2b6cd2678.png)

pac
```js
function FindProxyForURL(url, host) {
  if (shExpMatch(host, "*.xunlei.com") || shExpMatch(host, "*.edu.cn")) {
    return "DIRECT";
  } else if (
    isInNet(dnsResolve(host), "10.0.0.0", "255.0.0.0") ||
    isInNet(dnsResolve(host), "172.16.0.0", "255.240.0.0") ||
    isInNet(dnsResolve(host), "192.168.0.0", "255.255.0.0") ||
    isInNet(dnsResolve(host), "127.0.0.0", "255.0.0.0")
  ) {
    return "DIRECT";
  } else {
    return "SOCKS5 127.0.0.1:%mixed-port%; PROXY 127.0.0.1:%mixed-port%";
  }
}
```

### 复现步骤

开启 tun mode

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by vilau** [comment]
以前有人提过类似issue,你试试在tun mode 里关闭 auto-dect-interface。手动设置成WLAN再看看

**Comment by kusiru** [comment]
需要关掉system proxy

**Comment by saodis** [comment]
@vilau 没搜到这个 issue，方便发下链接么

**Comment by vilau** [comment]
> @vilau 没搜到这个 issue，方便发下链接么
https://github.com/Fndroid/clash_for_windows_pkg/issues/3088

**Comment by kusiru** [comment]
> > 需要关掉system proxy
> 
> 一本正经的胡说八道？关了代理，你还咋用...

你开了tun 模式，就不需要再开系统代理
