### ISSUE TITLE
0.8.5win10下无法订阅

### ISSUE THREAD

**Issue by songsongsong820** [Fndroid/clash_for_windows_pkg#318]
![image](https://user-images.githubusercontent.com/58823192/70733048-7bc96800-1d44-11ea-89eb-dd091f4b6902.png)
添加链接之后如图，搞不懂该怎么办了，求救。~

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/configfile.html

**Comment by manafei** [comment]
遇到了一样的问题，上面的网址完全牛头不对马嘴，根本解决不了，头大
