### ISSUE TITLE
[Feature Request]: 在Connections页中增加processname显示以及sort by processname的功能

### ISSUE THREAD

**Issue by asdfj2381k** [Fndroid/clash_for_windows_pkg#3180]
### 功能描述

当然这不是必须的功能。

但是可能会让用户更舒服。

![image](https://user-images.githubusercontent.com/56584082/176382988-0419cd12-9734-4aae-86d6-17eda7af9478.png)

### 其他内容

无

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/176571044-17a9f5de-edeb-4e56-a192-7aabbefb2d48.png)

可以试着切换到 Both，理论上，你给 telegram 分一个单独的策略组，也可以看到分流了。

**Comment by asdfj2381k** [comment]
谢谢  @yi-Xu-0100     

还有别的软件有陌生的域名和IP，如果增加会更方便 。

**Comment by yi-Xu-0100** [comment]
我这边直接搜索里输入 telegram 好像也能匹配到，不过我不确定这里的搜索匹配的范围。

**Comment by yi-Xu-0100** [comment]
@asdfj2381k https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.19.23

**Comment by asdfj2381k** [comment]
@yi-Xu-0100   Done.
