### ISSUE TITLE
[Bug]: Cron设置profile  10分钟更新一次似乎没有奏效

### ISSUE THREAD

**Issue by zjplab** [Fndroid/clash_for_windows_pkg#3184]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

2021.9.15 Premium 60597

### 操作系统

Windows x64

### 系统版本

Win 10

### 问题描述

Profile Update interval: 1h,
Update Cron: `*/10  * * * *`
Cron设置不顶用， 只按照1h更新

### 复现步骤

同上

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
所以是不是 Update interval 的优先级高于 Update Cron？

**Comment by Fndroid** [comment]
目前的话需要interval设置成0，cron才会生效，下个版本调整下两个可以同时有效

**Comment by zjplab** [comment]
@Fndroid 但是设置成`*/1  * * * *` interval为0 也没有更新啊

**Comment by yi-Xu-0100** [comment]
@zjplab https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.19.23
