### ISSUE TITLE
clash_for_windows v0.19.23 点击到中间标题软件重启

### ISSUE THREAD

**Issue by goohegle** [Fndroid/clash_for_windows_pkg#3187]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.23

### 操作系统

Windows x64

### 系统版本

Windows 10 19044

### 问题描述

每次点击到软件界面上方“clash for windows”会重启。因此如果检测版本时点中了偏左边会导致重启。

### 复现步骤

点击软件界面“clash for windows”，即“v0.19.23”的左边。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
It is a feature, not a bug. 😁

**Comment by goohegle** [comment]
谢谢楼上回复，刚发现这个情况，这个feature很容易误引发呀。再次感谢。

**Comment by yi-Xu-0100** [comment]
@goohegle 知道了之后，往右边点，误触就会小很多了，`v0.19.23`也很长的。🤣
