### ISSUE TITLE
[Bug]:无法使用共享代理

### ISSUE THREAD

**Issue by Ironman1231** [Fndroid/clash_for_windows_pkg#3188]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.22

### 操作系统

Windows x64

### 系统版本

19044.1766

### 问题描述

打开clash的Allow WLAN并且在手机里面设置好WiFi的代理，但是显示无互联网连接，刚开始以为是手机的问题，但是在ps上试了试发现也不行，请问是什么问题？

### 复现步骤

在clash客户端中打开Allow WLAN，并在手机设置里的互联网设置中的代理配置输入IP和端口，完成后显示无互联网连接，虽然可以依旧正常使用WiFi，但是翻不了墙

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
防火墙有没有开
