### ISSUE TITLE
[Bug]: 在线更新或下载后（非首次）安装，Clash for Windows 用户名下的 Country.mmdb 文件不能更新

### ISSUE THREAD

**Issue by AnyWAT** [Fndroid/clash_for_windows_pkg#3189]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.23

### 操作系统

Windows x64

### 系统版本

Windows 10 专业版 19044.1806

### 问题描述

在线更新或下载后（非首次）安装更新，Clash for Windows 在操作系统用户名下的 Country.mmdb 文件不能像 wintun.dll 一样更新

### 复现步骤

（非首次安装）安装较新版本的 Clash for Windows

**Comment by yi-Xu-0100** [comment]
新版 cfw 的 country.mmdb 有更新吗？

**Comment by AnyWAT** [comment]
从0.19.19开始用的，貌似在0.19.20就发现了有此问题，到0.19.23还是如此。

**Comment by AnyWAT** [comment]
在线更新的结果， Country.mmdb 文件仍然不能像 wintun.dll 一样更新

![image](https://user-images.githubusercontent.com/37962734/179156499-33301bf6-5e33-45a1-8a20-6f2f373eb995.png)

**Comment by yi-Xu-0100** [comment]
这个文件好像不会更新，就是给个默认的用，不会换，所以如果要更新得自己手动弄。

**Comment by AnyWAT** [comment]
谢谢！
知道能手动替换。
