### ISSUE TITLE
如何让不支持System Proxy的应用如Steam加入代理？

### ISSUE THREAD

**Issue by sceraser** [Fndroid/clash_for_windows_pkg#320]
Steam等没有自建代理也不支持系统代理的软件，怎么用CFW代理呢？

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/tap.html

**Comment by sceraser** [comment]
@Fndroid 
![image](https://user-images.githubusercontent.com/42718757/70848573-9881af00-1eae-11ea-8acd-377fbeb035c7.png)
没有理解说明文档的意思，"Fake IP"需要我手动去指定IP段吗？直接照抄说明文档的配置可以吗，还是需要修改什么呢？

**Comment by Fndroid** [comment]
直接照着写

**Comment by sceraser** [comment]
![image](https://user-images.githubusercontent.com/42718757/70979835-3c589e00-20ed-11ea-8682-3722780c12ca.png)

![image](https://user-images.githubusercontent.com/42718757/70979822-35319000-20ed-11ea-9ae9-f4836e1c81e3.png)
 TAP模式启用后，确定节点连接正常，Steam下载的流量已被正常导入Clash（可以在Clash网速统计里看到下载速度），但是社区依旧无法访问
@Fndroid

**Comment by Fndroid** [comment]
并不清楚steam具体工作原理，但是我建议你将dns中fallback那一部分去掉再试试

**Comment by sceraser** [comment]
发现是SteamCommunity_302软件把Steam社区地址屏蔽了，不是Clash的问题
![image](https://user-images.githubusercontent.com/42718757/74137257-6d0b0e80-4c2a-11ea-9be4-b94f6e35fdd3.png)
