### ISSUE TITLE
[Bug]: macOS Monterey dmg 报告损坏

### ISSUE THREAD

**Issue by Alendia** [Fndroid/clash_for_windows_pkg#3200]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.22, 0.19.23

### 操作系统

macOS arm64(M1,M1*)

### 系统版本

macOS Monterey 12.2.1

### 问题描述

在开启系统安装权限的情况下直接双击 dmg 出现 `"Clash.for.Windows.app" is damaged and can't be opend. You should move it to trash.` 。在 Terminal 下直接执行则可以正常打开，Terminal 未显示任何错误信息，此后退出再次双击能够正常打开。

```
cd /Applications/Clash \for \Windows.app
cd Contents/MacOS
./Clash \for \Windows
```
猜测是签名存在问题。

### 复现步骤

下载 v0.19.22 或者 v0.19.23 ARM64 dmg，在 Finder 中双击。

### 日志文件

因无法打开故不存在日志文件。

**Comment by yi-Xu-0100** [comment]
https://docs.cfw.lbyczf.com/contents/questions.html#macos-dmg-%E5%AE%89%E8%A3%85%E5%90%8E%E6%97%A0%E6%B3%95%E6%89%93%E5%BC%80-%E6%8F%90%E7%A4%BA%E6%8D%9F%E5%9D%8F

**Comment by Alendia** [comment]
> https://docs.cfw.lbyczf.com/contents/questions.html#macos-dmg-%E5%AE%89%E8%A3%85%E5%90%8E%E6%97%A0%E6%B3%95%E6%89%93%E5%BC%80-%E6%8F%90%E7%A4%BA%E6%8D%9F%E5%9D%8F

已尝试 xattr，无效。

**Comment by yann0917** [comment]
> https://docs.cfw.lbyczf.com/contents/questions.html#macos-dmg-%E5%AE%89%E8%A3%85%E5%90%8E%E6%97%A0%E6%B3%95%E6%89%93%E5%BC%80-%E6%8F%90%E7%A4%BA%E6%8D%9F%E5%9D%8F


有效
