### ISSUE TITLE
[Feature Request]: 日志过滤

### ISSUE THREAD

**Issue by hanrai** [Fndroid/clash_for_windows_pkg#3203]
### 功能描述

过滤日志内容，主要是忽略正常请求，保留错误日志。能自定义过滤就更好了，比如基于regex的过滤

**Comment by yi-Xu-0100** [comment]
不应该直接在文件编辑器里处理吗？

**Comment by hanrai** [comment]
> 不应该直接在文件编辑器里处理吗？
![微信截图_20220705175239](https://user-images.githubusercontent.com/7495736/177301997-ffd31323-c89d-4beb-86de-aaad2b2a86fb.png)
是这个Request Logs。我没有发现他有保存文件。
这个需求实际上是为了应对这种场景：打开TUN的时候会产生很多log，这时候某个应用出错了，想看看哪个连接出了问题，这时候早已经找不到出错的那条被刷到哪里去了。
有了过滤会方便很多。

**Comment by hanrai** [comment]
哦，找到了，谢谢！
