### ISSUE TITLE
General面板里的IPv6开关和Mixin配置文件里的IPv6：ture哪个是最上层的开关？

### ISSUE THREAD

**Issue by YirunFantasy** [Fndroid/clash_for_windows_pkg#3206]
理论上Mixin是优先级最高的，但是不确定，所以还是问一下作者，我的诉求是要打开IPv6开关。现在General面板开关是打开的，mixin里是false。是否需要修改mixin

**Comment by yi-Xu-0100** [comment]
1. mixin 配置是优先于 profile 的。
2. 而配置中根主键的 ipv6 不优先于 general 的 ipv6（个人猜测，因为我记得好像是 general 配置的都是根主键，不从 profile 读取）。
3. 然后 dns 里可以设置 ipv6 ，但与根主键的 ipv6 好像不一样。具体可看下官方的说明：<https://github.com/Dreamacro/clash/wiki/configuration>


如果是想打开，那就都设置为 true 为好。

**Comment by Fndroid** [comment]
不需要修改mixin，ipv6开关按general设置为准

**Comment by YirunFantasy** [comment]
> 1. mixin 配置是优先于 profile 的。
> 2. 而 profile 中根主键的 ipv6 不优先于 general 的 ipv6（个人猜测，因为我记得好像是 general 配置的都是根主键，不从 profile 读取）。
> 3. 然后 dns 里可以设置 ipv6 （我猜测你的 mixin 是用于加这个配置项），但与根主键的 ipv6 好像不一样。具体可看下官方的说明：<https://github.com/Dreamacro/clash/wiki/configuration>
> 
> 
> 如果是想打开，那就都设置为 true 为好。

谢谢，第三点很关键🤓

**Comment by YirunFantasy** [comment]
> 不需要修改mixin，ipv6开关按general设置为准

谢谢回复🤓

**Comment by YirunFantasy** [comment]
> 



> @YirunFantasy 为啥 dns 用 `[]` 包裹，不应该用 `''` 包裹吗

![微信截图_20220707210609](https://user-images.githubusercontent.com/88962428/177781560-97cdfa0d-c84c-4681-8a05-a0866ba02fc6.png)
![微信图片_20220707211037](https://user-images.githubusercontent.com/88962428/177781611-0138ed90-ef9d-4263-b5b7-f9c377ee5714.jpg)
谢谢耐心回复，[ ]是第一张截图里，wiki里说的，但是不管用，我又自己查了相关的问题，clash作者给别人的回复后面还加了端口号，然后引号标注（我是单引号，也能用），现在问题已经解决了，谢谢
