### ISSUE TITLE
[Bug]: vmess的h2协议证书校验问题

### ISSUE THREAD

**Issue by HelloWorld-create** [Fndroid/clash_for_windows_pkg#3207]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.23

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

出现问题的协议：vmess的h2协议
协议配置方式参考clash permium官网文档

国内机域名：cn.test.com
国外机域名：hk1.node.com
国外服务器申请证书的域名为为：hk1.node.com

中转节点信息如下：
{"name":"中继|NF|香港h2协议","type":"vmess","server":"cn.test.com","port":30597,"uuid":"4c5447be-af56-3278-bd40-7f4850888a03","alterId":0,"cipher":"auto","udp":true,"network":"h2","path":"/okok","h2-opts":null,"host":"hk1.node.com","tls":true}
直连节点信息如下：
{"name":"中继|NF|香港h2协议","type":"vmess","server":"hk1.node.com","port"398,"uuid":"4c5447be-af56-3278-bd40-7f4850888a03","alterId":0,"cipher":"auto","udp":true,"network":"h2","path":"/okok","h2-opts":null,"host":"hk1.node.com","tls":true}

以上两种情况下均校验的是server字段证书而不是host，所以导致直连节点能用中转节点不能用。grpc使用同样的配置逻辑没有问题，都是正常的均校验host字段的证书

这样做在跨境流量段会导致ssl证书和访问目标地址不一致

### 复现步骤

国内机域名：cn.test.com
国外机域名：hk1.node.com
国外服务器申请证书的域名为为：hk1.node.com

中转节点信息如下：
{"name":"中继|NF|香港h2协议","type":"vmess","server":"cn.test.com","port":30597,"uuid":"4c5447be-af56-3278-bd40-7f4850888a03","alterId":0,"cipher":"auto","udp":true,"network":"h2","path":"/okok","h2-opts":null,"host":"hk1.node.com","tls":true}
直连节点信息如下：
{"name":"中继|NF|香港h2协议","type":"vmess","server":"hk1.node.com","port"398,"uuid":"4c5447be-af56-3278-bd40-7f4850888a03","alterId":0,"cipher":"auto","udp":true,"network":"h2","path":"/okok","h2-opts":null,"host":"hk1.node.com","tls":true}

### 日志文件

<details><summary>logs</summary><p>

```
time="2022-07-07T17:40:58+08:00" level=warning msg="[TCP] dial 代理 (match IPCIDR/91.108.56.0/22) to 91.108.56.155:80 error: x509: certificate is valid for hk1.node.com, not cn.test.com"
```

</p></details>

**Comment by Fndroid** [comment]
clash core issue, refer: https://github.com/Dreamacro/clash/issues
