### ISSUE TITLE
安装0.8.6出现错误

### ISSUE THREAD

**Issue by suiahae** [Fndroid/clash_for_windows_pkg#321]
安装0.8.6出现错误
![image](https://user-images.githubusercontent.com/45323123/70796657-c8ad4d00-1ddd-11ea-87f3-9493a0418174.png)
尝试卸载旧版(0.8.5)出现错误
![image](https://user-images.githubusercontent.com/45323123/70796783-1924aa80-1dde-11ea-948f-7f0e724d786c.png)

请问直接删除CFW文件夹是否可以解决以上问题?

**Comment by Fndroid** [comment]
安装包没下载完整，重新下一个

**Comment by suiahae** [comment]
> 安装包没下载完整，重新下一个

同样安装失败. sha256校验结果与sha256sum文件显示一致

**Comment by Fndroid** [comment]
试试下载7z然后解压到安装目录覆盖

**Comment by suiahae** [comment]
> 试试下载7z然后解压到安装目录覆盖

7z解压覆盖后**CFW0.8.6运行正常**。但再次尝试使用`Clash.for.Windows.Setup.0.8.6.exe`覆盖安装失败。是不是以后只能下载7z解压覆盖了？

**Comment by Fndroid** [comment]
没有对安装包任何功能进行过调整，目前也暂时没有收到类似反馈，先观望一下

**Comment by suiahae** [comment]
> 没有对安装包任何功能进行过调整，目前也暂时没有收到类似反馈，先观望一下

![Snipaste_2019-12-13_19-23-15](https://user-images.githubusercontent.com/45323123/70797850-55f1a100-1de0-11ea-901a-749346c740ff.png)
之前尝试卸载时出现以上错误，安装失败是不是与此有关联呀？

**Comment by Fndroid** [comment]
可以试下删除如下文件夹重新安装：
1. 安装目录
2. C:\Users\<用户名>\AppData\Roaming\clash_win
3. C:\Users\<用户名>\AppData\Roaming\Clash for Windows
