### ISSUE TITLE
[Feature Request]: 自适应系统主题

### ISSUE THREAD

**Issue by Loongphy** [Fndroid/clash_for_windows_pkg#3213]
### 功能描述

# 当前功能
![image](https://user-images.githubusercontent.com/42089082/178109183-5dec3cc1-a455-40c1-91ca-196fc7368b11.png)
# 实现效果
提供一个跟随系统主题的选项，能够根据系统的亮暗自动切换主题。
效果如下：
![image](https://user-images.githubusercontent.com/42089082/178109158-df1da38c-681b-4a8d-b337-d3a32bd97f5c.png)

**Comment by Fndroid** [comment]
<img width="651" alt="image" src="https://user-images.githubusercontent.com/16091562/178127444-e567bb5c-80f8-44a8-b27c-23521a00f4c8.png">
