### ISSUE TITLE
[Feature Request]: 请支持多内核选择

### ISSUE THREAD

**Issue by fscarmen** [Fndroid/clash_for_windows_pkg#3215]
### 功能描述

由于要用 hysteria 协议，我手动更换了 clash meta 1.12 内核，具体做法是把 clash meta 的内核更换至以下路径
```
/Applications/Clash for Windows.app/Contents/Resources/static/files/darwin/x64/clash-darwin
```

已经可以使用了 hysteria了，但软件面板仍然未跟上，希望能在下个版本支持。

**Comment by yi-Xu-0100** [comment]
CFW 支持的是 premium core，其他的应该都不会支持。
