### ISSUE TITLE
[Feature Request]: 语言及配置文件

### ISSUE THREAD

**Issue by threerog** [Fndroid/clash_for_windows_pkg#3217]
### 功能描述

1.为什么官方不支持自带中文语言包
2.程序的配置文件以及clashcore等文件能不能直接在程序当前目录里存放，便于直接压缩打包 分享给别人呀
3.或者支持一键导出/导入完整配置备份

**Comment by yi-Xu-0100** [comment]
1. #999
2. https://docs.cfw.lbyczf.com/contents/7z.html
