### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Hugh08** [Fndroid/clash_for_windows_pkg#322]
请问F大能否考虑下，新增一个功能，proxy和direct流量统计。
在现有的版本中，统计的流量是所有经过clash的上传流量和下载流量，因为现大多数人使用的是机场提供的服务，如果在软件中能查看到代理使用的流量，最为方便，不用打开官网查看。
初步建议仅在总的流量统计基础上，增加两个分项，即通过proxy和direct的流量统计，后续可以再分细致点。

**Comment by jiaminxun** [comment]
这个功能好，希望加上

**Comment by UntaggedRui** [comment]
似乎是说这个东西clashx不支持所以做不了？不懂不懂

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
