### ISSUE TITLE
[Bug]: TUN模式微软商店无网络连接

### ISSUE THREAD

**Issue by xscit** [Fndroid/clash_for_windows_pkg#3220]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.23

### 操作系统

Windows x64

### 系统版本

Windows 11 Pro 22621.169

### TUN模式下微软商店、天气等微软应用提示没网；如果在设置里重置网络的话能正常十来分钟，随即又提示没网。
![Screenshot 2022-07-12 164829](https://user-images.githubusercontent.com/26691690/178450136-79595788-34f0-42a9-b670-7380b3fbefe7.png)
。

### 复现步骤

重置网络后能正常一会

### 日志文件

[2022-07-12-162244.log](https://github.com/Fndroid/clash_for_windows_pkg/files/9091277/2022-07-12-162244.log)

### 其他补充

tun mode默认配置，mixin和system proxy 均关闭，配置文件仅保留proxies/proxy-groups/rules

**Comment by xscit** [comment]
重置电脑后正常了😔

**Comment by danchaw** [comment]
只能重置电脑吗，我也遇到这个问题

**Comment by xscit** [comment]
重置网络后在secpol.msc和注册表里把WiFi和Clash的网络类型都改成public，然后重启貌似就正常了，有遇到这种情况的可以参考一下。
![Screenshot 2022-08-07 085852](https://user-images.githubusercontent.com/26691690/183270690-6f150709-e0f8-438b-ab41-ea66a44e0f3f.png)
![Screenshot 2022-08-07 090155](https://user-images.githubusercontent.com/26691690/183270787-b5196c7a-81b9-43ee-930b-ae7017fedd3a.png)
![Screenshot 2022-08-07 090250](https://user-images.githubusercontent.com/26691690/183270794-e743dba7-4754-4fc9-bb06-e0f8c8a6fcfa.png)
![Screenshot 2022-08-07 090306](https://user-images.githubusercontent.com/26691690/183270796-52b229dc-4195-48dc-8a49-87f8f35c6846.png)
