### ISSUE TITLE
[Bug]:  没有开tun时dns总是被重置为1.1.1.1

### ISSUE THREAD

**Issue by UntaggedRui** [Fndroid/clash_for_windows_pkg#3221]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.23

### 操作系统

macOS amd64(Intel)

### 系统版本

12.4 (21F79)

### 问题描述

使用时不开tun mode，不开启mixin，不开启system proxy(浏览器通过插件代理到7890端口使用clash)。但是dns总是被重置为1.1.1.1和114.114.114.114。可以手动改为223.5.5.5，也会生效也能够使用。但是不知道何时又会被更改为这两个默认的值。下面是正常使用时cfw的界面
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/28807947/178494489-29bbdd8a-f230-4bd0-926b-369ef7446f21.png">

<img width="668" alt="image" src="https://user-images.githubusercontent.com/28807947/178494847-135996a1-6c9a-448d-9bda-7a1b77c13eeb.png">
我是用的配置文件中关于dns的配置是这样的。但是上面也没有1.1.1.1啊

<img width="509" alt="image" src="https://user-images.githubusercontent.com/28807947/178495171-c4a0a21e-d4a1-4e6a-a0a9-03c76d925f31.png">
搜索到的issiue中也有反应这个问题的，是说tun的原因，但是我没有打开tun。
我的mixin的配置如下，但是我从来没有开启过mixin，因为我不需要用到tun mode。
<img width="622" alt="image" src="https://user-images.githubusercontent.com/28807947/178495403-a86db484-ae07-4e18-ae1f-4b4836b05791.png">

### 复现步骤

不知道如何复现。只知道某一段时间后系统中的dns会被重置为1.1.1.1和114.114.114.114。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by UntaggedRui** [comment]
平常需要在控制台(iterm2)中ssh到国外的机器，因为域名通过cf解析，这两个默认的dns无法解析只能添加223.5.5.5后才能ssh上去。但是一段时间后dns被改又无法ssh上去了。
issiue中类似的问题： #2469 
其他论坛中的相关讨论：https://www.v2ex.com/t/860627

**Comment by yi-Xu-0100** [comment]
把 listen 那行注释掉试试看还会不会修改。

**Comment by UntaggedRui** [comment]
> 把 listen 那行注释掉试试看还会不会修改。

好，已经注释掉了，今天看看情况。

**Comment by Fndroid** [comment]
mixin没开也要看配置文件里有没有写

**Comment by UntaggedRui** [comment]
> mixin没开也要看配置文件里有没有写

<img width="379" alt="image" src="https://user-images.githubusercontent.com/28807947/178647614-c5c60c4f-e379-4879-a58a-77ccedb13425.png">
现在配置文件是这样。2小时前采取楼上的建议注释listen，但是现在又被改为1.1.1.1和114.114.114.114了。
不知道是不是我更改后没有重启clash的原因，我现在再重启试一下。

**Comment by Fndroid** [comment]
你这配置文件里有没有配置tun这个字段

**Comment by UntaggedRui** [comment]
> 

<img width="736" alt="image" src="https://user-images.githubusercontent.com/28807947/178650027-8f977b03-69fa-4cc5-a1ad-6ea0090bf965.png">
没有。这是更详细的配置文件。之后就是proxy-providers:proxy-groups:rule-providers:rules:的相关配置了。

**Comment by UntaggedRui** [comment]
把listen注释掉，重启以后，今天一天dns都没有被修改了。看来还是这个dns配置会影响mac上的dns配置。不过[这里](https://www.v2ex.com/t/860627)说clashx没有这个问题，所以这种现象还是cfw导致的而不是上游导致的？
暂时先不用这个dns了。这个错误也不知道他发生在此刻，估计debug起来也蛮复杂的。

**Comment by meme-lau** [comment]
@UntaggedRui @Fndroid 我试过了上面的方法了，还是会被重置成1.1.1.1，和114.114.114.114，甚至我连dns配置都去除了，更没有开tun，每次只要配置文件一更新，就会被改掉dns，相当苦恼

**Comment by Fndroid** [comment]
@meme-lau 不一定只有mixin设置了dns，你的配置文件也可以原本就有
