### ISSUE TITLE
[Bug]: 点击关闭按钮无法缩放至系统托盘

### ISSUE THREAD

**Issue by feng-duo** [Fndroid/clash_for_windows_pkg#3226]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.23

### 操作系统

Windows x64

### 系统版本

win10 21H2

### 问题描述

点击关闭按钮只能最小化，且任务栏托盘不能显示软件图标

### 复现步骤

1、点击关闭按钮
![image](https://user-images.githubusercontent.com/46452340/178781677-0d2a96e2-2432-49e2-aa89-073533897aa9.png)
2、只能最小化，且系统托盘中无法操作软件
![image](https://user-images.githubusercontent.com/46452340/178782218-9a289ab5-b838-4bc4-af7e-bd3b9d1a5fd1.png)

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

尝试过卸载并清除配置和注册表，再次重装还是不能解决问题

**Comment by Fndroid** [comment]
平板吗？

**Comment by feng-duo** [comment]
> 

win10系统

**Comment by Fndroid** [comment]
是不是平板，或者触屏设备

**Comment by feng-duo** [comment]
台式机

**Comment by feng-duo** [comment]
台式机

**Comment by Shingkun** [comment]
更新新版本之后我也这样，点关闭直接退出不隐藏在右下角小图标那。
就算开启silent start，开机也是会弹出界面框。但是功能是正常能使用的

**Comment by Fndroid** [comment]
@Shingkun 你上个版本是哪个？

**Comment by Shingkun** [comment]
> @Shingkun 你上个版本是哪个？

你好，解决问题了。应该，是权限问题。解压在c盘programflies里面然后开启tun那个service就会出现这个问题。解压在其他盘符就不会出现这个问题。

**Comment by feng-duo** [comment]
@Shingkun 我的是解压在D盘，之前版本0.19.16没出现过这个问题，升级后就不行了，设置也没动过。
