### ISSUE TITLE
0.8.6报错，老版本没这问题

### ISSUE THREAD

**Issue by Darren-X1** [Fndroid/clash_for_windows_pkg#323]
<img width="1300" alt="截屏2019-12-1413 30 17" src="https://user-images.githubusercontent.com/51868406/70844152-d7e0d900-1e77-11ea-822c-3db803115eec.png">

**Comment by Fndroid** [comment]
Core不再支持chacha20加密，建议更换为其他加密方案

**Comment by Darren-X1** [comment]
大佬手回复真快
