### ISSUE TITLE
0.8.6版本遇到的一个错误

### ISSUE THREAD

**Issue by mikyan** [Fndroid/clash_for_windows_pkg#324]
![image](https://user-images.githubusercontent.com/32815180/70844835-cd2b4180-1e81-11ea-952b-c07d2c78d696.png)

似乎和站点的配置文件有关，但之前没遇到这个问题

**Comment by L1H0n9Jun** [comment]
chacha20 遇到相同的问题。

**Comment by Fndroid** [comment]
Duplicate of https://github.com/Fndroid/clash_for_windows_pkg/issues/323
