### ISSUE TITLE
[Bug]: clash开启tun模式后，大概率虚拟网卡显示无法连接网络，windows内的某些自带应用会报错，但其实网络正常

### ISSUE THREAD

**Issue by ericsyj** [Fndroid/clash_for_windows_pkg#3242]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.24

### 操作系统

Windows x64

### 系统版本

win10 21H2

### 问题描述

如题，开启tun模式后大概率虚拟网卡会显示无法连接网络：
![image](https://user-images.githubusercontent.com/97294040/179915803-00bd8379-fa28-410b-a90e-b69196484e4b.png)

换了一台笔记本测试也是这样，但是有时候开机的时候又会看到能虚拟网卡显示正常访问网络（但是概率很低），在虚拟网卡显示不能访问网络时，打开微软商店会报错：
![image](https://user-images.githubusercontent.com/97294040/179915569-372b86b7-9660-4959-b9bd-fd875c2925f8.png)

但其实是有网络的商店也可以正常更新，但就是一直会弹出报错窗口。
同时系统账户设置中的同步页面也显示无法连接网络：
![image](https://user-images.githubusercontent.com/97294040/179916211-715aaf74-189e-4ac0-83b3-11d1766489df.png)

浏览器和其他应用网络都是正常的，我也查看的几个类似的issues，以及也按照里面的回答设置了关闭windows的连通性检测，但是貌似这个对虚拟网卡并不生效，在 https://github.com/Dreamacro/clash/issues/1407#issue-892671385 看到了类似问题，但是按道理这边新版本应该早就修复了，不知道是不是哪里又出问题了，最近的几个版本都是这样，不过好在除了windows的自带应用其他并没有影响，我怀疑可能是windows自己的问题，反正只要虚拟网卡那边显示不能访问网络，不管物理网卡如何，win商店包括同步设置那里就报错，stack模式无论是gvisor还是system都一样。

### 复现步骤

打开tun模式即可复现。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
看看 tun mode 配置，有没有全选 uwploopback？

**Comment by ericsyj** [comment]
> 看看 tun mode 配置，有没有全选 uwploopback？

都选了，还是一样，主要是那个clash的虚拟网卡显示无网络访问权限，感觉和这个uwploopback没什么关系吧，tun模式已经接管系统所有流量了，选不选都是经过clash，我的微软商店不是不能联网，而是他一直弹出这个报错，你要是忽略它一直点×可以正常下载更新应用，感觉就是windows机制的锅，但是具体为什么虚拟网卡显示无网络就不知道了

**Comment by yi-Xu-0100** [comment]
关掉 allow lan 和 ipv6 试试

**Comment by ericsyj** [comment]
> 关掉 allow lan 和 ipv6 试试

试过了都一样，请问你那边是一切正常呢，就是那个虚拟网卡一直显示internet吗

**Comment by AkariiinMKII** [comment]
可能是DNS配置问题，例如在`nameserver`或`fallback`字段中配置了无法接通的doh时会导致系统无法检查联网状态

**Comment by yi-Xu-0100** [comment]
@ericsyj 我一直用的默认配置，一切正常。

**Comment by Ichigobai** [comment]
> > 关掉 allow lan 和 ipv6 试试
> 
> 试过了都一样，请问你那边是一切正常呢，就是那个虚拟网卡一直显示internet吗

我和你一样  就是无网络访问权限，怎么设置都不行，IP自动手动都设置过了， 其他的都是官方的配置

**Comment by ericsyj** [comment]
> 可能是DNS配置问题，例如在`nameserver`或`fallback`字段中配置了无法接通的doh时会导致系统无法检查联网状态

@AkariiinMKII @yi-Xu-0100  我这边就是不行，我也没有配置doh，就用默认配置也是一样：
![image](https://user-images.githubusercontent.com/97294040/179954239-0e9a0d67-6cc8-4b9d-b075-2a458f95892b.png)
![image](https://user-images.githubusercontent.com/97294040/179954301-615eda75-926b-47e1-a395-3a904001fa0b.png)
![屏幕截图 2022-07-20 175758](https://user-images.githubusercontent.com/97294040/179954749-24a9d0b9-d6c2-497b-bf4d-77e489a1e213.png)
![image](https://user-images.githubusercontent.com/97294040/179955014-9301892a-34b2-4d9c-90b4-53f70fb7e490.png)

疑难解答的诊断也是加载出错：
![image](https://user-images.githubusercontent.com/97294040/179955130-f2461083-966e-4c35-9832-ed79d6de2d2a.png)

网页什么的都没问题：
![image](https://user-images.githubusercontent.com/97294040/179955370-ded650e5-99d0-4750-9831-684fb1d2e815.png)

**Comment by Ichigobai** [comment]
> 可能是DNS配置问题，例如在`nameserver`或`fallback`字段中配置了无法接通的doh时会导致系统无法检查联网状态

  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback: []
这不都是默认的吗

**Comment by Ichigobai** [comment]
> @Ichigobai 你也是同样的问题吗？

而且我和你还不一样， 我的的无连接是啥都打不开 ，彻底断网的状态
@Fndroid

**Comment by Ichigobai** [comment]
> > > @Ichigobai 你也是同样的问题吗？
> > 
> > 
> > 而且我和你还不一样， 我的的无连接是啥都打不开 ，彻底断网的状态 @Fndroid
> 
> 你是不是没给clash-win64.exe的防火墙权限
我防火墙关了都不行。。

**Comment by AkariiinMKII** [comment]
> > 可能是DNS配置问题，例如在`nameserver`或`fallback`字段中配置了无法接通的doh时会导致系统无法检查联网状态
> 
> @AkariiinMKII @yi-Xu-0100 我这边就是不行，我也没有配置doh，就用默认配置也是一样： ![image](https://user-images.githubusercontent.com/97294040/179954239-0e9a0d67-6cc8-4b9d-b075-2a458f95892b.png) ![image](https://user-images.githubusercontent.com/97294040/179954301-615eda75-926b-47e1-a395-3a904001fa0b.png) ![屏幕截图 2022-07-20 175758](https://user-images.githubusercontent.com/97294040/179954749-24a9d0b9-d6c2-497b-bf4d-77e489a1e213.png) ![image](https://user-images.githubusercontent.com/97294040/179955014-9301892a-34b2-4d9c-90b4-53f70fb7e490.png)
> 
> 疑难解答的诊断也是加载出错： ![image](https://user-images.githubusercontent.com/97294040/179955130-f2461083-966e-4c35-9832-ed79d6de2d2a.png)
> 
> 网页什么的都没问题： ![image](https://user-images.githubusercontent.com/97294040/179955370-ded650e5-99d0-4750-9831-684fb1d2e815.png)

看一下tun网卡的详细状态，另外检查一下`connections`列表里面有没有出现`TUN`类型的连接

**Comment by ericsyj** [comment]
@AkariiinMKII connections里显示是tun类型的连接，tcp和udp都有，墙内外网站都正常访问，唯独某些windows自带服务不行，有些系统内的登陆微软账号的操作就登不了，总是说无法连接网络，但是微软商店什么的有时虽然报错但是可以下载更新，然后系统更新检测也没问题，然后我另外一台笔记本连着WiFi，clash同样的配置，一开始是clash网卡显示不能联网，症状就和我这个台式机一样，后来过了很久再去看了一下发现居然显示internet连接了，我发现只要clash虚拟网卡那边显示internet连接那么所有这些都会变正常。

**Comment by AkariiinMKII** [comment]
> @AkariiinMKII connections里显示是tun类型的连接，tcp和udp都有，墙内外网站都正常访问，唯独某些windows自带服务不行，有些系统内的登陆微软账号的操作就登不了，总是说无法连接网络，但是微软商店什么的有时虽然报错但是可以下载更新，然后系统更新检测也没问题，然后我另外一台笔记本连着WiFi，clash同样的配置，一开始是clash网卡显示不能联网，症状就和我这个台式机一样，后来过了很久再去看了一下发现居然显示internet连接了，我发现只要clash虚拟网卡那边显示internet连接那么所有这些都会变正常。

这个和window的网络状态检测周期有关，我比较推荐能用uwploopback的先用uwploopback

**Comment by ericsyj** [comment]
发现规律了，电脑得开机好一段时间clash的虚拟网卡才能显示internet访问，刚刚放了一个小时没动它就好了：
![image](https://user-images.githubusercontent.com/97294040/179988002-0fcda04e-fbc6-44f3-ad75-5cb4d58c600b.png)

这应该是windows网络连接状态检测机制的问题，目前我这边通过更改注册表对应项这些方法来关闭检测感觉并不管用，不知道能不能具体找到windows的具体网络刷新的服务项，然后手动或者用脚本及时的更新一下状态。

**Comment by ericsyj** [comment]
找到原因了，貌似是现在微软的ncsi的检测地址有点问题不知道是被墙了还是怎么样，我看了一下在我这边[ipv6.msftconnecttest.com](url)这个地址是根本解析不到的，而[www.msftconnecttest.com](url)这个地址非常不稳定，ping不通的概率很高，所以很容易检测失败（反正我是只要开了tun模式就失败，但是放一会也可能成功，这也印证了上面的现象），我目前是下载了这个工具[https://crazymax.dev/WindowsSpyBlocker/download/](url)，里面有一个更改ncsi查询地址的功能（具体可以看官网的文档），可以一键更改ncsi查询地址，我目前改为了Firefox的地址，然后记得在`dns`里面的`fake-ip-filter`中添加对应地址，然后就一切正常了，或者可以在注册表`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet`目录下手动更改下面几项为下图所示（最好备份一下原来的注册表）：
![屏幕截图 2022-07-20 215543](https://user-images.githubusercontent.com/97294040/180000287-ddc0eb74-2275-491d-afc7-f7bb25e1c2af.png)
然后重启就行了。

**Comment by Ichigobai** [comment]
> 找到原因了，貌似是现在微软的ncsi的检测地址有点问题不知道是被墙了还是怎么样，我看了一下在我这边[ipv6.msftconnecttest.com](http://ipv6.msftconnecttest.com)，这个地址是根本解析不到的，而[www.msftconnecttest.com](http://www.msftconnecttest.com/)这个地址非常不稳定，ping不通的概率很高，所以很容易检测失败（反正我是只要开了tun模式就失败，但是放一会也可能成功，这也印证了上面的现象），我目前是下载了这个工具[crazymax.dev/WindowsSpyBlocker/download/](https://crazymax.dev/WindowsSpyBlocker/download/)，里面有一个更改ncsi查询地址的功能（具体可以看官网的文档），可以一键更改ncsi查询地址，我目前改为了Firefox的地址，然后记得在`dns`里面的`fake-ip-filter`中添加对应地址，然后就一切正常了，或者可以在注册表`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet`目录下手动更改下面几项为下图所示（最好备份一下原来的注册表）： ![屏幕截图 2022-07-20 215543](https://user-images.githubusercontent.com/97294040/180000287-ddc0eb74-2275-491d-afc7-f7bb25e1c2af.png) 然后重启就行了。

  我按照你这个修改了还是不行
![image](https://user-images.githubusercontent.com/109598121/180041905-66367879-41d2-4a09-9627-c6d4a6206f32.png)

**Comment by Ichigobai** [comment]
> @Ichigobai 你这个完全不能上网和我这个情况还不太一样，你先解决上网的问题，看看其他issue
 
其他issue看过了 只有一个人和我一样 但是到最后也没解决。我人麻了

**Comment by lengxii** [comment]
我解决了，本地网线连接 名称是以太网，一直连不上网，我把名称改成WLAN 无线 ipv4 连上了，不知道是啥原因

**Comment by Mmx233** [comment]
我跟着改或者用 WindowsSpyBlocker 改都没用。最后手动对比了一下注册表，发现 EnableActiveProbing 是 0，改成 1 就正常了

**Comment by 466494ghs** [comment]
解决了，重装系统，不要更新系统就行了...

**Comment by 466494ghs** [comment]
> > @Ichigobai你这个完全不能上网而我这个情况还不太一样，你先解决了网上的问题，看其他issue
> 
> 其他问题看过了只有一个人和我一样但是到最后也没解决。我人麻了

我重装了一下系统解决了，别更新就行

**Comment by Wind-177** [comment]
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/111582945/6a74d6b4-d72d-4d80-b267-815ac2426ce0)
我把这两项移除后，等了几分钟就好了。但不是立即生效，要等一会，那个连接指示器是开着的

**Comment by MinMie531** [comment]
> ![image](https://user-images.githubusercontent.com/111582945/240857840-6a74d6b4-d72d-4d80-b267-815ac2426ce0.png) 我把这两项移除后，等了几分钟就好了。但不是立即生效，要等一会，那个连接指示器是开着的

解决了

**Comment by kingcard1131** [comment]
不要重装系统，高级网络设置里面--网络重置可以解决问题

**Comment by luck-lienji** [comment]
1、微软自带的 UWP 应用，例如 wsl、便笺、应用商店等 无法访问网络问题的解决办法
1.1、必要条件 UWP Loopback 开启，自行百度，把里面所有的软件勾选即可，此项是必须的，（PS：Clash 自带的过UWP 应用的软件（EnableLoopback.exe）可能无法获取应用列表，可以尝试将其替换掉。
1.2、是否开启了 Service Mode 、TUN Mode ，（这俩是绑定的一开具开），开的话，将  TUN Mode   里面的如下俩个配置去掉，借鉴楼上老哥的话 @Wind-177  :  *.msftncsi.com   、 *.msftconnecttest.com   ，若未开  Service Mode 与 TUN Mode 的话仍然连不上网络，可以尝试着按照以上步骤开启
1.3、clash 设置后需要重新启动该软件
1.4、clash：版本： v0.20.37  
[EnableLoopback.zip](https://github.com/Fndroid/clash_for_windows_pkg/files/12853521/EnableLoopback.zip)

**Comment by YXH-VIKI** [comment]
提供一个可能性，就是rule provider规则可能导致TUN网卡不发起网络连接状态查询（表现为日志中没有www.msftncsi.com请求）。
我删除rule provider后，就能够发起查询（日志中有www.msftncsi.com）。
而且很奇怪的是，删除一部分特点的rule provider后，可以发起查询，但是加上某些规则组就不行。更奇怪的是这不是百分百发生的事件。
不过只要删除rule provider整个部分，就必定能够发起查询。这是在我的环境下测试的结果，供各位参考。
