### ISSUE TITLE
[Bug]: Win 11 WSL (Ubuntu) 不能使用代理

### ISSUE THREAD

**Issue by Rubp-007** [Fndroid/clash_for_windows_pkg#3245]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.24

### 操作系统

Windows x64

### 系统版本

win11 21H2

### 问题描述

Clash 启动后浏览器能正常访问 google 和 github. 但 WSL 中不能 ping 通.

当前配置:
- Clash 中选择了 System Proxy
- Clash 中选择了 Allow LAN
- Clash 中 UWP Loopback 勾选了 Ubuntu
- 其他配置均使用默认值

### 复现步骤

1. 启动 Clash
2. 启动浏览器, 访问 google 和 github, 均可打开
3. 启动 WSL Ubuntu
4. ping google.com 或 ping github.com 均无反应 (ping baidu.com 正常)

### 日志文件
日志中没有 Ubuntu 访问 google 或 github 的记录.
<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

已尝试使用 [#372](https://github.com/Fndroid/clash_for_windows_pkg/issues/372) 中的方法, 在 WSL Ubuntu 中执行
```
export hostip=$(cat /etc/resolv.conf |grep -oP '(?<=nameserver\ ).*');
export https_proxy="http://${hostip}:7890";
export http_proxy="http://${hostip}:7890";
export all_proxy="socks5://${hostip}:7891";
``` 
并再次 ping google.com. 依旧没有反应

**Comment by Lemmingh** [comment]
用 `curl` 测连通性。

不要用 `ping`。你目前设置的是 proxy （代理）。而 `ping` 会自己开一个 raw socket，无视 proxy，这是由工作原理决定的。

**Comment by Rubp-007** [comment]
> 用 `curl` 测连通性。
> 
> 不要用 `ping`。你目前设置的是 proxy （代理）。而 `ping` 会自己开一个 raw socket，无视 proxy，这是由工作原理决定的。

谢谢指出. 我修改下原帖. 这是我刚测试了 curl 的输出, 也是不能使用代理.
```
$ curl www.google.com -v                                                                                                                                                                                        
*   Trying 108.160.169.54:80...
*   Trying 2001::1f0d:5332:80...
* Immediate connect fail for 2001::1f0d:5332: Network is unreachable
```
