### ISSUE TITLE
[Bug]: TUN模式下，其他设备共享局域网，显示无法连接网络

### ISSUE THREAD

**Issue by gaoyadian198** [Fndroid/clash_for_windows_pkg#3247]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

v 0.19.23  以及 v 0.19.24

### 操作系统

Windows x64

### 系统版本

Windows 11 专业版  21H2

### 问题描述

TUN模式开启，Allow LAN开启，PC网络访问正常。
手机或其他设备与PC连接同一wifi，在连接的wifi中设置手动代理，输入PC的IP地址和7890端口，显示无法连接网络。

### 复现步骤

两台不同的PC在各自的wifi下均出现上述问题。
第一台PC之前正常，手机、VR一体机均可以通过PC的局域网共享访问外网，但PC重启后出现问题，找来新的PC测试，问题复现。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```
[2022-07-21-133319.log](https://github.com/Fndroid/clash_for_windows_pkg/files/9156882/2022-07-21-133319.log)

</p></details>

**Comment by yi-Xu-0100** [comment]
日志全是 ip ，贴一下 tun 配置看看。

**Comment by gaoyadian198** [comment]
是这个吗？
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback: []
  fake-ip-filter:
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
tun:
  enable: true
  stack: gvisor
  auto-detect-interface: true
  auto-route: true
  dns-hijack:
    - 198.18.0.2:53
> 日志全是 ip ，贴一下 tun 配置看看。

**Comment by yi-Xu-0100** [comment]
看看这个  https://github.com/Fndroid/clash_for_windows_pkg/issues/3242#issuecomment-1190321276

**Comment by gaoyadian198** [comment]
> 看看这个 [#3242 (comment)](https://github.com/Fndroid/clash_for_windows_pkg/issues/3242#issuecomment-1190321276)

我的问题跟这个不一样，我的情况是PC可以正常上网，内外网都没问题，但就是不能让其他设备共享PC的局域网。
虽然我也碰到 #3242 里边讲的问题，但是我发现不影响使用，就没管他了。

**Comment by yi-Xu-0100** [comment]
@gaoyadian198 看看防火墙放行

**Comment by gaoyadian198** [comment]
> @gaoyadian198 看看防火墙放行

我不太会设置，按照这个来可以吗？
https://www.xinnet.com/service/cjwt/idc/jishu/1745.html#:~:text=Windows%E7%B3%BB%E7%BB%9F%E5%A6%82%E4%BD%95%E9%80%9A%E8%BF%87%E9%98%B2%E7%81%AB%E5%A2%99%E6%94%BE%E8%A1%8C%E6%88%96%E9%98%BB%E6%96%AD%E7%AB%AF%E5%8F%A3.%201.%E5%8D%95%E5%87%BB%E5%BC%80%E5%A7%8B%3E%E6%8E%A7%E5%88%B6%E9%9D%A2%E6%9D%BF%3E%20%E7%B3%BB%E7%BB%9F%E5%92%8C%E5%AE%89%E5%85%A8%20%3E,Windows%20%E9%98%B2%E7%81%AB%E5%A2%99%EF%BC%8C%E5%8D%95%E5%87%BB%E5%B7%A6%E4%BE%A7%E5%AF%BC%E8%88%AA%E7%AA%97%E6%A0%BC%E9%AB%98%E7%BA%A7%E8%AE%BE%E7%BD%AE%E3%80%82.%202.%E7%82%B9%E5%87%BB%E5%85%A5%E7%AB%99%E8%A7%84%E5%88%99%3E%E6%96%B0%E5%BB%BA%E8%A7%84%E5%88%99%E3%80%82.%203.%E5%8B%BE%E9%80%89%E7%AB%AF%E5%8F%A3%EF%BC%8C%E7%82%B9%E5%87%BB%E4%B8%8B%E4%B8%80%E6%AD%A5%E3%80%82.

**Comment by gaoyadian198** [comment]
估计我弄得不对，不管用。 @yi-Xu-0100

**Comment by gaoyadian198** [comment]
![image](https://user-images.githubusercontent.com/109715675/180179716-1ea70da5-5a58-4efd-8bbb-ca6414b3a116.png)
这是clash的入站规则，所有端口都是允许的。

**Comment by yi-Xu-0100** [comment]
控制面板 系统与安全 windows防火墙 允许的程序 

增加 clash-win64.exe 和 cfw ，公用私用都打勾

**Comment by gaoyadian198** [comment]
我这样设置的，对吧？但是不管用...... @yi-Xu-0100 
![image](https://user-images.githubusercontent.com/109715675/180198361-992f09bd-681a-40c1-ba16-c55af82b77f9.png)

**Comment by gaoyadian198** [comment]
你让我看防火墙放行的时候，就已经把专用、公用都打钩了。

> @gaoyadian198 看看防火墙放行

**Comment by yi-Xu-0100** [comment]
@gaoyadian198 增加 clash-win64.exe ，公用私用都打勾

**Comment by gaoyadian198** [comment]
还是不行
![image](https://user-images.githubusercontent.com/109715675/180211000-f81be191-d724-43ae-be06-51a5292845d8.png)


> @gaoyadian198 增加 clash-win64.exe ，公用私用都打勾

**Comment by yi-Xu-0100** [comment]
https://docs.cfw.lbyczf.com/contents/questions.html#%E5%9C%A8-windows-%E7%B3%BB%E7%BB%9F%E4%B8%AD-tun-%E6%A8%A1%E5%BC%8F%E4%B8%8B%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8%E7%83%AD%E7%82%B9%E5%88%86%E4%BA%AB%E5%8A%9F%E8%83%BD

**Comment by gaoyadian198** [comment]
> https://docs.cfw.lbyczf.com/contents/questions.html#%E5%9C%A8-windows-%E7%B3%BB%E7%BB%9F%E4%B8%AD-tun-%E6%A8%A1%E5%BC%8F%E4%B8%8B%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8%E7%83%AD%E7%82%B9%E5%88%86%E4%BA%AB%E5%8A%9F%E8%83%BD

谢谢！终于可以了！我明白了其中的逻辑。tun模式虚拟出来的网卡，共享给热点用，所以连接这个热点就可以通过TUN翻墙了。
但是我有两个疑问：
1、如果我重启电脑，是不是要重新启用热点？以至于连接热点的N个设备都要重新输入一遍自动生成的热点密码？如果是这样的话，比设置手动代理麻烦多了。
2、之前手动设置代理一切正常，为什么重启电脑后就出问题了。

**Comment by yi-Xu-0100** [comment]
1. 热点是 windows 的功能。不确定怎么设置，需要自行查找可设置功能。
2. 我不清楚，玄学 Windows

**Comment by gaoyadian198** [comment]
> 1. 热点是 windows 的功能。不确定怎么设置，需要自行查找可设置功能。
> 2. 我不清楚，玄学 Windows

无论如何，谢谢你的耐心回答！我再跟你讲个玄学的事，就在刚才我重启了一下电脑，是为了看看热点的问题。之前还有一个我没跟你说明情况，之前我电脑正常的时候连接的是5G频段的WiFi，手动设置代理就没有问题。今天出问题，是因为5G频段的WiFi没有了，我连的是2.4G频段的，但刚才重启之后5G频段的WiFi又出现了，所以手动设置代理又可以了。虽然不知道手动代理成功跟连接5G频段WiFi是否有因果关系，但总之一切正常了。明天我再去看一看我今天用来测试的机子好，测试的机子根本就没有成功过，今天也一直连接的是5G频段的WiFi。

**Comment by gaoyadian198** [comment]
这会儿我回家了，白天一直是用测试的PC，现在用的是原来的PC。

**Comment by gaoyadian198** [comment]
我又来提问了~
现在我用的是测试的PC，昨天的PC已经完全正常了。
目前这台PC的情况是：共享热点的方式可以连网；局域网手动设置代理还是无法连接网络；选择添加防火墙放行的软件中，没有clash-win64.exe可供选择。昨天的PC原本就有那一项，因此无需添加。
![image](https://user-images.githubusercontent.com/109715675/180351831-cf8fbd1a-b898-4ac1-bfec-11024f10ede1.png)

**Comment by yi-Xu-0100** [comment]
@gaoyadian198 在文件夹里找找，可以先自己搜索下

**Comment by gaoyadian198** [comment]
> @gaoyadian198 在文件夹里找找，可以先自己搜索下

ok！找到了！感谢！这台PC也可以正常使用了。问题就出在了防火墙上。此问题完结！留给有同样问题的朋友作参考吧~
TIPS：clash-win64.exe的文件路径：Clash\resources\static\files\win\x64

**Comment by Agan42** [comment]
正解，非常有用

**Comment by lionkingc** [comment]
请问下如果PC只有一条网线接到老路由上,怎么实现跟你一样的通过TUN共享给其他设备上网, 
PC上有VM,想给VM里的系统和应用程序共享上网

**Comment by kokoro-o** [comment]
> [https://docs.cfw.lbyczf.com/contents/questions.html#%E5%9C%A8-windows-%E7%B3%BB%E7%BB%9F%E4%B8%AD-tun-%E6 %A8%A1%E5%BC%8F%E4%B8%8B%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8%E7%83%AD%E7%82 %B9%E5%88%86%E4%BA%AB%E5%8A%9F%E8%83%BD](https://docs.cfw.lbyczf.com/contents/questions.html#%E5%9C%A8-windows-%E7%B3%BB%E7%BB%9F%E4%B8%AD-tun-%E6%A8%A1%E5%BC%8F%E4%B8%8B%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8%E7%83%AD%E7%82%B9%E5%88%86%E4%BA%AB%E5%8A%9F%E8%83%BD)

谢谢，看了你的回答，我解决了这个问题。
