### ISSUE TITLE
[Bug]: 在Windows 10系统上出现一系列复杂问题

### ISSUE THREAD

**Issue by greenredstone** [Fndroid/clash_for_windows_pkg#3249]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.24及0.19.25

### 操作系统

Windows x64

### 系统版本

Windows 10 家庭中文版 21H2

### 问题描述

一系列问题：
1.下载arm64安装程序进行安装，显示为安装完成但是安装目录只有卸载程序。
2.下载arm64压缩包解压使用提示“不支持的系统版本”。
3.下载ia32安装包及压缩包能够正常打开主程序，但是“failed to load clash core”，需要将core替换为amd64版本才能正常运行

### 复现步骤

如问题描述

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by greenredstone** [comment]
> 为啥用arm版本？确认是arm的？不是用amd的吗？

打错了，抱歉

**Comment by yi-Xu-0100** [comment]
那说明你的电脑就是应该用 amd 的啊？为啥用 arm 的？
