### ISSUE TITLE
[Bug]: 设置开机启动后，重启电脑打开 Calsh，开机启动设置为关闭状态

### ISSUE THREAD

**Issue by DustinWin** [Fndroid/clash_for_windows_pkg#3253]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.25

### 操作系统

Windows x64

### 系统版本

Windows 11 22622.436

### 问题描述

将 Clash 设置为开机启动，重启后 Clash 能够跟随开机启动，但打开 Clash 却发现开机启动设置为关闭状态。
![QQ截图20220722222223](https://user-images.githubusercontent.com/45238096/180461073-91bbafff-c3df-4b42-b042-6244378ed126.png)

### 复现步骤

1. 进入 Clash，将“Start with Windows”设置为开启状态；
2. 重启电脑，Clash 可以跟随开机启动；
3. 打开 Clash，查看“Start with Windows”设置状态。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
检查系统的启动项设置，是否有多个

**Comment by DustinWin** [comment]
> 检查系统的启动项设置，是否有多个

感谢回复，我似乎找到问题所在了，我在使用 0.19.25 版本时是直接导入 0.19.24 版本的配置（C:\Users\[用户名]\.config\clash）。我将 0.19.25 版本卸载重装并重新配置后就完全正常了。
