### ISSUE TITLE
[Bug]: 关闭系统代理之后无法访问b站直播频道，开启代理后可以正常访问但是起始阶段加载activity.hdslb.com:443时日志提示timeout

### ISSUE THREAD

**Issue by chasinglightx64** [Fndroid/clash_for_windows_pkg#3257]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.25

### 操作系统

Windows x64

### 系统版本

Windows 10

### 问题描述

关闭系统代理之后无法访问b站直播频道，开启代理后可以正常访问但是起始阶段加载activity.hdslb.com:443时日志提示timeout
![A6 JAF~L__C4JW@5W888`U](https://user-images.githubusercontent.com/62205441/180660228-b9732135-5e37-4a03-843e-1629a56e2644.png)

卸载clash后无法恢复，重置网络无法恢复，关闭clash重启电脑无法恢复
无论是直连还是规则都是一样，不开启系统代理直接无法访问

### 复现步骤

关闭系统代理之后无法访问b站直播频道，开启代理后可以正常访问但是起始阶段加载activity.hdslb.com:443时timeout

### 日志文件

<details><summary>logs</summary><p>
[2022-07-25-013910.log](https://github.com/Fndroid/clash_for_windows_pkg/files/9176377/2022-07-25-013910.log)

</p></details>

**Comment by yi-Xu-0100** [comment]
关闭代理都不行，很难不让怀疑你本身的网络情况了

**Comment by chasinglightx64** [comment]
今天用另一台电脑在公司网打开b站直播网页，确实是网络问题，因为公司网也打不开^^'，蚌埠住了，麻烦你了
