### ISSUE TITLE
网关模式

### ISSUE THREAD

**Issue by CoolPlayLin** [Fndroid/clash_for_windows_pkg#3259]
### 功能描述

希望CFW能实现像ClashX那样的网关模式，接管局域网内所有流量

**Comment by yi-Xu-0100** [comment]
allow lan + tun mode

**Comment by itKelis** [comment]
开启allow lan之后在其他设备上设置代理，就好了

**Comment by CoolPlayLin** [comment]
> 开启allow lan之后在其他设备上设置代理，就好了

可以代理Googe Play么

**Comment by CoolPlayLin** [comment]
?

**Comment by yi-Xu-0100** [comment]
@CoolPlayLin allow lan 允许其他设备走这个设备的代理，tun mode 接管所有流量
