### ISSUE TITLE
[Feature Request]: 建議增加為某個軟件單獨開啓TUN模式

### ISSUE THREAD

**Issue by tlerbao** [Fndroid/clash_for_windows_pkg#3263]
### 功能描述

我有個軟件必須開啓TUN模式才能更新和使用，但是另一個需要同時開的游戲如果開TUN就會上不去。

希望可以為某個軟件單獨設置TUN模式，或者TUN模式有白名單或黑名單？

**Comment by yi-Xu-0100** [comment]
process-name rule 规则代理整个软件试试

**Comment by tlerbao** [comment]
@yi-Xu-0100 能詳細點嗎，請問在哪裏設置？萬分感謝。

**Comment by yi-Xu-0100** [comment]
@tlerbao 不使用 tun 模式接管全局，而是使用 rule 规则，其中有个 process-name 能接管整个 软件，具体找下 clash wiki 看下，可以试试

**Comment by YirunFantasy** [comment]
有两个方法，一个一劳永逸，另一个可能每更新一次你都要重新设置，但是都不难。
1：通过“配置文件预处理”
右键你的配置文件，点击Parsers，然后选择Edit Parsers，进入编辑界面，相关截图给你参考一下
![11](https://user-images.githubusercontent.com/88962428/180923284-8c6efd9f-b42f-45b7-b42d-f963f89e9749.png)
![13](https://user-images.githubusercontent.com/88962428/180923320-72ebc33b-6d7c-46d8-a857-b52b4077e67f.png)
如图呢，你在规则里自己添加一行**PROCESS-NAME, QQ.exe, Proxy**（这只是我给你举了个例子，你的软件名字叫什么自己改，后面的Proxy就是你给它定的让它走代理的意思），软件名字建议通过windows的进程管理器查看你需要改的那个软件的真实的进程名字，不要想当然的输入常用名。
输入完后，保存，更新一下配置文件就可以了（还是第一步你右键点击的那个配置文件，配置文件上不是一个更新的原型箭头按钮吗，你点击，更新一下，相应的规则就会添加进去生效了）
一劳永逸。
2：不会搞配置文件，那就用最笨的方法，手动添加规则。
还是右键配置文件，选择Rules，然后点击右上角的Add，就出现相应的规则界面
![21](https://user-images.githubusercontent.com/88962428/180924083-dcb1e528-61a2-4453-b964-0e89bdea1eb1.png)
![22](https://user-images.githubusercontent.com/88962428/180924097-a40426c7-d24d-4548-9bc2-befe4e766874.png)
![23](https://user-images.githubusercontent.com/88962428/180924107-8e2bbabe-5a07-47b6-a72f-a0a692346696.png)
如图，你看我圈了一个圆圈和方框，都用蓝色箭头标识了，上面圆圈里就是填写你要改的那个软件进程的名字，下面方框就是表示这是按照进程名字识别的，选择好之后，鼠标滚轮下滑
![24](https://user-images.githubusercontent.com/88962428/180924281-7c57f90c-3112-48fc-b6c7-00c8d112aa00.png)
这时你能看见不同的策略，直连，代理，阻断，甚至你还可以看到你的所有节点，选择代理就行（用的节点就是你全局用的那个节点），或者你还可以选择某个节点让它指定某个节点来走代理，很方便是吧
![微信截图_20220726124204](https://user-images.githubusercontent.com/88962428/180924754-325e9001-0d5a-464b-afd5-e842d72b26a1.png)
然后一切都搞完之后，**记得点击右上角的Add把这个规则添加进去，再然后记得点击右上角的Save按钮保存**，就可以了。
这个方法比较直观，但是切记，你每次点击更新配置文件的时候，有可能会被覆盖，如果哪天发现没有了，你还得手动再来一遍，没什么事尽量不要更新配置文件

**Comment by 2-3-5-7** [comment]
> @tlerbao 不使用 tun 模式接管全局，而是使用 rule 规则，其中有个 process-name 能接管整个 软件，具体找下 clash wiki 看下，可以试试

兄弟你试过吗？
我这里不开 tun，process-name 规则无法生效的啊

**Comment by yi-Xu-0100** [comment]
@2-3-5-7 

![图片](https://user-images.githubusercontent.com/25523606/181402075-00342f9f-ecb4-4896-9451-0e9165d7190d.png)

**Comment by 2-3-5-7** [comment]
你这也太搞笑了，要是软件已经能指定 socks 或 http 代理了，楼主把软件配置成 clash 的代理端口不就行了，还使用 process-name 匹配干嘛？
这个问题的意思是，不开全局的 tun、不设置 clash 代理端口，怎么让某个进程用代理。

**Comment by yi-Xu-0100** [comment]
@2-3-5-7 嗯，我审题不清了。

@tlerbao 这里如果你一定要开启 tun 去接管某一个软件的更新，那对于无法有效工作的软件，尝试使用 process-name 规则匹配后走直连，将所有请求的域名或者 ip 加入 fake-ip-filter 试试，其他我也没太有办法了。

**Comment by Fndroid** [comment]
建议先了解下什么是tun再提建议

**Comment by Fndroid** [comment]
你不了解你当然可以问，但你不了解你直接提建议是不是有点问题？

你没有先问能不能实现，而是建议加这个加哪个。

我建议你先了解一下再建议有问题吗？我认为不能实现并且在你不了解的情况下没有讨论的必要了还不能close吗？

上升到“国内的人”和“免费软件”有什么必要呢。

**Comment by tlerbao** [comment]
@Fndroid 

我其实没在提建议，就是不知道怎么实现我想要的来提问，假设性的说了说。

你们的issues只有两个分类，功能建议 & BUG反馈，我只能发到功能建议里。

当然了，你的rep，随便close，我一点脾气没有哈。打扰了。

还是感谢提供这么优秀的软件免费使用。

**Comment by 2-3-5-7** [comment]
额，你这误会了，搞笑是说回答你的人没理解你的意思，没说你呀，不用这么敏感。而且后来人家给出正确的方法了，给受影响的进程添加一条直连的规则。

如果你想只给某些进程配置代理，这其实是 rule 里的逻辑非，即除某进程外都直连。就要用到 clash 的 script 模式。
在开启 TUN 模式后，用类似 python 的脚本判断进程名，不在你定义的列表内，都返回 DIRECT。

**Comment by tlerbao** [comment]
> 额，你这误会了，搞笑是说回答你的人没理解你的意思，没说你呀，不用这么敏感。而且后来人家给出正确的方法了，给受影响的进程添加一条直连的规则。
> 
> 如果你想只给某些进程配置代理，这其实是 rule 里的逻辑非，即除某进程外都直连。就要用到 clash 的 script 模式。 在开启 TUN 模式后，用类似 python 的脚本判断进程名，不在你定义的列表内，都返回 DIRECT。

@2-3-5-7 
嗯，感谢，我这两天在Mac下弄点东西，还没回到Windows弄这个问题，等我测试上面的方法后还要再来请教。万分感谢。

**Comment by tlerbao** [comment]
![image](https://user-images.githubusercontent.com/20442232/181914102-5ac0f2e0-edfd-4f82-899f-76c752330375.png)

我這個軟件運行後大概是這樣的，設置這樣的規則似乎不行，請問，那一串隨機字符串每次運行都不一樣，我這種情況要怎麽辦呢？

@yi-Xu-0100 @2-3-5-7 @YirunFantasy 
PROCESS-NAME, Geforce Experience, Proxy

**Comment by YirunFantasy** [comment]
![20220731_110613.png](https://user-images.githubusercontent.com/88962428/182008080-ca3617e8-3bf9-4469-bda2-9cf6f59aa2ef.png)

绷不住了兄弟🤣我平常也要用到geforce这个，但是貌似也被墙了，我是用别的方法知道它这个软件其实是连接哪些域名之后，把相关的域名添加到规则里走代理，你看截图里的三条横线标注的，都是跟geforce有关的

**Comment by tlerbao** [comment]
@yi-Xu-0100 哈哈，我這個不是geforce本體，我這個是游戲外掛僞裝成這個的。

**Comment by yi-Xu-0100** [comment]
@tlerbao 从详细信息里找找看

**Comment by joelucky198x** [comment]
> 有两个方法，一个一劳永逸，另一个可能每更新一次你都要重新设置，但是都不难。 1：通过 “配置文件预处理” 右键你的配置文件，点击 Parsers，然后选择 Edit Parsers，进入编辑界面，相关截图给你参考一下 ![11](https://user-images.githubusercontent.com/88962428/180923284-8c6efd9f-b42f-45b7-b42d-f963f89e9749.png) ![13](https://user-images.githubusercontent.com/88962428/180923320-72ebc33b-6d7c-46d8-a857-b52b4077e67f.png) 如图呢，你在规则里自己添加一行 **PROCESS-NAME, QQ.exe, Proxy**（这只是我给你举了个例子，你的软件名字叫什么自己改，后面的 Proxy 就是你给它定的让它走代理的意思），软件名字建议通过 windows 的进程管理器查看你需要改的那个软件的真实的进程名字，不要想当然的输入常用名。 输入完后，保存，更新一下配置文件就可以了（还是第一步你右键点击的那个配置文件，配置文件上不是一个更新的原型箭头按钮吗，你点击，更新一下，相应的规则就会添加进去生效了） 一劳永逸。 2：不会搞配置文件，那就用最笨的方法，手动添加规则。 还是右键配置文件，选择 Rules，然后点击右上角的 Add，就出现相应的规则界面 ![21](https://user-images.githubusercontent.com/88962428/180924083-dcb1e528-61a2-4453-b964-0e89bdea1eb1.png) ![22](https://user-images.githubusercontent.com/88962428/180924097-a40426c7-d24d-4548-9bc2-befe4e766874.png) ![23](https://user-images.githubusercontent.com/88962428/180924107-8e2bbabe-5a07-47b6-a72f-a0a692346696.png) 如图，你看我圈了一个圆圈和方框，都用蓝色箭头标识了，上面圆圈里就是填写你要改的那个软件进程的名字，下面方框就是表示这是按照进程名字识别的，选择好之后，鼠标滚轮下滑 ![24](https://user-images.githubusercontent.com/88962428/180924281-7c57f90c-3112-48fc-b6c7-00c8d112aa00.png) 这时你能看见不同的策略，直连，代理，阻断，甚至你还可以看到你的所有节点，选择代理就行（用的节点就是你全局用的那个节点），或者你还可以选择某个节点让它指定某个节点来走代理，很方便是吧 ![微信截图_20220726124204](https://user-images.githubusercontent.com/88962428/180924754-325e9001-0d5a-464b-afd5-e842d72b26a1.png) 然后一切都搞完之后，** 记得点击右上角的 Add 把这个规则添加进去，再然后记得点击右上角的 Save 按钮保存**，就可以了。 这个方法比较直观，但是切记，你每次点击更新配置文件的时候，有可能会被覆盖，如果哪天发现没有了，你还得手动再来一遍，没什么事尽量不要更新配置文件

哥们，这个是不是在tun模式才有效，在system proxy模式下无效啊。
