### ISSUE TITLE
[Feature Request]: windows shutdown IE-proxy auto restore

### ISSUE THREAD

**Issue by shoux0272** [Fndroid/clash_for_windows_pkg#3266]
### 功能描述

关机时关闭系统代理

**Comment by yi-Xu-0100** [comment]
参考 issue：

- https://github.com/Fndroid/clash_for_windows_pkg/issues/943#issuecomment-658603325
- https://github.com/Fndroid/clash_for_windows_pkg/issues/1102#issuecomment-699744462
