### ISSUE TITLE
[Bug]: 开启 TUN 模式，By Pass Domain 不生效

### ISSUE THREAD

**Issue by juzi214032** [Fndroid/clash_for_windows_pkg#3273]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.25

### 操作系统

macOS arm64(M1,M1*)

### 系统版本

12.5

### 问题描述

开启 TUN 模式，By Pass Domain 不生效

### 复现步骤

开启 TUN，配置 By Pass Domain

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
bypass 是针对系统代理的，tun 无法被避免

**Comment by juzi214032** [comment]
> bypass 是针对系统代理的，tun 无法被避免

了解了 感谢

**Comment by prynnekey** [comment]
那开启了Tun怎么才能实现bypass呢？
