### ISSUE TITLE
[Feature Request]: 日志界面复制网址

### ISSUE THREAD

**Issue by JackerGamer** [Fndroid/clash_for_windows_pkg#3274]
### 功能描述

![image](https://user-images.githubusercontent.com/94670721/182269171-c4a0f86a-335e-4837-a313-fed1dbecf5c2.png)
希望日志界面中的网址可以被选中和复制

**Comment by yi-Xu-0100** [comment]
双击下会复制网址加端口号

**Comment by JackerGamer** [comment]
> 双击下会复制网址加端口号

我竟然不知道，谢谢了
