### ISSUE TITLE
[Bug]: UOS最小化后，无法再激活主界面

### ISSUE THREAD

**Issue by tony1016** [Fndroid/clash_for_windows_pkg#3276]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.23

### 操作系统

Linux

### 系统版本

UnionTech OS GNU/Linux 20

### 问题描述

在UnionTech OS GNU/Linux 20 ，即Deepin中，最小化到任务栏后，单击图标可以调出菜单，但是无法再点击菜单项，似乎不无法捕获到鼠标指针。

### 复现步骤

最小化，点击图标，再尝试点击任一项

### 日志文件

似乎会有一句日志：xdg-settings: unknown desktop environment

**Comment by Fndroid** [comment]
上有electron问题吧

**Comment by tony1016** [comment]
试了0.19.25，该问题已经不存在
