### ISSUE TITLE
[Bug]: 冒死揭露Clash广告里的骗子机场极客云

### ISSUE THREAD

**Issue by happywanglaoxiansheng** [Fndroid/clash_for_windows_pkg#3277]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.25

### 操作系统

Windows x64

### 系统版本

windows10

### 问题描述

不要购买，不要购买，不要购买
别买极客云，垃圾机场超级不稳定，节点全部超时，挂了8个小时无人处理，客服失踪，群组全员禁言禁止评论。
一个付费的机场还不如免费公益机场稳定，超级智商税。
我只能说能帮一个算一个了，反正我已经上当了，没辙了
![image_2022-08-02_16-30-10](https://user-images.githubusercontent.com/110469717/182374875-f4cb69b0-8263-4ef3-9a8e-285a32580a6e.png)
![image_20220802200235](https://user-images.githubusercontent.com/110469717/182375026-f27e5fc4-ed97-4bcf-b967-8d15545e1722.png)
![image_20220802200400](https://user-images.githubusercontent.com/110469717/182375047-6b002a87-024d-49e7-9c4c-198f6b3e61ab.png)
![image_20220802200559](https://user-images.githubusercontent.com/110469717/182375073-ccc1df70-c44a-42f5-af09-0f0ecd255434.png)

### 复现步骤

购买广告里的机场

### 其他补充

千万别买！极客云是垃圾！
千万别买！极客云是垃圾！
千万别买！极客云是垃圾！

**Comment by Fndroid** [comment]
应该是节点格式没跟上最新客户端，可以复制网站里的SSR订阅到 https://sub.xeton.dev 这里转换成最新的，再把生成的连接导入到客户端就好了

**Comment by neoblackxt** [comment]
> 应该是节点格式没跟上最新客户端，可以复制网站里的SSR订阅到 https://sub.xeton.dev 这里转换成最新的，再把生成的连接导入到客户端就好了

不止格式问题，就算转换了一样，超级不稳定
![image_20220802222204](https://user-images.githubusercontent.com/22809337/182398082-292d6d31-dbc3-44a7-a1ec-fa2a84dcf194.png)

**Comment by happywanglaoxiansheng** [comment]
就算转换过也一样超级不稳定
![image_20220802222204](https://user-images.githubusercontent.com/110469717/182400056-b8e83dc5-1918-445b-a0d4-0d044c413680.png)
