### ISSUE TITLE
[Bug]: 为什么你不应该买广告推荐里的极客云

### ISSUE THREAD

**Issue by happywanglaoxiansheng** [Fndroid/clash_for_windows_pkg#3278]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.25

### 操作系统

Windows x64

### 系统版本

Windows x64

### 问题描述

极客云，它根本不极客。这是一个让你买了后悔的机场。其稳定性表现，完全配不上一个付费机场应有的水平。
更多真相请看[冒死揭露Clash广告里的骗子机场极客云](https://github.com/Fndroid/clash_for_windows_pkg/issues/3277)

### 复现步骤

购买广告里的机场

**Comment by happywanglaoxiansheng** [comment]
希望不再有更多不明真相的吃瓜群众再上当了，但事实上我不能阻止大多数人掉入无良奸商的陷阱。虽然做的这点事杯水车薪，微不足道，也就帮了一两个人，但至少良心上过得去，尽力了，就这样。

**Comment by Fndroid** [comment]
vmess需要和服务端时间同步所以我说把ssr订阅转换过去试试

<img width="950" alt="image" src="https://user-images.githubusercontent.com/16091562/182409891-c01eda61-f524-4dd1-833e-063600b85699.png">

另外和软件功能无关的问题能不能不要在我这里发了

**Comment by happywanglaoxiansheng** [comment]
大家有权利知道真相，和时间同步无关
![微信截图_20220803000314](https://user-images.githubusercontent.com/110469717/182420750-2ce78f38-e9b0-4ca4-ad8e-a0c646f44a92.png)

**Comment by happywanglaoxiansheng** [comment]
> vmess需要和服务端时间同步所以我说把ssr订阅转换过去试试
> 
> <img alt="image" width="950" src="https://user-images.githubusercontent.com/16091562/182409891-c01eda61-f524-4dd1-833e-063600b85699.png">
> 
> 另外和软件功能无关的问题能不能不要在我这里发了

那就说一个和功能有关的，应该广告一栏中注明，广告内容为赞助商独立提供，本软件不对赞助商的广告内容提供任何形式的背书，请用户自行鉴别。
