### ISSUE TITLE
关机时报错：Dashboard has crashed!

### ISSUE THREAD

**Issue by i-jie** [Fndroid/clash_for_windows_pkg#328]
Windows 7，Clash for Windows v0.8.6，关机时弹窗：
![弹窗](https://user-images.githubusercontent.com/20808213/70955500-165ed980-20ac-11ea-952f-7c9623c6c3ba.jpg)

**Comment by Fndroid** [comment]
@i-jie 这是应用异常关闭的提示。如果关机出现那么可以忽略

**Comment by i-jie** [comment]
@Fndroid OK
