### ISSUE TITLE
[Bug]: 解压打开0.19.26目录下的clash后，版本显示还是0.19.25

### ISSUE THREAD

**Issue by norangit** [Fndroid/clash_for_windows_pkg#3289]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.26

### 操作系统

Windows x64

### 系统版本

win10 21h2

### 问题描述

解压打开0.19.26目录下的clash后，版本显示还是0.19.25，用户配置目录下（C:\Users\xxx\.config\clash）的哪些文件是可以清空的，是不是清空下配置目录就可以了呢？都清空了的话是不是之前的配置都没了呢

### 复现步骤

解压打开0.19.26目录下的clash后，版本显示还是0.19.25

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Lemmingh** [comment]
或许，在解包新程序之前，你忘记去删除旧版本的程序。

此外，如果你怀疑 CFW 渲染出问题，可以考虑清理 Electron 的 Cache (`%APPDATA%\clash_win`)。

**Comment by Fndroid** [comment]
先把旧版本退出，不然启动新版本只会打开旧版本的界面
