### ISSUE TITLE
如果tap配置把fake-ip换成redir-host的话，tap网卡就显示断开电缆连接

### ISSUE THREAD

**Issue by lvhe19880210** [Fndroid/clash_for_windows_pkg#329]
还有就是在fake-ip模式下putty和winscp等ssh客户端不管走不走代理连接都会断开

**Comment by Fndroid** [comment]
> 如果tap配置把fake-ip换成redir-host的话，tap网卡就显示断开电缆连接

TAP不支持redir-host

> 还有就是在fake-ip模式下putty和winscp等ssh客户端不管走不走代理连接都会断开

断开是指用着用着突然断开还是无法登录？

**Comment by lvhe19880210** [comment]
> > 如果tap配置把fake-ip换成redir-host的话，tap网卡就显示断开电缆连接
> 
> TAP不支持redir-host
> 
> > 还有就是在fake-ip模式下putty和winscp等ssh客户端不管走不走代理连接都会断开
> 
> 断开是指用着用着突然断开还是无法登录？

无法登陆，提示network错误，然后窗口关闭

**Comment by lvhe19880210** [comment]
> > 如果tap配置把fake-ip换成redir-host的话，tap网卡就显示断开电缆连接
> 
> TAP不支持redir-host
> 
> > 还有就是在fake-ip模式下putty和winscp等ssh客户端不管走不走代理连接都会断开
> 
> 断开是指用着用着突然断开还是无法登录？

**Comment by lvhe19880210** [comment]
找到原因了，ssh走的是geo ip，而geo ip设置的是走本地http代理而不是direct，fake-ip模式下ssh貌似不支持这种中转再中转，不好意思给您添麻烦了
