### ISSUE TITLE
[Bug]: Winget 更新失败 

### ISSUE THREAD

**Issue by yi-Xu-0100** [Fndroid/clash_for_windows_pkg#3296]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.26

### 操作系统

Windows x64

### 系统版本

0.19.23 之后

### 问题描述

虽然 action 没有报错，但是内容中显示 error 而无法继续提交更新，有这样的问题：refusing to allow a Personal Access Token to create or update workflow `.github/workflows/spellCheck.yaml` without `workflow` scope.

@vedantmgoyal2009 可能 action 需要提供应对这样的问题的帮助？

### 复现步骤

https://github.com/Fndroid/clash_for_windows_pkg/runs/7676562144?check_suite_focus=true

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by vedantmgoyal2009** [comment]
@Fndroid you need to give the token `workflow` scope.

**Comment by yi-Xu-0100** [comment]
@vedantmgoyal2009 This error should make action failed for notification. 🙌

**Comment by Fndroid** [comment]
done
