### ISSUE TITLE
使用代理时windows10自带搜索无法显示预览

### ISSUE THREAD

**Issue by WongRuoran** [Fndroid/clash_for_windows_pkg#330]
在 windows 10 自带的搜索栏里搜索关键词，如“天气 上海”，理应有网页预览，但只要挂上代理，不管是设置到 Global 还是 Rule 模式，都会显示“天气 上海的预览当前不可用“。如果关掉代理，重置搜索，就能正常显示预览。
已经配置好 UWP Loopback，确认 UWP 应用都能正常访问网络。

**Comment by Fndroid** [comment]
应该是规则问题，我这里直连是可以的

**Comment by Fndroid** [comment]
试试把 bing.com 加到直连

**Comment by WongRuoran** [comment]
> 试试把 bing.com 加到直连

谢谢，解决了。

**Comment by DEXTERcyy** [comment]
我在想不直连难道就没法显示预览了吗? 把Windows区域和bing区域都设在美国应该就能显示预览了
