### ISSUE TITLE
[Feature Request]: macos 不能在菜单栏上面显示实时网速吗? 希望能添加此功能,像 clashx 那样

### ISSUE THREAD

**Issue by XuShall** [Fndroid/clash_for_windows_pkg#3306]
### 功能描述

![telegram-cloud-photo-size-5-6311917168819810440-m](https://user-images.githubusercontent.com/33885653/183840879-980e29d9-dafd-4e7d-8f6c-32983f736535.jpg)

我在设置中看到了配置项,但是我不能更改他,不知道为什么.
<img width="641" alt="image" src="https://user-images.githubusercontent.com/33885653/183840985-8a950738-e17b-40bf-ae5e-edab165c3b43.png">

**Comment by Yzcloud** [comment]
可以是可以不好用，你用鼠标把隐藏后面那3个小图标托去小猫咪旁边就行

**Comment by XuShall** [comment]
> 可以是可以不好用，你用鼠标把隐藏后面那3个小图标托去小猫咪旁边就行

谢谢
