### ISSUE TITLE
作者为什么不开源这个项目啊？他暗地里监听我们的网络怎么办？

### ISSUE THREAD

**Issue by echofly** [Fndroid/clash_for_windows_pkg#3308]
**_作者为什么不开源这个项目啊？他暗地里监听我们的网络怎么办？_**

**Comment by yi-Xu-0100** [comment]
要不你还是不用了吧 👀

**Comment by xuhaoyang** [comment]
claah core可以随便更换。electron的项目也可以反编译后看到前端资源。

信不过你可以别用。

**Comment by echofly** [comment]
> 要不你还是不用了吧 👀

我本来就不打算用，我目前用V2rayN，我只是有这个疑问

**Comment by echofly** [comment]
> claah core可以随便更换。electron的项目也可以反编译后看到前端资源。
> 
> 信不过你可以别用。

行吧，反正我没用，我只是好奇问问。这是个免费不盈利项目，作者宁愿自己花时间修bug维护，也不愿意开源让大家一起帮他修bug开发维护，所以担心背后有什么不可告人的目的

**Comment by yi-Xu-0100** [comment]
@echofly 应该是没必要吧，毕竟选择那么多，也不是必须要用，开源很累的，还得 review 啥的。

**Comment by echofly** [comment]
> @echofly 应该是没必要吧，毕竟选择那么多，也不是必须要用，开源很累的，还得 review 啥的。

害人之心不可有，防人之心不可无啊！

**Comment by yi-Xu-0100** [comment]
@echofly 警惕性不错，但要注意不失淳朴宽厚的为人为道。-- https://baike.baidu.com/item/害人之心不可有，防人之心不可无

**出处：**《菜根谭》：“害人之心不可有，防人之心不可无，此戒疏於虑也：宁受人之欺，勿逆人之诈，此警惕于察也，二语并存，精明而浑厚矣。”
**释义**：“害人之心不可有，防人之心不可无。”这句话是用来劝诫在与人交往时警觉性不够的人的。“宁可忍受他人的欺骗，也不愿在事先拆穿人家的骗局。”这句话是用来劝诫那些警觉性过高的人的。假如一个人在和别人相处时能牢记上面的两句话，那才算得上警觉性高而又不失纯朴宽厚的为人之道。
**注意：** 很多人只注意到上一句，但很少留意到下一句“宁受人之欺，勿逆人之诈”；其实作者真正想表达的是让大家做一个“警觉性高而又不失纯朴宽厚”的人。

**Comment by sgf** [comment]
> @echofly 警惕性不错，但要注意不失淳朴宽厚的为人为道。-- [https://baike.baidu.com/item/害人之心不可有，防人之心不可无](https://baike.baidu.com/item/%E5%AE%B3%E4%BA%BA%E4%B9%8B%E5%BF%83%E4%B8%8D%E5%8F%AF%E6%9C%89%EF%BC%8C%E9%98%B2%E4%BA%BA%E4%B9%8B%E5%BF%83%E4%B8%8D%E5%8F%AF%E6%97%A0)
> 
> **出处：**《菜根谭》：“害人之心不可有，防人之心不可无，此戒疏於虑也：宁受人之欺，勿逆人之诈，此警惕于察也，二语并存，精明而浑厚矣。” **释义**：“害人之心不可有，防人之心不可无。”这句话是用来劝诫在与人交往时警觉性不够的人的。“宁可忍受他人的欺骗，也不愿在事先拆穿人家的骗局。”这句话是用来劝诫那些警觉性过高的人的。假如一个人在和别人相处时能牢记上面的两句话，那才算得上警觉性高而又不失纯朴宽厚的为人之道。 **注意：** 很多人只注意到上一句，但很少留意到下一句“宁受人之欺，勿逆人之诈”；其实作者真正想表达的是让大家做一个“警觉性高而又不失纯朴宽厚”的人。


挺好的,我也决定试试开源的版本去了. 有个ClashN 可以试试
