### ISSUE TITLE
[Question] 如何清理旧的订阅配置

### ISSUE THREAD

**Issue by srikker** [Fndroid/clash_for_windows_pkg#3309]
删除了订阅配置，但是在配置管理中还能看到。如何清理旧的配置？
![image](https://user-images.githubusercontent.com/82227789/184090438-0dc09f24-00a7-4af8-8f38-b1cf013ec194.png)

**Comment by yi-Xu-0100** [comment]
老实说，你这是什么软件的界面？

**Comment by srikker** [comment]
> 老实说，你这是什么软件的界面？

抱歉，我走错地方了   - -\
