### ISSUE TITLE
clash对vmess协议中kcp协议的支持

### ISSUE THREAD

**Issue by sportshark** [Fndroid/clash_for_windows_pkg#331]
V2ray本身是支持KCP协议的，使用之后速度快了很多，目前很多节点都切换到了kcp，但目前clash for windows选择Vmess时，只能选择TCP，不能选择KCP，希望能支持。

**Comment by lizongzeshunshun** [comment]
可以去[上游](https://github.com/Dreamacro/)反馈。
以前也有过类似 Issues：[Dreamacro/clash #37](https://github.com/Dreamacro/clash/issues/37)
