### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Carlos920** [Fndroid/clash_for_windows_pkg#3315]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.26 免安装版

### 操作系统

Windows x64

### 系统版本

win11

### 问题描述

软件无法获取到最新版本

### 复现步骤

clash for windwos 点击版本号,
![image](https://user-images.githubusercontent.com/32257015/184468813-13974fd1-112f-4f00-b610-f6665e54e1d5.png)
![image](https://user-images.githubusercontent.com/32257015/184468820-66525813-17f8-4172-a521-b787c0082028.png)
![image](https://user-images.githubusercontent.com/32257015/184468822-934bbd9f-95f9-408a-a404-33f646fb515d.png)

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
可能需要清理下缓存？disk cache ，devtool 里清理请求缓存呢？下面是我的测试

![图片](https://user-images.githubusercontent.com/25523606/184469901-e6b23e8e-d049-4c81-ad5a-4aefd0e3d739.png)

**Comment by Carlos920** [comment]
> 可能需要清理下缓存？disk cache ，devtool 里清理请求缓存呢？下面是我的测试
> 
> ![图片](https://user-images.githubusercontent.com/25523606/184469901-e6b23e8e-d049-4c81-ad5a-4aefd0e3d739.png)

没有效果，不是缓存的问题，你用的是安装版还是便携版？我这个是便携版

**Comment by yi-Xu-0100** [comment]
@Carlos920 便携版

**Comment by Carlos920** [comment]
> @Carlos920 便携版
解决了，dns污染问题🤣
