### ISSUE TITLE
[Bug]: logs中的emoji显示bug

### ISSUE THREAD

**Issue by Wrandz** [Fndroid/clash_for_windows_pkg#3317]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.26

### 操作系统

macOS arm64(M1,M1*)

### 系统版本

12.5

### 问题描述

logs中显示的一个emoji，会莫名其妙的，有的时候显示是好的，有的时候又不行。如图
<img width="672" alt="截屏2022-08-14 11 30 30" src="https://user-images.githubusercontent.com/70056470/184521296-ba25b073-b3a7-4abd-8b04-d42647619e52.png">
这个emoji就是👨‍💻

### 复现步骤

在Windows和Mac平台的最近几个版本（包含最新的0.19.26）都存在这个问题，只要proxy group里面有这个emoji。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>
[2022-08-14-092249.log](https://github.com/Fndroid/clash_for_windows_pkg/files/9332650/2022-08-14-092249.log)

**Comment by Wrandz** [comment]
[2022-08-14-092249.log](https://github.com/Fndroid/clash_for_windows_pkg/files/9332651/2022-08-14-092249.log)

**Comment by Lemmingh** [comment]
ZWJ 没了，在 Clash 写入 `stdout` 的日志中，被 Logrus 转义了：

<https://github.com/sirupsen/logrus/blob/f8bf7650dccb756cea26edaf9217aab85500fe07/text_formatter.go#L337>

Logrus 的设计就是这样。恐怕无解。

**Comment by Wrandz** [comment]
@Lemmingh 如果是这样的话，那不是每次都会被转义，但是你看我的截图，同一个emoji，上面显示有问题，但是下面显示又是好的。也就是说，有的时候是可以的，有时候却又不行。

**Comment by Lemmingh** [comment]
稍作跟踪，结论如下：

在刚打开 Logs 界面时，CFW 载入预读日志，即来自 Clash 的 `stdout`。预读量由 `logPreloadLineCount` (Settings > Logs > Preload) 控制，默认为 30 条。

之后，CFW 从 Clash REST API 获取 JSON 格式的即时日志。

**Comment by Wrandz** [comment]
@Lemmingh 谢谢你，明白了，看来要改一下这个emoji了
