### ISSUE TITLE
按钮设计问题

### ISSUE THREAD

**Issue by freehehe** [Fndroid/clash_for_windows_pkg#333]
这个不好点
能不能设计在别的地方？

https://sm.ms/delete/9S1ZuGKhrzt3NX7Jk5i2aPCIMw
会挡住check

**Comment by freehehe** [comment]
https://sm.ms/image/2C36S4LRgKQqAft

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.8.7
