### ISSUE TITLE
[Bug]: 最新版本，开启轻量模式后，PC启动后弹窗问题。

### ISSUE THREAD

**Issue by mobilefish** [Fndroid/clash_for_windows_pkg#3334]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.26

### 操作系统

Windows x64

### 系统版本

windows 11 专业版

### 问题描述

最新版本0.19.26，开启“轻量模式”后，每次开机进入操作系统桌面时都会自动弹出clash for windows GUI界面，需要手工关闭才行。

如何设置每次开机启动 不自动弹出GUI界面，而是采用静默方式启动？

望能告知，谢谢！

### 复现步骤

轻量模式下，每次开机均自动弹出GUI界面，需要手工关闭才行。

**Comment by Fndroid** [comment]
预期行为
