### ISSUE TITLE
[Bug]: Proxy Providers更新时似乎没有带User Agent？

### ISSUE THREAD

**Issue by UntaggedRui** [Fndroid/clash_for_windows_pkg#3335]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.26

### 操作系统

macOS amd64(Intel)

### 系统版本

12.4

### 问题描述

使用V2board系统作为后台的机场，提供的订阅链接是通用的，只有一个。如果直接在浏览器访问看到的是一串乱码，应该默认的是V2rayN等软件使用的。在CFW的Profiles界面添加这个链接可以正常使用。猜测是请求这个链接时加了clash的UA或者某种手段让V2board返回了clash的yaml文件。但是同样的订阅链接放在proxy provider中，更新时会出现如下错误，而这个dHJVAMF恰好是直接访问这个链接的内容。是不是在更新proxy provider的时候请求的header 少了些什么？
![image](https://user-images.githubusercontent.com/28807947/185524742-dc33e544-bcf1-4a46-8c23-6da8fd2f3bbf.png)

### 复现步骤

在proxy provider中更新V2board的订阅链接，例如https://xn--4gq62f52gdss.com/api/v1/client/subscribe?token=XXXXX之类的。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
1. provider更新是Clash core做的所以UA不是CFW
2. 看了一眼代码，它提供`flag=clash`的参数直接获取

**Comment by UntaggedRui** [comment]
> 1. provider更新是Clash core做的所以UA不是CFW
所以这个问题是core的问题而不是CFW的问题吗
> 2. 看了一眼代码，它提供`flag=clash`的参数直接获取
好，那我改一下订阅链接了
