### ISSUE TITLE
[Bug]: 更新后右上角显示BUG

### ISSUE THREAD

**Issue by nnnosk** [Fndroid/clash_for_windows_pkg#3337]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.27

### 操作系统

Windows x64

### 系统版本

Win11 21H2

### 问题描述

更新后显示BUG
![image](https://user-images.githubusercontent.com/31917301/185620233-e9f250b6-31ec-4a25-b3d7-c0504ee4a4af.png)

### 复现步骤

显示bug

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
上游electron的bug

**Comment by LightAPIs** [comment]
我还以为是我跟不上现代 UI 的审美了。。。

**Comment by konnoyuukilove** [comment]
> 我还以为是我跟不上现代 UI 的审美了。。。

我也是...

**Comment by WritingWithFire** [comment]
electron的软件UI都挺现代化，但是使用体验奇差。。
