### ISSUE TITLE
[Feature Request]: 更新订阅时可否选择使用代理进行更新

### ISSUE THREAD

**Issue by ghkghkghk** [Fndroid/clash_for_windows_pkg#3341]
### 功能描述

更新订阅时可否选用使用代理进行更新？目前因DNS问题，导致很多订阅地址无法正常更新。请求是否可以增加此功能。

**Comment by LightAPIs** [comment]
打开 system proxy 不就行了。

**Comment by ghkghkghk** [comment]
日常使用时，有些用户不开System Proxy，仅在需代理的软件自身设置代理，socks5，127.0.0.1:7890
有些订阅地址因DNS污染导致无法直连，这就导致更新订阅不正常。

**Comment by yi-Xu-0100** [comment]
@ghkghkghk cfw 遵循系统代理，或者你可以看看electron应用一般怎么强制代理，在或者你需要更新订阅的时候开一下系统代理。

**Comment by ghkghkghk** [comment]
感谢大神回复！

个人目前的临时解决方案：
1. 不对CFW进行任何其他设置变动；
2. CF优选IP，将运营商无法DNS解析的订阅地址，在上级路由指定DNS为优选后的CF IP，可以进行更新。

优势：
1. 不用对CFW目前不开System Proxy的使用方式做任何改动；
2. 可以将所有订阅地址和转换地址都指向此IP。

劣势：优选的IP可能失效需手动更换。
