### ISSUE TITLE
v2ray一直配置不成功

### ISSUE THREAD

**Issue by listenLearning** [Fndroid/clash_for_windows_pkg#335]
Proxy:
  - type: vmess
    cipher: auto
    name: 233v2.com_***
    server: ***
    port: "32649"
    uuid: f9ae9e6d-8eeb-4650-9f58-5236eed6a1f6
    alterId: "233"
    tls: false
  - type: vmess
    cipher: auto
    name: 233v2.com_***
    server: ***
    port: "46091"
    uuid: 4f519bcb-5ddd-47ca-ab81-ff7e86795698
    alterId: "233"
    tls: false
Proxy Group:
  - type: select
    name: 🚀 Proxy
    proxies:
      - 233v2.com_***
      - 233v2.com_***
  - type: select
    name: 🎬 Netflix
    proxies: [233v2.com_***]
  - type: url-test
    name: US
    proxies: [233v2.com_***]
    url: http://www.qualcomm.cn/generate_204
    interval: 1200
  - type: url-test
    name: HK
    proxies: [233v2.com_***]
    url: http://www.qualcomm.cn/generate_204
    interval: 1200
  - type: select
    name: 🍎 Apple
    proxies:
      - DIRECT
      - 🚀 Proxy
      - US
      - HK
  - type: select
    name: 🍎 Apple CDN
    proxies:
      - DIRECT
      - 🍎 Apple
Rule:
  - MATCH,🚀 Proxy

**Comment by listenLearning** [comment]
以上是我的配置，但是这个一直都没法连接成功，请问这个配置有什么问题呢

**Comment by ly20190112** [comment]
先添加一个节点，后面的节点进配置文件手动添加就可以了
![捕获](https://user-images.githubusercontent.com/46617916/72710419-0736e400-3ba2-11ea-99a7-72f135defc54.PNG)

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
