### ISSUE TITLE
[Help]: 开启网络代理，web无法访问

### ISSUE THREAD

**Issue by funnyhan** [Fndroid/clash_for_windows_pkg#3351]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.27

### 操作系统

Linux

### 系统版本

Arch Linux

### 问题描述

求助！

前情：VMware Workstation 上装的Arch(2022.08.05)，NAT模式，能正常联网(web访问baidu，无法访问google；终端能ping baidu，无法ping google)
下载clash for windows 0.19.27-x64-liunx（解压在~/Downloads/下的），并'.cfw'启动，终端信息
【
LauchProcess: failed to execvp:
xdg-settings
libva eror vaGetDriverNameByIndex() failed with unknown libva error，driver_name=(null)
[1862:8823/125323.426400:ERROR:gpu_memory_buffer_support_xll.cc(44)] dri3 extension not supported.
】
但是能看到clash fow windows的面板出现和使用了。

问题：使用clash for windows，订阅配置之后，测速ok（能看到各节点的ms）。
但是网络设置开启代理后，web去访问baidu和google，面板logs中能看到中出现他们的
request logs信息，但是无法访问。终端能ping baidu，无法ping google。

request logs:
【www.baidu.com:443
  TCP DomainSuffix(baidu.com)   Domestic[DIRECT]
  127.0.0.1:49340   时间
】
【www.google.com:443
  TCP DomainKeyword(google)   Proxy[选中的代理节点名]
  127.0.0.1:49348   时间
】
这里应该是请求已经走代理端口了吧，而且匹配规则也生效了，baidu走的是DIRECT，google走的是Proxy。

### 复现步骤

应该都在上面了

### 日志文件

没看到有logs文件

### 其他补充

感觉没其他了

**Comment by whistlefancy** [comment]
同样的问题发生在ubantu20，软件版本0.19.29，暂未解决

**Comment by esportqt** [comment]
Fedora36同样的问题，我怎么找不到system proxy的按纽阿
![图片](https://user-images.githubusercontent.com/32286817/189357528-2f41c432-7be6-49d9-9959-8ffaed61e764.png)

**Comment by kid1412621** [comment]
run `export https_proxy=http://127.0.0.1:7890;export http_proxy=http://127.0.0.1:7890;export all_proxy=socks5://127.0.0.1:7890`.
then set proxy manully in settings of system or browser.
