### ISSUE TITLE
clash for windows问题

### ISSUE THREAD

**Issue by Snowfly-Guo** [Fndroid/clash_for_windows_pkg#3353]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.27

### 操作系统

Windows x64

### 系统版本

21H2

### 问题描述

打开clash for windows后连接代理没速度，Google也上不去，节点速度也很正常

### 复现步骤

打开后就出现问题，可是我的手机使用就没问题

### 日志文件

无日志

### 其他补充

看了类似的Issue但是没有解决问题
只修改过clash的语言配置文件

**Comment by Fndroid** [comment]
换别的

**Comment by Snowfly-Guo** [comment]
> 换别的
换了好几个免费了
这次的是付费的还不行
