### ISSUE TITLE
[Bug]: 系统代理{https:https://127.0.0.1:7890}是非标准的且应被更改

### ISSUE THREAD

**Issue by 123ABCDF11345** [Fndroid/clash_for_windows_pkg#3354]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.27

### 操作系统

Windows x64

### 系统版本

Windows10

### 问题描述

注意到：
软件将系统代理设置为
```
{'http': 'http://127.0.0.1:7890', 'https': 'https://127.0.0.1:7890', 'ftp': 'ftp://127.0.0.1:7890'}
```
但是当设置https代理为https://127.0.0.1:7890时，它并不会真的使用https代理（本地需要什么https...）而是http
大部分应用并不强制的要求，但是Python库requests在发送http请求时自动使用系统代理，当它使用HTTPS代理时，它检查了是否是真正的https代理，很显然这里不是。于是报错
```
The error happens since the proxy is not able to speak TLS but gets accessed by TLS. The fix is to use http://proxy and not https://proxy as the proxy address. Note that the latter worked in older versions of Python since proxy over HTTPS was not supported and a value of https:// for the protocol was treated the same as http://.
```
相关issue在[这里](https://github.com/pypa/pip/issues/9216#issuecomment-741836058)
因此我建议将代理改为：
```
{'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890', 'ftp': 'ftp://127.0.0.1:7890'}
```
当然这可能导致其他兼容性问题，但这是否可行？望告知
P.S.:我不知道应该提在Core还是这里，如应提在Core项目也请告知

### 复现步骤

/

**Comment by Wrandz** [comment]
恕我无知，这个问题，我之前看到相关的issue，不是通过PAC可以解决吗？

**Comment by 123ABCDF11345** [comment]
> 恕我无知，这个问题，我之前看到相关的issue，不是通过PAC可以解决吗？

抱歉，我没有找到这个，可以麻烦提供一个链接吗，十分感谢！

**Comment by Lemmingh** [comment]
是 Python 的 bug。最新版的 Python 应该已经修了。

**Comment by Wrandz** [comment]
@123ABCDF11345 时间久了，我忘记了，我简单搜索到这个，供你参考 https://github.com/Dreamacro/clash/issues/2043#event-6699278502

**Comment by 123ABCDF11345** [comment]
感谢各位帮助，已大致了解解决，Close
