### ISSUE TITLE
[Bug]: 开机后cfw自启动然后就卡住了

### ISSUE THREAD

**Issue by Wrandz** [Fndroid/clash_for_windows_pkg#3357]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.27

### 操作系统

Windows x64

### 系统版本

Windows11 21H2

### 问题描述

一般是发生在电脑刚开机时，此时cfw刚开机自启动，Logs界面和Connections界面什么都不显示，如下图所示（我等待了2分钟截图）
![Snipaste_2022-08-24_13-02-06](https://user-images.githubusercontent.com/70056470/186360398-30496040-74f7-4800-9b35-daf41ab2d888.png)
![Snipaste_2022-08-24_13-01-55](https://user-images.githubusercontent.com/70056470/186360428-04f1706b-841f-4ced-aae2-fef80c02259f.png)

在log中可以明显看到第一条报错，显示socket没有权限（不太懂这意味着什么）。

### 复现步骤

不知怎么复现，但一般是在刚开机时出现，出现这种问题之后，通过重启电脑或者重装cfw，能够解决。只是不定时，又还会出现。

### 日志文件

[2022-08-24-125926.log](https://github.com/Fndroid/clash_for_windows_pkg/files/9413953/2022-08-24-125926.log)

**Comment by Lemmingh** [comment]
```log
Start Mixed(http+socks) server error: listen tcp 127.0.0.1:7890: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
```

Clash 没能成功打开 socket，死掉了。

如果该问题只能在开机时发生，就不好判断是什么东西占位。因为很难在那几秒内运行 WMI 和 PowerShell 去抓日志。

`config.yaml` 里换个端口 (`mixed-port`) 吧。

**Comment by Fndroid** [comment]
如果每给其他app单独设置代理，那mixed port也可以random保证不被占用

**Comment by Wrandz** [comment]
@Fndroid 谢谢，我还纳闷呢，为啥socket被占用了那个随机端口的功能一点作用没起。原来主页那个功能不是默认开启，而是需要点绿。
