### ISSUE TITLE
麻烦把开关做到外部全局可见, 不要做到内部的General页面去了

### ISSUE THREAD

**Issue by dayfan0810** [Fndroid/clash_for_windows_pkg#336]

**Comment by Fndroid** [comment]
“外部全局可见”是指什么

**Comment by dayfan0810** [comment]
@Fndroid   ![image](https://user-images.githubusercontent.com/8685291/71351420-9904fe80-25ae-11ea-940b-db917040c57d.png)

噢噢,我表达不清楚, 就是像这样啊

**Comment by dayfan0810** [comment]
@Fndroid 噢噢,我表达不清楚, 就是有时候这个开关都没有打开, 必须要点击General后才能看到我们链接了没, 把开关做到和使用时间一样,到外面来不是挺好嘛
![image](https://user-images.githubusercontent.com/8685291/71351550-f305c400-25ae-11ea-8ff0-f4518ed881e3.png)

**Comment by Fndroid** [comment]
这个开关的状态会记住的，你开了之后重启软件也会自动给你打开的。没明白加到左边菜单有什么意义

**Comment by dayfan0810** [comment]
那能不能在通知区域加一个这个总开关呢

**Comment by Fndroid** [comment]
并没有什么“总开关”的说法，System Proxy只是设置系统代理
