### ISSUE TITLE
[Bug]: 关闭system proxy后，依然消耗节点流量

### ISSUE THREAD

**Issue by reoLantern** [Fndroid/clash_for_windows_pkg#3364]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.27

### 操作系统

Windows x64

### 系统版本

Windows 11 21H2

### 问题描述

我正在Epic Game Store下载游戏，此时关闭system proxy，clash左上角显示依然在消耗节点流量。经过证实，我的节点流量确实正被消耗。

### 复现步骤

使用中国大陆外的下载源下载文件（例如Epic Game Store），开始下载后关闭system proxy。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by reoLantern** [comment]
感觉我的问题可以更普遍一些，打开clash但是没有开启system proxy，同样会跑流量

**Comment by yi-Xu-0100** [comment]
看看有没有开 allow lan 或者 tun，看下系统设置确认下已经关闭。看下 conections ，截个图，如果有还在下载，右边×掉是否还在下载？

**Comment by reoLantern** [comment]
> 看看有没有开 allow lan 或者 tun，看下系统设置确认下已经关闭。看下 conections ，截个图，如果有还在下载，右边×掉是否还在下载？

我不是很明白allow lan和tun模式的意义，我之前没有打开。请问如何在系统设置中查看它们已经关闭呢？
×掉clash但仍然在后台运行，会继续消耗流量。退出clash后会停止下载。
connections截图如下（system proxy已经关闭）：
![图片](https://s3.bmp.ovh/imgs/2022/08/26/d95c6bda2fc6fd89.png)

**Comment by yi-Xu-0100** [comment]
@reoLantern allow lan 和 tun 在 general 界面确认关闭，如果 profile 配置中有相关配置，也去关闭。系统设置中找的是系统代理（即system proxy.），检查下确认关闭。

软件是否有设置代理？

**Comment by reoLantern** [comment]
谢谢您的解答，我的问题突然解决了，也无法再次复现，可能是一些小bug。感谢！

**Comment by reoLantern** [comment]
@yi-Xu-0100 您好！抱歉再次打扰，想问一下软件左下角的“Connected”标志自软件启动以来一直显示绿色，关闭system proxy之后依然显示connected，请问这是否正常？

**Comment by reoLantern** [comment]
@yi-Xu-0100 我的问题再次出现了...已经检查tun和allow lan关闭，且系统设置中的手动配置代理服务器已经关闭。这次出现问题的软件是steam，我发现只要是本地安装的软件，即使不开system proxy，下载资源就会消耗节点流量，但是浏览器访问网页没有这个问题。

**Comment by reoLantern** [comment]
> @yi-Xu-0100 我的问题再次出现了...已经检查tun和allow lan关闭，且系统设置中的手动配置代理服务器已经关闭。这次出现问题的软件是steam，我发现只要是本地安装的软件，即使不开system proxy，下载资源就会消耗节点流量，但是浏览器访问网页没有这个问题。

补充信息：在clash的Logs中我查看到，关闭system proxy后，在steam中进行下载，会在logs中刷新出走DIRECT的日志。然而，退出clash后在steam中下载却无法连接（应该是间歇性被墙了）。这种情况，关闭了system proxy后，clash依然会记录日志，这是否能够反映出相关bug？
![image](https://user-images.githubusercontent.com/61400197/187010694-26de109b-cfdc-47bc-9de5-794e82b15406.png)

**Comment by Lemmingh** [comment]
CFW Dashboard 左下角的 Connected 的意思是 Clash 内核已启动。

即使你已经关闭 system proxy （以 Windows Settings 中的 Proxy 设置为准），正在连网的应用也 **不会** 突然自行断开连接，只要代理程序 (Clash) 仍然在运行，它们就继续使用已经建立的连接。而且，Chromium 之类的软件甚至还会缓存 system proxy 信息，过一会才能刷新。

**Comment by Lemmingh** [comment]
一些程序

* 不服从 system proxy 或者有独立的网络设置，如，Instagram、QQ、微信、VRChat。

* 理解 system proxy 但行为很扭曲，如，Ubisoft Connect。

此时，通常利用 [TUN](<https://github.com/Dreamacro/clash/wiki/Clash-Premium-Features>)，在 IP 层拦截它们，再拆包暴露给 Clash。

---

一些程序使用 UDP，此时，必须给它们 SOCKS5，或者用 TUN。同时，需要远端的代理节点支持 UDP。

因为 Windows system proxy 只有 HTTP，而 HTTP 隧道的 UDP 代理仍然是草稿。不过，UDP 的代理有技术困难，这些程序走代理后可能无法正常连网。

---

一些程序

* 使用了无法被代理的东西，如，IPsec （IP packet 里包的是 ESP 或 AH）。

* 有诡异的端口用法。

此时，若想转发它们的流量，只能考虑 VPN。

---

一些用户希望拿 Clash 当网关使，于是有了 [Allow LAN (`allow-lan`)](<https://github.com/Dreamacro/clash/wiki/Configuration>)。

---

CFW Logs 界面有预读，看日志时请注意时间。

---

总之，建议你题问前 **多读文档**。

**Comment by reoLantern** [comment]
好的，谢谢了

**Comment by Lemmingh** [comment]
> <https://github.com/Fndroid/clash_for_windows_pkg/issues/3364#issuecomment-1229103695>

这张图里打码的入站方式是不是 `198.18.0.1` 之类的东西？

如果是，你大概在 Profile 或者 Mixin 中开了 TUN。

---

CFW 发给 Clash 的 config 源自多个设置的层叠混合，大致顺序为：

1. Profile

1. Mixin 及其简化版 TUN Mode Settings

1. Dashboard 中的其他一些项目

**Comment by reoLantern** [comment]
我没有在general或mixin的设置中开启TUN，Profile中似乎也没有相关设置（我在我的profile中没有搜索到TUN的相关设置）。可能就是如您所述的原因。
> 即使你已经关闭 system proxy （以 Windows Settings 中的 Proxy 设置为准），正在连网的应用也 不会 突然自行断开连接，只要代理程序 (Clash) 仍然在运行，它们就继续使用已经建立的连接。

**Comment by Lemmingh** [comment]
> 基于 HTTP 隧道的 UDP 代理仍然是草稿

[RFC 9298: Proxying UDP in HTTP](<https://www.rfc-editor.org/rfc/rfc9298>) 在 [8 月 24 日](<https://datatracker.ietf.org/doc/rfc9298/>)发布了。😂

**Comment by blxie** [comment]
最新版的 也遇到了这个问题，通过关闭 `General —— Allow LAN`，以及删除 `~/.local/clash`，重新导入解决问题！

> 注意：单独关闭 `LAN` 对我无效，正如 @Lemmingh 所讲，`profile` 缓存信息应该还在，没有更新，所以采用删除重新导入的方式完美解决！

**Comment by sky-hqn** [comment]
有什么办法解决吗？steam上面国区游戏的更新，把代理关了依旧还是跑节点的流量

**Comment by Alemax067** [comment]
> 有什么办法解决吗？steam上面国区游戏的更新，把代理关了依旧还是跑节点的流量

把模式改为规则就行了，不要用全局模式

**Comment by Alemax067** [comment]
> @yi-Xu-0100 我的问题再次出现了...已经检查tun和allow lan关闭，且系统设置中的手动配置代理服务器已经关闭。这次出现问题的软件是steam，我发现只要是本地安装的软件，即使不开system proxy，下载资源就会消耗节点流量，但是浏览器访问网页没有这个问题。

把模式改为规则（rule）,全局模式默认所有流量走节点，所以才会出现你描述的情况
