### ISSUE TITLE
在PAC设定启用下是如何使用CFW

### ISSUE THREAD

**Issue by leeharuhiofcn** [Fndroid/clash_for_windows_pkg#3366]
因工作环境要求，电脑需启启用特定PAC配置引导流量向公司特定服务器，以达到访问管制，不通过该服务器则无法上网。
这时如何配置CFW使流量指向以上所述服务器。
谢谢指导。

已知直接开启tun或mixin或配置模式都无法上网。PAC代码之后添上。

**Comment by yi-Xu-0100** [comment]
查下 clash wiki 中的 relay 用法

**Comment by leeharuhiofcn** [comment]
已解决
https://github.com/Fndroid/clash_for_windows_pkg/issues/1632#issuecomment-782596149
