### ISSUE TITLE
[Bug]: 新版程序在启动后首次开启 System Proxy 时界面上的开关 UI 无变化

### ISSUE THREAD

**Issue by LightAPIs** [Fndroid/clash_for_windows_pkg#3367]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.28

### 操作系统

Windows x64

### 系统版本

Windows 11

### 问题描述

程序在启动后**首次**开启 System Proxy 时 General 界面上的开关 UI 无变化(*通过托盘上下文菜单开启 System Proxy 也会出现这样的问题*)，托盘图标能正常变化，系统代理服务器也正常开启；若之后再次调整 System Proxy 开关时则显示正常。

### 复现步骤

1. 确保 Clash fow Windows 之前没有启用过 System Proxy
2. 启动 Clash fow Windows
3. 在 General 或通过托盘上下文菜单开启 System Proxy

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
下个版本修复
