### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mbcz123** [Fndroid/clash_for_windows_pkg#3369]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

v 0.19.28

### 操作系统

macOS amd64(Intel)

### 系统版本

12.5.1

### 问题描述

我是Mac，打开软件就显示“Failed to clash core, logs are not available”，然后左下角就是一个disconnected，点try to repair也没用，删掉.config文件里的clash文件夹也没用，求帮忙！

### 复现步骤

打开软件，general页面报错

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>
[2022-08-26-224144.log](https://github.com/Fndroid/clash_for_windows_pkg/files/9436558/2022-08-26-224144.log)

**Comment by leestarboy** [comment]
同问题， 测试降级0.19.27解决

**Comment by SamLukeYes** [comment]
`nur.repos.linyinfeng.clash-for-windows` 已经因为这个问题回滚到 0.19.27 了

**Comment by Fndroid** [comment]
@leestarboy 你的也是intel版本吗

**Comment by LightAPIs** [comment]
> @leestarboy 你的也是intel版本吗

试了下，macOS 12.5.1 amd64(Intel)，运行 0.19.28 版本同样会出现这个问题，0.19.27 上正常。

**Comment by leestarboy** [comment]
> @leestarboy 你的也是intel版本吗

我是M1 PRO版本

**Comment by leestarboy** [comment]
> @leestarboy 你的也是intel版本吗

ARM64 M1 PRO

**Comment by SamLukeYes** [comment]
确认 0.19.29 Linux 版已修复该问题

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.62, NixOS, 22.11 (Raccoon), 22.11pre403473.b784c5ae63d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(yes): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
