### ISSUE TITLE
[Feature Request]: 全局规则

### ISSUE THREAD

**Issue by geniuszxy** [Fndroid/clash_for_windows_pkg#3373]
### 功能描述

有些域名想走直连（比如firefox的自动更新）。手动添加的rule一旦更新profile就会被还原。有没有办法能添加全局的rules，无论使用哪个profile都能起效，而且不会因为更新profile被覆盖。

**Comment by yi-Xu-0100** [comment]
https://docs.cfw.lbyczf.com/contents/parser.html

1. 使用 `reg: ^.*$` 匹配任意规则。
