### ISSUE TITLE
Allow LAN 功能无法正常工作

### ISSUE THREAD

**Issue by cyanlink** [Fndroid/clash_for_windows_pkg#338]
开启Allow LAN，无论在系统的代理设置界面尝试哪个端口（7890/7891/7892），处于同一局域网的设备（Android，Linux 虚拟机）均无法科学上网。设备间都能够互相ping通。

**Comment by UntaggedRui** [comment]
clashx的logs界面有什么提示吗

**Comment by cyanlink** [comment]
@UntaggedRui logs界面没有任何连接的log，进入配置文件更换其他端口似乎也无效。另外，可否在文档补充一下，HTTP/HTTPS等栏位该填写什么端口号吗？

**Comment by cyanlink** [comment]
经检查，这是因为 Windows 防火墙并未允许clash-win64.exe在公有/私有网络上通信造成的。
只要进入防火墙设置，勾选两项，局域网就能正常通信。

**Comment by naturliche** [comment]
@cyanlink 你好，请问一下，我在允许应用通过防火墙中把clash-win64的专用/公用都勾选了，http，https，ftp端口都设置为7890，socks端口号设置为了7891，请问为什么linux虚拟机还是无法科学上网？

**Comment by cyanlink** [comment]
@naturliche 首先你的虚拟机能ping通本机吗？打开clash for windows的log界面，再尝试虚拟机访问google，能看到log里面的记录吗？

**Comment by naturliche** [comment]
抱歉，打扰了，重启之后居然可以了QAQ

**Comment by tea1111980** [comment]
我跟你是同样的问题，我的问题在于 Allow LAN 可以使用，但是速度慢得不正常 只有2KB的速度。但是本机访问代理速度正常，我是虚拟机Linux CentOS-7

**Comment by lkpopo** [comment]
> 经检查，这是因为 Windows 防火墙并未允许clash-win64.exe在公有/私有网络上通信造成的。 只要进入防火墙设置，勾选两项，局域网就能正常通信。

的确是防火墙的问题，我把两项勾上之后还是不行，我直接把共有网络的防火墙关了就可以了。
