### ISSUE TITLE
[Bug]: 无法订阅导入配置

### ISSUE THREAD

**Issue by DioBoLuo** [Fndroid/clash_for_windows_pkg#3385]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.26&0.19.29

### 操作系统

Windows x64

### 系统版本

21H2

### 问题描述

左上角流量一直显示0B/s节点测速全部time out，手机上的clash节点就可以使用（确定了不是节点问题）
用链接下载更新配置也显示network error,也无法从订阅转换链接那里直接导入配置
（貌似是小猫咪不能联网了？）、
卸载重装换了最新版本也无法解决，目前处于完全无法使用的状态。
![0f094eefaaea36e6f27fe6e860c0fec](https://user-images.githubusercontent.com/73374070/187503020-68434a70-8d2a-4014-bfd9-4242900c543a.png)
![c03e908555ebbb058e4648a8c1e9ad4](https://user-images.githubusercontent.com/73374070/187506141-b7f70f6a-669e-4cf9-b285-7965a0404c09.jpg)

### 复现步骤

我也不知道怎么复现，之前用的好好的，一段时间不用然后再也用不了了

### 日志文件

time="2022-08-31T01:03:38+08:00" level=info msg="RESTful API listening at: 127.0.0.1:55018"
time="2022-08-31T01:03:38+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"

**Comment by AkariiinMKII** [comment]
切到direct

**Comment by DioBoLuo** [comment]
> 切到direct

也没用，感觉小猫咪无法联网了貌似

**Comment by yi-Xu-0100** [comment]
@DioBoLuo 如果是 direct 也显示 network error，则订阅链接可能无法通过直连更新或者本身网络有问题。

**Comment by DioBoLuo** [comment]
> 

订阅链接我是直接用的手机版clash的，手机使用正常，网络的话我浏览网站什么都可以，用v2ray也可以正常科学上网，就是用小猫咪就不行了。。。。。

**Comment by DioBoLuo** [comment]
> @DioBoLuo 如果是 direct 也显示 network error，则订阅链接可能无法通过直连更新或者本身网络有问题。

订阅链接我是直接用的手机版clash的，手机使用正常，网络的话我浏览网站什么都可以，用v2ray也可以正常科学上网，就是用小猫咪就不行了。。。。。

**Comment by DioBoLuo** [comment]
在网络设置里把网络重置以后问题似乎解决了，我猜可能是我之前使用加速器修复网络导致的问题。。
