### ISSUE TITLE
bug在网站用QQ号登陆关联账号   不能用电脑上已登陆的QQ直接登陆

### ISSUE THREAD

**Issue by qq704361748** [Fndroid/clash_for_windows_pkg#339]
在网站用QQ号登陆关联账号   不能用电脑上已登陆的QQ直接登陆。断开clash的代理然后刷新就立马正常。

**Comment by killsting** [comment]
我亦有此問題。

**Comment by Code-God1024** [comment]
+1

**Comment by Code-God1024** [comment]
> 在网站用QQ号登陆关联账号 不能用电脑上已登陆的QQ直接登陆。断开clash的代理然后刷新就立马正常。

请问有解决方案了吗

**Comment by qq704361748** [comment]
> > 在网站用QQ号登陆关联账号不能用电脑上已登陆的QQ直接登陆。插入冲突的代理然后刷新就立马正常。
> 
> 请问有解决方案了吗吗

然而并没有

**Comment by Fndroid** [comment]
1. 点General中General YAML下面的小字
2. 在打开的配置文件中``cfw-bypass``加上``*.qq.com``：
```yaml
cfw-bypass:
  - "*.qq.com" # 加上这个
  - localhost
  - 127.*
  ......
```
3. 保存文件

**Comment by Code-God1024** [comment]
> 1. 点General中General YAML下面的小字
> 2. 在打开的配置文件中`cfw-bypass`加上`*.qq.com`：
> 
> ```yaml
> cfw-bypass:
>   - "*.qq.com" # 加上这个
>   - localhost
>   - 127.*
>   ......
> ```
> 
> 1. 保存文件

解决了,之前在Profiles文件里面加了 规则不行,用这个解决了

**Comment by TWiNKL1** [comment]
OK. 解决了

**Comment by Feiyuyu0503** [comment]
我尝试在cfw的home directory中的config.yaml中加入
cfw-bypass:
   - "localhost.ptlogin2.qq.com"
在mixin中也尝试加入了
cfw-bypass:
   - "localhost.ptlogin2.qq.com"
都没有解决这个问题
最后在注册表中搜索 'ProxyOverride'项，在数据中的最后加入localhost.ptlogin2.qq.com就正常了
希望作为另外一种思路做个参考吧

**Comment by yi-Xu-0100** [comment]
bypass 设置项现在在 setting 中设置。与原先不一样了。

**Comment by Feiyuyu0503** [comment]
> bypass 设置项现在在 setting 中设置。与原先不一样了。

感谢！成功了！
