### ISSUE TITLE
[Bug]: 订的季度，但第一个月过完后流量没有重置。我又买了一个重置流量包。

### ISSUE THREAD

**Issue by seapoacher1** [Fndroid/clash_for_windows_pkg#3398]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.20

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

 订的季度，但第一个月过完后流量没有重置。我又买了一个重置流量包。

### 复现步骤

不知道怎么复现，不会只有我一个吧。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by seapoacher1** [comment]
![QQ截图20220902210501](https://user-images.githubusercontent.com/65377749/188152568-f399b761-f1f7-4c5d-914f-056426f69ab2.png)

**Comment by Fndroid** [comment]
在哪里买的联系哪里

**Comment by lujimin** [comment]
这边是客户端又不是机场服务商。。
