### ISSUE TITLE
PAC mode?

### ISSUE THREAD

**Issue by littlef0x** [Fndroid/clash_for_windows_pkg#34]
CFW changes system proxy to 127.0.0.1, which makes UWP apps with loopback disabled unable to access the internet. Meanwhile, V2rayN and shadowsocks use PAC and does not influence UWP apps. So is it possible to add PAC mode to CFW? Thanks.

**Comment by Fndroid** [comment]
PAC里面依然是使用loopback地址作为代理服务器地址，所以并不是使用PAC就能让所有UWP应用正常联网。

PAC中的规则可以使请求绕过系统代理，但这仅限需要直连的应用，如果UWP应用请求被墙内容，一样无法联网。

另一个方面，使用PAC会破坏Clash的分流特性。建议还是使用工具开放UWP的loopback限制。
