### ISSUE TITLE
[Bug]: TUN模式下无法访问GitHub

### ISSUE THREAD

**Issue by caiciyu** [Fndroid/clash_for_windows_pkg#3400]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.29

### 操作系统

Windows x64

### 系统版本

Windows 10 家庭中文版

### 问题描述

已安装service mode，TUN Mode设置为默认设置
在TUN模式下GitHub打不开，只能通过system proxy才能打开，但是之前两个月GitHub可以通过TUN正常访问
![1662190170686](https://user-images.githubusercontent.com/90396377/188260785-6974ecf6-704a-495c-8d48-b9fac334eb78.png)

软件主界面如下图所示：
![1662189026841](https://user-images.githubusercontent.com/90396377/188260163-53350f76-21df-468d-b194-d10081b55a58.png)

值得注意的是，在TUN模式下打开GitHub，当我查看clash的log时，发现有奈飞节点，但我实际上并未打开过奈飞
![1662190127863](https://user-images.githubusercontent.com/90396377/188260765-01bb0971-e706-4119-832c-17f077792cbd.png)

当我再次尝试用global模式时，仍然打不开GitHub
其它网站（如谷歌）在TUN模式下正常访问

### 复现步骤

安装service mode，关闭system proxy，打开TUN Mode，无法访问GitHub

### 日志文件

15:32:14 INF [API] listening addr=127.0.0.1:58283
15:32:14 INF [Inbound] Mixed(http+socks) listening addr=[::]:7890
15:32:14 INF [Config] initial compatible provider name=IPLC负载组
15:32:14 INF [Config] initial compatible provider name=🇯🇵 日本节点
15:32:14 INF [Config] initial compatible provider name=🔯 故障转移
15:32:14 INF [Config] initial compatible provider name=🎥 奈飞节点
15:32:14 INF [Config] initial compatible provider name=🎯 全球直连
15:32:14 INF [Config] initial compatible provider name=台湾负载组
15:32:14 INF [Config] initial compatible provider name=香港负载组
15:32:14 INF [Config] initial compatible provider name=🇭🇰 香港节点
15:32:14 INF [Config] initial compatible provider name=Ⓜ️ 微软云盘
15:32:14 INF [Config] initial compatible provider name=📺 巴哈姆特
15:32:14 INF [Config] initial compatible provider name=🍃 应用净化
15:32:14 INF [Config] initial compatible provider name=新加坡负载组
15:32:14 INF [Config] initial compatible provider name=🚀 手动切换
15:32:14 INF [Config] initial compatible provider name=🔰 节点选择
15:32:14 INF [Config] initial compatible provider name=🎵 网易云音乐
15:32:14 INF [Config] initial compatible provider name=🐟 漏网之鱼
15:32:14 INF [Config] initial compatible provider name=日本负载组
15:32:14 INF [Config] initial compatible provider name=🇸🇬 狮城节点
15:32:14 INF [Config] initial compatible provider name=🇨🇳 台湾节点
15:32:14 INF [Config] initial compatible provider name=🆎 AdBlock
15:32:14 INF [Config] initial compatible provider name=🇬🇧 英国节点
15:32:14 INF [Config] initial compatible provider name=📺 哔哩哔哩
15:32:14 INF [Config] initial compatible provider name=🇺🇲 美国节点
15:32:20 INF [TCP] connected lAddr=127.0.0.1:58512 rAddr=capi.grammarly.com:443 mode=rule rule=Match() proxy=🐟 漏网之鱼[iplc|广港04|1.5x]
15:32:21 INF [Config] initial compatible provider name=日本负载组
15:32:21 INF [Config] initial compatible provider name=IPLC负载组
15:32:21 INF [Config] initial compatible provider name=🆎 AdBlock
15:32:21 INF [Config] initial compatible provider name=Ⓜ️ 微软云盘
15:32:21 INF [Config] initial compatible provider name=📺 巴哈姆特
15:32:21 INF [Config] initial compatible provider name=🇨🇳 台湾节点
15:32:21 INF [Config] initial compatible provider name=🍃 应用净化
15:32:21 INF [Config] initial compatible provider name=🐟 漏网之鱼
15:32:21 INF [Config] initial compatible provider name=新加坡负载组
15:32:21 INF [Config] initial compatible provider name=台湾负载组
15:32:21 INF [Config] initial compatible provider name=🇯🇵 日本节点
15:32:21 INF [Config] initial compatible provider name=🇸🇬 狮城节点
15:32:21 INF [Config] initial compatible provider name=🇭🇰 香港节点
15:32:21 INF [Config] initial compatible provider name=🔯 故障转移
15:32:21 INF [Config] initial compatible provider name=🇬🇧 英国节点
15:32:21 INF [Config] initial compatible provider name=🎥 奈飞节点
15:32:21 INF [Config] initial compatible provider name=📺 哔哩哔哩
15:32:21 INF [Config] initial compatible provider name=🎵 网易云音乐
15:32:21 INF [Config] initial compatible provider name=🎯 全球直连
15:32:21 INF [Config] initial compatible provider name=香港负载组
15:32:21 INF [Config] initial compatible provider name=🇺🇲 美国节点
15:32:21 INF [Config] initial compatible provider name=🚀 手动切换
15:32:21 INF [Config] initial compatible provider name=🔰 节点选择
15:32:21 INF [Inbound] TUN listening iface=Clash gateway=198.18.0.1
15:32:25 INF [TCP] connected lAddr=198.18.0.1:59121 rAddr=dns.weixin.qq.com.cn:80 mode=rule rule=DomainSuffix(cn) proxy=🎯 全球直连[DIRECT]
15:32:25 INF [TCP] connected lAddr=198.18.0.1:59120 rAddr=203.205.253.146:8080 mode=rule rule=Match() proxy=🐟 漏网之鱼[iplc|广港04|1.5x]
15:32:25 INF [TCP] connected lAddr=198.18.0.1:59124 rAddr=www.msftconnecttest.com:80 mode=rule rule=Match() proxy=🐟 漏网之鱼[iplc|广港04|1.5x]
15:32:28 INF [TCP] connected lAddr=198.18.0.1:59131 rAddr=go.microsoft.com:80 mode=rule rule=Match() proxy=🐟 漏网之鱼[iplc|广港04|1.5x]
15:32:29 INF [TCP] connected lAddr=198.18.0.1:59133 rAddr=dmd.metaservices.microsoft.com:80 mode=rule rule=Match() proxy=🐟 漏网之鱼[iplc|广港04|1.5x]
15:32:35 INF [TCP] connected lAddr=198.18.0.1:59144 rAddr=github.githubassets.com:443 mode=rule rule=DomainKeyword(github) proxy=🔰 节点选择[iplc|广港04|1.5x]
15:32:35 INF [TCP] connected lAddr=198.18.0.1:59143 rAddr=13.114.40.48:443 mode=rule rule=IPCIDR(13.112.0.0/14) proxy=🎥 奈飞节点[iplc|广港01|1.5x]
15:32:35 INF [TCP] connected lAddr=198.18.0.1:59148 rAddr=functional.events.data.microsoft.com:443 mode=rule rule=Match() proxy=🐟 漏网之鱼[iplc|广港04|1.5x]
15:32:38 INF [TCP] connected lAddr=198.18.0.1:59153 rAddr=13.114.40.48:443 mode=rule rule=IPCIDR(13.112.0.0/14) proxy=🎥 奈飞节点[iplc|广港01|1.5x]
15:32:43 INF [TCP] connected lAddr=127.0.0.1:59160 rAddr=wx.qlogo.cn:80 mode=rule rule=DomainSuffix(cn) proxy=🎯 全球直连[DIRECT]
15:32:54 INF [TCP] connected lAddr=198.18.0.1:59174 rAddr=assets.msn.cn:443 mode=rule rule=DomainSuffix(cn) proxy=🎯 全球直连[DIRECT]
15:32:55 INF [TCP] connected lAddr=198.18.0.1:59177 rAddr=sb.scorecardresearch.com:443 mode=rule rule=Match() proxy=🐟 漏网之鱼[iplc|广港04|1.5x]
15:32:55 INF [TCP] connected lAddr=198.18.0.1:59176 rAddr=c.msn.cn:443 mode=rule rule=DomainSuffix(cn) proxy=🎯 全球直连[DIRECT]
15:32:55 INF [TCP] connected lAddr=198.18.0.1:59175 rAddr=browser.events.data.msn.cn:443 mode=rule rule=DomainSuffix(cn) proxy=🎯 全球直连[DIRECT]
15:32:55 INF [TCP] connected lAddr=198.18.0.1:59185 rAddr=c.bing.com:443 mode=rule rule=DomainSuffix(bing.com) proxy=🔰 节点选择[iplc|广港04|1.5x]
15:32:55 INF [TCP] connected lAddr=198.18.0.1:59182 rAddr=browser.events.data.msn.cn:443 mode=rule rule=DomainSuffix(cn) proxy=🎯 全球直连[DIRECT]
15:32:55 INF [TCP] connected lAddr=198.18.0.1:59187 rAddr=assets.msn.cn:443 mode=rule rule=DomainSuffix(cn) proxy=🎯 全球直连[DIRECT]
15:32:55 INF [UDP] connected lAddr=198.18.0.1:59534 rAddr=www.google.com:443 mode=rule rule=DomainKeyword(google) proxy=🔰 节点选择[iplc|广港04|1.5x]
15:32:56 INF [UDP] connected lAddr=198.18.0.1:51851 rAddr=www.google.com.hk:443 mode=rule rule=DomainKeyword(google) proxy=🔰 节点选择[iplc|广港04|1.5x]
15:32:56 INF [TCP] connected lAddr=198.18.0.1:59203 rAddr=aa.google.com:443 mode=rule rule=DomainKeyword(google) proxy=🔰 节点选择[iplc|广港04|1.5x]
15:32:57 INF [UDP] connected lAddr=198.18.0.1:55370 rAddr=aa.google.com:443 mode=rule rule=DomainKeyword(google) proxy=🔰 节点选择[iplc|广港04|1.5x]
15:32:59 INF [TCP] connected lAddr=198.18.0.1:59236 rAddr=d27xxe7juh1us6.cloudfront.net:443 mode=rule rule=Domain(d27xxe7juh1us6.cloudfront.net) proxy=🔰 节点选择[iplc|广港04|1.5x]
15:33:00 INF [TCP] connected lAddr=198.18.0.1:59248 rAddr=10.112.0.251:7680 mode=rule rule=IPCIDR(10.0.0.0/8) proxy=🎯 全球直连[DIRECT]
15:33:00 INF [TCP] connected lAddr=198.18.0.1:49556 rAddr=outlook.office365.com:993 mode=rule rule=Domain(outlook.office365.com) proxy=🎯 全球直连[DIRECT]
15:33:00 INF [TCP] connected lAddr=198.18.0.1:59251 rAddr=ogs.google.com.hk:443 mode=rule rule=DomainKeyword(google) proxy=🔰 节点选择[iplc|广港04|1.5x]
15:33:00 INF [UDP] connected lAddr=198.18.0.1:63854 rAddr=ogs.google.com.hk:443 mode=rule rule=DomainKeyword(google) proxy=🔰 节点选择[iplc|广港04|1.5x]
15:33:01 INF [UDP] connected lAddr=198.18.0.1:56881 rAddr=www.gstatic.com:443 mode=rule rule=DomainSuffix(gstatic.com) proxy=🔰 节点选择[iplc|广港04|1.5x]
15:33:01 INF [TCP] connected lAddr=198.18.0.1:59259 rAddr=ssl.gstatic.com:443 mode=rule rule=DomainSuffix(gstatic.com) proxy=🔰 节点选择[iplc|广港04|1.5x]
15:33:07 INF [TCP] connected lAddr=198.18.0.1:49557 rAddr=outlook.office365.com:993 mode=rule rule=Domain(outlook.office365.com) proxy=🎯 全球直连[DIRECT]
15:33:11 INF [TCP] connected lAddr=198.18.0.1:59289 rAddr=edge.microsoft.com:443 mode=rule rule=Match() proxy=🐟 漏网之鱼[iplc|广港04|1.5x]

### 其他补充

TUN设置如下：（默认设置）
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback: []
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53

**Comment by AkariiinMKII** [comment]
较大可能是DNS投毒 改一下解析fallback到doh吧

**Comment by caiciyu** [comment]
> 较大可能是DNS投毒 改一下解析fallback到doh吧

那请问应该怎么改呢？小白求指导

**Comment by caiciyu** [comment]
> 较大可能是DNS投毒 改一下解析fallback到doh吧

点进“Logs”里一看关于GitHub的活动是IP，而没有域名，感觉就是DNS的问题。

**Comment by Fndroid** [comment]
浏览器关闭安全DNS选项

**Comment by caiciyu** [comment]
> 

我关闭了但是仍然没有效果

**Comment by fangruiL** [comment]
你好，不知道你后续解决了没有啊？我现在是连接tun模式就打不开奈飞和迪士尼，油管github这些都能用，就感觉我们情况还挺像的

**Comment by QGB** [comment]
> 你好，不知道你后续解决了没有啊？我现在是连接tun模式就打不开奈飞和迪士尼，油管github这些都能用，就感觉我们情况还挺像的

最新版依然存在这个问题。clash tun模式 无法访问 “github.com”

**Comment by jesse996** [comment]
![image](https://user-images.githubusercontent.com/20895372/213483084-91045fbe-6fe4-4d3f-b8a5-10f4a63e5f18.png)
删掉114.114.114.114那个dns server就行，114是国内的
