### ISSUE TITLE
[Feature Request]: settings页面的设置项，鼠标hover某一项时，整行高亮

### ISSUE THREAD

**Issue by harnseen** [Fndroid/clash_for_windows_pkg#3408]
### 功能描述

在设置页面，左边设置名称和右边开关间距太大，误操作的概率很大，希望能添加鼠标悬浮某一个行时整行高亮的功能

![image](https://user-images.githubusercontent.com/42644295/189254877-3b685769-7502-4231-8468-a4f5ed6d3927.png)

**Comment by yi-Xu-0100** [comment]
要不，不要全屏，缩小下？

**Comment by harnseen** [comment]
> 要不，不要全屏，缩小下？

节点太多了，选择节点的时候全屏看得清楚些
