### ISSUE TITLE
界面上的部分元素可以拖拽下来？

### ISSUE THREAD

**Issue by Olivercoco** [Fndroid/clash_for_windows_pkg#341]
界面上的部分元素可以用鼠标拖拽下来 ，参见截图
![image](https://user-images.githubusercontent.com/39828052/71321106-02720800-24f0-11ea-8942-2822449321cd.png)

**Comment by Fndroid** [comment]
@Olivercoco 会修复

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.8.7
