### ISSUE TITLE
[Bug]: 点“常规”-鼠标左键点击一次 ”Clash for Windows",会出现程序自动重启

### ISSUE THREAD

**Issue by Chengxcy** [Fndroid/clash_for_windows_pkg#3411]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.2

### 操作系统

Windows x64

### 系统版本

Windows 11

### 问题描述

点击主程序界面，“常规”- “Clash for Windows",会出现程序自动重启问题。

### 复现步骤

打开Clash for Windows.exe主程序，启动界面，选“常规”-鼠标左键
![Snipaste_2022-09-10_18-23-19](https://user-images.githubusercontent.com/91258009/189479426-21fd8596-fa09-4b23-9370-7b10097f9d57.png)
点击“Clash for Windows"一次，就会触发程序自动重启。测试了很多版本都有此问题

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

测试了很多版本都有此问题

**Comment by cczy-hub** [comment]
文档中有写，点击“Clash for Windows”（标题）可以快速重启软件

**Comment by Chengxcy** [comment]
> 文档中有写，点击“Clash for Windows”（标题）可以快速重启软件

好的，了解了。
