### ISSUE TITLE
[Feature Request]: 最新版更换meta核心之后无法安装service mode

### ISSUE THREAD

**Issue by isxh416** [Fndroid/clash_for_windows_pkg#3413]
### 功能描述

最新版更换meta核心之后无法安装service mode

**Comment by yi-Xu-0100** [comment]
service 不再支持换核。换核的话，需要使用管理员方式去开启 tun。

**Comment by Fndroid** [comment]
service是高权限的，如果core的二进制被劫持修改则可以无条件获得高权限，这并不安全
