### ISSUE TITLE
[Bug]: 安装最新版v0.20.2虚拟网卡时提示fail to install service

### ISSUE THREAD

**Issue by 47047093** [Fndroid/clash_for_windows_pkg#3417]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.2

### 操作系统

Windows x64

### 系统版本

19044.1889

### 问题描述

描述里提示的是process.title cannot be used as a valid name

### 复现步骤

用绿色版或安装版都提示这个

### 日志文件

09:42:10 INF [API] listening addr=127.0.0.1:55535
09:42:10 INF [Inbound] Mixed(http+socks) listening addr=127.0.0.1:7890

**Comment by yi-Xu-0100** [comment]
截图看看

**Comment by 47047093** [comment]
![class2](https://user-images.githubusercontent.com/33561914/189508724-970e5a3e-43c6-4512-8881-f4317feb76c4.jpg)
![class4](https://user-images.githubusercontent.com/33561914/189508727-5bb07270-c455-43b9-b4da-872fc498f988.jpg)


> 截图看看

**Comment by 47047093** [comment]
有人来回答一下怎么安装TUN吗，谢谢。。一直卡在这里

**Comment by keep1earning** [comment]
“ 使用的是官方版本（未替换及修改过安装目录程序文件）”
