### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Neo-fk** [Fndroid/clash_for_windows_pkg#3419]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.2

### 操作系统

Windows x64

### 系统版本

Windows 10

### 问题描述

1.)   connection error play games & use discord
2.)   service mode not install ( error - fail to install service)

### 复现步骤

Now I always get intermittent disconnection when playing online and using discord but restarting the software solves it but it's hard to keep doing it while playing so please fix it

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
@Neo-fk It is recommended to give the service status, color, and prompt after the installation has failed. You can try to install multiple times first, if prompted for permission, restart the software according to the prompts and then try to install.
