### ISSUE TITLE
安装clash以后配置yaml一直报错

### ISSUE THREAD

**Issue by surpassSelf** [Fndroid/clash_for_windows_pkg#342]

**Comment by surpassSelf** [comment]
报错内容：Could Not switch to this profile

**Comment by Fndroid** [comment]
请确保APP成功启动再切换配置文件

**Comment by waterzeong** [comment]
![image](https://user-images.githubusercontent.com/4068635/78148716-c68ffc80-7467-11ea-8d17-ad36a28690fc.png)

**Comment by Fndroid** [comment]
@waterzeong 格式错误，要按照clash配置文件格式

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
