### ISSUE TITLE
[Bug]: 无法安装Service Mode

### ISSUE THREAD

**Issue by 47047093** [Fndroid/clash_for_windows_pkg#3420]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.2

### 操作系统

Windows x64

### 系统版本

win7 sp1

### 问题描述

不管换什么版本，都不能安装Service Mode，提示
![class](https://user-images.githubusercontent.com/33561914/189511249-8610caf6-9a6f-44f4-8f63-3553be0a405a.jpg)
而且class core后面有个感叹号
![class2](https://user-images.githubusercontent.com/33561914/189511265-edb05d5f-fc4a-43ab-aa32-4baf2c9c07af.jpg)

请问怎么解决啊，谢谢。

### 复现步骤

搜索clash把所有文件都删除后依旧不行。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
1. 新版 electron 即将不支持 win7，建议迁移到 win10.
2. service 并不是一定要安装，如果不是特定需要 tun 的话。
3. Clash Core 后面的盾牌是为了配置防火墙设置，如果不需要使用 tun 中的 system 或者 allow lan，都可以不用管，点击盾牌会配置，成功会变成绿色。
4. 暂无明确说法解决 `process.title cannot be used as a valid name.` 的问题。

**Comment by 47047093** [comment]
> 

感谢，
1，主力机习惯用WIN7了，如果要换WIN10好多东西要重新配置。
2，就是想用TUN尝试代理抓包。
3，这个后面我点了没反应，不弹配置，看来还是系统问题了。
4，是我搜索也没搜到怎么解决这process.title cannot be used as a valid name的问题啊。

**Comment by yi-Xu-0100** [comment]
@47047093 如果想临时使用，这里给出 service mode 的替代方案（service mode 主要是给 CFW 提权）：

1. 直接管理员方式使用 CFW，开机自启应该会失效，可以尝试配置计划任务。
2. 使用 UAC 白名单等方式越过授权。

**Comment by 47047093** [comment]
> 

@yi-Xu-0100 主要是想用TUN的规则允许用fiddler抓包到微信小程序，如果是替代方案估计行不通的,UAC在WIN7的权限我已经设置到最低权限了

**Comment by 47047093** [comment]
> 

@yi-Xu-0100 主要是想用TUN的规则允许用fiddler抓包到微信小程序，如果是替代方案估计行不通的,UAC在WIN7的权限我已经设置到最低权限了

**Comment by yi-Xu-0100** [comment]
@47047093 这里给出的替代方案也是为了给 CFW 提权，之后就能正常使用 tun 了。service 可以是 tun 的充分条件，但不是必要条件。

**Comment by 47047093** [comment]
> 

@yi-Xu-0100 

> @47047093 这里给出的替代方案也是为了给 CFW 提权，之后就能正常使用 tun 了。service 可以是 tun 的充分条件，但不是必要条件。

@yi-Xu-0100 我有尝试管理员运行CFW，我发现TUN还是不亮的啊，我网络配置那也不会出现虚拟网卡，这样也能正常使用TUN吗？我打开XFW连接那现在显示的是
![tun](https://user-images.githubusercontent.com/33561914/189511932-e5ba5493-4f35-4a0f-8782-2c65306f9b87.jpg)
CFW配置页面显示
![tun2](https://user-images.githubusercontent.com/33561914/189511938-7f8e9d77-3039-4067-80e2-1f3e88318257.jpg)

**Comment by ac1982** [comment]
Win11也有这个问题，fail to install service

**Comment by 47047093** [comment]
> Win11也有这个问题，fail to install service

@ac1982 请问你解决了吗？

**Comment by xCANVAS** [comment]
我也是遇到这个问题，我电脑win11。fail to install service
![image](https://user-images.githubusercontent.com/76691501/189559263-2e746667-0bcf-4f60-8ac9-3f49fb7d5720.png)
我没有任何报错信息。

**Comment by Yuan68** [comment]
我也是遇到这个问题，但是我是可能有覆盖过.config/clash文档，并且是0.16.3老版本安装的时候意外退出，然后升级了0.20.3。现在删除所有的文件，在0.16.3卸载重装没有任何提升，0.20.3就是这个错误。按照文档中手动安装没有找到service的文件夹，手动复制过去安装没有报错，但是没有绿色地球。

**Comment by 47047093** [comment]
> 我也是遇到这个问题，但是我是可能有覆盖过.config/clash文档，并且是0.16.3老版本安装的时候意外退出，然后升级了0.20.3。现在删除所有的文件，在0.16.3卸载重装没有任何提升，0.20.3就是这个错误。按照文档中手动安装没有找到service的文件夹，手动复制过去安装没有报错，但是没有绿色地球。

恩，我也试过手动复制进去，还是报错的，WIN7，也不知道哪的问题了，我以前没有安装过老版本。所有文件我确定是删除干净了，用搜索也用了卸载工具去删除的。
