### ISSUE TITLE
[Feature Request]:  旧版一个好用的地方

### ISSUE THREAD

**Issue by newera-1992** [Fndroid/clash_for_windows_pkg#3422]
### 旧版一个好用的地方

> 很多版本之前了

就是右下角小图标，右键弹出菜单后，直接按 S 就是开关代理，按 Q 就是退出。

（现在需要按 S 后再按 Enter，能否考虑一下弹出菜单的首字母 S 唯一？）

（目前 Q 还保留，因为 菜单首字母 Q 目前唯一）

**Comment by Fndroid** [comment]
下个版本调整一下，S不唯一但会捕获键盘输入

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
