### ISSUE TITLE
[Bug]: 【已解决】service mode 安装失败但是无报错具体信息

### ISSUE THREAD

**Issue by xCANVAS** [Fndroid/clash_for_windows_pkg#3426]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.2

### 操作系统

Windows x64

### 系统版本

Windows 11 21h2

### 问题描述

安装service mode。报错：
![image](https://user-images.githubusercontent.com/76691501/189608555-87f305ed-6cdc-454d-a669-515c55493ab2.png)
卸载service mode。报错：
![image](https://user-images.githubusercontent.com/76691501/189609194-627cbce9-caf4-463e-9a33-2f9ede6971df.png)
更新service mode。报错：
![image](https://user-images.githubusercontent.com/76691501/189609277-8e0fe7cd-2d7b-42cc-884d-00c0a7bc667a.png)

安装失败但是无具体报错提示信息。早上起来看到一些issue，虽然他们也无法安装service mode，但是他们有具体报错提示信息。

### 复现步骤

昨天晚上更新了clash for windows 0.20.2。
然后发现service mode显示灰色
点击install service mode。
安装完成显示橙红色，点击update，报错：
![image](https://user-images.githubusercontent.com/76691501/189609045-204ea398-232e-4dc4-8945-d2c105740502.png)
点击uninstall，报错：
![image](https://user-images.githubusercontent.com/76691501/189609194-627cbce9-caf4-463e-9a33-2f9ede6971df.png)
但是reload重启软件之后，service mode地球图标变成灰色了。
于是重新install，还是不行。
![image](https://user-images.githubusercontent.com/76691501/189608555-87f305ed-6cdc-454d-a669-515c55493ab2.png)
service mode

**Comment by Fndroid** [comment]
Service Mode 更新后如果 manage 里显示 active 但图标显示红色，可以进入 Home Directory 管理员启动 cmd，执行 `icacls.exe service /remove:d Everyone` 后手动删除 service 文件夹，重启 APP 即可

**Comment by xCANVAS** [comment]
请问Home Directory指的是Clash for Windows的安装目录吗？

**Comment by Fndroid** [comment]
general里的home directory

**Comment by danielchans** [comment]
> general里的home directory

执行后显示如下，是什么原因呢？
C:\Users\Administrator>icacls.exe service /remove:d Everyone
service: 系统找不到指定的文件。
已成功处理 0 个文件; 处理 1 个文件时失败

**Comment by danielchans** [comment]
> Service Mode 更新后如果 manage 里显示 active 但图标显示红色，可以进入 Home Directory 管理员启动 cmd，执行 `icacls.exe service /remove:d Everyone` 后手动删除 service 文件夹，重启 APP 即可

执行后显示如下，是什么原因呢？
C:\Users\Administrator>icacls.exe service /remove:d Everyone
service: 系统找不到指定的文件。
已成功处理 0 个文件; 处理 1 个文件时失败

**Comment by xCANVAS** [comment]
> > Service Mode 更新后如果 manage 里显示 active 但图标显示红色，可以进入 Home Directory 管理员启动 cmd，执行 `icacls.exe service /remove:d Everyone` 后手动删除 service 文件夹，重启 APP 即可
> 
> 执行后显示如下，是什么原因呢？ C:\Users\Administrator>icacls.exe service /remove:d Everyone service: 系统找不到指定的文件。 已成功处理 0 个文件; 处理 1 个文件时失败

我也有这个问题。

**Comment by yi-Xu-0100** [comment]
@danielchans @xCANVAS 需要在 home directory 目录下执行

**Comment by danielchans** [comment]
> icacls.exe service /remove:d Everyone

感谢回答，按照你说的执行后显示如下：
![Snipaste_2022-09-12_18-53-26](https://user-images.githubusercontent.com/72936182/189636331-e48e1811-1048-4e0b-8278-54e73747694d.jpg)

**Comment by yi-Xu-0100** [comment]
@danielchans 从你第一次的回复看，是能够执行的，与现在的截图不符合，是否是需要管理员模式运行？

**Comment by danielchans** [comment]
> 

第一次是因为多复制了“C:\Users\Administrator>”，所以执行失败了

**Comment by yi-Xu-0100** [comment]
@danielchans 不，我指的是这里 

> C:\Users\Administrator>icacls.exe service /remove:d Everyone
service: 系统找不到指定的文件。
已成功处理 0 个文件; 处理 1 个文件时失败

看起来是能够执行的，只是没找到 service 文件夹，但是后续你的执行，是无法使用 icacls.exe

你也可以尝试，其他如 360 等管理软件粉碎这个文件夹

**Comment by xCANVAS** [comment]
完美解决！谢谢作者大大！
![image](https://user-images.githubusercontent.com/76691501/189672650-0f6f85b6-06e9-4b41-b9e2-6ac2df378a2b.png)
![image](https://user-images.githubusercontent.com/76691501/189672780-12a3f552-cd86-410d-85ee-222f4bb74fbc.png)

**Comment by danielchans** [comment]
> icacls.exe service /remove:d Everyone

感谢大佬
执行icacls.exe service /remove:d Everyone仍然失败，但是尝试用360粉碎文件成功。

**Comment by RichardWinters** [comment]
> > icacls.exe service /remove:d Everyone
> 
> 感谢大佬 执行icacls.exe service /remove:d Everyone仍然失败，但是尝试用360粉碎文件成功。

请问是粉碎哪个文件？我尝试粉碎clash文件夹下面所有文件，粉碎文件没问题，但还是无法解决问题。。。
 #![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/11906517/5e7538a1-b43e-4ba0-9572-eff3fad79684)
