### ISSUE TITLE
通过外部控制 http://127.0.0.1:63625/proxies 访问 页面显示{"message":"Unauthorized"}

### ISSUE THREAD

**Issue by jackwan990** [Fndroid/clash_for_windows_pkg#3428]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

clash for windows v0.19.29

### 操作系统

Windows x64

### 系统版本

Windows 11家庭中文版

### 问题描述

通过外部控制 http://127.0.0.1:63625/proxies 访问 页面

页面返回显示{"message":"Unauthorized"}

请问，如何能通过外部控制链接 进行获取代理列表，不出现上面问题
目前不知道如何去解决

--------------------------------------------------------
config.yaml 如下

mixed-port: 7890
allow-lan: true
external-controller: 127.0.0.1:63625
secret: 517a6e1e-8882-411d-bd2b-a00aa2b6473c

### 复现步骤

我们系统通过外部控制ip进行访问获得 代理列表。
通过外部控制 http://127.0.0.1:63625/proxies 
但页面显示{"message":"Unauthorized"}

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Lemmingh** [comment]
请再读一遍文档：
<https://github.com/Dreamacro/clash/wiki/External-controller-API-Reference#authentication>

```powershell
$Endpoint = '127.0.0.1:63625'
$Secret = '517a6e1e-8882-411d-bd2b-a00aa2b6473c'

$Request = @{
    Headers = @{ Authorization = "Bearer $Secret" }
    Method  = 'Get'
    Uri     = "http://$Endpoint/proxies"
}

$Response = Invoke-RestMethod @Request
ConvertTo-Json -InputObject $Response -Depth 100
```

**Comment by jackwan990** [comment]
非常谢谢！
