### ISSUE TITLE
功能增加建议：定时自动请求订阅链接

### ISSUE THREAD

**Issue by hongwanzhang** [Fndroid/clash_for_windows_pkg#343]
你好，clash非常好用，非常感谢；
请问能否增加定时自动请求订阅链接的功能？机场订阅链接会偶尔更新，如果可以自动更新就不需要自己点击刷新了。或者给个选项，默认不自动刷新，需要的时候才开启。

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/71338358-8973be80-258a-11ea-9a24-863855243288.png)
