### ISSUE TITLE
[Bug]: 无法代理tailscale的流量

### ISSUE THREAD

**Issue by tony1016** [Fndroid/clash_for_windows_pkg#3431]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.29

### 操作系统

Linux

### 系统版本

ubuntu 20.04

### 问题描述

因为我使用的网络有网络访问限制，但是通过代理可以。但是我发现无法代理tailscale访问DERP的流量，导致无法连接tailscale的节点

### 复现步骤

正常使用tailscale，在connection中未见tailscale的连接

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

tailscale的日志

tailscale.tailscaled[98495]: magicsock: [0xc0000de4b0] derp.Recv(derp-7): derphttp.Client.Recv connect to region 7 (tok): read tcp4 172.31.83.126:36426->103.84.155.188:443: read: connection reset by peer

**Comment by Lemmingh** [comment]
* <https://github.com/Dreamacro/clash/issues/2251>

**Comment by tony1016** [comment]
> * [[Bug] clash与tailscale的兼容问题 Dreamacro/clash#2251](https://github.com/Dreamacro/clash/issues/2251)

这个问题非常奇怪，我用LXC跑tailscale，host上的CFW就能抓到流量了，是不是tailscale使用的协议栈导致CFW直接是抓不到的

**Comment by tony1016** [comment]
原因找到了，因为tailscale在ip rule中的规则比较靠前

5210:	from all fwmark 0x80000 lookup main
5230:	from all fwmark 0x80000 lookup default
5250:	from all fwmark 0x80000 unreachable

只需要新增一条rule将流量打到tun即可
