### ISSUE TITLE
设置中的配置编辑器的作用是什么? (cfw/vscode)

### ISSUE THREAD

**Issue by ddzzkunye** [Fndroid/clash_for_windows_pkg#3436]
![image](https://user-images.githubusercontent.com/92249100/190296272-a14405d6-0527-4865-b198-d2f6f4384e4b.png)
![image](https://user-images.githubusercontent.com/92249100/190296296-6093be2a-3373-4418-ac9d-8f7349bae22b.png)

**Comment by kusiru** [comment]
打开文件方式

**Comment by ddzzkunye** [comment]
我修改了它们但并未观察到变化, 所以提了这个问题
我查阅了文档但没有找到相关说明

**Comment by ddzzkunye** [comment]
> 打开文件方式

我修改了它们但并未观察到变化, 所以提了这个问题
我查阅了文档但没有找到相关说明
