### ISSUE TITLE
关于 dns 字段的可覆盖性

### ISSUE THREAD

**Issue by RunningMelos** [Fndroid/clash_for_windows_pkg#344]
引援[配置文件 · Clash for Windows](https://docs.cfw.lbyczf.com/contents/configfile.html)此处的描述： 
>用户配置文件里的 Proxy/Proxy Group/Rule/dns 这几个字段的内容会被替换到 Clash 里面 

如果机场所提供的 Profile 包含了不标准的 dns 内容，此时如果要开启 TAP 模式，就必须手动修改 Profiles 内关于 dns 字段的内容，且每次更新订阅都要做出相应的修改。

但有注意到 CFW 的 `config.yml` 里也包含了关于 dns 字段的定义，那么此时能不能添加一个类似 `cfw-dns:` 的设置来让 CFW 仅仅使用 `config.yml` 里的 dns 内容呢？这样不管 Profiles 如何变化，dns 都只和 `config.yml` 里设置的有关。

-----
此外：此处关于 机场 的假设只是想说明 dns 字段的一些内容，事实上有时候为了保证同一份 Profile 能够在 Android上也能有足够的适应性，也会将 dns 字段稍作修改，希望F大可以理解。

**Comment by Fndroid** [comment]
切换配置dns覆盖是Clash Core的行为，而且目前也没办法改变

**Comment by RunningMelos** [comment]
🙌谢谢F大解答，这样的话就了解了。
