### ISSUE TITLE
[Feature Request]: CFW可否提供便携版本

### ISSUE THREAD

**Issue by Curious-r** [Fndroid/clash_for_windows_pkg#3441]
### 功能描述

指免安装、运行配置都保存在程序目录下，整个目录拷贝到新的机器上即可正常运行。
不知道现在本软件是否具有此功能，我目前下载的解压即用版本，在程序内更新后也会变成安装版，并且配置文件存在系统中用户目录下，迁移不便。

**Comment by AkariiinMKII** [comment]
https://docs.cfw.lbyczf.com/contents/7z.html#%E4%BE%BF%E6%90%BA%E6%A8%A1%E5%BC%8F

**Comment by Curious-r** [comment]
> https://docs.cfw.lbyczf.com/contents/7z.html#%E4%BE%BF%E6%90%BA%E6%A8%A1%E5%BC%8F

感谢！
