### ISSUE TITLE
[Bug]: 错别字

### ISSUE THREAD

**Issue by LightAPIs** [Fndroid/clash_for_windows_pkg#3446]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.3

### 操作系统

macOS amd64(Intel)

### 系统版本

12.5.1

### 问题描述

`Show Process If Present` 的说明里有一个错别字🐶，如图：

![weather](https://gcore.jsdelivr.net/gh/LightAPIs/PicGoImg@master/img/202209161246602.jpg)

### 复现步骤

- 打开 `Settings`

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
😂下个版本改

**Comment by LightAPIs** [comment]
Fixed in 0.20.4
