### ISSUE TITLE
最近几天clash一直连不上网

### ISSUE THREAD

**Issue by YYZ-rose** [Fndroid/clash_for_windows_pkg#345]
几个节点都是timeout，好几天都是这样。

**Comment by Fndroid** [comment]
timeout表示无法连接至该节点，请自行检查

**Comment by YYZ-rose** [comment]
> timeout表示无法连接至该节点，请自行检查

操作流程是正确的，但无论是电脑还是手机都是连接不上节点。

**Comment by Fndroid** [comment]
那节点问题排除了吗，比如用其他软件能否连接

**Comment by YYZ-rose** [comment]
> 那节点问题排除了吗，比如用其他软件能否连接

clash的所有节点一直连不上，我用蓝灯还有chomre插件都可以翻墙。

**Comment by Fndroid** [comment]
如果不知道怎么排除，就请自行联系给你节点的人

**Comment by YYZ-rose** [comment]
Could not switch to this profile错误
time="2019-12-25T16:12:07+08:00" level=info msg="Start initial compatible provider Proxy"
time="2019-12-25T16:12:07+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2019-12-25T16:12:07+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2019-12-25T16:12:07+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2019-12-25T16:12:07+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2019-12-25T16:12:08+08:00" level=info msg="127.0.0.1 --> 104.143.229.163 doesn't match any rule using DIRECT"
time="2019-12-25T16:12:08+08:00" level=info msg="127.0.0.1 --> 104.143.229.163 doesn't match any rule using DIRECT"
time="2019-12-25T16:12:13+08:00" level=warning msg="dial GLOBAL error: dial tcp4 91.108.56.102:80: i/o timeout"
time="2019-12-25T16:12:13+08:00" level=warning msg="dial GLOBAL error: dial tcp4 91.108.56.140:80: i/o timeout"
time="2019-12-25T16:12:13+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.175.55:80: i/o timeout"
time="2019-12-25T16:12:13+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.175.55:443: i/o timeout"
time="2019-12-25T16:12:13+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.175.55:80: i/o timeout"
time="2019-12-25T16:12:13+08:00" level=info msg="127.0.0.1 --> 104.143.229.163 match Match using DIRECT"
time="2019-12-25T16:12:14+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.167.50:80: i/o timeout"
time="2019-12-25T16:12:14+08:00" level=warning msg="dial GLOBAL error: dial tcp4 91.108.56.140:80: i/o timeout"
time="2019-12-25T16:12:14+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.167.51:443: i/o timeout"
time="2019-12-25T16:12:14+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.167.50:443: i/o timeout"
time="2019-12-25T16:12:14+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.167.51:80: i/o timeout"
time="2019-12-25T16:12:14+08:00" level=warning msg="dial GLOBAL error: dial tcp4 91.108.56.140:443: i/o timeout"
time="2019-12-25T16:12:14+08:00" level=warning msg="dial GLOBAL error: dial tcp4 91.108.56.102:443: i/o timeout"
time="2019-12-25T16:12:14+08:00" level=warning msg="dial GLOBAL error: dial tcp4 91.108.56.102:80: i/o timeout"
time="2019-12-25T16:12:15+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.167.50:80: i/o timeout"
time="2019-12-25T16:12:15+08:00" level=warning msg="dial GLOBAL error: dial tcp4 104.143.229.163:443: i/o timeout"
time="2019-12-25T16:12:15+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.167.51:443: i/o timeout"
time="2019-12-25T16:12:15+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.167.50:443: i/o timeout"
time="2019-12-25T16:12:15+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.167.51:80: i/o timeout"
time="2019-12-25T16:12:16+08:00" level=info msg="127.0.0.1 --> 104.143.229.163 doesn't match any rule using DIRECT"
time="2019-12-25T16:12:17+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.167.50:80: i/o timeout"
time="2019-12-25T16:12:17+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.167.51:443: i/o timeout"
time="2019-12-25T16:12:17+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.167.50:443: i/o timeout"
time="2019-12-25T16:12:17+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.167.51:80: i/o timeout"
time="2019-12-25T16:12:19+08:00" level=warning msg="dial GLOBAL error: dial tcp4 91.108.56.140:80: i/o timeout"
time="2019-12-25T16:12:19+08:00" level=warning msg="dial GLOBAL error: dial tcp4 91.108.56.102:80: i/o timeout"
time="2019-12-25T16:12:19+08:00" level=warning msg="dial GLOBAL error: dial tcp4 104.143.229.163:443: i/o timeout"
time="2019-12-25T16:12:21+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.167.50:80: i/o timeout"
time="2019-12-25T16:12:21+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.167.51:443: i/o timeout"
time="2019-12-25T16:12:21+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.167.50:443: i/o timeout"
time="2019-12-25T16:12:21+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.167.51:80: i/o timeout"
time="2019-12-25T16:12:21+08:00" level=warning msg="dial GLOBAL error: dial tcp4 104.143.229.163:443: i/o timeout"
time="2019-12-25T16:12:22+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.175.100:443: i/o timeout"
time="2019-12-25T16:12:22+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.175.100:80: i/o timeout"
time="2019-12-25T16:12:22+08:00" level=warning msg="dial GLOBAL error: dial tcp4 91.108.56.140:80: i/o timeout"
time="2019-12-25T16:12:22+08:00" level=warning msg="dial GLOBAL error: dial tcp4 91.108.56.140:443: i/o timeout"
time="2019-12-25T16:12:22+08:00" level=warning msg="dial GLOBAL error: dial tcp4 91.108.56.102:443: i/o timeout"
time="2019-12-25T16:12:22+08:00" level=warning msg="dial GLOBAL error: dial tcp4 91.108.56.102:80: i/o timeout"
time="2019-12-25T16:12:22+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.175.100:443: i/o timeout"
time="2019-12-25T16:12:22+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.175.100:80: i/o timeout"
time="2019-12-25T16:12:24+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.175.100:443: i/o timeout"
time="2019-12-25T16:12:24+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.175.100:80: i/o timeout"
time="2019-12-25T16:12:26+08:00" level=warning msg="dial GLOBAL error: dial tcp4 104.143.229.163:443: i/o timeout"
time="2019-12-25T16:12:27+08:00" level=warning msg="dial GLOBAL error: dial tcp4 91.108.56.140:80: i/o timeout"
time="2019-12-25T16:12:27+08:00" level=warning msg="dial GLOBAL error: dial tcp4 91.108.56.102:80: i/o timeout"
time="2019-12-25T16:12:27+08:00" level=warning msg="dial GLOBAL error: dial tcp4 104.143.229.163:443: i/o timeout"
time="2019-12-25T16:12:28+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.175.100:443: i/o timeout"
time="2019-12-25T16:12:28+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.175.100:80: i/o timeout"
time="2019-12-25T16:12:29+08:00" level=warning msg="dial GLOBAL error: dial tcp4 104.143.229.163:443: i/o timeout"
time="2019-12-25T16:12:29+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.167.91:443: i/o timeout"
time="2019-12-25T16:12:30+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.167.91:80: i/o timeout"
time="2019-12-25T16:12:30+08:00" level=warning msg="dial GLOBAL error: dial tcp4 91.108.56.140:80: i/o timeout"
time="2019-12-25T16:12:30+08:00" level=warning msg="dial GLOBAL error: dial tcp4 91.108.56.140:443: i/o timeout"
time="2019-12-25T16:12:30+08:00" level=warning msg="dial GLOBAL error: dial tcp4 91.108.56.102:443: i/o timeout"
time="2019-12-25T16:12:30+08:00" level=warning msg="dial GLOBAL error: dial tcp4 91.108.56.102:80: i/o timeout"
time="2019-12-25T16:12:30+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.167.91:443: i/o timeout"
time="2019-12-25T16:12:30+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.167.91:80: i/o timeout"
time="2019-12-25T16:12:32+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.167.91:443: i/o timeout"
time="2019-12-25T16:12:32+08:00" level=warning msg="dial GLOBAL error: dial tcp4 149.154.167.91:80: i/o timeout"

**Comment by Comah** [comment]
这很明显是节点太烂的问题了 086除了uwp走规则连不上外 其它没问题

**Comment by YYZ-rose** [comment]
是时间的问题

**Comment by ms20hj** [comment]
> 是时间的问题

可以了，时间快了3分钟，改回来就可以了
