### ISSUE TITLE
win10 64位操作系统下载哪个版本？

### ISSUE THREAD

**Issue by zmou** [Fndroid/clash_for_windows_pkg#3450]
### 功能描述

win10 64位操作系统下载哪个版本？releases里的版本没看明白windows 64位操作系统应该下载哪个

**Comment by Lemmingh** [comment]
* x86-64 用没有架构后缀的。

* ARM64 用 `arm64`。

**Comment by CoolPlayLin** [comment]
这个：[下载链接](https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.20.3/Clash.for.Windows.Setup.0.20.3.exe)

**Comment by PingZi-Wing** [comment]
把Assets展开就可以看到了，附件多被折叠了
