### ISSUE TITLE
I can't find the version I should download 我找不到我应该下载的版本

### ISSUE THREAD

**Issue by miaowu001** [Fndroid/clash_for_windows_pkg#3452]
My computer's system type is a 64 bit operating system based on x64 processor
Should I download [Flash. for. Windows - 0.20.3 - win. 7z]

我电脑的系统类型是  64 位操作系统, 基于 x64 的处理器
我是否应该下载   [Clash.for.Windows-0.20.3-win.7z]

**Comment by yi-Xu-0100** [comment]
@miaowu001 我觉得你可以尝试一下，当然 7z 后缀的是便携版本。

**Comment by mehdifirefox** [comment]
I Windows 10 64 Bit
I downloaded this
Clash.for.Windows.Setup.0.20.3.arm64.exe 

I think this file has a problem
I go to the installer file folder no file

**Comment by Fndroid** [comment]
<img width="428" alt="image" src="https://user-images.githubusercontent.com/16091562/191909296-67f05675-cad2-4ce6-905a-826a1f3962c2.png">

**Comment by mehdifirefox** [comment]
> <img alt="تصویر" width="428" src="">

what arm64.exe ?

**Comment by mehdifirefox** [comment]
> من ویندوز 10 64 بیت من اینو دانلود کردم Clash.for.Windows.Setup.0.20.3.arm64.exe
> 
> فکر کنم این فایل مشکل داره من به پوشه فایل نصب کننده no file می روم


I downloaded it
Clash.for.Windows.Setup.0.20.4.exe 
I have the same problem again again.

But this time I hit the first option as installed for all users
I was able to install

I think clash has a big problem to install
