### ISSUE TITLE
[Bug]: add firewall rules没有用

### ISSUE THREAD

**Issue by Snakebinp** [Fndroid/clash_for_windows_pkg#3453]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.3

### 操作系统

Windows x64

### 系统版本

21H2

### 问题描述

add firewall rules没有用，防火墙规则没有添加上，还是需要手动添加防火墙规则才能使用局域网连接功能

### 复现步骤

General→Clash Core 🛡→允许管理员权限

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by AkariiinMKII** [comment]
#### 1. 把 UAC 调到二档
![image](https://user-images.githubusercontent.com/6019344/190859576-e3fef1b9-5a5d-4142-bb11-eb1c5b12fa79.png)

#### 2. 点击添加防火墙规则按钮，弹出 UAC 窗口后不要点击，打开 PowerShell 执行
```PowerShell
Get-Content $env:LOCALAPPDATA\Temp\cfw-core-bypass-firewall.ps1
```
把输出的内容贴出来看一下

#### 3. 然后执行（弹出 UAC 窗口时点击允许）
```PowerShell
Start-Process powershell.exe -ArgumentList "$env:LOCALAPPDATA\Temp\cfw-core-bypass-firewall.ps1" -Verb RunAS -wait | Write-Error
```
如果有输出内容也贴出来看一下

#### 4. 以管理员权限打开 PowerShell 并执行
```PowerShell
Get-NetFirewallRule -Enabled True | ? { ($_.Description -eq "Work with Clash for Windows.") } | % { $_ | Get-NetFirewallPortFilter | Select-Object -ExpandProperty Protocol; $_ | Get-NetFirewallApplicationFilter | Select-Object -ExpandProperty Program }
```
把输出的内容贴出来看一下

**Comment by Snakebinp** [comment]
1.![Snipaste_2022-09-17_22-17-37](https://user-images.githubusercontent.com/44097708/190861902-284b0182-a963-4b1a-b1f0-b11787002842.png)
2.
![Snipaste_2022-09-17_22-20-44](https://user-images.githubusercontent.com/44097708/190861915-f3ee7a38-10fd-4a90-a1ad-cb36bbcbd965.png)
3.
![Snipaste_2022-09-17_22-22-16](https://user-images.githubusercontent.com/44097708/190861919-d3cc7d78-53fa-4700-a9c4-3609ebcebcb5.png)
4.
![Snipaste_2022-09-17_22-23-22](https://user-images.githubusercontent.com/44097708/190861929-ce5de7c2-df93-4838-b818-829b34435971.png)

**Comment by AkariiinMKII** [comment]
> 1.![Snipaste_2022-09-17_22-17-37](https://user-images.githubusercontent.com/44097708/190861902-284b0182-a963-4b1a-b1f0-b11787002842.png) 2. ![Snipaste_2022-09-17_22-20-44](https://user-images.githubusercontent.com/44097708/190861915-f3ee7a38-10fd-4a90-a1ad-cb36bbcbd965.png) 3. ![Snipaste_2022-09-17_22-22-16](https://user-images.githubusercontent.com/44097708/190861919-d3cc7d78-53fa-4700-a9c4-3609ebcebcb5.png) 4. ![Snipaste_2022-09-17_22-23-22](https://user-images.githubusercontent.com/44097708/190861929-ce5de7c2-df93-4838-b818-829b34435971.png)

这个结果是规则已经成功添加了

**Comment by Snakebinp** [comment]
卧槽，还真能局域网代理了。之前确实不能的，不晓得为啥现在可以了

**Comment by Snakebinp** [comment]
感谢大佬

**Comment by AkariiinMKII** [comment]
> 卧槽，还真能局域网代理了。之前确实不能的，不晓得为啥现在可以了

按理说这个只是把cfw做的事情手动做了一遍而已 效果是一样的

**Comment by Snakebinp** [comment]
好的，不管咋说，感谢

**Comment by Snakebinp** [comment]
不管咋说感谢大佬



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月17日(星期六) 晚上10:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Fndroid/clash_for_windows_pkg] [Bug]: add firewall rules没有用 (Issue #3453)





  
卧槽，还真能局域网代理了。之前确实不能的，不晓得为啥现在可以了
  
按理说这个只是把cfw做的事情手动做了一遍而已 效果是一样的

**Comment by cccff** [comment]
这咋办啊
