### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Apologetic22** [Fndroid/clash_for_windows_pkg#3455]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.3

### 操作系统

Windows x64

### 系统版本

windows 11 x64

### 问题描述

Failed to Clash core , logs are not available
![image](https://user-images.githubusercontent.com/99374816/190882374-d251b51e-176f-44f3-bb65-12cb964076db.png)
请问我怎么修复他，我换成别的版本也不管用，删除.config不行，手动启动clash core 和 clash 64也不行

### 复现步骤

Failed to Clash core , logs are not available
![image](https://user-images.githubusercontent.com/99374816/190882374-d251b51e-176f-44f3-bb65-12cb964076db.png)
请问我怎么修复他，我换成别的版本也不管用，删除.config不行，手动启动clash core 和 clash 64也不行

### 日志文件

09:59:40 INF [API] listening addr=127.0.0.1:52668
09:59:40 INF [Inbound] Mixed(http+socks) listening addr=127.0.0.1:7890

**Comment by Fndroid** [comment]
把安装目录加到防火墙白名单

**Comment by Apologetic22** [comment]
我防火墙都关了啊

**Comment by Apologetic22** [comment]
> 把安装目录加到防火墙白名单

我防火墙关了啊
