### ISSUE TITLE
建议：根据延迟和丢包率自动选择线路

### ISSUE THREAD

**Issue by realhuyang** [Fndroid/clash_for_windows_pkg#346]
希望可以添加自动选择线路的功能，每隔一段时间 ping 一下，自动选择最优线路。

我 ss 一共几十条线路，有时候某些线路炸了，要手动切换，很麻烦。
希望添加此功能，谢谢

**Comment by RunningMelos** [comment]
有个策略叫url-test

**Comment by iamyingzhou** [comment]
> 有个策略叫url-test

怎么搞啊 老哥

**Comment by Jet-coco** [comment]
#417

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
