### ISSUE TITLE
win7下 v20.3 service mode红色 选择激活和升级报错

### ISSUE THREAD

**Issue by stargazer974** [Fndroid/clash_for_windows_pkg#3461]
![QQ图片20220919120925](https://user-images.githubusercontent.com/63180810/190948588-776e080b-3e64-4111-bffd-b50df72f2e86.png)

**Comment by stargazer974** [comment]
![QQ图片20220919121100](https://user-images.githubusercontent.com/63180810/190948663-02f84dfe-9172-4b0b-b15f-fa0a8a4c2bfc.png)

**Comment by amir-valizadeh** [comment]
I have this issue on Linux too after  I access `sudo` permission, the app raises a permission error, if I know which packages need to activate service mode I can install it manually.

**Comment by Fndroid** [comment]
下个版本试下

**Comment by stargazer974** [comment]
> 下个版本试下

经过测试 20版本以下都正常 从20开始每个版本在windows7都出现此问题
但从20.3 似乎 service mode正常运行 只是图标是红色的    测试Lightweight Mode和TUN mode均正常启动  
点击install和update service mode 均出现此提示
![image](https://user-images.githubusercontent.com/63180810/191139445-e1e997ca-ab70-43a8-a801-47edc4fdffd2.png)

**Comment by lzfxxx** [comment]
macOS 12.5.1 也有类似的问题

<img width="886" alt="image" src="https://user-images.githubusercontent.com/12368329/191174249-8f15c9f2-3011-4fbd-aedc-36b84f0ccab6.png">

**Comment by stargazer974** [comment]
20.5已经修复

**Comment by yurenchen000** [comment]
> 20.5已经修复

seems this error back again on v0.20.15
