### ISSUE TITLE
[Bug]: TUN模式下：你的连接不是专用连接

### ISSUE THREAD

**Issue by Hinlavic** [Fndroid/clash_for_windows_pkg#3462]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.3

### 操作系统

Windows x64

### 系统版本

22000.978

### 问题描述

TUN模式下无法连接Google等，提示：你的连接不是专用连接；系统代理模式下可以正常连接。很久以前的问题了，似乎是从更新UI界面配置TUN设置参数的时候出现的，之后就没使用过TUN模式。
![image](https://user-images.githubusercontent.com/16399456/190951480-7474506c-792e-46cb-848b-cf13910abb6d.png)

### 复现步骤

1. 关闭TUN模式和服务模式，单独开启系统代理模式，打开Google，确认能正常连接。
2. 关闭系统代理模式，单独开启TUN模式和服务模式，打开Google，可以发现无法正常连接。不仅仅是Google，很多其他服务也无法正常工作。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
关闭浏览器安全dns

**Comment by sedasdas** [comment]
开启安全dns反而没问题，不开反而打不开，这是啥原因
