### ISSUE TITLE
[Feature Request]: 希望Parsers不改动代理节点配置格式的

### ISSUE THREAD

**Issue by redapple0204** [Fndroid/clash_for_windows_pkg#3463]
### 功能描述

本来的节点配置是一行行的，如下

>   - {name: xxx, server: xxxx, port: xxxxx, type: vmess, uuid: removed, alterId: 0, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /, headers: {Host: xxxx}}, udp: true}

一旦使用了parsers功能，例如预先向配置文件添加几个规则，节点配置就会变成这样

```
  - name: xxx
    server: xxx
    port: xxx
    type: trojan
    password: removed
    sni: xxxx
    skip-cert-verify: false
    udp: true
```

然而节点数一多这种形式的节点配置看的头晕眼花，因此希望Parsers功能不要修改原有的节点配置格式

**Comment by Fndroid** [comment]
无法实现
