### ISSUE TITLE
给 url-test 增加多个 URL 判断

### ISSUE THREAD

**Issue by laminux29** [Fndroid/clash_for_windows_pkg#3472]
Profilers -> 右边选中一个 -> Proxies -> 在 Proxy Groups 里选中一个 -> url-test，目前只能输入一个URL。

请问能否提供一个增加按钮，让用户可以添加无限个URL？

比如，用户添加了3个URL，那么只有当这3个URL都能被访问时，才继续保持该链路，否则就切换到别的链路上去。

**Comment by Fndroid** [comment]
clash core issue, refer: https://github.com/Dreamacro/clash/issues
