### ISSUE TITLE
[Bug]: failed to clash core，logs are not available

### ISSUE THREAD

**Issue by WoaW04** [Fndroid/clash_for_windows_pkg#3473]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.3

### 操作系统

Windows x64

### 系统版本

Windows 11 专业版 21H2

### 问题描述

重启系统第一次启动CFW一切正常，后面启动出现`failed to clash core, logs are not available`，且切换profile时提示`could not switch to this profile Error: Network Error`
尝试过手动启动`Clash for Windows\resources\static\files\win\x64`内的`clash-win64.exe`和`C:\Program Files\Clash for Windows\resources\static\files\win\x64\service`内的`clash-core-service.exe`，在手动启动后重启CFW能正常显示General页面，其他功能基本正常，但是无法启动代理（点击后无反应）
#2697 
此issue内方法全部试过，问题依旧
已重装过CFW，尝试过回退版本，问题依旧
已添加windows defender拦截白名单，问题依旧
已尝试删除.config内的clash文件夹，问题依旧
没有安装MacType
....

### 复现步骤

每次重启后第一次启动CFW正常，但后面关闭后再次打开都会出现此问题

### 日志文件

无log生成

### 其他补充

所有配置均为初始配置
出问题前第一次使用adb连接安卓模拟器(雷电)调试，但卸载模拟器后仍然存在此问题

**Comment by Allamss** [comment]
相同问题，似乎是升级22H2后导致，不过[WoaW04](https://github.com/WoaW04)是21H2，可能是连带的安全更新导致，如Microsoft Defender Antivirus
