### ISSUE TITLE
我自从更新了额Clash v0.8.6之后 我使用该程序会断线 然后要手动重连 请问是怎么个情况？

### ISSUE THREAD

**Issue by RevolutionR** [Fndroid/clash_for_windows_pkg#348]
我更新了应该是0.8.5之后吧 就发生这样的情况 每次都是翻墙浏览网页过10-20分钟 就断了 需要重新开关那个按钮 又能继续上网 我想问有人能告诉我怎么解决吗？

开了技术支持问了代理商 代理商说这个是软件问题 和代理没有任何关系 我现在有点犯愁 求大神教我一下是怎么会这样的 

我感觉我是自从让电信公司把我家的拨号上网改成动态上网之后 就这样了

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/312

**Comment by RevolutionR** [comment]
> #312

我用#312的程序查看了你说的注册表 发现搜狗输入法 有这个进程 我把它删了 现在还不知道会不会有问题
总之谢谢了~
我再测试一下看看

**Comment by Fndroid** [comment]
可以到我发的这个issue里评论上，说不定可以帮到后者，感谢

**Comment by RevolutionR** [comment]
我现在还是存在这样的问题。。。 我每次看一个youtube视频 看了10分钟就卡住了 加载不下去了  谷歌官网也打不开了 要重新开关按钮
刷新网页就又好了 反复如此真的很烦躁

Fndroid <notifications@github.com> 于2019年12月29日周日 下午1:06写道：

**Comment by Mr-Tsui** [comment]
你好，我也是经常断线，而且断了很难再连上，我用的事mac，请问怎么解决？

**Comment by GitHub-LYY** [comment]
也是经常掉线
