### ISSUE TITLE
[Bug]: Windows 11 22H2 更新后 再也无法开启 Service mode！

### ISSUE THREAD

**Issue by LiJT** [Fndroid/clash_for_windows_pkg#3480]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.3

### 操作系统

Windows x64

### 系统版本

Windows 11 22H2

### 问题描述

Service mode 现在在最新的win11版本中无法安装，安装后就弹出下图的错误

![1](https://user-images.githubusercontent.com/11270197/191651169-38a830d7-80fe-48ca-9969-054ad92217e2.png)

### 复现步骤

无论怎么重启还是重开软件该错误依然出现

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by LiJT** [comment]
我找到解决方法了

我的系统对BAT文件做出了修改，以前导致只能使用notepad++打开，
进入 注册表 
计算机\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.bat\
会发现里面有一个 OpenWithProgids 的文件夹，把这个删除了就可以了
![image](https://user-images.githubusercontent.com/11270197/191673048-13a83165-bca3-484b-8a76-5bdacfc9cf5e.png)

现在终于恢复了service mode！

**Comment by ruiwala** [comment]
解决了！666
