### ISSUE TITLE
[Bug]: 更新到最新版本后Service Mode失效

### ISSUE THREAD

**Issue by EL-File4138** [Fndroid/clash_for_windows_pkg#3482]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.3

### 操作系统

Linux

### 系统版本

Fedora release 36 (Thirty Six) x86_64 / 5.19.9-200.fc36.x86_64

### 问题描述

更新到最新版本后Service Mode失效
更新到最新版本后地球指示为红色，打开显示需要授予权限更新Service Mode，通过系统弹窗正确授予权限后提示安装失败，应用自动重启；
应用重启后再次安装更新提示消失但依然Inactive，再次尝试安装提示没有授予权限，重载应用后问题依然重复（没有授予权限）；

### 复现步骤

如上，其他修复尝试：
使用Wiki提供的 [手动安装](https://docs.cfw.lbyczf.com/contents/questions.html#service-mode-%E6%97%A0%E6%B3%95%E5%AE%89%E8%A3%85) 提示：
```
cp: 无法获取'/<cfw installation>/resources/static/files/linux/x64/service' 的文件状态(stat): 没有那个文件或目录
./cfw-tun.sh:行31: /<cfw installation>/resources/static/files/linux/common/service-installer/scripts/clash-core-service.service: 没有那个文件或目录
./cfw-tun.sh:行32: /<cfw installation>/resources/static/files/linux/common/service-installer/installer.sh: 没有那个文件或目录
```
检查发现文件确实不存在（手动安装脚本似乎与当前版本不符需要更新？）。
日志文件夹未发现相关日志。

### 日志文件

<details><summary>logs</summary><p>

```
0
```

</p></details>

**Comment by EL-File4138** [comment]
补充图片：

**Comment by EL-File4138** [comment]
补充图片：
![图片](https://user-images.githubusercontent.com/28867264/191734491-6a072ae9-9c24-4279-8a36-4510c362bd94.png)
![图片](https://user-images.githubusercontent.com/28867264/191734553-94af035a-2ba5-4bd9-824e-75997e9e85cc.png)

**Comment by Sh12uku** [comment]
手动运行了一下clash-core-service，发现cfw与服务进程通讯的时候返回了403，不知道是不是这个原因
系统：Manjaro-5.19.7-1 x86_64
![image](https://user-images.githubusercontent.com/73898758/191768009-1dbdb809-f02e-4413-b8fa-2bac774e5c6f.png)
下图是拿wireshark抓包结果
![image](https://user-images.githubusercontent.com/73898758/191769050-8ac3038d-1504-497c-a973-b9b7b3fbac93.png)

**Comment by Sh12uku** [comment]
> 你换了clash core？

都是在cfw里点了安装service mode以后生成的，没有做过改动

**Comment by EL-File4138** [comment]
> 你换了clash core？

我没有（
直接从Release页面下载后的原包解包的

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/3464

试试手动安装

**Comment by EL-File4138** [comment]
> #3464
> 
> 试试手动安装

已经确定问题了：
检查对应生成的service情况提示 `203/EXEC` 退出，是SELinux阻断了服务启动（服务Binary默认的fcontext为 `unconfined_u:object_r:config_home_t:s0` ），通过ausearch和audit2why手动生成策略包载入内核后成功启动，Service Mode显示Active。
希望下版本安装脚本中能添加一个SELinux策略包，或者将Binary放到一个正常fcontext能允许运行的地方。

**Comment by IT-Tagore** [comment]
> 

大佬能详细说说怎么解决更新clash后tun mode安装失败的方法吗

**Comment by EL-File4138** [comment]
> > 
> 
> 大佬能详细说说怎么解决更新clash后tun mode安装失败的方法吗

如上，首先建议清空一下 `/var/log/audit/audit.log`：
```bash
sudo truncate -s 0B /var/log/audit/audit.log
```
手动跑一遍安装流程，失败之后用audit2allow生成对应的SELinux内核模组：
```bash
sudo audit2why -M clash-service < /var/log/audit.audit.log
```
最后载入策略包
```bash
semodule -i clash-service.te
```

其他相关内容：[红帽对SELinux自定义模组的文档](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/using_selinux/writing-a-custom-selinux-policy_using-selinux)

**Comment by Porlockzzz** [comment]
> > > 
> > 
> > 
> > 大佬能详细说说怎么解决更新clash后tun mode安装失败的方法吗
> 
> 如上，首先建议清空一下 `/var/log/audit/audit.log`：
> 
> ```shell
> sudo truncate -s 0B /var/log/audit/audit.log
> ```
> 
> 手动跑一遍安装流程，失败之后用audit2allow生成对应的SELinux内核模组：
> 
> ```shell
> sudo audit2why -M clash-service < /var/log/audit.audit.log
> ```
> 
> 最后载入策略包
> 
> ```shell
> semodule -i clash-service.te
> ```
> 
> 其他相关内容：[红帽对SELinux自定义模组的文档](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/using_selinux/writing-a-custom-selinux-policy_using-selinux)


我这边也遇到了同样的203问题，但是似乎不是SELinux导致的，还有其他解决方案吗

**Comment by EL-File4138** [comment]
> > > > 
> > > 
> > > 
> > > 大佬能详细说说怎么解决更新clash后tun mode安装失败的方法吗
> > 
> > 
> > 如上，首先建议清空一下 `/var/log/audit/audit.log`：
> > ```shell
> > sudo truncate -s 0B /var/log/audit/audit.log
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 手动跑一遍安装流程，失败之后用audit2allow生成对应的SELinux内核模组：
> > ```shell
> > sudo audit2why -M clash-service < /var/log/audit.audit.log
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 最后载入策略包
> > ```shell
> > semodule -i clash-service.te
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 其他相关内容：[红帽对SELinux自定义模组的文档](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/using_selinux/writing-a-custom-selinux-policy_using-selinux)
> 
> 我这边也遇到了同样的203问题，但是似乎不是SELinux导致的，还有其他解决方案吗

因为我不确定你的系统具体情况所以不好排障。通常来说，203是因为可执行文件“无法执行”，如果SELinux没有阻止的话那么可以考虑检查下是否其他的权限有误，如有没有+x，权限和执行用户是否匹配，WorkingDirectory配置是否正确等等。
因为这个Service是CFW自动生成的，所以上述问题一般来说都不太可能出现，仅作为参考。

**Comment by Porlockzzz** [comment]
> 

感谢，已解决
原因是：clash-core-service.service中的执行路径未删除最后的右尖括号

**Comment by Hezupeng** [comment]
> 

到第二步找不到文件夹，怎么办

**Comment by Sh12uku** [comment]
Manjaro没有SELinux可以试试找到clash-core-service可执行文件，chmod手动加一个x权限，重启一下自己好了
系统：Manjaro-6.0.8-1 x86_64
