### ISSUE TITLE
自定义 选择代理的时候Could not switch to this profile!

### ISSUE THREAD

**Issue by remedy1111-git** [Fndroid/clash_for_windows_pkg#349]
![image](https://user-images.githubusercontent.com/58924487/71434727-b063f900-2720-11ea-9c9d-bad9d53d6145.png)
[Window Title]
Clash for Windows

Could not switch to this profile!

yaml: control characters are not allowed
用了三个多月了一直没有问题，今天突然就出现了，无论是在线输入订阅链接还是本地导入都是这样，请问大佬有没有解决办法呢？

**Comment by Fndroid** [comment]
yaml格式问题

**Comment by remedy1111-git** [comment]
> yaml格式问题

那就是机场的问题了是吗？

**Comment by Nonecrap** [comment]
同样的问题，我卸载了0.8.6，重装0.8.4就解决了

**Comment by YYZ-rose** [comment]
> 同样的问题，我卸载了0.8.6，重装0.8.4就解决了

0.8.4在哪装

**Comment by Nonecrap** [comment]
就在Code-release里面

**Comment by YYZ-rose** [comment]
> 就在Code-release里面

where 我咋没找到

**Comment by yiColddrink** [comment]
删除C:\Users\Administrator\.config\clash\Country.mmdb
重启软件解决

**Comment by agrichron** [comment]
找到Country.mmdb文件并删除，然后重启软件即可。

**Comment by skittles777** [comment]
> 删除C:\Users\Administrator.config\clash\Country.mmdb
> 重启软件解决

thanks

**Comment by Antairez** [comment]
为什么会有这个问题？yaml格式要如何修复？

**Comment by Fndroid** [comment]
yml格式错误请根据错误提示进行修改

**Comment by WSL33099** [comment]
> 删除C:\Users\Administrator.config\clash\Country.mmdb
为什么我的删除以后又自动生成呢

**Comment by WSL33099** [comment]
> > 删除C:\Users\Administrator.config\clash\Country.mmdb
> > 重启软件解决
> 
> thanks

为什么我的删除以后又自动生成怎么破
下载老版本也是一样

**Comment by Antairez** [comment]
> > > 删除C:\Users\Administrator.config\clash\Country.mmdb
> > > 重启软件解决
> > 
> > 
> > thanks
> 
> 为什么我的删除以后又自动生成怎么破
> 下载老版本也是一样

本来就该自动生成的，那是运行加载文件，不自动生成clash根本无法运作

**Comment by williamjaung** [comment]
> yaml格式问题

0.9.1版本同样出现这个问题。咋解决呢？

**Comment by xielu314** [comment]
> 删除C:\Users\Administrator.config\clash\Country.mmdb
> 重启软件解决

不行，没用。

**Comment by skywd** [comment]
> 删除C：\ Users \ Administrator.config \ clash \
> Country.mmdb重新启动软件解决方案

0.7.8也存在该问题，删除上述文件无法解决

**Comment by Fndroid** [comment]
@skywd 这是无法加载配置文件的弹框，配置文件有错，而且错误信息都不一样，不叫“存在该问题”

**Comment by yangqiang00** [comment]
我的也是这个问题， 删除也没有用，重新安装也么有用。  昨天还用的好好的。 怎么解 ？

**Comment by catboshi** [comment]
Clash 版本v0.10.3 选择代理出现Could not switch to this profile 
我的解决办法是先退出Clash，然后删除C:\Users\Administrator的.config文件，重启Clash，会自动重新生成.config，重新下载订阅后就可以了。

**Comment by Freya-EY** [comment]
同样could not switch to this profile, 但下方是invalid mode (不是上述显示的yaml: control...)，没有找到类似issue
试了删除.config，重启clash，重新下载订阅，update软件，都无法解决

**Comment by yi-Xu-0100** [comment]
@Freya-EY 给出错误截图

**Comment by Freya-EY** [comment]
> @Freya-EY 给出错误截图
![image](https://user-images.githubusercontent.com/79756959/109393728-6ac34180-795e-11eb-85a1-17b7e087b333.png)

**Comment by yi-Xu-0100** [comment]
@Freya-EY 你配置中 mode 的地方写的什么

**Comment by lzw1604748707** [comment]
> > @Freya-EY 给出错误截图
> > ![image](https://user-images.githubusercontent.com/79756959/109393728-6ac34180-795e-11eb-85a1-17b7e087b333.png)

兄弟你看一下 mode 里是不是把Rule 开头的r写成小写了。 应该是 Rule

**Comment by Hywfred** [comment]
这个问题是什么原因现在可以确定么，有没有解决方案？我下载最新版本0.16.1还是有这个错误。

**Comment by Freya-EY** [comment]
没有找到原因，最终解决方案是安装了14.7版本，问题消失

**Comment by Freya-EY** [comment]
> 同样could not switch to this profile, 但下方是invalid mode (不是上述显示的yaml: control...)，没有找到类似issue
> 试了删除.config，重启clash，重新下载订阅，update软件，都无法解决

没有找到原因，最终解决方案是安装了14.7版本，问题消失

**Comment by LcYusheng** [comment]
![image](https://user-images.githubusercontent.com/93134085/139855924-2676f48b-0287-492e-9b2b-d81c6d00da4a.png)
这个怎么解决啊

**Comment by raygift** [comment]
从yaml文件中找一些proxies 下的值替换掉花括号可以解决，不过有些替换过来会提示存在循环

**Comment by JoraNoe** [comment]
为什么我找不到这个 C：\ Users \ Administrator.config \ clash
Country.mmdb

**Comment by JoraNoe** [comment]
> 删除C:\Users\Administrator.config\clash\Country.mmdb 重启软件解决

不行啊 删除后 还是同样的问题啊

**Comment by JoraNoe** [comment]
1.关闭软件
2.进入：C:\Users\Administrator\.config
3.删除 clash 文件夹 （若提示此程序正在被占用-重启下电脑或者打开任务管理器找到clash-core...结束进程）
4.重新启动软件  进行下载Profiles

**Comment by Liitlewish** [comment]
![image](https://user-images.githubusercontent.com/80993472/148327334-72d69fc1-561e-4eaa-b53f-097d7c22e153.png)
这该怎么办

**Comment by JoraNoe** [comment]
> ![image](https://user-images.githubusercontent.com/80993472/148327334-72d69fc1-561e-4eaa-b53f-097d7c22e153.png) 这该怎么办

将Clash For Windows 配置文件全部删除干净（配置文件） 不是主文件 后重新启动Clash 

嫌麻烦可以下载此工具 Geek 卸载完 之后重新 安装即可

**Comment by litun5315** [comment]
> 找到Country.mmdb文件并删除，然后重启软件即可。

Thanks, really help me.

**Comment by BarryJame** [comment]
> ![image](https://user-images.githubusercontent.com/80993472/148327334-72d69fc1-561e-4eaa-b53f-097d7c22e153.png) 这该怎么办

很简单，官方下载yaml文件编辑文件，把里面所有头部的0.0.0.0的IP改成127.0.0.1保存之后即可完美使用，希望可以帮助你

**Comment by zhanghuanji** [comment]
![IMG_20220129_135801](https://user-images.githubusercontent.com/95843731/151664430-825adc58-e8aa-4671-b59b-5982d62e2b9b.jpg)
我的报错情况是这样的，谁来帮我看一下有什么问题吗？

**Comment by deng-dengdengdeng-deng** [comment]
![image](https://user-images.githubusercontent.com/65409577/153601179-b70970d2-2d6d-471f-a342-d63309325cb0.png)
我是这个问题，开了管理员模式就好了，但是开了管理员模式每次开机都会重新开一次系统代理，必须用火绒修复一下才能正常上网，很麻烦，不知道是什么问题导致的

**Comment by deng-dengdengdeng-deng** [comment]
> @Freya-EY 你配置中 mode 的地方写的什么

你好~麻烦看一哈我的问题~谢谢·~困扰一年了

**Comment by clear140** [comment]
> 对

**Comment by himawarl** [comment]
> ![image](https://user-images.githubusercontent.com/65409577/153601179-b70970d2-2d6d-471f-a342-d63309325cb0.png) 我是这个问题，开了管理员模式就好了，但是开了管理员模式每次开机都会重新开一次系统代理，必须用火绒修复一下才能正常上网，很麻烦，不知道是什么问题导致的

好用。兼容模式设置我也改成管理员运行

**Comment by JoraNoe** [comment]
> 
全局代理关闭     
就可以了，规则的代理就可以
DNS 设置成 自动获取

**Comment by hauite950** [comment]
![屏幕截图 2022-03-30 132722](https://user-images.githubusercontent.com/102648906/160765972-9f12496c-1800-4797-9a39-3e4a1b505d3a.jpg)
 这个怎么处理

**Comment by cxFUxiao** [comment]
> ![image](https://user-images.githubusercontent.com/80993472/148327334-72d69fc1-561e-4eaa-b53f-097d7c22e153.png) 这该怎么办

如果提示无法切换到此配置文件，错误：Command failed: route print 0.0.0.0 mask 0.0.0.0，需要打开系统的环境变量设置，在系统变量的Path中添加以下内容：%SystemRoot%\System32 from:https://www.dayuzy.com/archives/637

**Comment by jiangweihu** [comment]
![image](https://user-images.githubusercontent.com/71870389/170508124-83b1ed82-5e34-4ef4-bd23-61c8e16e8760.png)
请问这是什么问题 该怎么解决? 也是用着用着突然不能上网

**Comment by Fndroid** [comment]
@jiangweihu 你的配置文件被更新了格式不对吧

**Comment by jiangweihu** [comment]
> @jiangweihu 你的配置文件被更新了格式不对吧

额 我应该怎么修改解决呢

**Comment by 89silence** [comment]
![微信截图_20220610154250](https://user-images.githubusercontent.com/107288914/173168905-08ee4c10-b7b6-4885-9a76-51374d95ccc7.png)
我这个怎解决  删除Country.mmdb文件  不好用啊

**Comment by 89silence** [comment]
![微信截图_20220610154250](https://user-images.githubusercontent.com/107288914/173168970-d742af07-ecdb-4536-a8ad-81247bd045ba.png)
我这个怎解决 删除Country.mmdb文件 不好用啊

**Comment by xmayyy** [comment]
> ![微信截图_20220610154250](https://user-images.githubusercontent.com/107288914/173168970-d742af07-ecdb-4536-a8ad-81247bd045ba.png) 我这个怎解决 删除Country.mmdb文件 不好用啊

你解决了吗

**Comment by walle1911** [comment]
> > ![image](https://user-images.githubusercontent.com/80993472/148327334-72d69fc1-561e-4eaa-b53f-097d7c22e153.png) 这该怎么办
> 
> 很简单，官方下载yaml文件编辑文件，把里面所有头部的0.0.0.0的IP改成127.0.0.1保存之后即可完美使用，希望可以帮助你

非常有用，不用下载。点下面的edit，手动把0.0.0.0改成127.0.0.1就可以了。ctrl+f搜索出来就行了

**Comment by N1Lxl** [comment]
![image](https://user-images.githubusercontent.com/115674244/220973407-5d6b29d3-4491-4cd4-bb19-c4e61b03f85d.png)
我这个怎么办啊

**Comment by Ealsen** [comment]
> 找到Country.mmdb文件并删除，然后重启软件即可。

没有啊

**Comment by g3ntM28** [comment]
> ![微信截图_20220610154250](https://user-images.githubusercontent.com/107288914/173168970-d742af07-ecdb-4536-a8ad-81247bd045ba.png) 我这个怎解决 删除Country.mmdb文件 不好用啊
> 
> ![微信截图_20220610154250](https://user-images.githubusercontent.com/107288914/173168970-d742af07-ecdb-4536-a8ad-81247bd045ba.png) How can I delete the Country.mmdb file? It is not easy to use

老哥，请问你的解决了吗？我的也显示和你一样，只不过提示line 8

**Comment by g3ntM28** [comment]
<img width="638" alt="1677657544390" src="https://user-images.githubusercontent.com/113887158/222088657-ea6f8771-0529-4cca-808f-4b2c2c6441f5.png">
请问我这个怎么解决呢？

**Comment by Alicelovesun** [comment]
版本更新一下说不定能解决

**Comment by lishoulong** [comment]
> ![IMG_20220129_135801](https://user-images.githubusercontent.com/95843731/151664430-825adc58-e8aa-4671-b59b-5982d62e2b9b.jpg) 我的报错情况是这样的，谁来帮我看一下有什么问题吗？

一样的报错，轻轻解决了么？

**Comment by Anxonz** [comment]
在c盘user 搜索clash 把之前的配置文件都删除
windows下载exe安装版,当一个新软件安装即可解决问题

**Comment by Hatori-Kanon** [comment]
![image](https://user-images.githubusercontent.com/86350420/231677608-763a073c-e645-4916-928f-27ce238654df.png)
请问这是什么情况

**Comment by xsteafn** [comment]
大佬们能看看這是什么问题吗
![Snipaste_2023-04-20_12-54-59](https://user-images.githubusercontent.com/124412283/233262277-a5a401a0-b207-4477-bb0d-76fd02ed4e57.jpg)

**Comment by yi-Xu-0100** [comment]
@xsteafn 你这感觉配置文件有问题。

**Comment by BugMing01** [comment]
求问这个怎么解决
![屏幕截图 2023-06-20 195343](https://github.com/Fndroid/clash_for_windows_pkg/assets/135306967/66974c70-b336-4d8a-8c84-afee990217f9)

**Comment by ChongyouXu** [comment]
> 删除C:\Users\Administrator.config\clash\Country.mmdb 重启软件解决

直接把整个clash文件夹删掉后解决问题!

**Comment by RainLove1920** [comment]
我开了TUN Mode就能用了

**Comment by FlatMapIO** [comment]
今天也遇到这个问题了, 删除 Country.mmdb 能解决, 这个问题不应该被关闭.

**Comment by pitesssd** [comment]
![16888257762458893710217640147551](https://github.com/Fndroid/clash_for_windows_pkg/assets/138992168/d416ac26-3284-486c-a72c-4a4e13219f2c)
这个问题该怎么解决？

**Comment by zypy333** [comment]
我也遇到了，结果发现是机场会员过期了
