### ISSUE TITLE
[Bug]: failed with error:[Parser Error]f.filter is not a function

### ISSUE THREAD

**Issue by xiaoyv404** [Fndroid/clash_for_windows_pkg#3492]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.4

### 操作系统

Windows x64

### 系统版本

21H1

### 问题描述

下载配置文件时出现错误
![image](https://user-images.githubusercontent.com/63290381/192087828-9f147a45-8c42-41ce-84dd-832ba8f85cec.png)

### 复现步骤

N/A

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
检查或给出 parser 的脚本内容。

**Comment by xiaoyv404** [comment]
> parser

oh，我之前乱写然后打不开那个编辑界面了

**Comment by yi-Xu-0100** [comment]
@xiaoyv404 那要不备份后删除 home directory 重启试下

**Comment by xiaoyv404** [comment]
> @xiaoyv404 那要不备份后删除 home directory 重启试下

可以了w

**Comment by zhaxnb** [comment]
> @xiaoyv404 那要不备份后删除 home directory 重启试下

完美解决

**Comment by Michaelzhouisnotwhite** [comment]
> 检查或给出 parser 的脚本内容。

![image](https://user-images.githubusercontent.com/52443370/233913582-eaefcc98-917b-4c33-a29b-cdab1fd287b4.png)
请问我也遇到了这个问题，这里parser哪里写错了呢？我是按照<https://docs.cfw.lbyczf.com/contents/parser.html#commands-%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95-beta>操作的

**Comment by wonderhj** [comment]
> @xiaoyv404 那要不备份后删除 home directory 重启试下

我也出现这个问题了，起因是在配置文件里把香港的节点删了，然后就这样了。怎么解决啊。
备份后删除 home directory 重启试下 这个我看不懂，不知道怎么操作啊。

**Comment by Michaelzhouisnotwhite** [comment]
> > @xiaoyv404 那要不备份后删除 home directory 重启试下
> 
> 我也出现这个问题了，起因是在配置文件里把香港的节点删了，然后就这样了。怎么解决啊。 备份后删除 home directory 重启试下 这个我看不懂，不知道怎么操作啊。

![image](https://user-images.githubusercontent.com/52443370/234076448-2aa524e9-8488-44d4-a721-7d71c811d591.png)
点这个
![image](https://user-images.githubusercontent.com/52443370/234076525-eb834971-00c1-4ea8-8903-3ac45a4135cf.png)
把所有的都删除只留下这一行

**Comment by shangminghao** [comment]
我把那个节点界面删除了还怎么打开啊，直接找不到了
![2023-04-25](https://user-images.githubusercontent.com/45502500/234232456-ff55a23d-e183-47a3-b1eb-44bb8324b1c3.png)

**Comment by underdestiny** [comment]
> 
你这暴露了你的订阅链接呀，赶紧删了不然等下流量一下就被用光了
