### ISSUE TITLE
[Bug]: 此应用无法在你的电脑上运行

### ISSUE THREAD

**Issue by Daniel-sweet-Q** [Fndroid/clash_for_windows_pkg#3493]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.4

### 操作系统

Windows x64

### 系统版本

Windows 10 家庭中文版

### 问题描述

能安装，但是双击打开的时候提示 此应用无法在你的电脑上运行

### 复现步骤

点击打开 就会提示

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
安装版本是哪一个？

**Comment by Lemmingh** [comment]
请用 x86-64 版本，排除一下 WoW64 的问题。

`Clash.for.Windows-0.20.4-win.7z`

`Clash.for.Windows.Setup.0.20.4.exe`

**Comment by Hxhxhxhxhx001** [comment]
我的也是 下载的这个版本Clash.for.Windows-0.20.5-arm64-win.7z   w10 64位的系统 无解啊

**Comment by Lemmingh** [comment]
> `arm64-win.7z`
>
> 64 位的系统

你的系统究竟是 x86-64 还是 ARM64 架构？

我猜你没有 ARM 设备，那么，你所谓的“64 位”就是 x86-64。

**x86-64 的安装包没有架构标记字段**，请看上面的例子。而其他架构的有标记。

**Comment by 404notfoundational** [comment]
> 我的也是 下载的这个版本Clash.for.Windows-0.20.5-arm64-win.7z w10 64位的系统 无解啊

这个是免安装版，下载没有后缀名的那个setup.0.20.5.exe,那个是安装版
