### ISSUE TITLE
[Bug]: clash windows配置好了，不能上谷歌。

### ISSUE THREAD

**Issue by fszgsmt123** [Fndroid/clash_for_windows_pkg#3496]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.4

### 操作系统

Windows x64

### 系统版本

WIN10

### 问题描述

没有网速，也重新下载过，网络里的代理 也没打开，局域网不用，是用网线直连的，但手机WIFI连上用手机CALSH可以上。以前用过低版本的CLASH可以上的，现在过了几个月在用连不上了

### 复现步骤

我也不知道怎么出现这个问题的 

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

其它都 没动过

**Comment by yi-Xu-0100** [comment]
给下日志。

你是说你配置了系统代理，没开 tun 或者 mixin 用的 rule 模式，但是浏览器访问时不行？检查下 connection 或者 logs 里看看匹配的什么规则，有什么报错没

**Comment by fszgsmt123** [comment]
![image](https://user-images.githubusercontent.com/114336270/192150966-44e6be06-3ca7-4523-a777-96c08792b62b.png)

是这个吗？

**Comment by fszgsmt123** [comment]
![image](https://user-images.githubusercontent.com/114336270/192151007-1f8d55af-8dca-418e-b0c2-beda69ad6a4f.png)

**Comment by fszgsmt123** [comment]
![image](https://user-images.githubusercontent.com/114336270/192151032-470ff3b7-0102-48e4-87a9-3c39b8ecf811.png)

**Comment by fszgsmt123** [comment]
![image](https://user-images.githubusercontent.com/114336270/192151117-4f1025cf-41bf-4246-a7cb-8ca812a3f488.png)

**Comment by fszgsmt123** [comment]
帮忙看看是哪出了问题？

**Comment by fszgsmt123** [comment]
关闭是什么意思

**Comment by yi-Xu-0100** [comment]
请注意：使用的是官方版本（未替换及修改过安装目录程序文件）

**Comment by fszgsmt123** [comment]
我用了汉化，安装在了D盘，请问是跟这个有关系吗？

**Comment by fszgsmt123** [comment]
然后我重新安装没用汉化，出现了这个红色的，是说DNS有问题，还是IP有问题
![image](https://user-images.githubusercontent.com/114336270/192259047-b7ae6f19-792c-4b78-ac1f-41581c5821d4.png)

**Comment by fszgsmt123** [comment]
dns redir-host is deprecated, please use fake-ip instead

**Comment by fszgsmt123** [comment]
解决了，问题是，我用了站内下的汉化的app.asar，然后系统代理不行，用的TUN模式，就可以上谷歌了，但还是谢谢朋友们的帮忙

**Comment by SilenceXK** [comment]
o，所以是不能用汉化后的嘛？我是在网上找的汉化补丁现在重新装试试（之前调试自动删了文件）
