### ISSUE TITLE
[Feature Request]: clash-win64.exe.sign的签名规则是怎么样的？

### ISSUE THREAD

**Issue by htfcuddles** [Fndroid/clash_for_windows_pkg#3498]
### 功能描述

尝试替换clash-win64.exe为[Meta Core](https://github.com/MetaCubeX/Clash.Meta),大部分功能正常，但无法开启TUN。
发现在Service mode（启用TUN)下会对clash-win64.exe检查签名，签名文件猜测为clash-win64.exe.sign（证据为删除该文件后原版也无法启动，报错信息一致）。请问改文件是如何生成的？

**Comment by yi-Xu-0100** [comment]
@htfcuddles 为了 service 安全后，对 core 进行了自签名，所以不再支持换核后使用 service mode。 可以尝试管理员模式或者 uac 白名单模式提供 tun 的支持。

**Comment by htfcuddles** [comment]
@yi-Xu-0100 了解了，谢谢
