### ISSUE TITLE
[Bug]: 【已解决】TUN模式无法打开GitHub

### ISSUE THREAD

**Issue by xCANVAS** [Fndroid/clash_for_windows_pkg#3499]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

v 0.20.4

### 操作系统

Windows x64

### 系统版本

Windows 11 21H1

### 问题描述

TUN模式无法打开GitHub,其他模式可以打开（system proxy、TAP Device）
![image](https://user-images.githubusercontent.com/76691501/192317701-c8d40b53-2cc3-495c-ac3e-4368432c9473.png)

![image](https://user-images.githubusercontent.com/76691501/192318012-9509eb4f-0f18-4a9c-92bb-6c8e8f97af0e.png)

### 复现步骤

更新完最新版本之后就出现了这个问题。好几天用system proxy了。有大佬知道这个嘛。TUN Mode Setting是默认的。

![image](https://user-images.githubusercontent.com/76691501/192318676-d2bcc10c-6429-4d66-a640-0cfe66ebe0c6.png)

**Comment by Fndroid** [comment]
关闭浏览器安全dns

**Comment by xCANVAS** [comment]
> 关闭浏览器安全dns

所以为什么以前不需要啊（。？
