### ISSUE TITLE
从6.0升到8.6版本，开启system proxy之后，大部分UWP程序以及系统搜索框无法联网，关掉恢复正常

### ISSUE THREAD

**Issue by yusnake** [Fndroid/clash_for_windows_pkg#350]
不知道，是不是哪里需要设置？

**Comment by Comah** [comment]
是的 和我的一样 微软商店 天气等uwp应用全打不开 用全局就能走代理流量打开

**Comment by yusnake** [comment]
不知道是不是win10  1909 的锅，老电脑1809是可以的

**Comment by Fndroid** [comment]
开启system proxy之后uwp必须要解除loopback限制才能联网，General中已经提供了工具
