### ISSUE TITLE
[Bug]: 求大佬适配，windows11 22h2安装不了

### ISSUE THREAD

**Issue by HotCoffeeCup** [Fndroid/clash_for_windows_pkg#3504]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.4

### 操作系统

Windows11 x64

### 系统版本

22H2   22000.1042

### 问题描述

安装包和jar包的运行程序都无法运行该软件。

### 复现步骤

exe安装和zip解压运行，都不可以。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Wrandz** [comment]
我之前也是不知道，以为现在怎么不提供Win64的安装包了，后来才知道下载页面太长了需要展开

**Comment by HotCoffeeCup** [comment]
> 说明下载错了安装包，不要下arm64的，然后GitHub改版了下载页面需要展开

感谢大佬指导

**Comment by mingouuu** [comment]
> 说明下载错了安装包，不要下arm64的，然后GitHub改版了下载页面需要展开
哈哈哈，我也一样，习惯性的以为是win11适配性的问题。谢谢大佬提醒

**Comment by mingouuu** [comment]
> 说明下载错了安装包，不要下arm64的，然后GitHub改版了下载页面需要展开

哈哈哈，我也一样，习惯性的以为是win11适配性的问题。谢谢大佬提醒
