### ISSUE TITLE
[Bug]: 无法显示部分配置文件的流量信息

### ISSUE THREAD

**Issue by Marukon** [Fndroid/clash_for_windows_pkg#3508]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.4

### 操作系统

Windows x64

### 系统版本

Windows 11

### 问题描述

无法显示配置文件剩余流量信息
配置文件的header信息：
{"upload":"-5562957265B","download":"32.03GB","total":"500GB","expire":"不限时"}}
建议兼容负数的流量。

### 复现步骤

如上

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
去让机场适配，或者自己写 parser

**Comment by pacmanzou** [comment]
> 解决了没，兄弟
