### ISSUE TITLE
v0.8.7 bugs

### ISSUE THREAD

**Issue by iam3ddy** [Fndroid/clash_for_windows_pkg#351]
did a uninstall using revo uninstaller. deleted /.config folder
then install v0.8.7 again.
launch app. here's the issues
1. unable to load core. click repair core fails
2. unable to select the downloaded profile. prompted edited in text mode error

**Comment by iam3ddy** [comment]
installing back to v0.8.6 still can't solve this error. 
help pls

![Untitled](https://user-images.githubusercontent.com/21017389/71506432-dd98de80-28bb-11ea-9c10-f235c93fb583.jpg)

**Comment by Fndroid** [comment]
"Open logs folder" then common the content in the latest **.log** file

**Comment by iam3ddy** [comment]
install v0.8.7 overwrite current v0.8.6 solved Core issue
