### ISSUE TITLE
[Bug]: NetworkError on self signed Certificate

### ISSUE THREAD

**Issue by hiddify** [Fndroid/clash_for_windows_pkg#3515]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.4

### 操作系统

Windows x64

### 系统版本

11

### 问题描述

In the url section in profiles when we enter a url with self signed certificate it will show network error but it should show an error to save the certificate.
![image](https://user-images.githubusercontent.com/114227601/193157630-226fc43f-69e8-4957-8206-bc33dded3a60.png)

### 复现步骤

use `https://self-signed.badssl.com/` as the url in `Download from URL` section to see the error

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
0.20.5 allow to skip certificate validation by adding url in Settings-Allow unsafe URLs

**Comment by hiddify** [comment]
@Fndroid Great thanks
However, skip certificate validation in urls create a security hole but if there is an option to add the certificate it would be safer.

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
