### ISSUE TITLE
0.8.7 2个小问题

### ISSUE THREAD

**Issue by leosam1024** [Fndroid/clash_for_windows_pkg#352]
profile界面
1. 0.8.6 可以拖拽配置文件进行排序，新版不行
2. url 下载的时候，如果配置文件内容过大，下载时间过长，下载到一半就报ERROR。可以适当延长一下timeout时间。

另外开启系统代理后，图标变成黄色后，看一下系统代理还是关闭的，应该是被啥软件给关了。每次都得重新打开一下。可以加一个延迟检测的功能

**Comment by Fndroid** [comment]
1. 是个bug
2. 目前timeout已经有10s了
3. 系统代理被其他软件关闭请从其他软件方面入手

**Comment by iam3ddy** [comment]
found 1 more bug.

1. unable to drag servers to proxy group

**Comment by Fndroid** [comment]
是的，修复其中一个bug的时候导致的新bug

iam3ddy <notifications@github.com>于2019年12月27日 周五15:28写道：

**Comment by leosam1995** [comment]
有些提供订阅转换的机器，都是1m小水管。
下载链接，合并，转换订阅，然后下下来速度又慢，很多都会超时。
15秒或者30秒合适。因为很多不是链接超时，是10秒下载不完超时的，
另外，如果点击更新，超时了的话，是不会提示错误，什么也不会提示，可以加上超时提醒

**Comment by iam3ddy** [comment]
log level for debug mode not working

under General, still shows as "info"

**Comment by Fndroid** [comment]
1. 已在0.8.8中修复
2. 经检查，代码中超时其实一直是20s
