### ISSUE TITLE
[Bug]: 链接里面的暂停没有效果

### ISSUE THREAD

**Issue by zzcabc** [Fndroid/clash_for_windows_pkg#3520]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.5

### 操作系统

Windows x64

### 系统版本

Windows10 21H2

### 问题描述

在Connections里面点击Pause依旧在持续变化，没有像之前版本停止

### 复现步骤

在Connections里面点击Pause

### 日志文件

无日志

**Comment by LightAPIs** [comment]
试了试，我这的 Pause 是有效果。

**Comment by zzcabc** [comment]
> 试了试，我这的 Pause 是有效果。

删除旧的文件，然后解压就可以了

**Comment by tanpengsccd** [comment]
我是有时候失效
