### ISSUE TITLE
[Feature Request]: 建议推出DHCP Server功能（同MacOS上Clash的DHCP Server功能）

### ISSUE THREAD

**Issue by KyleCyaN** [Fndroid/clash_for_windows_pkg#3525]
### 功能描述

希望在Windows上同样可以启动与MacOS上Clash的DHCP功能，方便对局域网内其他设备进行地址及网关分配，比如Xbox Series系列，因系统代理功能被阉割，用不了传统的局域网代理

**Comment by Fndroid** [comment]
windows做不了网关，要dhcp有什么用呢

**Comment by KyleCyaN** [comment]
所以Xbox Series主机只能通过路由器翻墙的方式去加速吗
