### ISSUE TITLE
[Bug]: Ubuntu18.04使用后，无法连接外网，显示dns错误

### ISSUE THREAD

**Issue by qycqycqyc** [Fndroid/clash_for_windows_pkg#3528]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

20.5

### 操作系统

Linux

### 系统版本

ubuntu 18.04

### 问题描述

![2022-10-02 15-57-14屏幕截图](https://user-images.githubusercontent.com/48520573/193444269-8633f048-53da-47b6-82c6-d6e5586b4cdf.png)
![2022-10-02 15-57-03屏幕截图](https://user-images.githubusercontent.com/48520573/193444270-c592e14c-7b6e-4671-9105-6a8719a8a710.png)
![2022-10-02 15-56-46屏幕截图](https://user-images.githubusercontent.com/48520573/193444272-448c0ef0-7eba-45bd-976a-08963c86b082.png)
![2022-10-02 15-56-13屏幕截图](https://user-images.githubusercontent.com/48520573/193444275-7c7ddda6-1112-411d-910b-a083d7e323b2.png)

### 复现步骤

拜托了 一整天没解决 Windows和安卓都没问题，就Ubuntu有问题

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
你设置系统代理了吗？linux系统需要自行去系统设置里设置。

**Comment by qycqycqyc** [comment]
@yi-Xu-0100 是指的手动设置网络 127.0.0.1 7890吗？

**Comment by qycqycqyc** [comment]
![2022-10-02 16-17-44屏幕截图](https://user-images.githubusercontent.com/48520573/193444918-b4fed05e-4e90-43bf-96ee-d074b8ac7da5.png)

**Comment by yi-Xu-0100** [comment]
@qycqycqyc 去你的配置里面把 dns 的 enable 字段改成 false ，再试试

**Comment by qycqycqyc** [comment]
![2022-10-02 16-32-20屏幕截图](https://user-images.githubusercontent.com/48520573/193445381-47fa8e92-ea8c-40d2-b75c-ebe8732bda42.png)
@yi-Xu-0100 改了之后 还是不行  首先改了就不能更新，一更新就变成true了，然后我保存重启clash还是不行，谷歌 youtub都打不开

**Comment by qycqycqyc** [comment]
![2022-10-02 16-36-33屏幕截图](https://user-images.githubusercontent.com/48520573/193445500-fff5948f-299e-47a9-b1f1-c041fe9f011e.png)
这里就两个连接

**Comment by yi-Xu-0100** [comment]
@qycqycqyc 重新检查下你的 port 是否变更了，感觉完全没有代理上，看看你浏览器的代理设置。

如果想要更新订阅不变更，看看 parser 或者 diff, 或者 mixin。

https://docs.cfw.lbyczf.com/contents/parser.html
https://docs.cfw.lbyczf.com/contents/diff.html
https://docs.cfw.lbyczf.com/contents/mixin.html

**Comment by qycqycqyc** [comment]
> @qycqycqyc 重新检查下你的 port 是否变更了，感觉完全没有代理上，看看你浏览器的代理设置。
> 
> 如果想要更新订阅不变更，看看 parser 或者 diff, 或者 mixin。
> 
> https://docs.cfw.lbyczf.com/contents/parser.html https://docs.cfw.lbyczf.com/contents/diff.html https://docs.cfw.lbyczf.com/contents/mixin.html

这个port怎么检查啊？网络代理那里确实改成了手动7890，然后我在终端ping google.com,也ping不通

**Comment by qycqycqyc** [comment]
这个问题接下来怎么排查呢，这对我真的很重要，因为工作需要，可以有偿。 @yi-Xu-0100

**Comment by yi-Xu-0100** [comment]
general 界面截图看下，可能开了 random port 可能 port 就重启变化了

**Comment by Lemmingh** [comment]
```shell
sudo ss --listening --processes
```

**Comment by qycqycqyc** [comment]
![2022-10-02 22-54-22屏幕截图](https://user-images.githubusercontent.com/48520573/193460604-d62cb8d4-9ca0-4337-ae24-3ba809dced36.png)
@yi-Xu-0100 @Lemmingh

**Comment by Lemmingh** [comment]
Socket 看着没问题。

不过，排版咋这么乱呢？正常打印应该都是单行的：

```
Netid    State     Recv-Q    Send-Q    Local Address:Port    Peer Address:Port    Process
tcp      LISTEN    0         4096          127.0.0.1:7890         0.0.0.0:*       users:(("clash-linux",pid=2658,fd=19))
```

---

你用的应用程序有什么表现？

Linux 中的系统代理 (system proxy) 本质上是环境变量 (environment variables)。有些程序，如 Chrome，利用桌面系统的 API，可以即时更新。而有些程序需要重开才获取新 env。

**Comment by qycqycqyc** [comment]
@Lemmingh  可是我只是在终端中ping google.com都ping不通，更别说浏览器打开网页了

**Comment by qycqycqyc** [comment]
@Lemmingh 可以通过todesk帮我看看吗

**Comment by Lemmingh** [comment]
> 我在终端 `ping google.com`

Ping (ICMP Echo) 是没有意义的。

浏览器检测是最可靠的方法。HTTP-Ping (HTTP HEAD) 也行。

---

> 浏览器打开网页

浏览器说啥？打开 DevTools，切到 Network，刷新网页。

---

> 可以通过 ToDesk 帮我看看吗

<https://www.todesk.com/>

Emmm... 抱歉，看不太懂怎么用。

---

> <https://github.com/Fndroid/clash_for_windows_pkg/issues/3528#issuecomment-1264585337>

这 2 个连接是谁发起的？我猜是 CFW。

如果猜想正确，那么 system proxy 应该也已经正确配置。因为 CFW 基于 Electron 基于 Chromium，于是能从 GNOME API 更新设置。

所以，最后大概还是具体应用的配置问题。

**Comment by Lemmingh** [comment]
如果类似这几种情况，检查浏览器的网络设置。

Chrome

```
ERR_CONNECTION_CLOSED
ERR_CONNECTION_RESET
```

Firefox

```
PR_CONNECT_ABORTED_ERROR
PR_CONNECT_RESET_ERROR
PR_END_OF_FILE_ERROR
```

**Comment by qycqycqyc** [comment]
居然是浏览器的问题！！！！卧槽！！我把浏览器的设置为使用系统代理设置就好用了！谢谢各位大佬 @Lemmingh @yi-Xu-0100 谢谢谢谢

**Comment by Yojay97** [comment]
> ![2022-10-02 16-17-44屏幕截图](https://user-images.githubusercontent.com/48520573/193444918-b4fed05e-4e90-43bf-96ee-d074b8ac7da5.png)

通过这一步解决了问题，谢谢啦
