### ISSUE TITLE
TUN模式下非正常关闭电脑，开机后无法连接网络。

### ISSUE THREAD

**Issue by mohalikeyou** [Fndroid/clash_for_windows_pkg#3530]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.5

### 操作系统

Windows x64

### 系统版本

21H2

### 问题描述

# 问题
clash在后台运行，然后直接关闭电脑，再开机，会导致网络无法连接。
# 自己的办法
每次开机都得手动关闭TUN，并重新打开TUN，这样才能恢复正常。
# 希望的解决办法
希望clash无感运行，每次不需要每次都得手动重复开关动作，希望大佬能够解决一下这个问题，感谢！

### 复现步骤

1. 正常打开TUN模式。
2. 未手动关闭clash的前提下，直接重启电脑
3. 重启后再次打开clash，会出现网络异常。

### 日志文件

<details><summary>logs</summary><p>

```
无
```

</p></details>

### 其他补充

![image](https://user-images.githubusercontent.com/77050354/193563500-56799ca5-5c63-4e9b-995c-0bc560bc7d83.png)

**Comment by mohalikeyou** [comment]
> 这个问题不知道是因为windows 11 更新了22H2还是Clash更新了0.20.X

我的是window10，一直不太方便。
![image](https://user-images.githubusercontent.com/77050354/193586768-cb468f7d-4d1e-4599-8833-1543a2b7f284.png)

**Comment by uoox** [comment]
刚刚莫名其妙连上了，我做了这些操作，你试试看行不行。

首先先把你的订阅链接保存下。

打开Home Directory，在面板点Open Folder就是了，把这个文件夹里面的文件都删除了。
然后卸载Clash重装，重新配置好订阅并安装网卡开启TUN模式。就好了

猜测是某个版本做了一些配置，然后这些配置会导致网卡无法连接网络。

**Comment by mohalikeyou** [comment]
今天又试了一下。
开机后，国内网站是可以访问的，但是不能科学上网，虽然clash打开了TUN，所以还是得手动开关一次，才恢复正常
