### ISSUE TITLE
[Feature Request]: 请问能自定义css样式嘛？

### ISSUE THREAD

**Issue by rangluwme** [Fndroid/clash_for_windows_pkg#3532]
### 功能描述

如题，就是自定义某些样式之类的，如果能的话，路径应该是哪里呢？
![image](https://user-images.githubusercontent.com/63960943/193812451-bfccdaee-8bc5-4b20-807d-46c22e31ae70.png)

**Comment by Lemmingh** [comment]
全都是 Vue 生成的，编译一次变个样子，没法从外界搞它。

**Comment by rangluwme** [comment]
哦哦，感谢！
