### ISSUE TITLE
[Feature Request]: 增加DNS解析记录

### ISSUE THREAD

**Issue by rangluwme** [Fndroid/clash_for_windows_pkg#3537]
### 功能描述

请问能不能在log或者connections中，增加查看dns解析记录的功能，也方便查看具体是哪个dns解析的这个流量信息。
现在只能看到DNS-Mode
![image](https://user-images.githubusercontent.com/63960943/194104151-bfe8ab3f-de33-4200-b1a9-f73aea5dca06.png)

**Comment by yi-Xu-0100** [comment]
感觉是 core issue: <https://github.com/Dreamacro/clash/issues>

log 级别是 debug 的话， log 里应该能看到。

**Comment by rangluwme** [comment]
对，能看到！ 感谢！！！iQDNS 确实比阿里云快
