### ISSUE TITLE
👀见图👀这是什么情况？左下角绿色是不是已经运行成功了

### ISSUE THREAD

**Issue by uknowy** [Fndroid/clash_for_windows_pkg#354]
Could Not switch to this profile
![Could Not switch to this profile](https://user-images.githubusercontent.com/18025776/71521274-fd032c00-28fa-11ea-99b4-fe6da537c905.png)

**Comment by Fndroid** [comment]
运行成功不代表什么配置都能用，请使用clash格式的配置文件
