### ISSUE TITLE
[Feature Request]: 希望支持external-ui这个选项

### ISSUE THREAD

**Issue by HITers2018** [Fndroid/clash_for_windows_pkg#3541]
### 功能描述

目前默认情况是打开在线的web界面，希望支持external-ui选项，方便调用本地资源，比如调用更好看的yacd样式。

**Comment by HITers2018** [comment]
发现原来支持external-ui选项，能指定一个文件夹存放本地资源，只是需要手动访问（例如默认是127.0.0.1:9090/ui），希望clash客户端那个点击内核版本号时，如果检测到用户定义了external-ui，就自动跳转本地的，而不是官方提供的在线dashboard。

**Comment by HITers2018** [comment]
不需要了，可以通过浏览器直接作为网页应用安装，更优雅。

**Comment by yi-Xu-0100** [comment]
yacd 的版本可以作为网页应用安装吗？还是说你安装的什么？

**Comment by HITers2018** [comment]
> yacd 的版本可以作为网页应用安装吗？还是说你安装的什么？

clash 本身支持从本地部署dashboard，把yacd相关文件放文件夹，通过external-ui指向就可以了，clash就允许你手动访问（例如默认是127.0.0.1:9090/ui），然后用浏览器将网页作为pwa应用使用
![image](https://user-images.githubusercontent.com/45704621/201070636-a49244f0-0ac8-4cb2-81ea-c0a77adbd055.png)
等于生成了一个快捷方式，比如固定在任务栏或者创建快捷方式到桌面，直接点就可以了。
![image](https://user-images.githubusercontent.com/45704621/201071035-5fad1d2c-ee1f-4634-8011-4a5b7008754e.png)
这个适用于所有系统。

**Comment by yi-Xu-0100** [comment]
奇怪，我的edge没识别出来他是web应用可安装🤔

**Comment by Buliet** [comment]
<img width="366" alt="image" src="https://user-images.githubusercontent.com/32899664/205437701-8f2036a8-aee3-4ff5-9161-68508d97ede3.png">

Mac 这样配置后无法访问 http://127.0.0.1:9090/dash 显示

<img width="570" alt="image" src="https://user-images.githubusercontent.com/32899664/205437779-f6575c9b-0c2b-4cde-a3a3-2ded95026d8a.png">

静态资源文件夹 dash 已放在 ~/.config/clash

命令行 lsof -i:9090 发现端口没被使用
所以 clash_for_windows 是不支持吗
@yi-Xu-0100 @HITers2018 楼上两位大佬给瞅瞅

**Comment by yi-Xu-0100** [comment]
@Buliet 这个端口去 general 界面看 clash core 版本号后面的

**Comment by Buliet** [comment]
用 clash core 端口访问 显示 {"message":"Unauthorized"} 
@yi-Xu-0100 你那可以么

**Comment by yi-Xu-0100** [comment]
@Buliet 你可能没填密码，去 home directory 的 config.yml 看看密码

**Comment by Buliet** [comment]
谢谢 @yi-Xu-0100 
最初是想着用 web端 通过脚本自动点击来更新节点信息，发现也没这个选项
然后 发现：右键节点配置文件可以设置自动更新。。。0.0

**Comment by HITers2018** [comment]
> <img alt="image" width="366" src="https://user-images.githubusercontent.com/32899664/205437701-8f2036a8-aee3-4ff5-9161-68508d97ede3.png">
> 
> Mac 这样配置后无法访问 http://127.0.0.1:9090/dash 显示
> 
> <img alt="image" width="570" src="https://user-images.githubusercontent.com/32899664/205437779-f6575c9b-0c2b-4cde-a3a3-2ded95026d8a.png">
> 
> 静态资源文件夹 dash 已放在 ~/.config/clash
> 
> 命令行 lsof -i:9090 发现端口没被使用 所以 clash_for_windows 是不支持吗 @yi-Xu-0100 @HITers2018 楼上两位大佬给瞅瞅

你访问的方式不对，应该访问127.0.0.1:9090/ui，前面IP和端口号是看配置的，后面那个ui是固定的。

**Comment by HITers2018** [comment]
> 奇怪，我的edge没识别出来他是web应用可安装🤔

是手动安装的，不是它自己提示的。展开Edge的菜单，里面有一项是将当前站点安装为应用，点击安装就好了，不仅仅是yacd支持，原版dashboard也可以。

**Comment by Buliet** [comment]
谢谢两位大佬 @yi-Xu-0100 @HITers2018 
虽然还是没能通过 external-ui 实现 web 端展示
不过最初的目的已经达到了 也不纠结了
