### ISSUE TITLE
[Bug]: 在debug模式下，点击地址，无法复制该地址和端口

### ISSUE THREAD

**Issue by rangluwme** [Fndroid/clash_for_windows_pkg#3543]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

v.0.20.5

### 操作系统

Windows x64

### 系统版本

Windows

### 问题描述

在debug模式下，点击地址，无法复制该地址和端口
![image](https://user-images.githubusercontent.com/63960943/194552972-14ff0fce-183e-4a71-b0e6-71f9f52905a0.png)

### 复现步骤

打开debug日志格式

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by AkariiinMKII** [comment]
这条log里面没有可复制的内容
