### ISSUE TITLE
[Bug]: Mixin 增加 rules 规则，clash 原有规则全部失效。youtube，netflix 不上上。关闭Mixin 就好了

### ISSUE THREAD

**Issue by viplq** [Fndroid/clash_for_windows_pkg#3546]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.5

### 操作系统

Windows x64

### 系统版本

windown11

### 问题描述

Mixin 增加 rules 规则，clash 原有规则全部失效。youtube，netflix 不上上。关闭Mixin 就好了

mixin: # object
&nbsp; &nbsp; rules:
&nbsp; &nbsp; &nbsp; &nbsp; - "DOMAIN-SUFFIX,***.com,DIRECT"

### 复现步骤

mixin: # object
&nbsp; &nbsp; rules:
&nbsp; &nbsp; &nbsp; &nbsp; - "DOMAIN-SUFFIX,***.com,DIRECT"

**Comment by yi-Xu-0100** [comment]
mixin 是替换全部，用 diff 或者 parser 修改内容。

https://docs.cfw.lbyczf.com/contents/diff.html
https://docs.cfw.lbyczf.com/contents/parser.html

**Comment by viplq** [comment]
使用parser也不管用
parsers: # array
&nbsp;&nbsp;&nbsp;&nbsp;- reg: ^.*$ # 正则匹配域名
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;yaml:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; prepend-rules:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- DOMAIN-SUFFIX,xjjrj.com,DIRECT

**Comment by wheat0r** [comment]
> mixin 是替换全部，用 diff 或者 parser 修改内容。
> 
> https://docs.cfw.lbyczf.com/contents/diff.html https://docs.cfw.lbyczf.com/contents/parser.html

似乎不完全是，yaml方式会影响全部规则，js方式却可以只是添加规则
