### ISSUE TITLE
关于archlinux及其衍生版 Service Mode（服务模式)无法安装错误的解决办法

### ISSUE THREAD

**Issue by luochen570** [Fndroid/clash_for_windows_pkg#3555]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.5

### 操作系统

Linux

### 系统版本

archlinux

### 问题描述

很多archlinxu&衍生版用户遇到关于 Service Mode（服务模式)无法安装的问题的解决办法
aur的 “clash-for-windows-bin”  ”clash-for-windows-chinese“少数错误通常表现为
Service Mode（服务模式)无法安装
例如： https://github.com/Fndroid/clash_for_windows_pkg/issues/3432

解决办法：删除clash配置文件，更换相关文件为Releases里的文件

`rm -rf  ~/.config/clash & rm -rf  ~/.config/clash_win`

从Releases下载的文件解压覆盖下列对应目录的文件（直接解压打开cfw也可以用）
```
/opt/clash-for-windows-bin/

/opt/clash-for-windows-chinese/
```

重新打开后应该就可以正常使用cfw cfwc了

感谢https://github.com/Fndroid/clash_for_windows_pkg/issues/3432#issuecomment-1250094404 提出的解决方法，由于很多童鞋找不到解决办法，故发此Issues

### 复现步骤

。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Inverstar** [comment]
好，非常感谢！
