### ISSUE TITLE
[Bug]: Mac版arm64，提示已损坏无法打开

### ISSUE THREAD

**Issue by SDQ997** [Fndroid/clash_for_windows_pkg#3557]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.5

### 操作系统

macOS arm64(M1,M1*)

### 系统版本

Monterey12.1

### 问题描述

下载并安装Clash.for.windows-0.20.5-arm64.dmg
app已损坏无法打开

### 复现步骤

按照dmg版本，打开

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
https://docs.cfw.lbyczf.com/contents/questions.html#macos-dmg-%E5%AE%89%E8%A3%85%E5%90%8E%E6%97%A0%E6%B3%95%E6%89%93%E5%BC%80-%E6%8F%90%E7%A4%BA%E6%8D%9F%E5%9D%8F

**Comment by SDQ997** [comment]
> 

谢谢
