### ISSUE TITLE
安装了0.8.7版本，无法导入远程配置文件

### ISSUE THREAD

**Issue by zsq19958629** [Fndroid/clash_for_windows_pkg#356]
安装了0.8.7版本，无法导入远程配置文件

profiles菜单下，无任何操作的地方，点击url也无法唤起添加功能。

**Comment by Keanu-L** [comment]
卸载Clash后，删除电脑用户下的 .config/Clash 文件夹然后重装试试

**Comment by zsq19958629** [comment]
已经好了。谢谢楼上
