### ISSUE TITLE
有没有办法让某网站只使用特定的代理线路？

### ISSUE THREAD

**Issue by minshifu** [Fndroid/clash_for_windows_pkg#3568]
请问，有没有办法让某一个网站只使用特定的代理线路，比如让某网站只使用美国的代理线路，或只使用台湾的代理线路，但同时又不影响其他网站使用Auto代理模式？多谢了！

**Comment by yi-Xu-0100** [comment]
增加一个 proxy-group，然后 rule 指定

**Comment by minshifu** [comment]
> 增加一个 proxy-group，然后 rule 指定
好的，多谢！
