### ISSUE TITLE
[Bug]: linux系统 could not connect to clash core, logs are not avaliable

### ISSUE THREAD

**Issue by witcher-joey** [Fndroid/clash_for_windows_pkg#3576]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.17.3; 0.19.13; 0.20.5

### 操作系统

Linux

### 系统版本

ubuntu 18.04

### 问题描述

问题：./cfw启动clash for windows后，general页面显示：could not connect to clash core, logs are not avaliable.
config.yaml也无法导入，单击后，弹出提示框：could not switch to this profile!  Error: network error

### 复现步骤

没有一次成功过。每次打开都是问题页面。

### 日志文件

<details><summary>logs</summary><p>

```
日志文件无内容，为空白
```

</p></details>

**Comment by mmclofe** [comment]
楼主解决了吗，我Windows系统今天出现了跟你一样的问题

**Comment by witcher-joey** [comment]
> 楼主解决了吗，我Windows系统今天出现了跟你一样的问题

还没有，win系统的有专门的回答。

**Comment by TralMac** [comment]
我也出现这个问题了..不管是改端口还是重装clash都没有用

**Comment by Madhawamunasing** [comment]
try using "netsh winsock reset" on the cmd.
