### ISSUE TITLE
Rule-set 似乎无效

### ISSUE THREAD

**Issue by L0snight** [Fndroid/clash_for_windows_pkg#358]
在最新版的clash for windows里，配置文件按照config builder生成带rule-set的规则，对应的策略组是正确配置的。但在log里体现出只有GEOIP、MATCH这两个规则生效了。rule-set的部分没有生效。请问是必须要展开成具体规则吗？还是我配置不对。
部分配置如下:
![image](https://user-images.githubusercontent.com/19932520/71542900-1792df00-29a7-11ea-880c-3e72d5141b05.png)

**Comment by Fndroid** [comment]
CFW不支持RuleSet，builder里底部的``flat ruleset``请务必选上

**Comment by abae136ab** [comment]
> CFW不支持RuleSet，builder里底部的`flat ruleset`请务必选上

现在的0.9.2支持了吧？生效了，但重启CFA后失效，没搞清楚加载问题。
