### ISSUE TITLE
[Bug]: 在Ubuntu22中，无法正常处理Direct流量

### ISSUE THREAD

**Issue by DataSailor** [Fndroid/clash_for_windows_pkg#3585]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.5

### 操作系统

Linux

### 系统版本

Ubuntu 22.04 LTS

### 问题描述

在Ubuntu22中，设置代理后，无法处理Direct流量。其具体表现如下：
1. 若关闭代理设置，则可以正常访问内网。
2. 在Global模式下，所有流量均通过代理，可以正常访问大部分网站。
3. 在Rule模式下，外网可以正常访问，内网无法访问。
4. 在Direct模式下，无法访问几乎任何网络。

我的代理设置如下
![图片](https://user-images.githubusercontent.com/39119487/196581150-b47ee034-dddc-42f9-881f-0bec806b114a.png)
![图片](https://user-images.githubusercontent.com/39119487/196581202-c06176f5-9a8d-4691-9c18-9a94d0af57be.png)

我使用的是学校校园网环境，不知是否对此有影响

### 复现步骤

安装Ubuntu22，并启动CFW即可

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
看看日志。设置为 debug，进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框

**Comment by DataSailor** [comment]
> 看看日志。设置为 debug，进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框

我获取了一段log，但在安装文件夹下没有找到logs文件夹。不知道是不是哪里操作错误。
![图片](https://user-images.githubusercontent.com/39119487/196619772-a4e247b7-f82a-4fa6-b99a-b254df79e600.png)
![图片](https://user-images.githubusercontent.com/39119487/196619944-1c366ed1-0b9a-4bfc-99e6-223c10a94e21.png)

另外，我的使用方式是，下载x64-linux.tar.gz文件后用归档管理器解压，直接执行cfw文件使用，不知是否正确

**Comment by Fndroid** [comment]
你配置文件dns设置的全都用不了，换成普通udp dns就行了

**Comment by DataSailor** [comment]
> 你配置文件dns设置的全都用不了，换成普通udp dns就行了

了解，浪费二位时间了。感谢
