### ISSUE TITLE
修改log等级为silent后仍会产生一条等级为info的log

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [Fndroid/clash_for_windows_pkg#359]
`time="2019-12-29T00:50:51+08:00" level=info msg="Start initial compatible provider Proxy"`
log内容如上

**Comment by Fndroid** [comment]
是有这个问题，已经联系core修复

**Comment by Fndroid** [comment]
Core逻辑上可能很难修改这个行为，CFW的话，设置成silent不会再生成log文件
