### ISSUE TITLE
[Bug]: 开启TUN后，无法访问部分谷歌系网站

### ISSUE THREAD

**Issue by KagurazakaRin** [Fndroid/clash_for_windows_pkg#3593]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.5

### 操作系统

Linux

### 系统版本

Kubuntu 22.04

### 问题描述

在使用TUN模式后，firefox可以访问 `www.google.com.hk` 以及 Twitter 等，但无法访问 `www.google.com` 和 Youtube 等网站

### 复现步骤

这是 `curl` 的结果
![image](https://user-images.githubusercontent.com/55448679/196954976-b869d616-7c3c-4a93-9db0-3081faa7b61c.png)

使用 `nslookup www.google.com` 后发现直接定向到 `127.0.0.1`，但 `nslookup www.google.com.hk` 是正常的
![image](https://user-images.githubusercontent.com/55448679/196955699-4eca09f0-20d7-4585-82fd-fc434ab5e7a9.png)

### 日志文件

<details><summary>logs</summary><p>

```
[2022-10-20-224237.log](https://github.com/Fndroid/clash_for_windows_pkg/files/9831218/2022-10-20-224237.log)


```

</p></details>

### 其他补充

TUN mode 为默认设置

如果在 firefox 中设置代理，则可以正常访问 `www.google.com` （firefox已关闭安全DNS）
![image](https://user-images.githubusercontent.com/55448679/196957536-6e62453e-699c-401c-89c1-c41440d239bb.png)

**Comment by yi-Xu-0100** [comment]
有无日志，开到 debug 看看用的哪个 dns 解析的

**Comment by KagurazakaRin** [comment]
> 有无日志，开到 debug 看看用的哪个 dns 解析的
我尝试在firefox里访问 `www.google.com` 后的日志
[2022-10-20-224237.log](https://github.com/Fndroid/clash_for_windows_pkg/files/9831188/2022-10-20-224237.log)

**Comment by yi-Xu-0100** [comment]
日志里没有 www.google.com ，可能没进 clash 吧，建议还是给 firefox 设置代理为好。

**Comment by KagurazakaRin** [comment]
> 日志里没有 [www.google.com](http://www.google.com) ，可能没进 clash 吧，建议还是给 firefox 设置代理为好。

是没有进Clash。我今天重启虚拟机，然后自己添加了一条 google.com 的规则后就突然好了，也不太确定是什么原因导致的。
