### ISSUE TITLE
[问题求助]:  自己搭的梯子怎样配置才能在配置文件中显示流量信息

### ISSUE THREAD

**Issue by fsdfkefs** [Fndroid/clash_for_windows_pkg#3598]
### 功能描述

需要在代理服务端配置，或者是通过订阅转换，还是本地clashForWindows端配置就可以呀
求大佬给个关键词

**Comment by yi-Xu-0100** [comment]
https://docs.cfw.lbyczf.com/contents/urlscheme.html#subscription-userinfo
