### ISSUE TITLE
无论如何都无法连接上，一直显示黄色

### ISSUE THREAD

**Issue by beraken** [Fndroid/clash_for_windows_pkg#36]
这是录屏，https://d.pr/v/IblsVK
这个是Log文件的打包
https://d.pr/f/WCzms0

**Comment by Fndroid** [comment]
app关掉，教程里看看有没有clash-win64杀掉，再重启

**Comment by beraken** [comment]
试过了，没用，我觉得最诡异的是为何开启后我连国内的网站也上不去了

**Comment by CraftsmanHyj** [comment]
感觉被骗了

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
