### ISSUE TITLE
[Bug]: 拥有网桥的情况下（hyper-v配置相关）,TUN模式重复请求dns导致core卡死

### ISSUE THREAD

**Issue by Xianbei233** [Fndroid/clash_for_windows_pkg#3601]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.6

### 操作系统

Windows x64

### 系统版本

22h2

### 问题描述

![image](https://user-images.githubusercontent.com/16370242/197387679-82626ed9-d6cf-4052-89af-c0d872d0cd74.png)
如图，wlan网桥给hyper-v外网交换机，外网交换机共享链接给NAT交换机，开启tun模式后检测到出口网卡为（外网），开始重复请求dns server
![image](https://user-images.githubusercontent.com/16370242/197387793-f34754e0-e918-403a-ae5d-b85de2deec5c.png)

### 复现步骤

如上

### 日志文件

<details><summary>logs</summary><p>

没找到logs文件
</p></details>

**Comment by Xianbei233** [comment]
tun模式为默认设置

**Comment by Xianbei233** [comment]
![image](https://user-images.githubusercontent.com/16370242/197388065-fa2de94a-8091-4c87-823d-887ff246a429.png)

**Comment by yi-Xu-0100** [comment]
看起来是回环了，设置下 interfacee-name 看看有没有改善

**Comment by Xianbei233** [comment]
重装和重启后正常了。。。。。。尴尬，此单暂时关闭
