### ISSUE TITLE
[Bug]: 软件里面被下了木马

### ISSUE THREAD

**Issue by SZ001S** [Fndroid/clash_for_windows_pkg#3603]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.6

### 操作系统

Windows x64

### 系统版本

19043.2006

### 问题描述

系统报毒，
![image](https://user-images.githubusercontent.com/64235668/197477099-38379b1d-d44a-4bf3-ac06-4c0cecae2a46.png)
![image](https://user-images.githubusercontent.com/64235668/197477139-f92ab929-118a-4799-aa3c-db0f7b9b6135.png)

### 复现步骤

装一下软件就知道了 软件里面被下了木马

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

无

**Comment by yi-Xu-0100** [comment]
360安全大脑?！😂

**Comment by kyaukyue** [comment]
360安全管家是吧👍

**Comment by SZ001S** [comment]
之前都没报嘛 我现在是不敢更新的嘛

**Comment by SorenEricMent** [comment]
蚌埠住了 你電腦裏最大的木馬是360自己

**Comment by NsCrosu** [comment]
6

**Comment by Ke1v1n** [comment]
牛逼

**Comment by sudocodus** [comment]
6666 真安全
