### ISSUE TITLE
界面支持 FDS 设计

### ISSUE THREAD

**Issue by Shomnipotence** [Fndroid/clash_for_windows_pkg#362]
FDS 现已支持 Win32 程序，Windows 10 now enables you to use UWP controls in non-UWP desktop applications so that you can enhance the look, feel, and functionality of your existing desktop applications with the latest Windows 10 UI features that are only available via UWP controls. This means that you can use UWP features such as Windows Ink and controls that support the Fluent Design System in your existing WPF, Windows Forms, and C++ Win32 applications. This developer scenario is sometimes called XAML islands.

XAML Islands Demo: https://developer.microsoft.com/en-us/events/build/content/fluent-design-system-demo
Entire Fluent Design @ Build 2018 playlist: https://developer.microsoft.com/en-us/events/build/content/fluent-design-system-evolution?playlist=41f18bdd-6d5a-44b9-8586-0fa36ed91c45
Documentation here:  https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/xaml-host-controls

希望构建一个更为现代化的外观

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
