### ISSUE TITLE
开了tun system或者  proxy  天翼云登录不上

### ISSUE THREAD

**Issue by 986244073** [Fndroid/clash_for_windows_pkg#3622]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.6

### 操作系统

Windows x64

### 系统版本

w11 22H2

### 问题描述

开了tun system或者  proxy  天翼云登录不上

### 复现步骤

开了tun system或者  proxy  天翼云登录不上
已经使用  - PROCESS-NAME,eCloudUpgrade.exe,DIRECT
![image](https://user-images.githubusercontent.com/16508677/198786139-8bf9fae8-0d71-4a85-99bf-728df5cd793e.png)

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by 986244073** [comment]
打错了 是 system proxy

**Comment by yi-Xu-0100** [comment]
看看日志
