### ISSUE TITLE
[Bug]: 开启clash后IPV6网站打不开【问题再次出现#1120】

### ISSUE THREAD

**Issue by TeemoZhang-ice** [Fndroid/clash_for_windows_pkg#3627]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.6

### 操作系统

Windows x64

### 系统版本

Win10-LTSC

### 问题描述

开启clash后，在网站http://ip.zxinc.org/ipquery/ 中，显示我的网络不支持ipv6，但是关闭clash后，就可以显示我的ipv6地址。

### 复现步骤

开启clash代理，无法使用ipv6网站；
关闭代理，可以正常打开。
检测结果可用网站http://ip.zxinc.org/ipquery/
![image](https://user-images.githubusercontent.com/64951564/198861314-c6247385-66f7-4be5-88ee-29c6bcecd763.png)
![image](https://user-images.githubusercontent.com/64951564/198861329-25b9ad2c-83ca-4a44-a799-37fdf1b73f10.png)

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>
[2022-10-30-024710.log](https://github.com/Fndroid/clash_for_windows_pkg/files/9895025/2022-10-30-024710.log)

### 其他补充

手机上尝试stash时，一切正常。说明我的机场应该没有问题，这个问题有必要再次提及。
另外我找到的其他相关问题反馈都已关闭，且指向的[#933](https://github.com/Fndroid/clash_for_windows_pkg/issues/933)号问题已经失效（来自[#1160](https://github.com/Fndroid/clash_for_windows_pkg/issues/1160)），所以不得都已再次开一个新的问题反馈。

**Comment by TeemoZhang-ice** [comment]
已搜索过相关问题和文档，虽然有描述类似问题，但目前处于关闭状态，或处理方式无效，或问题回答如#933已失效。

**Comment by cancundeyingzi** [comment]
我在电脑上可用,但是别的设备不行(梅林clash/cfa/choc)

**Comment by 94run** [comment]
我今天申请公网ip之后，也遇到了同样的问题。之前没有问题

**Comment by lzh81569** [comment]
一样的问题

**Comment by alienzhangyw** [comment]
+1，怎么能解决？
