### ISSUE TITLE
proxy-groups 配置fallback interval  只检查一次[Bug]: 

### ISSUE THREAD

**Issue by Sanchew** [Fndroid/clash_for_windows_pkg#3630]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.6

### 操作系统

macOS arm64(M1,M1*)

### 系统版本

12

### 问题描述

我配置了一个proxy-groups  type为fallback   proxies 一个为代理软件  另一个是DIRECT    代理软件映射url访问的文件为本地文件
interval 设置为10   我希望我代理软件开启时走代理软件  否则直连,   
   但我发两步url的检查只请求一次  并不是每10秒一次   当代理软件关闭后可正常直连  但再次打开代理软件后无法自动转发连接到代理软件中,   需要clash重新加载,  

### 复现步骤

type设置为fallback 然后添加一个抓包软件  会发现 请求并不是按interval的时间间隔来请求

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
看起来像是 core issue: <https://github.com/Dreamacro/clash/issues>
