### ISSUE TITLE
[Bug]: 疯狂跑流量

### ISSUE THREAD

**Issue by webxiaoz** [Fndroid/clash_for_windows_pkg#3631]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.6

### 操作系统

Windows x64

### 系统版本

win10 20H2

### 问题描述

只要一打开允许局域网连接就疯狂跑上传下载，日志疯狂的刷，特别吓人
![image](https://user-images.githubusercontent.com/37789059/199006781-87ae45ad-d77d-45eb-beac-f5af27ba6b3f.png)
![image](https://user-images.githubusercontent.com/37789059/199006832-5b3d6d8c-30e1-4aa8-acd6-608b3bc2df4f.png)

### 复现步骤

允许局域网之后就能复现

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>
[2022-10-31-200432.log](https://github.com/Fndroid/clash_for_windows_pkg/files/9900970/2022-10-31-200432.log)

**Comment by xkww3n** [comment]
电脑暴露到公网还不开防火墙是吧，这不是软件Bug，是你有问题
