### ISSUE TITLE
[Bug]: tun模式无法接管

### ISSUE THREAD

**Issue by deuteros-gex** [Fndroid/clash_for_windows_pkg#3637]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.6

### 操作系统

Windows x64

### 系统版本

win10 19045.2193 (22H2)

### 问题描述

对特定网站（miobt.com），tun模式经常没法接管流量。
1、在tun模式下，偶尔能打开miobt.com，但更多时候是打不开的。
查看cfw的日志，发现miobt.com的流量并没有被clash接管（日志里搜miobt没东西）。
并不是规则的问题，因为此时关掉tun、打开system proxy，网站秒开。。
![image](https://user-images.githubusercontent.com/67225583/199153489-c82dbfba-febe-4777-9b2f-e6fc494ac889.png)

2、另外也经常出现这个浏览器能开、那个浏览器打不开的情况。。

3、其它网站，诸如油管、谷歌就没这个问题。

### 复现步骤

tun模式的只设置了stack为system，然后在win10防火墙里做了放行，其它设置全默认。

其它可能影响分流规则的设置（如bypass、parser、mixin）也都没做设置。

### 日志文件

没有日志，因为流量没有被成功接管。

**Comment by yi-Xu-0100** [comment]
要不改成 gvisor 试试

**Comment by jesee030** [comment]
> 要不改成 gvisor 试试

一般都能解决
