### ISSUE TITLE
Geoip database can't update in 2019.12.31

### ISSUE THREAD

**Issue by cgkings** [Fndroid/clash_for_windows_pkg#364]
MaxMind stop update
Steps for Migration     
Sign up for a MaxMind account (no purchase required)
Set your password and create a license key
Setup your download mechanism by using our GeoIP Update program or creating a direct download script

**Comment by Aceralon** [comment]
v0.8.8使用 https://static.clash.to/GeoIP2/GeoIP2-Country.mmdb url更新无法完成，更新进度停在2%或者3%

**Comment by Fndroid** [comment]
@Aceralon 只支持maxmind压缩格式的

**Comment by aglent** [comment]
新版MaxMind格式的URL填什么呢？

**Comment by cgkings** [comment]
> 新版MaxMind格式的URL填什么呢？

同问，这个URL到底填什么才对啊

**Comment by 0085-Ginkgo** [comment]
数据库填那个URL，能说明白点吗？

**Comment by cgkings** [comment]
> @Aceralon只支持maxmind压缩格式的

大佬，那这个数据库URL到底应该填哪个地址呢，或者说怎么获取这个地址？

**Comment by xby020** [comment]
MaxMind 的免费账户似乎需要公司或者组织级别的邮箱才能申请，不对个人用户开放

**Comment by zhujunsan** [comment]
MaxMind的官方说明：https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

说是需要用公司邮箱，但我用gmail也注册成功了。

验证完邮箱后，在下载页面（https://www.maxmind.com/en/download_files?direct=1），使用 GeoLite2-Country 的地址，粘贴进Clash里（可以把url里日期那个参数去掉，不然每次都要改日期才能下载到最新的数据库）

**Comment by xby020** [comment]
> MaxMind的官方说明：https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/
> 
> 说是需要用公司邮箱，但我用gmail也注册成功了。
> 
> 验证完邮箱后，在下载页面（https://www.maxmind.com/en/download_files?direct=1 ），使用 GeoLite2-Country 的地址，粘贴进Clash里（可以把url里日期那个参数去掉，不然每次都要改日期才能下载到最新的数据库）

经测试确实可以了，注意申请的时候关掉微屁恩。

**Comment by yyanxiao** [comment]
https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=YOUR_LICENSE_KEY&suffix=tar.gz
You will need to replace the YOUR_LICENSE_KEY placeholder with an active license key associated with your MaxMind account.

**Comment by aglent** [comment]
> 
> 
> > MaxMind的官方说明：https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/
> > 说是需要用公司邮箱，但我用gmail也注册成功了。
> > 验证完邮箱后，在下载页面（https://www.maxmind.com/en/download_files?direct=1 ），使用 GeoLite2-Country 的地址，粘贴进Clash里（可以把url里日期那个参数去掉，不然每次都要改日期才能下载到最新的数据库）
> 
> 经测试确实可以了，注意申请的时候关掉微屁恩。

下载的是gz格式文件 clash里更新后会自动解压吗？

**Comment by ntol** [comment]
Sorry, we are not able to provide you with an account.
-我用的gmail，不可以呢。

**Comment by aglent** [comment]
> 
> 
> > MaxMind的官方说明：https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/
> > 说是需要用公司邮箱，但我用gmail也注册成功了。
> > 验证完邮箱后，在下载页面（https://www.maxmind.com/en/download_files?direct=1 ），使用 GeoLite2-Country 的地址，粘贴进Clash里（可以把url里日期那个参数去掉，不然每次都要改日期才能下载到最新的数据库）
> 
> 经测试确实可以了，注意申请的时候关掉微屁恩。

注册时本地IP 更新的时候走了代理通道 收到邮件通知了

**Comment by conan4803** [comment]
感谢，GMAIL注册成功，更新IP成功

**Comment by suiahae** [comment]
> > MaxMind的官方说明：https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/
> > 说是需要用公司邮箱，但我用gmail也注册成功了。
> > 验证完邮箱后，在下载页面（https://www.maxmind.com/en/download_files?direct=1 ），使用 GeoLite2-Country 的地址，粘贴进Clash里（可以把url里日期那个参数去掉，不然每次都要改日期才能下载到最新的数据库）
> 
> 经测试确实可以了，注意申请的时候关掉微屁恩。

也就是地区要选择China是吗？

**Comment by aglent** [comment]
> 
> 
> > > MaxMind的官方说明：https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/
> > > 说是需要用公司邮箱，但我用gmail也注册成功了。
> > > 验证完邮箱后，在下载页面（https://www.maxmind.com/en/download_files?direct=1 ），使用 GeoLite2-Country 的地址，粘贴进Clash里（可以把url里日期那个参数去掉，不然每次都要改日期才能下载到最新的数据库）
> > 
> > 
> > 经测试确实可以了，注意申请的时候关掉微屁恩。
> 
> 也就是地区要选择China是吗？

我选china 因为不通过代理

**Comment by qvshuo** [comment]
> 
> 
> > > > MaxMind的官方说明：https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/
> > > > 说是需要用公司邮箱，但我用gmail也注册成功了。
> > > > 验证完邮箱后，在下载页面（https://www.maxmind.com/en/download_files?direct=1 ），使用 GeoLite2-Country 的地址，粘贴进Clash里（可以把url里日期那个参数去掉，不然每次都要改日期才能下载到最新的数据库）
> > > 
> > > 
> > > 经测试确实可以了，注意申请的时候关掉微屁恩。
> > 
> > 
> > 也就是地区要选择China是吗？
> 
> 我选china 因为不通过代理

不通过代理打不开maxmind呀

**Comment by qvshuo** [comment]
通过代理（台湾ip），注册时地区选择台湾，邮箱使用腾讯企业邮Foxmail，成功注册使用。

**Comment by LeungKowk** [comment]
申请了，并没有收到邮件...

**Comment by hyq3351** [comment]
> 申请了，并没有收到邮件...

是gmail吗

**Comment by 0085-Ginkgo** [comment]
注册MAXMIND账号显示不行  怎么弄啊
![image](https://user-images.githubusercontent.com/59409138/71774248-668fd400-2fa6-11ea-9664-f969ea142be6.png)

**Comment by Knight-Hang** [comment]
> 注册MAXMIND账号显示不行 怎么弄啊
> ![image](https://user-images.githubusercontent.com/59409138/71774248-668fd400-2fa6-11ea-9664-f969ea142be6.png)

注册的时候要退出clash哦，不是选择direct

**Comment by 0085-Ginkgo** [comment]
> > 注册MAXMIND账号显示不行怎么弄啊
> > ![图片](https://user-images.githubusercontent.com/59409138/71774248-668fd400-2fa6-11ea-9664-f969ea142be6.png)
> 
> 注册的时候要退出clash哦，不是选择direct

关了clash了怎么还是不可以 公司 国家 应该怎么填啊
![image](https://user-images.githubusercontent.com/59409138/71779533-0292fd00-2ff2-11ea-9765-60273a79404c.png)

**Comment by WenJunDuan** [comment]
最上面有个可以下载，然后手动替换的

**Comment by wordlesswind** [comment]
https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=YOUR_LICENSE_KEY&suffix=tar.gz
> You will need to replace the `YOUR_LICENSE_KEY` placeholder with an active license key associated with your MaxMind account.
You can see your license key information on [your account License Keys page](https://www.maxmind.com/en/accounts/current/license-key).

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
