### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by mj5219054** [Fndroid/clash_for_windows_pkg#3640]
### 功能描述

教程：https://github.com/chiupam/tutorial/tree/master/Loon/Plus

**Comment by yi-Xu-0100** [comment]
???

**Comment by mj5219054** [comment]
> ### 功能描述
> 
> 教程：https://github.com/chiupam/tutorial/tree/master/Loon/Plus
> ### 其他内容
> 
> _No response_
