### ISSUE TITLE
[Bug]: Mac上的cfw打开后，safari的网页翻译功能失效

### ISSUE THREAD

**Issue by Wrandz** [Fndroid/clash_for_windows_pkg#3643]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.6

### 操作系统

macOS arm64(M1,M1*)

### 系统版本

13.0

### 问题描述

打开cfw之后，safari的翻译功能失效了，edge是好的。在logs中可以看到访问了apple的地址，走的是直连。改成翻墙也不行。

### 复现步骤

我想请问大家有没有这个问题，还是只有我一个人有。复现就是打开cfw的情况下打开safari试一下翻译功能。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>
[2022-11-03-200336.log](https://github.com/Fndroid/clash_for_windows_pkg/files/9928161/2022-11-03-200336.log)

**Comment by Fndroid** [comment]
如果不需要代理apple的话，可以试试在 Settings - System Proxy 里 Bypass Domain 里多加最后这个
<img width="850" alt="image" src="https://user-images.githubusercontent.com/16091562/199734285-68d2103f-ed26-4276-90a1-b3e2157781b3.png">

**Comment by Wrandz** [comment]
@Fndroid 果然，这样就好了！纳闷，apple会识别出代理，然后拒绝服务吗？
