### ISSUE TITLE
打开clash提示安全警告安装证书

### ISSUE THREAD

**Issue by suonianjielai** [Fndroid/clash_for_windows_pkg#3645]
![image_2022-11-04_14-10-36](https://user-images.githubusercontent.com/106580909/199904747-b1d854bd-236f-4c72-977a-a8cb533a87fd.png)
想请问这个能不能安装，是属于第三方的还是clash里面需要的

**Comment by Tanimodori** [comment]
可能是订阅链接的https证书失效导致的
