### ISSUE TITLE
请问一下各位大师，ia-32-win与7z-win这两个版本有什么区别，我是win10操作系统 ，我应该安装哪个版本？

### ISSUE THREAD

**Issue by vipusername** [Fndroid/clash_for_windows_pkg#3652]
### 功能描述

我是小白，第一次用github.如有打扰，请见谅。

**Comment by yi-Xu-0100** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/3611#issuecomment-1291954296
