### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xuanshao-zty** [Fndroid/clash_for_windows_pkg#3653]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.7

### 操作系统

Windows x64

### 系统版本

win10 1909

### 问题描述

自己建的节点，相同配置下v2ray可以正常连接，clash提示超时，不清楚是不是配置哪里有问题。还是无法使用。我贴一下v2ray配置和clash配置。

### 复现步骤

v2ray:
{
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "xxx.xx.xxx.xx", // 已隐藏
            "port": 8080,
            "users": [
              {
                "id": "xxxxxxxxxxxxxxxxx", // 已隐藏
                "alterId": 0,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "kcp",
        "kcpSettings": {
          "uplinkCapacity": 100,
          "downlinkCapacity": 100,
          "congestion": true,
          "header": { "type": "dtls" }
        }
      },
      "mux": { "enabled": true }
    },
    { "protocol": "freedom", "settings": {}, "tag": "direct" },
    { "protocol": "blackhole", "settings": {}, "tag": "blocked" },
    { "protocol": "dns", "tag": "dns-out" }
  ],
  "inbounds": [
    {
      "port": "1099",
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp,udp",
        "timeout": 0,
        "followRedirect": true
      },
      "sniffing": { "enabled": true, "destOverride": ["http", "tls"] }
    },
    {
      "port": 2133,
      "tag": "dns-in",
      "protocol": "dokodemo-door",
      "settings": {
        "address": "119.29.29.29",
        "port": 53,
        "timeout": 0,
        "network": "tcp,udp"
      }
    },
    {
      "port": 2333,
      "protocol": "socks",
      "settings": { "auth": "noauth", "udp": true }
    },
    {
      "port": 6666,
      "protocol": "http",
      "settings": { "auth": "noauth", "udp": true }
    }
  ],
  "dns": {
    "servers": [
      {
        "address": "119.29.29.29",
        "port": 53,
        "domains": ["geosite:cn"],
        "expectIPs": ["geoip:cn"]
      },
      {
        "address": "1.1.1.1",
        "port": 53,
        "domains": ["geosite:geolocation-!cn"]
      },
      "8.8.8.8",
      "localhost"
    ]
  },
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      { "type": "field", "inboundTag": ["dns-in"], "outboundTag": "dns-out" },
      { "type": "field", "ip": ["geoip:private"], "outboundTag": "blocked" },
      { "type": "field", "ip": ["geoip:cn"], "outboundTag": "direct" },
      { "type": "field", "domain": ["geosite:cn"], "outboundTag": "direct" }
    ]
  }
}
clash: 
proxies:
  - {
      "type": "vmess",
      "name": "v2ray",
      "server": "xxx.xx.xx.xxx", // 已隐藏
      "port": "8080",
      "uuid": "xxxxxxxxxxxxxxxxxxx", // 已隐藏
      "alterId": "0",
      "cipher": "auto",
      "network": "kcp",
    }

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
要不把 skip-cert-verify: true 设上试试？

**Comment by xuanshao-zty** [comment]
> skip-cert-verify: true

**Comment by xuanshao-zty** [comment]
> 要不把 skip-cert-verify: true 设上试试？

没成还是失败

**Comment by Tun2Sucks** [comment]
"network": "kcp"

哪里支持了？？

**Comment by xuanshao-zty** [comment]
> "network": "kcp"
> 
> 哪里支持了？？

是不支持kcp吗？那支持哪几种传输协议？

**Comment by Tun2Sucks** [comment]
tcp

> > "network": "kcp"
> > 哪里支持了？？
> 
> 是不支持kcp吗？那支持哪几种传输协议？

tcp http h2 ws grpc

**Comment by xuanshao-zty** [comment]
> tcp
> 
> > > "network": "kcp"
> > > 哪里支持了？？
> > 
> > 
> > 是不支持kcp吗？那支持哪几种传输协议？
> 
> tcp http h2 ws grpc

非常感谢，改为HTTP协议后能正常连通了
