### ISSUE TITLE
[Bug]: 能不能把 clash for windows 改一下 强迫症看着难受

### ISSUE THREAD

**Issue by jamninetyfive** [Fndroid/clash_for_windows_pkg#3659]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.6

### 操作系统

macOS arm64(M1,M1*)

### 系统版本

13.0

### 问题描述

能不能把Mac版本的 clash for windows 改一下 强迫症看着难受

### 复现步骤

能不能把Mac版本的 clash for windows 改一下 强迫症看着难受

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
- https://github.com/Fndroid/clash_for_windows_pkg/issues/3169#issuecomment-1164350682
