### ISSUE TITLE
TAP模式处理纯IP请求失败以及模拟器网络慢

### ISSUE THREAD

**Issue by L0snight** [Fndroid/clash_for_windows_pkg#366]
1. 在使用TAP模式的过程中，发现纯IP请求无法处理，比如telegram无法连接网络。用sockets5可以正常连接。
2. TAP代理下，安卓模拟器的网络连接会很慢，log里会出现以下的log：
![微信截图_20200101085814](https://user-images.githubusercontent.com/19932520/71637074-a6d51680-2c75-11ea-83fe-8e5eb104ce3a.png)

**Comment by Fndroid** [comment]
1. TAP基于fakeip，所以无法处理不经过DNS的请求
2. 没用过安卓模拟器，这个日志是无法连接到这个地址``127.0.0.1:40737``
