### ISSUE TITLE
DNS解析ipv6

### ISSUE THREAD

**Issue by rangluwme** [Fndroid/clash_for_windows_pkg#3667]
### 功能描述

为什么要用fallback里的dns地址去解析ipv6地址呢？我这边的网络是没有ipv6的
![2022-11-09-16-38-52](https://user-images.githubusercontent.com/63960943/200781487-64262461-c96d-4890-af13-0a05003d998b.png)
![image](https://user-images.githubusercontent.com/63960943/200781462-26e7d69e-85aa-4829-8b64-f3061635034e.png)

**Comment by yi-Xu-0100** [comment]
那 dns 里设置 `ipv6: false` 和general 界面关闭 ipv6 试试
