### ISSUE TITLE
[Bug]: 在关机后，Clash不会将代理服务器关闭

### ISSUE THREAD

**Issue by Eason0731** [Fndroid/clash_for_windows_pkg#3670]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.7

### 操作系统

Windows x64

### 系统版本

Windows 11 22H2 专业版 64位

### 问题描述

每次关机后，Clash不会把系统设置里的"代理服务器"的按钮从"开启"设置为"关闭"
当再次开机后，无法上网，需要将代理服务器关闭后才能正常上网，我没有设置Clash为开机自启

而我试用了其他同类软件如v2RayN,ClashN,WinxRay后均为发现该问题，都会在开机再次启动后（不是重启），把代理服务器设置为"关闭"

### 复现步骤

1. 打开Clash软件，进行正常的软件使用，且并未设置开机自启动
2. 系统关机
3. 系统开机（非重启）
4. 打开浏览器输入网页，如:百度，会出现无法上网的提示
5. 在系统的代理服务器中会发现，此时的设置为"开启"，并非"关闭"
6. 将系统的代理服务器关闭后，即可正常上网，开启Clash后仍可正常使用

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
设置 system proxy 为 pac 模式

**Comment by Eason0731** [comment]
> 设置 system proxy 为 pac 模式

搞定，这个方法完全解决了问题，谢谢！
