### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by alex14563** [Fndroid/clash_for_windows_pkg#3674]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.6

### 操作系统

Windows x64

### 系统版本

22H2（内部版本号22621.755）

### 问题描述

无法更新到最新版本，点击General页面版本号无反应

### 复现步骤

点击General页面版本号无反应

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
日志中有无github访问？

**Comment by alex14563** [comment]
有的
[2022-11-12-111404.log](https://github.com/Fndroid/clash_for_windows_pkg/files/9993947/2022-11-12-111404.log)

**Comment by yi-Xu-0100** [comment]
@alex14563 只有刚启动的时候有，看起来不太像，而且用的直连，应该会查询不到。你是便携版吗？

**Comment by alex14563** [comment]
不是直连啊，一直用的是“规则”，开头的那块日志就是点击版本号时新出来的
![image](https://user-images.githubusercontent.com/19344483/201456543-cff30609-3ba2-455f-ad54-bf2114c0203a.png)
另外你说的便携版是这种吗？我记得当初是直接从GitHub的release里面拿下来用的
![image](https://user-images.githubusercontent.com/19344483/201456600-54e93fd8-7d1e-468d-97f6-e5e61e056ac8.png)

**Comment by alex14563** [comment]
后面更新过很多次都没问题，就这次点击更新没反应

**Comment by alex14563** [comment]
![image](https://user-images.githubusercontent.com/19344483/201456777-e6f52104-8fda-4fbe-9d34-0a5bc026ca1c.png)
