### ISSUE TITLE
Dial [GLOBAL] failed

### ISSUE THREAD

**Issue by CDOM** [Fndroid/clash_for_windows_pkg#368]
有人知道这个错误怎么解决吗？ Dial [GLOBAL] failed
![image](https://user-images.githubusercontent.com/3339107/71711083-46db9d00-2e3a-11ea-9290-cba8502d1640.png)

**Comment by Fndroid** [comment]
**GLOBAL**这个策略组选中的节点连接不上

**Comment by CDOM** [comment]
您好！用代理也是拨号失败
![image](https://user-images.githubusercontent.com/3339107/71763162-73afb300-2f13-11ea-8818-beb7176eae3e.png)

**Comment by CDOM** [comment]
> **GLOBAL**这个策略组选中的节点连接不上

您好！请问这个有什么解决方案吗？谢谢！

**Comment by Fndroid** [comment]
本地和节点服务器连接不上，可能是代理服务器出现网络波动，或者直接被墙了。没有解决办法

**Comment by CDOM** [comment]
> 本地和节点服务器连接不上，可能是代理服务器出现网络波动，或者直接被墙了。没有解决办法

好的，谢谢！
