### ISSUE TITLE
[Bug]: 重置全部设置失效，出现白屏

### ISSUE THREAD

**Issue by Maozai-Teng** [Fndroid/clash_for_windows_pkg#3687]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.5 开始

### 操作系统

Windows x64

### 系统版本

win10 22h2

### 问题描述

点击重置全部设置，出现白屏显示错误，然后什么都不能操作~
我从0.20.7一个个版本往下试，发现直到0.20.4才没有这个bug，也就是说从0.20.5开始直到现在0.20.7都有这个bug
![QQ截图20221115002923](https://user-images.githubusercontent.com/18625640/201714635-13a2a6b3-cdf5-476d-92c2-599252e549a5.jpg)
![QQ截图20221115003041](https://user-images.githubusercontent.com/18625640/201714652-b2cffffa-8e88-4eee-a498-3672cbcb6f8b.jpg)

### 复现步骤

0.20.5往后的版本，点击重置全部设置后，就出现白屏

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
下个版本修复，感谢反馈

**Comment by Maozai-Teng** [comment]
> 下个版本修复，感谢反馈

https://github.com/Fndroid/clash_for_windows_pkg/issues/3679#issuecomment-1312770918 嘻嘻，大佬也麻烦帮看看这个是啥问题，很多人都遇到，到底是啥原因咧~

**Comment by Fndroid** [comment]
@Maozai-Teng 这个我不太清楚没有使用安卓手机哦

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
