### ISSUE TITLE
System Proxy automatically turned off

### ISSUE THREAD

**Issue by Litchilitchy** [Fndroid/clash_for_windows_pkg#369]
Hi, I found `General ->System Proxy` would automatically turn off when it runs for several minutes.

If it turns off, the bypass rule will fail. And if I manually turn it on it will work again.

Similar behavior found in shadowsocks, every several minutes it would fail and if I switch a new server it would work for another few minutes..

Seems to be my os problem? But how could clash config be modified without my permission? Any ideas?

**Comment by Fndroid** [comment]
Clash for Windows has no such behavior.

If you can read Chinese, https://github.com/Fndroid/clash_for_windows_pkg/issues/312 will help.

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
