### ISSUE TITLE
[Bug]: 订阅官网无法访问 https://admin.clashcloud.xyz/

### ISSUE THREAD

**Issue by HY-HY-49** [Fndroid/clash_for_windows_pkg#3698]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.24

### 操作系统

Windows x64

### 系统版本

w10

### 问题描述

https://admin.clashcloud.xyz/  
，无法访问，购买的订阅还没到期，网站无法访问了。

### 复现步骤

直接访问https://admin.clashcloud.xyz/。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

no

**Comment by yi-Xu-0100** [comment]
请联系供应商 （😂）

**Comment by HY-HY-49** [comment]
> 请联系供应商 （😂）

**Comment by HY-HY-49** [comment]
> 请联系供应商 （😂）

jier，这不是CFW管理的站点噢。

**Comment by yi-Xu-0100** [comment]
@HY-HY-49 当然不是,CFW不提供订阅 （😂

**Comment by HY-HY-49** [comment]
> 

了解了解

**Comment by xiaofei10** [comment]
能访问了踢我

**Comment by jachin-byte** [comment]
大佬们，现在有新的替代网址么，能联系到供应商么，刚买了还没开始呢😂

**Comment by HY-HY-49** [comment]
> 大佬们，现在有新的替代网址么，能联系到供应商么，刚买了还没开始呢😂

我换了一个，http://okz2.xyz/#/login，是用qq邮箱注册，感觉站点丢失了应该能找回。
