### ISSUE TITLE
配置文件DNS设置

### ISSUE THREAD

**Issue by mkfd** [Fndroid/clash_for_windows_pkg#37]
[Clash A rule based tunnel in Go.](https://github.com/Dreamacro/clash) 中配置文件支持dns，cfw是否也是支持？
<pre><code>
dns:
<br># enable: true # set true to enable dns (default is false)
  <br># ipv6: false # default is false
  <br># listen: 0.0.0.0:53
  <br># enhanced-mode: redir-host
  <br># nameserver:
 <br> #   - 114.114.114.114
 <br> #   - tls://dns.rubyfish.cn:853 # dns over tls
  <br># fallback: # concurrent request with nameserver, fallback used when GEOIP country isn't CN
 <br> #   - 8.8.8.8'</code>
</pre>

**Comment by Fndroid** [comment]
支持，但目前没有UI配置
