### ISSUE TITLE
请求托盘图标的路径，希望手动替换托盘图标为黑白色。

### ISSUE THREAD

**Issue by Shomnipotence** [Fndroid/clash_for_windows_pkg#370]
请求托盘图标的路径，希望手动替换托盘图标为黑白色。以便与 Windows 系统托盘图标相统一

目前看到的是
%Program Files%\Clash for Windows\resources\static\imgs
%Program Files%\Clash for Windows\Clash for Windows.exe
这两处，但是只看到了蓝色图标，没看到黄色图标

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.8.9

https://docs.cfw.lbyczf.com/contents/trayicon.html
