### ISSUE TITLE
右键菜单栏显示太多Proxy Groups能否关闭？

### ISSUE THREAD

**Issue by zoe4477** [Fndroid/clash_for_windows_pkg#3703]
### 功能描述

更新到0.20版本后右键菜单显示太多Proxy Groups了，旧版本没有这个问题，这个能否设置关闭显示？
或者把System Proxy和Proxy Mode放在菜单最下边，方便点击
![Snipaste_2022-11-20_00-15-24](https://user-images.githubusercontent.com/38827851/202860720-5f4347a6-10d3-4ab4-9005-bea3049f886c.jpg)

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/202879795-5d27fdaa-85d2-4269-a6c1-9c4ac709ef80.png)
