### ISSUE TITLE
[Bug]: Tun 模式不能代理UWP应用？

### ISSUE THREAD

**Issue by WritingWithFire** [Fndroid/clash_for_windows_pkg#3704]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

1.20.7

### 操作系统

Windows x64

### 系统版本

Windows 10 pro 21H2

### 问题描述

我记得之前的版本是可以使用TUN模式代理UWP应用的，某次更新之后就不好使了，直到现在依旧无法代理UWP。。
有人遇到相同的情况吗

### 复现步骤

none

**Comment by yi-Xu-0100** [comment]
试试把 tun mode 设置中的 any:53 改成 192.168.2.0:53 试试

**Comment by keep1earning** [comment]
检查是否有解锁UWP回环限制,
如果没有,
请确保您开启TUN的同时,
**没有**开启系统代理(UWP应用默认被限制,无法访问127.0.0.1)

**Comment by WritingWithFire** [comment]
> 检查是否有解锁UWP回环限制, 如果没有, 请确保您开启TUN的同时, **没有**开启系统代理(UWP应用默认被限制,无法访问127.0.0.1)

解决了，感谢

**Comment by WonderDing** [comment]
> 试试把 tun mode 设置中的 any:53 改成 192.168.2.0:53 试试

感谢，我也遇到同样的问题，这么改就解决了
