### ISSUE TITLE
[Bug]: providers更新的定时器逻辑错误

### ISSUE THREAD

**Issue by lhbdhr** [Fndroid/clash_for_windows_pkg#3708]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.08

### 操作系统

Windows x64

### 系统版本

WIN10

### 问题描述

使用CFW时发现rule-providers不会自动更新，尝试把时间改成600就会更新。86400不更新是因为从软件启动开始计时的吧？
这里的定时器逻辑写错了吧？应该对比文件修改时间和设定的秒数。

### 复现步骤

NULL

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
clash core issue, refer: https://github.com/Dreamacro/clash/issues

**Comment by lhbdhr** [comment]
我在CFW提过issue了，他们让我来这儿的啊。。。。。。
