### ISSUE TITLE
level=warning msg="dial groups error: ss_server:ss_port connect error: dial tcp4 ss_ip:ss_port: i/o timeout"

### ISSUE THREAD

**Issue by oycol** [Fndroid/clash_for_windows_pkg#371]
动不动会出现这个问题，比如在浏览器输入网址后立即切换浏览器页面就会阻塞，并且必须切回去才会重新加载，阻塞时报这个错误，任何策略组都可能报这个问题，不懂问题产生的原因，

![QMVSLZK%}NA55(I)~QDBL2T](https://user-images.githubusercontent.com/23732968/71764087-2edd4980-2f1e-11ea-9fed-7b8b48264dc1.png)

**Comment by Fndroid** [comment]
@oycol 问题产生的原因就是本地无法连接这个地址，软件层面并没有办法避免
