### ISSUE TITLE
[Feature Request]: v0.20.8 看不到混合配置之后的内容

### ISSUE THREAD

**Issue by lx0758** [Fndroid/clash_for_windows_pkg#3711]
### 功能描述

如题, 我记得以前有个按钮可以切换查看生效后的配置. 这个功能感觉挺好用的, 能不能给返场一下~

**Comment by yi-Xu-0100** [comment]
![图片](https://user-images.githubusercontent.com/25523606/202997509-2599b521-e9b0-48ed-9133-58f8f814acd1.png)

**Comment by lx0758** [comment]
昂...打扰了打扰了
