### ISSUE TITLE
[Bug]: 新手求教，退出clash后，打开国内网站加载很慢，有的加载不出来

### ISSUE THREAD

**Issue by scumax** [Fndroid/clash_for_windows_pkg#3715]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.9

### 操作系统

Windows x64

### 系统版本

win10 21h2

### 问题描述

新手求教，使用clash访问国外网站没问题，关闭System Proxy并退出clash后，打开国内网站加载很慢，有的网站直接加载不出来，检查过系统的手动代理已关闭。
要重新打开clash，打开System Proxy，Proxies中选择Direct，再打开国内网站就没有任何问题。
请问是什么原因，谢谢！

### 复现步骤

正常使用clash访问国外网站，关闭System Proxy，退出clash，打开国内网站加载很慢，有的网站直接加载不出来。
重新打开System Proxy，Proxies中选择Direct，再打开国内网站就没有问题

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
未知，理论上，关闭clash了，就没有代理了，而且如果确认过系统代理关了的话，感觉也没啥影响了，清理dns缓存什么的不知道行不行，看不出来特别的原因

**Comment by scumax** [comment]
> 未知，理论上，关闭clash了，就没有代理了，而且如果确认过系统代理关了的话，感觉也没啥影响了，清理dns缓存什么的不知道行不行，看不出来特别的原因

清理dns缓存也没有用

**Comment by scumax** [comment]
> 未知，理论上，关闭clash了，就没有代理了，而且如果确认过系统代理关了的话，感觉也没啥影响了，清理dns缓存什么的不知道行不行，看不出来特别的原因

解决了，就是dns服务器设置的问题，谢谢

**Comment by zhaofy2323** [comment]
请问怎么设置dns服务器？我也遇见这个问题了
