### ISSUE TITLE
WSL 不走 clash 代理

### ISSUE THREAD

**Issue by Maasea** [Fndroid/clash_for_windows_pkg#372]
我记得之前是走的，重装了一下系统之后就不走了。UMP loopback 勾选了WSL ，Tap 模式也开了。

**Comment by Fndroid** [comment]
@Maasea 开了TAP之后把wsl的dns设置为127.0.0.1

**Comment by Maasea** [comment]
> @Maasea开了TAP之后把wsl的dns设置为127.0.0.1
需要在WSL 设置代理吗？（我记得之前是不用的），更改DNS 之后还是不可以。

**Comment by Max-Cheng** [comment]
参考一下我的做法
Bash
```bash
vim ~/.bashrc
#写入以下内容
export hostip=$(cat /etc/resolv.conf |grep -oP '(?<=nameserver\ ).*');
export https_proxy="http://${hostip}:7890";
export http_proxy="http://${hostip}:7890";
export all_proxy="socks5://${hostip}:7891";
```
Fish Shell
```fish
vim .config/fish/config.fish
#写入以下内容
set hostip (cat /etc/resolv.conf |grep -oP '(?<=nameserver\ ).*');
export https_proxy="http://$hostip:7890";
export http_proxy="http://$hostip:7890";
export all_proxy="socks5://$hostip:7891";
```

**Comment by maidamai0** [comment]
`git clone` 的时候报错:
```shell
Failed to connect to 172.17.176.1 port 7890: Connection timed out
```
但实际上 `Allow Lan`是开着的
![image](https://user-images.githubusercontent.com/16829798/93672172-5fc8d300-fadb-11ea-9293-6f314de7d0a0.png)

**Comment by daxinnan** [comment]
> `git clone` 的时候报错:
> 
> ```shell
> Failed to connect to 172.17.176.1 port 7890: Connection timed out
> ```
> 
> 但实际上 `Allow Lan`是开着的
> ![image](https://user-images.githubusercontent.com/16829798/93672172-5fc8d300-fadb-11ea-9293-6f314de7d0a0.png)

请问解决了吗WSL2碰到了这个问题，不知道如何走代理

**Comment by maidamai0** [comment]
@daxinnan 
我的后来解决了，应该是uwp的loopback开启就好了。不过时间有点久了，我记不太清楚。
你现在UWP的应用可以正常使用吗，新安装的UWP也要再clash里面开一下的。

**Comment by ythaha** [comment]
> export hostip=$(cat /etc/resolv.conf |grep -oP '(?<=nameserver\ ).*');

如果这个给出的 ip 是 wsl 的 ip，会导致 wsl 无法联网。这个 ip 需要是主机 ip。 可以把鼠标悬在 clash 界面的 allow Lan 上，查看 host ip
![image](https://user-images.githubusercontent.com/22343435/122317725-93dd0180-cf50-11eb-921c-f3ff3329878f.png)
