### ISSUE TITLE
[Bug]: tun模式下浏览器可以正常连接外网，但是terminal里ping和ssh无法连接外网

### ISSUE THREAD

**Issue by liunyl** [Fndroid/clash_for_windows_pkg#3726]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.9

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

在tun模式下，正常浏览器的访问都可以使用，但是在terminal内尝试ssh连接ec2并没有走clash的代理。尝试ping google.com也会失败。在Connections和log里都没有发型ssh连接的记录。
这个问题是2022/11/23出现的，之前是可以正常使用并且在Connections里也可以看到连接到ssh的ip地址的记录。

### 复现步骤

所有的配置文件都是默认的初始配置
tun mode config:
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback: []
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53

![WeChat Screenshot_20221125130432](https://user-images.githubusercontent.com/107381948/203905055-639e09d1-9490-495b-bccd-6d3dc3a50998.png)

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by ruan7k** [comment]
我的win 10 为什么打不开呢

**Comment by ruan7k** [comment]
程序启动不了

**Comment by yi-Xu-0100** [comment]
@liunyl 首先你得确认 tun 成功了，排除系统代理的问题，给出 connection 的情况，或者给出 logs 的情况。

**Comment by liunyl** [comment]
> @liunyl 首先你得确认 tun 成功了，排除系统代理的问题，给出 connection 的情况，或者给出 logs 的情况。

@yi-Xu-0100 
https://github.com/Fndroid/clash_for_windows_pkg/issues/3689
我看了这个issue，我的情况跟他的很像。curl google.com是可以正常返回的。很有可能是机场把22端口给封掉了。我去和他们确认一下。

**Comment by liunyl** [comment]
@yi-Xu-0100 

问一下如果机场把port22屏蔽了的话，我可以在本地上把port22的请求forward到其他Port上来绕开这个屏蔽吗？是需要forward到7890端口吗？

**Comment by yi-Xu-0100** [comment]
- #3229
- #3096

这两个可能有帮助 @liunyl

**Comment by liunyl** [comment]
@yi-Xu-0100 
情况似乎还不太一样，现在我看到的情况是在rule模式下，ssh的请求完全没有出现在logs中，不论是direct还是走机场的log都没有出现。似乎clash完全没有捕捉到ssh的请求,然后ssh直接连接到了ec2，导致连接非常不稳定经常断线。

当我按照上面2个issue的解决方案把ec2上的ssh端口改成443之后，clash依然没有捕捉到ssh请求。

**Comment by liunyl** [comment]
刚和客服确认了一下，他们并没有禁用22端口

**Comment by yi-Xu-0100** [comment]
母鸡，换机场吧~😂
