### ISSUE TITLE
[Bug]: 为什么我的可连接IP只有亚洲地区的网络啊？无论是更新，还是重置订阅，还是重新安装都是老样子，只有亚洲网络，根本没有欧美那边的。

### ISSUE THREAD

**Issue by qq456250** [Fndroid/clash_for_windows_pkg#3728]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.9

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

为什么我的可连接IP只有亚洲地区的网络啊？无论是更新，还是重置订阅，还是重新安装都是老样子，只有亚洲网络，根本没有欧美那边的。
![SharedScreenshot](https://user-images.githubusercontent.com/119052015/203984206-632798f5-c609-4c80-8e4c-d63f5e80464d.jpg)

![image](https://user-images.githubusercontent.com/119052015/203984359-140d7569-41aa-451c-8084-ad254f05d545.png)

### 复现步骤

自打用这个软件开始就是这样了

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
问问订阅提供者，这只是个软件，不内置节点

**Comment by qq456250** [comment]
> 询问订阅提供者，这只是一个软件，没有设置节点

已经问过好几次了，他们只会让我重复订阅链接

**Comment by yi-Xu-0100** [comment]
@qq456250 那没救了，可能你被忽悠了

**Comment by qq456250** [comment]
我是在https://xn--mest5a943ag8x.com/#/dashboard这个网站上下载的，您看看是不是被骗了

**Comment by qq456250** [comment]
我是在这个https://xn--mest5a943ag8x.com/#/dashboard
网站上下载的，您看看是不是被骗了
