### ISSUE TITLE
clash for windows 0.8.8 在教育版windows10 下不支持chacha20! 

### ISSUE THREAD

**Issue by jackwonglstc** [Fndroid/clash_for_windows_pkg#373]
使用环境：win10 教育版 64位
输入一个SS服务器的时候，加密方式为chacha20，设置之后配置文件报错，说不支持这种加密方式。
但是我在win10 专业版 64位 确认使用过这个服务器，一切正常！

在教育版10 使用chacha20-ietf-poly1305一切正常！

不知道是什么原因？

**Comment by Fndroid** [comment]
@jackwonglstc chacha20已不再支持。建议更换加密方式。

**Comment by jackwonglstc** [comment]
> @jackwonglstc chacha20已不再支持。建议更换加密方式。

原来如此，谢谢！
