### ISSUE TITLE
[Bug]: 从0.19.20版开始，节点前面的国旗就显示不出来，恢复字体为雅黑也不行。

### ISSUE THREAD

**Issue by jiaminxun** [Fndroid/clash_for_windows_pkg#3743]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.20至最新版

### 操作系统

Windows x64

### 系统版本

win10 22H2

### 问题描述

从0.19.20版开始，节点前面的国牌就显示不出来，恢复字体为雅黑也不行。0.19.19版正常显示。

### 复现步骤

安装0.19.20版

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
system-ui的字体里有emoji字符导致twemoji没能显示出来

使用 `Microsoft Yahei,TwemojiMozilla`
