### ISSUE TITLE
[Feature Request]: 设置软件本身自己可以走代理

### ISSUE THREAD

**Issue by ted423** [Fndroid/clash_for_windows_pkg#3744]
### 功能描述

增加一个开关，更新，规则以及rule providers走代理
这样自身的一些功能就不用开系统代理才会走代理

**Comment by yi-Xu-0100** [comment]
core issue: <https://github.com/Dreamacro/clash/issues>

**Comment by ted423** [comment]
那我研究下以后要不要process name 或者bypass之类的看看
