### ISSUE TITLE
[Feature Request]: 自动解析订阅url

### ISSUE THREAD

**Issue by punkmonday** [Fndroid/clash_for_windows_pkg#3747]
### 功能描述

目前的订阅url只能解析clash标准的yaml地址,能不能加一个智能判断,如果返回的是base64加密,就自动解析为yaml配置,这样就不用再去手动解析成yaml再导入了,直接填url就自动更新了

### 其他内容

目前测试了mysocks的url就解析不了,只能得到一串base64码

**Comment by yi-Xu-0100** [comment]
core 的行为，非 CFW 的行为。

core issue: <https://github.com/Dreamacro/clash/issues>

**Comment by Fndroid** [comment]
无法实现
