### ISSUE TITLE
[Bug] TUN模式下UDP流量无视规则直连

### ISSUE THREAD

**Issue by WritingWithFire** [Fndroid/clash_for_windows_pkg#3748]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.7

### 操作系统

Windows x64

### 系统版本

Windows 10 pro 21H2

### 问题描述

![image](https://user-images.githubusercontent.com/66851780/204526930-9512c4ee-a1f9-4bc5-a802-f08994f1fcf9.png)

![image](https://user-images.githubusercontent.com/66851780/204527123-25addd7d-4f41-405d-afd6-da69ce72c0a2.png)
如图所示链接应该会命中规则从而走代理（我把那条规则放在最顶端，不是优先级的问题），但是实际上直连了。
打开系统代理则可以正常命中该规则

help，有大佬帮帮忙嘛

### 复现步骤

none

**Comment by Fndroid** [comment]
如果节点没有标明 `udp: true` 那么 UDP 就会直接 DIRECT

**Comment by WritingWithFire** [comment]
谢大佬指点，已经解决了
