### ISSUE TITLE
[Bug]: 占用系统资源，卡顿

### ISSUE THREAD

**Issue by HsFrost** [Fndroid/clash_for_windows_pkg#3750]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.7

### 操作系统

Windows x64

### 系统版本

版本	Windows 11 教育版 版本	21H2 安装日期	‎2022/‎7/‎16 操作系统版本	22000.1219 体验	Windows 功能体验包 1000.22000.1219.0

### 问题描述

![image](https://user-images.githubusercontent.com/41307620/204527969-e79e3fac-63a1-41be-852a-6dfec1ac0617.png)
![image](https://user-images.githubusercontent.com/41307620/204528080-e0642110-83b6-4c66-bf07-32bb66fb307e.png)
连接数在几分钟内跳至几万

### 复现步骤

不知道问题具体出现在哪里，甚至没有开启代理，而是连接上这个配置文档，就开始跳连接数，疯狂占用CPU与内存，并且产生大量流量(吃了几个G，就不截图了)

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

[2022-11-29-194322.log](https://github.com/Fndroid/clash_for_windows_pkg/files/10113076/2022-11-29-194322.log)

### 其他补充
甚至产生了一个200M的日志
![image](https://user-images.githubusercontent.com/41307620/204532314-94eb9c7e-5ea2-4da5-b0f7-0ca4f1d4909d.png)

全部没有更改，默认状态，设置也未自定义过
![image](https://user-images.githubusercontent.com/41307620/204531570-a8f74ece-d17c-4515-9e82-35ca3967e4ec.png)

**Comment by yi-Xu-0100** [comment]
看看配置中有没有自带 tun 配置和 dns 配置。

**Comment by HsFrost** [comment]
> 看看配置中有没有自带 tun 配置和 dns 配置。 关闭或者删除再试试

解决了，3Q

**Comment by OXERIS** [comment]
> > 看看配置中有没有自带 tun 配置和 dns 配置。 关闭或者删除再试试
> 
> 解决了，3Q

你是按上面的建议解决的吗，我试了没效果

**Comment by HsFrost** [comment]
> > > 看看配置中有没有自带 tun 配置和 dns 配置。 关闭或者删除再试试
> > 
> > 
> > 解决了，3Q
> 
> 你是按上面的建议解决的吗，我试了没效果

是的，我这边配置文件有一个dns开关改为false就好了

**Comment by LiuJunhan2020** [comment]
![image](https://user-images.githubusercontent.com/73101620/217814508-55b10a2d-448e-4b93-a04c-d8f3c13713be.png)
请问这个是用什么软件查询的呢？

**Comment by Gytobp** [comment]
> ![image](https://user-images.githubusercontent.com/73101620/217814508-55b10a2d-448e-4b93-a04c-d8f3c13713be.png) 请问这个是用什么软件查询的呢？

看起来像火绒，安全工具 | 流量监控

**Comment by HsFrost** [comment]
是火绒

**Comment by HsFrost** [comment]
> ![image](https://user-images.githubusercontent.com/73101620/217814508-55b10a2d-448e-4b93-a04c-d8f3c13713be.png) 请问这个是用什么软件查询的呢？

是火绒
