### ISSUE TITLE
[Bug]: clash core service stopped upon switching to battery power on a laptop computer

### ISSUE THREAD

**Issue by bodayw** [Fndroid/clash_for_windows_pkg#3755]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.9

### 操作系统

Windows x64

### 系统版本

Windows 10 Pro 21H2 19044.2251

### 问题描述

从 0.20.8 开始，使用 schtasks 方式安装 service mode，由于计划任务创建时没有禁用“Stop if the computer switches to battery power”这一项，导致笔记本电脑在切换到电池时，clash core service 自动退出。

Windows 的这个计划任务默认总是启用这一项，很坑。我以前就给其他软件报告过相同的问题：
https://github.com/netchx/netch/issues/651

### 复现步骤

使用 schtasks 方式安装 service mode，拔掉笔记本电脑外接电源。

### 日志文件

应该不需要

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
