### ISSUE TITLE
[Bug]: Service Mode一处拼写错误

### ISSUE THREAD

**Issue by asit00** [Fndroid/clash_for_windows_pkg#3757]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.10

### 操作系统

Windows x64

### 系统版本

22H2 19045.2311

### 问题描述

Service Mode界面的Install Method中，schtasks(recommanded)应为recommended

### 复现步骤

点击主界面Service Mode的Manage

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
😁我就说好像有个typo还没改过来，漏了这个，感谢指正

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
