### ISSUE TITLE
[Bug]: Could not switch to this profile

### ISSUE THREAD

**Issue by PRSJMC** [Fndroid/clash_for_windows_pkg#3760]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.10

### 操作系统

Windows x64

### 系统版本

Win11 Pro 22623.730

### 问题描述
已知两种触发场景：
①CFW挂在后台不固定时间地出现无法联网情况，Proxies页面延迟测试timeout；
尝试更新订阅，开启System Proxy下无法更新Profile；
关闭代理后重新订阅再开启代理，Proxies页面延迟测试正常，但Chrome实际无法访问外网；
②较长时间使用后，主动切换profile，直接弹窗报错；

上述两种情况下，Profiles页面下均没有profile被选中；
然后尝试选择profile会弹窗报错：
`Could not switch to this profile! : timeout of 10000ms exceeded`
之后只能重启软件，有效的，可过了段时间又会重新出现。（共测试了4家不同机场的profile）

环境补充说明：
尝试过但无效的操作：用前两个大版本的旧CFW；兼容性选项设置为管理员权限；将CFW所在文件夹设置为Defender排除路径；

附图说明情况：
![image](https://user-images.githubusercontent.com/46528990/205286438-e883c63e-1b57-46fa-a5ba-3e599292a775.png)
![image](https://user-images.githubusercontent.com/46528990/205286392-08e55ff6-2e94-4a49-b87c-e0262d24111b.png)
![image](https://user-images.githubusercontent.com/46528990/205286423-36b6c6cc-d756-4ed3-90b5-dbd308d7929a.png)

### 复现步骤

可能用规则比较多的机场+多几个Profile，一直挂机+win11接近的系统版本就能复现吧。

### 日志文件

<details><summary>logs</summary><p>

debug级别，失效了一次的logs但可能没记录到。
[2022-12-02-192243.log](https://github.com/Fndroid/clash_for_windows_pkg/files/10141027/2022-12-02-192243.log)

</p></details>

### 其他补充

无自建规则，均为机场提供，部分Profile的规则集较多，举例脱敏文件见附件；
[profile1.txt](https://github.com/Fndroid/clash_for_windows_pkg/files/10140798/profile1.txt)

**Comment by yi-Xu-0100** [comment]
把 profile 里面的 dns 的 enable 改为 false 再试试

**Comment by PRSJMC** [comment]
> 把 profile 里面的 dns 的 enable 改为 false 再试试

好的，我试试。
另外看了下其他profile有的没有dns这一项，也会出现这个问题。
[profile2.txt](https://github.com/Fndroid/clash_for_windows_pkg/files/10141061/profile2.txt)

**Comment by yi-Xu-0100** [comment]
@PRSJMC 第二个没怎么看出来问题，日志没有问题，只是更新有问题的话，可能订阅有问题？

**Comment by blacker0403** [comment]
> 
你好，请问你这个问题解决了吗

**Comment by PRSJMC** [comment]
> > 
> 
> 你好，请问你这个问题解决了吗

暂时没发现解决办法。目前只留一个profile，问题出现频次会降低，没之前那么频繁。

**Comment by blacker0403** [comment]
> > > 
> > 
> > 
> > 你好，请问你这个问题解决了吗
> 
> 暂时没发现解决办法。目前只留一个profile，问题出现频次会降低，没之前那么频繁。

那行，谢了

**Comment by xqk1** [comment]
之前版本 0.20.9 好使，最近升级到了 0.20.10，就出现了这个问题，然后重新下载 0.20.9，也不行了，好奇到底出现了什么 bug

**Comment by PRSJMC** [comment]
> 之前版本 0.20.9 好使，最近升级到了 0.20.10，就出现了这个问题，然后重新下载 0.20.9，也不行了，好奇到底出现了什么 bug

又试了下，卸载前先把General-Home Directory这个配置文件夹删掉，之后重新装0.20.9，目前这个问题暂未复现。
