### ISSUE TITLE
[Bug]:  proxy-provider 发起的 http 请求中 user_agent异常

### ISSUE THREAD

**Issue by LikeJson** [Fndroid/clash_for_windows_pkg#3764]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.10

### 操作系统

Windows x64

### 系统版本

Win11

### 问题描述

由 proxy-provider 发起的 http 请求 中的 UA 部分为 Go 的默认值，不包含 clash/version 和 自定义 header
![image](https://user-images.githubusercontent.com/85022954/205426251-7bc09141-bbe3-4f57-83bc-cd42eb7bc6af.png)
![image](https://user-images.githubusercontent.com/85022954/205426327-a06351f9-27d5-419a-8e8e-fe31a268c6fe.png)

**Comment by yi-Xu-0100** [comment]
这个应该是 clash core 的请求。

Search or post in the Clash core issue: <https://github.com/Dreamacro/clash/issues>
