### ISSUE TITLE
[Bug]: 软件运行期间更新环境变量后从clash启动代理终端环境变量未更新

### ISSUE THREAD

**Issue by hhhxiao** [Fndroid/clash_for_windows_pkg#3769]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.20

### 操作系统

Windows x64

### 系统版本

windows11 22H2

### 问题描述

如果在软件运行期间更新了环境变量，这时候我从Clash页面启动终端，这个终端并不会刷新环境变量，而是会使用Clash启动时候的环境变量(外加一些代理的)，这就会导致某些命令无法使用，需要重启整个clash才行。

虽然这个场景比较少见，但是还是想问问能不能每次启动代理终端的时候都更新一下环境变量。

### 复现步骤

1. 启动clash
2. 把新的命令路径添加到环境变量
3. 从clash启动代理终端
4. 无法执行新的命令

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
预期行为，建议用TUN Mode接管自带的终端代理
