### ISSUE TITLE
一个errro

### ISSUE THREAD

**Issue by xlighting2017** [Fndroid/clash_for_windows_pkg#377]
如图所示

![image](https://user-images.githubusercontent.com/25970065/72166368-0c5a9d00-3404-11ea-9ba3-7b67a3880275.png)

再来一个清晰版的:
![image](https://user-images.githubusercontent.com/25970065/72166748-c81bcc80-3404-11ea-8d7d-a55b8eeddee1.png)

**Comment by Fndroid** [comment]
文件下载超时（20秒）
