### ISSUE TITLE
[Bug]: 图形界面的连接无法正常进行筛选和排序

### ISSUE THREAD

**Issue by dycwuxing** [Fndroid/clash_for_windows_pkg#3770]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.10

### 操作系统

Windows x64

### 系统版本

Windows10

### 问题描述

如图,近期的几个版本,在"连接"界面下都无法进行选择,或者修改配置文件后无法进行筛选,选择和排序

只能Ctrl+R进行刷新后才能正常工作,菜单一旦切换,就又会失效,win平台和mac平台都有这个问题

内核使用的meta内核

![image](https://user-images.githubusercontent.com/44988562/205540983-39a44d90-772a-478d-8675-9457e4aca0da.png)

![image](https://user-images.githubusercontent.com/44988562/205541071-bd2244fe-b8b8-46b6-ba16-e51dabdda687.png)

### 复现步骤

手工修改config文件并应用后,大概率是无法进行使用的,yaml文件并未报错

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by OXERIS** [comment]
你解决了吗？我也有一样的问题

**Comment by dycwuxing** [comment]
> 你解决了吗？我也有一样的问题

没有，改用clashverge了，对meta内核支持的好些
