### ISSUE TITLE
0.20.10-arm64-linux clash核心版本问题

### ISSUE THREAD

**Issue by xxhk123** [Fndroid/clash_for_windows_pkg#3775]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.10

### 操作系统

Linux

### 系统版本

debian

### 问题描述

升级最新版本后，clash核心版本未更新，还是旧的的版本2022.08.26 Premium而非更新日志中的2022.11.25 Premium

### 复现步骤

更新后未进行任何操作

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by lankylonky22** [comment]
weird bug

**Comment by yi-Xu-0100** [comment]
是否是跨版本太多了

**Comment by xxhk123** [comment]
没有跨版本，就上个版本升级到最新的，安装也是上个版本第一次安装

**Comment by xxhk123** [comment]
不记得还装过别的了😂

**Comment by Fndroid** [comment]
应该是更新核心的脚本有点问题，下个版本修复

**Comment by apktesl** [comment]
下个版本修复

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
