### ISSUE TITLE
[Bug]: 奇怪的TUN问题！请求大家帮助我一下

### ISSUE THREAD

**Issue by Gythiro** [Fndroid/clash_for_windows_pkg#3779]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.10

### 操作系统

Windows x64

### 系统版本

21H2

### 问题描述

在正常使用的状态 一切正常，没有任何问题
但是从前天reinstall servicemode后 出现了奇怪的问题

问题表现为：
在节点测试有效/开启了系统代理/选择了rule or global/ 的情况下
所有的游戏都无法连接网络 log 与 connections中都找不到对应的网络活动
摄像头监控软件也同样和游戏一样 无法链接网络 无log

但是这个时候打开tun之后 一切又正常了 同时可在log中查看到了上述提到软件的网络活动

Tun中的配置为clash默认配置文件
游戏和摄像头监控软件 在同网络下 另外一台设备中可以正常使用

### 复现步骤

N/A

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
没有日志的话，没进 clash ，是不是系统代理没开

**Comment by Gythiro** [comment]
> 没有日志的话，没进 clash ，是不是系统代理没开

开启了系统代理

**Comment by wzy461143268** [comment]
我是用了新的方法重装service之后偶尔会出现service mode状态异常，显示没安装服务，重启客户端就又ok了，暂时找不到复现方法
