### ISSUE TITLE
Hope to add multi language support, such as Chinese Translation

### ISSUE THREAD

**Issue by luoxiao-xy** [Fndroid/clash_for_windows_pkg#378]
Hope to add multi language support, such as Chinese Translation。 
希望增加多语言支持，如中文翻译

There are many users of agent software in mainland China, but most of them don't speak English, which seriously affects the user experience of the software. Therefore, we hope to increase multilingual support. By everyone to help translate, each region's language pack.

中国大陆使用代理软件的用户很多，然而大多数用户并不会英文，这严重影响了软件的用户体验。所以，希望增加多语言能力支持。由大家帮助翻译，各个地区的语言包。

**Comment by Fndroid** [comment]
不考虑
