### ISSUE TITLE
[Bug]: Clash0.20.10点击右上角x时概率性弹出Windows设置界面

### ISSUE THREAD

**Issue by armefaid1** [Fndroid/clash_for_windows_pkg#3788]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.10

### 操作系统

Windows x64

### 系统版本

Windows x64 21H2

### 问题描述

大概从0.19系列开始就经常性地出现开启代理后点击Clash右上角的x后跳出Windows设置界面（就是有着系统、设备、手机、网络和Internet的那个）。有时候就算不开启代理点击右上角x也会跳出同样的界面。虽然不是什么大问题但是看着就是有点烦。已经尝试过用Hitmanpro, malwarebytes以及卡巴斯基查杀过病毒，并没有恶意软件或是病毒存在。所以这里想请问一下这是bug还是我个人笔记本的问题？谢谢。

### 复现步骤

Update代理文件后开启System Proxy，而后在General, Proxies或Profiles任意板块内点击客户端右上角x后概率性跳出Windows设置界面。

### 其他补充

其余均为默认设置。

**Comment by yi-Xu-0100** [comment]
以前也有人报过，没人找到是什么原因。

**Comment by armefaid1** [comment]
> 以前也有人报过，没人找到是什么原因。

感谢解答，这样我就放心了。
