### ISSUE TITLE
[Bug]: 使用clash自带的编辑器，会把原本单行格式的节点列表给重置为多行的样式。

### ISSUE THREAD

**Issue by asdfj2381k** [Fndroid/clash_for_windows_pkg#3791]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

v0.20.10

### 操作系统

Windows x64

### 系统版本

windows7 x64

### 问题描述

现象： 原本很整洁的单行样式被修改为多行了，  多行的很不好看，也不方便编辑。

期待的结果： 编辑后仍然维持单行样式。

![image](https://user-images.githubusercontent.com/56584082/206901293-173a8f53-f7a9-497b-bdfe-2f8211e1fc54.png)

### 复现步骤

相信不用我说什么，大家是能够看明白的。

**Comment by yi-Xu-0100** [comment]
他是自动处理的，不使用编辑器，自己用其他的提前处理好，比如 subsconventer

**Comment by Fndroid** [comment]
内置的是输出为标准yaml格式，如果要保留格式只能文本编辑了
