### ISSUE TITLE
国内用户极多，能否直接挂个中文界面[Feature Request]: 

### ISSUE THREAD

**Issue by Sjun-Lucky** [Fndroid/clash_for_windows_pkg#3796]
### 功能描述

国内用户极多，能否直接挂个中文界面

**Comment by QS0x01** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/999

dupe

**Comment by plerks** [comment]
已经有人做了汉化，需要的话，可以试试[这个](https://github.com/ender-zhao/Clash-for-Windows_Chinese/releases)
