### ISSUE TITLE
[Feature Request]: 请问软件内tun模式如何禁用fake-ip，想改成使用redir-host

### ISSUE THREAD

**Issue by jiangmw** [Fndroid/clash_for_windows_pkg#3797]
### 功能描述

![image](https://user-images.githubusercontent.com/9959819/207215912-2e19e5b5-7bb3-4fd8-99a3-bcfd054d3302.png)
这里没看到编辑选项

**Comment by yi-Xu-0100** [comment]
如果不使用 mixin 自定义的话，可以在 fakeip-filter 里使用 `+.*` 去匹配所有以实现 redir-host。

**Comment by Fndroid** [comment]
不建议用fakeip，实在要用就用mixin
