### ISSUE TITLE
类似于Surge的“增强模式”

### ISSUE THREAD

**Issue by wangsijie** [Fndroid/clash_for_windows_pkg#38]
目前cfw应该是修改系统的Internet 选项中的代理来实现，建议增加“增强模式”，通过创建虚拟网卡的方式实现。因为并不是所有软件都走系统代理（尤其是cmd和powershell）

windows上目前知道的类似软件是proxifier

不过应该挺难搞的，这方面知识严重匮乏，只能求作者加油了

**Comment by Fndroid** [comment]
两者其实不类似，另外不走系统代理的软件大部分都允许自行添加代理。而且，现在不是能和Proxifier搭配使用吗？

**Comment by wangsijie** [comment]
> 两者其实不类似，另外不走系统代理的软件大部分都允许自行添加代理。而且，现在不是能和Proxifier搭配使用吗？

当然能和Proxifier搭配，只是希望能达到Surge的使用体验，这不是本项目追求的嘛。 当然了，我非贡献者，仅提建议

**Comment by GainSury** [comment]
sstap就是类似的模式，后面希望自己贡献相关代码。

**Comment by Fndroid** [comment]
> sstap就是类似的模式，后面希望自己贡献相关代码。

因为sstap不需要处理直连流量，clash的直连流量会在tun/tap里成环
