### ISSUE TITLE
allow lan

### ISSUE THREAD

**Issue by e71828** [Fndroid/clash_for_windows_pkg#380]
新版本 0.8.9 似乎局域网内连接 有一点问题，无法正常连接，而且每次启动cfw时默认状态都是关闭的

**Comment by Fndroid** [comment]
没有改相关的功能，试了一下也可以正常用。检查下是不是代理设置有问题。

启动状态受config.yml影响，要更改可以点击``General -> General YML(Text Mode Edit)``并修改该文件``allow-lan: true``，界面开关只做暂时开启或关闭用
