### ISSUE TITLE
[Bug]: macOS更新到Ventura13.0.1后TUN模式透明代理设备无法上网

### ISSUE THREAD

**Issue by cresstoo** [Fndroid/clash_for_windows_pkg#3800]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.10

### 操作系统

macOS amd64(Intel)

### 系统版本

macOS Ventura 13.0.1

### 问题描述

本人配置：Macbook Pro作主机挂CFW开TUN模式设置软路由，共享梯子给Apple TV等设备。
昨天升级了macOS到最新版Ventura 13.0.1，并且带电脑出门连了一下外面的WIFI。今天早上起来开机发现Apple TV没法上网了（WIFI显示连接打不开内容），梯子在规则、全局模式和DIRECT模式都打不开网络，换其他另外的WIFI直连可以上网。
尝试：
1、换其他静态IP，没用。
2、重启路由器、重启ATV，没用。
3、重装Service Mode，没用。
已检查系统代理是生效了的，TUN好像时好时坏。
<img width="842" alt="截屏2022-12-13 13 31 37" src="https://user-images.githubusercontent.com/2484232/207265546-7555a3fd-c47a-4d47-b9f0-2a2f465b2444.png">
<img width="855" alt="截屏2022-12-13 13 33 30" src="https://user-images.githubusercontent.com/2484232/207265568-03667ddc-e63e-4e4c-8967-f4912daeda75.png">
<img width="860" alt="截屏2022-12-13 16 25 16" src="https://user-images.githubusercontent.com/2484232/207265623-b111971f-3429-49ef-bfb0-5f9fefe03403.png">
<img width="848" alt="截屏2022-12-13 13 50 01" src="https://user-images.githubusercontent.com/2484232/207265644-5ee1fbfb-b616-4075-ab09-c1706c1abd8a.png">
<img width="857" alt="截屏2022-12-13 13 50 33" src="https://user-images.githubusercontent.com/2484232/207265652-db8a0e1f-a668-4c76-b17b-5dc5cfeb56be.png">
<img width="469" alt="截屏2022-12-13 16 20 02" src="https://user-images.githubusercontent.com/2484232/207268693-00019e2f-1d6d-4b1e-8b3d-37e7448f388b.png">
<img width="470" alt="截屏2022-12-13 16 26 59" src="https://user-images.githubusercontent.com/2484232/207268703-8be12f3d-ad41-4008-911b-95ddcf059adf.png">

### 复现步骤

升级macOS至最新版

### 日志文件

<details><summary>logs</summary><p>

```


进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

TUN设置
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback: []
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - apps.apple.com
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53

config.yaml核心配置

port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: rule
log-level: info
external-controller: '0.0.0.0:9090'
secret: ''
dns:
  enable: true
  ipv6: false
  listen: '0.0.0.0:53'
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 'https://223.5.5.5/dns-query'
    - 'https://doh.pub/dns-query'
    - 'tls://dns.rubyfish.cn:853'
  fallback:
    - 'tls://1.0.0.1:853'
    - 'tls://8.8.4.4:853'
    - 'https://doh.opendns.com/dns-query'
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

**Comment by yi-Xu-0100** [comment]
tun 配置中 nameserver 再加点公共 dns 吧

**Comment by cresstoo** [comment]
找到问题了，重启之后IP转发失效了，重新设置解决
