### ISSUE TITLE
[Feature Request]: 添加本地的订阅转换服务

### ISSUE THREAD

**Issue by WritingWithFire** [Fndroid/clash_for_windows_pkg#3801]
### 功能描述

可以在本地将v2ray等等其他格式的订阅链接转化成clash订阅

**Comment by linhongjun** [comment]
转换vmess连接

**Comment by QS0x01** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/3340 

dupe

> https://docs.cfw.lbyczf.com/contents/childprocess.html
> 
> https://github.com/tindy2013/subconverter
