### ISSUE TITLE
[Bug]:更新 v0.20.10版本后 TUN 无法捕捉到 git 流量

### ISSUE THREAD

**Issue by drink-crow** [Fndroid/clash_for_windows_pkg#3803]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.10

### 操作系统

Windows x64

### 系统版本

Windows 11 22H2

### 问题描述

直接不手动设置 git 的代理是能够使用 tun 模式自动切到代理的。更新之后发现不行了（不是特别确定），之前肯定是可以的，因为系统是新装的，各种设置是干净的，代码也能直接拉下来

### 复现步骤

设置系统代理和全局都显示 Connection was reset in connection to github.com:443

手动 git config --global http.proxy 等可以连通。
不设置 git 代理，使用软件配置好的 cmd 进行 git 命令也能连通。
就是不能自动为git使用tun模式，取消 git 全局代理，使用 tun ，git fetch 后在日志中无法找到 github.com有关的链接，手动设置git 代理则能在日志中找到对应的github.com记录

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
先确定 tun mode 启动正常。关系统代理，开浏览器，看看 connection 里是 tun 链接。

**Comment by drink-crow** [comment]
关系统代理后，connection里显示的全是 tun 链接（显示的全是数字ip而不是网站域名，（浏览器经过十几秒等待后）可以正常访问国内网站，外网依旧不行。
然后把 tun mode 切换了成了system，可以了……再切回gvisor，还是可以。git无代理也正常了，connection里显示就是正常的网站地址了。
需要的话这个issue可以关闭了
