### ISSUE TITLE
[Feature Request]: 关于轻量模式的建议

### ISSUE THREAD

**Issue by SESProMax** [Fndroid/clash_for_windows_pkg#3808]
### 功能描述

现在的轻量模式下体验仍有改进空间，具体如下：
1.希望轻量模式默认不显示任务栏图标（希望可以直接关闭相关进程，不要像现在一样只是隐藏图标，现在的隐藏图标选项仍会使图标显示1秒左右）。
2.轻量模式下跟随开机启动功能会导致静默启动失效，希望重构逻辑，在轻量模式下开机直接启动内核，不启动客户端界面。

### 其他内容

并且希望支持选择meta内核

**Comment by yi-Xu-0100** [comment]
1. lightweight mode 是指关闭 CFW 相关进程，只保留 core 。不知道你说的是不是这个。
2. 如果软件启动就直接进入 lightweight mode，后续无法正常进入CFW（逻辑上判断为此模式后，就只保留 core，删除 CFW 进程，以此往复而无法打开CFW界面）
3. 如果开机就想自启 core ,可以用 windows 计划任务实现
4. CFW 现在只支持 premium core。其他的core 自己替换即可，部分特色 core 功能不支持。注意换 core 的话，service mode 也会无法使用，用 tun 的 system 模式或者 allow lan 的时候需要自行解决管理员权限
