### ISSUE TITLE
[Bug]: 启动dns服务器失败

### ISSUE THREAD

**Issue by qkmk** [Fndroid/clash_for_windows_pkg#3809]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.9

### 操作系统

Windows x64

### 系统版本

Windows11 22h2 22621.963

### 问题描述

无法顺利开启代理，在日志中dns服务启动失败
[DNS] start DNS server failed
错误→监听udp 0.0.0.0：5353：bind：only one usage of each socket address (protocol/network address/port)is normally permitted
地址→0.0.0.0：5353

### 复现步骤

在启动的时候就会出现这个，左下角显示已连接但是并不会有数据的交换，在日志中看到这个红色的错误。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

在软件的安装目录找不到logs文件夹，上述内容都是在软件中日志栏里边的

**Comment by yi-Xu-0100** [comment]
日志去 general 界面找 Home Directory 找

去 profiles 看看有没有 dns 键，把里面的 enable 关了。如果不用 tun，把 tun 的enable 也关了

**Comment by qkmk** [comment]
好的谢谢！解决啦！
