### ISSUE TITLE
[Feature Request]: 状态栏显示上传下载速度

### ISSUE THREAD

**Issue by aomsir** [Fndroid/clash_for_windows_pkg#3813]
### 功能描述

<img width="323" alt="image" src="https://user-images.githubusercontent.com/60360782/208245392-444196fc-4c47-4e42-994b-f009fbbbe107.png">
不知道是不是我没找到相关设置，可否把上传下载速度的显示放在这里

**Comment by Varocol** [comment]
有个东西叫做增强托盘
