### ISSUE TITLE
什么时候能支持wireguard协议？[Feature Request]: 

### ISSUE THREAD

**Issue by nxuu** [Fndroid/clash_for_windows_pkg#3816]
### 功能描述

什么时候能支持wireguard协议？

**Comment by yi-Xu-0100** [comment]
core 如果是 2022.11.25 的版本以上（CFW版本 0.20.10 以上应该），应该都行了。

**Comment by lonelydespair** [comment]
> core 如果是 2022.11.25 的版本以上（CFW版本 0.20.10 以上应该），应该都行了。

大佬，请问下具体怎么操作，Linux服务器上已经安装好wireguard了

**Comment by nxuu** [comment]
> core 如果是 2022.11.25 的版本以上（CFW版本 0.20.10 以上应该），应该都行了。

有配置的格式模板么？求救

**Comment by yi-Xu-0100** [comment]
- https://github.com/Dreamacro/clash/wiki/Examples#rule-based-wireguard
- https://github.com/Dreamacro/clash/wiki/Clash-Premium-Features#proxy

**Comment by nxuu** [comment]
> * https://github.com/Dreamacro/clash/wiki/Examples#rule-based-wireguard
> * https://github.com/Dreamacro/clash/wiki/Clash-Premium-Features#proxy

thanks！！！
