### ISSUE TITLE
[Bug]: 安装不了：Window正在查找Clash for Windows.exe.如果想亲自查找文件，请点击“浏览”

### ISSUE THREAD

**Issue by echo860** [Fndroid/clash_for_windows_pkg#3820]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

Clash.for.Windows.Setup.0.20.11.arm64

### 操作系统

Windows x64

### 系统版本

WIN10

### 问题描述

提示如下：

缺少快捷方式
Window正在查找Clash for Windows.exe.如果想亲自查找文件，请点击“浏览”

快捷方式存在问题
该快捷方式所指向的项目Clash for Windows.exe已经更改或移动，累此该快捷方式无法正常工作

基本大小，日期和类型，最相近的匹配是：
D:\Pragrma Files\baidu\BaiduNetdisk\cmd.exe

你要修改快捷方式使其指向目标，还是删除该快捷方式

### 复现步骤

其它

**Comment by WangHaonie** [comment]
把杀毒软件退了试试，我以前遇到过，就是安装程序走完，然后桌面快捷方式就打不开了，然后把360退了重新安装就好了

**Comment by Fndroid** [comment]
下载错了，arm64不是给你的CPU用的

**Comment by JHSY11** [comment]
我遇到相同的问题，请问楼主是如何解决的？

**Comment by JHSY11** [comment]
解决了，谢谢

**Comment by hssy252** [comment]
where？

**Comment by hssy252** [comment]
> > 我也是，咋办的
> > 下载64exe下面的那个exe文件就行

where？

**Comment by JHSY11** [comment]
> 
![8985](https://user-images.githubusercontent.com/121548014/209818456-708a43a2-f41e-4bee-ac72-4ff8ecbbf01b.png)

**Comment by hssy252** [comment]
> > 
> 
> ![8985](https://user-images.githubusercontent.com/121548014/209818456-708a43a2-f41e-4bee-ac72-4ff8ecbbf01b.png)

谢了，为啥下载这么慢

**Comment by JHSY11** [comment]
> 
开加速器
没有的话我也不知道怎么办

**Comment by hssy252** [comment]
> > 
> 
> 开加速器 没有的话我也不知道怎么办

好
