### ISSUE TITLE
[Bug]: bypass通配符匹配不完全

### ISSUE THREAD

**Issue by rambleryu** [Fndroid/clash_for_windows_pkg#3828]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.11

### 操作系统

Windows x64

### 系统版本

win10 pro 21H2

### 问题描述

系统代理下，没有tun，tap，bypass规则始终匹配不全。
![image](https://user-images.githubusercontent.com/76433988/208950224-cf7b65db-224d-48f5-85fb-7f1ead5162b5.png)
已经将所有ubi，ubisoft，uplay放入bypass列表，但仍然会match到final策略代理。
![image](https://user-images.githubusercontent.com/76433988/208950492-37b513cc-b4e0-4222-bc46-eec0c03c106a.png)

![image](https://user-images.githubusercontent.com/76433988/208950013-c6b9bdb0-b769-4099-b2fe-27684adbfe53.png)

### 复现步骤

# UBI
  - "*.ubi.com"
  - "*.ubisoft.com"
  - "*.uplay.com"
  - "public-ubiservices.ubi.com"
  - "ubisoft-uplay-savegames.s3.amazonaws.com"
  - "ubisoft-orbit-savegames.s3.amazonaws.com"
  - "uplaypc-s-ubisoft.cdn.ubi.com"
# Battle.net战网非中国大陆地区游戏下载
  - "level3.blizzard.com" #CDN-Level3
  - "blzddist1-a.akamaihd.net" #CDN-Akamai
  - "blzddistkr1-a.akamaihd.net"
  - "kr.cdn.blizzard.com" #CDN-Blizzard
  - "us.cdn.blizzard.com"
  - "eu.cdn.blizzard.com"
  应该是这两个都会出错，uplay登录和battlenet国际服登录，始终能match到final策略。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```
[2022-12-21-235849.log](https://github.com/Fndroid/clash_for_windows_pkg/files/10279353/2022-12-21-235849.log)

</p></details>

**Comment by Fndroid** [comment]
有可能是UWP不认bypass只读了系统代理

**Comment by rambleryu** [comment]
收到，谢谢大大回复。
