### ISSUE TITLE
[Bug]: Parser功能会错误转义代理名称

### ISSUE THREAD

**Issue by wheat0r** [Fndroid/clash_for_windows_pkg#3829]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.11

### 操作系统

Windows x64

### 系统版本

Windows 11 21H2

### 问题描述

通过parser功能只添加prepend-rules后，在经过parser处理的配置文件中，代理名称中的引号消失，用于标识国家信息的“\U0001F1E8\U0001F1F3”会被转义为“🇨🇳”。
处理后的配置文件在cfw中可以正常使用，当代理和规则信息粘贴进原版clash的配置文件中时，“🇨🇳”会被vim进一步转义为<xxxx><xxxx><xxxx><xxxx>的格式，造成clash无法启动。

### 复现步骤

为一个没有写过parser的profile新增一个parser配置，添加任意一条prepend-rules，确保proxies里的代理名称为"\U0001F1E8\U0001F1F3 名称"的形式，更新这个profile

### 日志文件

原版clash在linux系统上启动时：
<details><summary>logs</summary><p>

12:44:10 FTL [Config] parse config failed error=yaml: invalid Unicode character

</p></details>

**Comment by yi-Xu-0100** [comment]
建议贴出截图，我这里好像没有转义，是不是没加`''`？

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/209104277-ef211e11-11fd-455c-947f-aa2868b484d5.png)

![image](https://user-images.githubusercontent.com/25523606/209104407-e3ef5d43-14cd-40d9-a9f6-13fd65f3ceae.png)

**Comment by Fndroid** [comment]
预期行为，因为与处理器第一步是将这个yaml转换成js的object，如果是你这个加几个规则的需求可以用diff试试

**Comment by wheat0r** [comment]
> 预期行为，因为与处理器第一步是将这个yaml转换成js的object，如果是你这个加几个规则的需求可以用diff试试

ok，这个功能本质上还是按照js运行的
