### ISSUE TITLE
[Bug]: 全屏状态退出Clash后，再次启动窗口位置会变得很怪

### ISSUE THREAD

**Issue by fireattack** [Fndroid/clash_for_windows_pkg#3830]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.11

### 操作系统

Windows x64

### 系统版本

Win10 22H2

### 问题描述

如果在全屏状态退出Clash，下次启动会变成：

* 窗口化
* 大小相当于全屏大小
* 左上坐标在屏幕大约中间的位置（可能是我上次窗口化时的位置）

会导致部分内容显示在屏幕外

### 复现步骤

1. 启动Clash
2. 全屏
3. 保持此状态，直接托盘右键退出
4. 重新启动Clash

### 日志文件

无相关内容

### 其他补充

有搜到一些和窗口位置相关的过往issue，但是没有讲全屏退出导致bug的。

正确的处理方式大概应该是：

1. 只记录窗口化情况下的上次使用大小/位置，**不记录全屏状态下的窗口大小**
2. 如果上次退出时时全屏状态，重启也恢复到全屏状态
3. 如果因为技术限制做不到2，那么启动为窗口化应该恢复为上次*窗口化*时的大小，而不是用全屏的尺寸来窗口化

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases

**Comment by fireattack** [comment]
现在有个别的bug，有时候启动后已经是窗口化状态，但是右上角按钮仍显示为“窗口化”（而非“最大化”），且点击无效

得手动拖拽窗口边框改变一次大小之后才能恢复。
