### ISSUE TITLE
延迟检测使用其他网址必超时[Bug]: 

### ISSUE THREAD

**Issue by FFDVDGD** [Fndroid/clash_for_windows_pkg#3831]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.11

### 操作系统

Windows x64

### 系统版本

win11

### 问题描述

延迟测试URL无论填什么包括baidu.com这些不远翻的网站全部超时，只有默认的网址可用

### 复现步骤

延迟测试URL里填入baidu.com,测试节点延迟，全部超时

### 日志文件

<details><summary>logs</summary><p>

```
抱歉，在安装目录下没有发现log文件夹或名为log的文件，请问需要怎样获取log
```

</p></details>

**Comment by Fndroid** [comment]
截图看看你填的什么

**Comment by FFDVDGD** [comment]
![image](https://user-images.githubusercontent.com/82321430/209689368-5b816dfd-5074-4fb7-ab69-74d756d17268.png)
我用了一个汉化插件，不过英文原版也是超时，之前试过
