### ISSUE TITLE
[Bug]: 求助  无法安装服务模式

### ISSUE THREAD

**Issue by 1409109991** [Fndroid/clash_for_windows_pkg#3838]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.7

### 操作系统

Windows x64

### 系统版本

win 11

### 问题描述

![image](https://user-images.githubusercontent.com/79674967/209462751-76862bf2-5779-4cd9-8935-ecd361f4719f.png)
我也尝试删除Clash for Windows Service文件夹后在安装，但是还是无法安装成功。

### 复现步骤

无

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

无

**Comment by redwhale-q** [comment]
同样的问题

**Comment by xlc520** [comment]
在`C:\Program Files`目录下，找到`Clash for Windows Service`文件，把他删除，在重新进软件安装服务就可以了。这是个文件，不是目录，没有后缀。
