### ISSUE TITLE
[Bug]: Fail to install service 

### ISSUE THREAD

**Issue by Airuop** [Fndroid/clash_for_windows_pkg#3839]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.11

### 操作系统

Windows x64

### 系统版本

windows 11

### 问题描述

App cant install  schtasks service 
![image](https://user-images.githubusercontent.com/114985398/209474743-8ef92486-5ac8-4293-bda8-85b3256c1255.png)

### 复现步骤

1. i try for reload app but don't work 
2. after step 1 i try to clean reinstall clash for solve this problem but don't work

**Comment by Fndroid** [comment]
try removing "C:\Program Files\Clash for Windows Service" and install again
