### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by amirrammari** [Fndroid/clash_for_windows_pkg#384]
Hello,
Has this app been released for Android OS either?

**Comment by Fndroid** [comment]
> Hello,
> Has this app been released for Android OS either?

No, just Windows.

**Comment by amirrammari** [comment]
Is this the official app?
https://play.google.com/store/apps/details?id=com.github.kr328.clash&hl=en_US

**Comment by Fndroid** [comment]
> Is this the official app?
> https://play.google.com/store/apps/details?id=com.github.kr328.clash&hl=en_US

This app and Clash for Windows are GUIs based on Clash core. Clash don’t have any official developer team. We just developers that love Clash and be willing to build GUI for it.

**Comment by amirrammari** [comment]
Ok, thank you for your response.
