### ISSUE TITLE
[Feature Request]: 更改TCP最长连接时间

### ISSUE THREAD

**Issue by WindowsMEMZ** [Fndroid/clash_for_windows_pkg#3840]
### 功能描述

如题，Clash似乎没有办法更改TCP最大连接时间，始终限制为120秒

**Comment by yi-Xu-0100** [comment]
Search or post in the Clash core issue: <https://github.com/Dreamacro/clash/issues>

**Comment by Fndroid** [comment]
clash core issue, refer: https://github.com/Dreamacro/clash/issues
