### ISSUE TITLE
[Bug]: 无法上网，大部分代理是超时的，剩下的那部分延时特别严重！

### ISSUE THREAD

**Issue by EashShow** [Fndroid/clash_for_windows_pkg#3841]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

v 0.20.11

### 操作系统

Windows x64

### 系统版本

Windows 10 X64

### 问题描述

无法上网，大部分代理连接超时，剩下一部分代码延时特别严重，几百个毫秒，甚至1-2秒的延时。
根本无法上网！
在你们网站上提交工单，没有任何回应。
你们微信客服，没有任何回应。
哎。。。

### 复现步骤

从来无法上网，不用复现。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
@EashShow 不知道你说的什么网站，建议找服务供应商，这只是个软件，不提供服务。

**Comment by EashShow** [comment]
就是代理不通。
比如谷歌，都一直打不开呢。

**Comment by EashShow** [comment]
我千兆带宽，上网易、新浪什么的，速度极快的。

**Comment by EashShow** [comment]
![image](https://user-images.githubusercontent.com/42777817/209499413-6b6dc93c-bc1c-4bf0-83bb-d08ca5ca4a59.png)

**Comment by EashShow** [comment]
@yi-Xu-0100 老兄，这咋搞？

**Comment by ougakuka** [comment]
你买的机场有问题，节点连不上
去找卖你这个机场的老板或客服
和这个软件没有关系
和你千兆带宽访问网易新浪很快也没有关系

**Comment by EashShow** [comment]
@ougakuka 那帮我把这VPN退费了吧？
我这电信的宽带其它用着都挺好的，买了一年，花了大几千。

**Comment by Fndroid** [comment]
这是免费软件，你节点哪里买就找哪里

**Comment by SilenceXK** [comment]
我连了节点78ms但就是上不了网，现在饿着肚子整这玩意...
