### ISSUE TITLE
[Bug]: 开启clash规则代理，编辑好规则的情况，进行steam下载速度很低

### ISSUE THREAD

**Issue by Varyooy** [Fndroid/clash_for_windows_pkg#3843]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.10

### 操作系统

Windows x64

### 系统版本

windows11

### 问题描述

启用代理之后，steam下载速度很慢，已使用预处理编辑好steam下载的相关规则，使用的是全球直连，关闭代理后，下载可以跑满速。
![规则](https://user-images.githubusercontent.com/115435538/209598020-ef3b6836-6b85-434e-b994-1d276154d629.png)
![代理下载](https://user-images.githubusercontent.com/115435538/209598049-630e72bf-2ddf-47a4-b45b-e4116ceab9e6.png)

下载相关的连接详情都是通过规则 DOMAIN-SUFFIX,steamcontent.com,全球直连来连接的
![连接详情](https://user-images.githubusercontent.com/115435538/209598316-7a02ae57-0b3e-4b78-9f8b-529913d1ebc4.png)

不使用代理之后，可以跑满速
![不代理下载](https://user-images.githubusercontent.com/115435538/209598071-cbcd4bed-dd05-497a-81b1-5fc2a19754cf.png)

### 复现步骤

如截图所示进行规则配置，再进行下载操作即可复现

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Varyooy** [comment]
更新，当去掉clash API的小盾牌后，速度上升部分，但未达到宽带满速，且十分不稳定
![去除api小绿盾](https://user-images.githubusercontent.com/115435538/209599034-acedf649-2100-4a92-9a39-a16fca188b28.png)

**Comment by Varyooy** [comment]
去掉API小盾牌以后，连接进程中不再出现steamcontent.com的direct连接详情

**Comment by Varyooy** [comment]
求助各位大佬这个是什么问题，问题尚未解决

**Comment by Glucy-2** [comment]
sgp明显是连到新加坡了，目前steam似乎通过DNS解析来选择节点，我暂时的解决方法是关闭代理打开steam，开始下载后再打开steam

**Comment by Varyooy** [comment]
> sgp明显是连到新加坡了，目前steam似乎通过DNS解析来选择节点，我暂时的解决方法是关闭代理打开steam，开始下载后再打开代理

但是我看截图里面，sgp走的DIRECT呢，所以就很奇怪，反正关掉代理倒是确实能正常速度，甚至我家里的路由器是加了shellClash的，但是同一个机场的规则，路由器上就不会把这个DIRECT限速，但是CFW的DIRECT就是限速的

**Comment by Varyooy** [comment]
> sgp明显是连到新加坡了，目前steam似乎通过DNS解析来选择节点，我暂时的解决方法是关闭代理打开steam，开始下载后再打开代理

应该没有连到新加坡，我在梯子网站看了，我的使用流量并没有变

**Comment by zzzerow** [comment]
我也遇到了相同的情况，直连使用speedtest.cn测速和完全关掉代理测速差别很大

**Comment by Varyooy** [comment]
> 

我上次仔细分析了，大概的原因是steam分析你登录IP，给你分配了国外，然后下载时默认走国外离你最近的下载点，然后你从国内直连那边的下载点导致的速度慢，但是你说的这种情况，还是和cfw的直连模式有关系

**Comment by Varyooy** [comment]
> 我也遇到了相同的情况，直连使用speedtest.cn测速和完全关掉代理测速差别很大

我上次仔细分析了，大概的原因是steam分析你登录IP，给你分配了国外，然后下载时默认走国外离你最近的下载点，然后你从国内直连那边的下载点导致的速度慢，但是你说的这种情况，还是和cfw的直连模式有关系
