### ISSUE TITLE
[Feature Request]: 允许关闭socks和http服务器

### ISSUE THREAD

**Issue by t4rf9** [Fndroid/clash_for_windows_pkg#3847]
### 功能描述

目前的cfw中，port必须配置一个有意义的值，使得config.yaml中存在一个有效的mixed-port选项。
然而，对于仅使用tun模式等其他代理方式而不使用socks或http代理服务器的用户，socks或http代理服务器就无效占用着资源。
希望可以引入一个不填mixed-port的选项，效果是移除config.yaml中的mixed-port、socks-port、port，避免资源浪费。

**Comment by Fndroid** [comment]
当前版本有个bug导致Port设置成0会无法启动，下个版本修复之后，可以直接把mixed-port设置成0就不会监听了

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
