### ISSUE TITLE
What Different Global>Direct mode and Direct mode?

### ISSUE THREAD

**Issue by amirrammari** [Fndroid/clash_for_windows_pkg#385]
![image](https://user-images.githubusercontent.com/23485114/72485753-fdb62080-381d-11ea-86c4-a3ba981bf5d3.png)
What is the difference between Mode 1 and Mode 2?

**Comment by Fndroid** [comment]
``GLOBAL`` is a proxy group that contains all proxy/proxy group.

``DIRECT`` is one of the default proxy groups in Clash.

Global(GLOBAL>DIRECT) is equal to Direct actually.

**Comment by amirrammari** [comment]
Ok, Thanks.
