### ISSUE TITLE
[Bug]: 在 Profiles 页面编辑完 Parsers 后会跳转到 Settings 页面

### ISSUE THREAD

**Issue by WangHaonie** [Fndroid/clash_for_windows_pkg#3855]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.12

### 操作系统

Windows x64

### 系统版本

Windows 10 Pro 22H2 x64 (19045.2364)

### 问题描述

能否让在 Profiles 页面编辑完 Parsers 后就保持在 Profiles 页面

### 复现步骤

1. 在 Profiles 页面选择一个配置文件，右键点击 Parsers。<br>![image](https://user-images.githubusercontent.com/68315280/210131423-b7ecc263-9b71-423f-92e0-7f6ed822398a.png)
2. 点击 Edit Parsers<br>![image](https://user-images.githubusercontent.com/68315280/210131456-2e6d157d-3f8f-43fb-91d1-539c30633e20.png)
3. 可以看到当编辑器打开时跳转到 Settings 了。<br>![image](https://user-images.githubusercontent.com/68315280/210131503-a44eb00e-3edb-46dd-af96-a5afa0b74f26.png)

**Comment by Fndroid** [comment]
其实就是这么设计的，因为编辑方式有多种所以才跳转的，不过确实来回跳转不方便，下个版本这个地方调整为用内部编辑器编辑

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
