### ISSUE TITLE
[Feature Request]:Vless Support 

### ISSUE THREAD

**Issue by norangit** [Fndroid/clash_for_windows_pkg#3857]
### 功能描述

刚发现有个 Clash Meta - https://github.com/MetaCubeX/Clash.Meta, 而且有2个基于clash的客户端，不过他们的客户端做的时间不长，没有这个强大，不知道本客户端有没有计划把 Meta 内核嵌入以支持 Vless 呢

**Comment by Fndroid** [comment]
没有
