### ISSUE TITLE
关于 Proxies 和 Profiles 的困惑

### ISSUE THREAD

**Issue by eromoe** [Fndroid/clash_for_windows_pkg#3859]
https://docs.cfw.lbyczf.com/contents/ui/proxies.html#%E5%88%87%E6%8D%A2%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F

文档里写着
```
Clash 共有三种工作模式：

全局（Global）：所有请求直接发往代理服务器
规则（Rule）：所有请求根据配置文件规则进行分流
直连（Direct）：所有请求直接发往目的地
切换不同模式时，对应的节点列表会对应变化
```

我目前是配置为：
- 一个proxy ，一个proxy group 
- 使用 rules  https://github.com/Loyalsoldier/clash-rules  
- 创建了一个黑名单Profile 和 一个白名单的 Profile 

比如我目前选择了白名单Profile 
我发现Proxies 里不管选择 Global 还是 Rule  访问 https://www.ip.cn/  都显示的是本机ip
也就是说明Global 情况下 rule 也生效了！

这导致我必须建一个没有rule set 的 Profile 来实现真正的全局模式

**Comment by yi-Xu-0100** [comment]
@eromoe 去 connections 里看走的什么规则。如果有规则，关闭该链接重新试下，可能是链接没断。建议截图看下 rule 分别在 global 和 rule 的情况下的结果。

**Comment by eromoe** [comment]
测试了，没有效果   global 还是显示本机IP

**Comment by eromoe** [comment]
OH, 用链接匹配看了下确实是这样。
