### ISSUE TITLE
萌新求助，这个东西是怎么使用的？

### ISSUE THREAD

**Issue by wwweeer** [Fndroid/clash_for_windows_pkg#3865]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

1

### 操作系统

Windows x64

### 系统版本

1

### 问题描述

萌新求助，这个东西是怎么使用的？

### 复现步骤

萌新求助，这个东西是怎么使用的？

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by QS0x01** [comment]
A. 搜索引擎
B. 金钱
C. 洗洗睡
