### ISSUE TITLE
[Bug]: deepin系统无法使用该软件，请问该软件支持deepin系统吗

### ISSUE THREAD

**Issue by tongchangD** [Fndroid/clash_for_windows_pkg#3866]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.16 0.20.11等多版本均无解

### 操作系统

Windows x64

### 系统版本

deepin 20.7.1

### 问题描述

无法上外网，如下图所示，  

![image](https://user-images.githubusercontent.com/36293393/211140212-31fc7b17-4115-4442-ad9f-7e727ac1486a.png)  

左上角没有网络速度，也没有跳动

### 复现步骤

您好，
我在新电脑上安装好了clash，但却无法使用，故前来寻求帮助，虚心求教。如下图所示，我已经下载好网络订阅链接。

![image](https://user-images.githubusercontent.com/36293393/211140250-89956c95-cfe5-4b2f-96f3-1326ccdb6134.png)

然后在proxies 界面选择好节点，如下图所示：

![image](https://user-images.githubusercontent.com/36293393/211140251-fcadc7ba-936e-4f92-8663-02f9fdc8d794.png)

最后在general 界面勾选以下链接，但是依旧不能访问谷歌，或者说左上角的网络数未跳动，如下图所示，请问这可能是什么原因导致的。
![image](https://user-images.githubusercontent.com/36293393/211140256-0dba213a-a762-4c52-b819-de8a17b7e858.png)

唯一的解释可能是GeoIP DataBase 与世界真实时间对不上，请问该如何对上。
其部分log日志如下图所示
![image](https://user-images.githubusercontent.com/36293393/211140262-2b0ccf9f-ba6b-463d-add7-04845f2b3180.png)

求教，

祝好

### 日志文件

<details><summary>logs</summary><p>

```
time="2023-01-07T15:55:08+08:00" level=info msg="RESTful API listening at: 127.0.0.1:45657"
time="2023-01-07T15:55:08+08:00" level=info msg="Start initial compatible provider CroLAX"
time="2023-01-07T15:55:09+08:00" level=warning msg="[CacheFile] can't open cache file: timeout"
time="2023-01-07T15:55:09+08:00" level=error msg="Start Mixed(http+socks) server error: listen tcp 127.0.0.1:7890: bind: address already in use"
time="2023-01-07T15:55:14+08:00" level=info msg="Start initial compatible provider CroLAX"
time="2023-01-07T15:55:25+08:00" level=info msg="Start initial compatible provider CroLAX"
time="2023-01-07T15:55:25+08:00" level=error msg="Start Tun interface error: operation not permitted"
```

</p></details>

**Comment by yi-Xu-0100** [comment]
自行设置系统代理。

**Comment by tongchangD** [comment]
> linux 需要自行设置系统代理。

请问如何自行设置系统代理？

**Comment by yi-Xu-0100** [comment]
@tongchangD https://www.baidu.com/s?wd=deepin%20%E8%AE%BE%E7%BD%AE%E7%B3%BB%E7%BB%9F%E4%BB%A3%E7%90%86

**Comment by tongchangD** [comment]
> @tongchangD https://www.baidu.com/s?wd=deepin%20%E8%AE%BE%E7%BD%AE%E7%B3%BB%E7%BB%9F%E4%BB%A3%E7%90%86

搜索，尝试了，发现无用才到这里提issues，请问是否有你们这种官方的教程

**Comment by yi-Xu-0100** [comment]
@tongchangD 把你设置的结果，和设置时的 CFW 的 general 界面截图给出了。主要看端口号对不对吧，还有就是注意浏览器的设置对不对，需不需要单独设置啥的。linux 类太多，没有官方的，一般都是百度解决吧，或者看有没谁用过，简单介绍下

**Comment by tongchangD** [comment]
@yi-Xu-0100  谢谢。我再用这种方案就可以了
1.在deepin自带的应用商店搜索clash并下载。
2.打开General选项，Port设置成7890，Allow LAN可以打开，Start with Linux可以打开。
3.在Profiles选项中粘贴获得的订阅链接，点击Download，可以看到导入的新设置，选择这个设置。
4.可以去Proxies中选择节点。
5.在你的计算机中选择系统代理--手动-----HTTP代理设为127.0.0.1，端口7890----HTTPS代理设为127.0.0.1，端口7890（两个都要和前面的Port一样）----保存。
如果不行重启电脑就好了

**Comment by 0000000O** [comment]
> @yi-Xu-0100 谢谢。我再用这种方案就可以了 1.在deepin自带的应用商店搜索clash并下载。 2.打开General选项，Port设置成7890，Allow LAN可以打开，Start with Linux可以打开。 3.在Profiles选项中粘贴获得的订阅链接，点击Download，可以看到导入的新设置，选择这个设置。 4.可以去Proxies中选择节点。 5.在你的计算机中选择系统代理--手动-----HTTP代理设为127.0.0.1，端口7890----HTTPS代理设为127.0.0.1，端口7890（两个都要和前面的Port一样）----保存。 如果不行重启电脑就好了

我深感震惊，deepin官方的商店里面有clash下载吗。。？

**Comment by yi-Xu-0100** [comment]
@0000000O 没用过，不知道。

**Comment by tongchangD** [comment]
> > @yi-Xu-0100 谢谢。我再用这种方案就可以了 1.在deepin自带的应用商店搜索clash并下载。 2.打开General选项，Port设置成7890，Allow LAN可以打开，Start with Linux可以打开。 3.在Profiles选项中粘贴获得的订阅链接，点击Download，可以看到导入的新设置，选择这个设置。 4.可以去Proxies中选择节点。 5.在你的计算机中选择系统代理--手动-----HTTP代理设为127.0.0.1，端口7890----HTTPS代理设为127.0.0.1，端口7890（两个都要和前面的Port一样）----保存。 如果不行重启电脑就好了
> 
> 我深感震惊，deepin官方的商店里面有clash下载吗。。？

有的

**Comment by tongchangD** [comment]
今儿重装系统后发现没有了
