### ISSUE TITLE
[Feature Request]: 延迟测速全部超时timeout

### ISSUE THREAD

**Issue by EliDoves** [Fndroid/clash_for_windows_pkg#3870]
### 功能描述

- 节点是自己用机场提供的api转换的订阅连接

1. 在直接引用了节点的策略组里进行延迟测试全部会timeout
![image](https://user-images.githubusercontent.com/51412618/211183977-b876923b-5064-43ae-83c1-94ee6cf43dbd.png)

 2. 如果将1中直接引用了订阅节点的策略组引用到另一个策略组中，则可以在该策略组中对被引用的策略组进行延迟测试。
![image](https://user-images.githubusercontent.com/51412618/211183952-1df7e8f0-5295-4c64-bf6c-44d7df320d9f.png)

- 而且尽管测试timeout，但是节点使用完全没问题，排除节点的问题，如果直接使用机场的订阅链接就不会timeout，机场配置文件dns是true，我自己配置的设置和机场是一样的。怀疑问题还是出在了转换连接上面，但不知道该怎么解决，请大佬们解惑

**Comment by yi-Xu-0100** [comment]
看看转换订阅的dns配置或者 tun 配置什么的。

**Comment by EliDoves** [comment]
> 看看转换订阅的dns配置或者 tun 配置什么的。

转换订阅都是输出的是node list，好像和配置TUN模式无关，我专门配置了两个文件一个开了tun一个没开，都是timeout

**Comment by yi-Xu-0100** [comment]
哦，你是转换后给provider是吧，那比对下节点转换后有没有区别，可能少些参数什么的。

**Comment by EliDoves** [comment]
> 哦，你是转换后给provider是吧，那比对下节点转换后有没有区别，可能少些参数什么的。

是的，对比了一下参数都是一样的😥

**Comment by EliDoves** [comment]
已经解决了，Proxy-Providers 下面要加一个url: http://www.gstatic.com/generate_204
