### ISSUE TITLE
新手求助，服务模式无法安装或卸载，导致TUN模式无法启用

### ISSUE THREAD

**Issue by chatseeon** [Fndroid/clash_for_windows_pkg#3874]
问题发生的经过：昨天家里突然断电，台式上的clash当时已经成功安装服务模式并成功开启TUN模式。待恢复供电后，发现服务模式无法安装或卸载，旁边的地球标识由绿变灰。TUN模式按钮仍可以打开，但并无效果。系统代理仍可用。

系统：windows10 20H2 19042.546

clash版本：0.20.12

ps:尝试重装clash后仍然无效，希望各位大佬能帮忙解决这个问题，不胜感激。
![屏幕截图 2023-01-09 120623](https://user-images.githubusercontent.com/107085673/211240303-1299c2f4-b1eb-4d93-a945-7e1a8ce2b9d5.jpg)
![屏幕截图 2023-01-09 120702](https://user-images.githubusercontent.com/107085673/211240308-7ea7dda2-4b81-49f8-908a-4d700963e283.jpg)
![屏幕截图 2023-01-09 120940](https://user-images.githubusercontent.com/107085673/211240314-1cbf4c89-07d7-431a-aba6-743c9fb60906.jpg)
![屏幕截图 2023-01-09 121044](https://user-images.githubusercontent.com/1
![屏幕截图 2023-01-09 121448](https://user-images.githubusercontent.com/107085673/211240322-7131174b-a0b8-485c-afbf-842b0e68f0c6.jpg)
07085673/211240316-bd8956cc-3aaa-4b84-b620-b8440a2bf763.jpg)

**Comment by chatseeon** [comment]
![屏幕截图 2023-01-09 121044](https://user-images.githubusercontent.com/107085673/211240608-5ff1b10d-db9e-4b25-8a79-2cf43bdb7628.jpg)
补张图

**Comment by xlc520** [comment]
在`C:\Program Files`目录下，找到`Clash for Windows Service`文件，把他删除，在重新进软件安装服务就可以了。这是个文件，不是目录，没有后缀。

**Comment by xlc520** [comment]
在`C:\Program Files`目录下，找到`Clash for Windows Service`文件，把他删除，在重新进软件安装服务就可以了。这是个文件，不是目录，没有后缀。

**Comment by eboxatGH** [comment]
哈哈，本人新手，之前也是碰到同样难题，但问题产生的原因有所不同，是WIN10，2个Microsoft帐户/用户，在第一个帐户成功开启TUN模式之后，尝试在第二个帐户开启TUN模式，然后，TUN模式出现上述崩溃现象，2个帐户的TUN模式都崩溃了。自己后来尝试[Service Mode 无法安装](https://docs.cfw.lbyczf.com/contents/questions.html#service-mode-%E6%97%A0%E6%B3%95%E5%AE%89%E8%A3%85)方法，无法新建 Clash for Windows Service 目录，被提示：同名文件夹/文件夹已经存在，然后发现，在C:\Program Files目录下，有一个隐藏的Clash for Windows Service文件，将其删除，即可正常操作相关步骤，然后TUN模式成功启用。
本人新手，对这个社区也比较陌生，在此斗胆建议，请有关人士考虑，在[Service Mode 无法安装](https://docs.cfw.lbyczf.com/contents/questions.html#service-mode-%E6%97%A0%E6%B3%95%E5%AE%89%E8%A3%85)中，补充这个可能的问题症状及解决对策。
谢谢！

**Comment by yifanlong** [comment]
![IMG20230203191718.jpg](https://user-images.githubusercontent.com/100976327/216591180-027dd379-de24-4c10-9594-7d9e676d2671.jpg)

谁能教教我😭😭

**Comment by eboxatGH** [comment]
进入 C:\Program Files 目录，设置 显示隐藏文件：尝试在该目录中，找到 一个 名为 Clash for Windows Service 的 隐藏文件。如果你能找它到并且删除它，然后，就应该可以重新顺利安装。如果你找不到那个隐藏文件，我也没有更好的建议了，你再请教高手。供你参考。

**Comment by yifanlong** [comment]
> 进入 C:\Program Files 目录，设置 显示隐藏文件：尝试在该目录中，找到 一个 名为 Clash for Windows Service 的 隐藏文件。如果你能找它到并且删除它，然后，就应该可以重新顺利安装。如果你找不到那个隐藏文件，我也没有更好的建议了，你再请教高手。供你参考。

谢谢！

**Comment by Ray88991234** [comment]
> 已打开C盘隐藏文件，依然找不到 Clash for Windows Service

**Comment by brib424** [comment]
![5591cab2d5d4443f8878d8a319f8591](https://user-images.githubusercontent.com/111207803/218493216-41a9ce02-0369-4d31-aede-7a6a8eed07a4.png)
我的这个就一直提示安装不了，但是我能打开tun模式，我这个又是什么原因呢，有大佬可以教一下吗，非常感谢

**Comment by yorshka0** [comment]
> 在`C:\Program Files`目录下，找到`Clash for Windows Service`文件，把他删除，在重新进软件安装服务就可以了。这是个文件，不是目录，没有后缀。

非常感谢 ！！！ ==看晚上的说词 我还以为是 在服务里面找尼

**Comment by CloudSail1** [comment]
> 



> 进入 C:\Program Files 目录，设置 显示隐藏文件：尝试在该目录中，找到 一个 名为 Clash for Windows Service 的 隐藏文件。如果你能找它到并且删除它，然后，就应该可以重新顺利安装。如果你找不到那个隐藏文件，我也没有更好的建议了，你再请教高手。供你参考。

我现在的clash版本是0.20.28，我并没有在C:\Program Files里发现没有后缀的clash for windows service，但我在C:\Windows\System32\Tasks里发现了这个文件，并且删除它之后打开clash安装服务，已经正常了。并且新的clash for windows service还是在tasks文件夹里，可能新版换了个位置吗？至少问题解决了。

**Comment by G6700SylveonM** [comment]
win11家庭版中文版无法安装Service Mode 提示 User did not grant permission. Force Quit后尝试使用管理员身份运行，仍提示此错误。而且找不到clash for windows service这个文件

**Comment by G6700SylveonM** [comment]
win11家庭版中文版无法安装Service Mode 提示 User did not grant permission. Force Quit后尝试使用管理员身份运行，仍提示此错误。而且找不到clash for windows service这个文件，怎么办？

**Comment by G6700SylveonM** [comment]
新买的电脑win11家庭版中文版无法安装Service Mode 提示 User did not grant permission. Force Quit后尝试使用管理员身份运行，仍提示此错误。显示隐藏文件也找不到clash for windows service这个文件，怎么办？

**Comment by CloudSail1** [comment]
> 新买的电脑win11家庭版中文版无法安装Service Mode 提示 User did not grant permission. Force Quit后尝试使用管理员身份运行，仍提示此错误。显示隐藏文件也找不到clash for windows service这个文件，怎么办？

尝试此文档中提供的解决方法，手动安装。
https://docs.cfw.lbyczf.com/contents/questions.html#service-mode-%E6%97%A0%E6%B3%95%E5%AE%89%E8%A3%85
