### ISSUE TITLE
[Bug]: Ubuntu端clash端口port号退出重新登录后显示为0，无法正常连接

### ISSUE THREAD

**Issue by allennyuan1210** [Fndroid/clash_for_windows_pkg#3878]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.12

### 操作系统

Linux

### 系统版本

ubuntu 22.04.1 LTS

### 问题描述

我在使用虚拟机上的ubuntu系统登陆clash for windows时，第一次会显示port端口号7890，但退出重新登陆后端口号就一直是0。ubuntu需要在设置中选择手动打开代理，输入端口号来使用clash，所以退出重新登陆后就无法正常使用。请问如何解决，谢谢。

### 复现步骤

进入ubuntu系统，进入clash for windows安装文件夹，打开cfw，进入dashboard后正常显示port号。退出clash for windows并重新进入，会发现port号变成0。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
linux 上有个 bug 会导致已启动的核心未能正确关闭，下次打开的时候端口因为被占用变成 0，这个问题下个版本会修复

暂时可以用 `pkill -9 clash-linux` 这个命令手动关闭之前的核心

**Comment by allennyuan1210** [comment]
好的，请尽快修复谢谢
