### ISSUE TITLE
[Bug]: 今天Proxies项下不显示节点，无法使用软件，昨天还一切正常，已经使用相当长时间

### ISSUE THREAD

**Issue by bitdarkspirit** [Fndroid/clash_for_windows_pkg#3879]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.12

### 操作系统

Windows x64

### 系统版本

Windows 10 专业版 21H2

### 问题描述

今天Proxies项下不显示节点，无法使用软件，昨天还一切正常，已经使用相当长时间。同一订阅节点在Shadowrocket上同一时间使用正常。望查验下问题，谢谢

### 复现步骤

打开clash，更新Profiles,点击Proxies不显示节点，无法使用。卸载软件，重新官方安装最新版，打开clash，重新Profiles添加订阅节点URL,显示sucess,点击Proxies不显示节点，只显示一项Debug,点击显示Timeout。之前使用过相当长时间和多个版本，昨日使用正常，今天突然出现这问题，同一订阅节点在Shadowrocket使用正常，望排查，谢谢

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
你确定profile里有节点么

**Comment by bitdarkspirit** [comment]
![image](https://user-images.githubusercontent.com/116473655/211269917-355e9804-2028-4f39-9606-0b350a9d488c.png)

**Comment by bitdarkspirit** [comment]
> 你确定profile里有节点么
![image](https://user-images.githubusercontent.com/116473655/211270138-48523cdb-21cc-413c-88eb-af98a932f8cd.png)
![image](https://user-images.githubusercontent.com/116473655/211270186-097dae5c-9de6-466b-86f7-156e6d612bd3.png)
![ab4ee9c6ffc3c8ae5cb550e7edb7d9f](https://user-images.githubusercontent.com/116473655/211270349-55aba52d-c924-46bd-b99d-577ec5c0317b.jpg)
截图如上，有节点，同一URL订阅在Shadowrocket能使用，我这样使用已经相当长一段时间，历经多个版本。在clash profie里有节点，但proxies里看不到节点，软件用不了，昨天还一切正常，我正常使用，没动什么。辛苦，麻烦查验下问题，谢谢

**Comment by bitdarkspirit** [comment]
> 你确定profile里有节点么
![image](https://user-images.githubusercontent.com/116473655/211272163-e87daf78-179e-451a-976d-aeeb1e35563a.png)
![image](https://user-images.githubusercontent.com/116473655/211272250-ff5c9a09-a97a-4ec3-85e9-10f6f4e15c65.png)
![image](https://user-images.githubusercontent.com/116473655/211272350-407fdf3d-06ef-4c09-ae12-973976e92f2f.png)
截图如上，有节点，同一URL订阅在Shadowrocket能使用，我这样使用已经相当长一段时间，历经多个版本。在clash profie里有节点，但proxies里看不到节点，软件用不了，昨天还一切正常，我正常使用，没动什么。辛苦，麻烦查验下问题，谢谢

**Comment by bitdarkspirit** [comment]
> 你确定profile里有节点么

![image](https://user-images.githubusercontent.com/116473655/211272685-b47a1b0f-8add-4742-b7d3-386da4f008c1.png)
![image](https://user-images.githubusercontent.com/116473655/211272735-2d3d3352-cd82-4c24-a6fb-7e7bc865f48f.png)
![image](https://user-images.githubusercontent.com/116473655/211272859-d2b09f08-a2f8-49de-9eea-a235e559417e.png)
截图如上，有节点，同一URL订阅在Shadowrocket能使用，我这样使用已经相当长一段时间，历经多个版本。在clash profie里有节点，但proxies里看不到节点，软件用不了，昨天还一切正常，我正常使用，没动什么。辛苦，麻烦查验下问题，谢谢

**Comment by Fndroid** [comment]
你也没有选中你的profile啊

**Comment by HaFred** [comment]
> > 你确定profile里有节点么
> 
> ![image](https://user-images.githubusercontent.com/116473655/211272685-b47a1b0f-8add-4742-b7d3-386da4f008c1.png) ![image](https://user-images.githubusercontent.com/116473655/211272735-2d3d3352-cd82-4c24-a6fb-7e7bc865f48f.png) ![image](https://user-images.githubusercontent.com/116473655/211272859-d2b09f08-a2f8-49de-9eea-a235e559417e.png) 截图如上，有节点，同一URL订阅在Shadowrocket能使用，我这样使用已经相当长一段时间，历经多个版本。在clash profie里有节点，但proxies里看不到节点，软件用不了，昨天还一切正常，我正常使用，没动什么。辛苦，麻烦查验下问题，谢谢

麻烦能告知一下是哪个vpn网站吗？我也想购买一个试用下，谢谢。

**Comment by bitdarkspirit** [comment]
> 你也没有选中你的profile啊

非常感谢你的回复，问题已找到并解决，更新的节点列表出现重复名导致没有选定，进入编辑后稍修改后连接成功，非常感谢。
