### ISSUE TITLE
[Bug]: TUN模式下无法启用redir-host模式

### ISSUE THREAD

**Issue by RookieBoy-lgbt** [Fndroid/clash_for_windows_pkg#3880]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.12

### 操作系统

Windows x64

### 系统版本

22H2

### 问题描述

启用Mixin与TUN Mode后Log提示
“!![DNS] redir-host is deprecated,please use fake-ip instead”

### 复现步骤

每次加载配置文件后均有该提示

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

已在Mixin中做出以下配置：

mixin: # object
    dns:
        enable: true
        listen: 127.0.0.1:53
        default-nameserver:
            - 223.5.5.5
            - 119.29.29.29
        enhanced-mode: redir-host
        use-hosts: true
        nameserver:
            - https://dns.alidns.com/dns-query
            - https://doh.pub/dns-query
            - tls://dns.alidns.com
            - tls://120.53.53.53
        fallback:
            - https://1.1.1.1/dns-query
            - https://dns.google/dns-query
            - tls://1.0.0.1:853
        fallback-filter:
            geoip: true
            geoip-code: CN
            ipcidr:
            - 240.0.0.0/4
            - 0.0.0.0/32
            - 127.0.0.1/32
            domain:
            - +.google.com
            - +.facebook.com
            - +.twitter.com
            - +.youtube.com
            - +.xn--ngstr-lra8j.com
            - +.google.cn
            - +.googleapis.cn
            - +.googleapis.com
            - +.gvt1.com

**Comment by yi-Xu-0100** [comment]
log 显示，应该不弹窗吧，他只是提示弃用，又没说没启用吧

**Comment by RookieBoy-lgbt** [comment]
> log 显示，应该不弹窗吧，他只是提示弃用，又没说没启用吧

看了一下connection里的信息，DNS mode确实是正常redir-host模式，只是开启后log显示让我误以为没有成功开启
