### ISSUE TITLE
「问题」想问下 subInfo 的功能是 cfw 提供的吗

### ISSUE THREAD

**Issue by wenfangdu** [Fndroid/clash_for_windows_pkg#3884]
没有找到对应的文档

<img width="287" alt="image" src="https://user-images.githubusercontent.com/28700378/211711641-a6e907f9-3ad3-4f73-b910-6227635f0a2a.png">

**Comment by yi-Xu-0100** [comment]
profile 下的 list.yml 应该是自动生成的。

数据应该是来自于 header 中的信息。

从 0.15.7 开始支持显示。
从 0.16.2 开始支持从配置文件的注释中读取。
