### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 1158523374** [Fndroid/clash_for_windows_pkg#3886]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.12

### 操作系统

Windows x64

### 系统版本

Windows10 1909

### 问题描述

请看图！
安装之后目录里只剩个卸载包，没有软件启动包和组件

### 复现步骤

安装3次还是如此，没有日志文件

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

没有日志文件，里面就一个卸载包

**Comment by 1158523374** [comment]
![QQ图片20230111145159](https://user-images.githubusercontent.com/72774771/211737701-2d36916b-0d9f-4eb8-8737-f3597653ad87.png)

**Comment by Fndroid** [comment]
安装错了安装包，arm64不是给你cpu用的

**Comment by 1158523374** [comment]
![image](https://user-images.githubusercontent.com/72774771/211974403-8333063f-1b74-41ed-9786-4ce260b6facc.png)
这个CPU不可以吗

**Comment by yi-Xu-0100** [comment]
@1158523374 你应该找这个 

![image](https://user-images.githubusercontent.com/25523606/211977508-b84acd42-7802-47a2-b002-fe20a76cf643.png)

**Comment by 1158523374** [comment]
没有找到这个

**Comment by 1158523374** [comment]
可以发下链接吗？谢谢

**Comment by yi-Xu-0100** [comment]
页面链接：https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.20.12
所指的下载链接：
https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.20.12/Clash.for.Windows.Setup.0.20.12.exe

**Comment by yi-Xu-0100** [comment]
我怀疑你看的是 https://github.com/Fndroid/clash_for_windows_pkg/releases

那要注意的是显示全部 
![image](https://user-images.githubusercontent.com/25523606/212012293-45feae09-8403-4756-b313-60cbdc3643b3.png)
