### ISSUE TITLE
[Bug]: win11更新系统后，clash for windows使用schtasks方式安装service mode失败

### ISSUE THREAD

**Issue by NEPDream** [Fndroid/clash_for_windows_pkg#3887]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.12

### 操作系统

Windows x64

### 系统版本

win11

### 问题描述

之前使用schtasks方式安装service mode一直没有任何问题，今天win11更新后，发现使用schtasks安装service mode后，服务依然是inactive状态，排查后在计划任务管理中，看到clash core service执行失败的记录，结果显示是“系统找不到指定文件”
![image](https://user-images.githubusercontent.com/31023128/211741758-c812f602-484c-471a-9f90-edba0277d1b7.png)
于是打开详情，查看具体执行的文件目录位置，发现问题所在
![image](https://user-images.githubusercontent.com/31023128/211742013-ba7463f9-192b-4689-817e-09f08de14764.png)
![image](https://user-images.githubusercontent.com/31023128/211742094-9091f168-a0d2-43f5-b057-b5da20f5657c.png)
也就是说，新版的win11更新后，在用schtasks方式安装service mode时候，会出现添加的计划任务中，出现文件路径"C:\Program Files\Clash for Windows Service\clash-core-service.exe"被拆分成C:\Program，然后参数是“Files\Clash for Windows Service\clash-core-service.exe”的情况，所以触发了bug，按照这个思路，把路径手动设置成正常clash-core-service，如下图所示
![image](https://user-images.githubusercontent.com/31023128/211742563-274901ab-9c06-4cd4-8037-9554e8001e67.png)
再次运行该计划任务，可以看到service mode重新正常了
![image](https://user-images.githubusercontent.com/31023128/211742842-c93d6d79-5aad-421f-ad39-42a99ad5f25c.png)

### 复现步骤

更新新版win11后，通过schtasks方式卸载再安装service mode就可以百分百复现

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by XinSSS** [comment]
win10也有这样的情况

**Comment by MUTED64** [comment]
Windows 10 build 19045.2486，出现相同情况

**Comment by wutong233** [comment]
+1，有时候restart能好，有时候不行。到22621.1105后没成功过

**Comment by Zxilly** [comment]
`schtasks /change /tn "Clash Core Service" /tr "C:\Program Files\Clash for Windows Service\clash-core-service.exe"`
应该改成
`schtasks /change /tn "Clash Core Service" /tr "\"C:\Program Files\Clash for Windows Service\clash-core-service.exe\""`

**Comment by chensrnile** [comment]
我就说怎么突然TUN不好使了😂

**Comment by amtoaer** [comment]
同在安装windows 11 KB5022303 后出现

**Comment by Fndroid** [comment]
下个版本修复

**Comment by NEPDream** [comment]
> 

辛苦老大了

**Comment by NEPDream** [comment]
> 下个版本修复

辛苦老大了！

**Comment by lemoeo** [comment]
> 下个版本修复

大佬好，我 Windows 10 系统更新后也出现schtasks方式安装service mode失败，错误信息如下：

<img width="320" alt="批注 2023-01-12 135100" src="https://user-images.githubusercontent.com/18618627/211988805-1ef20824-d425-41b4-8e9c-64ae05d6f429.png">
<img width="317" alt="批注 2023-01-12 135118" src="https://user-images.githubusercontent.com/18618627/211988853-8a97485f-31df-41f6-a5f3-3056949b3f80.png">

**Comment by lemoeo** [comment]
> > 下个版本修复
> 
> 大佬好，我 Windows 10 系统更新后也出现schtasks方式安装service mode失败，错误信息如下：
> 
> <img alt="批注 2023-01-12 135100" width="320" src="https://user-images.githubusercontent.com/18618627/211988805-1ef20824-d425-41b4-8e9c-64ae05d6f429.png">
> 
> <img alt="批注 2023-01-12 135118" width="317" src="https://user-images.githubusercontent.com/18618627/211988853-8a97485f-31df-41f6-a5f3-3056949b3f80.png">

我知道这个问题的原因了，我发现我的 C:\Program Files 目录下面有个 Clash for Windows Service 的文件，导致创建目录失败，我把文件删除再尝试安装就可以了。然后按照上面的方法在任务计划程序中修改启动程序的路径，Service Mode终于正常了😄😄😄

**Comment by Fitye** [comment]
看来不只是我一个人的问题，都遇到了相关问题，等待作者修复

**Comment by valetzx** [comment]
你好我也是这个问题，但是安装好了之后小地球没绿

**Comment by wutong233** [comment]
> > > 下个版本修复
> > 
> > 
> > 大佬好，我 Windows 10 系统更新后也出现schtasks方式安装service mode失败，错误信息如下：
> > <img alt="批注 2023-01-12 135100" width="320" src="https://user-images.githubusercontent.com/18618627/211988805-1ef20824-d425-41b4-8e9c-64ae05d6f429.png">
> > <img alt="批注 2023-01-12 135118" width="317" src="https://user-images.githubusercontent.com/18618627/211988853-8a97485f-31df-41f6-a5f3-3056949b3f80.png">
> 
> 我知道这个问题的原因了，我发现我的 C:\Program Files 目录下面有个 Clash for Windows Service 的文件，导致创建目录失败，我把文件删除再尝试安装就可以了。然后按照上面的方法在任务计划程序中修改启动程序的路径，Service Mode终于正常了😄😄😄

更新一月补丁前我这样也可以解决问题。但仅限于更新之前...

**Comment by FDUZS** [comment]
同样有这个问题，早知道更新系统前应该先来看看 issue 的

**Comment by Kanna-marin** [comment]
> 

大佬辛苦了，我也是最新版的win11更新了那个补丁就tun一直灰色，之前还可以重新安装tun用，现在是彻底用不了

**Comment by best-wxw** [comment]
发现问题，然后解决问题，还教着怎么解决，太感谢你了

**Comment by dqzscc** [comment]
勾选使用最高权限运行 重启电脑后 Service Mode可以正常 安装使用  
![image](https://user-images.githubusercontent.com/112539055/212474840-fb04de51-0552-4c3e-8244-5f75a01329ac.png)

**Comment by leafsoul365** [comment]
good，修改计划任务后确实解决了。
但我这发现一个问题，每开关一次tun，或是每重启一次电脑，右下角网络连接那，clash的网络连接名字就会+1，XX连接*1，XX连接*2.。。。。

**Comment by heywtb** [comment]
> 
目前这个方法有用，多谢。

**Comment by dqzscc** [comment]
这个 我的暂时没有出现这种情况

leafsoul ***@***.***> 于2023年1月16日周一 13:33写道：

**Comment by dqzscc** [comment]
能解决问题就好

HEYWTB ***@***.***> 于2023年1月17日周二 16:38写道：

**Comment by shenyimings** [comment]
同在安装windows 11 KB5022303 后出现，更新版本后已解决，感谢您和Fndroid！

**Comment by dqzscc** [comment]
解决问题就好 感谢Fndroid提供这个好用的工具

Yiming Shen ***@***.***> 于2023年1月27日周五 14:57写道：

**Comment by FDUZS** [comment]
这位 @dqzscc 同学，人家不是在和你对话。
你之所以会收到邮件，那是因为每个参与到 issue 讨论的人默认情况下都会收到与之相关的提醒。
所以，不要再把 issue 当成论坛灌水一样使用。

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
