### ISSUE TITLE
新版本0.8.10延迟检测好像出问题了。。。。。。

### ISSUE THREAD

**Issue by GHOSTagw** [Fndroid/clash_for_windows_pkg#389]
检测延迟之后，检测结果一闪而过，看不了......检测全部节点和单节点都这样，不知道是不是特意改的....谢谢

**Comment by Fndroid** [comment]
已知问题

Arnold <notifications@github.com>于2020年1月22日 周三20:28写道：

**Comment by du5** [comment]
同版本 `url-test` `fallback` 设置 URL 不生效

**Comment by Fndroid** [comment]
> 同版本 `url-test` `fallback` 设置 URL 不生效

什么叫不生效？哪里看的不生效

**Comment by du5** [comment]
[视频演示](https://download.iplc.wiki/Viewer/Video?single=true&shareKey=ovubmrad&path=/%E5%B1%8F%E5%B9%95%E5%BD%95%E5%88%B6%202020-01-31%20%E4%B8%8B%E5%8D%8810.32.08_2.mp4)

**Comment by du5** [comment]
> > 同版本 `url-test` `fallback` 设置 URL 不生效
> 
> 什么叫不生效？哪里看的不生效

[视频演示](https://download.iplc.wiki/Viewer/Video?single=true&shareKey=ovubmrad&path=/%E5%B1%8F%E5%B9%95%E5%BD%95%E5%88%B6%202020-01-31%20%E4%B8%8B%E5%8D%8810.32.08_2.mp4)

**Comment by Fndroid** [comment]
@du5 手动测速不会使用配置文件里的url，如果要定义，需要在cinfig.yml文件里添加``cfw-latency-url``，参考https://docs.cfw.lbyczf.com/contents/configfile.html

**Comment by du5** [comment]
那没事了，感谢老板。理解了

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.8.11
