### ISSUE TITLE
[求助]: TUN启动失败，报错：Error creating interface: Cannot create a file when that file already exists.

### ISSUE THREAD

**Issue by ZippyRhys** [Fndroid/clash_for_windows_pkg#3890]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.12 (P核版本11/25/2022)

### 操作系统

Windows 10 x64

### 系统版本

22H2, build 19045.2251

### 问题描述

因为某些偶发情况(具体不明，记不起来了，抱歉)，导致tun无法启动，出现log中的报错。
希望得到解决办法，感谢！

### 复现步骤

* 不记得最初出现此问题时做了什么操作，故不清楚如何复现，不好意思。
* 数次退出软件重新开启均无效。由于设置了开机自启动，故每次开机后tun也启动失败。
* 另外经过测试，使用管理员权限启动CFW后能够正常启动tun。

### 日志文件

<details><summary>logs</summary><p>

```
17:57:51 INF [API] listening addr=127.0.0.1:1203
17:57:51 INF [Inbound] Mixed(http+socks) listening addr=127.0.0.1:8964
17:57:51 INF [Config] start initial provider name=proxyProvider
17:57:51 INF [Config] initial compatible provider name=Nodes
17:57:53 INF [Config] initial rule provider name=ruleProvider
17:57:53 INF [DNS] server listening addr=[::]:53
17:57:53 WRN [TUN] auto redir start failed error=unsupported
17:58:08 ERR [Inbound] start failed error=Error creating interface: Cannot create a file when that file already exists. type=TUN stackType=system inet=198.18.0.1/16
```

</p></details>

### 其他补充

mixin配置内容如下：
```yaml
mixin:
  tun: 
    enable: true
    stack: system
    dns-hijack:
      - udp://any:53
      - tcp://any:53
    auto-redir: true
    auto-route: true
    auto-detect-interface: true  #自动检测出口网卡
```

**Comment by imaegoo** [comment]
我遇到了同样的错误，proxy可以，但tun不行，已尝试过重新安装service，以及删除所有配置文件，重新安装clash，仍然不行，我猜测与最近的版本升级有关（不确定）

**Comment by rongcc1985** [comment]
一样的情况，也是更新后tun用不了。用管理员权限启动后就可以。
唯一的区别是，报错的提示是：Error creating interface: Access is denied.

**Comment by ZippyRhys** [comment]
* 从昨日开始，这个问题莫名消失了：开机自启动后CFW能够正常启动tun、开关mixin正常、重启CFW正常。
* 我确定我从开放此issue开始至问题自己消失之间没有对电脑刻意做过任何与CFW有关的调试(除了以管理员权限重启CFW)，因此问题消失的原因不明。
