### ISSUE TITLE
[Feature Request]: 建议将状态栏右键选项栏中的 “More” 和 “Quit” 按钮往上移！！！

### ISSUE THREAD

**Issue by zhouzl7** [Fndroid/clash_for_windows_pkg#3893]
### 功能描述

当 Proxy Group 数量很多时，状态栏右键选项栏中的 “More” 和 “Quit” 按钮会被隐藏，需要下滑才能使用。
![1](https://user-images.githubusercontent.com/33414045/212255367-24023aee-d48f-45d1-8db6-227fe65d1a79.png)
按照按钮的使用频率优先级，建议将状态栏右键选项栏中的 “More” 和 “Quit” 按钮往上移，置于选项栏中的第二区更合适。
![2](https://user-images.githubusercontent.com/33414045/212255401-028ce405-dae4-4f9c-ab23-f475c01a6c8a.png)

**Comment by yi-Xu-0100** [comment]
感觉如果使用频率不高，直接用 submenu 更好。。。

**Comment by zhouzl7** [comment]
> 感觉如果使用频率不高，直接用 submenu 更好。。。

我感觉 Quit 的使用频率是最高的。 Proxy Groups 感觉可以再加一级 submenu

**Comment by yi-Xu-0100** [comment]
@zhouzl7 Proxy Groups 是可以 submenu 的

![图片](https://user-images.githubusercontent.com/25523606/212258023-3cbc9f7f-d351-4dc2-9cae-8c778faff96a.png)

**Comment by zhouzl7** [comment]
> @zhouzl7 Proxy Groups 是可以 submenu 的
> 
> ![图片](https://user-images.githubusercontent.com/25523606/212258023-3cbc9f7f-d351-4dc2-9cae-8c778faff96a.png)

学会了，解决了我的问题，感谢~
