### ISSUE TITLE
建议增加http和https的用户名密码设置

### ISSUE THREAD

**Issue by Allentong61** [Fndroid/clash_for_windows_pkg#39]
现在clash内核已经支持http和https出站模式了，要使用basicauth登录服务器需要有用户名和密码。目前只能手工编辑配置文件来实现。希望能有GUI界面实现这个功能

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.5.3

**Comment by Fndroid** [comment]
下个版本加上

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.5.4
