### ISSUE TITLE
[Bug]:  ubuntu 22.04 根据文档步骤，无法安装service mode

### ISSUE THREAD

**Issue by meislzhua** [Fndroid/clash_for_windows_pkg#3904]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.12

### 操作系统

Linux

### 系统版本

ubuntu 22.04

### 问题描述

根据文档步骤，无法安装service mode

### 复现步骤

1. 开机自动启动clash for window（或手动双击cfw打开）
2. 点击dashboard
3. 点击 service mode 右边的 manage
4. 点击 install 时，弹出错误框，fail to install service
![截图 2023-01-18 12-59-51](https://user-images.githubusercontent.com/8063591/213089364-1eaaa65b-5d6f-47cd-96ad-6d88345aebd8.png)
5. 点击reload app，后重复2，3，4步骤，弹出错误框
![截图 2023-01-18 13-01-48](https://user-images.githubusercontent.com/8063591/213089897-e37fc30c-43d2-4c9c-b5b2-467045240373.png)

### 其他补充

如果使用sudo 运行cfw，则需要添加 no sandbox，然后无法正常打开，白屏
![image](https://user-images.githubusercontent.com/8063591/213089743-ffce9df2-8c24-403a-9652-4c53909782b6.png)

**Comment by czp0204** [comment]
同问

**Comment by meislzhua** [comment]
@czp0204 1. 他的issue里面有一个教你手动安装的，最开始我就是这样解决的 2. 我重装之后Ubuntu之后，可以直接安装，虽然提示失败，重启后有绿色小地球，就是安装成功了
