### ISSUE TITLE
[Feature Request]: Custom Path

### ISSUE THREAD

**Issue by belompunya** [Fndroid/clash_for_windows_pkg#3907]
-

**Comment by tdjnodj** [comment]
Path is not domain.The domain is host.

```
name: VMESS 8080 NON TLS
type: vmess
server: server.com
port: xxx
uuid: xxxx
alterId: 0
cipher: auto
udp: true
tls: false
skip-cert-verify: true
servername: xxx
network: ws
ws-opts:
path: /path
headers:
Host: domain
```

**Comment by belompunya** [comment]
ok bro, i know that, but in my country, thats called 0p0k , 0 kuota 0 pulsa - 0 kuota 0 credit . 
called, free internet cellular, without pay . 
in openclash use , meta core, and netmod can.

this example :

proxies:
  - name: VMESS 8080 FREE INTERNET
    server: xray.server.com
    port: 8080
    type: vmess
    uuid: 71a7db14-1b6f-5aec-9e5d-9bd5f8beabax
    alterId: 0
    cipher: auto
    tls: 1
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: http://indosat.com/worryfree
      headers:
        Host: api.twitter.com

can you see, path with domain, and host with another domain, 

this condition, for free internet in my country  like that , custom path
