### ISSUE TITLE
[Bug]: 0.21.14版本覆盖provider路径时原有文件文件名会变为HASH码

### ISSUE THREAD

**Issue by RookieBoy-lgbt** [Fndroid/clash_for_windows_pkg#3914]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.21.14

### 操作系统

Windows x64

### 系统版本

22H2

### 问题描述

在0.21.12版本及以前下载provider文件时如果因为网络原因导致无法下载的话可以通过建立与配置文件中相同文件名的yaml文件以绕过cfw的报错，但现版本由于再覆盖路径时provider文件名同样会变为HAS码导致只能通过从github上下载配置文件，因此导致cfw启动失败（因为找不对对应provider文件）
![name](https://user-images.githubusercontent.com/84926161/213679301-5942b58c-1b30-4550-8073-49fcdea70f83.png)
![luan_name](https://user-images.githubusercontent.com/84926161/213679312-f1567a9a-cfe7-4229-b214-cc3e17839bc5.png)
如上图所示，在clash provider文件夹内的所有文件名变为了HASH码，导致我无法通过直接将对应provider文件粘贴到目录下从而避免cfw报错

### 复现步骤

更新订阅文件时发生

**Comment by Fndroid** [comment]
你不通过url下载更新的话，就不需要http类型的provider，把url删掉就好了

**Comment by RookieBoy-lgbt** [comment]
> 

其实是需要更新配置文件的，只不过国内直连GitHub下载文件大概率失败，所以我在新电脑上第一次启动cfw时都会手动将github上的配置文件放到对应目录中

**Comment by Jimmy20220531** [comment]
> 你不通过url下载更新的话，就不需要http类型的provider，把url删掉就好了

大佬，大佬，求你了，解决一下吧，呜呜。

**Comment by Jimmy20220531** [comment]
> > 
> 
> 其实是需要更新配置文件的，只不过国内直连GitHub下载文件大概率失败，所以我在新电脑上第一次启动cfw时都会手动将github上的配置文件放到对应目录中

是这个原因：https://github.com/Fndroid/clash_for_windows_pkg/issues/3891#issuecomment-1384969170

**Comment by Jimmy20220531** [comment]
卸载并完全清除残留，然后重装CFW，还是用以前的自定义配置，一切正常。

**Comment by undoubted** [comment]
我的providers放在内网，现在连不上内网，直接启动不了了。。。

**Comment by yeefaye** [comment]
> 你不通过url下载更新的话，就不需要http类型的provider，把url删掉就好了

一堆这样的文件名很不方便，不如以前的命名方式。
