### ISSUE TITLE
求老板权威推荐配置明细，谢谢！

### ISSUE THREAD

**Issue by btcforver** [Fndroid/clash_for_windows_pkg#392]
![image](https://user-images.githubusercontent.com/60208053/72956885-7009a080-3ddc-11ea-8d65-dd3f4018ce62.png)
之前选的chacha20报错，现在请老板指导这3项具体最优配置，以便达到最佳使用效果，谢谢！

**Comment by Fndroid** [comment]
没有所谓的最优配置，网络环境复杂。建议联系服务商咨询

**Comment by btcforver** [comment]
![image](https://user-images.githubusercontent.com/60208053/72957592-15257880-3ddf-11ea-8075-0cdb84377814.png)
改了协议重新更新又报这个错误了。

**Comment by yi-Xu-0100** [comment]
#1049 #1003 #373 #1064 类似问题已回复

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
