### ISSUE TITLE
how i can cross all traffic from clash

### ISSUE THREAD

**Issue by 1271300583** [Fndroid/clash_for_windows_pkg#3920]
hello. i have a problem with clash.i installed on pc  and my browser use clash but there are programs (meta trader) that their traffic dont get from clash and are filter at iran.my question is there is anyway that all pc traffic cross from clash or at least some programs their traffic cross from clash?

**Comment by yi-Xu-0100** [comment]
https://docs.cfw.lbyczf.com/contents/tun.html

**Comment by 1271300583** [comment]
> https://docs.cfw.lbyczf.com/contents/tun.html

thanks for your help.it worked and problem solved
