### ISSUE TITLE
请问 rule 模式下是如何判断百度等内地网站是需要直连的

### ISSUE THREAD

**Issue by wenfangdu** [Fndroid/clash_for_windows_pkg#3927]
如果 rules 里不包含百度，且最后有 `- MATCH,,漏网之鱼,dns-failed`，漏网之鱼是走的代理，那么百度是不是应该被漏网之鱼匹配，然后走代理呢？还是说有其他机制来判断百度是需要直连的？

**Comment by yi-Xu-0100** [comment]
logs 或者 connections 里看看走的什么规则。

**Comment by wenfangdu** [comment]
@yi-Xu-0100 感谢回复，在 connections 里看到了

<img width="175" alt="image" src="https://user-images.githubusercontent.com/28700378/214315136-7144cc42-ca6a-4246-a640-0cca1ae521e2.png">

对应 rules 里的 `GEOIP,CN,DIRECT` 就真相大白了

<img width="617" alt="image" src="https://user-images.githubusercontent.com/28700378/214316333-e06ed5cf-9178-4ed9-ba91-4bb617c265b5.png">

另外想问一点，为什么 log 里看不到百度的连接呢，是走代理的连接才会显示在 log 里嘛？

**Comment by yi-Xu-0100** [comment]
应该可以的，可能是级别问题？debug级别试试，还有去logs文件里搜索试试

**Comment by wenfangdu** [comment]
@yi-Xu-0100 试了一下 debug 似乎不行，不过影响不大
