### ISSUE TITLE
[Bug]: cfw在providers里更新proxy providers的其中一条订阅链接会报错

### ISSUE THREAD

**Issue by data7799** [Fndroid/clash_for_windows_pkg#3932]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.14

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

cfw在providers里更新proxy providers的其中一条订阅链接会报错get "此处为订阅链接" context deadline exceeded,怎么办呀？（之前用providers编辑完后还会报错wsarecv: An existing connection was forcibly closed by the remote host.今天没报这个错，但是出现了issue这个报错

### 复现步骤

编辑完providers后在proxy providers更新订阅链接

### 日志文件

<details><summary>logs</summary><p>

```
抱歉，没有找到今天的日志，只找到以前的，看了下，不是用的今天的订阅链接和配置
```

</p></details>

**Comment by jamessawyer** [comment]
0.20.15同样的问题，之前好好的，更新后就报错了

**Comment by data7799** [comment]
> 0.20.15同样的问题，之前好好的，更新后就报错了

我的已经解决了，方法是在订阅链接后面加上&flag=clash
