### ISSUE TITLE
[Feature Request]: 上架 MS Store

### ISSUE THREAD

**Issue by QuarticCat** [Fndroid/clash_for_windows_pkg#3933]
### 功能描述

如题

**Comment by ColanCN** [comment]
好想法，不建议

**Comment by QuarticCat** [comment]
这里有一些支持的理由可供参考：

1. 新系统在下载 clash 前没有翻墙手段，从 github release 下载只有几 KB/s 的速度，从商店下载则更快

2. 软件从 MS Store 下载的话，在新系统可以很方便地全部装回来，商店里有记录下载软件清单。每个软件分别找网站比较麻烦

3. 商店现在允许发布 win32 应用，而且已经有一些 VPN 应用了，感觉应该没有条款上的障碍

**Comment by jaoyina** [comment]
没有太大必要，可以自己先下好保存到硬盘上，新系统直接可以用。
