### ISSUE TITLE
[Feature Request]: connections查看具体程序

### ISSUE THREAD

**Issue by tianyeyuan** [Fndroid/clash_for_windows_pkg#3934]
### 功能描述

我记得之前的版本可以在connections里查看某个连接具体属于是哪个程序（有可能记错了），可以把这个功能加上吗

**Comment by Sakuzy0** [comment]
设置/connections/Show Process If Present？

**Comment by yi-Xu-0100** [comment]
需要rule里有process-name规则，你可以随便加一个。

**Comment by tianyeyuan** [comment]
> 需要rule里有process-name规则，你可以随便加一个。

非常感谢
