### ISSUE TITLE
[Bug]: 全屏状态下最小化后，如果通过托盘按钮恢复，会变成窗口化且最大化/窗口化按钮不可用

### ISSUE THREAD

**Issue by fireattack** [Fndroid/clash_for_windows_pkg#3938]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.15

### 操作系统

Windows x64

### 系统版本

Win10 22H2

### 问题描述

估计是修复 #3830 不完全导致的副作用

### 复现步骤

1. 最大化窗口
2. 按最小化按钮最小化clash到任务栏
3. 不点任务栏，而是点击托盘图标恢复clash

Expected:
恢复窗口为最大化

Observed:

恢复为窗口化，且第二个按钮依然显示为“窗口化”（即最大化时才应该有的状态），且点击完全无效，只有通过双击标题栏才能修复

### 日志文件

无关

**Comment by HggDemo** [comment]
你还能点击标题栏修复，我直接最大化 怎么都修复不了

**Comment by fireattack** [comment]
> 你还能点击标题栏修复，我直接最大化 怎么都修复不了

双击

**Comment by HggDemo** [comment]
> > 你还能点击标题栏修复，我直接最大化 怎么都修复不了
> 
> 双击

也不行，我是2k缩放150，反正满满一个屏幕占满了，怎么都缩放不了

**Comment by Fndroid** [comment]
确实有这个问题，预计下个版本修复

**Comment by benchacha** [comment]
![image](https://user-images.githubusercontent.com/97609866/221576100-daa66fe3-dfd3-4983-8942-4339a7cdd46a.png)
我更新订阅的时候，报了这个错误是什么原因啊，需要怎么修改呢？

**Comment by fireattack** [comment]
> ![image](https://user-images.githubusercontent.com/97609866/221576100-daa66fe3-dfd3-4983-8942-4339a7cdd46a.png) 我更新订阅的时候，报了这个错误是什么原因啊，需要怎么修改呢？

和这个bug没关系，新版删掉了redir-host模式，改下你的profile。

**Comment by fireattack** [comment]
Fixed in newest version, thanks.

**Comment by zhujianggg** [comment]
辛苦“众位大神”请问一下，文件验证码，好久以前不知从哪下载，有验证下载文件SHA256验证码，后来通过了解认为这里是原作者，也就放心。升级就升级，点几下。就升级了。升级好几次，V 0.20.17这版升级过程没有提示什么“issuer”升级后感觉卡卡，点资源管理器，一看占用4G内存，以为升级完一些付带安装程序没有退出，重起电脑，这就不是卡这么简单，没办法操作，只好重装系统，在重装系统期间，用另一部电脑，详细分析，升级前与升级后代码，用农民程度，认为是合理的修改，只是加了一个从未见过壳，这“壳”是做什么。要做什么。因电脑升级重起后，就没法“运行”法输入代码。有SHA256码。行想下载升级。在折腾，应该病毒🦠钻升级漏洞。

**Comment by zhujianggg** [comment]
不好意思，我是刷了几天，刷不出这个。一说这个文件就出来。上网被完全控制linux-arm64-targz: 2f053c2fee80a3c45c3214665314becc8f836712426f8d52f7c9ac34dcec596b
linux-amd64-targz: 61aeee98468418be99c89343198157be3313077c9829734515c7bf1092b1e1e9
mac-arm64-7z: 3632bb45da3e1d768bc10789b9f0cd09176fa5b6f66f2a933f4f8f57e04763b1
arm64-dmg: 87a0e3364cb7b900cd77780afabeb901cbf2f46e78a9454da636e608b6541709
mac-7z: 54e8ac914d3fad47d52827bbe55e0d3b161f3a74f37c1595bbd37a3404af8760
dmg: 33ba1f27d827815f4c12be9907e0b16f0f7c77a917a945a02b00dd41e4d293a2
arm64-exe: 66648c37cf42f9db3e4e1cedb3e5fb423513fc1e44f2959b8ea2555238490f8d
arm64-7z: 5e63242b735e42dff2837e3ed3e72e6c8895c03324061c706a3cb930c9769084
ia32-exe: 906e2b437dafbec2e71a8ca90c204c1120d437b15a0b9132d8ad857cd1f8e3a2
ia32-7z: 03a72bf18c8d5fbb0fcea905be1b2d21bb59701d6482011ee6d04902ca500c35
exe: ecc2c4119aea079be68158d7675b881f37803a0804cda53a0ce6f63f3a6b4d87
7z: e0d4ec45ab1d9858972372fafa6aa9cf099b58e98650716d7ec331256419c365
