### ISSUE TITLE
关于全局的意思和如何设置全局流量

### ISSUE THREAD

**Issue by bluerthanever** [Fndroid/clash_for_windows_pkg#394]
大佬好
之前都是用shadowsocksr，刚转过来。
不太明白软件中的全局（global）指的什么意思？
我现在设置完之后，比如自己写了一个python用socks5，经过clash访问twitter，但是clash总是说不符合规则，走direct。用浏览器访问又是没有问题的。
看日志貌似python走的话是直接IP形式的，浏览器的话是域名形式的。

我现在想走类似shadowsocks中的全局，不知道应该怎么设置？如果没有，能不能建议增加一个这个功能，程序不做判断直接全走代理？

**Comment by bluerthanever** [comment]
顺带一提，我现在用的是8.10版本，选择全局是在Proxies→Global下选择的，目前感觉没有用，还是会做规则判断。log里会出现，XXXX不符合规则，走direct之类的

**Comment by Fndroid** [comment]
global就是不做判断支持发给对应代理的

**Comment by bluerthanever** [comment]
但是为什么我觉得我目前用的时候是做判断的？特别是我提到的，我用python转发给clash的时候，所有IP的都提示不符合规则改用direct？

**Comment by bluerthanever** [comment]
有没有什么详细一点的规则说明呢？

**Comment by bluerthanever** [comment]
我发现，我选中global中的服务器后，貌似在UI的log里显示的规则，确实是走的GLOBAL，但是log里显示的还是不符合规则，走direct。
![WeChat Image_20200201171455](https://user-images.githubusercontent.com/17560146/73589835-6ab40080-4516-11ea-99a4-a527cafc89bd.png)

**Comment by Fndroid** [comment]
https://github.com/Dreamacro/clash/issues/483

**Comment by bluerthanever** [comment]
唔。。。好吧。那我先去研究一下python的socks5有没有什么特殊处理
