### ISSUE TITLE
[Bug]: 预处理规则 升级0.20.15版本后 提示“无法切换此配置文件”

### ISSUE THREAD

**Issue by zxmqq1234** [Fndroid/clash_for_windows_pkg#3943]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.15

### 操作系统

Windows x64

### 系统版本

WIN11 ,22H2 ,22623.1095

### 问题描述

      mix-rule-providers: 
        reject: #广告域名列表
          type: http
          behavior: domain
          url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
          path: ./ruleset/reject.yaml
          interval: 86400
          
        icloud: #iCloud 域名列表
          type: http
          behavior: domain
          url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt"
          path: ./ruleset/icloud.yaml
          interval: 86400
          
        apple: # Apple 在中国大陆可直连的域名列表
          type: http
          behavior: domain
          url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"
          path: ./ruleset/apple.yaml
          interval: 86400
          
        google: # Google 在中国大陆可直连的域名列表
          type: http
          behavior: domain
          url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt"
          path: ./ruleset/google.yaml
          interval: 86400
          
        proxy: # 代理域名列表
          type: http
          behavior: domain
          url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
          path: ./ruleset/proxy.yaml
          interval: 86400
          
        direct: # 直连域名列表
          type: http
          behavior: domain
          url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
          path: ./ruleset/direct.yaml
          interval: 86400
          
        private: # 私有网络专用域名列表
          type: http
          behavior: domain
          url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
          path: ./ruleset/private.yaml
          interval: 86400
          
        gfw: # GFWList 域名列表
          type: http
          behavior: domain
          url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt"
          path: ./ruleset/gfw.yaml
          interval: 86400
          
        greatfire: # GreatFire 域名列表
          type: http
          behavior: domain
          url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/greatfire.txt"
          path: ./ruleset/greatfire.yaml
          interval: 86400
          
        tld-not-cn: # 非中国大陆使用的顶级域名列表
          type: http
          behavior: domain
          url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt"
          path: ./ruleset/tld-not-cn.yaml
          interval: 86400
          
        telegramcidr: # Telegram 使用的 IP 地址列表
          type: http
          behavior: ipcidr
          url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt"
          path: ./ruleset/telegramcidr.yaml
          interval: 86400
          
        cncidr: # 中国大陆 IP 地址列表
          type: http
          behavior: ipcidr
          url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"
          path: ./ruleset/cncidr.yaml
          interval: 86400
          
        lancidr: # 局域网 IP 及保留 IP 地址列表
          type: http
          behavior: ipcidr
          url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"
          path: ./ruleset/lancidr.yaml
          interval: 86400
          
        applications: # 需要直连的常见软件列表
          type: http
          behavior: classical
          url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"
          path: ./ruleset/applications.yaml
          interval: 86400
`

这个是完整的预处理文件：

[预处理配置.txt](https://github.com/Fndroid/clash_for_windows_pkg/files/10528807/default.txt)

----------------------------------------------------------

反馈图片：
![image](https://user-images.githubusercontent.com/50194103/215300740-2d0618c0-626e-4b5b-a215-4acb90ae2ade.png)

上一个版本之前都是可以的

### 复现步骤

添加预处理然后更新规则

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by voice1230** [comment]
新版本改了服务商规则文件路径，我也遇到这个问题，以前可以手动下载去那文件夹替换，现在不行了，新的规则文件命名是随机生成的
