### ISSUE TITLE
[Bug]: 无法安装Service Mode 提示 User did not grant permission.

### ISSUE THREAD

**Issue by NextAbyss** [Fndroid/clash_for_windows_pkg#3948]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.15

### 操作系统

Windows x64

### 系统版本

Windows 11 22H2

### 问题描述

重装后的Win11，无法安装Service Mode 提示 User did not grant permission. Force Quit后尝试使用管理员身份运行，仍提示此错误。
![image](https://user-images.githubusercontent.com/63849033/215339866-7f0ca4f4-6dae-4484-8497-954da42c79dd.png)

### 复现步骤

正常安装Clash，安装Service Mode失败

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by MatrixLau** [comment]
我也是类似问题 死活安装不了服务模式刚升级15

**Comment by eboxatGH** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/3874#issuecomment-1416036895

**Comment by NextAbyss** [comment]
> [#3874 (comment)](https://github.com/Fndroid/clash_for_windows_pkg/issues/3874#issuecomment-1416036895)

谢谢
