### ISSUE TITLE
关于 Rocky Linux 9.1 以及 Fedora 37 无法安装使用 Service Mode 以及 Tun Mode 的简陋解决办法

### ISSUE THREAD

**Issue by irort** [Fndroid/clash_for_windows_pkg#3949]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.15

### 操作系统

Linux

### 系统版本

Rocky Linux 9.1

### 问题描述

在使用 Rocky linux 9.1 以及 Fedora 37 的过程中, 从clash for windows 的 Release 下载, 无法安装Service Mode, 点击 manager 会让输入 root 用户密码, cfw 自动重启后 Service Mode 的地球图标为灰色 , 无法使用 Tun Mode . 按照 #3464 的方法, Service Mode 状态显示 inactive , 使用 systemctl status clash-core-service , code=exited, status=203/EXEC :  <a href="https://images4.imagebam.com/57/e6/35/MEIEOLE_o.png" target="_blank"><img src="https://images4.imagebam.com/57/e6/35/MEIEOLE_o.png" alt="Screenshot_20230130_002526.png"/></a>

在寻找clash相关文档的过程中,看到了[Running-Clash-as-a-service#systemd](https://github.com/Dreamacro/clash/wiki/Running-Clash-as-a-service#systemd) , 使用 sudo 或 以 root 权限执行 `$HOME /.config/clash/service/clash-core-service -d $HOME/.config/clash` , 例如`sudo /home/irort/.config/clash/service/clash-core-service -d /home/irort/.config/clash` , 重启 cfw , 虽然 clash-core-service.service 仍然为 exited 203 , 但是 cfw 的 Service Mode 地球图标已经变绿, Tun Mode 可以使用 :
<a href="https://images4.imagebam.com/da/dd/74/MEIEP11_o.png" target="_blank"><img src="https://images4.imagebam.com/da/dd/74/MEIEP11_o.png" alt="Screenshot_20230130_005210.png"/></a> 
<a href="https://images4.imagebam.com/d4/95/a9/MEIEP12_o.png" target="_blank"><img src="https://images4.imagebam.com/d4/95/a9/MEIEP12_o.png" alt="Screenshot_20230130_005249.png"/></a>

### 复现步骤

1. Rocky Linux 9.1 或者 Fedora 37 打开 cfw
2. 点击 Service Mode 右侧的 Manage
3. 输入完 root 密码后自动重启 , Service Mode 状态 inactive, 无法使用 Tun Mode

### 日志文件

<details><summary>logs</summary><p>

```
00:51:36 INF [API] listening addr=127.0.0.1:34163
00:51:36 INF [Inbound] Mixed(http+socks) listening addr=[::]:7890
00:51:36 WRN [TCP] dial failed error=dial tcp4 0.0.0.0:443: connect: connection refused proxy=DIRECT lAddr=127.0.0.1:43704 rAddr=raw.githubusercontent.com:443
00:51:36 WRN [TCP] dial failed error=dial tcp4 0.0.0.0:443: connect: connection refused proxy=DIRECT lAddr=127.0.0.1:43730 rAddr=raw.githubusercontent.com:443
00:51:36 INF [TCP] connected, doesn't match any rule lAddr=127.0.0.1:43720 rAddr=api.github.com:443 proxy=DIRECT
00:51:36 INF [Config] initial compatible provider name=GlobalMedia
00:51:36 INF [Config] initial compatible provider name=Final
00:51:36 INF [Config] initial compatible provider name=自动选择快速节点
00:51:36 INF [Config] initial compatible provider name=LoadBalance
00:51:36 INF [Config] initial compatible provider name=PROXY
00:51:36 INF [Config] initial compatible provider name=Apple
00:51:36 INF [Config] initial compatible provider name=HKMTMedia
00:51:36 INF [Inbound] TUN listening iface=utun gateway=198.18.0.1
00:51:41 INF [TCP] connected lAddr=127.0.0.1:43744 rAddr=optimizationguide-pa.googleapis.com:443 mode=rule rule=DomainKeyword(google) proxy=PROXY[jp-domain]
00:51:55 INF [UDP] connected lAddr=198.18.0.1:40296 rAddr=time.ustc.edu.cn:123 mode=rule rule=DomainSuffix(cn) proxy=DIRECT
00:55:35 INF [UDP] connected lAddr=198.18.0.1:42565 rAddr=202.38.64.7:123 mode=rule rule=GeoIP(CN) proxy=DIRECT
00:58:19 INF [TCP] connected lAddr=127.0.0.1:58564 rAddr=safebrowsing.googleapis.com:443 mode=rule rule=DomainKeyword(google) proxy=PROXY[jp-domain]
01:00:36 INF [UDP] connected lAddr=198.18.0.1:60018 rAddr=time.ustc.edu.cn:123 mode=rule rule=DomainSuffix(cn) proxy=DIRECT

```

</p></details>

**Comment by yiskiee** [comment]
# 针对 Service Mode 以及 TUN Mode，一个在 Fedora37 Linux 上验证成功的解决办法

楼主的办法我在 Fedora37上尝试失败, 只有小地球图标变绿而并未真正可用。
我花了点时间找到了问题所在，或许对楼主有所帮助。

## 删除数据

如果不是第一次安装，首先清除原数据。
在操作前，请备份好重要的数据！

假设 Clash for Windows 安装在 `/opt/clashwin/` 目录下，删除该目录。
```shell
$ sudo rm -r /opt/clashwin/
```

移除服务文件
```shell
$ sudo rm /usr/lib/systemd/system/clash-core-service.service
```

第一次启动服务时会自动创建一个链接。
如果有，也一并移除。
```shell
$ sudo rm /etc/systemd/system/multi-user.target.wants/clash-core-service.service
```

移除用户家目录下的配置文件。
```shell
$ rm -rf ~/.config/clash*
```

# 重启系统
```shell
$ reboot
```


## 重新安装

以 root 身份解压软件包到合适的目录，推荐在 `/opt/` 目录下。
```shell
$ sudo tar -zxvf Clash.for.Windows-0.20.15-x64-linux.tar.gz -C /opt/
```

重命名解压出的文件夹，文件夹不要包含特殊符号。
这里命名为 `clashwin`。
```shell
$ sudo mv /opt/Clash\ for\ Windows-0.20.15-x64-linux/ /opt/clashwin/
```

以普通用户身份运行 Clash for Windows，使其在用户配置目录下生成配置文件。
此时请不要做额外操作，只需让它启动而已。
```shell
$ /opt/clashwin/cfw
```

新建一个终端窗口，以 root 身份设置服务程序的权限。
这里以 linux x64 演示。
```shell
$ sudo chmod 755 /opt/clashwin/resources/static/files/linux/x64/service/clash-core-service
```

以 root 身份创建服务文件: `/usr/lib/systemd/system/clash-core-service.service`，
写入信息并根据情况修改 `ExecStart` 这行内容。

但是请注意，通过 Clash for Windows 设置的 clash-core-service 默认在用户的配置目录 `~/.config/clash/` 中
经过我在 Fedora37 上的测试, 默认目录中的服务无法启动！！
这可能是导致无法安装 Service Mode 的原因，
所以需要在设置 Service Mode 前将服务程序的路径改为原始的路径。

```
[Unit]
Description=Clash core service created by Clash for Windows
After=network-online.target nftables.service iptabels.service

[Service]
Type=simple
ExecStart=/opt/clashwin/resources/static/files/linux/x64/service/clash-core-service
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
```

将服务使能，系统会创建一个符号链接。
同时查看服务状态。
```shell
$ sudo systemctl enable clash-core-service
$ sudo systemctl status clash-core-service.service
```

可以看到, 服务已启用但是未激活:
```
○ clash-core-service.service - Clash core service created by Clash for Windows
     Loaded: loaded (/usr/lib/systemd/system/clash-core-service.service; enabled; preset: disabled)
     Active: inactive (dead)
```


启动服务，并再次查看服务状态。
```shell
$ sudo systemctl start clash-core-service
$ sudo systemctl status clash-core-service.service
```

输出结果如下：
```
● clash-core-service.service - Clash core service created by Clash for Windows
     Loaded: loaded (/usr/lib/systemd/system/clash-core-service.service; enabled; preset: disabled)
     Active: active (running) since Mon 2023-02-06 16:06:01 +08; 42s ago
   Main PID: 4456 (clash-core-serv)
      Tasks: 5 (limit: 11789)
     Memory: 1.1M
        CPU: 4ms
     CGroup: /system.slice/clash-core-service.service
             └─4456 /opt/clashwin/resources/static/files/linux/x64/service/clash-core-service

Feb 06 16:06:01 fedora systemd[1]: Started clash-core-service.service - Clash core service created by Clash for Windows.
```
可以看到，服务成功启动。


## 最后

在 Clash for Windows 中安装启用 Service Mode。
如果不成功，选择重启程序。此时应该可以看到地球图标变绿了，开启 TUN  Mode 能正常工作。

再次查看服务状态。
```shell
$ sudo systemctl status clash-core-service.service
```

输出结果如下：
```
● clash-core-service.service - Clash core service created by Clash for Windows
     Loaded: loaded (/usr/lib/systemd/system/clash-core-service.service; enabled; preset: disabled)
     Active: active (running) since Mon 2023-02-06 16:06:01 +08; 16min ago
   Main PID: 4456 (clash-core-serv)
      Tasks: 21 (limit: 11789)
     Memory: 7.8M
        CPU: 500ms
     CGroup: /system.slice/clash-core-service.service
             ├─4456 /opt/clashwin/resources/static/files/linux/x64/service/clash-core-service
             └─4922 /opt/clashwin/resources/static/files/linux/x64/clash-linux -d /home/me/.config/clash

Feb 06 16:06:01 fedora systemd[1]: Started clash-core-service.service - Clash core service created by Clash for Windows.
Feb 06 16:08:31 fedora clash-core-service[4456]: 2023/02/06 16:08:31 "GET http://127.0.0.1:53000/stop HTTP/1.1" from 127.0.0.1:52316 - 204 0B in 40.457µs
Feb 06 16:11:07 fedora clash-core-service[4456]: 2023/02/06 16:11:07 "GET http://127.0.0.1:53000/stop HTTP/1.1" from 127.0.0.1:33490 - 204 0B in 57.43µs
Feb 06 16:13:56 fedora clash-core-service[4456]: 2023/02/06 16:13:56 "GET http://127.0.0.1:53000/stop HTTP/1.1" from 127.0.0.1:47836 - 204 0B in 41.179µs
Feb 06 16:14:22 fedora clash-core-service[4456]: 2023/02/06 16:14:22 "GET http://127.0.0.1:53000/ping HTTP/1.1" from 127.0.0.1:42230 - 200 4B in 47.4µs
Feb 06 16:14:23 fedora clash-core-service[4456]: 2023/02/06 16:14:23 "GET http://127.0.0.1:53000/stop HTTP/1.1" from 127.0.0.1:42230 - 204 0B in 27.322µs
Feb 06 16:14:23 fedora clash-core-service[4456]: 2023/02/06 16:14:23 "POST http://127.0.0.1:53000/start HTTP/1.1" from 127.0.0.1:42230 - 200 49B in 55.946526ms
```

顺利解决，重启系统也能正常使用。

**Comment by irort** [comment]
@yiskiee  感谢您的回复，确实解决了问题。我找到了另一种我认为更便捷的方式（当然，我无法得知这么做有没有安全问题），我在查看之前通过cfw创建的service日志，发现它会被redhat的selinux策略阻止<a href="https://images4.imagebam.com/44/c9/ef/MEILLOF_o.png" target="_blank"><img src="https://images4.imagebam.com/44/c9/ef/MEILLOF_o.png" alt="Screenshot_20230207_022510.png"/></a>，在搜索"redhat selinux is preventing /usr/lib/systemd/systemd from execute access on the file"时看到了类似问题[回答](https://serverfault.com/questions/1032597/selinux-is-preventing-from-execute-access-on-the-file-centos/1032766#1032766)的一部分：

“  The SELinux restricts binaries that can be used in ExecStart to paths that has system_u:object_r:bin_t:s0 attribute set. **Typically those are /usr/bin /usr/sbin /usr/libexec /usr/local/bin directories.**

You need to move the script into one of this directories or change selinux policy to allow systemd to use binaries in the desired location as:
`chcon -R -t bin_t /opt/tomcat/bin/`
”

于是，我直接运行 `sudo cp /opt/clash/resources/static/files/linux/x64/service/clash-core-service /usr/bin/ && sudo chmod +x /usr/bin/clash-core-service`, clash-core-service中的EXEC路径也随之改为`/usr/bin/clash-core-service`,
最后，祝您生活愉快！

**Comment by mariohide** [comment]
@irort 您好
> clash-core-service中的EXEC路径也随之改为/usr/bin/clash-core-service
这里我没太理解，是要修改这个文件里的某个字段吗？我用 vim 打开后发现是乱码。

**Comment by mariohide** [comment]
> # 针对 Service Mode 以及 TUN Mode，一个在 Fedora37 Linux 上验证成功的解决办法
> 楼主的办法我在 Fedora37上尝试失败, 只有小地球图标变绿而并未真正可用。 我花了点时间找到了问题所在，或许对楼主有所帮助。
> 
> ## 删除数据
> 如果不是第一次安装，首先清除原数据。 在操作前，请备份好重要的数据！
> 
> 假设 Clash for Windows 安装在 `/opt/clashwin/` 目录下，删除该目录。
> 
> ```shell
> $ sudo rm -r /opt/clashwin/
> ```
> 
> 移除服务文件。 第一次启动服务时还会自动创建一个链接。如果有，也一并移除。
> 
> ```shell
> $ sudo rm /usr/lib/systemd/system/clash-core-service.service
> $ sudo rm /etc/systemd/system/multi-user.target.wants/clash-core-service.service
> ```
> 
> 移除用户家目录下的配置文件。然后重启系统，或注销重新登陆。
> 
> ```shell
> $ rm -rf ~/.config/clash*
> $ reboot
> ```
> 
> ## 重新安装
> 以 root 身份解压软件包到合适的目录，推荐在 `/opt/` 目录下。 重命名解压出的文件夹，文件夹不要包含特殊符号。 这里命名为 `clashwin`。
> 
> ```shell
> $ sudo tar -zxvf Clash.for.Windows-0.20.15-x64-linux.tar.gz -C /opt/
> $ sudo mv /opt/Clash\ for\ Windows-0.20.15-x64-linux/ /opt/clashwin/
> ```
> 
> 以 root 身份创建服务文件: `/usr/lib/systemd/system/clash-core-service.service`， 写入信息并根据情况修改 `ExecStart` 这行内容指向安装包中 clash-core-service 的路径 。
> 
> 请注意，通过 Clash for Windows 设置的 clash-core-service 默认在用户的配置目录 `~/.config/clash/` 中 经过我在 Fedora37 上的测试, **默认目录中的服务无法启动！！** 这可能是系统限制导致无法安装 Service Mode。 所以需要在设置 Service Mode 前将服务程序的路径改为原始的路径。
> 
> ```
> [Unit]
> Description=Clash core service created by Clash for Windows
> After=network-online.target nftables.service iptabels.service
> 
> [Service]
> Type=simple
> ExecStart=/opt/clashwin/resources/static/files/linux/x64/service/clash-core-service
> Restart=always
> RestartSec=5
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> 将服务使能，系统会创建一个符号链接。 同时查看服务状态。
> 
> ```shell
> $ sudo systemctl enable clash-core-service
> $ sudo systemctl status clash-core-service.service
> ```
> 
> 可以看到, 服务已启用但是未激活:
> 
> ```
> ○ clash-core-service.service - Clash core service created by Clash for Windows
>      Loaded: loaded (/usr/lib/systemd/system/clash-core-service.service; enabled; preset: disabled)
>      Active: inactive (dead)
> ```
> 
> 启动服务，并再次查看服务状态。
> 
> ```shell
> $ sudo systemctl start clash-core-service
> $ sudo systemctl status clash-core-service.service
> ```
> 
> 输出结果如下：
> 
> ```
> ● clash-core-service.service - Clash core service created by Clash for Windows
>      Loaded: loaded (/usr/lib/systemd/system/clash-core-service.service; enabled; preset: disabled)
>      Active: active (running) since Mon 2023-02-06 16:06:01 +08; 42s ago
>    Main PID: 4456 (clash-core-serv)
>       Tasks: 5 (limit: 11789)
>      Memory: 1.1M
>         CPU: 4ms
>      CGroup: /system.slice/clash-core-service.service
>              └─4456 /opt/clashwin/resources/static/files/linux/x64/service/clash-core-service
> 
> Feb 06 16:06:01 fedora systemd[1]: Started clash-core-service.service - Clash core service created by Clash for Windows.
> ```
> 
> 可以看到，服务成功启动。
> 
> ## 最后
> 重新启动或注销重新登陆系统，此时应该可以看到地球图标变绿了，开启 TUN Mode 能正常工作。 **不要再次安装 Service Mode！！** 如果再次安装，需要重新设置服务文件 `/usr/lib/systemd/system/clash-core-service.service` 中的 `ExecStart` 路径
> 
> 再次查看服务状态。
> 
> ```shell
> $ sudo systemctl status clash-core-service.service
> ```
> 
> 输出结果如下：
> 
> ```
> ● clash-core-service.service - Clash core service created by Clash for Windows
>      Loaded: loaded (/usr/lib/systemd/system/clash-core-service.service; enabled; preset: disabled)
>      Active: active (running) since Mon 2023-02-06 16:06:01 +08; 16min ago
>    Main PID: 4456 (clash-core-serv)
>       Tasks: 21 (limit: 11789)
>      Memory: 7.8M
>         CPU: 500ms
>      CGroup: /system.slice/clash-core-service.service
>              ├─4456 /opt/clashwin/resources/static/files/linux/x64/service/clash-core-service
>              └─4922 /opt/clashwin/resources/static/files/linux/x64/clash-linux -d /home/me/.config/clash
> 
> Feb 06 16:06:01 fedora systemd[1]: Started clash-core-service.service - Clash core service created by Clash for Windows.
> Feb 06 16:08:31 fedora clash-core-service[4456]: 2023/02/06 16:08:31 "GET http://127.0.0.1:53000/stop HTTP/1.1" from 127.0.0.1:52316 - 204 0B in 40.457µs
> Feb 06 16:11:07 fedora clash-core-service[4456]: 2023/02/06 16:11:07 "GET http://127.0.0.1:53000/stop HTTP/1.1" from 127.0.0.1:33490 - 204 0B in 57.43µs
> Feb 06 16:13:56 fedora clash-core-service[4456]: 2023/02/06 16:13:56 "GET http://127.0.0.1:53000/stop HTTP/1.1" from 127.0.0.1:47836 - 204 0B in 41.179µs
> Feb 06 16:14:22 fedora clash-core-service[4456]: 2023/02/06 16:14:22 "GET http://127.0.0.1:53000/ping HTTP/1.1" from 127.0.0.1:42230 - 200 4B in 47.4µs
> Feb 06 16:14:23 fedora clash-core-service[4456]: 2023/02/06 16:14:23 "GET http://127.0.0.1:53000/stop HTTP/1.1" from 127.0.0.1:42230 - 204 0B in 27.322µs
> Feb 06 16:14:23 fedora clash-core-service[4456]: 2023/02/06 16:14:23 "POST http://127.0.0.1:53000/start HTTP/1.1" from 127.0.0.1:42230 - 200 49B in 55.946526ms
> ```
> 
> 顺利解决，重启系统也能正常使用。

非常感谢🙏🏻，终于弄好了😸

**Comment by 4SM** [comment]
> # 针对 Service Mode 以及 TUN Mode，一个在 Fedora37 Linux 上验证成功的解决办法
> 
> 楼主的办法我在 Fedora37上尝试失败, 只有小地球图标变绿而并未真正可用。 我花了点时间找到了问题所在，或许对楼主有所帮助。
> ## 删除数据
> 
> 如果不是第一次安装，首先清除原数据。 在操作前，请备份好重要的数据！
> 
> 假设 Clash for Windows 安装在 `/opt/clashwin/` 目录下，删除该目录。
> 
> ```shell
> $ sudo rm -r /opt/clashwin/
> ```
> 
> 移除服务文件。 第一次启动服务时还会自动创建一个链接。如果有，也一并移除。
> 
> ```shell
> $ sudo rm /usr/lib/systemd/system/clash-core-service.service
> $ sudo rm /etc/systemd/system/multi-user.target.wants/clash-core-service.service
> ```
> 
> 移除用户家目录下的配置文件。然后重启系统，或注销重新登陆。
> 
> ```shell
> $ rm -rf ~/.config/clash*
> $ reboot
> ```
> 
> ## 重新安装
> 
> 以 root 身份解压软件包到合适的目录，推荐在 `/opt/` 目录下。 重命名解压出的文件夹，文件夹不要包含特殊符号。 这里命名为 `clashwin`。
> 
> ```shell
> $ sudo tar -zxvf Clash.for.Windows-0.20.15-x64-linux.tar.gz -C /opt/
> $ sudo mv /opt/Clash\ for\ Windows-0.20.15-x64-linux/ /opt/clashwin/
> ```
> 
> 以 root 身份创建服务文件: `/usr/lib/systemd/system/clash-core-service.service`， 写入信息并根据情况修改 `ExecStart` 这行内容指向安装包中 clash-core-service 的路径 。
> 
> 请注意，通过 Clash for Windows 设置的 clash-core-service 默认在用户的配置目录 `~/.config/clash/` 中 经过我在 Fedora37 上的测试, **默认目录中的服务无法启动！！** 这可能是系统限制导致无法安装 Service Mode。 所以需要在设置 Service Mode 前将服务程序的路径改为原始的路径。
> 
> ```
> [Unit]
> Description=Clash core service created by Clash for Windows
> After=network-online.target nftables.service iptabels.service
> 
> [Service]
> Type=simple
> ExecStart=/opt/clashwin/resources/static/files/linux/x64/service/clash-core-service
> Restart=always
> RestartSec=5
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> 将服务使能，系统会创建一个符号链接。 同时查看服务状态。
> 
> ```shell
> $ sudo systemctl enable clash-core-service
> $ sudo systemctl status clash-core-service.service
> ```
> 
> 可以看到, 服务已启用但是未激活:
> 
> ```
> ○ clash-core-service.service - Clash core service created by Clash for Windows
>      Loaded: loaded (/usr/lib/systemd/system/clash-core-service.service; enabled; preset: disabled)
>      Active: inactive (dead)
> ```
> 
> 启动服务，并再次查看服务状态。
> 
> ```shell
> $ sudo systemctl start clash-core-service
> $ sudo systemctl status clash-core-service.service
> ```
> 
> 输出结果如下：
> 
> ```
> ● clash-core-service.service - Clash core service created by Clash for Windows
>      Loaded: loaded (/usr/lib/systemd/system/clash-core-service.service; enabled; preset: disabled)
>      Active: active (running) since Mon 2023-02-06 16:06:01 +08; 42s ago
>    Main PID: 4456 (clash-core-serv)
>       Tasks: 5 (limit: 11789)
>      Memory: 1.1M
>         CPU: 4ms
>      CGroup: /system.slice/clash-core-service.service
>              └─4456 /opt/clashwin/resources/static/files/linux/x64/service/clash-core-service
> 
> Feb 06 16:06:01 fedora systemd[1]: Started clash-core-service.service - Clash core service created by Clash for Windows.
> ```
> 
> 可以看到，服务成功启动。
> ## 最后
> 
> 重新启动或注销重新登陆系统，此时应该可以看到地球图标变绿了，开启 TUN Mode 能正常工作。 **不要再次安装 Service Mode！！** 如果再次安装，需要重新设置服务文件 `/usr/lib/systemd/system/clash-core-service.service` 中的 `ExecStart` 路径
> 
> 再次查看服务状态。
> 
> ```shell
> $ sudo systemctl status clash-core-service.service
> ```
> 
> 输出结果如下：
> 
> ```
> ● clash-core-service.service - Clash core service created by Clash for Windows
>      Loaded: loaded (/usr/lib/systemd/system/clash-core-service.service; enabled; preset: disabled)
>      Active: active (running) since Mon 2023-02-06 16:06:01 +08; 16min ago
>    Main PID: 4456 (clash-core-serv)
>       Tasks: 21 (limit: 11789)
>      Memory: 7.8M
>         CPU: 500ms
>      CGroup: /system.slice/clash-core-service.service
>              ├─4456 /opt/clashwin/resources/static/files/linux/x64/service/clash-core-service
>              └─4922 /opt/clashwin/resources/static/files/linux/x64/clash-linux -d /home/me/.config/clash
> 
> Feb 06 16:06:01 fedora systemd[1]: Started clash-core-service.service - Clash core service created by Clash for Windows.
> Feb 06 16:08:31 fedora clash-core-service[4456]: 2023/02/06 16:08:31 "GET http://127.0.0.1:53000/stop HTTP/1.1" from 127.0.0.1:52316 - 204 0B in 40.457µs
> Feb 06 16:11:07 fedora clash-core-service[4456]: 2023/02/06 16:11:07 "GET http://127.0.0.1:53000/stop HTTP/1.1" from 127.0.0.1:33490 - 204 0B in 57.43µs
> Feb 06 16:13:56 fedora clash-core-service[4456]: 2023/02/06 16:13:56 "GET http://127.0.0.1:53000/stop HTTP/1.1" from 127.0.0.1:47836 - 204 0B in 41.179µs
> Feb 06 16:14:22 fedora clash-core-service[4456]: 2023/02/06 16:14:22 "GET http://127.0.0.1:53000/ping HTTP/1.1" from 127.0.0.1:42230 - 200 4B in 47.4µs
> Feb 06 16:14:23 fedora clash-core-service[4456]: 2023/02/06 16:14:23 "GET http://127.0.0.1:53000/stop HTTP/1.1" from 127.0.0.1:42230 - 204 0B in 27.322µs
> Feb 06 16:14:23 fedora clash-core-service[4456]: 2023/02/06 16:14:23 "POST http://127.0.0.1:53000/start HTTP/1.1" from 127.0.0.1:42230 - 200 49B in 55.946526ms
> ```
> 
> 顺利解决，重启系统也能正常使用。

谢谢大佬。请问如何升级？我前几天升级后，把 opt 目录下的 clashwin 文件夹删除，下载 CFW 解压到 opt 目录，然后要重新再按照你的方法操作一次。弄得我以后都不敢更新了。

**Comment by irort** [comment]
> > # 针对 Service Mode 以及 TUN Mode，一个在 Fedora37 Linux 上验证成功的解决办法
> > 楼主的办法我在 Fedora37上尝试失败, 只有小地球图标变绿而并未真正可用。 我花了点时间找到了问题所在，或许对楼主有所帮助。
> > ## 删除数据
> > 如果不是第一次安装，首先清除原数据。 在操作前，请备份好重要的数据！
> > 假设 Clash for Windows 安装在 `/opt/clashwin/` 目录下，删除该目录。
> > ```shell
> > $ sudo rm -r /opt/clashwin/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 移除服务文件。 第一次启动服务时还会自动创建一个链接。如果有，也一并移除。
> > ```shell
> > $ sudo rm /usr/lib/systemd/system/clash-core-service.service
> > $ sudo rm /etc/systemd/system/multi-user.target.wants/clash-core-service.service
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 移除用户家目录下的配置文件。然后重启系统，或注销重新登陆。
> > ```shell
> > $ rm -rf ~/.config/clash*
> > $ reboot
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## 重新安装
> > 以 root 身份解压软件包到合适的目录，推荐在 `/opt/` 目录下。 重命名解压出的文件夹，文件夹不要包含特殊符号。 这里命名为 `clashwin`。
> > ```shell
> > $ sudo tar -zxvf Clash.for.Windows-0.20.15-x64-linux.tar.gz -C /opt/
> > $ sudo mv /opt/Clash\ for\ Windows-0.20.15-x64-linux/ /opt/clashwin/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 以 root 身份创建服务文件: `/usr/lib/systemd/system/clash-core-service.service`， 写入信息并根据情况修改 `ExecStart` 这行内容指向安装包中 clash-core-service 的路径 。
> > 请注意，通过 Clash for Windows 设置的 clash-core-service 默认在用户的配置目录 `~/.config/clash/` 中 经过我在 Fedora37 上的测试, **默认目录中的服务无法启动！！** 这可能是系统限制导致无法安装 Service Mode。 所以需要在设置 Service Mode 前将服务程序的路径改为原始的路径。
> > ```
> > [Unit]
> > Description=Clash core service created by Clash for Windows
> > After=network-online.target nftables.service iptabels.service
> > 
> > [Service]
> > Type=simple
> > ExecStart=/opt/clashwin/resources/static/files/linux/x64/service/clash-core-service
> > Restart=always
> > RestartSec=5
> > 
> > [Install]
> > WantedBy=multi-user.target
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 将服务使能，系统会创建一个符号链接。 同时查看服务状态。
> > ```shell
> > $ sudo systemctl enable clash-core-service
> > $ sudo systemctl status clash-core-service.service
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 可以看到, 服务已启用但是未激活:
> > ```
> > ○ clash-core-service.service - Clash core service created by Clash for Windows
> >      Loaded: loaded (/usr/lib/systemd/system/clash-core-service.service; enabled; preset: disabled)
> >      Active: inactive (dead)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 启动服务，并再次查看服务状态。
> > ```shell
> > $ sudo systemctl start clash-core-service
> > $ sudo systemctl status clash-core-service.service
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 输出结果如下：
> > ```
> > ● clash-core-service.service - Clash core service created by Clash for Windows
> >      Loaded: loaded (/usr/lib/systemd/system/clash-core-service.service; enabled; preset: disabled)
> >      Active: active (running) since Mon 2023-02-06 16:06:01 +08; 42s ago
> >    Main PID: 4456 (clash-core-serv)
> >       Tasks: 5 (limit: 11789)
> >      Memory: 1.1M
> >         CPU: 4ms
> >      CGroup: /system.slice/clash-core-service.service
> >              └─4456 /opt/clashwin/resources/static/files/linux/x64/service/clash-core-service
> > 
> > Feb 06 16:06:01 fedora systemd[1]: Started clash-core-service.service - Clash core service created by Clash for Windows.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 可以看到，服务成功启动。
> > ## 最后
> > 重新启动或注销重新登陆系统，此时应该可以看到地球图标变绿了，开启 TUN Mode 能正常工作。 **不要再次安装 Service Mode！！** 如果再次安装，需要重新设置服务文件 `/usr/lib/systemd/system/clash-core-service.service` 中的 `ExecStart` 路径
> > 再次查看服务状态。
> > ```shell
> > $ sudo systemctl status clash-core-service.service
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 输出结果如下：
> > ```
> > ● clash-core-service.service - Clash core service created by Clash for Windows
> >      Loaded: loaded (/usr/lib/systemd/system/clash-core-service.service; enabled; preset: disabled)
> >      Active: active (running) since Mon 2023-02-06 16:06:01 +08; 16min ago
> >    Main PID: 4456 (clash-core-serv)
> >       Tasks: 21 (limit: 11789)
> >      Memory: 7.8M
> >         CPU: 500ms
> >      CGroup: /system.slice/clash-core-service.service
> >              ├─4456 /opt/clashwin/resources/static/files/linux/x64/service/clash-core-service
> >              └─4922 /opt/clashwin/resources/static/files/linux/x64/clash-linux -d /home/me/.config/clash
> > 
> > Feb 06 16:06:01 fedora systemd[1]: Started clash-core-service.service - Clash core service created by Clash for Windows.
> > Feb 06 16:08:31 fedora clash-core-service[4456]: 2023/02/06 16:08:31 "GET http://127.0.0.1:53000/stop HTTP/1.1" from 127.0.0.1:52316 - 204 0B in 40.457µs
> > Feb 06 16:11:07 fedora clash-core-service[4456]: 2023/02/06 16:11:07 "GET http://127.0.0.1:53000/stop HTTP/1.1" from 127.0.0.1:33490 - 204 0B in 57.43µs
> > Feb 06 16:13:56 fedora clash-core-service[4456]: 2023/02/06 16:13:56 "GET http://127.0.0.1:53000/stop HTTP/1.1" from 127.0.0.1:47836 - 204 0B in 41.179µs
> > Feb 06 16:14:22 fedora clash-core-service[4456]: 2023/02/06 16:14:22 "GET http://127.0.0.1:53000/ping HTTP/1.1" from 127.0.0.1:42230 - 200 4B in 47.4µs
> > Feb 06 16:14:23 fedora clash-core-service[4456]: 2023/02/06 16:14:23 "GET http://127.0.0.1:53000/stop HTTP/1.1" from 127.0.0.1:42230 - 204 0B in 27.322µs
> > Feb 06 16:14:23 fedora clash-core-service[4456]: 2023/02/06 16:14:23 "POST http://127.0.0.1:53000/start HTTP/1.1" from 127.0.0.1:42230 - 200 49B in 55.946526ms
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 顺利解决，重启系统也能正常使用。
> 
> 谢谢大佬。请问如何升级？我前几天升级后，把 opt 目录下的 clashwin 文件夹删除，下载 CFW 解压到 opt 目录，然后要重新再按照你的方法操作一次。弄得我以后都不敢更新了。

升级和创建clash-core-service.service没关系啊, 例如我之前用的0.20.35的cfw(clash for windows), 解压到/opt/clash/ ,现在我要升级到0.20.37, 就下载对应的release的压缩包, 解压到/opt/clash/ 覆盖原有的文件就好了, 不会影响 .service
