### ISSUE TITLE
[Bug]: 电脑端所有节点均为超时状态

### ISSUE THREAD

**Issue by yangxiaozhao** [Fndroid/clash_for_windows_pkg#3952]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.15

### 操作系统

Windows x64

### 系统版本

windows 10

### 问题描述

机场链接确定有效，流量没有用完，同样的订阅链接，在手机端的clash能正常使用，但是在电脑端所有节点都是超时的，已经试过网上给的各种方法了都没有用

### 复现步骤

clash for windows 0.20.15

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by jaoyina** [comment]
这个多数是你电脑问题，检查下电脑的网络设置。

**Comment by yangxiaozhao** [comment]
发现问题了，是之前设置了本地路由对我的PC机限流，把限流关闭后，就能正常使用了
