### ISSUE TITLE
[Feature Request]: 添加文档链接到*Wiki*页

### ISSUE THREAD

**Issue by ddzzkunye** [Fndroid/clash_for_windows_pkg#3958]
### 功能描述

如题

https://docs.cfw.lbyczf.com/
上面这个链接加到↓这里↓
https://github.com/Fndroid/clash_for_windows_pkg/wiki

**Comment by Fndroid** [comment]
wiki已经很久远没改过很多内容都不对了哦

**Comment by ddzzkunye** [comment]
知道辣
