### ISSUE TITLE
TAP模式无法正常启用

### ISSUE THREAD

**Issue by Andychencn** [Fndroid/clash_for_windows_pkg#396]
您好，我按wiki教程配置的config文件，发现之前没有通过代理的软件仍然没有通过代理。cfw运行时查看网络适配器发现cfw-tap网卡处于“网络电缆被拔出”状态。
我的config文件dns部分配置如下：
![image](https://user-images.githubusercontent.com/54764347/73377259-b5a4fc80-42f9-11ea-8998-72984c195eea.png)
谢谢！

edit 1.30:我看见Dreamacro已经在主程序上添加了fake-ip模式下的tun支持，是否可以考虑在cfw里也添加对应支持，一并解决了udp转发的问题？

**Comment by Fndroid** [comment]
1. dns配置必须在配置文件里不是默认的config.yml里

2. tun不支持windows

**Comment by Andychencn** [comment]
> 1. dns配置必须在配置文件里不是默认的config.yml里
> 2. tun不支持windows

感谢！现在tap模式能正常工作了！
