### ISSUE TITLE
[Bug]: 使用最新版v 0.20.15时clash-win64.exe占满CPU 

### ISSUE THREAD

**Issue by zpengcom** [Fndroid/clash_for_windows_pkg#3962]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

v 0.20.15

### 操作系统

Windows x64

### 系统版本

win11

### 问题描述

使用最新版v 0.20.15时clash-win64.exe占满CPU ，试过卸载重装依然会在启动后立刻占满cpu, 换回旧的版本后正常。

### 复现步骤

试过安装版和解压版都出现问题

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by zpengcom** [comment]
tun模式问题

**Comment by HC-miss** [comment]
我这没开tun模式（主要是提示User did not grant permission），CPU也有大量占用，重启也没用。

**Comment by HC-miss** [comment]
> 我这没开tun模式（主要是提示User did not grant permission），CPU也有大量占用，重启也没用。 关闭代理，CPU就可以降下来。

B站一直加载不出来，导致疯狂建立连接。
![image](https://user-images.githubusercontent.com/40908362/218368570-d9c11ccb-6d2a-45bf-abb5-4fa7c1339568.png)

**Comment by zpengcom** [comment]
的确不是tun问题  我后来不知道怎么操作又正常了。好像重置了系统网络之类的东西

**Comment by zpengcom** [comment]
> > 我这没开tun模式（主要是提示User did not grant permission），CPU也有大量占用，重启也没用。 关闭代理，CPU就可以降下来。
> 
> B站一直加载不出来，导致疯狂建立连接。 ![image](https://user-images.githubusercontent.com/40908362/218368570-d9c11ccb-6d2a-45bf-abb5-4fa7c1339568.png)

你看下 网络连接里 clash新建的clash网络 是不是变成了手动获取IP,  改成自动就好了
