### ISSUE TITLE
clash的配置在哪里能找到呢？[Bug]: 

### ISSUE THREAD

**Issue by xindian720** [Fndroid/clash_for_windows_pkg#3964]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.15

### 操作系统

Windows x64

### 系统版本

windows10

### 问题描述

我以前安装clash到电脑的D：盘下，今天重新在C盘做了系统盘，打开clash软件后，发现里面我所有的订阅链接都没有了，请问一下，我的订阅链接不是在D盘里面吗？难道是在被我格式化了的C盘里面？

### 复现步骤

怎么才能找到我的订阅链接啊，有好多个呢

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by kusiru** [comment]
c盘里

**Comment by yi-Xu-0100** [comment]
> 我以前安装clash到电脑的D：盘下

去以前安装的文件夹下找找，没有就在C盘，可能被格了。

**Comment by xindian720** [comment]
> c盘里

啊啊，那我犯了严重错误了，请问一下，在C：盘的哪个位置了？以后可得记住备份出来了

**Comment by xindian720** [comment]
> > 我以前安装clash到电脑的D：盘下
> 
> 去以前安装的文件夹下找找，没有就在C盘，可能被格了。

啊啊，那我犯了严重错误了，请问一下，在C：盘的哪个位置了？以后可得记住备份出来了

**Comment by yi-Xu-0100** [comment]
@xindian720 去cfw第一个general界面，点home directory跳转

**Comment by Fndroid** [comment]
点 General 里的 Home Directory 里右边的 Open Folder 选项会打开一个叫 clash 的文件夹，这个文件夹备份一下
