### ISSUE TITLE
[Bug]: 配置编辑器缩放会同时影响程序主界面。 

### ISSUE THREAD

**Issue by QS0x01** [Fndroid/clash_for_windows_pkg#3967]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.15

### 操作系统

Windows x64

### 系统版本

Windows 11 专业版 22H2

### 问题描述

编辑配置文件时缩放会同步影响主界面，退出编辑后主界面不还原且不响应缩放快捷键。 

### 复现步骤

0. Setting Editor = Visual Studio Code (不清楚是否生效)
1. Profile -> Parsers
2. Ctrl + 9 放大编辑器
3. 退出后主界面字体也变大了。
4. Ctrl + 0 无反应。
5. Step 1.
6. Ctrl + 0 还原默认缩放比例。
7. 退出后主界面恢复正常。

### 日志文件

/ 无需日志

**Comment by Fndroid** [comment]
目前不支持单独缩放编辑器大小，下个版本会增加一个调整字体大小的设置，缩放是整体的不变
