### ISSUE TITLE
[Bug]:Fail to install service 

### ISSUE THREAD

**Issue by moyuwuhen601** [Fndroid/clash_for_windows_pkg#3968]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.15

### 操作系统

Windows x64

### 系统版本

22621.1194

### 问题描述

当我多次卸载service mode打算再次安装时出现如下错误
<img width="400" alt="image" src="https://user-images.githubusercontent.com/62698541/217142563-9ab2533d-aaef-4ffa-a153-83493fa4f260.png">

### 复现步骤

<img width="400" alt="image" src="https://user-images.githubusercontent.com/62698541/217142627-a057399b-ded4-4b3c-b3f7-1fc21bbe9ff0.png">
<img width="407" alt="image" src="https://user-images.githubusercontent.com/62698541/217142654-64ffbfca-3d25-41f4-b78a-1f8724206ac0.png">

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by eboxatGH** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/3874#issuecomment-1416036895

**Comment by moyuwuhen601** [comment]
> [第3874章（评论）](https://github.com/Fndroid/clash_for_windows_pkg/issues/3874#issuecomment-1416036895)

已经解决，谢谢
