### ISSUE TITLE
代理自动关闭，什么办法都用了

### ISSUE THREAD

**Issue by Qingwang-7** [Fndroid/clash_for_windows_pkg#397]
删除其他软件，监控进程都用了，还是自动关闭

**Comment by Fndroid** [comment]
软件里只有手动开关system proxy会修改，没有其他行为会自动修改了

**Comment by Qingwang-7** [comment]
> 软件里只有手动开关system proxy会修改，没有其他行为会自动修改了
手动打开过一会代理就无法使用了，打开软件刷新一下界面，system proxy自动关闭了

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/312
