### ISSUE TITLE
[Bug]: 一直提示 安装证书警告

### ISSUE THREAD

**Issue by xmokay** [Fndroid/clash_for_windows_pkg#3970]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.15

### 操作系统

Windows x64

### 系统版本

Windows 10

### 问题描述

持续弹如下提示：
![image](https://user-images.githubusercontent.com/9464343/217266744-8a2d7403-a428-4d65-91c0-d6003455845e.png)
通过抓弹窗窗口所属进程，进程属于clash for windows
查看该证书：
![image](https://user-images.githubusercontent.com/9464343/217267464-898858cb-53a2-4fd9-9f02-14e43367001a.png)

### 复现步骤

安装最新版本，不定时弹出这个提示

**Comment by yi-Xu-0100** [comment]
这网址有点问题吧，不确定是否下载的有问题。

**Comment by xmokay** [comment]
> 这网址有点问题吧，不确定是否下载的有问题。

官网下载的。看窗口进程关系，不是浏览器打开网址弹的，是CFW弹的。也可能是我的网络有问题。因为目前为止只在家里电脑发现这个问题。

不排除另外一种可能，什么地方触发了网络验证登录（类似某些开放网络连WiFi弹出网页然你验证手机号）做了劫持造成的。

**Comment by Fndroid** [comment]
你这个profile的证书验证不了
