### ISSUE TITLE
[Question]: 如何清理Fake-ip持久化缓存

### ISSUE THREAD

**Issue by RookieBoy-lgbt** [Fndroid/clash_for_windows_pkg#3976]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.15

### 操作系统

Windows x64

### 系统版本

Win11 22H2

### 问题描述

已在防火墙添加cfw放行
在Settings-Cache-Fake IP Cache中点击clear后提示“Failed with reason: bucket not found”

### 复现步骤

每次点击clear均有此提示

### 日志文件

11:02:07 WRN [CacheFile] flush fakeip failed error=bucket not found

**Comment by Fndroid** [comment]
General - Home Directory - Open Folder 打开的文件夹里有个 cache.db 删掉试试

**Comment by RookieBoy-lgbt** [comment]
> General - Home Directory - Open Folder 打开的文件夹里有个 cache.db 删掉试试

谢谢，看日志应该是删除这个文件后就成功清除缓存了
