### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by TimWan88** [Fndroid/clash_for_windows_pkg#3982]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.15

### 操作系统

Windows x64

### 系统版本

win10 22h2

### 问题描述

从系统代理切换到tun时，相当一部分节点会超时，关闭tun更新订阅或重启clash后恢复。

有人曾经反映过相似issue：https://github.com/Fndroid/clash_for_windows_pkg/issues/3329，但是并没有得到解决

虽然能够解决，但是比较麻烦。如果无法解决的话能否讲解一下出现的原因？

感谢

### 复现步骤

进入clash后，先打开系统代理，再关闭系统代理打开tun并进行测速

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

tun使用默认配置

**Comment by eboxatGH** [comment]
本人新手，我感觉我碰到的问题与#3982 上面描述的症状相似，因为新手外行，不太懂专业术语，就啰嗦描述一下。
以浏览器登陆网站为例，A类网站，无效使用CFW可以打开；B类网站，需要使用CFW才可以打开；
之前，不了解、未曾使用tun时候，电脑开机就一直打开CFW的系统代理，A类、B类网站都可以顺利打开；
现在，安装了Service Mode，打开tun之后，A类网站大多数情况卡顿或打不开（这个症状叫“节点超时”吗？我不懂这个术语的定义），B类网站可以顺利打开。
不知道如何解决，目前，只好很笨的办法，在需要时，打开tun；等到要登录A类网站时，再关闭tun，每次都是手工调节使用。
期待高手指教，解决这个难题。
谢谢了！

**Comment by yi-Xu-0100** [comment]
所以为啥要用 tun 呢? 系统代理一直是首选，也可以 tun 和系统代理都开，会优先走系统代理。

至于排查问题，给出日志，看看报错信息。可能的原因，与 tun 设置的 dns 和 windows 的网络设置有关

**Comment by eboxatGH** [comment]
多谢这么快速的回复！
我也学到了一条新知识：【tun 和系统代理都开，会优先走系统代理。】
您问得好，其实，从开始使用CFW以来都是在使用系统代理，浏览网站什么的，都没碰到问题，所以，本人对Tun也完全无知，都是设定CFW随PC开机自动启动、默认打开系统代理。
直到最近，碰到一个问题。
情况是这样的，有一个PC应用软件，之前，可以在打开CFW系统代理时正常使用，如果关闭CFW则完全无法使用；近期那个软件升级后，在只打开CFW系统代理时，始终显示“同步”失败，就是“同步”时被Block了。
为这个难题，第一次摸索来到这个论坛/社区，然后看到一个说法，说，有些PC软件不走“系统代理”，可以通过设置tun解决。
尝试设置了tun，结果还真的有效果，那个PC软件在CFW打开tun时，可以“同步”了。
所以，使用CFW的tun模式，倒不是为了赶时髦或者胡乱尝试，而是有需要、被迫尝试的办法。
目前，本人的笨办法是：
1）PC开机，自动启动CFW，默认打开系统代理+关闭tun；
2）要运行那个特定的软件时，就手动打开tun；
3）要登陆A类网站，就手动关闭tun
虽然 手动调节费时、很笨拙，但毕竟还可以在想要运行的时候，都能运行起来。
所以，还是要感谢在这个社区学到了如何使用tun模式，否则，那个软件无法运行才是最大棘手的难题。
当然，现在是 想尝试，看看有无更理想的解决方案。

**Comment by TimWan88** [comment]
![image](https://user-images.githubusercontent.com/108615198/218008771-fd665e43-ab5c-48e5-88be-f1298433a084.png)
这是日志，看着没有问题

**Comment by TimWan88** [comment]
> 所以为啥要用 tun 呢? 系统代理一直是首选，也可以 tun 和系统代理都开，会优先走系统代理。
> 
> 至于排查问题，给出日志，看看报错信息。可能的原因，与 tun 设置的 dns 和 windows 的网络设置有关

想问只是因为不知道能否解决，也不知道出现原因，浑身难受ヾ(•ω•`)o
