### ISSUE TITLE
[Bug]: 关闭Tun后，DNS被改为6.6.6.6导致无法上网

### ISSUE THREAD

**Issue by Murasame233** [Fndroid/clash_for_windows_pkg#3983]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.15

### 操作系统

macOS amd64(Intel)

### 系统版本

Monetary

### 问题描述

开启UU加速器时dns为6.6.6.6，关闭后为运营商dns，开启clash tun模式dns变为设置的 8.8.8.8，关闭后变成了6.6.6.6。

### 复现步骤

开uu加速器，别退出，开启tun模式，clash内核记住了原dns为6.6.6.6，关闭，dns还原为6.6.6.6.
从此之后，哪怕把uu加速器卸载了，clash依然会认为原dns为6.6.6.6

### 日志文件

日志中无任何dns变更信息

**Comment by Fndroid** [comment]
开tun前把dns改掉，关闭tun之后不会恢复成你改的吗

**Comment by Ruth-Seven** [comment]
我也有这个问题

**Comment by Ruth-Seven** [comment]
疯狂修改为6.6.6.6

**Comment by Ruth-Seven** [comment]
我吐了 有没有什么补救方法，每次开关wifi都要重新设置dns，怎么清楚clash数据，我真的吐了

**Comment by yi-Xu-0100** [comment]
@Ruth-Seven setting 右上角 reset all settings 不知道行不行

**Comment by Fndroid** [comment]
删掉 ~/Library/Application Support/Clash for Windows 这个文件夹试试

**Comment by Ruth-Seven** [comment]
> 删掉 ~/Library/Application Support/Clash for Windows 这个文件夹试试

好吧，最近我一直都尽量避免同时用tun和uu，这种现象少多了。

**Comment by Murasame233** [comment]
> 删掉 ~/Library/Application Support/Clash for Windows 这个文件夹试试

最好的方法是避免两个一起用，单独使用clash，而不用clash for windows也会有此问题，删除也没用
