### ISSUE TITLE
[Feature Request]: 需要一个TUN模式下修改DNS的enhanced-mode的功能

### ISSUE THREAD

**Issue by hundan2015** [Fndroid/clash_for_windows_pkg#3985]
### 功能描述

现在在TUN模式中默认使用fake-ip模式，但是在很多情况下fake-ip不能很好的工作，需要normal或者其他模式来访问。例如在Quest 2链接热点局域网的时候，fake-ip模式会导致网络连接受限。在本项目其他Bug中有关DNS的Bug也大概是和这个问题相关。

### 其他内容

顺便提供一个临时解法：启动TUN模式的时候windows会提供一个Clash网卡。在这种情况下打开网卡的IPv4设置，修改dns为8.8.8.8或者114.114.114.114即可解决问题

**Comment by yi-Xu-0100** [comment]
- #3797
