### ISSUE TITLE
「问题」v2ray 协议改成 tcp + tls 就 ping 不通了

### ISSUE THREAD

**Issue by wenfangdu** [Fndroid/clash_for_windows_pkg#3986]
v2ray 服务器 tcp 可以连接，改成 tcp + tls 就 ping 不通了，一直 timeout，在 app 里没找到设置 tls allowInsecure 的选项，请问如何处理呢？

**Comment by QS0x01** [comment]
非 cfw issue，建议问你的服务提供方是否支持或者到 core 那提。
————————————————————————————
另外看了你提的其它几个 issue，**个人建议**不懂就别瞎改保持默认，确认是 cfw 问题而不是你的问题再开 issue。

**Comment by wenfangdu** [comment]
`tls: true` 的 proxy 加上 `skip-cert-verify: true` 就可以了。
