### ISSUE TITLE
「问题」关于文档的疑问

### ISSUE THREAD

**Issue by wenfangdu** [Fndroid/clash_for_windows_pkg#3988]
> [最后一行对应系统中“请勿将代理服务器用于本地(Intranet)地址”选项，请确保此项在最底部](https://docs.cfw.lbyczf.com/contents/bypass.html)

请问这个 tip 还有效不，我尝试了新增 baidu.com 到最后一行，似乎没有什么影响，之前的最后一行是 240.0.0.0/4。

**Comment by yi-Xu-0100** [comment]
这是系统设置里系统代理那里的说法，如果你没有问题，那就不要管，等有问题的时候记得可能是这个问题导致的就行。
