### ISSUE TITLE
[Bug]: v0.20.16 的tun模式下，IPv6不工作

### ISSUE THREAD

**Issue by baraja** [Fndroid/clash_for_windows_pkg#3990]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.16

### 操作系统

Linux

### 系统版本

Fedora 37

### 问题描述

更新为该版本后，tun模式下原先正常使用的IIPv6节点全部离线
关闭tun模式，则IPv6节点正常
退回到上一个版本v0.20.15，继续使用tun模式，IPv6节点也正常

### 复现步骤

fedora 37系统，开启tun，测试节点，会发现所有IPv6节点测不通

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
试试直接用core，可能是core的原因。

**Comment by baraja** [comment]
> 试试直接用core，可能是core的原因。

谢谢，看了core的更新日志有一条

block ipv6 to clash for auto-route

确实是core的改动，我把这个关了

**Comment by huang5307** [comment]
> > 试试直接用core，可能是core的原因。
> 
> 谢谢，看了core的更新日志有一条
> 
> block ipv6 to clash for auto-route
> 
> 确实是core的改动，我把这个关了

请问要怎么设定ipv6才能正常执行？
