### ISSUE TITLE
[Bug]: 一直全屏化且无法任意缩放

### ISSUE THREAD

**Issue by HggDemo** [Fndroid/clash_for_windows_pkg#3992]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.16

### 操作系统

Windows x64

### 系统版本

22H2最新版

### 问题描述

笔记本2k屏幕，125%缩放下，软件打开一直全屏，无法缩放窗口，很难受
![image](https://user-images.githubusercontent.com/52238701/218228602-32a798ad-93e4-48f0-89f8-2240527a708b.png)

### 复现步骤

重新解压也一直全屏化，无法缩放窗口！！！

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by lus-zzz** [comment]
兄弟 怎么解决的 昨天 用的 好好的 今天也出现这种情况了 重装都没用 我是没有改缩放
