### ISSUE TITLE
压缩包版本和EXE版本有不同的文件, 用处是什么?

### ISSUE THREAD

**Issue by ddzzkunye** [Fndroid/clash_for_windows_pkg#3997]
压缩包版本和EXE版本有不同的文件, 用处是什么?
好奇问问.
![image](https://user-images.githubusercontent.com/92249100/218255023-139d9e24-89fa-41b5-9bb8-0890eac978bc.png)

**Comment by yi-Xu-0100** [comment]
一个是安装版，一个直接用的

**Comment by ddzzkunye** [comment]
> 一个是安装版，一个直接用的

啊, 我当然知道, 我是说安装之后文件有差异, 两个dll 和一个EXE, 

> 压缩包版本和EXE版本有不同的文件, 用处是什么? 好奇问问. ![image](https://user-images.githubusercontent.com/92249100/218255023-139d9e24-89fa-41b5-9bb8-0890eac978bc.png)

**Comment by leafsoul365** [comment]
> 

exe应该是软件运行权限相关。libEGL动态库文件应该与定义安装方式有关。
一个软件通过常规安装方式运行和绿色免安装方式运行，必然要有区别，否则哪里还用得着安装。你不去户籍处登记，自然要带点特别许可证

**Comment by ddzzkunye** [comment]
> exe应该是软件运行权限相关。libEGL动态库文件应该与定义安装方式有关。 一个软件通过常规安装方式运行和绿色免安装方式运行，必然要有区别，否则哪里还用得着安装。你不去户籍处登记，自然要带点特别许可证

exe没查到什么，好像是用来提权？
多出文件的是安装版，dll我查了一下两都是绘图api？

**Comment by yi-Xu-0100** [comment]
~~要不问问神奇的electron?~~

**Comment by Fndroid** [comment]
elevate.exe是选择安装给所有用户的情况下提权用的
