### ISSUE TITLE
[Bug]: Connection sort by "Download Speed" display error in v0.20.16

### ISSUE THREAD

**Issue by rbbt065** [Fndroid/clash_for_windows_pkg#4003]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.16

### 操作系统

Windows x64

### 系统版本

Win11 Pro 22H2

### 问题描述

Connections that have the fast download speed show in the bottom of the connection lists
![微信截图_20230212144713](https://user-images.githubusercontent.com/84926161/218297173-8b692291-535e-45dc-a3a6-74fd7c59bcec.png)

### 复现步骤

...

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
click it one more time to reverse
