### ISSUE TITLE
请问该如何配置tap能够对其产生正常网络访问？

### ISSUE THREAD

**Issue by CANYUEHUAYU** [Fndroid/clash_for_windows_pkg#401]
请问能不能说详细点配制tap的问题，我老是失败。不晓得你是如何配置的，我是这样配置的C:\Users\用户名.config\clash\profiles下的yml进行添加了
experimental:
send-through: 127.0.0.1:7891 # 192.168.xxx.xxx 为当前设备的局域网地址，:0 不要漏掉
dns:
enable: true
enhanced-mode: fake-ip # 可以使用 redir-host 模式
listen: :53
nameserver:
- 8.8.8.8
其余没动网络设置还是ip1.0.0.1 子网掩码255.255.255.0 dns127.0.0.1
啥都没碰，现目前网络cfw-tap无网络都是，但是字节再跑。然后clash for windows的流量检查为0，但是网络能上。具体是要怎么配才对，配了好久。

**Comment by CANYUEHUAYU** [comment]
我也试过吧127.0.0.1：7891改成家里的路由器的所在的局域网地址也还是不行

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
