### ISSUE TITLE
[Feature Request]: Connections 页面单个 connection 详情页添加 copy 按钮

### ISSUE THREAD

**Issue by yi-Xu-0100** [Fndroid/clash_for_windows_pkg#4010]
### 功能描述

![image](https://user-images.githubusercontent.com/25523606/218620850-5297b22c-4642-44a9-bd98-6ce26725311a.png)

**Comment by yi-Xu-0100** [comment]
于 v0.20.17 版本中添加。

![image](https://user-images.githubusercontent.com/25523606/221121936-a6e41051-6df7-4922-811f-a28e1087b130.png)

**Comment by WangHaonie** [comment]
这功能确实不错，但如果能做一个反馈动画就更好了，当点击 Copy 时显示 Copied 同时按钮背景也会变绿色，然后在3秒后又变回灰色的 Copy。另外就是当鼠标悬停在按钮上时应该是 <img src="https://user-images.githubusercontent.com/68315280/221357442-4350f366-19bd-4974-be37-51e0cb66c430.png" height="16px"> 而不是 <img src="https://user-images.githubusercontent.com/68315280/221357779-5b9aed4a-0223-4562-a6d8-0ad4e576b7ad.png" height="16px">。

**Comment by yi-Xu-0100** [comment]
@WangHaonie 点击之后，会有windows通知。
