### ISSUE TITLE
[Feature Request]: 允许隐藏 *复制URLMD5*

### ISSUE THREAD

**Issue by ddzzkunye** [Fndroid/clash_for_windows_pkg#4013]
### 功能描述

添加一个设置允许隐藏编辑器中的 *复制URLMD5*

### 其他内容

![image](https://user-images.githubusercontent.com/92249100/218714466-864f0c19-bd28-4563-8b83-1b7ae2a1179e.png)

**Comment by yi-Xu-0100** [comment]
一般不会一直看配置编辑界面吧（

**Comment by ddzzkunye** [comment]
主要是容易误触
改成ctrl+点击之类的操作也是一种方法
