### ISSUE TITLE
Win10 运行显示代码窗口，不知是缺失什么

### ISSUE THREAD

**Issue by chinsansan** [Fndroid/clash_for_windows_pkg#4019]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.16

### 操作系统

Windows x64

### 系统版本

Windows 10

### 问题描述

![clash-error-win.png](https://s1.locimg.com/2023/02/15/fd42c0ed7055f.png)

从 release 下载 [Clash for windows 0.20.16-win.7z](https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.20.16/Clash.for.Windows-0.20.16-win.7z)
解压后双击 clash.exe 运行，就显示上图所示的界面，感觉像缺失了什么。

### 复现步骤

我不知道。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
确定解压了，在解压后的exe打开的吧，我看你后面的界面还是解压软件的界面。

**Comment by chinsansan** [comment]
确实没解压，直接在压缩里打开的。谢谢。😂

**Comment by alvin-0313** [comment]
我也出现了类似的问题，开机首次启动clash，它的窗口就会变成这样。版本是0.20.17。重新安装后问题依旧存在。
