### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lumping** [Fndroid/clash_for_windows_pkg#4020]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.15

### 操作系统

Windows x64

### 系统版本

win10 22H2 专业版

### 问题描述

我们可以用宽带账户密码有线拨号上网，或者通过路由器的wifi进行上网
使用宽带账户密码直接拨号上网，左下角显示connected，但是没有办法上外网，
如果切换到wifi，就可以上外网
日志文件看起来是正常的

### 复现步骤

第一次使用拨号方式直接进行有线上网，无法连接到外网
第二次使用路由器的wifi进行上网，可以连接外网

### 日志文件

<details><summary>logs</summary><p>

12:24:10 INF [API] listening addr=127.0.0.1:15493
12:24:10 INF [Inbound] Mixed(http+socks) listening addr=127.0.0.1:7890
12:24:11 INF [Config] initial compatible provider name=📺 Disney
12:24:11 INF [Config] initial compatible provider name=🎬 iQiyi
12:24:11 INF [Config] initial compatible provider name=Final
12:24:11 INF [Config] initial compatible provider name=AmyTelecom
12:24:11 INF [Config] initial compatible provider name=🎬 myTVSUPER
12:24:11 INF [Config] initial compatible provider name=Hijacking
12:24:11 INF [Config] initial compatible provider name=📟 Twitter
12:24:11 INF [Config] initial compatible provider name=📺 International-Media
12:24:11 INF [Config] initial compatible provider name=🎬 Emby
12:24:11 INF [Config] initial compatible provider name=🖥 Learning
12:24:11 INF [Config] initial compatible provider name=🍎 Apple
12:24:11 INF [Config] initial compatible provider name=China-Media
12:24:11 INF [Config] initial compatible provider name=🌐 Google
12:24:11 INF [Config] initial compatible provider name=📺 Netflix
12:24:11 INF [Config] initial compatible provider name=🖥 Microsoft
12:24:11 INF [Config] initial compatible provider name=🎬 YouTube
12:24:11 INF [Config] initial compatible provider name=China-Websites
12:24:11 INF [Config] initial compatible provider name=📲 LineTV
12:24:11 INF [Config] initial compatible provider name=🎵 Tiktok
12:24:11 INF [Config] initial compatible provider name=🎬 Bilibili
12:24:11 INF [Config] initial compatible provider name=📲 Telegram
12:24:11 INF [DNS] server listening addr=127.0.0.1:8853

</p></details>

### 其他补充

其他使用的是默认的配置

**Comment by yi-Xu-0100** [comment]
拨号上网好像有自己的代理配置，需要设置一下，然后检查下拨号上网设置的名称是否是中文，改成英文

**Comment by lumping** [comment]
> 拨号上网好像有自己的代理配置，需要设置一下，然后检查下拨号上网设置的名称是否是中文，改成英文

感谢，就是宽带名称中文出的问题，已解决，谢谢
