### ISSUE TITLE
[Bug]: clash不能使用

### ISSUE THREAD

**Issue by cleaumtumn** [Fndroid/clash_for_windows_pkg#4024]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.15

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

![QQ截图20230216155602](https://user-images.githubusercontent.com/96287662/219303641-7ca078e3-2f7d-4af8-a7a8-1c4f9da56d33.png)
当进行网络配置时，一直出现“无法切换到此配置文件！”和“错误：timeout of 1000ms exceed”.

### 复现步骤

我也不太清楚

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by cleaumtumn** [comment]
> 

系统版本是win10

**Comment by chenmo2333333** [comment]
同样发生此问题，一台win10电脑出现该问题，其他设备均能正常使用
