### ISSUE TITLE
节点有速度，但日志和连接都没有显示

### ISSUE THREAD

**Issue by Gaoshu728** [Fndroid/clash_for_windows_pkg#4034]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.2

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

![1676646372160](https://user-images.githubusercontent.com/57578456/219690406-3b319f20-a1f3-477e-919a-f94a270a939b.png)
![1676646405501](https://user-images.githubusercontent.com/57578456/219690556-7252ec2d-19b5-4d38-bf4d-c9692112ed98.png)
![1676646445669](https://user-images.githubusercontent.com/57578456/219690767-81266c8a-c23b-4554-a7dc-e7c011543f2c.png)
![1676646454780](https://user-images.githubusercontent.com/57578456/219690787-de552f8c-4c3a-4ee1-a432-a190d9bbad82.png)

### 复现步骤

![1676646535527](https://user-images.githubusercontent.com/57578456/219691079-cf75c333-6eb6-4d5d-92a8-a309ecc1a375.png)

### 日志文件

<details><summary>logs</summary><p>

```
22:31:05 INF [API] listening addr=127.0.0.1:62007
22:31:05 INF [Inbound] Mixed(http+socks) listening addr=[::]:7890
```

</p></details>

**Comment by RayYoh** [comment]
我的使用一段时间也有这个问题，然后无法访问外网，其他设备是正常的，请问你怎么解决的

**Comment by Gaoshu728** [comment]
没有解决 尝试了网络重置 重新配置节点等方案都没有用 @RayYoh

**Comment by RayYoh** [comment]
> 

我每次重启下电脑，就又行了

**Comment by Sakuzy0** [comment]
在开着系统代理的时候，到win的使用代理服务器那看是否也开着，如果是打开的，那点设置看是否是127.0.0.1和7890

**Comment by Gaoshu728** [comment]
> 在开着系统代理的时候，到win的使用代理服务器那看是否也开着，如果是打开的，那点设置看是否是127.0.0.1和7890

谢谢！这里确实有问题，之前设置过这里，但是一旦退出修改界面又会自动关闭无法使用，正在查找解决方案

**Comment by Gaoshu728** [comment]
> 在开着系统代理的时候，到win的使用代理服务器那看是否也开着，如果是打开的，那点设置看是否是127.0.0.1和7890

谢谢你！非常感谢，发现了是权限的问题，只要用管理员身份打开clash就可以完美解决！感谢你提供的思路，这个问题真的困扰我好几天了！！

**Comment by Gaoshu728** [comment]
> > 
> 
> 我每次重启下电脑，就又行了

你好！不知道你的问题解决没有，我的是权限问题，只要给clash管理员权限就可以了，希望对你也有用！

**Comment by RayYoh** [comment]
> > > 
> > 
> > 
> > 我每次重启下电脑，就又行了
> 
> 你好！不知道你的问题解决没有，我的是权限问题，只要给clash管理员权限就可以了，希望对你也有用！

重启了两次，暂时没问题了
