### ISSUE TITLE
tun模式跟系统代理冲突，只能开一个，一般开系统代理不要开其他，开tun+mix就关掉系统代理

### ISSUE THREAD

**Issue by exsaier** [Fndroid/clash_for_windows_pkg#4039]
tun模式跟系统代理冲突，只能开一个，一般开系统代理不要开其他，开tun+mix就关掉系统代理

_Originally posted by @ayuayue in https://github.com/Fndroid/clash_for_windows_pkg/issues/4038#issuecomment-1435714558_
          
我系统代理关掉也是这样 tun模式 MIX也这样
tun+mix也连不上
![image](https://user-images.githubusercontent.com/125750483/219878085-dbe840eb-d86d-4c22-be7f-4a4ca7bf5a16.png)

**Comment by Wrandz** [comment]
我试过两个同时开，没有问题呀
