### ISSUE TITLE
通过cfw启动第三方应用的问问题

### ISSUE THREAD

**Issue by XiaoHuoZZ** [Fndroid/clash_for_windows_pkg#404]
你好，由于现在trojan没有很好的客户端UI，我用cfw来启动trojan并且分流感觉非常好用，但是一般用到十几分钟后，trojan进程就会假死。我在cfw-child-process下opions中把detached设置为true就不会出现这种问题，但是会跳出trojan的控制台，不是很完美。猜测是trojan进程的log输出叠加导致子进程卡死？请问有没有更好的解决方案，谢谢

**Comment by Fndroid** [comment]
如果是log输出问题，为什么不试试把trojan的log关闭呢
