### ISSUE TITLE
[Bug]: 自动安装tun网卡。

### ISSUE THREAD

**Issue by rockxcn** [Fndroid/clash_for_windows_pkg#4045]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.14

### 操作系统

Windows x64

### 系统版本

21H2

### 问题描述

已经卸载了cfw，删除了tun网卡，重启后tun网卡还是会自动加载驱动。
<img width="497" alt="image" src="https://user-images.githubusercontent.com/2076758/220013485-1a793390-356c-468f-a4cb-b0d188fcd910.png">

### 复现步骤

Service Mode安装后点开tun模式，不管状态如何，tun网卡都会自动加载存在。无法卸载。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
重新装下 CFW ，卸载 service mode 试试。

或者直接去系统计划任务看看，有没有相关的计划任务。

还有就是检查下是否安装了不同位置的 CFW。

**Comment by rockxcn** [comment]
关闭了service mode，反复卸载重装过。都存在这个问题。tun这个网卡无法删掉。
系统计划中看不到有相关的计划任务。
现在就是不清楚这个tun网卡自动安装是怎么调用的。

**Comment by rockxcn** [comment]
全盘搜索了下wintun.dll这个文件，发现是还有另外一个文件夹存在，已经解决了。谢谢
