### ISSUE TITLE
建议客户端"Logs"页面的日志记录添加时间排序选择

### ISSUE THREAD

**Issue by fe6520** [Fndroid/clash_for_windows_pkg#405]
平时看日志都是看最近时间的日志比较多，但是目前客户端排序都是最近时间排在最后，每次都要翻很多页才能看到自己想看的日子。望作者添加选择排序功能。谢谢！
![abc](https://user-images.githubusercontent.com/18222783/73907809-a2d68d00-48e2-11ea-84da-75f7e4e66b70.png)

**Comment by Fndroid** [comment]
用clear/start/stop按钮控制

**Comment by fe6520** [comment]
> 用clear/start/stop按钮控制

谢谢，目前查看日志是用的这种方法。
