### ISSUE TITLE
[Feature Request]: 节点增加搜索

### ISSUE THREAD

**Issue by cyleonebk** [Fndroid/clash_for_windows_pkg#4054]
### 功能描述

节点选择建议增加一个搜索框,节点太多有时候找到一个节点很困难。
比如搜索“香港”就把香港节点全部过滤出来，提高节点选择效率。

**Comment by Fndroid** [comment]
<img width="850" alt="image" src="https://user-images.githubusercontent.com/16091562/221084497-d775e6df-0f9d-496e-bed7-73d38d6bf5cf.png">
打开之后 Proxies 右下角会出现搜索框
