### ISSUE TITLE
走了这个程序之后影响多线程性能

### ISSUE THREAD

**Issue by 12697459** [Fndroid/clash_for_windows_pkg#406]
![image](https://user-images.githubusercontent.com/21971550/73917923-6bc0a580-48fb-11ea-93ed-f26ba740686a.png)
开了之后用IDM下载只有1-2个线程，没开的时候可以跑满32个线程

**Comment by Fndroid** [comment]
不会影响多线程下载，我觉得是你的这个下载请求被代理了，代理被对方服务器检测到了然后限制了

**Comment by 12697459** [comment]
> 不会影响多线程下载，我觉得是你的这个下载请求被代理了，代理被对方服务器检测到了然后限制了

我试了好多下载都是这样，并且确定走的是直连，没有经过代理服务器。
下图是用IDM从酷安下载王者荣耀。
![image](https://user-images.githubusercontent.com/21971550/74079951-2a560480-4a79-11ea-8ba5-4c125f110332.png)
![image](https://user-images.githubusercontent.com/21971550/74079970-7bfe8f00-4a79-11ea-8b16-57d5b7a8db9e.png)

当我关掉这个程序之后：
![image](https://user-images.githubusercontent.com/21971550/74079977-9afd2100-4a79-11ea-9ed0-dea079281c11.png)

**Comment by Fndroid** [comment]
更新下CFW和IDM吧，我这里复现不出来
