### ISSUE TITLE
无法切换到此配置文件invalid mode: redir-host

### ISSUE THREAD

**Issue by Ealsen** [Fndroid/clash_for_windows_pkg#4065]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.17

### 操作系统

Windows x64

### 系统版本

win 10

### 问题描述

我从0.20.16版本更新后，就发现我的配置列表没了然后点击就弹出这个
![image](https://user-images.githubusercontent.com/111371035/221338755-ad8a3dba-620e-4acf-a07b-faf7e3497f9a.png)
我该怎么办

### 复现步骤

从版本0.20.16更新至0.20.17

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

可能是我更新的时候删除了config.yml文件导致无法自动切换enhanced-mode: fake-ip
该怎么解决

**Comment by Ealsen** [comment]
看不懂英文

**Comment by Ealsen** [comment]
原因:
* 新版的clash现在只支持fake-ip模式。你的配置文件里用的是redir-host，不支持，要不你就用老版本的核心吧。如果能够修改增强模式（enhanced-mode）的话，可以设置为fake-ip。

已经解决，可以把配置文件中的enhanced-mode: redir-host改成enhanced-mode: fake-ip，就不会出现这个提示，仍能正常使用，不过更新订阅还是要重新改一次

解决来源：
https://github.com/Dreamacro/clash/issues/2559

**Comment by Ealsen** [comment]
> 原因:
> 
> * 新版的clash现在只支持fake-ip模式。你的配置文件里用的是redir-host，不支持，要不你就用老版本的核心吧。如果能够修改增强模式（enhanced-mode）的话，可以设置为fake-ip。
> 
> 已经解决，可以把配置文件中的enhanced-mode: redir-host改成enhanced-mode: fake-ip，就不会出现这个提示，仍能正常使用，不过更新订阅还是要重新改一次
> 
> 解决来源： [Dreamacro/clash#2559](https://github.com/Dreamacro/clash/issues/2559)



问题还是没有解决，最新版0.20.17的配置文件中的enhanced-mode不会自动变成enhanced-mode: fake-ip

**Comment by Ealsen** [comment]
> > 原因:
> > 
> > * 新版的clash现在只支持fake-ip模式。你的配置文件里用的是redir-host，不支持，要不你就用老版本的核心吧。如果能够修改增强模式（enhanced-mode）的话，可以设置为fake-ip。
> > 
> > 已经解决，可以把配置文件中的enhanced-mode: redir-host改成enhanced-mode: fake-ip，就不会出现这个提示，仍能正常使用，不过更新订阅还是要重新改一次
> > 解决来源： [Dreamacro/clash#2559](https://github.com/Dreamacro/clash/issues/2559)
> 
> 问题还是没有解决，最新版0.20.17的配置文件中的enhanced-mode不会自动变成enhanced-mode: fake-ip

好像是我的clash缺少了config.yml文件
当我现在没有办法恢复

**Comment by Ealsen** [comment]
![image](https://user-images.githubusercontent.com/111371035/221342247-0bf9e386-0165-40e0-83f3-71b7457e8ce3.png)

最后好像是机场的问题了

**Comment by Ealsen** [comment]
![Uploading image.png…]()

**Comment by Ealsen** [comment]
![image](https://user-images.githubusercontent.com/111371035/221342313-fdade8ef-3853-4c5f-9c00-f68d9af3f304.png)

**Comment by kingcard1131** [comment]
我的改成fake ip也不行

**Comment by Ealsen** [comment]
> 我的改成fake ip也不行，自动设置成fake ip的


确实，可以使用低版本的。

**Comment by kingcard1131** [comment]
> > 我的改成fake ip也不行，自动设置成fake ip的
> 
> 确实，可以使用低版本的。

我退回到20.16了。但是这个问题没解决啊，怎么close了？不知道啥问题，我看相关问题都close了，说用上一个版本，哈哈哈

**Comment by Ealsen** [comment]
> > > 我的改成fake ip也不行，自动设置成fake ip的
> > 
> > 确实，可以使用低版本的。
> 
> 我退回到20.16了。但是这个问题没解决啊，怎么close了？不知道啥问题，我看相关问题都close了，说用上一个版本，哈哈哈

大概就是软件版本太新，机场配置文件没有跟上，有有一些治标不治本的方法，目前最好的方法就是低版本

**Comment by Initial01LingXu** [comment]
> 我的改成fake ip也不行，自动设置成fake ip的

是改成fake-ip

**Comment by Ealsen** [comment]
> > 我的改成fake ip也不行，自动设置成fake ip的
> 
> 是改成fake-ip

最后还是会变成原样

**Comment by Initial01LingXu** [comment]
确实，每次刷新都会从机场那里获取，又被改回去了，得重新改，但只要不去刷新它就能一直用。

> > > 我的改成fake ip也不行，自动设置成fake ip的
> > 
> > 
> > 是改成fake-ip
> 
> 最后还是会变成原样

确实，每次刷新都会从机场那里获取，又被改回去了，得重新改，但只要不去刷新它就能一直用。

**Comment by Ealsen** [comment]
> > > > 我的改成fake ip也不行，自动设置成fake ip的
> > > 
> > > 
> > > 是改成fake-ip
> > 
> > 最后还是会变成原样
> 
> 确实，每次刷新都会从机场那里获取，又被改回去了，得重新改，但只要不去刷新它就能一直用。

我问过机场的人，他们说是机场配置文件没更新

**Comment by ArendelleLeah** [comment]
我直接改了fake-ip就好了, 还不行的话可以重新下载配置文件试试

**Comment by EddyLee88** [comment]
对, v0.20.17已经不支持redir-host了, 需要使用fake-ip, 应该联系供应商将你们的订阅配置中的dns.enhanced-mode修改为fake-ip;
当然, 也可以使用CFW的预处理配置功能:
```
parsers:
  - url: https://此处替换为你的订阅地址
    yaml:
      commands:
        - dns.enhanced-mode=fake-ip
```
使用以上代码配置预处理配置, 即可每次更新订阅都覆盖enhanced-mode为fake-ip
更多用法可以参考官方文档[配置文件预处理](https://docs.cfw.lbyczf.com/contents/parser.html)
我也是研究了很久才搞定, 希望可以帮到你

**Comment by Ealsen** [comment]
> 对, v0.20.17已经不支持redir-host了, 需要使用fake-ip, 应该联系供应商将你们的订阅配置中的dns.enhanced-mode修改为fake-ip;
> 当然, 也可以使用CFW的预处理配置功能:
> ```
> parsers:
>   - url: https://此处替换为你的订阅地址
>     yaml:
>       commands:
>         - dns.enhanced-mode=fake-ip
> ```
> 使用以上代码配置预处理配置, 即可每次更新订阅都覆盖enhanced-mode为fake-ip
> 更多用法可以参考官方文档[配置文件预处理](https://docs.cfw.lbyczf.com/contents/parser.html)
> 我也是研究了很久才搞定, 希望可以帮到你

感谢您！机场已经更新配置文件了

**Comment by KeFan999** [comment]
> 对, v0.20.17已经不支持redir-host了, 需要使用fake-ip, 应该联系供应商将你们的订阅配置中的dns.enhanced-mode修改为fake-ip; 当然, 也可以使用CFW的预处理配置功能:
> 
> ```
> parsers:
>   - url: https://此处替换为你的订阅地址
>     yaml:
>       commands:
>         - dns.enhanced-mode=fake-ip
> ```
> 
> 使用以上代码配置预处理配置, 即可每次更新订阅都覆盖enhanced-mode为fake-ip 更多用法可以参考官方文档[配置文件预处理](https://docs.cfw.lbyczf.com/contents/parser.html) 我也是研究了很久才搞定, 希望可以帮到你

这个方法有效，谢谢您！

**Comment by wenlittleoil** [comment]
> onfig.yml文件导致无法自动切换enhanced-mode: fak

感谢，我的是macos，用此方法可以。

**Comment by AoThen** [comment]
> 对, v0.20.17已经不支持redir-host了, 需要使用fake-ip, 应该联系供应商将你们的订阅配置中的dns.enhanced-mode修改为fake-ip; 当然, 也可以使用CFW的预处理配置功能:
> 
> ```
> parsers:
>   - url: https://此处替换为你的订阅地址
>     yaml:
>       commands:
>         - dns.enhanced-mode=fake-ip
> ```
> 
> 使用以上代码配置预处理配置, 即可每次更新订阅都覆盖enhanced-mode为fake-ip 更多用法可以参考官方文档[配置文件预处理](https://docs.cfw.lbyczf.com/contents/parser.html) 我也是研究了很久才搞定, 希望可以帮到你

@EddyLee88 
感谢分享,在此基础上,带上全匹配,通杀
```
parsers:
  - reg: '^.*$'
    yaml:
      commands:
        - dns.enhanced-mode=fake-ip
```

**Comment by Darkshadow-create** [comment]
感谢，这些针对parsers的修改确实有效。

**Comment by LingkKang** [comment]
> 在此基础上,带上全匹配,通杀
> 
> ```
> parsers:
>  - reg: '^.*$'
>    yaml:
>      commands:
>        - dns.enhanced-mode=fake-ip
> ```

@AoThen 感谢！！
