### ISSUE TITLE
[Feature Request]: 支持 Clash Meta

### ISSUE THREAD

**Issue by xkww3n** [Fndroid/clash_for_windows_pkg#4066]
### 功能描述

[Clash Meta](https://docs.metacubex.one/) 基于 Clash FOSS，支持原版 Clash FOSS 不支持的 RULE Set, DNS over QUIC, 并发 DNS 解析和 PASS 策略等功能，且完全开源。希望可以添加对该 Fork 的支持。

**Comment by QS0x01** [comment]
开 issue 前不如先搜索下，免得浪费大家时间。

dupe https://github.com/Fndroid/clash_for_windows_pkg/issues/2901

**Comment by Fndroid** [comment]
没有计划
