### ISSUE TITLE
界面适应

### ISSUE THREAD

**Issue by TerriblePanda** [Fndroid/clash_for_windows_pkg#407]
![image](https://user-images.githubusercontent.com/44699887/73926293-5e5ee780-490a-11ea-839e-834eaf228d44.png)

打游戏的时候会自动调整分辨率，然后我的Clash就成这样了，还不能自己调整，只能重启。

**Comment by ShadowLyin** [comment]
同样有这个问题，玩红警2时，游戏内分辨率设置为 800×600 ，出来后所有程序窗口都会集中在左上角，而 CFW 就会变成如图所示的模样，但是重启下软件即可恢复。

**Comment by GrayXu** [comment]
same problem happened when I exit CS:GO with 800*600

**Comment by Fndroid** [comment]
使用最新版，最小化一次恢复
