### ISSUE TITLE
[Bug]: silent start 

### ISSUE THREAD

**Issue by Airuop** [Fndroid/clash_for_windows_pkg#4071]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.17

### 操作系统

Windows x64

### 系统版本

22h2

### 问题描述

silent start dont work 
app window show in every restart 

### 复现步骤

i try to on & off 
but dont work 
every time i see app window in auto  startup

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
Locate the relevant content in the Windows registry, delete it, and then try to reset it.

**Comment by Airuop** [comment]
> Locate the relevant content in the Windows registry, delete it, and then try to reset it.

thanks
but i cant find app in regedit
where is path in regedit?

**Comment by yi-Xu-0100** [comment]
@Airuop `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`

**Comment by Airuop** [comment]
> @Airuop `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`

thanks, 
i try it but problem not solved
i see vfw dashboard in startup

**Comment by yi-Xu-0100** [comment]
1. Do you use the `lightweight` mode? It needs to open the dashboard once.
2. Could you back up the `Home directory`(Find it in General page), and delete it, then reset the app and restart it?
  3. Could you back up the `Cache directory`(`%AppData%\clash_win`), and delete it, then reset the app and restart it?
