### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mayuzhe** [Fndroid/clash_for_windows_pkg#4076]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.17

### 操作系统

Windows x64

### 系统版本

win10-22H2

### 问题描述

安装好以后打不开，显示Windows正在查找clash for Windows.exe，好几个人都这个问题
![7c14232c23c11f4925b1978750d12ec](https://user-images.githubusercontent.com/52539600/221550631-c53a1b3b-020c-4607-a218-5f519637128f.png)

### 复现步骤

![7c14232c23c11f4925b1978750d12ec](https://user-images.githubusercontent.com/52539600/221550692-b1325d42-c75b-4434-86aa-9b8a879899ef.png)

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

根本就进不去软件，这些没法提供，

**Comment by Cindysheep** [comment]
请问是怎么解决的
