### ISSUE TITLE
请问更新profiles时，怎样才能不覆盖自己已编写的规则？

### ISSUE THREAD

**Issue by nssiwi** [Fndroid/clash_for_windows_pkg#408]
每次更新都会覆盖掉

**Comment by nssiwi** [comment]
https://github.com/Fndroid/jsbox_script/wiki/%E5%BC%80%E6%94%BE%E6%8E%A5%E5%8F%A3%E4%BD%BF%E7%94%A8%E5%8F%8A%E8%AF%B4%E6%98%8E#clash%E9%85%8D%E7%BD%AE%E4%BF%AE%E6%94%B9
这里的说明是在服务器端定义，可否实现本地自定义规则，软件使用的规则包含本地规则

**Comment by Fndroid** [comment]
https://fndroid.github.io/clash-config-builder/

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
