### ISSUE TITLE
[Bug]: 每次开机clash for win会弹出到桌面,能否静默启动?

### ISSUE THREAD

**Issue by paopjian** [Fndroid/clash_for_windows_pkg#4086]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.17

### 操作系统

Windows x64

### 系统版本

win10 

### 问题描述

 每次开机clash for win会弹出到桌面, 应该是直接在右下角出现图标才对

### 复现步骤

不清楚

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```
[renderer.log](https://github.com/Fndroid/clash_for_windows_pkg/files/10856620/renderer.log)

</p></details>

**Comment by yi-Xu-0100** [comment]
setting -> silent start

**Comment by nxy1999** [comment]
> setting -> silent start

open or close?when i open it, it dos not work.
