### ISSUE TITLE
第一次安装Clash会因为.config/clash文件夹不存在而导致报错

### ISSUE THREAD

**Issue by Antairez** [Fndroid/clash_for_windows_pkg#409]
Clash版本：0.8.10

<img width="848" alt="image" src="https://user-images.githubusercontent.com/7032726/74046279-3ace9680-4a09-11ea-8dbc-fb4943b0b0d5.png">

问题描述：第一次安装clash的系统一定会报错，导致必须重启Clash否则无法使用，点击Try to repair也没有办法解决问题。

重现方式：
1. 删除文件夹 C:\Users\用户名\\.config\clash
2. 重启Clash
3. 打开Clash主介面
4. 发现报错信息

或
1. 找任何一台没有安装过Clash的电脑，安装Clash
2. 打开Clash主介面
3. 发现报错信息

Log:
```
time="2020-02-08T00:21:22+08:00" level=info msg="Can't find config, create an empty file"
time="2020-02-08T00:21:22+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-02-08T00:21:22+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-02-08T00:21:22+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-02-08T00:21:22+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-02-08T00:21:22+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
```

短期解决方案：
安装完Clash之后运行Clash，退出Clash，再打开Clash就可正常使用

长期解决方案：
未知

**Comment by Antairez** [comment]
@Fndroid 问题重现方式已明确，有空请协助支持，谢谢，辛苦了！

**Comment by Fndroid** [comment]
下个版本修复

**Comment by Antairez** [comment]
> 下个版本修复

感谢！

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.8.11
