### ISSUE TITLE
[Feature Request]: 请问下这个和clash for windows或者clashx 有什么区别啊？

### ISSUE THREAD

**Issue by leslie555** [Fndroid/clash_for_windows_pkg#4091]
### 功能描述

之前有用clash for windows 和clashX, 今天刚发现这个app， 我看star很多， 就下载来试了下， 感觉界面和clash for windows 一样， 没有感觉到有什么特色。 可以把这个app存在的意义写在readme里面吗

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/222321869-83606161-0618-4c73-9fe3-294695179f09.png)

我不知道你用的哪个“Clash for windows”，但我知道这是“Clash for windows”的官方发布地址。

**Comment by vj23456** [comment]
有没有可能你用了李鬼，然后跑正主这来搞笑了？

**Comment by leslie555** [comment]
> ![image](https://user-images.githubusercontent.com/25523606/222321869-83606161-0618-4c73-9fe3-294695179f09.png)
> 
> 我不知道你用的哪个“Clash for windows”，但我知道这是“Clash for windows”的官方发布地址。
 😂😂😂好吧， 我之前用的这个Go语言写的这个https://github.com/Dreamacro/clash，GUI也是写的clash for windows。 然后clashX 是这个地址 https://github.com/yichengchen/clashX.

**Comment by yi-Xu-0100** [comment]
@leslie555 你说有没有种可能，<https://github.com/Dreamacro/clash> 这是 Clash core的地址？而且 README 没提到 Clash for windows 吧。

**Comment by leslie555** [comment]
@yi-Xu-0100 但是下载window版本之后图形界面确实是写的clash for windows

**Comment by yi-Xu-0100** [comment]
@leslie555 所以说，我不知道你在哪下载的 windows 版本，这个只在 GitHub 发布才对。建议检查来源（

**Comment by leslie555** [comment]
@yi-Xu-0100 很有可能当时是从你们这下载的安装包， 然后我误以为是从clash那里安装的， 然后今天整个愣住了，以为本库是增强版，毕竟两三年没去重新下载了。 我刚从前段时间看过的clash for windows的[**文档**](https://docs.cfw.lbyczf.com/) 点击跳转到的也是你们这个repo. 一个月前升级了我windows的clash 版本也确实是0.20.x。 抱歉抱歉😅

**Comment by liusk98** [comment]
> 

@vj23456 李鬼的称呼没必要吧，Dreamacro 也给 ClashX 提交PR了 https://github.com/yichengchen/clashX/pull/114

**Comment by iyu98** [comment]
请看 readme  文件：https://github.com/yichengchen/clashX
ClashX 旨在提供一个简单轻量化的代理客户端，如果需要更多的定制化，可以考虑使用 CFW Mac 版

**Comment by iyu98** [comment]
> 

CFW（Clash for windows）
