### ISSUE TITLE
[Bug]: RuleSet规则失效

### ISSUE THREAD

**Issue by rbbt065** [Fndroid/clash_for_windows_pkg#4092]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.17

### 操作系统

Windows x64

### 系统版本

Win11 22H2

### 问题描述

RuleProvider内配置的规则失效，Clash仅匹配配置文件内规则以及GEOIP类规则(不会匹配配置文件内Rule-Set内的规则)

### 复现步骤

加载配置文件后出现

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

mixin: # object
  dns:
    enable: true
    ipv6: false
    listen: 0.0.0.0:53
    default-nameserver:
      - 114.114.114.114
      - 1.1.1.1
      - 8.8.8.8
    enhanced-mode: fake-ip
    fake-ip-range: 172.31.0.1/16
    fake-ip-filter:
    nameserver:
      - https://223.5.5.5/dns-query
      - https://1.12.12.12/dns-query

  tun:
    enable: true
    stack: system
    dns-hijack:
      - any:53
    auto-route: true
    auto-detect-interface: true

**Comment by yi-Xu-0100** [comment]
日志和规则看看

**Comment by rbbt065** [comment]
> 日志和规则看看

引用规则集：
rule-providers:
  AppleDirectRules:
    type: http
    behavior: domain
    url: "http://example.com/AppleDirectRules.yaml"
    path: ./rule_provider/AppleDirectRules.yaml
    interval: 86400
  AppleProxyRules:
    type: http
    behavior: domain
    url: "http://example.com/AppleProxyRules.yaml"
    path: ./rule_provider/AppleProxyRules.yaml
  DomesticServicesRules:
    type: http
    behavior: domain
    url: "http://example.com/DomesticServicesRules.yaml"
    path: ./rule_provider/DomesticServicesRules.yaml
  GameProcessRules:
    type: http
    behavior: domain
    url: "http://example.com/GameProcessRules.yaml"
    path: ./rule_provider/GameProcessRules.yaml
  OverseaServicesRules:
    type: http
    behavior: domain
    url: "http://example.com/OverseaServicesRules.yaml"
    path: ./rule_provider/OverseaServicesRules.yaml
  StreamingMediaRules:
    type: http
    behavior: classical
    url: "http://example.com/StreamingMediaRules.yaml"
    path: ./rule_provider/StreamingMediaRules.yaml
    interval: 86400

规则文件：
rules:
  - DOMAIN-SUFFIX,tangxm1114.com,DIRECT
  #Microsoft检测联网
  - DOMAIN,dns.msftncsi.com,US
  - DOMAIN,www.msftconnecttest.com,US
  #域名/noresolve类规则集
  - RULE-SET,AppleProxyRules,US
  - RULE-SET,AppleDirectRules,DIRECT
  - RULE-SET,GameProcessRules,DIRECT
  - RULE-SET,StreamingMediaRules,US
  - RULE-SET,DomesticServicesRules,DIRECT
  - RULE-SET,OverseaServicesRules,US
  #T-Mobile WiFi-Calling
  - IP-CIDR,66.94.0.0/19,US
  - IP-CIDR,208.54.0.0/16,US
  - IP-CIDR,206.29.177.36/32,US
  #IP类规则
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - PROCESS-NAME,uu.exe,DIRECT
  - MATCH,US
  
  运行日志：
  15:55:36 INF [Config] start initial provider name=US_Nexitally
15:55:36 INF [Config] start initial provider name=HK_Nexitally
15:55:36 INF [Config] start initial provider name=TW_Nexitally
15:55:36 INF [Config] initial compatible provider name=Backup
15:55:36 INF [Config] initial rule provider name=GameProcessRules
15:55:36 INF [Config] initial rule provider name=OverseaServicesRules
15:55:36 INF [Config] initial rule provider name=StreamingMediaRules
15:55:36 INF [Config] initial rule provider name=AppleDirectRules
15:55:36 INF [Config] initial rule provider name=AppleProxyRules
15:55:36 INF [Config] initial rule provider name=DomesticServicesRules
15:55:36 INF [Inbound] TUN listening iface=Clash gateway=172.31.0.1
15:55:36 DBG [TUN] hijack udp dns addr=172.31.0.2:53
15:55:36 DBG [TCP] accept connection lAddr=172.31.0.1:61205 rAddr=zgdx.tangxm1114.com:6690 inbound=TUN
15:55:36 DBG [TCP] accept connection lAddr=172.31.0.1:61206 rAddr=91.108.56.103:443 inbound=TUN
15:55:36 DBG [Matcher] find process success addr=91.108.56.103 path=\Device\HarddiskVolume3\Program Files\WindowsApps\TelegramMessengerLLP.TelegramDesktop_4.6.3.0_x64__t4vj0pshhgkwm\Telegram.exe
15:55:36 DBG [TCP] accept connection lAddr=172.31.0.1:61207 rAddr=91.108.56.103:80 inbound=TUN
15:55:36 DBG [Matcher] find process success addr=91.108.56.103 path=\Device\HarddiskVolume3\Program Files\WindowsApps\TelegramMessengerLLP.TelegramDesktop_4.6.3.0_x64__t4vj0pshhgkwm\Telegram.exe
15:55:36 DBG [UDP] accept session lAddr=172.31.0.1:63056 rAddr=17.188.178.24:3485 inbound=TUN
15:55:36 DBG [DNS] dns response source=https://1.12.12.12/dns-query qType=A name=topyxys.kumgrb.xyz. answer=["42.157.194.178"]
15:55:36 DBG [Matcher] find process failed error=process not found addr=17.188.178.24
15:55:36 DBG [DNS] dns response source=https://223.5.5.5/dns-query qType=A name=zgdx.tangxm1114.com. answer=["124.114.79.29"]
15:55:36 DBG [DNS] dns response source=https://223.5.5.5/dns-query qType=A name=wsvknsg.iqbuud.lol. answer=["180.101.133.68"]
15:55:36 DBG [TUN] hijack udp dns addr=172.31.0.2:53
15:55:36 DBG [TUN] hijack udp dns addr=172.31.0.2:53
15:55:36 DBG [TUN] hijack udp dns addr=172.31.0.2:53
15:55:36 DBG [TUN] hijack udp dns addr=172.31.0.2:53
15:55:36 DBG [TCP] accept connection lAddr=172.31.0.1:63063 rAddr=45-courier.push.apple.com:5223 inbound=TUN
15:55:36 DBG [Matcher] find process failed error=process not found addr=45-courier.push.apple.com
15:55:36 DBG [DNS] dns response source=https://223.5.5.5/dns-query qType=A name=45-courier.push.apple.com. answer=["17.57.145.170","17.57.145.168","17.57.145.167","17.57.145.164","17.57.145.165","17.57.145.166","17.57.145.172","17.57.145.169"]
15:55:36 DBG [Matcher] resolve success host=45-courier.push.apple.com ip=17.57.145.166
15:55:36 INF [TCP] connected lAddr=172.31.0.1:61205 rAddr=zgdx.tangxm1114.com:6690 mode=rule rule=DomainSuffix(tangxm1114.com) proxy=DIRECT
15:55:36 INF [TCP] connected lAddr=172.31.0.1:61206 rAddr=91.108.56.103:443 mode=rule rule=Match() proxy=US[🇺🇸 USA San Jose 01 [Premium]]
15:55:36 INF [UDP] connected lAddr=172.31.0.1:63056 rAddr=17.188.178.24:3485 mode=rule rule=Match() proxy=US[🇺🇸 USA San Jose 01 [Premium]]
15:55:36 INF [TCP] connected lAddr=172.31.0.1:61207 rAddr=91.108.56.103:80 mode=rule rule=Match() proxy=US[🇺🇸 USA San Jose 01 [Premium]]
15:55:36 INF [TCP] connected lAddr=172.31.0.1:63063 rAddr=45-courier.push.apple.com:5223 mode=rule rule=Match() proxy=US[🇺🇸 USA San Jose 01 [Premium]]
15:55:36 DBG [TUN] hijack udp dns addr=172.31.0.2:53
15:55:36 DBG [TUN] hijack udp dns addr=172.31.0.2:53
15:55:36 DBG [TCP] accept connection lAddr=172.31.0.1:63064 rAddr=49.4.32.130:5223 inbound=TUN
15:55:36 DBG [Matcher] find process failed error=process not found addr=49.4.32.130
15:55:36 INF [TCP] connected lAddr=172.31.0.1:63064 rAddr=49.4.32.130:5223 mode=rule rule=GeoIP(CN) proxy=DIRECT
15:55:37 DBG [TUN] hijack udp dns addr=172.31.0.2:53
15:55:37 DBG [TCP] accept connection lAddr=172.31.0.1:61228 rAddr=client.wns.windows.com:443 inbound=TUN
15:55:37 DBG [Matcher] find process success addr=client.wns.windows.com path=\Device\HarddiskVolume3\Windows\System32\svchost.exe
15:55:37 DBG [DNS] dns response source=https://223.5.5.5/dns-query qType=A name=client.wns.windows.com. answer=["20.198.162.78"]
15:55:37 DBG [Matcher] resolve success host=client.wns.windows.com ip=20.198.162.78
15:55:37 DBG [DNS] dns response source=https://223.5.5.5/dns-query qType=A name=wsvknsg.iqbuud.lol. answer=["180.101.133.68"]
15:55:37 INF [TCP] connected lAddr=172.31.0.1:61228 rAddr=client.wns.windows.com:443 mode=rule rule=Match() proxy=US[🇺🇸 USA San Jose 01 [Premium]]
15:55:37 DBG [TCP] accept connection lAddr=172.31.0.1:61233 rAddr=zgdx.tangxm1114.com:6690 inbound=TUN
15:55:37 DBG [DNS] dns response source=https://223.5.5.5/dns-query qType=A name=zgdx.tangxm1114.com. answer=["124.114.79.29"]
15:55:37 INF [TCP] connected lAddr=172.31.0.1:61233 rAddr=zgdx.tangxm1114.com:6690 mode=rule rule=DomainSuffix(tangxm1114.com) proxy=DIRECT
15:55:37 DBG [DNS] dns response source=https://223.5.5.5/dns-query qType=A name=ss.epdg.epc.mnc260.mcc310.pub.3gppnetwork.org. answer=["208.54.39.131"]
15:55:37 DBG [UDP] accept session lAddr=172.31.0.1:62906 rAddr=ss.epdg.epc.mnc260.mcc310.pub.3gppnetwork.org:4500 inbound=TUN
15:55:37 DBG [Matcher] find process failed error=process not found addr=ss.epdg.epc.mnc260.mcc310.pub.3gppnetwork.org
15:55:38 INF [UDP] connected lAddr=172.31.0.1:62906 rAddr=ss.epdg.epc.mnc260.mcc310.pub.3gppnetwork.org:4500 mode=rule rule=IPCIDR(208.54.0.0/16) proxy=US[🇺🇸 USA San Jose 01 [Premium]]

**Comment by rbbt065** [comment]
> 日志和规则看看
