### ISSUE TITLE
配置文件载入失败问题[Bug]: 

### ISSUE THREAD

**Issue by EliDoves** [Fndroid/clash_for_windows_pkg#4093]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.17

### 操作系统

Windows x64

### 系统版本

Windows11

### 问题描述

想请教一下，忘记从哪个版本开始，自己配置的订阅就开始更新失败，总是提示要么Rule-Provider错误要么就是Proxy-Provider错误，不明白为什么，节点信息是转换的List，规格是托管在github仓库的，整个配置我呢见托管在Gist上面。规格检查了是正确的，之前用是没有问题的，不知道有没有遇到同样问题的。
![image](https://user-images.githubusercontent.com/51412618/222414065-aedaff3a-bb6d-4754-b39d-231641aa1bab.png)

![image](https://user-images.githubusercontent.com/51412618/222414161-20c07047-bfd9-4129-9cff-d23dfced788a.png)

### 复现步骤

*

### 日志文件

*

### 其他补充

*

**Comment by yi-Xu-0100** [comment]
@EliDoves 你这个报错是键值重复了，建议检查下这个关键词。当然也可能是其他引起的。但是你第二个截图和你第一个没关系感觉(

**Comment by EliDoves** [comment]
> @EliDoves 你这个报错是键值重复了，建议检查下这个关键词。当然也可能是其他引起的。但是你第二个截图和你第一个没关系感觉(

噢这个是修改配置文件时候弄错了，改过来了，

其实是这种错误：
![image](https://user-images.githubusercontent.com/51412618/222433153-b8da87d6-ee85-4d0a-9bfe-6fc34625a671.png)

![image](https://user-images.githubusercontent.com/51412618/222433206-78d55d06-6e58-4a0c-a24c-629fe825edda.png)

两个轮流出现

**Comment by yi-Xu-0100** [comment]
@EliDoves 网络请求没成功，建议换成可以直连下载的链接。

**Comment by EliDoves** [comment]
> @EliDoves 网络请求没成功，建议换成可以直连下载的链接。

好的谢谢！

**Comment by Ouguangqing** [comment]
![Uploading image.jpg…]()这个怎么解决，求大佬告知

**Comment by Ouguangqing** [comment]
![Uploading 7FDA4D82-F189-4307-865D-8DDBC2460193.jpeg…]()

**Comment by EliDoves** [comment]
> ![Uploading image.jpg…]()这个怎么解决，求大佬告知
> 
> 

🎣？你这怎么一直显示在上传图片
