### ISSUE TITLE
开启TUN模式后访问本地内网共享网盘会从直连变成代理[Bug]: 

### ISSUE THREAD

**Issue by EliDoves** [Fndroid/clash_for_windows_pkg#4094]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.17

### 操作系统

Windows x64

### 系统版本

Windows11

### 问题描述

开启TUN模式后访问本地内网共享网盘会从直连变成代理，已经在配置文件里面将本地网段加入到bypass里面了，并且在电脑代理里面也设置了请勿将代理服务器用于本地（Intranet）地址，依旧无效，请大佬解惑，谢谢
下面是TUN模式配置：

![image](https://user-images.githubusercontent.com/51412618/222603154-22af9c61-08a9-4b70-99aa-1d5f4e15cb64.png)

### 复现步骤

- 

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

-

**Comment by yi-Xu-0100** [comment]
看看日志

**Comment by EliDoves** [comment]
> 看看日志

这样的，抱歉因为是公司内网，所以打码了，开启TUN模式之前，是绕过Clash的，这条记录也不会显示到Log里面，开始TUN之后就走代理了

![image](https://user-images.githubusercontent.com/51412618/222609830-e8077a49-d673-45c7-886f-effd965f42b2.png)

**Comment by yi-Xu-0100** [comment]
tun 会全部接管，不会绕过，所以你需要加规则匹配让他直连。

**Comment by EliDoves** [comment]
> tun 会全部接管，不会绕过，所以你需要加规则匹配让他直连。

好的我试试，开始TUN模式后cfw-bypass是不是就失效了

**Comment by yi-Xu-0100** [comment]
@EliDoves bypass 只适用于跳过系统代理，而 TUN 会接管不走代理的部分。

**Comment by EliDoves** [comment]
> @EliDoves bypass 只适用于跳过系统代理，而 TUN 会接管不走代理的部分。

哦，了解了，谢谢
