### ISSUE TITLE
[Bug]: 订阅连接可以下载到cfw里面，但是切换时报错

### ISSUE THREAD

**Issue by HeX-GitHub** [Fndroid/clash_for_windows_pkg#4098]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.17

### 操作系统

Windows x64

### 系统版本

Windows 11

### 问题描述

直接导入和通过订阅连接下载都不能成功切换到订阅
![image](https://user-images.githubusercontent.com/101781769/222935388-c92f3c5f-8750-49df-9dbc-7447dbdbada3.png)

### 复现步骤

每次通过订阅导入的时候都会这样

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by antong1212** [comment]
是0.20.17的bug，切换到0.20.9就可以了

**Comment by HeX-GitHub** [comment]
谢谢你，可是我试了下0.20.9与0.20.15都有相同的情况

**Comment by HeX-GitHub** [comment]
> 是0.20.17的bug，切换到0.20.9就可以了
谢谢你，可是我试了下0.20.9与0.20.15都有相同的情况

**Comment by HeX-GitHub** [comment]
> 是0.20.17的bug，切换到0.20.9就可以了

谢谢你，可是我试了下0.20.9与0.20.15都有相同的情况

**Comment by Fndroid** [comment]
配置文件格式不对，不是自己写就找给你地址的人改

**Comment by HeX-GitHub** [comment]
> 就找给你地址的

谢谢，已解决
