### ISSUE TITLE
这种是什么问题？

### ISSUE THREAD

**Issue by Zzzziiii** [Fndroid/clash_for_windows_pkg#41]
我设置都没问题 左下角也是绿色的connected to clash,但就是没反应 
time="2018-12-09T23:16:25+08:00" level=info msg="RESTful API listening at: 0.0.0.0:9090"
time="2018-12-09T23:16:25+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2018-12-09T23:16:25+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2018-12-09T23:16:25+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"

**Comment by Zzzziiii** [comment]
![image](https://user-images.githubusercontent.com/22714893/49699304-61791d80-fc0a-11e8-9c40-dbe8acbc989c.png)

**Comment by Fndroid** [comment]
没反应是什么意思……

**Comment by Zzzziiii** [comment]
![image](https://user-images.githubusercontent.com/22714893/49699327-8ff6f880-fc0a-11e8-8a95-fba72c162a4d.png)

**Comment by Fndroid** [comment]
用了插件要关掉，节点确定一下有没断开

**Comment by Zzzziiii** [comment]
节点没问题，v2rayN可以用， 关了SwitchyOmega 或者换Edge 都没用

**Comment by Zzzziiii** [comment]
test 也能痛
![image](https://user-images.githubusercontent.com/22714893/49699411-b701fa00-fc0b-11e8-9d1a-933a540dbd5a.png)
