### ISSUE TITLE
[Feature Request]: add proxy selector in tray menu for Linux please

### ISSUE THREAD

**Issue by otakutyrant** [Fndroid/clash_for_windows_pkg#4104]
### 功能描述

I wonder why my Clash for Windows has proxy selector in tray menu and my Clash for Linux does not. According to the descriptions of [v 0.19.18](https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.19.18) and [v 0.19.19](https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.19.19), it seems that the feature is unimplemented for Linux.

### 其他内容

I suspect that the Linux version misses a lot of features according to my impression of Clash settings between Windows and Linux.

**Comment by Fndroid** [comment]
There are some features that cannot be implemented on Linux, such as system proxy and dynamic updating of taskbar menus.

**Comment by Oyami-Srk** [comment]
System-wide proxy is not easily provided in Linux kernel level. Instead, most of software is aware of environment variables like `http_proxy`. (Or something depends on your DE). If you use linux you should be capable of changing your profile file. Changing global network proxy statically via profile programmatically could introduce more problem.
Other way, hooking execve and inject proxy settings is too hard to be implemented.

Tray menu are highly depended on specific DE. Linux has no such stable thing.
