### ISSUE TITLE
[Bug]: 启用DoH后部分网站无法正常解析成Host Name走分流规则

### ISSUE THREAD

**Issue by Cloudy-Kumori** [Fndroid/clash_for_windows_pkg#4105]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.17

### 操作系统

Windows x64

### 系统版本

Windows 11 22H2

### 问题描述

启用DoH的DNS解析后，有部分网站在Connections里面直接被解析成了IP地址，不再解析成Host Name，这就导致了预先设定的基于Host Name的分流规则失效，使得这部分网站的流量直接走了基于IP分流的“漏网之鱼”/“其他流量”规则。请问这是DoH的特性吗？是否可以在递交DNS解析的时候将域名和解析返回的IP绑定，并根据设定的域名规则分流？

### 复现步骤

在TUN模式下添加阿里（https://dns.alidns.com/dns-query ）和腾讯（https://doh.pub/dns-query ） 的DoH域名，然后新建一个针对于国外IP流量的Match规则组并命名为“漏网之鱼”，同时为微软必应的域名新建一个基于域名Host Name分流的规则组，两个规则组都添加代理和直连模式。再进行相关设置后，打开浏览器访问www.bing.com，此时没有跳转到cn.bing.com，并且connections中出现了微软的IP地址，判定为走了代理。将微软必应规则组调到直连模式，此时仍然是国际版bing。将漏网之鱼规则组调到直连模式后，bing跳转到cn.bing.com，此时判定bing为直连流量。可以看出，DoH下基于域名分流的规则组已经失效，并由IP分流规则接管。

### 日志文件

<details><summary>logs</summary><p>

```
 00:00:15 INF [Config] initial compatible provider name=Proxy
 00:00:15 INF [API] listening addr=127.0.0.1:4386
 00:00:15 INF [Inbound] Mixed(http+socks) listening addr=[::]:7890
 00:00:15 INF [Config] initial compatible provider name=苹果服务
 00:00:15 INF [Config] initial compatible provider name=国外媒体
 00:00:15 INF [Config] initial compatible provider name= 直接连接
 00:00:15 INF [Config] initial compatible provider name= 国外流量
 00:00:15 INF [Config] initial compatible provider name=微软必应
 00:00:15 INF [Config] initial compatible provider name=广告过滤
 00:00:15 INF [Config] initial compatible provider name= 其他流量
 00:00:15 INF [Config] initial rule provider name=applications
 00:00:15 INF [Config] initial rule provider name=reject
 00:00:15 INF [Config] initial rule provider name=proxy
 00:00:15 INF [Config] initial rule provider name=telegram
 00:00:15 INF [Config] initial rule provider name=google
 00:00:15 INF [Config] initial rule provider name=icloud
 00:00:15 INF [Config] initial rule provider name=cncidr
 00:00:16 INF [Config] initial rule provider name=lancidr
 00:00:16 INF [Config] initial rule provider name=direct
 00:00:16 INF [Config] initial rule provider name=apple
 00:00:17 INF [Inbound] TUN listening iface=Clash gateway=198.18.0.1
 00:00:23 INF [TCP] connected lAddr=198.18.0.1:4422 rAddr=14.119.104.189:80 mode=rule rule=RuleSet(cncidr) proxy= 直接连接[DIRECT]
 00:00:23 WRN [TCP] dial failed error=couldn't find ip: wpad.tail395e6.ts.net proxy=DIRECT lAddr=198.18.0.1:4423 rAddr=wpad.tail395e6.ts.net:80 rule=Process rulePayload=svchost.exe
 00:00:23 INF [TCP] connected lAddr=198.18.0.1:4407 rAddr=51.105.71.137:443 mode=rule rule=Process(OneDrive.exe) proxy=DIRECT
 00:00:23 INF [TCP] connected lAddr=198.18.0.1:4408 rAddr=20.54.24.69:443 mode=rule rule=Process(svchost.exe) proxy=DIRECT
 00:00:23 INF [TCP] connected lAddr=198.18.0.1:4406 rAddr=20.42.65.89:443 mode=rule rule=Process(OneDrive.exe) proxy=DIRECT
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4427 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4432 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4428 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4430 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4417 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4431 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4426 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4416 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4434 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4429 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4433 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4404 rAddr=heartbeat.dm.origin.com:80 mode=rule rule=RuleSet(proxy) proxy= 国外流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4415 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4482 rAddr=www.msftconnecttest.com:80 mode=rule rule=Process(svchost.exe) proxy=DIRECT
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4473 rAddr=www.msftconnecttest.com:80 mode=rule rule=Process(svchost.exe) proxy=DIRECT
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4487 rAddr=www.msftconnecttest.com:80 mode=rule rule=Process(svchost.exe) proxy=DIRECT
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4480 rAddr=www.msftconnecttest.com:80 mode=rule rule=Process(svchost.exe) proxy=DIRECT
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4483 rAddr=www.msftconnecttest.com:80 mode=rule rule=Process(svchost.exe) proxy=DIRECT
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4481 rAddr=chrome.cloudflare-dns.com:443 mode=rule rule=RuleSet(proxy) proxy= 国外流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4484 rAddr=chrome.cloudflare-dns.com:443 mode=rule rule=RuleSet(proxy) proxy= 国外流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4500 rAddr=service.aecichina.com:80 mode=rule rule=RuleSet(direct) proxy= 直接连接[DIRECT]
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4514 rAddr=kv801.prod.do.dsp.mp.microsoft.com:443 mode=rule rule=DomainKeyword(microsoft) proxy=微软必应 
 00:00:25 INF [TCP] connected lAddr=198.18.0.1:4516 rAddr=20.198.118.190:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:25 INF [TCP] connected lAddr=198.18.0.1:4518 rAddr=20.42.73.26:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:26 INF [TCP] connected lAddr=198.18.0.1:4524 rAddr=rta.xboxlive.com:443 mode=rule rule=RuleSet(proxy) proxy= 国外流量 
 00:00:26 INF [TCP] connected lAddr=198.18.0.1:4525 rAddr=chat.xboxlive.com:443 mode=rule rule=RuleSet(proxy) proxy= 国外流量 
 00:00:26 INF [TCP] connected lAddr=198.18.0.1:4533 rAddr=www.xboxab.com:443 mode=rule rule=RuleSet(proxy) proxy= 国外流量 
 00:00:26 INF [TCP] connected lAddr=198.18.0.1:4530 rAddr=peoplehub.xboxlive.com:443 mode=rule rule=RuleSet(proxy) proxy= 国外流量 
 00:00:26 INF [TCP] connected lAddr=198.18.0.1:4529 rAddr=xblmessaging.xboxlive.com:443 mode=rule rule=RuleSet(proxy) proxy= 国外流量 
 00:00:26 INF [TCP] connected lAddr=198.18.0.1:4532 rAddr=privacy.xboxlive.com:443 mode=rule rule=RuleSet(proxy) proxy= 国外流量 
 00:00:27 INF [TCP] connected lAddr=198.18.0.1:4528 rAddr=xblmessaging.xboxlive.com:443 mode=rule rule=RuleSet(proxy) proxy= 国外流量 
 00:00:27 INF [TCP] connected lAddr=198.18.0.1:4531 rAddr=notificationinbox.xboxlive.com:443 mode=rule rule=RuleSet(proxy) proxy= 国外流量 
 00:00:28 INF [TCP] connected lAddr=198.18.0.1:4541 rAddr=www.msftconnecttest.com:80 mode=rule rule=Process(svchost.exe) proxy=DIRECT
 00:00:28 WRN [TCP] dial failed error=couldn't find ip: wpad.tail395e6.ts.net proxy=DIRECT lAddr=198.18.0.1:4549 rAddr=wpad.tail395e6.ts.net:80 rule=Process rulePayload=svchost.exe
 00:00:29 INF [TCP] connected lAddr=198.18.0.1:4545 rAddr=204.79.197.200:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:31 INF [TCP] connected lAddr=198.18.0.1:4555 rAddr=14.119.104.189:80 mode=rule rule=RuleSet(cncidr) proxy= 直接连接[DIRECT]
 00:00:31 INF [UDP] connected lAddr=198.18.0.1:64498 rAddr=23.32.56.169:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:31 INF [UDP] connected lAddr=198.18.0.1:61362 rAddr=23.32.56.169:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:31 INF [TCP] connected lAddr=198.18.0.1:4560 rAddr=20.205.115.81:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:32 INF [TCP] connected lAddr=198.18.0.1:4564 rAddr=23.32.56.163:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:32 INF [TCP] connected lAddr=198.18.0.1:4566 rAddr=40.79.150.120:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:32 INF [TCP] connected lAddr=198.18.0.1:4568 rAddr=40.126.35.86:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:32 INF [TCP] connected lAddr=198.18.0.1:4571 rAddr=13.105.28.3:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:32 INF [TCP] connected lAddr=198.18.0.1:4573 rAddr=40.79.150.120:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:33 WRN [TCP] dial failed error=couldn't find ip: wpad.tail395e6.ts.net proxy=DIRECT lAddr=198.18.0.1:4578 rAddr=wpad.tail395e6.ts.net:80 rule=Process rulePayload=svchost.exe
 00:00:34 INF [TCP] connected lAddr=198.18.0.1:4579 rAddr=204.79.197.203:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:34 INF [TCP] connected lAddr=198.18.0.1:4581 rAddr=40.126.35.151:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:34 INF [TCP] connected lAddr=198.18.0.1:4585 rAddr=104.74.196.139:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:35 WRN [TCP] dial failed error=couldn't find ip: wpad.tail395e6.ts.net proxy=DIRECT lAddr=198.18.0.1:4589 rAddr=wpad.tail395e6.ts.net:80 rule=Process rulePayload=svchost.exe
 00:00:36 INF [TCP] connected lAddr=198.18.0.1:4591 rAddr=v20.events.data.microsoft.com:443 mode=rule rule=DomainKeyword(microsoft) proxy=微软必应 
 00:00:36 INF [TCP] connected lAddr=198.18.0.1:4609 rAddr=23.67.53.146:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:36 INF [TCP] connected lAddr=198.18.0.1:4610 rAddr=23.67.53.146:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:36 INF [TCP] connected lAddr=198.18.0.1:4612 rAddr=23.67.53.146:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:36 INF [TCP] connected lAddr=198.18.0.1:4596 rAddr=140.82.112.26:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:36 INF [TCP] connected lAddr=198.18.0.1:4611 rAddr=23.67.53.146:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:36 INF [TCP] connected lAddr=198.18.0.1:4608 rAddr=23.67.53.146:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:36 WRN [TCP] dial failed error=dial tcp4 49.171.153.225:7680: i/o timeout proxy=DIRECT lAddr=198.18.0.1:4369 rAddr=49.171.153.225:7680 rule=Process rulePayload=svchost.exe
 00:00:36 INF [TCP] connected lAddr=198.18.0.1:4622 rAddr=23.67.53.146:443 mode=rule rule=Match() proxy= 其他流量 

```

</p></details>

**Comment by GrigorGB** [comment]
unsubscribeSent from my iPhoneOn 6 Mar 2023, at 08:27, Cloudy-骁云 ***@***.***> wrote:﻿
请认真检查以下清单中的每一项

 已经搜索过，没有发现类似issue
 已经搜索过文档，没有发现相关内容
 已经尝试使用过最新版，问题依旧存在
 使用的是官方版本（未替换及修改过安装目录程序文件）

软件版本
0.20.17
操作系统
Windows x64
系统版本
Windows 11 22H2
问题描述
启用DoH的DNS解析后，有部分网站在Connections里面直接被解析成了IP地址，不再解析成Host Name，这就导致了预先设定的基于Host Name的分流规则失效，使得这部分网站的流量直接走了基于IP分流的“漏网之鱼”/“其他流量”规则。请问这是DoH的特性吗？是否可以在递交DNS解析的时候将域名和解析返回的IP绑定，并根据设定的域名规则分流？
复现步骤
在TUN模式下添加阿里（https://dns.alidns.com/dns-query ）和腾讯（https://doh.pub/dns-query ） 的DoH域名，然后新建一个针对于国外IP流量的Match规则组并命名为“漏网之鱼”，同时为微软必应的域名新建一个基于域名Host Name分流的规则组，两个规则组都添加代理和直连模式。再进行相关设置后，打开浏览器访问www.bing.com，此时没有跳转到cn.bing.com，并且connections中出现了微软的IP地址，判定为走了代理。将微软必应规则组调到直连模式，此时仍然是国际版bing。将漏网之鱼规则组调到直连模式后，bing跳转到cn.bing.com，此时判定bing为直连流量。可以看出，DoH下基于域名分流的规则组已经失效，并由IP分流规则接管。
日志文件
logs
 00:00:15 INF [Config] initial compatible provider name=Proxy
 00:00:15 INF [API] listening addr=127.0.0.1:4386
 00:00:15 INF [Inbound] Mixed(http+socks) listening addr=[::]:7890
 00:00:15 INF [Config] initial compatible provider name=苹果服务
 00:00:15 INF [Config] initial compatible provider name=国外媒体
 00:00:15 INF [Config] initial compatible provider name= 直接连接
 00:00:15 INF [Config] initial compatible provider name= 国外流量
 00:00:15 INF [Config] initial compatible provider name=微软必应
 00:00:15 INF [Config] initial compatible provider name=广告过滤
 00:00:15 INF [Config] initial compatible provider name= 其他流量
 00:00:15 INF [Config] initial rule provider name=applications
 00:00:15 INF [Config] initial rule provider name=reject
 00:00:15 INF [Config] initial rule provider name=proxy
 00:00:15 INF [Config] initial rule provider name=telegram
 00:00:15 INF [Config] initial rule provider name=google
 00:00:15 INF [Config] initial rule provider name=icloud
 00:00:15 INF [Config] initial rule provider name=cncidr
 00:00:16 INF [Config] initial rule provider name=lancidr
 00:00:16 INF [Config] initial rule provider name=direct
 00:00:16 INF [Config] initial rule provider name=apple
 00:00:17 INF [Inbound] TUN listening iface=Clash gateway=198.18.0.1
 00:00:23 INF [TCP] connected lAddr=198.18.0.1:4422 rAddr=14.119.104.189:80 mode=rule rule=RuleSet(cncidr) proxy= 直接连接[DIRECT]
 00:00:23 WRN [TCP] dial failed error=couldn't find ip: wpad.tail395e6.ts.net proxy=DIRECT lAddr=198.18.0.1:4423 rAddr=wpad.tail395e6.ts.net:80 rule=Process rulePayload=svchost.exe
 00:00:23 INF [TCP] connected lAddr=198.18.0.1:4407 rAddr=51.105.71.137:443 mode=rule rule=Process(OneDrive.exe) proxy=DIRECT
 00:00:23 INF [TCP] connected lAddr=198.18.0.1:4408 rAddr=20.54.24.69:443 mode=rule rule=Process(svchost.exe) proxy=DIRECT
 00:00:23 INF [TCP] connected lAddr=198.18.0.1:4406 rAddr=20.42.65.89:443 mode=rule rule=Process(OneDrive.exe) proxy=DIRECT
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4427 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4432 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4428 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4430 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4417 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4431 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4426 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4416 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4434 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4429 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4433 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4404 rAddr=heartbeat.dm.origin.com:80 mode=rule rule=RuleSet(proxy) proxy= 国外流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4415 rAddr=104.18.13.173:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4482 rAddr=www.msftconnecttest.com:80 mode=rule rule=Process(svchost.exe) proxy=DIRECT
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4473 rAddr=www.msftconnecttest.com:80 mode=rule rule=Process(svchost.exe) proxy=DIRECT
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4487 rAddr=www.msftconnecttest.com:80 mode=rule rule=Process(svchost.exe) proxy=DIRECT
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4480 rAddr=www.msftconnecttest.com:80 mode=rule rule=Process(svchost.exe) proxy=DIRECT
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4483 rAddr=www.msftconnecttest.com:80 mode=rule rule=Process(svchost.exe) proxy=DIRECT
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4481 rAddr=chrome.cloudflare-dns.com:443 mode=rule rule=RuleSet(proxy) proxy= 国外流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4484 rAddr=chrome.cloudflare-dns.com:443 mode=rule rule=RuleSet(proxy) proxy= 国外流量 
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4500 rAddr=service.aecichina.com:80 mode=rule rule=RuleSet(direct) proxy= 直接连接[DIRECT]
 00:00:24 INF [TCP] connected lAddr=198.18.0.1:4514 rAddr=kv801.prod.do.dsp.mp.microsoft.com:443 mode=rule rule=DomainKeyword(microsoft) proxy=微软必应 
 00:00:25 INF [TCP] connected lAddr=198.18.0.1:4516 rAddr=20.198.118.190:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:25 INF [TCP] connected lAddr=198.18.0.1:4518 rAddr=20.42.73.26:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:26 INF [TCP] connected lAddr=198.18.0.1:4524 rAddr=rta.xboxlive.com:443 mode=rule rule=RuleSet(proxy) proxy= 国外流量 
 00:00:26 INF [TCP] connected lAddr=198.18.0.1:4525 rAddr=chat.xboxlive.com:443 mode=rule rule=RuleSet(proxy) proxy= 国外流量 
 00:00:26 INF [TCP] connected lAddr=198.18.0.1:4533 rAddr=www.xboxab.com:443 mode=rule rule=RuleSet(proxy) proxy= 国外流量 
 00:00:26 INF [TCP] connected lAddr=198.18.0.1:4530 rAddr=peoplehub.xboxlive.com:443 mode=rule rule=RuleSet(proxy) proxy= 国外流量 
 00:00:26 INF [TCP] connected lAddr=198.18.0.1:4529 rAddr=xblmessaging.xboxlive.com:443 mode=rule rule=RuleSet(proxy) proxy= 国外流量 
 00:00:26 INF [TCP] connected lAddr=198.18.0.1:4532 rAddr=privacy.xboxlive.com:443 mode=rule rule=RuleSet(proxy) proxy= 国外流量 
 00:00:27 INF [TCP] connected lAddr=198.18.0.1:4528 rAddr=xblmessaging.xboxlive.com:443 mode=rule rule=RuleSet(proxy) proxy= 国外流量 
 00:00:27 INF [TCP] connected lAddr=198.18.0.1:4531 rAddr=notificationinbox.xboxlive.com:443 mode=rule rule=RuleSet(proxy) proxy= 国外流量 
 00:00:28 INF [TCP] connected lAddr=198.18.0.1:4541 rAddr=www.msftconnecttest.com:80 mode=rule rule=Process(svchost.exe) proxy=DIRECT
 00:00:28 WRN [TCP] dial failed error=couldn't find ip: wpad.tail395e6.ts.net proxy=DIRECT lAddr=198.18.0.1:4549 rAddr=wpad.tail395e6.ts.net:80 rule=Process rulePayload=svchost.exe
 00:00:29 INF [TCP] connected lAddr=198.18.0.1:4545 rAddr=204.79.197.200:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:31 INF [TCP] connected lAddr=198.18.0.1:4555 rAddr=14.119.104.189:80 mode=rule rule=RuleSet(cncidr) proxy= 直接连接[DIRECT]
 00:00:31 INF [UDP] connected lAddr=198.18.0.1:64498 rAddr=23.32.56.169:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:31 INF [UDP] connected lAddr=198.18.0.1:61362 rAddr=23.32.56.169:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:31 INF [TCP] connected lAddr=198.18.0.1:4560 rAddr=20.205.115.81:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:32 INF [TCP] connected lAddr=198.18.0.1:4564 rAddr=23.32.56.163:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:32 INF [TCP] connected lAddr=198.18.0.1:4566 rAddr=40.79.150.120:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:32 INF [TCP] connected lAddr=198.18.0.1:4568 rAddr=40.126.35.86:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:32 INF [TCP] connected lAddr=198.18.0.1:4571 rAddr=13.105.28.3:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:32 INF [TCP] connected lAddr=198.18.0.1:4573 rAddr=40.79.150.120:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:33 WRN [TCP] dial failed error=couldn't find ip: wpad.tail395e6.ts.net proxy=DIRECT lAddr=198.18.0.1:4578 rAddr=wpad.tail395e6.ts.net:80 rule=Process rulePayload=svchost.exe
 00:00:34 INF [TCP] connected lAddr=198.18.0.1:4579 rAddr=204.79.197.203:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:34 INF [TCP] connected lAddr=198.18.0.1:4581 rAddr=40.126.35.151:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:34 INF [TCP] connected lAddr=198.18.0.1:4585 rAddr=104.74.196.139:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:35 WRN [TCP] dial failed error=couldn't find ip: wpad.tail395e6.ts.net proxy=DIRECT lAddr=198.18.0.1:4589 rAddr=wpad.tail395e6.ts.net:80 rule=Process rulePayload=svchost.exe
 00:00:36 INF [TCP] connected lAddr=198.18.0.1:4591 rAddr=v20.events.data.microsoft.com:443 mode=rule rule=DomainKeyword(microsoft) proxy=微软必应 
 00:00:36 INF [TCP] connected lAddr=198.18.0.1:4609 rAddr=23.67.53.146:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:36 INF [TCP] connected lAddr=198.18.0.1:4610 rAddr=23.67.53.146:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:36 INF [TCP] connected lAddr=198.18.0.1:4612 rAddr=23.67.53.146:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:36 INF [TCP] connected lAddr=198.18.0.1:4596 rAddr=140.82.112.26:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:36 INF [TCP] connected lAddr=198.18.0.1:4611 rAddr=23.67.53.146:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:36 INF [TCP] connected lAddr=198.18.0.1:4608 rAddr=23.67.53.146:443 mode=rule rule=Match() proxy= 其他流量 
 00:00:36 WRN [TCP] dial failed error=dial tcp4 49.171.153.225:7680: i/o timeout proxy=DIRECT lAddr=198.18.0.1:4369 rAddr=49.171.153.225:7680 rule=Process rulePayload=svchost.exe
 00:00:36 INF [TCP] connected lAddr=198.18.0.1:4622 rAddr=23.67.53.146:443 mode=rule rule=Match() proxy= 其他流量 



其他补充
No response
