### ISSUE TITLE
[Bug]: 便携模式下，打开”隐藏任务栏托盘“，关闭窗口，无法关闭

### ISSUE THREAD

**Issue by rangluwme** [Fndroid/clash_for_windows_pkg#4107]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

20.17

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

[Bug]: 便携模式下，打开”隐藏任务栏托盘“，关闭窗口，无法关闭，只能打开任务管理器，结束进程，才可以关闭窗口。
便携模式下，打开”隐藏任务栏托盘“，关闭窗口，无法关闭，只能打开任务管理器，结束进程，才可以关闭窗口。
但是关闭后，clash仍然可以正常使用

### 复现步骤

如上所述

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
hide tray icon 会隐藏任务栏托盘，此时为了保证 CFW 正常运行，关闭窗口会变成最小化，感觉是预期行为。

结束进程需要同时结束掉 clash-win64.exe ，clash core 才会停止运行。

**Comment by rangluwme** [comment]
对的，

**Comment by Fndroid** [comment]
settings里右上角不是有quit吗

**Comment by rangluwme** [comment]
> settings里右上角不是有quit吗

经过尝试，在开启“hide tray icon"的条件下，点quit是直接完全退出clash（应该clash-win64.exe ，clash core 都关闭了），点击 Force Quit, clash窗口关闭了，clash是可以正常使用的。hh请问大佬这是不是弄反了？

**Comment by yi-Xu-0100** [comment]
@rangluwme 没反，我是这样理解的：软件主体是CFW，force quit 是强制退出，只保证退出CFW进程，不退出下属其他进程，如core。quit
 是正常退出，退出所有所属进程，会同时退出调用的 core

**Comment by rangluwme** [comment]
OKK
