### ISSUE TITLE
[Feature Request]: 脚本能不能实现根据http heard请求头识别不同的节点？

### ISSUE THREAD

**Issue by ypy121** [Fndroid/clash_for_windows_pkg#4110]
### 功能描述

有时候需要同一个地址不同的账户，不同的账户走不同的节点，如果用指定程序的方式，好像不能实现这样的功能，如果用脚本，没有思路，能不能给个思路？

**Comment by Fndroid** [comment]
> 脚本能不能实现根据http heard请求头识别不同的节点

不能
