### ISSUE TITLE
配置不成功，显示 is not a slice

### ISSUE THREAD

**Issue by Ather886** [Fndroid/clash_for_windows_pkg#412]
下载成功，切换配置时显示如下
![image](https://user-images.githubusercontent.com/60834945/74096355-c4c94d00-4b38-11ea-86de-933a2fbefb27.png)

**Comment by Ather886** [comment]
#
![QQ图片20200209123737](https://user-images.githubusercontent.com/60834945/74096375-0954e880-4b39-11ea-8456-909c97e50b6f.png)

**Comment by Fndroid** [comment]
配置文件格式错误，参考：https://github.com/Dreamacro/clash/tree/dev#config
