### ISSUE TITLE
[Bug]: Arm版的macos上有x86的程序

### ISSUE THREAD

**Issue by GavinIves** [Fndroid/clash_for_windows_pkg#4120]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.17

### 操作系统

macOS arm64(M1,M1*)

### 系统版本

13

### 问题描述

<img width="946" alt="image" src="https://user-images.githubusercontent.com/38970877/223779422-9319ea00-6ba5-469a-bce9-97a1f724960f.png">
我下载的是arm版的dmg，理论上应该没有x86程序在后台 但事实上有这个进程 想知道是正常现象还是遗漏了 后期会修复吗

### 复现步骤

无

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
Service Mode先卸载再重新安装一次看看

**Comment by GavinIves** [comment]
解决了！！！！
