### ISSUE TITLE
请问预处理规则可以在域名中使用通配符吗？

### ISSUE THREAD

**Issue by chimiansw** [Fndroid/clash_for_windows_pkg#4124]
请问大佬预处理规则可以在域名中使用通配符吗？就是有些网站基于某些大家都知道的原因经常会更换域名，大多数都是很简单的更换域名末尾的数字，比如abc001.com,abc002.com，预处理里面可不可以加一条类似
- DOMAIN-SUFFIX,'abc*.com', Proxy
这样的语句来让所有这样的域名走代理呢？我试了简单的这样写好像没什么用，希望大佬们指点，谢谢！

**Comment by chimiansw** [comment]
目前用KEYWORD实现了，好像要编辑预处理后重启一下clash才可以

**Comment by chimiansw** [comment]
我之前用KEYWORD不知道为什么更新配置也没生效，后来重启了一下CFW才生效，不知道除了KEYWORD还有没有什么其他方法

**Comment by yi-Xu-0100** [comment]
@chimiansw 暂时不知道还有什么其他的合适的方法。

**Comment by AkariiinMKII** [comment]
> 我之前用KEYWORD不知道为什么更新配置也没生效，后来重启了一下CFW才生效，不知道除了KEYWORD还有没有什么其他方法

script可以 但是没有必要

**Comment by chimiansw** [comment]
明白了，那就用keyword吧，感谢各位大佬！
