### ISSUE TITLE
[Bug]: [linux] Service mode: User did not grant permission

### ISSUE THREAD

**Issue by Martinits** [Fndroid/clash_for_windows_pkg#4126]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.17

### 操作系统

Linux

### 系统版本

Archlinux

### 问题描述

无法安装service mode

### 复现步骤

打开就这样

### 日志文件

日志里没有任何错误信息或者相关信息

**Comment by ZaeXT** [comment]
安装并运行polkit

**Comment by Martinits** [comment]
> 安装并运行polkit https://wiki.archlinuxcn.org/wiki/Polkit

这个是装了的（应该是别的包的依赖），但是我要怎么运行？cfw需要什么样的配置？

**Comment by Martinits** [comment]
好吧，要装一个agent，因为我是sway这种WM，不是DE，所以没有预装agent
