### ISSUE TITLE
[Bug]: Could not switch to this profile! 

### ISSUE THREAD

**Issue by HuberyChang** [Fndroid/clash_for_windows_pkg#4127]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.18

### 操作系统

Windows x64

### 系统版本

win11

### 问题描述

今天注册了账号，网站首页复制订阅链接后，复制到profile链接填写框中，没法下载文件

### 复现步骤

按照正常的流程走

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
没法下载的话，建议找下链接提供者。这个和CFW本身无关

**Comment by HuberyChang** [comment]
> 没法下载的话，建议找下链接提供者。这个和CFW本身无关

请问怎么找链接提供者？

**Comment by yi-Xu-0100** [comment]
去你注册的网站找找。

**Comment by HuberyChang** [comment]
> 去你注册的网站找找。

![image](https://user-images.githubusercontent.com/28822971/224361489-ef2d8222-9d8e-4364-b283-e5f7d9647080.png)

就这个网站，请问我在哪看？
这是订阅链接
https://sub1.smallstrawberry.com/api/v1/client/subscribe?token=e7820f7a3c0467c0a293d97a08d4b2f0

**Comment by yi-Xu-0100** [comment]
网页上让你找telegram群，如果联系不上，或者找不到网站的反馈系统，那就找你找到这个网站的途径吧。

**Comment by HuberyChang** [comment]
> 网页上让你找telegram群，如果联系不上，或者找不到网站的反馈系统，那就找你找到这个网站的途径吧。
> 
> 而且我看你这个截图显示你没有订阅，可能是这个原因，看看使用说明啥的。

ok，感谢
