### ISSUE TITLE
[Bug]: 使用最新版本(0.20.18) 提示 此应用无法在你的电脑上运行

### ISSUE THREAD

**Issue by 13462249457** [Fndroid/clash_for_windows_pkg#4129]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.18

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

电脑解压最新版本(0.20.18),提示如下图

![image](https://user-images.githubusercontent.com/40123216/224467096-06ae744e-568e-417c-a9e1-ed302501b387.png)

### 复现步骤

启动必现

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
软件版本按错了，去release下载，可能需要展开一下

**Comment by Luozhe-Socrates** [comment]
我的也是，从20.12版本之后都不可以。安装exe文件无法安装，下载压缩包点击显示在你的电脑无法运行

**Comment by Fndroid** [comment]
说明下载错了
