### ISSUE TITLE
关于延迟测试的疑问

### ISSUE THREAD

**Issue by 0wQ** [Fndroid/clash_for_windows_pkg#413]
想问一下为什么会出现这种情况（**单个测试** 比 **一起测试** 延迟更低）

![1.gif](https://i.loli.net/2020/02/09/hFwQyv38167POHX.gif)

我用 Wireshark 抓包试了下 **一起测试** 时是https协议，**单个测试** 时是http协议，不知道是不是我抓包出现问题了。

**Comment by Fndroid** [comment]
有没有设置``cfw-latency-url``这个参数？

**Comment by 0wQ** [comment]
> 有没有设置`cfw-latency-url`这个参数？

是我的锅，自己以前设置成https的，忘记改回来了😂

还有个疑问，**单个测试** 时使用的是 `http://www.gstatic.com/generate_204`
自定义的 `cfw-latency-url` 对它不生效

**Comment by Fndroid** [comment]
@0wQ 单个没有用设定的url是bug，下个版本修

**Comment by Fndroid** [comment]
fixed in this release: https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.0
