### ISSUE TITLE
关于TUN模式和移动热点的一些疑问

### ISSUE THREAD

**Issue by Konseru** [Fndroid/clash_for_windows_pkg#4130]
服务模式Service Mode安装成功后(右边地球图标已变为绿色)是不是不论是否启用TUN模式都需要按照issues #3835 去进行相关设置才能上网？
![image](https://user-images.githubusercontent.com/90184282/224470831-55d048b1-ad50-41c8-a9f2-e25d2f34e33b.png)
我自己在未启用TUN模式、关闭系统代理、开启移动热点的情况下无法上网，按照issues #3835 下面的解决方法设置后就能够上网了，我想问的是这种情况算BUG吗？在官方的常见问题中存在解决方法
> Windows 系统中，TUN 模式下无法使用热点分享功能
> 1. 开启热点分享功能，此时系统网络设置中会生成一个网卡
> 2. 开启 TUN 模式
> 3. 进入系统网络设置，在 Clash 网卡右键选择属性，选择共享标签页
> 4. 勾选“允许其他网络用户通过此计算机的 Internet 连接来连接”
> 5. 在“家庭网络连接”选择框中选择第 1 步生成的网卡

问题是我在只安装`Service Mode`而未启用TUN模式的情况下也能算做在TUN模式下吗？

**Comment by yi-Xu-0100** [comment]
可能你的订阅profiles里有tun配置或者mixin启用了tun配置，需要自行检查一下

**Comment by Konseru** [comment]
> 可能你的订阅profiles里有tun配置或者mixin启用了tun配置，需要自行检查一下

谢谢回复，刚才去试了试没有再出现我说问题但应该不是你说的原因，因为我用同样的配置没有出现相同的问题，还出现过在已经设置过允许(共享此时同时使用TUN模式和移动热点能正常上网)然后再关闭允许共享在一段时间内不论是否同时启用TUN模式和移动热点都能正常上网，可能设置需要一段时间才能生效吧
