### ISSUE TITLE
[Bug]: 使用最新版本(0.20.18) Clash.for.Windows.Setup.0.20.18.exe 在Win11系统上无法运行安装程序

### ISSUE THREAD

**Issue by 1774298958** [Fndroid/clash_for_windows_pkg#4131]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.18

### 操作系统

Windows x64

### 系统版本

Windows 11 最新版本系统

### 问题描述

Clash.for.Windows.Setup.0.20.18.exe 在Win11系统上无法运行安装程序

### 复现步骤

Clash.for.Windows.Setup.0.20.18.exe 在Win11系统上无法运行安装程序

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
你的电脑是 arm 架构的吗？

**Comment by 1774298958** [comment]
不是的  是AMD处理器

**Comment by JUN176** [comment]
请问解决了吗
