### ISSUE TITLE
[Bug]: 更新到v 0.20.18后节点列表ping全部显示超时，但能正常上外网

### ISSUE THREAD

**Issue by singularity2000** [Fndroid/clash_for_windows_pkg#4135]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（只用了个官方推荐的app.asar汉化文件）

### 软件版本

0.20.18

### 操作系统

Windows x64

### 系统版本

Win11 22H2 22621.1344

### 问题描述

更新到了最新版v0.20.18，结果**SSR**节点ping值全部显示为超时，**但能正常上外网**
更新之前节点列表ping值正常，上网正常
我一直是通过在GitHub下载7z压缩包 解压然后替换安装目录文件的方式升级clash的，此前升级都没遇到过任何问题

### 复现步骤

设置菜单最底下有个“清除fake-ip缓存”选项，不知道是不是新加进去的，点了显示“失败原因：未找到DNS存储桶“
我是小白，不知道是不是因为最近有关fake-ip的重大改版导致的，怎么在不降级的情况下解决这个问题呢？
总之节点ping值看不到，对节点的切换影响很大

**最新：采用覆盖文件法回退到0.20.17版，bug消失，ping值正常显示；返回到0.20.18版bug重新出现**

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Clarry-Rachel** [comment]
我也有相同问题

**Comment by Ealsen** [comment]
就用旧版不好吗

**Comment by GlobalHeLLRemoker** [comment]
我也有相同问题

**Comment by SACMaker** [comment]
+1

**Comment by 7hiuhiu** [comment]
我还没升级呢在v 0.20.17，今天也是一样的问题，节点全挂，唯一不同的是也上不去外网

**Comment by Fndroid** [comment]
> （只用了个官方推荐的app.asar汉化文件）
那你发什么issue

**Comment by 7hiuhiu** [comment]
> 

那我呢55，我是从官方下的版本，今天不管是更没更新，节点全挂掉了，订阅还未到期，关键是shadowsocks官网都进不去了

**Comment by Clarry-Rachel** [comment]
修改测试连接可能work out

**Comment by cold-runner** [comment]
> 修改测试连接可能work out
确实，我换成这个链接，现在就解决了http://www.google.com/generate_204
![image](https://user-images.githubusercontent.com/86516312/225165619-cf7064a5-b9f9-4dc8-8da7-22a1f9473aa3.png)

**Comment by Damon1988** [comment]
有没有已经解决的朋友，我也是一样的问题。

**Comment by adrewzhang** [comment]
> > 修改测试连接可能work out
> > 确实，我换成这个链接，现在就解决了http://www.google.com/generate_204
> > ![image](https://user-images.githubusercontent.com/86516312/225165619-cf7064a5-b9f9-4dc8-8da7-22a1f9473aa3.png)

我的yml文件里没有health-check啊！
