### ISSUE TITLE
ubuntu  无法使用

### ISSUE THREAD

**Issue by freemankevin** [Fndroid/clash_for_windows_pkg#4138]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.18.0

### 操作系统

Linux

### 系统版本

ubuntu 22.04

### 问题描述

![image](https://user-images.githubusercontent.com/71524776/224540849-660690c5-3b57-4ccb-86cc-b057dcd41833.png)

无法正常使用

### 复现步骤

![image](https://user-images.githubusercontent.com/71524776/224540849-660690c5-3b57-4ccb-86cc-b057dcd41833.png)

无法正常使用

### 日志文件

无异常日志

**Comment by yi-Xu-0100** [comment]
更新到最新版，注意检查端口占用。

**Comment by freemankevin** [comment]
确实是，后台进程启动了，不好意思。干掉就OK了。多谢。

**Comment by euminds** [comment]
怎么删掉后台进程，我这里也是显示0

**Comment by freemankevin** [comment]
> 怎么删掉后台进程，我这里也是显示0

>将  `${PORXY_PORT}`  换成自己的代理端口即可
```shell
 lsof -i:${PORXY_PORT}| xargs kill -9
```
