### ISSUE TITLE
[Feature Request]: Mixin自动嗅探功能

### ISSUE THREAD

**Issue by Ao-Last** [Fndroid/clash_for_windows_pkg#4141]
### 功能描述

**现状**
核心问题: 配置管理复杂, 目前共有以下几处设置影响最终配置:

1. Mixin选项, 貌似拥有最高优先级 (最后进行混合), 可以影响所有字段?
2. 导入的Config文件 (影响proxy, rule, dns 相关的配置)
3. GUI中的TUN设置, 优先级较Mixin低.
4. 配置预处理(有点复杂).

**解决方案**
1. GUI中添加一个Mixin自动嗅探的开关, 开启该模式后开启Mixin嗅探.
2. **Mixin嗅探** 具体表现为: 对于导入的config文件中, 被`#@cfx-mixin`修饰的字段将被视为mixin的内容并进行替换.

**优点**
1. 这样只需要维护一个config文件, 不需要在导入config后手动将部分内容复制到mixin当中, 也能解决在mixin修改配置后还需要再复制回config文件当中以保存修改 2.相较于较`配置预处理`又比较简单. 3. 是对Mixin功能的一个加强

**Comment by Fndroid** [comment]
你mixin不写，不就按你config里的内容了吗

**Comment by Ao-Last** [comment]
可是不是只有rule，proxy，dns相关的几个字段会使用倒入的config吗？ 

而对于其他字段比如tun就得重新复制到mixin当中，而每当config修改一次就需要维护一次mixin

**Comment by Fndroid** [comment]
不是

**Comment by Ao-Last** [comment]
1. 根据您在[文档](https://docs.cfw.lbyczf.com/contents/configfile.html#profiles-xxxx-yaml)中的描述, 是只有几个字段会被替换. 如图:
<img width="848" alt="image" src="https://user-images.githubusercontent.com/63785048/224676449-76f2f13e-efba-4969-8643-02a54ae1d639.png">
2. 因为您是作者, 所以我也尝试了一下, 1)关掉mixin 2)把tun, dns字段内容放到导入的config当中 3)通过GUI中的那个config preview的按钮查看“最终提交的config”, 发现里面dns, tun字段的内容是GUI当中TUN设置里的内容, 而不是我的config当中的内容. 
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/63785048/224678463-5cfaa019-7322-4272-9b13-7726d62c86aa.png">

**Comment by yi-Xu-0100** [comment]
@Ao-Last profile < parser < tun < mixin ，大概是这样的优先级。mixin 最高。

**Comment by Ao-Last** [comment]
我测试了一下, 在GUI中关掉TUN的开关, 预览的配置当中的tun,dns部分使用的是导入的config. 
但我有一个问题, 关掉这个开关**是否影响tun模式的正常工作? **
因为我目前发现如果关掉这个开关, tun模式失效, 但打开这个开关使用mixin去替代配置则tun模式工作正常.
