### ISSUE TITLE
[Feature Request]: 希望能够增设上级rule模式

### ISSUE THREAD

**Issue by frsama** [Fndroid/clash_for_windows_pkg#4144]
### 功能描述

我先描述一下为什么我需要此功能。

给我提供订阅服务的提供商为了安全性，要求我们必须频繁的更新订阅服务器，频繁程度达到几个小时更新一次。
而我在学校由于需要以校内ip登录的方式才能访问学校购买的学术资料数据库。
所以我不得不在我的订阅提供商提供的rule模式上，再增加我自己需要的rule。
综合上面的原因，我不得不忍受过几个小时就要重新修改rule的情况。

所以我希望能够在订阅提供商提供的rule之上，增加上级rule。
优先按照上级rule的约定进行工作，当上级rule相关条目不存在时，再转到订阅提供商的rule进行工作。

我不确定clash是否本身具备此功能。
如果有，望告知。
否则，请问可以在后续版本中增加此功能吗？

**Comment by yi-Xu-0100** [comment]
rule 匹配从上到下，给 rules 的前面添加自定义规则即可。

更新订阅的时候自动加入，使用 diff 或者 parser

https://docs.cfw.lbyczf.com/contents/diff.html

https://docs.cfw.lbyczf.com/contents/parser.html

**Comment by frsama** [comment]
问题解决了，非常感谢
