### ISSUE TITLE
3月14日全部节点突然全部Timeout，版本是0.20.18

### ISSUE THREAD

**Issue by josspolo** [Fndroid/clash_for_windows_pkg#4148]
3月14日全部节点突然全部Timeout，是怎么回事

**Comment by josspolo** [comment]
日志显示拨号失败

**Comment by josspolo** [comment]
![image](https://user-images.githubusercontent.com/49901358/224894282-41cc5eae-6541-4dcc-897c-c96a9e3eaf91.png)

**Comment by QS0x01** [comment]
非 cfw 问题，检查你的环境。

系统时间没问题就重启环境。

**Comment by josspolo** [comment]
> 非 cfw 问题，检查你的环境。
> 
> 系统时间没问题就重启环境。

环境问题？？
我两台机器不同版本，一个是0.20.12，一个是0.20.18，两台机器前天还正常使用，系统时间检查也没有问题。
重启完还是不行

**Comment by LittleQBerry** [comment]
同样的问题

**Comment by josspolo** [comment]
> 同样的问题
找到问题所在了，防火墙地址变了，变成465了。yml文件中的443换成465就能正常上了

**Comment by LittleQBerry** [comment]
> > 同样的问题
> > 找到问题所在了，防火墙地址变了，变成465了。yml文件中的443换成465就能正常上了

感谢，解决了

**Comment by adrewzhang** [comment]
> > > 同样的问题
> > > 找到问题所在了，防火墙地址变了，变成465了。yml文件中的443换成465就能正常上了
> 
> 感谢，解决了

大哥，怎么解决的？我的yml文件里没有什么防火墙地址啊？也没搜到443或者465

**Comment by navee** [comment]
如果是Tun模式的话，检查一下tun设置中的Interface Name是不是正确的

**Comment by josspolo** [comment]
怎么可能没有啊？你是不是找错文件了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月23日 13:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [Fndroid/clash_for_windows_pkg] 3月14日全部节点突然全部Timeout，版本是0.20.18 (Issue #4148) |

同样的问题
找到问题所在了，防火墙地址变了，变成465了。yml文件中的443换成465就能正常上了

感谢，解决了

大哥，怎么解决的？我的yml文件里没有什么防火墙地址啊？也没搜到443或者465

**Comment by adrewzhang** [comment]
> 怎么可能没有啊？你是不是找错文件了
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年03月23日 13:26 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>、State ***@***.***> | | 主题 | Re: [Fndroid/clash_for_windows_pkg] 3月14日全部节点突然全部Timeout，版本是0.20.18 (Issue #4148) | 同样的问题 找到问题所在了，防火墙地址变了，变成465了。yml文件中的443换成465就能正常上了 感谢，解决了 大哥，怎么解决的？我的yml文件里没有什么防火墙地址啊？也没搜到443或者465 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

不是Profiles里的订阅yml文件吗？
![image](https://user-images.githubusercontent.com/40358127/227135663-60d56378-4312-407f-8748-59d5fe485290.png)

**Comment by josspolo** [comment]
是这个文件，找到这里的443端口改成现在的465端口发自我的手机-------- 原始邮件 --------发件人： adrewzhang ***@***.***>日期： 2023年3月23日周四 15:41收件人： Fndroid/clash_for_windows_pkg ***@***.***>抄送： josspolo ***@***.***>, State change ***@***.***>主    题： Re: [Fndroid/clash_for_windows_pkg] 3月14日全部节点突然全部Timeout，版本是0.20.18 (Issue #4148)

怎么可能没有啊？你是不是找错文件了
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年03月23日 13:26 | | 收件人 | @.> | | 抄送至 | @.>、State @.> | | 主题 | Re: [Fndroid/clash_for_windows_pkg] 3月14日全部节点突然全部Timeout，版本是0.20.18 (Issue #4148) | 同样的问题 找到问题所在了，防火墙地址变了，变成465了。yml文件中的443换成465就能正常上了 感谢，解决了 大哥，怎么解决的？我的yml文件里没有什么防火墙地址啊？也没搜到443或者465 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***>

不是Profiles里的订阅yml文件吗？
