### ISSUE TITLE
更新订阅报错

### ISSUE THREAD

**Issue by abae136ab** [Fndroid/clash_for_windows_pkg#415]
![TIM截图20200209223758](https://user-images.githubusercontent.com/56730294/74104220-6e3a2e00-4b8d-11ea-82a9-0871346e5bb1.jpg)
最近好几个版本订阅都无法更新，今天更新0.8.11后报错了。
确认订阅是好的，其他终端或者浏览器均可以下载更新。

**Comment by Fndroid** [comment]
CFW里更新不会被代理，看下是不是被墙了

**Comment by thomas0612** [comment]
8.11版本 出现一样的问题 
经测试 
1.开启CDN情况下域名到国内所有地区解析正常 无法下载
2.关闭CDN后裸连仍然无法正常下载   裸连IP为大陆国外检测正常IP
