### ISSUE TITLE
[Bug]: Ubuntu怎么使用？代理

### ISSUE THREAD

**Issue by chuckrui** [Fndroid/clash_for_windows_pkg#4152]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.18

### 操作系统

Linux

### 系统版本

Ubuntu20.04

### 问题描述

不知道怎么使用？如何使用代理，我在windows下开了，端口那里会显示一个端口号，然后我在手机wifi上输入代理以及端口号就能使用了，但是现在在linux系统下，这个端口号这里没有自动显示出来，是需要配置什么吗？
![1678786179337](https://user-images.githubusercontent.com/76715008/224957019-15be87f9-a4c5-459d-963d-630dc2c40d04.png)
![1678786205320](https://user-images.githubusercontent.com/76715008/224957118-778ed249-0892-4366-b172-b95d752a8917.png)

### 复现步骤

在ubuntu系统上命令行运行./cfw然后启动clash for window 然后进去profile复制我在shdowfly下的链接

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
可能端口被占用，需要检查一下端口专用的问题

**Comment by chuckrui** [comment]
> 可能端口被占用，需要检查一下端口占用的问题

端口被占用？问题是我在windows下用的话，那个端口都是自动的啊，在ubuntu下我都没有用

**Comment by yi-Xu-0100** [comment]
@chuckrui 搜索一下如何检查端口是否被占用，看下有无这个情况。

**Comment by chuckrui** [comment]
> @chuckrui 搜索一下如何检查端口是否被占用，看下有无这个情况。

我想我已经解决了这个问题了，现在更新重新更新一下matter协议应该没问题了
