### ISSUE TITLE
从V0.8.9开始一打开系统代理就会报错

### ISSUE THREAD

**Issue by dragxing** [Fndroid/clash_for_windows_pkg#416]
V0.8.8及之前的都没有问题，从V0.8.9开始一打开代理开关就会弹出一个报错窗口，具体内容是：
![image](https://user-images.githubusercontent.com/52147143/74115453-43ca8e00-4bea-11ea-8ef5-0d83db5ea442.png)
我的系统是Windows10 专业版 1809

**Comment by Fndroid** [comment]
设置过NODE_ENV吗

powershell里执行一下：
```
node --eval="console.log(process.env.NODE_ENV)"
```

看输出什么

**Comment by dragxing** [comment]
输出development，想起来之前学node配的node_env

**Comment by Fndroid** [comment]
@dragxing 清掉应该就行了

**Comment by dragxing** [comment]
> 设置过NODE_ENV吗
> 
> powershell里执行一下：
> 
> ```
> node --eval="console.log(process.env.NODE_ENV)"
> ```
> 
> 看输出什么

输出development，之前学node设置过NODE_ENV

**Comment by dragxing** [comment]
> @dragxing 清掉应该就行了

好了，感谢
