### ISSUE TITLE
[Bug]: Could not switch to this profile ! invalid dns enhanced-mode: redir-host

### ISSUE THREAD

**Issue by Megosztott** [Fndroid/clash_for_windows_pkg#4161]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.18

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

Could not switch to this profile ! invalid dns enhanced-mode: redir-host

### 复现步骤

I just add a new profile to this lastest version and then if I  wanna switch to this new profile. I t shows up: Could not switch to this profile ! invalid dns enhanced-mode: redir-host. And want me to Edit in Text Mode. I Have tried every suggestions that I can find but not one can hrlp me.

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
- https://github.com/Fndroid/clash_for_windows_pkg/issues/4055#issuecomment-1443053448

If you use the mixin or parser, check the enhanced-mode in codes.

**Comment by yeousunn** [comment]
go to profiles and edit the profile. Change the text "redir-host" to "fake-ip".

**Comment by Megosztott** [comment]
I commented out the line of code that contains Gu'an's" Redir host "in the configuration file, and it was resolved.
