### ISSUE TITLE
[Feature Request]: Hello! Been using this tool for a long time and it's great! 👍 But there is a problem. . .

### ISSUE THREAD

**Issue by zhouxinghong** [Fndroid/clash_for_windows_pkg#4163]
### 功能描述

Hello! Been using this tool for a long time and it's great! 👍 But I found a problem. It would be perfect if the position of the tabs on the left side of the UI could allow users to freely drag up and down according to their usage habits. Hope the next version can improve this problem. Thank you so much for such a great tool! Thanks! 😜👍
System: Windows 10
Version: 0.20.18
![2023-03-17_07472888888888885](https://user-images.githubusercontent.com/54253524/225777293-0dd0c90f-d3bf-41e3-ad73-f1df728f1df0.png)

**Comment by Fndroid** [comment]
Right click on one of these items then select `Reorder`
