### ISSUE TITLE
[Bug]: Cannot create a file when that file already exists. type=TUN stackType=system

### ISSUE THREAD

**Issue by OwO996** [Fndroid/clash_for_windows_pkg#4167]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.18

### 操作系统

Windows x64

### 系统版本

22H2

### 问题描述

TUN 模式一直开启不了，Mixin 里的 tun.stack 是 system，cfw 的根目录里也改成 gvisor 了，还是启动失败。

### 复现步骤

安装最新版本 Clash；
安装 service mode；
配置 mixin；
开启 TUN。

### 日志文件

<details><summary>logs</summary><p>

```
00:32:54 ERR [Inbound] start failed error=Error creating interface: Cannot create a file when that file already exists. type=TUN stackType=system inet=198.18.0.1/16
```

</p></details>

### 其他补充

我的 mixin 配置：
`mixin:
  dns:
    enable: true
    enhanced-mode: fake-ip
    use-hosts: true
    default-nameserver:
      - 119.29.29.29
      - 223.5.5.5
      - 8.8.8.8
      - 8.8.4.4
    fake-ip-range: 198.18.0.1/16
    fake-ip-filter:
      - "dns.msftncsi.com"
      - "www.msftncsi.com"
      - "www.msftconnecttest.com"
    nameserver:
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
      - https://doh.360.cn/dns-query
    fallback:
      - https://dns.quad9.net:5053/dns-query
      - https://dns-unfiltered.adguard.com/dns-query
      - https://doh.opendns.com/dns-query
    fallback-filter:
      geoip: false
      ip-cidr:
        - 240.0.0.0/4
      domain:
        - "+.github.com"
  tun:
    enable: true
    stack: system
    auto-route: true
    auto-detect-interface: true`

**Comment by yi-Xu-0100** [comment]
地球有绿吗？日志呢

**Comment by Fndroid** [comment]
设备管理器里找网络适配器，把里面的Clash Tunnel卸载掉

**Comment by OwO996** [comment]
> 设备管理器里找网络适配器，把里面的Clash Tunnel卸载掉

感谢，删了，能开 TUN 了。

**Comment by OwO996** [comment]
> 地球有绿吗？日志呢

是绿色的，感谢回复。
