### ISSUE TITLE
大佬们好，我想请教个问题，clash安装目录下有一个locales文件夹，里面好像是语言包，请问这些怎么使用?

### ISSUE THREAD

**Issue by xiaoJ136** [Fndroid/clash_for_windows_pkg#4175]
Hello guys, I would like to ask a question. There is a 'locales' folder in the clash installation directory, which seems to be language packs. How to use these? Can I use them to change language of clash? Thanks again！

**Comment by Fndroid** [comment]
不是语言包，暂时没有语言切换功能
