### ISSUE TITLE
bilibili的视频文件走了代理

### ISSUE THREAD

**Issue by cranelee** [Fndroid/clash_for_windows_pkg#418]
bilivideo.com域名下的视频文件走了代理。域名加到cfw-bypass也没用

  - '*.bilivideo.com'

**Comment by cranelee** [comment]
同时发现很多网站都走了代理，这是我发现的一部分

  - '*.aliyun.com'
  - '*.chouti.com'
  - '*.chinaz.com'
  - '*.aizhan.com'
  - '*.btschool.club'
  - '*.moviesoon.com'
  - '*.apple.com'

**Comment by Fndroid** [comment]
走不走代理完全是根据你的配置文件

**Comment by Fndroid** [comment]
参考：https://github.com/Dreamacro/clash/tree/dev#config
