### ISSUE TITLE
[Bug]: 安装TAP适配器，添加Mixin后，开启全局代理网络正常，开启Mixin，断网

### ISSUE THREAD

**Issue by niu164** [Fndroid/clash_for_windows_pkg#4186]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.18

### 操作系统

Windows x64

### 系统版本

W10 22H2

### 问题描述

安装tap适配器，启用全局代理，添加Mixin
mixin:
  dns:
    enable: true    
    enhanced-mode: redir-host
    listen: :53
    nameserver:
      - https://doh.dns.sb/dns-query
      - https://dns.adguard.com/dns-query
      - https://cdn-doh.ssnm.xyz/dns-query
      - 119.29.29.29 #腾讯
      - 223.5.5.5 #阿里
启用Mixin
所有网页无法打开，求解决
网络适配器里面cfw-tap 显示无网络连接
![QQ浏览器截图20230324010802](https://user-images.githubusercontent.com/76257039/227283139-2158b858-f8dd-4663-89fb-50d06298ef5c.png)

### 复现步骤

按照问题描述里面操作

### 日志文件

<details><summary>logs</summary><p>

``
[2023-03-24-010330.log](https://github.com/Fndroid/clash_for_windows_pkg/files/11053693/2023-03-24-010330.log)
`

```

</p></details>


### 其他补充

mixin配置：
mixin:
  dns:
    enable: true    
    enhanced-mode: redir-host
    listen: :53
    nameserver:
      - https://doh.dns.sb/dns-query
      - https://dns.adguard.com/dns-query
      - https://cdn-doh.ssnm.xyz/dns-query
      - 119.29.29.29 #腾讯
      - 223.5.5.5 #阿里

**Comment by yi-Xu-0100** [comment]
用 tun,不用 tap

**Comment by niu164** [comment]
> 用 tun,不用 tap

tun模式也能用我发的mixin嘛

**Comment by rangluwme** [comment]
> > 用 tun,不用 tap
> 
> tun模式也能用我发的mixin嘛

对

**Comment by niu164** [comment]
> > > 用 tun,不用 tap
> > 
> > tun模式也能用我发的mixin嘛
> 
> 对

🤔我这个mixin是网上复制的，还不知道有啥用，我是用clash来配合922 s5 proxy的，大佬能看看这个mixin起啥作用嘛，网上教的配合使用是用tap模式+这个mixin

**Comment by rangluwme** [comment]
> > > > 用 tun,不用 tap
> > > 
> > > 
> > > tun模式也能用我发的mixin嘛
> > 
> > 
> > 对
> 
> 🤔我这个mixin是网上复制的，还不知道有啥用，我是用clash来配合922 s5 proxy的，大佬能看看这个mixin起啥作用嘛，网上教的配合使用是用tap模式+这个mixin

其实没必要，你先打开service mode，然后打开自带的Tun mode就行了，tun里面的dns就够用了，或者你再添加dns都是可以的，mixin用不到的，mix是为了写入初始配置用的，不要用tap了，tun模式更好。

**Comment by feileb** [comment]
clash不支持redirect-host以后，tap模式就无效了
