### ISSUE TITLE
[Bug]: 更换节点一直提示无法切换到此配置文件

### ISSUE THREAD

**Issue by bigyangsoul** [Fndroid/clash_for_windows_pkg#4189]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.19

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

 一是提示无法切换到此配置文件 换了好几个版本都不行 
![微信图片_20230324154204](https://user-images.githubusercontent.com/128787435/227458883-fcd347d9-661c-4388-9716-faa90227b7fc.png)

### 复现步骤

换了很多个版本都切换不了

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
配置文件有问题
