### ISSUE TITLE
[Bug]: Update cron 设置5分钟更新一次 不生效

### ISSUE THREAD

**Issue by syanming** [Fndroid/clash_for_windows_pkg#4191]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.19

### 操作系统

Windows x64

### 系统版本

windows11

### 问题描述

在profiles->settings>update cron中设置profile文件自动更新
设置为 0 0/5 * * *
5分钟过后依旧没有刷新
![Snipaste_2023-03-24_18-35-29](https://user-images.githubusercontent.com/34526129/227498729-f97a4c6e-b0a6-4830-8fe5-140f069120c8.jpg)
![Snipaste_2023-03-24_18-37-26](https://user-images.githubusercontent.com/34526129/227499155-ae191ad4-5a34-41d2-9291-875fc9424289.jpg)

### 复现步骤

在profiles->settings>update cron中设置profile文件自动更新
设置为 0 0/5 * * *

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by syanming** [comment]
![image](https://user-images.githubusercontent.com/34526129/227498944-b3a8b0e7-f4bd-4877-943b-066e8f1d6cf8.png)

**Comment by yi-Xu-0100** [comment]
有没有可能你设置错了。 https://crontab.guru/#0_0/5_*_*_*

![image](https://user-images.githubusercontent.com/25523606/227499542-70c6fa26-e10e-474a-a460-75a45c52a11f.png)

**Comment by syanming** [comment]
> 有没有可能你设置错了，你这是每五小时吧。 https://crontab.guru/#0_0/5_____*
> 
> ![image](https://user-images.githubusercontent.com/25523606/227499542-70c6fa26-e10e-474a-a460-75a45c52a11f.png)

我按照这个方式设置后依旧没有生效
