### ISSUE TITLE
不打开clash软件，epic库存就断网，单纯是打开软件不开代理

### ISSUE THREAD

**Issue by Rache886** [Fndroid/clash_for_windows_pkg#4194]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.12

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

只有打开clash，epic商城库存才会更新，在connection里面会看到epic的连接信息，显示是直连。关闭clash，库存不再更新也不能刷新，但是点击库存中刚刚更新的那些游戏图标右键，下载或者转到商城页面的功能都可以，但是收藏功能不行。这些都建立在单纯打开clash但不开启代理的基础上，我很疑惑的是epic自带的网络检测没有问题但是不打开clash就不行。当我把profiles文件删除后，依旧不打开不行，并且clash卸载后，依旧不能更新，重装后只有打开clash后才能更新库存。以上出现无法更新库存的情况包括刷新按钮消失，新购买和白嫖的游戏无法显示，游戏库游戏减少或者清空只剩下安装的游戏。这个问题从我用的版本到一年多前的版本都没有解决，网上没有同类，应该是我的问题，但是不知道是不是clash的问题。在游玩overwatch的过程中出现（关于导致其他会影响库存更新的解决办法我几乎都试过了）在游玩overwatch的过程中出现正在更新的显示，如果不打开clash就会更新失败退出游戏，打开后在connect界面就会出现直连标志，更新成功。

![image](https://user-images.githubusercontent.com/32485970/227551315-daa83cf0-3423-4ceb-89c3-3c9fee93efb4.png)

### 复现步骤

打开epic库，退出clash，库不能更新然后点击右键功能会变灰，库存可能会自动清空

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
用 pac ，然后直接绕过 clash 试试。

**Comment by Rache886** [comment]
> 用 pac ，然后直接绕过 clash 试试。

**Comment by Rache886** [comment]
解决了，确实是应该绕过clash，使用任务管理器强制关闭而不使用clash自带的退出关闭即可解决
