### ISSUE TITLE
[Bug]: Ubuntu 20.04 无法连接，好像配置不起作用

### ISSUE THREAD

**Issue by chenjch906** [Fndroid/clash_for_windows_pkg#4197]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.19

### 操作系统

Linux

### 系统版本

ubuntu 20.04

### 刚刚下载了 0.20.19 版本软件，然后一直连不上

- 执行 ./cfw 有报错
`libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed`
`/bin/sh: 1: kill: No such process`
- PC 连接设置
  - 使用网线直连，关闭了网络代理配置，关闭了 wifi
- Setting 界面是默认没有修改
- General 配置
![image](https://user-images.githubusercontent.com/20964307/227710045-28832d89-f29e-43f3-8aa9-73aa8c23b04c.png)
- log 界面没有更新，google.com 连不上
![image](https://user-images.githubusercontent.com/20964307/227710157-077e213c-62e7-4285-9485-a0427bada5e0.png)

### 复现步骤

直接能复现

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by chenjch906** [comment]
另外说下不是 Port 为 0 的问题，我重启后是这个配置，也一样无法访问 google.com
![image](https://user-images.githubusercontent.com/20964307/227710689-052adc07-f18d-41c1-8947-61b45bc4eeea.png)

**Comment by yi-Xu-0100** [comment]
linux 的话， 你系统设置代理了吗？如果没有，搜索下，怎么给你的系统（比如 ubuntu）设置代理？

**Comment by chenjch906** [comment]
已解决，系统设置代理就好了

**Comment by xuyanging** [comment]
你们都是从哪里看到linux下的教程的？我这边只能windows用，linux用的是wsl2
