### ISSUE TITLE
[Bug]: linux 下使用clash for windows 无法正常访问

### ISSUE THREAD

**Issue by euminds** [Fndroid/clash_for_windows_pkg#4201]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.14(0.20.19问题仍存在）

### 操作系统

Linux

### 系统版本

Linux version 5.15.0-67-generic (buildd@lcy02-amd64-029) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023

### 问题描述

按照教程正常配置clash，访问外网超时，百度和局域网均正常。
![image](https://user-images.githubusercontent.com/46481864/227751242-386e3f86-fef2-4f41-b240-4e8c0aa873eb.png)
![image](https://user-images.githubusercontent.com/46481864/227751253-ba8f28f3-db32-43ab-93fc-1eaea5c13432.png)
![image](https://user-images.githubusercontent.com/46481864/227751264-e9bce6b6-923e-4786-a812-78ca3774476b.png)
![image](https://user-images.githubusercontent.com/46481864/227751289-14634d03-4bb3-47ba-a767-9f6a1bec68dd.png)

### 复现步骤

正常安装后启动./cfw即可

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
日志？

**Comment by euminds** [comment]
> 日志？

linux下关于clash的日志在哪找，小白不知道哪里找

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/227861282-246bbb7c-66c1-451a-bd81-4b21a1258e69.png)

**Comment by euminds** [comment]
> ![image](https://user-images.githubusercontent.com/25523606/227861282-246bbb7c-66c1-451a-bd81-4b21a1258e69.png)

日志文件命名是啥

**Comment by yi-Xu-0100** [comment]
@euminds 是日期吧应该

**Comment by euminds** [comment]
> @euminds 是日期吧应该

给了cfw权限可以了

**Comment by Milkve** [comment]
> > @euminds 是日期吧应该
> 
> 给了cfw权限可以了

大佬细说怎么给的权限，我在解压以后的文件夹 `sudo ./cfw --no-sandbox` 执行以后只剩一个空界面了
