### ISSUE TITLE
[Bug]: tun模式下协议栈的选择貌似会影响udp连接

### ISSUE THREAD

**Issue by rbbt065** [Fndroid/clash_for_windows_pkg#4202]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.19

### 操作系统

Windows x64

### 系统版本

Win11 22H2

### 问题描述

我目前使用方法是在笔记本上使用clash，开启tun模式并将tun网卡共享给无线热点网卡以实现手机翻墙。

但是使用过程中发现在协议栈类型为system条件下（已添加防火墙例外），手机开启wifi-calling后会产生udp连接，但不会有上下行数据，并且在几分钟后这个连接会消失。但将协议栈切换为gvisor后，手机上的wifi-calling可以成功建立udp连接并且有上下行数据传输。

所以目前推测是tun模式协议栈引发的问题。

### 复现步骤

stack为system时100%复现

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
Clash core issue, Search or post in <https://github.com/Dreamacro/clash/issues>
