### ISSUE TITLE
[Bug]: 开启tun模式无法全局代理，无法使用git clone命令，

### ISSUE THREAD

**Issue by wzgrx** [Fndroid/clash_for_windows_pkg#4205]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.19

### 操作系统

Windows x64

### 系统版本

win11

### 问题描述

git clone 拉取仓库，显示 
OpenSSL/1.1.1s: error:1408F10B:SSL routines:ssl3_get_record:wrong version number，
unable to access '/': Recv failure: Connection was reset
OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443

tun模式不是全局代理吗，为什么cmd不走命令

### 复现步骤

使用cmd访问github都会报错，除了cmd或者powershell，其他网站访问都正常

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
日志看看

**Comment by wzgrx** [comment]
> 日志看看

window安装目录没有log

**Comment by wzgrx** [comment]
安装之前的 设置ssh
Host github.com
Hostname ssh.github.com
Port 443
User git

设置后还是用不了git，报错SSL_ERROR_SYSCALL in connection to github.com:443
