### ISSUE TITLE
[Bug]: 启用TUN模式，电脑从睡眠状态启动后无法联网，需重启才能重新联网

### ISSUE THREAD

**Issue by Indolencoma** [Fndroid/clash_for_windows_pkg#4206]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.19

### 操作系统

Windows x64

### 系统版本

windows 11 22H2

### 问题描述

启用TUN模式，如果电脑进入睡眠一段时间，再次启动后无法联网，日志中出现大量dial failed提示，需要重新启动CFW才能联网。
该问题从0.20.17开始出现，0.20.16及以前未发现类似问题。

附上日志截图：
![image](https://user-images.githubusercontent.com/128992392/227790263-a5170ac1-c0fb-4a44-b8a4-dc974cc090c3.png)

### 复现步骤

电脑设置的是10分钟关闭屏幕同时睡眠，如果睡眠超过10分钟或更长时间，一般再次启动后都会出现

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by tony1016** [comment]
为什么关了，确认我也有这个问题

**Comment by Indolencoma** [comment]
> 为什么关了，确认我也有这个问题

我自己关的，当时关键词没搜到，换了“dial [failed”搜就搜到了相似的。[https://github.com/Fndroid/clash_for_windows_pkg/issues/4169](url)，
目前已经关了Auto Detect Interface，暂时没有再出现问题，等修复了
