### ISSUE TITLE
[Feature Request]: 建议添加一个仅更新订阅，不更新规则的功能

### ISSUE THREAD

**Issue by Fly-Felix** [Fndroid/clash_for_windows_pkg#4207]
### 功能描述

由于我使用的订阅每天会自动换ip，所以我每天必须更新一次订阅，重新更新订阅的时候会导致先前编辑的规则被覆盖，每次更新订阅都需要重新编辑一次，我编辑最频繁的规则只有一个那就是：translate.googleapis.com这个地址目前默认规则是“全球直连”，但这个在国内停用了，所以无法访问，每次都需要修改成“节点选择”，每次编辑一下只需要几秒就搞定了，如果之后有多个规则需要修改的话就比较麻烦了

**Comment by yi-Xu-0100** [comment]
diff 或者 parser

https://docs.cfw.lbyczf.com/contents/diff.html

https://docs.cfw.lbyczf.com/contents/parser.html

**Comment by Fly-Felix** [comment]
感谢，我目前用Diif方式实现了

**Comment by Fly-Felix** [comment]
> diff 或解析器
> 
> https://docs.cfw.lbyczf.com/contents/diff.html
> 
> https://docs.cfw.lbyczf.com/contents/parser.html

感谢，我目前用Diif方式实现了
