### ISSUE TITLE
[Bug]: clash强制代理，epic等一些应用根本无法联网

### ISSUE THREAD

**Issue by Rache886** [Fndroid/clash_for_windows_pkg#4208]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.19

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

只要退出clash，epic库就无法更新，无网络连接，卸载epic后，重新安装也无法联网安装，打开clash就可以联网，把clash所有信息数据都从windows删除，重置网络，网卡修复，代理网络修复，epic管理员运行，dns修复，lsp修复，淘宝店家，防火墙规则设置等等都没用。必须下回来clash才能联网，明明没有开启代理，clash就强制代理一些网络地址走规则，包括全局或者直连或者全局流量，凡是这些connections所包含的网址，只要关闭clash，那些需要这些连接的应用就无法直接连接到internet网络，这些应用必须走clash相对应端口才能连接，导致了关闭clash后这些应用的一些特定连接网络的功能就再也无法连接到网络。上一次任务管理器直接关闭clash后，能正常联网是因为clashwin64.exe没有关闭依旧在后台运行。心态崩了，这玩意有毒。

### 复现步骤

应该是用上就出事，电脑没好无法复现

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

原始配置就出事，连profile导入都不需要。

**Comment by Fndroid** [comment]
进系统设置里把系统代理关闭

**Comment by Rache886** [comment]
> 进系统设置里把系统代理关闭

没有用呀，这么简单我会不知道吗π_π

**Comment by Fndroid** [comment]
那关闭了还能怎么影响你网络呢

**Comment by Rache886** [comment]
> 那关闭了还能怎么影响你网络呢

貌似epic依旧去连那个7890端口，没有clash就没网，打开clash就自动联网，连接显示的地址host本地全能ping到

**Comment by Rache886** [comment]
> 那关闭了还能怎么影响你网络呢

epic官方那边怀疑有可能是代理产生的问题，还不知道下文，反正clash是正常关闭的，后台全清的，我删除过去版本的所有遗留文件后重装了新版clash，依旧是有问题

**Comment by Rache886** [comment]
> 那关闭了还能怎么影响你网络呢

还有一个网游在更新后进入游戏，在游戏内还要一个小的更新，也是依旧无法更新直接崩溃，一打开clash就好了，怀疑是同样的问题

**Comment by yi-Xu-0100** [comment]
@Rache886 clash 并不会设置软件的代理，只会设置系统代理，系统代理恢复了就和clash无关了。建议排查自己做的相关的设置项。

**Comment by Rache886** [comment]
> 那关闭了还能怎么影响你网络呢

破案了，fiddler网络抓包软件打开后也是代理，epic也能联网了，目前原理和原因还不懂，为啥他们一打开就行
