### ISSUE TITLE
[Bug]: 本地 hosts 失效

### ISSUE THREAD

**Issue by jiakme** [Fndroid/clash_for_windows_pkg#4213]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.19

### 操作系统

Linux

### 系统版本

5.15.102-1-MANJARO

### 问题描述

使用最新版本后, 切换本地 host 无效, 代理还是访问外网地址.

### 复现步骤

修改本机 hosts, chrome 依旧访问外网地址. 

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
dns 配置中有 use-hosts 和 host 配置项

**Comment by jiakme** [comment]
这样子调整实在是不方面.  我这边因为工作学习需要, 不时需要切换 hosts, 依赖本地 hosts 切换, 使用 clash 太不方便啦~您这边看是否可以更新一下技术设计.

**Comment by yi-Xu-0100** [comment]
@jiakme Clash core issue, Search or post in <https://github.com/Dreamacro/clash/issues>

**Comment by xdaniel9** [comment]
我也遇到这个问题，有解决方案了吗

**Comment by jiakme** [comment]
设置 DNS 不启用

**Comment by xdaniel9** [comment]
> 设置 DNS 不启用

已经在data/config.yaml里添加了，还是不行
```
dns:
  use-hosts: true
  enable: false
```

**Comment by jiakme** [comment]
![image](https://user-images.githubusercontent.com/8815138/233543097-5762ded4-5949-442c-ac96-bf9f4f39efd2.png)

```
mixin: # object
    dns:
      enable: false
```

**Comment by xdaniel9** [comment]
解决了，thx
