### ISSUE TITLE
[Bug]: PAC+TUN没网

### ISSUE THREAD

**Issue by WSJJS** [Fndroid/clash_for_windows_pkg#4214]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.19

### 操作系统

Windows x64

### 系统版本

21H2

### 问题描述

为什么proxy从HTTP改到PAC后，打开tun mode就没网，然后system porxy就能正常上网，但是在PAC下，打开system porxy
的话Discord就无法使用，但为了加速器正常加速游戏情况下又不能开http下的tun影响游戏体验，又能保证Discord有网络可以聊天就只能换PAC用了，但在PAC下我开TUN是没网的，日志也全红

### 复现步骤

proxy改PAC，打开tun mode

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
日志？

**Comment by WSJJS** [comment]
就是在logs这里显示红完，然后没网，无论是浏览器还是其他软件

**Comment by WSJJS** [comment]
![20230328171434](https://user-images.githubusercontent.com/93639515/228190220-69fa8ad6-ddc7-4914-8a4c-c1ed000e9267.png)

**Comment by WSJJS** [comment]
@yi-Xu-0100 然后在任务管理器中clash-win64.exe会CPU占用高，clash变卡，最后只能通过任务管理器关闭clash才能重新有网

**Comment by WSJJS** [comment]
[2023-03-28-165542.log](https://github.com/Fndroid/clash_for_windows_pkg/files/11087955/2023-03-28-165542.log)
[2023-03-27-215457.log](https://github.com/Fndroid/clash_for_windows_pkg/files/11087960/2023-03-27-215457.log)

**Comment by WSJJS** [comment]
现在又出现新问题，http下开tun也用不了，也是断网，然后connections里看链接数几千，过一会clash卡死再次点开画面空白
![QQ图片20230328200447](https://user-images.githubusercontent.com/93639515/228233245-b201c417-241d-497c-8383-4d19d4eb6046.png)

**Comment by WSJJS** [comment]
已解决，虽然不知道什么原因，但我在win10设置里网络重置后可以正常使用了
