### ISSUE TITLE
[Bug]: 无法注册新的账号，提示无法验证

### ISSUE THREAD

**Issue by WanyueKJ** [Fndroid/clash_for_windows_pkg#4220]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

https://cp.antigfw.net/

### 操作系统

Windows x64

### 系统版本

https://cp.antigfw.net/

### 问题描述

我邀请了其他朋友，使用gogocloud，在注册时提示无法通过验证，一直无法注册成功

### 复现步骤

重新注册一个新账号即可

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

无

**Comment by yi-Xu-0100** [comment]
该软件不需要注册账号（
