### ISSUE TITLE
[Bug]: 看到有讨论说Clash断线太快、会导致被ChatGPT拦截？

### ISSUE THREAD

**Issue by git-syl** [Fndroid/clash_for_windows_pkg#4227]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.19

### 操作系统

Windows x64

### 系统版本

Windows 11  22H2

### 问题描述

讨论原帖：https://www.v2ex.com/t/926415

_chatGPT 问多个个问题时候，第二个问题开始必须刷新页面，怀疑是后台连接断的太快了然后重连的时候被 cloudfare 拦了，换用 v2rayN 之后就没有出现过问题，都是用的一个 clash 规则，差异只在软件上，而且我还专门试了几次才定位到根源。可惜 v2rayN 在 clash 配置方面人性化程度稍微低了一点，但是我终于不用每次问问题都得刷新页面了！_

——最近看到v站有讨论说Clash会导致ChatGPT拦截，希望作者可以确认下。非常感谢。

### 复现步骤

使用ChatGPT，提问后稍等片刻，再问第二个问题。发现失败。刷新后触发cf 验证。 怀疑是后台连接断的太快了然后重连的时候被 cloudfare 拦了，其他软件无这个问题。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by QS0x01** [comment]
跟 clash 有啥关系，你开个下载几个小时都不会断线，openai那边没响应所以断了。

而且虽然断的快，这边实测也不会第二个问题就断，只能说你节点不行。
