### ISSUE TITLE
[Bug]: YouTube无法发表评论

### ISSUE THREAD

**Issue by haoxiaoyueh** [Fndroid/clash_for_windows_pkg#4237]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.19

### 操作系统

Windows x64

### 系统版本

Windows 11 专业版 21H2

### 问题描述

无法在YouTube上发表评论，显示“未能发表评论”。确定不是节点的问题，相关的机场节点换了5家都不行，同样的节点v2ray就可以了。这是什么原因？

### 复现步骤

打开YouTube网站，点进一条视频，使用一条可用的线路进行评论，会发现视频可以观看，评论无法交互

**Comment by yi-Xu-0100** [comment]
log 看看
