### ISSUE TITLE
[Feature Request]: 订阅文件的响应头为中文会乱码

### ISSUE THREAD

**Issue by sakz** [Fndroid/clash_for_windows_pkg#4240]
### 功能描述

https://docs.cfw.lbyczf.com/contents/urlscheme.html#%E4%B8%8B%E8%BD%BD%E9%85%8D%E7%BD%AE
content-disposition: attachment; filename="abc.yaml"
如果abc.yaml是中文的话，会乱码，这个怎么解决

**Comment by Fndroid** [comment]
content-disposition要按规范

**Comment by sakz** [comment]
> content-disposition要按规范

```
ctx.set('Content-Disposition', `attachment; filename="${encodeURIComponent(fileName)}"`);
```
应该做url转码了，浏览器打开订阅链接也能正常下载，中文文件名也能正常显示，但是clash的文件名是转码后，这种情况怎么处理

**Comment by Fndroid** [comment]
`attachment; filename*=UTF-8''<URL编码后的文件名>`

浏览器能识别是因为它不按规范识别

**Comment by sakz** [comment]
> `attachment; filename*=UTF-8''<URL编码后的文件名>`
> 
> 浏览器能识别是因为它不按规范识别

这样改了之后，再把客户端更新到最新版本，可以正常显示了，感谢回复，可以关闭了
