### ISSUE TITLE
[Feature Request]: 建议增加筛选器关键字保存功能。

### ISSUE THREAD

**Issue by Jason525** [Fndroid/clash_for_windows_pkg#4248]
### 功能描述

![image](https://user-images.githubusercontent.com/16285695/229391141-56e1a550-c8b8-41ab-809c-cc86dbf6f776.png)
每次启动软件之后都需要手动输入筛选关键字。能不能把这个关键字保存下来，下次启动自动筛选呢？

**Comment by yi-Xu-0100** [comment]
建议用parser做个group

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
