### ISSUE TITLE
安装好后打开Profile一片空白

### ISSUE THREAD

**Issue by Recollections** [Fndroid/clash_for_windows_pkg#425]
版本：0.8.10&0.8.11
![1jViqJ.png](https://s2.ax1x.com/2020/02/14/1jViqJ.png)
如图，安装好后就是这样，无法导入配置。无法使用。

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/360

**Comment by Recollections** [comment]
![1j1gAO.png](https://s2.ax1x.com/2020/02/14/1j1gAO.png)
安装目录内没有profiles文件夹

**Comment by Fndroid** [comment]
general 里 home directory 目录，不是安装目录

**Comment by Recollections** [comment]
找到了，在C:\Users\(用户名)\.config\clash内
