### ISSUE TITLE
[Bug]: 无法切换配置文件

### ISSUE THREAD

**Issue by djkddddd** [Fndroid/clash_for_windows_pkg#4255]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.19

### 操作系统

Windows x64

### 系统版本

window11

### 问题描述

![638d13412054ef566e12ff31b3456c4](https://user-images.githubusercontent.com/124492560/229537422-f20fb8a9-ac62-4ab7-9e81-dd3d77ce6cf6.png)

### 复现步骤

![638d13412054ef566e12ff31b3456c4](https://user-images.githubusercontent.com/124492560/229537422-f20fb8a9-ac62-4ab7-9e81-dd3d77ce6cf6.png)

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by QS0x01** [comment]
下次开 issue 前不如动手自己搜下历史记录。

https://github.com/Fndroid/clash_for_windows_pkg/issues/4161
