### ISSUE TITLE
下载Profiles时提示报错

### ISSUE THREAD

**Issue by Recollections** [Fndroid/clash_for_windows_pkg#426]
版本：0.8.11
![1jwKl8.png](https://s2.ax1x.com/2020/02/14/1jwKl8.png)
如图，承接上个issue中删掉了profiles文件夹后，clash的profiles是恢复正常了，但是无法正常导入yml文件。yml链接没问题（在另一台电脑上一切正常，不用删profiles文件夹就直接顺利导入了），网络也正常。

**Comment by Fndroid** [comment]
超时了，20s下载不了
