### ISSUE TITLE
allow lan 开启认证的小问题，麻烦帮一下忙

### ISSUE THREAD

**Issue by YirunFantasy** [Fndroid/clash_for_windows_pkg#4267]
翻阅clash的文档，查询到
 ```
#authentication of local SOCKS5/HTTP(S) server
 authentication:
  - "user1:pass1"
  - "user2:pass2"
```
  我确实需要配置这个认证，想问下，这是要编写两个帐户密码吗？
还有，user1&user2是电脑开机登录的账户名还是我可以自定义创建用于clash认证的，电脑小白，请解答一下
我这样写对吗，需要写两个账户吗
 ```
authentication:
  - "XiaoSun:mypasswordTEST"
```

**Comment by yi-Xu-0100** [comment]
这个好像是随意设置的，是指当使用代理时，都需要进行这个验证，可以自定义设置多个。

但是注意，这样本机使用也同样如此，浏览器需要进行验证才能使用，而且由于 windows 没有保存验证信息的能力，好像每次都会触发输入验证，过于繁琐。

**Comment by YirunFantasy** [comment]
> 这个好像是随意设置的，是指当使用代理时，都需要进行这个验证，可以自定义设置多个。
> 
> 但是注意，这样本机使用也同样如此，浏览器需要进行验证才能使用，而且由于 windows 没有保存验证信息的能力，好像每次都会触发输入验证，过于繁琐。
> 

好的，谢谢
