### ISSUE TITLE
interfere show me a error

### ISSUE THREAD

**Issue by mei19830821** [Fndroid/clash_for_windows_pkg#427]
the error is:
time="2020-02-15T00:59:11+08:00" level=fatal msg="Can't load mmdb: error opening database: invalid MaxMind DB file"
i tried 3 os, 2 win10 1909 & 1903, win7 not this error but is not work. i use the same node on clash for android. node is ok.

**Comment by Fndroid** [comment]
Try clicking the “Try to repair” button
