### ISSUE TITLE
[Bug]: 当Windows用户名中含有空格时，开机不能自动启动

### ISSUE THREAD

**Issue by zyzsdy** [Fndroid/clash_for_windows_pkg#4273]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.19

### 操作系统

Windows x64

### 系统版本

Windows 11 build 23424

### 问题描述

当Windows用户名中含有空格时，无法自动启动。

### 复现步骤

1. 建立一个新的Windows用户，用户名中包含空格。
2. 为当前用户安装Clash For Windows
3. 运行软件，然后打开Start with Windows
4. 重启电脑，Cfw没有自动启动。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

若Windows用户名中没有空格，此功能正常。

**Comment by yi-Xu-0100** [comment]
@zyzsdy 看看开机自启的注册表条目是不是需要加上引号。

但是还是不建议有空格，或者中文目录。

**Comment by Fndroid** [comment]
调用的是Electron提供的API，无法调整
