### ISSUE TITLE
[Feature Request]: 可以让CFW在Linux下以静默的方式自动启动吗？

### ISSUE THREAD

**Issue by Knighthana** [Fndroid/clash_for_windows_pkg#4278]
### 功能描述

当CFW在我的桌面环境上被设置为随用户登入自动启动的时候，它会在启动完成后在桌面显示一个可见的窗口
我注意到在Microsoft Windows下的CFW自动启动时不会弹出窗口，仅仅只是在后台静默运行
我在Linux的CFW自动启动设置是通过启用CFW“General”面板中的“Start with Linux“选项进行的
我留意到这是通过向“会话和启动”中添加了一个启动"cfw"可执行文件的条目实现的
我试图在目录中寻找一个能够不显示窗口的静默启动方式，但没有找到这样的可执行二进制文件

请问目前有实现静默启动方式的方法吗？
或者可以添加这样的功能吗？

**Comment by yi-Xu-0100** [comment]
setting -> silent start

**Comment by Knighthana** [comment]
I didn't notice it ago,
My bad, sorry for that issue .......

**Comment by whu-lyh** [comment]
这样设置之后，如何重新打开界面呢？
