### ISSUE TITLE
有时Clash无法开机正常启动

### ISSUE THREAD

**Issue by 00why00** [Fndroid/clash_for_windows_pkg#428]
有时开机后会出现下面的情况，System Proxy会被强制关闭，Port和Socks Port会变为0
![image](https://user-images.githubusercontent.com/30547971/74582691-fab77700-4ff9-11ea-9f26-7c290a923c9a.png)
与配置文件中的端口号不一致
![image](https://user-images.githubusercontent.com/30547971/74582732-5d107780-4ffa-11ea-8ef9-399fd4d8f398.png)

**Comment by Fndroid** [comment]
看日志

**Comment by 00why00** [comment]
level=error msg="Start HTTP server error: listen tcp 127.0.0.1:7890: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
这是什么意思，端口没有被占用啊

**Comment by 00why00** [comment]
> 看日志
level=error msg="Start HTTP server error: listen tcp 127.0.0.1:7890: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
这是什么意思，端口没有被占用啊

**Comment by 00why00** [comment]
> 看日志

level=error msg="Start HTTP server error: listen tcp 127.0.0.1:7890: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
这是什么意思，端口没有被占用啊

**Comment by Fndroid** [comment]
很明显了，这7890端口不能开启，在config.yml里改一个别的吧
