### ISSUE TITLE
【问题】`showTrayProxyDelayIndicator` 是干啥用的

### ISSUE THREAD

**Issue by wenfangdu** [Fndroid/clash_for_windows_pkg#4281]
发现配置文件里有，但在文档里并没有找到，开启/关闭分别有什么效果呢？

**Comment by yi-Xu-0100** [comment]
会在图标右键里的节点选择左边显示延迟指示。

**Comment by wenfangdu** [comment]
@yi-Xu-0100 多谢。给未来读者，就是这个：
![image](https://user-images.githubusercontent.com/28700378/230553254-a8a4c7c3-eb2e-4ca6-832e-e48e5ffdce77.png)
