### ISSUE TITLE
[Feature Request]: 新增系统开机启动

### ISSUE THREAD

**Issue by imzeroan** [Fndroid/clash_for_windows_pkg#4288]
### 功能描述

新增开机自启动

**Comment by yi-Xu-0100** [comment]
有吧。

**Comment by wenfangdu** [comment]
你是什么系统，windows 和 macOS 都有开机自启的选项

**Comment by imzeroan** [comment]
> 你是什么系统，windows 和 macOS 都有开机自启的选项

不好意思，在settings里找了半天没找到，原来在general里：P
