### ISSUE TITLE
经常断流打不开网页，过一会或刷新几次就好。

### ISSUE THREAD

**Issue by milohsu** [Fndroid/clash_for_windows_pkg#429]
查看日志提示一下错误。
time="2020-02-15T17:20:11+08:00" level=warning msg="dial 📹 YouTube error: Dial cuteus.zhileshu.com error: 429 Too Many Requests"
time="2020-02-15T17:20:11+08:00" level=info msg="[TCP] 127.0.0.1:6646 --> r3---sn-i3b7kn7r.googlevideo.com match DomainSuffix using 📹 YouTube[🇺🇲 BGP 美国Netflix(1)]"
time="2020-02-15T17:20:11+08:00" level=warning msg="dial 📹 YouTube error: Dial cuteus.zhileshu.com error: 429 Too Many Requests"
time="2020-02-15T17:20:11+08:00" level=warning msg="dial 📹 YouTube error: Dial cuteus.zhileshu.com error: 429 Too Many Requests"
time="2020-02-15T17:20:11+08:00" level=warning msg="dial 📹 YouTube error: Dial cuteus.zhileshu.com error: 429 Too Many Requests"

用v2rayN都正常的，能看看是什么原因不。

**Comment by Fndroid** [comment]
这个看起来是机场禁止的，可能是 url test 导致机场限制连接了

**Comment by milohsu** [comment]
好的，感谢了哈

**Comment by milohsu** [comment]
机场不改限制数，软件可以禁用url test么

**Comment by Fndroid** [comment]
用不用url test和软件无关，和你自己的配置文件有关

**Comment by mesotescode** [comment]
我连续试了Clash.for.Windows-0.20.29、0.20.30、0.20.31三个版本，360极速浏览器断连次数频繁，同样的节点挂v2rayN使用同一浏览器就不会断连。
反复刷新几次后又能重新连接上。系统代理模式、tun模式均是如此。此外tun模式有的网页链接无法打开，关掉tun模式就可以。
我看有一些网友反馈：clash貌似浏览器标签页开多了 节点就会断连一阵。
