### ISSUE TITLE
[Bug]: URL配置下载失败

### ISSUE THREAD

**Issue by ouershuoshuoxiri** [Fndroid/clash_for_windows_pkg#4293]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.85

### 操作系统

Windows x64

### 系统版本

Windows10

### 问题描述

URL配置下载失败，更新后也是下载失败

### 复现步骤

![URL下载失败](https://user-images.githubusercontent.com/105426507/230732609-5231d616-e0a2-4489-8101-35b77f66e103.png)

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
请使用官方版本（未替换及修改过安装目录程序文件）

**Comment by ouershuoshuoxiri** [comment]
我是按照教程下载的啊

**Comment by ouershuoshuoxiri** [comment]
那该怎么下载并使用呢？

**Comment by ouershuoshuoxiri** [comment]
我去官方没有看到x64的下载版本呢？

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/235124452-06f08ff7-afbe-4989-94de-e01ae4d32009.png)

https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.20.22

**Comment by ouershuoshuoxiri** [comment]
可以了，感谢
