### ISSUE TITLE
[Bug]: 校园网无线网可以访问外网，有线网经常性掉线，几乎不能用

### ISSUE THREAD

**Issue by Dopamine-AI** [Fndroid/clash_for_windows_pkg#4296]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.19

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

使用校园网，如果使用以太网就经常性不能访问外网，偶尔可以访问，国内网可以访问，如果是使用wifi的话（也是校园网），访问外网很流畅。
如果使用以太网的话，使用一些插件可以流畅访问外网。
估计是一些设置问题，我是小白，请问大佬如何解决呢

### 复现步骤

使用校园网应该可以复现

**Comment by louis-star** [comment]
win11校园网也有同样的问题，连上cfw后一段时间能用，过一段时间就会断掉，有时候重启电脑也无法解决。

**Comment by Crea-ntech** [comment]
我也有类似问题，当时从网上搜了很多方法尝试。经过实践，这个是本人电脑和网络环境下唯一有效的办法：

**禁用PMTU发现**
如果禁用了 PMTU 发现，则 TCP 将仅发送 MTU 大小为 576 且未设置 Don't Fragment 位的数据包。这样路由器就能够将数据包分段并跨网络发送数据包。 
此方法影响发送到所有目标的数据包。通常，在数据包大小为 576 时，性能处于一个可接受的级别，但是，如果启用了 PMTU 发现且路径支持的 MTU 大小大于 576，则性能将会更低。 
要禁用 PMTU 发现，请按照下列步骤操作：
1.	单击“开始”，单击“运行”，键入 regedit，然后单击“确定”。
2.	在注册表中找到下面的项：  
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
3.	在“编辑”菜单上，指向“新建”，然后单击“DWORD 值”。
4.	键入 EnablePMTUDiscovery，然后按 Enter。
5.	在“编辑”菜单上，单击“修改”。
6.	在“数值数据”框中，键入 0，然后单击“确定”。
7.	退出注册表编辑器，然后重新启动计算机。
[https://support.microsoft.com/zh-cn/topic/%E4%B8%BA-mtu-%E5%A4%A7%E5%B0%8F%E4%BD%8E%E4%BA%8E-576-%E7%9A%84-wan-%E9%93%BE%E6%8E%A5%E6%8E%A8%E8%8D%90%E7%9A%84-tcp-ip-%E8%AE%BE%E7%BD%AE-2312050e-2a1b-1e89-94a1-b2868afa436f](url)

当时我的问题是没法正常访问google、Youtube等网站，但是对于其他同样需要魔法的网站却仍然能正常访问。虽然不知道什么原理，但是使用了此方法后确实成功解决了无法正常访问google、Youtube网站的问题。

我是用了这个方法才解决的，之前还从见到过一些修改连接名字成英文，修改端口的方法，但是在自己的机器上都没有效果。
