### ISSUE TITLE
RK3399PRO主板启动程序后，配置好网络代理，无法上外网

### ISSUE THREAD

**Issue by STRIVESS** [Fndroid/clash_for_windows_pkg#4298]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.17

### 操作系统

Linux

### 系统版本

arm64

### 问题描述

您好！在RK3399 PRO主板，按照以下操作配置网络代理，重启电脑，并启动了./cfw程序后，但是仍然无法访问外网
`export http_proxy=http://127.0.0.1:7890`
`export https_proxy=https://127.0.0.1:7890`
`echo $http_proxy`
`echo $https_proxy`

### 复现步骤

1.下载软件包[Clash.for.Windows-0.20.17-arm64-linux.tar.gz](https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.20.17/Clash.for.Windows-0.20.17-arm64-linux.tar.gz)
2.按照问题描述步骤来操作
3.把log文件上传到百度网盘 [clash_logs.tar.gz]
(https://pan.baidu.com/s/1-Edmxxbp8IgdoY_hRBmYBg?pwd=23xk )

### 日志文件
<details><summary>logs</summary><p>

```
could not open /proc/net/psched: open /proc/net/psched: no such file or directory
11:12:32 INF [API] listening addr=127.0.0.1:42765
11:12:32 INF [Inbound] Mixed(http+socks) listening addr=[::]:7890
11:12:33 INF [Config] initial compatible provider name=故障转移
11:12:33 INF [Config] initial compatible provider name=自动选择
11:12:33 INF [Config] initial compatible provider name=BH专线版
11:14:00 INF [Inbound] Mixed(http+socks) listening addr=127.0.0.1:7890
```
</p></details>

**Comment by QS0x01** [comment]
没有日志文件，也没有配置文件，不如问问神奇的小海螺。

**Comment by STRIVESS** [comment]
> 没有日志文件，也没有配置文件，不如问问神奇的小海螺。

您好！我把日志上传到百度网盘，你可以看看，谢谢

**Comment by QS0x01** [comment]
1. github 可以直接上传文件。
2. 以下结果来自 chatgpt.

![image](https://user-images.githubusercontent.com/119924985/231136454-662121cb-05ec-4b9b-9006-b249f836b550.png)

**Comment by STRIVESS** [comment]
> 1. github 可以直接上传文件。
> 2. 以下结果来自 chatgpt.
> 
> ![image](https://user-images.githubusercontent.com/119924985/231136454-662121cb-05ec-4b9b-9006-b249f836b550.png)

谢谢大佬，我按照你的方法设置，重启arm板子，可以上外网了。其实很简单的一个操作，但是rk3399 pro的network没有那个network proxy的设置选项，折腾了一个上午；我之前去chatgpt搜了是这个答案，我也在怀疑是不是操作有问题
![20230411-194709](https://user-images.githubusercontent.com/40514204/231153629-57caca32-ed0b-4862-8bcf-25e5aa2a2c7b.jpg)
