### ISSUE TITLE
[Bug]: clash for windows客户端里面的profiles不能导入clash订阅的url

### ISSUE THREAD

**Issue by FanShuixing** [Fndroid/clash_for_windows_pkg#4299]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.20

### 操作系统

Windows x64

### 系统版本

64

### 问题描述

![image](https://user-images.githubusercontent.com/35692924/230877669-3cb9a0fa-fde7-4f39-878f-2f5f381babf9.png)
当我把第一个url复制到clash for windows里面的Profiles中时，下载成功，但是Proxies不能加载出Rule，访问google失败。

当我把第二个url复制到clash for windows里面的Profiles中时，下载失败，显示如图下所示
![image](https://user-images.githubusercontent.com/35692924/230878027-466c15e3-2834-4d53-b36d-02fce735fc6f.png)

### 复现步骤

1.https://github.com/Fndroid/clash_for_windows_pkg/releases这个页面中下载[Clash.for.Windows-0.20.20-win.7z](https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.20.20/Clash.for.Windows-0.20.20-win.7z)

2.General中打开System Proxy

3.Profiles中导入下图中的链接
![image](https://user-images.githubusercontent.com/35692924/230878344-cf92cdcc-0aaa-4601-831f-08f11201ca20.png)

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by FanShuixing** [comment]
/

**Comment by FanShuixing** [comment]
/

**Comment by yi-Xu-0100** [comment]
- #4055
