### ISSUE TITLE
Logs功能建议

### ISSUE THREAD

**Issue by Hugh08** [Fndroid/clash_for_windows_pkg#430]
感谢F大提供的优秀软件。
感觉在日常使用中，日志状态栏倒序显示会更贴切使用者想获取的最新信息。如果可以，建议在日志状态栏中加个选项（正序or倒序）。
望采纳，感谢。

**Comment by negnegneg** [comment]
对了，反馈一下，
0.8.11的版本Logs似乎有BUG，状态栏无论如何都无法显示动态日志，目前回退到0.8.9使用中。

**Comment by Maasea** [comment]
> 对了，反馈一下，
> 0.8.11的版本Logs似乎有BUG，状态栏无论如何都无法显示动态日志，目前回退到0.8.9使用中。

同排序附议，如果能在log里增加筛选就更好了。

**Comment by Fndroid** [comment]
最新版已经能自动滚动
