### ISSUE TITLE
[Feature Request]: 开机自启动，只启动clash核心，不启动仪表盘

### ISSUE THREAD

**Issue by DarknessLeaf** [Fndroid/clash_for_windows_pkg#4304]
### 功能描述

开机自启动，只启动用于上网的clash核心，不启动仪表盘，类似于跳过启动仪表盘主程序，直接进入轻量模式的状态，选择节点也可以通过自带的网页端控制面板进行。仪表盘开机启动速度较慢，会有较长一段时间无法上网，而且占用内存较大。而轻量模式依然需要启动仪表盘，只是在启动仪表盘之后再将其主动关闭。
因此希望增加这个功能，非常感谢。

**Comment by Fndroid** [comment]
原理上无法实现

**Comment by DarknessLeaf** [comment]
好吧，谢啦
