### ISSUE TITLE
新手小白请教：在电脑某分区目录中出现很多WebSeal文档，与CFW有关系吗？谢谢！

### ISSUE THREAD

**Issue by eboxatGH** [Fndroid/clash_for_windows_pkg#4306]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.20

### 操作系统

Windows x64

### 系统版本

WIN10

### 问题描述

最近偶然发现在电脑D分区中，出现多个文件名如 [WebSeal_972_20230410140028] 的文本文档（.log）。
本人新手小白，对这个不熟悉。
请教大佬、高手，
这类文档的出现、生成与使用CFW有关联吗？
感谢！

### 复现步骤

这个真的不知道。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
给一个文件看看，文件名看起来无关，大概率无关。

**Comment by yi-Xu-0100** [comment]
https://bbs.pcbeta.com/viewthread-1963774-1-1.html

**Comment by eboxatGH** [comment]
多谢大佬指教！
过了2周了，还在帮着留意这个问题，感谢！
的确如此，问题 与 CLW 无关。
而与CLW无关，还帮着找到了答案。
更加感谢！谢谢！
