### ISSUE TITLE
[Bug]: 0.20.20版本ubuntu下托盘图标显示异常

### ISSUE THREAD

**Issue by ACE-830** [Fndroid/clash_for_windows_pkg#4310]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.20

### 操作系统

Linux

### 系统版本

ubuntu 18.04

### 问题描述

ubuntu下托盘图标显示异常，只在最新版本0.20.20出现，之前版本没有问题。
异常（最新版本0.20.20）：
![2023-04-12 13-50-40屏幕截图](https://user-images.githubusercontent.com/59821932/231363216-03da8b01-5ebb-494d-acd8-2b27980b29d6.png)
正常（0.20.19及之前版本）：
![2023-04-12 14-15-55屏幕截图](https://user-images.githubusercontent.com/59821932/231367714-ee8575bb-c01d-4cfb-92e7-a85591f7190b.png)

### 复现步骤

在ubuntu中打开cfw 0.20.20

### 日志文件

<details><summary>logs</summary><p>

```
time="Wed Apr 12 2023 14:11:09 GMT+0800 (中国标准时间)" level=info msg="app start with mode: production"
time="Wed Apr 12 2023 14:11:09 GMT+0800 (中国标准时间)" level=info msg="load data from general config.yaml"
time="Wed Apr 12 2023 14:11:09 GMT+0800 (中国标准时间)" level=info msg="mixed-port changed"
time="Wed Apr 12 2023 14:11:09 GMT+0800 (中国标准时间)" level=info msg="external controller port changed"
time="Wed Apr 12 2023 14:11:09 GMT+0800 (中国标准时间)" level=info msg="clash axios client changed"
time="Wed Apr 12 2023 14:11:09 GMT+0800 (中国标准时间)" level=info msg="external controller port changed"
time="Wed Apr 12 2023 14:11:09 GMT+0800 (中国标准时间)" level=info msg="clash axios client changed"
time="Wed Apr 12 2023 14:11:09 GMT+0800 (中国标准时间)" level=info msg="restarting clash core..."
time="Wed Apr 12 2023 14:11:09 GMT+0800 (中国标准时间)" level=info msg="check for app update, current: 0.20.20"
time="Wed Apr 12 2023 14:11:09 GMT+0800 (中国标准时间)" level=info msg="clash status change to [connected]"
time="Wed Apr 12 2023 14:11:09 GMT+0800 (中国标准时间)" level=info msg="restore at index: 0"
```

</p></details>

**Comment by Horace-wang** [comment]
fedora也是一样的情况，我估计是gnome的托盘插件程序和新版本的clash for windows不兼容导致的

**Comment by Fndroid** [comment]
大概是Electron有调整，20.21会把图标分辨率降低一点看看正不正常

**Comment by ACE-830** [comment]
0.20.21版本可以正常显示，谢谢！
图标缩小了点，不过不影响使用。
![2023-04-14 10-39-41屏幕截图](https://user-images.githubusercontent.com/59821932/231928569-4dbad9da-bbbe-4289-9926-eecc8ce89b11.png)
