### ISSUE TITLE
已过期。。。

### ISSUE THREAD

**Issue by zhouxinghong** [Fndroid/clash_for_windows_pkg#4311]
### 功能描述

11

**Comment by zhouxinghong** [comment]
![image](https://user-images.githubusercontent.com/54253524/231733754-f2590ebe-a910-4e94-a37f-c755d06c0671.png)

**Comment by Fndroid** [comment]
<img width="850" alt="image" src="https://user-images.githubusercontent.com/16091562/231918695-e1dc6d00-402e-4fbc-9bb3-f1a71aa0a01e.png">

**Comment by zhouxinghong** [comment]
But it would be more convenient to add another trigger button.

**Comment by zhouxinghong** [comment]
![image](https://user-images.githubusercontent.com/54253524/231928920-becc4393-ecc9-4da1-88ce-71319b664800.png)

Even after I set it up the way you did, every time I hit the test button, all the node speed delay sorts get messed up again, which is very frustrating.
So the best way is: it will be more convenient and friendly to add another trigger button to perform sorting operations.

**Comment by zhouxinghong** [comment]
It is recommended to add another button here to sort in ascending or descending order.
![image](https://user-images.githubusercontent.com/54253524/231382289-be46e0d0-68ad-42c5-b8c1-cc29be3a8744.png)

**Comment by zhouxinghong** [comment]
应该安装延迟时间从小大大排序，例如排序格式如下：
0
1
2
3
4
5
6
7
8
9
10
....
目前的排序格式是：
0
1
8
3
6
2
0
5
8
9
....
所以延迟排序非常乱。。。。这才是需要增加一个按钮来手动触发升序或降序的意义。
