### ISSUE TITLE
[Bug]: clash for windows无法下载

### ISSUE THREAD

**Issue by huixin-hub** [Fndroid/clash_for_windows_pkg#4313]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.19

### 操作系统

Windows x64

### 系统版本

windows11

### 问题描述

<img width="745" alt="image" src="https://user-images.githubusercontent.com/77789025/231666091-24c5c16b-9167-4f8a-aa2e-dab5df60feb3.png">

### 复现步骤

试了很多次，进度条下载一点，就显示无法下载—网络问题，再点击就变成图片里的需要授权，试着连接手机热点，无线路由器重启，都无法解决，都是一样的提示，麻烦大佬们帮我看一下

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Sakuzy0** [comment]
右键复制链接用idm 迅雷下，或者换个浏览器？
