### ISSUE TITLE
[Bug]: 我都关了clash，程序还在，端口还在

### ISSUE THREAD

**Issue by YangQing1989** [Fndroid/clash_for_windows_pkg#4314]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.20

### 操作系统

Windows x64

### 系统版本

windows10

### 问题描述

我都关了，程序还在，端口还在

### 复现步骤

1、底部工具栏，关闭clash客户端
2、检查进程（tasklist）和端口(netstat)，依然都在

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
点Settings里的Quit或者右键任务栏菜单里的Quit

**Comment by xk-mt** [comment]
> 点Settings里的Quit或者右键任务栏菜单里的Quit

大哥看你解决了好多问题，方便解决一下我的吗，我的任务栏没有图标
