### ISSUE TITLE
[Bug]: 在多个profile的情况下，为其中一个profile的某个组选择节点，会导致另一个profile对应的组忘记选择过的节点（即重置为节点列表的第一个节点）

### ISSUE THREAD

**Issue by TXH1997** [Fndroid/clash_for_windows_pkg#4317]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.20

### 操作系统

Windows x64

### 系统版本

22H2

### 问题描述

在多个profile的情况下，为其中一个profile的某个组选择节点，会导致另一个profile对应的组忘记选择过的节点（即重置为节点列表的第一个节点）

### 复现步骤

1. 存在多个profile
2. 在profiles界面选择其中一个profile
3. 切换到proxies界面，选择Rule模式，选择一个组，并为该组选择一个节点（该节点不能是节点列表的第一个节点）
4. 在profiles界面选择另一个profile
5. 切换到proxies界面，选择Rule模式，选择和步骤2同名的组，并为该组选择一个节点（该节点不能是节点列表的第一个节点）
6. 在profiles界面选择步骤2中选择的profile，切换到proxies界面，选择Rule模式，会发现步骤3中为该组选择的节点被重置为节点列表的第一个节点

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>
21:40:28 INF [API] listening addr=127.0.0.1:5415
21:40:28 INF [Inbound] Mixed(http+socks) listening addr=127.0.0.1:54321
21:40:28 DBG [TCP] accept connection lAddr=127.0.0.1:4485 rAddr=raw.githubusercontent.com:443 inbound=HTTP Connect
21:40:28 DBG [TCP] accept connection lAddr=127.0.0.1:4487 rAddr=api.github.com:443 inbound=HTTP Connect
21:40:29 INF [TCP] connected, doesn't match any rule lAddr=127.0.0.1:4487 rAddr=api.github.com:443 proxy=DIRECT
21:40:29 INF [Config] initial compatible provider name=🎬 HBO MAX
21:40:29 INF [Config] initial compatible provider name=🇸🇬 狮城节点
21:40:29 INF [Config] initial compatible provider name=🇯🇵 日本节点
21:40:29 INF [Config] initial compatible provider name=🌏 国外网站
21:40:29 INF [Config] initial compatible provider name=🇰🇷 韩国节点
21:40:29 INF [Config] initial compatible provider name=🧩 微软服务
21:40:29 INF [Config] initial compatible provider name=📲 聊天软件
21:40:29 INF [Config] initial compatible provider name=🎬 国外媒体
21:40:29 INF [Config] initial compatible provider name=♻️ 专线节点
21:40:29 INF [Config] initial compatible provider name=🇭🇰 香港节点
21:40:29 INF [Config] initial compatible provider name=🎬 哔哩哔哩
21:40:29 INF [Config] initial compatible provider name=🇨🇳 台湾节点
21:40:29 INF [Config] initial compatible provider name=🎵 TikTok
21:40:29 INF [Config] initial compatible provider name=🎬 NETFLIX
21:40:29 INF [Config] initial compatible provider name=🎬 YouTube
21:40:29 INF [Config] initial compatible provider name=🎬 HBO GO
21:40:29 INF [Config] initial compatible provider name=🐟 漏网之鱼
21:40:29 INF [Config] initial compatible provider name=🎬 EMBY
21:40:29 INF [Config] initial compatible provider name=🎬 港台媒体
21:40:29 INF [Config] initial compatible provider name=🎬 巴哈姆特
21:40:29 INF [Config] initial compatible provider name=♻️ 手动切换
21:40:29 INF [Config] initial compatible provider name=🎬 Prime
21:40:29 INF [Config] initial compatible provider name=🎬 日韩媒体
21:40:29 INF [Config] initial compatible provider name=🎬 DisneyPlus
21:40:29 INF [Config] initial compatible provider name=🍎 苹果服务
21:40:29 INF [Config] initial compatible provider name=🇧🇹 BT&PT
21:40:29 INF [Config] initial compatible provider name=🇺🇲 美国节点
21:40:29 INF [Config] initial compatible provider name=🎬 爱奇艺
21:40:29 INF [Config] initial compatible provider name=🎵 Spotify
21:40:29 INF [Config] initial compatible provider name=🌍 其他地区
21:40:29 INF [Config] initial compatible provider name=🌏 国内网站
21:40:29 INF [Config] initial compatible provider name=🎮 游戏平台
21:40:31 DBG [TCP] accept connection lAddr=127.0.0.1:4490 rAddr=alive.github.com:443 inbound=HTTP Connect
21:40:31 DBG [Matcher] resolve success host=alive.github.com ip=140.82.112.25
21:40:31 INF [TCP] connected lAddr=127.0.0.1:4490 rAddr=alive.github.com:443 mode=rule rule=DomainKeyword(github) proxy=🌏 国外网站[AA-中继-JP-Sakura.02[海外直连] - 18348]
21:40:33 WRN [TCP] dial failed error=dial tcp4 185.199.110.133:443: i/o timeout proxy=DIRECT lAddr=127.0.0.1:4485 rAddr=raw.githubusercontent.com:443
21:40:33 DBG [TCP] accept connection lAddr=127.0.0.1:4493 rAddr=raw.githubusercontent.com:443 inbound=HTTP Connect
21:40:33 DBG [Matcher] resolve success host=raw.githubusercontent.com ip=185.199.110.133
21:40:33 INF [TCP] connected lAddr=127.0.0.1:4493 rAddr=raw.githubusercontent.com:443 mode=rule rule=DomainKeyword(github) proxy=🌏 国外网站[AA-中继-JP-Sakura.02[海外直连] - 18348]
21:40:38 INF [Config] initial compatible provider name=🎵 Spotify
21:40:38 INF [Config] initial compatible provider name=🐟 漏网之鱼
21:40:38 INF [Config] initial compatible provider name=🇯🇵 日本节点
21:40:38 INF [Config] initial compatible provider name=🎬 巴哈姆特
21:40:38 INF [Config] initial compatible provider name=🎬 YouTube
21:40:38 INF [Config] initial compatible provider name=🎬 EMBY
21:40:38 INF [Config] initial compatible provider name=🎬 日韩媒体
21:40:38 INF [Config] initial compatible provider name=🎵 TikTok
21:40:38 INF [Config] initial compatible provider name=🍎 苹果服务
21:40:38 INF [Config] initial compatible provider name=🎬 HBO MAX
21:40:38 INF [Config] initial compatible provider name=🎬 国外媒体
21:40:38 INF [Config] initial compatible provider name=🎬 爱奇艺
21:40:38 INF [Config] initial compatible provider name=🇧🇹 BT&PT
21:40:38 INF [Config] initial compatible provider name=🎮 游戏平台
21:40:38 INF [Config] initial compatible provider name=🌍 其他地区
21:40:38 INF [Config] initial compatible provider name=🇸🇬 狮城节点
21:40:38 INF [Config] initial compatible provider name=🇺🇲 美国节点
21:40:38 INF [Config] initial compatible provider name=♻️ 手动切换
21:40:38 INF [Config] initial compatible provider name=🇨🇳 台湾节点
21:40:38 INF [Config] initial compatible provider name=🎬 哔哩哔哩
21:40:38 INF [Config] initial compatible provider name=🌏 国外网站
21:40:38 INF [Config] initial compatible provider name=♻️ 专线节点
21:40:38 INF [Config] initial compatible provider name=🇰🇷 韩国节点
21:40:38 INF [Config] initial compatible provider name=🎬 港台媒体
21:40:38 INF [Config] initial compatible provider name=🎬 HBO GO
21:40:38 INF [Config] initial compatible provider name=🎬 NETFLIX
21:40:38 INF [Config] initial compatible provider name=🎬 DisneyPlus
21:40:38 INF [Config] initial compatible provider name=📲 聊天软件
21:40:38 INF [Config] initial compatible provider name=🎬 Prime
21:40:38 INF [Config] initial compatible provider name=🌏 国内网站
21:40:38 INF [Config] initial compatible provider name=🇭🇰 香港节点
21:40:38 INF [Config] initial compatible provider name=🧩 微软服务
21:40:50 DBG [TCP] accept connection lAddr=127.0.0.1:4496 rAddr=client.wns.windows.com:443 inbound=HTTP Connect
21:40:50 DBG [Matcher] resolve success host=client.wns.windows.com ip=20.198.162.78
21:40:50 INF [TCP] connected lAddr=127.0.0.1:4496 rAddr=client.wns.windows.com:443 mode=rule rule=DomainSuffix(windows.com) proxy=🧩 微软服务[AA-V2ray-SG-Linode[海外直连]]
21:40:56 INF [Config] initial compatible provider name=🌏 国内网站
21:40:56 INF [Config] initial compatible provider name=🎬 哔哩哔哩
21:40:56 INF [Config] initial compatible provider name=🎬 巴哈姆特
21:40:56 INF [Config] initial compatible provider name=🇯🇵 日本节点
21:40:56 INF [Config] initial compatible provider name=🎮 游戏平台
21:40:56 INF [Config] initial compatible provider name=🎬 Prime
21:40:56 INF [Config] initial compatible provider name=🎬 日韩媒体
21:40:56 INF [Config] initial compatible provider name=🎬 NETFLIX
21:40:56 INF [Config] initial compatible provider name=🌍 其他地区
21:40:56 INF [Config] initial compatible provider name=🇰🇷 韩国节点
21:40:56 INF [Config] initial compatible provider name=🎬 爱奇艺
21:40:56 INF [Config] initial compatible provider name=🌏 国外网站
21:40:56 INF [Config] initial compatible provider name=🎵 TikTok
21:40:56 INF [Config] initial compatible provider name=🎬 港台媒体
21:40:56 INF [Config] initial compatible provider name=🎵 Spotify
21:40:56 INF [Config] initial compatible provider name=🎬 EMBY
21:40:56 INF [Config] initial compatible provider name=♻️ 手动切换
21:40:56 INF [Config] initial compatible provider name=🇨🇳 台湾节点
21:40:56 INF [Config] initial compatible provider name=📲 聊天软件
21:40:56 INF [Config] initial compatible provider name=🎬 HBO MAX
21:40:56 INF [Config] initial compatible provider name=🇸🇬 狮城节点
21:40:56 INF [Config] initial compatible provider name=🇺🇲 美国节点
21:40:56 INF [Config] initial compatible provider name=🇧🇹 BT&PT
21:40:56 INF [Config] initial compatible provider name=🎬 国外媒体
21:40:56 INF [Config] initial compatible provider name=🧩 微软服务
21:40:56 INF [Config] initial compatible provider name=🎬 YouTube
21:40:56 INF [Config] initial compatible provider name=🇭🇰 香港节点
21:40:56 INF [Config] initial compatible provider name=🍎 苹果服务
21:40:56 INF [Config] initial compatible provider name=🐟 漏网之鱼
21:40:56 INF [Config] initial compatible provider name=🎬 DisneyPlus
21:40:56 INF [Config] initial compatible provider name=♻️ 专线节点
21:40:56 INF [Config] initial compatible provider name=🎬 HBO GO
21:41:47 DBG [TCP] accept connection lAddr=127.0.0.1:4507 rAddr=alive.github.com:443 inbound=HTTP Connect
21:41:47 DBG [Matcher] resolve success host=alive.github.com ip=140.82.112.25
21:41:47 INF [TCP] connected lAddr=127.0.0.1:4507 rAddr=alive.github.com:443 mode=rule rule=DomainKeyword(github) proxy=🌏 国外网站[AA-中继-JP-Sakura.02[海外直连] - 18348]
21:42:13 DBG [TCP] accept connection lAddr=127.0.0.1:6881 rAddr=ipv6.msftconnecttest.com:80 inbound=HTTP
21:42:13 DBG [TCP] accept connection lAddr=127.0.0.1:6882 rAddr=www.msftconnecttest.com:80 inbound=HTTP
21:42:13 DBG [Matcher] resolve failed error=lookup ipv6.msftconnecttest.com: no such host host=ipv6.msftconnecttest.com
21:42:13 DBG [Matcher] find process failed error=Access is denied. addr=ipv6.msftconnecttest.com
21:42:13 DBG [Matcher] resolve success host=www.msftconnecttest.com ip=23.72.90.86
21:42:13 DBG [Matcher] find process failed error=Access is denied. addr=www.msftconnecttest.com
21:42:13 INF [TCP] connected lAddr=127.0.0.1:6882 rAddr=www.msftconnecttest.com:80 mode=rule rule=Match() proxy=🐟 漏网之鱼[AA-中继-JP-Sakura.02[海外直连] - 18348]
21:42:13 INF [TCP] connected lAddr=127.0.0.1:6881 rAddr=ipv6.msftconnecttest.com:80 mode=rule rule=Match() proxy=🐟 漏网之鱼[AA-中继-JP-Sakura.02[海外直连] - 18348]
21:42:48 DBG [TCP] accept connection lAddr=127.0.0.1:6887 rAddr=ipv6.msftconnecttest.com:80 inbound=HTTP
21:42:48 DBG [Matcher] resolve failed error=lookup ipv6.msftconnecttest.com: no such host host=ipv6.msftconnecttest.com
21:42:48 DBG [Matcher] find process failed error=Access is denied. addr=ipv6.msftconnecttest.com
21:42:48 INF [TCP] connected lAddr=127.0.0.1:6887 rAddr=ipv6.msftconnecttest.com:80 mode=rule rule=Match() proxy=🐟 漏网之鱼[AA-中继-JP-Sakura.02[海外直连] - 18348]
21:43:17 DBG [TCP] accept connection lAddr=127.0.0.1:6893 rAddr=update.googleapis.com:443 inbound=HTTP Connect
21:43:17 DBG [Matcher] resolve success host=update.googleapis.com ip=58.254.137.162
21:43:17 INF [TCP] connected lAddr=127.0.0.1:6893 rAddr=update.googleapis.com:443 mode=rule rule=DomainKeyword(google) proxy=🌏 国外网站[AA-中继-JP-Sakura.02[海外直连] - 18348]
21:43:49 DBG [TCP] accept connection lAddr=127.0.0.1:6899 rAddr=edge.microsoft.com:443 inbound=HTTP Connect
21:43:49 DBG [Matcher] resolve success host=edge.microsoft.com ip=204.79.197.239
21:43:49 INF [TCP] connected lAddr=127.0.0.1:6899 rAddr=edge.microsoft.com:443 mode=rule rule=DomainKeyword(microsoft) proxy=🧩 微软服务[AA-中继-JP-Sakura.02[海外直连] - 18348]
21:43:50 DBG [TCP] accept connection lAddr=127.0.0.1:6901 rAddr=edge.microsoft.com:443 inbound=HTTP Connect
21:43:50 DBG [Matcher] resolve success host=edge.microsoft.com ip=13.107.21.239
21:43:50 INF [TCP] connected lAddr=127.0.0.1:6901 rAddr=edge.microsoft.com:443 mode=rule rule=DomainKeyword(microsoft) proxy=🧩 微软服务[AA-中继-JP-Sakura.02[海外直连] - 18348]
21:43:55 DBG [TCP] accept connection lAddr=127.0.0.1:6903 rAddr=github.com:443 inbound=HTTP Connect
21:43:55 DBG [Matcher] resolve success host=github.com ip=20.205.243.166
21:43:55 INF [TCP] connected lAddr=127.0.0.1:6903 rAddr=github.com:443 mode=rule rule=DomainKeyword(github) proxy=🌏 国外网站[AA-中继-JP-Sakura.02[海外直连] - 18348]
21:43:55 DBG [TCP] accept connection lAddr=127.0.0.1:6905 rAddr=github.com:443 inbound=HTTP Connect
21:43:55 DBG [Matcher] resolve success host=github.com ip=20.205.243.166
21:43:55 INF [TCP] connected lAddr=127.0.0.1:6905 rAddr=github.com:443 mode=rule rule=DomainKeyword(github) proxy=🌏 国外网站[AA-中继-JP-Sakura.02[海外直连] - 18348]
21:43:56 DBG [TCP] accept connection lAddr=127.0.0.1:6907 rAddr=objects-origin.githubusercontent.com:443 inbound=HTTP Connect
21:43:56 DBG [Matcher] resolve success host=objects-origin.githubusercontent.com ip=140.82.114.21
21:43:56 INF [TCP] connected lAddr=127.0.0.1:6907 rAddr=objects-origin.githubusercontent.com:443 mode=rule rule=DomainKeyword(github) proxy=🌏 国外网站[AA-中继-JP-Sakura.02[海外直连] - 18348]
21:43:56 DBG [TCP] accept connection lAddr=127.0.0.1:6909 rAddr=objects-origin.githubusercontent.com:443 inbound=HTTP Connect
21:43:56 DBG [Matcher] resolve success host=objects-origin.githubusercontent.com ip=140.82.114.21
21:43:56 INF [TCP] connected lAddr=127.0.0.1:6909 rAddr=objects-origin.githubusercontent.com:443 mode=rule rule=DomainKeyword(github) proxy=🌏 国外网站[AA-中继-JP-Sakura.02[海外直连] - 18348]
21:44:11 DBG [TCP] accept connection lAddr=127.0.0.1:6913 rAddr=objects-origin.githubusercontent.com:443 inbound=HTTP Connect
21:44:11 DBG [Matcher] resolve success host=objects-origin.githubusercontent.com ip=140.82.114.21
21:44:11 INF [TCP] connected lAddr=127.0.0.1:6913 rAddr=objects-origin.githubusercontent.com:443 mode=rule rule=DomainKeyword(github) proxy=🌏 国外网站[AA-中继-JP-Sakura.02[海外直连] - 18348]
21:44:11 DBG [TCP] accept connection lAddr=127.0.0.1:6915 rAddr=objects-origin.githubusercontent.com:443 inbound=HTTP Connect
21:44:11 DBG [Matcher] resolve success host=objects-origin.githubusercontent.com ip=140.82.114.21
21:44:12 INF [TCP] connected lAddr=127.0.0.1:6915 rAddr=objects-origin.githubusercontent.com:443 mode=rule rule=DomainKeyword(github) proxy=🌏 国外网站[AA-中继-JP-Sakura.02[海外直连] - 18348]
21:44:27 DBG [TCP] accept connection lAddr=127.0.0.1:6921 rAddr=objects-origin.githubusercontent.com:443 inbound=HTTP Connect
21:44:27 DBG [Matcher] resolve success host=objects-origin.githubusercontent.com ip=140.82.114.21
21:44:27 INF [TCP] connected lAddr=127.0.0.1:6921 rAddr=objects-origin.githubusercontent.com:443 mode=rule rule=DomainKeyword(github) proxy=🌏 国外网站[AA-中继-JP-Sakura.02[海外直连] - 18348]

**Comment by Fndroid** [comment]
最新版恢复原来的逻辑了
