### ISSUE TITLE
[Bug]: 每次更换节点后需要重启浏览器才能生效

### ISSUE THREAD

**Issue by Mingtha** [Fndroid/clash_for_windows_pkg#4325]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.20

### 操作系统

Windows x64

### 系统版本

win11 22H2 专业工作站版

### 问题描述

每次使用托盘或者更换订阅后必须重启浏览器才能生效，刷新页面不会生效，这样每次操作会比较麻烦，希望能够更换节点后能直接生效

### 复现步骤

浏览器打开任一查询ip的网站，然后更换节点，无论怎么刷新ip都不会更改，必须重启浏览器

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by QS0x01** [comment]
clash connection filter close

**Comment by Mingtha** [comment]
@QS0x01 谢谢！
