### ISSUE TITLE
最新版本按照文档操作开启便携模式报错

### ISSUE THREAD

**Issue by hypogaea** [Fndroid/clash_for_windows_pkg#433]
用的是Windows 10 1903，按照文档里的操作

> 进入安装目录/resources/static/files/目录中进行如下操作：
新建config.yml（文件可以为空，但一定要创建）
重新启动Clash for Windows
此时文件夹目录中还有其他文件及文件夹，请勿对其修改

然后General就提示：oops, got an error here

**Comment by Fndroid** [comment]
感谢反馈，将在下个版本修复

**Comment by hypogaea** [comment]
收到，谢谢

**Comment by Fndroid** [comment]
fixed in this release: https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.0

**Comment by hypogaea** [comment]
问题解决了，不过新问题又来了
![image](https://user-images.githubusercontent.com/14803915/75551236-b2bf3800-5a6e-11ea-8d42-8f368e8b072d.png)
进入安装目录/resources/static/files/目录中新建config.yml之后，在如图所示路径中依然会生成.config文件夹，不太了解这个文件夹对便携模式有什么影响

**Comment by dcrzty** [comment]
support yaml instead of yml
看提示是改成config.yaml了，不再使用config.yml

**Comment by hypogaea** [comment]
> support yaml instead of yml
> 看提示是改成config.yaml了，不再使用config.yml

非常感谢，确实是这样的，这样一来才是真正开启便携模式了，建议开发者也应该更新一下文档了：https://docs.cfw.lbyczf.com/contents/7z.html

**Comment by hsdhlxy** [comment]
> 用的是Windows 10 1903，按照文档里的操作
> 
> > 进入安装目录/ resources / static / files /目录中进行如下操作：
> > 新建config.yml（文件可以为空，但一定要创建）
> > 重新启动Windows的冲突Windows
> > 文件夹目录中还有其他文件及文件夹，请勿进行修改
> 
> 然后一般就提示：糟糕，这里出现错误

我也是同样的错误，我下载打开小猫咪，就提示这个错误，我该怎么解决
