### ISSUE TITLE
[Bug]: [复现] proxy-providers initial error (no proxies field)

### ISSUE THREAD

**Issue by QS0x01** [Fndroid/clash_for_windows_pkg#4338]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.21

### 操作系统

Windows x64

### 系统版本

Win11 22H2 x64

### 问题描述

历史 Issue 里翻到的，遇到相同问题。
https://github.com/Fndroid/clash_for_windows_pkg/issues/3931

使用 HTTP 模式初始化 proxy-providers 失败，提示缺少 proxies 字段。
![image](https://user-images.githubusercontent.com/119924985/232486993-288827da-7907-45d7-bbe6-cff0f62e3d09.png)
但是手动下载 url 指向的配置文件，打开第一行就是 "proxies:"
![image](https://user-images.githubusercontent.com/119924985/232489505-df0d15be-a492-484f-97d7-4bbe6c5e3a24.png)

### 复现步骤

无法稳定复现，因为之前成功初始化过其它配置文件，但这个配置文件始终失败。
![image](https://user-images.githubusercontent.com/119924985/232490078-d3f668b3-56f6-4b8b-8aca-874a2876bb55.png)

临时解决方案：
copy url md5，然后手动下载配置文件，重命名为 md5.yaml 放入目标路径。
可以看到，手动下载的配置文件被成功加载，但是点击更新依然提示缺少 proxy 字段。
![image](https://user-images.githubusercontent.com/119924985/232491236-27103601-1907-4b3e-8c1d-87921408ce1b.png)

### 日志文件

<details><summary>logs</summary><p>

```
20:28:22 INF [API] listening addr=127.0.0.1:65259
20:28:22 INF [Inbound] Mixed(http+socks) listening addr=[::]:27890
20:28:22 DBG [TCP] accept connection lAddr=127.0.0.1:65265 rAddr=raw.githubusercontent.com:443 inbound=HTTP Connect
20:28:22 WRN [TCP] dial failed error=lookup raw.githubusercontent.com: getaddrinfow: The requested name is valid, but no data of the requested type was found. proxy=DIRECT lAddr=127.0.0.1:65265 rAddr=raw.githubusercontent.com:443
20:28:22 DBG [TCP] accept connection lAddr=127.0.0.1:65266 rAddr=raw.githubusercontent.com:443 inbound=HTTP Connect
20:28:22 WRN [TCP] dial failed error=lookup raw.githubusercontent.com: getaddrinfow: The requested name is valid, but no data of the requested type was found. proxy=DIRECT lAddr=127.0.0.1:65266 rAddr=raw.githubusercontent.com:443
20:28:22 DBG [TCP] accept connection lAddr=127.0.0.1:65268 rAddr=api.github.com:443 inbound=HTTP Connect
20:28:22 INF [Config] start initial provider name=HK
20:28:22 INF [Config] start initial provider name=TW
20:28:22 INF [Config] start initial provider name=JP
20:28:22 INF [Config] start initial provider name=Test
20:28:22 INF [TCP] connected, doesn't match any rule lAddr=127.0.0.1:65268 rAddr=api.github.com:443 proxy=DIRECT
20:28:32 INF [Config] start initial provider name=HK
20:28:32 INF [Config] start initial provider name=TW
20:28:32 INF [Config] start initial provider name=JP
20:28:32 INF [Config] start initial provider name=Test
20:28:44 DBG [TCP] accept connection lAddr=127.0.0.1:65462 rAddr=sync-v2.brave.com:443 inbound=HTTP Connect
20:28:44 INF [TCP] connected, doesn't match any rule lAddr=127.0.0.1:65462 rAddr=sync-v2.brave.com:443 proxy=DIRECT
20:28:45 DBG [TCP] accept connection lAddr=192.168.1.70:37882 rAddr=www.googleapis.com:443 inbound=HTTP Connect
20:28:47 DBG [TCP] accept connection lAddr=127.0.0.1:65486 rAddr=licensing.mp.microsoft.com:443 inbound=HTTP Connect
20:28:47 INF [TCP] connected, doesn't match any rule lAddr=127.0.0.1:65486 rAddr=licensing.mp.microsoft.com:443 proxy=DIRECT
20:28:49 DBG [TCP] accept connection lAddr=192.168.1.70:37884 rAddr=www.googleapis.com:443 inbound=HTTP Connect
20:28:50 WRN [TCP] dial failed error=dial tcp4 142.251.42.234:443: i/o timeout proxy=DIRECT lAddr=192.168.1.70:37882 rAddr=www.googleapis.com:443
20:28:54 WRN [TCP] dial failed error=dial tcp4 172.217.163.42:443: i/o timeout proxy=DIRECT lAddr=192.168.1.70:37884 rAddr=www.googleapis.com:443
```

</p></details>

**Comment by yi-Xu-0100** [comment]
path 写错了，要用md5文件名

**Comment by QS0x01** [comment]
> path 写错了，要用md5文件名

使用 md5 文件名偷渡确实可以成功加载，但即使把 path 改成 md5，依旧是提示缺少 proxies 字段。
我个人是这么推测的：能提示缺少字段，说明文件路径这关是成功过了，只是读取下载的配置文件出错了/

**Comment by yi-Xu-0100** [comment]
@QS0x01 本地看看下载的md5文件内容。

**Comment by QS0x01** [comment]
> @QS0x01 本地看看下载的md5文件内容。

clash 下载的配置文件应该是在缓存内吧，只有通过检查才会替换到 .config/clash 的配置文件目录，如何看下载的文件呢？

**Comment by yi-Xu-0100** [comment]
不清楚了，或许你像你提到的类似issue那样，先直接CFW加载provider试下呢？

**Comment by QS0x01** [comment]
> 不清楚了，或许你像你提到的类似issue那样，先直接CFW用profile下载试下呢？

哈哈，既然提到了历史的 #3931，还开了这个 issue，那必然是没用啊（悲伤

不过今天通过一种类似的解法成功了。

clash profile edit internally -> locate to the provider url -> ctrl click follow link -> refresh provider
