### ISSUE TITLE
最近clash的Windows版本占用内存过高[Bug]: 

### ISSUE THREAD

**Issue by UyCode** [Fndroid/clash_for_windows_pkg#4342]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.21

### 操作系统

Windows x64

### 系统版本

win11 pro

### 问题描述

![image](https://user-images.githubusercontent.com/24651136/232710577-d794e7d6-5c93-474a-b016-c09759d2d85b.png)

### 复现步骤

启动clash后查看进程

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

![image](https://user-images.githubusercontent.com/24651136/232710710-1e6eefd3-cec0-4a61-b006-6c29273f45d7.png)

**Comment by UyCode** [comment]
就离谱
![image](https://user-images.githubusercontent.com/24651136/232711238-bd914d0c-c992-4fe4-a3bf-0dcdd2cb338c.png)

**Comment by yi-Xu-0100** [comment]
看看日志，可能是回环了，试试指定interface-name试试，还是不行，问问core那边

**Comment by UyCode** [comment]
好的，谢谢你了，我刚重启了一下电脑就好了，可能真的是你说的这个问题导致的 @yi-Xu-0100

**Comment by UyCode** [comment]
> 看看日志，可能是回环了，试试指定interface-name试试，还是不行，问问core那边
好的，谢谢你了，我刚重启了一下电脑就好了，可能真的是你说的这个问题导致的 @yi-Xu-0100

**Comment by UyCode** [comment]
> 看看日志，可能是回环了，试试指定interface-name试试，还是不行，问问core那边


好的，谢谢你了，我刚重启了一下电脑就好了，可能真的是你说的这个问题导致的
