### ISSUE TITLE
[Bug]: 按照官网教程下载了软件并执行完毕流程，Rule里没有分发的地址，空空如也

### ISSUE THREAD

**Issue by LemonStar0** [Fndroid/clash_for_windows_pkg#4344]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.21

### 操作系统

Windows x64

### 系统版本

w10

### 问题描述

https://hutaodocuments.gitbook.io/hutaocloud/tutorial/windows/clash-for-windows
按照流程下载完之后  rule没有内容，导致没有代理成功，无法使用

### 复现步骤

直接下载链接即可

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
不是软件自身问题请勿发issue
