### ISSUE TITLE
[Bug]: This app can't run your pc

### ISSUE THREAD

**Issue by realSamy** [Fndroid/clash_for_windows_pkg#4345]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.21

### 操作系统

Windows x64

### 系统版本

Windows 11 22H2 (OS Build 22624.1546)

### 问题描述

- Package installer doesn't extract any file but the uninstaller file
- I tried extracting all the executable files from installer, also tried the .7z file from releases, in both situations I got the error screen: "This app can't run on your pc" 

### 复现步骤

I'm using Windows 11 version 22H2 (OS Build 22624.1546) insider preview, it seems there is a compatibility problem on this version of windows, I hadn't this problem before and I don't know on which release of windows the "Clash for windows" app was working

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
Please download the installation package without the arm64 suffix, and click "show all" to expand the list of all installation packages.

**Comment by realSamy** [comment]
> Please download the installation package without the arm64 suffix, and click "show all" to expand the list of all installation packages.

Thanks, it worked!
