### ISSUE TITLE
[Bug]: win11系统，clash在tun模式下WhatsApp客户端无法联网

### ISSUE THREAD

**Issue by nickonline2005** [Fndroid/clash_for_windows_pkg#4346]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.21

### 操作系统

Windows x64

### 系统版本

Windows 11

### 问题描述

新安装的win11系统，在微软商店安装的WhatsApp最新版客户端。已用工具解除loopback限制。
clash运行在tun模式下，tun配置未改动，用的默认设置，浏览器及其它软件网络访问都没有问题，WhatsApp登录就是刷不出二维码。同节点换用v2rayn的tun模式，WhatsApp成功现实二维码，成功登录并发出消息。换回clash的tun模式，虽然WhatsApp还在登录模式下，但是消息发不出去。

### 复现步骤

win11，clash tun模式，商店版WhatsApp

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
看看日志。

**Comment by yonsanjohnson** [comment]
你好，同样得情况。无法刷二维码

**Comment by yxzlwz** [comment]
同样情况+1，请求重新开放issue
