### ISSUE TITLE
[Bug]: parsers无效

### ISSUE THREAD

**Issue by wxwmaple** [Fndroid/clash_for_windows_pkg#4357]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.9

### 操作系统

Windows x64

### 系统版本

win11

### 问题描述

parsers配置无效

### 复现步骤

首先，我在parsers配置如下规则并保存：
![mmexport1681970287904](https://user-images.githubusercontent.com/31494894/233271756-804dbe8e-01a9-4e69-a0a3-fef77dc1f322.jpg)
然后，我成功更新对应订阅节点，并查看其parsers，显示已经匹配成功：
![mmexport1681970290566](https://user-images.githubusercontent.com/31494894/233271908-2a2bec20-ed64-4c69-bbf4-df6285b4e6d9.jpg)
然而，在最新的规则里，找不到test.com的规则信息：
![QY@SI_P(Q9%7QG` CAOQZVL](https://user-images.githubusercontent.com/31494894/233272037-64126ab2-33ae-478b-b10c-997899bd85a5.png)
已经尝试过软件重启，更新订阅等各种方案，均无效。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by wxwmaple** [comment]
经过反复测试，使用yaml语法直接写无效，使用js注入法有效，供大家参考。
`parsers: # array
- reg: ^.*$
  code: |
    module.exports.parse = async (raw, { axios, yaml, notify }, { url, selected, mode, name }) => {
      const obj = yaml.parse(raw)
      const { 'rules': rules = [] } = obj
      rules.unshift("DOMAIN-SUFFIX,bing.com,Proxy")
      rules.unshift("DOMAIN-SUFFIX,cloudflare.com,Proxy")
      rules.unshift("DOMAIN-SUFFIX,openai.com,Proxy")
      return yaml.stringify(obj);
    }`

**Comment by wxwmaple** [comment]
经过反复测试，使用yaml语法直接写无效，使用js注入法有效，供大家参考。
```
parsers: # array
- reg: ^.*$
  code: |
    module.exports.parse = async (raw, { axios, yaml, notify }, { url, selected, mode, name }) => {
      const obj = yaml.parse(raw)
      const { 'rules': rules = [] } = obj
      rules.unshift("DOMAIN-SUFFIX,bing.com,Proxy")
      rules.unshift("DOMAIN-SUFFIX,cloudflare.com,Proxy")
      rules.unshift("DOMAIN-SUFFIX,openai.com,Proxy")
      notify(`${name} 配置文件预处理成功`, `自定义规则已合并到订阅配置文件中`);
      return yaml.stringify(obj);
    }
```

**Comment by Fndroid** [comment]
> ![](https://user-images.githubusercontent.com/31494894/233271756-804dbe8e-01a9-4e69-a0a3-fef77dc1f322.jpg)

缩进不对
