### ISSUE TITLE
TUN模式：上网、代理正常但是右下角WiFi显示图标是不能上网的样式

### ISSUE THREAD

**Issue by SJJ-dot** [Fndroid/clash_for_windows_pkg#4368]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.21

### 操作系统

Windows x64

### 系统版本

win11，最新

### 问题描述

TUN模式：上网、代理正常但是右下角WiFi显示图标是不能上网的样式

### 复现步骤

TUN模式：上网、代理正常但是右下角WiFi显示图标是不能上网的样式

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
找找相关 issue ，无网络访问 啥的

**Comment by Barbarossa1889** [comment]
这种情况，打开TUN的同时，断开下本地网络重连等待几秒就会正常。

**Comment by q2051839** [comment]
大概是DNS问题，本机是否跑了其他DNS应用

**Comment by Back-T0** [comment]
请问是如何解决的，我也出现了一样的问题
