### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by crazyNi** [Fndroid/clash_for_windows_pkg#4369]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.17

### 操作系统

Linux

### 系统版本

Ubuntu 22.04 LTS

### 问题描述

尝试了各种方法依然没法google。。
运行过了export https_proxy=http://127.0.0.1:%mixedPort%;export http_proxy=http://127.0.0.1:%mixedPort%;export all_proxy=socks5://127.0.0.1:%mixedPort%
看上去proxy设置已经正常了吧。。
上传下传一直为0b/s。浏览器试了试也不行。

### 复现步骤

![image](https://user-images.githubusercontent.com/130941523/233818494-348ccb40-10ff-4d35-9a66-63054f22e4c4.png)
![image](https://user-images.githubusercontent.com/130941523/233818502-03d9f67b-f149-493e-aa41-a4b6faaf6460.png)
我是没有界面的ubuntu，装了个远程界面，不知道是不是跟这个有关系。。？

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>
[2023-04-23-114103.log](https://github.com/Fndroid/clash_for_windows_pkg/files/11302778/2023-04-23-114103.log)

**Comment by yi-Xu-0100** [comment]
应该用curl检查是否成功，而不是ping.

浏览器访问需要设置系统代理，我不知道你没有界面怎么去设置，或者浏览器设置里找找设置代理。

**Comment by crazyNi** [comment]
> 

谢谢，那好像是OK的了。

**Comment by QS0x01** [comment]
![image](https://user-images.githubusercontent.com/119924985/233882185-ba483657-0435-40da-aabe-7a21031e328c.png)
