### ISSUE TITLE
使用provider导入的节点， 点击延迟时间无法重新测延迟

### ISSUE THREAD

**Issue by Zhaowei-Yu** [Fndroid/clash_for_windows_pkg#437]
![image](https://user-images.githubusercontent.com/48342561/74796691-50469900-5304-11ea-812b-06a43de12c38.png)
点此无法测延迟，需要check health才能重新测。 版本：cfw 0.8.11

**Comment by Fndroid** [comment]
Provider节点无法单独测试，需要在Provider页面中操作
