### ISSUE TITLE
[Bug]: Clash 无法切换到此配置文件 Error: timeout of 10000ms exceeded

### ISSUE THREAD

**Issue by Cxy1111111111** [Fndroid/clash_for_windows_pkg#4372]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

Clash for Windows v 0.20.21

### 操作系统

Windows x64

### 系统版本

Windows 10 企业版 22H2

### 问题描述

打开Clash的系统代理模式可以翻墙，但是打开tun模式反馈给我的却是无法切换到此配置文件Error: timeout of 10000ms exceeded，应该如何解决这个问题？

![24143d47d4732edcc49b08081e146a7](https://user-images.githubusercontent.com/131019933/233829830-03df47e1-292d-4004-b438-ebf39e775c4b.png)

### 复现步骤

无复现步骤

### 日志文件

![1682240121545](https://user-images.githubusercontent.com/131019933/233829936-0c937f80-966c-468c-a5af-c23587359b4d.png)

**Comment by yi-Xu-0100** [comment]
> 使用的是官方版本（未替换及修改过安装目录程序文件）

**Comment by sanwacompany** [comment]
我也是，用TUN模式就这样。

**Comment by Saddss** [comment]
也遇到了，怎样解决呢
