### ISSUE TITLE
clash这是在上传什么呢？

### ISSUE THREAD

**Issue by rangluwme** [Fndroid/clash_for_windows_pkg#4374]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.21

### 操作系统

Windows x64

### 系统版本

64

### 问题描述

![2023-04-23_21-19-57](https://user-images.githubusercontent.com/63960943/233842112-da60f05d-189e-47a6-a4f2-f541e5f8434b.jpg)

![2023-04-23_21-20-09](https://user-images.githubusercontent.com/63960943/233842097-d692417d-267e-4713-8d92-79341553d666.jpg)

### 复现步骤

无

**Comment by rangluwme** [comment]
我记得之前有个版本在connections里面看到，某个连接是来自哪个应用（是不是叫process path），现在怎么看不到了。

**Comment by yi-Xu-0100** [comment]
rules中包含一个process-name规则，logs开debug即可

**Comment by lankylonky22** [comment]
win security就够了
