### ISSUE TITLE
开启代理后默认设置系统代理为http代理而无法设置为socks代理

### ISSUE THREAD

**Issue by XuuKoo** [Fndroid/clash_for_windows_pkg#438]
配置文件中为http代理、socks代理分别设置了端口，通过打开system proxy按钮启动代理后，clash会为系统（win10）设置的代理为“127.0.0.1:http代理端口”，若手动将端口更改为socks的端口，clash的代理则会停止。
请问该如何将系统的代理设置为clash的socks代理，或者关闭clash的http代理？

**Comment by Fndroid** [comment]
“手动设置代理”并不支持socks
