### ISSUE TITLE
建议在Mac M1上可以设置隐藏Dock icon图标，仅保留右上角图标

### ISSUE THREAD

**Issue by garywu520** [Fndroid/clash_for_windows_pkg#4388]
### 功能描述

建议在M1上隐藏Dock icon图标，仅保留右上角图标

**Comment by garywu520** [comment]
有此功能，已解决

**Comment by duzhen1996** [comment]
抱歉，这个功能好像没有解决。关闭窗口之后dock栏的图标依据存在。

**Comment by LeoCao-X** [comment]
您好，目前这个问题好像没有解决。使用macOS13.5，Clash for Windows v0.20.31
