### ISSUE TITLE
系统被代理到80端口

### ISSUE THREAD

**Issue by SweetPotatoo** [Fndroid/clash_for_windows_pkg#439]
clash界面上的port一直显示0，打开系统代理后系统(win10 1909)被代理到80端口，无法使用。
配置文件中的port值应该是正确的。(即使使用默认的配置文件Port依然显示0)

**Comment by SweetPotatoo** [comment]
![image](https://user-images.githubusercontent.com/30442103/74849150-59bb1a00-5373-11ea-84f2-e32c303d1274.png)

**Comment by SweetPotatoo** [comment]
![image](https://user-images.githubusercontent.com/30442103/74849431-a4d52d00-5373-11ea-8b5b-918176b7fa1a.png)

**Comment by Fndroid** [comment]
1. 显示0表示端口被占用，clash无法启动对应的http proxy server
2. 由于1的缘故，system proxy也就无法正常打开

**Comment by SweetPotatoo** [comment]
知道了。感谢

> 1. 显示0表示端口被占用，clash无法启动对应的http proxy server
> 2. 由于1的缘故，system proxy也就无法正常打开
