### ISSUE TITLE
Capture界面在某些情况下显示混乱

### ISSUE THREAD

**Issue by ryans233** [Fndroid/clash_for_windows_pkg#44]
版本0.5.8。不是很清楚稳定复现的条件，但是出现的几率蛮高的，刷一下 [育碧商城](https://store.ubi.com) 可能会出现……
![{}KLGLGULRK{I(0SPLBZ~DB.png](https://i.loli.net/2018/12/17/5c17c0734ad6e.png)

**Comment by Fndroid** [comment]
没写FINAL或者MATCH

**Comment by ryans233** [comment]
果然如此。猜想是因为旧版的规则没有随着Clash的升级而迁移。
