### ISSUE TITLE
搞不懂的clash 崩溃

### ISSUE THREAD

**Issue by wuligai** [Fndroid/clash_for_windows_pkg#440]
同一节点v2ray正常，但clash连上几秒打开chorme 就崩溃 日志是"Can't load mmdb: CreateFileMapping: The volume for a file has been externally altered so that the opened file is no longer valid."

**Comment by Fndroid** [comment]
进入Home Directory，删除Country.mmdb并重启软件

**Comment by wuligai** [comment]
谢谢 按您的方法解决了
