### ISSUE TITLE
clash的所有线路都是timeout，不可用是为什么?

### ISSUE THREAD

**Issue by qsyzzzz** [Fndroid/clash_for_windows_pkg#441]
昨天刚按照安装教程安装好了，试了以下可以用，然后下午晚上以及今天使用的时候，测试所有线路都是timeout，然后连不上外网，请问怎么解决啊？

**Comment by L0snight** [comment]
先检查你的节点是否正常

**Comment by qsyzzzz** [comment]
都检查了，和安装说明中一样的

**Comment by Fndroid** [comment]
突然不能用的话，先更新配置文件试试

**Comment by qsyzzzz** [comment]
我更新了配置文件，然后只有一个线路可以用，过一段时间后又是全部线路timeout

**Comment by Fndroid** [comment]
timeout有几个可能的原因：
1. 节点配置错误
2. 节点无法访问
3. 配置的url-test所用的url不合理

一般都和软件无关

**Comment by ms20hj** [comment]
我也是这样子，我自己家里的笔记本都能 用的好好的，在公司电脑就是不能用
![image](https://user-images.githubusercontent.com/23376892/76289085-443a6f80-62e3-11ea-820e-d9677489b9da.png)

**Comment by lvshuaiyang** [comment]
更改一下系统时间。

**Comment by XinSSS** [comment]
我现在也是出现了这个问题, 所有的线路全是timeout, 但是同样的节点用v2RayN以及在android上使用没问题...求解问题可能出在哪? Windows防火墙也关了

**Comment by XinSSS** [comment]
#602 解决了

**Comment by LiTianxiong** [comment]
> #602 解决了

遇到同样的问题，能说下怎么解决的吗

**Comment by XinSSS** [comment]
> > #602 解决了
> 
> 遇到同样的问题，能说下怎么解决的吗

进上面的issue看, 我自己是v2线路timeout, 别的情况就不清楚了

**Comment by sparereal** [comment]
> 更改一下系统时间。

感谢，我的timeout确是系统时间导致的，更新后正常了。

**Comment by Papaw-Mill** [comment]
> 更改一下系统时间。

真的可以！！！！太开心啦哈哈哈哈哈哈

**Comment by HaiLin545** [comment]
更改系统时间？

**Comment by pfyuan** [comment]
直接更改电脑的系统时间吗？？？

**Comment by Papaw-Mill** [comment]
> 直接更改电脑的系统时间吗？？？

嗯嗯。我是这样的。

**Comment by onlineage** [comment]
> 直接更改电脑的系统时间吗？？？

电脑时间 自动更新一次 就行了

**Comment by MaJesTySA** [comment]
> 更改一下系统时间。

补充一下，更新系统时间可以解决。
Win10 1909设置-搜索“日期”-进入“时间和日期”-“同步时钟”下点击“立刻同步”

**Comment by visile** [comment]
请问一下，要把系统时间改成什么呀？

**Comment by visile** [comment]
> > 直接更改电脑的系统时间吗？？？
> 
> 嗯嗯。我是这样的。

请问一下是直接同步时间吗？

**Comment by truthciao** [comment]
> 更改一下系统时间。

装了ubuntu20.04双系统，返回win10的时候系统时间不对导致clash全部timeout，通过禁用ubuntu的UTC解决了

**Comment by win5do** [comment]
电脑很久未使用，但时间是正确的（目测），clash 全部 timeout。
设置中点同步时间后，clash 恢复正常。

**Comment by JR-cityweaver** [comment]
2021/9/19上周之前clash就开始出现连接一段时间就全部节点timeout的情况，只要重启就能重新打开，但是隔一小段时间又timeout了，节点是glados的，是那边出问题了还是最近更新的问题呢？

**Comment by luxiaokui520** [comment]
> 更改一下系统时间。

非常有用，十分感谢

**Comment by dirk1041** [comment]
> 更改一下系统时间。
还真的是 非常感谢

**Comment by miozus** [comment]
果然 ： DNS 有问题!
为了登录微软账号，设置了 DNS 4.2.2.1 ，清空后（自动获取），就连接上了。

**Comment by BIU64** [comment]
和时间/DNS都无关的话，可以试试这个方案：https://maofun.com/2104.html
为作者打Call，太有效了

**Comment by Piaoboyisheng** [comment]
> 和时间/DNS都无关的话，可以试试这个方案：https://maofun.com/2104.html 为作者打Call，太有效了

这个问题也困扰了我好几个月时间，刚刚按您的指点试了试分享的链接，果然有效，其他矫正系统时间的招根本就是盲人奇瞎马！

**Comment by NileXu** [comment]
亲测有效，来自知乎：https://www.zhihu.com/question/506101771/answer/2313909982

"右键点击你订阅的节点，打开所在文件夹，把节点对应的yml文件使用记事本打开，将dns下的enable后的true改为false。"

**Comment by Piaoboyisheng** [comment]
> 亲测有效，来自知乎：https://www.zhihu.com/question/506101771/answer/2313909982
> 
> "右键点击你订阅的节点，打开所在文件夹，把节点对应的yml文件使用记事本打开，将dns下的enable后的true改为false。"

谢谢楼主提供了另一个思路。可惜我的.yaml配置文件中一直都没有dns一项，过去也用得好好的。还是楼上给的替换parsers文件的办法彻底解决了问题。

**Comment by NileXu** [comment]
> > 亲测有效，来自知乎：https://www.zhihu.com/question/506101771/answer/2313909982
> > "右键点击你订阅的节点，打开所在文件夹，把节点对应的yml文件使用记事本打开，将dns下的enable后的true改为false。"
> 
> 谢谢楼主提供了另一个思路。可惜我的.yaml配置文件中一直都没有dns一项，过去也用得好好的。还是楼上给的替换parsers文件的办法彻底解决了问题。

我的是替换parsers的办法无效，找到这个办法才成功的．

**Comment by seekerrc** [comment]
> 更改一下系统时间。

卧槽太强了，我的超人

**Comment by alexthelegendhero** [comment]
以上方法都试过了，还是没有解决问题，更新的 vmess 在 WinXray 里面可以正常使用，转换了 放到 clash 里面 就全部都是 timeout。

**Comment by wenwennannan** [comment]
> 和时间/DNS都无关的话，可以试试这个方案：https://maofun.com/2104.html 为作者打Call，太有效了

有用，太感谢了。

**Comment by Lete114** [comment]
> 以上方法都试过了，还是没有解决问题，更新的 vmess 在 WinXray 里面可以正常使用，转换了 放到 clash 里面 就全部都是 timeout。

同样全部试过了，没一个能解决的，就在今天早上还能使用，到了11点钟就全部timeout了，但同样的节点放到v2ray完全能正常使用

**Comment by ColdRain-Moro** [comment]
挺怪的，我也遇到了这个问题，但是我的解决方法跟上面有大佬提到的相反，把配置中dns.enable改为true就好了。
为什么呢？难道是 dns 这一块存在什么问题吗，比如缓存啥的。

顺便一提，我是 Manjaro Linux用户。

**Comment by BlankSeed** [comment]
> 亲测有效，来自知乎：https://www.zhihu.com/question/506101771/answer/2313909982
> 
> "右键点击你订阅的节点，打开所在文件夹，把节点对应的yml文件使用记事本打开，将dns下的enable后的true改为false。"

有用，感谢！

**Comment by xiaozeng2296** [comment]
> 为啥复制他会说代码错误 第一行语法有问题

**Comment by xiaozeng2296** [comment]
> > 和时间/DNS都无关的话，可以试试这个方案：https://maofun.com/2104.html 为作者打Call，太有效了
> 
> 有用，太感谢了。

为啥复制他会说代码错误 第一行语法有问题

**Comment by 1206lizijing** [comment]
> 

请问您解决了吗？我也是第一行语法有问题

**Comment by xiaozeng2296** [comment]
> > 
> 
> 请问您解决了吗？我也是第一行语法有问题

我朋友是泉州地区的 他们好像买的vpn在泉州地区就无法使用，买其他的vpn就好了，这个好像是有些地区有什么保护。

**Comment by xiaozeng2296** [comment]
> > 
> 
> 请问您解决了吗？我也是第一行语法有问题
语法问题最后就没去解决，测了好几个版本都不行，一直全部timeout可以考虑换一下vpn订阅链接，可以拿朋友其他的梯子试一下

**Comment by JR-cityweaver** [comment]
可能是因为电脑的火绒冲突，你可以试试看关闭火绒在打开会不会出现类似的问题，我现在有时候clash也会崩溃，如果真的被这个问题困扰，建议换一个软件，ssr，shadowrocket这类的都行
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fndroid/clash_for_windows_pkg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月9日(星期一) 上午10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fndroid/clash_for_windows_pkg] clash的所有线路都是timeout，不可用是为什么? (#441)





   
请问您解决了吗？我也是第一行语法有问题

**Comment by SakurajimaMaii** [comment]
好家伙，真的是时间问题

**Comment by Chasellin** [comment]
> 没有用，用公司wifi不行，链接手机热点就可以。怀疑是公司网络问题，但是设置clash的dns无效，设置电脑网络的dns也不起作用

请问你最后解决了吗 我也是这样，换个网络就不行

**Comment by cxn304** [comment]
> 

我感觉是ip被封了

**Comment by dukuzu** [comment]
现在这个网址打不开了> 亲测有效，来自知乎：https://www.zhihu.com/question/506101771/answer/2313909982
> 
> 
> 
> "右键点击你订阅的节点，打开所在文件夹，把节点对应的yml文件使用记事本打开，将dns下的enable后的true改为false。"

**Comment by wordscode** [comment]
> 和时间/DNS都无关的话，可以试试这个方案：https://maofun.com/2104.html 为作者打Call，太有效了

报错！！！
Error: Document contains trailing content
not separated by a ... or --- line at line 1,
column 16:
[prism lang=""]parsers:
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/75980075/6947a013-3101-4aab-a3df-011c7ffc7224)

**Comment by Hezhexi2002** [comment]
> > 更改一下系统时间。
> 
> 补充一下，更新系统时间可以解决。 Win10 1909设置-搜索“日期”-进入“时间和日期”-“同步时钟”下点击“立刻同步”

卧槽，真的可以了，但是我想知道为啥会这样呢，同步系统时间和节点超时有什么必然联系吗

**Comment by elanwoo** [comment]
> 可能是因为电脑的火绒冲突，你可以试试看关闭火绒在打开会不会出现类似的问题，我现在有时候clash也会崩溃，如果真的被这个问题困扰，建议换一个软件，ssr，shadowrocket这类的都行 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Fndroid/clash_for_windows_pkg" ***@***.***&gt;; 发送时间:&nbsp;2023年1月9日(星期一) 上午10:31 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Fndroid/clash_for_windows_pkg] clash的所有线路都是timeout，不可用是为什么? (#441) 请问您解决了吗？我也是第一行语法有问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

兄弟，谢谢你，真的！如果没看到你提醒，我可能到死都想不到是火绒拦截了。

我是这么解决的：

火绒软件里点击“防护中心”，然后点击“系统防护”，把“联网控制”关闭，timeout直接变成毫秒延迟的数字，正常上网！

希望能帮到个别小伙伴。

最后再感谢一下JR-cityweaver朋友，比心！
