### ISSUE TITLE
[Bug]: route print 0.0.0.0 mask 0.0.0.0 ‘route’ ......

### ISSUE THREAD

**Issue by yydsxiaozhang** [Fndroid/clash_for_windows_pkg#4410]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.0

### 操作系统

Windows x64

### 系统版本

0.19.0

### 问题描述

在更新配置后，会弹出一个如 route print 0.0.0.0 mask 0.0.0.0 ‘route’ ......的小窗口 然后无法连接

### 复现步骤

在更新配置上的时候

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
换最新版试试
