### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by JSCSZZSS** [Fndroid/clash_for_windows_pkg#4416]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.22

### 操作系统

Windows x64

### 系统版本

版本	Windows 10 专业版 版本号	22H2 

### 问题描述

订阅链接点download会报错network error，没有其他操作，第一次下载clash
小白求救，不管是clash还是v2rayn订阅的时候都会报错，试了好几个版本，clash订阅下载就是network error，v2rayN就是一种访问权限不允许的方式做了一个访问套接字的尝试

### 复现步骤

订阅链接点download会报错network error，没有其他操作，第一次下载clash，其他电脑没有这种问题

**Comment by yi-Xu-0100** [comment]
订阅链接需要支持直连下载，这个得问提供者。
