### ISSUE TITLE
Clash反应慢，启动好几分钟。。。。。启动起来就好了

### ISSUE THREAD

**Issue by hupo376787** [Fndroid/clash_for_windows_pkg#442]
每次一开软件就这样子白屏。要等好几分钟才能加载出界面。

Win10 x64 1909，i7，32G

![image](https://user-images.githubusercontent.com/14960168/74949956-65711400-5439-11ea-8424-fec21ce0d8c1.png)

**Comment by Delecomp** [comment]
> 每次一开软件就这样子白屏。要等好几分钟才能加载出界面。
> 
> Win10 x64 1909，i7，32G
> 
> ![image](https://user-images.githubusercontent.com/14960168/74949956-65711400-5439-11ea-8424-fec21ce0d8c1.png)

换电脑

**Comment by hupo376787** [comment]
@Delecomp 换i9的电脑吗🙃🙃🙃

**Comment by Fndroid** [comment]
先从这两个地方排除下吧：
1. 是不是开了一些类似GPU加速/软件加速的工具
2. powershell输入``node --eval="console.log(process.env.NODE_ENV)"``看下输出是不是``development``

**Comment by hupo376787** [comment]
@Fndroid 
1. 没有GPU加速的东西，只是Nvidia控制面板是高性能模式。现在改成自动模式也是一样的。

2. 输入`node --eval="console.log(process.env.NODE_ENV)"` ，输出undefined。

好蛋疼，为什么别人都没遇到这个bug

**Comment by Olivercoco** [comment]
![image](https://user-images.githubusercontent.com/39828052/75620062-ec9f5400-5bbe-11ea-83a0-b608c4726f85.png)
我每次启动会在这个页面停顿大概40S，然后恢复正常。V0.9.0

**Comment by cyrto** [comment]
@Fndroid 
> 先从这两个地方排除下吧：
> 
> 1. 是不是开了一些类似GPU加速/软件加速的工具
> 2. powershell输入`node --eval="console.log(process.env.NODE_ENV)"`看下输出是不是`development`

现在遇到了一打开就白屏的问题，加载不出任何页面，而且一直卡在白屏界面输入是`node --eval="console.log(process.env.NODE_ENV)"`是development说明了什么？

**Comment by Fndroid** [comment]
@cyrto 

```

SET NODE_ENV=production

```

**Comment by Qiqia** [comment]
> @cyrto
> 
> ```
> 
> SET NODE_ENV=production
> ```

腻害了 还真是这个问题  把这个环境变量干掉就好了

**Comment by flipped-cj** [comment]
> 先从这两个地方排除下吧：
> 
> 1. 是不是开了一些类似GPU加速/软件加速的工具
> 2. powershell输入`node --eval="console.log(process.env.NODE_ENV)"`看下输出是不是`development`

还真是，这个问题困扰我一个星期了，这软件还能识别node的环境变量么

**Comment by cairongquan** [comment]
如果你环境变量是development 去windows环境变量里面改production 或者直接把NODE_ENV这个变量删了 打开白屏就解决了吧。。

> > 先从这两个地方排除下吧：
> > 
> > 1. 是不是开了一些类似GPU加速/软件加速的工具
> > 2. powershell输入`node --eval="console.log(process.env.NODE_ENV)"`看下输出是不是`development`
> 
> >还真是，这个问题困扰我一个星期了，这软件还能识别node的环境变量么

>比较electron开发的嘛。。。

**Comment by cairongquan** [comment]
如果你环境变量是development 去windows环境变量里面改production 或者直接把NODE_ENV这个变量删了 打开白屏就解决了吧。。
