### ISSUE TITLE
[Bug]: 最近下载完profiles:5月9日和5月10日的 都报错：could not to switch to this file

### ISSUE THREAD

**Issue by jennazheng90** [Fndroid/clash_for_windows_pkg#4428]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.22

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

最近下载完profiles:5月9日和5月10日的 都报错：could not to switch to this file 报错内容不一样

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/32327387/2f54e366-f89f-4c91-a6f2-2e00976c54bb)

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/32327387/ea062a3a-2113-493f-88e0-1dae60a1e2d5)

### 复现步骤

最近下载完profiles:5月9日和5月10日的 都报错：could not to switch to this file 报错内容不一样

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/32327387/2f54e366-f89f-4c91-a6f2-2e00976c54bb)

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/32327387/ea062a3a-2113-493f-88e0-1dae60a1e2d5)

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
有个节点的格式 clash 可能不支持。找到然后删除就好了

**Comment by jennazheng90** [comment]
> 有个节点的格式 clash 可能不支持。找到然后删除就好了

好的 已经解决！感谢回复！
