### ISSUE TITLE
0.8.11 logs不显示内容

### ISSUE THREAD

**Issue by ininolee** [Fndroid/clash_for_windows_pkg#444]
0.8.11 logs不显示内容

**Comment by Fndroid** [comment]
软件哪里下载的

**Comment by ininolee** [comment]
就在这里下载的

**Comment by ininolee** [comment]
软件的logs不显示日志，但是文件夹里的log文件是有记录的

**Comment by Xxurc** [comment]
> 软件哪里下载的

我也出现了这种情况，就是下载的最新exe版本，日志文件里是正常的，但是在clash的logs里不显示任何东西

**Comment by Fndroid** [comment]
在这里下载的，那有没有换个软件里的文件，比如clash-win64.exe

**Comment by Xxurc** [comment]
> 在这里下载的，那有没有换个软件里的文件，比如clash-win64.exe

替换了内核...因为是ssr用，上个版本是没有问题的，以后会改回来吗？还是保持现状
