### ISSUE TITLE
[Feature Request]: I recommended to import multi-profile functionality.

### ISSUE THREAD

**Issue by MarkIvory2973** [Fndroid/clash_for_windows_pkg#4443]
### 功能描述

Multi-profile means you can select different profile in a time.

When the proxies of profile are in low speed, you will switch another profile to get a better speed. But with the import of multi-profile you won't do this. When I switches more than 2 profiles, the clash will put their proxies into a big proxies pool. Then the clash will select the lowest speed proxy automatically.

**Comment by yi-Xu-0100** [comment]
use proxy-provider.
