### ISSUE TITLE
[Bug]: 托盘图标的右键菜单变得非常缓慢

### ISSUE THREAD

**Issue by Fitmtfk** [Fndroid/clash_for_windows_pkg#4449]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.23

### 操作系统

Windows x64

### 系统版本

Windows11 21H2 22000.613

### 问题描述

托盘图标的右键菜单变得非常缓慢
大约右键点击后2秒钟才会出现
菜单的操作反应及时 正常
![1](https://github.com/Fndroid/clash_for_windows_pkg/assets/31401013/2b9968db-eefb-4dcc-942e-cf5b318a39be)

### 复现步骤

使用scoop install clash-for-windows安装，来源buckets为dorado
我尝试了0.22.17 18 19 20 21 22 23都是这样
我尝试删除了所有的配置文件包括软件本身的设置，无法解决此问题
但是印象当中以前用这些老版本时的右键菜单很正常
我在ToogleDevTools里看到了一些错误 不知道是否有关联
![图片](https://github.com/Fndroid/clash_for_windows_pkg/assets/31401013/6f02f578-522e-47e2-ae04-fed5bf084029)
![图片](https://github.com/Fndroid/clash_for_windows_pkg/assets/31401013/6417e9aa-232b-491a-a42f-fd21a737f1b8)

**Comment by Fitmtfk** [comment]
我刚刚在vmware虚拟机中的win10进行了尝试，没发现问题

**Comment by Fndroid** [comment]
<img width="683" alt="image" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/16091562/725acd84-5062-4a60-93b0-ba4971fd36f3">

**Comment by Fitmtfk** [comment]
> <img alt="image" width="683" src="https://user-images.githubusercontent.com/16091562/238195292-725acd84-5062-4a60-93b0-ba4971fd36f3.png">

![2](https://github.com/Fndroid/clash_for_windows_pkg/assets/31401013/1094e36a-253d-49db-8a6c-aa71ebb35a60)
似乎并没有什么区别
我正在尝试寻找系统上的问题

**Comment by Fitmtfk** [comment]
有了一点发现
就算我将Tray Proxy Groups Style设置为Default或者Submenu 也一样无法加载出节点信息 可能这就是问题所在
就算我删除全部的配置文件 还原全部的软件设置 也并不能解决此问题
我也尝试了不使用scoop 直接安装cfw 也未能解决
我尝试用相同的镜像 全新安装了系统 使用相同的设置和配置文件 右键菜单正常工作
似乎是我当前的系统有什么东西 影响到了cfw Tray Proxy Groups的工作
我想不到有什么潜在的可能

**Comment by Fitmtfk** [comment]
我找到原因了，我上周使用cmake编译一些东西时为cmake设置了代理（使用的方法是添加名为http_proxy与https_proxy的环境变量）
我刚刚将这两个环境变量删除后重启了clash 他恢复了正常
怀疑是它们影响了CFW与Clash Core之间的通讯

**Comment by xvhuan** [comment]
我最近两天也出现这种问题了。。。不知道怎么解决 XD

**Comment by xvhuan** [comment]
好了，我也修好了。我是安装composer的时候，给我添加了个全局代理，然后我去环境变量把这个删掉就好了。看样子这种问题的出现就是环境变量导致的 👍

**Comment by lssdo12** [comment]
我也是装composer后出现这个问题了，在环境变量里有个变量http_proxy，值为127.0.0.1:7890，把他删了就好了
