### ISSUE TITLE
版本0.8.11，could not connect to clash core

### ISSUE THREAD

**Issue by stevenzhang027** [Fndroid/clash_for_windows_pkg#445]
根据之前的issue修改了proxy, socks, external等端口依然无效。
[2020-02-22-122131.log](https://github.com/Fndroid/clash_for_windows_pkg/files/4238806/2020-02-22-122131.log)

**Comment by KeSaite** [comment]
我0.8.11也一样，全新安装的win10也出现这个问题，log看也没报错
[2020-02-26-024754.log](https://github.com/Fndroid/clash_for_windows_pkg/files/4251586/2020-02-26-024754.log)

**Comment by codeAndxv** [comment]
0.8.11，win10，同样遇到这个问题。修改external端口无效，重启后正常。

**Comment by Mn4CaO5** [comment]
Windows 10 Pro，0.8.11，遇到同样问题。
通过以下2个步骤解决：
1) 以管理员权限运行exe安装包。
2) 安装过程中，勾选为所有用户安装。

**Comment by Mn4CaO5** [comment]
Windows 10 Pro，0.8.11，遇到同样问题。
通过以下2个步骤解决：
1）以管理员权限运行exe安装包。
2）安装过程中，勾选为所有用户安装。

**Comment by ManassehZhou** [comment]
clash for windows 调用的配置文件是config.yml
clash 调用的配置文件里是config.yaml
.yaml里面只有一个`http-port:7890`, 所以日志文件里只显示了`listen http port 7890`
其实是还没启动起来...

**Comment by Fndroid** [comment]
@ManassehZhou 默认情况下config.yaml是空的（除非手动改过），clash会读取config.yml

**Comment by ManassehZhou** [comment]
@Fndroid 

10天前clash更新了代码, https://github.com/Dreamacro/clash/blame/master/config/initial.go#L41

初始化的时候不是空文件了, 现在会往里写一行东西...

**Comment by ManassehZhou** [comment]
> @ManassehZhou 默认情况下config.yaml是空的（除非手动改过），clash会读取config.yml

(如果是全新安装的话, 用最新版的clash.exe可能会有问题, 但是如果是之前已经有config.yaml的话就没问题.

**Comment by ManassehZhou** [comment]
我看issue里面好多都是这个问题
暂时的解决办法:
1. 先开软件, 出来`can't connect to clash core`之后退出
2. 打开`C:\Users\<username>\.config\clash`, 把里面的 `config.yaml` 这个文件的内容清空
3. 重启软件

**Comment by Fndroid** [comment]
感谢反馈

**Comment by Fndroid** [comment]
fixed in this release: https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.0
