### ISSUE TITLE
[Bug]: TUN模式，YouTube视频加载，vmess节点速度上不去，ss节点正常

### ISSUE THREAD

**Issue by re-b0t** [Fndroid/clash_for_windows_pkg#4454]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

20.23,20.18

### 操作系统

Windows x64

### 系统版本

WIN11

### 问题描述

tun模式，起初是发现YouTube加载转圈，vmess节点速度上不去，ss节点正常
系统代理模式正常

### 复现步骤

20.23卸载后转20.18没有删除配置文件继续用，情况依旧

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

无

**Comment by coco456** [comment]
系统的时间和网络时间不同步，大于2分钟，vmess就不能用

**Comment by re-b0t** [comment]
> 系统的时间和网络时间不同步，大于2分钟，vmess就不能用

在用v2ray客户端的时遇到过，不过我还是进行了时间同步操作，没什么效果。

**Comment by re-b0t** [comment]
@coco456 不懂了，对比了下，也许是规则不好，另外一家的VMESS又没事

**Comment by weedsstars** [comment]
> @coco456 不懂了，对比了下，也许是规则不好，另外一家的VMESS又没事
我也遇到了，system模式正常，tun模式看youtube的network activity 一直0kb要等很久才正常。
