### ISSUE TITLE
[Bug]: 为啥新版本不能开机启动了？

### ISSUE THREAD

**Issue by xivi1839** [Fndroid/clash_for_windows_pkg#4465]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

Clash.for.Windows-0.20.23-win.7z

### 操作系统

Windows x64

### 系统版本

WIN10_22H2

### 问题描述

下载的Clash.for.Windows-0.20.23-win.7z，
以前旧版本一直都可以开机启动的，现在下载的新版本居然失效了，开机启动不了，搞得我现在一直手动启动，有点烦！
这个问题能修复一下吗？

### 复现步骤

·

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

·

**Comment by xivi1839** [comment]
![Snipaste_2023-05-20_18-04-56](https://github.com/Fndroid/clash_for_windows_pkg/assets/24610024/dcc33290-b890-485c-8cae-a7b6749b597b)



版本	Windows 10 专业版
版本号	22H2
安装日期	‎2023/‎2/‎21
操作系统内部版本	19045.2604
体验	Windows Feature Experience Pack 120.2212.4190.0

**Comment by depewzhang** [comment]
我新升级了0.20.37后出现这个问题了……怎么解决啊？
