### ISSUE TITLE
rule模式用不了，全局代理可以。

### ISSUE THREAD

**Issue by Androidyes** [Fndroid/clash_for_windows_pkg#447]
在rule模式下，翻不出去。已经确定服务器可用，因为在global下，同一个服务器是可以用的。
![捕获](https://user-images.githubusercontent.com/61401807/75131827-95f1d000-570f-11ea-867f-a62c3083c807.PNG)
日志显示如上。
rule里，dometic选的direct，其他都是proxy里的服务器。
dns设置的是8888和8844。尝试改过，但是没用。
跪求大佬帮忙分析原因

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
