### ISSUE TITLE
clash每隔10-15分鐘斷開網絡連接

### ISSUE THREAD

**Issue by Allan1337** [Fndroid/clash_for_windows_pkg#449]
非常煩人...無論system proxy是開還是關, 
每過10-15分鐘(chrome裡面的網絡)就會斷開 完全死掉一樣, 
但是只有chrome和chromium斷開, 
其他軟件, 包括其他瀏覽器(edge)也是連接正常的,

只能手動再打開/關掉system proxy一次, 網絡才能正常
就算換成V2RAYN也是一樣的情況,
把clash force quit了也沒有用...

求救...新手勿噴

**Comment by abingx** [comment]
断网后看看你的系统代理设置是什么，我猜想你的代理设置被其他应用修改了，你开关一次system proxy又重新写了一次系统代理

**Comment by Allan1337** [comment]
> 断网后看看你的系统代理设置是什么，我猜想你的代理设置被其他应用修改了，你开关一次system proxy又重新写了一次系统代理

不好意思你指的是windows設定裡面的proxy設置嗎? 全部都是關掉的...如果會錯意還麻煩你指出問題所在...實在是很困擾
然後就是 關於'代理设置被其他应用修改了', 這個情況是最近使用V2RAY, 下載了clash才開始出現的

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
