### ISSUE TITLE
[Feature Request]: 使用Parsers、proxy-providers合并多个订阅的节点、规则

### ISSUE THREAD

**Issue by Karonolandiis** [Fndroid/clash_for_windows_pkg#4490]
### 功能描述

使用Parsers来删掉原订阅链接的规则、添加上自己的规则是非常好用的，然而对于不同的订阅链接使用Parsers也只能得到相同规则、不同节点的多个配置文件。是否可以加入Surge一样的、能够将多个订阅链接的节点、规则合并的功能？

**Comment by Karonolandiis** [comment]
发现 mix-proxy-providers 可以实现。

**Comment by yi-Xu-0100** [comment]
path 中文件名要用url的md5

**Comment by Karonolandiis** [comment]
> 

这个是cfw中Parsers里的配置，clash core配置里的path会由cfw修改为md5。

**Comment by yi-Xu-0100** [comment]
@Karonolandiis parser也是修改profiles的内容，CFW修改应该是在提交的时候，你去general节目点那个芯片的标志看看最后提交的结果。

或者你看看你paraer修改成功profile了吗？

**Comment by yi-Xu-0100** [comment]
还有一个问题，如果节点名称一致，CFW节目反推出来的provider是有问题的。

**Comment by Karonolandiis** [comment]
> 还有一个问题，如果节点名称一致，CFW节目反推出来的provider是有问题的。这个没法解决。
那应该是这个问题了，谢谢！
