### ISSUE TITLE
[Bug]: copy command界面内的%mixedPort%没有被替换成端口

### ISSUE THREAD

**Issue by xlsfs** [Fndroid/clash_for_windows_pkg#4493]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.24

### 操作系统

macOS arm64(M1,M1*)

### 系统版本

13.2.1 (22D68)

### 问题描述

copy command界面内的%mixedPort%没有被替换成端口

![20230527182242](https://github.com/Fndroid/clash_for_windows_pkg/assets/7886342/7fd34c15-f638-4def-aa10-7638394f5751)

### 复现步骤

打开软件就这样

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by LiweiDong** [comment]
同样的问题，很多个版本之前就这样了。
能不能修复一下呢 感谢

**Comment by Fndroid** [comment]
这里的意思是点”OK“这个按钮的时候把转换后的命令复制到剪贴板，不是直接去拷贝这个输入框的命令

**Comment by LiweiDong** [comment]
> 这里的意思是点”OK“这个按钮的时候把转换后的命令复制到剪贴板，不是直接去拷贝这个输入框的命令

原来如此。  以为点OK就是关闭弹框而已。

**Comment by Fndroid** [comment]
我下个版本改一下术语

**Comment by xlsfs** [comment]
原来如此。

**Comment by yurenchen000** [comment]
> 同样的问题，很多个版本之前就这样了。 能不能修复一下呢 感谢

> 这里的意思是点”OK“这个按钮的时候把转换后的命令复制到剪贴板，不是直接去拷贝这个输入框的命令

@Fndroid 

maybe it feels better if preview the final content (%mixedPort% replaced with real value) ?
