### ISSUE TITLE
[Bug]: 挂着clash打某网络游戏总是会导致一些网络bug

### ISSUE THREAD

**Issue by dbsxdbsx** [Fndroid/clash_for_windows_pkg#4494]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.24

### 操作系统

Windows x64

### 系统版本

win10 22h2

### 问题描述

我在挂着clash的tun模式下（其实不是tun模式也有这个问题），打dnf的pk，总是会过一段时间导致---对方打得到我，但我却打不到对方。必须得重启游戏才能解决。

我已经换了2个代理源了，用的rule规则（也就是国内肯定是直连的）。都有这个问题，（也换过电脑了）以下为我的配置：
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/17372655/7c107fb7-435c-47fe-a789-8e061f7237e7)

我推测是否clash每隔一段时间会断掉个1段时间，所以才会导致整个这问题（因为我在打其他实时网络游戏时也会出现某刻突然怪物都“智障”了，然后过了几秒又恢复的情况）

### 复现步骤

win10，不用设置任何系统代理，打开clash 0.20.24，用wegame进入游戏打一会儿pk（大约15分钟）。问题就出现了。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

win10下使用v2rayn就没这问题。

**Comment by yi-Xu-0100** [comment]
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/25523606/0b617893-966c-4ce6-ba4d-d221561d76ed)

设置下这个试试

**Comment by dbsxdbsx** [comment]
> ![image](https://user-images.githubusercontent.com/25523606/241556816-0b617893-966c-4ce6-ba4d-d221561d76ed.png)
> 
> 设置下这个试试

您好，我按照这个配置试了下，还是不行。

然后我又基于你这个配置，把“Break when Profile Change” 去掉，也不行。 然后我又试了这个配置：
![Uploading image.png…]()

还是不行 =_=

**Comment by yi-Xu-0100** [comment]
@dbsxdbsx 应该是None,和全关试试。再不行我也不知道，我一般都不开clash打游戏

**Comment by dbsxdbsx** [comment]
> @dbsxdbsx 应该是None,和全关试试。再不行我也不知道，我一般都不开clash打游戏

就算改成这样还是不行，好吧，那就先这样吧。
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/17372655/560cdc80-f2ee-4cab-98b9-0a05df670c58)
