### ISSUE TITLE
[Bug]: "Follow System Theme" doesn't work on Linux

### ISSUE THREAD

**Issue by Henry8192** [Fndroid/clash_for_windows_pkg#4496]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.24

### 操作系统

Linux

### 系统版本

SteamOS 3.4.6, KDE Plasma Version 5.26.1

### 问题描述

CFW does not follow system dark theme with "Follow System Theme" toggled on.

### 复现步骤

首先使用KDE自带的breeze (light theme)，保证为global theme（下同）。打开CFW with Follow System Theme ON，颜色为白色，正常；
完全退出CFW，在系统设置里选择主题为breeze dark (dark theme)。重新启动CFW，发现主题色仍然为白色，并没有变成黑色。

### 日志文件

<details><summary>logs</summary><p>

```
N/A
```

</p></details>

**Comment by yi-Xu-0100** [comment]
可能那个是Windows的。。。

**Comment by Henry8192** [comment]
我以为linux版本用proton应该会听gtk-theme来着……请问有类似的实现计划嘛

**Comment by Fndroid** [comment]
要上游Electron支持
