### ISSUE TITLE
功能增加建议：只关闭界面进程不关闭内核进程

### ISSUE THREAD

**Issue by VegeHime** [Fndroid/clash_for_windows_pkg#451]
如果没有频繁切换配置的需求 其实主界面没有留在后台的必要
web面板提供的功能也可以满足一定的需求
而且electron程序占用内存稍高 关闭主界面的进程可以节省一定量的内存

**Comment by Fndroid** [comment]
可以直接用clash+ http://clash.razord.top/#/proxies

**Comment by XuuKoo** [comment]
> 
> 
> 可以直接用clash+ http://clash.razord.top/#/proxies

请问下 可以关闭外部控制这个功能吗？感觉不安全。
