### ISSUE TITLE
How to bypass certain domains on linux systems?

### ISSUE THREAD

**Issue by DS-Liu** [Fndroid/clash_for_windows_pkg#4513]
I'm wondering how to bypass certain domains on Linux systems since there's no "System proxy Bypass" in the setting pannel for Clash for Windows on Linux systems like that on [Windows](https://docs.cfw.lbyczf.com/contents/bypass.html#%E8%AE%BE%E7%BD%AE%E6%96%B9%E5%BC%8F), I'm wondering how to bypass a domain on linux systems. The version of Calsh for Windows I'm using is v0.20.22.

**Comment by yi-Xu-0100** [comment]
Electron does not provide a unified system proxy interface for Linux. If you google how to set the system proxy in your system, you should have a bypass setting on the same setting interface.

**Comment by divflex** [comment]
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/99337708/d44f0887-94f3-4fa4-97aa-067e1a8e0180)

最下面
