### ISSUE TITLE
问大家个小问题，怎么让他走PAC? 或者大陆白名单之类的？

### ISSUE THREAD

**Issue by onlyJinx** [Fndroid/clash_for_windows_pkg#452]
我知道有个cfw_pass，但一个一个添加太不实际了，应该有其他办法吧？ 求教一下，谢谢。
![批注 2020-02-25 192827](https://user-images.githubusercontent.com/21324835/75243573-1c3c0e00-5805-11ea-8bb8-50e8fefcb5b2.png)

**Comment by neteroster** [comment]
配置文件中加入规则。

参阅：https://github.com/Dreamacro/clash 中的示例配置文件。

或者选择现成的规则（Google），Others 选择 「Proxy」 即为白名单。

**Comment by leosam1024** [comment]
有做好的
https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/GeneralClashConfig.yml

**Comment by onlyJinx** [comment]
@neteroster @leosam1024 
看了一些文章，Proxy 和 Proxy Group的基本懂了，但有一个还是有点疑问
GEOIP,CN,DIRECT代表的是不是CN的IP就全部直连？
- MATCH,Final代表的是什么?这个Final是我前边我定义的服务器，这MATCH是什么意思?匹配的域名就走Final这个代理吗？按照什么去MATCH?
![批注 2020-02-27 185801](https://user-images.githubusercontent.com/21324835/75438860-b5009400-5993-11ea-938f-e0c203a013f1.png)

**Comment by leosam1024** [comment]
GEOIP 是一个ip数据库，他可以通过域名对应的ip，获得对应的国家。CN是中国的意思。
这句话，代表指向中国地址的ip或者域名 ，走直连

MATCH是兜底匹配。所有上面那些没匹配的，走最后那个策略。

剩下的google一下就行

**Comment by onlyJinx** [comment]
明白了，谢了~
