### ISSUE TITLE
[Feature Request]: TUN模式 进程白名单或者指定地址IP白名单

### ISSUE THREAD

**Issue by xky0007** [Fndroid/clash_for_windows_pkg#4523]
### 功能描述

TUN模式配置目前仅支持对fake-ip-filter内的地址不走tun模式，能否添加功能指定对可执行文件走TUN模式，而非选中的程序默认直连。

或者是指定IP或者域名才走TUN模式。

多谢。

**Comment by Fndroid** [comment]
1. fake-ip-filter 不是不走 TUN ，而是不下发 fake ip
2. TUN 是走 TCP 的，全部行为基于路由表，做不到过滤某个应用，你要绕过 TUN 只能自己添加路由表

**Comment by xky0007** [comment]
> 1. fake-ip-filter 不是不走 TUN ，而是不下发 fake ip
> 2. TUN 是走 TCP 的，全部行为基于路由表，做不到过滤某个应用，你要绕过 TUN 只能自己添加路由表

好的。非常感谢。
