### ISSUE TITLE
[Bug]: [URL:Blacklist]: 安装了Avast，几乎每个半小时左右就会提示拦截了一个属于黑名单的URL。。有大佬能分析一下吗？

### ISSUE THREAD

**Issue by najihua** [Fndroid/clash_for_windows_pkg#4527]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.24

### 操作系统

Windows x64

### 系统版本

Windows 10 专业版

### 问题描述

安装Avast后已经更新过几个版本的clash软件了，每个版本都会每半小时左右就被提示拦截了一个属于黑名单的URL请求，具体URL为：001eddccidfg.jumpbc.chuairan.com，下面是我的截图，有大佬能帮分析一下吗？
![微信图片_20230606200357](https://github.com/Fndroid/clash_for_windows_pkg/assets/17824716/2d2d0336-c6ba-408d-be88-bc92a5ef25a3)
![微信图片_20230606200846](https://github.com/Fndroid/clash_for_windows_pkg/assets/17824716/5b86a209-dfea-45b0-aa7d-10a20fe06e62)

### 复现步骤

电脑安装有Avast防病毒软件，正常使用Clash时就会提示有这样的请求。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by najihua** [comment]
check domain blacklist
![微信图片_20230606202505](https://github.com/Fndroid/clash_for_windows_pkg/assets/17824716/c617f92d-a110-4595-9dbd-3264a80c4d39)

**Comment by yi-Xu-0100** [comment]
所有的网络请求都会过 clash-win64.exe, 可以尝试添加 process-name 规则，logs 级别设置 debug 看看这个请求是哪个软件请求的。

**Comment by najihua** [comment]
经过观察确实发现了其他发起请求的软件，感谢上面回答的兄弟。
