### ISSUE TITLE
请问能否在右键任务栏图标加入 开启/关闭System Proxy 的选项？

### ISSUE THREAD

**Issue by babuf** [Fndroid/clash_for_windows_pkg#453]
因为需经常因为速度切换节点而没有使用rule，所以想右键图标切换开关则无需打开图形界面那么麻烦了。

**Comment by LM-Firefly** [comment]
@babuf 建议使用 ss-win v2rayN

**Comment by Ricardo-Ke** [comment]
强烈建议右键加入 System Proxy 开/关的选项，每次遇到需要临时关闭代理的情景，就必须打开整个界面，很是无奈

**Comment by Fndroid** [comment]
最新版已经有了
