### ISSUE TITLE
[Bug]: TUN 打开后无法使用  电脑直接全部断网 (已解决)

### ISSUE THREAD

**Issue by 972793884** [Fndroid/clash_for_windows_pkg#4536]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.21

### 操作系统

Windows x64

### 系统版本

10

### 问题描述

service mode  地球是绿的
tun mode  启用后电脑直接断网   cpu飙升  软件卡成ppt   关闭tun mode后 电脑恢复正常

### 复现步骤

un mode  启用后电脑直接断网   cpu飙升  软件卡成ppt   关闭tun mode后 电脑恢复正常

### 日志文件

无

### 其他补充

**目前已解决
请先看一下是否与我的环境一致
1.家庭网络/也就是自己在联通移动办的
2.电脑通过网线直接连接光猫(未经过路由器)
3.ip不是公网ip   (cmd  打开  输入ipconfig  ipv4地址是192.168.*.*)

解决办法
1.打开 Allow LAN
2.修改tun mode 配置  -->关闭Auto Detect Interface -->Interface Name 填写   以太网   --->保存**

然后打开 tun mode功能就能正常使用了

**Comment by LiHang941** [comment]
一样script模式也无法使用

**Comment by LiHang941** [comment]
降级正常

**Comment by lonslam** [comment]
今天也遇到了这个问题，折腾了大半天，蛋疼

**Comment by scuyjzh** [comment]
> 

请问你是怎么解决的 我按照楼主的方法还是不行

**Comment by scuyjzh** [comment]
@lonslam

**Comment by lonslam** [comment]
> > 
> 
> 请问你是怎么解决的 我按照楼主的方法还是不行

我是解决之后才看到这个的。我试了很多种方法，还原系统，重置适配器，甚至把系统从win10升到了win11，杀毒软件的断网修复，这些都没有卵用。电脑可以连接上手机的热点，也可以用手机usb共享WiFi，连上网之后重新在笔记本官网下载了驱动，安装上好像就能连上WiFi了。（其实我不确定是不是因为装上驱动的原因，当时还在更新系统）。系统更新重启之后又特么出问题了，连上WiFi，手机热点，手机usb共享都没网，气的差点还原系统或者重装，冷静了下，打开系统的网络诊断，诊断结果是“远程计算机或设备部接受连接”，搜索了一下，按照知乎上的一篇文章解决了问题。这下终于彻底搞定了。

我是右击托盘图标想关闭代理的时候误点到TUN模式的，点了之后，电脑好像不能获取到IPv4地址，解决这个问题应该就能行了，但是路由器是公司的，我不知道在哪，也不能去在路由器上操作啥的，所以折腾了大半天@scuyjzh

**Comment by 972793884** [comment]
如果还是不行  请在  适配器列表里删除   传入连接   那个网卡  也可能叫传入的连接   记不清了 
下面是我删除后的
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/32860073/c2b011d9-6957-4f55-9946-ee06dd127783)

**Comment by 972793884** [comment]
>

**Comment by code1202** [comment]
在网上找了一大圈没有解决，直到看到了题主的方法，非常感谢。题主是英文版的，我再重复下汉化版的路径吧，主页—TUN模式“设置”—关闭左边最下面的“自动检测接口”—接着下面会多出一个手动输入接口名称的地方，这里就是输入你原来宽带连接的名称，比如原来的连接名称是“以太网”，那就输入 以太网 就可以了。
