### ISSUE TITLE
[Bug]: 我使用fog world的clash订阅链接的时候，会出现错误导致无法使用URL下载，导入相应的配置文件的时候也会有同样的错误，错误提示是 无法切换到此配置文件，proxy 0：unsupport proxy type:vless

### ISSUE THREAD

**Issue by lmwzj** [Fndroid/clash_for_windows_pkg#4542]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.25

### 操作系统

Windows x64

### 系统版本

win11

### 问题描述

我使用clash订阅链接的时候，会出现错误导致无法使用URL下载，导入相应的配置文件的时候也会有同样的错误，错误提示是 无法切换到此配置文件，proxy 0：unsupport proxy type:vless。这个问题已经出现好几天了。
![QQ截图20230609201658](https://github.com/Fndroid/clash_for_windows_pkg/assets/134917251/a166b2b8-40da-4063-9107-b72a3ae45de4)

### 复现步骤

拷贝订阅链接，到clash for Windows中使用URL下载，下载之后就会有弹窗提示 无法切换到此配置文件

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by kwanled** [comment]
我在网上下了个clash-meta，重启下和重新导入就好了
