### ISSUE TITLE
无法启动clash core

### ISSUE THREAD

**Issue by gugu-hw** [Fndroid/clash_for_windows_pkg#455]
重装、重启均无效，logs显示如下：
time="2020-02-27T09:43:25+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"

**Comment by UyxD** [comment]
需将config.yml和Country.mmdb放置在软件目录下resources/static/files文件夹中，我这样成功的

**Comment by Fndroid** [comment]
参考这个：https://github.com/Fndroid/clash_for_windows_pkg/issues/445#issuecomment-592308302
