### ISSUE TITLE
[Feature Request]: Adding rules outside of the Profile

### ISSUE THREAD

**Issue by JayCroghan** [Fndroid/clash_for_windows_pkg#4555]
### 功能描述

I want to add all of the following rules to Clash: https://github.com/dler-io/Rules/tree/main/Clash

The problem is when I add them to the Profile, the next time the profile is updated they are all lost. We need a way to add the rules outside of the profile so we can keep the rules when the profile updates.

**Comment by QS0x01** [comment]
https://docs.cfw.lbyczf.com/contents/parser.html
