### ISSUE TITLE
clash报错

### ISSUE THREAD

**Issue by IlO0OlI** [Fndroid/clash_for_windows_pkg#456]
晚上挂机下载，早上起来发现报错。关闭软件并重新打开后正常。
最后一段时间日志如下。
<details>
panic: runtime error: slice bounds out of range [16406:24]

goroutine 64361 [running]:
internal/poll.(*FD).Write(0xc0000b0c80, 0xc0007ba000, 0x18, 0x8000, 0x0, 0x0, 0x0)
	c:/go/src/internal/poll/fd_windows.go:731 +0x450
net.(*netFD).Write(0xc0000b0c80, 0xc0007ba000, 0x18, 0x8000, 0x4016, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:164 +0x56
net.(*conn).Write(0xc0003ac048, 0xc0007ba000, 0x18, 0x8000, 0x0, 0x0, 0x0)
	c:/go/src/net/net.go:196 +0x6f
crypto/tls.(*Conn).write(0xc000072000, 0xc0007ba000, 0x18, 0x8000, 0xc00082f000, 0x2, 0x1000)
	c:/go/src/crypto/tls/conn.go:915 +0x167
crypto/tls.(*Conn).writeRecordLocked(0xc000072000, 0x17, 0xc00082f000, 0x4002, 0x1000, 0x4ffe, 0x4ffe, 0x10)
	c:/go/src/crypto/tls/conn.go:964 +0x2a6
crypto/tls.(*Conn).Write(0xc000072000, 0xc00082b000, 0x4002, 0x5000, 0x0, 0x0, 0x0)
	c:/go/src/crypto/tls/conn.go:1133 +0x1be
github.com/Dreamacro/clash/component/vmess.(*aeadWriter).Write(0xc0004f6000, 0xc000965000, 0x5000, 0x5000, 0x0, 0x0, 0x0)
	C:/golang-projects/clash/component/vmess/aead.go:46 +0x3f4
github.com/Dreamacro/clash/component/vmess.(*Conn).Write(0xc000924000, 0xc000965000, 0x5000, 0x5000, 0x5000, 0x5000, 0x0)
	C:/golang-projects/clash/component/vmess/conn.go:42 +0x59
github.com/Dreamacro/clash/tunnel.(*tcpTracker).Write(0xc000766320, 0xc000965000, 0x5000, 0x5000, 0x5000, 0x0, 0x0)
	C:/golang-projects/clash/tunnel/tracker.go:45 +0x5f
io.copyBuffer(0xfe51d8, 0xc000766320, 0xfe51f8, 0xc0006fc900, 0xc000965000, 0x5000, 0x5000, 0x8c4fa0, 0x0, 0xfe51f8)
	c:/go/src/io/io.go:404 +0x202
io.CopyBuffer(0xfe51d8, 0xc000766320, 0xfe51f8, 0xc0006fc900, 0xc000965000, 0x5000, 0x5000, 0x4, 0x4, 0xc0006a8200)
	c:/go/src/io/io.go:375 +0x89
github.com/Dreamacro/clash/tunnel.relay(0x9b21e0, 0xc0006fc900, 0xfe5180, 0xc000766320)
	C:/golang-projects/clash/tunnel/connection.go:129 +0x1a0
github.com/Dreamacro/clash/tunnel.(*Tunnel).handleSocket(...)
	C:/golang-projects/clash/tunnel/connection.go:113
github.com/Dreamacro/clash/tunnel.(*Tunnel).handleTCPConn(0xc000137650, 0x9b4a00, 0xc0006fc900)
	C:/golang-projects/clash/tunnel/tunnel.go:282 +0x4a9
created by github.com/Dreamacro/clash/tunnel.(*Tunnel).process
	C:/golang-projects/clash/tunnel/tunnel.go:123 +0xe5
</details>

**Comment by Fndroid** [comment]
哪个版本

**Comment by IlO0OlI** [comment]
> 哪个版本

0.8.11

**Comment by taken7** [comment]
我反而想用回0.8.11

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
