### ISSUE TITLE
[Bug]: Rule button

### ISSUE THREAD

**Issue by SadraKhazaei** [Fndroid/clash_for_windows_pkg#4580]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.26

### 操作系统

Windows x64

### 系统版本

Win 11

### 问题描述

in the main interface, the rule button doesn't work!
(in the proxies section, the rule button on top)

### 复现步骤

change between global mode and rule mode.(but not from the system tray. it remains unchanged.)

**Comment by asinitial** [comment]
Same here, the rule button can not be clicked, but the rule proxy works.

**Comment by Fndroid** [comment]
@asinitial  @SadraKhazaei  are you guys using `relay` type proxy groups?

**Comment by zacred0rryn** [comment]
I'm encountering the same issue as them and I'm using `load-balance` proxy groups.

**Comment by ruleroller** [comment]
@Fndroid **Rule** and **Script** are not clickable.  I'm using  load-balance proxy groups.  Back to 0.20.25 now, everything is fine.

**Comment by OOKAMISAMA** [comment]
The same problem has been solved by falling back to 0.20.25.

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.20.27

fixed in 0.20.27

**Comment by OOKAMISAMA** [comment]
> https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.20.27
> 
> fixed in 0.20.27

It has been updated and confirmed that the fix was successful.

**Comment by SadraKhazaei** [comment]
The issue is fixed!
Thank you for your hard work.❤️
