### ISSUE TITLE
[Bug]: 弱弱的问一句，Linux版本的cfw怎么更新啊=.=，是直接解压覆盖原来的文件就可以了吗？

### ISSUE THREAD

**Issue by YirunFantasy** [Fndroid/clash_for_windows_pkg#4583]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.25

### 操作系统

Linux

### 系统版本

Debian 12

### 问题描述

准备升级到0.20.26,因为之前安装service模式很艰难，参照作者之前的回答好不容易安装成功，也在正常使用了，担心覆盖什么的会直接不能使用了，Linux版本cfw该怎么更新呢大佬

### 复现步骤

emm

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by xing-yv** [comment]
> ### 请认真检查以下清单中的每一项
> * [x]  已经搜索过，没有发现类似issue
> * [x]  已经搜索过文档，没有发现相关内容
> * [x]  已经尝试使用过最新版，问题依旧存在
> * [x]  使用的是官方版本（未替换及修改过安装目录程序文件）
> 
> ### 软件版本
> 0.20.25
> 
> ### 操作系统
> Linux
> 
> ### 系统版本
> Debian 12
> 
> ### 问题描述
> 准备升级到0.20.26,因为之前安装service模式很艰难，参照作者之前的回答好不容易安装成功，也在正常使用了，担心覆盖什么的会直接不能使用了，Linux版本cfw该怎么更新呢大佬
> 
> ### 复现步骤
> emm
> 
> ### 日志文件
> logs
> ### 其他补充
> _No response_

可以参考下文档，应该是覆盖data文件夹：
https://docs.cfw.lbyczf.com/contents/7z.html#%E6%9B%B4%E6%96%B0%E8%BD%AF%E4%BB%B6
