### ISSUE TITLE
[Bug]: Clash crash on macOS Sonoma beta2

### ISSUE THREAD

**Issue by ZibYang** [Fndroid/clash_for_windows_pkg#4589]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

Can't open the general page(since the whole app just crash)

### 操作系统

macOS arm64(M1,M1*)

### 系统版本

14.0 Beta (23A5276g)

### 问题描述

When you tap the app on the status bar, it crashes and disappears

### 复现步骤

1. Open the app
2. Tap the app's icon on mac's status bar

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Gunale0926** [comment]
Dev Beta 2独占的bug 我更新后也遇到了

**Comment by suxj22** [comment]
确实，更新dev beta 2后已经无法使用，希望尽快解决

**Comment by daboooooo** [comment]
Clash X Pro 也有同样的问题。启动后可以使用，但是点击图标就自动退出了

**Comment by HeMuling** [comment]
crash后网络无法使用，显示连接不上服务器

**Comment by jeniuslu** [comment]
多次crash恢复了初始配置，这段时间status bar可以正常点击，当加入订阅链接以后再去点icon就开始崩，现在靠着自动选择节点看运气出国了

**Comment by haveagoodday-github** [comment]
You can use v2rayU.

**Comment by ZibYang** [comment]
Clash version 1.116.3 solve the problem, so I am going to close this issue :D
