### ISSUE TITLE
[Wiki]: DNS污染对Clash（for Windows）的影响

### ISSUE THREAD

**Issue by freemedom** [Fndroid/clash_for_windows_pkg#4593]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

Wiki

### 操作系统

Windows x64

### 系统版本

Wiki

### 问题描述

> 都已经可以避免大部分的污染情况，除非污染获得的IP地址是属于CN，即国内的。然而多数情况下，为了保障国内地址的可访问性，这种情况并不多见。

“为了保障国内地址的可访问性，这种情况并不多见。”请教一下这句话是什么意思，对国内地址的访问有什么影响吗

### 复现步骤

[Wiki](https://github.com/Fndroid/clash_for_windows_pkg/wiki/DNS%E6%B1%A1%E6%9F%93%E5%AF%B9Clash%EF%BC%88for-Windows%EF%BC%89%E7%9A%84%E5%BD%B1%E5%93%8D)

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Dyannna** [comment]
这句话要和前文的规则合起来看，首先要确保你已经理解它之前的几句话。这是一个极端简单的例子，意在说明如果即使你之前设置再多的规则，最后的MATCH规则只要设置为Proxy，一般都不会因为DNS污染而无法访问海外网站——例如若假设中国ISP的用户访问Youtube的流量都被指向腾讯，那么对于腾讯来说无异于平白遭受了网络攻击——而实际应用中恰如我们的假设，中国在进行DNS污染时，目标IP通常是Facebook和Twitter两家的，偶尔也会有127.0.0.1这样的，它们的共同点在于在中国大陆境内随意污染不会影响到当地企业和用户的生产生活。

这种方式不会影响你使用中国的服务，但会造成“没有因为被域名规则命中而触发fake-ip”的DNS查询请求被境内DNS服务器记录。不排除有人利用这些记录到的数据来提高特定用户的风险评估值的可能性，最起码一线城市的公安确实在做根据网络帐户发布的言论、人口流动情况、工作单位等信息制作公民风险画像这件事。

**Comment by freemedom** [comment]
> 例如若假设中国ISP的用户访问Youtube的流量都被指向腾讯，那么对于腾讯来说无异于平白遭受了网络攻击——而实际应用中恰如我们的假设，中国在进行DNS污染时，目标IP通常是Facebook和Twitter两家的，偶尔也会有127.0.0.1这样的，它们的共同点在于在中国大陆境内可随意用作虚假目标而不会影响到当地企业和用户的生产生活（如果在经过GFW时一定被reset，那么对这两家也没有影响

懂了，非常感谢
