### ISSUE TITLE
[Bug]: Actons 似乎不能正确工作

### ISSUE THREAD

**Issue by ssyangchn** [Fndroid/clash_for_windows_pkg#4598]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.25

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

参考以下文档，Actions脚本在使用.js文件时，可以通过npm引入第三方模块
[Actions](https://docs.cfw.lbyczf.com/contents/actions.html#%E5%AE%9A%E4%B9%89%E8%A1%8C%E4%B8%BA)

> CFW 调用用户定义的run方法时，会传入 2 个参数，分别是proxy 或 profile 属性，工具类对象/方法
> proxy 或 profile 属性
> payload 是一个对象，表示右键点击的对象
> 
> 工具类对象/方法
> 包括：
> 
> axios：网络请求框架，[GitHub(opens new window)](https://github.com/axios/axios)
> yaml：yaml 框架，[GitHub(opens new window)](https://github.com/eemeli/yaml)
> notify：发出系统通知方法，签名为function notify(title:string, message:string, silent:bool)
> console：日志输出至文件，方便调试，在 Settings 界面中 Actions 设置下方 Console Output 打开
> homeDir：Home Directory 目录
> dialog: 对话框，可以获取用户选择，[Docs(opens new window)](https://www.electronjs.org/zh/docs/latest/api/dialog#dialogshowmessageboxbrowserwindow-options)
> TIP
> 
> 除了以上工具类，在使用.js文件时，也可以通过npm引入第三方模块

我在使用import语句后脚本无法正常运行，请问作者如何正确的引入第三方模块呢？
我的代码如下
```
import fs from 'fs'
module.exports.run = (payload, { dialog,console,fs }) => {
    console.log('get in')
    dialog({
        message: `proxy name: ${payload.name}`
    })

    /*const file = fs.readFileSync('C:\\Users\\Rex\\.config\\clash\\my.yml', 'utf8')
    console.log(YAML.parse(file));*/
}
```
不加import fs from 'fs'时，在节点上点击`run script`可以正常运行，加了后点击无反应

### 复现步骤

如上描述

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
用CommonJS
```js
const fs = require('fs');
```
