### ISSUE TITLE
自定义Rules被托管规则覆盖

### ISSUE THREAD

**Issue by beckyeeky** [Fndroid/clash_for_windows_pkg#46]
每次更新云端服务商的Profile，手动添加的规则就会被覆盖掉。
请问能否分开保存？

**Comment by Fndroid** [comment]
https://github.com/Fndroid/jsbox_script/wiki/%E5%BC%80%E6%94%BE%E6%8E%A5%E5%8F%A3%E4%BD%BF%E7%94%A8%E5%8F%8A%E8%AF%B4%E6%98%8E#clash%E9%85%8D%E7%BD%AE%E4%BF%AE%E6%94%B9
