### ISSUE TITLE
建议优化更新逻辑

### ISSUE THREAD

**Issue by EricBrownz** [Fndroid/clash_for_windows_pkg#460]
便携版更新建议默认下载便携版7z，而不是exe

**Comment by Fndroid** [comment]
已经开启了便携模式了吗？还是只是下载了.7z

**Comment by EricBrownz** [comment]
config.yml和Country.mmdb放置在软件目录下resources/static/files文件夹中这样就是开启便携模式吧，wiki没有外面搜了才知道 :D

**Comment by EricBrownz** [comment]
> 已经开启了便携模式了吗？还是只是下载了.7z

config.yml和Country.mmdb放置在软件目录下resources/static/files文件夹中这样就是开启便携模式吧，wiki没有外面搜了才知道 :D
