### ISSUE TITLE
[Feature Request]:Can sort by delay ?

### ISSUE THREAD

**Issue by hy-allron** [Fndroid/clash_for_windows_pkg#4607]
### 功能描述

Sorting by latency helps to quickly locate the fastest nodes without the need for human eyes. Help improve the user experience. Thank you !

**Comment by jaoyina** [comment]
Settings - Proxies - Order By, select Latency

**Comment by yansheng836** [comment]
> Settings - Proxies - Order By, select Latency

I think it might be better if set to default `Order By Latency`.

@Fndroid @vedantmgoyal2009

**Comment by Guanran928** [comment]
请关闭 Issue。
