### ISSUE TITLE
[提问] 快捷键 ctrl + r 无法重启了

### ISSUE THREAD

**Issue by lengthmin** [Fndroid/clash_for_windows_pkg#461]
上个版本使用 ctrl + r 可以直接重启 clash, 不能用的时候可以刷新一下，现在按这个键已经没有用了。。那要怎么实现快速重启 clash 呢

**Comment by Fndroid** [comment]
点一下General里的标题

**Comment by lengthmin** [comment]
> 点一下General里的标题

好的，谢谢
