### ISSUE TITLE
[Bug]: 每次软件更新后，钉在任务栏的图标，都会消失

### ISSUE THREAD

**Issue by hupo376787** [Fndroid/clash_for_windows_pkg#4611]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.27

### 操作系统

Windows x64

### 系统版本

win11

### 问题描述

每次软件更新后，钉在任务栏的图标，都会消失

### 复现步骤

1. 任务栏钉上图标。
2. 更新软件
3. 看任务栏图标

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
上游electron builder的bug，https://github.com/electron-userland/electron-builder/issues/2514
