### ISSUE TITLE
clash处于打开状态下, 重启电脑, 在没设置开机启动clash, 则上不了网

### ISSUE THREAD

**Issue by Syrea7** [Fndroid/clash_for_windows_pkg#4613]
1. 具体原因应该是clash设置好了系统代理, 但是重启后 , 由于clash并未设置开机启动, 所以在代理没激活的情况下使用了代理, 导致电脑无法联网 .
2.  如何解决 ? 由于关机时clash没有安全退出 , 重启电脑又不想设置clash开机启动. 是否可以加上一个功能 , 设置开机定时任务 ,当 "开机启动"处于激活的时候 , 不进行任何设置, 但是如果处于 "未激活"状态, 则加上一个开机动任务, 清除代理 .  这样就可以在用户不设置开机启动的时候, clash的代理也能随着机器启动而清除, 以此解决启动电脑出现无法联网的情况.
3. 简单点就是 开机启动项加上一个清除代理的功能.

**Comment by Syrea7** [comment]
1. 已经找到解决方法, 可以避免在未关闭代理而关闭电脑导致下次开机无法上网.
2. 
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/50922702/3aa24783-02cc-4474-aaaf-cd6f16018193)
如图, 选择pac就好了.

**Comment by jojo2223** [comment]
感谢，有效
