### ISSUE TITLE
关于让某个程序app不走代理直接直连的续问

### ISSUE THREAD

**Issue by dbsxdbsx** [Fndroid/clash_for_windows_pkg#4615]
本issue是根据[这条](https://github.com/Fndroid/clash_for_windows_pkg/issues/2419#issuecomment-1007878697)的后续疑问：

目前最新的0.20.27，我试了几种不同的mixin写法（其他设置为tun模式）：
1：
```
mixin:
  rules:
    - 'PROCESS-NAME,process.exe,DIRECT'
```
2: 
```
mixin: 
  - 'PROCESS-NAME,process.exe,DIRECT'
```
3:
```
- PROCESS-NAME,process.exe,DIRECT
```
结果是1使得所有代理都走的直连，而2，3是虽然tun模式正常，但是这个mixin规则却不没生效。（以上每种写法我都是第二行缩进2格）。

另外，若按照[这个](https://github.com/Fndroid/clash_for_windows_pkg/issues/2419#issuecomment-1238932906)的做法，则这个额外规则没有生效。 所以我已经不知该怎么写了。

**Comment by Fndroid** [comment]
不能用mixin设置rules，因为会覆盖所有rules

**Comment by dbsxdbsx** [comment]
> 不能用mixin设置rules，因为会覆盖所有rules

所以暂时这个问题算是无解了咯？
