### ISSUE TITLE
[Bug]: Memory Leak

### ISSUE THREAD

**Issue by 110rever** [Fndroid/clash_for_windows_pkg#4618]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.27

### 操作系统

Windows x64

### 系统版本

11

### 问题描述

It appears that clash-win64 is experiencing significant memory leaks. Specifically, when connected to a WLAN network, if the network connection is accidentally disconnected, there appears to be a significant memory leak when attempting to reconnect.
![Uploading image.png…]()

### 复现步骤

Please use a WLAN network to reproduce the problem if you can.

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by 110rever** [comment]
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/89204813/f0300f83-038d-46c4-8ebe-5203f4150cb0)

**Comment by 110rever** [comment]
Encountered a very serious problem, it seems that it will generate several G log files on the C drive. until the disk is full.
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/89204813/c96af08e-e7cb-4b6a-bd7a-356777f883cb)

**Comment by Fndroid** [comment]
1. disable `Allow LAN`
2. if using TUN Mode, disable `Auto Detect Interface Name`, fill `Interface Name` with `WLAN`

**Comment by 110rever** [comment]
Ok, I will try the solution you suggested.
