### ISSUE TITLE
cfw勾选了开机自启但未生效，开机后可以看到proxysever已经被cfw修改，但是进程里没有，此时也无法访问任何网页，需要手动开启。 

### ISSUE THREAD

**Issue by SakuraAaneru** [Fndroid/clash_for_windows_pkg#462]
如题

之前有过的操作 
为了解决网银控件和WIN10最新版本proxysever上的设置兼容问题，更改过HKCU里的internet settings权限让其只能让administrator完全控制，cfw本身设置为以administrator身份运行。

安全软件用的火绒，开机自启项里火绒显示CFW为允许开机自启

**Comment by Fndroid** [comment]
开机启动是通过注册表``HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run``实现的

**Comment by SakuraAaneru** [comment]
@Fndroid 已解决 卸载cfw后重新安装到系统盘就可以了。

另外在此过程中产生一个新的问题，cfw的卸载程序执行完毕UI提示卸载成功后实际并没有卸载成功，文件数量并没有任何减少，cfw依然可以运行

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
