### ISSUE TITLE
[Bug]:试过全局代理各个国家节点，steam客户端登陆，查登陆IP都显示是香港

### ISSUE THREAD

**Issue by jeamasyang** [Fndroid/clash_for_windows_pkg#4620]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.27

### 操作系统

Windows x64

### 系统版本

21H2

### 问题描述

系统代理和tun模式代理都尝试过，登陆steam客户端都只显示是在香港，但是登陆网页版就能正确识别到代理后的节点地区，例如我选择的是阿根廷节点，登陆steam客户端查询登陆历史是在香港，但是打开网页登陆他就能正确识别到是阿根廷IP。
我就想让steam客户端也能正确被代理，不然客户端购买怕被红信

### 复现步骤

设置代理模式为系统代理，节点选择阿根廷（除香港以外都行），登陆steam客户端查询最近登陆IP记录，会显示IP为香港。steam网页登陆，通过steam最新登陆记录查询就能正常显示是阿根廷IP

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by jeamasyang** [comment]
[2023-07-03-093802.log](https://github.com/Fndroid/clash_for_windows_pkg/files/11932272/2023-07-03-093802.log)

**Comment by palmcivetcn** [comment]
你清除一下dns应该就好了
