### ISSUE TITLE
[Bug]: 我下载安装包之后 解压内容只有uninstallcfw.exe

### ISSUE THREAD

**Issue by yapeng-wyp** [Fndroid/clash_for_windows_pkg#4621]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.0

### 操作系统

Windows x64

### 系统版本

win11

### 问题描述

无法更新版本, 我计划更新到0.20.*版本

### 复现步骤

1. 电脑上卸载clash for windows.
2.  进入 https://github.com/Fndroid/clash_for_windows_pkg/releases 
3. 选取任一win版本的exe文件
4. 双击执行

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yapeng-wyp** [comment]
version :  0.19.10

**Comment by Fndroid** [comment]
下错了安装包，不要下arm64，下最短那个exe

**Comment by yapeng-wyp** [comment]
是下载这个么?
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/84566810/3ac757d1-de0a-4917-9a32-fc240ec627c4)
