### ISSUE TITLE
[Bug]: cfw tray icon bug in win10 (win10下任务栏托盘图标右键点击bug)

### ISSUE THREAD

**Issue by Tsuki0125** [Fndroid/clash_for_windows_pkg#4630]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.27

### 操作系统

Windows x64

### 系统版本

WINDOWS10  22H2 (19045.3086)

### 问题描述

在Windows10 22H2(19045.3086)版本中，右键点击clash for Windows任务栏托盘图标，同时触发了“右键点击cfw”和“右键点击任务栏”的响应。
经过测试bug几乎可以稳定复现（稳定每点击两次就会出现一次）。
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/56633891/6e938fe6-97c3-4c14-a49e-8e232cbdd47d)
注意，此bug在本人另外的win11设备上并未出现，经猜测是与win11和win10任务栏组件改动有关。

### 复现步骤

在Windows10 22H2版本的设备上安装最新版cfw，启动后从折叠的tray中拖拽至任务栏，右键点击，在正常弹出右键菜单一次后，任意点击其他地方关闭菜单，随后再次右键点击一次cfw任务栏图标，即可触发上述的“双击”bug。
cfw exe和zip版本均能复现上述bug。
win11没有出现这个bug。

### 日志文件

<details><summary>logs</summary><p>

```
由于日志文件记录的均为网络相关的log，并未包含本bug相关的日志，因此无需上传
```

</p></details>

### 其他补充

其他选项均默认

**Comment by Fndroid** [comment]
这个应该是上游electron的bug，而且存在很久了还没修

**Comment by Tsuki0125** [comment]
经过测试，CFW0.19.18似乎是Windows10下最后一个不会产生此bug的版本。只能暂时回退版本使用了。
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/56633891/12f74ed1-e7f8-4694-8aee-2aa204e3c148)

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/56633891/c59efc05-a5d2-47a3-a324-257695d0c17c)
