### ISSUE TITLE
[Bug]: 用clash meta 核心无法开启tun

### ISSUE THREAD

**Issue by Filterrr** [Fndroid/clash_for_windows_pkg#4636]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.28

### 操作系统

Windows x64

### 系统版本

10

### 问题描述

用clash meta 核心无法开启tun

### 复现步骤

打开常规无法开启

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by aaron50james** [comment]
me too

**Comment by Innersider** [comment]
自行更换内核后，服务模式安装的Clash Core Service无法识别，如果需要开TUN并且使用Meta内核的话，用管理员权限打开Clash for Windows后可以开启TUN，或者换用Clash Verge。
