### ISSUE TITLE
问一下，在Flatpak商店里的cfw是作者自己上传的包吗？不是被人盗用的吧？

### ISSUE THREAD

**Issue by YirunFantasy** [Fndroid/clash_for_windows_pkg#4641]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.28

### 操作系统

Linux

### 系统版本

debian 12

### 问题描述

![Screenshot_20230710_163722](https://github.com/Fndroid/clash_for_windows_pkg/assets/88962428/9022526a-6bdc-4f6f-8ea2-ff5238a2028f)

地址
[https://flathub.org/zh-Hans/apps/io.github.Fndroid.clash_for_windows](url)

在Flatpak商店里无意间看到 cfw ，作者的名字一样，往下面拉，软件的版本，项目地址什么的也都对，我就想问下是不是作者自己上传的官方包，如果是的话，以后我就用这个了，更新也方便，现在我都是自己手动下载解压覆盖安装新版本的，不太方便

### 复现步骤

😀😀😀😀😀😀😀

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by AkariiinMKII** [comment]
不是 落后当前版本很久了
