### ISSUE TITLE
[Bug]: add firewall rules 失败

### ISSUE THREAD

**Issue by hczhch** [Fndroid/clash_for_windows_pkg#4651]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.28

### 操作系统

Windows x64

### 系统版本

win10企业版 22H2

### 问题描述

![error](https://github.com/Fndroid/clash_for_windows_pkg/assets/7745300/0daa756b-b676-4932-93b1-bb9ab0b3d75b)

### 复现步骤

General -> Clash Core -> add firewall rules

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by AkariiinMKII** [comment]
参考文档内容 notice 2
https://docs.cfw.lbyczf.com/contents/tun.html#windows

**Comment by hczhch** [comment]
![Snipaste_2023-07-21_19-32-20](https://github.com/Fndroid/clash_for_windows_pkg/assets/7745300/edb1502d-5924-45e2-94b3-e1a563ab9df9)
