### ISSUE TITLE
[Bug]: 高内存和CPU占用

### ISSUE THREAD

**Issue by uniform641** [Fndroid/clash_for_windows_pkg#4652]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.28

### 操作系统

Linux

### 系统版本

Debian 12

### 问题描述

从 S1 状态恢复后，在重新连接到 wifi 的过程中，内存和 CPU 占用率快速提升至几乎100%，并保持该状态。
![2023-07-12_21-31-corp](https://github.com/Fndroid/clash_for_windows_pkg/assets/45708157/c39ac872-4489-4ba7-94fa-f07ccf29dcf3)

成功连接 wifi 后，CPU 和内存占用保持较高状态。
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/45708157/cb47d527-f912-4e1a-8fb3-891ea292dbcc)
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/45708157/b5bd7d4d-c45c-444e-a18c-f045eaf65e77)

### 复现步骤

打开clash使其正常工作，睡眠并恢复即可复现问题。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yqf23333** [comment]
同问，版本20.32，Windows下从S0状态唤醒，clash-win64长时间维持占用30-50%

**Comment by uniform641** [comment]
v0.20.33 已解决
