### ISSUE TITLE
[Feature Request]: 公司网络所有节点都是timeout

### ISSUE THREAD

**Issue by BugChang** [Fndroid/clash_for_windows_pkg#4656]
### 功能描述

公司网络目前应该是内网通过转发访问的外网，这种情况需要怎么设置呢，trojan的协议貌似没被屏蔽，但是其他协议全部失效，可能有屏蔽策略？有大佬知道该怎么搞么

**Comment by bigwheat-y** [comment]
我也遇到了同样的问题,突然某天节点就全部timeout了

**Comment by FrozenIU** [comment]
版本v0.20.28，同样遇到了这个问题，上周好好的，这周一来了就全部timeout。同样网络环境下，另外一家的节点就没问题。然后换了4G热点timeout的就都正常了。感觉像是混淆的域名被ban了。

**Comment by BugChang** [comment]
我研究了一下，发现公司自己的DNS服务器会有防火墙，而且是通过域名进行拦截的，所以不管你咋加密什么协议都没用，域名不在白名单直接就会拦住
