### ISSUE TITLE
0.9.0版本TAP的一个问题

### ISSUE THREAD

**Issue by YGdevi** [Fndroid/clash_for_windows_pkg#466]
当使用TAP时会出现一些应用无法联网
![image](https://user-images.githubusercontent.com/21022713/75608501-eebfcf00-5b3a-11ea-8da8-22e099a9db97.png)
经过多次测试 ，不适用TAP 时可以正常访问
![image](https://user-images.githubusercontent.com/21022713/75608517-19aa2300-5b3b-11ea-8189-d9e12eae5a62.png)
使用TAP时，查看链接日志都是正常链接没有错误的，想知道是怎么回事？求解决

**Comment by Fndroid** [comment]
TAP会导致微软的联网检查出现问题，这个暂时无解

**Comment by arietta0820** [comment]
> TAP会导致微软的联网检查出现问题，这个暂时无解

我这边也出现，0.9.0的TAP会导致Exchange服务无法连接O365，这个挺严重的，基本上班就无法用TAP了。

**Comment by Love4Taylor** [comment]
1. 确保 Clash 的 53 监听在 0.0.0.0（ 或者局域网 IP？）
2. 手动将 TAP 网卡 DNS 从 127.0.0.1 修改为 TAP 的地址 10.0.0.1（ 或者局域网 IP？）

目前看起来是 Windows 不认 127.0.0.1 作为 DNS 服务器。
CFW 默认设置的 127.0.0.1 但状态里 IPv4 DNS 服务器那里是空的。
![127.0.0.1 的结果](https://i.imgur.com/lCsurUr.png)

修改为 10.0.0.1 后则一切正常。
![10.0.0.1 的结果](https://i.imgur.com/z1VWnG6.png)

**Comment by Fndroid** [comment]
@Love4Taylor 确定是这个问题导致微软联网检查无法通过吗？

**Comment by Love4Taylor** [comment]
是的，参考：https://support.umbrella.com/hc/en-us/articles/230900948-Umbrella-Roaming-Client-Microsoft-Windows-Limited-Network-Connectivity-Warning-Yellow-Triangle-

**Comment by Fndroid** [comment]
> 是的，参考：https://support.umbrella.com/hc/en-us/articles/230900948-Umbrella-Roaming-Client-Microsoft-Windows-Limited-Network-Connectivity-Warning-Yellow-Triangle-
> 
> 案例：[DNSCrypt/dnscrypt-proxy#878](https://github.com/DNSCrypt/dnscrypt-proxy/issues/878)

这个看起来是解决网络图标显示的问题吧，把DNS改成10.0.0.1之后Office也依然不能联网

**Comment by yanyumihuang** [comment]
> > 是的，参考：https://support.umbrella.com/hc/en-us/articles/230900948-Umbrella-Roaming-Client-Microsoft-Windows-Limited-Network-Connectivity-Warning-Yellow-Triangle-
> > 案例：[DNSCrypt/dnscrypt-proxy#878](https://github.com/DNSCrypt/dnscrypt-proxy/issues/878)
> 
> 这个看起来是解决网络图标显示的问题吧，把DNS改成10.0.0.1之后Office也依然不能联网

可以的，除了dns要改，配置文件中的127.0.0.1也要改为0.0.0.0。微软应该就是判断第一个网卡可不可以联网来做验证的。
![image](https://user-images.githubusercontent.com/26965886/79411665-fac1fc00-7fd5-11ea-88cd-f7c7438c6c94.png)

**Comment by yanyumihuang** [comment]
改两个地方，一个是
![image](https://user-images.githubusercontent.com/26965886/79411695-16c59d80-7fd6-11ea-85c7-fad4b3c95beb.png)
另一个是
![image](https://user-images.githubusercontent.com/26965886/79411717-27761380-7fd6-11ea-9ac1-f316c2882192.png)

**Comment by yanyumihuang** [comment]
经过多次实验，我又回来了，楼上的办法是可行的，但操作完后要看cfw网卡的状态，必须是Internet连接正常才行。如果改为后仍然为无法连接网络，可以重装网卡，然后直接改配置文件和dns改完后重启clash，应该就可以验证了，记住clfw网卡能联网后不能重启clash。正确操作后cfw网卡的状态是下图
![image](https://user-images.githubusercontent.com/26965886/79415982-2b5b6300-7fe1-11ea-85f8-48cc00685288.png)

**Comment by iYato** [comment]
> 1. 确保 Clash 的 53 监听在 0.0.0.0（ 或者局域网 IP？）
> 2. 手动将 TAP 网卡 DNS 从 127.0.0.1 修改为 TAP 的地址 10.0.0.1（ 或者局域网 IP？）
> 
> 目前看起来是 Windows 不认 127.0.0.1 作为 DNS 服务器。
> CFW 默认设置的 127.0.0.1 但状态里 IPv4 DNS 服务器那里是空的。
> ![127.0.0.1 的结果](https://camo.githubusercontent.com/b58ae24dd5ee6a657350880debc568709c503363/68747470733a2f2f692e696d6775722e636f6d2f6c4373757255722e706e67)
> 
> 修改为 10.0.0.1 后则一切正常。
> ![10.0.0.1 的结果](https://camo.githubusercontent.com/b293757bc8515f883a1fcfb1df3a0070e547a54f/68747470733a2f2f692e696d6775722e636f6d2f7a3156576e47362e706e67)

经测试此方法可行

**Comment by Fndroid** [comment]
根据上面各位的线索试出来解决方法了：

1. 把``cfw-tap``网卡首选DNS改为``10.0.0.1``，配置文件将DNS监听在``0.0.0.0``（这个在下个版本0.9.6中会修复，重新``Intall TAP Device``即可生效）
2. 如果使用``fake-ip``模式，要添加``fake-ip-filter``:
  ```yaml 
  dns:
    enable: true
    listen: 0.0.0.0:53
    enhanced-mode: fake-ip
    nameserver:
      - 8.8.8.8
      - 114.114.114.114
    fake-ip-filter:
      - 'dns.msftncsi.com'
      - 'www.msftncsi.com'
      - 'www.msftconnecttest.com'
  ```
3. 或者直接将``fake-ip``模式改为``redir-host``

**Comment by iYato** [comment]
> 根据上面各位的线索试出来解决方法了：
> 
> 
> 
> 1. 把``cfw-tap``网卡首选DNS改为``10.0.0.1``，配置文件将DNS监听在``0.0.0.0``（这个在下个版本0.9.6中会修复，重新``Intall TAP Device``即可生效）
> 
> 2. 如果使用``fake-ip``模式，要添加``fake-ip-filter``:
> 
>   ```yaml 
> 
>   dns:
> 
>     enable: true
> 
>     listen: 0.0.0.0:53
> 
>     enhanced-mode: fake-ip
> 
>     nameserver:
> 
>       - 8.8.8.8
> 
>       - 114.114.114.114
> 
>     fake-ip-filter:
> 
>       - 'dns.msftncsi.com'
> 
>       - 'www.msftncsi.com'
> 
>       - 'www.msftconnecttest.com'
> 
>   ```
> 
> 3. 或者直接将``fake-ip``模式改为``redir-host``

我在 fake-ip 下只用了两个步骤得以解决。
1. 将 dns 监听地址改为 `0.0.0.0:53`
2. 将 cfw-tap 网卡的dns设置为 `10.0.0.1`
最后重启cfw就好，并未设置 fake-ip-filter。

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.6

**Comment by bigbighill** [comment]
> > 根据上面各位的线索试出来解决方法了：
> > 
> > 1. 把`cfw-tap`网卡首选DNS改为`10.0.0.1`，配置文件将DNS监听在`0.0.0.0`（这个在下个版本0.9.6中会修复，重新`Intall TAP Device`即可生效）
> > 2. 如果使用`fake-ip`模式，要添加`fake-ip-filter`:
> > 
> > ```yaml
> > dns:
> > 
> >   enable: true
> > 
> >   listen: 0.0.0.0:53
> > 
> >   enhanced-mode: fake-ip
> > 
> >   nameserver:
> > 
> >     - 8.8.8.8
> > 
> >     - 114.114.114.114
> > 
> >   fake-ip-filter:
> > 
> >     - 'dns.msftncsi.com'
> > 
> >     - 'www.msftncsi.com'
> > 
> >     - 'www.msftconnecttest.com'
> > ```
> > 
> > 
> > 
> > 1. 或者直接将`fake-ip`模式改为`redir-host`
> 
> 我在 fake-ip 下只用了两个步骤得以解决。
> 
> 1. 将 dns 监听地址改为 `0.0.0.0:53`
> 2. 将 cfw-tap 网卡的dns设置为 `10.0.0.1`
> 
> 最后重启cfw就好，并未设置 fake-ip-filter。

这种配置，onedrive 不能连网

**Comment by nekronhuang** [comment]
```
experimental:
  ignore-resolve-fail: true
  interface-name: WLAN
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 8.8.8.8
    - 114.114.114.114
  fake-ip-filter:
    - 'dns.msftncsi.com'
    - 'www.msftncsi.com'
    - 'www.msftconnecttest.com'
```
使用如上配置，或者改redir-host，网卡的dns也设置了，仍然是无访问权限。。。是还好少了什么步骤吗

![image](https://user-images.githubusercontent.com/6133789/79679722-1d088380-823b-11ea-9984-ae3cf440d91a.png)

**Comment by Love4Taylor** [comment]
配置完要重启一次 clash 的。

**Comment by nekronhuang** [comment]
> 配置完要重启一次 clash 的。

恩。。。也重启过N回，本地dns我也清了几遍（虽然不知道有没有用）
