### ISSUE TITLE
到底支不支持linux

### ISSUE THREAD

**Issue by MrLuer** [Fndroid/clash_for_windows_pkg#4663]
### 功能描述

如果支持linux，那安装包为什么还叫clash_for_windows.xxx ？ 
如果支持linux，那安装和配置教程在哪里？

**Comment by wenfangdu** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/3795

**Comment by NMSLOOO** [comment]
“windows”为什么一定就是操作系统呢？

**Comment by zhouxinghong** [comment]
Linux有几个人使用啊！那么喜欢Linux，建议你自己开发一款会更好。

**Comment by MrLuer** [comment]
> Linux有几个人使用啊！那么喜欢Linux，建议你自己开发一款会更好。既然度已经Linux了更加用不着GUI了，直接命令爽翻天

windows我已经有了，linux是在特定开发情景下不得不的一个需求。你个蠢材不明白情况就开喷了

**Comment by freegecko** [comment]
参考教程 https://www.freegecko.com

**Comment by yuansongming** [comment]
1. 下载最新的发行版本和图标

```
wget https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.20.28/Clash.for.Windows-0.20.28-x64-linux.tar.gz
cd Downloads
tar -zxvf Clash.for.Windows-0.20.28-x64-linux.tar.gz
mv 'Clash for Windows-0.20.28-x64-linux' clash-for-windows
cd clash-for-windows
wget https://cdn.jsdelivr.net/gh/Dreamacro/clash@master/docs/logo.png
cd ..
```

2. 移动到程序目录

```
sudo mv clash-for-windows/ /opt
cd /opt/clash-for-windows/
```

3. 创建程序快捷方式

```
sudo vim /usr/share/applications/clash-for-windows.desktop
```

```
[Desktop Entry]
Name=Clash for Windows
Comment=A Windows/macOS/Linux GUI based on Clash and Electron.
Exec=/opt/clash-for-windows/cfw
Icon=/opt/clash-for-windows/logo.png
Type=Application
Categories=Development;
StartupNotify=true
NoDisplay=false
```

**Comment by xuzhi0413** [comment]
linux下载之后一直没有system proxy这个按钮，我下载两个版本了都这样，有人遇到过这问题吗？怎么解决呀

**Comment by NMSLOOO** [comment]
> linux下载之后一直没有system proxy这个按钮，我下载两个版本了都这样，有人遇到过这问题吗？怎么解决呀

为什么不会使用搜索引擎？

**Comment by xuzhi0413** [comment]
> > linux下载之后一直没有system proxy这个按钮，我下载两个版本了都这样，有人遇到过这问题吗？怎么解决呀
> 
> 为什么不会使用搜索引擎？

您为什么一定要用反问跟别人说话呢？您怎么知道我没有搜索过呢？如果您知道解决方案，还请您友善的告诉我

**Comment by wulawu-pk** [comment]
> > > linux下载之后一直没有system proxy这个按钮，我下载两个版本了都这样，有人遇到过这问题吗？怎么解决呀
> > 
> > 
> > 为什么不会使用搜索引擎？
> 
> 您为什么一定要用反问跟别人说话呢？您怎么知道我没有搜索过呢？如果您知道解决方案，还请您友善的告诉我

呃这个在网上还真有教程，我之前用kubuntu的时候试过，可以用的，建议你找下

**Comment by xuzhi0413** [comment]
> > > > linux下载之后一直没有system proxy这个按钮，我下载两个版本了都这样，有人遇到过这问题吗？怎么解决呀
> > > 
> > > 
> > > 为什么不会使用搜索引擎？
> > 
> > 
> > 您为什么一定要用反问跟别人说话呢？您怎么知道我没有搜索过呢？如果您知道解决方案，还请您友善的告诉我
> 
> 呃这个在网上还真有教程，我之前用kubuntu的时候试过，可以用的，建议你找下

好的，谢谢你啦

**Comment by april211** [comment]
支持的啊，用的正爽～

**Comment by xuzhi0413** [comment]
> 动动小手，google 一下，别像个幼儿园的孩子一样张嘴等人喂。
> 
> ![image](https://user-images.githubusercontent.com/119924985/254327244-e757d47c-a678-44e4-a166-eab61fd20e13.png)

谢谢你的建议，但你一定要踩我一脚讽刺我像幼儿园的孩子一样等着别人喂你就能得到快乐是吗

**Comment by NMSLOOO** [comment]
> 

这样是非常快乐的

**Comment by xuzhi0413** [comment]
> > 
> 
> 这样是非常快乐的

哇哦，讽刺别人自己就能非常快乐那现实生活中你得多扭曲多阴暗多需要发泄呀，我很同情你

**Comment by april211** [comment]
谁来关一下这个问题 :rofl:

**Comment by NMSLOOO** [comment]
> > > 
> > 
> > 
> > 这样是非常快乐的
> 
> 哇哦，讽刺别人自己就能非常快乐那现实生活中你得多扭曲多阴暗多需要发泄呀，我很同情你

内心阴暗之人看什么都是阴暗的，我更同情你

**Comment by JunjieWang0528** [comment]
> 1. 下载最新的发行版本和图标
> 
> ```
> cd Downloads
> wget https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.20.28/Clash.for.Windows-0.20.28-x64-linux.tar.gz
> tar -zxvf Clash.for.Windows-0.20.28-x64-linux.tar.gz
> mv 'Clash for Windows-0.20.28-x64-linux' clash-for-windows
> cd clash-for-windows
> wget https://cdn.jsdelivr.net/gh/Dreamacro/clash@master/docs/logo.png
> cd ..
> ```
> 
> 2. 移动到程序目录
> 
> ```
> sudo mv clash-for-windows/ /opt
> ```
> 
> 3. 创建程序快捷方式
> 
> ```
> sudo vim /usr/share/applications/clash-for-windows.desktop
> ```
> 
> ```
> [Desktop Entry]
> Name=Clash for Windows
> Comment=A Windows/macOS/Linux GUI based on Clash and Electron.
> Exec=/opt/clash-for-windows/cfw
> Icon=/opt/clash-for-windows/logo.png
> Type=Application
> Categories=Development;
> StartupNotify=true
> NoDisplay=false
> ```
通过您的方法安装成功！已经通过url导入配置文件，但常规中没有系统代理选项，且不能连接原本被墙的网站，请问怎么解决
![微信图片_20230720032316
![微信图片_20230720032324](https://github.com/Fndroid/clash_for_windows_pkg/assets/51773333/d38fa000-c706-4cd7-9a85-701adc42e393)
](https://github.com/Fndroid/clash_for_windows_pkg/assets/51773333/8c9d0e74-c851-42b4-90ce-39e3c07e4ebf)

**Comment by itstartstosnow** [comment]
喷开发者干嘛，多提供个 Linux 平台很好啊，有人确实想要有 GUI 的 Linux clash （比如我）

安装的话没多少步骤，解压之后就发现可以执行了，可能就没特意写吧…… 

配置选项那些和其他平台一样的，网上找教程或者，自己机场的教程

**Comment by MrLuer** [comment]
> 动动小手，google 一下，别像个幼儿园的孩子一样张嘴等人喂。
> 
> ![image](https://user-images.githubusercontent.com/119924985/254327244-e757d47c-a678-44e4-a166-eab61fd20e13.png)



> 动动小手，google 一下，别像个幼儿园的孩子一样张嘴等人喂。
> 
> ![image](https://user-images.githubusercontent.com/119924985/254327244-e757d47c-a678-44e4-a166-eab61fd20e13.png)

此clash非彼clash，不同仓库版本不同使用方法不同，谷歌来的另个仓库的教程你觉得一定能用吗，看官方仓库的教程这不才是正常操作吗？ 你这种蠢材应该跟抖音上的键盘侠战狼战狗是一类的，反正不管三七二十一都要喷，本质是自卑攻击别人找优越感

**Comment by NMSLOOO** [comment]
非要给你嚼碎了再喂到嘴里是吗？
![1689850208362](https://github.com/Fndroid/clash_for_windows_pkg/assets/32746104/7b5738e5-57d8-45a0-a7c5-4f53d51959af)

**Comment by MrLuer** [comment]
> 非要给你嚼碎了再喂到嘴里是吗？ ![1689850208362](https://user-images.githubusercontent.com/32746104/254860851-7b5738e5-57d8-45a0-a7c5-4f53d51959af.jpg)

蠢材是不认识字 ？

**Comment by NMSLOOO** [comment]
我觉得你还是不要上网了，真的好丢人啊

**Comment by NMSLOOO** [comment]
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/32746104/5b356bcd-db7a-4c4e-8814-0940fe326b27)
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/32746104/6b665f03-6043-419b-9623-4c8a7611eaa6)
天天说别人蠢材的人什么成分？

**Comment by MrLuer** [comment]
> 

我一向不建议巨婴上网，没人强迫你回答，你这种杂种真的令人很不理解，我上面你认识字吗，我说了，需要官方资料，别的资料可能不对口， 真的不理解你这种杂种，别人给你讲道理，你说立场。你这智商回去重上幼儿园吧。别人提问你可以无视就好了，自然有热心人回答，你非要过来喷一喷，你应该就是抖音那种什么都要喷一喷的杂种，实际上就是自卑敏感对不，现实没朋友loser一个，网上自己是最墙强的，别人都是弱智，真尼玛杂种，无法理解的杂种

**Comment by MrLuer** [comment]
> > 此clash非彼clash，不同仓库版本不同使用方法不同，谷歌来的另个仓库的教程你觉得一定能用吗，看官方仓库的教程这不才是正常操作吗？ 你这种蠢材应该跟抖音上的键盘侠战狼战狗是一类的，反正不管三七二十一都要喷，本质是自卑攻击别人找优越感
> 
> 我们一向不建议铸币上网，没有人有义务为你提供帮助，尤其对于除了张嘴啥都不会的人。
> 
> 另外如果没有幼儿园手把手教程就玩不明白，那我建议你还是老实回去用 windows 的好。 别折腾 linux 了，免得给自己添麻烦同时还污染其他人的眼睛。

我一向不建议巨婴上网，没人强迫你回答，你这种杂种真的令人很不理解，我上面你认识字吗，我说了，需要官方资料，别的资料可能不对口， 真的不理解你这种杂种，别人给你讲道理，你说立场。你这智商回去重上幼儿园吧。别人提问你可以无视就好了，自然有热心人回答，你非要过来喷一喷，你应该就是抖音那种什么都要喷一喷的杂种，实际上就是自卑敏感对不，现实没朋友loser一个，网上自己是最墙强的，别人都是弱智，真尼玛杂种，无法理解的杂种

**Comment by NMSLOOO** [comment]
> > > 此clash非彼clash，不同仓库版本不同使用方法不同，谷歌来的另个仓库的教程你觉得一定能用吗，看官方仓库的教程这不才是正常操作吗？ 你这种蠢材应该跟抖音上的键盘侠战狼战狗是一类的，反正不管三七二十一都要喷，本质是自卑攻击别人找优越感
> > 
> > 
> > 我们一向不建议铸币上网，没有人有义务为你提供帮助，尤其对于除了张嘴啥都不会的人。
> > 另外如果没有幼儿园手把手教程就玩不明白，那我建议你还是老实回去用 windows 的好。 别折腾 linux 了，免得给自己添麻烦同时还污染其他人的眼睛。
> 
> 我一向不建议巨婴上网，没人强迫你回答，你这种杂种真的令人很不理解，我上面你认识字吗，我说了，需要官方资料，别的资料可能不对口， 真的不理解你这种杂种，别人给你讲道理，你说立场。你这智商回去重上幼儿园吧。别人提问你可以无视就好了，自然有热心人回答，你非要过来喷一喷，你应该就是抖音那种什么都要喷一喷的杂种，实际上就是自卑敏感对不，现实没朋友loser一个，网上自己是最强的，别人都是弱智，真尼玛杂种，无法理解的杂种

多给自己积点德吧，不为自己也想想你的家人

**Comment by freegecko** [comment]
参考教程：https://hiif.ong/clash
机场：https://www.freegecko.com

**Comment by tmacattank** [comment]
> 

蠢材

**Comment by Gio-2020** [comment]
> > 1. 下载最新的发行版本和图标
> > 
> > ```
> > cd Downloads
> > wget https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.20.28/Clash.for.Windows-0.20.28-x64-linux.tar.gz
> > tar -zxvf Clash.for.Windows-0.20.28-x64-linux.tar.gz
> > mv 'Clash for Windows-0.20.28-x64-linux' clash-for-windows
> > cd clash-for-windows
> > wget https://cdn.jsdelivr.net/gh/Dreamacro/clash@master/docs/logo.png
> > cd ..
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. 移动到程序目录
> > 
> > ```
> > sudo mv clash-for-windows/ /opt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. 创建程序快捷方式
> > 
> > ```
> > sudo vim /usr/share/applications/clash-for-windows.desktop
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > [Desktop Entry]
> > Name=Clash for Windows
> > Comment=A Windows/macOS/Linux GUI based on Clash and Electron.
> > Exec=/opt/clash-for-windows/cfw
> > Icon=/opt/clash-for-windows/logo.png
> > Type=Application
> > Categories=Development;
> > StartupNotify=true
> > NoDisplay=false
> > ```
> 
> 通过您的方法安装成功！已经通过url导入配置文件，但常规中没有系统代理选项，且不能连接原本被墙的网站，请问怎么解决 ![微信图片_20230720032324](https://user-images.githubusercontent.com/51773333/254763038-6f213ed9-6e56-4f6b-9292-d8df6c803374.jpg) ![微信图片_20230720032316](https://user-images.githubusercontent.com/51773333/254763047-5c501fde-cc2f-4bf4-b9e6-eafed15088d1.jpg)

设置里打开mixin, 系统设置代理端口
![938de3a871b6aafe1efb79a58c81709e](https://github.com/Fndroid/clash_for_windows_pkg/assets/65337741/8331c111-7c59-4b2b-8dc0-62ed40e94607)

**Comment by Guanran928** [comment]
请关闭 Issue。
