### ISSUE TITLE
[Feature Request]: Linux 版本是否可以提供一个命令行参数, 比如类似于 --background, 或者 --hidden之类, 支持软件启动时不要弹出窗口。

### ISSUE THREAD

**Issue by SailorCrane** [Fndroid/clash_for_windows_pkg#4674]
### 功能描述

Linux 版本是否可以提供一个命令行参数, 比如类似于 --background, 或者 --hidden之类, 支持软件启动时不要弹出窗口。

场景是我会把这个软件当做开机启动项, 但是开机后它默认跑就足够了, 不要多弹出一个窗口来。（在托盘展示一个图标已经足够了,  托盘支持是目前已经有的）

如果支持后, 我就可以把这个命令选项配置在我的linux startup 配置中。

谢谢。

--------------------------
Is it possible to provide a command line parameter in Linux version,  such as "--background" or "--hidden", to support starting the proxy without displaying a window?

The situation is that I want to set this proxy in startup items, but I prefer it to run silently in the background without popping up a window.(Just display a icon in the icon tray is enought)

Thanks for that.

**Comment by april211** [comment]
试试打开这个？
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/53203590/c36abc42-70cc-4d21-96f0-d40c4ada2401)

**Comment by SailorCrane** [comment]
Thanks, "Silent Start" mode works perfectly for me. 
That's exactly what I want.

**Comment by kingsuperfight** [comment]
楼主，下载下来gz文件后解压缩后 怎么安装怎么启动clash啊 小白求教

**Comment by april211** [comment]
> 楼主，下载下来gz文件后解压缩后 怎么安装怎么启动clash啊 小白求教

可以参考我自己写的更新脚本，如下。

> cd ~/Downloads/
> mv Clash*.tar.gz clash.tar.gz
> sudo rm -rf /opt/clash/
> sudo tar -zxvf clash.tar.gz -C /opt/
> sudo mv /opt/Clash* /opt/clash
> rm -f clash.tar.gz
