### ISSUE TITLE
[Bug]: This version loses the "Copy Domain:Port" function, even if the Detailed mode is turned on.

### ISSUE THREAD

**Issue by lianwensheng** [Fndroid/clash_for_windows_pkg#4675]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.29

### 操作系统

Windows x64

### 系统版本

Windows 11 22H2

### 问题描述

This version loses the "Copy Domain:Port" function, even if the Detailed mode is turned on.

![屏幕截图 2023-07-19 165636](https://github.com/Fndroid/clash_for_windows_pkg/assets/36002202/05afbc47-ddb4-4e75-b315-6f4aee4f2d5e)

![屏幕截图 2023-07-19 165402](https://github.com/Fndroid/clash_for_windows_pkg/assets/36002202/e3f643ea-e500-4ef6-a0d5-99c5f6b4be86)

### 复现步骤

![屏幕截图 2023-07-19 165636](https://github.com/Fndroid/clash_for_windows_pkg/assets/36002202/fd4fbbc1-fcfc-4193-b2ea-a712a9a3ab4d)

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases

By the way, I have moved the copy action to the right-click menu.
