### ISSUE TITLE
[Feature Request]: 建议修改Connections页面的”Pause“和“Close All”按钮为相同的尺寸

### ISSUE THREAD

**Issue by lianwensheng** [Fndroid/clash_for_windows_pkg#4676]
### 功能描述

建议修改Connections页面的”Pause“和“Close All”按钮为相同的尺寸，看起来更协调美观。

![屏幕截图 2023-07-19 173101](https://github.com/Fndroid/clash_for_windows_pkg/assets/36002202/d813f1d4-2ed8-4b0d-b3f2-f478559bc943)

### 其他内容

软件版本
0.20.29

操作系统
Windows x64

系统版本
Windows 11 Pro 22H2

**Comment by Fndroid** [comment]
下个版本调整下，感谢

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
