### ISSUE TITLE
[Bug]:TUN模式下steam商店，社区界面无法打开

### ISSUE THREAD

**Issue by ximohhtl** [Fndroid/clash_for_windows_pkg#4677]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.29

### 操作系统

Windows x64

### 系统版本

win11 专业版 22H2

### 问题描述

当开启TUN模式时steam可以登录但是社区与商店界面无法打开，显示拒绝连接，用系统代理的话可以。网页版也是一样的情况。

### 复现步骤

1.clash中开启TUN 
2.打开steam
3.打开商店或社区

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by gonglixin980926** [comment]
我这也发现了，想问下大佬是咋解决的
