### ISSUE TITLE
[Feature Request]: clash core service 是否能在应用退出后完全退出？

### ISSUE THREAD

**Issue by com314159** [Fndroid/clash_for_windows_pkg#4681]
### 功能描述

<img width="1249" alt="image" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/5378240/bbce5e60-35e9-4867-81a8-9422d8019618">

安装Service Mode以后，即使clash for windows 退出以后，mac的这个进程还存在，除非手工uninstall serivice mod

**Comment by com314159** [comment]
mac 系统

**Comment by Fndroid** [comment]
做不到的，service依赖daemon提权

**Comment by com314159** [comment]
@Fndroid 我有办法手工退出吗？除了界面上的uninstall service 的方法，感觉这个方法好麻烦。 或者不使用Service Mod我可以翻墙成功吗？我试了下不开这个mod 好像不行，或者我方式不对？

**Comment by Fndroid** [comment]
不开service也行，手动在系统网络里设置代理
