### ISSUE TITLE
[Bug]: Could not switch to this profile! initial rule provider error

### ISSUE THREAD

**Issue by liao02** [Fndroid/clash_for_windows_pkg#4684]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

20.25

### 操作系统

Windows x64

### 系统版本

win10家庭版-  22H2   -  19045.2006

### 问题描述

在profiles界面添加连接提示成功，之后选择这个配置的时候报错，导致节点刷新不出来。
![230720](https://github.com/Fndroid/clash_for_windows_pkg/assets/75597448/a4644617-8fb5-4e07-ac31-91ea70899458)

### 复现步骤

一直刷新就是一直报错，但是报错的内容不一样，总体来说都是Could not switch to this profile! initial rule provider （xxxxxx ）error.     括号内的信息不固定，其他内容都是一样的

### 日志文件

日志界面的截图
![logs](https://github.com/Fndroid/clash_for_windows_pkg/assets/75597448/6129148f-b4ed-4c91-92ca-0662f59abd85)

### 其他补充

我看有人说吧电脑连接手机热点就可以获取到节点信息，但是我试了，有的电脑可以有的电脑不可以，求助。谢谢

**Comment by AkariiinMKII** [comment]
clash core拉取provider文件失败 属于core报错 与cfw无关 存在运营商阻断的可能 建议反馈给dler

**Comment by liao02** [comment]
> 冲突核心拉取提供商文件失败属于核心报错与 cfw 无关存在运营商爆发的可能建议反馈给 dler

非常感谢

**Comment by RexLee0929** [comment]
> clash core拉取provider文件失败 属于core报错 与cfw无关 存在运营商阻断的可能 建议反馈给dler

还是有关的,毕竟provider强制直连更新
