### ISSUE TITLE
[Feature Request]: 重新启用 Action 发布到 WinGet

### ISSUE THREAD

**Issue by CoolPlayLin** [Fndroid/clash_for_windows_pkg#4689]
### 功能描述

#4209 已经在 russellbanks/Komac#245 中解决，并已经同步到 winget-releaser 中 ( https://github.com/vedantmgoyal2009/winget-releaser/commit/62a17a536e233bb6c82b2d147cbb1f3d9373939b )，可以重新启用 Action 来继续发布到 WinGet

**Comment by CoolPlayLin** [comment]
@Fndroid

**Comment by Fndroid** [comment]
好👍

**Comment by CoolPlayLin** [comment]
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/96709586/662a24fe-85c2-4f4f-871c-e9b777472f9e)
🤔

**Comment by CoolPlayLin** [comment]
done
