### ISSUE TITLE
增加排序功能请求

### ISSUE THREAD

**Issue by holll** [Fndroid/clash_for_windows_pkg#469]
能不能在检测节点延迟后自动排序，把低延迟的放前面。这样，选择节点的时候会方便很多

**Comment by luanshixiao** [comment]
你可以直接用ursltest模式，自动选择延迟最低节点

**Comment by holll** [comment]
> 你可以直接用ursltest模式，自动选择延迟最低节点

延迟最低的都是高倍率节点，用不起啊

**Comment by luanshixiao** [comment]
> > 你可以直接用ursltest模式，自动选择延迟最低节点
> 
> 延迟最低的都是高倍率节点，用不起啊

subconverter转换订阅，exclude 高倍率节点

**Comment by tea1111980** [comment]
你可以把高倍率节点在代理节点中去掉，不就行了?

**Comment by holll** [comment]
> 你可以把高倍率节点在代理节点中去掉，不就行了?

我就是提个需求，自动模式根本就不好用，每次选择的都不是延迟最低的节点。排序不就是很正常的一个附加功能吗？按延迟高低自动排列，然后用户根据延迟，节点地区，手动选择自己需要的节点

**Comment by jimmygiven** [comment]
你既然觉得它的urltest不准，那就手动测试延迟，然后手动选择一个你觉得不错的节点。你提的需求自身就是矛盾的。

**Comment by holll** [comment]
不，是自动模式不准，不是urltest不准，你没理解我的意思

**Comment by holll** [comment]
> 你既然觉得它的urltest不准，那就手动测试延迟，然后手动选择一个你觉得不错的节点。你提的需求自身就是矛盾的。

不，是自动模式不准，不是urltest不准，你没理解我的意思

**Comment by holll** [comment]
> 你既然觉得它的urltest不准，那就手动测试延迟，然后手动选择一个你觉得不错的节点。你提的需求自身就是矛盾的。

请问你哪里看见我说urltest不准，它检测出来的延迟是正确的，但它不会选择哪个延迟最低的。请认真审题

**Comment by tea1111980** [comment]
你可以这样写，就会自动选择了。


Proxy Group:
- name: AUTO
  type: url-test
  proxies:
        - 
- name: Manual
  type: select
  proxies:
        - AUTO   ## 加入 url-test类型节点的- name: 名称

这样就把延时低的节点，自动选中并使用了。不用你手动来选。

不知道这样写你能否懂？

**Comment by holll** [comment]
> 你可以这样写，就会自动选择了。
> 
> Proxy Group:
> 
> * name: AUTO
>   type: url-test
>   proxies:
>   -
> * name: Manual
>   type: select
>   proxies:
>   - AUTO   ## 加入 url-test类型节点的- name: 名称
> 
> 这样就把延时低的节点，自动选中并使用了。不用你手动来选。
> 
> 不知道这样写你能否懂？

懂是懂，但是这个AUTO模式和自带的AUTO有什么不同吗？如果没有的话，可能不太好使，未知问题，AUTO模式下检测出来的最低延迟节点和proxies中手动点击检测出来的最低延迟节点不同，且根据经验，手动检测出来的节点更符合真实情况

**Comment by holll** [comment]
> 你可以这样写，就会自动选择了。
> 
> ```
> Proxy Group:
> - name: AUTO
>    type: url-test
>     proxies:
>        - HK
>        - TW
>        - JP
> 
> - name: Manual
>    type: select
>    proxies:
>        - AUTO   ## 加入 url-test类型节点的- name: 名称
> 
> 
> 这样就把延时低的节点，自动选中并使用了。不用你手动来选。
> 
> 不知道这样写你能否懂？
> ```

谢谢，解决了，原来自带的那个AUTO模式的选择规则不是我想当然的选择最低延迟

**Comment by tea1111980** [comment]
AUTO这个名称是随意起的，你也可以随意起，要是要注意  type: 的部分，它里面写的是什么，就是什么类型，而name: 这个可以随意起，只要你知道你起的这个名字，对应的type: 是什么就行。

···text
### 第一段
- name: Code1
   type: fallback
    proxies:
       - HK
       - TW
       - JP

### 第二段
- name: Code2
   type: url-test
    proxies:
       - HK
       - TW
       - JP
···

只有Code2 里面，才是你要的类型 即：`url-test` 所以加入手动的name 就是Code2 而不是Code1 因为 `1` 里面的type 为 fallback 而不是你要的 url-test

明白？

**Comment by holll** [comment]
> AUTO这个名称是随意起的，你也可以随意起，要是要注意 type: 的部分，它里面写的是什么，就是什么类型，而name: 这个可以随意起，只要你知道你起的这个名字，对应的type: 是什么就行。
> 
> ···text
> 
> ### 第一段
> * name: Code1
>   type: fallback
>   proxies:
>   - HK
>   - TW
>   - JP
> 
> ### 第二段
> * name: Code2
>   type: url-test
>   proxies:
>   - HK
>   - TW
>   - JP
>   ···
> 
> 只有Code2 里面，才是你要的类型 即：`url-test` 所以加入手动的name 就是Code2 而不是Code1 因为 `1` 里面的type 为 fallback 而不是你要的 url-test
> 
> 明白？

明白，是我自己的问题，fallback写在那里没有反应过来

**Comment by tea1111980** [comment]
你这两个引用，能重新引用一下吗？因为在你引用之前，我改了里面的内容。

**Comment by tea1111980** [comment]
其实这样的写法，不利用代理游戏，因为游戏代理只能单独用一个服务器，而这样代理服务器老是变化的话，游戏方 是要把你踢除游戏的。所以这种自动选择的方法还是适合日常，如果代理游戏的话，就需要select了。

**Comment by holll** [comment]
> 你可以这样写，就会自动选择了。
> 
> ```
> Proxy Group:
> - name: AUTO
>    type: url-test
>     proxies:
>        - HK
>        - TW
>        - JP
> 
> - name: Manual
>    type: select
>    proxies:
>        - AUTO   ## 加入 url-test类型节点的- name: 名称
> 
> 
> 这样就把延时低的节点，自动选中并使用了。不用你手动来选。
> 
> 不知道这样写你能否懂？
> ```

谢谢，解决了，原来自带的那个AUTO模式的选择规则不是我想当然的选择最低延迟

> AUTO这个名称是随意起的，你也可以随意起，要是要注意 type: 的部分，它里面写的是什么，就是什么类型，而name: 这个可以随意起，只要你知道你起的这个名字，对应的type: 是什么就行。
> 
> ```
> ### 第一段
>  - name: Code
>     type: fallback
>      proxies:
>         - HK
>         - TW
>         - JP
> 
> ### 第二段
>  - name: Code
>     type: url-test
>      proxies:
>         - HK
>         - TW
>         - JP
> ```
> 
> 只有第二段 Code 里面，才是你要的类型 即：`url-test` 所以加入手动的name 就是第二段Code 而不是第一段Code 因为 `第一段` 里面的 type (类型) 为 fallback 而不是你要的 url-test
> 
> 明白？
> 这就跟全部都是AUTO 是一样的

谢谢，解决了，原来自带的那个AUTO模式的选择规则不是我想当然的选择最低延迟

**Comment by holll** [comment]
> AUTO这个名称是随意起的，你也可以随意起，要是要注意 type: 的部分，它里面写的是什么，就是什么类型，而name: 这个可以随意起，只要你知道你起的这个名字，对应的type: 是什么就行。
> 
> ```
> ### 第一段
>  - name: Code
>     type: fallback
>      proxies:
>         - HK
>         - TW
>         - JP
> 
> ### 第二段
>  - name: Code
>     type: url-test
>      proxies:
>         - HK
>         - TW
>         - JP
> ```
> 
> 只有第二段 Code 里面，才是你要的类型 即：`url-test` 所以加入手动的name 就是第二段Code 而不是第一段Code 因为 `第一段` 里面的 type (类型) 为 fallback 而不是你要的 url-test
> 
> 明白？
> 这就跟全部都是AUTO 是一样的

谢谢，解决了，原来自带的那个AUTO模式的选择规则不是我想当然的选择最低延迟

**Comment by holll** [comment]
> 其实这样的写法，不利用代理游戏，因为游戏代理只能单独用一个服务器，而这样代理服务器老是变化的话，游戏方 是要把你踢除游戏的。所以这种自动选择的方法还是适合日常，如果代理游戏的话，就需要select了。

感谢提醒，我是日常使用，不怕IP经常变动

**Comment by tea1111980** [comment]
哦对了。你要在AUTO上面加一个
```text
### 上面的部分我就不写了，我只写关键的部分

    - DIRECT
    - AUTO

这样的话，你访问国内网站会先 DIRECT (直连)，如果 直连不通，程序会自动往下面执行 即执行玛AUTO
这样就不会觉得加载国内网站慢了

**Comment by holll** [comment]
> 哦对了。你要在 - AUTO上面加一个
> 
> ```
> ### 上面的部分我就不写了，我只写关键的部分
>  type: select
>    proxies:
>       - DIRECT
>       - AUTO
> 
> 这样的话，你访问国内网站会先 走DIRECT (直连)，如果 直连不通，程序会自动往下面执行 即执行AUTO
> 这样就不会觉得加载国内网站慢了
> ```

这个理解了好一会，不过总算是编写对了

**Comment by Fndroid** [comment]
> 哦对了。你要在 - AUTO上面加一个
> 
> ```text
> 
> ### 上面的部分我就不写了，我只写关键的部分
> 
>  type: select
> 
>    proxies:
> 
>       - DIRECT
> 
>       - AUTO
> 
> 
> 
> 这样的话，你访问国内网站会先 走DIRECT (直连)，如果 直连不通，程序会自动往下面执行 即执行AUTO
> 
> 这样就不会觉得加载国内网站慢了

select是手动选，不会按你说的先直连再auto

**Comment by tea1111980** [comment]
> > 哦对了。你要在 - AUTO上面加一个
> > ```
> > 
> > ### 上面的部分我就不写了，我只写关键的部分
> > 
> >  type: select
> > 
> >    proxies:
> > 
> >       - DIRECT
> > 
> >       - AUTO
> > 
> > 
> > 
> > 这样的话，你访问国内网站会先 走DIRECT (直连)，如果 直连不通，程序会自动往下面执行 即执行AUTO
> > 
> > 这样就不会觉得加载国内网站慢了
> > ```
> 
> select是手动选，不会按你说的先直连再auto

那怎么才能实现这个功能呢?

**Comment by Fndroid** [comment]
最新版已经支持
