### ISSUE TITLE
为什么安装了clash后，开机后不打开clash就上不了网呢

### ISSUE THREAD

**Issue by WilliamNGB** [Fndroid/clash_for_windows_pkg#470]
为什么安装了clash后，开机后不打开clash就上不了网呢

**Comment by MafuyuC** [comment]
也许是win的系统代理没有关闭

**Comment by WilliamNGB** [comment]
> 也许是win的系统代理没有关闭

有什么解决办法吗，还是每次关机前都要手动关闭代理

**Comment by MafuyuC** [comment]
按理说clash有设置关闭事件
如果你确定的确是代理问题的话，可以在windows的任务计划 建立一个 系统启动事件 执行关闭代理
reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ProxyEnable" /d 0 /f
上面这段修改代理开关

**Comment by WilliamNGB** [comment]
> 按理说clash有设置关闭事件
> 如果你确定的确是代理问题的话，可以在windows的任务计划 建立一个 系统启动事件 执行关闭代理
> reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ProxyEnable" /d 0 /f
> 上面这段修改代理开关

谢谢

**Comment by Fndroid** [comment]
软件无法监听关机事件，所以无法在关机时还原系统代理设置

**Comment by orziie** [comment]
观察了一下，ShadowsocksR这个软件在win10中是修改自动代理的配置，关机重启软件没启动，也可以正常上网，clash 是修改的手动代理配置。关机重启后手动代理开关不会变。
