### ISSUE TITLE
[Feature Request]:可以更新到当前软件的目录吗？ 

### ISSUE THREAD

**Issue by 107295472** [Fndroid/clash_for_windows_pkg#4703]
### 功能描述

现在更新后都到C:\Users\Administrator\AppData\Local\Programs 这里了

**Comment by Fndroid** [comment]
应该是有两个目录了，你把两个都卸载了，在安装到想要的地方，更新就会覆盖你安装的目录

**Comment by 107295472** [comment]
是开始用的不是安装版 ，更新后就到默认目录了
