### ISSUE TITLE
公司网络禁了网易云等网站，Global可以访问，但是Rule不行，请问怎么可以在rule的规则里访问网易云呢？

### ISSUE THREAD

**Issue by wangshaojie** [Fndroid/clash_for_windows_pkg#4704]
我不想全局代理，只想在Rule的规则里添加一个可以访问网易云的规则，请问怎么弄啊

**Comment by RinOnCloud** [comment]
Proflies→右键再用的选项→edit→rules里按照上下相似的规则写一条针对music.163.com的
这种方法下载一次profile就会失效，长期使用参考[https://docs.cfw.lbyczf.com/contents/parser.html#版本要求](url)

**Comment by wangshaojie** [comment]
模仿加了一条，但是不行
```
 - 'DOMAIN,music.163.com,DIRECT'
 - 'DOMAIN,v1.dogapi.yachts,DIRECT'
 - 'DOMAIN-SUFFIX,ap.spotify.com,DIRECT'
 - 'DOMAIN-KEYWORD,epochtimes,REJECT'
 ```
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/15683944/aea2ab93-4b8e-4232-a43c-f4e463f5d279)

第一条是我复制后面添加的，保存配置后，还是Global可以访问，Rule无法访问

**Comment by wangshaojie** [comment]
我试图尝试，但是失败了，谢谢
