### ISSUE TITLE
如何控制某个程序exe不走代理

### ISSUE THREAD

**Issue by Gminkra** [Fndroid/clash_for_windows_pkg#4713]
例如Discord.exe，就是想让在规则或者全局模式下，Discord.exe 不能连接

**Comment by AkariiinMKII** [comment]
- PROCESS-NAME,Discord.exe,DIRECT

**Comment by Gminkra** [comment]
> * 进程名称，不和谐.exe，直接



> * 进程名称，不和谐.exe，直接

通过使用文档。我懂了，还是要谢谢你
