### ISSUE TITLE
[Bug]: cfw配置引用外部规则导致读取失败

### ISSUE THREAD

**Issue by jaychoubaby** [Fndroid/clash_for_windows_pkg#4716]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.30

### 操作系统

Windows x64

### 系统版本

Windows 10 专业版

### 问题描述

cfw配置中引用外部规则，初次使用的时候由于需要将每一个引用规则下载到本地，导致每次由于某一个规则无法保存至本地而整个配置加载失败

### 复现步骤

cfw配置中引用外部规则，例如：

`rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400`

### 日志文件

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/26641387/710be30b-4711-4c3c-8c34-ded371e1fd64)

### 其他补充

建议：某一个外部配置规则引用失败不影响整个配置文件的正常加载，待配置加载成功后通过 Providers 菜单功能进行手动处理加载失败的配置文件

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/26641387/464f45cc-7fa3-4dd0-8893-5eea70d815bd)

**Comment by jaychoubaby** [comment]
> 这个报错是 core 抛出的，cfw 无解。
> 
> 
> 
> 不过你可以手动下载文件到 config 文件夹实现偷渡。

我的理解是cfw读取配置中的引用配置逐个下载保存到config文件夹下，只不过只要有一个读取超时或者失败导致整个配置不可用，手动下载文件似乎不可行，因为成功下载到本地之后的配置文件似乎是时间戳文件名，无法对应上

**Comment by ZengHugh** [comment]
老老实实默认规则吧，懒得折腾。

**Comment by AkariiinMKII** [comment]
> > 这个报错是 core 抛出的，cfw 无解。
> > 
> > 
> > 
> > 不过你可以手动下载文件到 config 文件夹实现偷渡。
> 
> 我的理解是cfw读取配置中的引用配置逐个下载保存到config文件夹下，只不过只要有一个读取超时或者失败导致整个配置不可用，手动下载文件似乎不可行，因为成功下载到本地之后的配置文件似乎是时间戳文件名，无法对应上

cfw editor 中 copy URL MD5 然后重命名对应文件

**Comment by jaychoubaby** [comment]
> > > 这个报错是 core 抛出的，cfw 无解。
> > > 不过你可以手动下载文件到 config 文件夹实现偷渡。
> > 
> > 
> > 我的理解是cfw读取配置中的引用配置逐个下载保存到config文件夹下，只不过只要有一个读取超时或者失败导致整个配置不可用，手动下载文件似乎不可行，因为成功下载到本地之后的配置文件似乎是时间戳文件名，无法对应上
> 
> cfw editor 中 copy URL MD5 然后重命名对应文件
> 
> 另外 clash core 下载 provider 文件是不走代理通道的，拉取 github 文件出错属于预期状况，用 fastgit 之类的镜像加速服务就能解决

感谢，已自行部署加速服务解决gfw问题了
