### ISSUE TITLE
选用rule，怎么不绕过本机host

### ISSUE THREAD

**Issue by denghuotongming** [Fndroid/clash_for_windows_pkg#472]
遇到的问题是其他软件激活有联网验证机制，需要在本地host种屏蔽才行，但是挂上clash选用rule，变成都走clash了。怎么才能不绕过本机host？这是clash可以设置还是clash没法绕过，只能改clash的规则？望解答，谢谢！

**Comment by Fndroid** [comment]
删除profile里的dns设置

**Comment by denghuotongming** [comment]
> 删除profile里的dns设置

"cfw-bypass:
  - qq.com
  - music.163.com
  - "*.music.126.net"
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>"
是这个么？我把localhost删了也没用。

**Comment by rain0002009** [comment]
我估摸着把 host里的规则在clash的rule里面也写一遍 不就行了

**Comment by Fndroid** [comment]
- 点Profiles
- 点当前选中配置文件下面的“铅笔”打开文本编辑
- 把里面dns那部分删掉

**Comment by denghuotongming** [comment]
> 我估摸着把 host里的规则在clash的rule里面也写一遍 不就行了

不行，自己加的规则，订阅更新一下就没了呀

**Comment by denghuotongming** [comment]
> 1. 点Profiles
> 2. 点当前选中配置文件下面的“铅笔”打开文本编辑
> 3. 把里面dns那部分删掉

没错呀，我改的就是这个文件，时间戳.yml的这个配置文件嘛？搜了一下里面没关于DNS的呀

**Comment by denghuotongming** [comment]
> 1. 点Profiles
> 2. 点当前选中配置文件下面的“铅笔”打开文本编辑
> 3. 把里面dns那部分删掉

能说明白一点嘛？愚钝！我之前贴的就是您说的那个文件。

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
