### ISSUE TITLE
[Bug]: 无法删除 clash-core-service.exe 这个文件

### ISSUE THREAD

**Issue by fudan4** [Fndroid/clash_for_windows_pkg#4729]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.30

### 操作系统

Windows x64

### 系统版本

Windows 11 22H2

### 问题描述

当我试图删除 "C:\Program Files\Clash for Windows Service" 中的 "clash-core-service.exe" 文件时，弹出提示
操作无法完成，因为文件已在 clash-core-service.exe 打开
请关闭该文件并重试
卸载 "Clash for Windows" 后也会出现这种情况

### 复现步骤

安装完 "Service Mode" 后会发生这种情况，同时无法 Uninstall "Service Mode"

**Comment by ihsgnodoay** [comment]
（版本0.20.32）我下载了 Service Mode 后开启 TUN Mode 并关闭 Auto Detect Interfaceh 后网络会丢失，本地使用 `ping  www.google.com` 命令后成功，但是无法访问网页，卸载 Service Mode 失败，更新到 0.20.32 后其他版本也是这样。

同样无法删除 clash-core-service.exe 这个文件，但是我重新安装 clash 后，使用其他卸载工具卸载 clash 后连同 clash-core-service.exe 卸载了。

当关闭 Service Mode 后网络才会连接，网页也可以打开。

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/50910401/32a25298-1819-4b44-b0e6-1ce89e6c468c)

**Comment by ihsgnodoay** [comment]
> （版本0.20.32）我下载了服务模式后开启TUN模式并关闭自动检测接口后网络会丢失，本地使用后，但是`ping www.google.com`无法访问网页命令，卸载服务模式失败，更新到0.20.32后其他版本也是这样。
> 
> 无法删除clash-core-service.exe这个文件，但是我重新安装clash后，使用其他卸载工具同样卸载clash后将clash-core-service.exe卸载了。
> 
> 当关闭服务模式后网络才会连接，网页也可以打开。
> 
> ![图像](https://user-images.githubusercontent.com/50910401/262576247-32a25298-1819-4b44-b0e6-1ce89e6c468c.png)

**Comment by ihsgnodoay** [comment]
我卸彻底卸载软件后重新安装后解决此问题，按照该链接 https://docs.cfw.lbyczf.com/contents/questions.html#service-mode-%E6%97%A0%E6%B3%95%E5%AE%89%E8%A3%85 重新安装 Service Mode ，然后打开 TUN Mode  不会出现我描述的问题了。

**Comment by fudan4** [comment]
解决了，需要关掉任务管理器里的一项进程
