### ISSUE TITLE
[Bug]: 必须开启 TUN mode 才能联网

### ISSUE THREAD

**Issue by xeuyuuyuex** [Fndroid/clash_for_windows_pkg#4736]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.30

### 操作系统

Windows x64

### 系统版本

10

### 问题描述

最近到国外旅游，不需要使用 Clash 了。但是现在电脑必须打开 Clash 的 TUN mode 才能上网，无论任何浏览器或应用都无法上网。卸载了 Clash 也没用，恳请帮助。

### 复现步骤

只要一关闭 TUN mode，就连不了网。
有无开启 clash 都无关。
有无开启 system proxy 也无关。
必须打开 TUN mode 才能连接网络。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

**TUN 配置如下**
已经尝试 reset 过了

dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback: []
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53

**Comment by BinZJU** [comment]
> 

请问最后怎么解决的？今天也遇到类似问题了，谢谢 @xeuyuuyuex @Fndroid
