### ISSUE TITLE
Allow LAN什么意思？

### ISSUE THREAD

**Issue by denghuotongming** [Fndroid/clash_for_windows_pkg#474]
新人问下Allow LAN什么意思？允许局域网作用是什么？绕过局域网还是啥?

**Comment by updater1234** [comment]
Allow LAN：是否允许局域网代理

**Comment by lvhate** [comment]
> Allow LAN：是否允许局域网代理

愚钝！就是不知道这啥意思，作用是什么呢？

**Comment by updater1234** [comment]
参见：https://ssr.tools/116

**Comment by denghuotongming** [comment]
> 参见：https://ssr.tools/116

感谢

**Comment by GGGIsGGG** [comment]
用来做网关，然后其他设备fq啊

**Comment by updater1234** [comment]
这个issue应该可以关闭了。

**Comment by DamienMM** [comment]
我觉的不能关闭，问题并没有解决

**Comment by yuha0lin** [comment]
是不是意思就是允许同一局域网下的设备通过该设备代理，例如允许手机由局域网内的电脑代理上网，求教
