### ISSUE TITLE
[Bug]: 干净的系统，CLASH会访问奇怪的URL

### ISSUE THREAD

**Issue by NextAbyss** [Fndroid/clash_for_windows_pkg#4741]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.30

### 操作系统

Windows x64

### 系统版本

22621.2070

### 问题描述

重装后的干净系统，用的本地的规则配置，不存在远程订阅等联网行为。CFW会莫名其妙的与奇怪的URL进行通信，请作者严查。
<img width="361" alt="image" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/63849033/dc8cf2fe-2edc-41d4-919f-3188fdf28d0a">
<img width="623" alt="image" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/63849033/d4c3df5a-59ff-4575-aaac-8f55a32a7f02">

### 复现步骤

打开CFW，点击Connections查看连接状态

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
Feedback里的广告图片

**Comment by NextAbyss** [comment]
> Feedback里的广告图片

..............................................
