### ISSUE TITLE
[Bug]: Won't focus on search input

### ISSUE THREAD

**Issue by JerryWn12** [Fndroid/clash_for_windows_pkg#4748]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.31

### 操作系统

Windows x64

### 系统版本

Windows 11 22H2 22621.2070

### 问题描述

On connection tab, click on search won't focus on search input bar, need click twice to type.
The focus is on popup filter panel, maybe?

### 复现步骤

On connection tab, click search, can't input, click again then you can input.

**Comment by JerryWn12** [comment]
Normal behavior should be click once and I can type something.

**Comment by Fndroid** [comment]
I will fix this issue in the next version

**Comment by JerryWn12** [comment]
fixed in 0.20.32
