### ISSUE TITLE
[Bug]: Problem related to the installation package of windows version 

### ISSUE THREAD

**Issue by koishi-daisuki** [Fndroid/clash_for_windows_pkg#4754]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.31

### 操作系统

Windows x64

### 系统版本

Windows 11

### 问题描述

When I download and try to install [this version of the program](https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.20.31/Clash.for.Windows.Setup.0.20.31.arm64.exe)
It tells me that I have installed it successfully, However when I click the button 'open', the system tells me that "we are not able to find Clash for windows.exe". then I look at the folder I installed and find that the only file in this folder is 'Uninstall Clash for windows.exe'. Finally, I downloaded version 0.20.30 and it can be operated successfully. 

### 复现步骤

Download [https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.20.31/Clash.for.Windows.Setup.0.20.31.arm64.exe](https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.20.31/Clash.for.Windows.Setup.0.20.31.arm64.exe)
and try to install it.

### 日志文件

It's not related to logs

**Comment by DotRacel** [comment]
I don't really have **ARM** devices. But I've got a simple question, why are you installing arm64 on your x64 system?

**Comment by koishi-daisuki** [comment]
> I don't really have **ARM** devices. But I've got a simple question, why are you installing arm64 on your x64 system?

It's my problem of using the version of the application mismatched on my device. Thanks for let me know.
