### ISSUE TITLE
[Bug]: TUN模式下仅仅进不去谷歌

### ISSUE THREAD

**Issue by WenlongJiao** [Fndroid/clash_for_windows_pkg#4758]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.31

### 操作系统

Windows x64

### 系统版本

windows 11

### 问题描述

开启TUN模式以后只有谷歌上不了，其他的目前来看都可以，包括youtube ins等等。
但是使用系统代理一切正常。
并且是使用多个订阅文件都有这个问题，感觉不是节点问题。

logs里面显示dial failed

### 复现步骤

正常开启TUN就会出现

### 日志文件

<details><summary>logs</summary><p>

```
16:00:25 WRN [TCP] dial failed error=dial tcp4 10.88.8.8:443: i/o timeout proxy=DIRECT lAddr=198.18.0.1:58567 rAddr=10.88.8.8:443 rule=IPCIDR rulePayload=10.0.0.0/8
```

</p></details>

**Comment by WenlongJiao** [comment]
解决了，不知道什么时候host被篡改了

**Comment by Guanran928** [comment]
请关闭 issue。
