### ISSUE TITLE
[Bug]: url-test没有起到应有的作用

### ISSUE THREAD

**Issue by ra1nbow2000** [Fndroid/clash_for_windows_pkg#4765]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

v0.20.31

### 操作系统

Windows x64

### 系统版本

Windows 10 Ltsc

### 问题描述

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/32125748/4742fc7b-d8d0-4ff8-bd62-12b4a57f86b4)
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/32125748/f91b082a-c2b6-4fa0-bbae-e373e5885303)
如图所示，有两组proxy（url-test是问题组，select是对照组用来表示providers中有多个代理节点且至少有一个可用），按照我的理解url-test理应选择一个延迟最低且可用的节点，但是该组所选节点锚定在了providers的第一个节点（也就是不可用的HK14），且在我设定的60s interval时间中没有发生所选节点的更换。

### 复现步骤

这是我所用的  proxy-groups 配置文件
- name: Final
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: Proxy
    type: select
    proxies:
      - M
      - M-test
  - name: M
    type: select
    use:
      - mesl
  - name: M-test
    type: url-test
    url: 'http://www.google.com'
    interval: 60
    use:
      - mesl

### 日志文件

非网络问题，所以没有相关log

**Comment by dylenala** [comment]
macOS 上也有同样的问题，只默认选择第一个节点，无法自动切换

**Comment by Fndroid** [comment]
provider有设置health check吗

**Comment by dylenala** [comment]
> provider有设置health check吗

谢谢，已解决，原来proxy-providers 里每个集合都要加health check😅

**Comment by ra1nbow2000** [comment]
> provider有设置health check吗

已解决，感谢解答
