### ISSUE TITLE
[咨詢]: 這個感嘆號是什麽意思？

### ISSUE THREAD

**Issue by saodis** [Fndroid/clash_for_windows_pkg#4768]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.31

### 操作系统

Windows x64

### 系统版本

win11 22h2

### 问题描述

這個感嘆號是什麽意思？
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/51149477/b131f1f1-5620-4115-bfc7-a1efb11a71dd)

### 复现步骤

這個感嘆號是什麽意思？

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
有profile定时更新失败了

**Comment by saodis** [comment]
> 有profile定时更新失败了

建议鼠标移上去给个提示
