### ISSUE TITLE
[Bug]: 安装服务模式后TUN会导致clash代理无法连接Internet。

### ISSUE THREAD

**Issue by NebulaTechs** [Fndroid/clash_for_windows_pkg#4775]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.31

### 操作系统

Windows x64

### 系统版本

Windows11 22H2

### 问题描述

<img width="642" alt="屏幕截图 2023-08-13 111325" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/126944988/d9ce71eb-d803-4754-a352-4d49b335ecbd">

<p>在我安装了服务模式后仍然显示clash无法访问Internet。</p>

<img width="30" alt="屏幕截图 2023-08-13 111329" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/126944988/e79a0cbd-b4e8-442b-bd80-4e89820c9a8a">

### 复现步骤

安装服务模式，然后启动TUN模式，就会显示：

<img width="30" alt="屏幕截图 2023-08-13 111329" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/126944988/78712b80-c878-40a6-81d7-71c88b2147d7">

### 日志文件

无

### 其他补充

无

**Comment by AquaSimulacra** [comment]
你可以关闭mixin

**Comment by AquaSimulacra** [comment]
你把tunnel删掉重添加就好了

**Comment by AquaSimulacra** [comment]
<img width="846" alt="image" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/98635189/cf464f0d-49fa-4a53-8a86-8606000b771b">

**Comment by AquaSimulacra** [comment]
<img width="585" alt="image" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/98635189/be2e618a-1418-4930-9ae8-f9cfcf9c3ab7">
去设备管理器卸载

**Comment by AkariiinMKII** [comment]
首先，ncsi逻辑混乱是win11体验的一环
其次，![Screenshot_20230814-042027~2.png](https://github.com/Fndroid/clash_for_windows_pkg/assets/6019344/592c8e62-afb0-45e4-9a8c-0570f45646c8)

？

**Comment by myleftface** [comment]
同样的问题，还没有解决

**Comment by mesotescode** [comment]
开启tun模式断流 崩溃的概率比关闭时高很多
