### ISSUE TITLE
到底怎么配置profile才有内容显示

### ISSUE THREAD

**Issue by LING15205** [Fndroid/clash_for_windows_pkg#4776]
买了节点并且导入之后代理的规则里什么也没有，按照#694看到的方法进行了编辑，但仍然无法解决。
事实上我不太清楚我的编辑方法是否正确，粘贴订阅链接是标着API的那个链接是吗……
刷新之后仍然没有看到，重启、重装也无法解决。点击了配置中的节点，然后点击编辑，只能看到一串似乎是按月订阅的语句，并没有可以把什么proxy更改成什么proxies的语句……对不起我是小白……求教感谢！！

**Comment by Sakuzy0** [comment]
看你机场教程

**Comment by LING15205** [comment]
> 看你机场教程

我只看明白了粘贴URL和扫描QR码，手动配置没有详细说明…………

**Comment by LING15205** [comment]
> > 看你机场教程
> 
> 我只看明白了粘贴URL和扫描QR码，手动配置没有详细说明…………

我按照粘贴URL的方式做了但出现了这样的问题orz

**Comment by Sakuzy0** [comment]
最起码给点截图吧 没规则大概率你订阅导入的都是错的

**Comment by LING15205** [comment]
> 最起码给点截图吧 没规则大概率你订阅导入的都是错的

<img width="644" alt="image" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/142154523/5b3b40a4-12ce-48d3-8a9e-c1741c994aff">
我从这里复制了下载链接，然后这样粘贴导入了
<img width="518" alt="image" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/142154523/1e30e65d-2116-4745-99ff-397f37edb683">

**Comment by Sakuzy0** [comment]
> <img alt="image" width="644" src="https://user-images.githubusercontent.com/142154523/260304166-5b3b40a4-12ce-48d3-8a9e-c1741c994aff.png"> 我从这里复制了下载链接，然后这样粘贴导入了 <img alt="image" width="518" src="https://user-images.githubusercontent.com/142154523/260304247-1e30e65d-2116-4745-99ff-397f37edb683.png">
大概率是给v2系用的 没给clash设置专用的，如果你不会手动配置还是订阅转换吧

**Comment by LING15205** [comment]
> 

编辑页面看起来似乎是这样：
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/142154523/b888f86b-7e2e-4dc3-91f3-af207a505d93)

代理只能看到这两个：
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/142154523/12a2fe96-9c53-4deb-bd4d-0a38142a89ea)

规则里什么东西也没有：
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/142154523/6de27bf5-2f52-4eee-99c0-ee8d077a8d8b)

我先是根据作者那个便捷修改尝试了修改，然后又尝试了删掉C盘config并重启重新导入，但是并没有用

**Comment by LING15205** [comment]
> 
感谢……但可以问问怎么订阅转换吗

**Comment by Sakuzy0** [comment]
大概率是给v2系用的 没给clash设置专用的，如果你不会手动配置还是订阅转换吧 谷歌搜订阅转换 靠前的几个都行

**Comment by LING15205** [comment]
> > 
> 
> 感谢……但可以问问怎么订阅转换吗

啊啊感谢我看到了

**Comment by kusiru** [comment]
这个才是订阅把
![Snipaste_2023-08-28_12-25-56](https://github.com/Fndroid/clash_for_windows_pkg/assets/23467939/22008c99-4809-44d7-b731-abc07b3a460c)

**Comment by Fndroid** [comment]
哪买去哪问吧，关了
