### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by whhxmwhh** [Fndroid/clash_for_windows_pkg#478]
订阅已经转换的了.可以访问.填入我们的订阅地址提示网络错误?
![network error捕获](https://user-images.githubusercontent.com/7959854/75730184-212e1f80-5d27-11ea-8a23-e66eda10317a.JPG)

**Comment by whhxmwhh** [comment]
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: Rule
log-level: info
external-controller: '127.0.0.1:9090'
secret: ''

# System proxy will ignore these domains(or ipnet)
cfw-bypass:
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>

# Proxies module latency test settings
cfw-latency-timeout: 3000 # seconds
cfw-latency-url: http://www.gstatic.com/generate_204

# Identify strategy of breaking connections after switching to a new proxy/profile/mode
# Options for proxy: none, chain(proxy group in connection chains), all
# Options for profile: true, false
# Options for mode: true, false
cfw-conn-break-strategy:
  proxy: none
  profile: true
  mode: false

# Run child process after CFW started
# Refer: https://docs.cfw.lbyczf.com/contents/childprocess.html
cfw-child-process: []

# Will be ignored after profile selection
Proxy:
  - name: Shadowsocks
    type: socks5
    server: 127.0.0.1
    port: 1080
Proxy Group:
  - name: Proxy
    type: select
    proxies:
      - Shadowsocks
Rule:
  - 'MATCH,DIRECT'

**Comment by Fndroid** [comment]
可能：
1. 请求超时（20s）
2. 地址被墙

**Comment by whhxmwhh** [comment]
哦。谢谢。有别的方法导入订阅节点或者我通过V2RAYNG导入节点？

**Comment by whhxmwhh** [comment]
问题找到了。我的原来有占用9090端口9091端口。
我要如何来更改端口呢？

**Comment by whhxmwhh** [comment]
是要在my config.yml里修改吗？

**Comment by samwulol** [comment]
同样的问题，不知道怎么搞

**Comment by whhxmwhh** [comment]
![log捕获](https://user-images.githubusercontent.com/7959854/76197115-7fc33400-6226-11ea-8522-88c1ec11e468.JPG)
打开这两两个文件把端口都改为9099就可以了。

**Comment by whhxmwhh** [comment]
> 订阅已经转换的了.可以访问.填入我们的订阅地址提示网络错误?
> ![network error捕获](https://user-images.githubusercontent.com/7959854/75730184-212e1f80-5d27-11ea-8a23-e66eda10317a.JPG)
