### ISSUE TITLE
请问各位大佬有办法设置仅指定的程序走代理吗？

### ISSUE THREAD

**Issue by hsiayuchih** [Fndroid/clash_for_windows_pkg#4781]
### 功能描述

参考了该[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues/4168)按照里面的方式进行了配置后，发现使用的软件仍没有流量通过，不知道是什么原因，我甚至把相关的进程名都添加进去了，但还是没有效果。
![QQ截图20230814233708](https://github.com/Fndroid/clash_for_windows_pkg/assets/21278771/aef2cf61-c961-4501-b7f4-bc02db792fdd)

**Comment by AkariiinMKII** [comment]
注意缩进格式

**Comment by hsiayuchih** [comment]
> 注意缩进格式

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/21278771/d2c98c2d-4863-48c9-ba15-b4467fa17e38)
这样吗？这样也不行

**Comment by JerryWn12** [comment]
更新订阅

**Comment by longxiying** [comment]
> > 注意缩进格式
> 
> ![image](https://user-images.githubusercontent.com/21278771/260618792-d2c98c2d-4863-48c9-ba15-b4467fa17e38.png) 这样也不行

`
parsers: # array
- url: https://********/
  yaml:
    prepend-rules:
      - DOMAIN-SUFFIX,anthropic.com,新加坡01
      - DOMAIN-SUFFIX,openai.com,新加坡01
      - DOMAIN-SUFFIX,claude.ai,新加坡01
`

**Comment by longxiying** [comment]
`parsers: # array
- url: https://efanyun.me/clash/253194/jL0v4cjNaE/
  yaml:
    prepend-rules:
      - DOMAIN-SUFFIX,anthropic.com,新加坡01
      - DOMAIN-SUFFIX,openai.com,新加坡01
      - DOMAIN-SUFFIX,claude.ai,新加坡01`

**Comment by flyfanc** [comment]
开启系统代理才有效

**Comment by hsiayuchih** [comment]
> 开启系统代理才有效，可能还要开tun mode
