### ISSUE TITLE
[Bug]: “允许局域网连接”会允许来自广域网的访问

### ISSUE THREAD

**Issue by ywdncn** [Fndroid/clash_for_windows_pkg#4782]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.31

### 操作系统

Windows x64

### 系统版本

Windows 11 22621.2134

### 问题描述

打开“允许局域网连接”后会允许广域网访问，导致代理被盗用

如果这是预期行为，请将“允许局域网访问”改为“允许其它主机访问”，只有设备网卡所属的 CIDR 才属于局域网，用局域网称呼会造成误解

### 复现步骤

在主界面打开“允许局域网连接”

**Comment by AirportR** [comment]
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/104753221/6222e4da-6c6e-411f-a19b-8babca7f2957)
它写的是 "Allow LAN" ，并没有找到 “允许局域网连接” 相关字样哦。

**Comment by AkariiinMKII** [comment]
![Screenshot_20230814-042027~2.png](https://github.com/Fndroid/clash_for_windows_pkg/assets/6019344/592c8e62-afb0-45e4-9a8c-0570f45646c8)
？

**Comment by ywdncn** [comment]
> ![image](https://user-images.githubusercontent.com/104753221/260611605-6222e4da-6c6e-411f-a19b-8babca7f2957.png) 它写的是 "Allow LAN" ，并没有找到 “允许局域网连接” 相关字样哦。

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/133489883/d022cca5-a783-4fdb-9768-61882660ed71)

**Comment by ywdncn** [comment]
> ![Screenshot_20230814-042027~2.png](https://user-images.githubusercontent.com/6019344/260325447-592c8e62-afb0-45e4-9a8c-0570f45646c8.png) ？



> ![Screenshot_20230814-042027~2.png](https://user-images.githubusercontent.com/6019344/260325447-592c8e62-afb0-45e4-9a8c-0570f45646c8.png) ？

抬杠？要不要我去翻翻词典告诉你 Allow LAN 是什么意思？

**Comment by Fndroid** [comment]
自己写bind address

**Comment by AkariiinMKII** [comment]
> > ![Screenshot_20230814-042027~2.png](https://user-images.githubusercontent.com/6019344/260325447-592c8e62-afb0-45e4-9a8c-0570f45646c8.png) ？
> 
> 抬杠？要不要我去翻翻词典告诉你 Allow LAN 是什么意思？

看看主板网口上标的什么？

**Comment by caiysmy** [comment]
你有公网ip，开了dmz
