### ISSUE TITLE
[Bug]: [GeolP]无法解码地理数据文件

### ISSUE THREAD

**Issue by beyondth** [Fndroid/clash_for_windows_pkg#4796]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

Clash for Windows V0.20.32

### 操作系统

Windows x64

### 系统版本

11

### 问题描述

内核替换成了Clash.Meta，一直用得好好的，打开突然不能用了，切换配置时显示这个：
rules[35] (GEOIP,microsoft, Microsoft] error: [GeolP] failed to decode geodata file:
GeolP.dat, base error: country code microsoft not found in GeolP.dat

配置文件里有这一段：
geodata-mode: true
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"

### 复现步骤

不知道

**Comment by Fndroid** [comment]
？
