### ISSUE TITLE
0.5.9 错误日志，导致代理失效

### ISSUE THREAD

**Issue by xj90512** [Fndroid/clash_for_windows_pkg#48]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x525b9a]

goroutine 227 [running]:
github.com/Dreamacro/clash/constant.(*Metadata).String(0xc00021c840, 0xc0001c4bd0, 0xc0001c8c17)
	/home/travis/gopath/src/github.com/Dreamacro/clash/constant/metadata.go:44 +0x3a
github.com/Dreamacro/clash/tunnel.(*Tunnel).match(0xc0000ae4b0, 0xc00021c840, 0x0, 0x0)
	/home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:160 +0x285
github.com/Dreamacro/clash/tunnel.(*Tunnel).handleConn(0xc0000ae4b0, 0x8e4be0, 0xc0002d86a0)
	/home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:133 +0x405
created by github.com/Dreamacro/clash/tunnel.(*Tunnel).process
	/home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:88 +0x9a

**Comment by Fndroid** [comment]
是不是新建了没有节点的策略组？

**Comment by xj90512** [comment]
我把proxy group重新配置后，几分钟后依然报错
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x525b9a]

goroutine 266 [running]:
github.com/Dreamacro/clash/constant.(*Metadata).String(0xc0002b4280, 0xc0002c6510, 0xc0002ca3c7)
	/home/travis/gopath/src/github.com/Dreamacro/clash/constant/metadata.go:44 +0x3a
github.com/Dreamacro/clash/tunnel.(*Tunnel).match(0xc0000ae4b0, 0xc0002b4280, 0x0, 0x0)
	/home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:160 +0x285
github.com/Dreamacro/clash/tunnel.(*Tunnel).handleConn(0xc0000ae4b0, 0x8e4be0, 0xc0003b6100)
	/home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:133 +0x405
created by github.com/Dreamacro/clash/tunnel.(*Tunnel).process
	/home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:88 +0x9a

**Comment by beyondkmp** [comment]
> 我把proxy group重新配置后，几分钟后依然报错
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x10 pc=0x525b9a]
> 
> goroutine 266 [running]:
> github.com/Dreamacro/clash/constant.(*Metadata).String(0xc0002b4280, 0xc0002c6510, 0xc0002ca3c7)
> /home/travis/gopath/src/github.com/Dreamacro/clash/constant/metadata.go:44 +0x3a
> github.com/Dreamacro/clash/tunnel.(*Tunnel).match(0xc0000ae4b0, 0xc0002b4280, 0x0, 0x0)
> /home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:160 +0x285
> github.com/Dreamacro/clash/tunnel.(*Tunnel).handleConn(0xc0000ae4b0, 0x8e4be0, 0xc0003b6100)
> /home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:133 +0x405
> created by github.com/Dreamacro/clash/tunnel.(*Tunnel).process
> /home/travis/gopath/src/github.com/Dreamacro/clash/tunnel/tunnel.go:88 +0x9a

能给下具体的配置吗？

**Comment by beyondkmp** [comment]
不好意思啊，哈哈。那就是clash的锅的，感觉又是dns的问题

**Comment by Dreamacro** [comment]
@xj90512 是否使用自定义 DNS ?

**Comment by xj90512** [comment]
> 
> 
> @xj90512 是否使用自定义 DNS ? 以及网络状态是否良好，是在离线状态下还是由联网变成离线状态？

dns:
  enable: true
  ipv6: false
  # listen: 0.0.0.0:53
  # enhanced-mode: redir-host
  nameserver:
     - 114.114.114.114
     - 223.5.5.5
     - tls://dns.rubyfish.cn:853 # dns over tls
  fallback: # 与 nameserver 内的服务器列表同时发起请求，当规则符合 GEOIP 在 CN 以外时，fallback 列表内的域名服务器生效。
     - 114.114.114.114
     - tls://dns.rubyfish.cn:853 # dns over tls
     - 8.8.8.8

**Comment by xj90512** [comment]
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: Rule
log-level: info
external-controller: '0.0.0.0:9090'
secret: ''
Proxy: 
- { name: "vmess", type: vmess, server: server, port: 443, uuid: uuid, alterId: 16, cipher: auto }
Proxy Group: 
  - name: Proxy
    type: select
    proxies:
      - vmess
Rule:
  - 'DOMAIN-SUFFIX,google.com,Proxy'
  - 'DOMAIN-KEYWORD,google,Proxy'
  - 'DOMAIN-SUFFIX,ad.com,REJECT'
  - 'GEOIP,CN,DIRECT'
  - 'FINAL,,Proxy'

使用这个配置规则，依然存在这样的问题。

**Comment by xj90512** [comment]
注意清理profiles目录内容！close！
