### ISSUE TITLE
如何正确使用cfw0.9版的tap模式？在设置tap模式中遇到个问题，请教F大

### ISSUE THREAD

**Issue by liangxyz** [Fndroid/clash_for_windows_pkg#480]
请教各位大佬，有人知道如何正确使用cfw的tap模式吗？
我这边按照官网0.9版教程 https://docs.cfw.lbyczf.com/contents/tap.html ，添加dns和experimental:interface-name: net在我的profiles配置里，
现在是有个问题。

就是在我每次开机或者切换profiles或者从休眠唤醒的时候，必须要重新install tap才能连接上，请问有什么办法一直连接的吗？
经过测试发现无法上网的时候，tap网卡有接收数据但是没有发送数据！
请问有什么办法能够自动化或者不需要重新安装就能正常使用tap吗？

这是我按照教程修改的配置文件一部分：
dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:53
  enhanced-mode: fake-ip
  nameserver:
     - 223.5.5.5
experimental:
  interface-name: net

**Comment by liangxyz** [comment]
简单说，就是每次开机或者切换配置，都需要在cfw主界面重新点击install tap才能正常上网！请问有什么办法能够自动化或者不需要重新安装就能正常使用tap吗？

**Comment by pcysanji** [comment]
测试了将近 3 个小时，得到以下情况。

安装虚拟网卡之后，IP 地址和dns 服务器如下
![image](https://user-images.githubusercontent.com/43318710/75798070-043e2e80-5db1-11ea-8d1e-d0a4d45aafc1.png)

当我切换为其他未设置 dns 的配置文件、或退出clash for windows，此时 ip地址和dns服务器照旧。

当我切换回有 dns 设置的配置文件，ip地址和dns服务器就会变成 自动，如下图
![image](https://user-images.githubusercontent.com/43318710/75798396-7b73c280-5db1-11ea-91f7-b8ff6708ab55.png)

这也就导致了 cfw-tap 变成未识别的网络的原因，以致于 TAP 模式无法正常使用。

此时只能选中配置文件，再次安装虚拟网卡，才能 ip地址和dns服务器 的设置才会正常。

此现象在，0.8.11 不会发生。0.8.11 正常使用TAP

**Comment by Fndroid** [comment]
> 当我切换回有 dns 设置的配置文件，ip地址和dns服务器就会变成 自动
这个不是预期行为，我这里无法复现

**Comment by liangxyz** [comment]
> 测试了将近 3 个小时，得到以下情况。
> 
> 安装虚拟网卡之后，IP 地址和dns 服务器如下
> ![image](https://user-images.githubusercontent.com/43318710/75798070-043e2e80-5db1-11ea-8d1e-d0a4d45aafc1.png)
> 
> 当我切换为其他未设置 dns 的配置文件、或退出clash for windows，此时 ip地址和dns服务器照旧。
> 
> 当我切换回有 dns 设置的配置文件，ip地址和dns服务器就会变成 自动，如下图
> ![image](https://user-images.githubusercontent.com/43318710/75798396-7b73c280-5db1-11ea-91f7-b8ff6708ab55.png)
> 
> 这也就导致了 cfw-tap 变成未识别的网络的原因，以致于 TAP 模式无法正常使用。
> 
> 此时只能选中配置文件，再次安装虚拟网卡，才能 ip地址和dns服务器 的设置才会正常。
> 
> 此现象在，0.8.11 不会发生。0.8.11 正常使用TAP。同时我也测试过包含原版 clash内核在内的多款clash编译版，在0.9.0 版本均有此现象。

谢谢大佬测试，我这边手动指定网卡设置以后，发现有接收和发送流量包，但是网页依旧打不开。不清楚什么原因，但只要重新install tap，就能正常。

**Comment by liangxyz** [comment]
> > 当我切换回有 dns 设置的配置文件，ip地址和dns服务器就会变成 自动
> 
> 这个不是预期行为，我这里无法复现

请教F大，我每次开机或切换profiles只能重新install tap才能正常上网是什么原因呢？有没有install tap的bat文件？我想直接丢到启动文件夹。另外我在resources\static\files\tun2socks的文件夹里发现3个bat文件，依次运行依旧没有作用

**Comment by pcysanji** [comment]
> > 当我切换回有 dns 设置的配置文件，ip地址和dns服务器就会变成 自动
> 
> 这个不是预期行为，我这里无法复现

感谢回复。
## 预期行为
 虚拟网卡在关机、关闭cfw或切换配置的操作后，依旧能正常连接。

## 存在问题
 目前情况是，在关机、关闭cfw或切换配置的操作后，需要重新安装 TAP 才能正常连接。

## 推测原因
 在断开cfw-tap并重新加载配置之后，cfw-tab 的ipv4协议的IP和dns都会变成自动。

0.9.0 的TUN无法使用不是个例。
今天我换了一台电脑，重启 clash for windows 后，cfw-tab 是正常的。
这两台电脑从系统和网络环境的基本情况是相似的。

我暂时找不出原因。但是 cfw-tab 的网络在“拔出”和重启后 ID 和 DNS 会变成重置应该不是个例。在 0.8.11 我没有发现这个问题。

**Comment by liangxyz** [comment]
> > 当我切换回有 dns 设置的配置文件，ip地址和dns服务器就会变成 自动
> 
> 这个不是预期行为，我这里无法复现

经过测试，当我切换profiles或者重新开机以后，运行下面2条命令即可正常连接网络：
netsh interface ip set address cfw-tap static 10.0.0.1 255.255.255.0 10.0.0.0

netsh interface ip set dnsservers cfw-tap static address=127.0.0.1

**Comment by liangxyz** [comment]
> > 当我切换回有 dns 设置的配置文件，ip地址和dns服务器就会变成 自动
> 
> 这个不是预期行为，我这里无法复现

我全新安装了win10最新版1909系统，只安装了驱动以后，再次测试clash，发现还是一样的情况，必须要设置tap网卡的ip，网关和dns才能正常上网

**Comment by Fndroid** [comment]
我已经测试过多次了，也没找到必定能触发清除IP/DNS的方法。如果你找到了，请务必告知

**Comment by littlesmilelove** [comment]
```yaml
dns:
   enable: true
   enhanced-mode: fake-ip # 或 redir-host
   listen: 127.0.0.1:53
   nameserver:
      - 223.5.5.5
experimental:
  interface-name: LAN # WLAN 为物理网卡名
```
按照文档进行设置，改了物理网卡名，但是还是无法使用 TAP 模式，一直提示 Dial Error。切换成正常模式是没问题的。求 @Fndroid 大大解答。

**Comment by Material3600** [comment]
我遇到的问题是，电脑从休眠恢复以后，必须重启CFW才能正常使用TAP模式。
我开启TAP模式的方法就是按照文档设置。

**Comment by rain0002009** [comment]
这个tap模式我就没成功过 网络连接 那里 永远显示的都是 网络电缆被拔出
所有的yml文件都都改了一遍了 一点用都没有

**Comment by fanvinga** [comment]
如果你是中文系统.并且使用有线网络.那么interface-name部分应该写成
```
experimental:
  interface-name: '以太网'
```

**Comment by liangxyz** [comment]
> 如果你是中文系统.并且使用有线网络.那么interface-name部分应该写成
> 
> ```
> experimental:
>   interface-name: '以太网'
> ```

我测试前会把网卡名改成net。不过我会测试一下不改名

**Comment by liangxyz** [comment]
> 我已经测试过多次了，也没找到必定能触发清除IP/DNS的方法。如果你找到了，请务必告知

F大你好，我经过一下午的测试，认为已经发现了问题，下面复述下我的测试过程和发现：
1. 有网友告诉我，他从旧版本升级到0.9版，一切正常。所以我重新下载了0.89版的cfw，替换了0.9版cfw的 tun2socks 文件夹里的add_tap_device.bat文件，并按照 https://docs.cfw.lbyczf.com/contents/tap.html 的教程设置了Profile。再点击cfw主页面的install tap，发现可以正常上网，切换profile和重新开机都是正常，但是此时telegram是无法上网的，这符合教程里的0.8.11及以前版本的特征，即如果请求直接使用IP地址而非域名，则不会被发往TAP，例如Telegram。
2.为了进一步探寻原因，我又恢复了cfw 0.9版本的add_tap_device.bat文件，并重新点击cfw主页面的install  tap，这时bug又出现了：切换profile或者重新开机后就无法上网，体现在tap网卡没有发出的数据包，只有在重新运行一个命令后才正常：
`netsh interface ip set address cfw-tap static 10.0.0.1 255.255.255.0 10.0.0.0`
然后我经过仔细对比，终于发现原因了：在cfw 0.9版本，切换profile或者重新开机以后，cfw-tap网卡的网关消失了，取而代之的是DHCP的服务器变成了10.0.0.0 。这样就会导致cfw-tap网卡找不到网关而上网失败！请看截图
![切换profile后不正常连接](https://user-images.githubusercontent.com/8108927/76083922-acd6d300-5fe9-11ea-910a-46c336aa8e06.png)
![正常网络连接](https://user-images.githubusercontent.com/8108927/76083931-b2341d80-5fe9-11ea-813e-dd4317e8a17c.png)

所以我认为，可能是cfw在重启配置的时候，不知道哪里出问题导致tap网卡的默认网关被设置成了dhcp而引起的bug。希望F大你能研究下

**Comment by Fndroid** [comment]
你试试卸载掉，然后安装的时候选择“安装给所有用户”，不要选只安装给自己

**Comment by Fndroid** [comment]
同时，请不要使用管理员权限启动Clash for Windows

**Comment by rain0002009** [comment]
0.8.9->可以打开tap
0.8.11->可以
0.9.0->不行
配置文件我都没删，把0.9.0卸载安装0.8.11一打开马上就连上了
我也试过 只为我安装和为所有人安装，结果 不行的版本就不行，行的版本怎么样都行

**Comment by sunshe35** [comment]
> 这个tap模式我就没成功过 网络连接 那里 永远显示的都是 网络电缆被拔出
> 所有的yml文件都都改了一遍了 一点用都没有

我也是这个样子，不知道什么原因。。。
