### ISSUE TITLE
[Feature Request]: 用户配置文件和`Mixin`中添加对`inbounds`字段的支持

### ISSUE THREAD

**Issue by qiuykv** [Fndroid/clash_for_windows_pkg#4801]
### 功能描述

我目前使用场景是给WSL2设置代理，由于WSL2 IP地址不固定，在Mixin中通过JS获取WSL2网卡的IP地址后，再配置`inbounds`字段.
在`Preview the final configuration file`中已显示该字段配置，但未生效.
![1](https://github.com/Fndroid/clash_for_windows_pkg/assets/142500373/7b1f9c3e-943e-40df-87ab-0283a64b5b83)

(虽然`allow-lan: true`也能解决，但是也会暴露代理给局域网)

### 其他内容

无

**Comment by Fndroid** [comment]
因为inbounds类似general，不会因profile改变而改变
