### ISSUE TITLE
[Bug]: General->Clash Core->Script Test->Fail,error:[object Object]  测试任何规则都是报这个错误

### ISSUE THREAD

**Issue by EllisLiang988** [Fndroid/clash_for_windows_pkg#4804]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

v0.20.32

### 操作系统

Windows x64

### 系统版本

win 11 专业版64位 21H2

### 问题描述

操作步骤:General->Clash Core->播放按钮Script Test->Host输入baidu.com->点击测试按钮->提示:Fail,error:[object Object]  

我再次尝试测试任何其它域名,都是报这个错误.

我试了前面几个旧版本v0.20.30,不会有这个提示,就最新版本v0.20.32提示这个错误.

### 复现步骤

General->Clash Core->Script Test->Host输入baidu.com->点击测试按钮->提示:Fail,error:[object Object]  

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
下个版本修复，感谢反馈

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases
