### ISSUE TITLE
[Feature Request]: 开机启动默认不显示窗口

### ISSUE THREAD

**Issue by luiguangguan** [Fndroid/clash_for_windows_pkg#4806]
### 功能描述

Windows启动后，软件随系统启动会打开窗口。其实一般都是手动关闭窗口，不需要做什么操作。
反而自动启动展示窗口让人不舒服。
所以建议加个设置可以启动后自动关闭窗口。

**Comment by Fndroid** [comment]
<img width="850" alt="image" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/16091562/9a3137b5-f4bf-4718-8473-8bde18d8c143">
