### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by liuzhihai520** [Fndroid/clash_for_windows_pkg#4820]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.32

### 操作系统

Windows x64

### 系统版本

win11 22h2

### 问题描述

我在配置文件中尝试编辑ip白名单失败，提示rules[11] [IP-CIDR,47.242.180.215/3306,DIRECT] error: payload error

<img width="531" alt="微信图片_20230829104220" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/2859095/f2589cdc-1c28-4a0b-8fe4-ac39b1ceb869">

### 复现步骤

点击Profiles编辑配置文件

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
cidr格式错了，/后不是端口

https://aws.amazon.com/what-is/cidr/

**Comment by liuzhihai520** [comment]
感谢你的解答，问题已经解决，谢谢。
