### ISSUE TITLE
[Bug]: 我知道如何设置某个网站走GOLBAL、RULES，但是如何设置某个网站走指定节点的代理？

### ISSUE THREAD

**Issue by wfnian** [Fndroid/clash_for_windows_pkg#4822]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.31

### 操作系统

Windows x64

### 系统版本

Windows 10

### 问题描述

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/18214955/21875948-d08d-401c-ae05-88c6d812185e)
如图所示，我明白第一种方式指定代理类型，如果想某网站走指定的节点（例如日本）该如何设置？

### 复现步骤

None

**Comment by wfnian** [comment]
请问我具体要去哪里设置什么东西？

**Comment by Fndroid** [comment]
你这个2不就是了吗
