### ISSUE TITLE
[Bug]: load-balance模式总是使用相同proxy

### ISSUE THREAD

**Issue by padixa** [Fndroid/clash_for_windows_pkg#4831]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.32

### 操作系统

Windows x64

### 系统版本

Windows 10

### 问题描述

在ProxyGroup中增加了load-balance模式后, 在所有rule中使用该group, 但是访问油管时每次都是相同proxy, 如: sn2--**.youtube.com 或者sn3--**.youtube.com 总是使用[proxy3], 而忽略了其他的proxy, 这就导致无法使用load-balance的轮询来提高速度. 每次只能是相同的proxy, 

我们之所以使用Load-balance不就是希望每次的请求都走proxy-group中的该组proxy中的每一个proxy(轮询方式)吗? url-test没问题的情况下为什么不这样走? 而感觉像是缓存了一样, URL二级/三级域名都不一样, 还一直走同一个proxy. 这就导致没法使用轮询方式走不通proxy之间加速油管视频.....

希望改善该Bug.

### 复现步骤

1.创建很多proxy.
2.创建proxy-group并把所有proxy放进去, 把模式改为:load-balance
3.所有rule都使用该proxy-group
4.油管看视频, 一段时间后无论不通的URL (Clash日志显示:sn2--**.youtube.com 或 sn3--**.youtube.com), 都一直用相同proxy

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
```yaml
type: load-balance
strategy: round-robin
```

**Comment by padixa** [comment]
> ```yaml
> type: load-balance
> strategy: round-robin
> ```

好像确实可以, 麻烦你说一下原理可以吗?  和旧模式的具体区别是什么呢?
