### ISSUE TITLE
[Feature Request]: proxy-group能否让load-balance模式忽略url测试?

### ISSUE THREAD

**Issue by padixa** [Fndroid/clash_for_windows_pkg#4835]
### 功能描述

如果我们确定我们服务器绝对可用的情况下, 在load-balance模式下能否禁止url测试?  这会防止因为url测试时超时或者网络原因导致Clash以为proxy不可用.   

比如直接设置: interval : -1 (不检查url-test) 或者url: none, 然后直接轮询的方式进行load-balance. 它不对该组load-balance进行url检查. 轮询发送请求.

**Comment by padixa** [comment]
特别是每次休眠后启动, 发现那些proxy都变红, 明显网络还没恢复导致url检查测试失败, 结果Clash就开始忽略那些proxy. 还不如禁止.

**Comment by Fndroid** [comment]
clash core issue, refer: https://github.com/Dreamacro/clash/issues
