### ISSUE TITLE
[Feature Request]: 能否自动以管理员身份运行

### ISSUE THREAD

**Issue by muci-u** [Fndroid/clash_for_windows_pkg#4840]
### 功能描述

能不能给CFW增加一个功能，点击图标就可以自动以管理员身份运行。
或者说CFW其实是可以不需要以管理员身份运行的？
现在win10如果不右键以管理员身份运行的话，打开软件也无法访问外网
求大佬解答

**Comment by HHuiLin** [comment]
不是能在属性直接设置？？

**Comment by muci-u** [comment]
> 不是能在属性直接设置？？

之前在属性设置一次可以，但是现在失效了，重装都没用

**Comment by Fndroid** [comment]
不需要管理员运行，且不建议管理员运行

无法访问网络可能要到防火墙里添加放行`安装目录/resources/static/files/win64/clash-win64.exe`（默认第一次会请求允许，可能你拒绝了）

**Comment by muci-u** [comment]
> 不需要管理员运行，且不建议管理员运行
> 
> 无法访问网络可能要到防火墙里添加放行`安装目录/resources/static/files/win64/clash-win64.exe`（默认第一次会请求允许，可能你拒绝了）

<img width="447" alt="image" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/122511579/e5708360-3226-4d4d-a59b-8178c0dd1160">
已经是这样了，算是放行了吗？

不是管理员身份运行的话，可以正常登录其他网站，国外的网站登录不了。

**Comment by Fndroid** [comment]
clash-win64.exe不在就不算

**Comment by muci-u** [comment]
> clash-win64.exe不在就不算

<img width="445" alt="image" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/122511579/d698519b-4bdb-4343-b14b-ad7f768c98ef">
已经设置成这样了，但还是不行。

**Comment by Fndroid** [comment]
看log

**Comment by muci-u** [comment]
> 看log，defender如果没关可能还要加一下排除项
<img width="648" alt="image" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/122511579/58684876-e5d8-45d0-bc80-f4c47ad28e7d">

**Comment by muci-u** [comment]
> 看log，defender如果没关可能还要加一下排除项

安装了火绒，defender关了

**Comment by muci-u** [comment]
> 唉

没办法解决吗？

**Comment by muci-u** [comment]
> 

好的谢谢你。
想问一下你如果没有以管理员运行CFW，可以正常使用吗？

**Comment by muci-u** [comment]
> > 没办法解决吗？
> 
> 你做错事引别人不愉悦了。
> 
> * 使用的是官方版本（未替换及修改过安装目录程序文件）

好的谢谢你。
想问一下你如果没有以管理员运行CFW，可以正常使用吗？
