### ISSUE TITLE
[Bug]: mac端切换或更新订阅导致dns丢失, 已找出复现方法

### ISSUE THREAD

**Issue by GavinAndre** [Fndroid/clash_for_windows_pkg#4841]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.33

### 操作系统

macOS amd64(Intel)

### 系统版本

12.6.3

### 问题描述

mac端切换或更新订阅导致dns丢失, [#3565](https://github.com/Fndroid/clash_for_windows_pkg/issues/3565)该issue中提到过但长时间未解决被关闭了, 估计是找不到复现方法, 但问题确实存在已经能够百分百复现

### 复现步骤

1. 在系统偏好设置-网络中添加两个位置, 比如home和work
2. 位置选择home, 点击高级-dns, 不添加dns
3. 位置选择work, 点击高级-dns, 添加dns, 如223.5.5.5
4. 位置选择home, 打开cfw, 在cfw内安装service mode(如果已经是已安装就先卸载再安装)
5. 位置选择work, 在cfw中切换或更新订阅就可以发现系统偏好设置-网络-高级-dns中设置的223.5.5.5丢失

**Comment by Fndroid** [comment]
> 点general里clash core右边那个芯片按钮看看里面有没有dns和tun的设置

目前只有在设置tun的时候会修改系统dns

**Comment by GavinAndre** [comment]
> > 点general里clash core右边那个芯片按钮看看里面有没有dns和tun的设置
> 
> 目前只有在设置tun的时候会修改系统dns

我复现步骤可能搞复杂了, 精简一下步骤, 位置实际上不用去添加也不用切换, 其实步骤很简单:
1. 网络-高级-dns, 把设置的dns都删除后点ok
2. 在cfw内安装service mode(如果已经是已安装就先卸载再安装)
3. 网络-高级-dns, dns设置223.5.5.5, 添加好后点ok
4. 在cfw中切换或更新订阅就可以发现网络-高级-dns中设置的223.5.5.5丢失

**Comment by GavinAndre** [comment]
> > 点general里clash core右边那个芯片按钮看看里面有没有dns和tun的设置
> 
> 目前只有在设置tun的时候会修改系统dns

我觉得问题在于mac中安装service mode会保存当前网络配置(包括dns), 然后切换订阅会把保存的网络配置覆盖回去, 所以在安装完service mode后对dns进行修改, 然后再切换订阅, 后来设置的dns就丢了

**Comment by Fndroid** [comment]
我意思是你配置文件里如果有配置tun，那么dns被更改是正常的，不然tun就不能正常工作

**Comment by zhangdp** [comment]
> 我意思是你配置文件里如果有配置tun，那么dns被更改是正常的，不然tun就不能正常工作

#4376 这个就是我之前提的bug，确确实实未开启tun模式，但是系统dns被改

**Comment by GavinAndre** [comment]
> 我意思是你配置文件里如果有配置tun，那么dns被更改是正常的，不然tun就不能正常工作

第一没开关tun模式 第二订阅里也没有dns的配置 能麻烦按照我的步骤试下吗 步骤很简单写的也很详细了 试下就能复现出来

**Comment by GavinAndre** [comment]
> 我意思是你配置文件里如果有配置tun，那么dns被更改是正常的，不然tun就不能正常工作

你指的配置文件里有tun是指图里的吗

![Jietu20230908-172825](https://github.com/Fndroid/clash_for_windows_pkg/assets/15795435/48f664e7-075f-457b-a842-cad2dab9c33d)
![Jietu20230908-172848](https://github.com/Fndroid/clash_for_windows_pkg/assets/15795435/12512387-6bfc-4735-89d0-b5ca5a55d13b)

**Comment by GavinAndre** [comment]
> 我意思是你配置文件里如果有配置tun，那么dns被更改是正常的，不然tun就不能正常工作

如果你指的是订阅里的配置 我订阅里也没有tun和dns的配置 但是一切换订阅就是会丢dns

![Jietu20230913-084100](https://github.com/Fndroid/clash_for_windows_pkg/assets/15795435/91f791f6-5040-4fb1-91fd-825828bafc16)
![Jietu20230913-084344](https://github.com/Fndroid/clash_for_windows_pkg/assets/15795435/1c6f44af-1391-479f-9bf5-1de884128207)

**Comment by Fndroid** [comment]
@GavinAndre  看看这个有没有打开
<img width="456" alt="image" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/16091562/b8808b6e-72d9-4548-b035-0d97c5de2863">

<img width="618" alt="image" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/16091562/8dbfc15a-8d94-4a47-9749-99f49154605a">

**Comment by GavinAndre** [comment]
> @GavinAndre 看看这个有没有打开 <img alt="image" width="456" src="https://user-images.githubusercontent.com/16091562/267552274-b8808b6e-72d9-4548-b035-0d97c5de2863.png">
> 
> <img alt="image" width="618" src="https://user-images.githubusercontent.com/16091562/267552345-8dbfc15a-8d94-4a47-9749-99f49154605a.png">

是没打开的

![Jietu20230913-173628](https://github.com/Fndroid/clash_for_windows_pkg/assets/15795435/ab94fec5-1979-4125-a2c6-c91be53233ec)

**Comment by Fndroid** [comment]
0.20.36调整了一下，可以试试看还有没问题

**Comment by GavinAndre** [comment]
> 0.20.36调整了一下，可以试试看还有没问题

试过了 已经修复了 感谢

**Comment by GavinAndre** [comment]
@zhangdp 0.20.36版本修复了
