### ISSUE TITLE
[Bug]: macbook换了clash meta内核后直接不能用了

### ISSUE THREAD

**Issue by cengzhijie3** [Fndroid/clash_for_windows_pkg#4842]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### General界面截图

<img width="941" alt="截圖 2023-09-07 下午12 16 19" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/89333400/afa2849a-6a88-474d-8bb7-64010021ebd2">

### 操作系统

macOS arm64(M1,M1*)

### 系统版本

latest

### 问题描述

macbook换了clash meta内核后直接不能用了

### 复现步骤

用clash meta安装在macbook上

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
不支持打mod
