### ISSUE TITLE
[Bug]: 不知道为什么，我用的grpc配置的都不能在clash上工作

### ISSUE THREAD

**Issue by cengzhijie3** [Fndroid/clash_for_windows_pkg#4844]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### General界面截图

<img width="530" alt="截圖 2023-09-08 上午10 49 14" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/89333400/3f2cdd36-3515-4d13-9bb1-e31fd0da5e6c">

### 操作系统

macOS arm64(M1,M1*)

### 系统版本

latest

### 问题描述

不知道为什么，我用的grpc配置的都不能在clash上工作，无论是xray grpc还是sing-box grpc reality配置之后都不能运行报错，但在其他客户端可以正常使用，应该是clash自己出问题而不是配置出问题因为我的配置是按照clash官方微博来写的

### 复现步骤

可以试下grpc trojan或vless，能成功导入但运行不了

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
发错repo了吧

**Comment by cengzhijie3** [comment]
> 

你好，我试过多次仍然不能用

**Comment by cengzhijie3** [comment]
> 发错repo了吧

是cfw，它真的不能用grpc的不知道为什么
