### ISSUE TITLE
[Bug]: 0.20.34 fatal crash shortly after launching 

### ISSUE THREAD

**Issue by quantumfallout** [Fndroid/clash_for_windows_pkg#4845]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### General界面截图

无

### 操作系统

Windows x64

### 系统版本

Windows 11 22H2 22621.2215

### 问题描述

Crash on 0.20.34

### 复现步骤

install and run 0.20.34

### 日志文件

No logs were produced at Home Directory/logs and \AppData\Roaming\clash_win\logs

**Comment by Fndroid** [comment]
下错安装包了吧

**Comment by quantumfallout** [comment]
下的是`Clash.for.Windows-0.20.34-win.7z`没错，不过重新下了一遍又好了。
