### ISSUE TITLE
[Bug]: Tun Mode

### ISSUE THREAD

**Issue by Hellonuworld** [Fndroid/clash_for_windows_pkg#4857]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### General界面截图
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/65324115/0a52dc86-d65d-4c2f-b0fb-43957eb10782)

[Inbound]start failed
ERROR Error creating interface: The device is not ready for use.TYPE ->TUN      STACKTYPE-> gvisor     INET->198.18.0.1/16

### 操作系统

Windows x64

### 系统版本

win11

### 问题描述

TUN网卡无法创建，报错如上。
[Inbound]start failed
ERROR Error creating interface: The device is not ready for use.TYPE ->TUN      STACKTYPE-> gvisor     INET->198.18.0.1/16

已尝试替换wintun至最新0.14版本，无效
已github下载最新的cfw版本，0.20.4，无效
已尝试TUN模式改为system, 无效
电脑用的killer网卡，也已关闭killer  control center中的killer prioraztion  engine设置， 无效
    -----killer网卡设置中心菜单比较少，不知道是否还有其他地方可以调整
已尝试config添加tun 规则，无效

另：TAP模式的话可以正确生成虚拟网卡。

你的善良让夜空的星星更加闪耀

### 复现步骤

从未成功运行TUN，
[Inbound]start failed
ERROR Error creating interface: The device is not ready for use.TYPE ->TUN      STACKTYPE-> gvisor     INET->198.18.0.1/16

### 日志文件

<details><summary>logs</summary><p>
15:13:31 ERR [Inbound] start failed error=Error creating interface: The device is not ready for use. type=TUN stackType=gvisor inet=198.18.0.1/16
15:13:46 ERR [Inbound] start failed error=Error creating interface: The device is not ready for use. type=TUN stackType=gvisor inet=198.18.0.1/16
15:14:02 ERR [Inbound] start failed error=Error creating interface: The device is not ready for use. type=TUN stackType=gvisor inet=198.18.0.1/16
15:14:36 ERR [Inbound] start failed error=Error creating interface: The device is not ready for use. type=TUN stackType=gvisor inet=198.18.0.1/16

</p></details>

**Comment by Hellonuworld** [comment]
目前自己曲线救国，走TAP模式

1. service mode卸载原来装的TUN
2. mixin设置里面，加入以下代码
mixin: 
  dns:
    enable: true    
    enhanced-mode: fake-ip
    listen: :53
    nameserver: 
      - 8.8.8.8
      - 119.29.29.29 #腾讯
      - 223.5.5.5 #阿里
3. 开启 mixin

enhance-mode 不知道fake-ip跟 redir-host啥区别，但是使用redir-host就不行

希望可以帮助到有需要的人

愿圣光与你同在

**Comment by zzccoder** [comment]
我也是同样的问题，
12:53:49 ERR [Inbound] start failed error=Error creating interface: The device is not ready for use. type=TUN stackType=gvisor inet=198.18.0.1/16

**Comment by Hellonuworld** [comment]
互联网的互助真的越来越少，大家越来越忙

**Comment by Hellonuworld** [comment]
> 我也是同样的问题， 12:53:49 ERR [Inbound] start failed error=Error creating interface: The device is not ready for use. type=TUN stackType=gvisor inet=198.18.0.1/16

后来有搞定不，不行的话就用我的曲线救国。
