### ISSUE TITLE
[Feature Request]: parser 中的 commands 怎么全匹配下面全部内容进行操作

### ISSUE THREAD

**Issue by chenzhihao1040728129** [Fndroid/clash_for_windows_pkg#4859]
### General界面截图

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/49114216/ef96e23f-9b5c-47ef-a07f-fbba7b616bb9)

### 功能描述

commands:
        - proxies.0.skip-cert-verify=true
        
大佬们您好,  
这行怎么全匹配  proxies 下面的所有 skip-cert-verify ???

**Comment by chenzhihao1040728129** [comment]
自己尝试过了:
- proxies.*.skip-cert-verify=true
- proxies.(*).skip-cert-verify=true
- proxies.1-999.skip-cert-verify=true

**Comment by Fndroid** [comment]
再加一个parser，url写你的，code按下面的
```yaml
- url: https://example.com/profile.yaml
  code: |
    module.exports.parse = async (raw, { axios, yaml, notify, console }, { name, url, interval, selected }) => {
      const obj = yaml.parse(raw)
      obj.proxies.forEach(p => ({...p, 'skip-cert-verify': true}))
      return yaml.stringify(obj)
    }
```

**Comment by chenzhihao1040728129** [comment]
> 再加一个parser，url写你的，code按下面的
> 
> ```yaml
> - url: https://example.com/profile.yaml
>   code: |
>     module.exports.parse = async (raw, { axios, yaml, notify, console }, { name, url, interval, selected }) => {
>       const obj = yaml.parse(raw)
>       obj.proxies.forEach(p => ({...p, 'skip-cert-verify': true}))
>       return yaml.stringify(obj)
>     }
> ```

首先谢谢大佬的回答,   其次:
commands 命令是不支持这种全匹配是吗,  只能通过代码方式?

**Comment by chenzhihao1040728129** [comment]
> > 再加一个parser，url写你的，code按下面的
> > ```yaml
> > - url: https://example.com/profile.yaml
> >   code: |
> >     module.exports.parse = async (raw, { axios, yaml, notify, console }, { name, url, interval, selected }) => {
> >       const obj = yaml.parse(raw)
> >       obj.proxies.forEach(p => ({...p, 'skip-cert-verify': true}))
> >       return yaml.stringify(obj)
> >     }
> > ```
> 
> 首先谢谢大佬的回答, 其次: commands 命令是不支持这种全匹配是吗, 只能通过代码方式?

我这样写不行的吗
`- reg: '^.*$'
    code: |
      module.exports.parse = async (raw, { axios, yaml, notify, console }, { name, url, interval, selected }) => {
          const obj = yaml.parse(raw)
          obj.proxies.forEach(p => ({...p, 'skip-cert-verify': true}))
          return yaml.stringify(obj)
      }`
      
    必须得 url?

**Comment by chenzhihao1040728129** [comment]
好像不行,   2种方式都试了

parsers:   
  - reg: 'zhihao$'
  # - reg: '^.*$'
    yaml:
      prepend-rules:
        - DOMAIN-KEYWORD,imgtu.com,DIRECT
        - DOMAIN-KEYWORD,csdn.net,DIRECT
        - DOMAIN-KEYWORD,qq.com,DIRECT
        - DOMAIN-KEYWORD,zhihao,DIRECT
        - DOMAIN-KEYWORD,zhihu,DIRECT
        - DOMAIN-KEYWORD,ddys,DIRECT
        - DOMAIN-KEYWORD,steamcontent,♻️ 自动选择
        - DOMAIN-KEYWORD,steamstatic,♻️ 自动选择
        - DOMAIN-KEYWORD,bard,📢 谷歌FCM
        - DOMAIN-KEYWORD,gate,🇭🇰 香港节点
        - DOMAIN-KEYWORD,deepl,♻️ 自动选择
        - DOMAIN-KEYWORD,google*,♻️ 自动选择
      append-proxy-groups:
        - name: ⚖️ 负载均衡-散列
          type: load-balance
          url: 'http://www.google.com/generate_204'
          interval: 30
          strategy: consistent-hashing
        - name: ⚖️ 负载均衡-轮询
          type: load-balance
          url: 'http://www.google.com/generate_204'
          interval: 30
          strategy: round-robin
      commands:
        - proxy-groups.⚖️ 负载均衡-散列.proxies=[]proxyNames
        - proxy-groups.0.proxies.0+⚖️ 负载均衡-散列
        - proxy-groups.⚖️ 负载均衡-轮询.proxies=[]proxyNames
        - proxy-groups.0.proxies.0+⚖️ 负载均衡-轮询 

parser:
  - url: https://sub.xeton.dev/subxxxx
    code: |
      module.exports.parse = async (raw, { axios, yaml, notify, console }, { name, url, interval, selected }) => {
          const obj = yaml.parse(raw)
          obj.proxies.forEach(p => ({...p, 'skip-cert-verify': true}))
          return yaml.stringify(obj)
      }
      
      
      
      parsers:   
  - reg: 'zhihao$'
  # - reg: '^.*$'
    yaml:
      prepend-rules:
        - DOMAIN-KEYWORD,imgtu.com,DIRECT
        - DOMAIN-KEYWORD,csdn.net,DIRECT
        - DOMAIN-KEYWORD,qq.com,DIRECT
        - DOMAIN-KEYWORD,zhihao,DIRECT
        - DOMAIN-KEYWORD,zhihu,DIRECT
        - DOMAIN-KEYWORD,ddys,DIRECT
        - DOMAIN-KEYWORD,steamcontent,♻️ 自动选择
        - DOMAIN-KEYWORD,steamstatic,♻️ 自动选择
        - DOMAIN-KEYWORD,bard,📢 谷歌FCM
        - DOMAIN-KEYWORD,gate,🇭🇰 香港节点
        - DOMAIN-KEYWORD,deepl,♻️ 自动选择
        - DOMAIN-KEYWORD,google*,♻️ 自动选择
      append-proxy-groups:
        - name: ⚖️ 负载均衡-散列
          type: load-balance
          url: 'http://www.google.com/generate_204'
          interval: 30
          strategy: consistent-hashing
        - name: ⚖️ 负载均衡-轮询
          type: load-balance
          url: 'http://www.google.com/generate_204'
          interval: 30
          strategy: round-robin
      commands:
        - proxy-groups.⚖️ 负载均衡-散列.proxies=[]proxyNames
        - proxy-groups.0.proxies.0+⚖️ 负载均衡-散列
        - proxy-groups.⚖️ 负载均衡-轮询.proxies=[]proxyNames
        - proxy-groups.0.proxies.0+⚖️ 负载均衡-轮询 

  - url: https://sub.xeton.dev/subxxxx
    code: |
      module.exports.parse = async (raw, { axios, yaml, notify, console }, { name, url, interval, selected }) => {
          const obj = yaml.parse(raw)
          obj.proxies.forEach(p => ({...p, 'skip-cert-verify': true}))
          return yaml.stringify(obj)
      }
