### ISSUE TITLE
need help，can't use the program.

### ISSUE THREAD

**Issue by danieldengdcx** [Fndroid/clash_for_windows_pkg#487]
windows 10 

first time use，there are words in red like：

time="2020-03-04T15:43:07+08:00" level=fatal msg="Parse config error: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `dm1lc3M...` into config.RawConfig"

I have reinstall 4 times.help :(

**Comment by Fndroid** [comment]
1. Open ``Home Directory`` folder
2. Delete ``config.yaml`` and ``config.yml``
3. Restart the APP

**Comment by danieldengdcx** [comment]
It works！thanks for your help ：）
