### ISSUE TITLE
Add clash meta core to software and 'float'64 bug

### ISSUE THREAD

**Issue by Kingal20000** [Fndroid/clash_for_windows_pkg#4871]
code 'password' expected type 'string', got unconvertible type 'float'64
 Give me this error when i change profile how can I fix that and add clash meta

**Comment by Fndroid** [comment]
```yaml
password: "01234567"
```

**Comment by Kingal20000** [comment]
> ```yaml
> password: "01234567"
> ```

How use this ? Delete  this or change this?
