### ISSUE TITLE
[Bug]: 报错 error

### ISSUE THREAD

**Issue by gonglixin980926** [Fndroid/clash_for_windows_pkg#4875]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### General界面截图

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/40887236/b212c4ad-c97c-4ec9-ba6e-9ebf21d6ee69)

### 操作系统

macOS amd64(Intel)

### 系统版本

10.15.8

### 问题描述

在mixin里配置了 rules 某个域名为DIRECT
但这个域名还是报错了

### 复现步骤

`module.exports.parse = ({ content, name, url }, { yaml, axios, notify }) => {
  const proxyGroup = content['proxy-groups'];

  const openAiProxies = content.proxies
    .filter((item) => item.name.includes('台湾') || item.name.includes('美国'))
    .map((item) => item.name);
  proxyGroup.push({
    name: 'OpenAi',
    type: 'select',
    proxies: [...openAiProxies, 'Proxy'],
  });
  const { rules } = content;

  const qwe = ['DOMAIN-SUFFIX,xxx.com,DIRECT'];

  content.rules.unshift(..qwe);
  console.log(content.rules,'rules')

  return content;
}`

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by simouse** [comment]
你的代码有问题：

```js
  const proxyGroup = content['proxy-groups'];
  const openAiProxies = content.proxies
    .filter((item) => item.name.includes('台湾') || item.name.includes('美国'))
    .map((item) => item.name);
  proxyGroup.push({
    name: 'OpenAi',
    type: 'select',
    // 3. 检查你有没有名为 'Proxy' 的代理或代理组，如果没有会报错
    proxies: [...openAiProxies],
  });
  // 1. 这一行删掉
  // const { rules } = content;
  const qwe = ['DOMAIN-SUFFIX,xxx.com,DIRECT'];
  // 2. 你写的 spread operator 是两个点，正确的语法是三个点
  content.rules.unshift(...qwe);
  console.log(content.rules, 'rules')
  return content;
```

你可以先尝试修改一下代码，再看看能不能工作😊

**Comment by gonglixin980926** [comment]
> 你的代码有问题：
> 
> ```js
>   const proxyGroup = content['proxy-groups'];
>   const openAiProxies = content.proxies
>     .filter((item) => item.name.includes('台湾') || item.name.includes('美国'))
>     .map((item) => item.name);
>   proxyGroup.push({
>     name: 'OpenAi',
>     type: 'select',
>     // 3. 检查你有没有名为 'Proxy' 的代理或代理组，如果没有会报错
>     proxies: [...openAiProxies],
>   });
>   // 1. 这一行删掉
>   // const { rules } = content;
>   const qwe = ['DOMAIN-SUFFIX,xxx.com,DIRECT'];
>   // 2. 你写的 spread operator 是两个点，正确的语法是三个点
>   content.rules.unshift(...qwe);
>   console.log(content.rules, 'rules')
>   return content;
> ```
> 
> 你可以先尝试修改一下代码，再看看能不能工作😊

我的代理组：
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/40887236/09ef9deb-eefe-4952-8b63-fee9c979c233)

我的代码里是三个点，在提issue的时候少敲了一个，
我这里是有的
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/40887236/3f8526a1-fd3a-49ec-986b-12714e43c7a7)

**Comment by gonglixin980926** [comment]
> 你的代码有问题：
> 
> ```js
>   const proxyGroup = content['proxy-groups'];
>   const openAiProxies = content.proxies
>     .filter((item) => item.name.includes('台湾') || item.name.includes('美国'))
>     .map((item) => item.name);
>   proxyGroup.push({
>     name: 'OpenAi',
>     type: 'select',
>     // 3. 检查你有没有名为 'Proxy' 的代理或代理组，如果没有会报错
>     proxies: [...openAiProxies],
>   });
>   // 1. 这一行删掉
>   // const { rules } = content;
>   const qwe = ['DOMAIN-SUFFIX,xxx.com,DIRECT'];
>   // 2. 你写的 spread operator 是两个点，正确的语法是三个点
>   content.rules.unshift(...qwe);
>   console.log(content.rules, 'rules')
>   return content;
> ```
> 
> 你可以先尝试修改一下代码，再看看能不能工作😊

代码会正常工作，但在issue图中界面是有报错

**Comment by simouse** [comment]
> > 你的代码有问题：
> > ```js
> >   const proxyGroup = content['proxy-groups'];
> >   const openAiProxies = content.proxies
> >     .filter((item) => item.name.includes('台湾') || item.name.includes('美国'))
> >     .map((item) => item.name);
> >   proxyGroup.push({
> >     name: 'OpenAi',
> >     type: 'select',
> >     // 3. 检查你有没有名为 'Proxy' 的代理或代理组，如果没有会报错
> >     proxies: [...openAiProxies],
> >   });
> >   // 1. 这一行删掉
> >   // const { rules } = content;
> >   const qwe = ['DOMAIN-SUFFIX,xxx.com,DIRECT'];
> >   // 2. 你写的 spread operator 是两个点，正确的语法是三个点
> >   content.rules.unshift(...qwe);
> >   console.log(content.rules, 'rules')
> >   return content;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 你可以先尝试修改一下代码，再看看能不能工作😊
> 
> 代码会正常工作，但在issue图中界面是有报错

我看你日志里面写的是 `ERROR -> dial tcp4 127.0.0.1:443`，我这里写的是网站解析后的 IP，不是本机。你是不是 hosts 文件，或者 dns 有问题？如果不是这个，那我也不知道了。

**Comment by gonglixin980926** [comment]
> > > 你的代码有问题：
> > > ```js
> > >   const proxyGroup = content['proxy-groups'];
> > >   const openAiProxies = content.proxies
> > >     .filter((item) => item.name.includes('台湾') || item.name.includes('美国'))
> > >     .map((item) => item.name);
> > >   proxyGroup.push({
> > >     name: 'OpenAi',
> > >     type: 'select',
> > >     // 3. 检查你有没有名为 'Proxy' 的代理或代理组，如果没有会报错
> > >     proxies: [...openAiProxies],
> > >   });
> > >   // 1. 这一行删掉
> > >   // const { rules } = content;
> > >   const qwe = ['DOMAIN-SUFFIX,xxx.com,DIRECT'];
> > >   // 2. 你写的 spread operator 是两个点，正确的语法是三个点
> > >   content.rules.unshift(...qwe);
> > >   console.log(content.rules, 'rules')
> > >   return content;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 你可以先尝试修改一下代码，再看看能不能工作😊
> > 
> > 
> > 代码会正常工作，但在issue图中界面是有报错
> 
> 我看你日志里面写的是 `ERROR -> dial tcp4 127.0.0.1:443`，我这里写的是网站解析后的 IP，不是本机。你是不是 hosts 文件，或者 dns 有问题？如果不是这个，那我也不知道了。

我这个host文件是没问题的
我这里有自定义host
127.0.0.1   xxx.com

**Comment by gonglixin980926** [comment]
又不复现了，估计是更新后修好了
