### ISSUE TITLE
可不可以右下状态栏加个右键断开or连接啊？

### ISSUE THREAD

**Issue by lfscqk67** [Fndroid/clash_for_windows_pkg#488]

**Comment by Fndroid** [comment]
并没有断开和连接的概念，所以加不了

**Comment by lfscqk67** [comment]
> 并没有断开和连接的概念，所以加不了

我的意思就是system proxy的开关

**Comment by GrayXu** [comment]
@Fndroid this issue can be closed by [v0.9.5 release](https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.5) with tray menu?
