### ISSUE TITLE
[Bug]: Relay前置代理：需要访问被墙的HTTP代理，链接超时。

### ISSUE THREAD

**Issue by hzct123** [Fndroid/clash_for_windows_pkg#4888]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### General界面截图

<img width="589" alt="image" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/145844655/60eee39a-af0a-4adc-bd89-4072dc5d3276">

### 操作系统

Windows x64

### 系统版本

win11 pro

### 问题描述

无法通过SS或者VMESS当前置访问HTTP代理。 SOCKS5通过前置和直连都可以。  HTTP直连可以，通过Relay就不通了。   

### 复现步骤

SS > VMESS  ✓
VMESS > SS  ✓
SS > SOCKS5  ✓
VMESS > SOCKS5  ✓
SS > HTTP  ×
VMESS > HTTP  ×

**Comment by Fndroid** [comment]
clash core issue, refer: https://github.com/Dreamacro/clash/issues
