### ISSUE TITLE
开启Allow Lan，重启软件后该选项就重新关闭了

### ISSUE THREAD

**Issue by luke3721** [Fndroid/clash_for_windows_pkg#489]
软件重启后需要再次打开该选项，建议优化一下此选项

**Comment by rain0002009** [comment]
要不手改config.yaml里面的allow-lan试试

**Comment by Fndroid** [comment]
开关只是临时调试用，具体设置在``General YAML``里的``allow-lan``属性

**Comment by Gonglja** [comment]
感谢，Allow Lan重启后自动关闭问题已经解决

**Comment by qzhsjz** [comment]
激活的配置文件里allow-lan:true，但软件依旧不会自动打开Allow LAN。

**Comment by yi-Xu-0100** [comment]
@qzhsjz 最好重开 issue 讨论，给出使用的版本和是否修改过文件的信息。

然后，这个 `allow-lan` 的选项只有在 clash 的主配置文件 `config.yaml` 中设置才能生效，远程订阅的配置文件设置后激活也是无效的。

我在最新版（0.11.2）中使用是没有问题的，设置后，会自动更新状态。
