### ISSUE TITLE
最近经常出现域名访问长时间等待后出现访问失败的情况

### ISSUE THREAD

**Issue by hudingwen** [Fndroid/clash_for_windows_pkg#4899]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### General界面截图

无

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

当我访问一个全球直连直连的域名时,浏览器出现长时间等待然后访问失败

### 复现步骤

当我关一次clash的代理和开启clash代理后,网页就能访问了,后面就正常访问.但是过一段时间又不能访问了

### 日志文件

clash下面没有logs文件夹

**Comment by coderZoe** [comment]
确实，我也有这个情况，有时过了一会又能访问了

**Comment by aoaoaoao-wu** [comment]
我和我的室友最近发现微软系服务器包括bing chat一会儿能访问，一会儿又在长时间尝试连接后显示bing关闭了连接；youtube能加载页面，加载不了视频；github也是一会儿能访问，一会儿不行，各种模式节点切换各种重置重启均无法根除，这问题这一两个月发现的，好像退回0.20.31版本能减少发作频率。与此同时同样的节点在安卓手机clash上访问youtube没问题。

但是但是，最近两天我发现出现故障时切换电脑连到手机热点就可以访问了，这两天一直用手机热点，再没出现过问题，不确定是路由器、光猫、移动公司哪个环节出了问题。我的路由器是100左右最便宜的路由器，不知有无关系。
具体可见我反应的另一个小bug的补充  #4891

**Comment by hudingwen** [comment]
我还是换v2rayN了   没用clash了  感觉clash已经止步不前了  现在clash还是clash内核已经完全是为了更新版本号而更新
