### ISSUE TITLE
0.5.9 final规则似乎依然没有修复？

### ISSUE THREAD

**Issue by moonaileen** [Fndroid/clash_for_windows_pkg#49]
![snipaste_2018-12-22_01-30-25](https://user-images.githubusercontent.com/2804132/50352641-2e7b4600-0589-11e9-96a1-6eaa2eca32c8.png)

设置了  - 'FINAL,,PROXY'规则
还是会出现如图这样的各种doesn't
在0.5.6之前都没有遇到过这种问题

**Comment by moonaileen** [comment]
您好，感谢回复。
但是我在改成了"MATCH,PROXY"之后依然还是doesn't 然后变成直连

**Comment by Fndroid** [comment]
> 您好，感谢回复。
> 但是我在改成了"MATCH,PROXY"之后依然还是doesn't 然后变成直连

需要在Profiles里面改，不是改config.yml

**Comment by moonaileen** [comment]
啊啊原来是改错了地方><非常感谢！给您添麻烦了！
