### ISSUE TITLE
使用通用控件构建外观

### ISSUE THREAD

**Issue by Shomnipotence** [Fndroid/clash_for_windows_pkg#490]

**Comment by Fndroid** [comment]
能稍微详细一点解释一下原因和所谓的“通用控件”是什么吗

**Comment by Shomnipotence** [comment]
UWP Universal Controls https://docs.microsoft.com/en-us/windows/uwp/design/basics/design-and-ui-intro#controls

About Fluent Design:
https://medium.com/microsoft-design/fluent-makeover-photolab-a583d25f362b

On how to use Fluent Design and XAML in Win32:
Windows 10 now enables you to use UWP controls in non-UWP desktop applications so that you can enhance the look, feel, and functionality of your existing desktop applications with the latest Windows 10 UI features that are only available via UWP controls. This means that you can use UWP features such as Windows Ink and controls that support the Fluent Design System in your existing WPF, Windows Forms, and C ++ Win32 applications. This developer scenario is sometimes called XAML islands.

Announced at Build 2018 during the keynote: https://developer.microsoft.com/en-us/events/build/content/announcing-uwp-xaml-islands
XAML Islands Demo: https://developer.microsoft.com/en-us/events/build/content/fluent-design-system-demo
Entire Fluent Design @ Build 2018 playlist: https://developer.microsoft.com/en-us/events/build/content/fluent-design-system-evolution?playlist=41f18bdd-6d5a-44b9-8586-0fa36ed91c45
Documentation here: https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/xaml-host-controls

**Comment by Shomnipotence** [comment]
> 能稍微详细一点解释一下原因和所谓的“通用控件”是什么吗

虽然最好是整个界面都长的像原生的，但是那样你可能不方便搞 macOS 版本了，至少把标题栏用原生的了吧，然后把深色模式的颜色从紫灰色改成深灰色或者黑色，这样或许就和谐点了。

UWP Universal Controls https://docs.microsoft.com/en-us/windows/uwp/design/basics/design-and-ui-intro#controls

About Fluent Design:
https://medium.com/microsoft-design/fluent-makeover-photolab-a583d25f362b

On how to use Fluent Design and XAML in Win32:
Windows 10 now enables you to use UWP controls in non-UWP desktop applications so that you can enhance the look, feel, and functionality of your existing desktop applications with the latest Windows 10 UI features that are only available via UWP controls. This means that you can use UWP features such as Windows Ink and controls that support the Fluent Design System in your existing WPF, Windows Forms, and C ++ Win32 applications. This developer scenario is sometimes called XAML islands.

Announced at Build 2018 during the keynote: https://developer.microsoft.com/en-us/events/build/content/announcing-uwp-xaml-islands
XAML Islands Demo: https://developer.microsoft.com/en-us/events/build/content/fluent-design-system-demo
Entire Fluent Design @ Build 2018 playlist: https://developer.microsoft.com/en-us/events/build/content/fluent-design-system-evolution?playlist=41f18bdd-6d5a-44b9-8586-0fa36ed91c45
Documentation here: https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/xaml-host-controls

**Comment by Fndroid** [comment]
我不是太明白“像原生”有什么意义

**Comment by Shomnipotence** [comment]
> 我不是太明白“像原生”有什么意义

Lynnette：在某些情况下，创建自定义控件可能很棒，但是在其他情况下，对于最终用户或开发而言，这可能不是最佳选择。在创建新的自定义控件之前，请查看Fluent工具包中是否已经存在可用于整个体验的通用控件。最好与已经存在的通用控件保持一致。

https://medium.com/microsoft-design/fluent-makeover-photolab-a583d25f362b

当然，或许…… 这一点上我们无法达成一致，……当然，作为用户毫无疑问希望各家应用遵循各个平台的设计规范。对于安卓应用来说，采用 MD 设计，对于 Windows 应用采用 FDS…… 这不是显而易见的吗。鉴于这是一个跨平台的应用，我们并不能要求其使用原生控件构建，仅仅外观相似即可

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
