### ISSUE TITLE
[Feature Request]: 建议添加一个禁止自动检测cfw更新的功能

### ISSUE THREAD

**Issue by ForestL18** [Fndroid/clash_for_windows_pkg#4900]
### General界面截图

由于cfw启动后会自动检测更新，所以会在启动后第一时间向github发起域名请求，而这个时候的域名请求是没有代理的，会被本地dns污染。
后续即使使用代理连接github，也会存在连接反应慢的情况出现，在dns flush后正常。

所以希望作者可以添加一个禁止检测更新的按钮，以规避以上问题。

@Fndroid 

### 功能描述

如上

**Comment by Fndroid** [comment]
fixed or implement in latest release, check it out from https://github.com/Fndroid/clash_for_windows_pkg/releases

**Comment by ForestL18** [comment]
作者可以指明一下按钮在什么地方吗？我找了半天也没看见😥

**Comment by ForestL18** [comment]
@Fndroid

**Comment by ForestL18** [comment]
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/45709305/6bd72fa5-accc-4f3f-8bb4-84409020db9d)

找到了，在cfw-setting里面，我以为是GUI的按钮，作者写release note的时候麻烦稍微声明一下，不然像我这种小白很容易搞不清。

如果可以的话，还是希望作者加一个GUI按钮，这样方便一些。

谢谢作者的贡献和对这个issue的处理。

**Comment by Kiritocyz** [comment]
> ![image](https://user-images.githubusercontent.com/45709305/273172642-6bd72fa5-accc-4f3f-8bb4-84409020db9d.png)
> 
> 找到了，在cfw-setting里面，我以为是GUI的按钮，作者写release note的时候麻烦稍微声明一下，不然像我这种小白很容易搞不清。
> 
> 如果可以的话，还是希望作者加一个GUI按钮，这样方便一些。
> 
> 谢谢作者的贡献和对这个issue的处理。

啊？我没找到……

**Comment by Kiritocyz** [comment]
> ![image](https://user-images.githubusercontent.com/45709305/273172642-6bd72fa5-accc-4f3f-8bb4-84409020db9d.png)
> 
> 找到了，在cfw-setting里面，我以为是GUI的按钮，作者写release note的时候麻烦稍微声明一下，不然像我这种小白很容易搞不清。
> 
> 如果可以的话，还是希望作者加一个GUI按钮，这样方便一些。
> 
> 谢谢作者的贡献和对这个issue的处理。

原来在配置文件目录下的cfw-setting文件里，谢谢

**Comment by ForestL18** [comment]
> > ![image](https://user-images.githubusercontent.com/45709305/273172642-6bd72fa5-accc-4f3f-8bb4-84409020db9d.png)
> > 找到了，在cfw-setting里面，我以为是GUI的按钮，作者写release note的时候麻烦稍微声明一下，不然像我这种小白很容易搞不清。
> > 如果可以的话，还是希望作者加一个GUI按钮，这样方便一些。
> > 谢谢作者的贡献和对这个issue的处理。
> 
> 啊？我没找到……

在General——Open Folder——cfw-setting.yaml

作者是直接放到配置文件里修改的😖

**Comment by Fndroid** [comment]
其实是bug，下版本修复...

**Comment by ForestL18** [comment]
> 其实是bug，下版本修复...

现在还有个问题，就是cfw启动的时候还是会向`raw.githubusercontent.com`发起直连请求，这是bug吗？

**Comment by ForestL18** [comment]
> 其实是bug，下版本修复...


0.20.38版本，关闭check for update后，启动cfw仍会有`raw.githubusercontent.com`的直连请求

@Fndroid
