### ISSUE TITLE
[Bug]: 下载资料：失败，错误: HTTP 响应状态代码(400)

### ISSUE THREAD

**Issue by gyyyyyyym** [Fndroid/clash_for_windows_pkg#4906]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### General界面截图

![fe960cf8f4db3efa39f9a308c04d5e8](https://github.com/Fndroid/clash_for_windows_pkg/assets/146693325/da9dac50-ae12-4d92-a53e-522375a1d516)

### 操作系统

Windows x64

### 系统版本

win11

### 问题描述

在SockBoom订阅的clash，在clashforwindos 上配置不了，试过最新的版本也用不了。

### 复现步骤

1.更新clash for windows至最新版本，无果
2.刷新clash链接，无果
3.删除电脑clash文件夹，无果

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by AkariiinMKII** [comment]
![Screenshot_20231002-124701.png](https://github.com/Fndroid/clash_for_windows_pkg/assets/6019344/04264e6b-e7d1-44c7-9b7d-da0ac0f1ab4b)

**Comment by gyyyyyyym** [comment]
什么意思 重新下载也没有用
