### ISSUE TITLE
[Bug]: load-balance节点变红后, 无法使用该节点发送请求(和interval时间无关)

### ISSUE THREAD

**Issue by padixa** [Fndroid/clash_for_windows_pkg#4913]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### General界面截图

![jj](https://github.com/Fndroid/clash_for_windows_pkg/assets/103999705/af6ffd0c-06a7-45ff-80c5-9ac59fca4322)

### 操作系统

Windows x64

### 系统版本

0.20.34

### 问题描述

proxy-group使用load-balance模式中, 如果节点出现不可访问,  那该节点直接变红, 下次就不会再用load-balance模式, 而只用第一个节点发送请求, load-balance模式变成了鸡肋.

这种情况下, load-balance不会再用变红的这些节点请求(所有请求只用第一个节点发送), 这导致每次我都需要手动刷新interval, 本来每次手动刷新就够烦的(所以interval设置的比较长). 

1.有没有开关能控制这种不能访问节点变红?  我想禁用.(确保节点可用的前提下)
2.或者能否让load-balance忽略这种变红情况, 继续轮询发送.

### 复现步骤

1.在proxy-goup中新增proxy列表, interval设置为比较长的时间(确保节点实时可用的前提)
2.节点出现不可能问.
3.节点变红, proxy每次请求只发送第一个节点, 其他节点全部不能用load-balance模式发送请求.

**Comment by padixa** [comment]
能否有人说一下, 这个东西变红的原理??  变红了就不能让它自动每分钟重新请求一次吗?  (不要用interval时间), 或干脆别变红.(禁止掉)

**Comment by Fndroid** [comment]
1. 客户端连不上服务器就变红
2. 当前没有设置可以禁止这个行为（可以去Clash core发PR）
3. 只有用延迟测试可以重置这个标记
