### ISSUE TITLE
[Bug]: 乌班图用不了

### ISSUE THREAD

**Issue by yanchen13** [Fndroid/clash_for_windows_pkg#4929]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### General界面截图

![QQ截图20231013022739](https://github.com/Fndroid/clash_for_windows_pkg/assets/145423994/bbee2dda-d520-47e7-b092-cacf9a8c77b8)
![QQ截图20231013022752](https://github.com/Fndroid/clash_for_windows_pkg/assets/145423994/8c540b90-d4bb-4123-868a-72b0b0d46c4f)

### 操作系统

Linux

### 系统版本

最新

### 问题描述

什么东西都是最新

### 复现步骤

解压到home运行

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
手动设置代理127.0.0.1:23432

**Comment by yanchen13** [comment]
感谢回复，但我希望他能像前几个版本那样一键翻墙
