### ISSUE TITLE
[Feature Request]: 希望添加meta内核的支持

### ISSUE THREAD

**Issue by sf467** [Fndroid/clash_for_windows_pkg#4931]
### General界面截图

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/121373973/0990e595-b062-4941-9fb7-bc0d708a61b1)

### 功能描述

希望这个软件可以适配一下clash.meta内核，现在meta内核拥有更新的特性，支持更多的协议

**Comment by longhuan1999** [comment]
同感

**Comment by cancundeyingzi** [comment]
meta的win版内核全是bug
