### ISSUE TITLE
[Bug]: Clash节点测速正常，但打不开国外网站

### ISSUE THREAD

**Issue by wmkai** [Fndroid/clash_for_windows_pkg#4932]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### General界面截图

![22d6033a2007a99730daef8ac0e41313](https://github.com/Fndroid/clash_for_windows_pkg/assets/39148461/c015f26a-466b-48c9-8be8-c44713eabaaf)
![49f6f0341b7358614d3fbcee41498dc7](https://github.com/Fndroid/clash_for_windows_pkg/assets/39148461/346bc38e-0f33-4592-a4d9-36c3b2975e6b)
![0b0673eb5f325cf432e2083b57807a3e](https://github.com/Fndroid/clash_for_windows_pkg/assets/39148461/62cd1aed-e0c9-4008-b216-28f29132d3eb)

### 操作系统

Windows x64

### 系统版本

WIN10

### 问题描述

Clash节点测速正常，但打不开国外网站

### 复现步骤

在WIN10下使用网线和手机流量开热点均有这个问题。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by mdhlgz** [comment]
我也是耶，手机能用的节点放电脑就不行了，还以为是浏览器/杀毒软件之类的给我拦截了

**Comment by wmkai** [comment]
> 我也是耶，手机能用的节点放电脑就不行了，还以为是浏览器/杀毒软件之类的给我拦截了

是的，手机clash可以用，浏览器把插件禁用了也还是不行

**Comment by mdhlgz** [comment]
> > 我也是耶，手机能用的节点放电脑就不行了，还以为是浏览器/杀毒软件之类的给我拦截了
> 
> 是的，手机冲突可以用，浏览器把插件禁用了也还是不行

找到问题了，防火墙拦截了

**Comment by wmkai** [comment]
> > > 我也是耶，手机能用的节点放电脑就不行了，还以为是浏览器/杀毒软件之类的给我拦截了
> > 
> > 
> > 是的，手机冲突可以用，浏览器把插件禁用了也还是不行
> 
> 找到问题了，防火墙拦截了

感谢，我在win10系统设置里把一些没用的代理服务器删掉就OK了
