### ISSUE TITLE
[Bug]: 网络宽带占用率极高

### ISSUE THREAD

**Issue by black-pwq** [Fndroid/clash_for_windows_pkg#4942]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### General界面截图

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/105478488/f083b270-6b7a-46e1-a4a1-98ac7efc53dc)

### 操作系统

Windows x64

### 系统版本

22H2

### 问题描述

Same problem with #4910.

CFW会占用极高的网络带宽（原因仍未知）。

我发现这个问题的时候我自己的梯子已经用了将近10G的流量（几小时内），还被供应商锁了流量，最后排查原因到CFW上。

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/105478488/10f6198b-0c11-4c35-b16e-aa7fbe268bdc)

上面这张图片是我刚重启电脑截图的，可以看到CFW的网络占用十分大。另外我并没有启动任何其他应用，也没有添加新的自启应用，最多更新了Windows的几个补丁，在没更新CFW新版本前还可以正常使用（并没有这么大的宽带占用）。CFW中的连接数量也极其庞大
<img width="643" alt="image" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/105478488/aff6f673-7b96-4a50-ae3c-bb7974360a77">

（甚至截完这张图CFW就死机了）

出现这个问题之前我一直用的是老版本（相对而言），直到更新到0.20.36（不保证一定是这个版本之后才出现的这个问题，因为我不记得老版本了），但新版本（0.20.38）也仍然具有相同的问题。而且和#4910, #4924 中 @A2Data 描述的一样，尽管关闭系统代理也会出现相同的问题

### 复现步骤

不确定。对于我个人而言重启电脑后就能出现这个问题

### 日志文件

<details><summary>logs</summary><p>

[2023-10-17-173708.log](https://github.com/Fndroid/clash_for_windows_pkg/files/12927414/2023-10-17-173708.log)

</p></details>

### 其他补充
个人推测与配置文件、UWP等无关，因为使用默认配置文件、关闭UWP，甚至关闭系统代理仍然会出现此问题。
另外我在看log的时候，肉眼观察好像出现最多的是45.147.197.165. 不知道为什么会一直访问这个，不管TCP连接成功还是失败。

补：尽管重启貌似不能解决问题，但关机（吃顿饭）再启动貌似能解决这个问题

**Comment by Fndroid** [comment]
Allow LAN默认会绑定在所有接口上，如果你有公网IP那可能就直接暴露了，先关掉看看吧

**Comment by black-pwq** [comment]
> Allow LAN默认会绑定在所有接口上，如果你有公网IP那可能就直接暴露了，先关掉看看吧

@Fndroid  一直在排查我主机的问题，没想到还有局域网的因素，感谢大佬的回复，看起来就是这个原因。

那这样的话连接像WSL2这样具备虚拟局域网的应用CFW有没有好的解决方案？（我以前一直都是开着Allow LAN连的WSL）

**Comment by black-pwq** [comment]
> Allow LAN默认会绑定在所有接口上，如果你有公网IP那可能就直接暴露了，先关掉看看吧

@Fndroid  一直在排查我主机的问题，没想到还有局域网的因素，感谢大佬的回复，看起来就是这个原因。

那这样的话连接像WSL2这样具备虚拟局域网的应用CFW有没有好的解决方案？（我以前一直都是开着Allow LAN连的WSL）
