### ISSUE TITLE
Clash for Windows 0.9.0 开机自启弹窗

### ISSUE THREAD

**Issue by RisingInIris2017** [Fndroid/clash_for_windows_pkg#495]
#### Clash for Windows 版本
0.9.0
#### 产生Bug的步骤
1. 开启系统代理。
2. 点击 General 菜单中的“Start with Windows”，设置 Clash for Windows 开机自启动。
3. 重启系统，看到如下弹窗。

#### 反映Bug的图片
![报错](https://user-images.githubusercontent.com/28519848/76090088-e6add680-5ff5-11ea-92bd-094a40a0b682.png)

在关闭 Clash 的开机自启动，或者开机自启动但没有自动开启代理的情况下，
均不会观察到上述现象。
必须在 Clash 开机自启动，且自动开启代理时，才会见到上述现象。
不是一个很大的问题，但是我认为值得写个反馈。

感谢您拨冗阅读反馈，
期待您的回复！

**Comment by Fndroid** [comment]
上游修改注册表项目：https://www.npmjs.com/package/regedit

但是基本没看到类似的反馈，考虑下是不是电脑缺少某些组件或服务未启动
