### ISSUE TITLE
[Feature Request]: 可以新增在Scoop此类的包管理器上面安装的方式吗

### ISSUE THREAD

**Issue by 129duckflew** [Fndroid/clash_for_windows_pkg#4959]
### General界面截图

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/62204325/c8e34da9-3692-43bd-9466-cfd594b1e534)

### 功能描述

新增在Scoop此类的包管理器上的安装方式

**Comment by junlongzzz** [comment]
第三方Bucket有这包倒是挺多的，但官方Bucket貌似是没有该软件的，比如Extras内，我在用的包含cfw的桶推荐：https://github.com/chawyehsu/dorado

**Comment by 129duckflew** [comment]
> 第三方Bucket有这包倒是挺多的，但官方Bucket貌似是没有该软件的，比如Extras内，我在用的包含cfw的桶推荐：https://github.com/chawyehsu/dorado

OK，那就可以了，谢谢分享
