### ISSUE TITLE
[Bug]:  windows无法完全卸载，clash-core-service.exe每次开机都会自启动

### ISSUE THREAD

**Issue by ChenjieShou** [Fndroid/clash_for_windows_pkg#4967]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### General界面截图

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/44863145/6ab9f86c-5dc5-4149-bd02-f15ea10d49aa)

### 操作系统

Windows x64

### 系统版本

Windows 10 企业版22H2 19045.3570

### 问题描述

卸载不干净，留了启动项还会自动启动。启动项在C:\Program Files\Clash for Windows Service\clash-core-service.exe。怎么彻底删除clash for weindows。有改动注册表吗？

### 复现步骤

卸载后任务计划程序里还有启动项

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Leyoud** [comment]
你安装了 Service Mode 肯定卸载出问题啊，先在 clash for windows 里卸载掉

**Comment by Leyoud** [comment]
先在ClashForWindows General界面 卸载 Service Mode

**Comment by ChenjieShou** [comment]
解决了，重新安装clash for windows后，卸载Service Mode，重启后就能删掉文件夹了。
