### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by codeMauguin** [Fndroid/clash_for_windows_pkg#4978]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### General界面截图

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/67811091/0b62490a-532b-4e78-8dc3-ed61a2fb10fc)

### 操作系统

Windows x64

### 系统版本

11   

### 问题描述

在window和mac上都复现了，延迟类型选择平均，测速后显示的是underfunded ms 但是还是能排序，虽然看不出到底排序是否正确

### 复现步骤

打开延迟类型选择平均类型

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
general截图

**Comment by codeMauguin** [comment]
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/67811091/32774349-10c6-459c-9b57-104394444f31)
是管理员权限打开的

**Comment by codeMauguin** [comment]
是这内核切换的问题么？
