### ISSUE TITLE
问个使用问题，为何有的进程在”连接“里看不到

### ISSUE THREAD

**Issue by likaifenkeng** [Fndroid/clash_for_windows_pkg#4980]
TUN模式
版本 0.20.39

例如：
firefox可以看到，firefox的连接记录可以看到进程名
TeamViewer.exe看不到，能看到连接到TeamViewer.com，但是连接记录没有 TeamViewer.exe进程名

类似例子挺多，导致 部分应用无法在yml里使用  PROCESS-NAME  定义规则。

**Comment by Fndroid** [comment]
log的类型改成debug可以在log里看到
