### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by uauwaw** [Fndroid/clash_for_windows_pkg#4985]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### General界面截图

![PMP](https://github.com/Fndroid/clash_for_windows_pkg/assets/130812977/e847c930-a05d-4b94-be62-a19b4666cd89)

### 操作系统

Windows x64

### 系统版本

win11

### 问题描述

本地向clash端口发送socks5协议包连接外部服务器包时可收到回应(05 00 00 01 7f 00 00 01  1e d2),但是继续发送包时发现连接被断开,wireshark抓包发现外连接到外部服务器.
我记得以前版本没问题的,更换v2rayN也没问题可以连接.
是否修改了socks5连接逻辑

### 复现步骤

本地向clash端口发送socks5协议包连接外部服务器

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
clash core issue, refer: https://github.com/Dreamacro/clash/issues
