### ISSUE TITLE
长时间使用会出现内存泄漏

### ISSUE THREAD

**Issue by ryans233** [Fndroid/clash_for_windows_pkg#50]
![20181229211500.png](https://i.loli.net/2018/12/29/5c27725964a2b.png)
长时间使用后内存占用非常大，截图的情况是连续运行一天左右的结果，任务管理器可以观察到每秒有几十KB左右的上涨。

**Comment by Fndroid** [comment]
看下log有多大

**Comment by ryans233** [comment]
2018-12-28-175156.log
这个应该是昨天到刚刚重启CFW前的log，大小为97.7 MB (102,480,484 字节)。

**Comment by Fndroid** [comment]
什么level的？开了多久？这个log文件有点大

**Comment by ryans233** [comment]
默认的info，运行了28个小时。

Fndroid <notifications@github.com> 于2018年12月29日周六 下午11:12写道：

**Comment by Fndroid** [comment]
改成``silent``，观察一下

**Comment by zddewe** [comment]
我也发现有这个问题 @Fndroid @ryans233

**Comment by Fndroid** [comment]
> 我也发现有这个问题 @Fndroid @ryans233 

log level改成silent重启再看看会不会
