### ISSUE TITLE
DNS问题（ipv6）

### ISSUE THREAD

**Issue by DragonLie** [Fndroid/clash_for_windows_pkg#500]
dns设置目前支持fe80::1嘛
我设置的时候提示错误
另外cfw-bypass字段怎么设置跳过v6地址

**Comment by Fndroid** [comment]
IPV6格式应该是这样的``[ip6]:port``，bypass也要用括号括起来

**Comment by DragonLie** [comment]
cfw-bypass:
  - [fe80::1]设置了没报错
但是
dns:
  enable: true
  ipv6: true
  listen: :53
  nameserver:
    - [fe80::1]
    - 223.5.5.5
    - 114.114.114.114
    - https://cloudflare-dns.com/dns-query
    - tls://dns.google:853
报错了
time="2020-03-11T11:50:57+08:00" level=fatal msg="Parse config error: yaml: line 13: did not find expected '-' indicator"

**Comment by Fndroid** [comment]
引号引起来，还有端口号也要写

**Comment by DragonLie** [comment]
这下可以了 谢谢带佬

**Comment by DragonLie** [comment]
还想问一下：  listen: :53这个删不删有什么不一样的

**Comment by Fndroid** [comment]
> 还想问一下： listen: :53这个删不删有什么不一样的

是否开启本地DNS服务器
