### ISSUE TITLE
chrome无法访问google

### ISSUE THREAD

**Issue by dawn-flash** [Fndroid/clash_for_windows_pkg#506]
其他浏览器可以访问google，但是chrome无法访问。

**Comment by dawn-flash** [comment]
![QQ截图20200310231435](https://user-images.githubusercontent.com/20416895/76327507-10803980-6325-11ea-92ed-c1090ac71d75.png)

**Comment by Fndroid** [comment]
其他浏览器能用就说明不是CFW的问题了吧，Chrome不能用有很多可能，google下吧
