### ISSUE TITLE
安装clash客户端后无法打开

### ISSUE THREAD

**Issue by neverbackoff** [Fndroid/clash_for_windows_pkg#51]
clash版本：0.5.13
系统：win7 64 旗舰版
问题：安装后没任何反应，右下角没有小图标，C:\Users\{用户名}\.config\clash路径下只有config.yml、Country.mmdb两个文件，config.yml还是空的，没有logs文件夹，重启多次，创新安装也没用，尝试0.5.12也是一样

**Comment by pwbty** [comment]
之前能用，今天也这个情况，双击毫无反应

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
