### ISSUE TITLE
clash的网页控制界面无法被局域网内的别的电脑访问

### ISSUE THREAD

**Issue by magiclu** [Fndroid/clash_for_windows_pkg#510]
用netstat命令查看了127.0.0.1：9090的端口是开放的，但是192.168.x.x：9090是不开放的，我把防火墙关了也是这样的，把9090改成别的数字也没用，secret改了也没用
配置文件用的是几乎默认的，就只改了一下allow-lan
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: '127.0.0.1:9090'
secret: ''
cfw-bypass:
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
cfw-latency-timeout: 3000
Proxy:
  - name: Shadowsocks
    type: socks5
    server: 127.0.0.1
    port: 1080
Proxy Group:
  - name: Proxy
    type: select
    proxies:
      - Shadowsocks
Rule:
  - 'MATCH,DIRECT'

我想在局域网里用别的电脑控制这个电脑，来手动选节点什么的

具体的姿势是有个openwrt的虚拟机，lean的版本，在ssr plus里设置了socks5代理到192.168.x.x:7891，这样就不用更新openclash之类的了，更新个windows版的clash简单很多,这个openwrt就永远不需要更新了,也可以作为手机之类的设备的网关

127.0.0.1:9090这个网页是能打开的，也能用yacd开操作，但是192.168.x.x:9090是无法被访问的，不管是哪个电脑

192.168.x.x:7891是能被别的设备正常通过socks5连接来科学上网的

**Comment by magiclu** [comment]
log里有

time="2020-03-11T13:47:44+08:00" level=warning msg="dial DIRECT error: dial tcp4 192.168.99.222:9090: connectex: No connection could be made because the target machine actively refused it."

**Comment by ShadowThiefCC** [comment]
你难道不是应该把监听地址改为0.0.0.0？

**Comment by magiclu** [comment]
> 你难道不是应该把监听地址改为0.0.0.0？

谢谢，改了之后能用了
我过会去试一下，是默认是127.0.0.1的还是我订阅后被自动改了
