### ISSUE TITLE
clash for windows客户端中profiles配置项无效

### ISSUE THREAD

**Issue by feichangyl** [Fndroid/clash_for_windows_pkg#511]
在客户端中点击profiles选项进行服务器订阅，发现客户端中该选项卡无效，不能进行服务器订阅和配置服务器

**Comment by satrianixx** [comment]
我也是这样，Profiles面板空，机场一键订阅报错。

**Comment by Fndroid** [comment]
如果出现空白，先进General里进入Home Directroy然后删除目录里profiles文件夹
