### ISSUE TITLE
无法安装TAP

### ISSUE THREAD

**Issue by 954455850** [Fndroid/clash_for_windows_pkg#512]
按照F大的
![image](https://user-images.githubusercontent.com/31529293/76625482-4c5c0e80-6572-11ea-95a5-4348dd834f5c.png)
![image](https://user-images.githubusercontent.com/31529293/76625536-6990dd00-6572-11ea-85e1-19b1f85493cb.png)
输出安装失败

**Comment by 954455850** [comment]
重装系统解决。。。

**Comment by Nonecrap** [comment]
同样的问题，我不想重装系统，有什么解决办法吗？
