### ISSUE TITLE
用几个小时，Proxies页面就错乱了

### ISSUE THREAD

**Issue by abae136ab** [Fndroid/clash_for_windows_pkg#525]
重启就恢复双排，再用一会儿就又变成这样了~
![cfw](https://user-images.githubusercontent.com/56730294/76926625-c9dba200-6917-11ea-90ed-5f33580271a3.png)

**Comment by Fndroid** [comment]
应该是窗口大小改变了导致的，试下https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.2，把窗口拉大一点

**Comment by abae136ab** [comment]
> 应该是窗口大小改变了导致的，试下新版
> 
> https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.2

已经在用0.9.2了，很棒！
