### ISSUE TITLE
logs显示，可以实现自动刷新显示吗？

### ISSUE THREAD

**Issue by abae136ab** [Fndroid/clash_for_windows_pkg#526]
现在需要用鼠标跟着滚动，才能看到最新的日志信息。谢谢！

**Comment by Fndroid** [comment]
要是一直滚动，怎么看呢

**Comment by abae136ab** [comment]
> 要是一直滚动，怎么看呢
现在是要看最新的，就需要一直滚动。。。
你这么一回复，我大概就知道你的设计初衷了~自动滚动的时候，如果鼠标放上去，可以停止，且可以上下滚动查看，是不是个比较好的方案？就是不知道代码实现复杂不。
surge dashboard那样就很好，一直在动，鼠标可以滚动查看上下。

**Comment by GrayXu** [comment]
@Fndroid this issue can be closed by [v0.9.6 release](https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.6) with auto scrolling?
