### ISSUE TITLE
[Feature Request]右键菜单增加"开关系统代理"选项

### ISSUE THREAD

**Issue by H4M5TER** [Fndroid/clash_for_windows_pkg#528]
现在(0.9.1)的任务栏右键菜单只有Dashboard、Force Quit和Quit，需要切换系统代理时需要双击打开Dashboard然后移动鼠标较远距离。
参考: https://github.com/Fndroid/clash_for_windows_pkg/issues/206 https://github.com/Fndroid/clash_for_windows_pkg/issues/347
个人认为，用于切换节点和规则的确是GUI比较直观，但是仅仅开关功能还是可以做到右键里的，并不会增加太多复杂度。

**Comment by oGsLP** [comment]
+1

**Comment by hfun2017** [comment]
加一个全局的快捷键也很好，不知道开发者愿不愿意做😂

**Comment by kris115** [comment]
可能是习惯了v2rayN的操作方法，增加模式快捷切换选项，确实方便不少。

**Comment by lxk0301** [comment]
> 可能是习惯了v2rayN的操作方法，增加模式快捷切换选项，确实方便不少。
v2rayN上面vmess的h2协议 ，这个软件支持吗？

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.5
