### ISSUE TITLE
CFW有支持trojan的可能吗？

### ISSUE THREAD

**Issue by guardiora** [Fndroid/clash_for_windows_pkg#531]
如题，谢谢🙏🏿

**Comment by hyq3351** [comment]
clash也不支持trojan的呀  Trojan到底哪里好啊

**Comment by abae136ab** [comment]
> clash也不支持trojan的呀 Trojan到底哪里好啊
D大说已加入？

**Comment by hyq3351** [comment]
> > clash也不支持trojan的呀 Trojan到底哪里好啊
> > D大说已加入？
> > Dreamacro commented 2 days ago
> > @caesarjing 加上了

我没注意 0.9.2确实可以Trojan了
