### ISSUE TITLE
删除 Profile 时，正在使用的 Profile 定位出现问题

### ISSUE THREAD

**Issue by AzunyanDaisuki** [Fndroid/clash_for_windows_pkg#533]
删除一个位于正在使用的 Profile 之前的 Profile 时，当前正在使用的 Profile 会被向后顺延一位，但此时 Proxies 中的内容还未发生改变，如果这时再重启 CFW，Proxies 中的内容的就会被切换成后一个 Profile 的内容。
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/18110400/77133250-667b7c80-6a9d-11ea-81d4-d4279d206ca3.gif)
![Clash for Windows 3_20_2020 11_22_47](https://user-images.githubusercontent.com/18110400/77133256-6aa79a00-6a9d-11ea-8439-765adb5d34b7.png)
重启 CFW 后变成了后一个 Profile 的节点

**Comment by Fndroid** [comment]
感谢反馈

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.5
