### ISSUE TITLE
Proxy Group中url和interval分别是什么意思？

### ISSUE THREAD

**Issue by ryanxci** [Fndroid/clash_for_windows_pkg#534]
type: url-test
url: http://www.gstatic.com/generate_204
interval: 300

这里http://www.gstatic.com/generate_204是专门用来测速的吗？我看很多人配置的都是这个
interval：300是指300秒测试一次吗？

**Comment by ryanxci** [comment]
我发现我两台vps的latency非常不稳定，用http://www.gstatic.com/generate_204来测试latency可靠吗？

**Comment by Fndroid** [comment]
- generate_204一般用于连通性检测
- 300单位是秒
- 并没有可不可靠的说法，延迟测试时间是服务端代理一个请求所用时间
