### ISSUE TITLE
配置定时更新的问题

### ISSUE THREAD

**Issue by ausers** [Fndroid/clash_for_windows_pkg#536]
服务器端运行subconverter，订阅采用服务器配置profile文件的方式

服务器端：机场订阅定时更新正常，转换订阅使用IP127.0.0.1定时更新正常
**电脑端**：机场订阅定时更新正常，**转换订阅使用IP服务器IP不自动更新**

**Comment by Fndroid** [comment]
更新的地址能正常访问吗，比如用浏览器能否打开

**Comment by ausers** [comment]
> 更新的地址能正常访问吗，比如用浏览器能否打开

可以，cfw中手动点更新也能更新，甚至挂subconverter的服务器跟我就在同一个省

**Comment by ausers** [comment]
> 更新的地址能正常访问吗，比如用浏览器能否打开

又观察了一段时间，感觉有可能是超时导致的
