### ISSUE TITLE
rule-set加载失败，规则没有生效

### ISSUE THREAD

**Issue by abae136ab** [Fndroid/clash_for_windows_pkg#541]
右下角通知已经提示update成功，edit rules点进去，更新时间也是最新的，但rule未生效。

**Comment by Fndroid** [comment]
不支持rule-set

**Comment by abae136ab** [comment]
> 不支持rule-set
明明生效了呀…而且界面提醒更新成功…logs里都显示ruleset匹配了…

**Comment by abae136ab** [comment]
> 不支持rule-set

![01](https://user-images.githubusercontent.com/56730294/77226774-dd0b9d80-6bb5-11ea-8e68-31cb39b8c5db.png)
![02](https://user-images.githubusercontent.com/56730294/77226776-ded56100-6bb5-11ea-9688-eefb1252d10f.png)
![3](https://user-images.githubusercontent.com/56730294/77226777-e0068e00-6bb5-11ea-8097-e6194a769059.png)
略迷惑~~~
