### ISSUE TITLE
什么时候能够支持Trojan啊？

### ISSUE THREAD

**Issue by WinnieCrazyUniverse** [Fndroid/clash_for_windows_pkg#542]
目前Windows下最中意的代理软件就是clash了，界面美观，操作简单，堪比iOS端的shadowrockets，但是不支持trojan让我十分难过，希望可以早日支持哦！给程序员哥哥点赞！

**Comment by abae136ab** [comment]
等clash-core吧，看D大意思应该快了？

**Comment by neteroster** [comment]
0.9.2 支持了
