### ISSUE TITLE
求助，有一半的线路都用不了

### ISSUE THREAD

**Issue by xixizzz** [Fndroid/clash_for_windows_pkg#543]
普通线路都不用了，请问是因为什么原因？

**Comment by Fndroid** [comment]
无关问题请自行联系服务商

**Comment by xixizzz** [comment]
我朋友就可以每条线路都用，到我电脑就有接近一半的线路用不了，这是为什么？


我这边还有一种情况，就是已经在profiles里建好了域名关键词direct，但是打开的时候是无网页的，显示网络错误，这种情况改怎么解决？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Fndroid"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月21日(星期六) 晚上9:28
收件人:&nbsp;"Fndroid/clash_for_windows_pkg"<clash_for_windows_pkg@noreply.github.com&gt;;
抄送:&nbsp;"354567132"<354567132@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Fndroid/clash_for_windows_pkg] 求助，有一半的线路都用不了 (#543)





 
无关问题请自行联系服务商
