### ISSUE TITLE
clash有没有办法识别某一个目录的*.yaml

### ISSUE THREAD

**Issue by huanx9** [Fndroid/clash_for_windows_pkg#549]
一般来说 我们用拖拽的方式把 *.yaml l喂到 clash
clash能不能自己判断某一个路径下 有一些*.yaml 在启动clash 自动读取这个路径下的 *.yaml

我反复阅读了官方文档，恕我比较菜鸡 找不到这样的办法
修改appdate下  clash好像也无法读取..

clash  download from a url  只能读取一个配置 且无法直接命名 yaml

我是想要 批量生成yaml 然后自动加载到 profiles 里面..

**Comment by Fndroid** [comment]
配置文件路径可以自定义：https://docs.cfw.lbyczf.com/contents/profilespath.html

CFW读取需要读取里面的list.yml文件，按格式生成一个就好了

**Comment by huanx9** [comment]
成功了。谢谢开发者。
