### ISSUE TITLE
0.9.2版本无法用rule翻墙

### ISSUE THREAD

**Issue by Michaela-Jackson** [Fndroid/clash_for_windows_pkg#550]
如题....不知道是为什么，只能用global模式翻墙？

**Comment by Fndroid** [comment]
根据log文件排除

**Comment by Michaela-Jackson** [comment]
> 根据log文件排除

![image](https://user-images.githubusercontent.com/54223354/77240965-58596780-6c27-11ea-90b6-75d98a21788f.png)
这样的显示？

**Comment by Fndroid** [comment]
节点问题，策略组配置问题
