### ISSUE TITLE
总是这样子，不知道为什么用的绿色版

### ISSUE THREAD

**Issue by 1353604736** [Fndroid/clash_for_windows_pkg#552]
总是这样子，不知道为什么用的绿色版
![360截图16520815354150](https://user-images.githubusercontent.com/12869582/77245684-645f1c80-6c5b-11ea-80a0-0f5f0317587a.png)

**Comment by 1353604736** [comment]
安装板无法安装，提示中止安装，绿色版下下来就无法使用，真是醉了

**Comment by Fndroid** [comment]
看最新的log

**Comment by 1353604736** [comment]
已解决，删除C盘配置重启即可
