### ISSUE TITLE
0.9.2版本出现的问题 - Could not connect to Clash Core

### ISSUE THREAD

**Issue by aghao** [Fndroid/clash_for_windows_pkg#554]
之前未曾出现该问题，0.9.2中，开着代理一段时间，偶而出现该问题，quit或者force quit，重新打开Clash均无法解决，并且之前开着代理，会导致打开Clash代理自动打开，而无法上任何国内外网站。尝试Try to Repair无效无反应，重启Explorer.exe也无效，目前不知如何解决

**Comment by aghao** [comment]
![Snipaste_2020-03-22_19-12-06](https://user-images.githubusercontent.com/4003426/77248402-173b7480-6c74-11ea-8650-0d759629aa49.png)
![Snipaste_2020-03-22_19-27-17](https://user-images.githubusercontent.com/4003426/77248404-19053800-6c74-11ea-84a4-16c124ce49e0.png)

**Comment by aghao** [comment]
按如下解决办法，尝试清空config.yaml以及删除mmdb依旧无效
https://github.com/Fndroid/clash_for_windows_pkg/issues/445#issuecomment-592308302

**Comment by aghao** [comment]
#更新
别人电脑排查后，发现可能安全软件隔离问题，加入信任名单或卸载也许可解决

**Comment by vanppo** [comment]
同样的问题，根据 https://github.com/Fndroid/clash_for_windows_pkg/issues/445#issuecomment-592308302 解决了 。
