### ISSUE TITLE
Clash 间歇性崩溃

### ISSUE THREAD

**Issue by Bi-lank** [Fndroid/clash_for_windows_pkg#557]
Clash 在使用时不定时出现崩溃。所使用节点为SS节点，系统信息见附件。该问题出现于Clash 0.9.1 和0.9.2。另卸载0.9.1并清理安装路径后安装0.9.2版本号依然显示0.9.1

[info.zip](https://github.com/Fndroid/clash_for_windows_pkg/files/4366863/info.zip)

**Comment by Bi-lank** [comment]
崩溃时报错窗口截图
![image](https://user-images.githubusercontent.com/43201428/77275403-2ca3b380-6cf3-11ea-968f-533517d09a81.png)

**Comment by Fndroid** [comment]
这个问题暂时未清楚是什么原因造成的，麻烦留意下什么情况下能触发这个bug，感谢

**Comment by Bi-lank** [comment]
目前尚无法找到方法有效复现问题，但闪退现象依然偶发。将会留意bug的出现的特点

**Comment by Jevanzhu** [comment]
楼主的clash是如何安装的？是下载的安装包，还是压缩包。楼主试试用压缩包看看，然后做成便携模式，配置文件和软件在同一个文件夹里。然后试试卸载下迅雷之类的第三方软件。

**Comment by wks1311386136** [comment]
听说国内GitHub限速，我找的资源在百度网盘下的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jevan Zhu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月24日(星期二) 晚上10:15
收件人:&nbsp;"Fndroid/clash_for_windows_pkg"<clash_for_windows_pkg@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Fndroid/clash_for_windows_pkg] Clash 间歇性崩溃 (#557)





 
楼主的clash是如何安装的？是下载的安装包，还是压缩包。楼主试试用压缩包看看，然后做成便携模式，配置文件和软件在同一个文件夹里。然后试试卸载下迅雷之类的第三方软件。

**Comment by Jevanzhu** [comment]
> 听说国内GitHub限速，我找的资源在百度网盘下的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Jevan Zhu"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月24日(星期二) 晚上10:15 收件人:&nbsp;"Fndroid/clash_for_windows_pkg"<clash_for_windows_pkg@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [Fndroid/clash_for_windows_pkg] Clash 间歇性崩溃 (#557) 楼主的clash是如何安装的？是下载的安装包，还是压缩包。楼主试试用压缩包看看，然后做成便携模式，配置文件和软件在同一个文件夹里。然后试试卸载下迅雷之类的第三方软件。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

从这里下一个回去试试，做成便携版，删掉原来的。限速就限速咯，也就下一次而已。我的没出过问题，我看了下楼主的系统文件，除了笔记本和台式的局别，也就只有CPU平台不一样了。系统版本之类的都一样，显卡都是N卡。就只能一步一步排除原因，去复现了。

**Comment by kulocora** [comment]
我反过来的，V2 会报这个错，SS 不会

**Comment by linzyjx** [comment]
同样出现间歇性崩溃问题，0.9.4版本依旧
使用安装包安装到Program Files目录下

我尝试一下使用便携模式

**Comment by jaxguo** [comment]
我是笔记本电脑,什么都不干,放一段时间就会崩溃.不管开不开proxy都会崩.开启崩溃的概率高点

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.5

做了一些调整，可以试下有没有解决

**Comment by jaxguo** [comment]
挂了两天,没有崩溃,感谢,问题应该是解决了!

**Comment by Saya-g** [comment]
0.9.5使用两天未发生崩溃，大概是解决了

**Comment by Bi-lank** [comment]
0.9.5 使用后未出现崩溃现象，问题应该解决了，感谢！
