### ISSUE TITLE
默认带个Rule会不会更好

### ISSUE THREAD

**Issue by zddewe** [Fndroid/clash_for_windows_pkg#56]
这个rule，作者fndroid附带更新就好了（其实rule也没啥太多更新的）。让用户只需配置节点信息就够了。
弄个自定义（大神要折腾自定义rule），和小白（默认）模式，爽歪歪

**Comment by Fndroid** [comment]
没有计划做，嫌规则麻烦可以直接

GEOIP, CN, DIRECT
MATCH, Proxy
