### ISSUE TITLE
出错

### ISSUE THREAD

**Issue by 505e** [Fndroid/clash_for_windows_pkg#560]
![image](https://user-images.githubusercontent.com/59630693/77328273-4545b500-6d57-11ea-8da9-df44fecfe6e1.png)

**Comment by Fndroid** [comment]
点try to repair

**Comment by 505e** [comment]
点了没反应

**Comment by Fndroid** [comment]
点 Open logs folder，打开目录之后返回上一目录，删除里面的Country.mmdb文件后重启软件

**Comment by 505e** [comment]
好了
