### ISSUE TITLE
切换配置失败 ProxyGroup Proxy : 'proxies' is not a slice

### ISSUE THREAD

**Issue by starlhl** [Fndroid/clash_for_windows_pkg#561]
配置文件是直接下载更新的，应该没有问题，但这个提示好像是指文件有问题，不太理解是哪里出了问题。

PS：已试过删除所有文件，重新安装程序，更换程序版本等方法。

**Comment by Fndroid** [comment]
第一句就有问题了

**Comment by Fndroid** [comment]
哪里下载就找哪

**Comment by winmerdx** [comment]
我也是同样的问题，经常报错

**Comment by yi-Xu-0100** [comment]
@winmerdx 给出对应位置相应结构，或者替换敏感内容和密钥等内容，给出配置文件，不然没法得知是什么样的错误。

或者找配置文件提供者，让其帮忙排查

**Comment by winmerdx** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fndroid/clash_for_windows_pkg"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月9日(星期二) 晚上6:21
收件人:&nbsp;"Fndroid/clash_for_windows_pkg"<clash_for_windows_pkg@noreply.github.com&gt;;
抄送:&nbsp;"winmer"<1522461914@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Fndroid/clash_for_windows_pkg] 切换配置失败 ProxyGroup Proxy : 'proxies' is not a slice (#561)





 
@winmerdx 给出对应位置相应结构，或者替换敏感内容和密钥等内容，给出配置文件，不然没法得知是什么样的错误。
 
或者找配置文件提供者，让其帮忙排查

**Comment by winmerdx** [comment]
> @winmerdx 给出对应位置相应结构，或者替换敏感内容和密钥等内容，给出配置文件，不然没法得知是什么样的错误。
> 
> 或者找配置文件提供者，让其帮忙排查

邮箱发过去了

**Comment by yi-Xu-0100** [comment]
@winmerdx 啥，你发的哪个邮箱？

**Comment by winmerdx** [comment]
> @winmerdx 啥，你发的哪个邮箱？

![image](https://user-images.githubusercontent.com/62535410/107385126-960bfb00-6b2d-11eb-89ed-6aaf3d9642fe.png)

**Comment by yi-Xu-0100** [comment]
@winmerdx 我看了你的文件，由于你将对应部分完全删除，我也看不出是否原先有问题，你可以**替换字段内容**(如更换端口号和 server 的值等等)，保留结构再发一次看看。
我按照你的格式，添加了个示例（修改了 proxies 部分和 proxy-groups 第一个部分），可以被正常识别。下面的文件是我添加示例后的文件，你可以参考看看格式是否有问题。
注意修改文件后缀为 yml。

[test.txt](https://github.com/Fndroid/clash_for_windows_pkg/files/5952476/test.txt)

**Comment by winmerdx** [comment]
![image](https://user-images.githubusercontent.com/62535410/107393739-16365e80-6b36-11eb-9ca5-e7cf9098e6ca.png)
可以打开，打开是这个样子的，但是没有节点

**Comment by yi-Xu-0100** [comment]
@winmerdx 你是直接使用我发的示例吗？里面的节点名称是 Shadowsocks（第二排第一个），是个假的节点，作为参考格式使用。如果你没有相应的自用节点，建议自行查找如何获取。

**Comment by Lzf2640487101** [comment]
> 配置文件是直接下载更新的，应该没有问题，但这个提示好像是指文件有问题，不太理解是哪里出了问题。
> 
> PS：已试过删除所有文件，重新安装程序，更换程序版本等方法。

想问一下解决了吗，我也遇到相同问题
