### ISSUE TITLE
谷歌学术进不去请亲想办法解决一下鸭

### ISSUE THREAD

**Issue by matebookandxiaoxin** [Fndroid/clash_for_windows_pkg#565]
谷歌学术进不去请亲想办法解决一下鸭

**Comment by Fndroid** [comment]
不是软件问题，要么是规则，要么是节点

**Comment by matebookandxiaoxin** [comment]
> 不是软件问题，要么是规则，要么是节点
规则问题该怎么解决？我的显示是
your client does not have permission to get URL/from this server.(client IP address:xxxxx)
