### ISSUE TITLE
希望能改进的一些实用功能

### ISSUE THREAD

**Issue by Anonymous042973** [Fndroid/clash_for_windows_pkg#569]
我目前机场的订阅Windows端使用的是Clash，iOS端使用的是Quantumult。相比Quantumult已有的功能，我希望Clash对于订阅能增加如下功能：
一、部分更新，即只更新本地已有服务器的信息。
二、个性化，即更新时不更新对应服务器的名称。
希望Clash的开发者能在日后的更新中更新这些实用功能，感谢！

**Comment by Fndroid** [comment]
目前不考虑添加任何修改配置文件的功能
