### ISSUE TITLE
Profiles界面空白 无法订阅

### ISSUE THREAD

**Issue by lochishien** [Fndroid/clash_for_windows_pkg#570]
可能因为把profiles里的内容全删了，profiles界面一片空白，尝试添加订阅时会反馈“download profile failed with error： cannot read property “url” of null”。重启，重装，删yaml和删roaming全部没用。麻烦大佬帮帮忙。。。谢谢

**Comment by lochishien** [comment]
time="2020-03-26T12:41:08+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-03-26T12:41:08+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2020-03-26T12:41:08+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-03-26T12:41:08+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-03-26T12:41:08+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-03-26T12:41:08+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"

time="2020-03-26T12:42:15+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-03-26T12:42:15+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-03-26T12:42:15+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-03-26T12:42:15+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-03-26T12:42:15+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-03-26T12:42:15+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"

time="2020-03-26T12:53:30+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-03-26T12:53:30+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-03-26T12:53:30+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-03-26T12:53:30+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-03-26T12:53:30+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2020-03-26T12:53:30+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-03-26T13:12:05+08:00" level=info msg="HTTP proxy listening at: :7890"
time="2020-03-26T13:12:05+08:00" level=info msg="SOCKS proxy listening at: :7891"
time="2020-03-26T13:12:05+08:00" level=info msg="Redir proxy listening at: :7892"
time="2020-03-26T13:12:05+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2020-03-26T13:12:07+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-03-26T13:12:07+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-03-26T13:12:07+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-03-26T13:12:07+08:00" level=warning msg="Failed to start Redir UDP Listener: listen udp 127.0.0.1:7892: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
time="2020-03-26T13:12:11+08:00" level=info msg="HTTP proxy listening at: :7890"
time="2020-03-26T13:12:11+08:00" level=info msg="SOCKS proxy listening at: :7891"
time="2020-03-26T13:12:11+08:00" level=info msg="Redir proxy listening at: :7892"
time="2020-03-26T13:12:11+08:00" level=warning msg="Failed to start Redir UDP Listener: listen udp :7892: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
time="2020-03-26T13:12:13+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-03-26T13:12:13+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-03-26T13:12:13+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-03-26T13:12:13+08:00" level=warning msg="Failed to start Redir UDP Listener: listen udp 127.0.0.1:7892: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."

**Comment by Fndroid** [comment]
把profiles文件夹也删掉再重启试试吧

**Comment by lochishien** [comment]
> 把profiles文件夹也删掉再重启试试吧

请问profiles文件夹在哪里。。。不好意思

**Comment by Fndroid** [comment]
Geneal-Home Directroy里

**Comment by lochishien** [comment]
> Geneal-Home Directroy里

有用了！！！真的谢谢
