### ISSUE TITLE
允许局域网的连接会自动关闭。

### ISSUE THREAD

**Issue by OXERIS** [Fndroid/clash_for_windows_pkg#571]
每次windows的clash客户端重启，Allow LAN都会自动关闭，需要重新打开

**Comment by hyq3351** [comment]
在配置文件修改

**Comment by neteroster** [comment]
#489

**Comment by OXERIS** [comment]
配置文件是改过的，但是依然启动后要手动开启

NeterOster <notifications@github.com> 于 2020年3月26日周四 18:21写道：

**Comment by Fndroid** [comment]
Duplicate of #489 

没生效说明改错文件了

**Comment by OXERIS** [comment]
> Duplicate of #489
> 
> 没生效说明改错文件了

请问下General yaml的路径在哪？
