### ISSUE TITLE
Google podcast 安卓端部分订阅无法播放（WSJ What's News、The Journal等）

### ISSUE THREAD

**Issue by AcquireKnown** [Fndroid/clash_for_windows_pkg#573]
前段时间在rule的模式下可以播放，最近在rule的模式下不能播放，在globle的模式下可以播放。

**Comment by Fndroid** [comment]
安卓端？

**Comment by AcquireKnown** [comment]
> 安卓端？

对啊，安卓端，标题写了

**Comment by Fndroid** [comment]
发错地方了吧，这是windows的

**Comment by AcquireKnown** [comment]
> 
> 
> 发错地方了吧，这是windows的

补充一下，网页版的Google podcast也是这种情况，上面提到的这两个节目播放不了

**Comment by beckball** [comment]
> > 发错地方了吧，这是windows的
> 
> 补充一下，网页版的Google podcast也是这种情况，上面提到的这两个节目播放不了

既然全局下可以播放 那么是你的规则问题而不是软件问题

**Comment by AcquireKnown** [comment]
> 
> 
> > > 发错地方了吧，这是windows的
> > 
> > 
> > 补充一下，网页版的Google podcast也是这种情况，上面提到的这两个节目播放不了
> 
> 既然全局下可以播放 那么是你的规则问题而不是软件问题
但是规则我一直没有修改过，原先是可以播放的

**Comment by beckball** [comment]
> > > > 发错地方了吧，这是windows的
> > > 
> > > 
> > > 补充一下，网页版的Google podcast也是这种情况，上面提到的这两个节目播放不了
> > 
> > 
> > 既然全局下可以播放 那么是你的规则问题而不是软件问题
> > 但是规则我一直没有修改过，原先是可以播放的

规则是有你的服务商决定或者由其他转换过程修改的
如果原来可用 现在不可用 说明你现有的配置无法满足podcast的要求 需要自行寻找相应分流去满足你自己的要求

**这里是反馈软件相关问题 不是解决规则分流策略问题的 谢谢**
