### ISSUE TITLE
How to use `cfw-font-family` for changing font?

### ISSUE THREAD

**Issue by zhouzl7** [Fndroid/clash_for_windows_pkg#574]
How to use `cfw-font-family` for changing font? Can you give some example?

**Comment by chaggle** [comment]
such as open General YAML and write somewhere like 
`cfw-font-family:` 'consolas'
The font style must be in your operate system

**Comment by SpecN997** [comment]
![2020-03-27_153109](https://user-images.githubusercontent.com/13669961/77733288-94cefe00-7041-11ea-8196-6b8bb6735823.png)

**Comment by zhouzl7** [comment]
Can it support different fonts for Chinese and English simultaneously? Such as 'Arial' for English and '宋体' for Chinese.

**Comment by SpecN997** [comment]
> Can it support different fonts for Chinese and English simultaneously? Such as 'Arial' for English and '宋体' for Chinese.

seriously? what for?

**Comment by john-jane-doe** [comment]
> 
> 
> > Can it support different fonts for Chinese and English simultaneously? Such as 'Arial' for English and '宋体' for Chinese.
> 
> seriously? what for?

Personally I think i may be useful for CFW to accept **a list of fonts** to choose from (just like the `font-family` in CSS), more than just accepting two different fonts for Chinese and English characters.

For example, I want to use `Consolas` as the font of CFW, but `Consolas` does not contain Chinese characters, so Chinese characters will fall back to `宋体` by default, which is rather ugly; if CFW can accept a list of fonts, I will set the fallback font to `Microsoft YaHei UI` to make a decent user interface.

**PS:** As CFW seems to be based on Electron, it may be quite easy for CFW to support a font list.

**Comment by kingofotaku** [comment]
谁知道可以指定字体大小吗？

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/font.html
