### ISSUE TITLE
CFW v0.9.3 界面问题

### ISSUE THREAD

**Issue by john-jane-doe** [Fndroid/clash_for_windows_pkg#576]
在升级到 0.9.3 之后，CFW 界面似乎出现了一些问题：

1. 在节点列表中，每个节点所占的区域宽度似乎不再固定，节点名称不能自动折行，导致节点名称较长时会破坏一排两个节点的排列方式（如下图）；
2. Emoji 有部分不一致，如在下图中，可以看出 `Proxy` 策略组的小飞机图标 ✈ 为微软系自带 emoji（特征：有黑边），而小国旗以及 `Fastest` 策略组的小闪电图标 ⚡ 为原 CFW（v0.9.2）中所带 emoji。

附图：

<img width="653" alt="screen-capture" src="https://user-images.githubusercontent.com/62677758/77727304-f341af80-7034-11ea-8587-3e094195787b.png">

**Comment by Fndroid** [comment]
1. 目前来说是有意的，避免节点名称被遮挡
2. emoji使用的是最新twitter/emoji，如果不显示应该就是不支持了

**Comment by jmireles7** [comment]
长短不一看着好难受，如果强强要这样的话，能不能以最长的为标准统一长度。

**Comment by john-jane-doe** [comment]
> 1. 目前来说是有意的，避免节点名称被遮挡
> 2. emoji使用的是最新twitter/emoji，如果不显示应该就是不支持了

@Fndroid 然而在旧版的 CFW（如 v0.9.2，如下图所示）中，采用的策略为每个节点所占区域长度固定而高度不固定，在节点名称过长的情况下通过折行保证长度不变且节点名称不被遮挡。现在采取这样“长短不一”的策略是因为换字体之后无法采用原来的“长度固定高度可变”的策略吗？

<img width="657" alt="screen-capture-0-9-2" src="https://user-images.githubusercontent.com/62677758/77731797-921ed980-703e-11ea-9e51-5bf5b2a794d6.png">

**Comment by Fndroid** [comment]
已重传了安装包对此部分进行调整

**Comment by ASmallAnimal** [comment]
> 已重传了安装包对此部分进行调整
最新版最后的两个节点仍然框框对不齐，
且在全屏情况下多数节点框效果明显

**Comment by john-jane-doe** [comment]
@Fndroid 感谢 :pray:

（不过最后一行依然对不齐+1

<img width="515" alt="capture-0-9-3-new" src="https://user-images.githubusercontent.com/62677758/77742160-fba7e380-7050-11ea-81ec-f14756c64181.png">

**Comment by JoshDaone** [comment]
I got same issue as john-jane-doe mentioned.

**Comment by Remonli** [comment]
最后一行对不齐,逼死强迫症哇.

**Comment by auxford** [comment]
+1，0.92无此问题

**Comment by Fndroid** [comment]
下个版本修复

**Comment by wangfeng35** [comment]
强迫症受不了 23333

**Comment by john-jane-doe** [comment]
新版本 v0.9.4 已经解决问题。感谢 :pray:
