### ISSUE TITLE
这个电脑版太TM好用了，感谢

### ISSUE THREAD

**Issue by echo860** [Fndroid/clash_for_windows_pkg#578]
我做外贸生意的，每天都翻墙。手上SSR，V2Ray，蓝灯，谷歌翻墙插件一堆，到目前为止只有这个是稳的！速度相对其它几个来说是最快的，而且这个月从来没有中断过。

**Comment by aiFTong** [comment]
你好，请问这个软件在哪里啊，，我没看到打包下载的东西啊

**Comment by echo860** [comment]
> 你好，请问这个软件在哪里啊，，我没看到打包下载的东西啊

就这个论坛的exe版本啊

**Comment by Fndroid** [comment]
感谢
