### ISSUE TITLE
最新版本当系统重启，重开机后打开老是扯拐

### ISSUE THREAD

**Issue by YFTX2015** [Fndroid/clash_for_windows_pkg#579]
要不就是打不开系统代理，即使把旋钮调成打开状态，也会立即自动返回关闭状态。要不就是打开出现错误，连不起核心，自然界面也无法正常显示。

**Comment by abae136ab** [comment]
> 要不就是打不开系统代理，即使把旋钮调成打开状态，也会立即自动返回关闭状态。要不就是打开出现错误，连不起核心，自然界面也无法正常显示。
你修改过代理端口吗？

**Comment by zhouzl7** [comment]
我也遇到类似问题，软件运行一段时间后，系统代理按钮会自动变成关闭态。希望能修复。

**Comment by Fndroid** [comment]
Duplicate of #312
