### ISSUE TITLE
开机自启动后代理失败，需要重启之后才可以走代理

### ISSUE THREAD

**Issue by GoodWillChase** [Fndroid/clash_for_windows_pkg#58]
不确定是否是普遍现象。
Clash for Windows 最新版，v0.5.17。
之前几版应该也是同样情况。

**Comment by Fndroid** [comment]
开机启动成功后（通知弹出），到logs文件夹看下最新的log显示什么

**Comment by GoodWillChase** [comment]
> 开机启动成功后（通知弹出），到logs文件夹看下最新的log显示什么

抱歉，经过测试之后发现开机自启之后可以代理成功，只是需要等待时间稍微久一点。log 文件正常。

可以关闭 issue 了~
