### ISSUE TITLE
是否考虑加一个彻底关闭写磁盘日志的开关，日志等级设置为silent仍然会写一条记录

### ISSUE THREAD

**Issue by defix** [Fndroid/clash_for_windows_pkg#582]
我的用法是放在OneDrive里，多台电脑自动同步配置。但是当使用“便携方式”时，在files目录同时产生logs，log文件打开导致不能完全同步。
虽不影响使用，但是感觉要是有个写磁盘日志的开关或者可以指定到%temp%路径也是挺好的。
恳请考虑添加相关功能和特性！

日志等级设置为silent后，仍然会产生一条记录的日志文件。
>time="2020-03-30T17:48:56+08:00" level=info msg="Start initial compatible provider Proxy"

**Comment by anye1998** [comment]
你可以关闭日志写入的，把日志等级调为silent就好了

**Comment by defix** [comment]
silent还是有一条输出
`port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: silent
external-controller: '127.0.0.1:9090'
secret: ''`
> time="2020-03-30T17:48:56+08:00" level=info msg="Start initial compatible provider Proxy"

**Comment by Fndroid** [comment]
0.9.6在设置了log-level=silent之后不会生出log文件了
