### ISSUE TITLE
连接上没两秒钟就报错,点修复不行 ,必须重启软件才行

### ISSUE THREAD

**Issue by qq976457223** [Fndroid/clash_for_windows_pkg#583]
[DIRECT]"
time="2020-03-30T19:43:35+08:00" level=fatal msg="Can't load mmdb: error opening database: invalid MaxMind DB file"

**Comment by abae136ab** [comment]
> [DIRECT]"
> time="2020-03-30T19:43:35+08:00" level=fatal msg="Can't load mmdb: error opening database: invalid MaxMind DB file"

看起来是GeoIP的问题，目录里有db文件吗

**Comment by qq976457223** [comment]
安装目录吗?貌似是没找到




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "abae136ab"<notifications@github.com&gt;; 
发送时间: 2020年3月30日(星期一) 晚上8:27
收件人: "Fndroid/clash_for_windows_pkg"<clash_for_windows_pkg@noreply.github.com&gt;; 
抄送: "储依明"<976457223@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Fndroid/clash_for_windows_pkg] 连接上没两秒钟就报错,点修复不行 ,必须重启软件才行 (#583)





  
[DIRECT]"
 time="2020-03-30T19:43:35+08:00" level=fatal msg="Can't load mmdb: error opening database: invalid MaxMind DB file"
  
看起来是GeoIP的问题，目录里有db文件吗

**Comment by qq976457223** [comment]
我该怎么处理这个问题?老哥

**Comment by zhouzl7** [comment]
出这个问题是因为你更新GeoIP出错，可能没更新完。
两种解决方案：

1. 点击repair，等待半小时左右应该能重新下载好GeoIP
2. 卸载软件重新安装

**Comment by qq976457223** [comment]
好的,我试试

**Comment by Fndroid** [comment]
更新到最新版，点击try to repair修复
