### ISSUE TITLE
使用DB-ip代替MaxMind作为GEOip的数据来源

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [Fndroid/clash_for_windows_pkg#589]
**描述**
使用DB-ip代替MaxMind作为GEOip的数据来源
并且希望以月为周期自动更新数据库
https://db-ip.com/db/download/ip-to-country-lite

**其他说明**
可以参考
https://github.com/qbittorrent/qBittorrent/pull/12014/files

**Comment by Fndroid** [comment]
clash core issue, refer: https://github.com/Dreamacro/clash/issues
