### ISSUE TITLE
0.5.20版本安装后无法打开，Windows 10 1809

### ISSUE THREAD

**Issue by NestRoomPast** [Fndroid/clash_for_windows_pkg#59]
安装完成后弹出此提示，然后Clash for Windows就无法打开了![csrss_2019-01-29_21-59-13](https://user-images.githubusercontent.com/23567285/51913425-6770cb00-2411-11e9-8e8c-f5936d436d12.png)
而且最大的问题是由于安装时没有取消勾选System Proxy，这样一来电脑就上不了网了，想下载一个旧版本的安装包都不行233333

**Comment by Fndroid** [comment]
可以在系统代理设置里关闭

**Comment by Fndroid** [comment]
不能安装可以试试先完全删除旧版再安装

**Comment by NestRoomPast** [comment]
> 可以在系统代理设置里关闭

感谢提示，之前不知道这个操作
