### ISSUE TITLE
关于load balance的建议

### ISSUE THREAD

**Issue by GHinStyle** [Fndroid/clash_for_windows_pkg#591]
**描述**
最近在测试clash for windows load balance的时候，发现urltest+load balance的组合，在网络可能不那么理想的环境下，代理体验不太好。主要是因为urltest的准确性不足，导致实际线路较好的节点，在urltest的测试中延时较高，这样在load balance的使用场景下，实际优质的节点被选中的几率较低。
能否考虑 在配置使用load balance的时候，提供一个可选项，由用户决定使用 urltest、tcp延时测试或是纯粹随机的策略。我相信这将会提升cfw的load balance使用体验。
谢谢！

**其他说明**
无。

**Comment by tea1111980** [comment]
url-test 和 fallback 还有 load-balance 这三个类型的功能都是自动的，唯独select类型是手动选择的，请自行组合需要的类型即可达到你想实现的目标。

#### 例如：策略组
Proxy Group:
- name: Proxy_Num1_FallBack
  type: fallback     ## 自动类型，不可手动选择。balance跟类型相同
  proxies:
        - DIRECT
        - HK
        - TW
        - JP

- name: Proxy_Num2_Url_Test
  type: url-test    ## 自动类型，不可手动选择。balance跟类型相同
  proxies:
        - DIRECT
        - HK
        - TW
        - JP

- name: Proxy_Num3_Manual
  type: select    ## 手动类型，可自行手动选择指定 自己需要的代理服来使用。
  proxies:
        - HK
        - TW
        - JP

这样就可以手动选择你需要的代理服了。

**Comment by GHinStyle** [comment]
> url-test 和 fallback 还有 load-balance 这三个类型的功能都是自动的，唯独select类型是手动选择的，请自行组合需要的类型即可达到你想实现的目标。
> 
> #### 例如：代理组
> ```
> Proxy Group:
>   - name: Proxy_Num1_FallBack
>     type: fallback    ## 自动类型，不可手动选择。balance跟类型相同，这个与select类型作用相反，它会根据自身的功能，按需自动跳代理服。
>     proxies:
>           - DIRECT
>           - HK
>           - TW
>           - JP
> 
>   - name: Proxy_Num2_Url_Test
>     type: url-test    ## 自动类型，不可手动选择。balance跟类型相同，这个与select类型作用相反，它会根据自身的功能，按需自动跳代理服。
>     proxies:
>           - DIRECT
>           - HK
>           - TW
>           - JP
> 
>   - name: Proxy_Num3_Manual
>     type: select    ## 手动类型，可自行手动选择指定 自己需要的代理服来使用。选择代理服之后是固定死的，它不会乱跳到你没有选择的代理服上。
>     proxies:
>           - HK
>           - TW
>           - JP
> ```
> 
> #### 策略组
> ```
> Rule:
>       - DOMAIN-SUFFIX,163.com,DIRECT  ##直连，不走任何代理的网址
>       - DOMAIN-SUFFIX,baidu.com,DIRECT
>       - DOMAIN-SUFFIX,sina.com,DIRECT
> 
>       - DOMAIN-SUFFIX,netflix.com,Proxy_Num2_Url_Test   ## 走自动类型的url-test代理，不可选择一切由url-test的实际功能提供自动选择
>       - DOMAIN-SUFFIX,youtube.com,Proxy_Num3_Manual  ## 走手动类型的代理，也就是你自己选择的代理
>       - DOMAIN-SUFFIX,facebook.com, Proxy_Num1_FallBack  ## 走自动类型的fallback代理，不可选择一切由fallback的实际功能提供自动选择
> ……………………  以此类推。
> ```
> 
> 这样就可以手动选择你需要的代理服了。
> 
> * 并且你所有的代理服，都会按照上面的自动类型，自行选择它们相应功能的节点。
> * 代理组 只是设置你代理服的使用方式，但具体真正用来使用这些代理服的，是你自己在策略组里，指定相应的：
>   网址 + 代理组name名称。
> * 并且只有select类型里面的节点是可以手动选择的，其它的都是自动并无法自行选择。
> 
> 我不知道，我这样理解对不对，仅供参考。

你没明白我的意思 哈哈 我的意思是即使你选load balance cfw 其实还是基于urltest的结果去筛选 而不是随机或轮询

**Comment by Fndroid** [comment]
> 我的意思是即使你选load balance cfw 其实还是基于urltest的结果去筛选 而不是随机或轮询

这个结论是怎么得出的？load-balance为什么会给予url-test？

**Comment by GHinStyle** [comment]
因为我观察connection里面 总是延时低的 被选中

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Fndroid <notifications@github.com>
发送时间: Wednesday, April 1, 2020 11:49:41 AM
收件人: Fndroid/clash_for_windows_pkg <clash_for_windows_pkg@noreply.github.com>
抄送: GHinStyle <orgiraffe@msn.com>; Author <author@noreply.github.com>
主题: Re: [Fndroid/clash_for_windows_pkg] 关于load balance的建议 (#591)


我的意思是即使你选load balance cfw 其实还是基于urltest的结果去筛选 而不是随机或轮询

这个结论是怎么得出的？load-balance为什么会基于url-test？

―

**Comment by Fndroid** [comment]
clash里的load-balance是根据顶级域来分派连接的，如果多个域名的顶级域是一样就会分到同一个节点里

不同顶级域才会按顺序分到不同节点

**Comment by GHinStyle** [comment]
好的 明白了
