### ISSUE TITLE
cfw-latency-timeout的问题

### ISSUE THREAD

**Issue by 643406834** [Fndroid/clash_for_windows_pkg#592]
修改了clash默认的延迟时间，软件默认是30000
修改为：cfw-latency-timeout: 600，再使用clash的test-url，使用默认设置，软件自动每隔10分钟检查线路，会出现超过600的节点；如果用手动点击一键测试则没有超600的节点，超600的节点显示为timeout
![批注 2020-04-01 090356](https://user-images.githubusercontent.com/39716940/78088777-c7894580-73f7-11ea-9bff-5b9f75441b38.png)
![批注 2020-04-01 090513](https://user-images.githubusercontent.com/39716940/78088815-e8ea3180-73f7-11ea-8d0f-fb7adff08a4c.png)
![1111](https://user-images.githubusercontent.com/39716940/78088851-09b28700-73f8-11ea-82c4-9109b33d978a.png)

**Comment by Fndroid** [comment]
``cfw-latency-url``和``cfw-latency-timeout``都是手动测试用的，自动测试会按照配置文件配置的url和timeout

**Comment by 643406834** [comment]
> `cfw-latency-url`和`cfw-latency-timeout`都是手动测试用的，自动测试会按照配置文件配置的url和超时

大神，怎样修改配置文件配置的url和超时
