### ISSUE TITLE
自定义规则在更新订阅后消失

### ISSUE THREAD

**Issue by poemsiu** [Fndroid/clash_for_windows_pkg#593]
**描述**
自行添加规则后，一旦更新了订阅，自定义规则就会消失不见。建议优化为自定义规则在每次更新订阅后再自动加进配置文件中。

**其他说明**
无

**Comment by Fndroid** [comment]
所谓的更新，只是从服务器下载配置文件。做不到记住你改了什么内容然后再加回去并且保证没问题

**Comment by strawhatboy** [comment]
分享个python脚本，可以在更新订阅的时候自动合并订阅的配置和自定义配置...o(*￣▽￣*)o [https://github.com/strawhatboy/clash-for-win-self-rules-appender](https://github.com/strawhatboy/clash-for-win-self-rules-appender)

**Comment by beckball** [comment]
这个项目就为你的需求而生
https://github.com/tindy2013/subconverter

**Comment by strawhatboy** [comment]
> 这个项目就为你的需求而生
> https://github.com/tindy2013/subconverter

妙，妙啊！

**Comment by wonderhj** [comment]
请问加哪里可以保证更新订阅后自己加的规则不消失啊。
