### ISSUE TITLE
clash core已更新v2ray的tcp+http混淆，望下一版更新一下

### ISSUE THREAD

**Issue by Rasta0501** [Fndroid/clash_for_windows_pkg#597]
如题，https://github.com/Dreamacro/clash/blob/dev/README.md
示例配置已经添加了写法。

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.4

**Comment by Rasta0501** [comment]
![Snipaste_2020-04-03_12-42-53](https://user-images.githubusercontent.com/25950481/78324930-b7fd2e80-75a8-11ea-994f-dee9cd2ef176.png)
已经是0.9.4了，tcp没有看到可以配置header的

**Comment by Rasta0501** [comment]
![Snipaste_2020-04-03_12-45-03](https://user-images.githubusercontent.com/25950481/78325007-f85cac80-75a8-11ea-82a7-92a1eab47e6f.png)
已经是0.9.4了，tcp没有header可以配置
