### ISSUE TITLE
无法连接clash core

### ISSUE THREAD

**Issue by BoyceLig** [Fndroid/clash_for_windows_pkg#598]
**信息**
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
界面显示could not connect to clash core，我用之前的版本也提示这个，我上次关机忘记关闭代理，再打开软件就无法连接内核，右下角图标变成黄色小猫。

**复现**
1. 进入软件
2. 点击代理
3. 强制关闭软件
4. 再次打开触发问题

**预期行为**
清晰地描述期望看到的行为

**截图**
![image](https://user-images.githubusercontent.com/49801599/78319936-dfe59580-759a-11ea-9d84-d1ecbbc849f3.png)
![image](https://user-images.githubusercontent.com/49801599/78319945-e2e08600-759a-11ea-81b9-b64995630708.png)

**其他说明**
log
time="2020-04-03T11:08:06+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-04-03T11:08:06+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-04-03T11:08:06+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-04-03T11:08:06+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-04-03T11:08:06+08:00" level=error msg="External controller error: listen tcp 127.0.0.1:9090: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
time="2020-04-03T11:08:06+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-04-03T11:08:06+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2020-04-03T11:08:06+08:00" level=info msg="[TCP] 127.0.0.1:14728 --> 91.108.56.111 match Match using DIRECT"
time="2020-04-03T11:08:06+08:00" level=info msg="[TCP] 127.0.0.1:14729 --> 91.108.56.111 match Match using DIRECT"
time="2020-04-03T11:08:06+08:00" level=info msg="[TCP] 127.0.0.1:14730 --> 91.108.56.111 match Match using DIRECT"
time="2020-04-03T11:08:06+08:00" level=info msg="[TCP] 127.0.0.1:14731 --> 91.108.56.111 match Match using DIRECT"
time="2020-04-03T11:08:06+08:00" level=info msg="[TCP] 127.0.0.1:14737 --> raw.githubusercontent.com match Match using DIRECT"
time="2020-04-03T11:08:09+08:00" level=info msg="[TCP] 127.0.0.1:14742 --> note.youdao.com match Match using DIRECT"

**Comment by Fndroid** [comment]
其他界面有显示吗？比如Proxies

**Comment by BoyceLig** [comment]
Proxies没显示  别的有

**Comment by Fndroid** [comment]
进``C:\Users\{用户名}\AppData\Roaming\clash_win\logs``里，把renderer.log文件发一下

**Comment by BoyceLig** [comment]
[renderer.log](https://github.com/Fndroid/clash_for_windows_pkg/files/4424867/renderer.log)

**Comment by Fndroid** [comment]
你的9090端口被占用了，所以core启动不了，试下换一个大点的端口

**Comment by Fndroid** [comment]
大概是有其他占用9090的软件启动比较快，然后core拿不到，就失败了

**Comment by BoyceLig** [comment]
好的  完美解决了

**Comment by ZR1314** [comment]
我也是连接不上内核不知道怎么搞，无法连接Clash内核
time="2021-03-30T02:40:41+08:00" level=info msg="Start initial compatible provider Proxy"
time="2021-03-30T02:40:41+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2021-03-30T02:40:41+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2021-03-30T02:40:41+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2021-03-30T02:40:41+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2021-03-30T02:40:41+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2021-03-30T02:41:51+08:00" level=info msg="Start initial compatible provider Proxy"
time="2021-03-30T02:41:51+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2021-03-30T02:41:51+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2021-03-30T02:41:51+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2021-03-30T02:41:51+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2021-03-30T02:41:51+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2021-03-30T02:42:33+08:00" level=info msg="Start initial compatible provider Proxy"
time="2021-03-30T02:42:33+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2021-03-30T02:42:33+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2021-03-30T02:42:33+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2021-03-30T02:42:33+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2021-03-30T02:42:33+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2021-03-30T02:43:41+08:00" level=info msg="Start initial compatible provider Proxy"
time="2021-03-30T02:43:41+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2021-03-30T02:43:41+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2021-03-30T02

**Comment by ZR1314** [comment]
> 我也是连接不上内核不知道怎么搞，无法连接Clash内核
> time="2021-03-30T02:40:41+08:00" level=info msg="Start initial compatible provider Proxy"
> time="2021-03-30T02:40:41+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
> time="2021-03-30T02:40:41+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
> time="2021-03-30T02:40:41+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
> time="2021-03-30T02:40:41+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
> time="2021-03-30T02:40:41+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
> time="2021-03-30T02:41:51+08:00" level=info msg="Start initial compatible provider Proxy"
> time="2021-03-30T02:41:51+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
> time="2021-03-30T02:41:51+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
> time="2021-03-30T02:41:51+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
> time="2021-03-30T02:41:51+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
> time="2021-03-30T02:41:51+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
> time="2021-03-30T02:42:33+08:00" level=info msg="Start initial compatible provider Proxy"
> time="2021-03-30T02:42:33+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
> time="2021-03-30T02:42:33+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
> time="2021-03-30T02:42:33+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
> time="2021-03-30T02:42:33+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
> time="2021-03-30T02:42:33+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
> time="2021-03-30T02:43:41+08:00" level=info msg="Start initial compatible provider Proxy"
> time="2021-03-30T02:43:41+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
> time="2021-03-30T02:43:41+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
> time="2021-03-30T02

可以帮一下忙吗
