### ISSUE TITLE
Windows10 1809下无法使用

### ISSUE THREAD

**Issue by aluo-blog** [Fndroid/clash_for_windows_pkg#60]
连续打开好几次，logs都是下面这样：
```
time="2019-01-30T08:51:31+08:00" level=info msg="Can't find MMDB, start download"
time="2019-01-30T08:51:31+08:00" level=fatal msg="Initial configuration directory error: Can't download MMDB: Get http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz: dial tcp 104.16.38.47:80: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."
```
用管理员身份运行也没用。另外还无法导入配置，确定yaml文件是有效的。并且在`profiles`的编辑框里可以看到代理列表。但是一旦点击配置文件尝试导入，就会提示`Unable to reload this configuration file.Please try to correct the error in text mode!`

**Comment by Fndroid** [comment]
初始化失败了，下载一下这个文件到C:\Users\用户名\.config\clash目录里，https://github.com/Fndroid/clash_for_windows_pkg/raw/master/Country.mmdb

**Comment by aluo-blog** [comment]
好的，问题已解决，谢谢：）
