### ISSUE TITLE
有没有服务器负载均衡功能？

### ISSUE THREAD

**Issue by TplusSs** [Fndroid/clash_for_windows_pkg#601]
**描述**
有的话想问下怎么开启，如果没有希望增加一个，像ShadowsockSR里的负载均衡，可以自动切换可用节点。
**其他说明**
其他补充内容

**Comment by chenyang12315** [comment]
请仔细看过文档，或者Google之后再考虑开Issue

![image](https://user-images.githubusercontent.com/30497926/78330853-9b74ec80-75d0-11ea-9c77-3e4f52b8ac8c.png)

[https://docs.cfw.lbyczf.com/contents/ui/proxies.html](url)

[https://github.com/Fndroid/jsbox_script/wiki/%E5%85%B3%E4%BA%8E%E7%AD%96%E7%95%A5%E7%BB%84%E7%9A%84%E7%90%86%E8%A7%A3](url)
