### ISSUE TITLE
CFW 0.9.4 Vmess+TCP+TLS 无法正常握手

### ISSUE THREAD

**Issue by chenyang12315** [Fndroid/clash_for_windows_pkg#602]
**信息**
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
在从先前版本更新至0.9.4之后，Vmess TCP+TLS 全部无法正常握手（客户端显示节点Timeout）。同节点使用0.8.X/0.9.X均可正常连通。同节点Vmess WS+TLS配置均可正常连通。

相关V2服务端日志：

> >Date&Time IP:Port rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > tls: first record does not look like a TLS handshake

V2-Core服务端版本：4.23.1 for linux 64

复现：
问题在多个Vmess TCP+TLS节点上复现，尚不清楚是否与0.9.4新版Clash Core有关。已排除墙/V2服务端本身问题（客户端/服务端均在国外）。0.9.3及之前版本，CFA等其他Clash客户端均未发现有相同问题。

**截图**
服务端：
![Screenshot 2020-04-03 172113](https://user-images.githubusercontent.com/30497926/78330404-9ebba880-75cf-11ea-97b8-96bdcbf6c3c6.png)

**Comment by liberal-boy** [comment]
这个故障来自上游项目 [clash](https://github.com/Dreamacro/clash)，clash 已经[修复](https://github.com/Dreamacro/clash/commit/5591e15452780625bf5b569991dbbec92fae0e54)了该故障

**Comment by chenyang12315** [comment]
> 这个故障来自上游项目 [clash](https://github.com/Dreamacro/clash)，clash 已经[修复](https://github.com/Dreamacro/clash/commit/5591e15452780625bf5b569991dbbec92fae0e54)了该故障

感谢指点，手动更新过Core之后一切正常（文件后附）。CFW使用者的Clash Core一般位于：

> X:\Program Files\Clash for Windows\resources\static\files

结束Clash进程/关闭CFW之后手动替换文件即可。

[clash-win64.zip](https://github.com/Fndroid/clash_for_windows_pkg/files/4426716/clash-win64.zip)


附F大留言：“vmess tls，可以自己换一下，或者等下次更新”

**Comment by abae136ab** [comment]
> > 这个故障来自上游项目 [clash](https://github.com/Dreamacro/clash)，clash 已经[修复](https://github.com/Dreamacro/clash/commit/5591e15452780625bf5b569991dbbec92fae0e54)了该故障
> 
> 感谢指点，手动更新过Core之后一切正常（文件后附）。CFW使用者的Clash Core一般位于：
> 
> > X:\Program Files\Clash for Windows\resources\static\files
> 
> 结束Clash进程/关闭CFW之后手动替换文件即可。
> 
> [clash-win64.zip](https://github.com/Fndroid/clash_for_windows_pkg/files/4426716/clash-win64.zip)
> 
> 附F大留言：“vmess tls，可以自己换一下，或者等下次更新”

已搞定~
