### ISSUE TITLE
port 代理仍然走 rule 规则？

### ISSUE THREAD

**Issue by yi-Xu-0100** [Fndroid/clash_for_windows_pkg#603]
**信息**

- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**

为了对部分网页进行代理，我使用了 Proxy Switchyomega 对网页进行了规则匹配，让需要对网站走port 代理，但是从 log 中发现网站走完 port 代理后，任然走规则进入 rule，造成网站走 other->Domestic->DIRECT。无法完成想要对代理效果。

希望能够个人添加自定义规则集，增加或覆盖订阅提供的规则，或者 port 代理直接是走 Proxy。

我不太确定 port 代理和 socks 代理是否一定走 rule ？（以前是可以代理成功的，最近不行，我查了很久，才从 log 中确定了访问仍然走 rule ，不知道是不是和原先的规则不一样了，我想要代理的网站是 inoreader.com）

**Comment by wangfeng35** [comment]
规则选全局就直接都走代理了

不然自己定义yaml的规则

**Comment by yi-Xu-0100** [comment]
嗯，我让 other 走代理了，然后不开系统代理，浏览器还是用 Proxy Switchyomega 控制策略，没问题了。
