### ISSUE TITLE
[求助] 请问下大家 有没有办法让windows更新的流量也走cfw?

### ISSUE THREAD

**Issue by onlyJinx** [Fndroid/clash_for_windows_pkg#605]
如图所示
![image](https://user-images.githubusercontent.com/21324835/78384569-fcbab100-760c-11ea-9792-dc11ce600dc4.png)

**Comment by beckball** [comment]
1打开clash的system proxy
2Proxies改为Global

**Comment by onlyJinx** [comment]
@beckball 这个Global没办法让"Windows更新"走代理吧，那些不走ie代理的软件Global对他们都无效

**Comment by beckball** [comment]
> @beckball 这个Global没办法让"Windows更新"走代理吧，那些不走ie代理的软件Global对他们都无效

安装Tap Device 利用网卡级导流实现

**Comment by onlyJinx** [comment]
我点了install,然后提了一下管理员权限之后就没任何反映了, 也没有安装向导, 不知道正常不....
![image](https://user-images.githubusercontent.com/21324835/78472761-07d92280-776e-11ea-9c76-98c14e5ae51c.png)

**Comment by beckball** [comment]
> 我点了install,然后提了一下管理员权限之后就没任何反映了, 也没有安装向导, 不知道正常不....
> ![image](https://user-images.githubusercontent.com/21324835/78472761-07d92280-776e-11ea-9c76-98c14e5ae51c.png)

你可以在网络适配器中检查网卡是否被安装

**Comment by onlyJinx** [comment]
好像装了
![image](https://user-images.githubusercontent.com/21324835/78499871-f26ff280-7785-11ea-9b89-8ae4ba184344.png)

**Comment by onlyJinx** [comment]
今天试着更新lol, 流量好像不经过clash
![image](https://user-images.githubusercontent.com/21324835/78556772-26105280-7842-11ea-83c5-67573ca6de91.png)

**Comment by beckball** [comment]
> 好像装了
> ![image](https://user-images.githubusercontent.com/21324835/78499871-f26ff280-7785-11ea-9b89-8ae4ba184344.png)

压根都没有连接上怎么走tap网卡？
这玩家都不学不练不搜索的么？
https://github.com/Fndroid/clash_for_windows_pkg/wiki/%E6%96%B0%E7%89%88-TAP

**Comment by onlyJinx** [comment]
老哥教训的是, 看完改完配置文件后应该ok了, 谢谢....

**Comment by 2427237507** [comment]
Windows的更新是位于微软北京的服务器吧，国内走代理可能会更慢

**Comment by onlyJinx** [comment]
@2427237507 让他走clash不是因为更新慢不慢的问题, 是因为他有时候在我玩游戏的时候后台偷偷跟新然后我容易卡, 所以有时候我要reject掉这些流量.....
