### ISSUE TITLE
clash退出后，设置里面的代理不会跟着关闭！

### ISSUE THREAD

**Issue by denghuotongming** [Fndroid/clash_for_windows_pkg#606]
clash退出后，设置>>网络和Intelnet>>代理，这里面的开关不会复原！这样有个问题，clash退出了，开关没跟着关闭，会导致网页打不开了，每次都的手动去设置里把代理开关关闭，有点麻烦！！

**Comment by youngj78** [comment]
原来的版本是有这个问题，现在最新版还没解决么。

**Comment by boatz2002** [comment]
嗯，的确有这个问题。

**Comment by Fndroid** [comment]
点右下角图标，选择exit退出，会关闭系统代理

**Comment by denghuotongming** [comment]
> 点右下角图标，选择exit退出，会关闭系统代理

不行的，quit和force quit都不行

**Comment by Fndroid** [comment]
那能在Clash for Windows里启动system proxy吗

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/312
