### ISSUE TITLE
输入框中的字体没有跟随cfw-font-family

### ISSUE THREAD

**Issue by AzunyanDaisuki** [Fndroid/clash_for_windows_pkg#607]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [ ] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题
更改 cfw-font-family 字段后，输入框中的文字字体并没有随着改变，而是使用了默认的衬线字体
**复现**
请描述复现问题的步骤:
1. 修改 cfw-font-family 字段

**预期行为**
清晰地描述期望看到的行为
所有文字的字体随 cfw-font-family 字段改变
**截图**
如果可以，请提供对应问题的截图
![image](https://user-images.githubusercontent.com/18110400/78482195-9a7ebf00-7778-11ea-9eae-2267aee00db9.png)

**其他说明**
其他补充内容 截图中设置的字体是 Noto Sans CJK SC

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.5
