### ISSUE TITLE
AdGuard7.3桌面版无法过滤广告

### ISSUE THREAD

**Issue by Mon5ter777** [Fndroid/clash_for_windows_pkg#608]
#194 
从过去的issue里找到了和我一样情况的，但是我AdGuard打开了filter localhost之后仍然无法过滤广告。
请问该如何解决。
另外clash与adguard同时打开时会导致访问网页很慢(clash内没有去广告规则)，但是单独打开adguard或者clash时访问网页正常，请问是什么原因。

**Comment by Fndroid** [comment]
我没有用adguard桌面版了，所以只能看看其他人有没有办法了

**Comment by Mon5ter777** [comment]
> 我没有用adguard桌面版了，所以只能看看其他人有没有办法了

我用机场订阅地址和api转换的地址试验了一下发现机场订阅地址可以过滤广告
在api订阅地址最后加上
```
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,17.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
```
就好了
但是adguard和clash同时打开时，网页加载速度变慢还没找到解决方法。

**Comment by 2020LeftistStrikeBack** [comment]
在Adguard高级设置里打开“过滤localhost连接”就可以了，**关键在于：**在完成这项设置后，需要关闭Clash并重新打开才能生效，以后也都得保证Clash在Adguard之后运行，而不是之前。目前我用的版本是7.4 RC1。
#194

**Comment by ous50** [comment]
我在adguard那边开了个issue，链接如下，大家可以过来看看https://github.com/AdguardTeam/AdguardFilters/issues/62089

**Comment by kingforme** [comment]
1.在Adguard高级设置里打开“过滤localhost连接
2.在完成这项设置后，需要关闭Clash并重新打开才能生效，以后也都得保证Clash在Adguard之后运行(让adguard随系统启动)
3.禁用Block Teredo
![屏幕截图 2021-03-29 222001](https://user-images.githubusercontent.com/62692476/112850871-002c2f80-90dd-11eb-8276-4c7c7e5b57fc.png)
