### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by a823827920** [Fndroid/clash_for_windows_pkg#609]
![image](https://user-images.githubusercontent.com/34757112/78551480-61a61f00-7838-11ea-9aaf-783ae3cea670.png)

打开就一直是这样，换了几个版本也没法用。

**Comment by Fndroid** [comment]
节点连不上

**Comment by a823827920** [comment]
什么意思，我就刚下的软件，还没有添加配置文件，我试了就算导入配置文件也不成功，就一直这样。

**Comment by Fndroid** [comment]
默认配置里没有叫star发节点

**Comment by a823827920** [comment]
好了，感谢。原来是一年前用过一次这个软件后来删了之后配置文件还有残留。
