### ISSUE TITLE
uwp版qq无法正常使用

### ISSUE THREAD

**Issue by neo16ye** [Fndroid/clash_for_windows_pkg#61]
打开clash的情况下，用fiddler对qq破除uwp限制，此时qq里图片无法加载，如果不破除uwp限制，qq无法联网，只有关掉clash才能正常使用。

**Comment by Fndroid** [comment]
在config.yml文件里的``cfw-bypass``的``localhost``前添加一个``*.qq.com``，重启软件，试试

**Comment by neo16ye** [comment]
> 在config.yml文件里的`cfw-bypass`的`localhost`前添加一个`*.qq.com`，重启软件，试试

按照设置，QQ已走直连，还是无法联网。

**Comment by Fndroid** [comment]
重启cfw了么

**Comment by neo16ye** [comment]
> 重启cfw了么

重启了啊

**Comment by Fndroid** [comment]
关闭系统代理，清楚QQ的loopback限制

**Comment by neo16ye** [comment]
好像有效，感谢

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/wiki/UWP%E5%BA%94%E7%94%A8%E8%81%94%E7%BD%91
