### ISSUE TITLE
订阅地址时一直报错could not switch to this profile

### ISSUE THREAD

**Issue by Lucas798** [Fndroid/clash_for_windows_pkg#610]
安装完成后，订阅地址一直报这个错误，该怎么办啊？
![image](https://user-images.githubusercontent.com/63257061/78591073-7523ab00-7875-11ea-8bce-af1d56502e2d.png)

**Comment by ktt711** [comment]
我也是这个问题，请问你解决了吗？

**Comment by Fndroid** [comment]
Duplicate of #318
