### ISSUE TITLE
SSR的配置一直Timeout,用其他软件打开正常

### ISSUE THREAD

**Issue by tujidelv** [Fndroid/clash_for_windows_pkg#612]
**信息**
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
SSR的配置貌似不生效，是type写错了吗
![image](https://user-images.githubusercontent.com/18022617/78636357-c31eca00-78da-11ea-87ff-3409dd059d26.png)

**Comment by tujidelv** [comment]
别沉啊大佬们，ssr如何配置呢

**Comment by Fndroid** [comment]
不支持ssr
