### ISSUE TITLE
怎样配置Microsoft To Do这个应用绕过代理

### ISSUE THREAD

**Issue by wbmvincent** [Fndroid/clash_for_windows_pkg#613]
请问怎样配置这个应用直连？用抓包工具把该应用所有的链接请求都添加到规则里了还是无法同步，关闭或退出clash之后就正常

**Comment by hyq3351** [comment]
![image](https://user-images.githubusercontent.com/54705050/78644571-a7222500-78e8-11ea-9684-7d60064b782d.png)
https://github.com/Fndroid/clash_for_windows_pkg/wiki/UWP%E5%BA%94%E7%94%A8%E8%81%94%E7%BD%91
Wiki看看？？？？

**Comment by Fndroid** [comment]
General -> UWP Loopback Helper -> Exempt All 打勾 -> Save Changes

**Comment by luzhengli** [comment]
> 

Thanks!!!
