### ISSUE TITLE
youtube等视频网站访问问题

### ISSUE THREAD

**Issue by fadeorfake** [Fndroid/clash_for_windows_pkg#616]
使用最新release的Clash For Windows。

使用一样的线路和VPS（GCP 台湾机房，同一个VPS)。 如果用V2RayN客户端访问页面正常，如果用CFW访问，规则通过DOMAIN KEYWORD [YOUTUBE],指定走一样的VPS, 打开网站页面后，页面上的视频的小样不显示，但是点击播放时可以的。

在LOG文件看过确定规则生效的。请问哪位大大给建议如何改善？

谢谢！

**Comment by zm24120** [comment]
规则不全或者去广告干掉了~

**Comment by fadeorfake** [comment]
我也是这么想，所以在某考研网站上出现类似问题就不断查log，把没有的规则补回去，能解决。但是youtube的刷了许多次还没找到缺少的规则。继续找下看吧。

**Comment by fadeorfake** [comment]
在日志文件找不到线索，后来试试打开页面后检查页面元素，发现有域名YTIMG.COM下的许多资源加载失败，把YTIMG加入DOMAINKEYWORD，Proxy的规则后解决了。
