### ISSUE TITLE
无法启动system proxy，Port和socks port均显示为0

### ISSUE THREAD

**Issue by 666keke** [Fndroid/clash_for_windows_pkg#617]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
偶尔会出现无法启动system proxy，Port和socks port均显示为0，重启后解决，退出或强行退出均无法解决。

**复现**
间歇性，常见于刚刚开机时，开机期间不会，或极少出现。

**预期行为**
正常启动系统代理

**截图**
![SharedScreenshot](https://user-images.githubusercontent.com/20734123/78776881-1f611700-79cb-11ea-945a-a5156b1871f2.jpg)

**其他说明**
日志文件
time="2020-04-08T18:54:58+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-04-08T18:54:58+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-04-08T18:54:58+08:00" level=error msg="Start HTTP server error: listen tcp 127.0.0.1:7890: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2020-04-08T18:54:58+08:00" level=error msg="Start SOCKS5 server error: listen tcp 127.0.0.1:7891: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2020-04-08T18:54:58+08:00" level=error msg="Start Redir server error: listen tcp 127.0.0.1:7892: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2020-04-08T18:54:58+08:00" level=info msg="Start initial compatible provider load-balance"
time="2020-04-08T18:54:58+08:00" level=info msg="Start initial compatible provider Unlockneteasemusic"
time="2020-04-08T18:54:58+08:00" level=info msg="Start initial compatible provider fallback-auto"
time="2020-04-08T18:54:58+08:00" level=info msg="Start initial compatible provider Netflix"
time="2020-04-08T18:54:58+08:00" level=info msg="Start initial compatible provider otherGlobalTV"
time="2020-04-08T18:54:58+08:00" level=info msg="Start initial compatible provider Steam"
time="2020-04-08T18:54:58+08:00" level=info msg="Start initial compatible provider 巴哈姆特动画疯"
time="2020-04-08T18:54:58+08:00" level=info msg="Start initial compatible provider HBOGO"
time="2020-04-08T18:54:58+08:00" level=info msg="Start initial compatible provider Speedtest"
time="2020-04-08T18:54:58+08:00" level=info msg="Start initial compatible provider auto"
time="2020-04-08T18:54:58+08:00" level=info msg="Start initial compatible provider line"
time="2020-04-08T18:54:58+08:00" level=info msg="Start initial compatible provider AdBlock"
time="2020-04-08T18:54:58+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-04-08T18:54:58+08:00" level=info msg="Start initial compatible provider GlobalMusic"

**Comment by impoint** [comment]
me too!

**Comment by sambell361** [comment]
我也遇到了同样的问题，从我的日志来看我估计是默认的7890端口被占用了，检查了我的网络发现`clash for windows`未启动时这个端口并没有被占用，而当`clash for windows`启动后会多出一个名为`svhost`的进程，他的远程端口就是7890。
下面是日志和截图。
![20200409080236](https://user-images.githubusercontent.com/30614073/78844670-00996980-7a39-11ea-9965-e9666405474b.png)

> time="2020-04-09T08:04:50+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-04-09T08:04:50+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-04-09T08:04:50+08:00" level=error msg="Start HTTP server error: listen tcp 127.0.0.1:7890: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2020-04-09T08:04:50+08:00" level=error msg="Start SOCKS5 server error: listen tcp 127.0.0.1:7891: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2020-04-09T08:04:50+08:00" level=error msg="Start Redir server error: listen tcp 127.0.0.1:7892: bind: An attempt was made to access a socket in a way forbidden by its access permissions."

**Comment by Fndroid** [comment]
General YAML里把port和sock-port换成更高位端口试试

**Comment by 666keke** [comment]
> General YAML里把port和sock-port换成更高位端口试试

实测无效

**Comment by sambell361** [comment]
我发现开机时cfw的启动时间相较于其他软件较晚，能否使cfw提前启动以避免端口被占用问题？

**Comment by Fndroid** [comment]
> 我发现开机时cfw的启动时间相较于其他软件较晚，能否使cfw提前启动以避免此类端口被占用问题？

换个端口号不就行了

**Comment by 666keke** [comment]
> > 我发现开机时cfw的启动时间相较于其他软件较晚，能否使cfw提前启动以避免此类端口被占用问题？
> 
> 换个端口号不就行了

但是更换无用，不打开cfw也不会有端口占用

**Comment by impoint** [comment]
是的，我也进行过尝试更改配置文件中的端口号，但是打开软件后，端口处依旧是0，而且以管理员身份运行程序也没有效果。

**Comment by beckball** [comment]
> > General YAML里把port和sock-port换成更高位端口试试
> 
> 实测无效

有其他程序占用端口号 请先更改yaml内的端口 而后再启动clash

**Comment by zhx79513** [comment]
兄弟解决了吗？我也是所有端口都显示为0，然后log中也报这种错误，然后用netstat查看了端口并没有被占用。

**Comment by zhx79513** [comment]
执行netsh winsock reset之后重启就正常了

**Comment by zhx79513** [comment]
我的找到原因了，我安装了Docker for Windows，这软件用的虚拟机是Hyper-V，Hyper-V会保留很多个端口段来备用，处于备用端口段的端口无法被其他应用程序使用。  
使用 **netsh interface ipv4 show excludedportrange protocol=tcp** 可以查看被保留的端口段。

**Comment by 666keke** [comment]
> 我的找到原因了，我安装了Docker for Windows，这软件用的虚拟机是Hyper-V，Hyper-V会保留很多个端口段来备用，处于备用端口段的端口无法被其他应用程序使用。
> 使用 **netsh interface ipv4 show excludedportrange protocol=tcp** 可以查看被保留的端口段。

感谢，实测关闭hyper-v并删除相关网卡后一切正常，应该是这个问题

**Comment by andylizi** [comment]
如果不想关闭 Hyper-V，也可以使用这里面提到的方法：shadowsocks/shadowsocks-windows#1835

**Comment by wenq77** [comment]
> General YAML里把port和sock-port换成更高位端口试试

换了后解决了

**Comment by erbanku** [comment]
我也记录一下解决过程吧（Windows 11）
正如 @zhx79513 所说，端口确实被保留占用了，General YAML里把port和sock-port换成更高端口可解。
如果不想换端口，可以在Powershell管理员模式下运行方命令，并重启电脑可解。
把7890端口释放出来：
`netsh int ipv4 add excludedportrange protocol=tcp startport=7890 numberofports=1`
把7890端口释放出来（可选，因为9090端口本来就没有问题）：
`netsh int ipv4 add excludedportrange protocol=tcp startport=9090 numberofports=1`
