### ISSUE TITLE
0.93更新到0.94后无法使用

### ISSUE THREAD

**Issue by Altrla** [Fndroid/clash_for_windows_pkg#618]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
Windows10 1909 
0.93更新到0.94后，节点检测延时全是timeout，无法使用，系统代理，国内国外网页全部打不开，提示请检查代理设置，试过重装，下载安装包和压缩包版本都是一样，换回0.93后恢复正常.
没有开启TAP模式。

**Comment by Fndroid** [comment]
看下是不是这个问题


https://github.com/Fndroid/clash_for_windows_pkg/issues/602

**Comment by agateriver** [comment]
same problem confirmed!

**Comment by agateriver** [comment]
> 看下是不是这个问题 #602

Followed #602. Resovled.

**Comment by Altrla** [comment]
> 看下是不是这个问题 #602

应该是的，等下个版本更新吧。谢谢！
