### ISSUE TITLE
订阅连接报错Could not switch to this profile

### ISSUE THREAD

**Issue by zhangeden** [Fndroid/clash_for_windows_pkg#619]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
订阅连接后报错“Could not switch to this profile!  proxy0:unsupport proxy type:ssr”

**复现**
每次订阅均会出现

**Comment by Fndroid** [comment]
不支持ssr
