### ISSUE TITLE
0.9.3更换emoji后~部分常用表情丢失~

### ISSUE THREAD

**Issue by zm24120** [Fndroid/clash_for_windows_pkg#621]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
0.9.3-0.9.4版本，更换png的emoji为svg后，部分常用表情丢失
希望尽量补回来

**截图**
![图片](https://user-images.githubusercontent.com/53201527/78871502-5f330780-7a7a-11ea-963c-a3e471040385.png)

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.5

**Comment by zm24120** [comment]
Thanks~Get it
