### ISSUE TITLE
0.8版本升级0.9版本后所有节点ping不通。。。

### ISSUE THREAD

**Issue by zxz25** [Fndroid/clash_for_windows_pkg#622]
0.8版本升级0.9版本后所有节点ping不通。。。刚开始以为是节点问题，后来发现另一台老版本的电脑上能通，降级后发现是版本问题。现在不敢升级了，大概会是什么问题呢？？？

**Comment by Fndroid** [comment]
vmess节点？0.9.4版本？

**Comment by zxz25** [comment]
对的，vmess节点转的clash节点

**Comment by Fndroid** [comment]
更新0.9.5
