### ISSUE TITLE
大佬们帮我看看这个怎么回事，是那个地方错误了

### ISSUE THREAD

**Issue by TIAN77** [Fndroid/clash_for_windows_pkg#623]
![KVXY0EI4L(5@3@S6I$~~WY3](https://user-images.githubusercontent.com/63409555/78953157-86d1b080-7b0a-11ea-83f7-a76f71af5052.png)
![KM%CE 3R6 `X%WBQP75HLA8](https://user-images.githubusercontent.com/63409555/78953161-8a653780-7b0a-11ea-94e7-5a9a52c20c47.png)

**Comment by Fndroid** [comment]
系统里没有打开yaml格式文件的软件
