### ISSUE TITLE
系统代理无法开启，开启后自动关闭

### ISSUE THREAD

**Issue by Mr-Liu1996** [Fndroid/clash_for_windows_pkg#626]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题

**复现**
请描述复现问题的步骤:
1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
清晰地描述期望看到的行为

**截图**
如果可以，请提供对应问题的截图

**其他说明**
其他补充内容

**Comment by Mr-Liu1996** [comment]
。

**Comment by Mr-Liu1996** [comment]
用了0.9.3 0.9.4都是这个问题

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/312
