### ISSUE TITLE
0.9.4升级0.9.5后，同一配置文件无法使用。

### ISSUE THREAD

**Issue by jimmygiven** [Fndroid/clash_for_windows_pkg#628]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
升级并安装0.9.5后，原有配置文件无法使用。退回至0.9.4可正常使用。

**复现**
请描述复现问题的步骤:
1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
0.9.4可正常运行的配置文件在0.9.5正常使用。

**截图**
如果可以，请提供对应问题的截图

**其他说明**
从最新的release说明里没有看到有关配置文件格式变化的部分，如果有遗漏请提醒一下谢谢

**Comment by roytiamo** [comment]
同情况。
升级路径：0.9.3→0.9.3.1→0.9.4（补丁）→0.9.5
升级至0.9.5，更新订阅后节点全部为空。
还原至旧版本后再次获取恢复正常。

**Comment by Fndroid** [comment]
无法使用是指什么？不能切换？

**Comment by roytiamo** [comment]
> 无法使用是指什么？不能切换？

从那位兄弟原描述中“没有看到有关配置文件格式变化”，**估计**和我状况一样，都是升级0.9.5后更新订阅后节点消失。
本人问题已从服务商侧解决：增加新的UA。

**Comment by jimmygiven** [comment]
> 无法使用是指什么？不能切换？

无法在Profiles中选中配置并应用，弹出提示需要在text mode进行修改

**Comment by jimmygiven** [comment]
> > 无法使用是指什么？不能切换？
> 
> 无法在Profiles中选中配置并应用，弹出提示需要在text mode进行修改

问题解决了，之前为了TAP全局，在配置文件中写了一个DNS设置，应该是没有正确配置这一块，整个注释掉之后0.9.5就不报错了

出错的配置如下：
`# DNS 设置
dns:
   enable: true
   enhanced-mode: fake-ip # 或 redir-host
   listen: 127.0.0.1:53
   nameserver:
      - 223.5.5.5
      - 119.29.29.29
experimental:
  interface-name: Realtek PCIe GbE Family Controller # WLAN 为物理网卡名`
