### ISSUE TITLE
修改端口不生效，端口未被占用

### ISSUE THREAD

**Issue by yuzunyue** [Fndroid/clash_for_windows_pkg#629]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
我修改配置文件中的端口信息，可是并不生效，0.9.4就有这个问题，今天更新了这个问题还是存在，我查看端口并未被占用

**复现**
请描述复现问题的步骤:
1. 修改了配置文件中的端口信息，可是并未生效

**截图**
![image](https://user-images.githubusercontent.com/32872977/78969322-42a9d480-7b39-11ea-80ab-81436e4ffeef.png)
这是我配置文件中修改后的端口信息
![image](https://user-images.githubusercontent.com/32872977/78969341-50f7f080-7b39-11ea-8c33-9ca1fa3aeaa7.png)
并未生效
![image](https://user-images.githubusercontent.com/32872977/78969365-5ead7600-7b39-11ea-8e1a-73f41a180fc0.png)
这两个端口也并未被占用

**其他说明**
无

**Comment by zm24120** [comment]
没问题~你改错文件了吧~
修改这个 
![图片](https://user-images.githubusercontent.com/53201527/78972061-7daf0680-7b3f-11ea-86c8-c62627e94f4d.png)
*\Clash\resources\static\files\config.yaml

**Comment by yuzunyue** [comment]
> 没问题~ 你改错文件了吧~
> 修改这个
> ![图片](https://user-images.githubusercontent.com/53201527/78972061-7daf0680-7b3f-11ea-86c8-c62627e94f4d.png)
> *\Clash\resources\static\files\config.yaml

原来是这样，竟然是两个配置文件。。。为什么不用profiles中的配置信息
