### ISSUE TITLE
完全无法连接任何网站

### ISSUE THREAD

**Issue by dream-potatoes** [Fndroid/clash_for_windows_pkg#63]
抱歉，我的电脑可能问题有点多。 #60 中我提交了一个无法初始化的issue，今天我发现突然完全无法连接任何服务器了，即使是通过`DIRCET`模式连接，只要浏览器走了Clash的本地代理就会出现`建立安全连接失败`的情况。
![default](https://user-images.githubusercontent.com/30206355/52025119-39d57000-253e-11e9-9e99-a9958ceb0d71.png)
日志文件是这样的：
```
time="2019-01-31T09:36:13+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2019-01-31T09:36:13+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:8080"
time="2019-01-31T09:36:13+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:8081"
time="2019-01-31T09:36:13+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:8082"
......
time="2019-01-31T09:36:16+08:00" level=info msg="www.baidu.com match GEOIP using DIRECT"
time="2019-01-31T09:36:16+08:00" level=warning msg="Proxy[DIRECT] connect [www.baidu.com] error: dial tcp 183.232.231.173:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."
......
time="2019-01-31T09:36:13+08:00" level=warning msg="Proxy[Proxy] connect [127.0.0.1] error: (我的代理地址) connect error"
```
所有日志里就这两种提示，看上去像是我的服务器无法连接，但是我在手机上使用相同的服务器却没有任何问题。请帮忙解决下，谢谢。

**Comment by Fndroid** [comment]
请更新软件版本，确保配置文件里节点属性和服务端对应

**Comment by Fndroid** [comment]
根据最近的反馈，如果有开启clash的dns，也要关闭

**Comment by Fndroid** [comment]
此issue先关闭，问题依旧请reopen

**Comment by Edger** [comment]
> time="2019-06-12T10:01:45+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2019-06-12T10:01:45+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2019-06-12T10:01:45+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2019-06-12T10:01:45+08:00" level=error msg="External controller error: listen tcp 127.0.0.1:9090: bind: An attempt was made to access a socket in a way forbidden by its access permissions."

我也碰到这个问题，无法加载配置文件（unable to reload configuration）, system proxy 也无法勾选。

**Comment by Fndroid** [comment]
> > time="2019-06-12T10:01:45+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
> > time="2019-06-12T10:01:45+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
> > time="2019-06-12T10:01:45+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
> > time="2019-06-12T10:01:45+08:00" level=error msg="External controller error: listen tcp 127.0.0.1:9090: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
> 
> 我也碰到这个问题，无法加载配置文件（unable to reload configuration）, system proxy 也无法勾选。

你这个9090端口被占用了，换一个就好

**Comment by Edger** [comment]
> > > time="2019-06-12T10:01:45+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
> > > time="2019-06-12T10:01:45+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
> > > time="2019-06-12T10:01:45+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
> > > time="2019-06-12T10:01:45+08:00" level=error msg="External controller error: listen tcp 127.0.0.1:9090: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
> > 
> > 
> > 我也碰到这个问题，无法加载配置文件（unable to reload configuration）, system proxy 也无法勾选。
> 
> 你这个9090端口被占用了，换一个就好

应该是的，我重启了一下电脑就正常了。

谢谢解答🙏
