### ISSUE TITLE
希望增加对非select策略组折叠的支持

### ISSUE THREAD

**Issue by cccarbondioxide** [Fndroid/clash_for_windows_pkg#630]
**描述**
希望增添个按钮将urltest和fallback配置组折叠或隐藏

**其他说明**
部分配置文件繁冗复杂，需要大量的urltest和fallback策略组(10-20个)的支持，对视觉的观感不太友好

**Comment by Fndroid** [comment]
点一下策略名不就折叠了

**Comment by cccarbondioxide** [comment]
嘛，指将所有urltest和fallback组不再显示或在proxy面板隐藏，
    部分初接触clash的群众觉得无法主观控制的策略组有些冗余
(即不理解这些无法自行选择节点策略组存在的意义

**Comment by Fndroid** [comment]
所以他们无法理解，为什么要我改？

不应该是他们自己去理解下么？

**Comment by cccarbondioxide** [comment]
额，好像也是...

**Comment by Doraemon2020** [comment]
这个是要给CFA提，不是CFW提的
