### ISSUE TITLE
0.9.5 ua

### ISSUE THREAD

**Issue by imrbg** [Fndroid/clash_for_windows_pkg#633]
"-" "got/9.6.0 (https://github.com/sindresorhus/got)"
0.9.5 ua没填 导致根据ua判断的订阅内容失效
User Agent

It's a good idea to set the 'user-agent' header so the provider can more easily see how their resource is used. By default, it's the URL to this repo. You can omit this header by setting it to undefined.

const got = require('got');
const pkg = require('./package.json');

got('https://sindresorhus.com', {
	headers: {
		'user-agent': `my-package/${pkg.version} (https://github.com/username/my-package)`
	}
});

got('https://sindresorhus.com', {
	headers: {
		'user-agent': undefined
	}
});

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.6
