### ISSUE TITLE
Clash 分流问题

### ISSUE THREAD

**Issue by 1031918137** [Fndroid/clash_for_windows_pkg#634]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [X ] 已经尝试更新到最新版本，问题依旧存在
- [X ] 软件从本仓库下载
- [X ] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题
打开Clash后我打开本地网页延迟增加
**复现**
请描述复现问题的步骤:
1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
清晰地描述期望看到的行为

**截图**
如果可以，请提供对应问题的截图
这是打开后
![R8{H%QZ IW%}B$D56%`59`N](https://user-images.githubusercontent.com/62833720/78985005-49950f00-7b5a-11ea-9457-e52412f08aea.png)
这是关闭后
![X3M$RTY`HGP5Q%QTM3FKN}Q](https://user-images.githubusercontent.com/62833720/78985133-911b9b00-7b5a-11ea-9c0c-4018c6353b55.png)
这是我的分流
![@`CD15}@U3K}6U$12SF9A%R](https://user-images.githubusercontent.com/62833720/78985192-b7413b00-7b5a-11ea-9260-cc4cd69c8486.png)

**其他说明**
其他补充内容

**Comment by 1031918137** [comment]
这个是打开后![Z{@0~C {0X)NKQ4FN`FYUU2](https://user-images.githubusercontent.com/62833720/78985541-9d542800-7b5b-11ea-96fb-e2425f1b3bc4.png)









这个是关闭后
![)M(DL6K}VMZ1{R$AONZY}LN](https://user-images.githubusercontent.com/62833720/78985651-ea37fe80-7b5b-11ea-98d6-443f33641780.png)

**Comment by Fndroid** [comment]
这个PING不是网页延迟，是你连接speedtest的ping值，和你规则有关

**Comment by 1031918137** [comment]
ok i know and thank you very much

Fndroid <notifications@github.com> 于2020年4月10日周五 下午8:31写道：
