### ISSUE TITLE
指定网络接口时如果该接口有多ip地址会出现不从默认网关连接网络的情况

### ISSUE THREAD

**Issue by GainSury** [Fndroid/clash_for_windows_pkg#635]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [ X] 已经尝试更新到最新版本，问题依旧存在
- [ X] 软件从本仓库下载
- [ X] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题
tun模式下，当clash指定网络接口时，该接口存在多ip地址，clash没有从默认网关进行网络连接。
cfw版本：0.9.5
Windows版本：1909

**复现**
请描述复现问题的步骤:
1. 进入'配置中选择的网络接口'
2. 设置静态ip地址A（192.168.31.208），并在高级设置中设定一个与默认网关，网段不同的ip地址B，比如默认网关为192.168.31.1/24，设定ip地址192.168.1.126/24
3. 配置为fake-ip模式
4. 触发问题
cfw会默认使用静态地址B连接所有外出地址，而不是默认网关，此时会出现无法连接网络，cpu疯狂占用，内存泄漏等问题。
删除静态ip地址B恢复并重启CFW恢复正常，或者通过命令
`Set-NetIPAddress -IPAddress 192.168.1.126 -SkipAsSource $True` 将静态地址设定为该接口的非主地址时，cfw会使用默认网关连接外出地址。

**预期行为**
清晰地描述期望看到的行为
cfw使用默认网关连接所有外出地址
建议在配置中增加指定接口地址。
interface-address: 192.168.31.1

**截图**
如果可以，请提供对应问题的截图

**其他说明**
其他补充内容
已经在两台机器上复现

**Comment by Fndroid** [comment]
experimental.interface-name是clash core的功能，可以去core的repo反馈下
