### ISSUE TITLE
io timeout

### ISSUE THREAD

**Issue by iisuwi** [Fndroid/clash_for_windows_pkg#636]
**信息**log里的流量异常
如果符合，请将``[ ]``改为``[x]``
- [ x] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载
- [ ] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题
经常会有类似的错误连接，这是什么原因导致的呢
**复现**
请描述复现问题的步骤:
1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
清晰地描述期望看到的行为

**截图**
如果可以，请提供对应问题的截图
![image](https://user-images.githubusercontent.com/47839016/78994896-c08ad180-7b73-11ea-80e5-6b2f4169e207.png)
![image](https://user-images.githubusercontent.com/47839016/78994970-ea43f880-7b73-11ea-9a3e-f7907d3639c4.png)

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
- 连接不了这个策略组里的节点
- 如果选DIRECT的话，就是这个直连网站访问不了
