### ISSUE TITLE
你们有没有反复Timeout

### ISSUE THREAD

**Issue by Doraemon2020** [Fndroid/clash_for_windows_pkg#637]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载
- [x ] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题
Test Latency的时候大面积Time

**复现**
请描述复现问题的步骤:
1. Test Latency的时候大面积Timeout
2. 单独Test单一节点是通的
3.再次Test又可能会Timeout，反反复复

**预期行为**
清晰地描述期望看到的行为

**截图**
如果可以，请提供对应问题的截图

**其他说明**
其他补充内容

**Comment by coderloverXH** [comment]
我这边没有出现反复Timeout的情况哦

**Comment by cccarbondioxide** [comment]
遇见了类似的状况
目前在下是0.9.6版本
不知名原因触发全节点timeout，单测节点也为timeout，
此时检查general界面，确认系统代理确认为为打开状态，
当关闭软件后再次启动，general界面显示系统代理关闭，打开系统代理，可恢复正常运作，
过几分钟又出现大面积节点timeout，如此反复

**Comment by cb360** [comment]
[x ] 已经尝试更新到最新版本，问题依旧存在
[x ] 软件从本仓库下载
[x ] 软件下载后未修改任何安装目录中的文件

**Comment by Emphasia** [comment]
会有 并发测试的时候就会出现 单独测试就好很多 不确定是节点问题还是程序问题
