### ISSUE TITLE
win

### ISSUE THREAD

**Issue by iwsbiwy** [Fndroid/clash_for_windows_pkg#638]
# 情况描述
 1. 安装软件后，会默认打开系统设置的`手动设置代理`，这时候如果不打开软件，浏览器是没法上网的。
 2. 关了这个手动设置代理，不开软件的时候浏览器能上网。
 3. 关了这个手动设置代理，打开软件后，也能正常翻墙。
# 问题
 1. 这个手动设置代理开不开有什么区别？
 2. 既然开不开手动设置代理，都能翻墙，软件为什么打开这个设置？

![QQ图片20200411083359.png](https://i.loli.net/2020/04/11/4nB9aSevUKdAwLM.png)

**Comment by Fndroid** [comment]
开关对应于软件里的System Proxy
