### ISSUE TITLE
大年初一发个帖：节点连通测试和节点连通对比 

### ISSUE THREAD

**Issue by FormosaZh** [Fndroid/clash_for_windows_pkg#64]
关于节点连通测试的问题，已经解决一部分了，但是今天的我又有了更多的HTTPS节点，所以仍有更多的连通测试是超时的，随着节点越来越多，节点延迟对比也成了问题，我想在一个界面下看到几十个节点的对比结果和连续测试对比结果，可以实现吗？

![default](https://user-images.githubusercontent.com/27438860/52271736-81655d00-297f-11e9-99ba-d4a9acb53b38.png)

**Comment by Fndroid** [comment]
测速问题反馈：https://github.com/Dreamacro/clash/issues

难道要一页显示所有节点？明显不合理

**Comment by FormosaZh** [comment]
都反馈过了啊！https://github.com/Dreamacro/clash/issues/114

**Comment by Fndroid** [comment]
没有连续测试

我是实在不清楚你说的多节点对比是怎么样的

**Comment by FormosaZh** [comment]
就是有几十个以上的节点，所以想长时间监测一下连通情况，间隔测试，连续测试，能排序更好！

**Comment by Fndroid** [comment]
延迟测试如果有大量节点会导致界面卡顿无法切换所以不做。至于排序，节点顺序和你配置文件里顺序是一样的
