### ISSUE TITLE
fallback策略组定时自动测延迟有bug，它不能自动刷新延迟值

### ISSUE THREAD

**Issue by coderloverXH** [Fndroid/clash_for_windows_pkg#640]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
环境：win10， clash_for_windows v 0.9.5
v 0.9.5之前的版本没有出现类似的问题

**复现**
fallback策略组的interval = 10s，按道理来说，每隔10秒就自动测一次延迟，并更新延迟值。然而更新到v 0.9.5版本后，无论过多久也不再更新延迟值了。

![1-1](https://user-images.githubusercontent.com/63088614/79035013-d5577b80-7bec-11ea-8194-64dd0869291b.png)

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.6
