### ISSUE TITLE
希望可以一键复制代理命令的功能回归，有时候要打代理命令挺烦的

### ISSUE THREAD

**Issue by qanyue** [Fndroid/clash_for_windows_pkg#641]
发现0.9.5删除了一键打开代理命令行的功能，都已经习惯在cfw复制代理命令了。

**Comment by Fndroid** [comment]
下次更新加回来

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.6
