### ISSUE TITLE
切换代理规则时的卡顿

### ISSUE THREAD

**Issue by fxzxmicah** [Fndroid/clash_for_windows_pkg#643]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [ ] 软件下载后未修改任何安装目录中的文件

**描述**
0.9.5版本在切换Proxies时，点击Global，Rule，Direct按钮时，相比以前版本切换会有延迟

**复现**
请描述复现问题的步骤:
1. 进入Proxies
2. 点击Global，Rule，Direct任一与当前不同的按钮
3. 出现切换延迟，会在当前页面停顿一下，之后才会跳到选择的页面

**预期行为**
点击按钮，立即切换

**截图**
由于这是一个连续过程所以无法提供截图

**其他说明**
我使用的时ClashR，即替换了clash-win64.exe的文件，但是在0.9.3时（0.9.4我未更新）进行同样的操作，替换同样的文件时不存在这个卡顿。

**Comment by Fndroid** [comment]
只要替换了任何文件，都不用在我这里发issue

**Comment by fxzxmicah** [comment]
这只是使用问题，并不是功能问题，另外，在替换之前就存在这个问题，0.9.3切换很流畅，不存在卡顿（替换前）。另外，rule页在自动更换了节点后也没有自动刷新，我还以为它没有切换，直到我换到其它页再换到proxies页才看到更换了节点。

**Comment by fxzxmicah** [comment]
感谢修复。
