### ISSUE TITLE
0.9.5版本更新配置文件不会走代理

### ISSUE THREAD

**Issue by wanderzzzzz** [Fndroid/clash_for_windows_pkg#644]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
0.9.5版本更新配置文件时不会走代理，导致无法更新

**复现**
请描述复现问题的步骤:
1. 进入'Profiles'
2. 更新来自被墙或被污染的网址的配置
3. 触发问题

**预期行为**
更新配置的请求与浏览器访问一样按全局或规则走代理

**截图**
如果可以，请提供对应问题的截图

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
旧版本也一样不走代理

**Comment by wanderzzzzz** [comment]
> 旧版本也一样不走代理

是吗。。刚换回0.9.4确定可以更新，到0.9.5就不行了

**Comment by MPC-SLZQ** [comment]
我也有这个问题，0.9.5有点时候在打开System Proxy的状态下，新配置会一直在Downloading

**Comment by xzyc** [comment]
我也遇到这种情况了，在0,9.4版本可以下载，0.9.5版本会一直download

**Comment by xzyc** [comment]
> 旧版本也一样不走代理

我也遇到这种情况了，在0,9.4版本可以下载，0.9.5版本会一直download

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.6
