### ISSUE TITLE
将获取订阅的 UA 恢复为之前的格式

### ISSUE THREAD

**Issue by DesperadoJ** [Fndroid/clash_for_windows_pkg#645]
**描述**

之前版本获取订阅的 UA 为
`ClashforWindows/7.0 (Windows NT 10.0; Win64; x64) Chrome/76.0.3809.126 Electron/6.0.3`

v 0.9.5 获取订阅的 UA 变成了
`got/9.6.0 (https://github.com/sindresorhus/got)`

部分机场通过 UA 内容分发不同类型的托管内容 (如: UA 中包含 `clash` 就下发 Clash 的配置文件)。希望下个版本可以将获取订阅的 UA 恢复为之前的格式。

**其他说明**
无

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.6
