### ISSUE TITLE
不同代理分组相同服务器测速结果不能同步刷新，yaml文件错误不能提示错误所在行号。

### ISSUE THREAD

**Issue by kris115** [Fndroid/clash_for_windows_pkg#646]
【信息】
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

【描述】
- 问题1：不同代理分组相同服务器测速结果不能同步刷新。
- 问题2：yaml配置文件有错误时，只提示不能切换配置文件，不能提示当前文件错误发生在哪里

【复现】
- 1、进入Dashboard
- 2、点击proxies
- 3、点击Auto分组的测速按钮后得出本次测速结果，但proxy分组不能同步测试结果。

【预期行为】
- 1、不管在哪个分组点击测速后，除了本组服务器测速结果改变外，其他分组与测速分组中相同服务的测速结果应同步刷新。
- 2、当yaml文件有错误时，不能提示发生错误的所在的行号。

【截图】
版本【0.9.5】
![0 9 5-1](https://user-images.githubusercontent.com/12155282/79048566-9d821f80-7c50-11ea-872e-a6e72ff405af.png)
![0 9 5](https://user-images.githubusercontent.com/12155282/79048569-a4109700-7c50-11ea-8a09-6e73caf725a2.png)

版本【0.9.4】

![0 9 4-1](https://user-images.githubusercontent.com/12155282/79048647-15e8e080-7c51-11ea-957c-5af5b34a03c2.png)
![0 9 4](https://user-images.githubusercontent.com/12155282/79048651-197c6780-7c51-11ea-8182-20cfa39e53be.png)

【其他说明】

- 版本【0.9.4】不存在上述问题

**Comment by kris115** [comment]
> 【信息】
> [0.9.5] 已经尝试更新到最新版本，问题依旧存在
> [0.9.5] 软件从本仓库下载
> [0.9.5] 软件下载后未修改任何安装目录中的文件
> 
> 【描述】
> 问题1：不同代理分组相同服务器测速结果不能同步刷新。
> 问题2：yaml配置文件有错误时，至提示不能切换配置文件，不能提示当前文件错误发生在哪里。
> 
> 【复现】
> 1、进入Dashboard
> 2、点击proxies
> 3、点击Auto分组的测速按钮后得出本次测速结果，但proxy分组不能同步测试结果。
> 
> 【预期行为】
> 1、不管在哪个分组点击测速后，除了本组服务器测速结果改变外，其他分组与测速分组中相同服务的测速结果应同步刷新。
> 
> 2、当yaml文件有错误时，不能提示发生错误的所在的行号。
> 
> 【截图】
> 
> 【其他说明】
> 版本【0.9.4】不存在上述问题。

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.6
