### ISSUE TITLE
添加一键开关代理快捷键

### ISSUE THREAD

**Issue by HeronZhang** [Fndroid/clash_for_windows_pkg#647]
**描述**
虽然有订阅网络分流规则，但在规则外的网站有时连了代理就无法打开，得手动关掉代理。平时浏览网页还挺多的，经常会切换系统代理开关。这时候就得手动点开clash进行切换。希望加一个键盘快捷键，一键切换

**其他说明**
其他补充内容

**Comment by howieWo** [comment]
确实，很想要这个功能

**Comment by yi-Xu-0100** [comment]
@howieWo setting 最后有快捷键设置。

**Comment by my-orbit** [comment]
我的笔记本键盘上的F12键带星号，是用户自定义键，选择操作按键顺序，我设置的是ctrl+alt+F12，再在clash的setting中设置一样的，就实现一键开关了。

**Comment by my-orbit** [comment]
@yi-Xu-0100 setting设置完快捷键重启后就失效了

**Comment by yi-Xu-0100** [comment]
@my-orbit 可以尝试新开 issue 并给出版本信息，复现过程，最好有视频或者截图内容。
