### ISSUE TITLE
GeoIP database need license key and URL

### ISSUE THREAD

**Issue by LeviChenhh** [Fndroid/clash_for_windows_pkg#648]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [ ] 软件下载后未修改任何安装目录中的文件

**描述**
点击GeoIP Database 需要 license key and URL
请问可以从哪里获得？

**预期行为**
更新GeoIP Database

**截图**
如果可以，请提供对应问题的截图![图片](https://user-images.githubusercontent.com/48642188/79087362-9acb1b80-7d71-11ea-98b5-6d408dff61f7.png)

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
url填 https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb
key留空
