### ISSUE TITLE
问题反馈：Clash for Windows 下使用vmess[ws，非TLS]协议后，xshell无法通过此代理实现SSH连接

### ISSUE THREAD

**Issue by lqdflying** [Fndroid/clash_for_windows_pkg#65]
Clash for Windows 下使用vmess[ws，非TLS]协议后，xshell无法通过此代理实现SSH连接。节点配置方法如下图：
![_20190206213417](https://user-images.githubusercontent.com/30266323/52344932-fbb4e080-2a56-11e9-8e25-5e9f9ae8e691.png)
通过Xshell连接结果如下：
Looking up proxy server '127.0.0.1'...
Host '127.0.0.1' resolved to 127.0.0.1.
Connecting to 127.0.0.1:7891...
Connection established.
To escape to local shell, press 'Ctrl+Alt+]'.
Connection closing...Socket close.

Connection closed by foreign host.

Disconnected from remote host(google-drive) at 21:35:23.

Type `help' to learn how to use Xshell prompt.
[C:\~]$

**Comment by Fndroid** [comment]
其他类型的节点有问题吗

**Comment by lqdflying** [comment]
SS类型节点没问题，只有Vmess节点出现这个问题

**Comment by Fndroid** [comment]
请使用0.5.23版本测试，如问题依旧，请reopen此issue
