### ISSUE TITLE
点击Edit rule，显示为空，不能修改规则 #bug

### ISSUE THREAD

**Issue by lurengeng** [Fndroid/clash_for_windows_pkg#650]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
点进去Edit rule后，显示为空，不能修改规则。edit policy也基本为空。
原来使用过免安装版本的（.7z压缩包的那个），后来下载了更新的版本（免安装）未覆盖原版本，打开新版本后，订阅机场链接，可连接节点使用。但是

**复现**
请描述复现问题的步骤:
1. 原来使用过免安装版本的（.7z压缩包的那个）可正常使用
2. 后来下载了更新的版本（免安装）未覆盖原版本
3. 打开新版本后，订阅机场链接，可连接节点使用。
4. 在profile页，找到自己的yaml,点Edit rule后，显示为空，不能修改规则。edit policy也基本为空。
5. 即便我安装了setup版本，该问题reng'ra仍然存在

**预期行为**
希望能正常使用图形化界面修改rule 和policy

**截图**
![image](https://user-images.githubusercontent.com/61215384/79142185-ae1bcc80-7ded-11ea-8b86-368ce111c9d3.png)
![image](https://user-images.githubusercontent.com/61215384/79142204-b83dcb00-7ded-11ea-948d-a9fc49cc9d3d.png)

**Comment by abae136ab** [comment]
> **信息**
> 如果符合，请将`[ ]`改为`[x]`
> 
> * [x]  已经尝试更新到最新版本，问题依旧存在
> * [x]  软件从本仓库下载
> * [x]  软件下载后未修改任何安装目录中的文件
> 
> **描述**
> 点进去Edit rule后，显示为空，不能修改规则。edit policy也基本为空。
> 原来使用过免安装版本的（.7z压缩包的那个），后来下载了更新的版本（免安装）未覆盖原版本，打开新版本后，订阅机场链接，可连接节点使用。但是
> 
> **复现**
> 请描述复现问题的步骤:
> 
> 1. 原来使用过免安装版本的（.7z压缩包的那个）可正常使用
> 2. 后来下载了更新的版本（免安装）未覆盖原版本
> 3. 打开新版本后，订阅机场链接，可连接节点使用。
> 4. 在profile页，找到自己的yaml,点Edit rule后，显示为空，不能修改规则。edit policy也基本为空。
> 5. 即便我安装了setup版本，该问题reng'ra仍然存在
> 
> **预期行为**
> 希望能正常使用图形化界面修改rule 和policy
> 
> **截图**
> ![image](https://user-images.githubusercontent.com/61215384/79142185-ae1bcc80-7ded-11ea-8b86-368ce111c9d3.png)
> ![image](https://user-images.githubusercontent.com/61215384/79142204-b83dcb00-7ded-11ea-948d-a9fc49cc9d3d.png)

等待cfw匹配最新的clash配置描述就好了。

**Comment by lurengeng** [comment]
> > **信息**
> > 如果符合，请将`[ ]`改为`[x]`
> > 
> > * [x]   已经尝试更新到最新版本，问题依旧存在
> > * [x]   软件从本仓库下载
> > * [x]   软件下载后未修改任何安装目录中的文件
> > 
> > **描述**
> > 点进去Edit rule后，显示为空，不能修改规则。edit policy也基本为空。
> > 原来使用过免安装版本的（.7z压缩包的那个），后来下载了更新的版本（免安装）未覆盖原版本，打开新版本后，订阅机场链接，可连接节点使用。但是
> > **复现**
> > 请描述复现问题的步骤:
> > 
> > 1. 原来使用过免安装版本的（.7z压缩包的那个）可正常使用
> > 2. 后来下载了更新的版本（免安装）未覆盖原版本
> > 3. 打开新版本后，订阅机场链接，可连接节点使用。
> > 4. 在profile页，找到自己的yaml,点Edit rule后，显示为空，不能修改规则。edit policy也基本为空。
> > 5. 即便我安装了setup版本，该问题reng'ra仍然存在
> > 
> > **预期行为**
> > 希望能正常使用图形化界面修改rule 和policy
> > **截图**

> 
> 等待cfw匹配最新的clash配置描述就好了。

等待？等多久？等CFW新版发布？

**Comment by zhouyilong** [comment]
我最近更新的0.9.7和0.9.8都有这个问题

**Comment by Fndroid** [comment]
新版已经替换为新字段
