### ISSUE TITLE
使用URL访问本地配置文件在新版本不可用

### ISSUE THREAD

**Issue by bososha** [Fndroid/clash_for_windows_pkg#651]
**信息**
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
使用URL访问本地配置文件在新版本不可用

**复现**
配置文件URL键入以下内容
file:///C:/path/to/ClashForWindows/config.yaml
刷新后提示：Download profile failed with error: Unsupported protocol "file:"

**截图**
![image](https://user-images.githubusercontent.com/16136181/79193954-81ad8380-7de0-11ea-8940-b5317801fb9d.png)
![image](https://user-images.githubusercontent.com/16136181/79193962-85d9a100-7de0-11ea-9c55-e7ba72cb2576.png)

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.6
