### ISSUE TITLE
Windows10 v1909，最新版本CFW无法远程更新配置文件

### ISSUE THREAD

**Issue by marcosteam** [Fndroid/clash_for_windows_pkg#653]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
Windows 0.9.5最新版本，无法下载订阅更新，但使用浏览器可正常访问订阅地址并生成配置文件。

**复现**
1. 直接运行clash
2. 点击Profiles
3. 填入使用Subconverter生成的订阅链接
4. 触发问题（长时间卡downloading）

**log**
![image](https://user-images.githubusercontent.com/25745812/79199772-0abbcd80-7e68-11ea-887d-d08d2a2d7e31.png)

**错误截图**
（此截图只出现过一次，后期就没有提示了）
![image](https://user-images.githubusercontent.com/25745812/79200842-a568dc00-7e69-11ea-9c63-702878f5f227.png)

**其他说明**
换用0.9.3版本，可正常下载更新订阅

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.6
