### ISSUE TITLE
求问 win10 使用PPPoE拨上的网，该如何用这个clash代理呢

### ISSUE THREAD

**Issue by luckily18894** [Fndroid/clash_for_windows_pkg#655]
我的上网环境需先使用PPPoE拨号，才能上公网，但是之后再使用clash 代理访问国外站点 就无法访问。  
而使用预先拨号的（插上就能用）环境 就能正常使用clash代理。
已经开启了Allow LAN ，也没效果。
请问 还需要修改哪里么？？

**Comment by scalar42** [comment]
有可能是PPPoe名称带中文的缘故，可以尝试一下。

**Comment by luckily18894** [comment]
> 有可能是PPPoe名称带中文的缘故，可以尝试一下。

确实是网卡名称的问题，虽然不是中文，但有个下划线 ___ 去掉就好了！！！谢谢大佬~

**Comment by gongcavalry** [comment]
刚看了这个帖子，改了宽带拨号的名称为英文，没效果。
然后我就了一下IPV6，就可以了。我赶紧把google chrome的同步给解决了。
然后我登陆github来回帐号。
在回复的同时我感觉要严谨一些，要确认这个英文名称到底有没有用，我断了英文拨号，改回原来的中文拨号，再看。
确认中文拨号不行，我又切回英文拨号，依然不行，留下风中凌乱的我。

搞不明白了。

**Comment by gongcavalry** [comment]
我确认了问题在哪，只要把端口改一下，马上就可以了，原理我不懂。
