### ISSUE TITLE
无法打开面板

### ISSUE THREAD

**Issue by horryruo** [Fndroid/clash_for_windows_pkg#656]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载
- [x ] 软件下载后未修改任何安装目录中的文件

**描述**
今晚点托盘唤出主面板，但是面板始终不显示，只有个任务栏图标，重启软件，重启电脑，重新下载打开，都无法显示

**复现**
请描述复现问题的步骤:
打开软件。。。打不开，界面无法显示

**预期行为**
清晰地描述期望看到的行为

**截图**
![image](https://user-images.githubusercontent.com/33121172/79355742-a9cbec80-7f70-11ea-91fe-7f1f8a90d59a.png)
如图，多任务界面是白的，但是实际上是点不卡的，一直点都什么都不出来，但是截不了图。

**其他说明**
其他补充内容

**Comment by YinBuLiao** [comment]
怎么解决的
