### ISSUE TITLE
Clash更新GeoIP时不走代理

### ISSUE THREAD

**Issue by ghost** [Fndroid/clash_for_windows_pkg#657]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
您好，我发现新版本Clash即使在开启代理的情况下更新GeoIP Database时似乎也不走代理。
更新过程很缓慢，并且容易出现下载中断，导致数据库更新错误导致Clash core报错从而无法使用。

**复现**
请描述复现问题的步骤:
1,只是简单的更新GeoIP Database

**预期行为**
GeoIP Database更新时走Clash代理。

**Comment by ntol** [comment]
应该是专门不让走的，挂上代理反而不能更新了，具体原理不了解。

**Comment by Fndroid** [comment]
除非开启TAP模式，否则整个CFW里的请求都不会走代理（包括更新GEOIP，更新配置文件）
