### ISSUE TITLE
无法连接至clash core

### ISSUE THREAD

**Issue by kld123509945** [Fndroid/clash_for_windows_pkg#659]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
关闭杀软，为本计算机所有用户安装，安装完以后直接运行clash，显示 could not connect to clash core. 退出软件，使用管理员模式运行，依旧无法连接。

**log日志**
time="2020-04-17T01:37:39+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-04-17T01:37:40+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-04-17T01:37:40+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-04-17T01:37:40+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-04-17T01:37:40+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-04-17T01:37:40+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"

**截图**

![TIM截图20200417013715](https://user-images.githubusercontent.com/34784522/79488469-56c76780-804c-11ea-967e-7b2fb7b5074a.png)

**Comment by hexd2019** [comment]
同样问题

**Comment by Fndroid** [comment]
试试：
1. 关闭软件
2. 删除 C:\Users{你的用户名}.config\clash 文件夹
3. 重启软件

**Comment by hexd2019** [comment]
谢谢，解决!

**Comment by xxyzuo** [comment]
> 试试：
> 
> 1. 关闭软件
> 2. 删除`C:\Users\{你的用户名}\.config\clash `文件夹
> 3. 重启软件

删除文件夹重启后，故障仍然存在

**Comment by kld123509945** [comment]
> 试试：
> 
> 1. 关闭软件
> 2. 删除 `C:\Users\{你的用户名}\.config\clash `文件夹
> 3. 重启软件

问题依然存在：
![批注 2020-04-20 001623](https://user-images.githubusercontent.com/34784522/79693273-3988d800-829c-11ea-8622-64948382c399.png)

**Comment by wecenss** [comment]
我也一样，删除重装都没办法解决。

**Comment by hadoken7** [comment]
> **信息**
> 如果符合，请将`[ ]`改为`[x]`
> 
> * [x]  已经尝试更新到最新版本，问题依旧存在
> * [x]  软件从本仓库下载
> * [x]  软件下载后未修改任何安装目录中的文件
> 
> **描述**
> 关闭杀软，为本计算机所有用户安装，安装完以后直接运行clash，显示 could not connect to clash core. 退出软件，使用管理员模式运行，依旧无法连接。
> 
> **log日志**
> time="2020-04-17T01:37:39+08:00" level=info msg="Start initial compatible provider Proxy"
> time="2020-04-17T01:37:40+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
> time="2020-04-17T01:37:40+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
> time="2020-04-17T01:37:40+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
> time="2020-04-17T01:37:40+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
> time="2020-04-17T01:37:40+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
> 
> **截图**
> 
> ![TIM截图20200417013715](https://user-images.githubusercontent.com/34784522/79488469-56c76780-804c-11ea-967e-7b2fb7b5074a.png)

更换下所有的端口试试

**Comment by sherlock221** [comment]
改用户下.config下  config文件 里面端口解决
