### ISSUE TITLE
能否直接将二进制安装文件包含在code中？

### ISSUE THREAD

**Issue by dream-potatoes** [Fndroid/clash_for_windows_pkg#66]
GitHub release上的文件是托管在Amazon S3上的，下载速度实在是慢，才几kb/s，并且挂不挂proxy都一样。

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/52607395-0a652280-2eb1-11e9-975e-78b936d28993.png)

100M宽带且挂代理

**Comment by dream-potatoes** [comment]
好吧，可能是我这边封锁的比较严
