### ISSUE TITLE
win7 dns tls

### ISSUE THREAD

**Issue by clashthe** [Fndroid/clash_for_windows_pkg#660]
0.9.4 测试dns 中有tls://时部分timeout   去掉后正常
0.8.11 测试dns 中有tls://时全部正常
测试仅针对win7 64 win10全部正常

**Comment by vpsceo** [comment]
的确是这个问题，只需要将配置中的  enable: true  改成 enable: false 就可以了
dns:
  enable: false

**Comment by vpsceo** [comment]
希望作者查询下是什么原因导致的

**Comment by lex0bomb** [comment]
Win10 升级到0.9.11之后(之前是9.5可能) 所有节点测试timeout
改了profile里面的配置 dns选false 之后恢复正常
应该是机场的托管文件写的问题吧
