### ISSUE TITLE
更新后tor browser用不了

### ISSUE THREAD

**Issue by easyasd** [Fndroid/clash_for_windows_pkg#661]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载
- [ ] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题

**复现**
请描述复现问题的步骤:
1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
清晰地描述期望看到的行为

**截图**
如果可以，请提供对应问题的截图

**其他说明**
其他补充内容

**Comment by mephisX** [comment]
![image](https://user-images.githubusercontent.com/30206556/79627954-33490d80-816f-11ea-95b6-b7581be3f778.png)
買個新電腦應該就可以解決了

**Comment by easyasd** [comment]
> ![image](https://user-images.githubusercontent.com/30206556/79627954-33490d80-816f-11ea-95b6-b7581be3f778.png)
> 買個新電腦應該就可以解決了

额。用的alpha版  真的好像不大行，没整网桥
