### ISSUE TITLE
版本0.9.6 yaml配置文件出错时仍然不能提示行号

### ISSUE THREAD

**Issue by kris115** [Fndroid/clash_for_windows_pkg#662]
**信息**
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
版本0.9.6没有解决：yaml配置文件出错时提示错误所在行的功能。

**预期行为**
本地编辑yaml配置文件如发生格式错误，能够提示格式错误所在行号。

**截图**
![3](https://user-images.githubusercontent.com/12155282/79582760-c4cc6700-80fe-11ea-9e34-8e82072ef9fe.png)

![4](https://user-images.githubusercontent.com/12155282/79582855-edecf780-80fe-11ea-9511-ffd40ed40a5c.png)

**其他说明**
该问题在[#646](https://github.com/Fndroid/clash_for_windows_pkg/issues/646) 提出，但新版本并未解决该问题，0.9.3、0.9.4版本均能提示错误行号。

**Comment by junjiego** [comment]
遇到同样的问题，除了不能显示行号之外，0.9.6是不是修改了规则的规范，同样的yaml配置在0.9.4正常运行，更新到0.9.5和0.9.6之后报错，而且不显示行号
