### ISSUE TITLE
打开软件 General界面中间一直显示Loading

### ISSUE THREAD

**Issue by maygop** [Fndroid/clash_for_windows_pkg#664]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
打开软件 General界面中间一直显示Loading.

**截图**
![image](https://user-images.githubusercontent.com/63893289/79628009-9dfa4900-816f-11ea-9236-9d6a1526dc8f.png)

**其他说明**
日志：time="2020-04-18T12:16:05+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"

**Comment by Fndroid** [comment]
日志就只有一句吗？

**Comment by maygop** [comment]
> 日志就只有一句吗？

嗯！就一句。

**Comment by Fndroid** [comment]
1. 关闭软件
2. 删除 C:\Users\{你的用户名}\.config\clash 文件夹
3. 重启软件

**Comment by maygop** [comment]
> 1. 关闭软件
> 2. 删除C：\ Users {你的用户名} .config \ clash文件夹
> 3. 重启软件

噢！可以了！谢谢你Fndroid ！！

**Comment by bao-wei** [comment]
> 1. 关闭软件
> 2. 删除 C:\Users{你的用户名}.config\clash 文件夹
> 3. 重启软件

删除后重启还是不行，下载的0.11.9安装版。请问如何解决？

**Comment by Fndroid** [comment]
> > 1. 关闭软件
> 
> > 2. 删除 C:\Users{你的用户名}.config\clash 文件夹
> 
> > 3. 重启软件
> 
> 
> 
> 删除后重启还是不行，下载的0.11.9安装版。请问如何解决？

点左下角文字，看看端口是不是被占了

**Comment by peoplechinapower** [comment]
> 1. 关闭软件
> 2. 删除 C:\Users{你的用户名}.config\clash 文件夹
> 3. 重启软件

可以了 谢谢

**Comment by realrxen** [comment]
> 1. 关闭软件
> 2. 删除 C:\Users{你的用户名}.config\clash 文件夹
> 3. 重启软件

cool, it works!
