### ISSUE TITLE
CFW的UI显示错误

### ISSUE THREAD

**Issue by EthanWeee** [Fndroid/clash_for_windows_pkg#666]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载
- [ x] 软件下载后未修改任何安装目录中的文件

**描述**
打开cfw时，General界面中的System Proxy开关显示关闭状态（实际上已经打开了），在切换洁面后（切到Proxies界面再切回General界面），显示正常

**复现**
请描述复现问题的步骤:
尝试多次了，假如在退出cfw时，system proxy是打开的状态，下次打开cfw时，general界面的system proxy显示是关闭的，但是实际上系统代理已经打开了，是显示错误

**预期行为**
修复BUG

**截图**
![微信截图_20200418134346](https://user-images.githubusercontent.com/56794580/79629284-f3882300-817a-11ea-8345-49a1d7c9e6c5.png)

**其他说明**
开启cfw后，loading时间有点长，以前0.8.x的版本，基本都是秒加载的，如果时间允许的话，期望F大能够优化增强一下启动加载时间。

**Comment by rolle33** [comment]
遇到同样问题

**Comment by Fndroid** [comment]
fixed in release:https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.7

**Comment by Fandshu** [comment]
> fixed in release:https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.7

0.9.7便携模式   右击以管理员运行正常，直接双击打开同样的问题复现。
