### ISSUE TITLE
完善TAP启动的脚本

### ISSUE THREAD

**Issue by a86913179** [Fndroid/clash_for_windows_pkg#667]
**描述**
根据我在mellow那边的PR，修改了适配cfw的batch脚本，去除win7不支持的powershell命令改为使用netch。由于go-tun2socks指定参数启动后是启用DHCP的，所以不需要在batch设置静态IP，故注释掉了。建议改下cfw源码，在启动go-tun2socks时执行脚本config_route.bat，退出cfw的时候执行脚本recover_route.bat。

**其他说明**
文件我上传到了这里 https://github.com/a86913179/cfw_tun2socks_batch

**Comment by Fndroid** [comment]
不是很理解为什么要在开关的时候修改路由表

**Comment by a86913179** [comment]
> 不是很理解为什么要在开关的时候修改路由表

这样不影响正常使用啊，开启TAP添加一条0.0.0.0/0的路由让流量走TAP，关闭TAP删除，让流量走回默认网卡，所有用TAP的软件都是这样做的啊。

**Comment by Fndroid** [comment]
路由在网卡断开连接就不会生效了吧，卸载网卡之后也会跟着删除。

**Comment by Fndroid** [comment]
TAP网卡的路由被删，应该是go-tun2socks的bug吧，不是应该才源码入手吗

**Comment by a86913179** [comment]
> TAP网卡的路由被删，应该是go-tun2socks的bug吧，不是应该才源码入手吗

我用mellow的时候，core（作者自己改的go-tun2v2ray，没开源）并不会默认添加0.0.0.0/0的路由，需要用batch脚本手动添加，这个不算BUG吧，本身就没添加默认路由。

我看cfw的batch脚本写的很乱，add_tap_device.bat里有一条删198.18.0.0/16的路由，感觉没啥意义，安装网卡的时候也没添加路由啊。

然后set_route.bat里第一条是删除0.0.0.0/0，然后又添加198.18.0.0/16，现在不是可以指定网卡避免环回了吗？

set_dns.bat的意义我也不知道在哪里，add_tap_device.bat里已经指定了网卡的静态IP和静态DNS。

然后go-tun2socks一启动，你在add_tap_device.bat里设置的静态IP和静态DNS又会变成DHCP获取，所以这几条命令也没啥意义。

我也觉得你误解了go-tun2socks的用法，它跟badvpn-tun2socks不一样，后者是会添加一条0.0.0.0/0的默认路由。

**Comment by Fndroid** [comment]
> go-tun2socks源码里没有删除路由的代码

实际上go-tun2socks会删除默认路由（在管理员权限下），这是[issue](https://github.com/eycorsican/go-tun2socks/issues/103#issuecomment-604174705)

> 我看cfw的batch脚本写的很乱，add_tap_device.bat里有一条删198.18.0.0/16的路由，感觉没啥意义，安装网卡的时候也没添加路由啊。
> 然后set_route.bat里第一条是删除0.0.0.0/0，然后又添加198.18.0.0/16，现在不是可以指定网卡避免环回了吗？

这是对应旧版本的，以前并不能指定网卡，所以需要fake-ip段做入口

> 然后go-tun2socks一启动，你在add_tap_device.bat里设置的静态IP和静态DNS又会变成DHCP获取，所以这几条命令也没啥意义。

我知道会DHCP分配，但是同时它会删除我的默认的路由，因为有这个行为，所以我不希望它用管理员权限启动，所以DHCP也无法分配

> 我觉得你误解了go-tun2socks的用法，它跟badvpn-tun2socks不一样，后者是会添加一条0.0.0.0/0的默认路由。

默认路由是安装TAP的时候生成的，你可以自己验证下，并不是badvpn-tun2socks生成

**Comment by a86913179** [comment]
> > go-tun2socks源码里没有删除路由的代码
> 
> 实际上go-tun2socks会删除默认路由（在管理员权限下），这是[issue](https://github.com/eycorsican/go-tun2socks/issues/103#issuecomment-604174705)
> 
> > 我看cfw的batch脚本写的很乱，add_tap_device.bat里有一条删198.18.0.0/16的路由，感觉没啥意义，安装网卡的时候也没添加路由啊。
> > 然后set_route.bat里第一条是删除0.0.0.0/0，然后又添加198.18.0.0/16，现在不是可以指定网卡避免环回了吗？
> 
> 这是对应旧版本的，以前并不能指定网卡，所以需要fake-ip段做入口
> 
> > 然后go-tun2socks一启动，你在add_tap_device.bat里设置的静态IP和静态DNS又会变成DHCP获取，所以这几条命令也没啥意义。
> 
> 我知道会DHCP分配，但是同时它会删除我的默认的路由，因为有这个行为，所以我不希望它用管理员权限启动，所以DHCP也无法分配
> 
> > 我觉得你误解了go-tun2socks的用法，它跟badvpn-tun2socks不一样，后者是会添加一条0.0.0.0/0的默认路由。
> 
> 默认路由是安装TAP的时候生成的，你可以自己验证下，并不是badvpn-tun2socks生成

我是在Windows 10上直接用Administrator账户的，没有创建默认路由，也没有删除路由的行为，全都需要脚本来执行。启动tun2socks，没有默认路由，然后用脚本添加，关闭tun2socks，默认路由还在，然后用脚本删除。

**Comment by a86913179** [comment]
> > go-tun2socks源码里没有删除路由的代码
> 
> 实际上go-tun2socks会删除默认路由（在管理员权限下），这是[issue](https://github.com/eycorsican/go-tun2socks/issues/103#issuecomment-604174705)
> 
> > 我看cfw的batch脚本写的很乱，add_tap_device.bat里有一条删198.18.0.0/16的路由，感觉没啥意义，安装网卡的时候也没添加路由啊。
> > 然后set_route.bat里第一条是删除0.0.0.0/0，然后又添加198.18.0.0/16，现在不是可以指定网卡避免环回了吗？
> 
> 这是对应旧版本的，以前并不能指定网卡，所以需要fake-ip段做入口
> 
> > 然后go-tun2socks一启动，你在add_tap_device.bat里设置的静态IP和静态DNS又会变成DHCP获取，所以这几条命令也没啥意义。
> 
> 我知道会DHCP分配，但是同时它会删除我的默认的路由，因为有这个行为，所以我不希望它用管理员权限启动，所以DHCP也无法分配
> 
> > 我觉得你误解了go-tun2socks的用法，它跟badvpn-tun2socks不一样，后者是会添加一条0.0.0.0/0的默认路由。
> 
> 默认路由是安装TAP的时候生成的，你可以自己验证下，并不是badvpn-tun2socks生成

可能是因为你创建的是永久路由

**Comment by a86913179** [comment]
我又试了下outline已经编译好的[badvpn-tun2socks](https://github.com/Jigsaw-Code/outline-client/blob/master/third_party/badvpn/win32/badvpn-tun2socks.exe)，也是不会创建0.0.0.0/0的默认路由和删除0.0.0.0/0的默认路由，除非你在add_tap_device.bat里用`netsh interface ip set address`指定了网关，而outline的脚本里是`netsh interface ip set address 10.0.85.2 255.255.255.0`，这就跟tun2socks没关系了，是netsh命令干的事，而且我用outline的badvpn-tun2socks配合clash也是正常使用，clash开启fake-ip，UDP请求也能接收到域名并转发。go-tun2socks比badvpn-tun2socks好的一点是icmp local echo，就是开启tun2socks，ping任何地址都是返回1ms。顺便说下cfw的GUI添加节点的时候并没有开启udp代理，需要在config里的节点配置添加`udp: true`，不然可以看到Session里udp都是直连，log里显示nonmatch rule using direct。

Anyway，这是你的项目，我只是提个建议。我现在自己用batch启用clash和badvpn-tun2socks一切都很好，GUI对我来说不是必须的。
