### ISSUE TITLE
无法连接到本地socks5代理

### ISSUE THREAD

**Issue by jarvanh** [Fndroid/clash_for_windows_pkg#668]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x]已经尝试更新到最新版本，问题依旧存在
- [x]软件从本仓库下载
- [x]软件下载后未修改任何安装目录中的文件

**描述**
无法连接到本地socks5代理

**复现**
请描述复现问题的步骤:
1. Proxies中添加一个本地socks5代理

**截图**
![image](https://user-images.githubusercontent.com/5900885/79640603-00c9ff80-81c5-11ea-8fd8-25110e956bf4.png)

![image](https://user-images.githubusercontent.com/5900885/79640643-2d7e1700-81c5-11ea-9a44-61ac5086050e.png)

**Comment by Fndroid** [comment]
TAP模式下是会这样，因为设置了interface-name之后连接就回不到127.0.0.1了

**Comment by jarvanh** [comment]
原来如此。谢谢
