### ISSUE TITLE
打开proxies选项时呈现空白

### ISSUE THREAD

**Issue by sunflower6** [Fndroid/clash_for_windows_pkg#669]
自从更新以后经常会出现proxies选项时呈现空白的情况，以前的版本都是好好的，而且只是某一个机场出现这种情况，我不知道是哪儿出了问题
![批注 2020-04-19 093618](https://user-images.githubusercontent.com/56858288/79677199-3ef50c80-8221-11ea-99c5-799308c00d84.jpg)

**Comment by JunerLee** [comment]
遇到同样问题，突然出现的，重新启动软件依然没用

**Comment by sunflower6** [comment]
我这边打开配置文件后发现并不是标准的格式，而是HTML，应该是clash从网站下载订阅文件的时候出了问题，但我不清楚这是clash的原因还是订阅链接的原因

JunerLee <notifications@github.com> 于 2020年4月24日周五 15:17写道：
