### ISSUE TITLE
能否以后台模式启动？

### ISSUE THREAD

**Issue by haphap** [Fndroid/clash_for_windows_pkg#67]
目前Windows系统启动后，Clash for windows（版本:0.5.21）都是以窗口形式运行，还需要手动最小化，能否提供选项直接以后台模式启动运行？

**Comment by Fndroid** [comment]
一直都是直接启动在后台的

**Comment by Fndroid** [comment]
你的这个问题应该是你自己设置过自启动（复制快捷方式的方法），然后又打开了软件里的Auto Launch导致的

**Comment by haphap** [comment]
确实如此，谢谢了

**Comment by KnightRise** [comment]
如果想要完全隐藏任务栏和托盘中的图标呢？
