### ISSUE TITLE
请求支持 Windows on ARM

### ISSUE THREAD

**Issue by RINKIGAI** [Fndroid/clash_for_windows_pkg#670]
**描述**
目前在 Surface Pro X 无法正常运行 Clash 的 32 位程序，希望能够支持 arm 64 的 Windows 电脑。Clash 是我唯一在用的翻墙服务，特别希望开发者能够满足~

**Comment by GrayXu** [comment]
You can try [lzdnico/ClashWeb](https://github.com/lzdnico/ClashWeb) temporarily

**Comment by fredzb2013** [comment]
Any update on this request?
