### ISSUE TITLE
win10更新到最新版后以太网下TAP模式不能使用

### ISSUE THREAD

**Issue by 1121726636** [Fndroid/clash_for_windows_pkg#672]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
在win10 进行4月累计更新前（最后更新是3月18日），我是可以正常使用TAP模式的（以太网和WLAN都没问题）。
然而在进行4月累计更新之后，TAP模式就无法在以太网下使用了，WLAN下依旧可以使用。
我注意到win10在3月18日至4月19日期间的更新KB4554364曾对VPN网络问题进行修复，不知道是不是因为这个。

**复现**
请描述复现问题的步骤:
照着F大教的TAP设置
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 119.29.29.29
    - 114.114.114.114
    - 223.5.5.5
  fake-ip-filter:
    - 'dns.msftncsi.com'
    - 'www.msftncsi.com'
    - 'www.msftconnecttest.com'
experimental:
  interface-name: '以太网'
保存，连接以太网，安装cfw-tap网卡，重启clash，刷新dns

**预期行为**
可以正常使用网络，并且能让不遵循系统代理的软件走代理

**截图**
4月19日win10更新记录
![image](https://user-images.githubusercontent.com/29080642/79686650-9375a780-8274-11ea-9de3-fa6b0747909e.png)

**其他说明**

**Comment by Fndroid** [comment]
我很早更新了没发现有问题

**Comment by 1121726636** [comment]
> 我很早更新了没发现有问题

因为是在可用和不可用之间只隔了更新系统并重启的操作，所以我才以为是win10更新导致的。请问大佬，如果不是win10更新引起的，我这种情况应该是什么原因呢。

**Comment by 1121726636** [comment]
我折腾了一会（关闭再打开clash 拔插网线 网卡卸载重装 重启路由器等），又无缘无故地恢复了，还是不知道啥原因，总之解决了，感谢F大的回复，大佬早点休息

**Comment by 1121726636** [comment]
今早又不行了，我复现了昨晚的操作，但是没有能解决，依旧是WLAN可以用，以太网没法用。求助大佬。

**Comment by Fndroid** [comment]
用的管理员权限启动cfw么

**Comment by 1121726636** [comment]
不是管理员，正常启动
![image](https://user-images.githubusercontent.com/29080642/79752446-e6b82a80-8346-11ea-848b-e20633ebd518.png)

**Comment by Flammulinavelutipes** [comment]
公司电脑有线环境配置如下：
interface-name: '以太网'
TAP模式无法启动

家里笔记本WIFI环境配置如下：
interface-name: WLAN
TAP模式正常

系统均为win10家庭版最新

**Comment by Flammulinavelutipes** [comment]
![企业微信截图_20200511103921](https://user-images.githubusercontent.com/26811405/81519771-e8d53e00-9374-11ea-83b6-82716544c0a9.png)
当配置文件中配置为：
dns:
   listen: 0.0.0.0:53

此时cfw-tap能够连接，但全部timeout，direct和proxy均无法上网。


![企业微信截图_20200511104106](https://user-images.githubusercontent.com/26811405/81519928-5aad8780-9375-11ea-8d88-efdce3bf2de7.png)
当配置文件中配置为：
dns:
   listen: 127.0.0.1:53

此时连接正常，但cfw-tap显示拔出，tap模式不可用。

并且第一个配置在笔记本WiFi环境下使用一切正常，cfw-tap能够连接，无timeout问题，可正常上网。
不知是有线以太网环境时配置文件有特别的地方需要修改吗？还是别的什么问题？
配置文件如下：
# port of HTTP
port: 7890

# port of SOCKS5
socks-port: 7891

# redir port for Linux and macOS
# redir-port: 7892

allow-lan: false

# Only applicable when setting allow-lan to true
# "*": bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
# bind-address: "*"

# Rule / Global / Direct (default is Rule)
mode: Rule

# set log level to stdout (default is info)
# info / warning / error / debug / silent
log-level: info

# RESTful API for clash
external-controller: 127.0.0.1:9090

# you can put the static web resource (such as clash-dashboard) to a directory, and clash would serve in `${API}/ui`
# input is a relative path to the configuration directory or an absolute path
# external-ui: folder

# Secret for RESTful API (Optional)
# secret: ""

# experimental feature
experimental:
  ignore-resolve-fail: true # ignore dns resolve fail, default value is true
  interface-name: '以太网' # outbound interface name

# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# # experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
# # static domain has a higher priority than wildcard domain (foo.example.com > *.example.com > .example.com)
# hosts:
#   '*.clash.dev': 127.0.0.1
#   '.dev': 127.0.0.1
#   'alpha.clash.dev': '::1'


dns:
   enable: true # set true to enable dns (default is false)
   ipv6: false # default is false
   listen: 0.0.0.0:53
  # # default-nameserver: # resolve dns nameserver host, should fill pure IP
  # #   - 114.114.114.114
  # #   - 8.8.8.8
   enhanced-mode: fake-ip
  # # fake-ip-range: 198.18.0.1/16 # if you don't know what it is, don't change it
  # fake-ip-filter: # fake ip white domain list
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com
   nameserver:
     - 114.114.114.114
     - tls://dns.rubyfish.cn:853 # dns over tls
     - https://1.1.1.1/dns-query # dns over https
  # fallback: # concurrent request with nameserver, fallback used when GEOIP country isn't CN
  #   - tcp://1.1.1.1
  # fallback-filter:
  #   geoip: true # default
  #   ipcidr: # ips in these subnets will be considered polluted
  #     - 240.0.0.0/4

---------------------------------------------------------------------------------------------------------
@Fndroid  麻烦看下了。谢谢。

**Comment by Fndroid** [comment]
@Flammulinavelutipes 问题不一样就开一个新的issue问，别在别人不同的问题下回复

**Comment by lvhe19880210** [comment]
有没有可能是不同网卡硬件导致的问题？同样clash版本配置同一网络下其中一台笔记本用无线就可以tap，另外一台台式机用有线就不行（曾经可以的， 最近不行了， 忘了是哪个版本开始不行的），配置用的最新说明里的

**Comment by Fndroid** [comment]
不一定双击启动就不是管理员，如果用户是超级管理员（如默认都Administrator），所有程序将默认用管理员模式运行。

cmd（非管理员模式）运行以下命令：
```
fsutil dirty query %systemdrive%
```

如果提示没有权限就正常

**Comment by lvhe19880210** [comment]
> 不一定双击启动就不是管理员，如果用户是超级管理员（如默认都Administrator），所有程序将默认用管理员模式运行。
> 
> cmd（非管理员模式）运行以下命令：
> 
> ```
> fsutil dirty query %systemdrive%
> ```
> 
> 如果提示没有权限就正

> 不一定双击启动就不是管理员，如果用户是超级管理员（如默认都Administrator），所有程序将默认用管理员模式运行。
> 
> cmd（非管理员模式）运行以下命令：
> 
> ```
> fsutil dirty query %systemdrive%
> ```
> 
> 如果提示没有权限就正常

安装了最新版本已经恢复ok了 赞
