### ISSUE TITLE
请教各位大佬，这个TAP模式到底怎么开启？ 

### ISSUE THREAD

**Issue by xuyaocrazy** [Fndroid/clash_for_windows_pkg#673]
![Snipaste_2020-04-20_16-00-22](https://user-images.githubusercontent.com/50657741/79728165-1142bd00-8320-11ea-802b-9b12406b45f4.png)

配置文件都填进去了，还是显示网络电脑被拔出？ 
![Snipaste_2020-04-20_16-01-48](https://user-images.githubusercontent.com/50657741/79728512-9ded7b00-8320-11ea-98fa-419d49d9c3fd.png)

官方文档的开启步骤也没有讲的很详细。看了其他的TAP问题，没找到详细的开启步骤~~~ 以太网我把它改成了：WLAN。就想开启TAP模式让客户端软件也能实现代理，太难了。

请教各位大佬，正确的步骤应该是怎样的！！
望大佬帮忙。

**Comment by 1121726636** [comment]
[#624](https://github.com/Fndroid/clash_for_windows_pkg/issues/624)

**Comment by 1121726636** [comment]
最好不在全局配置里加，在Profiles栏里加比较好，加好安装TAP网卡重启clash就行

**Comment by xuyaocrazy** [comment]
![Snipaste_2020-04-20_17-49-05](https://user-images.githubusercontent.com/50657741/79738778-ce88e100-832f-11ea-8157-ce4eea182529.png)
![Snipaste_2020-04-20_17-52-54](https://user-images.githubusercontent.com/50657741/79738790-d21c6800-832f-11ea-8564-a1f0fea5546a.png)
每个文件都添加了，还是不管用啊

**Comment by 1121726636** [comment]
> ![Snipaste_2020-04-20_17-49-05](https://user-images.githubusercontent.com/50657741/79738778-ce88e100-832f-11ea-8157-ce4eea182529.png)
> ![Snipaste_2020-04-20_17-52-54](https://user-images.githubusercontent.com/50657741/79738790-d21c6800-832f-11ea-8564-a1f0fea5546a.png)
> 每个文件都添加了，还是不管用啊

看你cfw-tap网卡状态，可能是没正确添加语句或者用管理员身份打开的cfw

**Comment by xuyaocrazy** [comment]
![Snipaste_2020-04-20_19-45-46](https://user-images.githubusercontent.com/50657741/79748689-6c84a780-8340-11ea-8aee-c2a96629e3f6.png)
![Snipaste_2020-04-20_19-48-29](https://user-images.githubusercontent.com/50657741/79748716-75757900-8340-11ea-9b71-d356c74c7eb7.png)
语句都是填在最后面的啊， CFW也是直接点开的，没有开启管理员身份

**Comment by Fndroid** [comment]
“使用中的Profile”


![image](https://user-images.githubusercontent.com/16091562/79749632-22042a80-8342-11ea-8194-7782d4329f3a.png)

**Comment by 1121726636** [comment]
> ![Snipaste_2020-04-20_19-45-46](https://user-images.githubusercontent.com/50657741/79748689-6c84a780-8340-11ea-8aee-c2a96629e3f6.png)
> ![Snipaste_2020-04-20_19-48-29](https://user-images.githubusercontent.com/50657741/79748716-75757900-8340-11ea-9b71-d356c74c7eb7.png)
> 语句都是填在最后面的啊， CFW也是直接点开的，没有开启管理员身份

右边配置是错的，
![image](https://user-images.githubusercontent.com/29080642/79749707-3fd18f80-8342-11ea-8fb8-5ef78a02b044.png)应该把这个填进去，mixin是全局config里的

**Comment by 1121726636** [comment]
> ![Snipaste_2020-04-20_19-45-46](https://user-images.githubusercontent.com/50657741/79748689-6c84a780-8340-11ea-8aee-c2a96629e3f6.png)
> ![Snipaste_2020-04-20_19-48-29](https://user-images.githubusercontent.com/50657741/79748716-75757900-8340-11ea-9b71-d356c74c7eb7.png)
> 语句都是填在最后面的啊， CFW也是直接点开的，没有开启管理员身份

右边配置是错的，
![image](https://user-images.githubusercontent.com/29080642/79749882-8fb05680-8342-11ea-9ab0-67fa7e93af5f.png)
应该把这个填进去，mixin应该是全局config里的，不用加就行

**Comment by xuyaocrazy** [comment]
![Snipaste_2020-04-20_20-26-32](https://user-images.githubusercontent.com/50657741/79751520-4c0b1c00-8345-11ea-821c-912d5ededf3d.png)
无法连接到 Internet ， 软件还是无法代理。 还是哪些地方没设置好吗~~~

**Comment by 1121726636** [comment]
![image](https://user-images.githubusercontent.com/29080642/79752763-6514cc80-8347-11ea-938b-f51d20848c9a.png)
![image](https://user-images.githubusercontent.com/29080642/79752819-765dd900-8347-11ea-91f1-8319e62052a4.png)
这是我的配置和正常使用的网卡状态，只在这个配置文本里并且是开头加了dns相关语句，config和list里面都没加，希望能对你有帮助

**Comment by 1121726636** [comment]
顺带一提，如果是在config中添加语句是这样
![image](https://user-images.githubusercontent.com/29080642/79753950-57f8dd00-8349-11ea-96a4-9e9ad4fe9aa7.png)并且v0.9.6右下角需要打开Mixin
![image](https://user-images.githubusercontent.com/29080642/79754068-8080d700-8349-11ea-8cba-6cb3376ef66a.png)

**Comment by xuyaocrazy** [comment]
![image](https://user-images.githubusercontent.com/50657741/79758712-52eb5c00-8350-11ea-8221-a89c7cb3f427.png)
谢谢大佬们的热心讲解。 @1121726636 太感谢您了！！！
