### ISSUE TITLE
求助：clash for windows添加订阅的时候出现错误：Proxy1:unsupport proxy type:trojan

### ISSUE THREAD

**Issue by 471898998** [Fndroid/clash_for_windows_pkg#675]
在添加订阅的时候弹出Could not switch to this profile!
错误提示：Proxy1:unsupport proxy type:trojan

之前用的都没问题，今天突然这样了，卸载重装也不管用，请问大佬怎么解决呀？

**Comment by Fndroid** [comment]
什么版本

**Comment by dankexiahuxi** [comment]
我的电脑也出现了，我一直觉得是不是因为我前段时间下载了一个vpn，后面突然用不了我卸载后，一开始网页都打不开只能用其他软件微信也能用，后面网上说是dns出了问题。然后我就设置成自动获取dns和自动获取IP才可以用浏览器的。我不知道这个错误提示是不是这个原因导致的

**Comment by dankexiahuxi** [comment]
![Uploading IMG_20230519_155056.jpg…]()
