### ISSUE TITLE
TAP网卡显示网络电缆被拔出

### ISSUE THREAD

**Issue by ForeverBRS** [Fndroid/clash_for_windows_pkg#676]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载
- [x ] 软件下载后未修改任何安装目录中的文件

**描述**
TAP网卡安装后不能使用，之前0.9.3也有这个问题

**复现**
启动clash for windows
打开dashboard
点击install tap device
网络连接出现TAP-Windows Adapter V9
显示“网络电缆已被拔出”

**预期行为**
tap网卡应显示“已连接”

**截图**
![image](https://user-images.githubusercontent.com/43440593/79827813-e7e26980-83d1-11ea-90ed-cedd05776109.png)

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
dns配置了么，interface-name配置了么

**Comment by ForeverBRS** [comment]
DNS为默认的10.0.0.1，interface-name没有配置

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/tap.html

**Comment by tifish** [comment]
我这里也是同样的现象，redir-host和fake-ip都不行。曾经有个0.9.x的版本成功过，但之后再也没有能成功使用。

**Comment by ForeverBRS** [comment]
你试试在配置文件里加Experimental:(你的网卡名)




 
发件人： Tinyfish
发送时间： 2020-05-23 00:24
收件人： Fndroid/clash_for_windows_pkg
抄送： ForeverBRS; Author
主题： Re: [Fndroid/clash_for_windows_pkg] TAP网卡显示网络电缆被拔出 (#676)
我这里也是同样的现象，redir-host和fake-ip都不行。曾经有个0.9.x的版本成功过，但之后再也没有能成功使用。

**Comment by Roarcannotprogramming** [comment]
同样出现这个问题
配置文件加入
```
dns:
   enable: true
   enhanced-mode: fake-ip
   listen: 0.0.0.0:53
   nameserver:
      - 223.5.5.5
experimental:
   interface-name: '以太网'
```
然后在TAP device中install 
![image](https://user-images.githubusercontent.com/34340275/83950186-55036e80-a85b-11ea-9b8d-e9ce779851f2.png)
在网络和共享中心中只能看到以太网活跃
![image](https://user-images.githubusercontent.com/34340275/83950204-7e23ff00-a85b-11ea-8c4e-52c3d448254e.png)
在网络连接中显示网络线缆拔出
![image](https://user-images.githubusercontent.com/34340275/83950215-98f67380-a85b-11ea-8875-17273ab3c698.png)

**Comment by doudoubinga** [comment]
添加好这个
dns:
   enable: true
   enhanced-mode: fake-ip
   listen: 0.0.0.0:53
   nameserver:
      - 223.5.5.5
experimental:
   interface-name: '以太网'
然后把规则模式改成全局就好了
# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Global
