### ISSUE TITLE
为什么我的老是出现这个啊

### ISSUE THREAD

**Issue by isArtJay** [Fndroid/clash_for_windows_pkg#679]
![image](https://user-images.githubusercontent.com/48620527/79869474-00737380-8414-11ea-9041-d32bad17e2d6.png)

**Comment by Fndroid** [comment]
什么版本，试过最新版了吗

**Comment by isArtJay** [comment]
> 什么版本，试过最新版了吗

就是最新版，重启了电脑，现在好了
