### ISSUE TITLE
现在能实现 允许局域网连接吗

### ISSUE THREAD

**Issue by FFTU** [Fndroid/clash_for_windows_pkg#68]
首先感谢开发者
问个问题，现在有这个功能吗？类似飞机的那个  “允许局域网连接”，让其他电脑也能用节点

**Comment by Fndroid** [comment]
1. 点击General里的Home Directory右边的路径
2. 编辑打开文件夹里的config.yml，将allow-lan的值改成**true**
3. 重启软件
4. 查看代理地址
![image](https://user-images.githubusercontent.com/16091562/52685398-89775b00-2f84-11e9-8f89-43ca4bf822fb.png)
