### ISSUE TITLE
规则代理变为全局代理

### ISSUE THREAD

**Issue by liucan12138** [Fndroid/clash_for_windows_pkg#682]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载
- [x ] 软件下载后未修改任何安装目录中的文件

**描述**
选择规则代理，实际却是全局代理，查看ip地址全是服务器的ip地址，不知道是我哪儿没有设置对，原来0.9.2都是好好的，后来升级0.9.3就变成这样了，再卸载重装最新0.9.6也不行

**截图**
![QQ截图20200422094800](https://user-images.githubusercontent.com/49614071/79931806-6dbbee80-847e-11ea-8940-fc9d58350254.png)

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
规则问题
