### ISSUE TITLE
system proxy开启后Windows聚焦不能更新图片

### ISSUE THREAD

**Issue by Ansoek** [Fndroid/clash_for_windows_pkg#683]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
system proxy开启后Windows聚焦不能更新图片，关闭后一刷新就可以了

**Comment by Fndroid** [comment]
UWP Loopback 里全选上了吗

**Comment by Ansoek** [comment]
> UWP Loopback 里全选上了吗

解决了，确实是这个问题
