### ISSUE TITLE
0.9.6版本添加规则后，刷新规则会被删掉

### ISSUE THREAD

**Issue by Amhertx** [Fndroid/clash_for_windows_pkg#685]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载
- [x ] 软件下载后未修改任何安装目录中的文件

**描述**
添加规则后，点刷新，添加的规则会消失

**复现**
请描述复现问题的步骤:
1. 进入'profiles'
2. 点击'rule'
3.add添加规则
4. save
5.点击刷新更新rule按钮

**预期行为**
清晰地描述期望看到的行为

**截图**
![image](https://user-images.githubusercontent.com/46993971/79954369-d079ae00-84af-11ea-94eb-83fbbfce34f2.png)
保存后点击刷新
![image](https://user-images.githubusercontent.com/46993971/79954423-e2f3e780-84af-11ea-8ffd-30b81862d3dc.png)

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
刷新是重新下载配置文件，这是预期行为
