### ISSUE TITLE
TAP模式建议

### ISSUE THREAD

**Issue by LeonSparta** [Fndroid/clash_for_windows_pkg#686]
**描述**
TAP模式可以达到与路由器代理相似的效果，但是因为默认CFW开启时会将系统代理（WINDOWS系统设置-网络设置-代理）打开，如若不将UWP应用加入回环，微软的Movies&TV以及应用商店或者说UWP应用都会出现没有网络的情况，此时将系统代理关闭又可以正常使用。
能否添加TAP模式运行方式，此时不自动打开系统代理呢，只用TAP接管流量。
建议原因：因为Movies&TV未知原因，即便流量通过CFW代理后，看电影时速度也很慢，与未开代理时速度一样。
目前能将其成功“代理”的方法就是通过TAP接管流量，若在TAP开启时将其加入回环，速度与未开启TAP时一样，应该是没有通过TAP接管；若不加入回环，不关闭系统代理又访问不了网络。因此目前唯一可行的方法就是开启带有TAP的CFW后手动关掉系统代理。

**Comment by Fndroid** [comment]
手动关闭System Proxy也不会有多麻烦吧

**Comment by LeonSparta** [comment]
好嘛好嘛。
其实还想知道为什么Movies&TV那么奇葩，加入回环后虽然串流速度慢，但是下载的话速度又是很快的。

**Comment by LeonSparta** [comment]
> 
> 
> 手动关闭System Proxy也不会有多麻烦吧，而且TAP也能做成mixin在任务栏里开关
那请问可以通过mixin来控制系统开关代理吗，不是很清楚通过什么指令来达到开关系统代理的。

**Comment by LeonSparta** [comment]
突然发现如果只打开CFW而不启动系统代理，启用TAP的话就会达到我想要的TAP接管所有流量的效果。
