### ISSUE TITLE
可否将规则独立于服务器profiles之外

### ISSUE THREAD

**Issue by LeslieSong** [Fndroid/clash_for_windows_pkg#687]
目前规则都是在服务器profiles里面定义，一旦更新之后，自定义的规则就没有了。很多网友都提过类似的问题。
可以参考shadowsocks软件，使用订阅的方式去获取、更新gfwlist.txt文件，并可以在这个文件基础上进行本地编辑。
建议就在proxies界面的Rule按钮上添加查看、更新、编辑功能。

**Comment by GrayXu** [comment]
duplicated. you should check clash core repo.  
[Dreamacro/clash#272
](https://github.com/Dreamacro/clash/issues/272)
