### ISSUE TITLE
订阅配置出现 could not switch to this profile!

### ISSUE THREAD

**Issue by jason-chang** [Fndroid/clash_for_windows_pkg#688]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [X] 已经尝试更新到最新版本，问题依旧存在
- [X] 软件从本仓库下载
- [X] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题

**复现**
请描述复现问题的步骤:
1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
清晰地描述期望看到的行为

**截图**
如果可以，请提供对应问题的截图
![image](https://user-images.githubusercontent.com/4367687/80063268-1f831a00-8568-11ea-886e-5270c199db62.png)

**其他说明**
其他补充内容
使用版本 0.9.6

配置如下 请开发者大大 重命名去掉 .txt
[config.yml.txt](https://github.com/Fndroid/clash_for_windows_pkg/files/4520493/config.yml.txt)

**Comment by Fndroid** [comment]
CFW启动成功了吗，General有没有报错

**Comment by skywd** [comment]
0.7.8 版本出现该问题，无法解决

**Comment by skywd** [comment]
> 0.7.8版本出现该问题，无法解决

问题已解决，升级0.9.6版本前（清空config配置）

**Comment by jason-chang** [comment]
@skywd 谢谢,清配置后正常
