### ISSUE TITLE
0.9.6今天crash了

### ISSUE THREAD

**Issue by heham** [Fndroid/clash_for_windows_pkg#689]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载
- [x ] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题
今天上午可以正常使用，中午睡觉起来发现crash了，显示dashboard has crashed！两个选择reload 和exit。
**复现**
请描述复现问题的步骤:
偶然碰到一次，不知道到怎么复现

**预期行为**
清晰地描述期望看到的行为
正常运行
**截图**
如果可以，请提供对应问题的截图
不知道怎么发图片附件，如上描述。
**其他说明**
其他补充内容

**Comment by skywd** [comment]
clash for windows 0.7.8 出现问题，无法订阅，点击downloading出现error！

**Comment by Fndroid** [comment]
把log-level设置成silent试试

**Comment by heham** [comment]
> 把log-level设置成silent试试

那个一直都是silent
