### ISSUE TITLE
配置文件能否支持#号开头的注释？

### ISSUE THREAD

**Issue by yyysuo** [Fndroid/clash_for_windows_pkg#69]
自己想写个注释，直接提示UTF8的开头不支持。

**Comment by Fndroid** [comment]
支持的

**Comment by yyysuo** [comment]
能给个带注释的配置示例吗？每行顶格写个#我试过了，是不可以的。

**Comment by Fndroid** [comment]
```
# Test

port: 8888
socks-port: 8889
```

**Comment by yyysuo** [comment]
明白了，注释不支持中文，英文不报错，中文报下面的错误。

yaml:invalid leading UTF-8 octet Clash for Windows

**Comment by Fndroid** [comment]
试了一下，也不会，你是改的config.yml？

**Comment by yyysuo** [comment]
不是，改的自动生成的一串数字的那个yml文件，系统是windows 10 pro x64最新版本，cfw是最新的，文本编辑器试过win自带的notepad和emeditor，另存时指定编码也不管用。

**Comment by Fndroid** [comment]
文件编码改为UTF8
