### ISSUE TITLE
使用TAP模式时Windows系统登陆账号显示网络错误

### ISSUE THREAD

**Issue by LeonSparta** [Fndroid/clash_for_windows_pkg#691]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
使用TAP模式时Windows系统登陆账号显示网络错误，输入完账号添加就显示没有网络连接，请检查网络。

**复现**
请描述复现问题的步骤:
1. 开启CFW TAP模式
2. 打开Win10邮件应用
3. 添加账号
4. 触发问题

**预期行为**
正常登录

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/466#issuecomment-614716133

**Comment by LeonSparta** [comment]
> 
> 
> [#466 (comment)](https://github.com/Fndroid/clash_for_windows_pkg/issues/466#issuecomment-614716133)

好的，谢谢大哥
