### ISSUE TITLE
无法在基于arm64芯片的机器上运行

### ISSUE THREAD

**Issue by fredzb2013** [Fndroid/clash_for_windows_pkg#692]
去年到今年，陆续出现了基于新arm64架构的Windows 10平板或笔记本，其中有Microsoft Surface Pro X和三星的Galaxy Book S。我目前是在使用Galaxy Book S，基于高通8cx。当我试图运行Clash时，遇到如下错误：

![image](https://user-images.githubusercontent.com/37322476/80115273-238a5880-85b7-11ea-854c-7c3e821c438a.png)

是否可以在下个版本中修复？

**Comment by Fndroid** [comment]
修复？这是要适配一个arm64的版本，不是一个bug。。

**Comment by Fndroid** [comment]
Duplicate of #https://github.com/Fndroid/clash_for_windows_pkg/issues/670
