### ISSUE TITLE
Profiles-Edit policies和Profiles-Edit rules功能界面无法正常显示

### ISSUE THREAD

**Issue by coderloverXH** [Fndroid/clash_for_windows_pkg#694]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件
使用环境：win10 、Clash for window v 0.9.7

**描述**
Profiles-Edit policies和Profiles-Edit rules功能界面无法正常显示

**复现**
请描述复现问题的步骤:
1. 进入'Profiles'
2. 点击'Edit policies'图标或'Edit rules'图标，发现功能界面无法正常显示

**预期行为**

**截图**
（1）点击Profiles里的'Edit policies'图标或'Edit rules'图标
![1-1](https://user-images.githubusercontent.com/63088614/80167626-77c32600-8613-11ea-966b-9caeefc16a17.png)
（2）然后发现'Edit policies'功能界面无法正常显示
![1-2](https://user-images.githubusercontent.com/63088614/80167692-9c1f0280-8613-11ea-8d95-1a371f5df3d7.png)
（3）然后发现'Edit rules'功能界面无法正常显示，也无法匹配规则。
![1-3](https://user-images.githubusercontent.com/63088614/80167737-b78a0d80-8613-11ea-9ec8-74eea6390132.png)

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
预期行为。

此版本后将不再支持编辑Rule/Proxy/Proxy Group字段配置文件，请用rules/proxies/proxy-groups替代

**Comment by penwong** [comment]
我觉得普通用户修改成本有点大，这些升级换代的不能无缝更新吗

**Comment by Fndroid** [comment]
@penwong 因为我不想我的开发成本变大

**Comment by penwong** [comment]
> @penwong 因为我不想我的开发成本变大

好吧，毕竟免费，但大量的issue反映文档指引也没写，0.9.9删除.config，再生成也是旧的字段配置。

**Comment by penwong** [comment]
> @penwong 因为我不想我的开发成本变大

无意冒犯，绝对理解。不太会说话

**Comment by lickety** [comment]
> @penwong 因为我不想我的开发成本变大

建议再考虑一下更新兼容老版,你这样大量用户不能正常使用,每个用户耗费10分钟去处理的话,累加耗费了多少用户多少时间你想过没
不断用户来反馈,也白耗费项目维护人员的时间

**Comment by suyi1117** [comment]
已加退9.6

**Comment by LeslieSong** [comment]
> 预期行为。
> 
> 此版本后将不再支持编辑Rule/Proxy/Proxy Group字段配置文件，请用rules/proxies/proxy-groups替代

没查到修改这个的地方呀……

**Comment by chenzhihao1040728129** [comment]
> @penwong因为我不想我的开发成本变大
理解理解, 就是对新用户来说成本过大, 网上的自定义规则都是之前的版本!

**Comment by zazitufu** [comment]
1，在Profiles界面，在你需要修改的配置文件那里，点击左下的Edit in text mode，进入文本编辑模式。

2，在文本编辑里面，
把【Rule】修改为【rules】，
把【Proxy】修改为【proxies】，
把【Proxy Group】修改为【proxy-groups】。
其实就是修改3个地方，不要输入括号，注意大小写敏感。不要直接搜索替换，免得把其他地方的也弄掉了。

3，其实这很简单的修改方式，作者不愿意在release更新/wiki里加以说明，而愿意在issue里面看一堆人来问，只能说程序员的思路跟普通人不同。我能理解修改字段降低开发成本，但无法理解不加说明文档造成的issue。

**Comment by chenzhihao1040728129** [comment]
> 1，在Profiles界面，在你需要修改的配置文件那里，点击左下的Edit in text mode，进入文本编辑模式。
> 
> 2，在文本编辑里面，
> 把【Rule】修改为【rules】，
> 把【Proxy】修改为【proxies】，
> 把【Proxy Group】修改为【proxy-groups】。
> 其实就是修改3个地方，不要输入括号，注意大小写敏感。不要直接搜索替换，免得把其他地方的也弄掉了。
> 
> 3，其实这很简单的修改方式，作者不愿意在release更新/wiki里加以说明，而愿意在issue里面看一堆人来问，只能说程序员的思路跟普通人不同。我能理解修改字段降低开发成本，但无法理解不加说明文档造成的issue。

谢了兄弟!

**Comment by Fndroid** [comment]
@zazitufu  所以所谓的“普通人”能去看wiki和release note也没空看看issue上面的pin是吧，发issue也不会先搜索是吧，github给出来的类似推荐也能顺便忽略掉是么

**Comment by zazitufu** [comment]
> @zazitufu 所以所谓的“普通人”能去看wiki和release note也没空看看issue上面的pin是吧，发issue也不会先搜索是吧，github给出来的类似推荐也能顺便忽略掉是么


一个能看懂源码并提出修改意见的人，可能会是你的用户
一个只会打开/关闭软件的人，也可能会是你的用户

作者有技术，希望你的产品更多人使用，也希望你的产品更容易使用。

**Comment by yi-Xu-0100** [comment]
根据当前的[配置文件预处理方法](https://docs.cfw.lbyczf.com/contents/parser.html)以及以前的[作者写过的配置例子](https://github.com/Fndroid/clash_for_windows_pkg/issues/877)，给出如下便捷修改方式：

在 **`Settings`** 中的 **`Profiles`** 中的 **`Parsers`** 中设置如下:

``` yaml
parsers:
  - url: https://example.com/example.yaml
    code: |
      module.exports.parse = (raw, { yaml }) => {
        const rawObj = yaml.parse(raw)
        const { 'Rule': rules = [], 'Proxy Group':groups = [], 'Proxy': proxies = [] } = rawObj
        delete rawObj['Rule']
        delete rawObj['Proxy Group']
        delete rawObj['Proxy']
        return yaml.stringify({ ...rawObj, proxies, 'proxy-groups': groups, rules })
      }
```

**注意**：
1. 修改 **`url`** 为对应的订阅链接。
2. 如果有多个订阅，复制多份，保证 yaml 格式并相应修改对应链接。

**Comment by BCccc64** [comment]
> 
> 
> 1，在Profiles界面，在你需要修改的配置文件那里，点击左下的Edit in text mode，进入文本编辑模式。
> 
> 2，在文本编辑里面，
> 把【Rule】修改为【rules】，在规则列表最开头。
> 把【Proxy】修改为【proxies】，在节点列表最开头。
> 把【Proxy Group】修改为【proxy-groups】，在节点规则组最开头。
> 其实就是修改3个地方，不要输入括号，注意大小写敏感。不要直接搜索替换，免得把其他地方的也弄掉了。
> 
> 3，其实这很简单的修改方式，作者不愿意在release更新/wiki里加以说明，而愿意在issue里面看一堆人来问，只能说程序员的思路跟普通人不同。我能理解修改字段降低开发成本，但无法理解不加说明文档造成的issue。

在最新的0.11.2中不修改rule，只修改后两项才可使用，否则会切换不了该订阅节点

**Comment by Lanpice** [comment]
> > @zazitufu 所以所谓的“普通人”能去看wiki和release note也没空看看issue上面的pin是吧，发issue也不会先搜索是吧，github给出来的类似推荐也能顺便忽略掉是么
> 
> 一个能看懂源码并提出修改意见的人，可能会是你的用户
> 一个只会打开/关闭软件的人，也可能会是你的用户
> 
> 作者有技术，希望你的产品更多人使用，也希望你的产品更容易使用。

同意。程序本身没有任何提示，项目首页README没有说明，wiki没有说明，每个升级的用户都要自行排查一遍，回滚的回滚，google的google，都是时间成本。作者不愿兼容无可厚非，但是不愿意在显眼的地方给个指引，最终还得来issues里问/查。这个我也无法理解。
如果一个商业产品发了一个不兼容的新版本，不发公告，release note不注明，也不通知用户，等用户提工单或者找客服后，丢了个入口不显眼的url过来告诉用户：我告诉你们不兼容了啊。我相信这样会引起不少用户的不满的，也会给客服和售后团队增加压力。不愿意兼容，最起码让用户知道有变动，知道怎么处理也好过现在的issues里有不少说的是同一个问题吧。

**Comment by yi-Xu-0100** [comment]
1. 程序非商业产品，应该。
2. 前几次更新中有提到需要注意适配。
3. 发布 issue 之前查看置顶 issue 和查询历史 issue 减少困扰，我觉得应该是用户的义务。
4. 更多的提示和说明会更好，但个人作品，无可厚非，个人风格。
5. 个人观点，不代表作者立场和想法，如果不愿意了解产品风格或不适应产品风格，我觉得更换产品就好，毕竟这是个人作品，时间和精力有限，感觉没法照顾到所有人。
7.参见[提问的智慧](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)，会更方便交流。
