### ISSUE TITLE
0.9.7 Profiles/Edit rules 消失了

### ISSUE THREAD

**Issue by ntol** [Fndroid/clash_for_windows_pkg#696]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题
如题：ver0.9.7 Profiles/Edit rules 全部消失了，但在Connections里面查看，实际还是按rules走的。

**复现**
请描述复现问题的步骤:
1. 进入'Profiles'
2. 点击任意Profile的'Edit rules'
3. 触发问题

**预期行为**
清晰地描述期望看到的行为

**截图**
如果可以，请提供对应问题的截图
![image](https://user-images.githubusercontent.com/6648081/80170139-de4b4280-8619-11ea-8cd4-0f7cff89ff4d.png)

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
Duplicate of #https://github.com/Fndroid/clash_for_windows_pkg/issues/694?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDgzODI2MjY5NToxNjA5MTU2Mg%3D%3D#event-3267558409
