### ISSUE TITLE
Script 模式无法折叠策略组

### ISSUE THREAD

**Issue by AzunyanDaisuki** [Fndroid/clash_for_windows_pkg#698]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [ ] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题
除 Rule 模式，其它模式均无法折叠策略组，在 Script 下对正常使用影响较大。
**复现**
请描述复现问题的步骤:
1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
清晰地描述期望看到的行为
策略组可以折叠。
**截图**
如果可以，请提供对应问题的截图

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
fixed in release:https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.8
