### ISSUE TITLE
删除后重新安装启动界面空白Profiles下载失败（已解决）

### ISSUE THREAD

**Issue by YuLaiZ** [Fndroid/clash_for_windows_pkg#702]
**为什么提issue**
在issue中发现有类似问题，并没有解决方案，大家可以参考是否相同问题
希望开发者可以在下个版本进行针对性优化
解决方法在最后

**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
版本v 0.9.7
zip解压方式安装使用，之后删除目录
再次安装，打开后General空白，Profiles下载失败
已尝试退回版本v 0.9.6，尝试exe方式安装与卸载再重新安装

Profiles下载、启用提示：
Could not switch to this profile!
Cannot read property 'put' of null

**复现**
请描述复现问题的步骤:
1. zip解压使用
2. 关闭程序
3. 删除目录
4. 再次安装
5. 触发问题

**预期行为**
希望正常运行

**截图**
![clash_for_windows_pkg_issues_1](https://user-images.githubusercontent.com/8369157/80197942-f8087c00-8651-11ea-909b-3891b761bc7a.png)
![clash_for_windows_pkg_issues_2](https://user-images.githubusercontent.com/8369157/80197946-f939a900-8651-11ea-9074-016cf70ef9cb.png)

**解决方案**
删除C:\Users\{UserName}\.config\clash后，重新启动程序，问题解决
未验证覆盖升级后是否会出现该问题

**Comment by airium** [comment]
遇到了一样的情况，版本为 0.17.1
解决方法为删除profile文件夹下(如果portable模式则是主程序同目录dat目录下)的config.yaml
为该文件内容错误导致，在vscode或quicklook下提示为二进制文件
同理可以检查任何其它yaml文件
