### ISSUE TITLE
选择直连模式后能不能直接关掉代理？

### ISSUE THREAD

**Issue by liuhl666** [Fndroid/clash_for_windows_pkg#705]
选择直连模式后能不能直接关掉代理而不只是在软件里面应用直连规则？

**Comment by Fndroid** [comment]
关闭系统代理不就好

**Comment by Lighsark** [comment]
直连模式： 无法正常访问Google服务。
Rule模式： Google匹配直连规则无法访问。
_在墙外非美国关掉代理可访问Google_
不能直接关闭系统代理，因为Hulu，Desney+，ABC等等需要走美国代理。
