### ISSUE TITLE
0.9.7版本后连接不上本地 socks5 代理

### ISSUE THREAD

**Issue by jarvanh** [Fndroid/clash_for_windows_pkg#706]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [ x] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载
- [ x] 软件下载后未修改任何安装目录中的文件

**描述**
更新0.9.7版本后连接不上本地 socks5 代理

**复现**
请描述复现问题的步骤:
1. 节点使用本地 socks5 代理

**截图**
![image](https://user-images.githubusercontent.com/5900885/80223475-ec7d7b00-867a-11ea-96eb-4c17e2c1a97e.png)

**Comment by jarvanh** [comment]
![image](https://user-images.githubusercontent.com/5900885/80223828-63b30f00-867b-11ea-8dd0-4193910f89d7.png)

**Comment by jarvanh** [comment]
没有使用tap模式。更新0.9.7版本的时候删除了 interface-name 字段

**Comment by Fndroid** [comment]
是个bug，可以先退回上一版先

**Comment by jarvanh** [comment]
好的。谢谢！

**Comment by Fndroid** [comment]
fixed in release:https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.8

**Comment by Dibel** [comment]
Same problem in 0.9.8

![image](https://user-images.githubusercontent.com/3395113/80240979-5a36a080-8695-11ea-8f25-c52458e70321.png)

**Comment by Fndroid** [comment]
> Same problem in 0.9.8
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/3395113/80240979-5a36a080-8695-11ea-8f25-c52458e70321.png)
> 
> 
> 
> 

如果想用Clash内置的DNS，但又不使用TAP，需要将dns: listen去掉或监听在127.0.0.1上，不然会被误判成TAP模式，影响联网

**Comment by jarvanh** [comment]
@Dibel 参考我的配置
