### ISSUE TITLE
once edit and save user rule, it will stop work.

### ISSUE THREAD

**Issue by mcdulljobs** [Fndroid/clash_for_windows_pkg#707]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题

**复现**
请描述复现问题的步骤:
1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
清晰地描述期望看到的行为

**截图**
如果可以，请提供对应问题的截图

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
添加了什么规则？

**Comment by mcdulljobs** [comment]
比如
- DOMAIN-SUFFIX,jd.com,DIRECT
- DOMAIN-SUFFIX,zoom.us,DIRECT
添加了点save，然后就google都打不开了。
0.96 之前版本是好的。
