### ISSUE TITLE
0.9.7和0.9.8版本，edit rules中的列表为空

### ISSUE THREAD

**Issue by Sazanka** [Fndroid/clash_for_windows_pkg#709]
0.9.7和0.9.8版本，edit rules中的列表为空。
退回0.9.6之后，列表恢复正常。

![20200425020256](https://user-images.githubusercontent.com/64279019/80243236-6b81ac00-8699-11ea-9c53-22e8ce0df6da.jpg)

**Comment by Fndroid** [comment]
Duplicate of #694
