### ISSUE TITLE
UTF-8配置文件注释被覆盖，Proxy Group明明存在提示不存在

### ISSUE THREAD

**Issue by yyysuo** [Fndroid/clash_for_windows_pkg#71]
大佬，有2个建议，请您考虑
1：Profile图形界面编辑节点或者规则后保存，编码格式默认为ANSI，会把原来UTF-8格式的配置文件覆盖掉，这样原来的注释就丢掉了。
2：Proxy Groups嵌套情况下，比如先定义了Group A，新建Group B时包含A时，有时候会提示不存在。
原因是默认是从配置文件Group B位置向上搜索A，搜索不到则提示A不存在，可否同时搜索向上向下2个方向
搜索？

**Comment by Fndroid** [comment]
1. UI编辑会将yml数据load成JavaScript对象，注释会被忽略。
2. Group的引用和定义由Clash核心控制。
