### ISSUE TITLE
0.9.8版本Allow LAN开关一旦打开无法关闭

### ISSUE THREAD

**Issue by kris115** [Fndroid/clash_for_windows_pkg#710]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
在General界面点击开启Allow LAN开关后，无法关闭开关。

**复现**
请描述复现问题的步骤:
1. 进入Dashboard
2. 点击General
3. 点击Allow LAN
4. 鼠标移动到这个开关时，会弹出当前网卡ip信息遮挡开关，且网卡信息不会消失，开关无法点击关闭。

**预期行为**
网卡信息显示后，能够点击关闭Allow Lan开关

**截图**
![Snipaste_2020-04-25_07-59-48](https://user-images.githubusercontent.com/12155282/80265668-dd261e00-86ca-11ea-8d25-a693573d5f72.png)

**其他说明**
无

**Comment by metathrone** [comment]
我也有这个情况 鼠标在clash窗体里面移动的时候提示框会消失 移出clash窗体后不消失

**Comment by TsXcd** [comment]
今天也遇到了，只能暂时去修改主配置config.yaml文件来关掉了

**Comment by Fndroid** [comment]
下个版本移到底部居中

**Comment by Fndroid** [comment]
最新版已调整
