### ISSUE TITLE
0.9.8 Edit Policies UI界面读取配置文件不正常

### ISSUE THREAD

**Issue by XiaoHuoZZ** [Fndroid/clash_for_windows_pkg#712]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题
当cfw读取我的配置文件时，Edit Policies UI界面不会显示配置文件里的proxy groups和proxies，我确信配置文件没有语法错误且不影响正常使用
**复现**
请描述复现问题的步骤:
1.点击Profiles
2.点击Edit Policies

**预期行为**
读取配置文件正常

**截图**
![image](https://user-images.githubusercontent.com/36838772/80268841-3ac36600-86dd-11ea-8151-dc4e16915ce2.png)
![image](https://user-images.githubusercontent.com/36838772/80268874-9b52a300-86dd-11ea-923f-a9a3f00c0720.png)

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
Duplicate of #694

**Comment by XiaoHuoZZ** [comment]
Sorry , I don't see that
