### ISSUE TITLE
v0.9.8及v0.9.7，profiles内点击任意文件的edit profiles均为空白

### ISSUE THREAD

**Issue by livinghub** [Fndroid/clash_for_windows_pkg#715]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [√] 已经尝试更新到最新版本，问题依旧存在
- [√] 软件从本仓库下载
- [√] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题
从v0.9.7开始，发现profiles内点击任意文件的edit profiles均为空白，edit in text mode正常，proxies正常，使用正常。v0.9.8下覆盖重装，卸载重装均不能解决问题。

**复现**
请描述复现问题的步骤:
1. 进入'clash for Windows'
2. 点击'profiles'
3. 点击任意配置文件的'edit profiles'
4. 触发问题，编辑页面一片空白

**预期行为**
edit profiles内编辑功能恢复正常。

**截图**
![image](https://user-images.githubusercontent.com/23092938/80271143-ef668300-86ef-11ea-9110-8089193cc764.png)

**其他说明**
无

**Comment by Fndroid** [comment]
Duplicate of https://github.com/Fndroid/clash_for_windows_pkg/issues/694
