### ISSUE TITLE
规则列表不见了

### ISSUE THREAD

**Issue by Amhertx** [Fndroid/clash_for_windows_pkg#719]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载
- [ x] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题
![image](https://user-images.githubusercontent.com/46993971/80277117-7a12a680-871f-11ea-9f90-302da8810b5c.png)
规则列表不显示了，点击edit rule进来什么规则都没有，但是直接打开yml是有规则的
![image](https://user-images.githubusercontent.com/46993971/80277168-cd84f480-871f-11ea-947c-8938824e8905.png)

**复现**
请描述复现问题的步骤:
1. 进入''
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
清晰地描述期望看到的行为

**截图**
如果可以，请提供对应问题的截图
![image](https://user-images.githubusercontent.com/46993971/80277141-9b739280-871f-11ea-8d32-02d8c9121231.png)

**其他说明**
其他补充内容

**Comment by zhouzl7** [comment]
我也遇到了这个问题，请问你是怎么解决的？

**Comment by Amhertx** [comment]
> 我也遇到了这个问题，请问你是怎么解决的？

我，自己更改了通过clash订阅更新下来的一些字段
