### ISSUE TITLE
0.9.8 加载配置文件失败

### ISSUE THREAD

**Issue by v3470** [Fndroid/clash_for_windows_pkg#720]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
跟 https://github.com/Fndroid/clash_for_windows_pkg/issues/688 有点类似，也是`Could not switch to this profile!` `Cannot read property 'put' of null`。

**复现**
可能要特定的配置文件才能触发

**预期行为**
正常加载

**截图**
跟 #688 一样

**其他说明**
- 配置文件是从机场订阅的。
- 为了解决这个问题，尝试使用旧版本（随便下载了个0.9.0），然后运行提示failed，要清空配置文件。清空之后再下载profile就又可以了。之后尝试升级到0.9.5, 0.9.7，最后到0.9.8，都正常。
- 于是目前为了保险起见，留了一份0.9.0保底

**Comment by mixool** [comment]
我的情况是最新版，编辑改变profile的proxy后，无论重启cfw还是重新选择profile ，cfw选择代理还是编辑以前的那个代理，即使已经删除。
