### ISSUE TITLE
使用Allow LAN 功能后，虚拟机里的系统传输非常的慢，宿主系统速度正常

### ISSUE THREAD

**Issue by tea1111980** [Fndroid/clash_for_windows_pkg#721]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题
我使用VMware虚拟机上的CentOS7系统，想让它下载一些程序包，但是使用后速度非常的慢，以前我在 `SS` 上也使用过这个功能，但是速度正常。
另外，我在主机上使用 `Clash` 传输，没问题，代理速度正常。
没有安装 Linux版本的 Clash，因为Linux版本的蛮复杂。使用的都是Win版本的Clash。
**复现**
请描述复现问题的步骤:
同上

**预期行为**
清晰地描述期望看到的行为
想让其它主机使用代理，传输速度正常
另外防火墙我都设置好了，没问题，即使关闭了防火墙也是传输速度慢，我想这已经不是防火墙的问题了，因为在使用此功能上没有阻止的现象。就是传输慢。
**截图**
如果可以，请提供对应问题的截图

#### 虚拟机 上使用截图
![image](https://user-images.githubusercontent.com/16295097/80283805-1010f600-874d-11ea-8830-47c477de032e.png)

#### Win10系统 上使用截图

![image](https://user-images.githubusercontent.com/16295097/80283974-089e1c80-874e-11ea-979f-e72e74fb4006.png)

**其他说明**
无

**Comment by Fndroid** [comment]
确定虚拟机里代理设置好了吗

**Comment by tea1111980** [comment]
> 确定虚拟机里代理设置好了吗

我非常的确定虚拟机 从内到外全部设置都调了一遍，还是不行。这不是  只是弄了几个小时而已，是连续的弄了一个星期。

最终。。我弄好了，不是 @Fndroid Clash for Windows 的锅。是.那...呜呜呜~~我…………想静静。

更新了内核 到最新版，然后去掉了sysctl.conf 调优 只保留了基本的几个，然后突然 网速就像洪水泛滥一样，泳得 我的 Docker 快的都飞上天了，pull IMAGE 嗖嗖的。


不过呢，我还是觉得clash 有些问题：比如 测试延时的那个功能 感觉不太好用，这一段时间 用这功能，一测不要紧，测完全红，并且红的 真的代理不了， 以为红的只是暂时的。

每次测一次速 基本上70%都红了（共20多个服）
但是我问了提供商了，他们那边说是好的。我感觉都蒙了，不知道哪里的问题了。

这个问题我先关了，因为此贴的问题已经解决了。最后，谢了。

**Comment by tea1111980** [comment]
刚才编辑的时候点错了，点到隐藏上面去了，不知道上面的回复，你还看得到不？

**Comment by Fndroid** [comment]
延迟测试是让代理服务器转发一个http head请求的耗时，timeout只有几种可能：
1. 本地连不上代理服务器
2. 代理服务器连不上测试用的url
3. 转发延迟太高，超过timeout

后面两点都可以自定义：https://docs.cfw.lbyczf.com/contents/configfile.html

CFW并不干预这个过程。

**Comment by tea1111980** [comment]
> 延迟测试是让代理服务器转发一个http head请求的耗时，timeout只有几种可能：
> 
> 1. 本地连不上代理服务器
> 2. 代理服务器连不上测试用的url
> 3. 转发延迟太高，超过timeout
> 
> 后面两点都可以自定义：https://docs.cfw.lbyczf.com/contents/configfile.html
> 
> CFW并不干预这个过程。

谢谢回复！
这个问题，我已经解决了。。但是有新的问题来了。不过我先去自已查查 弄弄，实在不行了，再回来请教。

**Comment by BruceDeng619** [comment]
@tea1111980 请教一下。我在笔记本上clash开启allow lan，手机配置wifi，可以扶墙，但是下行速度很慢。您这边知道是出了什么问题吗？

**Comment by hdc8899** [comment]
> @tea1111980 请教一下。我在笔记本上clash开启allow lan，手机配置wifi，可以扶墙，但是下行速度很慢。您这边知道是出了什么问题吗？

请问如何给手机扶墙呀？谢谢
