### ISSUE TITLE
自定义连接规则后，无法连接google等节点

### ISSUE THREAD

**Issue by danyunliuhen** [Fndroid/clash_for_windows_pkg#722]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
正确设置订阅之后,点击编辑Profiles下的Edit rules,增加一个本地直连规则 立刻连接所有爬梯子网址失败

**复现**
请描述复现问题的步骤:
1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
清晰地描述期望看到的行为

**截图**
如果可以，请提供对应问题的截图

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
什么叫``本地直连规则``？

**Comment by danyunliuhen** [comment]
> 什么叫`本地直连规则`？

大佬 抱歉是我描述不清晰 在Clash中操作如下:
Profiles->订阅-->Edit rules-->Add->create a new rule -->增加一个域名关键词类型的Direct连接策略-->bug复现，无法使用节点连接任何除了这个直连规则之外的网址

**Comment by Fndroid** [comment]
我猜你的规则编辑列表里是空的，https://github.com/Fndroid/clash_for_windows_pkg/issues/694
