### ISSUE TITLE
请更新文档

### ISSUE THREAD

**Issue by wulifuji** [Fndroid/clash_for_windows_pkg#723]
文档里并没有描述script，请问是脚本？还是个啥？如果是脚本，给个格式呗

**Comment by FFTU** [comment]
同问

**Comment by Apocalypsor** [comment]
这问题你应该去内核那问，在这问个什么劲。。。
可以参考这个非官方文档：
```https://lancellc.gitbook.io/clash/clash-config-file/script```

**Comment by wulifuji** [comment]
先谢谢您的链接，另cfw也有文档的，并不是想跟您杠哦（**^^**)
