### ISSUE TITLE
EditProxies类型不显示trojan和snell

### ISSUE THREAD

**Issue by Emphasia** [Fndroid/clash_for_windows_pkg#724]
**信息**
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
0.9.6 ``edit policies``中对``proxies``编辑 类型不显示``trojan``和``snell``

**复现**
``Profiles`` - ``edit policies`` - ``proxies``

**截图**
![2020-04-26](https://user-images.githubusercontent.com/8478234/80301894-501dba80-87d9-11ea-96a9-e9796b28a658.png)

一直都是直接编辑的配置所以压根没注意到
刚发现 https://github.com/Fndroid/clash_for_windows_pkg/issues/590 好像也是说的这个

**Comment by Fndroid** [comment]
不支持编辑，手动改一下吧
