### ISSUE TITLE
无法使用韩国winktv等网站

### ISSUE THREAD

**Issue by lklx520** [Fndroid/clash_for_windows_pkg#726]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载
- [x ] 软件下载后未修改任何安装目录中的文件

**描述**
能打开winktv网站，但是无法登陆和观看。

**预期行为**
能使用winktv

**其他说明**
v2ray可以打开

**Comment by Fndroid** [comment]
开global能访问么

**Comment by lklx520** [comment]
不能访问

**Comment by lklx520** [comment]
包括手机端也是如此，手机端也上不了

**Comment by Fndroid** [comment]
你说的winktv是这个么：http://www.winktv.co.kr/

我这里是可以访问的

**Comment by lklx520** [comment]
能播放吗，我是可以访问，但是进不了直播间

Fndroid <notifications@github.com> 于2020年4月27日周一 上午9:24写道：

**Comment by Fndroid** [comment]
@lklx520 能播放
