### ISSUE TITLE
关于UWP LOOPBACK

### ISSUE THREAD

**Issue by RudeTheJack** [Fndroid/clash_for_windows_pkg#727]
![批注 2020-04-26 182651](https://user-images.githubusercontent.com/27954602/80304955-48b3dc80-87ec-11ea-93eb-bf96c2b68509.png)
![批注 2020-04-26 182710](https://user-images.githubusercontent.com/27954602/80304960-4a7da000-87ec-11ea-8182-f6b9220f667d.png)
不知道该怎么解决，手动google了几年都没解决，逼得没办法了，前来求助

**Comment by Fndroid** [comment]
只是警告。这个工具有两个获取uwp应用的方法，其中一个是走系统API，另一个是读注册表，当第一个方法失败了就会用第二个，正常现象。

**Comment by RudeTheJack** [comment]
> 只是警告。这个工具有两个获取uwp应用的方法，其中一个是走系统API，另一个是读注册表，当第一个方法失败了就会用第二个，正常现象。

谢谢大佬解答，但是好像邮箱的uwp不能使用loopback是吗

**Comment by Fndroid** [comment]
不清楚，我基本都用TAP
