### ISSUE TITLE
L2TP VPN可能有冲突。

### ISSUE THREAD

**Issue by mrs504aa** [Fndroid/clash_for_windows_pkg#729]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
在浙大校园网环境下，登录L2TP VPN后无法使用clash for windows 0.9.8和0.9.7，并且有一定概率触发断连VPN。
无法使用指的是GLOBAL，RULE以及DIRECT模式均无法使用。
重新安装0.9.6版本可以正常使用。

**复现**
请描述复现问题的步骤:
1. 进入Windows。
2. 通过学校L2TP连接到互联网。
3. 打开clash。
4. 触发问题

**预期行为**
希望能正常使用最新版的clash。

**截图**
![image](https://user-images.githubusercontent.com/26762860/80329575-5b262880-8875-11ea-88d5-e819af1e2fe2.png)

**其他说明**
修改订阅配置文件中的DNS为学校网络中心DNS，无效。

**Comment by Fndroid** [comment]
把dns里的listen注释掉试试

**Comment by mrs504aa** [comment]
> 把dns里的listen注释掉试试

按照您说的，问题解决了。多谢。

**Comment by YiRan0** [comment]
解决了，感谢

**Comment by SuKiWSN** [comment]
> 把dns里的listen注释掉试试

大佬,我在订阅配置文件里没看到dns 和listen
