### ISSUE TITLE
Foxmail无法收发gmail邮件

### ISSUE THREAD

**Issue by trakoo** [Fndroid/clash_for_windows_pkg#732]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**

之前一直是用SSR的方式科学上网，Foxmail收发gmail也一直正常。这几天换用Clash，发现Clash真的强大，速度比SSR快，更重要的是可以设置规则让不同的网站(应用)走不同的节点，这完全就是PC版的Quantumult X的感觉。

本想彻底弃用SSR，但是发现Clash有一个问题，就是Foxmail无法收发gmail邮件，用SSR则一切如常，目前只能交替着用ShadowsocksR跟Clash，收邮件时开ShadowsocksR，其他时候开Clash.

Foxmail收发邮件时的错误提示是这个"ssl connect error, errorCode: 5"，google搜到的结果是叫foxmail设置那里取消SSL勾选，163这样不需要SSL的邮箱是可以正常收发，但是gmail用客户端收发邮件是需要SSL的，取消SSL勾选就连不上的。 

我不知道这是Clash的问题，还是vmess协议的问题，因为不单Clash有这个问题，貌似v2Ray也有这个问题--用foxmail无法收发gmail([https://github.com/233boy/v2ray/issues/379]).

**Comment by Fndroid** [comment]
进Foxmail里设置代理，选择系统代理

**Comment by trakoo** [comment]
> 进Foxmail里设置代理，选择系统代理

谢谢这么快回复！ 已经试过多次，不行喔。

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/80350305-187b4500-88a3-11ea-98f0-f4d488c98177.png)

![image](https://user-images.githubusercontent.com/16091562/80350366-3183f600-88a3-11ea-8b97-0e179d0a51c3.png)

![image](https://user-images.githubusercontent.com/16091562/80350433-4bbdd400-88a3-11ea-97d0-1a330e3c7ff4.png)

**Comment by trakoo** [comment]
谢谢！

![Foxmail_setting](https://user-images.githubusercontent.com/62501559/80356915-bd4e5000-88ac-11ea-9321-60e0c8c0d04c.png)
两种代理方式都试过多次，都是如下图这样的错误:
![foxmail_error](https://user-images.githubusercontent.com/62501559/80356921-bde6e680-88ac-11ea-95fd-19f8d33708a0.png)

请问你是用vmess节点吗？ 如果不是，我怀疑是vmess协议的问题，我刚才用v2ray也折腾过，也是不行.

![vmess](https://user-images.githubusercontent.com/62501559/80356908-bc1d2300-88ac-11ea-9bd3-2cc4bd9abb75.png)

**Comment by trakoo** [comment]
终于搞清楚了，跟Clash没有关系，果真是vmess背的锅，我随便去网上找了两个SS节点，用这两个SS节点foxmail收发没任何问题，用vmess节点则不行！ 

![OKle](https://user-images.githubusercontent.com/62501559/80360268-a9f1b380-88b1-11ea-865f-b00f714d5399.png)

**Comment by trakoo** [comment]
再更新一下，我冤枉vmess了，跟vmess协议无关，是该由我之前用的机场背的锅！ 我今天换了个机场，SS跟vmess, foxmail都能正常收发gmail.
