### ISSUE TITLE
无法正常连上代理

### ISSUE THREAD

**Issue by zyq759316417** [Fndroid/clash_for_windows_pkg#734]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [ ] 软件下载后未修改任何安装目录中的文件 (将软件内核换成了clashr)

**描述**
在rule模式下无法连接上谷歌等墙外网址，全局模式一切正常

**截图**
![image](https://user-images.githubusercontent.com/32996436/80392520-dcb3a000-88e1-11ea-8d74-0f8e91635500.png)

**其他说明**
log中显示warning：
time="2020-04-27T23:42:54+08:00" level=warning msg="dial 🎯 全球直连 error: dial tcp4 127.0.0.1:443: connectex: No connection could be made because the target machine actively refused it."

**Comment by Fndroid** [comment]
换了文件就别问我了，我不会
