### ISSUE TITLE
支持端口 override?

### ISSUE THREAD

**Issue by DeXtmL** [Fndroid/clash_for_windows_pkg#735]
**描述**
为了和其它一些服务保持兼容，需要更改clash的listen port ，并且不开system proxy。
但是，鉴于墙的周期性升级，不少机场的订阅每天都需要更新，每次更新都会全部覆盖。如此，编辑配置文件中的端口变得不现实（或者说，编辑任何配置都变得不现实）。
如果同时有多个订阅，事情就更麻烦。
因此最好有一种手动全局端口重载的手段

**其他说明**
无

**Comment by Fndroid** [comment]
http port和socks port并不随配置更新而改变
