### ISSUE TITLE
更新 TAP 驱动

### ISSUE THREAD

**Issue by Love4Taylor** [Fndroid/clash_for_windows_pkg#737]
**描述**
更新 TAP 驱动至 9.23.3.601

**其他说明**
我通过手动替换 cfw 目录里的资源文件以实现驱动的更新。目前使用了两周左右，无任何问题。

**Comment by thank243** [comment]
tap的IP地址能换下吗?我家是10.0.0.0/24的内网，好像和我家路由器冲突了，导致没法用tap

**Comment by Love4Taylor** [comment]
@Fndroid 说起来一直想吐槽用到的 go-tun2socks 在老旧低压 U（i5-4200u）的性能太差了，走 DIRECT 都只有 70Mbps 左右 。而同类 WireGuard 以及 Anyconnect 都能跑满。

**Comment by Fndroid** [comment]
0.9.10已经使用最新驱动。性能问题只能等有人做wireguard to socks才能解决
