### ISSUE TITLE
通过UI编辑规则与策略组的页面显示空白

### ISSUE THREAD

**Issue by Mon5ter777** [Fndroid/clash_for_windows_pkg#738]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**

通过UI编辑规则与策略组的页面显示空白，但是文本编辑器中写了规则且能正常使用。

**复现**
请描述复现问题的步骤:
1. 进入'Profiles'
2. 点击'Edit Polices'
3. 触发问题 页面空白

**预期行为**

希望通过UI编辑规则和策略组的页面正常显示。

**截图**
![QQ图片20200428155258](https://user-images.githubusercontent.com/62795820/80462086-cef52d80-8968-11ea-8194-5ab5baec2471.png)
![QQ图片20200428155305](https://user-images.githubusercontent.com/62795820/80462090-d0265a80-8968-11ea-85ef-b30b51ae0d8d.png)
![image](https://user-images.githubusercontent.com/62795820/80462208-f4823700-8968-11ea-8657-419b7b47f7e2.png)
**其他说明**
无

**Comment by smcdl** [comment]
我也有同样的问题，已确认0.9.6没问题，之后的版本有这个问题

**Comment by Fndroid** [comment]
Duplicate of https://github.com/Fndroid/clash_for_windows_pkg/issues/694
