### ISSUE TITLE
添加自定义rule后，google无法访问

### ISSUE THREAD

**Issue by jasonxu610** [Fndroid/clash_for_windows_pkg#739]
添加自定义rule后，rule内的地址可以正常访问，但是google访问不了；
删除该rule后，google可以正常访问，rule的地址访问不了；

![image](https://user-images.githubusercontent.com/50004522/80477459-88123280-897e-11ea-888b-96e2ddc6ff03.png)

**Comment by Fndroid** [comment]
Duplicate of #694

**Comment by jasonxu610** [comment]
收到，谢谢大佬
