### ISSUE TITLE
有没有办法让桌面软件自动判断是否走代理

### ISSUE THREAD

**Issue by iwsbiwy** [Fndroid/clash_for_windows_pkg#74]
比如下载软件，像浏览器那样，如果下载被墙的网站走代理，下载国内的直连。
软件设置127.0.0.1好像是所有的都走代理。
有没有方法能实现？

**Comment by Fndroid** [comment]
Clash依赖规则（域名，IP，关键字等）判断是否代理

**Comment by iwsbiwy** [comment]
> Clash依赖规则（域名，IP，关键字等）判断是否代理

意思就是只要设置正确，clash是可以实现我说的功能的吗？

**Comment by Fndroid** [comment]
是

**Comment by iwsbiwy** [comment]
> 是

多谢，我研究研究。
