### ISSUE TITLE
关于默认使用密码调用clash 内核

### ISSUE THREAD

**Issue by YH0426** [Fndroid/clash_for_windows_pkg#741]
**描述**
最近在研究Clash 的RESTful API ，发现Clash for windows 并未使用 
```
secret: ''
``` 
字段控制Clash 内核
自己写了一个小程序通过127.0.0.1:9090轻松读取并修改了Clash for windows当前使用的配置组
**可能的控制方法**
1.伪装成Clash相关程序通过Telegram 传播给小白用户
2.伪装成订阅转换网页使用XHR、fetch 控制Clash
**可能的造成危害**
1.某人写了读取Clash 节点配置信息并上传置其服务器的程序并通过telegram 传播给小白用户
2.某人配置了一台代理服务器，并修改他人Clash 配置，使其输入正常网址后恶意解析跳转至钓鱼域名所链接的服务器

**功能建议**
在Clash for windows 上添加secret 参数，在用户初次客户端设置或随机生成secret 参数。

**Comment by Fndroid** [comment]
Clash for Windows是会读取secret字段的，只是Clash目前版本secret有个小bug，导致验证默认会被通过，现在已经修复，新版会正常

**Comment by YH0426** [comment]
Clash for windows安装包打包了clash内核，是否考虑在安装时随机生成一个secret并填入配置文件,以保证不被其他软件随意调用。

**Comment by Fndroid** [comment]
> Clash for windows安装包打包了clash内核，是否考虑在安装时随机生成一个secret并填入配置文件,以保证不被其他软件随意调用。

目前不考虑。如果需要的话，手动在General YAML中指定即可。
