### ISSUE TITLE
下载profiles失败，弹出Error错误

### ISSUE THREAD

**Issue by 754971664** [Fndroid/clash_for_windows_pkg#742]
不管是0.9.4还是0.9.8都这样，换其他家的订阅地址也这样

Download profile failed with error: Cannot read property 'findIndex' of undefined .

![QQ截图20200429133718](https://user-images.githubusercontent.com/29936701/80563786-a3347f00-8a1e-11ea-8b4c-0c1b57d926df.png)

**Comment by Fndroid** [comment]
Home Directory里把profiles文件夹删掉重启软件
