### ISSUE TITLE
proxies 里的rule下面是空白的没有配置

### ISSUE THREAD

**Issue by Crazjo** [Fndroid/clash_for_windows_pkg#743]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载
- [x ] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题

proxies 里的rule下面是空白的没有配置
从机场里导入配置 会提示不支持SSR 是什么情况

**复现**
请描述复现问题的步骤:
1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
清晰地描述期望看到的行为

**截图**
如果可以，请提供对应问题的截图
![TIM截图20200429224123](https://user-images.githubusercontent.com/64541632/80609553-cf75ed00-8a6a-11ea-9c0c-22d814ace0aa.png)
![TIM截图20200429224412](https://user-images.githubusercontent.com/64541632/80609687-fc2a0480-8a6a-11ea-87f6-7b8a1facfc47.png)
![TIM截图20200429224418](https://user-images.githubusercontent.com/64541632/80609695-fe8c5e80-8a6a-11ea-97d5-6351caa0ffc9.png)

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
配置文件有问题就找给你配置文件的人，不是什么问题都定性到软件
