### ISSUE TITLE
Connections-ConnectionInfo-ProxyChains会来回倒置

### ISSUE THREAD

**Issue by Emphasia** [Fndroid/clash_for_windows_pkg#746]
**信息**
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
``Connections``中点击展开``Connection Info``会使``endpoint proxy``在 proxies(出口/终点) 和 proxy-groups(入口/起点) 之间来回切换（proxychains倒置）
也就是点开奇数次会显示错误 偶数次就正常

**复现**
1. 进入``Connections``
2. 点击``条目``
3. 触发问题

**截图**
![点开一次后](https://user-images.githubusercontent.com/8478234/80679579-b5322280-8aef-11ea-88f4-9192b1a99984.png)
![出现错误再点开](https://user-images.githubusercontent.com/8478234/80679583-b6634f80-8aef-11ea-8496-dad83fbfbe00.png)
![再点开](https://user-images.githubusercontent.com/8478234/80679585-b6fbe600-8aef-11ea-91f6-4fd4ae657cf3.png)

**Comment by Fndroid** [comment]
感谢反馈，下个版本修复

**Comment by Fndroid** [comment]
已修复
