### ISSUE TITLE
不插网线的情况下，只使用无线网络无法使用tap模式

### ISSUE THREAD

**Issue by thank243** [Fndroid/clash_for_windows_pkg#747]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
笔记本无线网络下无法使用tap模式。

**复现**
请描述复现问题的步骤:
个人profile已经按教程设置了dns和interface，如下

> dns:
>    enable: true
>    enhanced-mode: fake-ip # 或 redir-host
>    listen: 0.0.0.0:53
>    nameserver:
>       - 223.5.5.5
> experimental:
>   interface-name: WLAN # WLAN 为物理网卡名

**预期行为**
cfw-tap显示未插网线，导致无法使用tap模式。

**截图**
如果可以，请提供对应问题的截图
![无标题2](https://user-images.githubusercontent.com/11692994/80684603-7e143f00-8af8-11ea-9b1d-b3a6f3c75437.png)
![无标题](https://user-images.githubusercontent.com/11692994/80684609-810f2f80-8af8-11ea-9c94-060ad633a6a2.png)
**其他说明**
其他补充内容

**Comment by moonaileen** [comment]
啊……我也是用无线的，更新后发现无法使用TAP模式……
不过我把TAP卸载后想重装却装不上了T__T

**Comment by Fndroid** [comment]
@thank243 listen不能写127.0.0.1，文档里也写了要0.0.0.0

**Comment by thank243** [comment]
> @thank243 listen不能写127.0.0.1，文档里也写了要0.0.0.0

> dns:
>    enable: true
>    enhanced-mode: fake-ip # 或 redir-host
>    listen: 0.0.0.0:53
>    nameserver:
>       - 223.5.5.5
> experimental:
>   interface-name: WLAN # WLAN 为物理网卡名
尝试过，也不行。cfw-tap就从未显示已启用状态。一直说未插网线。

**Comment by blucartfhg** [comment]
> > @thank243 listen不能写127.0.0.1，文档里也写了要0.0.0.0
> 
> > dns:
> > enable: true
> > enhanced-mode: fake-ip # 或 redir-host
> > listen: 0.0.0.0:53
> > nameserver:
> > - 223.5.5.5
> > experimental:
> > interface-name: WLAN # WLAN 为物理网卡名
> > 尝试过，也不行。cfw-tap就从未显示已启用状态。一直说未插网线。

同样的问题

**Comment by thank243** [comment]
![image](https://user-images.githubusercontent.com/11692994/80697050-f71c9200-8b0a-11ea-9780-039bd1af68d5.png)
你看嘛。

**Comment by blucartfhg** [comment]
![image](https://user-images.githubusercontent.com/48641773/80697654-dd2f7f00-8b0b-11ea-955d-2ac81f7f1fb9.png)


> > > @thank243 listen不能写127.0.0.1，文档里也写了要0.0.0.0
> > 
> > 
> > > dns:
> > > enable: true
> > > enhanced-mode: fake-ip # 或 redir-host
> > > listen: 0.0.0.0:53
> > > nameserver:
> > > 
> > > * 223.5.5.5
> > >   experimental:
> > >   interface-name: WLAN # WLAN 为物理网卡名
> > >   尝试过，也不行。cfw-tap就从未显示已启用状态。一直说未插网线。
> 
> 同样的问题

**Comment by Fndroid** [comment]
把interface-name注释掉试试

**Comment by blucartfhg** [comment]
> 把interface-name注释掉试试

![image](https://user-images.githubusercontent.com/48641773/80697886-3dbebc00-8b0c-11ea-876d-b336d0c8d76b.png)

**Comment by Fndroid** [comment]
experimental也注释掉...

**Comment by blucartfhg** [comment]
> experimental也注释掉...

可以了。谢谢您

**Comment by thank243** [comment]
> experimental也注释掉...

删掉interface后正常使用，谢谢老大。
