### ISSUE TITLE
大部分节点timeout且速度特别慢

### ISSUE THREAD

**Issue by XiaoyuZeng** [Fndroid/clash_for_windows_pkg#748]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
大部分节点timeout且速度特别慢

**复现**
test latency后，大部分节点timeout，每次都只有少数几个节点可以尝试连接。连接后，速度很慢。

**预期行为**
清晰地描述期望看到的行为

**截图**

**其他说明**
与下列两个issue问题类似。
https://github.com/Fndroid/clash_for_windows_pkg/issues/600
https://github.com/Fndroid/clash_for_windows_pkg/issues/602

根据https://github.com/Fndroid/clash_for_windows_pkg/issues/602
建议更换了Clash Core，问题依然存在。

**Comment by Fndroid** [comment]
节点问题排除了吗？配置文件没问题吗？

**Comment by Glacier-Luo** [comment]
我遇到了类似的问题（v0.9.9），但是所有的节点都无法连接，确定不是节点以及配置的问题，重启程序就可以。
![failed](https://user-images.githubusercontent.com/30594509/80866198-0729a280-8cc0-11ea-9af8-ca54c858dfe6.jpg)
暂退回到v0.9.5。

**Comment by Qm520** [comment]
同更新最新版本后所有节点time out 并且在此情况下试了每一个节点,都无法连接

**Comment by appactrsss** [comment]
尝试下更改系统时间，（我使用的某个机场）系统时间与实际时间超过2分钟，所有的节点均 timeout

**Comment by lvanlaw** [comment]
遇到同样问题，更新到最新版本0.9.8后出现此问题，回退到0.9.6后消失

**Comment by cikichen** [comment]
同样的问题，0.9.9的问题特别严重，关键是会出现直连也失败的问题
![image](https://user-images.githubusercontent.com/1478821/81461057-db388080-91db-11ea-886d-9b867a156cf9.png)

**Comment by Fndroid** [comment]
把配置文件里的dns注释掉，出这问题多数是因为安装了TAP网卡，配置了dns导致错误启动了TAP模式
