### ISSUE TITLE
0.5.25 版本规则代理不起作用，退回0.5.21没问题

### ISSUE THREAD

**Issue by LE88I5** [Fndroid/clash_for_windows_pkg#75]
0.5.25 版本规则代理不起作用，全局模式的时候有用，捕捉tab页看不到任何记录，退回0.5.21没问题

**Comment by 760777012** [comment]
原来不只是我，我还以为电脑出问题了

**Comment by Fndroid** [comment]
检查config.yml里面是否有dns字段，有的话先关闭

**Comment by LE88I5** [comment]
> 检查config.yml里面是否有dns字段，有的话先关闭

试了下，关闭可行。

**Comment by LE88I5** [comment]
关闭 config.yml 中的 dns 功能后，的确解决了代理不起作用问题，使用了约 3 小时时间。 不稳定，问题好像还是和 dns 有关？网站时不时找不到，怎么刷都没用，换个服务器（和服务供应商稳定性无关）又可以，切换为 0.5.21 版本没有这个问题。

**Comment by Fndroid** [comment]
> 关闭 config.yml 中的 dns 功能后，的确解决了代理不起作用问题，使用了约 3 小时时间。 不稳定，问题好像还是和 dns 有关？网站时不时找不到，怎么刷都没用，换个服务器（和服务供应商稳定性无关）又可以，切换为 0.5.21 版本没有这个问题。

托管的配置文件看看是不是也有dns的设置

**Comment by LE88I5** [comment]
> > 关闭 config.yml 中的 dns 功能后，的确解决了代理不起作用问题，使用了约 3 小时时间。 不稳定，问题好像还是和 dns 有关？网站时不时找不到，怎么刷都没用，换个服务器（和服务供应商稳定性无关）又可以，切换为 0.5.21 版本没有这个问题。
> 
> 托管的配置文件看看是不是也有dns的设置

是的，托管配置中包含
```
dns:
  enable: true
```
0.5.25 版本我是按照你的提示，将当前配置作为副本，点击该副本，并进行编辑，将 enable 设置为 false，重启软件。
访问一些网站，没问题，比较正常。但用上一阵子就挂了，Chrome 页签上的那个圈圈倒转，最后无法显示页面，这个时在 profile tab 中换一个节点，刷几下页签又能出来 （就是有点不稳定的样子）。
然后我尝试安装2个不同版本，用  beyond compare 进行比较  .config 文件夹下的内容，似乎也没发现什么不对的地方。

另外还点小细节，我来回安装了好几次这两个版本，后面发现 0.5.21 这个版本时不时变成紫色的小托盘图标（之前好像没有这个现象），于是我把软件卸载后，把 .config 文件也删除了，重新安装 0.5.21，并订阅配置，目前安好，图标也是橘黄色的。

**Comment by Fndroid** [comment]
变成紫色说明clash核心遇到错误了，把log打包一下发我？

**Comment by LE88I5** [comment]
> 变成紫色说明clash核心遇到错误了，把log打包一下发我？

log 已经被我删除了额（包括 .config) 文件夹……因为退回到了 0.5.2.1，现在不会出现紫色的图标了，要不这个 issue 先关闭了，等我倒腾的时候，再次遇到（有日志）我再打开它。
