### ISSUE TITLE
更新到最新版本之后，选中某个proxy会跳跃到另外一个

### ISSUE THREAD

**Issue by JunlinLai** [Fndroid/clash_for_windows_pkg#750]
**信息**
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
更新到最新版0.99之后，在Global或者Rule模式中选中某个proxy后会跳跃到另外一个。

【更新】看了下面大家的回复之后，我发现确实是延迟的问题，只是延迟时间有点长，可达数秒之久。

**复现**
请描述复现问题的步骤:
1. 进入'Global'或者‘Rule’模式
2. 点击'随便一个proxy'
4. 触发问题

**Comment by Emphasia** [comment]
好像是有切换的延迟而已 多等几秒试试

**Comment by AzunyanDaisuki** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/18110400/80717354-6c985a80-8b2b-11ea-93c7-ad476325ada0.gif)
我也遇到了同样的问题，看起来并不像是延迟，因为点击目标代理组后，稍等1-2秒，会跳回之前选中的代理组，此时需要再次点击目标代理组，才能切换过来

**Comment by GrayXu** [comment]
我这里的现象是，原来是A，点击切换到B后。B被高亮，A又跳到高亮，B又跳回高亮。类似上面说的延迟。

**Comment by Fndroid** [comment]
来自上游（core）的bug

**Comment by lydasia** [comment]
解决了吗。。我怎么都感觉是ui的问题啊，鼠标滑过才会乱跳，如果切换完节点鼠标不动，或者绕过按钮移到别的地方，就没问题。

**Comment by Fndroid** [comment]
使用最新版
