### ISSUE TITLE
关于TAP状态的系统托盘图标的优化

### ISSUE THREAD

**Issue by Sanly** [Fndroid/clash_for_windows_pkg#751]
**描述**
在TAP模式下是无需将CFW设置为系统代理的，但不选择系统代理，系统托盘图标与非TAP模式没有区别，不知能否在TAP模式下换一种图标颜色，使得“普通非系统代理状态”、“系统代理状态”、“TAP模式”能够区分，避免出现使用“TAP模式”+“系统代理状态”（此模式下UWP应用非回环无法使用，还不如不用“TAP模式”）

**其他说明**
强迫症需求，做不做不影响使用。

**Comment by ShadowLyin** [comment]
@Fndroid 您好，请问下这个需求有考虑实现吗？

**Comment by yi-Xu-0100** [comment]
@ShadowLyin  TAP 或者 TUN 模式下的 UWP 回环问题应该可通过 UWP lookback 解决。而且个人在使用 TAP 或者 TUN 的同时会同时开启系统代理，这样，会优先走系统代理，不行的走 TAP 或者 TUN ，增加容错率。

**Comment by ShadowLyin** [comment]
> @ShadowLyin TAP 或者 TUN 模式下的 UWP 回环问题应该可通过 UWP lookback 解决。而且个人在使用 TAP 或者 TUN 的同时会同时开启系统代理，这样，会优先走系统代理，不行的走 TAP 或者 TUN ，增加容错率。

使用 TUN 之后就没必要再开系统代理了
