### ISSUE TITLE
Edit Policies and Edit Rules are broken since V0.9.7~0.9.9

### ISSUE THREAD

**Issue by myfingerhurt** [Fndroid/clash_for_windows_pkg#752]
**信息**
- [X] 已经尝试更新到最新版本，问题依旧存在
- [X] 软件从本仓库下载
- [X] 软件下载后未修改任何安装目录中的文件

click Edit Polices or Edit Rules
![image](https://user-images.githubusercontent.com/12622279/80748173-79cf3c80-8b5f-11ea-9c38-c71963b5a6a9.png)

**V0.9.7** **V0.9.8** **V0.9.9**
When click Edit Polices or Edit Rules there are empty.
![image](https://user-images.githubusercontent.com/12622279/80747826-f877aa00-8b5e-11ea-9e67-89103d165861.png)

![image](https://user-images.githubusercontent.com/12622279/80748299-aaaf7180-8b5f-11ea-8c45-26537cdbb34c.png)

-------------------------------
**V0.9.6**
When click Edit Polices or Edit Rules works as expected.
![image](https://user-images.githubusercontent.com/12622279/80747680-c49c8480-8b5e-11ea-8720-c9999508d63f.png)

![image](https://user-images.githubusercontent.com/12622279/80748114-62904f00-8b5f-11ea-9bea-52f570d2f0bd.png)

**Comment by Fndroid** [comment]
Duplicate of https://github.com/Fndroid/clash_for_windows_pkg/issues/694
