### ISSUE TITLE
win10系统，退出clash之前直接重启计算机，则重启后网页无法打开任何网站

### ISSUE THREAD

**Issue by TaylorLeon** [Fndroid/clash_for_windows_pkg#753]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [X ] 已经尝试更新到最新版本，问题依旧存在
- [ X] 软件从本仓库下载
- [X ] 软件下载后未修改任何安装目录中的文件

**描述**
win10系统，退出clash之前直接重启计算机，则重启后浏览器无法打开任何网站. 
但是重启完成后打开clash后又恢复正常。

**Comment by HOOOOOH** [comment]
貌似是因为关机时，Clash设置的系统代理还是保留了，没有重置。所以重启后流量还是走clash的代理，而clash并未运行，所以无法上网。

**Comment by tea1111980** [comment]
好像听作者讲过，这是Windows系统的问题，是因为在关机时，不允许做其它操作了，所以代理设置 在系统中无法被释放，最后就导致了你这个问题。

**Comment by soniczxzero0** [comment]
1.右键任务栏右下网络图标
2.点击“打开网络和Internet设置”
3.点击“代理”
4.“使用代理服务器”设置为“关”

**Comment by Fndroid** [comment]
> 好像听作者讲过，这是Windows系统的问题，是因为在关机时，不允许做其它操作了，
> 除非是用户主动操作关闭相关的软件，才能正确的释放代理在系统中的设置，否则代理设置 在系统中无法被释放，最后就导致了你这个问题。

这是正解。

**Comment by EzraRT** [comment]
虽然已经close了有些抱歉，但似乎有在关机时关闭系统proxy的方法，希望可以添加这个功能，原理见https://github.com/2dust/v2rayN/issues/1549
