### ISSUE TITLE
0.99版本偶发性断开连接

### ISSUE THREAD

**Issue by Mickyzh** [Fndroid/clash_for_windows_pkg#754]
**信息**
如果符合，请将``[ ]``改为``[x]``
-[x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
使用0.99版本在下载过程中出现clash左下角连接状态变为disconnected，同时日志中出现以下错误信息
goroutine 822155 [running]:
bytes.(*Buffer).ReadFrom(0xc003844cd8, 0x9d2260, 0xc001945e80, 0x40a59c, 0x89eba0, 0x908ee0)
	/opt/hostedtoolcache/go/1.14.2/x64/src/bytes/buffer.go:209 +0x1b6
crypto/tls.(*Conn).readFromUntil(0xc003844a80, 0x28006040, 0xc000e02300, 0x816, 0xc000e02300, 0x0)
	/opt/hostedtoolcache/go/1.14.2/x64/src/crypto/tls/conn.go:782 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc003844a80, 0x0, 0x0, 0x4c9d2a)
	/opt/hostedtoolcache/go/1.14.2/x64/src/crypto/tls/conn.go:634 +0x57a
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.14.2/x64/src/crypto/tls/conn.go:557
crypto/tls.(*Conn).Read(0xc003844a80, 0xc0045e27d0, 0x2, 0x2, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.2/x64/src/crypto/tls/conn.go:1233 +0x162
io.ReadAtLeast(0x169b3e0, 0xc003844a80, 0xc0045e27d0, 0x2, 0x2, 0x2, 0xc002539d30, 0x4c7704, 0xc0000d7900)
	/opt/hostedtoolcache/go/1.14.2/x64/src/io/io.go:310 +0x8e
io.ReadFull(...)
	/opt/hostedtoolcache/go/1.14.2/x64/src/io/io.go:329
github.com/brobird/clash/component/vmess.(*aeadReader).Read(0xc002785d60, 0xc002078000, 0x8000, 0x8000, 0x0, 0x0, 0xc000056418)
	/home/runner/work/clash/clash/component/vmess/aead.go:82 +0x1c5
github.com/brobird/clash/component/vmess.(*Conn).Read(0xc002f87290, 0xc002078000, 0x8000, 0x8000, 0x8000, 0x7ee, 0x0)
	/home/runner/work/clash/clash/component/vmess/conn.go:47 +0x103
github.com/brobird/clash/tunnel.(*tcpTracker).Read(0xc001451b60, 0xc002078000, 0x8000, 0x8000, 0x7ee, 0x0, 0x0)
	/home/runner/work/clash/clash/tunnel/tracker.go:37 +0x5f
io.copyBuffer(0x27d84fc8, 0xc00168df40, 0x27d84fe8, 0xc001451b60, 0xc002078000, 0x8000, 0x8000, 0x8f0d60, 0xc0032b7300, 0x27d84fe8)
	/opt/hostedtoolcache/go/1.14.2/x64/src/io/io.go:405 +0x129
io.CopyBuffer(0x27d84fc8, 0xc00168df40, 0x27d84fe8, 0xc001451b60, 0xc002078000, 0x8000, 0x8000, 0x1000000000001, 0xc0032a5740, 0x0)
	/opt/hostedtoolcache/go/1.14.2/x64/src/io/io.go:378 +0x89
github.com/brobird/clash/tunnel.relay.func1(0x9de440, 0xc00168df40, 0x169b458, 0xc001451b60, 0xc0003768a0)
	/home/runner/work/clash/clash/tunnel/connection.go:124 +0x134
created by github.com/brobird/clash/tunnel.relay
	/home/runner/work/clash/clash/tunnel/connection.go:122 +0xaa

**复现**
请描述复现问题的步骤:
1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
清晰地描述期望看到的行为

**截图**
如果可以，请提供对应问题的截图

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
> 软件下载后未修改任何安装目录中的文件

你是怎么好意思把这个勾上的？
