### ISSUE TITLE
UI 小瑕疵

### ISSUE THREAD

**Issue by NekoInverter** [Fndroid/clash_for_windows_pkg#755]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
![image](https://user-images.githubusercontent.com/42698724/80910424-eca80580-8d61-11ea-948b-c52f361ea9ff.png)
![image](https://user-images.githubusercontent.com/42698724/80910411-db5ef900-8d61-11ea-9a28-bf34173ba038.png)
没有对齐（

**Comment by Fndroid** [comment]
由于可以更换字体，所以这个地方不同人可能会不同
