### ISSUE TITLE
无法正常从命令行启动并运行，命令行输出错误提示

### ISSUE THREAD

**Issue by byzod** [Fndroid/clash_for_windows_pkg#756]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
无法从命令行（cmd）启动

**复现**
请描述复现问题的步骤:
1. 编写`.bat`文件，内容如下：
```Batchfile
@echo off
start "app" "Clash for Windows.exe"
```
2. 放置于cfw安装目录，并双击该bat文件
3. 触发问题

**预期行为**
cfw启动，命令行（cmd）自动关闭

**实际行为**
cfw启动，命令行提示错误，不会自动关闭。手动关闭命令行后，cfw也跟着关闭，无法正常运行

**截图**
![A_1](https://user-images.githubusercontent.com/848607/80932738-689e5e00-8df3-11ea-9e2a-524c2694f4d7.gif)

**其他说明**
OS: win10 1703

**Comment by Fndroid** [comment]
试试：`` explorer clash://``

**Comment by byzod** [comment]
> 
> 
> 试试：` explorer clash://`

有效，谢谢！

**Comment by haobaod** [comment]
##信息
如果符合，请将[ ]改为[x]

[]已经尝试更新到最新版本，问题依旧存在
[]软件从本仓库下载
[]软件下载后未修改任何安装目录中的文件
##描述
cmd taskkill 命令关闭clash导致网络断开

##复现
请描述复现问题的步骤:

cmd输入
TASKKILL /F /IM ”Clash for Windows.exe“ /T
网络断开连接

预期行为
clash进程关闭，网络连接正常

实际行为
网络断开连接

其他说明
OS: win10
