### ISSUE TITLE
win7下无法运行

### ISSUE THREAD

**Issue by Aaron-Y-Wong** [Fndroid/clash_for_windows_pkg#757]
**信息**
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
在Windows7 64位版本系统上点击运行clash客户端无反应

**Comment by FANminiworld** [comment]
是否有日志？
如果有就贴出来
