### ISSUE TITLE
0.9.9版本在ltsc2019下运行频繁出现连不上clash内核的情况

### ISSUE THREAD

**Issue by goodffd** [Fndroid/clash_for_windows_pkg#758]
![photo_2020-05-04_23-11-03](https://user-images.githubusercontent.com/62946026/80981680-e185d000-8e5c-11ea-931f-41e036669f2b.jpg)

**Comment by Fndroid** [comment]
日志呢

**Comment by goodffd** [comment]
日志跟could not connect to clash core #759 这个一样的。

**Comment by nailongzhenren** [comment]
同ltsc2019，没有这个问题，CFW使用正常

**Comment by ensonlu** [comment]
我也有这个问题，时不时的出现。有时候重启就好。我是 win10 2004
日志1：
time="2020-05-07T11:35:02+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-05-07T11:35:02+08:00" level=info msg="RESTful API listening at: 127.0.0.1:51987"
time="2020-05-07T11:35:02+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:11987"
time="2020-05-07T11:35:02+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:21987"
time="2020-05-07T11:35:02+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2020-05-07T11:35:02+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:31987"
time="2020-05-07T11:35:02+08:00" level=info msg="[TCP] 127.0.0.1:9697 --> cn.bing.com match Match using DIRECT"
time="2020-05-07T11:35:11+08:00" level=warning msg="dial DIRECT error: dial tcp4 64.233.189.188:443: i/o timeout"
日志2：
time="2020-05-07T11:32:08+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-05-07T11:32:08+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-05-07T11:32:08+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-05-07T11:32:08+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-05-07T11:32:08+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-05-07T11:32:08+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"

**Comment by Fndroid** [comment]
这两个日志看着都没问题，哪里下载的软件？

**Comment by ensonlu** [comment]
> 这两个日志看着都没问题，哪里下载的软件？

就是这里下载的.
最近倒是很少发生了，可能是我本地有冲突还是啥的导致clash-win64关闭了。

**Comment by goodffd** [comment]
到了0.9.11问题依然如此。不知道是什么原因了。而且出现上述故障的时候，clash-win64进程依然在后台

**Comment by TheStar4Fate** [comment]
同样的问题
日志
time="2020-05-27T23:00:20+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-05-27T23:00:20+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-05-27T23:00:20+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-05-27T23:00:20+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-05-27T23:00:20+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-05-27T23:00:20+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2020-05-27T23:00:20+08:00" level=error msg="External controller error: listen tcp 127.0.0.1:9090: bind: An attempt was made to access a socket in a way forbidden by its access permissions."

**Comment by Fndroid** [comment]
> 同样的问题
> 
> 日志
> 
> time="2020-05-27T23:00:20+08:00" level=info msg="Start initial compatible provider Proxy"
> 
> time="2020-05-27T23:00:20+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
> 
> time="2020-05-27T23:00:20+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
> 
> time="2020-05-27T23:00:20+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
> 
> time="2020-05-27T23:00:20+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
> 
> time="2020-05-27T23:00:20+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
> 
> time="2020-05-27T23:00:20+08:00" level=error msg="External controller error: listen tcp 127.0.0.1:9090: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
> 
> 

你这个就单纯的是端口问题

**Comment by WongRuoran** [comment]
> > 同样的问题
> > 日志
> > time="2020-05-27T23:00:20+08:00" level=info msg="Start initial compatible provider Proxy"
> > time="2020-05-27T23:00:20+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
> > time="2020-05-27T23:00:20+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
> > time="2020-05-27T23:00:20+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
> > time="2020-05-27T23:00:20+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
> > time="2020-05-27T23:00:20+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
> > time="2020-05-27T23:00:20+08:00" level=error msg="External controller error: listen tcp 127.0.0.1:9090: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
> 
> 你这个就单纯的是端口问题

~~~
time="2020-05-28T08:09:25+08:00" level=info msg="RESTful API listening at: 127.0.0.1:7892"
time="2020-05-28T08:09:25+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-05-28T08:09:25+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-05-28T08:09:25+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-05-28T08:09:25+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2020-05-28T08:09:25+08:00" level=error msg="External controller error: listen tcp 127.0.0.1:7892: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
~~~
这个也是端口占用吗？还是说设置有问题，要改一个7892？
