### ISSUE TITLE
could not connect to clash core

### ISSUE THREAD

**Issue by Celinezqy** [Fndroid/clash_for_windows_pkg#759]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
general界面显示could not connect to clash core，重启、更新到最新版和try to repair都未解决问题。log文件显示warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform”

**复现**
请描述复现问题的步骤:
1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
清晰地描述期望看到的行为

**截图**
如果可以，请提供对应问题的截图
<img width="650" alt="general页面" src="https://user-images.githubusercontent.com/64822427/81032616-1298eb80-8ec3-11ea-9b61-2b64cf1d1856.png">
<img width="683" alt="日志1" src="https://user-images.githubusercontent.com/64822427/81032619-14fb4580-8ec3-11ea-925a-ecf61d8de274.png">
<img width="679" alt="日志2" src="https://user-images.githubusercontent.com/64822427/81032621-1593dc00-8ec3-11ea-927a-4d3ec205961a.png">

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
1. 检查任务管理器里有没有``clash-win64.exe``这个进程
2. 浏览器访问``http://127.0.0.1:9090``看输出什么

**Comment by goodffd** [comment]
我也是同样的问题，高频次出现。而且不要说有没有开启代理了，关闭代理的情况下，就下载个配置文件，选择该配置文件后都可以导致连不上clash core。极其不稳定。

**Comment by Celinezqy** [comment]
> 1. 检查任务管理器里有没有`clash-win64.exe`这个进程
> 2. 浏览器访问`http://127.0.0.1:9090`看输出什么

1.任务管理器有进程
2.网址加载不出来
ps，代理是关闭的
<img width="436" alt="任务管理器" src="https://user-images.githubusercontent.com/64822427/81044854-a8467200-8ee7-11ea-9ca7-358e8bc677e5.png">
<img width="630" alt="试图访问127 0 0 1打不开" src="https://user-images.githubusercontent.com/64822427/81044861-aaa8cc00-8ee7-11ea-8287-acbe1f68ffcf.png">
<img width="345" alt="代理服务器界面" src="https://user-images.githubusercontent.com/64822427/81044879-b0061680-8ee7-11ea-91ab-2231d0f54f47.png">

**Comment by Fndroid** [comment]
不是Clash for Windows这个进程，是 clash-win64.exe 进程有没有

**Comment by Celinezqy** [comment]
> 不是`Clash for Windows`这个进程，是`clash-win64.exe`进程有没有

抱歉看错，有的
<img width="495" alt="任务管理器进程2" src="https://user-images.githubusercontent.com/64822427/81046139-4804ff80-8eea-11ea-9b86-e3143e5f312e.png">

**Comment by Fndroid** [comment]
如果log没发错的话，就只能是系统里某些软件阻止了127.0.0.1这个地址的访问。

如果不能确定可以试试手动编辑config.yaml（logs文件夹上一层）里面`external-controller`，后面的9090端口换一个更大的如34567试试。

不行的话只能是从其他软件入手了

**Comment by Celinezqy** [comment]
log是没错的，十几个log内容都一样。不是很懂这个端口能填啥范围，我就改成34567了...也不好使，那可能是别的软件的问题吧...谢谢解答！
<img width="251" alt="config yaml截图" src="https://user-images.githubusercontent.com/64822427/81046893-e47bd180-8eeb-11ea-92f7-ab50cbc0327d.png">

**Comment by Celinezqy** [comment]
重启电脑后莫名好了...看来真是其他软件的问题（捂脸）
