### ISSUE TITLE
0.9.9异常资源占用

### ISSUE THREAD

**Issue by WileyChia** [Fndroid/clash_for_windows_pkg#762]
常发生于电脑从睡眠唤醒后，CPU利用率一直在二三十的水平，出现好几次了，重启应用后恢复正常

**Comment by WileyChia** [comment]
对了安装了TAP设备

**Comment by Fndroid** [comment]
不用TAP的话，就在设备管理器里卸载掉``TAP-Windows Adapter V9``网卡。
要用TAP的话，先退回上一版本。

**Comment by killsting** [comment]
> 不用TAP的话，就在设备管理器里卸载掉`TAP-Windows Adapter V9`网卡。
> 要用TAP的话，先退回上一版本。

从 0.8.11 后的版本开启 TAP 都会引起 CPU 占用超高。

**Comment by Shadow0703** [comment]
> 不用TAP的话，就在设备管理器里卸载掉`TAP-Windows Adapter V9`网卡。
> 要用TAP的话，先退回上一版本。

卸载了仍然出现CPU占用过高（30%-50%）,电脑待机一段时间不使用出现，点击界面任意按钮或重启软件则会恢复正常。

**Comment by LinEvil** [comment]
复现了问题，且没安装 tap 驱动，也没有打开 tap 选项。

**Comment by mohuishou** [comment]
v0.9.11 复现了这个问题
