### ISSUE TITLE
建议日志改按天存储

### ISSUE THREAD

**Issue by nailongzhenren** [Fndroid/clash_for_windows_pkg#763]
`目前版本的CFW客户端是每次启动后生成日志，时间久了看着有点乱，建议日志改按天存储。
![image](https://user-images.githubusercontent.com/24807096/81136173-64a64380-8f8d-11ea-8470-d0c95f19b545.png)

**Comment by Fndroid** [comment]
感觉意义不大，出了问题更不好排查了
