### ISSUE TITLE
局域网共享白名单

### ISSUE THREAD

**Issue by qzshi97** [Fndroid/clash_for_windows_pkg#764]
能否增加一个局域网共享白名单功能？
目前已有局域网共享功能，也可以看到局域网中哪个ip地址的主机正在使用本机的代理。
希望增加一个过滤器，只允许白名单中ip地址的主机共享代理

**Comment by Fndroid** [comment]
有什么意义吗？加上authentication不好吗

**Comment by qzshi97** [comment]
因为profiles一段时间就要换一个，实验室几个人一起用，就每个人每次都要更新一下，比较麻烦，另外一个就是，大家不在同一个屋子里，学校又是用的内网ip绑定学号用的，就没办法挂到同一个路由器下面。主要是想方便一点，每次只需要更新一台机器的profiles，大家就都能用了，然后还能避免内网中的外人使用。

**Comment by Fndroid** [comment]
不想给其他人用就加上authentication啊

**Comment by qzshi97** [comment]
能说一下怎么加吗？能用什么样方式加上去？没太懂

**Comment by abae136ab** [comment]
> 能说一下怎么加吗？能用什么样方式加上去？没太懂
profile文件里加入
# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"
