### ISSUE TITLE
请问免安装版与安装版有区别吗？

### ISSUE THREAD

**Issue by Nevidebla** [Fndroid/clash_for_windows_pkg#765]
我的免安装版本，一直卡在这样的界面
![image](https://user-images.githubusercontent.com/54260027/81179505-503d6780-8fdc-11ea-9017-2ee2ce73c7ab.png)

**Comment by Fndroid** [comment]
哪里下载的？

**Comment by Nevidebla** [comment]
> 哪里下载的？

就是在这个项目的releases页面里面啊。一个版本是exe文件，另一个是压缩包。
而且我后来又用了exe文件的安装版，也是这样的故障

**Comment by timorpic** [comment]
这个情况我也遇到了 
改了配置文件里面 
- “Proxy” 现在改成“proxies”
- “proxy-group” 改成 “proxy-groups”
- “Rule” 改成 “rules”
就好了

**Comment by Nevidebla** [comment]
> 这个情况我也遇到了
> 改了配置文件里面
> 
> * “Proxy” 现在改成“proxies”
> * “proxy-group” 改成 “proxy-groups”
> * “Rule” 改成 “rules”
>   就好了

谢谢，我去试试

**Comment by Nevidebla** [comment]
配置文件路径在哪呀？还有就是貌似解压版与安装版是共用数据文件的。我先用解压免安装版导入了一个订阅，后来安装版打开就直接有那个订阅了。

> 这个情况我也遇到了
> 改了配置文件里面
> 
> * “Proxy” 现在改成“proxies”
> * “proxy-group” 改成 “proxy-groups”
> * “Rule” 改成 “rules”
>   就好了

配置文件路径是？
还有就是貌似免安装版与安装版共用数据文件，我先是用免安装解压版导入了一个订阅，然后再安装的安装版，打开里面直接就有那个订阅了

**Comment by Spole0168** [comment]
修改那个配置文件？
.config\clash\profiles

**Comment by lzhaoyang** [comment]
我也遇到了这个问题 ，免安装版本的
![image](https://user-images.githubusercontent.com/14249262/83230894-26332b80-a1bd-11ea-96f4-ac7af8ef2e59.png)
一直卡在这个loading界面，希望可以修复一下

**Comment by lzhaoyang** [comment]
> 我也遇到了这个问题 ，免安装版本的
> ![image](https://user-images.githubusercontent.com/14249262/83230894-26332b80-a1bd-11ea-96f4-ac7af8ef2e59.png)
> 一直卡在这个loading界面，希望可以修复一下

找到问题了，可能是之前装了老版本的clash，卸载删除的时候没有把对于的配置文件删除，配置文件在.config\clash ，可以尝试删除这些老的配置文件，可以看文件时间。然后重新运行新的免安装的clash，就可以跑起来了。
![image](https://user-images.githubusercontent.com/14249262/83231465-1bc56180-a1be-11ea-8c4b-af22451d543a.png)

**Comment by lzhaoyang** [comment]
老版本的clash的配置文件是大写开头的
![image](https://user-images.githubusercontent.com/14249262/83232143-3b10be80-a1bf-11ea-8e89-ce1229ac2911.png)
但是新版本的配置文件是小写开头
![image](https://user-images.githubusercontent.com/14249262/83232226-65fb1280-a1bf-11ea-98fc-7dff7ddf2171.png)
所以在你之前安装过老版本clash，如果不删除这个老版本配置文件，直接运行新的clash，就会卡在loading界面，解决方法1 


> 这个情况我也遇到了
> 改了配置文件里面
> 
> * “Proxy” 现在改成“proxies”
> * “proxy-group” 改成 “proxy-groups”
> * “Rule” 改成 “rules”
>   就好了

方法二就是删除老版本配置，直接重新配置这个文件。
