### ISSUE TITLE
0.9.9版本在win10下能连上但测速延时都是timeout

### ISSUE THREAD

**Issue by Cost11** [Fndroid/clash_for_windows_pkg#766]
**描述**
能连上服务器 但不能使用

服务端用的是v2ray 已用v2rayN测试过 节点能用 但用CFW就timeout且 无法使用
配置也没有问题 以前一直能用 昨天突然不能用了  除了昨天安装了系统补丁KB4550945
今天重新删除所有配置，再试了一次，还是不能用，不知道什么问题。
希望有大佬能解决一下！！！
**截图**
![无](https://user-images.githubusercontent.com/37539782/81256510-4ad73000-9063-11ea-8b2b-b7a6b7953a30.png)

**其他说明**
日志
time="2020-05-07T12:40:20+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-05-07T12:40:20+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-05-07T12:40:20+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2020-05-07T12:40:20+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-05-07T12:40:20+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-05-07T12:40:20+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-05-07T12:40:31+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-05-07T12:40:33+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-05-07T12:42:08+08:00" level=info msg="Start initial compatible provider load-balance"
time="2020-05-07T12:42:08+08:00" level=info msg="Start initial compatible provider fallback-auto"
time="2020-05-07T12:42:08+08:00" level=info msg="Start initial compatible provider auto"
time="2020-05-07T12:42:08+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-05-07T12:44:03+08:00" level=warning msg="dial auto error: xx.xxx.xxx:443 connect error"
time="2020-05-07T12:44:03+08:00" level=warning msg="dial auto error: xx.xxx.xxx:443 connect error"
time="2020-05-07T12:44:03+08:00" level=warning msg="dial auto error: xx.xxx.xxx:443 connect error"
time="2020-05-07T12:44:03+08:00" level=warning msg="dial Proxy error: xx.xxx.xxx:443 connect error"
time="2020-05-07T12:44:08+08:00" level=warning msg="dial auto error: xx.xxx.xxx:443 connect error"
time="2020-05-07T12:44:08+08:00" level=warning msg="dial auto error: xx.xxx.xxx:443 connect error"
time="2020-05-07T12:44:08+08:00" level=warning msg="dial Proxy error: xx.xxx.xxx:443 connect error"
time="2020-05-07T12:44:08+08:00" level=warning msg="dial auto error: xx.xxx.xxx:443 connect error"
time="2020-05-07T12:44:18+08:00" level=warning msg="dial auto error: xx.xxx.xxx:443 connect error"
time="2020-05-07T12:44:18+08:00" level=warning msg="dial Proxy error: xx.xxx.xxx:443 connect error"   /真实域名已用xx.xxx.xxx代替

**Comment by Fndroid** [comment]
升级到最新版试试先
