### ISSUE TITLE
网速变慢

### ISSUE THREAD

**Issue by fybiachi** [Fndroid/clash_for_windows_pkg#767]
本来测速是100m 用了这个之后变成了2m，但是开着这个测速能到50-80m，关了就很慢 ，但是下载东西速度却正常，打开国内网站慢，具体是不是因为这个软件导致的我也不清楚，家用电信宽带，昨天喊客服弄了下恢复正常100m，然后我继续使用clash，之后又掉到2m。到底是不是这个软件导致，评论区的朋友们有同样的情况吗

**Comment by Phowx** [comment]
应该是规则问题，看日志排查一下

**Comment by fybiachi** [comment]
> 
> 
> 应该是规则问题，看日志排查一下

怎么在不用这个软件之后重置规则呢，有时候在全局模式下关掉软件，浏览网页速度正常，有时候也是慢。

**Comment by rqtingfeng** [comment]
就是这个软件，也就最近6个版本有这个问题，启用系统代理，还可能会导致没有网速
