### ISSUE TITLE
TAP模式下使用“redir-host”的问题

### ISSUE THREAD

**Issue by Sanly** [Fndroid/clash_for_windows_pkg#768]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
在TAP模式下使用“redir-host”，winapp2ool（更新CCleaner自定义规则的工具：[winapp2] (https://github.com/MoscaDotTo/Winapp2) ）无法使用，提示错误日志：

> 未经处理的异常:  System.IO.FileNotFoundException: 未能找到文件“C:\Users\Sanly\AppData\Local\Temp\version.txt”。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   在 System.IO.StreamReader..ctor(String path)
   在 winapp2ool.downloadr.getFileDataAtLineNum(String path, Int32 lineNum)
   在 winapp2ool.updater.getVersionFromLocalFile(String path)
   在 winapp2ool.updater.getRemoteVersion(String remotelink)
   在 winapp2ool.updater.toolVersionCheck()
   在 winapp2ool.updater.checkUpdates(Boolean cond)
   在 winapp2ool.Winapp2ool.printMenu()
   在 winapp2ool.MenuMaker.initModule(String name, Action showMenu, Action`1 handleInput, Int32 itmLen)
   在 winapp2ool.Winapp2ool.main()

在TAP模式下，如使用“fake-ip”，则winapp2ool可以正常使用。

使用“redir-host”的原因：使用“fake-ip”时，cfw-tap会显示无法连接到internet。

**Comment by Fndroid** [comment]
1. 这个软件报错不是应该反馈给它吗？
2. fake-ip显示未联网：https://github.com/Fndroid/clash_for_windows_pkg/issues/466#issuecomment-614716133

**Comment by Sanly** [comment]
因为我想着在TAP模式下，无论是“redir-host”还是“fake-ip”，只是对于DNS的不同处理，最终效果应该是相同的，所以对于同一软件的连通性应该也是一样的。但现在表现出的现象确实一个有问题一个没有问题，所以我觉得应该是代理软件的问题，可能是clash内核的问题。也不知道我理解的对不对。
