### ISSUE TITLE
GeoIP Database更新完毕后一直处于Restarting core状态，以前版本都没此问题

### ISSUE THREAD

**Issue by YFTX2015** [Fndroid/clash_for_windows_pkg#769]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题

**复现**
请描述复现问题的步骤:
1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
清晰地描述期望看到的行为

**截图**
如果可以，请提供对应问题的截图
![2020-05-08](https://user-images.githubusercontent.com/12757305/81366792-17a5a700-911e-11ea-94b3-6329a2e788f7.png)

**其他说明**
其他补充内容

**Comment by IDforHYIT** [comment]
同遇到此情况，早前版本更新后秒重启内核，最新0.9.10版本更新GeoIP重启内核速度明显变慢甚至一直保持一直处于重启状态

**Comment by Sanly** [comment]
我的GeoIP Database好像没法更新，之前的版本一直如此：
![批注 2020-05-08 114952](https://user-images.githubusercontent.com/9320187/81368799-4bcf9680-9123-11ea-9689-93c45b44928b.png)

**Comment by ggdxwz** [comment]
看了你的issue之后手贱更新了，现在也restarting了😂
但是重启之后就好了
![image](https://user-images.githubusercontent.com/33804090/81391601-f362be00-914f-11ea-9206-4aee881b63f6.png)

**Comment by FangLeeway** [comment]
应该只是状态没有更新，重启应用之后，GeoIP 更新其实已经成功了。

**Comment by Fndroid** [comment]
下个版本修复

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.11

**Comment by ntol** [comment]
已更新至v0.9.11，两个问题依旧存在

**Comment by sanddudu** [comment]
更新至v0.9.11之后问题依旧，另外只要手动更新 geoip 后卡在重启核心，geoip 功能就会失效，删除新下载的 geoip 文件改用版本默认的就不会有问题

**Comment by ntol** [comment]
> 更新至v0.9.11之后问题依旧，另外只要手动更新 geoip 后卡在重启核心，geoip 功能就会失效，删除新下载的 geoip 文件改用版本默认的就不会有问题

不要用自己注册的maxmind去更新Geoip，用Owner给的https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb，Key留空。也需要先删除下载的数据库文件，不然一样卡重启核心。

**Comment by Fredpata** [comment]
> > 更新至v0.9.11之后问题依旧，另外只要手动更新 geoip 后卡在重启核心，geoip 功能就会失效，删除新下载的 geoip 文件改用版本默认的就不会有问题
> 
> 不要用自己注册的maxmind去更新Geoip，用Owner给的[https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb，Key留空。也需要先删除下载的数据库文件，不然一样卡重启核心。](https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb%EF%BC%8CKey%E7%95%99%E7%A9%BA%E3%80%82%E4%B9%9F%E9%9C%80%E8%A6%81%E5%85%88%E5%88%A0%E9%99%A4%E4%B8%8B%E8%BD%BD%E7%9A%84%E6%95%B0%E6%8D%AE%E5%BA%93%E6%96%87%E4%BB%B6%EF%BC%8C%E4%B8%8D%E7%84%B6%E4%B8%80%E6%A0%B7%E5%8D%A1%E9%87%8D%E5%90%AF%E6%A0%B8%E5%BF%83%E3%80%82)

用默认的……一直无法更新.卡在1%不动……
用https://static.clash.to/GeoIP2/GeoIP2-Country.tar.gz
就一直卡在重启核心
