### ISSUE TITLE
开机自启后的一个小bug

### ISSUE THREAD

**Issue by sakuyamaij** [Fndroid/clash_for_windows_pkg#77]
平时使用是开机自启后和系统代理两个都✔的。
平时系统代理打勾后，右下角的猫是土黄色的，没打勾是蓝色的。这个大家都知道
但是开机自启后，系统代理默认是没打勾的，但猫却是土黄色的。

希望能修复这2个bug
1. 开机能自动系统代理
2. 如果开机没有开启系统代理，猫的颜色显示修复

**Comment by Fndroid** [comment]
系统代理开关的状态是会被记住的，下次启动会恢复这个状态。自启动和手动启动都一样

至于界面中没有打勾，可以通过切换左侧menu看看刷新状态，或者进入系统设置的代理设置中查看

**Comment by sakuyamaij** [comment]
今天再次测试了下。环境Windows10 Pro 1809 17763.316
在确认CFW系统代理打勾，【局域网设置代理服务器】为开的情况下。重新启动电脑。
重启后【局域网设置代理服务器为】为关，CFW的猫是黄色的，开启后显示系统代理打勾了，点击左侧menu刷新下状态后，系统代理的勾消失了，猫也变回蓝色。
今晚再试下，cfw不启用的情况下重启电脑，【局域网设置代理服务器】会不会也会自动关闭。如果依然发生的话就和CFW没什么关系了。

但是今天又发现一个问题，我的clash配置里有一个socks5，是ssr的端口。当ssr客户端中切换节点，或者ssr客户端关闭再启动后，均会导致cfw的系统代理这一栏的勾消失。所以目前推测可能是开机启动时由于ssr客户端的启动导致的，总之晚上再测试一下了。

**Comment by Fndroid** [comment]
@sakuyamaij Clash for Windows和SSR的系统代理只能选一个..

**Comment by sakuyamaij** [comment]
不好意思，发现是由于SSR客户端里【系统代理模式】设置的是直连模式。导致每次操作SSR后都会刷新状态将系统代理给关了，改为【保持目前状态不修改】后已经一切正常。感谢作者的答复
