### ISSUE TITLE
安装 0.9.9 或 0.9.10 版本后，tap 模式无效

### ISSUE THREAD

**Issue by everplus** [Fndroid/clash_for_windows_pkg#770]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
安装 0.9.9 或 0.9.10 版本后，tap 模式无效，删除 experimental 试过也无效，一直显示网络电缆被拔出，换回 0.9.8 后恢复正常

**Comment by Flammulinavelutipes** [comment]
0.9.10测试tap模式有效。
但发现所有流量均走Proxy，Rule规则无效，不知道是bug还是就这样设计的？ @Fndroid

**Comment by Fndroid** [comment]
把experimental加回去，用0.9.10就正常

**Comment by Fndroid** [comment]
@Flammulinavelutipes https://github.com/Fndroid/clash_for_windows_pkg/issues/694

**Comment by everplus** [comment]
experimental 加了的，试了 0.9.11 也不行，家里的电脑可以，公司的就不可以
