### ISSUE TITLE
未知原因无法连接Clash core

### ISSUE THREAD

**Issue by Dabrit** [Fndroid/clash_for_windows_pkg#771]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
启动clash for windows 加载后出现"could not connect to Clash core"字样，点击“Try to repair”无法修复，经检查.config/clash目录中的config.yaml的xternal-controller端口为9090，而**9090端口并无任何应用占用**，后将yml文件修改至其它端口也无法解决。问题出现前一直正常使用没有改动文件。

**复现**  
 进入Clash for windows百分百复现

**版本**
0.9.9，issue写一半升级到0.9.10发现问题依旧

**截图**
![image](https://user-images.githubusercontent.com/35628088/81379521-da501200-913b-11ea-9ef8-30ca15c609a8.png)

**日志文件**
~~不知道为甚么无法直接上传，先凑合一下~~

`time="2020-05-08T14:53:26+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-05-08T14:53:26+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-05-08T14:53:26+08:00" level=error msg="External controller error: listen tcp 127.0.0.1:9090: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2020-05-08T14:53:26+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-05-08T14:53:26+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-05-08T14:53:26+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-05-08T14:53:26+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2020-05-08T14:54:43+08:00" level=info msg="[TCP] 127.0.0.1:9743 --> github-production-user-asset-6210df.s3.amazonaws.com match Match using DIRECT"
time="2020-05-08T14:54:46+08:00" level=warning msg="dial DIRECT error: dial tcp4 172.217.160.69:443: i/o timeout"
time="2020-05-08T14:54:59+08:00" level=info msg="[TCP] 127.0.0.1:9757 --> github-production-repository-file-5c1aeb.s3.amazonaws.com match Match using DIRECT"
time="2020-05-08T14:55:29+08:00" level=info msg="[TCP] 127.0.0.1:9785 --> github-production-repository-file-5c1aeb.s3.amazonaws.com match Match using DIRECT"
`

**Comment by Dabrit** [comment]
已经自行恢复，原理未知

**Comment by haominzheng** [comment]
我今天出现了这样的问题

**Comment by usr-4124** [comment]
@haominzheng 

可以尝试修改 C:\Users\你的用户名\.config\clash 目录下 config.yaml

把 `external-controller: '127.0.0.1:9090'` 里面的端口号 `9090` 换成一个五位数的端口，例如`43210`。

至少我是这样解决的，希望能帮上你！
