### ISSUE TITLE
UI 小瑕疵·续😂

### ISSUE THREAD

**Issue by NerfThat** [Fndroid/clash_for_windows_pkg#772]
**信息**
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
更新0.9.10后General上方的分割线明显过宽了（正常分割线2倍粗细），反而0.9.9版本我这是正常的，并没有遇到 https://github.com/Fndroid/clash_for_windows_pkg/issues/755 提到的这个问题，高分屏缘故？

**复现**
无

**预期行为**
无

**截图**
![批注 2020-05-08 184414](https://user-images.githubusercontent.com/65015698/81399484-a685e400-915d-11ea-8ec0-33d20d77e412.png)

**其他说明**

**Comment by Fndroid** [comment]
自定义了字体吗

**Comment by NerfThat** [comment]
> 自定义了字体吗

没有，刚查看config.yaml后没有自定义字体的配置，系统也一直是原版

**Comment by NerfThat** [comment]
> 自定义了字体吗

我看了下其他人0.9.10的issues同样是这样的

**Comment by AlleluiaCN** [comment]
我这边同样效果。

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.11
