### ISSUE TITLE
这个软件的配置文件在什么路径位置？

### ISSUE THREAD

**Issue by Nevidebla** [Fndroid/clash_for_windows_pkg#774]
看大家的评论，说最新版有bug，需要先手动修改一下配置文件才能使用。

**Comment by abae136ab** [comment]
> 看大家的评论，说最新版有bug，需要先手动修改一下配置文件才能使用。

c:\user\.config\clash

**Comment by Nevidebla** [comment]
> > 看大家的评论，说最新版有bug，需要先手动修改一下配置文件才能使用。
> 
> ```
> c:\user\xxx\.config\clash
> ```

我的配置文件是不是有点问题？
![image](https://user-images.githubusercontent.com/54260027/81480142-3dd06180-925a-11ea-838b-a872d5417352.png)
那个config.yaml里面只有端口号这一个数据。
![image](https://user-images.githubusercontent.com/54260027/81480156-5f314d80-925a-11ea-9619-5eecddf4f85e.png)
![image](https://user-images.githubusercontent.com/54260027/81480175-73754a80-925a-11ea-96a1-a40065695296.png)
这里面也只是端口号数据
![image](https://user-images.githubusercontent.com/54260027/81480187-90aa1900-925a-11ea-8dc4-170595493178.png)
这个文件编码格式都是乱码

**Comment by Fndroid** [comment]
下载最新版，清空目录，启动
