### ISSUE TITLE
从0.8更新到0.9 出现诡异问题

### ISSUE THREAD

**Issue by Imtonoo** [Fndroid/clash_for_windows_pkg#775]
在新的主界面有一个tap device install 的东西， 出于好奇点了一下，

结果无法通过浏览器翻墙了，但在proxies里面测试响应时间没问题，即使在设备管理器里面禁用或是卸载仍然不行。 卸载重新安装软件也不行，有什么办法恢复原样吗？

**Comment by Fndroid** [comment]
什么版本
