### ISSUE TITLE
从0.9.4不论升级到0.9.9还是0.9.10均无法使用

### ISSUE THREAD

**Issue by RoxasKing** [Fndroid/clash_for_windows_pkg#777]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
一旦开启代理，节点测速全部timeout；
0.9.4一切功能正常使用，0.9.8、0.9.9、0.9.10都完全没法用，是彻底没法用的那种，开了代理连境内网都上不成的那种

**截图**
![QQ图片20200509195746](https://user-images.githubusercontent.com/29565140/81473311-22e8f780-9230-11ea-9bbd-c3b21b8929c0.png)

**Comment by chliqk** [comment]
把Windows系统时间设置为北京时间。

**Comment by popo3505** [comment]
编辑订阅配置，把dns-enable设置为false

**Comment by RoxasKing** [comment]
> 编辑订阅配置，把dns-enable设置为false

可以了，非常感谢！
