### ISSUE TITLE
下载配置文件的时候，请求头加上clash core的版本号

### ISSUE THREAD

**Issue by feng92f** [Fndroid/clash_for_windows_pkg#778]
建议 在配置文件更新和下载时请求头上加上自己的版本信息
 
core-version: x
cfw-version:y

让不同的客户端下载到适合的配置文件。避免配置文件格式变化引起的兼容性问题。

**Comment by joewongex** [comment]
是的

**Comment by Fndroid** [comment]
计划在下个版本加入自定义request headers的功能，允许用户定义header的值

并一并解决这个问题：https://github.com/Fndroid/clash_for_windows_pkg/issues/515

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.9.11
