### ISSUE TITLE
无法使用混合配置mixin

### ISSUE THREAD

**Issue by moonaileen** [Fndroid/clash_for_windows_pkg#779]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [ ] 软件下载后未修改任何安装目录中的文件

**描述**
升级至0.9.10后无法使用混合配置mixin

**复现**
请描述复现问题的步骤:
在config.yaml文件中加入了cfw-ropfile-mixin字段：
`` cfw-profile-mixin:
  dns:
    enable: true
    listen: :53
    nameserver:
    - 8.8.8.8
    - 114.114.114.114 ``
并开启mixin开关，显示成功。tap也显示已连接。
但是开启mixin后，只能访问直连网站，需要代理连接的网站都无法打开，节点已经确认正常，并且能够正常ping通。
关上mixin开关后一切正常。

**Comment by Fndroid** [comment]
> 软件下载后未修改任何安装目录中的文件

改过什么文件？

**Comment by moonaileen** [comment]
> > 软件下载后未修改任何安装目录中的文件
> 
> 改过什么文件？

就只改了config.yaml这个文件

**Comment by Fndroid** [comment]
不能访问的时候log显示什么

**Comment by moonaileen** [comment]
![Snipaste_2020-05-11_18-54-25](https://user-images.githubusercontent.com/2804132/81548885-eac0f080-93b8-11ea-9a33-5b3264d8efda.png)


> 不能访问的时候log显示什么

log显示如图：
我也不知道为什么会这样orz

**Comment by Fndroid** [comment]
看下配置文件里是不是有设置dns，是的话先去掉kjkj

**Comment by moonaileen** [comment]
> 看下配置文件里是不是有设置dns，是的话先去掉看看

不可以，去掉以后提示错误：
![Snipaste_2020-05-11_18-59-40](https://user-images.githubusercontent.com/2804132/81549379-99fdc780-93b9-11ea-8235-144c741d9d3f.png)

**Comment by Fndroid** [comment]
配置没改对，自己学学yaml语法？

**Comment by moonaileen** [comment]
![Snipaste_2020-05-11_19-04-08](https://user-images.githubusercontent.com/2804132/81550146-cd8d2180-93ba-11ea-8791-7484b3255159.png)
我现在是这么设的，因为就是想跨配置文件用tap功能，但是打开mixin就不行。
刚才我可能理解错您的意思，把nameserver字段删掉了。所以才报错囧

**Comment by Fndroid** [comment]
缩进要对齐，interface-name不要弄错，不确定就删掉等它自动识别

**Comment by moonaileen** [comment]
> 缩进要对齐，interface-name不要弄错，不确定就删掉等它自动识别
interface-name没有弄错，删掉的我也试过了，只要打开就不行……
我一开始就是按照配置说明里的样式写进去的，但是也没有用……看了下log全都是失败
![Snipaste_2020-05-11_19-39-54](https://user-images.githubusercontent.com/2804132/81552902-43938780-93bf-11ea-8d9c-5a199e3bb351.png)
![Snipaste_2020-05-11_19-41-13](https://user-images.githubusercontent.com/2804132/81553014-6de54500-93bf-11ea-82ba-1386680e46cb.png)
本来以为TAP模式可以靠这个方式注入到其他订阅的配置文件里，我就不用自己手改了，但是一直没成功，现在还是在复制订阅配置文件到本地手动修改😂😂

**Comment by Fndroid** [comment]
mixin就是这么用的，前提是你缩进不能写错

**Comment by moonaileen** [comment]
又看了一遍，我的缩进好像没问题啊？😂

**Comment by moonaileen** [comment]
😭问题还是没有得到解决……还是没懂到底哪里出了问题……
大大一开始说设置里关掉dns是指的哪里呀？如果是订阅的配置文件里的dns的话，我订阅的配置文件里没有设dns额……
orz对不起真的不知道自己哪里有问题……看来我只能老老实实复制成本地文件手动修改了吗T_T

**Comment by Fndroid** [comment]
> 又看了一遍，我的缩进好像没问题啊？😂
> 把interface-name删掉了，现在是这样：
> ![Snipaste_2020-05-11_20-04-12](https://user-images.githubusercontent.com/2804132/81554983-a89cac80-93c2-11ea-845a-db15bd24366d.png)
> 看log还是一样的问题
> ![Snipaste_2020-05-11_20-04-23](https://user-images.githubusercontent.com/2804132/81555008-b18d7e00-93c2-11ea-92bc-9b95f34d8aa1.png)

这里不都已经正常了么

**Comment by moonaileen** [comment]
> > 又看了一遍，我的缩进好像没问题啊？😂
> > 把interface-name删掉了，现在是这样：
> > ![Snipaste_2020-05-11_20-04-12](https://user-images.githubusercontent.com/2804132/81554983-a89cac80-93c2-11ea-845a-db15bd24366d.png)
> > 看log还是一样的问题
> > ![Snipaste_2020-05-11_20-04-23](https://user-images.githubusercontent.com/2804132/81555008-b18d7e00-93c2-11ea-92bc-9b95f34d8aa1.png)
> 
> 这里不都已经正常了么

不正常，打开mixin和最开始一样，无法连接需要代理的网站，只能打开直连的网站

**Comment by Fndroid** [comment]
显示NoMatch，就是没匹配上规则，可能：
1. 把``rules``字段也缩进到``cfw-profile-mixin``里面了，然后没有规则
2. 原来的配置文件就没有``rules``

**Comment by moonaileen** [comment]
————啊啊啊！！对了对了！原来是这个问题啊……TOT
我原来以为添加的rules字段相当于在原来的配置基础上单独注入一条新规则，原来不是哦……
这下明白了，太感谢了orz
