### ISSUE TITLE
疑似DNS问题，Dial [DIRECT] failed

### ISSUE THREAD

**Issue by Fredpata** [Fndroid/clash_for_windows_pkg#780]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [X] 已经尝试更新到最新版本，问题依旧存在
- [X] 软件从本仓库下载
- [X] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题
一直断断续续会有无法正常访问部分网址的问题，比如t.co 短域名，微博图片，JD、淘宝网站（及部分图片）。改全局或者关掉clash 可以解决。
DNS设置过114 阿里 腾讯 ISP本地DNS，均无法持续改善。感觉是移动宽带资源的问题，clash是否存在DNS缓存？能否强制全部刷新啊？

**复现**
请描述复现问题的步骤:
访问JD 网站

**预期行为**
清晰地描述期望看到的行为
期望正常访问，实际访问极慢，图片无法出现，或者直接无法访问

**截图**
如果可以，请提供对应问题的截图

![1](https://user-images.githubusercontent.com/1464774/81494129-c988d300-92d8-11ea-9799-6c26e26650d6.jpg)

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
关掉dns试下？

**Comment by Fredpata** [comment]
> 关掉dns试下？

这样可以解决国内访问……t.co 短域名好像还是不行。启用DNS 首选8.8.8.8 有时候能打开……全局的时候倒是正常的……

唉

**Comment by Fndroid** [comment]
关掉dns就是用系统dns了，和clash也没关系了

**Comment by tea1111980** [comment]
> > 关掉dns试下？
> 
> 这样可以解决国内访问……t.co 短域名好像还是不行。启用DNS 首选8.8.8.8 有时候能打开……全局的时候倒是正常的……
>
> 唉

你需要 SmartsDNS 来过滤一下。

**Comment by chenlikunlove** [comment]
在Mixin中写入以下内容即可：
`mixin: # 注意下面缩进 dns: enable: true listen: :53 nameserver: - 8.8.8.8`

**Comment by hugyu** [comment]
> 

请问Mixin 在哪呢

**Comment by hugyu** [comment]
> 在Mixin中写入以下内容即可： `mixin: # 注意下面缩进 dns: enable: true listen: :53 nameserver: - 8.8.8.8`
请问Mixin 在哪呢
