### ISSUE TITLE
Edit policies 和 Edit rules 不显示配置内容

### ISSUE THREAD

**Issue by Doraemon2020** [Fndroid/clash_for_windows_pkg#781]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
版本：0.9.10
Edit policies 和 Edit rules 里面是空的，不显示配置内容

**截图**
![微信截图_20200511004927](https://user-images.githubusercontent.com/59880367/81505586-f06bf700-9322-11ea-99fd-ea07fc5e5e07.png)
![微信截图_20200511004858](https://user-images.githubusercontent.com/59880367/81505594-fd88e600-9322-11ea-8028-d7f834b4237a.png)

**Comment by NerfThat** [comment]
rename some fields (backwards compatibility until 1.0)
    Proxy --> proxies
    Proxy Group --> proxy-groups
    Rule --> rules
    proxy-provider --> proxy-providers
