### ISSUE TITLE
有线网络环境tap模式不可用

### ISSUE THREAD

**Issue by Flammulinavelutipes** [Fndroid/clash_for_windows_pkg#782]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**

****PC有线以太网环境****

当配置文件中配置为：
dns:
listen: 0.0.0.0:53

此时cfw-tap能够连接，但全部timeout，direct和proxy均无法上网。
![企业微信截图_20200511103921](https://user-images.githubusercontent.com/26811405/81531923-25656180-9396-11ea-8713-80527808ca7d.png)

当配置文件中配置为：
dns:
listen: 127.0.0.1:53

此时连接正常，但cfw-tap显示拔出，tap模式不可用。
![企业微信截图_20200511104106](https://user-images.githubusercontent.com/26811405/81531935-2bf3d900-9396-11ea-9802-3c0af8eb38f6.png)

**复现**
请描述复现问题的步骤:
有线以太网环境
1. 修改配置文件：
dns:
listen: 127.0.0.1:53
2. 拖动配置文件到“Profiles”并点击应用
3. 点击“Proxies”→“Global”→“Test latency”→正常
4. 查看系统网络连接，cfw-tap显示“拔出”，tap模式不可用

5.修改配置文件：
dns:
listen: 0.0.0.0:53
6.拖动配置文件到“Profiles”并点击应用
7. 点击“Proxies”→“Global”→“Test latency”→显示timeout，direct和proxy均无法打开网页
8.查看系统网络连接，cfw-tap显示“连接”，说明tap模式正常

**预期行为**
cfw-tap显示“连接”，tap模式可用，并且不出现timeout问题，能够正常使用

**截图**
截图如上

**其他说明**

并且如下配置
dns:
listen: 0.0.0.0:53
在笔记本WiFi环境下使用一切正常，cfw-tap能够连接，无timeout问题，可正常上网。
不知是有线以太网环境时配置文件有特别的地方需要修改吗？还是别的什么问题？

配置文件如下（忽略了proxies、proxy-groups、rules部分以及注释部分）：

port: 7890

socks-port: 7891

allow-lan: false

mode: Rule

log-level: info

external-controller: 127.0.0.1:9090

experimental:
ignore-resolve-fail: true # ignore dns resolve fail, default value is true
interface-name: '以太网' # outbound interface name

dns:
enable: true # set true to enable dns (default is false)
ipv6: false # default is false
listen: 0.0.0.0:53
nameserver:
- 114.114.114.114
- tls://dns.rubyfish.cn:853 # dns over tls
- https://1.1.1.1/dns-query # dns over https

**Comment by Fndroid** [comment]
1. 0.9.6之后dns必须监听在0.0.0.0才能启动TAP
2. TAP模式需要``interface-name``指定为系统物理网卡名称才能避免回环，不同网络环境``interface-name``可能会改变。把这个值删掉软件会尝试自动识别。

**Comment by Flammulinavelutipes** [comment]
> 1. 0.9.6之后dns必须监听在0.0.0.0才能启动TAP
> 2. TAP模式需要`interface-name`指定为系统物理网卡名称才能避免回环，不同网络环境`interface-name`可能会改变。把这个值删掉软件会尝试自动识别。

原来如此，已解决，感谢。
