### ISSUE TITLE
Profiles内的规则会莫名其妙的消失

### ISSUE THREAD

**Issue by thatseason** [Fndroid/clash_for_windows_pkg#783]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
Profiles内的规则会莫名其妙的消失，上次0.9开机2、3天就消失了，重新配置一遍，更新到最新版还是这样，什么情况？又不能导出，每次重新配置，崩溃！

**其他说明**
是不是自动更新订阅就把规则全覆盖了？

**Comment by Fndroid** [comment]
更新配置文件就是重新下载一份配置文件覆盖
