### ISSUE TITLE
仍然无法按延迟排序

### ISSUE THREAD

**Issue by realhuyang** [Fndroid/clash_for_windows_pkg#784]
**信息**
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
cfw-proxies-order: latency
设置了这个，仍然无法按延迟排序

**截图**
![image](https://user-images.githubusercontent.com/25172023/81599403-16fd6100-93fb-11ea-9f1f-c7169b71a04d.png)

**Comment by Fndroid** [comment]
设置在哪里了？配置文件还是General里的General YAML

**Comment by realhuyang** [comment]
设置在 Profiles 里的 config.yaml 无效。
设置在 General 里的 General YAML，会直接导致软件奔溃不可用。

**Comment by Fndroid** [comment]
崩溃？界面提示什么

**Comment by realhuyang** [comment]
在 General 里的 General YAML 添加 cfw-proxies-order: latency 后
就会一直 loading
![image](https://user-images.githubusercontent.com/25172023/81632419-c73f8980-943c-11ea-9d47-db91f8e31ee2.png)

不显示线路
![image](https://user-images.githubusercontent.com/25172023/81632422-ceff2e00-943c-11ea-969b-5fcbd51fe81c.png)

**Comment by Fndroid** [comment]
点左下角文字，发最新log

**Comment by realhuyang** [comment]
time="2020-05-12T10:45:00+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-05-12T10:45:00+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-05-12T10:45:00+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-05-12T10:45:00+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-05-12T10:45:00+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2020-05-12T10:45:00+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-05-12T10:45:08+08:00" level=info msg="[TCP] 127.0.0.1:2903 --> live.github.com match Match using DIRECT"
time="2020-05-12T10:45:09+08:00" level=warning msg="dial DIRECT error: dial tcp4 172.217.24.10:443: i/o timeout"
time="2020-05-12T10:45:10+08:00" level=warning msg="dial DIRECT error: dial tcp4 172.217.24.10:443: i/o timeout"
time="2020-05-12T10:45:39+08:00" level=info msg="[TCP] 127.0.0.1:2910 --> content-autofill.googleapis.com match Match using DIRECT"
time="2020-05-12T10:45:40+08:00" level=info msg="[TCP] 127.0.0.1:2913 --> content-autofill.googleapis.com match Match using DIRECT"

**Comment by Fndroid** [comment]
看着没问题，卡住loading的log有么

**Comment by realhuyang** [comment]
time="2020-05-12T11:12:32+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-05-12T11:12:32+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-05-12T11:12:32+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-05-12T11:12:32+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-05-12T11:12:32+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-05-12T11:12:32+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2020-05-12T11:12:36+08:00" level=info msg="[TCP] 127.0.0.1:3326 --> live.github.com match Match using DIRECT"
time="2020-05-12T11:12:40+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-05-12T11:12:40+08:00" level=info msg="[TCP] 127.0.0.1:3331 --> live.github.com match Match using DIRECT"
time="2020-05-12T11:12:48+08:00" level=info msg="Start initial compatible provider PROXY"
time="2020-05-12T11:12:48+08:00" level=info msg="Start initial compatible provider FINAL"
time="2020-05-12T11:12:48+08:00" level=info msg="Start initial compatible provider Hijacking"
time="2020-05-12T11:12:53+08:00" level=info msg="[TCP] 127.0.0.1:3336 --> live.github.com match Match using FINAL[x1.0 伦敦 - 直连1]"
time="2020-05-12T11:12:56+08:00" level=info msg="[TCP] 127.0.0.1:3338 --> live.github.com match Match using FINAL[x1.0 伦敦 - 直连1]"
time="2020-05-12T11:13:00+08:00" level=info msg="[TCP] 127.0.0.1:3341 --> live.github.com match Match using FINAL[x1.0 伦敦 - 直连1]"

**Comment by realhuyang** [comment]
time="2020-05-12T11:13:06+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-05-12T11:13:06+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-05-12T11:13:06+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-05-12T11:13:06+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-05-12T11:13:06+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-05-12T11:13:06+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2020-05-12T11:13:07+08:00" level=info msg="[TCP] 127.0.0.1:3354 --> live.github.com match Match using DIRECT"
time="2020-05-12T11:13:08+08:00" level=info msg="Start initial compatible provider PROXY"
time="2020-05-12T11:13:08+08:00" level=info msg="Start initial compatible provider Hijacking"
time="2020-05-12T11:13:08+08:00" level=info msg="Start initial compatible provider FINAL"

**Comment by realhuyang** [comment]
time="2020-05-12T11:13:27+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-05-12T11:13:27+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-05-12T11:13:27+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-05-12T11:13:27+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-05-12T11:13:27+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2020-05-12T11:13:27+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-05-12T11:13:27+08:00" level=info msg="[TCP] 127.0.0.1:3414 --> live.github.com match Match using DIRECT"
time="2020-05-12T11:13:27+08:00" level=info msg="[TCP] 127.0.0.1:3415 --> live.github.com match Match using DIRECT"
time="2020-05-12T11:14:23+08:00" level=info msg="[TCP] 127.0.0.1:3427 --> github.com match Match using DIRECT"
time="2020-05-12T11:14:25+08:00" level=info msg="[TCP] 127.0.0.1:3429 --> github.com match Match using DIRECT"
time="2020-05-12T11:14:25+08:00" level=info msg="[TCP] 127.0.0.1:3431 --> github.com match Match using DIRECT"
time="2020-05-12T11:14:25+08:00" level=info msg="[TCP] 127.0.0.1:3432 --> github.com match Match using DIRECT"
time="2020-05-12T11:14:25+08:00" level=info msg="[TCP] 127.0.0.1:3434 --> github.com match Match using DIRECT"
time="2020-05-12T11:14:25+08:00" level=info msg="[TCP] 127.0.0.1:3433 --> github.com match Match using DIRECT"
time="2020-05-12T11:14:30+08:00" level=warning msg="dial DIRECT error: dial tcp4 172.217.160.74:443: i/o timeout"
time="2020-05-12T11:14:32+08:00" level=warning msg="dial DIRECT error: dial tcp4 172.217.160.74:443: i/o timeout"

**Comment by Fndroid** [comment]
1. 要么General YAML没改对格式
2. 要么某些软件阻止了127.0.0.1:9090访问
