### ISSUE TITLE
GeoIP疑似无法匹配，且会一直重启核心，Baidu会走代理

### ISSUE THREAD

**Issue by Hsiung233** [Fndroid/clash_for_windows_pkg#786]
**信息**
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
使用rule时，将GeoIP国家代码CN设为直连无效，有的依然会走代理

**复现**
1.GeoIP Database的 License Key 留空，URL 为 https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb ，更新完了之后一直重启核心
2.在配置文件的rule将CN设为直连，但是依然会走代理

**预期行为**
国内的网站应该会直连

**截图**
![Snipaste_2020-05-12_15-22-03](https://user-images.githubusercontent.com/29259049/81652802-e521e400-9466-11ea-919a-9367742cb159.png)
![Snipaste_2020-05-12_15-21-27](https://user-images.githubusercontent.com/29259049/81653148-25816200-9467-11ea-9e9d-e63ef7ab897c.png)
![Snipaste_2020-05-12_15-20-34](https://user-images.githubusercontent.com/29259049/81652818-ea7f2e80-9466-11ea-85bf-c7ff419e9231.png)
![Snipaste_2020-05-12_15-43-08](https://user-images.githubusercontent.com/29259049/81653397-519ce300-9467-11ea-914b-2e67cafecd82.png)

**其他说明**
无

**Comment by Fndroid** [comment]
Duplicate of https://github.com/Fndroid/clash_for_windows_pkg/issues/769
