### ISSUE TITLE
电脑网络使用宽带连接后，clash不能使用

### ISSUE THREAD

**Issue by zhxrrb** [Fndroid/clash_for_windows_pkg#787]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
之前电脑连接无线网络，可以正常使用，但在更换为有线宽带之后就不能用了，谷歌什么的都没有办法使用

**复现**
请描述复现问题的步骤:
1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
清晰地描述期望看到的行为

**截图**
如果可以，请提供对应问题的截图

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
拨号？

**Comment by zhxrrb** [comment]
是的

**Comment by Fndroid** [comment]
网卡名是中文的话设置不了系统代理，改成英文

**Comment by zhxrrb** [comment]
网卡名是指网络的名称吗？像这样？
![TIM截图20200512194809](https://user-images.githubusercontent.com/41381435/81684449-8e79d180-9489-11ea-82a8-7750b6661034.jpg)
.png…]()

**Comment by zhxrrb** [comment]
我设置完，然后重启了一下，已经可以正常使用了！非常感谢~

**Comment by Hellq** [comment]
非常有用，感谢

**Comment by zhouyuangan** [comment]
可以，很强，感谢

**Comment by lyogurts** [comment]
感谢

**Comment by mengrank** [comment]
感谢

**Comment by WSJ-github** [comment]
感谢大佬！！！

**Comment by xaingang** [comment]
![屏幕截图 2023-03-07 222049](https://user-images.githubusercontent.com/91340703/223449604-3a826da1-52ab-42b9-89e8-7345befc8ff8.png)
这样的呢，怎么改

**Comment by Gogobee** [comment]
> 

加一

**Comment by ibenyi** [comment]
> 

请问您最后改好了嘛   是怎么改的呀  我的笔记本我太会操作

**Comment by Gogobee** [comment]
因为我是用的校园网，需要上网认证，反正不能是SRUN3k专用宽带拨号连接，必须是你自己的英文拨号连接




我是用的我们学校的上网认证网址进行上网认证就行了



superhuman
***@***.***







                       
Original Email
                       
                     

Sender:"ibenyi"< ***@***.*** &gt;;

Sent Time:2023/4/2 9:08

To:"Fndroid/clash_for_windows_pkg"< ***@***.*** &gt;;

Cc recipient:"Gogobee"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

Subject:Re: [Fndroid/clash_for_windows_pkg] 电脑网络使用宽带连接后，clash不能使用 (#787)




   
请问您最后改好了嘛   是怎么改的呀  我的笔记本我太会操作

**Comment by WHYERR** [comment]
校园网的有线网怎么弄啊，不是自己的网卡？

**Comment by nicr2008** [comment]
有用，感谢

**Comment by nicr2008** [comment]
校园网也能改名称，拨号连接那里

**Comment by nicr2008** [comment]
校园网也能改名称，拨号连接那里

**Comment by Eser-Tired** [comment]
我也遇到一样的问题，感谢大佬，在Win11自带的拨号里面该名称为英文就好了
