### ISSUE TITLE
希望打开Allow LAN以后（CFW），以后每次开机这个选项都是开着的

### ISSUE THREAD

**Issue by SenchunYao** [Fndroid/clash_for_windows_pkg#789]
**描述**
因为每天都需要重新开机，但是每次开机都要重新打开`Allow Lan`选项，而不是保存CFW上次关闭时的状态。希望这个功能能够添加进去~

**Comment by Fndroid** [comment]
Duplicate of https://github.com/Fndroid/clash_for_windows_pkg/issues/489
