### ISSUE TITLE
无法正常打开System Proxy.

### ISSUE THREAD

**Issue by KimigaiiWuyi** [Fndroid/clash_for_windows_pkg#790]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
无法打开System Proxy.

**复现**
正常打开CFW

**预期行为**
反复开关System proxy开关/反复重启软件/删除Clash文件夹/重启电脑均无效

**截图**
![Snipaste_2020-05-13_11-21-30.png](http://yanxuan.nosdn.127.net/f6c85aa202c72547579343b7065d4a6d.png)

**Comment by KimigaiiWuyi** [comment]
**补充截图**
![Snipaste_2020-05-13_11-21-30.png](https://i.loli.net/2020/05/13/2PbnMx1e8Bl5CTd.png)

**Comment by NerfThat** [comment]
确认系统设置里的手动设置代理没切过去吗？

**Comment by KimigaiiWuyi** [comment]
@NerfThat 
是这个意思吗...截取了系统代理设置的截图
**图**
![Snipaste_2020-05-13_12-46-03.png](https://i.loli.net/2020/05/13/WYahP3GIC6LSTKs.png)

**Comment by Fndroid** [comment]
拨号联网的么

**Comment by KimigaiiWuyi** [comment]
> 拨号联网的么

wifi

**Comment by Fndroid** [comment]
有使用什么安全软件么？可能其他软件锁定了注册表

**Comment by KimigaiiWuyi** [comment]
> 有使用什么安全软件么？可能其他软件锁定了注册表

没有使用安全软件，WD都关闭了
昨晚还能正常使用，今天早上就不行了，不知道原因为何
log显示无法启用Redir UDP监听，有什么办法可以解决吗
已经重新安装过了（甚至改变了安装的盘符）都没有有效解决~

**Comment by NerfThat** [comment]
> > 有使用什么安全软件么？可能其他软件锁定了注册表
> 
> 没有使用安全软件，WD都关闭了
> 昨晚还能正常使用，今天早上就不行了，不知道原因为何
> log显示无法启用Redir UDP监听，有什么办法可以解决吗
> 已经重新安装过了（甚至改变了安装的盘符）都没有有效解决~

你这系统是动过的吧，系统代理手动填上试试能不能用（能不能填）

**Comment by Fndroid** [comment]
> log显示无法启用Redir UDP监听，有什么办法可以解决吗

这个是正常的，因为redir不支持windows

无法打开系统代理多半是因为系统问题，可能很多，建议google一下

**Comment by KimigaiiWuyi** [comment]
> > > 有使用什么安全软件么？可能其他软件锁定了注册表
> > 
> > 
> > 没有使用安全软件，WD都关闭了
> > 昨晚还能正常使用，今天早上就不行了，不知道原因为何
> > log显示无法启用Redir UDP监听，有什么办法可以解决吗
> > 已经重新安装过了（甚至改变了安装的盘符）都没有有效解决~
> 
> 你这系统是动过的吧，系统代理手动填上试试能不能用（能不能填）

能填，但是也没有什么用
系统没动过，最新预览版
魔幻的是昨晚都行，今天一早起来就完全不行了。
完全想象不到中间发生了什么

**Comment by KimigaiiWuyi** [comment]
> > log显示无法启用Redir UDP监听，有什么办法可以解决吗
> 
> 这个是正常的，因为redir不支持windows
> 
> 无法打开系统代理多半是因为系统问题，可能很多，建议google一下

谷歌了半天，也没办法确定原因
比较魔幻，昨晚睡前关电脑之前明明都可以，今天一大早就不行了 
中间没有系统更新，没有修改任何文件，中间到底发生了什么完全不知道

**Comment by KimigaiiWuyi** [comment]
> > log显示无法启用Redir UDP监听，有什么办法可以解决吗
> 
> 这个是正常的，因为redir不支持windows
> 
> 无法打开系统代理多半是因为系统问题，可能很多，建议google一下

测试V2ray也不行，SSR却可以
IE设置里局域网链接(LAN)的选项打开无论怎么设置都无法按确定键保存

**Comment by KimigaiiWuyi** [comment]
@Fndroid 
弄了一天终于解决了。
注册表HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinHttpAutoProxySvc的start值修改为2，重启即可。
希望对后来的人能有所帮助

**Comment by msie60** [comment]
同样遇到这个问题，随系统自动启动后，system 开关无效，即使任务栏右键点击或者dashboard上点了后，系统设置中也不会打开系统开关。
但是在系统代理设置中手动打开，上网是可以的。同@KimigaiiWuyi 开始可以，突然就不行了。
