### ISSUE TITLE
使用9.10版本全部timeout，无法连接

### ISSUE THREAD

**Issue by LieCoding** [Fndroid/clash_for_windows_pkg#791]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x]软件下载后未修改任何安装目录中的文件

**描述**
使用9.10，9.9版本全部timeout，浏览器也无法使用，连境内网都进不去。
9.6版本可以使用，但是会经常出现连接被重置，刷新后又可以使用，
使用的是拨号连接，

**截图**
如果可以，请提供对应问题的截图
![image](https://user-images.githubusercontent.com/64515587/81791983-030c4900-953a-11ea-876a-397b458ba2f5.png)

![image](https://user-images.githubusercontent.com/64515587/81792072-21724480-953a-11ea-9ed3-6da46edfe664.png)

![image](https://user-images.githubusercontent.com/64515587/81791889-e7a13e00-9539-11ea-9ca1-04bc131e1abb.png)

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
看看配置文件里有没有写dns，有的话enable改成false试试

**Comment by LieCoding** [comment]
![image](https://user-images.githubusercontent.com/64515587/81797642-a4e36400-9541-11ea-8ab3-9dfcce15c72f.png)



改成false后可以使用了，但是还存在连接重置的问题，刷新之后又可以使用。

**Comment by LieCoding** [comment]
> 看看配置文件里有没有写dns，有的话enable改成false试试



![image](https://user-images.githubusercontent.com/64515587/81797839-dbb97a00-9541-11ea-84de-586fa673ba51.png)

改了之后可以联网了，但是连接重置问题还存在。

**Comment by Fndroid** [comment]
多数是因为本地连接到远端服务器出现问题导致的，换个服务器或者换个服务商试试

**Comment by LieCoding** [comment]
> 多数是因为本地连接到远端服务器出现问题导致的，换个服务器或者换个服务商试试

你好，我换成v2ray后就没有出现这个问题了，不知道是不是这个程序配置的问题。

**Comment by Fndroid** [comment]
配置问题你得咨询你的服务商
