### ISSUE TITLE
Messenger 无法登录

### ISSUE THREAD

**Issue by FaiChou** [Fndroid/clash_for_windows_pkg#792]
这是一条问题请教。

![Snipaste_2020-05-13_19-32-21](https://user-images.githubusercontent.com/18500846/81810617-d6fec100-9555-11ea-9128-6339b5378155.png)

在 Store 里下载的 Messenger app，使用了[两种方法](https://zhuanlan.zhihu.com/p/29989157)代理 UWP 应用。

已经代理成功，因为如果不成功那么登录按钮不能点击。但是点击登录时候会报错，信息如截图所示。

但在 clashx 里看到这个 api 请求应该没有 timeout。

![Snipaste_2020-05-13_20-03-53](https://user-images.githubusercontent.com/18500846/81811507-54770100-9557-11ea-8ad2-16eb64f6a0da.png)

运行环境/尝试过：
1. 设置为系统代理
2. 设置为 Global

**Comment by LeonSparta** [comment]
使用TAP模式可以代理上，Messenger算是不走系统代理的奇葩
