### ISSUE TITLE
CFW没有正确处理clash://install-config?url=MY_URL中URL的参数

### ISSUE THREAD

**Issue by cyanlink** [Fndroid/clash_for_windows_pkg#795]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
CFW丢弃了clash URL scheme中，订阅URL的第2、3、4……个参数。

**复现**
请描述复现问题的步骤:

1. 构建如下URL：clash://install-config?url=https://www.foobar.com/hello?alpha=1&beta=1
2. 复制粘贴进入浏览器地址栏，选择打开CFW。
3. CFW会打开Profiles界面，且上方文本框显示：https://www.foobar.com/hello?alpha=1 并尝试从这个URL获得订阅配置文件 ，只得到了第一个参数alpha，而‘&’符号后面订阅URL的参数beta=1被截断，导致无法正确获得订阅。有的订阅URL的参数可能包含关键的token。

**预期行为**
CFW不应丢弃通过clash URL scheme获得的订阅URL的后续参数。

**截图**
![批注 2020-05-14 233844](https://user-images.githubusercontent.com/14952800/81954967-18699c00-963c-11ea-817f-adacec98f9b5.png)
如图所示，首个参数mu=0被识别，但是后续参数filter_offline根本没有进入CFW。在有些情况下，后续参数可能为一些关键token，导致订阅无法被正确下载。

**其他说明**
我不确定这是否是clash上游错误处理URL Scheme引入的问题

**Comment by Fndroid** [comment]
urlencode

**Comment by cyanlink** [comment]
@Fndroid 稍等附上图片，我使用的是 v2ray2clash工具（github开源），其中订阅URL的确经过了urlencode

**Comment by cyanlink** [comment]
@Fndroid v2ray2clash工具使用了golang gin框架提供的PathEscape函数，它产生的clash URL形式如下：
`"clash://install-config?url=http:%2F%2F192.168.1.203:5050%2Fv2ray2clash%3Flan_link=https:%2F%2Fwww.zhixin66.com%2Fmodules%2Fservers%2FV2raySocks%2Fsubscribe%2F%3Fsid=123456&token=EXAMPLEUSE"`

其中&符号没有被编码，同样，CFW只得到了sid，而最后的参数token被抛弃

**Comment by cyanlink** [comment]
定位到了问题出现在v2ray2clash身上，这个工具错误地使用了PathEscape函数而不是QueryEscape函数。。。（订阅URL应该被视作是一个Query，而不是URL Path，因此&符号也应该被转义）
