### ISSUE TITLE
希望能够改变一下连接信息里的显示方式

### ISSUE THREAD

**Issue by Hsiung233** [Fndroid/clash_for_windows_pkg#798]
**描述**
希望在连接信息的Time选项卡中，最新的连接放在顶部，因为查看下载速度的时候，最大的在上面，但是Time选项卡里最新的连接又在下面，需要反复滚动列表，有些麻烦
![image](https://user-images.githubusercontent.com/29259049/82008943-9bbcd900-96a0-11ea-8318-6d7c6dd3af8f.png)
另外，希望连接时间可以改成直接显示时分秒，不要显示几秒，几分钟前，有时候列表的项目多了就会变卡，显示时分秒就不必更新整个列表的连接时间了

**其他说明**
无

**Comment by coderloverXH** [comment]
说出了我的心声
