### ISSUE TITLE
在Profiles中Edit rule - >Add rule后默认规则失效

### ISSUE THREAD

**Issue by AmberBufei** [Fndroid/clash_for_windows_pkg#799]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载
- [ ] 软件下载后未修改任何安装目录中的文件

**描述**

点击Profiles，Add一条rule，之后发现只有该条规则生效，默认的规则全部失效了。
且当前版本打开Profiles--Edit Rules 里面rule为空，不显示默认规则。

建议

应该把用户新增规则设置为附加规则，增加几条就附加几条，如果添加一条用户规则，原有默认规则全部都失效，这不合常理。

**复现**
请描述复现问题的步骤:
1. 进入'Profies '
2. 点击Edit rules.'
3. add 一条 新rules
4. 确认- save
5.默认规则失效，无法访问外网。

**预期行为**
 应该把用户新增规则设置为附加规则，增加几条就附加几条，把用户新增加的rule权重提高，覆盖默认规则里面已存在的rule。

**截图**

![image](https://user-images.githubusercontent.com/26531400/82035484-24a03880-96d2-11ea-81b4-793194e7d9f0.png)

**其他说明**

**Comment by Fndroid** [comment]
Duplicate of #694
