### ISSUE TITLE
休眠自动断开问题

### ISSUE THREAD

**Issue by sunyi369** [Fndroid/clash_for_windows_pkg#8]
勾选systemproxy，计算机在自动休眠唤醒后，打开cfw，此时system proxy选项是没有勾选的，计算机休眠cfw会自动断开。
系统：win7 x64 旗舰版

**Comment by Fndroid** [comment]
尝试一下最新的release

**Comment by zhaorui963** [comment]
在最新的0.36版本中仍然如此。

**Comment by Fndroid** [comment]
讨论 #312
