### ISSUE TITLE
GUI上更改的配置没法即使更新到 config.yml 文件

### ISSUE THREAD

**Issue by xiaojinzi123** [Fndroid/clash_for_windows_pkg#80]

**Comment by Fndroid** [comment]
Clash for Windows支持多配置

所以没有更改config.yml的地方，config.yml只是作为启动的一个配置文件，仅仅会应用General部分

其余部分（dns/proxy/proxy group/rule）均使用Profiles里定义的，而UI里的更改是针对特定的Profile的

**Comment by Fndroid** [comment]
此issue将暂时进行关闭处理，如问题依旧，欢迎reopen

**Comment by xiaojinzi123** [comment]
我知道你的更改是不作用到 config.yml 文件的,但是您能做一个小功能让 profile 中的某一个文件可以一键覆盖 config.yml  上,毕竟站在用户的角度上,用户去修改一个 profile 中的文件就是想让修改的生效,我目前的做法是 GUI 上的修改保存以后手动去复制 profile 中的文件内容到 config.yml,这很明显让使用者很不舒服,您看是否可以把这个问题解决下

**Comment by Fndroid** [comment]
使用不舒服是因为你没有理解怎么正确的使用

我上面说了config.yml只是作为启动基准配置文件，启动完了GUI会自动切换到上次退出前使用的那个profile

在profile中修改文件都是立即生效的

如果没有，请更新
