### ISSUE TITLE
希望支持全局rules规则添加功能

### ISSUE THREAD

**Issue by zhouzl7** [Fndroid/clash_for_windows_pkg#800]
**描述**
希望支持全局rules规则添加功能，现在增加rule只能在每个Profile中单独添加，且更新订阅链接后，手动添加的规则将被清除，十分不友好。希望增加全局规则，可以应用到每个Profile中，也不会随着更新订阅而被清除。

**其他说明**
![image](https://user-images.githubusercontent.com/33414045/82041468-cfb4f000-96da-11ea-9755-90d83851efdb.png)

**Comment by Fndroid** [comment]
说过很多遍了，规则不是独立存在都，它依赖于策略/节点，不能单独增加
