### ISSUE TITLE
使用TAB模式，如不打开系统代理选项，则youtube首页视频无缩略图

### ISSUE THREAD

**Issue by mixool** [Fndroid/clash_for_windows_pkg#801]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [ x] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载
- [ ] 软件下载后未修改任何安装目录中的文件

**描述**
使用TAB模式，如不打开系统代理选项，则youtube首页视频无缩略图，视频可正常播放
开启系统代理后则能正常显示缩略图

**预期行为**
使用TAB模式，无需打开系统代理就能正常显示youtube缩略图

**截图**
![off](https://s1.ax1x.com/2020/05/15/Yyu6xO.png)
![on](https://s1.ax1x.com/2020/05/15/YyuhdA.png)

mixin配置：
cfw-profile-mixin: 
  dns:
    enable: true
    enhanced-mode: redir-host
    listen: 0.0.0.0:53
    nameserver:
      - 223.5.5.5
      - 119.29.29.29
  experimental:
    interface-name: XXX
  tun:
    enable: true

不清楚是什么原因导致
是不是我cfw-profile-mixin中的DNS配置问题，望指导

**Comment by Fndroid** [comment]
enhanced-mode换成fake-ip试试

**Comment by mixool** [comment]
@Fndroid fake-ip模式下同样出现，并非全部缩略图无法显示，能显示几张，打开系统代理后即可迅速正常加载完毕

**Comment by Fndroid** [comment]
把nameserver换成一个``tls://dns.rubyfish.cn:853``，原来两个都去掉

**Comment by mixool** [comment]
@Fndroid 换成tls的dns依然无改善，现象和之前一样，均尝试了fake-ip和redir-host。尝试清空了所有规则配置全部走代理，依然一样，应该和规则路由规则无关。
我的网络是中国移动

**Comment by ForestL18** [comment]
关闭mixin，使用TAB模式，不开启系统代理选项的时候一切正常

**Comment by ForestL18** [comment]
YouTube缩略图无法加载可能和节点有关系，我也是只开了TAP，其他的如mixin，系统代理都没开。某些节点可以正常显示，某些节点就是不能显示YouTube缩略图，打开其他网页正常
