### ISSUE TITLE
以高优先级开机启动CFW

### ISSUE THREAD

**Issue by NonXZhu** [Fndroid/clash_for_windows_pkg#802]
**描述**
现在的开机启动方式往往晚于一些使用情况，尤其是在tap模式下无法访问网络。希望提供以系统服务或其他方式提高启动优先级。

**Comment by Fndroid** [comment]
迟一点会有什么问题呢？

**Comment by NonXZhu** [comment]
1、设置了系统代理后，直到CFW启动，才可以使用。
2、设置了TAP后可以比其他自启程序更早的启动来接管它们的流量。

**Comment by XuuKoo** [comment]
可以使用计划任务（管理员权限），启动会更快一些。
