### ISSUE TITLE
关于软件的设置问题

### ISSUE THREAD

**Issue by 00why00** [Fndroid/clash_for_windows_pkg#804]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载
- [x ] 软件下载后未修改任何安装目录中的文件

**描述**
我下载Clash之后，Epic Games客户端会默认选择国外的CDN结点，而不是国内的CDN结点，在选择rule模式时，下载速度可以达到10Mb/s，在选择模式为Direct模式后，下载游戏速度显著下降到1Mb/s，在关闭Clash后，Epic客户端会提示没有网络，我想知道Clash是否修改了哪个设置，让Epic误认为我在国外，我又如何改回来。

**其他说明**
我尝试过卸载Clash，但是Epic仍然连接国外的CDN结点

**Comment by Fndroid** [comment]
CFW关闭之后，任何网络都和它无关了，并不会修改什么设置
