### ISSUE TITLE
默认程序

### ISSUE THREAD

**Issue by denghuotongming** [Fndroid/clash_for_windows_pkg#805]
问一下，为什么要修改默认程序！火绒提示的

**Comment by Fndroid** [comment]
能带个图么，什么都没怎么答你？

**Comment by denghuotongming** [comment]
![image](https://user-images.githubusercontent.com/51149477/82453790-8f42e100-9ae3-11ea-8336-556511f4cef5.png)

**Comment by Fndroid** [comment]
这是注册系统对于``clash://``连接都交给CFW处理，方便你导入配置文件都，如果你不需要可以禁止，这样就不能用urlsheme打开CFW了，参考：https://docs.cfw.lbyczf.com/contents/urlscheme.html

**Comment by denghuotongming** [comment]
好的 多谢！火绒是绿的也就允许了，不太懂就问了下。

Fndroid <notifications@github.com> 于2020年5月20日周三 下午10:13写道：
