### ISSUE TITLE
0.9.11版本，软件内无法编辑策略

### ISSUE THREAD

**Issue by DannyVim** [Fndroid/clash_for_windows_pkg#806]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
今天更新到0.9.11版本，尝试在软件内编辑策略信息，然后出现如图情况（所有的profiles都是如此）：
![image](https://user-images.githubusercontent.com/7478103/82134103-8bcf0180-9826-11ea-9400-276c7a7cbbc6.png)

请问，是我本地的错误，还是这个版本的bug？

**Comment by Fndroid** [comment]
Duplicate of https://github.com/Fndroid/clash_for_windows_pkg/issues/694
