### ISSUE TITLE
tap 模式

### ISSUE THREAD

**Issue by time-byte** [Fndroid/clash_for_windows_pkg#808]
救救孩子吧!
![image](https://user-images.githubusercontent.com/40427877/82143108-fa867c00-9873-11ea-8fd5-2ea9ce53ee24.png)
![image](https://user-images.githubusercontent.com/40427877/82143118-0a05c500-9874-11ea-9dfc-af8bf796caed.png)
![image](https://user-images.githubusercontent.com/40427877/82143123-0e31e280-9874-11ea-906c-f5683af9120e.png)
![image](https://user-images.githubusercontent.com/40427877/82143148-37eb0980-9874-11ea-881c-3215a487e05b.png)

**Comment by Fndroid** [comment]
dns设置在哪个文件里？

**Comment by time-byte** [comment]
![image](https://user-images.githubusercontent.com/40427877/82143486-f019b180-9876-11ea-86b6-98420ab1b71b.png)


list.yml

**Comment by Fndroid** [comment]
哪里看到要写到这个文件里的？

点开界面中的Profiles，点你用着的那个配置文件的“铅笔”按钮，加到配置文件里

**Comment by time-byte** [comment]
谢谢 -
