### ISSUE TITLE
打开软件提示time=“2020-08-18T10:37:14”

### ISSUE THREAD

**Issue by zhaokelei** [Fndroid/clash_for_windows_pkg#809]
如果符合，请将``[ ]``改为``[x]``
- [X ] 已经尝试更新到最新版本，问题依旧存在
- [ X] 软件从本仓库下载
- [ ] 软件下载后未修改任何安装目录中的文件

time="2020-05-18T10:37:14+08:00" level=fatal msg="Parse config error: invalid mode"

打开加载一会就这样了
time="2020-05-18T10:37:14+08:00" level=fatal msg="Parse config error: invalid mode"

![YW0ToQ.png](https://s1.ax1x.com/2020/05/18/YW0ToQ.png)

**Comment by Fndroid** [comment]
改过什么文件

**Comment by zhaokelei** [comment]
替换了一个汉化文件，不过一直也没问题，昨天晚上出现的

**Comment by Fndroid** [comment]
替换了就别发issue了，我不知道
