### ISSUE TITLE
请问不小心删掉config.yml了，然后卸载重装还是没有怎么办

### ISSUE THREAD

**Issue by imaqine** [Fndroid/clash_for_windows_pkg#81]
请问不小心删掉config.yml了，然后卸载重装还是没有怎么办

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/raw/master/config.yml

**Comment by imaqine** [comment]
谢谢你，成功使用uwp版网易云了

**Comment by zhaoaaaaa5** [comment]
> https://github.com/Fndroid/clash_for_windows_pkg/raw/master/config.yml

你好 这个地址404了，请问还有新地址吗？

**Comment by sinosman** [comment]
玩这东西太麻烦了
