### ISSUE TITLE
无法寻得rules

### ISSUE THREAD

**Issue by Amhertx** [Fndroid/clash_for_windows_pkg#813]
字段都是更改好的了，但是无法在rules里面看到规则
![image](https://user-images.githubusercontent.com/46993971/82209964-c88f1b80-9940-11ea-8b3a-832d3995927c.png)

**Comment by Amhertx** [comment]
是最新版0.9.11

**Comment by Fndroid** [comment]
先选中一份配置文件，再编辑

**Comment by Amhertx** [comment]
> 先准备一份配置文件，再编辑

哦哦，好了谢谢
