### ISSUE TITLE
Connections界面性能问题

### ISSUE THREAD

**Issue by NonXZhu** [Fndroid/clash_for_windows_pkg#816]
**信息**
- [x] 软件从本仓库下载
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
Connections如果存在过多的历史连接，无论是滚动、排序还是整个CFW界面都有明显的性能问题。

**复现**
请描述复现问题的步骤:
1. 进入'Connections'
2. 静置一段时间或建立很多连接
3. 触发问题

**预期行为**
界面响应速度不受影响

**截图**
![image](https://user-images.githubusercontent.com/31027139/82215201-eb084100-990e-11ea-9961-51270d8397d8.png)

**Comment by Emphasia** [comment]
如果能加个可选项设置展示或清除多久的历史就好了
