### ISSUE TITLE
安装完成后打开，General页面一直显示Loading

### ISSUE THREAD

**Issue by Kingson** [Fndroid/clash_for_windows_pkg#817]
![Lark20200519-104002](https://user-images.githubusercontent.com/468509/82278679-5c063200-99bd-11ea-9702-e26282cf24ce.png)
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
安装完成后打开，General页面一直显示Loading

**Comment by Fndroid** [comment]
日志贴下

**Comment by Kingson** [comment]
> 日志贴下

不好意思，麻烦问一下日志的目录是？

**Comment by ntol** [comment]
> > 日志贴下
> 
> 不好意思，麻烦问一下日志的目录是？

点软件左下角的“Connected”连接状态即可快速打开目录

**Comment by Kingson** [comment]
> 日志贴下

time="2020-05-14T13:59:36+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-05-14T13:59:36+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-05-14T13:59:36+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-05-14T13:59:36+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"

**Comment by Kingson** [comment]
> > > 日志贴下
> > 
> > 
> > 不好意思，麻烦问一下日志的目录是？
> 
> 点软件左下角的“Connected”连接状态即可快速打开目录

Thanks！

**Comment by Spole0168** [comment]
大神，我的也是那个一直链接中。。。
日志如下：
time="2020-05-21T11:36:18+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"

**Comment by jjjtui** [comment]
将用户名/.config/clash删掉就正常了

**Comment by Spole0168** [comment]
好的，多谢。

**Comment by Bruce-wong** [comment]
time="2020-04-23T18:38:05+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-04-23T18:38:05+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-04-23T18:38:05+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-04-23T18:38:05+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"

**Comment by Bruce-wong** [comment]
我的也是这样，一直loading

**Comment by R5MTF** [comment]
me too,happened? my log:
time="2020-05-26T10:16:39+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-05-26T10:16:39+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-05-26T10:16:39+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-05-26T10:16:39+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-05-26T10:16:39+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-05-26T10:16:39+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"

**Comment by Kingson** [comment]
> 将用户名/.config/clash删掉就正常了

Thanks，It's working now！

**Comment by Kingson** [comment]
> 我的也是这样，一直loading

将用户名/.config/clash删掉就正常了

**Comment by Kingson** [comment]
> me too,what happened? my log:
> time="2020-05-26T10:16:39+08:00" level=info msg="Start initial compatible provider Proxy"
> time="2020-05-26T10:16:39+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
> time="2020-05-26T10:16:39+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
> time="2020-05-26T10:16:39+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
> time="2020-05-26T10:16:39+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
> time="2020-05-26T10:16:39+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"

将用户名/.config/clash删掉就正常了

**Comment by sesamefly** [comment]
请问如何将将用户名/.config/clash删掉就正常了删除？ @Kingson
