### ISSUE TITLE
clash for Windows的线路显示timeout

### ISSUE THREAD

**Issue by sanxiu0** [Fndroid/clash_for_windows_pkg#818]
同样的线路在我的clash for Android中可以使用，但是Windows版本无法使用，日志显示无效套字节和无法解析的dns。请问有什么办法可以解决。
![222](https://user-images.githubusercontent.com/57577636/82297627-810e9b00-99e5-11ea-956a-d9666d572ef4.png)

**Comment by sanxiu0** [comment]
版本是最新的0.9.11

**Comment by Fndroid** [comment]
发个log吧

**Comment by linshiyx** [comment]
同样的问题，下面是唯一异常的log
time="2020-05-24T20:38:05+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"

**Comment by UntaggedRui** [comment]
你在手机中用的是流量吗？可能是电脑上的宽带网络和手机的移动数据网络环境不同导致的。我的机场，手机上流量能用大部分节点，电脑上用的移动宽带，只能用很少几个节点。

**Comment by echo860** [comment]
我的也是，在手机上很好用，在电脑上节点少速度超慢，以前电脑上一直用得很稳定的，我返回以前的版本试试看

**Comment by JessYi228** [comment]
我的也有这种情况，但是是有时能用，有时突然就全部timeout

**Comment by flyfinec** [comment]
![image](https://user-images.githubusercontent.com/3030186/93951743-b2271f80-fd79-11ea-9e72-6aadc4a58b95.png)
下载网络服务商的yml配置文件后，如上图，将dns enable设置为false或者删除google的fallback，就没再出现timeout，大家试试

**Comment by XDFHTY** [comment]
同样的问题，测试全部超时，楼上的方法也没有用，打开配置文件没有DNS选项！！

log: time="2021-03-18T14:33:20+08:00" level=warning msg="Parse metadata failed: script not found"

**Comment by cpslamdunk** [comment]
"下载网络服务商的yml配置文件"
请问这个yml配置文件去哪里下载啊？
谁能发一份给我的QQ邮箱里吗？  543341817@qq.com
万分感激！

**Comment by cpslamdunk** [comment]
> ![image](https://user-images.githubusercontent.com/3030186/93951743-b2271f80-fd79-11ea-9e72-6aadc4a58b95.png)
> 下载网络服务商的yml配置文件后，如上图，将dns enable设置为false或者删除google的fallback，就没再出现timeout，大家试试
下载网络服务商的yml配置文件，这一步如何实现呢？

**Comment by flyfinec** [comment]
@cpslamdunk 这个ss服务商提供的下载地址，可以从下载地址快速下载配置，要看ss服务商是否提供，是否有这个功能。

**Comment by zjgbql** [comment]
> ![image](https://user-images.githubusercontent.com/3030186/93951743-b2271f80-fd79-11ea-9e72-6aadc4a58b95.png) 下载网络服务商的yml配置文件后，如上图，将dns enable设置为false或者删除google的fallback，就没再出现timeout，大家试试

感谢你八辈祖宗。困扰我好多天的问题。能告诉我为什么吗？

**Comment by DeasonHu** [comment]
@zjgbql 你设置fallback肯定是希望国外的域名通过国外的dns解析，你肯定也知道国内连不上国外的dns所以你肯定设置了通过节点解析。
于是当你解析节点的域名的时候，你的节点肯定在国外，这个域名就会被送到节点通过国外的dns解析，但这时你的节点还是不可用的，于是你节点的域名就没法解析，然后节点就timeout了

**Comment by DeasonHu** [comment]
我也被这个问题困扰了几个月 今天看到这里突然就想通了 真的感谢 cpslamdunk 八辈祖宗

**Comment by SEUZTh** [comment]
Mac和Linux上都不会有这个问题，就是win上有

**Comment by stringang** [comment]
也有可能是 DNS 问题，手动设置网络的 DNS 服务器。
