### ISSUE TITLE
两台设备都是win10专业版，其中有一台无法正常连接，版本均为0.9.10

### ISSUE THREAD

**Issue by wangran101** [Fndroid/clash_for_windows_pkg#819]
time="2020-05-20T08:58:56+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-05-20T08:58:56+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-05-20T08:58:56+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-05-20T08:58:56+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-05-20T08:58:56+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-05-20T08:58:56+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2020-05-20T08:58:56+08:00" level=warning msg="dial DIRECT error: lookup raw.githubusercontent.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."
time="2020-05-20T08:58:56+08:00" level=info msg="[TCP] 127.0.0.1:62590 --> api.github.com match Match using DIRECT"
time="2020-05-20T08:58:56+08:00" level=info msg="[TCP] 127.0.0.1:62588 --> 203.119.169.109 match Match using DIRECT"
time="2020-05-20T08:59:14+08:00" level=info msg="[TCP] 127.0.0.1:62604 --> officecdn.microsoft.com match Match using DIRECT"
time="2020-05-20T09:02:17+08:00" level=warning msg="dial Proxy error: endtime.baidu.com:80 connect error"
time="2020-05-20T09:02:17+08:00" level=warning msg="dial Proxy error: endtime.baidu.com:80 connect error"
time="2020-05-20T09:02:19+08:00" level=info msg="[TCP] 127.0.0.1:62943 --> officecdn.microsoft.com match DomainSuffix using Domestic[DIRECT]"
time="2020-05-20T09:02:19+08:00" level=info msg="[TCP] 127.0.0.1:62945 --> 203.119.169.109 match GeoIP using Domestic[DIRECT]"
![image](https://user-images.githubusercontent.com/52906730/82393848-19eef600-9a7a-11ea-9fc8-9274645535cd.png)
![image](https://user-images.githubusercontent.com/52906730/82393954-5589c000-9a7a-11ea-8604-640d01a0c1d5.png)
![image](https://user-images.githubusercontent.com/52906730/82393968-5fabbe80-9a7a-11ea-92d6-6313db7324e2.png)

**Comment by Fndroid** [comment]
看下配置文件（Profiles）里是不是定义了dns，是的话先删掉试试

**Comment by wangran101** [comment]
> 看下配置文件（Profiles）里是不是定义了dns，是的话先删掉试试

我在profile下看了三个yml文件，没有定义dns，应该都是保持的默认设置。

**Comment by wangran101** [comment]
> 看下配置文件（Profiles）里是不是定义了dns，是的话先删掉试试

已解决  原因为我的这台chrome上启用了谷歌上网助手  关闭后恢复正常  非常感谢您的回复
