### ISSUE TITLE
www.messenger.com 无法访问此网站

### ISSUE THREAD

**Issue by ShichaoNie** [Fndroid/clash_for_windows_pkg#82]
从使用v0.5.23-v0.5.27 使用dlercloud的订阅。www.messenger.com就无法访问此网站。从rule切换到global能正常打开。换回v0.5.21 www.messenger.com就能正常访问。想问一下是什么原因呢。

**Comment by LiangkeZhong** [comment]
应该是规则未更新的感觉

**Comment by VoVAllen** [comment]
一样的问题，也是dlercloud的，只不过网站是www.instagram.com

**Comment by Fndroid** [comment]
检查一下config.yml里面是不是有dns配置，有的话先删除试试

**Comment by VoVAllen** [comment]
检查过了没有

**Comment by ShichaoNie** [comment]
> 检查一下config.yml里面是不是有dns配置，有的话先删除试试

删除dns配置后，正常访问了

**Comment by VoVAllen** [comment]
我也fix了，把网卡DNS地址改了就好了

**Comment by ShichaoNie** [comment]
> 我也fix了，把网卡DNS地址改了就好了

怎么修改 在哪里修改啊

**Comment by ShichaoNie** [comment]
我现在的问题是config添加dns www.messenger.com无法访问。删除dns www.youtube.com无法访问

**Comment by VoVAllen** [comment]
就是改适配器设置，把首要DNS改成8.8.8.8

**Comment by HiMeHM** [comment]
> 就是改适配器设置，把首要DNS改成8.8.8.8

謝了，用的同一家dlercloud，之前更新後除了google搜索，其餘基本陣亡。現在改了DNS，Rule可以正常訪問
