### ISSUE TITLE
profile变成空白了

### ISSUE THREAD

**Issue by cataroreca** [Fndroid/clash_for_windows_pkg#820]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
删除了之前的订阅后，profile变成空白了。不知道要怎么更新订阅。大家可以帮帮我吗，谢谢！🙏
![image](https://user-images.githubusercontent.com/61407920/82517157-1f6a4000-9b4f-11ea-83ab-07abb5526fb1.jpg)

**Comment by Fndroid** [comment]
进入 General-Home Directory里把 profiles文件夹删除重启app

**Comment by cataroreca** [comment]
谢谢你啦！🥳



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Fndroid <notifications@github.com&gt;
发送时间: 2020年5月21日 10:42
收件人: Fndroid/clash_for_windows_pkg <clash_for_windows_pkg@noreply.github.com&gt;
抄送: cataroreca <3486413477@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Fndroid/clash_for_windows_pkg] profile变成空白了 (#820)





 
进入 General-Home Directory里把 profiles文件夹删除重启app
