### ISSUE TITLE
provider中的节点无法测速

### ISSUE THREAD

**Issue by hoha** [Fndroid/clash_for_windows_pkg#822]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
点击闪电按钮或者单个点击都没反应，只显示初始化的速度

**Comment by Fndroid** [comment]
核心限制原因，provider节点需要在

![image](https://user-images.githubusercontent.com/16091562/82559184-bc55c900-9ba1-11ea-93ea-f791c779b570.png)

里面操作
