### ISSUE TITLE
b站视频加载一场

### ISSUE THREAD

**Issue by ztisdashen** [Fndroid/clash_for_windows_pkg#824]
**信息**
version:9.11

**描述**
打开软件后，b站视频无法加载
**截图**
![TIM截图20200522122816](https://user-images.githubusercontent.com/45029776/82631351-cfab7780-9c27-11ea-86a6-151487b627d9.png)

**Comment by Fndroid** [comment]
根据日志检查规则和服务器

**Comment by Raibows** [comment]
@Fndroid 我使用的版本是0.10.4，似乎对视频加载（无论b站或爱奇艺）有异常。关闭system proxy之后，异常消失（模式均设定为DIRECT下）。可能是clash core的问题。还请排查。
![image](https://user-images.githubusercontent.com/37944786/92986203-c18da980-f4eb-11ea-98cf-66e82bd39317.png)

**Comment by yi-Xu-0100** [comment]
@Raibows 我的 bilibili 一直加载有问题，所以我直接配置了 bypass 关键词，这样不走 clash 代理，看起来**没有改善**。

感觉就是网络问题吧……如果认为与系统代理有关，配置 bypass 测试吧……

**Comment by Raibows** [comment]
@yi-Xu-0100 我已经控制变量了，打开DIRECT模式，仅仅就是打开或者关闭system proxy选项，bilibili的加载速度相差极大（一个10几秒，一个1s内）。而且尝试多次，无一例外。

**Comment by yi-Xu-0100** [comment]
@Raibows 如果认为**与 CFW 设置的系统代理**有关，配置 bypass 解决，bypass 会让域名不走 CFW 设置的系统代理……
链接：<https://docs.cfw.lbyczf.com/contents/bypass.html>

**Comment by Raibows** [comment]
@yi-Xu-0100 感谢！域名是否支持通配符呢？b站加载资源，有很多域名，想要domain-keyword的效果，例如``*bilibili*``，设置``- www.bilibili.com``后，主页加载速度有明显改善。

**Comment by yi-Xu-0100** [comment]
@Raibows 支持的，文档中有说明的。

![image](https://user-images.githubusercontent.com/25523606/92992655-11d22f00-f51f-11ea-8e36-73aa9add1d88.png)

**Comment by Raibows** [comment]
@yi-Xu-0100 输入``*bilibili*``会报错，通配符似乎只支持ip

**Comment by yi-Xu-0100** [comment]
@Raibows  注意加引号

![image](https://user-images.githubusercontent.com/25523606/92992733-a341a100-f51f-11ea-934e-ce240df66c79.png)

**Comment by Raibows** [comment]
@yi-Xu-0100 谢谢！目前测试了几个视频，速度都有很大的改善。

**Comment by yi-Xu-0100** [comment]
我这样配置之后，效果也有点吧，但是还是很慢，只能说人与人之间的体质不同吧，能帮到就好~🤪

**Comment by Raibows** [comment]
@yi-Xu-0100 经过我这几天使用及测试，可以确定是ipv6的原因。你可以尝试禁用ipv6再使用一下。

**Comment by yi-Xu-0100** [comment]
@Raibows 感谢你的建议，我会试试看，b 站看会卡一直是我的心病，还就电脑卡，希望这次能够解决这个问题~
