### ISSUE TITLE
打开时  general页面出错

### ISSUE THREAD

**Issue by 123driod** [Fndroid/clash_for_windows_pkg#825]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载
- [ ] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题

**复现**
请描述复现问题的步骤:
1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
清晰地描述期望看到的行为

**截图**
如果可以，请提供对应问题的截图

**其他说明**
其他补充内容
界面![image](https://user-images.githubusercontent.com/54090829/82685778-5a6f8f00-9c87-11ea-8a33-2453e7d4cd60.png)
日志
![image](https://user-images.githubusercontent.com/54090829/82685835-6e1af580-9c87-11ea-9ab2-541188ff25ff.png)

**Comment by 123driod** [comment]
我的window  10版本是2004

**Comment by Fndroid** [comment]
哪下的软件？

**Comment by 123driod** [comment]
> 哪下的软件？

GitHub上

**Comment by Fndroid** [comment]
9090端口被占用了，点左下角小字进入目录，返回上一级，修改config.yaml文件里external-controller端口，重启app
