### ISSUE TITLE
软件安装位置异常

### ISSUE THREAD

**Issue by fxzxmicah** [Fndroid/clash_for_windows_pkg#826]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
我无法将软件安装到类似于/Clash/这样的文件夹，每当我指定/Clash/软件就会安装在/Clash/Clash for Windows/这个文件夹下。

**预期行为**
希望能够将软件安装到/Clash/文件夹下，而不是/Clash/Clash for Windows/文件夹。

**Comment by Fndroid** [comment]
下载7z解压不就好

**Comment by fxzxmicah** [comment]
额，你这个，我无力反驳。但是我只是发现了这样一个问题，虽然不影响使用，但是这也是个问题，我只是发现了问题，反馈一下而已。

**Comment by realhuyang** [comment]
你用绿色版的啊

**Comment by fxzxmicah** [comment]
@realhuyang 我说了，我只是发现个问题，反馈一下而已，这个又不影响使用，也和我用绿色版还是安装版无关。

**Comment by Fndroid** [comment]
你其实可以指定为``.../Clash``而不是``.../Clash/``

**Comment by fxzxmicah** [comment]
？？我指定了`/Clash/`和`/Clash`都不行啊？
