### ISSUE TITLE
Clash for windows 导致防火墙失效

### ISSUE THREAD

**Issue by liugaocn** [Fndroid/clash_for_windows_pkg#827]
我将windows自带的防火墙设置为了阻止任何程序联网，只允许少部分应用联网。不过我最近发现，有很多平常不允许联网的应用，可通过Clash大量的下载数据，比如更新程序，而且文件的大小很大。
希望Clash能够添加向防火墙一样的设置，只允许部分程序通过Clash联网。提供一个TXT规则文件加载选项，应该不需要消耗很多的资源。

**Comment by Fndroid** [comment]
自己设置reject规则
