### ISSUE TITLE
Proxies->Rule->自动选择，支持排除一些节点

### ISSUE THREAD

**Issue by ypji** [Fndroid/clash_for_windows_pkg#828]
**描述**
大伙都知道这是机场软件，很多服务商会提供一些国内中转节点，延迟很低，速度很快，但是流量是按倍率计算的，流量消耗特别快，所以最好能支持“自动选择”排除掉一些节点，比如按正则表达式去除`\dx`的节点

**Comment by Fndroid** [comment]
配置文件不是我提供的，你找我有什么用呢

**Comment by ypji** [comment]
服务商提供了很多选择给用户
* 港的，日的，湾的，美的
* 延迟低，速度快，但是流量按倍数计算的
* 延迟高，速度低，但是流量按0.倍数计算的

Clash自动选择节点，应该是只是选择延迟最低的节点
但是如果增加一些过滤条件呢？
比如：用户做日本生意，经常访问日本网站，他想Clash的“自动选择”只选择日本节点里面最快最稳定的。难道只能给服务商发工单，说我的订阅只给我返回日本节点？？
此时“自动选择”功能简单加一个正则表达，或子串匹配就能轻松应对。

**如果作者觉得此功能无意义，请直接删除issue**

**Comment by Fndroid** [comment]
所以你要定制配置文件不是找你的服务商么？

**Comment by xgdgsc** [comment]
给服务商提ticket了不支持，这样做他们可以更快用完你的流量，没动力这样做。

**Comment by yi-Xu-0100** [comment]
parser 处理吧，文档：<https://docs.cfw.lbyczf.com/contents/parser.html>

**Comment by RungePei** [comment]
不知道还需要不需要了，我提供下我的parser代码
```
parsers: # array
  - url: https:www.example.com
    code: |
      module.exports.parse = (raw, {yaml}) => {
        let config = yaml.parse(raw)
        config['proxies'] = config['proxies'].filter(p=>!p.name.includes("倍率"))
        config['proxy-groups'].forEach(g => {
          g['proxies'] = g['proxies'].filter(n=>!n.includes("倍率"))
        })
        return yaml.stringify(config)
      }
```

**Comment by wxupjack** [comment]
感谢 https://github.com/Fndroid/clash_for_windows_pkg/issues/828#issuecomment-1474085767 , 小改下支持更多关键词筛选
```javascript
code: |
        module.exports.parse = (raw, {yaml}) => {
          let config = yaml.parse(raw)
          let keywords = /北京|广东|上海/
          config['proxies'] = config['proxies'].filter(p=>!p.name.match(keywords))
          config['proxy-groups'].forEach(g => {
            g['proxies'] = g['proxies'].filter(n=>!n.match(keywords))
          })
          return yaml.stringify(config)
        }
```

**Comment by jackywong001** [comment]
> 感谢 [#828 (comment)](https://github.com/Fndroid/clash_for_windows_pkg/issues/828#issuecomment-1474085767) , 小改下支持更多关键词筛选
> 
> ```js
> code: |
>         module.exports.parse = (raw, {yaml}) => {
>           let config = yaml.parse(raw)
>           let keywords = /北京|广东|上海/
>           config['proxies'] = config['proxies'].filter(p=>!p.name.match(keywords))
>           config['proxy-groups'].forEach(g => {
>             g['proxies'] = g['proxies'].filter(n=>!n.match(keywords))
>           })
>           return yaml.stringify(config)
>         }
> ```

感谢分享，我复制了你的代码进去加入我不要的节点名称，更新之后还是没有变化呢，不知道是否哪里出问题，可以指导下么

**Comment by wxupjack** [comment]
> > 感谢 [#828 (comment)](https://github.com/Fndroid/clash_for_windows_pkg/issues/828#issuecomment-1474085767) , 小改下支持更多关键词筛选
> > ```js
> > code: |
> >         module.exports.parse = (raw, {yaml}) => {
> >           let config = yaml.parse(raw)
> >           let keywords = /北京|广东|上海/
> >           config['proxies'] = config['proxies'].filter(p=>!p.name.match(keywords))
> >           config['proxy-groups'].forEach(g => {
> >             g['proxies'] = g['proxies'].filter(n=>!n.match(keywords))
> >           })
> >           return yaml.stringify(config)
> >         }
> > ```
> 
> 感谢分享，我复制了你的代码进去加入我不要的节点名称，更新之后还是没有变化呢，不知道是否哪里出问题，可以指导下么

可能是竖线分隔符混淆了？中英文的不同 |｜
可以先用[RungePei](https://github.com/RungePei) 的版本，检查更新后代码能否生效。
或者放一下你的代码

**Comment by jackywong001** [comment]
> > 感谢分享，我复制了你的代码进去加入我不要的节点名称，更新之后还是没有变化呢，不知道是否哪里出问题，可以指导下么
> 
> @jackywong001 可能是竖线分隔符混淆了？中英文的不同 |｜ 可以先用[RungePei](https://github.com/RungePei) 的版本，检查更新后代码能否生效。或者放一下你的代码

多谢大佬回复我，我缩进搞错了，复制的时候多了俩空格，我试了几次已经搞好了，灰常感谢。。。

**Comment by Money001** [comment]
> 所以你要定制配置文件不是找你的服务商么？

他的意思是，clash里面可以自定义选择使用哪些节点或者禁用哪些节点。

**Comment by bkbx** [comment]
> 感谢 [#828 (comment)](https://github.com/Fndroid/clash_for_windows_pkg/issues/828#issuecomment-1474085767) , 小改下支持更多关键词筛选
> 
> ```js
> code: |
>         module.exports.parse = (raw, {yaml}) => {
>           let config = yaml.parse(raw)
>           let keywords = /北京|广东|上海/
>           config['proxies'] = config['proxies'].filter(p=>!p.name.match(keywords))
>           config['proxy-groups'].forEach(g => {
>             g['proxies'] = g['proxies'].filter(n=>!n.match(keywords))
>           })
>           return yaml.stringify(config)
>         }
> ```

感谢嘞我的哥，我就是需要剔除节点
