### ISSUE TITLE
interface-name 自动检测在存在 hyper v 虚拟交换机的环境下会失败

### ISSUE THREAD

**Issue by GhostFlying** [Fndroid/clash_for_windows_pkg#829]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
删除 tap 配置文件的 
```
experimental:
   interface-name: vEthernet (out)
```
字段后，启用 tap 模式，断网（日志里显示所有链接均失败）

**复现**
请描述复现问题的步骤:
1. hyper v 中添加虚拟交换机，类型为外部，选择物理网卡桥接
2. 使用任何不具有 interface-name 字段的 tap 配置文件即可复现

**预期行为**
正确识别到当前正确的 interface-name 为 vEthernet (out)

**Comment by Fndroid** [comment]
在群里回过了，不能自动识别出虚拟网卡作为出口
