### ISSUE TITLE
能否改进Clash的"url-test"？

### ISSUE THREAD

**Issue by 3andero** [Fndroid/clash_for_windows_pkg#83]
目测当下的url-test只会测试一次，这样就有可能把那些偶尔响应快但是平均响应速度不快的节点给选中，如果每次url-test可以多测试几次取平均响应时间，就能够避免这种情况。
不清楚这个改动是否涉及到clash的代码，但看起来在cfw里改动也能实现？
谢谢。

**Comment by Fndroid** [comment]
Clash for Windows并不能干预延迟测试流程，请到Clash仓库下反馈
