### ISSUE TITLE
Clash for Windows/win10配置界面空白

### ISSUE THREAD

**Issue by qwer12345687** [Fndroid/clash_for_windows_pkg#830]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [ x] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载
- [x ] 软件下载后未修改任何安装目录中的文件

**描述**
配置界面空白

**复现**
请描述复现问题的步骤:

**预期行为**
清晰地描述期望看到的行为

**截图**
![MMAEXN{@3}JF}C_0U$NO{CN](https://user-images.githubusercontent.com/65883301/82778786-f9150f00-9e84-11ea-9c5a-805426036639.png)

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/820
