### ISSUE TITLE
路由器网关是172.0.0开头的话会进不了路由器管理页面

### ISSUE THREAD

**Issue by catevan** [Fndroid/clash_for_windows_pkg#833]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载
- [ ] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题

**复现**
请描述复现问题的步骤:
1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
清晰地描述期望看到的行为

**截图**
如果可以，请提供对应问题的截图

**其他说明**
其他补充内容

**Comment by Paubrk** [comment]
被认为是公网ip了，如果一定要用，你需要自己在 config.yaml 增加规则。
