### ISSUE TITLE
疯狂启动命令行，造成我内存不够了！

### ISSUE THREAD

**Issue by xdeng** [Fndroid/clash_for_windows_pkg#836]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
今天刚升的最新版，疯狂启动cmd命令行进程，造成系统提示我内存不够了，系统强制结束了我一些别的进程。
退出即可释放内存。

**复现**
直接打开过一会，非常容易出现。

**截图**
![QQ截图20200528171818](https://user-images.githubusercontent.com/2641745/83123945-20c7d980-a108-11ea-9399-576317e60ddb.jpg)

**Comment by xdeng** [comment]
发现规律了刚打开一个cmd 貌似卡住了，然后随着时间的推移越来越多的cmd创建并卡住了。win7系统。

**Comment by Fndroid** [comment]
退回0.9.6

**Comment by xdeng** [comment]
> 退回0.9.6

是的，我从高到低逐个尝试，发现0.9.6就没这个问题了。

**Comment by Fndroid** [comment]
0.10.1已经修复

**Comment by tea1111980** [comment]
@xdeng 请问，你使用的是什么任务管理器，怎么还带有颜色的？

**Comment by xdeng** [comment]
> @xdeng 请问，你使用的是什么任务管理器，怎么还带有颜色的？

procexp

**Comment by tea1111980** [comment]
> > @xdeng 请问，你使用的是什么任务管理器，怎么还带有颜色的？
> 
> procexp


收到，谢谢！
