### ISSUE TITLE
建议增加 PowerShell 的一键代理命令复制

### ISSUE THREAD

**Issue by neteroster** [Fndroid/clash_for_windows_pkg#837]
**描述**
PowerShell 的运用越来越广泛，希望考虑支持 PowerShell 代理命令的一键复制。

**其他说明**
PowerShell 增加环境变量的语法[1]：
```PowerShell
$Env:<variable-name> = "<new-value>"
```

设置代理的示例（HTTP 代理）：
```PowerShell
$Env:http_proxy = "http://127.0.0.1:$port_http"
$Env:https_proxy = "http://127.0.0.1:$port_http"
```

[1] [Microsoft Docs - PowerShell - About Environment Variables](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables)

**Comment by Fndroid** [comment]
powershell不是走系统代理么

**Comment by neteroster** [comment]
@Fndroid 我这里测试不会欸，查资料似乎没有说默认走系统代理的。

**Comment by Fndroid** [comment]
我弄错了，原来是curl才会走，我看下加一下

**Comment by Fndroid** [comment]
好像cmd的命令也能用在powershell 里吧

**Comment by neteroster** [comment]
@Fndroid 应该不行，`set` 虽然不报错但是确实是没有设置环境变量的。

**Comment by AvailCat** [comment]
This will not work for most Windows-only application (exclude .NET Core 3 / .NET 5).

For .NET Framework based application, registry setting (system wide) will be used, and for PowerShell script who use "Invoke-WebRequest" you should set `[Net.WebRequest]::DefaultWebProxy`

**Comment by Fndroid** [comment]
0.10.1已经修复

**Comment by littlesmilelove** [comment]
> 0.10.1已加

如何使用呢？界面中似乎没有入口。
