### ISSUE TITLE
节点可以测速但启用后不能科学上网

### ISSUE THREAD

**Issue by Karben233** [Fndroid/clash_for_windows_pkg#838]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
订阅了节点, 在软件Proxies页面可以对节点进行测速, 点击System Proxy按钮后并没有报错, 显示是打开状态, 但使用浏览器似乎并不能科学上网. 
软件已经使用过半年了.也并不是更新最新版本后立即出现的这个问题,更新版本后可以正常使用,但用了几天突然就不行了

**复现**
请描述复现问题的步骤:
1.对节点测速,可以显示测速结果
2.点击System Proxy后并不能科学上网

**预期行为**
点击System Proxy后可以正常上网

**截图**
如果可以，请提供对应问题的截图

**其他说明**
尝试过但并没有解决问题的操作:
1.更改http端口 sock5端口
2.重装软件
3.删除 user/.config/clash文件夹
4.任务管理器里有clash-win64.exe;http://127.0.0.1:9090/可以正常访问

**不知道有没有用的说明**
使用clash启动代理后在ip查询网站上查到自己的ip还是本地ip,而使用其他软件开启代理后查询到的ip则是香港ip

**logs** 
time="2020-05-29T00:03:02+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-05-29T00:03:02+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-05-29T00:03:02+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-05-29T00:03:02+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-05-29T00:03:02+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-05-29T00:03:02+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2020-05-29T00:03:02+08:00" level=info msg="Start initial compatible provider GlobalTV"
time="2020-05-29T00:03:02+08:00" level=info msg="Start initial compatible provider Others"
time="2020-05-29T00:03:02+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-05-29T00:03:02+08:00" level=info msg="Start initial compatible provider Domestic"
time="2020-05-29T00:03:02+08:00" level=info msg="Start initial compatible provider AsianTV"
time="2020-05-29T00:03:04+08:00" level=info msg="Start initial compatible provider Domestic"
time="2020-05-29T00:03:04+08:00" level=info msg="Start initial compatible provider AsianTV"
time="2020-05-29T00:03:04+08:00" level=info msg="Start initial compatible provider GlobalTV"
time="2020-05-29T00:03:04+08:00" level=info msg="Start initial compatible provider Others"
time="2020-05-29T00:03:04+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-05-29T00:18:42+08:00" level=info msg="[TCP] 127.0.0.1:14444 --> 91.108.56.197 match IPCIDR using Proxy[[V2]Basic|香港04|2.0|NF*]"
time="2020-05-29T00:18:42+08:00" level=info msg="[TCP] 127.0.0.1:14446 --> 91.108.56.197 match IPCIDR using Proxy[[V2]Basic|香港04|2.0|NF*]"
time="2020-05-29T00:18:42+08:00" level=info msg="[TCP] 127.0.0.1:14445 --> 91.108.56.197 match IPCIDR using Proxy[[V2]Basic|香港04|2.0|NF*]"
time="2020-05-29T00:18:42+08:00" level=info msg="[TCP] 127.0.0.1:14449 --> 91.108.56.197 match IPCIDR using Proxy[[V2]Basic|香港04|2.0|NF*]"
time="2020-05-29T00:19:59+08:00" level=info msg="[TCP] 127.0.0.1:1039 --> by3302.storage.live.com match DomainSuffix using Proxy[[V2]Basic|香港04|2.0|NF*]"
time="2020-05-29T00:19:59+08:00" level=info msg="[TCP] 127.0.0.1:1041 --> api.onedrive.com match Match using Others[[V2]Basic|香港04|2.0|NF*]"
time="2020-05-29T00:20:01+08:00" level=info msg="[TCP] 127.0.0.1:1076 --> mobile.pipe.aria.microsoft.com match DomainSuffix using Domestic[DIRECT]"
time="2020-05-29T00:20:01+08:00" level=info msg="[TCP] 127.0.0.1:1077 --> mobile.pipe.aria.microsoft.com match DomainSuffix using Domestic[DIRECT]"
time="2020-05-29T00:28:34+08:00" level=info msg="[TCP] 127.0.0.1:3846 --> safebrowsing.googleapis.com match DomainKeyword using Proxy[[V2]Basic|香港04|2.0|NF*]"
time="2020-05-29T00:28:42+08:00" level=info msg="[TCP] 127.0.0.1:3954 --> 91.108.56.197 match IPCIDR using Proxy[[V2]Basic|香港04|2.0|NF*]"
time="2020-05-29T00:28:42+08:00" level=info msg="[TCP] 127.0.0.1:3955 --> 91.108.56.197 match IPCIDR using Proxy[[V2]Basic|香港04|2.0|NF*]"
time="2020-05-29T00:28:46+08:00" level=info msg="[TCP] 127.0.0.1:3959 --> v10.events.data.microsoft.com match DomainSuffix using Domestic[DIRECT]"
time="2020-05-29T00:29:04+08:00" level=info msg="[TCP] 127.0.0.1:4147 --> mobile.pipe.aria.microsoft.com match DomainSuffix using Domestic[DIRECT]"
time="2020-05-29T00:29:04+08:00" level=info msg="[TCP] 127.0.0.1:4146 --> mobile.pipe.aria.microsoft.com match DomainSuffix using Domestic[DIRECT]"
time="2020-05-29T00:29:16+08:00" level=info msg="[TCP] 127.0.0.1:4242 --> login.live.com match DomainSuffix using Proxy[[V2]Basic|香港04|2.0|NF*]"

**Comment by Karben233** [comment]
找了半天原因,发现换了一个浏览器就没问题了.原来是我浏览器里某个插件集成了谷歌访问功能,接管了我的浏览器代理,导致系统代理在浏览器上失效了...

**Comment by zy-myname** [comment]
> 

谢谢这位老哥，我本来被搞得心烦意乱的，两天了……去看了一眼插件，好家伙，上一个没关。感恩！！

**Comment by Hermann0222** [comment]
感谢老哥，同样的困扰！！

**Comment by ChuYueGrace** [comment]
感恩感恩！！我也是这个问题！

**Comment by meikuang500** [comment]
感谢！！！

**Comment by FFeiLong** [comment]
感谢老哥，同样的问题！！！
