### ISSUE TITLE
win10无法使用

### ISSUE THREAD

**Issue by rekoye** [Fndroid/clash_for_windows_pkg#842]
![image](https://user-images.githubusercontent.com/63369297/83238217-b165ee80-a1c8-11ea-888b-3f38b5aa9f12.png)

**Comment by Lan-st** [comment]
可以试试#694 的方法

**Comment by doctormin** [comment]
谢谢提醒 已试 没有解决这个报错

**Comment by Fndroid** [comment]
把home directory里的profiles文件夹删掉重启app

**Comment by doctormin** [comment]
感谢作者的回复，如果我没有理解错意思的话
- 我删除了\.config\clash\profile并重启了程序（此时便只有default config了）
- 重新填写订阅链接并下载
- 将下载到的配置文件的Rule / Proxy / Proxy Group 做了修改
- 点击配置文件，仍然报错`Cannot read property ‘put’ of null`

**Comment by Fndroid** [comment]
发下最新的log看看，看着似乎连core都没启动成功

**Comment by doctormin** [comment]
似乎是的 log我专门看了 是空的（both in the app UI and /log)

**Comment by rekoye** [comment]
> 发下最新的log看看，看着似乎连core都没启动成功

general里显示loading，应该core没启动

**Comment by YogiLai** [comment]
用管理员账号启动软件即可

**Comment by zhoudujin** [comment]
解决了吗 ?我也是这个问题

**Comment by doctormin** [comment]
还没解决 不知是哪里的问题 可以用老版本试试

**Comment by anywaySSS** [comment]
楼主解决没，我今天重装了win10 2004以后也碰到了跟你一模一样的问题。。。

**Comment by Han991212** [comment]
直接去看General里面，有提示错误log，直接点击repair就可以了（版本v0.19.23）
