### ISSUE TITLE
删除后无法重新安装？

### ISSUE THREAD

**Issue by OrangeVillage** [Fndroid/clash_for_windows_pkg#843]
由于大意，（可能）没正确卸载Clash而是手动删除了安装目录下的全部文件
![error02](https://user-images.githubusercontent.com/66137598/83293230-0e3fc400-a21e-11ea-8384-166b80ce9d24.jpg)
，造成重新安装的时候进程无法继续
![error01](https://user-images.githubusercontent.com/66137598/83293251-14ce3b80-a21e-11ea-85c1-a68e45447cca.jpg)
，请问怎么办？

**Comment by niuwadiandian** [comment]
从“设置->应用->应用和功能”是删不掉的，应该去“控制面板->程序->程序和功能”卸载。希望能帮到你。

**Comment by OrangeVillage** [comment]
> 从“设置->应用->应用和功能”是删不掉的，应该去“控制面板->程序->程序和功能”卸载。希望能帮到你。

谢谢你的关注，不过重点不是无法卸载，而是Clash无法安装了

**Comment by niuwadiandian** [comment]
你试过吗？如果没有可以尝试一下，会有惊喜。不能安装可能是因为安装程序发现系统中已经有了这个软件，但是到目录里却找不到，懵了。

**Comment by OrangeVillage** [comment]
> 你试过吗？如果没有可以尝试一下，会有惊喜。不能安装可能是因为安装程序发现系统中已经有了这个软件，但是到目录里却找不到，懵了。所以要先卸载干净

好滴，我这就去试试，谢谢~

**Comment by niuwadiandian** [comment]
> > 你试过吗？如果没有可以尝试一下，会有惊喜。不能安装可能是因为安装程序发现系统中已经有了这个软件，但是到目录里却找不到，懵了。所以要先卸载干净
> 
> 好滴，我这就去试试，谢谢~

问题可以解决吗？
