### ISSUE TITLE
未勾选Auto Launch,开机数分钟后自动启动了Clash for Windows客户端。

### ISSUE THREAD

**Issue by wangzp0303** [Fndroid/clash_for_windows_pkg#85]
之前用过开机自启挺好用的，后来订阅到期了没有续订就取消勾选了。
目前System Proxy和Auto Launch都没有勾选。
Windows10任务管理器的启动选项卡中没有Clash，启动文件夹内没有Clash，计划任务程序没有找到和Clash相关的。
但是我现在开机数分钟(具体几分钟我没有统计过)后，Clash客户端会自己弹出来。
任务栏里面的自启动程序都是我设置的，只有这个是我勾掉了自动启动还是会弹出来的。
log文件没有异常之类的信息，都只是启动成功。

**Comment by Fndroid** [comment]
软件自带的自启动是通过注册表实现的，具体路径如下：
``HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run``

请检查底下Clash for Windows对应的数值是否为空，为空即不会自动启动

**Comment by wangzp0303** [comment]
看了一下是空的。搞不清除是怎么回事，只能先卸载了，等有需要再装回来吧。

**Comment by Fndroid** [comment]
软件只有这一种启动途径，如果确定为空。可以考虑是否被其他软件启动，此issue将被关闭，如有需要请reopen，感谢
