### ISSUE TITLE
【功能建议】希望加入右键菜单，右击节点时可以查看/编辑节点详情

### ISSUE THREAD

**Issue by leic4u** [Fndroid/clash_for_windows_pkg#852]
**描述**
目前各个策略组的节点卡片中，只显示了节点别名/类型/延迟，无法查看节点服务器地址/端口等节点详情，希望可以加入右键菜单，右击节点弹出菜单，提供查看/编辑节点详情功能。

**其他说明**
暂无

**Comment by Fndroid** [comment]
不是什么高频操作，现有编辑器已经能完成

**Comment by leic4u** [comment]
@Fndroid 现在要查看节点信息的时候必须要从Proxies转到Profiles，再点击编辑配置文件通过编辑器打开，最后再搜索节点关键字，对于只想看一眼节点信息的情况来说，着实有点麻烦了。

**Comment by Fndroid** [comment]
节点信息有什么是经常看的吗

**Comment by leic4u** [comment]
@Fndroid 我自己有个场景，我的机场订阅比较多，通过sub-conventor都合到一个配置文件里面了，有些时候节点出问题了，不知道这个节点属于哪个订阅。
所以对于多个订阅合到同一个配置文件的情况，可以方便查看这个节点属于哪个订阅，因为有时单凭名称不一定看得出来，得结合地址查看属于哪个订阅。
（配置文件里新增参数用于识别订阅地址这个，我也给sub-conventor的开发者也提了个建议ISSUE）

另外，点击查看单个节点的更多信息，同时提供编辑功能，可以简化很多写配置文件代码的操作。
后期还可以考虑加入不通过写配置文件来使用CFW的方式，比如CFW内置一套路由规则，在内置的某个策略组下面可以新增单个节点，这样可以让很多整不动配置文件的小白快速上手CFW。
（我就是学了好几天配置文件的写法，还是会写错，就用sub-conventor生成了自己再改。。。）

**Comment by Fndroid** [comment]
我不觉得单独编辑节点有任何意义，因为它依赖于规则和策略。

内置规则，方便小白这些都不会做。

**Comment by leic4u** [comment]
@Fndroid 好的，了解
