### ISSUE TITLE
出现奇怪的问题无法解释，回退版本即可解决，具体信息看里面

### ISSUE THREAD

**Issue by Ivy233** [Fndroid/clash_for_windows_pkg#854]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在，而且仅最新版本（0.9.11）出现该问题。
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
症状大概如下：

- 任何网页都会卡一阵子。
- favcion.ico要转半分钟左右的圈才可以自由点击，在这之前什么事情都做不了（已缓存的似乎没问题）。时间有可能会长到报页面没有响应。
- bilibili视频无法观看。smzdm.com网站无法打开。
- 已经重复安装过本软件，而且清空过**全部**文件。
- 测试发现仅0.9.11出现该症状，回退0.9.10症状消失。

系统信息：

- Windows版本：20.04（19041.264）
- Edge版本（Chromium）：83.0.478.37
- Edge Beta版本：忘记看版本号了，反正是当时的最新（不如推到85试试？）
- IE：直接用Win10自带的IE，没有更新过。
- 机器型号：LG gram 2019 i5版本

其他情况：似乎没啥发现，CPU和内存占用正常的，但是网络走不动

**复现**

- 不需要啥操作，按照描述内容把0.9.11安装上去就行

**截图**
需要截图的话我补就行了= =（懒）

**其他说明**
没啥补充的，还要信息的话直接问就是

**Comment by ShadowLyin** [comment]
你的配置文件包含 DNS 字段么？
我也有过这个问题，更换了 DNS 就解决了，或者你直接删除 DNS 字段试试。

**Comment by Ivy233** [comment]
DNS字段才看，是没有的= =
不过现在用11.x了，问题已经消失。。。
