### ISSUE TITLE
0.9.11版本对于profile文件Edit rules或edit policys进去后为空白

### ISSUE THREAD

**Issue by deardamon** [Fndroid/clash_for_windows_pkg#855]
**信息**
问题主要存在于最新版本0.9.11，只测试了退回0.9.6版本正常，相同的yml文件。
- [X ] 已经尝试更新到最新版本，问题依旧存在
- [X ] 软件从本仓库下载
- [X ] 软件下载后未修改任何安装目录中的文件

**描述**
0.9.11版本对于profile文件Edit rules或edit policys进去后为空白，规则实际上应该是生效的，只是无法直接在软件中编辑规格或策略。
OS: windows 10

**截图**
![image](https://user-images.githubusercontent.com/52314134/83479923-87fcd980-a4cc-11ea-8496-bc36eb77b64b.png) 
从这里进入，
![image](https://user-images.githubusercontent.com/52314134/83480017-ce523880-a4cc-11ea-9fd9-392e1d893d1e.png)

在0.9.6版本显示正常。
![image](https://user-images.githubusercontent.com/52314134/83480072-fd68aa00-a4cc-11ea-8795-63ebcc08aad5.png)

**Comment by Fndroid** [comment]
Duplicate of https://github.com/Fndroid/clash_for_windows_pkg/issues/694
