### ISSUE TITLE
clash和qq浏览器不兼容，clash打开之后打开qq浏览器的应用中心不能显示完整同时侧边栏不能联网，关闭clash之后就正常显示。

### ISSUE THREAD

**Issue by lyuinc** [Fndroid/clash_for_windows_pkg#858]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载
- [ ] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题

**复现**
请描述复现问题的步骤:
1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
清晰地描述期望看到的行为

**截图**
如果可以，请提供对应问题的截图

**其他说明**
其他补充内容

**Comment by time-byte** [comment]
###  抓包 分流

**Comment by ted423** [comment]
你开的什么模式，看过log么，别最后发现开了全局？
