### ISSUE TITLE
添加 TAP 设备卸载功能

### ISSUE THREAD

**Issue by shellqiqi** [Fndroid/clash_for_windows_pkg#859]
**描述**
可以在主界面选择卸载 TAP 设备。

**其他说明**
使用场景：开发软件使用内网机器，配置文件内有 NAT 穿透规则，环境切换后，部分私有地址的 NAT 穿透需要取消，卸载 TAP 设备。
另外 WSL2 与 Proxifier 冲突，切换时需要重置 winsock，故只能使用 TAP 设备进行代理。

**Comment by Fndroid** [comment]
0.10.1已经修复
