### ISSUE TITLE
could not run clash core

### ISSUE THREAD

**Issue by DESMOND1235** [Fndroid/clash_for_windows_pkg#862]
logs:
time="2020-06-04T00:41:24+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-06-04T00:41:24+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-06-04T00:41:24+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-06-04T00:41:24+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-06-04T00:41:24+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2020-06-04T00:41:24+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"

谢谢！

**Comment by DESMOND1235** [comment]
版本是0.9.11

**Comment by Fndroid** [comment]
config.yaml删掉重启app

**Comment by DESMOND1235** [comment]
感谢答复，按您说的操作之后还是一样的情况。以下是最新的log

time="2020-06-04T13:07:38+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-06-04T13:07:38+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-06-04T13:07:38+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-06-04T13:07:38+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-06-04T13:07:38+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2020-06-04T13:07:38+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"

**Comment by Fndroid** [comment]
你这个日志是没问题的，只能是配置文件格式问题，确定删掉了.clash/config.yaml文件了么

**Comment by DESMOND1235** [comment]
确定删除了.clash/config.yaml文件
昨天整个删除了.clash目录，重装最新版软件，结果都没有改变。
尝试其他软件翻墙也出现了问题。
近期我曾在c盘删除一些其他文件，大概自那之后clash就出现了现在的情况。是不是有所关联？
