### ISSUE TITLE
CFW 无法处理 JSON 格式的订阅

### ISSUE THREAD

**Issue by KuterAlaska** [Fndroid/clash_for_windows_pkg#863]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题
为了方便起见服务端采用的是 JSON 格式的 Clash 订阅，查阅资料发现 YAML 是 JSON 的超类，也就是 YAML 解释器一般都支持解析 JSON，经过测试在 ClashX 和 Clash for Android 上都可以完美解析 JSON 格式的订阅，然而在 Clash for Windows 上增加订阅之后点击编辑订阅按钮，弹出的文件内容是 `[Object object]`，也无法和使用查看任何订阅中的代理

**复现**
请描述复现问题的步骤:
1. 进入Profiles
2. 粘贴订阅链接
3. 点击对应订阅的编辑按钮
4. 弹出的文件内容是 `[Object object]`

**预期行为**
弹出的文件内容应该是完整的 JSON 文件，或是 Clash for Windows 处理后的 YAML 格式文件

**截图**
如果可以，请提供对应问题的截图
暂无，抱歉

**其他说明**
其他补充内容
JSON 的订阅格式如下
```jsonc
{
  "proxies": [{
    "type": "ss",
    "server": "xxxx.com",
    // More specifications
  },
  {
    // Server 2
  }],
  "proxy-group": [{
    // Proxy Group 1
  },
  {
    // Proxy Group 2
  }],
  "Rule": [{
    // Here comes the rules
  }]
}
```
以上 JSON 格式在 ClashX 和  Clash for Android 上测试可用

**Comment by Fndroid** [comment]
你这几个字段的key就不对，proxy-groups、rules

**Comment by KuterAlaska** [comment]
> 你这几个字段的key就不对，proxy-groups、rules

感谢指正，一时没写对
但是即便是改成 proxy-groups 和 rules ，依旧不能用 JSON 格式的订阅

**Comment by Fndroid** [comment]
能切换么，报什么错

**Comment by KuterAlaska** [comment]
不能切换，没有明显报错，表现就是手动编辑规则后弹出的文件内容是 `[Object object]`，Proxy里无任何代理可见

**Comment by Fndroid** [comment]
截个图看看吧，我试了JSON是没问题的。

**Comment by KuterAlaska** [comment]
是的，我测试了下，手动创建一个 JSON 文件 CFW 是能解析的，但是拉取一个 JSON 格式的订阅文件就会复现这样的问题，我觉得应该是下载的处理上可能出了点问题

https://github.com/KuterAlaska/Test9r8y289y/releases/download/v1.0/test.json

这是个测试用的配置，如果手动把这个配置里的内容手动复制到 CFW 的配置里，是可以正常使用的；但是如果直接把这个链接填到订阅地址栏里并下载，最后手动编辑这个订阅会发现内容只有 `[Object object]`

**Comment by Fndroid** [comment]
0.10.1已经修复

**Comment by Utaea** [comment]
v0.14.x 中似乎这个 bug 被重新引入了，v0.13.5 上可以正常使用，升级到 v0.14.x 之后又出现下载订阅失败，打开订阅文件内容为 [Object object] 的情况

**Comment by Fndroid** [comment]
@Utaea 这是上游axios的问题 https://github.com/axios/axios/issues/907
