### ISSUE TITLE
tap模式下在启动clash后,对不需要外部访问的程序网络造成了影响?

### ISSUE THREAD

**Issue by zqr95518** [Fndroid/clash_for_windows_pkg#864]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
本地进行java程序开发，且程序本身未访问任何除了192.168.*.*和10.*.*.*以外的IP(有一部分通过了host但是本身IP也在这个范围内)。
在程序启动前运行clash(tap模式)，程序运行正常，这时候关闭clash，程序本身所有的访问都会中断一段时间。
在程序启动后运行clash，对程序没有造成任何影响。

**复现**
请描述复现问题的步骤:
1. 运行clash(tap模式)
2. 运行一个spring boot web应用
3. 关闭clash
4. 应用本身进行网络访问

**预期行为**
不管在程序启动在clash启动的前后，clash关闭对只进行本地访问程序不应该造成任何影响。

**截图**
如果可以，请提供对应问题的截图

**其他说明**
这个影响可能是有几秒到十几秒网络就会恢复，但是在clash启动前启动程序就完全不会受到影响。
是不是可以给clash配一个全局的进程白名单，和profile分离？这样就不会在更新profile的时候总是去重新编辑了。

**Comment by Fndroid** [comment]
> 程序本身所有的访问都会中断一段时间。

是指本地服务器127.0.0.1访问不了么？还是说这个Java程序请求不了其他网站？

**Comment by zqr95518** [comment]
这个程序本身访问不了其他的192.168.*.*的IP了，别人也访问不了他

**Comment by Fndroid** [comment]
理论上不会影响这个，因为192.168.0.0/8一般都在路由表里，不会被tap网卡的路由命中的

**Comment by zqr95518** [comment]
clash不关闭没有影响，在clash启动前启动的程序也没有影响，但是clash启动后启动的程序在我退出的时候影响到了。
