### ISSUE TITLE
Clash无法正常工作

### ISSUE THREAD

**Issue by OrangeVillage** [Fndroid/clash_for_windows_pkg#865]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
启动Clash后进入General画面无限Loading。Proxies和Profiles界面里无有效内容。从URL下载Profile报错。

**复现**
请描述复现问题的步骤:
同描述

**预期行为**
我另一台电脑里的Clash是这样的，所以我知道新版在正常工作下应该是什么样子：
![normal](https://user-images.githubusercontent.com/66137598/83725373-68a0b080-a674-11ea-9719-4d24134a309c.jpg)
![normal'](https://user-images.githubusercontent.com/66137598/83725380-6c343780-a674-11ea-8acf-ff9c18fc0d0d.jpg)
![normal''](https://user-images.githubusercontent.com/66137598/83725384-6f2f2800-a674-11ea-92e6-b2236d7a4a01.jpg)

**截图**
而这本电脑中显示出的结果是这样的：
![error01](https://user-images.githubusercontent.com/66137598/83725445-89690600-a674-11ea-9798-29583b136bb8.jpg)
![error03](https://user-images.githubusercontent.com/66137598/83725469-91c14100-a674-11ea-84fd-136b855fdcf2.jpg)
![error04](https://user-images.githubusercontent.com/66137598/83725476-94239b00-a674-11ea-84e5-d6e6b5310390.jpg)
把URL粘贴进去后点Download后报这个错误：
![error02](https://user-images.githubusercontent.com/66137598/83725567-bae1d180-a674-11ea-86f7-634ead367456.jpg)

**其他说明**
本机曾安装过一个早期版本Clash，版本号忘了，直接覆盖安装了0.9.11版，结果成了这样

**Comment by OrangeVillage** [comment]
追加：控制面板里卸载后重装问题不能解决。

**Comment by Fndroid** [comment]
点左下角**Connected**，进入目录后返回上一级，清空所有内容，重启app
