### ISSUE TITLE
ERROR :Updating GeoIP is not allowed in CFW,please do it manually

### ISSUE THREAD

**Issue by yanghaigang** [Fndroid/clash_for_windows_pkg#869]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [ X] 已经尝试更新到最新版本，问题依旧存在
- [ X] 软件从本仓库下载
- [ X] 软件下载后未修改任何安装目录中的文件

**描述**
更新geoip database 标题所示问题

**复现**
请描述复现问题的步骤:
1. 进入clash for windows的general 
2. 点击geoip database 
3.触发问题

**预期行为**
更新数据库到最新日期

**截图**
如果可以，请提供对应问题的截图
![Uploading 83831554...]()
**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
暂时禁止了，因为有上游的bug
