### ISSUE TITLE
说来奇怪。只有网易云音乐这个UWP不能正常联网

### ISSUE THREAD

**Issue by wingchaos** [Fndroid/clash_for_windows_pkg#87]
已经在UWP loopback里面添加全部了。。只有网易云音乐不能正常。。其他UWP没问题。不知道是不是我自己的节点问题。。emmm
其他大佬们会酱紫咩。

**Comment by Fndroid** [comment]
@wingchaos https://github.com/Fndroid/clash_for_windows_pkg/wiki/UWP%E5%BA%94%E7%94%A8%E8%81%94%E7%BD%91
