### ISSUE TITLE
0.10.1 版本不提供绿色版了吗？

### ISSUE THREAD

**Issue by realhuyang** [Fndroid/clash_for_windows_pkg#870]
我没有看到。

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/83832142-8bd26b00-a71b-11ea-84ad-34cab65a272a.png)

**Comment by WarrenChan1027** [comment]
我用7-Zip解压那个exe文件，解压后运行不了，里面只有一个uninstall.exe是可执行文件。
