### ISSUE TITLE
[功能建议]clash for windows mac版本功能建议

### ISSUE THREAD

**Issue by UntaggedRui** [Fndroid/clash_for_windows_pkg#871]
**描述**
请具体并清楚地描述期望功能及期望的效果
没想到有一天CFW竟然支持mac版本了！非常喜欢CFW的General页面和Logs页面，于是在知道后立即尝试使用了，目前觉得有几点希望能改进下。
1. 希望在运行时在dock栏中不要显示这个图标。
![tD7WnO.png](https://s1.ax1x.com/2020/06/05/tD7WnO.png)
2. 希望在任务栏中能够显示上传下载速度。图为clashx的效果。（如果能只显示通过代理的速度而不现实直连的速度那就更好了，不过这似乎是clash core的内容而你无法做到？这个做不到没关系。）
![tDHXxx.png](https://s1.ax1x.com/2020/06/05/tDHXxx.png)
3. 希望能像clashx一样方便地切换节点和不同的配置文件。
![tD7INd.png](https://s1.ax1x.com/2020/06/05/tD7INd.png)
![tDb1Wn.png](https://s1.ax1x.com/2020/06/05/tDb1Wn.png)
4. 回头一看发现提的好多建议都是clashx中有的功能，，，希望不要介意。喜欢CFW的原因是因为第一次使用clash就用的CFW，有感情了。所以有了mac版的非常支持。
**其他说明**
其他补充内容
祝工作顺利，软件用户越来越多！

**Comment by jarvanh** [comment]
windows 版本表示也想要😄

**Comment by Fndroid** [comment]
1. 不明白为什么要去掉
2. 下个版本会加
3. 不会做

**Comment by UntaggedRui** [comment]
1. 因为长期占用在那里占用dock栏位置，程序入口可以从任务栏进去。就如同windows中后台运行的程序只在右下角有显示但是任务栏没有显示。不做也没关系。
2. 感谢，期待。
3. 没关系。
再次感谢您的回复！
