### ISSUE TITLE
最新版没有windows压缩包

### ISSUE THREAD

**Issue by Sentsuki** [Fndroid/clash_for_windows_pkg#872]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
请问windows压缩包（便携模式）之后是不是不发布了，要靠自己编译了吗？最新版下载页面没有压缩包。

**Comment by Sentsuki** [comment]
我是小聋瞎

**Comment by WarrenChan1027** [comment]
请问压缩包版本在哪下载？我下了只有exe版本的，解压好像不行。另外一个是dmg，解压后是macOS的app文件夹程序来的。请问Windows版本的压缩包在哪？

**Comment by Sentsuki** [comment]
> 请问压缩包版本在哪下载？我下了只有exe版本的，解压好像不行。另外一个是dmg，解压后是macOS的app文件夹程序来的。请问Windows版本的压缩包在哪？

exe解压覆盖即可。主流压缩软件都可以。
