### ISSUE TITLE
[BUG]无法更新Goeip

### ISSUE THREAD

**Issue by Lighsark** [Fndroid/clash_for_windows_pkg#874]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [ ] 软件下载后未修改任何安装目录中的文件

**描述**
无法更新Goeip
之前版本正常

**复现**

**预期行为**
正常更新Goeip

**截图**
![image](https://user-images.githubusercontent.com/40225316/83868759-08863900-a75e-11ea-8931-8e8fddbe64fa.png)

**其他说明**

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/869
