### ISSUE TITLE
无法通过CFW编辑配置文件

### ISSUE THREAD

**Issue by szl0834** [Fndroid/clash_for_windows_pkg#875]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
无法通过CFW编辑profile，点击edit policy和edit rules 出来的界面是空的，做出的任何修改均不能保存。这个问题应该是近两个版本才出现的，我的另一台机器上安装的老版本（0.9.6）并没有这个问题。

**复现**
请描述复现问题的步骤:
1. 进入'profile'
2. 点击'edit rules'
4. 触发问题

**截图**
![2020-06-05](https://user-images.githubusercontent.com/16066867/83878635-0a0c2d00-a76f-11ea-86c1-f67d8ff63588.png)

**Comment by Fndroid** [comment]
发issue前建议先搜索下，https://github.com/Fndroid/clash_for_windows_pkg/issues/694
