### ISSUE TITLE
有个小小的问题，偶然性会出现

### ISSUE THREAD

**Issue by DragonLie** [Fndroid/clash_for_windows_pkg#879]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题
安装后win10设置-卸载应用里出现两个Clash For Windows
**复现**
请描述复现问题的步骤:
不一定出现 不知道触发机制是什么

**预期行为**
清晰地描述期望看到的行为

**截图**
https://i.ibb.co/6P8d5mD/QQ-20200606104940.png
**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
这个应该是上游electron的问题
