### ISSUE TITLE
不能使用远程配置

### ISSUE THREAD

**Issue by Maxith** [Fndroid/clash_for_windows_pkg#88]
错误图片如下:
![](https://i.loli.net/2019/03/19/5c90533e86b72.png)
LOG如下:
time="2019-03-19T10:19:23+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2019-03-19T10:19:23+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2019-03-19T10:19:23+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2019-03-19T10:19:23+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
2019/03/19 10:19:23 http: panic serving 127.0.0.1:60606: runtime error: invalid memory address or nil pointer dereference
goroutine 25 [running]:
net/http.(*conn).serve.func1(0xc000050e60)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/server.go:1746 +0xd7
panic(0x800f40, 0xb8ef60)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/panic.go:513 +0x1c7
github.com/Dreamacro/clash/adapters/outbound.NewSelector(0xc000233cb8, 0x5, 0xc00030f000, 0x8e, 0x100, 0x8e, 0x100, 0x0)
	/home/travis/gopath/src/github.com/Dreamacro/clash/adapters/outbound/selector.go:67 +0x77
github.com/Dreamacro/clash/config.parseProxies(0xc000166200, 0xc000042780, 0x0, 0x0)
	/home/travis/gopath/src/github.com/Dreamacro/clash/config/config.go:277 +0x1464
github.com/Dreamacro/clash/config.Parse(0xc00001c700, 0x34, 0xc000154750, 0x0, 0x0)
	/home/travis/gopath/src/github.com/Dreamacro/clash/config/config.go:124 +0xc4
github.com/Dreamacro/clash/hub/executor.ParseWithPath(0xc00001c700, 0x34, 0x8791e6, 0x5, 0xbb8e80)
	/home/travis/gopath/src/github.com/Dreamacro/clash/hub/executor/executor.go:20 +0x3c
github.com/Dreamacro/clash/hub/route.updateConfigs(0x8e6760, 0xc0001ae000, 0xc000166100)
	/home/travis/gopath/src/github.com/Dreamacro/clash/hub/route/configs.go:93 +0x124
net/http.HandlerFunc.ServeHTTP(0x894f38, 0x8e6760, 0xc0001ae000, 0xc000166100)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/server.go:1964 +0x4b
github.com/go-chi/chi.(*Mux).routeHTTP(0xc000042480, 0x8e6760, 0xc0001ae000, 0xc000166100)
	/home/travis/gopath/pkg/mod/github.com/go-chi/chi@v3.3.3+incompatible/mux.go:424 +0x240
github.com/go-chi/chi.(*Mux).routeHTTP-fm(0x8e6760, 0xc0001ae000, 0xc000166100)
	/home/travis/gopath/pkg/mod/github.com/go-chi/chi@v3.3.3+incompatible/mux.go:368 +0x4f
net/http.HandlerFunc.ServeHTTP(0xc00003e0a0, 0x8e6760, 0xc0001ae000, 0xc000166100)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/server.go:1964 +0x4b
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc000042480, 0x8e6760, 0xc0001ae000, 0xc000166100)
	/home/travis/gopath/pkg/mod/github.com/go-chi/chi@v3.3.3+incompatible/mux.go:69 +0x456
github.com/go-chi/chi.(*Mux).Mount.func1(0x8e6760, 0xc0001ae000, 0xc000166100)
	/home/travis/gopath/pkg/mod/github.com/go-chi/chi@v3.3.3+incompatible/mux.go:291 +0xfc
net/http.HandlerFunc.ServeHTTP(0xc000004220, 0x8e6760, 0xc0001ae000, 0xc000166100)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/server.go:1964 +0x4b
github.com/go-chi/chi.(*Mux).routeHTTP(0xc000042300, 0x8e6760, 0xc0001ae000, 0xc000166100)
	/home/travis/gopath/pkg/mod/github.com/go-chi/chi@v3.3.3+incompatible/mux.go:424 +0x240
github.com/go-chi/chi.(*Mux).routeHTTP-fm(0x8e6760, 0xc0001ae000, 0xc000166100)
	/home/travis/gopath/pkg/mod/github.com/go-chi/chi@v3.3.3+incompatible/mux.go:368 +0x4f
net/http.HandlerFunc.ServeHTTP(0xc00003e060, 0x8e6760, 0xc0001ae000, 0xc000166100)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/server.go:1964 +0x4b
github.com/Dreamacro/clash/hub/route.authentication.func1(0x8e6760, 0xc0001ae000, 0xc000166100)
	/home/travis/gopath/src/github.com/Dreamacro/clash/hub/route/server.go:87 +0x215
net/http.HandlerFunc.ServeHTTP(0xc000004100, 0x8e6760, 0xc0001ae000, 0xc000166100)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/server.go:1964 +0x4b
github.com/go-chi/cors.(*Cors).Handler.func1(0x8e6760, 0xc0001ae000, 0xc000166100)
	/home/travis/gopath/pkg/mod/github.com/go-chi/cors@v1.0.0/cors.go:199 +0xf9
net/http.HandlerFunc.ServeHTTP(0xc000004120, 0x8e6760, 0xc0001ae000, 0xc000166100)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/server.go:1964 +0x4b
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc000042300, 0x8e6760, 0xc0001ae000, 0xc000184100)
	/home/travis/gopath/pkg/mod/github.com/go-chi/chi@v3.3.3+incompatible/mux.go:81 +0x29a
net/http.serverHandler.ServeHTTP(0xc000192000, 0x8e6760, 0xc0001ae000, 0xc000184100)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/server.go:2741 +0xb2
net/http.(*conn).serve(0xc000050e60, 0x8e6e20, 0xc000054580)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/server.go:1847 +0x64d
created by net/http.(*Server).Serve
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/server.go:2851 +0x2fc

**Comment by Fndroid** [comment]
使用的是什么版本？

**Comment by Maxith** [comment]
> 使用的是什么版本？

dlercloud机场提供的修改版,版本号是0.5.21.0

**Comment by Fndroid** [comment]
先更新版本吧
    	
    	

    	Fndroid
    
  




On Wed, Mar 20, 2019 at 9:11 AM +0800, "Maxith chou" <notifications@github.com> wrote:














使用的是什么版本？





dlercloud机场提供的修改版,版本号是0.5.21.0

**Comment by Maxith** [comment]
> 先更新app

OK,更新到0.5.30后解决问题...
