### ISSUE TITLE
更新Profiles时使用当前使用的Profile网络环境更新

### ISSUE THREAD

**Issue by GainSury** [Fndroid/clash_for_windows_pkg#880]
**描述**
更新某个Profiles时使用当前使用Profile的定义的网络进行更新，直连网络可能无法连接网络

**Comment by Fndroid** [comment]
我大概不会把这个改为默认行为，除非Windows和Electron其中一方更新使得Electron内请求会跟随系统代理。

如果你需求强烈，可以尝试下使用TAP模式，接管几乎所有网络请求，自然就包括CFW本身的。
