### ISSUE TITLE
cfw-profile-parsers可以变相实现rules部分分离吗？

### ISSUE THREAD

**Issue by abae136ab** [Fndroid/clash_for_windows_pkg#881]
cfw-profile-parsers:
  - url: https://example.com/profile.yaml
  - code: |
      module.exports.parse = async (raw, {  yaml  }) => {
        const obj = yaml.parse(raw)
        return yaml.stringify(obj)
      }
不知道是否可以将rules写入yaml文件，code内获取后后直接输出，变相实现rules分离订阅？
配置文件预处理的机制是追加到profiles内吗？
谢谢！

**Comment by Fndroid** [comment]
当配置文件触发刷新（包括自动更新）时，CFW会调用此方法对下载的配置文件内容进行处理，再写入本地文件中

**Comment by abae136ab** [comment]
> 当配置文件触发刷新（包括自动更新）时，CFW会调用此方法对下载的配置文件内容进行处理，再写入本地文件中
写入哪个配置文件？是覆盖？还是追加？还是？

**Comment by Fndroid** [comment]
1. 从url下载配置文件内容，字符串
2. 调用praser处理
3.存入对应profiles里

**Comment by abae136ab** [comment]
> * 从url下载配置文件内容，字符串
> * 调用praser处理
> * 存入对应profiles里
看起来能实现我说的rules分离，我试试吧，谢谢。
这个存入，是追加还是覆盖呢？

**Comment by abae136ab** [comment]
> * 从url下载配置文件内容，字符串
> * 调用praser处理
> * 存入对应profiles里

存入对应的profiles，是指的下载A.yaml处理后存为对应的xxxx.yaml，而不是追加或者覆盖到当前使用的yaml？

**Comment by Fndroid** [comment]
要是不能理解的话，随便写一个试试不是更快知道吗？

**Comment by abae136ab** [comment]
> 要是不能理解的话，随便写一个试试不是更快知道吗？

试过了，没看出效果所以才问的…第一时间就试了
