### ISSUE TITLE
是否可以考虑增加前置代理选项

### ISSUE THREAD

**Issue by dfc643** [Fndroid/clash_for_windows_pkg#882]
**描述**
在一些公司网络是需要设置前置代理才能上网的，即 Clash 作为二级代理使用，能否考虑增加前置代理功能？

**其他说明**
其他补充内容

**Comment by flyingwhitewhale** [comment]
clash 已经支持relay功能，变相实现前置代理了

**Comment by abae136ab** [comment]
> clash 已经支持relay功能，变相实现前置代理了

clash的relay怎么用能变相实现前置代理？
