### ISSUE TITLE
无法更新GeoIP

### ISSUE THREAD

**Issue by AsunaKazuto** [Fndroid/clash_for_windows_pkg#885]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
无法更新GeoIP Database。

**截图**
![屏幕截图(3)](https://user-images.githubusercontent.com/32733404/84022470-e3d9cd80-a9b8-11ea-9e46-9a0df8813713.png)

**其他说明**
Clash For Windows 版本：0.10.1
Windows 10 版本号：1909

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/874
