### ISSUE TITLE
0.9.6 , 0.10.1 win10 2004 经常假死。

### ISSUE THREAD

**Issue by MRDHR** [Fndroid/clash_for_windows_pkg#888]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
如题，在win10 2004经常假死，使用0.10.1版本甚至出现刚刚启动不到一分钟就假死(必须任务管理器里关掉进程)，程序里点击任何位置无反应。

**复现**
请描述复现问题的步骤:
1. 启动Clash（管理员权限或非管理员权限）
2. 等待30秒左右
3. 触发卡死

**预期行为**
期望win10 2004版不会出现假死的现象。

**截图**
如果可以，请提供对应问题的截图

**其他说明**
目前回退到0.8.9版本没有出现该问题。

**Comment by xy9860** [comment]
我也有类似情况，cfw主界面打开一片空白。我还以为我电脑配置不行，毕竟公司电脑，家里没有出现过。后来我连任务管理器打开都看不见进程，一开cfw系统就好像卡死了一样，但是别的应用程序还是正常使用的。最后我打算把cfw复制到ssd运行，发现复制失败，提示主程序无法访问，我重新下载删掉原来的，暂时好像没事了。我经常会长时间运行cfw

**Comment by ted423** [comment]
我这似乎不会，最近新装的2004

**Comment by wulifuji** [comment]
日志上说是udp问题，面板上有“找不到核心”、“找不到某个文件（不要问哪个，我给忘了）”两个问题间接发生，在开机第一次启动时总是出现这个问题，尚未尝试重装，待试验。。。

**Comment by xy9860** [comment]
我一直都把日志关了，我打开看看

**Comment by wulifuji** [comment]
> 日志上说是udp问题，面板上有“找不到核心”、“找不到某个文件（不要问哪个，我给忘了）”两个问题间接发生，在开机第一次启动时总是出现这个问题，尚未尝试重装，待试验。。。

重装后恢复，假死应该是内存问题，与本问题无关

**Comment by guozijianjijiu** [comment]
这个软件会不会自动更新的吗。还是每次都要下载新的安装包

**Comment by ted423** [comment]
> 这个软件会不会自动更新的吗。还是每次都要下载新的安装包

1. out of topic
2. 很简单就能确认的问题。
