### ISSUE TITLE
yml配置文件中，规则字段key错误

### ISSUE THREAD

**Issue by cyanlink** [Fndroid/clash_for_windows_pkg#889]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载
- [x ] 软件下载后未修改任何安装目录中的文件

**描述**
yaml区分大小写，目前0.10.1版CFW，识别配置文件中的“rules” key，增删规则等均是在此key对应的列表中操作，但是，CFW识别的其他的字段，如Proxy、Proxy Group并未遵循[Clash原版yaml文档](https://github.com/Dreamacro/clash#config)，（应为proxy、proxy-group，全小写、横杠分割）。
而有些工具以及提供Clash配置文件的机场，将路由规则放在“Rule”字段下（这遵循的是[CFW的文档](https://docs.cfw.lbyczf.com/contents/configfile.html)），而这个字段实际不会被CFW识别。
文档与程序实际行为不一致。

**复现**
请描述复现问题的步骤:
1. 我使用的飞机场为npsboost，它最近新增了Clash配置文件的选项。
2. 从npsboost获取的yml，其规则字段使用的是“Rule”作为key
3. 这些规则不会被CFW识别。因为现版本CFW只识别“rules”字段。
4. 之前版本的CFW，凭记忆应该是会识别“Rule”，有待确认。
不清楚这是CFW的问题，还是这些配置文件提供者的问题。

**预期行为**
清晰地描述期望看到的行为

**截图**
如果可以，请提供对应问题的截图

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
Duplicate of https://github.com/Fndroid/clash_for_windows_pkg/issues/694
