### ISSUE TITLE
请问 Logs 显示的这个是个什么东西

### ISSUE THREAD

**Issue by juzi214032** [Fndroid/clash_for_windows_pkg#890]
**描述**
![image](https://user-images.githubusercontent.com/38206169/84181671-d6f1d280-aabb-11ea-9461-f108702f45ec.png)
这个请求没显示域名，也不知道是什么软件发起的请求
是 CFW 的 bug 吗？

**Comment by Fndroid** [comment]
就告诉你tcp连接到某个ip的时候超时了，对你访问没影响就忽略它。

**Comment by juzi214032** [comment]
好的，感谢解答
