### ISSUE TITLE
开启tap模式我的wifi图标变成了端口图标 然后我重新安装tap模式 wifi图标就没变了 这有什么区别吗

### ISSUE THREAD

**Issue by sekongy** [Fndroid/clash_for_windows_pkg#891]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载
- [ ] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题

**复现**
请描述复现问题的步骤:
1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
清晰地描述期望看到的行为

**截图**
如果可以，请提供对应问题的截图

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
tap模式会使用虚拟网卡拦截流量，tap网卡优先级更高，所以系统会认为当前联网的是物理网卡而不是Wi-Fi，是正常现象
