### ISSUE TITLE
如何在开发环境绕过代理

### ISSUE THREAD

**Issue by pertance** [Fndroid/clash_for_windows_pkg#892]
代理对开发环境的访问域名进行了解析，访问不到项目，配置域名直连也没效果，应该怎么处理？

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/bypass.html

**Comment by pertance** [comment]
我之前在这边配置过好像没起作用，稍等我看看给您发个截图

**Comment by pertance** [comment]
![image](https://user-images.githubusercontent.com/35564076/84562679-ef4a4180-ad88-11ea-9c9e-54fda36840bf.png)
![image](https://user-images.githubusercontent.com/35564076/84562718-494b0700-ad89-11ea-8b39-171bf3db7e93.png)
映射的本地 hosts 地址，没办法访问

**Comment by mw418** [comment]
> ![image](https://user-images.githubusercontent.com/35564076/84562679-ef4a4180-ad88-11ea-9c9e-54fda36840bf.png)
> ![image](https://user-images.githubusercontent.com/35564076/84562718-494b0700-ad89-11ea-8b39-171bf3db7e93.png)
> 映射的本地 hosts 地址，没办法访问

解决了吗 我记得旧版本是可以的  现在最新的不行了
