### ISSUE TITLE
win10 2004 隔一段时间就会断连

### ISSUE THREAD

**Issue by Lyn6969** [Fndroid/clash_for_windows_pkg#893]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
隔一段时间就会出现无法连接，间隔时间不等

**复现**
请描述复现问题的步骤:
1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
清晰地描述期望看到的行为

**截图**

![image](https://user-images.githubusercontent.com/42564665/84220662-e4cc4580-ab05-11ea-8b17-fa7376c0937f.png)

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
1. 节点确定没问题么
2. 系统时间确定没问题么
3. 本地网络确定没问题么

**Comment by liyanan24** [comment]
> 1. 节点确定没问题么
> 2. 系统时间确定没问题么
> 3. 本地网络确定没问题么

节点确定没有问题。因为也不是一直连不上，就是突然会断连，然后等一会可能自己就连上了。
系统时间同步的微软时间。
本地网络也没有问题，关闭system proxy可以正常联网。

**Comment by Fndroid** [comment]
> 因为也不是一直连不上，就是突然会断连，然后等一会可能自己就连上了

这个能说明节点没问题吗？

**Comment by liyanan24** [comment]
> > 因为也不是一直连不上，就是突然会断连，然后等一会可能自己就连上了
> 
> 这个能说明节点没问题吗？
我有好几个机场，断连的时候所有的机场测试网速都是time out。正常的时候所有的机场都能连接的。
我重新校准了一下之间，现在能连接上了。我后续再观察一下吧，感谢回复！

**Comment by liyanan24** [comment]
![image](https://user-images.githubusercontent.com/42564665/84222717-d7658a00-ab0a-11ea-8b1e-88540d7fdd5b.png)

**Comment by wanghaiwei** [comment]
我这里也有相同问题

**Comment by thalatta** [comment]
我也是，直接wifi断掉。用ss客户端就没问题

**Comment by Pearlulu** [comment]
补个图，一用steam下载游戏就会疯狂刷屏，刷一会儿就直接断掉了。完全卸载重装可以复现，是直连下载，就算用初始默认的config.yaml配置也会这样刷屏后断掉。
![image](https://user-images.githubusercontent.com/5378519/84346537-cdaf5580-abe2-11ea-9422-359f3a379944.png)

**Comment by zhaojunhhu** [comment]
同样升级到win10 2004后使用原来的机场出现该问题，换了个vmess的vps又能用了。

**Comment by NicoYaZaW** [comment]
2004 没这问题，节点有问题吧

**Comment by Lyn6969** [comment]
> 2004 没这问题，节点有问题吧

这两天好些了，前两天比较差。应该不是节点的问题，我用别的软件也测试了。
