### ISSUE TITLE
tap模式会使用虚拟网卡拦截流量，tap网卡优先级更高，所以系统会认为当前联网的是物理网卡而不是Wi-Fi，是正常现象

### ISSUE THREAD

**Issue by sekongy** [Fndroid/clash_for_windows_pkg#894]
tap模式会使用虚拟网卡拦截流量，tap网卡优先级更高，所以系统会认为当前联网的是物理网卡而不是Wi-Fi，是正常现象

_Originally posted by @Fndroid in https://github.com/Fndroid/clash_for_windows_pkg/issues/891#issuecomment-641666529_

那没有变是正常的吗  我第一次变的时候不小心删了 第二次就没了

**Comment by Fndroid** [comment]
两个网卡都连接了就没问题了，任务栏显示不一定准确

**Comment by sekongy** [comment]
> 两个网卡都连接了就没问题了，任务栏显示不一定准确

感谢
