### ISSUE TITLE
两个网卡都连接了就没问题了，任务栏显示不一定准确

### ISSUE THREAD

**Issue by sekongy** [Fndroid/clash_for_windows_pkg#895]
两个网卡都连接了就没问题了，任务栏显示不一定准确

_Originally posted by @Fndroid in https://github.com/Fndroid/clash_for_windows_pkg/issues/894#issuecomment-641686873_
感谢

**Comment by Fndroid** [comment]
回复就回复，能不能别开新issue

**Comment by sekongy** [comment]
我回复错了

**Comment by sekongy** [comment]
那需要删除吗

**Comment by sekongy** [comment]
> 回复就回复，能不能别开新issue
那需要删除吗

**Comment by sekongy** [comment]
> 回复就回复，能不能别开新issue
删除下这个问题 我回复错了 谢谢

**Comment by sekongy** [comment]
> 回复就回复，能不能别开新issue

我用github不多不熟悉 你不说我还不知道我点错了 希望谅解
