### ISSUE TITLE
什么时候能开发ubuntu版本

### ISSUE THREAD

**Issue by JackieLee-cn** [Fndroid/clash_for_windows_pkg#896]
**描述**
希望开发一款能够在ubuntu下运行的软件

**其他说明**
其他补充内容

**Comment by e71828** [comment]
|OS|version|
|ubuntu|[clash](https://github.com/Dreamacro/clash)| 
|mac |[clashx](https://github.com/yichengchen/clashX)|

**Comment by e71828** [comment]
另外，根据最新提交 https://github.com/Fndroid/clash_for_windows_pkg/commit/d643359a3a0e420b0b61c518c1762cb786ed1e16 ，这个版本也将支持 `macOS `

**Comment by iiivii** [comment]
Ubuntu下可以用[Clashy](https://github.com/SpongeNobody/Clashy)，有deb包。

**Comment by Fndroid** [comment]
暂时没有计划
