### ISSUE TITLE
[BUG]clash配置文件中不支持secret参数

### ISSUE THREAD

**Issue by xuan880** [Fndroid/clash_for_windows_pkg#90]
如果clash的配置文件中有secret参数就会导致cfw启动后界面异常，无法进行控制。
例如下面这种最简单的配置也会出现这种问题。
`port: 7777
socks-port: 7778
allow-lan: True
mode: Rule
log-level: info
external-controller: 0.0.0.0:7779
secret: "abc"
Proxy:
- { name: "ss", type: socks5, server: 127.0.0.1, port: 1080 }
- { name: "Proxy",type: select, proxies: ["ss"] }
Rule:
- GEOIP,CN,DIRECT
- MATCH,Proxy`
![a](https://user-images.githubusercontent.com/2383369/54610284-a1fcf880-4a8f-11e9-9b09-1fb868d24a6b.jpg)

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.5.30
