### ISSUE TITLE
QQ快速登陆会无法出现，关闭Clash正常

### ISSUE THREAD

**Issue by passwii** [Fndroid/clash_for_windows_pkg#900]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载
- [ ] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题

**复现**
请描述复现问题的步骤:
1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
清晰地描述期望看到的行为

**截图**
如果可以，请提供对应问题的截图

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
善用搜索：https://github.com/Fndroid/clash_for_windows_pkg/issues/339#issuecomment-616068475

**Comment by lonelyman0108** [comment]
![image](https://user-images.githubusercontent.com/43877343/87841597-15f41e80-c8d9-11ea-90e4-6a8fab7873bb.png)
添加了...还是不行诶
