### ISSUE TITLE
建议 | 关于通知时候的icon

### ISSUE THREAD

**Issue by Liny927** [Fndroid/clash_for_windows_pkg#901]
**描述**
开发者你好!
先简述一下我的环境: 
win10 pro 2004, **cfw v0.10.1**
我遇到的问题是: 
每次刚打开cfw时弹出的欢迎通知icon似乎无法正常显示, 比正常大小略小.

![image](https://user-images.githubusercontent.com/52920114/84349825-b7a59300-abea-11ea-9ef4-57d0b7989eb0.png)
![image](https://user-images.githubusercontent.com/52920114/84350126-5c27d500-abeb-11ea-8cc5-87dccbb4c01d.png)

**图1.                           类似于缩略图的icon**

 但在使用cfw时, 后续弹出的某些通知icon却可以正常显示.
![image](https://user-images.githubusercontent.com/52920114/84350479-ecfeb080-abeb-11ea-89c0-eb6e65751640.png)
**图2.                         我认为的正常大小icon**
这两种icon均出现在了我设备上的通知中
不知道是否是我配置或是软件的问题, 希望开发者能够解答一下. 感谢!

**Comment by Fndroid** [comment]
应该是个bug
