### ISSUE TITLE
使用 ClashX 时，Win10 自带的应用失去网络连接

### ISSUE THREAD

**Issue by wz233** [Fndroid/clash_for_windows_pkg#902]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
如果打开 ClashX（代理模式），Win10 自带的 Microsoft Store 及其他 Win10 应用（例如自带的 Mail）均会出现网络连接问题——商店会提示“无法加载页面，请稍后重试”，邮件则完全不能发送接收邮件。但如果使用 V2Ray-Win，则没有任何问题。

**复现**
请描述复现问题的步骤:
1. 打开 ClashX-for-Windows；
2. 使能 System Proxy

**预期行为**
即便打开 ClashX 代理，Windows 自带的应用也应该能够正常工作。为此，我比较了 V2RAY-WIN 和 ClashX 打开的情况下，Internet 的连接设置。见下面截图。

**截图**
![V2Ray代理打开时的局域网连接设置](https://user-images.githubusercontent.com/5774992/84367481-e2054980-ac06-11ea-9f80-acad85f59863.png "V2Ray代理打开时的局域网连接设置")

![ClashX代理打开时的局域网连接设置](https://user-images.githubusercontent.com/5774992/84367493-e7629400-ac06-11ea-9097-fba6969353af.png "ClashX代理打开时的局域网连接设置")

**其他说明**
暂无

**Comment by Fndroid** [comment]
点General里的uwp loopback，打开的程序把所有勾上，保存即可。

还有，这APP叫Clash for Windows

**Comment by wz233** [comment]
> 点General里的uwp loopback，打开的程序把所有勾上，保存即可。
> 
> 还有，这APP叫Clash for Windows

谢谢，我试一下。

**Comment by wz233** [comment]
> 点General里的uwp loopback，打开的程序把所有勾上，保存即可。
> 
> 还有，这APP叫Clash for Windows

谢谢，问题已解决，名字已替换。

**Comment by AlkeneSun** [comment]
> 点General里的uwp loopback，打开的程序把所有勾上，保存即可。
> 
> 还有，这APP叫Clash for Windows

thx very much!

**Comment by COSMYSELF** [comment]
> 点General里的uwp loopback，打开的程序把所有勾上，保存即可。
> 
> 还有，这APP叫Clash for Windows

正解, 感谢~~
