### ISSUE TITLE
Clash for windows在mac os里打不开系统代理，提示没有权限

### ISSUE THREAD

**Issue by zseventh** [Fndroid/clash_for_windows_pkg#903]
**描述**
Clash for windows在mac os里打不开系统代理，在终端查看，提示没有权限

**复现**
1.安装sysporxy helper
2.打开设置-网络，没有代理信息
3.运行安装的sysporxy，运行完成后提示没有写入错误，没有权限

终端提示信息：
Last login: Thu Jun 11 19:46:24 on ttys001
seventh.z@iMac ~ % /Users/seventh.z/.config/clash/sysproxy ; exit;
zsh: failed to write history file /Users/seventh.z/.zsh_history: permission denied

[进程已完成]

**Comment by Fndroid** [comment]
嗯，第一版在非mackbook下确实会这样，下个版本会修复这个问题

**Comment by Fndroid** [comment]
或者试试这个：https://c-t.work/s/6146e405b53543

**Comment by zseventh** [comment]
> 或者试试这个：[https](https://c-t.work/s/6146e405b53543) ://ct.work/s/6146e405b53543[](https://c-t.work/s/6146e405b53543)
> 
> 重新安装下Sysproxy助手

可以用了，不过“忽略这些主机与域的代理设置”里的链接没了

还有个问题就是网盘里这个版本在更新的时候会提示更新吗？

**Comment by Fndroid** [comment]
这段加到General YAML里：
```yaml
cfw-bypass:
  - 127.0.0.1
  - 192.168.0.0/16
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 100.64.0.0/10
  - 17.0.0.0/8
  - localhost
  - "*.local"
  - 169.254.0.0/16
  - 224.0.0.0/4
  - 240.0.0.0/4
```

**Comment by z245045** [comment]
大佬您是不是发错邮件了。。还是刚刚我不小心点到啥了。。。。
打扰到您了哈





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Fndroid"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月14日(星期天) 上午8:56
收件人:&nbsp;"Fndroid/clash_for_windows_pkg"<clash_for_windows_pkg@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Fndroid/clash_for_windows_pkg] Clash for windows在mac os里打不开系统代理，提示没有权限 (#903)





 
这段加到General YAML里：
 cfw-bypass:   - 127.0.0.1   - 192.168.0.0/16   - 10.0.0.0/8   - 172.16.0.0/12   - 100.64.0.0/10   - 17.0.0.0/8   - localhost   - "*.local"   - 169.254.0.0/16   - 224.0.0.0/4   - 240.0.0.0/4
