### ISSUE TITLE
每次开机无法正常加载任务栏图标导致弹出错误且无法上网

### ISSUE THREAD

**Issue by liangxyz** [Fndroid/clash_for_windows_pkg#904]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题
每次开机无法正常加载任务栏图标导致弹出错误且无法上网

**复现**
请描述复现问题的步骤:
每次开机均会出现，需要关闭错误对话框以后才正常

**预期行为**
清晰地描述期望看到的行为
开机正常启动

**截图**
如果可以，请提供对应问题的截图
<img width="418" alt="2020-6-12 21-54-11" src="https://user-images.githubusercontent.com/8108927/84510608-eeb59a80-acf7-11ea-8702-50b7f77ef09a.png">

**其他说明**
其他补充内容
看样子是右下角任务栏的图标无法正常加载，但是我关闭错误对话框以后，在cfw主页面重启却不会出问题

**Comment by Fndroid** [comment]
@liangxyz 你电脑上装了node吗

**Comment by liangxyz** [comment]
@Fndroid 大佬你好，我电脑是win10 19041.264 全新安装，并没有安装node
![QQ截图20200612224401](https://user-images.githubusercontent.com/8108927/84514934-5ff84c00-acfe-11ea-9ed0-c63dccb8c754.png)
