### ISSUE TITLE
cfw System proxy点按不动

### ISSUE THREAD

**Issue by kkk37** [Fndroid/clash_for_windows_pkg#906]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
cfw0.10.1
之前的笔记本用的一直没问题，但今天用台式机后发现System proxy系统代理一直点不了（确定其他操作都正常），具体表现是：按一下红按钮后它又会继续跳回红色，网上看了一圈好像也没人有过一样的问题，不知道是什么原因。

另外换了好几个版本重新安装，从0.9到最新的版本，还是一样的问题

**Comment by Fndroid** [comment]
说明有其他应用在你改了之后又给改回去

https://github.com/Fndroid/clash_for_windows_pkg/issues/312

**Comment by kkk37** [comment]
那该怎么解决呢，怎么查找是哪个应用？
