### ISSUE TITLE
Could not connect to Clash Core，找不到 config.yaml 文件

### ISSUE THREAD

**Issue by yungkcx** [Fndroid/clash_for_windows_pkg#907]
**信息**
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
今天打开电脑就这样了
![批注 2020-06-13 190251](https://user-images.githubusercontent.com/16053312/84567106-fed98280-ada8-11ea-9150-46a6e5960447.png)
然后我点了 Try to repair，就这样
![批注 2020-06-13 190319](https://user-images.githubusercontent.com/16053312/84567116-0b5ddb00-ada9-11ea-8fee-0dadd7878711.png)
但是这个文件当然是存在的

**log如下**
time="2020-06-13T19:08:06+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-06-13T19:08:06+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-06-13T19:08:06+08:00" level=error msg="External controller error: listen tcp 127.0.0.1:9090: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2020-06-13T19:08:06+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-06-13T19:08:06+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-06-13T19:08:06+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-06-13T19:08:06+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"

**Comment by Fndroid** [comment]
第一个图是因为你的9090端口被占用了

第二个图是因为文件不存在

**Comment by yungkcx** [comment]
端口没有被占用，文件也是存在的。而且在 config.yaml 里改成其他端口也是一样的。

**Comment by yungkcx** [comment]
我懂了，是因为 Windows 保留的动态端口，所以虽然看不到被占用，但是也不能用。用命令
`netsh int ipv4 show dynamicport tcp`
可以查看范围，用命令
`netsh int ipv4 set dynamicport tcp start=49152 num=16384`
修改范围，就可以正常使用 9090 端口了。至于为什么保留端口会突然变化，尚未找到原因。

**Comment by silvericestorm** [comment]
我解决了，步骤如下：

打开config.yaml文件。
修改mixed-port和external-controller属性对应的端口，改成任意没使用的端口就行。
重启clash软件。
应该还是端口占用的问题，但是很奇怪，我用netstat查不到，用资源管理器也查不到
