### ISSUE TITLE
一直报错，进不了general

### ISSUE THREAD

**Issue by hth10226** [Fndroid/clash_for_windows_pkg#908]
![image](https://user-images.githubusercontent.com/55045061/84589302-8639fb00-ae68-11ea-9da4-3e9239afd605.png)
如果点击try to repair会变成这样
![image](https://user-images.githubusercontent.com/55045061/84589328-b71a3000-ae68-11ea-8ec9-9d95da221b4c.png)

日志：
> time="2020-06-14T17:55:47+09:00" level=info msg="Start initial compatible provider Proxy"
time="2020-06-14T17:55:47+09:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-06-14T17:55:47+09:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-06-14T17:55:47+09:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-06-14T17:55:47+09:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-06-14T17:55:47+09:00" level=error msg="External controller error: listen tcp 127.0.0.1:9090: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2020-06-14T17:55:47+09:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/907
