### ISSUE TITLE
针对连接被重置时的重试功能

### ISSUE THREAD

**Issue by ztjal** [Fndroid/clash_for_windows_pkg#909]
**描述**
连接被重置这个应该都清楚，因为好多次在游戏中因被RESET了而相当愤怒。
这个RESET只是随机或者不知道是什么总之先RESET就对了的，而不是被检测到。
因被RESET了，数据肯定没被发到服务器上去，这时只要有“重试”功能，就能再发一次，浏览器上对POST的数据用REPLAY HXR试过是成功的，但现在游戏已经中断了，再发也没意义。
在“重试”功能运作的时候，先不把结果返回客户端，等“重试”到HTTP状态正常的数据才传回去。
这个“重试”要手动在设置文件里打开，且可以设置“重试”的次数，超出次数改为弹DIALOG，问是否继续重次，NO就断了吧……

![无标题](https://user-images.githubusercontent.com/6552290/84591036-e3847b00-ae6d-11ea-875e-f72b8ba6f58d.jpg)

**Comment by Fndroid** [comment]
做不到
