### ISSUE TITLE
[BUG]切换代理不立即生效

### ISSUE THREAD

**Issue by weijinsun** [Fndroid/clash_for_windows_pkg#91]
在全局模式下 切换节点,  切换后, 查询ip 没有变化,   浏览器 强制刷新好几次 , ip显示才变, 或者重启浏览器 ip 显示才变 , 不知道这个是 浏览器的问题  还是clash的问题, 但是感觉这个问题, 对使用有影响

**Comment by Fndroid** [comment]
1. 浏览器可能有缓存（Chrome可能需要关闭tab重新打开）
2. Clash核心不会强行打断链接，只会在重新发起请求才会分配给新的Proxy

**Comment by weijinsun** [comment]
我关闭tab页  或者 强制刷新 都出现IP 没有切换的情况, 只有重启浏览器 才行, 
强制刷新 或者 关闭tab页 , 再打开同一个网页  应该算是重新发起的请求吧 
http://2019.ip138.com/ic.asp   页面请求也是200 不是304 ,应该不是缓存问题, 但是ip地址没变
是因为浏览器没有发起新的http链接吗 所以clash 没有使用新的代理
我的理解里, 当我在clash切换了节点后, 其实是希望浏览器的下个请求立马切换代理的, 即便是同一个页面 非强制刷新, 除了 视频一类的流媒体,

**Comment by weijinsun** [comment]
是不是, 浏览器保持了http链接 没有切换啊,

**Comment by weijinsun** [comment]
我的想法是, 在手动切换代理的情况下, clash 可以主动断开链接,  使用了代理自动切换策略的情况下, 使用现在的逻辑, 不主动断开

**Comment by Fndroid** [comment]
https://github.com/Dreamacro/clash/issues/4

**Comment by Fndroid** [comment]
如果你用Chrome，可以试试这个插件

[Modify Headers for Google Chrome™](https://chrome.google.com/webstore/detail/modify-headers-for-google/innpjfdalfhpcoinfnehdnbkglpmogdi)

![image](https://user-images.githubusercontent.com/16091562/54734375-fad8a800-4bd9-11e9-9e68-8a37b5f40418.png)

可以强制浏览器去除keep alive，插件图标右键可以设置为特定网页才生效

**Comment by weijinsun** [comment]
好的, 多谢

**Comment by salzburgrujvnun** [comment]
在Connections中关闭所有连接。

**Comment by salzburgrujvnun** [comment]
![image](https://user-images.githubusercontent.com/79001470/129481119-62825868-ba6d-445a-a729-5a769a5ac171.png)

Break When Proxy Change
代理更改时中断
None
Chain
All 
没有任何
链
全部
Break When Profile Change

Break When Mode Change

Display Chain Type 
Proxy
Group
Both





配置文件更改时中断

模式改变时中断

显示链类型
代理人
团体
两个都
