### ISSUE TITLE
能否在状态栏显示实时网速

### ISSUE THREAD

**Issue by CoderTonyChan** [Fndroid/clash_for_windows_pkg#911]
**描述**
请具体并清楚地描述期望功能及期望的效果

能否在状态栏显示实时网速，想ClashX一样

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/84612404-250b3980-aef3-11ea-8f31-db26a9763487.png)

在做了，下个版本加上

**Comment by OpenWaygate** [comment]
[XMeters](https://entropy6.com/xmeters/download/)
![image](https://user-images.githubusercontent.com/27287694/84917738-4a19cb00-b0f2-11ea-950a-64f7cb91950f.png)

**Comment by IlluminateDarkheat** [comment]
[TrafficMonitor](https://github.com/zhongyang219/TrafficMonitor)
