### ISSUE TITLE
mac版状态栏图标能否改为全黑

### ISSUE THREAD

**Issue by mps1209** [Fndroid/clash_for_windows_pkg#912]
跟其他图标颜色不一样感觉好奇怪。。。
![image](https://user-images.githubusercontent.com/20399711/84618376-9c959480-af04-11ea-841a-843478a40a04.png)

**Comment by SpecN997** [comment]
先自己右鍵顯示包內容Contents/Resources/Clash for Windows.icns替換下？
系統改成暗黑模式就是白貓了（

**Comment by Fndroid** [comment]
最新版已经是全黑/白了
