### ISSUE TITLE
mac版CFW退出问题

### ISSUE THREAD

**Issue by steven756284184** [Fndroid/clash_for_windows_pkg#914]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
macOS Catalina Version 10.15.4
右键点击Dock上的CFW图标退出，没有反应。打开Dashboard后，使用快捷键command+Q，或点击顶部菜单栏左上角的程序标题后点击Quit clash_win都无法退出。必须点击顶部菜单栏的icon后点击Quit才能退出。
关机时如果CFW没有退出，关机过程会中途暂停，直到手动退出CFW之后才继续。
请问这是feature吗。。？

**复现**
请描述复现问题的步骤:
1. 采取上述任意一种退出CFW的尝试。
2. 在CFW未退出情况下关机或重启。

**预期行为**
CFW正常退出/mac正常关机或重启。

**截图**
无。

**其他说明**
无。

**Comment by Fndroid** [comment]
感谢反馈，下个版本会修复这几个问题的

**Comment by steven756284184** [comment]
感谢修复
