### ISSUE TITLE
安装不上，显示安装中止

### ISSUE THREAD

**Issue by hornfeifan** [Fndroid/clash_for_windows_pkg#919]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ ] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载
- [ ] 软件下载后未修改任何安装目录中的文件

**系统**

[//]: # (平台及版本号)

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
解压用

**Comment by hornfeifan** [comment]
那个节点可用，在里面全部都显示timeout 这个怎么处理

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Fndroid <notifications@github.com>
发送时间: Wednesday, June 17, 2020 7:02:25 PM
收件人: Fndroid/clash_for_windows_pkg <clash_for_windows_pkg@noreply.github.com>
抄送: hornfeifan <feifan.me@outlook.com>; Author <author@noreply.github.com>
主题: Re: [Fndroid/clash_for_windows_pkg] 安装不上，显示安装中止 (#919)


Closed #919<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FFndroid%2Fclash_for_windows_pkg%2Fissues%2F919&data=02%7C01%7C%7C8876f290b7124249870708d812adebd0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637279885479933895&sdata=Z7kwQiqNhxOWDsi%2FixgZAQ6A0dFHg4VoZtlxrtmWfk4%3D&reserved=0>.

―
