### ISSUE TITLE
按照文档设置网易云的绕过系统代理后没有效果

### ISSUE THREAD

**Issue by Aceralon** [Fndroid/clash_for_windows_pkg#92]
具体设置如下
![批注 2019-03-23 201710.jpg](https://i.loli.net/2019/03/23/5c9623e8aff24.jpg)
系统的代理设置绕过中没有添加入网易云有关的值
![批注 2019-03-23 201734.jpg](https://i.loli.net/2019/03/23/5c9623e8a48cb.jpg)
手动添加后可以使用网易云
![批注 2019-03-23 201844.jpg](https://i.loli.net/2019/03/23/5c9624293c5ef.jpg)

但是重新启动Clash之后设置会被还原回去

**Comment by Fndroid** [comment]
因为你改错文件，改的是config.yml

**Comment by Aceralon** [comment]
谢谢，可以了，被gui里面配置文件名字迷惑了😅
