### ISSUE TITLE
Mac Clashx

### ISSUE THREAD

**Issue by JustCrazyer** [Fndroid/clash_for_windows_pkg#920]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载
- [x ] 软件下载后未修改任何安装目录中的文件

**系统**

[//]: # (平台及版本号)
MACOS 10.15.5

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
Mac ClashX 控制台界面空白

**复现**

[//]: # (请描述复现问题的步骤)

重启电脑打开clashx控制台，依然空白

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

![1592399847](https://gitee.com/justcrazyer/image-bed/raw/master/uPic/1592399847.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
clashx？

**Comment by JustCrazyer** [comment]
> clashx？

不好意思，发错地方了
