### ISSUE TITLE
安装包太大了，希望能减小一下体积。。。

### ISSUE THREAD

**Issue by abc34567** [Fndroid/clash_for_windows_pkg#923]
如题。。。。

SSR客户端只有1.5M，v2rayN才20M，这个clash实在太大了，自己下载、传给别人，都很不方便。

**Comment by Fndroid** [comment]
那就用别的

**Comment by kingcomxu** [comment]
说实话, 安装包体积大不是问题, 内存占用才是大问题, 一个破界面用electron来做...

**Comment by Fndroid** [comment]
> 说实话, 安装包体积大不是问题, 内存占用才是大问题, 一个破界面用electron来做...

您怎么不做一个？
