### ISSUE TITLE
自动打开允许本地和添加本地pac列表

### ISSUE THREAD

**Issue by fanyueyue** [Fndroid/clash_for_windows_pkg#926]
**描述**
希望allow lan每次打开都可以自动打开不需要再手动打开

希望可以增加一个本地的pac列表，不然每次同步了节点之后，自己经常使用的小众网站比如inoreader.com就要自己添加一条规则，希望可以自己有一个本地列表，无论怎么更新配置，都不变，谢谢

**其他说明**
其他补充内容

**Comment by Apocalypsor** [comment]
0202年了还搁这pac呢，建议回去用xxr

**Comment by Fndroid** [comment]
可以自己写一个pac，端口填clash的。

不考虑做这个功能。
