### ISSUE TITLE
重启软件Proxies模式出现错误

### ISSUE THREAD

**Issue by Gavin-Foo** [Fndroid/clash_for_windows_pkg#927]
**信息**

- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**系统**

Windows 2004

**描述**

CFW更新为最新版后，代理模式无论选择何种，重启软件都是自动跳到Rule模式
旧版一直使用的都是Global模式，可是新版使用这个重启软件还是变成Rule模式

**复现**

- v 0.11.0版本进入Proxies，选中Global或其他，并重启软件
- 打开CFW，再次进入Proxies，发现模式已处于Rule
- 此时打开[IP查询](https://www.chaip.org/) ，国内外所显示ip不同，对应Rule模式

**预期行为**

每次开启客户端软件，Proxies对应关闭客户端前所选，打开[IP查询](https://www.chaip.org/) ，IP对于所选Proxies

**日志**

**截图**

![image](https://user-images.githubusercontent.com/68200097/87255556-6d9c1f80-c4be-11ea-81f4-52e53a7393f3.png)

![image](https://user-images.githubusercontent.com/68200097/87255237-86570600-c4bb-11ea-9cd2-6cb3c4b56b7a.png)

**其他说明**

望早日修复此Bug，效果同 v 0.10.4 版本，谢谢！

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/934

**Comment by Gavin-Foo** [comment]
> [＃934](https://github.com/Fndroid/clash_for_windows_pkg/issues/934)

引用的问题和我的并不同，所以到底是软件Bug还是机场配置文件错误？

请给出具体错误原因，如何是机场配置文件错误，能否给出修改方案，谢谢！

**Comment by Fndroid** [comment]
会按你profile设置的mode，不是General YAML里的，没设置就是rule

**Comment by Gavin-Foo** [comment]
> 会按你profile设置的mode，不是General YAML里的，没设置就是rule

![image](https://user-images.githubusercontent.com/68200097/87467593-c8628200-c64a-11ea-8dc8-ed835f4a20cb.png)

如图通过修改配置文件的方法确实可以实现所讲效果，重启软件mode不变。

不过对于经常需要变换Proxies mode的用户来说，每次都要进入配置文件修改属实麻烦，**能否有办法软件修改mode，重启依旧维持原mode，除非下次软件修改原mode，否则一次维持上次修改效果。**
