### ISSUE TITLE
win10升级0.11客户端无法上网

### ISSUE THREAD

**Issue by iMikuX** [Fndroid/clash_for_windows_pkg#928]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [ ] 软件下载后未修改任何安装目录中的文件

**系统**

[//]: # (平台及版本号)
win10

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/15759469/87261236-29257980-c4e8-11ea-9db4-309b9dca0649.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
看更新日志再问

**Comment by iMikuX** [comment]
以解决！谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Fndroid"<notifications@github.com&gt;; 
发送时间: 2020年7月13日(星期一) 上午9:09
收件人: "Fndroid/clash_for_windows_pkg"<clash_for_windows_pkg@noreply.github.com&gt;; 
抄送: "一库大神"<735692351@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Fndroid/clash_for_windows_pkg] win10升级0.11客户端无法上网 (#928)





 
看更新日志再问

**Comment by xyh101** [comment]
> 以解决！谢谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Fndroid"<notifications@github.com&gt;; 发送时间: 2020年7月13日(星期一) 上午9:09 收件人: "Fndroid/clash_for_windows_pkg"<clash_for_windows_pkg@noreply.github.com&gt;; 抄送: "一库大神"<735692351@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [Fndroid/clash_for_windows_pkg] win10升级0.11客户端无法上网 (#928) 看更新日志再问 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
请问你是怎么解决的 我的timeout

**Comment by iMikuX** [comment]
新版本需要对配置文件名称进行手动修改，改动如下：
Proxy--&gt;proxiesProxy Group--&gt;proxy-groups
Rule--&gt;rules






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xyh101"<notifications@github.com&gt;; 
发送时间: 2020年7月13日(星期一) 中午11:19
收件人: "Fndroid/clash_for_windows_pkg"<clash_for_windows_pkg@noreply.github.com&gt;; 
抄送: "一库大神"<735692351@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Fndroid/clash_for_windows_pkg] win10升级0.11客户端无法上网 (#928)





  
以解决！谢谢
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Fndroid"<notifications@github.com&gt;; 发送时间: 2020年7月13日(星期一) 上午9:09 收件人: "Fndroid/clash_for_windows_pkg"<clash_for_windows_pkg@noreply.github.com&gt;; 抄送: "一库大神"<735692351@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [Fndroid/clash_for_windows_pkg] win10升级0.11客户端无法上网 (#928) 看更新日志再问 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
 请问你是怎么解决的 我的timeout

**Comment by iMikuX** [comment]
> > 以解决！谢谢
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "Fndroid"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年7月13日(星期一) 上午9:09 收件人: "Fndroid/clash_for_windows_pkg"<[clash_for_windows_pkg@noreply.github.com](mailto:clash_for_windows_pkg@noreply.github.com)>; 抄送: "一库大神"<[735692351@qq.com](mailto:735692351@qq.com)>; "Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [Fndroid/clash_for_windows_pkg] win10升级0.11客户端无法上网 (#928) 看更新日志再问 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 请问你是怎么解决的 我的timeout

新版本需要对配置文件名称进行手动修改，改动如下：
Proxy-->proxies
Proxy Group-->proxy-groups
Rule-->rules
