### ISSUE TITLE
怎么重置CFW？

### ISSUE THREAD

**Issue by YFTX2015** [Fndroid/clash_for_windows_pkg#929]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ ] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载
- [ ] 软件下载后未修改任何安装目录中的文件

**系统**

[//]: # (平台及版本号)

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)卸载不干净，个人设置改动仍然保留，要完全清除个人设置，彻底恢复成默认设置。

**Comment by Fndroid** [comment]
能不能稍微看下文档/更新日志再问？https://docs.cfw.lbyczf.com/contents/configfile.html

**Comment by YFTX2015** [comment]
当然是看了之后不能解决我的问题所以才问，而你后头发的那篇文档，我就是从头到尾，翻来覆去看了很多遍，都还是不晓得咋个整。里面只不过是说了有些文件最好不要去碰，那么万一改遭了，又咋个整？反正在那里头我是没看到任何解决方案。然后说说我为啥子要改。我也是看了最近几个版本Mixin那个地方打了个惊叹号，链接出了个文档，说的是可以添加一些字段，然后就好奇心使然，按照里头的说明手动添加了，以为这样子可以获得更好的效果，结果还不要说取得好的效果，反而还整得要不得了，连软件都用不起了。然后看了你现在发的这篇文档，说的是如非必要最好不要改动某某文件。而我现在的想法也是任何关于修改配置的操作我二天都不想再去碰了。全部初始设置就好。但是我就搞不懂了，你到底是希望用户添加内容，还是不要添加内容？添加了内容是不是就比不添加的效果要好？如果只是希望懂得起的用户添加内容，那为啥子不在侧边标明不懂的不要去搞？本来在早几个版本的时候，没得这个说明或者功能的时候，我也不得去管，用得尚好，现在既然弄出这么个东西，起码的警示还是应该要有嘛，未必然你敢保证你的用户都不会像我一样二，都能改得巴巴适适的，一点错都不犯？还有，我之前还发了个建议，我不晓得你看没得，现在我也懒得关心你得不得去理会，不过，既然你让我们看文档日志，恢复成默认设置的方法总应该提供，而且是让小白也能看得懂的浅显易懂的那种，要是你说你后头发给我的这篇文档已经说清楚了，我是不得相信的哈。

**Comment by KintaMiao** [comment]
还有这是开源软件，Fndroid并没有义务给你解答，这一切只是程序员的热情和情分罢了，希望您注意态度谢谢

**Comment by KintaMiao** [comment]
如果是CFW本身有问题就重装核心
