### ISSUE TITLE
系统代理及开机启动勾选不了

### ISSUE THREAD

**Issue by TGRyan** [Fndroid/clash_for_windows_pkg#93]
Clash 0.5.3
Win10 64bit
System Proxy 及 Start with windows 无法勾选，点击无反应

**Comment by Fndroid** [comment]
@TGRyan 读写注册表的操作，检查是不是有其他安全软件限制

**Comment by jiahe224** [comment]
> @TGRyan 读写注册表的操作，检查是不是有其他安全软件限制

请问什么软件会限制呢？我没有装杀毒软件，cold Turkey会限制吗？这是一款禁止打开某些网站的软件

**Comment by jiahe224** [comment]
> @TGRyan 读写注册表的操作，检查是不是有其他安全软件限制

另外不勾选这个就无法用代理吗？我看有的教程上面系统代理不是必选项

**Comment by Fndroid** [comment]
> > @TGRyan 读写注册表的操作，检查是不是有其他安全软件限制
> 
> 另外不勾选这个就无法用代理吗？我看有的教程上面系统代理不是必选项

不勾选可以用，给要代理的软件单独设置上http/socks5代理即可

**Comment by Licheng-Xu** [comment]
打扰各位，不好意思
在用 0.11.2 版本，这个问题依然存在，关闭了火绒以管理员身份运行也不行
但是同样的条件下 shadowsocksr 和 fiddler 是可以正常打开系统代理的
请问有什么方法可以检测到是那个工具在限制么

**Comment by lpiert** [comment]
regedit: "Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinHttpAutoProxySvc " 
‘start’ modify this feild to '3' or '2' then restart your Computer.
the question had fixed. click 'get help' and send your quests, you will get a link, then answer in pages.

**Comment by hongjoy** [comment]
您的方法对我有效，谢谢！

**Comment by 1Rone11** [comment]
> regedit: "Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinHttpAutoProxySvc " ‘start’ modify this feild to '3' or '2' then restart your Computer. the question had fixed. click 'get help' and send your quests, you will get a link, then answer in pages.

谢谢。很好的方法
