### ISSUE TITLE
route ip+net: no such network interface

### ISSUE THREAD

**Issue by xyh101** [Fndroid/clash_for_windows_pkg#932]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ 是] 已经尝试更新到最新版本，问题依旧存在
- [  是] 软件从本仓库下载
- [  是] 软件下载后未修改任何安装目录中的文件

**系统**

[//]: # win10 clash 0.11
**描述**

[//]: # 配置文件已经按新版写好 0.10.4使用没问题 0.11直接timeout  连direct也timeout 日志显示 route ip+net: no such network interface

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
配置文件dns删掉

**Comment by xyh101** [comment]
> 配置文件dns删掉

搞好了 谢谢
