### ISSUE TITLE
疑似v0.11.0无法通过IPv6连接服务器

### ISSUE THREAD

**Issue by Pentacene** [Fndroid/clash_for_windows_pkg#933]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**系统**

[//]: 
Windows 10 Pro Workstation 19041.329 (2004)

**描述**

[//]:
 一个IPv4/IPv6双栈网络，想实现所有流量走IPv6。在v0.10.4能够将配置文件中的server解析成ipv6地址，v0.11.0则不能。连接时提示 
`_MY_SERVER_HOST_:443 connect error: dial tcp4 _MY_SERVER_IPv4_:443 i/o timeout TIME`
clash的配置文件已更新为proxies proxies-group rules
该配置文件在CFW v0.10.4及CFA无报错

**复现**

[//]: # (请描述复现问题的步骤)

1. 在v0.10.4一切工作正常
2. 升级到v0.11.0，无脑下一步
3. 触发问题
4. 手动关闭网卡IPv4选项
5. 问题未解决
6. 在4的基础上，手动设置IPv6 DNS地址为[2606:4700:4700::1111]
7. 问题未解决
8. 手动ping -6 _MY_SERVER_HOST_
9. 可以ping通

**预期行为**

[//]: # (清晰地描述期望看到的行为)
LOG中出现 
```
Dail [_PROXIES_GROUP_NAME_] failed
_MY_SERVER_HOST_:443 connect error: dial tcp4 _MY_SERVER_IPv4_:443 i/o timeout TIME
```
**日志**

[//]: # (上传触发问题对应的日志文件)
```
Dail [_PROXIES_GROUP_NAME_] failed
_MY_SERVER_HOST_:443 connect error: dial tcp4 _MY_SERVER_IPv4_:443 i/o timeout TIME
```
**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/48641773/87300665-d2985980-c540-11ea-891a-97a4b551d74a.png)

**其他说明**

[//]: # (其他补充内容)
如开发者无相应环境复现问题，可高度配合。

**Comment by Fndroid** [comment]
试试在profile中加入

```yaml
ipv6: true
```

**Comment by Pentacene** [comment]
> 试试在profile中加入
> 
> ```yaml
> ipv6: true
> ```

感谢，问题已解决。

**Comment by TianYaDY** [comment]
尝试关闭wan6口，并且使用ipv6里面那个中继模式，最终成功了。

**Comment by TianYaDY** [comment]
> 试试在profile中加入
> 
> ```yaml
> ipv6: true
> ```

大佬，如果说用了这个软件，还想使用ipv6，怎么做？加入ipv6:true以后，ipv6测试依然不通过。

**Comment by Pentacene** [comment]
> > 试试在profile中加入
> > ```yaml
> > ipv6: true
> > ```
> 
> 大佬，如果说用了这个软件，还想使用ipv6，怎么做？加入ipv6:true以后，ipv6测试依然不通过。

你好，因为这是我提的issue所以收到了mail，我把我的配置文件给你看一下，可能会有帮助。

我说开启了TAP模式，TAP没有ipv6的地址，所以连接IPv6的时候，还是默认走原本的网卡的。

**Comment by TianYaDY** [comment]
> > > 试试在profile中加入
> > > ```yaml
> > > ipv6: true
> > > ```
> > 
> > 
> > 大佬，如果说用了这个软件，还想使用ipv6，怎么做？加入ipv6:true以后，ipv6测试依然不通过。
> 
> 你好，因为这是我提的issue所以收到了mail，我把我的配置文件给你看一下，可能会有帮助。
> 
> 我是开启了TAP模式，TAP没有ipv6的地址，所以连接IPv6的时候，还是默认走原本的网卡的。
> 
> ![批注 2020-07-21 113658](https://user-images.githubusercontent.com/48641773/88010170-db8fb900-cb46-11ea-94be-33dc3ece7e98.png)

多谢大佬！还有一个问题，如果是订阅的机场，经常自动更新配置文件，这种情况下，每次都需要改文件吗？

**Comment by Pentacene** [comment]
我不太了解，但是应该有一个全局覆盖的东西。你可以摸索摸索
________________________________

**Comment by TianYaDY** [comment]
> 我不太了解，但是应该有一个全局覆盖的东西。你可以摸索摸索
> […](#)
> ________________________________ From: TianYaDY <notifications@github.com> Sent: Tuesday, July 21, 2020 11:57:12 AM To: Fndroid/clash_for_windows_pkg <clash_for_windows_pkg@noreply.github.com> Cc: Pentacene <blucartfhg@outlook.com>; State change <state_change@noreply.github.com> Subject: Re: [Fndroid/clash_for_windows_pkg] 疑似v0.11.0无法通过IPv6连接服务器 (#933) 试试在profile中加入 ipv6: true 大佬，如果说用了这个软件，还想使用ipv6，怎么做？加入ipv6:true以后，ipv6测试依然不通过。 你好，因为这是我提的issue所以收到了mail，我把我的配置文件给你看一下，可能会有帮助。 我是开启了TAP模式，TAP没有ipv6的地址，所以连接IPv6的时候，还是默认走原本的网卡的。 [批注 2020-07-21 113658]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48641773%2F88010170-db8fb900-cb46-11ea-94be-33dc3ece7e98.png&data=02%7C01%7C%7C6a0b7c586a6b44901e9108d82d2a265f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637309006332392570&sdata=JCccv67F1LbJejrPb85rXYXUjfS%2Br0gRxcuKV4QiOUk%3D&reserved=0> 多谢大佬！还有一个问题，如果是订阅的机场，经常自动更新配置文件，这种情况下，每次都需要改文件吗？ ― You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FFndroid%2Fclash_for_windows_pkg%2Fissues%2F933%23issuecomment-661617231&data=02%7C01%7C%7C6a0b7c586a6b44901e9108d82d2a265f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637309006332402566&sdata=f%2FwzR4Kqp1klFe7xI0U%2BirVg%2FQTw12rzmelemiJjvkI%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALTDN3IWN6LULYE7YAX3X3TR4UGZRANCNFSM4OYMU4OQ&data=02%7C01%7C%7C6a0b7c586a6b44901e9108d82d2a265f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637309006332412569&sdata=fZYDu0ehUjdxrWfYdnR87YNuVamyH2IFFkhSkSBfgck%3D&reserved=0>.

0.0

**Comment by Fndroid** [comment]
@Pentacene TAP目前不能用ipv6

**Comment by Lyn6969** [comment]
机场主没有写关于dns的部分，是不是要自己加上？

**Comment by Lyn6969** [comment]
> @Pentacene TAP目前不能用ipv6

请问要全局修改是在哪里改呢？config.yaml吗？
