### ISSUE TITLE
v0.11.0 版本 Log Level 配置无效

### ISSUE THREAD

**Issue by giftzn** [Fndroid/clash_for_windows_pkg#934]
**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**系统**

[//]: # (平台及版本号)
Windows 10 2004（19041.329）

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
config.yaml 中配置的 log-level 无效了，无论怎么改 CFW 中始终都是 info

**复现**

[//]: # (请描述复现问题的步骤)

1. 删除 config.yaml 重启 CFW
2. 打开新生成的 config.yaml 把 log-level 改为warning
3. 再次重启CFW，软件中的 log-level 依然是 info

**Comment by Fndroid** [comment]
预期行为，此版本及以后log-level及mode都会使用profile中定义的值，如果没有就是默认值info及rule
