### ISSUE TITLE
v0.11.0 Portable 安装模式配置文件无法控制 Log level

### ISSUE THREAD

**Issue by L1H0n9Jun** [Fndroid/clash_for_windows_pkg#935]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**系统**

[//]: # (平台及版本号)
Windows 10 x64 2004

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
Portable 安装模式，即主配置文件 `config.yaml` 位于 `安装根目录\resources\static\files\` 时，`log-level` 配置无效，软件启动时 log level 一直保持为 info mode。而主配置文件位于 `~/.config/...` 时 `log-level` 配置有效（即配置为 `warning/debug` mode 等会生效）。

**预期行为**

[//]: # (清晰地描述期望看到的行为)
通过portable 模式下主配置文件 `安装根目录\resources\static\files\config.yaml` 配置 `log-level`，可修改日志级别。

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/934
