### ISSUE TITLE
更新为0.11.0后中不显示节点

### ISSUE THREAD

**Issue by wtchalloo** [Fndroid/clash_for_windows_pkg#937]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**系统**

[//]: # (平台及版本号)
win10 1903
**描述**

[//]: # (请具体并清楚地描述遇到的问题)
更新为0.11.0后Proxies中不显示节点
**复现**

[//]: # (请描述复现问题的步骤)

1. 安装新版0.11.0并运行进入Proxies不显示节点
2. 更新列表后依然不显示,重新打开还是一样

**预期行为**

[//]: # (清晰地描述期望看到的行为)
之前版本都能正常显示节点，正常使用
**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![Screenshot_20200714001904](https://user-images.githubusercontent.com/9428961/87330690-8adaf780-c56b-11ea-9a80-21e37e03cc98.png)
![Screenshot_20200714001916](https://user-images.githubusercontent.com/9428961/87330700-8e6e7e80-c56b-11ea-9473-8632341672e7.png)

**其他说明**

[//]: # (其他补充内容)

重新安装旧版恢复正常使用

**Comment by hermitgreen** [comment]
win10 2004同样问题

**Comment by Gavin-Foo** [comment]
![image](https://user-images.githubusercontent.com/68200097/87363826-9565b300-c5a4-11ea-9bf5-502dbc7a2071.png)
从v 0.11.0开始，配置文件又改了，之后的版本需要新的配置文件支持，不想麻烦的话还是用老版吧

**Comment by lhie1** [comment]
不看更新日志的？

**Comment by Fndroid** [comment]
看更新日志及里面的链接
