### ISSUE TITLE
0.11.0版本新的设置文件的使用方法？

### ISSUE THREAD

**Issue by washstar** [Fndroid/clash_for_windows_pkg#938]
**描述**
0.11.0版本使用了新的设置配置，但是使用手册中没有新的设置配置相关的使用方法和关键字之类的内容，导致不能实现上一个版本中个的自定义配置。

**Comment by washstar** [comment]
希望更新一下说明文档，感谢

**Comment by Fndroid** [comment]
看更新日志及里面的链接
