### ISSUE TITLE
安装 Tap 网卡失败

### ISSUE THREAD

**Issue by zaunist** [Fndroid/clash_for_windows_pkg#939]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ x] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载
- [ x] 软件下载后未修改任何安装目录中的文件

**系统**
win10 1903
[//]: # (平台及版本号)

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
尝试过 clash 和 clashR，都无法安装 tap 网卡，点击后无反应。截图中使用的版本是 0.10.3 的ClashR 汉化版，[github地址](https://github.com/BoyceLig/ClashR_for_Windows/releases/download/0.10.3_0.20.01/ClashR.for.Windows-0.10.3_0.20.01-Chinese.7z)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入软件主页面
2. 点击安装Tap 网卡
3. 没有任何反应
4.我找到了安装目录下的 bat 脚本，尝试直接通过脚本安装，结果报错

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**
[//]: # (如果可以，请提供对应问题的截图)

![image](https://user-images.githubusercontent.com/38528079/87380429-0b7a1200-c5c5-11ea-8472-79919e96e535.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
不知道
