### ISSUE TITLE
Rule模式的一个小问题

### ISSUE THREAD

**Issue by siwei-Z** [Fndroid/clash_for_windows_pkg#94]
Rule模式下，chrome新标签页的google，也就是google.com会经常访问不了，但是google.co.jp，youtube什么的都没问题；我用的以前版本（0.5.21)似乎没有这个问题。

**Comment by Fndroid** [comment]
访问一下google.com，看看请求的log

**Comment by siwei-Z** [comment]
![Snipaste_2019-03-26_09-46-57](https://user-images.githubusercontent.com/36556673/54966281-c20c4a80-4fae-11e9-8092-2c7e9ada09d0.png)
![Snipaste_2019-03-26_10-05-48](https://user-images.githubusercontent.com/36556673/54966283-c20c4a80-4fae-11e9-9504-4f3f16273216.png)

**Comment by Fndroid** [comment]
Clash的log，HomeDirectory/logs

**Comment by siwei-Z** [comment]
time="2019-03-26T14:15:18+08:00" level=info msg="127.0.0.1 --> cuscochromeextension-pa.googleapis.com match DomainKeyword using BoomCloud"
time="2019-03-26T14:15:26+08:00" level=info msg="127.0.0.1 --> ssl.gstatic.com match DomainSuffix using BoomCloud"
time="2019-03-26T14:15:26+08:00" level=info msg="127.0.0.1 --> lh3.googleusercontent.com match DomainKeyword using BoomCloud"
time="2019-03-26T14:15:26+08:00" level=info msg="127.0.0.1 --> www.gstatic.com match DomainSuffix using BoomCloud"

**Comment by Fndroid** [comment]
没看到你请求google.com
