### ISSUE TITLE
更新版本后配置数据丢失

### ISSUE THREAD

**Issue by sukekes** [Fndroid/clash_for_windows_pkg#940]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [1 ] 已经尝试更新到最新版本，问题依旧存在
- [2 ] 软件从本仓库下载

**系统**

[//]: # (平台及版本号)

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
更新客户端覆盖安装后，配置信息丢失

**复现**

[//]: # (请描述复现问题的步骤)

1、客户端提示版本更新，点击打开更新链接，下载安装包
2、安装客户端，选择覆盖安装
3、覆盖安装后运行客户端
3、打开客户端后服务器配置等数据为空

**预期行为**

[//]: # (清晰地描述期望看到的行为)
覆盖安装后数据均丢失

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by geeklihui** [comment]
补个图，我升级0.10后也是所有节点都没了，卸载重装clash、重新导入订阅都不行。
![image](https://user-images.githubusercontent.com/28993319/87394439-5f472400-c5e2-11ea-92e7-a369537faeee.png)

**Comment by tediorelee** [comment]
> 补个图，我升级0.11后也是所有节点都没了，卸载重装clash、重新导入订阅都不行。
> 
> ![微信图片_20200714150705](https://user-images.githubusercontent.com/28993319/87395282-b699c400-c5e3-11ea-9fe8-a3cf6d88e617.png)
> ![微信图片_20200714150708](https://user-images.githubusercontent.com/28993319/87395287-b994b480-c5e3-11ea-928c-7973656f672b.png)
> ![微信图片_20200714150711](https://user-images.githubusercontent.com/28993319/87395294-bac5e180-c5e3-11ea-8fcd-4b88183ddf9b.png)
> ![微信图片_20200714150713](https://user-images.githubusercontent.com/28993319/87395297-bb5e7800-c5e3-11ea-92e5-bd6811e3a67b.png)

应该是clash的配置文件里面有几个写法变了，看这里https://github.com/Dreamacro/clash/wiki/breaking-changes-in-1.0.0

**Comment by geeklihui** [comment]
@tediorelee 多谢，已解决，修改Proxy为proxies，Proxy Group为proxy-groups，Rule为rules后就可以了，但要注意开头的mode后的Rule不能修改为rules。

**Comment by bantianyigiao** [comment]
这怎么办啊我还是用不了啊

**Comment by yangqiang00** [comment]
我的也用不了。大佬， 怎么解

**Comment by yangqiang00** [comment]
做了个简单的 workaround, 将 clash for window 软件恢复为旧的版本， 将 C:\Users\user\.config\clash 里面的文件也恢复为旧的版本。暂时可以先用着。
