### ISSUE TITLE
关机时没有关闭系统代理导致开机后无法上网

### ISSUE THREAD

**Issue by AoEiuV020** [Fndroid/clash_for_windows_pkg#943]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载
- [x ] 软件下载后未修改任何安装目录中的文件

**系统**

[//]: # (平台及版本号)
win10 ltsc
**描述**

[//]: # (请具体并清楚地描述遇到的问题)
电脑重启后发现无法上网，检查发现系统代理设置没有关闭，
如果是普通的关闭软件，系统代理会被正常关闭，是否关机时有什么处理存在异常导致系统代理设置没有关闭？
**复现**

[//]: # (请描述复现问题的步骤)

1. 正常使用，
2. 开启系统代理，
3. 开启开机自启，
4. 在任务管理器中禁用cfw开机自启，
5. 重启电脑，
6. 触发问题，系统代理设置还存在，cfw没有启动前无法上网，
**预期行为**

[//]: # (清晰地描述期望看到的行为)
cfw启动前系统代理设置是关闭状态，可以正常上网，
**日志**

[//]: # (上传触发问题对应的日志文件)
无
**截图**

[//]: # (如果可以，请提供对应问题的截图)
无
**其他说明**

[//]: # (其他补充内容)
无

**Comment by Wildwizard404** [comment]
打开win10设置——网络和Internet——代理，在手动设置代理处关闭使用代理服务器即可。
当然这显然很麻烦，不如直接启动cfw然后关闭代理方便。
建议设置cfw开机自启。

**Comment by Fndroid** [comment]
这个windows上并没有比较好的解决方案，mac上倒是可以在关机/重启前阻止系统

**Comment by MW8023** [comment]
你不如直接将cfw设为开机启动项 反正电脑开着我都会开着

**Comment by AoEiuV020** [comment]
@MW8023 我是刚换机场在试用clash，电脑上装着ssr, v2ray, clash三个梯子开机自启，然后在任务管理器统一管理禁用两个或者三个测试，
正常使用的话确实是开机自启着用的，
但就算开机自启，cfw启动也不快的感觉，我发现问题时就是开机自启的情况，在cfw启动成功前我就打开了浏览器，然后发现cfw启动前无法上网，
最好还是能处理一下，

**Comment by AoEiuV020** [comment]
electron那边似乎有人正在处理，虽然pr还没被合并，但也许什么时候就解决了，这边更新依赖electron版本就可以，
[https://github.com/electron/electron/pull/24261/commits](https://github.com/electron/electron/pull/24261/commits)

**Comment by orziie** [comment]
同样的问题，clash 开机自启动 很慢。每次启动电脑都折腾一番，发现是代理的问题，好在现在有经验了。

**Comment by AoEiuV020** [comment]
@Fndroid 所以我常用电脑已经放弃cfw改用原生clash了，处理成后台服务优先启动并且同步开关系统代理，

**Comment by Fndroid** [comment]
好

**Comment by cysx07** [comment]
大佬，请问clash win版设置了开机自启动，用的tun模式，规则代理，可以正常使用，可是第二天重新打开电脑后，就不能上网了要怎么解决啊
