### ISSUE TITLE
could not switch to this profile:TAP mode enable but no interface-name setted

### ISSUE THREAD

**Issue by lj522** [Fndroid/clash_for_windows_pkg#947]
[信息]: # (如不按模版填写，则issue将被直接关闭)
could not switch to this profile
TAP mode enable but no interface-name setted

[过程]: # (如果符合，请将``[ ]``改为``[x]``)

- [1 ] 已经尝试更新到最新版本，问题依旧存在
- [2 ] 软件从本仓库下载
- [3 ] 软件下载后未修改任何安装目录中的文件

**系统**

[系统]: # (平台及版本号)
win 7 sp1
**描述**

[//]: # (请具体并清楚地描述遇到的问题)
导入订阅链接后提示could not switch to this profile:TAP mode enable but no interface-name setted
**复现**

[//]: # (请描述复现问题的步骤)

1. 进入clash
2. 点击'profiles
3. 复制订阅链接到'download for a URL'
4.点击'download '
5.显示'success'
6.点击导入的profile
7.触发问题
**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![1594802760(1)](https://user-images.githubusercontent.com/68360506/87618101-96851480-c74b-11ea-8a10-d58575943508.png)
![1594802524(1)](https://user-images.githubusercontent.com/68360506/87618106-98e76e80-c74b-11ea-811f-1e35bf70cf62.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
编辑配置文件，把里面dns的enable改成false
