### ISSUE TITLE
ByPass无法以*号开头

### ISSUE THREAD

**Issue by mengbo1991** [Fndroid/clash_for_windows_pkg#948]
**描述**
bypass部分添加*.qq.com显示Error，添加*.qq.com是为QQ可以快速安全登录，不设置只能手机扫码。，无奈只能在win10的设置代理内添加，但是每次电脑重启又得重新设置，望可以以*开头，感谢。

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
```yaml
bypass:
  - "*.qq.com"
```

**Comment by mengbo1991** [comment]
感谢大佬

**Comment by niusz** [comment]
> ```yaml
> bypass:
>   - "*.qq.com"
> ```

bypass文件在哪里啊？

**Comment by mengbo1991** [comment]
> > ```yaml
> > bypass:
> >   - "*.qq.com"
> > ```
> 
> bypass文件在哪里啊？

setting->System Proxy->Bypass Domain/IPNet----edit
