### ISSUE TITLE
想问下CFW v 0.10.4的socks端口号在哪？

### ISSUE THREAD

**Issue by DearDeer7** [Fndroid/clash_for_windows_pkg#949]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**系统**
Clash for Windows v.0.10.4

[//]: # (平台及版本号)

**描述**
想给IDM配置代理下载油管视频，CFW用的版本是v0.9.6，一直报连接超时（好像代理有点问题？），刚更新到了v 0.10.4，发现主界面没有socks端口了，请问如何配置？

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/42965045/87635289-5f295e80-c771-11ea-9e06-45930b55469b.png)
![image](https://user-images.githubusercontent.com/42965045/87635410-90a22a00-c771-11ea-9414-a211d74a4128.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by AkariiinMKII** [comment]
https://t.me/fndroid_news/529

**Comment by Fndroid** [comment]
界面中的port就是http和socks

**Comment by DearDeer7** [comment]
我按port那里填写的好像无效，我用路由器端代理的socks端口就有效
