### ISSUE TITLE
[BUG]开机无法启动CFW且无法关闭

### ISSUE THREAD

**Issue by VincentCJ** [Fndroid/clash_for_windows_pkg#95]
**Describe the bug**
新版本CFW遇到过两次同样的问题，开机无法启动，无法打开dashboard且无法退出，只有用资源管理器关闭后重启才可以正常使用。之前的版本未出现此问题，且此问题发生的时候并没有log。
**To Reproduce**

**Expected behavior**

**Screenshots**

**Error Logs (located in HomeDirectory)**
```
// paste below this line
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows10]

**Additional context**

**Comment by Fndroid** [comment]
开机之后进程已经有CFW了么？

**Comment by VincentCJ** [comment]
是的，有进程了，dashboard加载不出来，选择quit也无法退出。只能关闭进程。

**Comment by Fndroid** [comment]
尝试一下重新开关一下``Start with Windows``

**Comment by VincentCJ** [comment]
好的，谢谢F大，我试一下。如果还有问题再咨询您。

**Comment by VincentCJ** [comment]
![30AD40AFD3DC74EF29FC00D53C083706](https://user-images.githubusercontent.com/33440778/55202291-caa88f00-5201-11e9-97a0-03115c822d5f.png)
![72315E4CB0755DE52E571897DA3B2181](https://user-images.githubusercontent.com/33440778/55202292-cc725280-5201-11e9-812e-5c1d71e5d28d.png)

**Comment by VincentCJ** [comment]
F大，今天早上又发生了一遍，无法打开网站，无法退出，请查看照片。

**Comment by Fndroid** [comment]
杀了之后可以正常启动么

**Comment by VincentCJ** [comment]
对，杀了之后可以正常使用，目前并没有发现如何引发这个问题，但是每次都是在发生开机后。昨天重新点了一遍 Start with Windows。

**Comment by VincentCJ** [comment]
F大早上好，好久没来请安了，我今天刚准备说没出现问题了，结果flag不能立，今天又出现问题了，31版本。不知是否是启动进程冲突。问题是发生在新下了一个桌面日历软件后发生的，我关掉那个软件的自启动试试看。

**Comment by VincentCJ** [comment]
F大晚上好,我又来反馈了,还是无法开启也无法关闭,只能force quite,我把那个自启动的软件已经关闭启动了,还是出现这样的情况,下一步试试退回到旧版试试.

**Comment by Fndroid** [comment]
还记得哪个版本正常的吗

**Comment by VincentCJ** [comment]
F大，应该是29版本正常，目前还是没找到原因。

**Comment by Fndroid** [comment]
TG私聊我一下，我发个包你试试

**Comment by Fndroid** [comment]
This issue has not been updated for a long time. I am sorry to close it.

Please try updating to the latest version first to see if the problem has disappeared.

If not, feel free to start a new issue.
