### ISSUE TITLE
连接节点timeout, 但是v2rayn可以正常连接

### ISSUE THREAD

**Issue by NiuXZi** [Fndroid/clash_for_windows_pkg#950]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [X] 已经尝试更新到最新版本，问题依旧存在
- [X] 软件从本仓库下载
- [X] 软件下载后未修改任何安装目录中的文件

**系统**

[//]: # Clash for windows v 0.11.0

**描述**

[//]: # clash 连接v2ray失败显示timeout，但是在v2rayn上可以正常连接。服务器除了v2服务还建了另一个网站，cloudreve的网盘程序，关掉那个网站的ssl后，可以正常连接，打开就连不了。（但是那个网站的SSL不能关。。。还需要用。。。）

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # 可以不用关SSL也能正常连接

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # 我还有另一台机子也是两个网站，搭了一个图床，但是，可以正常连接。

**Comment by Fndroid** [comment]
skip-cert-verify设置成false试试
