### ISSUE TITLE
0.11.0及之后的版本如何设置clash-profile-builder子进程？

### ISSUE THREAD

**Issue by Bennett-Yang** [Fndroid/clash_for_windows_pkg#951]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**系统**

 Windows 10 2004

**描述**

更新到0.11.0及之后的版本后，原本设置的clash-profile-builder子进程的设置失效了。我在settings模块中找到了设置的地方，但是不知道该如何正确设置。

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/childprocess.html
