### ISSUE TITLE
关于更新新版本后打开出现白屏的问题

### ISSUE THREAD

**Issue by Snrat** [Fndroid/clash_for_windows_pkg#953]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**系统**

[//]: # (平台及版本号)

Windows10 19041.329

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

问题发生在更新Clash0.11.1后，后续尝试更换为0.10.4版本问题依旧。
打开Clash界面后显示白屏，无任何内容，大约在1-3分钟后出现内容。

**复现**

[//]: # (请描述复现问题的步骤)

1. 打开Clash
2. 双击任务栏图标打开界面
3. 触发问题，软件白屏
4.1-3min后软件内容展现

**预期行为**

[//]: # (清晰地描述期望看到的行为)

了解此问题发生的原因并修复

**日志**

[//]: # (上传触发问题对应的日志文件)

time="2020-07-17T18:40:36+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-07-17T18:40:36+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-07-17T18:41:12+08:00" level=error msg="External controller error: listen tcp 127.0.0.1:9090: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
time="2020-07-17T18:41:12+08:00" level=error msg="Start Mixed(http and socks5) server error: listen tcp 127.0.0.1:7890: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
-07-17T18:46:20+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-07-17T18:46:20+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-07-17T18:46:33+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2020-07-17T18:47:23+08:00" level=info msg="Start initial compatible provider Proxy"

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
```
time="2020-07-17T18:41:12+08:00" level=error msg="External controller error: listen tcp 127.0.0.1:9090: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
```

9090端口被占用，改个别的

**Comment by Snrat** [comment]
经测试，在使用端口不被占用的情况下，该问题依旧产生。
且在白屏过后软件才会正常产生日志，本次日志如下：
time="2020-07-17T20:41:07+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-07-17T20:41:07+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-07-17T20:41:23+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2020-07-17T20:41:44+08:00" level=info msg="Start initial compatible provider Proxies"
time="2020-07-17T20:41:44+08:00" level=info msg="Start initial compatible provider Netease Music"
time="2020-07-17T20:41:44+08:00" level=info msg="Start initial compatible provider Domestic"
time="2020-07-17T20:41:44+08:00" level=info msg="Start initial compatible provider Stream Services"
time="2020-07-17T20:41:44+08:00" level=info msg="Start initial compatible provider Apple Services"
time="2020-07-17T20:41:44+08:00" level=info msg="Start initial compatible provider AD Block"
