### ISSUE TITLE
QQ快捷登录异常

### ISSUE THREAD

**Issue by lonelyman0108** [Fndroid/clash_for_windows_pkg#954]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**系统**

[//]: # (平台及版本号) 
WIN 10 PRO 18363.959

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
QQ快捷登录功能异常

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'https://qzone.qq.com/'
2. 触发问题，无法触发快捷登录，关闭系统代理刷新后就恢复正常了

**预期行为**

[//]: # (清晰地描述期望看到的行为)
如下图

**日志**

[//]: # (上传触发问题对应的日志文件)
![image](https://user-images.githubusercontent.com/43877343/87785050-11445180-c86a-11ea-81c7-57b7c4e6ab14.png)

**截图**

[//]: # (如果可以，请提供对应问题的截图)
打开系统代理：
![image](https://user-images.githubusercontent.com/43877343/87784685-55832200-c869-11ea-8ba2-b5344445470c.png)
![image](https://user-images.githubusercontent.com/43877343/87784845-a4c95280-c869-11ea-9074-aa1895d91cd2.png)

关闭系统代理：
![image](https://user-images.githubusercontent.com/43877343/87784772-82373980-c869-11ea-8fe9-7196ffb851d6.png)
控制台全部正常

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues?q=is%3Aissue+qq+%E7%99%BB%E9%99%86

**Comment by lonelyman0108** [comment]
![image](https://user-images.githubusercontent.com/43877343/87841659-8ef37600-c8d9-11ea-8528-4466b1f35da3.png)
添加了，还不不行

**Comment by lonelyman0108** [comment]
在win10内的系统代理内添加了规则才好

**Comment by liangchenhe55** [comment]
友情提示，当前版本（0.11.2）中，在 `General YAML` 中添加 `cfw-bypass` 或 `bypass` 字段似乎已经失效。

新的方案参考 [CFW 文档](https://docs.cfw.lbyczf.com/contents/bypass.html) 来设置 bypass 域名。或者直接编辑 Home Dir 下 `cfw-settings.yaml` 里 `bypassText: bypass:` 数组。

PS: 如果只想解决快速登录问题，那么绕过 `localhost.ptlogin2.qq.com` 就行了。
