### ISSUE TITLE
软件无法显示主界面，在左下角看到一个图标，无法设置各种参数

### ISSUE THREAD

**Issue by huaxiwwh** [Fndroid/clash_for_windows_pkg#957]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**系统**

[//]: # (平台及版本号)

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入windows
2. 点击图标
3. 拖动到（不适用）
4. 触发问题，软件运行，但是无法显示主界面

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # 

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
0.11.0会么

**Comment by huaxiwwh** [comment]
我在尝试一下，可能和我前几天关闭了某些系统服务有关，但是我记不清楚前几天的关闭了哪些服务。

**Comment by huaxiwwh** [comment]
非常感谢，已经解决。

**Comment by Fndroid** [comment]
所以是cfw的原因么？

**Comment by huaxiwwh** [comment]
可能与电脑的杀毒软件有关吧,问题还是完美解决了.
