### ISSUE TITLE
下载速度也太慢了吧！[FR]

### ISSUE THREAD

**Issue by smiletoohiahia** [Fndroid/clash_for_windows_pkg#96]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by smiletoohiahia** [comment]
下载速度太慢了，这是什么原因呢？

**Comment by Fndroid** [comment]
什么下载速度？

**Comment by Fndroid** [comment]
此issue将被关闭，如问题依旧，欢迎reopen
