### ISSUE TITLE
no such file or directory 

### ISSUE THREAD

**Issue by lizhuoyuan** [Fndroid/clash_for_windows_pkg#960]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**
![image](https://user-images.githubusercontent.com/15923901/87845229-2ebffc80-c8f8-11ea-9ef0-6ec112b25c8f.png)

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**系统**
win 10
[//]: # (平台及版本号)

**描述**
![image](https://user-images.githubusercontent.com/15923901/87845227-2a93df00-c8f8-11ea-9304-177c40bb306d.png)
config:
mixed-port: 7890
allow-lan: false
log-level: info
external-controller: '127.0.0.1:9090'
secret: ''
ipv6: false

# Will be ignored after profile selection

proxies:

  - name: Shadowsocks
    type: socks5
    server: 127.0.0.1
    port: 1080
    proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - Shadowsocks
        rules:
  - 'MATCH,DIRECT'
[//]: # (请具体并清楚地描述遇到的问题)

**复现**
打开的时候就出现这个, repair无效
[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
应该显示无错

[//]: # (清晰地描述期望看到的行为)

**日志**
time="2020-07-18T13:10:13+08:00" level=warning msg="MMDB invalid, remove and download"

[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/15923901/87845238-41d2cc80-c8f8-11ea-8d21-d3a46a8802b9.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)
先下载的最新版,然后下载的这个版本 都一样的问题

**Comment by abae136ab** [comment]
settings改一下配置文件目录试试？

**Comment by lizhuoyuan** [comment]
卸载之后 下载了一个旧版本  旧版本可以用
然后再装新版本就ok了
