### ISSUE TITLE
macos 通过mixin开启TUN，失败

### ISSUE THREAD

**Issue by flyingwhitewhale** [Fndroid/clash_for_windows_pkg#961]
CFW  0.11.1 

拟通过mixin开启tun，mixin内容如下
mixin: # object
  dns:
     enable: true
     enhanced-mode: redir-host
     nameserver:
       - 223.5.5.5
       - 119.29.29.29
  #interface-name: en0
  tun:
    enable: true
    stack: system  # or gvisor
    dns-hijack:
      - 119.29.29.29
      - 223.5.5.5
    macOS-auto-route: true # auto set global route
    macOS-auto-detect-interface: true

root enable成功，系统dns设置和dns-hijack同款。

但是无法正常上google，仅在开启7890端口代理时可以使用。

日志提示
time="2020-07-18T13:51:35+08:00" level=info msg="Tun Proxy listening at: utun2(198.18.0.1)"
time="2020-07-18T13:51:35+08:00" level=error msg="[TUN] Stack initial error: listen udp4 198.18.0.1:7777: bind: address already in use"
time="2020-07-18T13:51:40+08:00" level=info msg="[TCP] 127.0.0.1:59527 --> www.google.com match DomainKeyword using [[YoYu-Air]   Light HK 01 [0.2]]"

希望大佬们指正下配置问题，谢谢

**Comment by KKFantasy** [comment]
@flyingwhitewhale 我也遇到了同样的问题，请问怎么解决的，谢谢
