### ISSUE TITLE
订阅Profiles出错，yaml: unmarshal errors: line 1: cannot unmarshal !

### ISSUE THREAD

**Issue by manning120008** [Fndroid/clash_for_windows_pkg#963]
![yaml错误](https://i.loli.net/2020/07/19/yhsSQZHD8bI1eXU.png)
Could not switch to this profile!
yaml: unmarshal errors:
line 1: cannot unmarshal !strt dm1Ic3M.. into config.RawConfig一> Edit in Text Mode

**Comment by Fndroid** [comment]
https://docs.cfw.lbyczf.com/contents/configfile.html

**Comment by Lance-123** [comment]
请问怎样解决的呀

**Comment by nkzhengwt** [comment]
求问怎么解决的+1

**Comment by antoniosuen** [comment]
求解决

**Comment by SiYun916** [comment]
我这个报错，最后发现是订阅到期了 - -！

**Comment by Clairehou111** [comment]
转换工具，https://bianyuan.xyz/
选择基础模式，把订阅链接放进去，可以选在下方的一键导入

**Comment by JackHuHappy** [comment]
> 转换工具，https://bianyuan.xyz/ 选择基础模式，把订阅链接放进去，可以选在下方的一键导入
没有用呀，还是不行

**Comment by MUJINYE2017** [comment]
转换工具，https://bianyuan.xyz/
选择基础模式，把订阅链接放进去，可以选在下方的一键导入，这个对安卓版不行啊
