### ISSUE TITLE
谷歌学术无法访问

### ISSUE THREAD

**Issue by CZY3434123** [Fndroid/clash_for_windows_pkg#965]
![image](https://user-images.githubusercontent.com/28703617/87865198-f5919600-c9a4-11ea-8552-1dd336a8b7af.png)

**Comment by Fndroid** [comment]
不填template也起码发个log吧

**Comment by CZY3434123** [comment]
> 不填template也起码发个log吧

是这个吗，主要是不懂
![image](https://user-images.githubusercontent.com/28703617/87865655-a9495480-c9aa-11ea-867f-8e6cad30fcc4.png)

**Comment by CZY3434123** [comment]
> 不填template也起码发个log吧
是这个吗，小白一枚
![image](https://user-images.githubusercontent.com/28703617/87865698-1230cc80-c9ab-11ea-8e54-25a6863fbe75.png)

**Comment by CZY3434123** [comment]
> 不填template也起码发个log吧

不知为什么，现在又可以了。。。。。
