### ISSUE TITLE
general界面UI

### ISSUE THREAD

**Issue by Oneliey** [Fndroid/clash_for_windows_pkg#969]
**描述**
我非常喜欢之前的 general 界面的样式，感觉很炫酷。能否在之后的版本中，保留这个布局？
能否在设置中 增加general页面样式选择的选项，同时保留改版前和改版后的布局，让用户选择自己心仪的样式？
十分感谢！
![image](https://user-images.githubusercontent.com/30212642/87911396-20abe080-ca9e-11ea-9527-da3bb0d3ffc1.png)

**其他说明**
其他补充内容

**Comment by Wildwizard404** [comment]
+1

**Comment by Fndroid** [comment]
不会再加回这个了

**Comment by Oneliey** [comment]
能询问一下具体的原因吗

**Comment by Fndroid** [comment]
@Oneliey 因为凑9格很困难

**Comment by Oneliey** [comment]
哈哈哈，你说的好有道理233。 不过，感觉这个设计真的很好看。
