### ISSUE TITLE
更新到0.11.1后发现又不能更新GeoIP

### ISSUE THREAD

**Issue by Azrael2233** [Fndroid/clash_for_windows_pkg#970]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**系统**
win10 1909
[//]: # (平台及版本号)

**描述**
我本来的版本是0.9.xx 更新到了0.11.1之后点击GeoIP Database会提示“updating geoip database is not allowed in cfw”
谷歌了一番之后发现可以手动更新 但是并不知道替换哪个文件 也找不到教程
[//]: # (请具体并清楚地描述遇到的问题)

**复现**
点击GeoIP Database会提示“updating geoip database is not allowed in cfw”
[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
开始走进度条 然后日期为当前的日期
[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/68552448/87950063-64700b80-cad9-11ea-8989-ba55a1421b9b.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by Azrael2233** [comment]
我按照谷歌教的0.8.8教程的方法注册了那个maxmind 然后下了一份GeoLite2-Country 里面有个mmdb文件 教程只说替换到文件夹内 但是我不知道能替换到那里……所以这个manually到底怎么manually……

**Comment by ZnCu-Shadow** [comment]
#869 
提 issue 之前自己先搜一下行不行

**Comment by Fndroid** [comment]
替换到Home Directory里

**Comment by alililala** [comment]
> **信息**
> 
> * [x]  已经尝试更新到最新版本，问题依旧存在
> * [x]  软件从本仓库下载
> * [x]  软件下载后未修改任何安装目录中的文件
> 
> **系统**
> win10 1909
> [//](#): # (平台及版本号)
> 
> **描述**
> 我本来的版本是0.9.xx 更新到了0.11.1之后点击GeoIP Database会提示“updating geoip database is not allowed in cfw”
> 谷歌了一番之后发现可以手动更新 但是并不知道替换哪个文件 也找不到教程
> [//](#): # (请具体并清楚地描述遇到的问题)
> 
> **复现**
> 点击GeoIP Database会提示“updating geoip database is not allowed in cfw”
> [//](#): # (请描述复现问题的步骤)
> 
> 1. 进入'...'
> 2. 点击'....'
> 3. 拖动到'....'
> 4. 触发问题
> 
> **预期行为**
> 开始走进度条 然后日期为当前的日期
> [//](#): # (清晰地描述期望看到的行为)
> 
> **日志**
> 
> **截图**
> ![image](https://user-images.githubusercontent.com/68552448/87950063-64700b80-cad9-11ea-8989-ba55a1421b9b.png)
> 
> **其他说明**

跟你一样的问题。版本0.11.2   win7 64

**Comment by zrz130** [comment]
> #869
> 提 issue 之前自己先搜一下行不行
哦，我懂了，原来github的风气就是这样啊，别人有困难求助不是先帮助别人，而是准备开始他的教育事业，你当这里是百度贴吧？还是当这里是抖音？

**Comment by Fndroid** [comment]
搜一下先不应该吗？

重复的问题谁有回几次谁有这个功夫？都是要工作生活的。

**Comment by zrz130** [comment]
2020年8月17日(月) 12:32 Fndroid <notifications@github.com>:

**Comment by zrz130** [comment]
> 搜一下先不应该吗？
> 
> 重复的问题回几次谁有这个功夫？都是要工作生活的。

你是从哪就觉得人家就没搜呢？万一人家没找到或者是还不理解呢？怎么的github是你家的还是怎么的？不允许别人问问题了？你有时间在这开展你的教育事业，说没时间工作生活？我看你教育人挺有时间的啊？跑到这来当人上人来了？

**Comment by Fndroid** [comment]
> > 搜一下先不应该吗？
> 
> > 
> 
> > 重复的问题回几次谁有这个功夫？都是要工作生活的。
> 
> 
> 
> 你是从哪就觉得人家就没搜呢？万一人家没找到或者是还不理解呢？怎么的github是你家的还是怎么的？不允许别人问问题了？你有时间在这开展你的教育事业，说没时间工作生活？我看你教育人挺有时间的啊？跑到这来当人上人来了？

滚吧
