### ISSUE TITLE
大佬们！用了这个好像就没有用IPV6了，怎么整？

### ISSUE THREAD

**Issue by TianYaDY** [Fndroid/clash_for_windows_pkg#971]
关闭软件可以检测到IPV6，开启后就没了，是不是需要设置。。。

**Comment by Fndroid** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/issues/933

**Comment by TianYaDY** [comment]
重新试了下，不使用wan6口，lan口和wan口的内置ipv6关掉，好像就行了。

**Comment by TeemoZhang-ice** [comment]
> #933

回答已404，需要更新，目前问题又出现了，谢谢大佬
