### ISSUE TITLE
update geoip database is not allowed in cfw，求解决

### ISSUE THREAD

**Issue by Hong-qing** [Fndroid/clash_for_windows_pkg#973]
今天尝试更新GeoIP时弹出如下错误
![图片](https://user-images.githubusercontent.com/49011700/88005353-cd886b00-cb3b-11ea-97f7-fe99e8ea1fcc.png)
尝试寻找了一个解决方法[Clash for Windows 更新GeoIP Database](https://blog.yosheng.tw/clash-for-windows-geoip-database)，可是到最后仍然不能更新，使用的Clash版本为v 0.10.4，请教大家怎么解决，另外这个GeoIP有什么用呢，不嫌麻烦的话也希望好兄弟们科普一下。

**Comment by Fndroid** [comment]
Duplicate of https://github.com/Fndroid/clash_for_windows_pkg/issues/970
