### ISSUE TITLE
最新版V0.11.1，请问要怎样更新GeoIP DataBase?

### ISSUE THREAD

**Issue by echo860** [Fndroid/clash_for_windows_pkg#975]
还是提示要手动更新。 Not allowed in CFW，pls do it manually
可是我在maxmind里下的license添加不进去，那个地方点不动

**Comment by RivenM** [comment]
将下载好的mmdb文件命名为Country.mmdb, 替换Home Directory里的

**Comment by echo860** [comment]
> 将下载好的mmdb文件命名为Country.mmdb, 替换Home Directory里的

以好，mmdb文件在哪里下载？我只有license. 纯电脑小白

**Comment by Quzard** [comment]
https://geolite.clash.dev/

**Comment by qzi** [comment]
这个功能这么普通，为啥不添加上去
