### ISSUE TITLE
v0.11.1，proxies中没有任何rule

### ISSUE THREAD

**Issue by ljh0519** [Fndroid/clash_for_windows_pkg#976]
v0.10.x 是正常的
![image](https://user-images.githubusercontent.com/38551537/88135771-6ab9d100-cc1a-11ea-83fd-429a28c68cfb.png)
![image](https://user-images.githubusercontent.com/38551537/88135782-71e0df00-cc1a-11ea-951c-0f962fea6289.png)

**Comment by Gackson** [comment]
同问

**Comment by CyberTNT** [comment]
Clash最近更改了配置文件的写法，改一下就行

**Comment by Gackson** [comment]
已解决，建议用老版本，等Profile源更新后再升新版本。

**Comment by TonnyTonny** [comment]
我的從上一版也是這樣，退回到v0.10.4了。

**Comment by yi-Xu-0100** [comment]
#694 我在置顶的 issue 中回复了便捷修改方式，可参考

**Comment by TonnyTonny** [comment]
@yi-Xu-0100 Thank

**Comment by XuCpeng** [comment]
请教一下，Profile编写格式的更改，是来自Clash上游，还是只限于Clash for Windows？ 有无官方文档，我现在Clash用不了，不方便查。

**Comment by yi-Xu-0100** [comment]
> 请教一下，Profile编写格式的更改，是来自Clash上游，还是只限于Clash for Windows？ 有无官方文档，我现在Clash用不了，不方便查。

好像是来自 clash 上游，clash 模板官方文档：https://github.com/Dreamacro/clash/wiki/Configuration 

好像从 0.9.7 之后，CFW不再支持编辑 `Rule/Proxy/Proxy Group` 字段配置文件，替换为 `rules/proxies/proxy-groups`

**Comment by CaoXiufengwhut** [comment]
同问 clash 0.11怎么使用

**Comment by arcayi** [comment]
> proxy-groups

正解，解决问题

**Comment by arcayi** [comment]
> > 请教一下，Profile编写格式的更改，是来自Clash上游，还是只限于Clash for Windows？ 有无官方文档，我现在Clash用不了，不方便查。
> 
> 好像是来自 clash 上游，clash 模板官方文档：https://github.com/Dreamacro/clash/wiki/Configuration
> 
> 好像从 0.9.7 之后，CFW不再支持编辑 `Rule/Proxy/Proxy Group` 字段配置文件，替换为 `rules/proxies/proxy-groups`

正解，解决问题

**Comment by CaoXiufengwhut** [comment]
我用的clash的网址：https://github.com/Fndroid/clash_for_windows_pkg/releases


你用的clash 那个版本，要是0.11之后的版本 需要对以前的订阅链接进行转换 才能使用

转换https://subcon.py6.pw/网址，且在   更多选项--》选择 clash新字段，

你qq或者微信多少 我的微信/qq：303363858
________________________________
发件人: Walter Arca Yi <notifications@github.com>
发送时间: 2020年8月6日 12:34
收件人: Fndroid/clash_for_windows_pkg <clash_for_windows_pkg@noreply.github.com>
抄送: CaoXiufengwhut <cxf0417@hotmail.com>; Comment <comment@noreply.github.com>
主题: Re: [Fndroid/clash_for_windows_pkg] v0.11.1，proxies中没有任何rule (#976)


请教一下，Profile编写格式的更改，是来自Clash上游，还是只限于Clash for Windows？ 有无官方文档，我现在Clash用不了，不方便查。

好像是来自 clash 上游，clash 模板官方文档：https://github.com/Dreamacro/clash/wiki/Configuration

好像从 0.9.7 之后，CFW不再支持编辑 Rule/Proxy/Proxy Group 字段配置文件，替换为 rules/proxies/proxy-groups

正解，解决问题

―

**Comment by LING15205** [comment]
请教一下！按照694的方法更改了仍然profile的rule里什么东西也没有怎么办
