### ISSUE TITLE
无法显示任何Proxies。

### ISSUE THREAD

**Issue by Gackson** [Fndroid/clash_for_windows_pkg#977]
![image](https://user-images.githubusercontent.com/26532664/88173957-0583d100-cc56-11ea-8248-d122eadfcd18.png)
载入配置后貌似无法加载任何规则。
![image](https://user-images.githubusercontent.com/26532664/88173981-0ddc0c00-cc56-11ea-8cc5-8f77847a4d70.png)
点击编辑后提示：
![image](https://user-images.githubusercontent.com/26532664/88174007-16ccdd80-cc56-11ea-84e5-ec0606737313.png)
系统关联中无法找到yaml文件的关联。
在另一台电脑的较早版本上正常。初步怀疑可能和Windows更新后对文件关联规则的变动所致。

**Comment by Rimliya** [comment]
就是转换规则没更新的问题而已
clash那边整了一手新的

**Comment by Gackson** [comment]
换了更新前的版本，完美解决了。

**Comment by bianxg** [comment]
遇到同样问题。换了哪个版本？
