### ISSUE TITLE
每次打开clash 默认模式都会切换成global

### ISSUE THREAD

**Issue by MoeSoap** [Fndroid/clash_for_windows_pkg#979]
是否有办法让默认模式变成rules

**Comment by realoyrz** [comment]
同感，希望能记忆退出前的设置

**Comment by iiivii** [comment]
检查下配置文件里的mode模式是不是global

**Comment by yi-Xu-0100** [comment]
从[CFW V0.11.1](https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.11.1)开始 `mode` 参数按照配置文件的设置缓存，应该是远程的订阅源中的配置覆盖了本地配置。

我在 #988 中给出，使用[配置文件预处理方法](https://docs.cfw.lbyczf.com/contents/parser.html)可以对配置文件修改，可以结合 **js 语法规则**对 `mode` 关键词修改设置，防止配置更新造成该设置修改。

**Comment by yi-Xu-0100** [comment]
我实验了我的配置文件预处理方法中对 `mode` 关键词的修改，可以成功修改配置文件。

但是我发现，这个缓存按配置文件的意思，好像是对同一个订阅有同样设置，远程配置文件的规则好像不会覆盖本地设置。

也就是说，如果是同一个配置文件，本地设置过后，应该再次打开，是不会被覆盖的（我个人测试是没有覆盖的，版本 [V0.11.2](https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.11.2)）。

建议给出电脑版本，log记录，或者任何可能的其他的信息。或者升级版本查看是否还是存在当前的问题。

**Comment by Fndroid** [comment]
最新版mode的选择会被记住，并不会因为更新配置文件改变

**Comment by yi-Xu-0100** [comment]
> 最新版mode的选择会被记住，并不会因为更新配置文件改变

@Fndroid 请问后期会提供，按照配置文件中的设置进行设置嘛？我是指其他的关键词，远程的配置是否会覆盖本地配置。使用配置文件预处理方法后，感觉配置文件的修改更加简单，方便了。

**Comment by Fndroid** [comment]
> > 最新版mode的选择会被记住，并不会因为更新配置文件改变
> 
> 
> 
> @Fndroid 请问后期会提供，按照配置文件中的设置进行设置嘛？我是指其他的关键词，远程的配置是否会覆盖本地配置。使用配置文件预处理方法后，感觉配置文件的修改更加简单，方便了。

这个mode现在缓存方式已经是最优解了吧，parser处理就显得麻烦了

**Comment by yi-Xu-0100** [comment]
好的，确实如此，只是都放在一个 js 中，感觉可以整合一起，感谢提供这样的方法，解决我想自定义规则的想法。
