### ISSUE TITLE
谷歌浏览器不能访问[BUG]

### ISSUE THREAD

**Issue by fdtl01** [Fndroid/clash_for_windows_pkg#98]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Error Logs (located in HomeDirectory)**
```
// paste below this line
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows10]

**Additional context**

**Comment by Fndroid** [comment]
开启System Proxy或者使用浏览器插件连接Clash的http/socks5端口

如果是拨号，只能使用后者

**Comment by fdtl01** [comment]
> 开启System Proxy或者使用浏览器插件连接Clash的http/socks5端口
> 
> 如果是拨号，只能使用后者

浏览器插件是什么，具体一下，谢啦

**Comment by Fndroid** [comment]
@fdtl01 SwithyOmega
