### ISSUE TITLE
找不到config.yaml

### ISSUE THREAD

**Issue by web4zn** [Fndroid/clash_for_windows_pkg#980]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [Y] 已经尝试更新到最新版本，问题依旧存在
- [Y] 软件从本仓库下载
- [Y] 软件下载后未修改任何安装目录中的文件

**系统**

[//]: # (平台及版本号)

windows 10 2004

[//]: # (请具体并清楚地描述遇到的问题)

**复现**
[//]: # (请描述复现问题的步骤)
最初安装的是之前的版本，后来断网或者重启后就会有这个问题，重新安装11后直接提示找不到目录无法使用。

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)
LOG
time="2020-07-23T14:15:16+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-07-23T14:15:16+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-07-23T14:15:16+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2020-07-23T14:15:16+08:00" level=error msg="External controller error: listen tcp 127.0.0.1:9090: bind: An attempt was made to access a socket in a way forbidden by its access permissions."

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/10208505/88260023-197f0f80-ccf6-11ea-98ad-fa58f6758532.png)
**其他说明**

[//]: # (其他补充内容)
我尝试过更换config下的external端口，似乎没有作用

**Comment by carlsonsoft** [comment]
可以通过命令查看端口被什么程序占用 netstat -o 如果占用，修改config.yaml中的external-controller: '127.0.0.1:9090'端口
我就是这样解决的
如果还是不行，可以尝试 #907 再修改端口

**Comment by web4zn** [comment]
参考#907
