### ISSUE TITLE
为什么Proxy Mode自动跳到Global?

### ISSUE THREAD

**Issue by echo860** [Fndroid/clash_for_windows_pkg#982]
最新版v 0.11.1
我每次打开CFW后手动调到Rule，但是我下次打开CFW，不经意中想起这个时，一看Model又自动跳到Global了

**Comment by yi-Xu-0100** [comment]
从[CFW V0.11.1](https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.11.1)开始 `mode` 参数按照配置文件的设置缓存，应该是远程的订阅源中的配置覆盖了本地配置。

我在 #988 中给出，使用[配置文件预处理方法](https://docs.cfw.lbyczf.com/contents/parser.html)可以对配置文件修改，可以结合 **js 语法规则**对 `mode` 关键词修改设置，防止配置更新造成该设置修改。

**Comment by yi-Xu-0100** [comment]
我实验了我的配置文件预处理方法中对 `mode` 关键词的修改，可以成功修改配置文件。

但是我发现，这个缓存按配置文件的意思，好像是对同一个订阅有同样设置，远程配置文件的规则好像不会覆盖本地设置。

也就是说，如果是同一个配置文件，本地设置过后，应该再次打开，是不会被覆盖的（我个人测试是没有覆盖的，版本 [V0.11.2](https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.11.2)）。

建议给出电脑版本，log记录，或者任何可能的其他的信息。或者升级版本查看是否还是存在当前的问题。

**Comment by yi-Xu-0100** [comment]
#979 相同情况的 issue ,建议此 issue 关闭。
