### ISSUE TITLE
最新的0.11.2会被Windows Defender攻击面减少规则拦截

### ISSUE THREAD

**Issue by Gladtbam** [Fndroid/clash_for_windows_pkg#983]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**系统**
Windows10专业版，版本：19041.388

[//]: # (平台及版本号)

**描述**
直接被Windows Denfender的攻击面减少规则拦截

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**
Windows事件查看器日志：
Microsoft Defender 攻击防护阻止了 IT 管理员不允许的操作。
 有关详细信息，请与 IT 管理员联系。
 	ID: 01443614-CD74-433A-B99E-2ECDC07BFC25
 	检测时间: 2020-07-24T04:43:34.258Z
 	用户: 
 	路径: D:\Program Files\Clash_for_Windows\Clash for Windows.exe
 	进程名称: C:\Windows\explorer.exe
 	安全智能版本: 1.319.2143.0
 	引擎版本: 1.1.17200.2
 	产品版本: 4.18.2006.10

[//]: # (上传触发问题对应的日志文件)

**截图**
![image](https://user-images.githubusercontent.com/49943258/88361910-40e4e380-cdad-11ea-86f8-6bf0b880638d.png)

![image](https://user-images.githubusercontent.com/49943258/88361779-bef4ba80-cdac-11ea-9499-252f1a1a1018.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**
暂时添加了排除项

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
Duplicate of https://github.com/Fndroid/clash_for_windows_pkg/issues/984
