### ISSUE TITLE
0.11.2被McAfee Endpoint Security拦截并清理

### ISSUE THREAD

**Issue by tjxddt** [Fndroid/clash_for_windows_pkg#984]
自适应威胁防护已修复 C:\Users\xxxxx\Documents\Clash.for.Windows\Clash for Windows.exe TargetType，因为其信誉 (已知恶意文件) 低于配置的清理阈值。
Analyzer / Detector
Product name	McAfee Endpoint Security
Product version	10.7.0.1886
Feature name	Real Protect Cloud
 
Threat
Action taken	清理
Threat category	检测到恶意软件
Threat event ID	35107
Threat handled	Yes
Threat name	Real Protect-EC!F4E5238077C9
Threat severity	Critical
Threat timestamp	2020-7-24 1:10 PM
Threat type	特洛伊木马程序
 
Source
Source access time	2020-7-24 1:09 PM
Source create time	2020-6-19 3:13 AM
Source file path	C:\Windows
Source file size	4484696
Source modify time	2020-6-19 3:13 AM
Source process name	explorer.exe
 
Target
Target hash	f4e5238077c99cd081c43f56bf6e12cb
Target name	Clash for Windows.exe
Target path	C:\Users\XXXXXXX\Documents\Clash.for.Windows

 
Other
Vector type	Local System
Detection message	自适应威胁防护检测
Detection quarantine ID	{2662A65A-B096-47F0-9A78-F88327F6461E}

**Comment by Fndroid** [comment]
未签名被拦截是正常现象

如无法信任，请更换其他软件使用，感谢
