### ISSUE TITLE
能否增加新版本提醒功能？

### ISSUE THREAD

**Issue by free4537** [Fndroid/clash_for_windows_pkg#987]
**描述**
如题，比如启动时自动检查是否有新版本，如有，则提醒。

**其他说明**
无

**Comment by GrayXu** [comment]
一直有，主界面的版本号有红New提醒。

**Comment by free4537** [comment]
> 一直有，主界面的版本号有红New提醒。

两码事，那个不去关注的话，不知道有更新。
