### ISSUE TITLE
请问如何兼顾Profiles更新和自定义规则？

### ISSUE THREAD

**Issue by ffplayer** [Fndroid/clash_for_windows_pkg#988]
#### 背景：
- 用的服务商提供的配置url，这个需要定期更新以获取最新的节点信息。
- 同时自己对节点有自己的配置，比如某些网站用特定的节点、用urltest模式等等
- 但是自己编辑了这份yml之后，再从url更新配置的话，自己的改动就会被覆盖

求问如何能使用自己的配置规则，同时又能保持更新为最新的节点呢？

看了文档似乎mixin是有这功能，但是https://docs.cfw.lbyczf.com/contents/mixin.html 这个链接里面说的并不详细。
那么请问mixin是可以解决我的这个问题么(看例子好像只是更改dns那些的配置)？ 有没有关于cfw中，mixin更具体的用法说明呢？

---

补充：
> mixin设计的目的就是覆盖除了rules/proxy-groups/proxies外的其他内容的

搜了下issues，看到这个 [issue](https://github.com/Fndroid/clash_for_windows_pkg/issues/680) 中的说明，这3点不能覆盖的话，那我想实现的这个就不行了么？ T. T

**Comment by ffplayer** [comment]
退而求其次的话，，proxy-providers 这个功能有没有具体一些的说明啊？

**Comment by pxw139** [comment]
我最后还是自己搭了个订阅API实现的...
不过仔细看完了subconverter的功能后发现用远程配置是可以解决这个问题的
如果能更简单的保留自己的配置就更好了

**Comment by yi-Xu-0100** [comment]
根据当前的[配置文件预处理方法](https://docs.cfw.lbyczf.com/contents/parser.html)以及以前的[作者写过的配置例子](https://github.com/Fndroid/clash_for_windows_pkg/issues/877)，可以对**替换旧关键词**和**自定义规则**(添加，删除或修改规则)有如下便捷修改方式：

在 **`Settings`** 中的 **`Profiles`** 中的 **`Parsers`** 中设置如下:

``` yaml
parsers:
  - url: https://example.com/example.yaml
    code: |
      module.exports.parse = (raw, { yaml }) => {
        const rawObj = yaml.parse(raw)
        const { 'Rule': rules = [], 'Proxy Group':groups = [], 'Proxy': proxies = [] } = rawObj
        delete rawObj['Rule']
        delete rawObj['Proxy Group']
        delete rawObj['Proxy']
        rules.push("DOMAIN-SUFFIX,example.com,Others")
        return yaml.stringify({ ...rawObj, proxies, 'proxy-groups': groups, rules })
      }
```

**注意**：
1. 修改 `url` 为对应的订阅链接。
2. 如果有多个订阅，复制多份，保证 yaml 格式并相应修改对应链接。
3. 如果认为 `code` 内容太多，可以参考教程使用 `file` 参数。
4. 此仅为抛砖引玉，有更多的想法，都可以**结合 js 语法规则**在修改代码，使载入配置的同时对配置进行自定义。

**Comment by yi-Xu-0100** [comment]
根据[配置文件](https://docs.cfw.lbyczf.com/contents/configfile.html)的相关介绍，可以看出，配置文件中的大部分关键词无法替换根目录下的配置信息。

该[配置文件预处理方法](https://docs.cfw.lbyczf.com/contents/parser.html)仅对配置文件内容进行修改，能够生效的应该只有 `rules/proxy-groups/proxies/dns` 这些字段的内容，其中 `dns` 建议使用 [mixin](https://docs.cfw.lbyczf.com/contents/mixin.html) 进行配置。

**Comment by ffplayer** [comment]
> 根据[配置文件](https://docs.cfw.lbyczf.com/contents/configfile.html)的相关介绍，可以看出，配置文件中的大部分关键词无法替换根目录下的配置信息。
> 
> 该[配置文件预处理方法](https://docs.cfw.lbyczf.com/contents/parser.html)仅对配置文件内容进行修改，能够生效的应该只有 `rules/proxy-groups/proxies/dns` 这些字段的内容，其中 `dns` 建议使用 [mixin](https://docs.cfw.lbyczf.com/contents/mixin.html) 进行配置。

非常感谢，我学习一下。

**Comment by ArakiTatsuzou** [comment]
> 根据当前的[配置文件预处理方法](https://docs.cfw.lbyczf.com/contents/parser.html)以及以前的[作者写过的配置例子](https://github.com/Fndroid/clash_for_windows_pkg/issues/877)，可以对**替换旧关键词**和**自定义规则**(添加，删除或修改规则)有如下便捷修改方式：
> 
> 在 **`Settings`** 中的 **`Profiles`** 中的 **`Parsers`** 中设置如下:
> 
> ```yaml
> parsers:
>   - url: https://example.com/example.yaml
>     code: |
>       module.exports.parse = (raw, { yaml }) => {
>         const rawObj = yaml.parse(raw)
>         const { 'Rule': rules = [], 'Proxy Group':groups = [], 'Proxy': proxies = [] } = rawObj
>         delete rawObj['Rule']
>         delete rawObj['Proxy Group']
>         delete rawObj['Proxy']
>         rules.push("DOMAIN-SUFFIX,example.com,Others")
>         rawObj['mode'] = 'Rule'
>         return yaml.stringify({ ...rawObj, proxies, 'proxy-groups': groups, rules })
>       }
> ```
> 
> **注意**：
> 
> 1. 修改 `url` 和为对应的订阅链接。
> 2. 如果有多个订阅，复制多份，保证 yaml 格式并相应修改对应链接。
> 3. 如果认为 `code` 内容太多，可以参考教程使用 `file` 参数。
> 4. 此仅为抛砖引玉，有更多的想法，都可以**结合 js 语法规则**在修改代码，使载入配置的同时对配置进行自定义。
> 5. 虽然能够成功修改配置文件中 `mode` 关键词，但缓存规则并不会被覆盖，V0.11.2 的版本依旧是采用**记住本地操作设置**。

请问这里面的rules.push()方法以及类似的其它方法，我可以在哪里找到文档呢？

**Comment by ArakiTatsuzou** [comment]
> > 根据[配置文件](https://docs.cfw.lbyczf.com/contents/configfile.html)的相关介绍，可以看出，配置文件中的大部分关键词无法替换根目录下的配置信息。
> > 该[配置文件预处理方法](https://docs.cfw.lbyczf.com/contents/parser.html)仅对配置文件内容进行修改，能够生效的应该只有 `rules/proxy-groups/proxies/dns` 这些字段的内容，其中 `dns` 建议使用 [mixin](https://docs.cfw.lbyczf.com/contents/mixin.html) 进行配置。
> 
> 非常感谢，我学习一下。

可以参考下我的

**Comment by ArakiTatsuzou** [comment]
可以参考下我的js，替换指定字符串和在规则头部插入内容

> module.exports.parse = (raw, { yaml }) => {
  while (raw.indexOf('字符串A') != -1) { raw = raw.replace('字符串A', '字符串B') } 
  const rawObj = yaml.parse(raw)
  const { 'rules': rules = [] } = rawObj
  rules.unshift("DOMAIN-KEYWORD, google, 代理", "规则2", "规则3")
  return yaml.stringify({ ...rawObj })
}

**Comment by WrathGluttony** [comment]
> 根据当前的[配置文件预处理方法](https://docs.cfw.lbyczf.com/contents/parser.html)以及以前的[作者写过的配置例子](https://github.com/Fndroid/clash_for_windows_pkg/issues/877)，可以对**替换旧关键词**和**自定义规则**(添加，删除或修改规则)有如下便捷修改方式：
> 
> 在 **`Settings`** 中的 **`Profiles`** 中的 **`Parsers`** 中设置如下:
> 
> ```yaml
> parsers:
>   - url: https://example.com/example.yaml
>     code: |
>       module.exports.parse = (raw, { yaml }) => {
>         const rawObj = yaml.parse(raw)
>         const { 'Rule': rules = [], 'Proxy Group':groups = [], 'Proxy': proxies = [] } = rawObj
>         delete rawObj['Rule']
>         delete rawObj['Proxy Group']
>         delete rawObj['Proxy']
>         rules.push("DOMAIN-SUFFIX,example.com,Others")
>         rawObj['mode'] = 'Rule'
>         return yaml.stringify({ ...rawObj, proxies, 'proxy-groups': groups, rules })
>       }
> ```
> 
> **注意**：
> 
> 1. 修改 `url` 和为对应的订阅链接。
> 2. 如果有多个订阅，复制多份，保证 yaml 格式并相应修改对应链接。
> 3. 如果认为 `code` 内容太多，可以参考教程使用 `file` 参数。
> 4. 此仅为抛砖引玉，有更多的想法，都可以**结合 js 语法规则**在修改代码，使载入配置的同时对配置进行自定义。
> 5. 虽然能够成功修改配置文件中 `mode` 关键词，但缓存规则并不会被覆盖，V0.11.2 的版本依旧是采用**记住本地操作设置**。

您好，我用的是clash for windows 0.12.0安装版，我想一直是Rule，但是重启电脑后，Proxy Mode偶尔会变为Global，请问我如何用“配置文件预处理”这个方法？在Settings-Profiles-Parsers里，代码如何写？打搅了，谢谢

**Comment by yi-Xu-0100** [comment]
@WrathGluttony `Proxy Mode` 没有配置策略，因为软件的设置是 **记住本地上次的设置操作** ，所以无需个人配置。

个人给出可能的修复方式为：修改 `General/General YAML` 中的 `mode` 字段为 `Rule`。(`windows` 下该文件默认位于 `C:\Users\用户名\.config\clash\config.yaml`，该文件是总的配置文件)。

如果你仍然存在问题，建议提交新的 `issue`， 最好能够给出可能导致的原因或者复现手段，以等待别人给出更好的解决办法。

**Comment by WrathGluttony** [comment]
谢谢大牛的不吝赐教，非常感激

**Comment by DISVGOD** [comment]
> 根据当前的[配置文件预处理方法](https://docs.cfw.lbyczf.com/contents/parser.html)以及以前的[作者写过的配置例子](https://github.com/Fndroid/clash_for_windows_pkg/issues/877)，可以对**替换旧关键词**和**自定义规则**(添加，删除或修改规则)有如下便捷修改方式：
> 
> 在 **`Settings`** 中的 **`Profiles`** 中的 **`Parsers`** 中设置如下:
> 
> ```yaml
> parsers:
>   - url: https://example.com/example.yaml
>     code: |
>       module.exports.parse = (raw, { yaml }) => {
>         const rawObj = yaml.parse(raw)
>         const { 'Rule': rules = [], 'Proxy Group':groups = [], 'Proxy': proxies = [] } = rawObj
>         delete rawObj['Rule']
>         delete rawObj['Proxy Group']
>         delete rawObj['Proxy']
>         rules.push("DOMAIN-SUFFIX,example.com,Others")
>         rawObj['mode'] = 'Rule'
>         return yaml.stringify({ ...rawObj, proxies, 'proxy-groups': groups, rules })
>       }
> ```
> 
> **注意**：
> 
> 1. 修改 `url` 和为对应的订阅链接。
> 2. 如果有多个订阅，复制多份，保证 yaml 格式并相应修改对应链接。
> 3. 如果认为 `code` 内容太多，可以参考教程使用 `file` 参数。
> 4. 此仅为抛砖引玉，有更多的想法，都可以**结合 js 语法规则**在修改代码，使载入配置的同时对配置进行自定义。
> 5. 虽然能够成功修改配置文件中 `mode` 关键词，但缓存规则并不会被覆盖，V0.11.2 的版本依旧是采用**记住本地操作设置**。

我用的配置文件是ssr订阅用sub转clash,用预处理的方法无法更新配置文件，表示下载配置文件失败，这种情况该怎么解决

**Comment by yi-Xu-0100** [comment]
@DISVGOD 建议新开 issue 并贴出报错截图和 parser 内容。主要屏蔽敏感内容。

**Comment by DISVGOD** [comment]
> @DISVGOD 建议新开 issue 并贴出报错截图和 parser 内容。主要屏蔽敏感内容。

![image](https://user-images.githubusercontent.com/59304605/129706445-c77fc5fd-6d5a-4e29-8efe-7b50d41ca81b.png)
![image](https://user-images.githubusercontent.com/59304605/129706755-168a76ad-49ab-4d5b-9678-cec33fbf325d.png)

**Comment by DISVGOD** [comment]
> @DISVGOD 建议新开 issue 并贴出报错截图和 parser 内容。主要屏蔽敏感内容。

好的，谢谢

**Comment by usedlife** [comment]
> 根据当前的[配置文件预处理方法](https://docs.cfw.lbyczf.com/contents/parser.html)以及以前的[作者写过的配置例子](https://github.com/Fndroid/clash_for_windows_pkg/issues/877)，可以对**替换旧关键词**和**自定义规则**(添加，删除或修改规则)有如下便捷修改方式：
> 
> 在 **`Settings`** 中的 **`Profiles`** 中的 **`Parsers`** 中设置如下:
> 
> ```yaml
> parsers:
>   - url: https://example.com/example.yaml
>     code: |
>       module.exports.parse = (raw, { yaml }) => {
>         const rawObj = yaml.parse(raw)
>         const { 'Rule': rules = [], 'Proxy Group':groups = [], 'Proxy': proxies = [] } = rawObj
>         delete rawObj['Rule']
>         delete rawObj['Proxy Group']
>         delete rawObj['Proxy']
>         rules.push("DOMAIN-SUFFIX,example.com,Others")
>         rawObj['mode'] = 'Rule'
>         return yaml.stringify({ ...rawObj, proxies, 'proxy-groups': groups, rules })
>       }
> ```
> 
> **注意**：
> 
> 1. 修改 `url` 和为对应的订阅链接。
> 2. 如果有多个订阅，复制多份，保证 yaml 格式并相应修改对应链接。
> 3. 如果认为 `code` 内容太多，可以参考教程使用 `file` 参数。
> 4. 此仅为抛砖引玉，有更多的想法，都可以**结合 js 语法规则**在修改代码，使载入配置的同时对配置进行自定义。
> 5. 虽然能够成功修改配置文件中 `mode` 关键词，但缓存规则并不会被覆盖，V0.11.2 的版本依旧是采用**记住本地操作设置**。

改 rules 只写这一段就行了：
```
parsers:
  - url: 第三方配置的url
    code: |
      module.exports.parse = (raw, { yaml }) => {
        const { rules, ...rest } = yaml.parse(raw)
        # 自定义 rules，覆盖第三方的配置
        rules.push("DOMAIN-SUFFIX,example.com,Others")
        return yaml.stringify({ ...rest, rules })
      }
```

**Comment by usedlife** [comment]
> 根据当前的[配置文件预处理方法](https://docs.cfw.lbyczf.com/contents/parser.html)以及以前的[作者写过的配置例子](https://github.com/Fndroid/clash_for_windows_pkg/issues/877)，可以对**替换旧关键词**和**自定义规则**(添加，删除或修改规则)有如下便捷修改方式：
> 
> 在 **`Settings`** 中的 **`Profiles`** 中的 **`Parsers`** 中设置如下:
> 
> ```yaml
> parsers:
>   - url: https://example.com/example.yaml
>     code: |
>       module.exports.parse = (raw, { yaml }) => {
>         const rawObj = yaml.parse(raw)
>         const { 'Rule': rules = [], 'Proxy Group':groups = [], 'Proxy': proxies = [] } = rawObj
>         delete rawObj['Rule']
>         delete rawObj['Proxy Group']
>         delete rawObj['Proxy']
>         rules.push("DOMAIN-SUFFIX,example.com,Others")
>         rawObj['mode'] = 'Rule'
>         return yaml.stringify({ ...rawObj, proxies, 'proxy-groups': groups, rules })
>       }
> ```
> 
> **注意**：
> 
> 1. 修改 `url` 和为对应的订阅链接。
> 2. 如果有多个订阅，复制多份，保证 yaml 格式并相应修改对应链接。
> 3. 如果认为 `code` 内容太多，可以参考教程使用 `file` 参数。
> 4. 此仅为抛砖引玉，有更多的想法，都可以**结合 js 语法规则**在修改代码，使载入配置的同时对配置进行自定义。
> 5. 虽然能够成功修改配置文件中 `mode` 关键词，但缓存规则并不会被覆盖，V0.11.2 的版本依旧是采用**记住本地操作设置**。

上面代码主要是重命名 yml 中的 key，若自定义 rule 改几行就行，如下：
```
parsers:
  - url: 第三方配置的url e.g.  https://a.config.dev?xx=xx
    code: |
      module.exports.parse = (raw, { yaml }) => {
        const { rules = [], ...rest } = yaml.parse(raw) || {}
        
        # 添加自定义的 rules
        rules.push("DOMAIN-SUFFIX,steamcontent.com,DIRECT")
        
        # 如果 rules.push 不生效，尝试使用 rules.unshift
        # 我的第三方配置会在结尾放个 - MATCH, 代理
        # 比如：
        rules.unshift("DOMAIN-SUFFIX,steamcontent.com,DIRECT")
        # ...
         
        return yaml.stringify({ ...rest, rules })
      }
```
