### ISSUE TITLE
电脑版line正确设置后无法发送或接受图片

### ISSUE THREAD

**Issue by shujunxiong** [Fndroid/clash_for_windows_pkg#989]
**信息**
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载

**系统**

1909版本，软件0.11.2

**描述**

正确连接clash，可以上网，在line中设置了代理服务器，正确设置端口，使用socks5和http都测试过，只能够接受发送文字，图片、文件等均无法发送或接受，tg，discord等其他聊天软件正常，在line高级设置中测试代理服务器也正常，检查配置文件，https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/Line.list 此网址中规则在配置文件中均存在，使用netch测试line功能正常。

**预期行为**

希望line可以快速的发送图片

**截图**

![图片](https://user-images.githubusercontent.com/53935557/88452253-ca6ce200-ce8f-11ea-8137-f47b1fe70490.png)

**其他说明**

使用https://github.com/BoyceLig/Clash_Chinese_Patch 了此汉化包

**Comment by Fndroid** [comment]
只要改了任何一个文件，都请不要在本仓库发issue，感谢

**Comment by shujunxiong** [comment]
刚刚开始使用，不太了解，抱歉打扰了，感谢大佬做的贡献。
