### ISSUE TITLE
[BUG] 反复报错

### ISSUE THREAD

**Issue by VoVAllen** [Fndroid/clash_for_windows_pkg#99]
**Describe the bug**
![image](https://user-images.githubusercontent.com/8686776/55335851-7423a500-54ce-11e9-829d-f3d3e65aa1b5.png)

**To Reproduce**
用的是dlercloud的默认配置，之前都好。尝试添加自制的yml后开始报错，删了之后依旧报错

**Expected behavior**

**Screenshots**

**Error Logs (located in HomeDirectory)**
```
// paste below this line
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows10]

**Additional context**

**Comment by Fndroid** [comment]
0.5.31版本更新Clash核心，load-balance策略组需要添加url和interval字段
