### ISSUE TITLE
希望添加更新订阅时，节点筛选以及节点排除的功能

### ISSUE THREAD

**Issue by zhouzl7** [Fndroid/clash_for_windows_pkg#991]
**描述**
希望添加更新订阅时，节点筛选以及节点排除的功能。比如更新订阅时，排除所有ssr协议的节点，或者只保留ssr协议的节点。

**其他说明**
其他补充内容

**Comment by jackking01** [comment]
请问一下怎么下载到mac

**Comment by yi-Xu-0100** [comment]
> 请问一下怎么下载到mac

这个软件是 windows 平台的，请去找找 mac 平台的 clash 图形化软件。

**Comment by yi-Xu-0100** [comment]
CFW 支持[配置文件预处理方法](https://docs.cfw.lbyczf.com/contents/parser.html)，在 #988 我给出部分可行的自定义方式，可以结合 js 语法规则，实现个人对配置文件的相关处理。

**Comment by abae136ab** [comment]
> > 请问一下怎么下载到mac
> 
> 这个软件是 windows 平台的，请去找找 mac 平台的 clash 图形化软件。

都支持Mac好久了。。。

**Comment by yi-Xu-0100** [comment]
> > > 请问一下怎么下载到mac
> > 
> > 
> > 这个软件是 windows 平台的，请去找找 mac 平台的 clash 图形化软件。
> 
> 都支持Mac好久了。。。

这里不是clash for windows 吗？这个软件应该不支持 mac 吧。
