### ISSUE TITLE
关于Profile编写格式 (About "Profile" format)

### ISSUE THREAD

**Issue by XuCpeng** [Fndroid/clash_for_windows_pkg#993]
请教一下，Profile编写格式的更改，是来自Clash上游，还是只限于Clash for Windows？ 有无官方文档，我现在Clash用不了，不方便查。

对开发者一直以来的努力表示感谢。不知后续版本中是否有计划处理与“旧格式”不兼容的情况（例如切换选项或自动替换），如果没有我先写个脚本用着，若有就等大佬更新。

**Comment by XuCpeng** [comment]
服务商那边我也会提一下工单，但不能把希望寄托在服务商更新Profile源，因为其用户还有不少都在用老版Clash。

**Comment by XuCpeng** [comment]
我认为，在一个软件的正常开发周期中，这种会影响可用性的改动，应该留有缓冲时间。比如Chrome取消flash支持的过程

**Comment by XuCpeng** [comment]
### English version to show respect：

I would like to ask, does the change of the profile format come from the upstream of Clash, or is it limited to Clash for Windows?
Is there any official document? I can’t use Clash now, so it’s not convenient to check.

Thank the developers for their continuous efforts.

I don’t know if there are plans to deal with incompatibility with the "old format" in subsequent versions (such as switching options or automatic replacement). If not, I will write a script to use it first, and if there is, I will wait for the big guy to update it.

I will also mention the work order from the service provider, but I cannot pin my hope on the service provider to update the profile source, because many of its users are using the old version of Clash.

In my opinion, in the normal development cycle of a software, there should be a buffer time for such changes that will affect usability. For example, chrome cancels Flash support

**Comment by Fndroid** [comment]
不升级用旧版就好了。

建议提前更换字段适配也不是一天两天的事情了。

**Comment by XuCpeng** [comment]
> 不升级用旧版就好了。有多少人用旧版，并不是我关心的事。
> 
> 建议提前更换字段适配也不是一天两天的事情了。

好的，谢谢。看来是Clash改了，今天也注意到Android版的提醒了，不过还好还能用。
![image](https://user-images.githubusercontent.com/19551139/88530275-b8c43f80-d033-11ea-9a36-f84e1e1a8fe6.png)
