### ISSUE TITLE
could not connect to clash core

### ISSUE THREAD

**Issue by joker-kingdom** [Fndroid/clash_for_windows_pkg#994]
日志：
time="2020-07-28T10:03:50+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-07-28T10:03:50+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2020-07-28T10:03:50+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
已经使用过改端口，重置网络，等手段，均无法生效

**Comment by Quzard** [comment]
先查看Windows动态端口范围   
.\netsh int ipv4 show dynamicport tcp
如果7890，9090在该范围内，改Windows动态端口范围可解决
.\netsh int ipv4 set dynamicport tcp start=49152 num=16384

**Comment by seefs001** [comment]
怕不是和我一样更新了Win10 20H2

**Comment by joker-kingdom** [comment]
> 怕不是和我一样更新了Win10 20H2
感谢回复，找到原因了，是因为开了防火墙，，，

**Comment by joker-kingdom** [comment]
> 先查看Windows动态端口范围
> .\netsh int ipv4 show dynamicport tcp
> 如果7890，9090在该范围内，改Windows动态端口范围可解决
> .\netsh int ipv4 set dynamicport tcp start=49152 num=16384

感谢回复，找到原因了，是因为开了防火墙，，，

**Comment by chengqot** [comment]
重启网卡就行了
```powershell
Get-NetAdapter
Restart-NetAdapter
```
