### ISSUE TITLE
开启这个之后企业微信图片收发受到影响

### ISSUE THREAD

**Issue by syymo** [Fndroid/clash_for_windows_pkg#995]
开启这个之后企业微信图片收发受到影响

**Comment by iiivii** [comment]
受什么影响，是图片加载缓慢还是直接加载失败，可以看下是不是配置文件里走代理了还是相关域名被ban了。

**Comment by syymo** [comment]
> 受什么影响，是图片加载缓慢还是直接加载失败，可以看下是不是配置文件里走代理了还是相关域名被ban了。

发送不出去图片，收不到图片，红色感叹号~
配置中关于qq 微信的都是DIRECT

**Comment by iiivii** [comment]
> > 受什么影响，是图片加载缓慢还是直接加载失败，可以看下是不是配置文件里走代理了还是相关域名被ban了。
> 
> 发送不出去图片，收不到图片，红色感叹号~
> 配置中关于qq 微信的都是DIRECT

你发图或者接收图片的时候看下Logs或者Connection，看看有没有哪个域名是被Reject的。

**Comment by Love4Taylor** [comment]
看起来是企业微信的锅，在企业微信里手动填一次代理就可以正常用了。

**Comment by tsddts** [comment]
> 看起来是企业微信的锅，在企业微信里手动填一次代理就可以正常用了。

遇到了同样的问题，请问手动填写代理怎么填？或者clash上面是否有设置可以跳过某个指定的应用程序

**Comment by formgithub** [comment]
closed。但是没解决

**Comment by ln90s** [comment]
找到折中的方案了, 关闭clash的system proxy , 然后在需要使用代理的地方指定使用http的127.0.0.1:7890
例如chrome中使用插件[SwitchyOmega]
@formgithub @tsddts @syymo @iiivii
