### ISSUE TITLE
clash 0.11 无法使用

### ISSUE THREAD

**Issue by CaoXiufengwhut** [Fndroid/clash_for_windows_pkg#996]
clash 0.11 无法使用了 在profile中的xml文件更新了也不行

求使用0.11的教程

**Comment by iiivii** [comment]
这个无法使用具体是什么问题，提示或者Logs是什么，不描述清楚也没办法解决啊。

**Comment by CaoXiufengwhut** [comment]
已经解决了 需要使用Subscription Converter 生成新的订阅链接 以前的链接不能直接在0.11以上的版本里面使用了
