### ISSUE TITLE
程序正在进行远程线程注入

### ISSUE THREAD

**Issue by hzmming** [Fndroid/clash_for_windows_pkg#997]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

**描述**
这个是什么情况？？
![image](https://user-images.githubusercontent.com/15829377/88686763-ff946100-d129-11ea-9b6c-3bec15a1e12a.png)

[//]: # (请具体并清楚地描述遇到的问题)

**复现**
到了晚上经常会自己出现，我也不知道怎么复现
**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by ljh0519** [comment]
关闭360，解决一切烦恼
