### ISSUE TITLE
Clash经常所有节点全部同时失联

### ISSUE THREAD

**Issue by bin28281010** [Fndroid/clash_for_windows_pkg#998]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Windows10

[//]: # (平台及版本号)
1909

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
经常使用过程中突然失去连接，频率不好界定，有时候一个小时就有一两次，有时候半天一两次。进入clash测试进行延迟测试，所有节点Timeout无法使用。同时测试手机上小火箭上的节点（同样配置节点），都可以正常使用。
如果等待其自行恢复，恢复时间不可预期。但是如果失联后手机上使用该节点浏览网页，好像可以立即触发电脑断恢复连接。多次尝试好像都可以。

**复现**

[//]: # (请描述复现问题的步骤)

1. 日常浏览网页
2. 一段时间所有节点崩溃

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)
暂时未捕获，等再发生时候再上传

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/37745896/88694285-e93ed300-d132-11ea-9ae2-a81fb5cc85d1.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by pqq1112** [comment]
我这边windows也经常出现这种情况，同样的节点在macbook上就正常

**Comment by Alienswj** [comment]
遇到同样的问题 windows10 2004

**Comment by CHENGY12** [comment]
同样的问题， 所有的节点都不能用了，已经一天了都没有恢复

**Comment by Alienswj** [comment]
> 同样的问题， 所有的节点都不能用了，已经一天了都没有恢复

是线路提供方的问题，不是软件的问题。我之前也是全断，后来查询我的机场（ctcloud）时候发现他转让给了另一家（似乎叫windycloud），换了新的订阅链接就ok了

**Comment by CHENGY12** [comment]
非常感谢， 请问要怎么换新的订阅链接呢

**Comment by yi-Xu-0100** [comment]
??? 更新订阅链接的话，去机场官网看看呗，重置或者看看有没有啥公告

**Comment by CHENGY12** [comment]
机场官网登不上了~~ 可能是出问题了

**Comment by yi-Xu-0100** [comment]
(*Φ皿Φ*)，怕不是跑路了~

**Comment by CHENGY12** [comment]
貌似确实是机场出问题了~~  感谢大家的回答

**Comment by Return-s** [comment]
关掉内置dns试试

**Comment by Freemenwong** [comment]
我这边是windows 11的手提电脑经常超时，而PC端的window 10和Macbook用同样版本的clash以及同样的节点却从来没有掉线过

**Comment by Garbage123King** [comment]
我之前windows能用，linux全Timeout，把clash从0.17换成0.20就好了。
