### ISSUE TITLE
很好奇为啥不考虑中文？

### ISSUE THREAD

**Issue by steeltalons1996** [Fndroid/clash_for_windows_pkg#999]
虽然英文也能用，现在也习惯了，不加也能接受

这样做为了提升使用门槛防树大招风么?

**Comment by Fndroid** [comment]
没什么为什么，就是觉得没必要

**Comment by akw5454521** [comment]
一共就没多少单词，而且很多都是专有名词——就算汉化了也不翻译那种

**Comment by kouhe3** [comment]
为什么不添加中文？你这个软件是要给中国人用还是外国人用？
我觉得主要是给中国人用，那么为什么不支持中文？

**Comment by Fndroid** [comment]
@kouhe3 你觉得是你觉得，我不想是我不想，也不冲突

**Comment by leizhnxp** [comment]
> 为什么不添加中文？你这个软件是要给中国人用还是外国人用？
> 我觉得主要是给中国人用，那么为什么不支持中文？

您用这玩意儿，主要也就是为了和国际接轨吧🤣作者良苦用心的说，做着新东方一样的事业，竟然还不收钱

**Comment by akw5454521** [comment]
> 为什么不添加中文？你这个软件是要给中国人用还是外国人用？
> 我觉得主要是给中国人用，那么为什么不支持中文？

你要是这么说，那这软件还真不是给中国人用的。知道什么是非法信道吗？你在打算用这软件之前，最好看看你的信道是否合法，建议询问下当地公安机关，看看警察叔叔让不让你用

**Comment by kouhe3** [comment]
一款主要是中国人用的软件，却不支持中文。
拜托，不要像surge那样 [傲娇](https://github.com/KeiKinn/ShadowsocksBio/blame/e4151c3a3d3d2a7f523ae3d37b2389f23dcf045d/readme.md#L252) 啊喂
